### ISSUE TITLE
Script for telegram notification

### ISSUE THREAD

**Issue by psztoch** [Icinga/icinga2#10063]
## Describe the solution you'd like

Ready for use script `/etc/icinga2/scripts/telegram-host-notification.sh` and 
`/etc/icinga2/scripts/telegram-service-notification.sh`.

Updated `/etc/icinga2/conf.d/commands.conf`.

## Is your feature request related to a problem? Please describe.

I believe that Telegram is so popular that it is worth including this script in the official distribution along with "object NotificationCommand".

**Comment by moreamazingnick** [comment]
Telegram is indeed very nice but here are some things to consider

* messages by bots do not include end-to-end encryption
* you are trusting a third party with no Data Processing Agreement with you alert data.
* If you are not paying for it you are the product, not the customer

**Comment by oxzi** [comment]
I would second @moreamazingnick's opinion. Personally I would not use Telegram for sensitive information, or anything at all.

Furthermore, there are already lots of [notification plugins](https://exchange.icinga.com/search?q=telegram) out there. Please use some of those scripts, as adding this additional maintenance to the main Icinga 2 repository should not be worth the effort.

**Comment by abielan** [comment]
A plugin for several of the most popular messengers should be in the main repo and standard package.
The lack of a plugin for Telegram is a problem that is definitely worth solving.
Icinga has great monitoring but poor reporting and average notifications.
