### ISSUE TITLE
[Documentation] Installation documentation for current/new versions of Amazon Linux

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icinga2#10067]
## Describe the bug
Amazon seems to release a new version of their distrubtion every two years [link](https://docs.aws.amazon.com/linux/al2023/ug/release-cadence.html) and this is currently not present in the icinga.com documentation (for AL 2023) or at least not in a very detailed way.

**Comment by Al2Klimov** [comment]
And Fedora releases twice a year – not documented either IIRC. 🤷‍♂️

**Comment by yhabteab** [comment]
> nd this is currently not present in the icinga.com documentation (for AL 2023) or at least not in a very detailed way.

It would be more helpful if you could describe exactly what you are missing or what is not working for you as documented. As far as I can see, there is a detailed [installation docs](https://icinga.com/docs/icinga-2/latest/doc/02-installation/09-Amazon-Linux/) for all supported AL versions with special notes for **AL 2**, like any other installation docs for other distros.

**Comment by RincewindsHat** [comment]
Sorry, my initial description was lacking a lot of details. A problem specifically is the [missing support of EPEL on AL2023](https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#epel) which means no `monitoring-plugins` or `nagios-plugins` package.
While installing Icinga2 is not really a problem, having no Monitoring Plugins makes this kinda useless.

I am not sure though, how this could/should be properly fixed, apart from shipping `monitoring-plugins` (or even `nagios-plugins`) from the icinga.com repositories (which may cause a lot of headache).

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icinga2/blob/d662ca0adadff287d6912b547b8c6f4d97a95043/doc/02-installation.md?plain=1#L433

* https://github.com/amazonlinux/amazon-linux-2023/issues/367

🤷‍♂️

**Comment by RincewindsHat** [comment]
@Al2Klimov  thanks, didn't see that yet. At least I can then point to that issue.

I have some suggestion though: Although it is my fault for not reading the complete paragraph, adding such a note as the very last thing is maybe not the most obvious choice.
