### ISSUE TITLE
IcingaDB: add support Redis connection via Unix sockets

### ISSUE THREAD

**Issue by sbraz** [Icinga/icinga2#10097]
## Is your feature request related to a problem? Please describe.
Hello,
As far as I know, all other Icinga-related projects allow connecting to databases via Unix sockets, it doesn't seem to be the case for IcingaDB.
```
[2024-07-06 00:54:06 +0200] information/IcingaDB: Trying to connect to Redis server (async) on host '/run/redis/redis.sock:6380'
[2024-07-06 00:54:06 +0200] critical/IcingaDB: Cannot connect to /run/redis/redis.sock:6380: Host not found (authoritative) [asio.netdb:1]
```

## Describe the solution you'd like

I would like to be able to specify the following:
```
object IcingaDB "icingadb" {
  host = "/run/redis/redis.sock"
}
```

## Describe alternatives you've considered

At the moment, I have to use a TCP connection to localhost to connect to my Redis instance.

## Additional context

From what I see, there is no Unix socket support here https://github.com/Icinga/icinga2/blob/bca1a8447af26313123183efa863f947f9590731/lib/icingadb/redisconnection.cpp#L316

**Comment by yhabteab** [comment]
Hi, thanks for reporting! That's already supported and [documented](https://icinga.com/docs/icinga-2/latest/doc/09-object-types/#icingadb)! You have to use `path` instead if you want to use Unix sockets.
