### ISSUE TITLE
mass-migration of api-objects

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga2#10249]
## Describe the bug

I need to migrate a few thousend hosts and services. These objects were created with api-calls. Our zones have changed and I am in need to move those objects into a new zone. 

When I change the zone-attribute of a host and its services in `/var/lib/icinga2/api/packages/_api/<individual_name>/conf.d/services and /hosts` on the configmaster, the checks for those objects are executed manualy without problems afterwards, but the automatic scheduling seems broken, because the checks are pending now. Manual scheduling works to fix this temporary, but in the next cycle there's no automatic scheduling again.

after zone-attribute modification:
![image](https://github.com/user-attachments/assets/f74374e4-7e48-4e73-b99a-998436312dd6)

after manual execution:
![image](https://github.com/user-attachments/assets/018c0a44-f867-4f11-b325-87ce446531d7)

next automatic cycle:
![image](https://github.com/user-attachments/assets/6afc07e6-6f66-4cc1-9ffb-ed40fd46402b)

When I move the zone-attribute back to its original value, scheduling of those checks is working again.

## Question

Is there a convenient way to mass-migrate api-objects into another zone? Just the zone-attribute needs to change.
I have no automatic way to perform this.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.13.10
* Operating System and version: RHEL8
* Enabled features (`icinga2 feature list`): 
```
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb2 livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker icingadb influxdb mainlog notification
```
* Icinga Web 2 version and modules (System - About): 2.12.1

**Comment by K0nne** [comment]
I have tested your suggestion (changed the zones-attribute of a host and its services to the new zone, increased the version-attibute of those objects by 1, reloaded the configmaster and all affected satellites), but unfortunately it did not change anything.

**Comment by Al2Klimov** [comment]
Is deletion and re-creation not an option because of existing history and downtimes? Even then, at least you could(?) re-create everything which is OK at the moment.

**Comment by K0nne** [comment]
That sounds like a plan. Thanks for your input.
