### ISSUE TITLE
[dev.icinga.com #6196] Update icinga2 node wizard so it can be used to set up HA clusters

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#1543]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6196

**Created by gbeutner on 2014-05-12 14:04:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-07-24 18:19:02 +00:00 (in Redmine)_

---

Scenarios:

a) New agent with upstream zone which has multiple nodes
b) New cluster node in an existing zone

---

**Relations**:

* relates [#8213](https://dev.icinga.com/issues/8213)

**Comment by dnsmichi** [comment]
Please use the method described in the documentation.

https://www.icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#high-availability-master-with-clients
