### ISSUE TITLE
[dev.icinga.com #6209] Config error: Error while evaluating expression: Object 'icinga2a' of type 'Host' re-defined

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#1550]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6209

**Created by mfriedrich on 2014-05-14 14:46:48 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2014-05-14 15:49:37 +00:00_)
Target Version: _0.0.11_
Last Update: _2014-05-14 15:49:37 +00:00 (in Redmine)_

    Icinga Version: 0.0.10

---

    [2014-05-14 14:42:16 +0000]  critical/config: Location:
    /etc/icinga2/zones.d/checker/health.conf(1): object Host "icinga2b" {
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
    /etc/icinga2/zones.d/checker/health.conf(2):   display_name = "Health Checks on icinga2b"
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /etc/icinga2/zones.d/checker/health.conf(3): 

    /etc/icinga2/zones.d/checker/health.conf(4):   address = "192.168.33.20"
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /etc/icinga2/zones.d/checker/health.conf(5):   check_command = "dummy"
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
    /etc/icinga2/zones.d/checker/health.conf(6): }
                                                 ^
    /etc/icinga2/zones.d/checker/health.conf(7): 
    /etc/icinga2/zones.d/checker/health.conf(8): apply Service "cluster" {

    Config error: Error while evaluating expression: Object 'icinga2b' of type 'Host' re-defined: in /etc/icinga2/zones.d/checker/health.conf: 1:0-6:1; previous definition: in ./zones.d/checker/health.conf: 1:0-6:1
    [2014-05-14 14:42:16 +0000]  critical/config: Location:
    /etc/icinga2/zones.d/master/health.conf(1): /* cluster health checks */
    /etc/icinga2/zones.d/master/health.conf(2): 
    /etc/icinga2/zones.d/master/health.conf(3): object Host "icinga2a" {
                                                ^^^^^^^^^^^^^^^^^^^^^^^^
    /etc/icinga2/zones.d/master/health.conf(4):   display_name = "Health Checks on icinga2a"
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /etc/icinga2/zones.d/master/health.conf(5): 

    /etc/icinga2/zones.d/master/health.conf(6):   address = "192.168.33.10"
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /etc/icinga2/zones.d/master/health.conf(7):   check_command = "dummy"
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
    /etc/icinga2/zones.d/master/health.conf(8): }
                                                ^
    /etc/icinga2/zones.d/master/health.conf(9): 
    /etc/icinga2/zones.d/master/health.conf(10): apply Service "cluster" {

    Config error: Error while evaluating expression: Object 'icinga2a' of type 'Host' re-defined: in /etc/icinga2/zones.d/master/health.conf: 3:1-8:1; previous definition: in ./zones.d/master/health.conf: 3:1-8:1

**Comment by devarti** [comment]
So what is the solution if we use master + satellite mode to sync the configs? it seems like /var/lib/icinga2/api... broken when adding nodes manually and running icinga2 daemon -C and then restart. The only solution right now is to delete folders from api and then restart.

Thanks
Devarshi

**Comment by dnsmichi** [comment]
Please don't bump old issues. Join the community channels with your questions.

Regards,
Michael
