### ISSUE TITLE
[dev.icinga.com #6901] add a section for 'monitoring the icinga2 node'

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#1880]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6901

**Created by mfriedrich on 2014-08-13 09:23:24 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-12-08 00:48:57 +00:00_)
Target Version: _(none)_
Last Update: _2016-12-08 00:48:57 +00:00 (in Redmine)_

---

Similar to https://wiki.icinga.org/display/howtos/Monitoring+the+Icinga+Host but extended with icinga and cluster health checks.

**Comment by dnsmichi** [comment]
Changed my mind when I needed to do a performance analysis in a customer environment. Will be added as part of #5137.
