### ISSUE TITLE
[dev.icinga.com #7071] Re-design passive checks and freshness

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#1951]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7071

**Created by mfriedrich on 2014-09-03 19:18:34 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-09 14:59:57 +00:00 (in Redmine)_

---

=&gt; Monitoring Basics

    21:05:45 < CrossWire> question: i am trying to deploy a passive check wherewith the client uses nsca to submit results. It works fine ... stats get updated as 
                          expected. However when the hosts stop sending 'updates' icinga2 still happily thinks all is fine (with a last check 30 minutes ago) ... in 
                          the service i disabled active checks and enabled passive checks (like i did with nagios). Did i miss an option for him to notice its not 
                          getting any updates?
    21:11:14 < shroud> CrossWire: icinga2 reschedules checks when it receives passive check results, so all you have to do is to enable active checks, set the check 
                       interval to a somewhat larger interval and decrease the retry interval
    21:12:01 < shroud> for example, assuming nsca sends check results every 5 minutes and you want notifications after about 10 minutes if you don't get any 
                       results: check_interval = 10m, retry_interval = 10s
    21:12:10 < CrossWire> so active checks should be enabled
    21:12:13 < shroud> yes
    21:14:46 < shroud> something like this should work:
    21:14:50 < shroud> object Service "nsca-svc" {
    21:14:50 < shroud>   import "generic-service"
    21:14:50 < shroud>   check_command = "passive"
    21:14:50 < shroud>   check_interval = 10m
    21:14:50 < shroud>   max_check_attempts = 1
    21:14:52 < shroud> }
    21:15:22 < shroud> http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/configuring-icinga2#plugin-check-command-passive

---

**Relations**:

* relates [#7071](https://dev.icinga.com/issues/7071)

**Comment by htriem** [comment]
@lippserd Is this still relevant?

**Comment by lippserd** [comment]
> @lippserd Is this still relevant?

@htriem I think we can close this one.
