### ISSUE TITLE
[dev.icinga.com #2834] Downtimes: dynamic global / dmz-based downtime for maintenance

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#209]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/2834

**Created by mfriedrich on 2012-07-12 19:15:04 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2014-11-24 15:04:19 +00:00_)
Target Version: _(none)_
Last Update: _2014-11-24 15:04:19 +00:00 (in Redmine)_

---

this is a feature request like [\#1261](https://dev.icinga.com/issues/1261) and eases known network maintenance either globally, or within the defined dmz.

**Comment by danielbotting-mcr** [comment]
Hi, 

Is this possible now, as originally stated it would be particularly useful when doing maintenance on a large estate. I appreciate that you can hold down shift and keep selecting, however with a large number of hosts this still takes a while.

Many thanks
