### ISSUE TITLE
[dev.icinga.com #7441] Add support for node setup/wizard without auto-signing certificates

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2101]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7441

**Created by mfriedrich on 2014-10-24 10:18:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2014-11-14 10:14:43 +00:00 (in Redmine)_

---

Required if the master cannot be reached for some reason. Affects the cli node setup/wizard commands and the windows installer.

-   Generate CSR and print to stdout/screen
-   User must manually sign the CSR and copy cert file to a defined location
-   setup parameter / windows file location popup for the cert file location (--cert)
-   setup command will copy the signed cert to its final destination
-   proceed with installation

---

**Relations**:

* relates [#7248](https://dev.icinga.com/issues/7248)
* relates [#7527](https://dev.icinga.com/issues/7527)

**Comment by dnsmichi** [comment]
Imho this should be considered when allowing asymetric certificate signing in #3847. Closing this is partial duplicate.
