### ISSUE TITLE
[dev.icinga.com #7456] Call x::exceptions for all fstreams

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2110]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7456

**Created by gbeutner on 2014-10-27 13:39:48 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-25 00:34:59 +00:00 (in Redmine)_

---

---

**Relations**:

* relates [#6070](https://dev.icinga.com/issues/6070)
* relates [#10948](https://dev.icinga.com/issues/10948)
* relates [#7456](https://dev.icinga.com/issues/7456)
* duplicates [#7456](https://dev.icinga.com/issues/7456)

**Comment by dnsmichi** [comment]
Won't happen anytime soon.

**Comment by dnsmichi** [comment]
Closing in favor of #7159.
