### ISSUE TITLE
[dev.icinga.com #7632] Please allow one to disable "repository"

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2226]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7632

**Created by tgelf on 2014-11-11 10:15:17 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2015-01-12 10:24:00 +00:00_)
Target Version: _(none)_
Last Update: _2017-01-14 13:05:53 +00:00 (in Redmine)_

    Icinga Version: 2.4.1

---

IMO "repository" should be a feature one could disable on demand. Reasons:

-   While it is a nice feature I currently have no use case for it
-   It pollutes my config directory and therefore conflicts with Puppet Modules "purging" config directories
-   It wastes resources. Didn't measure the impact on large environments, but given the current update frequency it's probably more than "nothing"

I'd really love to use live repository data via the API for a config tool or similar, but I have no need for those files and I will probably never have. Same goes for the related CLI commands. They are very nice, I like them. However, people not using them should still be able to get a cleaner system.

Best,
Thomas

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Relations**:

* relates [#7632](https://dev.icinga.com/issues/7632)

**Comment by dnsmichi** [comment]
#4799

**Comment by dnsmichi** [comment]
Will be removed with the referenced issue.
