### ISSUE TITLE
[dev.icinga.com #7703] Use clang-format to format the source code in a uniform way

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2263]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7703

**Created by gbeutner on 2014-11-17 17:27:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-04-29 16:02:31 +00:00 (in Redmine)_

---

**Comment by dnsmichi** [comment]
Not relevant anymore.
