### ISSUE TITLE
[dev.icinga.com #7710] Reimplement the Windows wizard using wxWidgets

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2269]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7710

**Created by gbeutner on 2014-11-17 17:35:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-23 13:36:40 +00:00 (in Redmine)_

---

---

**Relations**:

* relates [#7710](https://dev.icinga.com/issues/7710)
* relates [#7710](https://dev.icinga.com/issues/7710)

**Comment by dnsmichi** [comment]
Won't be implemented.
