### ISSUE TITLE
[dev.icinga.com #7752] Please support systemd startup notification

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2287]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7752

**Created by formorer on 2014-11-20 09:52:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-10-29 08:55:06 +00:00 (in Redmine)_

---

Hi,

systemd supports startup notifications via sd\_notify ( http://www.freedesktop.org/software/systemd/man/sd\_notify.html ) to signal systemd that the daemon is ready.
Maybe adding watchdog support via sd\_watchdog\_enabled ( http://www.freedesktop.org/software/systemd/man/sd\_watchdog\_enabled.html ) would be nice too.
That would allow systemd to supervise icinga2 properly.

---

**Relations**:

* relates [#10226](https://dev.icinga.com/issues/10226)

**Comment by gunnarbeutner** [comment]
This was implemented as part of #5996.
