### ISSUE TITLE
[dev.icinga.com #7922] livestatus large amount of submitting unix socket command results in broken pipes messages

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2373]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7922

**Created by kruisdraad on 2014-12-02 10:29:12 +00:00**

Assignee: _kruisdraad_
Status: _Closed_  (closed on _2016-02-25 00:30:09 +00:00_)
Target Version: _(none)_
Last Update: _2016-02-25 00:30:09 +00:00 (in Redmine)_

    Icinga Version: r2.2.0

---

With about 1000 commands being submitted using livestatus results in sporadic errors in icinga:

\[2014-11-06 15:47:50 +0100\] critical/Socket: send() failed with error code 32, "Broken pipe"
\[2014-11-06 15:47:50 +0100\] critical/LivestatusQuery: Cannot write to tcp socket.
\[2014-11-06 15:47:50 +0100\] critical/ThreadPool: Exception thrown in event handler:
/build/buildd/icinga2-2.1.1/lib/base/networkstream.cpp(46): Throw in function virtual size\_t icinga::NetworkStream::Read(void\*, size\_t)
Dynamic exception type: boost::exception\_detail::clone\_impl<boost::exception_detail::error_info_injector<std::invalid_argument> &gt;
std::exception::what: Tried to read from closed socket.
\[icinga::StackTrace\*\] =
(0) libbase.so: void boost::throw\_exception<boost::exception_detail::error_info_injector<std::invalid_argument> &gt;(boost::exception\_detail::error\_info\_injector<std::invalid_argument> const&) (+0x1a7) \[0x2ae3193cfba7\]
(1) libbase.so: void boost::exception\_detail::throw\_exception\_<std::invalid_argument>(std::invalid\_argument const&, char const**, char const**, int) (+0x69) \[0x2ae3193d9239\]
(2) libbase.so: icinga::NetworkStream::Read(void\*, unsigned long) (+0x75) \[0x2ae3193ea2b5\]
(3) libbase.so: icinga::Stream::ReadLine(icinga::String\*, icinga::ReadLineContext&) (+0x26c) \[0x2ae31940c86c\]
(4) liblivestatus.so: icinga::LivestatusListener::ClientHandler(boost::shared\_ptr<icinga::Socket> const&) (+0x14b) \[0x2ae3201351fb\]
(5) libbase.so: icinga::ThreadPool::WorkerThread::ThreadProc(icinga::ThreadPool::Queue&) (+0x3b3) \[0x2ae319415b93\]
(6) libboost\_thread.so.1.54.0: <unknown function> (+0xba4a) \[0x2ae31a49ea4a\]
(7) libpthread.so.0: <unknown function> (+0x8182) \[0x2ae319112182\]
(8) libc.so.6: clone (+0x6d) \[0x2ae319fc3fbd\]

This error seems cosmetic as the client 'disconnected' from the socket before the server was done with it. This
shouldn't really matter, its not nice but just close it and continue ...

Using unixcat does not give these problems, at least looping them with 500 processes submitting each 5000 results with unixcat did not gave any errors. The same amounts using a PHP class did result in loads of errors.

The API class being used is https://github.com/aashley/nagios-livestatus-client with a addition for the 'command' function which can be found here: http://pastie.org/private/go0z0qwye9nrq4lbybm2vg

Now as you can see adding a sleep before closing the socket fixes the problem, or at least i am not seeing any more errors or memory increasement anymore. As Unixcat handles this differently its logically not able to reproduce this. Given the error does not release the memory (seems to be the result area) from the process and can be found in the memory dumps.

**Comment by kajla** [comment]
I have a similar problem here. :(

/var/log/icinga2/icinga2.log:
```
[2018-01-08 13:13:02 +0100] critical/Socket: send() failed with error code 32, "Broken pipe"
[2018-01-08 13:13:02 +0100] critical/LivestatusQuery: Cannot write query response to socket.
[2018-01-08 13:13:02 +0100] critical/LivestatusQuery: Cannot write query response to socket.
[2018-01-08 13:13:02 +0100] critical/ThreadPool: Exception thrown in event handler:
Error: Tried to read from closed socket.

        (0) libbase.so.2.8.0: <unknown function> (+0xca801) [0x7f0ba1fca801]
        (1) libbase.so.2.8.0: icinga::NetworkStream::Read(void*, unsigned long, bool) (+0x75) [0x7f0ba1febbf5]
        (2) libbase.so.2.8.0: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr<icinga::Stream> const&, bool) (+0x58) [0x7f0ba1fb2268]
        (3) libbase.so.2.8.0: icinga::Stream::ReadLine(icinga::String*, icinga::StreamReadContext&, bool) (+0x74) [0x7f0ba1fb23a4]
        (4) liblivestatus.so.2.8.0: icinga::LivestatusListener::ClientHandler(boost::intrusive_ptr<icinga::Socket> const&) (+0x13a) [0x7f0b9ce274ea]
        (5) libbase.so.2.8.0: icinga::ThreadPool::WorkerThread::ThreadProc(icinga::ThreadPool::Queue&) (+0x365) [0x7f0ba20082c5]
        (6) libboost_thread.so.1.54.0: <unknown function> (+0xcc0a) [0x7f0ba2c34c0a]
        (7) libpthread.so.0: <unknown function> (+0x8744) [0x7f0ba1543744]
        (8) libc.so.6: clone (+0x6d) [0x7f0ba2f29aad]


[2018-01-08 13:13:02 +0100] critical/Socket: send() failed with error code 32, "Broken pipe"
[2018-01-08 13:13:02 +0100] critical/LivestatusQuery: Cannot write query response to socket.
[2018-01-08 13:13:02 +0100] critical/LivestatusQuery: Cannot write query response to socket.
[2018-01-08 13:13:02 +0100] critical/ThreadPool: Exception thrown in event handler:
Error: Tried to read from closed socket.

        (0) libbase.so.2.8.0: <unknown function> (+0xca801) [0x7f0ba1fca801]
        (1) libbase.so.2.8.0: icinga::NetworkStream::Read(void*, unsigned long, bool) (+0x75) [0x7f0ba1febbf5]
        (2) libbase.so.2.8.0: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr<icinga::Stream> const&, bool) (+0x58) [0x7f0ba1fb2268]
        (3) libbase.so.2.8.0: icinga::Stream::ReadLine(icinga::String*, icinga::StreamReadContext&, bool) (+0x74) [0x7f0ba1fb23a4]
        (4) liblivestatus.so.2.8.0: icinga::LivestatusListener::ClientHandler(boost::intrusive_ptr<icinga::Socket> const&) (+0x13a) [0x7f0b9ce274ea]
        (5) libbase.so.2.8.0: icinga::ThreadPool::WorkerThread::ThreadProc(icinga::ThreadPool::Queue&) (+0x365) [0x7f0ba20082c5]
        (6) libboost_thread.so.1.54.0: <unknown function> (+0xcc0a) [0x7f0ba2c34c0a]
        (7) libpthread.so.0: <unknown function> (+0x8744) [0x7f0ba1543744]
        (8) libc.so.6: clone (+0x6d) [0x7f0ba2f29aad]


[2018-01-08 13:13:02 +0100] critical/Socket: send() failed with error code 32, "Broken pipe"
[2018-01-08 13:13:02 +0100] critical/LivestatusQuery: Cannot write query response to socket.
[2018-01-08 13:13:02 +0100] critical/LivestatusQuery: Cannot write query response to socket.
[2018-01-08 13:13:02 +0100] critical/ThreadPool: Exception thrown in event handler:
Error: Tried to read from closed socket.

        (0) libbase.so.2.8.0: <unknown function> (+0xca801) [0x7f0ba1fca801]
        (1) libbase.so.2.8.0: icinga::NetworkStream::Read(void*, unsigned long, bool) (+0x75) [0x7f0ba1febbf5]
        (2) libbase.so.2.8.0: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr<icinga::Stream> const&, bool) (+0x58) [0x7f0ba1fb2268]
        (3) libbase.so.2.8.0: icinga::Stream::ReadLine(icinga::String*, icinga::StreamReadContext&, bool) (+0x74) [0x7f0ba1fb23a4]
        (4) liblivestatus.so.2.8.0: icinga::LivestatusListener::ClientHandler(boost::intrusive_ptr<icinga::Socket> const&) (+0x13a) [0x7f0b9ce274ea]
        (5) libbase.so.2.8.0: icinga::ThreadPool::WorkerThread::ThreadProc(icinga::ThreadPool::Queue&) (+0x365) [0x7f0ba20082c5]
        (6) libboost_thread.so.1.54.0: <unknown function> (+0xcc0a) [0x7f0ba2c34c0a]
        (7) libpthread.so.0: <unknown function> (+0x8744) [0x7f0ba1543744]
        (8) libc.so.6: clone (+0x6d) [0x7f0ba2f29aad]
```

Icinga2 version: r2.8.0-1
Enabled features: api checker compatlog ido-mysql livestatus mainlog notification
Operating system: SUSE Linux Enterprise Server 12 SP3

Could you help me, please?

Thank you in advance.
