### ISSUE TITLE
[dev.icinga.com #8213] HA-Setup with update-config

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2516]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8213

**Created by aledermueller on 2015-01-14 12:15:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-14 13:05:54 +00:00 (in Redmine)_

---

Hi,

i am using a HA-Setup like this:

    object Endpoint "master1.domain" {
      host = "master1.domain"
    }
    object Endpoint "master2.domain" {
      host =  "master2.domain"
    }
    object Zone "master" {
      endpoints = [ "master1.domain", "master2.domain" ]
    }

On each master i am using \`icinga2 node update-config\` to write the config which is sent from icinga2-agents. After the update-config icinga2 cannot be restarted, because master1 gets his own config from master2 and vice versa. This leads to a duplicated definition of zones, endpoints, hosts and services.

e.g. on master1 i have to remove

repository.d/zones/master.conf
repository.d/zones/master1.domain.conf
repository.d/endpoints/master2.domain.conf
repository.d/hosts/master1.domain.conf
repository.d/hosts/master1.domain/

Kind regards,
Achim

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Relations**:

* relates [#8213](https://dev.icinga.com/issues/8213)
* relates [#9927](https://dev.icinga.com/issues/9927)
* relates [#8213](https://dev.icinga.com/issues/8213)

**Comment by dnsmichi** [comment]
Closing since the entire mode will be removed with #4799.
