### ISSUE TITLE
[dev.icinga.com #8513] Remove acknowledgement/downtime on output change (1.x: "Stalking")

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2655]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8513

**Created by Foxeronie on 2015-02-23 21:12:35 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2016-03-31 10:41:14 +00:00_)
Target Version: _(none)_
Last Update: _2016-03-31 10:41:14 +00:00 (in Redmine)_

---

Hi,

I saw that there was a Stalking Mode Feature in Icinga 1.
It would be great if something like this would be in Icinga 2 with the feature to remove an acknowledgement or downtime, when the Output of a service has changed.
We splitted our Hardware Check for Dell Server from three up to ten to ensure that we can acknowledge every problem without overlooking other errors. But sometimes this isn't working (a second fan, disk, etc. fail and we don't see it).
There is not always the possibility to directly changing the defective hardware, so we need to wait a couple of weeks. In this time nobody can see other failing hardware parts.
Also having seven more checks to run on worker nodes with almost full load causes more timeouts than before.
Another use case for us are our running pools from a service or a hypervisor with a lot of vm's. If one of this have a problem and it is acknowledged you can't see any other problems for this services.
So removing a acknowledge when the output has changed would be a wonderful solution.
My idea for the realization is a additional table:

    host_name | service_name | last_output
    -----------------|---------------------|------------------
    my_server1|Dell Storage___|0:0:1 failed

Then you can set a new parameter for an Service.

    object Service "Dell Storage" {
    ...
        stalk_output = "line-breaks|lines|signs"
    ...
    }

If the option is enabled, Icinga 2 is checking the last\_ouput in this table with the output from the current output if the problem is acknowledged (or it's checkig if there is one after there was a different).
If there are other counts of breaks/lines/signs it removes the acknowledge and the state\_changed will be set to the current time, so the services shows up at the top.

With over 3000 servers we have a lot of this cases and reducing checks, load, work and possible crashes would be a great argument for realizing Icinga 2 for our default monitoring.

That's all for now.

Best regards,
Patrick

**Comment by outermedia-sol** [comment]
I see that the label enhancement was added after the issue was closed. Can you reopen it. The idea is still valid and could be very helpful in a lot of situations.

**Comment by dnsmichi** [comment]
That was done by the migration script applying the labels matching redmine -> GitHub. With the use of the API event streams, one can already implement this logic. As such, there's still no plans to move this into the core itself.
