### ISSUE TITLE
[dev.icinga.com #8532] Execute Icinga as non-root user

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2667]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8532

**Created by frjaraur on 2015-02-25 11:27:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-01-26 18:00:29 +00:00 (in Redmine)_

    Icinga Version: 2.2.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

We will like to keep separated monitoring applications from system (using sudo for root-required monitors) .
Icinga2 daemon runs as icinga user (or selected user if we compile source code), but why do we need root for enabling/disabling Icinga2 modules for example?. We found same root Icinga2 usages that we don't really think they are necessary (for example configuring icinga2 modules). We try using sudo but we are afraid of root permission issues for newly created files.
Is it really a root required application? or just for installing purposes.

Many Thanks,
Javier R.

**Comment by dnsmichi** [comment]
Closing this in favour of the newly created issue #4947.
