### ISSUE TITLE
[dev.icinga.com #8662] Processing TimePeriods when parsing large configurations

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2719]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8662

**Created by mdetrano on 2015-03-09 21:21:11 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-26 09:12:37 +00:00 (in Redmine)_

    Icinga Version: 2.3.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

I ran into an issue while trying to process a large configuration (attempted port from a "in-production" Nagios system, but I can reproduce this by creating a mockup system with many hosts and service apply rules).

I attempt to verify the config with:

icinga2 daemon -C -x debug

and five minutes into the process, I see it starts parsing out TimePeriods starting from 1970 and running to now.

...

debug/TimePeriod: Adding segment 'Wed Dec 31 17:00:00 1969' &lt;-&gt; 'Thu Jan 1 00:00:00 1970' to TimePeriod 'nonworkhours'
debug/TimePeriod: Adding segment 'Thu Jan 1 00:00:00 1970' &lt;-&gt; 'Thu Jan 1 09:00:00 1970' to TimePeriod 'nonworkhours'
debug/TimePeriod: Adding segment 'Thu Jan 1 17:00:00 1970' &lt;-&gt; 'Fri Jan 2 00:00:00 1970' to TimePeriod 'nonworkhours'
debug/TimePeriod: Adding segment 'Fri Jan 2 00:00:00 1970' &lt;-&gt; 'Fri Jan 2 09:00:00 1970' to TimePeriod 'nonworkhours'
debug/TimePeriod: Adding segment 'Fri Jan 2 17:00:00 1970' &lt;-&gt; 'Sat Jan 3 00:00:00 1970' to TimePeriod 'nonworkhours'
debug/TimePeriod: Adding segment 'Sat Jan 3 00:00:00 1970' &lt;-&gt; 'Sun Jan 4 00:00:00 1970' to TimePeriod 'nonworkhours'

...

With a few time periods setup..especially ones with several specs per day, this parsing can take hours.

This behaviour seems to be time dependent, not \# of hosts/applies .. On a more powerful system I can get a lot more services processed...but at 5 minutes (exactly 5 minutes), the strange TimePeriods segment parsing starts.

My workaround is to avoid using some apply rules where I can use a direct host assignment on these services, which speeds up the verification. However, it would be nice to be able to use the apply..assign syntax for "any" sized configuration.

**Comment by Al2Klimov** [comment]
```
Breakpoint 1, icinga::TimePeriod::AddSegment (this=this@entry=0x7fffcc7087a0, begin=28800, end=end@entry=57600) at /usr/src/debug/icinga2-2.3.0/lib/icinga/timeperiod.cpp:65
65              if (GetValidBegin().IsEmpty() || begin < GetValidBegin())
(gdb) bt
#0  icinga::TimePeriod::AddSegment (this=this@entry=0x7fffcc7087a0, begin=28800, end=end@entry=57600) at /usr/src/debug/icinga2-2.3.0/lib/icinga/timeperiod.cpp:65
#1  0x00007ffff0f0b293 in icinga::TimePeriod::AddSegment (this=this@entry=0x7fffcc7087a0, segment=...) at /usr/src/debug/icinga2-2.3.0/lib/icinga/timeperiod.cpp:107
#2  0x00007ffff0f1105e in icinga::TimePeriod::UpdateRegion (this=0x7fffcc7087a0, begin=begin@entry=0, end=end@entry=1493975236.858537, clearExisting=clearExisting@entry=false)
    at /usr/src/debug/icinga2-2.3.0/lib/icinga/timeperiod.cpp:214
#3  0x00007ffff0f115cb in icinga::TimePeriod::UpdateTimerHandler () at /usr/src/debug/icinga2-2.3.0/lib/icinga/timeperiod.cpp:281
```
`TimePeriod::UpdateTimerHandler()` is called only by a timer which is being set up by `TimePeriod::StaticInitialize()` which is called **unconditionally**.

**Comment by Crunsher** [comment]
@Al2Klimov Do you have an idea how to easily fix this?

**Comment by Al2Klimov** [comment]
Right now I've none as I'm busy with non-I2 things. I think if I *had* one, I've been done somewhat more than just commenting. (Or maybe I had one how to do it "quick and dirty", but I left the design decision up to you, @Crunsher @gunnarbeutner @dnsmichi)

**Comment by Al2Klimov** [comment]
Whiteboxtested the code again:

1. Forget the "unconditionally" part. Those methods only get invoked on/after object activation.
2. It's a debug log message. I doubt we should even care.

**Comment by Al2Klimov** [comment]
@mdetrano Did you create this issue? If yes, please test Icinga v2.10.2.

**Comment by mdetrano** [comment]
> @mdetrano Did you create this issue? If yes, please test Icinga v2.10.2.

Yes, I believe this was fixed some time ago actually.  Just re-tested on a lab system running 2.10.3.

In "real life" I have not had any configuration, even large ones, take so long to parse anyhow.  However, when forced to run for more than five minutes the original Timeperiod problem reported no longer occurs.
