### ISSUE TITLE
[dev.icinga.com #8813] Add runtime validation for object attributes

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2797]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8813

**Created by mfriedrich on 2015-03-19 11:32:11 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-04-07 09:48:35 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

    <18> => h.check_command = "foo"
    null
    <19> => h.last_check_result.output 
    "HTTP OK: HTTP/1.0 200 OK - 46260 bytes in 1,385 second response time "
    <20> => icinga2: /usr/include/boost/smart_ptr/intrusive_ptr.hpp:162: T *boost::intrusive_ptr::operator->() const [T = icinga::CheckCommand]: Assertion `px != 0' failed.
    Caught SIGABRT.
    Current time: 2015-03-19 12:34:31 +0100

    critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in '/var/log/icinga2/crash/report.1426764871.2607679'

    Context:
        (0) Executing check for object 'test'

    critical/checker: Exception occured while checking 'test': Error: Function call 'open' for file '/var/log/icinga2/crash/report.1426764871.2607679' failed with error code 13, 'Permission denied'

---

**Relations**:

* relates [#8813](https://dev.icinga.com/issues/8813)
* blocks [#8813](https://dev.icinga.com/issues/8813)

**Comment by dnsmichi** [comment]
Won't happen, the console is a debug playground only.
