### ISSUE TITLE
[dev.icinga.com #8833] service checks stuck in "pending" or last check and ignores force check

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2810]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8833

**Created by rhillmann on 2015-03-21 22:36:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-17 12:41:29 +00:00 (in Redmine)_

    Icinga Version: 2.3.2
    Backport?: Not yet backported
    Include in Changelog: 1

---

I have seen a big problem in our cluster environment and cant see what can be wrong, so i guess this is a critical bug in icinga2.
A lot of checks are stucks at the pending state or not getting re-sheduled. Some checks should checked in the past, but stuck at the last check time (&gt;6h!).

Sheduling the next chick (with force) doesnt solve the problem, the check becomes only a new shedule time, but the check never happened.
I have doubled check the services with classicui and the new web2. Its almost the same, so the problem needs to be located at the core.

I observed this issue since 2.3.0, but i am not sure if this problem was present in earlier releases.
The cluster nodes are not under heavy load, so its not an performance issue. They are almost on a load of 2.

zone.conf

    object Endpoint "hydrogenguest6.a2.rz1.domain.com" {
      host = "hydrogenguest6.a2.rz1.domain.com" 
      log_duration = 2h
    }
    object Endpoint "fluorineguest6.b3.rz1.domain.com" {
      host = "fluorineguest6.b3.rz1.domain.com" 
      log_duration = 2h
    }
    object Endpoint "hydrogenguest4.a1.rz0.domain.com" {
      host = "hydrogenguest4.a1.rz0.domain.com" 
      log_duration = 2h
    }
    object Endpoint "dresdenguest6.muc.domain.com" {
      host = "dresdenguest6.muc.domain.com" 
      log_duration = 2h
    }
    object Endpoint "hydrogenguest3.a1.rz0.domain.com" {
      host = "hydrogenguest3.a1.rz0.domain.com" 
      log_duration = 2h
    }
    object Endpoint "chlorineguest10.a2.rz1.domain.com" {
      host = "chlorineguest10.a2.rz1.domain.com" 
      log_duration = 2h
    }
    object Endpoint "dresdenguest7.muc.domain.com" {
      host = "dresdenguest7.muc.domain.com" 
      log_duration = 2h
    }
    object Endpoint "hydrogenguest9.b2.rz1.domain.com" {
      host = "hydrogenguest9.b2.rz1.domain.com" 
      log_duration = 2h
    }
    object Zone "global" {
      global = true
    }

    object Zone "frontend" {
      endpoints = ["hydrogenguest4.a1.rz0.domain.com","dresdenguest7.muc.domain.com",]
    }

    object Zone "master" {
      endpoints = ["hydrogenguest6.a2.rz1.domain.com","fluorineguest6.b3.rz1.domain.com",]
      parent = "frontend" 
    }

    object Zone "worker" {
      endpoints = ["dresdenguest6.muc.domain.com","hydrogenguest3.a1.rz0.domain.com","chlorineguest10.a2.rz1.domain.com","hydrogenguest9.b2.rz1.domain.com",]
      parent = "master" 

**Attachments**

* [master-1.debug.1.tar.gz](https://dev.icinga.com/attachments/download/2361/master-1.debug.1.tar.gz) rhillmann - _2015-03-30 14:58:53 +00:00_ - _debug log part1_
* [master-1.debug.2.tar.gz](https://dev.icinga.com/attachments/download/2362/master-1.debug.2.tar.gz) rhillmann - _2015-03-30 14:58:57 +00:00_ - _debug log part2_
* [object-list.txt](https://dev.icinga.com/attachments/download/2368/object-list.txt) rhillmann - _2015-03-31 09:03:09 +00:00_ - _stuck service check ping4_
* [workqueue.PNG](https://dev.icinga.com/attachments/download/3002/workqueue.PNG) sudeshkumar - _2016-01-14 14:44:50 +00:00_
* [troubleshooting-2016-06-12_16_25_32.log](https://dev.icinga.com/attachments/download/3426/troubleshooting-2016-06-12_16_25_32.log) rglemaire - _2016-06-12 16:42:57 +00:00_

**Comment by dnsmichi** [comment]
I consider this being fixed with v2.6.1. Please upgrade to the latest stable & supported version. 2.4.x is EOL already.
