### ISSUE TITLE
[dev.icinga.com #8897] Duplicated scheduled downtimes created in cluster HA zone

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2844]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8897

**Created by dgoetz on 2015-03-30 07:52:53 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-09 14:52:13 +00:00 (in Redmine)_

    Icinga Version: 2.3.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

### Setup

-   ha master with 2 nodes
-   one config master with zones.d
-   ScheduledDowntime object configuration

### Problem

Both cluster nodes sync their configuration, and will schedule a new downtime from the configuration objects.
The cluster event will be sent to each other and creating an additional downtime with the same time window, but different id.

### Proposed Solution

Check for config\_owner attribute in AddDowntime() and do not add the downtime if there already exists one.
This is similar to how we prevent deleting downtimes at runtime which are generated from config objects.

### Original description

A Scheduled Downtime creates a Downtime on every host in ha zone, this causes no problems except of to many objects and bloated views.

---

**Relations**:

* relates [#9927](https://dev.icinga.com/issues/9927)
* relates [#9777](https://dev.icinga.com/issues/9777)

**Comment by dnsmichi** [comment]
Duplicate of #4272

**Comment by dnsmichi** [comment]
## SDs paused

![scheduled_downtime_ha_cluster_paused](https://user-images.githubusercontent.com/382049/49448636-9edc4600-f7d9-11e8-9b08-f34539d08913.png)

## Downtimes just once

![scheduled_downtime_ha_cluster_just_one_downtime](https://user-images.githubusercontent.com/382049/49448653-a7cd1780-f7d9-11e8-9ac0-b819129bfb5a.png)

**Comment by dnsmichi** [comment]
ref/IC/9673

**Comment by dgoetz** [comment]
ref/NC/590176
ref/NC/591721
