### ISSUE TITLE
[dev.icinga.com #9117] Make features HA-aware

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2941]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9117

**Created by dgoetz on 2015-04-20 12:13:28 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-08-16 10:25:34 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Some features are already ha aware, I think Perfdata-Writer and perhaps others like Graphite-Writer needs to be aware also.

My environment for example:
- Two nodes icinga2 in master zone
- One node with the webinterface and pnp4nagios

Workarounds now:
- Both master feature perfdata is active, I need a script which gets the data from one host and purges the others and switches if the first one is down and handle recovery properly, so I do net mess up data.
- Only one node manual intervention is neccessary on both sides and I have gaps.

Best solution would be every host writes its own perfdata for only the executed and not the transferred checks and I collect all perfdata files. (Not sure if I configure now a suffix with the endpoints name to not get a file collision.)

---

**Relations**:

* relates [#9117](https://dev.icinga.com/issues/9117)

**Comment by friesoft** [comment]
Any news? :) We would love to use this in combination with the new logstashwriter with an icinga2 cluster 
With 2 nodes and a central elastic stack.

**Comment by dnsmichi** [comment]
The LogstashWriter is still undergoing review and has not been merged to release branches. In terms of this feature - please dive into the code and contribute a patch.
