### ISSUE TITLE
[dev.icinga.com #9206] daemonize blocks on start w/ ApiListener and non-existing bind_host

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#2980]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9206

**Created by Nanfonpi on 2015-04-30 13:58:47 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-19 11:48:35 +00:00 (in Redmine)_

    Icinga Version: 2.3.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

We have some nodes which are connected to our infrastructure via openvpn.

We were unable to reboot these machines after upgrading to icinga2.
The cause was the IP address configured in "bind\_host" in ApiListener Object, which in our case is the address of our openvpn interface was not up at the time when icinga was started by the init system.
The result was that icinga blocked the complete boot process.

This issue can be reproduced with any address configured in "bind\_host" which is not available on the system and starting icinga.

Expected behavior:
Icinga exits with an error message, when listening IP address is not found.

Kind regards

---

**Relations**:

* relates [#9206](https://dev.icinga.com/issues/9206)

**Comment by dnsmichi** [comment]
Unless someone contributes a patch, this remains closed.
