### ISSUE TITLE
[dev.icinga.com #9267] Behaviour of node whitelist/blacklist

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3014]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9267

**Created by formorer on 2015-05-13 08:49:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-14 13:07:03 +00:00 (in Redmine)_

    Icinga Version: 2.3.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

On one of my systems I have the following blacklist filter:

    blacklist filter for Node: '*' Host: '*' Service: '*'.

Which correctly ignores everything.

I now added the following whitelistfilter:
whitelist filter for Node: '**' Host: 'i2-slave2.icinga.int' Service: '**'.

But that doesn't work:

    warning/cli: Skipping node 'i2-slave2.icinga.int' on blacklist.

What works is:

    whitelist filter for Node: 'i2-slave2.icinga.int' Host: '*' Service: '*'.

That behaviour is at least unpexected and should be either adapted or fixed.

The terminus "node" and "zone" are also mixed, the parameter is talking about zone, whereas the
output talks about "node". That also needs some clarification

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Comment by dnsmichi** [comment]
#4799
