### ISSUE TITLE
[dev.icinga.com #9271] Icinga2 OpenWRT Package(s)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3018]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9271

**Created by vlda on 2015-05-13 11:18:13 +00:00**

Assignee: _vlda_
Status: _Resolved_  (closed on _2015-05-13 11:50:03 +00:00_)
Target Version: _(none)_
Last Update: _2015-05-13 11:58:33 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

icinga2 is one of few monitoring solutions allowing encrypted communication between the server
and agent (without the need of a vpn). Moreover, if in icinga2 client mode, the client sends it's states to the server.

In a setup, where agents are connected via dial-up, dsl, or other means resulting in a dynamically assigned ip, the way icinga2 works has strong benefits.

I think there is no need to introduce OpenWRT.

Bringing Icinga2 to OpenWRT would be very very cool, since there is nothing comparable to find in the OpenWRT packages \[nagios/nrpe is too old and flawed/insecure, zabbix/zabbix-agent are insecure\], which brings the flexibility icinga2 offers.

I hope that it is possible to bring native (or maybe static?) icinga2 packages to OpenWRT.

Thank you :)

**Changesets**

_2015-05-13 11:48:02 +00:00_ by _(unknown)_ 2658c16c0b8ffca36a4813a39fe9bf9236a7134a

    Change permissions for the etc directory on Windows
    
    fixes #9271

_2015-05-13 11:48:11 +00:00_ by _(unknown)_ 3a8d37c2710ef58986999d445949b4d7a7270fac

    Change permissions for the etc directory on Windows
    
    fixes #9271

_2015-05-13 11:52:51 +00:00_ by _(unknown)_ bad6ca1108049edcbfc67d31e00159712857e1b3

    Change permissions for the etc directory on Windows
    
    fixes #9271

_2015-05-13 11:53:07 +00:00_ by _(unknown)_ 2324f5e13ce0f5b304968ce0c400bae515eaf47c

    Change permissions for the etc directory on Windows
    
    fixes #9271

**Comment by nwf** [comment]
This issue appears to be erroneously closed, and I am eager to have openwrt packages for icinga2 and icingaweb2 if anyone is working on them? :)

**Comment by stibi** [comment]
Ho guys, what is the status? Was there any problem to build an openwrt package for icinga2?

**Comment by dnsmichi** [comment]
Currently there's no plans to add such packages to our repos. I would suggest to build them and share such in community repositories. Highly likely the community forums are the best place to discuss building packages.

**Comment by nwf** [comment]
@dnsmichi Can this issue be reopened until they exist?

**Comment by dnsmichi** [comment]
I don't think that we should keep this issue open, as we from 'icinga2' won't be adding it.
