### ISSUE TITLE
[dev.icinga.com #9295] 100 Million Records in Log file: Read from event FD failed

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3029]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9295

**Created by TechIsCool on 2015-05-19 23:49:12 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-26 22:51:06 +00:00 (in Redmine)_

    Icinga Version: 3.2.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

So today I had a virtual NFS disk lag due to external issues not related to Icinga, On one of my Windows Servers I experienced an issue where I almost ran out of Disk space. icinga notified me correctly but it was Icinga that was consuming all the space with its log file.

I have a copy of the Data but I don't think anyone wants the 10+GB files so I have trimmed it down to just the errors that occurred with the counts of them. If you want to see a section let me know and I will rip it from the file.

This is from the icinga2.log not debug.log which I would have expected to see this size file.

2 critical/TcpSocket: getaddrinfo() failed with error code 11001, "No such host is known. "
2 information/Application: Received request to shut down.
2 information/Application: Shutting down...
2 information/ConfigItem: Activated all objects.
3 critical/ApiListener: Cannot connect to host 'abydos.domainname.com' on port '5665'
3 information/ApiClient: No messages for identity 'vault.domainname.com' have been received in the last 60 seconds.
8 critical/ThreadPool: Exception thrown in event handler:
8 rogram Files (x86)\\ICINGA2\\var/lib/icinga2/icinga2.state.tmp' failed with error code 13, 'Permission denied'
9 warning/ApiClient: Error while sending JSON-RPC message for identity 'vault.domainname.com'
11 critical/TcpSocket: Invalid socket: 10061, "No connection could be made because the target machine actively refused it."
11 warning/ApiListener: Removing API client for endpoint 'vault.domainname.com'. 0 API clients left.
12 critical/ApiListener: Cannot connect to host 'vault.domainname.com' on port '5665'
12 information/ApiListener: New client connection for identity 'vault.domainname.com'
12 warning/ApiClient: API client disconnected for identity 'vault.domainname.com'
14 information/ApiClient: Not sending heartbeat for endpoint 'vault.domainname.com' because we're replaying the log for it.
19 warning/ApiClient: API client disconnected for identity 'abydos.domainname.com'
19 warning/ApiClient: Error while sending JSON-RPC message for identity 'abydos.domainname.com'
19 warning/ApiListener: Removing API client for endpoint 'abydos.domainname.com'. 0 API clients left.
23 information/ApiClient: Reconnecting to API endpoint 'vault.domainname.com' via host 'vault.domainname.com' and port '5665'
24 information/ApiListener: New client connection for identity 'abydos.domainname.com'
25 information/ApiClient: Reconnecting to API endpoint 'abydos.domainname.com' via host 'abydos.domainname.com' and port '5665'
825 information/ApiClient: Not sending heartbeat for endpoint 'abydos.domainname.com' because we're replaying the log for it.
2,178 information/DynamicObject: Dumping program state to file 'C:\\Program Files (x86)\\ICINGA2\\var/lib/icinga2/icinga2.state'
108,616,317 critical/SocketEvents: Read from event FD failed.

This log file Starts at 5-12-2015 around 2PM and Ends 5-19-2015 at 3PM

The Error that continually appears started at 5-19-2015 11:45 Ends 5-19-2015 at 3PM

So just in about 3 Hours I had 10GB consumed

---

**Relations**:

* relates [#9295](https://dev.icinga.com/issues/9295)

**Comment by t-rex2** [comment]
This problem also occured to some of my Windows Server 2008 R2 with installed icinga2-agent version 2.8.0:

 [2018-08-13 09:13:38 +0200] critical/SocketEvents: Read from event FD failed.
 [2018-08-13 09:13:38 +0200] critical/SocketEvents: Read from event FD failed.
 [2018-08-13 09:13:38 +0200] critical/SocketEvents: Read from event FD failed.
 [2018-08-13 09:13:38 +0200] critical/SocketEvents: Read from event FD failed.

One log was about 7 GB and on another server it was about 13 GB. As a result of this, the C:\-Partition run out of disk space.

**Comment by dnsmichi** [comment]
I could silence the logging, but actually this is a real error when the FD is gone inside the socket IO thread. I haven't found it yet why this only happens on Windows with `poll`.

**Comment by Al2Klimov** [comment]
Hello @t-rex2!

Do I understand you right that your Windows agent produces gigs of log with the most messages being the ones you posted?

Best,
AK

**Comment by t-rex2** [comment]
Hi Al2Klimov,

yes that's right.

Kind regards

**Comment by Al2Klimov** [comment]
This issue seems to have been addressed by #7005.

**Comment by dnsmichi** [comment]
Hi @t-rex2,

snapshot packages for Windows are available for testing on https://packages.icinga.com
Would be awesome if you can test them :)

Thanks,
Michael

**Comment by dnsmichi** [comment]
I consider this being resolved. Please test the snapshot packages either way prior to the release not to run into any other pitfalls.
