### ISSUE TITLE
[dev.icinga.com #9332] Send custom attributes/groups/etc from satellite to master for node update-config

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3044]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9332

**Created by adegtyarev on 2015-05-28 14:12:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-14 13:08:23 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Variables that set on satellite side are not passed to master:

satellite:

    # icinga2 object list --type host
     ...
      * vars
        * check_pgsql = 1
          % = modified in '/etc/icinga2/conf.d/hosts.conf', lines 7:3-7:22
        * notification
          * sms = 1
            % = modified in '/etc/icinga2/conf.d/hosts.conf', lines 10:3-10:27
        * os = "Linux"
     ...

master:

    # icinga2 object list --type host
     ...
      * vars
        * notification
          * mail
            % = modified in '/etc/icinga2/conf.d/satellite.conf', lines 2:3-4:3
            * groups = [ "infrastructure" ]
     ...

This eventually leads to some lacks:

-   Unable to use groups according to vars set on satellites:

    object HostGroup "linux-servers"{
      display_name = "Linux Servers"
      assign where host.vars.os == "Linux"
    }

No satellite host will appear in this group regardless `host.vars.os` is set on satellite or not. This could probably workarrounded with satellite's hosts definition directly on master, but it this case the idea of satellites looks not so much attractive..

-   Unable to use notifications on master based on host/service vars from satellites:

    apply Notification "sms" to Service {
        import "sms-service-notification"
        assign where host.vars.notification.sms
    }

As long as `host.vars.*` unset on master, no notification will be applied to satellite's services. To make this notifications work, notifications on satellites required to be enabled, which is not always possible.

Would be a nice feature if variables from satellites gets transferred to master as well.

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Comment by dnsmichi** [comment]
#4799
