### ISSUE TITLE
[dev.icinga.com #9437] Notifications are not working properly when enabled in master- and child-zone

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3075]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9437

**Created by mwaldmueller on 2015-06-17 10:53:07 +00:00**

Assignee: _(none)_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:55:34 +00:00 (in Redmine)_

    Icinga Version: 2.3.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

My setup:
- "master"-zone is parent zone with one node
- "checker"-zone is child zone with one node
- notification feature is enabled on all nodes in both zones

Problem: Inital notification is send from both zones
Problem: Re-notifications are either send from master- or checker-zone

---

**Relations**:

* relates [#11562](https://dev.icinga.com/issues/11562)

**Comment by Al2Klimov** [comment]
@mwaldmueller Does this issue still occur in v2.10.2?

**Comment by dnsmichi** [comment]
Markus is on vacation, there's no feedback any time soon. I'll close this and if it is still the case, please create a new issue.
