### ISSUE TITLE
[dev.icinga.com #9438] Notifications from child-nodes should be visible on master-node

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3076]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9438

**Created by mwaldmueller on 2015-06-17 11:04:46 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2016-11-15 09:34:23 +00:00_)
Target Version: _Backlog_
Last Update: _2016-11-15 10:47:47 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

My setup:
- "master"-zone is parent zone

The notifications that are sent from nodes from a child-/checker-zone should be transfered to the master, so that they are also visible in GUI's like Icinga Web 2 on the master.

---

**Relations**:

* blocks [#9871](https://dev.icinga.com/issues/9871)

**Comment by Al2Klimov** [comment]
@lippserd This is about _notification sending events_, not the _notification config objects_, right?

**Comment by Al2Klimov** [comment]
_PING_ @lippserd

**Comment by lippserd** [comment]
I'm afraid it won't be fixed anytime soon.
