### ISSUE TITLE
[dev.icinga.com #9443] Add practical examples for conditional apply (services, notifications, dependencies)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3079]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9443

**Created by mfriedrich on 2015-06-18 07:50:19 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-25 14:29:41 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

### Requirement

-   Add conditionals (url to language reference)
-   Add reference to expressions
-   Explain them by example

#### Services

check\_commands based on Host-Attributes: http://www.monitoring-portal.org/wbb/index.php?page=Thread&postID=218018#post218018

    object CheckCommand "ping4_tos" {
      import "ping4"

      arguments += {
        "-Q" = "$ping_tos$"
      }
    }

    object Host "host-tos" {
      address = "127.0.6.6"
      check_command = "hostalive"

      vars.ping_tos = 666
    }

    object Host "host-notos" {
      address = "127.0.6.7"
      check_command = "hostalive"
    }

    apply Service "my-ping4" {
      check_interval = 1s
      retry_interval = 1s

      if (host.vars.ping_tos) {
        check_command = "ping4_tos"
      } else {
        check_command = "ping4"
      }

      assign where host.address
    }

#### Notifications

http://www.monitoring-portal.org/wbb/index.php?page=Thread&postID=217593#post217593
http://www.monitoring-portal.org/wbb/index.php?page=Thread&postID=217609#post217609
https://twitter.com/noledge/status/611429338563649537
![icinga2_notification_conditions.png](https://dev.icinga.com/attachments/download/2514/icinga2_notification_conditions.png)

    apply Notification "mail-icingaadmin" to Service {
      import "mail-service-notification"

      user_groups = host.vars.notification.mail.groups

      if (match("ssh*", service.name)) {
        interval = 30s
      } else {
        interval = 60s
      }

      assign where host.vars.notification.mail
    }

    nbmif /etc/icinga2/conf.d # icinga2 object list --type Notification --name *ssh*
    Object 'nbmif.int.netways.de!ssh!mail-icingaadmin' of type 'Notification':
      % declared in '/etc/icinga2/conf.d/notifications.conf', lines 19:1-19:48
      * __name = "nbmif.int.netways.de!ssh!mail-icingaadmin"
      * command = "mail-service-notification"
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 63:3-63:39
      * command_endpoint = ""
      * host_name = "nbmif.int.netways.de"
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 19:1-19:48
      * interval = 30
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 25:5-25:18
      * name = "mail-icingaadmin"
      * period = "24x7"
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 70:3-70:17
      * service_name = "ssh"
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 19:1-19:48
      * states = [ 1, 2, 4, 8 ]
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 65:3-65:45
      * templates = [ "mail-icingaadmin", "mail-service-notification" ]
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 19:1-19:48
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 62:1-62:49
      * times = null
      * type = "Notification"
      * types = [ 32, 16, 64, 8, 128, 256, 1, 2, 4 ]
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 66:3-68:57
      * user_groups = [ "icingaadmins" ]
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 22:3-22:50
      * users = null
      * vars = null
      * zone = ""

    Object 'nbmif.int.netways.de!ping4!mail-icingaadmin' of type 'Notification':
      % declared in '/etc/icinga2/conf.d/notifications.conf', lines 19:1-19:48
      * __name = "nbmif.int.netways.de!ping4!mail-icingaadmin"
      * command = "mail-service-notification"
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 63:3-63:39
      * command_endpoint = ""
      * host_name = "nbmif.int.netways.de"
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 19:1-19:48
      * interval = 60
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 27:5-27:18
      * name = "mail-icingaadmin"
      * period = "24x7"
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 70:3-70:17
      * service_name = "ping4"
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 19:1-19:48
      * states = [ 1, 2, 4, 8 ]
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 65:3-65:45
      * templates = [ "mail-icingaadmin", "mail-service-notification" ]
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 19:1-19:48
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 62:1-62:49
      * times = null
      * type = "Notification"
      * types = [ 32, 16, 64, 8, 128, 256, 1, 2, 4 ]
        % = modified in '/etc/icinga2/conf.d/templates.conf', lines 66:3-68:57
      * user_groups = [ "icingaadmins" ]
        % = modified in '/etc/icinga2/conf.d/notifications.conf', lines 22:3-22:50
      * users = null
      * vars = null
      * zone = ""

**Attachments**

* [icinga2_notification_conditions.png](https://dev.icinga.com/attachments/download/2514/icinga2_notification_conditions.png) mfriedrich - _2015-06-18 07:50:04 +00:00_

**Changesets**

_2015-07-08 11:12:19 +00:00_ by _Napsty_ 9776ae86bd7a3f5ac7fd26f7646808acca1a6511

    Docs: Add examples for dynamic notification apply rule
    
    Reviewed and adopted a bit.
    
    refs #9443
    
    Signed-off-by: Michael Friedrich <michael.friedrich@netways.de>

_2015-07-08 11:12:48 +00:00_ by _(unknown)_ 33b273f3d9ee4b8f6af4baf978a4b616bc3a4939

    Update AUTHORS
    
    refs #9443

**Comment by dnsmichi** [comment]
Please send PRs for your own examples, if you find any.
