### ISSUE TITLE
[dev.icinga.com #9445] changelog.py: Enhance for releases

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3080]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9445

**Created by mfriedrich on 2015-06-18 11:26:21 +00:00**

Assignee: _jflach_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-04-13 10:13:54 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 0

---

config file for each project

    project: icinga2
    redmine_url: "https://dev.icinga.org"
    redmine_project: i2
    files:
      - 
        name: doc/1-about.md
        type: changelog
        marker: "##  What's New"
        links: true
        major_only: true
      -
        name: ChangeLog
        type: changelog
      -
        name: icinga2.spec
        type: version
        regex: "Version: (.*)"
      -
        name: icinga2.nuspec
        type: version
        regex: "(.*)"
      -
        name: tools/chocolateyInstall.ps1
        type: version
        regex: "Icinga2-v(.*).exe"

-   Update docs and changelog
-   Update versions
-   Check issue ids in git log history (ensure that cherry-picks are really done)
    -   If issue id is missing, print an error and exit(1)

**Comment by dnsmichi** [comment]
Obsolete, we should think about a new process for GitHub.
