### ISSUE TITLE
[dev.icinga.com #9456] Windows client w/ command_endpoint broken with $nscp_path$ and NscpPath detection

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3088]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9456

**Created by mfriedrich on 2015-06-19 11:14:25 +00:00**

Assignee: _mfriedrich_
Status: _Resolved_  (closed on _2015-06-19 13:25:03 +00:00_)
Target Version: _2.3.6_
Last Update: _2015-06-19 13:25:03 +00:00 (in Redmine)_

    Icinga Version: 2.3.5
    Backport?: Not yet backported
    Include in Changelog: 1

---

### Problem

Original post: http://www.monitoring-portal.org/wbb/index.php?page=Thread&postID=217650#post217650

* Windows client as command execution bridge and include <nscp>

* $nscp\_path$ as runtime macro is calculated on the **master** which results in "."

**** calls {{ NscpPath }}

**** which calls dirname(msi\_get\_component\_path("{5C45463A-4AE9-4325-96DB-6E239C034F93}"))

    $ sudo icinga2 console
    Icinga (version: v2.3.0-279-g7cd0077)
    <1> => dirname(msi_get_component_path("{5C45463A-4AE9-4325-96DB-6E239C034F93}"))
    "."
    <2> => 

-   The runtime macros are sent to the remote client and override the local NscpPath macro (which is set as default, but gets overridden)
-   This results in ".\\nscp.exe" being executed

    [2015-06-18 10:27:03 W. Europe Daylight Time] warning/PluginCheckTask: Check command for object 'INTSRV.INT.LAN' (PID: 0, arguments: '".\nscp.exe" "client" "-a" "show-all" "-b" "-q" "check_windows_updates"') terminated with exit code 127, output: Command ".\nscp.exe" "client" "-a" "show-all" "-b" "-q" "check_windows_updates" failed to execute: 2, "The system cannot find the file specified."

### Workaround

Set NscpPath in your constants.conf

    const NscpPath = "C:\\Program Files\\NSClient++"

**Changesets**

_2015-06-19 11:30:26 +00:00_ by _(unknown)_ 708366675c8f004def7f3c89657ed4d16c1104db

    Fix wrong nscp path w/ command_endpoint runtime macros
    
    Do not allow to override the nscp path by runtime macros.
    This causes the (linux) master to send just "." as $nscp_path$
    and the windows client ignores the local global constant NscpPath
    being overridden by the master.
    
    Only happens with command_endpoints where runtime macros are passed
    from the master to the clients.
    
    refs #9456

_2015-06-19 13:20:22 +00:00_ by _(unknown)_ c1923c9e5ad2d330677a2f8725a24b44b2d2e027

    Fix wrong nscp path w/ command_endpoint runtime macros
    
    Do not allow to override the nscp path by runtime macros.
    This causes the (linux) master to send just "." as $nscp_path$
    and the windows client ignores the local global constant NscpPath
    being overridden by the master.
    
    Only happens with command_endpoints where runtime macros are passed
    from the master to the clients.
    
    fixes #9456

_2015-06-19 13:20:51 +00:00_ by _(unknown)_ 9e663eea4b869e583680377ed4f5f6e53ae0a987

    Fix wrong nscp path w/ command_endpoint runtime macros
    
    Do not allow to override the nscp path by runtime macros.
    This causes the (linux) master to send just "." as $nscp_path$
    and the windows client ignores the local global constant NscpPath
    being overridden by the master.
    
    Only happens with command_endpoints where runtime macros are passed
    from the master to the clients.
    
    fixes #9456

---

**Relations**:

* relates [#9256](https://dev.icinga.com/issues/9256)

**Comment by Stefar77** [comment]
Problem still happening on Icinga2-v2.6.3-x86_64
How do I resolve this?

Command "c:\Program Files\ICINGA2\sbin scp.exe" client --critical load>90 --log critical --module CheckSystem --show-all --time 1m --time 5m --time 15m --warning load>80 -b -q check_cpu failed to execute: 2, "The system cannot find the file specified."
