### ISSUE TITLE
[dev.icinga.com #9561] Parser allows array for action_url|notes_url

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3124]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9561

**Created by dgoetz on 2015-07-06 09:26:11 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-07-06 09:39:28 +00:00 (in Redmine)_

    Icinga Version: 2.3.5
    Backport?: Not yet backported
    Include in Changelog: 1

---

Parser allows array for action\_url|notes\_url which results in an objecttype entry in ido.

Icinga Web 2 will support the format known from Icinga 1 (https://dev.icinga.org/issues/9196) and adding URLs in the gui directly (https://dev.icinga.org/issues/7367)

**Changesets**

_2015-07-06 09:36:14 +00:00_ by _dgoetz_ 946cf7ad90fdd88379d745c01d49f6d570bb6596

    Added documentation for multi url format.
    
    refs #9561

---

**Relations**:

* relates [#10712](https://dev.icinga.com/issues/10712)

**Comment by gunnarbeutner** [comment]
@dgoetz: Am I correct in assuming that this ticket is essentially dead? :)

**Comment by dgoetz** [comment]
Have not looked into, but I think parser is now strict enough to not allow it anymore. If you have the time to confirm, you can consider it dead. If not, I will have a look into as soon as I find some time.

**Comment by dnsmichi** [comment]
I consider it dead either way, regarding action_url and more inside the core's config. We should consider using custom attributes in the future monitoring module.
