### ISSUE TITLE
[dev.icinga.com #9568] Parser doesn't return a helpful error message in case of missing brackets

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3128]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9568

**Created by dgoetz on 2015-07-07 06:47:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-08-21 19:44:13 +00:00 (in Redmine)_

    Icinga Version: 2.3.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Parser gives not helpful error message in case of missing round braket (closing an if-condition).

Config snippet (with error):

    apply Service "Isilon Devices Status" {
    import "isilon-service"
    check_command = "check_isi_devices"
    vars.isilon_sudo = true
      if (host.vars.hardware == "x200"{
           vars.isilon_warning = ["status_healthy:(12..12)","status_replace:(0..0)","status_smartfail:(0..0)"]
           vars.isilon_critical = ["status_smartfail:(0..1)","status_not_available:(0..0)"]
      } else {
           vars.isilon_warning = ["status_healthy:(36..36)","status_replace:(0..0)","status_smartfail:(0..0)"]
           vars.isilon_critical = ["status_smartfail:(0..1)","status_not_available:(0..0)"]
        }
    assign where host.vars.os == "onefs" && host.vars.type == "node"
    }

Parser message (also not next to the file with the error, but printed after the last file in the corresponding zones directory):

    critical/config: Error: syntax error, unexpected '{'
    Location:

**Comment by dnsmichi** [comment]
That's really hard to guess from inside the parser, and add a fix. I'll close it as wont-fix.
