### ISSUE TITLE
[dev.icinga.com #9583] Add practical examples for apply expressions

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3133]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9583

**Created by mfriedrich on 2015-07-08 10:41:08 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-25 14:29:40 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

e.g.

    assign where host.vars.os in [ "a", "b", "c" ]

http://www.monitoring-portal.org/wbb/index.php?page=Thread&postID=218109#post218109
http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/language-reference#expression-operators

This should be added to the advanced topics chapter where functions and conditionals are already explained in detail.

**Changesets**

_2015-10-29 16:00:18 +00:00_ by _dgoetz_ 93488ff0262a61b20dbd9556de81c0cf57c54acf

    Advanced usage of apply for rules:
    Conditional apply based on attribute using key and value from the for loop
    
    refs #9583

**Comment by dnsmichi** [comment]
I did rephrase the patch (during feature branch cleanup), and modified the examples for some real world functionality. Thanks 👍
