### ISSUE TITLE
[dev.icinga.com #9596] Add silent installation flags to Icinga 2 Windows agent

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3141]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9596

**Created by twidhalm on 2015-07-10 10:59:21 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2015-07-13 06:06:47 +00:00_)
Target Version: _(none)_
Last Update: _2016-06-09 15:12:00 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

It's convenient to use `icinga2 node setup --ticket [ticket] --endpoint [endpoint]...` on Linux hosts to set up Agents in an unattended way. Please add the options of `icinga2 node setup` as flags to the installation package of Icinga 2 Agent on Windows so Agents can be installed unattend (given you have the correct ticket at hand)

Cheers,
Thomas

**Comment by dgoeger** [comment]
For me too. Without unattended installation i can cancle our icinga2-Agent project.
