### ISSUE TITLE
[dev.icinga.com #9619] Acknowledge: Persistent Comment is removed on status change or acknowledgement remove

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3146]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9619

**Created by Foxeronie on 2015-07-14 18:51:35 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-07 22:23:44 +00:00 (in Redmine)_

    Icinga Version: v2.3.4

---

Hi!

I checked the "Persistent Comment" box for some acknowledgement's, but the comment is always gone when the status changes or someone removes the acknowledgement.

I'm using Icinga Web 2
commit 8b4c2c459a92d1bebc6114a13cc4690e95491223
Author: Johannes Meyer &lt;johannes.meyer@netways.de&gt;
Date: Mon Jul 13 12:51:50 2015 +0200

Cheers,
Patrick

---

**Relations**:

* relates [#11035](https://dev.icinga.com/issues/11035)
* relates [#13377](https://dev.icinga.com/issues/13377)

**Comment by dnsmichi** [comment]
That's fixed in v2.7.0
