### ISSUE TITLE
[dev.icinga.com #9733] Improve the CSR signing process

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3181]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9733

**Created by hector on 2015-07-24 12:32:29 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-08-21 19:04:36 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Currently, Icinga2 masters have the ability to sign client certificates. Authorization for this operation is granted via a generated ticket, which is created in the master and needs to be done in the clients.

This process, as well as pre-signing certificates, presents some problems for automated setups where clients come and go automatically and frequently (clouds), as it require either manual interventions.

In order to allow clients with unknown hostnames to automatically report to icinga masters when they boot from pre-baked images, a more flexible CSR-signing authorization approach needs to be provided. For these there are some options:

1) Allow automatic CSR signing without tickets: if explicitally configured, a master will sign any certificate it is presented with, without the need of an authorization (ticket)

2) Allow clients to wait for certificate signing once a request is submitted to the master: in this fashion, a client will generate and send its CSR to the master, and wait until the master signs it. This could happen automatically when a client is started and detects that it is in a "slave" zone. An external process (a human or a cron job or a daemon) could request the list of pending CSRs in the master, and decide which ones to trust/sign. Once that step is complete, the client receives the signed certificate and is now able to communicate normally with the master zone. This approach is similar to Puppet, where clients would generate a certificate if it's not present, and wait (if configured) for the master to sign it during the first Puppet run.

3) Allow to configure a external authorizator for CSRs in the master. When a CSR is received, if it does not have a ticket number, it will trigger the external authorizator, which is a script that is called with the appropiate parameters (CSR, fqdn, fingerprint..). If the script returns sucessfully, the certificate is signed. Otherwise it is not.

The solutions should basically allow clients to easily start reporting to a Icinga2 master, without human intervention. In order to prevent unauthorized clients, Icinga2 should be able to easily delegate the decision on something else. An external authenticator would be able, given the CSR information and access to the right APIs, be able to decide is a client request comes from a known/trusted client in the cloud, or not.

In a first approach, current workflow seems require ugly workarounds to achieve such functionality and it is not flexible enough, which promotes other remote-check methods like SSH, SMPD, NRPE which have their own downsides but are easier to set up in cloud/automated environments.

---

**Relations**:

* relates [#10978](https://dev.icinga.com/issues/10978)

**Comment by dnsmichi** [comment]
Closed in favor of #5450.
