### ISSUE TITLE
[dev.icinga.com #9744] SSL PKI CRL distribution

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3183]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9744

**Created by mfrosch on 2015-07-27 09:06:54 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-02-24 23:51:12 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

We should think about a way to distribute the latest CRL of the CA to all Icinga 2 instances.

This should probably:

-   be enabled by default
-   should ask all connecting instances for their latest timestamp of the CRL
-   verify if the CRL is valid (signed by its CA)

**Comment by Crunsher** [comment]
Closing this as it saw this issue saw no interaction in two years and recent features improved working with the icinga PKI
