### ISSUE TITLE
[dev.icinga.com #9878] TcpSocket should listen on dual-stack per default

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3249]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9878

**Created by mfrosch on 2015-08-11 10:46:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-02-24 23:38:10 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Currently bind\_host defaults internally to 0.0.0.0, only when "::" is specified it listens to both protocols.

Question is if that might cause us problems on Windows or other non Linux platforms.

---

**Relations**:

* relates [#12245](https://dev.icinga.com/issues/12245)

**Comment by dnsmichi** [comment]
https://stackoverflow.com/a/20658285/1821348

**Comment by Al2Klimov** [comment]
At the moment Icinga listens on dual stack by default, doesn't it?

**Comment by lazyfrosch** [comment]
No it does not, `0.0.0.0` is hardcoded in ApiListener.ti

```
sudo netstat -plunt | grep 5665
tcp        0      0 0.0.0.0:5665            0.0.0.0:*               LISTEN      19248/icinga2
```

**Comment by Al2Klimov** [comment]
You're right. It seems I've accidentally fixed this while rewriting... something.

**Comment by dnsmichi** [comment]
```
$ netstat -an | grep 5665
tcp46      0      0  *.5665                 *.*                    LISTEN
```
