### ISSUE TITLE
[dev.icinga.com #9880] Add missing index for icinga_comments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3251]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9880

**Created by mfrosch on 2015-08-11 11:02:24 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-11 08:46:56 +00:00 (in Redmine)_

---

When having a lot of downtimes or comments inside Icinga, the update query on reload can get problematic, since it is using an non-optimal index.

We should add the following index:

MySQL:

    ALTER TABLE `icinga_comments` ADD INDEX `comment_instance_time` ( `instance_id`, `comment_time`,`internal_comment_id`);

PostgreSQL:

    CREATE INDEX comment_instance_time
      ON icinga_comments
      (instance_id, comment_time, internal_comment_id);

**Comment by dnsmichi** [comment]
That's described in the combined issue already.
