### ISSUE TITLE
[dev.icinga.com #9889] Add runtime macro for all contacts that are being notified

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3258]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9889

**Created by mwaldmueller on 2015-08-12 09:45:45 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-01-22 16:30:36 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Add runtime macro for all contacts that are being notified like NOTIFICATIONRECIPIENTS in Icinga 1 (http://docs.icinga.org/latest/en/macrolist.html#macrolist-notificationrecipients).

**Comment by dnsmichi** [comment]
In the event of a notification, there's only one user object available, and you can get it with `$user.name$`. We don't do any kind of notified users pre-calculation here unfortunately. After a specific notification happened, you may fetch the notified users from `/v1/objects/notifications`.
