### ISSUE TITLE
[dev.icinga.com #9918] endless loop at log() or JSON::encode()

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3270]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9918

**Created by ggzengel on 2015-08-16 14:25:21 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-05-11 07:43:42 +00:00 (in Redmine)_

    Icinga Version: V2.3.8
    Backport?: Not yet backported
    Include in Changelog: 1

---

On linked lists with prev and next elements, log() and JSON::encode() will run endless.
Small solution: stop after x cycles.
Bigger solution: remember pointer pair (self,next) of traversed objects.

    one={ }
    other={ }
    one.next=other
    other.prev=one

    log(other)
    log("never been here.")

**Comment by dnsmichi** [comment]
Loop detection in hand-crafted configuration is pretty hard, I'd say we'll leave it as is.

**Comment by ggzengel** [comment]
> Small solution: stop after x cycles.
Better than an endless running unusable system.
