### ISSUE TITLE
[dev.icinga.com #9922] icinga2 stops on SIGHUP while reloading

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3273]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9922

**Created by lbetz on 2015-08-17 07:35:47 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-09-05 10:56:42 +00:00 (in Redmine)_

    Icinga Version: 2.3.8
    Backport?: Not yet backported
    Include in Changelog: 1

---

After a a reload icinga2 reads and processes the configuration. In this time range if you send another HUP, the icinga2 process crashes. At this time nothing is logged.

**Comment by dnsmichi** [comment]
Never seen that in recent versions, sorry for the late response.
