### ISSUE TITLE
[dev.icinga.com #9923] Take time differences between icinga2 instances

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3274]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9923

**Created by lbetz on 2015-08-17 07:44:54 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-03-10 21:22:42 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

In a setup using several icinga2 instance like satellites or agents it's important to have the same time on all involved parties. Maybe we can use the heartbeat to calculate the time difference and take the difference to schedule all time sensitive things correctly?

---

**Relations**:

* relates [#9923](https://dev.icinga.com/issues/9923)

**Comment by marcofl** [comment]
Might not be related to this at all, but I think the bigger issue is, that when you have servers with a time drift into the future, then correct the time (by fixing NTP) and then end up with all check results being "ignored" on the satellite or master. also the client seems to not accept any "check now" commands anymore. I could not find a way to "reset" this.

**Comment by marcofl** [comment]
@dnsmichi  should I open a new issue for the "time in future breaks further check results" issue?

**Comment by htriem** [comment]
NTP is the way to go. Other implementations are currently not considered.
