### ISSUE TITLE
[dev.icinga.com #9964] icinga2 node update should not write config for blacklisted zones/host

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3300]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9964

**Created by henti on 2015-08-19 08:23:22 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-14 13:05:55 +00:00 (in Redmine)_

    Icinga Version: 2.3.8
    Backport?: Not yet backported
    Include in Changelog: 1

---

This looks like a possible regression of [\#8211](https://dev.icinga.com/issues/8211) or at least an edge case.

I've blacklist two hosts on my setup while users do testing which involve changing dates on the hosts which causes issue on monitoring.

    icinga2 node blacklist add --zone "*" --host "dev-qua-za-ff03.domain.com"
    icinga2 node blacklist add --zone "*" --host "dev-qua-za-ff05.domain.com"

Check the blacklist is in place.

    root@prd-qua-za-mon:/etc/icinga2# icinga2 node blacklist list
    Listing all blacklist entries:
    blacklist filter for Node: '*' Host: '*' Service: 'apt'.
    blacklist filter for Node: '*' Host: '*' Service: 'ping6'.
    blacklist filter for Node: '*' Host: '*' Service: 'ping4'.
    blacklist filter for Node: '*' Host: '*' Service: 'cpu'.
    blacklist filter for Node: '*' Host: 'dev-qua-za-ff03.domain.com' Service: ''.
    blacklist filter for Node: '*' Host: 'dev-qua-za-ff05.domain.com' Service: ''.

Noticed the services addition. Not sure if this is correct.

icinga2 node update-config creates the host, endpoint and zone files

    Adding host 'dev-qua-za-ff03.domain.com'
        check_command = "cluster-zone"
        import = [ "satellite-host" ]
    Adding endpoint 'dev-qua-za-ff03.domain.com'
    Adding zone 'dev-qua-za-ff03.domain.com'
        endpoints = [ "dev-qua-za-ff03.domain.com" ]
        parent = "master"
    Adding host 'dev-qua-za-ff05.domain.com'
        check_command = "cluster-zone"
        import = [ "satellite-host" ]
    Adding endpoint 'dev-qua-za-ff05.domain.com'
    Adding zone 'dev-qua-za-ff05.domain.com'
        endpoints = [ "dev-qua-za-ff05.domain.com" ]
        parent = "master"

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Relations**:

* relates [#9964](https://dev.icinga.com/issues/9964)

**Comment by dnsmichi** [comment]
Closing in favour of #4799.
