### ISSUE TITLE
[dev.icinga.com #9990] Source installation: icinga2 crashes with wrong permissions on /var/cache/icinga2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3317]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9990

**Created by elabedzki on 2015-08-25 07:22:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-01-22 15:02:20 +00:00 (in Redmine)_

    Icinga Version: 2.3.9
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi guys,

it's me, for testing purposes i've build my own docker container with a full icinga2 stack on it, so i can use it as a labor or test station.

But there is a nasty bug on the 'make install' target, he doesn't correct the right's on it's own install location/directories so when you did a run without changes on directories like '/usr/local/icinga2/var/cache/icinga2' ( where the owner is root:stuff at this time ) then icinga2 will crash internally without a usefull message or a exception stack or somthing else, it prints 'Abort.' that's all.

Gunnar helped me to debug that phenomenon, so i attached that two images.

My build ist from the current master branch.

Kind regards
Enrico

**Attachments**

* [icinga2-crash-insuffient-rights-on-bootstrap.png](https://dev.icinga.com/attachments/download/2640/icinga2-crash-insuffient-rights-on-bootstrap.png) elabedzki - _2015-08-25 07:07:45 +00:00_
* [icinga2-crash-with-fixed-rights-on-var-dir-.png](https://dev.icinga.com/attachments/download/2641/icinga2-crash-with-fixed-rights-on-var-dir-.png) elabedzki - _2015-08-25 07:07:45 +00:00_

**Comment by dnsmichi** [comment]
There is a patch in git master for that.
