### ISSUE TITLE
[dev.icinga.com #10000] Removing zones crash remote icinga instances

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3323]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10000

**Created by lbetz on 2015-08-26 11:41:24 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-14 14:49:20 +00:00 (in Redmine)_

    Icinga Version: 2.3.9
    Backport?: Not yet backported
    Include in Changelog: 1

---

Remove a zone on the config (master) server hasn't an effect to remote instances with accept\_config. The zone is still there in /var/lib/icinga2/api/zones. Please remove it automatically.

**Attachments**

* [signature.asc](https://dev.icinga.com/attachments/download/2655/signature.asc) lbetz - _2015-08-31 20:21:03 +00:00_

---

**Relations**:

* relates [#10000](https://dev.icinga.com/issues/10000)
* relates [#10000](https://dev.icinga.com/issues/10000)
* relates [#10000](https://dev.icinga.com/issues/10000)
* relates [#10000](https://dev.icinga.com/issues/10000)
* relates [#10000](https://dev.icinga.com/issues/10000)

**Comment by dnsmichi** [comment]
I've found the working issue for cluster config sync staging with #4354. I'm closing here in favour of this TODO.
