### ISSUE TITLE
[dev.icinga.com #10047] API action to schedule downtime for hosts and their respective child hosts

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3344]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10047

**Created by schaefus on 2015-08-31 08:39:19 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-09-07 13:30:38 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

There was a bug &lt;https://dev.icinga.org/issues/7337&gt; which was closed.

The "SCHEDULE\_AND\_PROPAGATE\_TRIGGERED\_HOST\_DOWNTIME" and "SCHEDULE\_AND\_PROPAGATE\_HOST\_DOWNTIME" external commands aren´t there any longer. It would be nice to have an API action in 2.4 to schedule downtime for hosts and their childs.

**Comment by dnsmichi** [comment]
This has been implemented with the latest release.
