### ISSUE TITLE
[dev.icinga.com #10054] clients should send their config to master which executes checks

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3350]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10054

**Created by ziaunys on 2015-08-31 18:49:55 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2017-01-14 13:08:53 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Maybe I am doing something wrong, but it looks like that the update-config command won't update objects where the parameters may have changed. For example, on the client config, if I update a service objects' "retry\_interval" to a different value and reload the client, it will never update on the parent node after running "icinga2 node update-config" unless I completely remove the config file. This is a problem for me especially since I already have to solve the problem of automatically syncing configs from clients. If this doesn't work, I'll have to use a different solution for syncing configs such as exported resources in Puppet which are much slower. I would really love if there was an option to have configs sync automatically. I saw there was another ticket requesting that feature, but it looks like it was closed so I'm not sure if there are any plans to add it.

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Comment by dnsmichi** [comment]
#4799

**Comment by Crunsher** [comment]
With the deprecation/future removal of the node command - is this still relevant?

**Comment by Crunsher** [comment]
Closing with @gunnarbeutner approval
