### ISSUE TITLE
[dev.icinga.com #10062] IDO:  Create redundant bidirectional index on host/servicegroup tables

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3356]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10062

**Created by tgelf on 2015-09-01 12:26:47 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-11 08:46:48 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

It's often hard for developers to build joins according available indexes, because of multiple reasons (too many layers of abstraction, not enough DB knowledge or even pure ignorance :p ). I'd opt for creating the grpmbrs\_oid\_gid index twice, oid\_gid and gid\_oid. This is redundant but helps to speed up joins in any direction.

---

**Relations**:

* relates [#10062](https://dev.icinga.com/issues/10062)

**Comment by dnsmichi** [comment]
Not relevant anymore, thanks though.
