### ISSUE TITLE
[dev.icinga.com #10063] IDO: Use CI collation on search fields (alias, display_name)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3358]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10063

**Created by tgelf on 2015-09-01 12:29:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-18 13:58:49 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

alias and display\_name are non-unique fields, there solely purpose are display reasons - and they are also often involved in search requests. Search is always case insensitive, so instead of casting data at search time (expensive) we should do so at index time (cheap).

**Comment by dnsmichi** [comment]
Not relevant anymore, thanks though.
