### ISSUE TITLE
[dev.icinga.com #10064] IDO: icinga_comments and icinga_acknowledgements have no object_id index

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3359]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10064

**Created by tgelf on 2015-09-01 12:30:48 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-11 08:46:49 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

That's the most relevant index, as comments and acknowledgements are rarely if ever queried without a relation to their object.

**Comment by dnsmichi** [comment]
Not relevant anymore, thanks though.
