### ISSUE TITLE
[dev.icinga.com #10065] IDO: icinga_customvariables lacks important index

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3360]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10065

**Created by tgelf on 2015-09-01 12:32:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-18 13:58:50 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

An index on (object\_id, varname) is missing. This doesn't really hurt as we usually select only from icinga\_customvariablestatus. Nonetheless, this should be fixed to have both tables showing similar performance.

**Comment by dnsmichi** [comment]
Not relevant anymore, thanks though.
