### ISSUE TITLE
[dev.icinga.com #10067] IDO: drop a bunch of indexes on icinga_{host,service}status

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3362]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10067

**Created by tgelf on 2015-09-01 12:36:32 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-11 08:46:51 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Namely indexes like those:

      KEY "hoststatus_stat_upd_time_idx" ("status_update_time"),
      KEY "hoststatus_check_type_idx" ("check_type"),
      KEY "hoststatus_notif_enabled_idx" ("notifications_enabled"),
      KEY "hoststatus_problem_ack_idx" ("problem_has_been_acknowledged"),
      KEY "hoststatus_act_chks_en_idx" ("active_checks_enabled"),
      KEY "hoststatus_pas_chks_en_idx" ("passive_checks_enabled"),
      KEY "hoststatus_event_hdl_en_idx" ("event_handler_enabled"),
      KEY "hoststatus_flap_det_en_idx" ("flap_detection_enabled"),
      KEY "hoststatus_is_flapping_idx" ("is_flapping"),
      KEY "hoststatus_p_state_chg_idx" ("percent_state_change"),
      KEY "hoststatus_latency_idx" ("latency"),
      KEY "hoststatus_ex_time_idx" ("execution_time"),
      KEY "hoststatus_sch_downt_d_idx" ("scheduled_downtime_depth")

I'm aware of no single query able to make any use of those, similar for servicesstatus. Those two tables get by far the most write requests while Icinga is running, modifying so many indices again and again really hurts.

**Comment by dnsmichi** [comment]
Not relevant anymore, thanks though.
