### ISSUE TITLE
[dev.icinga.com #10068] IDO: index display_name and alias

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3363]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10068

**Created by tgelf on 2015-09-01 12:37:55 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-11 08:46:52 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

We should at least partially index those tables, they are often involved in search requests. Not sure whether it makes sense to combine that index with object\_id.

---

**Relations**:

* relates [#10068](https://dev.icinga.com/issues/10068)

**Comment by dnsmichi** [comment]
Not relevant anymore, thanks though.
