### ISSUE TITLE
[dev.icinga.com #10072] IDO: indices on icinga_{host,service}dependencies make no sense

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3367]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10072

**Created by tgelf on 2015-09-01 14:13:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-11 08:46:55 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

No idea what they could be useful for. Has low impact, as most frontends are afaik not using those tables.

**Comment by dnsmichi** [comment]
Not relevant anymore, thanks though.
