### ISSUE TITLE
[dev.icinga.com #10076] Icinga Studio: Properly detect wxGTK(3) devel packages on modern systems

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3371]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10076

**Created by mfriedrich on 2015-09-01 19:48:34 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-05-25 03:16:29 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Fedora 22 uses wxGTK3-devel for example, and this ugly symlink to make it work.

    $ sudo ln -s /usr/bin/wx-config-3.0 /usr/bin/wx-config

**Comment by dnsmichi** [comment]
Icinga Studio won't receive updates soon, it'll stay "as is" for now. I wouldn't bother with CMake here, but leave it to packagers.
