### ISSUE TITLE
[dev.icinga.com #10087] Icinga Studio: Check the master's certificate on connect

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3376]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10087

**Created by mfriedrich on 2015-09-03 14:39:58 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-09-03 14:39:58 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

**Comment by dnsmichi** [comment]
Icinga Studio has been removed.
