### ISSUE TITLE
[dev.icinga.com #10120] Allow addition of global zone with node wizard / CLI commands

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3388]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10120

**Created by twidhalm on 2015-09-08 11:57:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-08-08 15:45:58 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi!

Please add an option to add one or more global zones with the node wizard or the corresponding `icinga2 node` cli commands.

The wizard is great for creating the communication between master and agent but adding the global zone is still something to be done manually. You could save us this extra step by a wizard question about global zones.

Cheers,
Thomas

**Attachments**

* [0001-Added-global-zone-questions-to-node-wizard.patch](https://dev.icinga.com/attachments/download/3056/0001-Added-global-zone-questions-to-node-wizard.patch) AountAgatha - _2016-02-03 02:13:51 +00:00_
* [0002-Added-global-zone-questions-to-node-wizard.patch](https://dev.icinga.com/attachments/download/3086/0002-Added-global-zone-questions-to-node-wizard.patch) AountAgatha - _2016-02-10 20:09:35 +00:00_

**Changesets**

_2016-08-16 16:03:25 +00:00_ by _AountAgatha_ f82d9cdfd60d050d69ab4b2033874685e144aa30

    Add global zone parameter to node wizard/setup cli commands
    
    Node wizard in satellite configuration mode did not ask for
    global zones which had to be inserted manually into the file
    by the user. Functionality was now added.
    
    refs #10120
    
    Signed-off-by: Michael Friedrich <michael.friedrich@netways.de>

---

**Relations**:

* relates [#10120](https://dev.icinga.com/issues/10120)
* duplicates [#10120](https://dev.icinga.com/issues/10120)

**Comment by Crunsher** [comment]
Is still relevant? The topic changed from "global zone creation in wizard", which makes no sense to me tbh, to "multiple global zones"

**Comment by Crunsher** [comment]
With 2.7 we create a global zone by default
