### ISSUE TITLE
[dev.icinga.com #10131] cluster is corrupted, when nr of nodes > 2 in a master/master cluster

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3396]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10131

**Created by penyilas on 2015-09-10 16:16:07 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2015-10-17 01:31:39 +00:00_)
Target Version: _(none)_
Last Update: _2016-01-18 13:46:32 +00:00 (in Redmine)_

    Icinga Version: 2.3.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

I've created a test cluster with virtual machines to reproduce the problem.
The layout:
2master (zone: master)
3satellite (zone: icinga) (with 2 satellites, cluster is working properly)

If you're run this cluster, here's an output:
master1:
Node 'slave3' (last seen: Thu Sep 10 17:07:16 2015)
Node 'slave1' (last seen: Thu Sep 10 17:07:19 2015)
Node 'slave2' (last seen: Thu Sep 10 17:07:17 2015)
Node 'master2' (last seen: Thu Sep 10 17:07:14 2015)

master2:
Node 'slave3' (last seen: Thu Sep 10 17:07:16 2015)
Node 'slave1' (last seen: Thu Sep 10 17:07:19 2015)
Node 'master1' (last seen: Thu Sep 10 17:07:16 2015)
Node 'slave2' (last seen: Thu Sep 10 17:07:17 2015)

slave1:
Node 'slave3' (last seen: Thu Sep 10 17:07:16 2015)
Node 'slave2' (last seen: Thu Sep 10 17:07:17 2015)

slave2:
Node 'slave3' (last seen: Thu Sep 10 17:07:16 2015)
Node 'slave1' (last seen: Thu Sep 10 17:07:19 2015)

slave3:
Node 'slave2' (last seen: Thu Sep 10 17:07:17 2015)

from this point, slave3 doesn't get updates from slave1 (check results, commands, etc)

If I add manually the node to slave3, it doesn't updates

I think, it's related to: https://dev.icinga.org/issues/8833 (and my old) https://dev.icinga.org/issues/9803

If the satellite zone has only 2 members, the cluster works properly. If you increase the number of nodes, the problem still exists (at least with 4 nodes, that's my production.

I've attached the whole /etc/icinga2 directory contents, if you need to check the syntax/configs etc...

**Attachments**

* [conf-master1.tgz](https://dev.icinga.com/attachments/download/2701/conf-master1.tgz) penyilas - _2015-09-10 16:14:47 +00:00_ - _/etc/icinga2 contents_
* [conf-master2.tgz](https://dev.icinga.com/attachments/download/2702/conf-master2.tgz) penyilas - _2015-09-10 16:14:47 +00:00_ - _/etc/icinga2 contents_
* [conf-slave1.tgz](https://dev.icinga.com/attachments/download/2703/conf-slave1.tgz) penyilas - _2015-09-10 16:14:48 +00:00_ - _/etc/icinga2 contents_
* [conf-slave3.tgz](https://dev.icinga.com/attachments/download/2704/conf-slave3.tgz) penyilas - _2015-09-10 16:14:48 +00:00_ - _/etc/icinga2 contents_
* [conf-slave2.tgz](https://dev.icinga.com/attachments/download/2705/conf-slave2.tgz) penyilas - _2015-09-10 16:14:48 +00:00_ - _/etc/icinga2 contents_
* [master2-debug.log.tgz](https://dev.icinga.com/attachments/download/2708/master2-debug.log.tgz) penyilas - _2015-09-11 14:24:40 +00:00_
* [master1-debug.log.tgz](https://dev.icinga.com/attachments/download/2709/master1-debug.log.tgz) penyilas - _2015-09-11 14:24:40 +00:00_
* [slave2-debug.log.tgz](https://dev.icinga.com/attachments/download/2710/slave2-debug.log.tgz) penyilas - _2015-09-11 14:24:41 +00:00_
* [slave1-debug.log.tgz](https://dev.icinga.com/attachments/download/2711/slave1-debug.log.tgz) penyilas - _2015-09-11 14:24:41 +00:00_
* [slave3-debug.log.tgz](https://dev.icinga.com/attachments/download/2712/slave3-debug.log.tgz) penyilas - _2015-09-11 14:24:41 +00:00_
* [workqueue.PNG](https://dev.icinga.com/attachments/download/3003/workqueue.PNG) sudeshkumar - _2016-01-14 14:57:18 +00:00_

---

**Relations**:

* relates [#10365](https://dev.icinga.com/issues/10365)

**Comment by iDemonix** [comment]
+1
