### ISSUE TITLE
[dev.icinga.com #10179] Livestatus: Problem with stats min operator

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3410]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10179

**Created by sni on 2015-09-21 08:26:47 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-12 07:37:56 +00:00 (in Redmine)_

    Icinga Version: r2.3.8-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

When doing a time filter on the log table only a few combinations actually work.
Filtering by greater than does not work most of the times, ex.:

        echo -e "GET log\nColumns: type time contact_name message\nFilter: time >1042819123 \n\n" | unixcat tmp/run/live

-&gt; does not work

Except with very low numbers like:

        echo -e "GET log\nColumns: type time contact_name message\nFilter: time > 0\n\n" | unixcat tmp/run/live

-&gt; works

A funny workaround with negate seems to work:

        echo -e "GET log\nColumns: type time contact_name message\nFilter: time < 1442819123\nNegate:\n" | unixcat tmp/run/live

-&gt; works

**Comment by mboden** [comment]
I think I have the same problem. I see no alert logs what so ever in thruk. Using icinga 2.6.0.

**Comment by dnsmichi** [comment]
Short heads-up - we're not working on Livestatus issues. Please be so kind and look into fixing this and sending in a PR.

**Comment by gitmopp** [comment]
It seems like the Livestatus module has some problems which will not be fixed.
As a workaround for thruk you can use
`# thruk -a logcacheupdate -b Icinga2 --local /var/log/icinga2/compat/icinga.log`
Of course for this you have to configure https://www.thruk.org/documentation/logfile-cache.html

**Comment by gitmopp** [comment]
I' m not able to compile and debug the code. Maybe someone has a working build environment and can check the file lib/livestatus/minaggregator.cpp
This is the code from the file. It is more or less the same as for maxaggregator which works:
```
	Column column = table->GetColumn(m_MinAttr);

	Value value = column.ExtractValue(row);

	if (value < m_Min)
		m_Min = value;
```
Either `table->GetColumn(m_MinAttr);` does not contain any data or it always returns at least one time a value of 0, which will set m_Min to 0 `(if (value < m_Min))`

**Comment by dnsmichi** [comment]
Any specific distribution you prefer to getting a quick development environment?

**Comment by gitmopp** [comment]
I tested the fix #5316 on openSUSE and it seems to work.

**Comment by dnsmichi** [comment]
Can you please share your tests and outputs? I'd like to verify the fix before merging it.

**Comment by gitmopp** [comment]
What kind of tests do you expect?
I don' t have an unit test for it.
```
# echo -e "GET log\nStats: min time\nStats: max time\n\n" | nc 0 6558
1495177848;1497364274
# echo -e "GET hosts\nStats: min last_check\nStats: max last_check\nStats: avg last_check\n\n" | nc 0 6558
1497364420;1497364715;1497364569.132597

# echo -e "GET hosts\nStats: min last_check\nStats: max last_check\n"  | nc localhost 6558
1497364440;1497364721

# echo -e "GET services\nStats: min last_check\nStats: max last_check\nStats: avg last_check\n\n" | nc 0 6558
1497361354;1497364778;1497364383.740413

```

**Comment by dnsmichi** [comment]
Just that output, thanks :) Sometimes people just say "yeah, tested it" and then you'll recognize that it got worse after merging the patch.
