### ISSUE TITLE
[dev.icinga.com #10208] Eventhandler trigger on all endpoints in high available zone 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3431]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10208

**Created by dgoetz on 2015-09-24 07:54:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-03-18 17:09:10 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Eventhandlers are triggerd on all endpoints in a high available setup.
We see an Eventhandler command triggered on both systems in the high available zone. First it is triggerd on the check source than after replication on the other endpoint.
Worst case scenario the eventhandler restarts a problematic service twice with some seconds delay which could cause more problems than fix!

Plattform is RHEL 7 64 bit, Icinga 2 Release 2.3.10 from packages.icinga.org

**Attachments**

* [node1-debug.log](https://dev.icinga.com/attachments/download/2730/node1-debug.log) dgoetz - _2015-09-25 07:28:08 +00:00_
* [node2-debug.log](https://dev.icinga.com/attachments/download/2731/node2-debug.log) dgoetz - _2015-09-25 07:28:39 +00:00_

**Comment by leeclemens** [comment]
I'm not sure why this is marked low/enhancement, using an event command that performs a system restart with some timeout could likely reboot the server twice. This would be completely unexpected behavior. This would go the same for any event_command restarting a service (think services that take a while to start up like databases)...second execution would knock it back down.

"triggered locally when the check result is processed". I thought checks were scheduled between cluster members (forgive me if I'm wrong), so the same check result would only be processed by one cluster member for any given check execution? If so, this wouldn't be a problem.

Ref: https://lists.icinga.org/pipermail/icinga-users/2017-February/011844.html

**Comment by leeclemens** [comment]
tag: @dgoetz @dnsmichi

**Comment by MarcusCaepio** [comment]
Hi all,
is this still not fixed?

**Comment by Thomas-Gelf** [comment]
@MarcusCaepio: i talked to @dgoetz, as far as he knows this isn't fixed.

**Comment by dnsmichi** [comment]
I've got the same question from @MarcusCaepio and I believe no-one looked into this yet. That's what I've told him at OSMC.

**Comment by dnsmichi** [comment]
Since questions came up why no-one looked into this for a long period of time: Event handlers were ported from 1.x where no cluster or HA feature was yet implemented. Event handlers in the current feature-set would need a re-design, especially when it comes to command_endpoint enabled clients (see #5658 for details) or how parameters can be passed. That is the reason why I've tagged this as a feature a while ago.

In terms of the problem itself, each instance determines whether to execute event handlers upon received check results in an HA-enabled zone. The object authority for checkable objects can be determined by the `paused` attribute.

## Tests

### Configuration

```
mbmif /usr/local/tests/icinga2/master-slave (master *+) # cat icinga2a/etc/icinga2/zones.d/master/hosts.conf
object Host "testmaster" {
  check_command = "dummy"
  address = "127.0.0.1"
}
object Host "testmaster1" {
  check_command = "dummy"
}
object Host "testmaster2" {
  check_command = "random"
  event_command = "testevent"
  check_interval = 1s
  retry_interval = 1s
}
object EventCommand "testevent" {
  command = [ "/usr/bin/true" ]
}
```

```
michi@mbmif ~/coding/icinga/icinga2 (fix/eventhandler-ha-zone *) $ curl -k -s -u root:icinga 'https://localhost:7000/v1/objects/hosts/testmaster2?attrs=paused&attrs=name&pretty=1'
{
    "results": [
        {
            "attrs": {
                "name": "testmaster2",
                "paused": false
            },
            "joins": {

            },
            "meta": {

            },
            "name": "testmaster2",
            "type": "Host"
        }
    ]
}

michi@mbmif ~/coding/icinga/icinga2 (fix/eventhandler-ha-zone *) $ curl -k -s -u root:icinga 'https://localhost:8000/v1/objects/hosts/testmaster2?attrs=paused&attrs=name&pretty=1'
{
    "results": [
        {
            "attrs": {
                "name": "testmaster2",
                "paused": true
            },
            "joins": {

            },
            "meta": {

            },
            "name": "testmaster2",
            "type": "Host"
        }
    ]
}
```

## Fix

### Git Master

icinga2a
```
[2018-05-11 12:48:12 +0200] notice/Checkable: State Change: Checkable 'testmaster2' hard state change from DOWN to UP detected.
[2018-05-11 12:48:12 +0200] notice/Checkable: Executing event handler 'testevent' for service 'testmaster2'
```

icinga2b
```
[2018-05-11 12:48:12 +0200] notice/Checkable: State Change: Checkable 'testmaster2' hard state change from DOWN to UP detected.
[2018-05-11 12:48:12 +0200] notice/Checkable: Executing event handler 'testevent' for service 'testmaster2'
```

### Applied

icinga2a

```
[2018-05-11 12:41:25 +0200] notice/Checkable: State Change: Checkable 'testmaster2' soft state change from DOWN to DOWN detected.
[2018-05-11 12:41:25 +0200] notice/Checkable: Executing event handler 'testevent' for checkable 'testmaster2'
```

icinga2b
```
[2018-05-11 12:41:25 +0200] notice/Checkable: State Change: Checkable 'testmaster2' soft state change from DOWN to DOWN detected.
[2018-05-11 12:41:25 +0200] critical/Checkable: Skipping event handler for HA-paused checkable 'testmaster2'
Context:
	(0) Executing event handler for object 'testmaster2'
```

Note: The critical logging will be turned into notice inside the patch.

### Single instance test

```
object Zone "master" {
  //endpoints = [ "icinga2a", "icinga2b" ]
  endpoints = [ "icinga2a" ]
}
```

```
[2018-05-11 12:54:08 +0200] notice/Checkable: State Change: Checkable 'testmaster2' soft state change from UP to DOWN detected.
[2018-05-11 12:54:08 +0200] notice/Checkable: Executing event handler 'testevent' for checkable 'testmaster2'
```

There won't be any 2.8.x minor release anymore, and since this change also requires further tests with the snapshot packages, I'll schedule this for 2.9 as an exception (actually the issue set is frozen).
