### ISSUE TITLE
[dev.icinga.com #10244] certificate verify against multiple ca certificates 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3453]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10244

**Created by lbetz on 2015-09-29 14:20:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-18 17:05:23 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Autosigning is a nice feature, but isn't usable in distributed monitoring environment. One CA on the master isn't enough. Agents must signed against an signing CA on a satellite, because in general there is no permission to connect to the master's CA.

**Comment by dnsmichi** [comment]
I'm closing this in favour of the CA proxy established with 2.8.
