### ISSUE TITLE
[dev.icinga.com #10357] Stacktrace on Command Pipe Error

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3483]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10357

**Created by zeuz on 2015-10-13 15:46:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-10-17 01:35:43 +00:00 (in Redmine)_

    Icinga Version: 2.3.10-1.el7.centos
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

I was surprised to see a stack-trace when pushing commands to non-existent services:

(log level: severity = "information")

\[root@icinga ~\]\# tail -f /var/log/icinga2/icinga2.log
\[2015-10-13 17:33:36 +0200\] information/ExternalCommandListener: Executing external command: \[1444750416.515721762\] PROCESS\_SERVICE\_CHECK\_RESULT;swi-cb03-97;LinkState;1;Interface GigabitEthernet1/1/13 went up
\[2015-10-13 17:33:36 +0200\] warning/ExternalCommandListener: External command failed.Error: Cannot process passive service check result for non-existent service 'LinkState' on host 'swi-cb03-97'
(0) icinga2: void boost::throw\_exception<boost::exception_detail::error_info_injector<std::invalid_argument> &gt;(boost::exception\_detail::error\_info\_injector<std::invalid_argument> const&) (+0xe9) \[0x417dc9\]
(1) libbase.so: void boost::exception\_detail::throw\_exception\_<std::invalid_argument>(std::invalid\_argument const&, char const**, char const**, int) (+0x6d) \[0x2b944fdfa11d\]
(2) libicinga.so: icinga::ExternalCommandProcessor::ProcessServiceCheckResult(double, std::vector<icinga::String, std::allocator<icinga::String> &gt; const&) (+0x51b) \[0x2b9456ea511b\]
(3) libicinga.so: icinga::ExternalCommandProcessor::Execute(double, icinga::String const&, std::vector<icinga::String, std::allocator<icinga::String> &gt; const&) (+0x1f0) \[0x2b9456e8e830\]
(4) libicinga.so: icinga::ExternalCommandProcessor::Execute(icinga::String const&) (+0x1f3) \[0x2b9456e8f253\]
(5) libcompat.so: icinga::ExternalCommandListener::CommandPipeThread(icinga::String const&) (+0x23c) \[0x2b945789be9c\]
(6) libboost\_thread-mt.so.1.53.0: <unknown function> (+0xd24a) \[0x2b944f37124a\]
(7) libpthread.so.0: <unknown function> (+0x7df5) \[0x2b9452726df5\]
(8) libc.so.6: clone (+0x6d) \[0x2b945224c1ad\]

The message on line 2 is correct (there is no service "LinkState" of host "swi-cb03-97"), but I'm somehow surprised to see a stack-trace. Is this default behavior, or is there some hidden problem?

Opinions?

**Comment by dnsmichi** [comment]
The proper fix would be to change all exception locations. Since this isn't doable in a reasonable amount of time for legacy compat, we've agreed on hiding the exception stack trace for the warning log level, thus adding a full verbose one for the notice level.

**Comment by dnsmichi** [comment]
```
echo "[`date +%s`] PROCESS_SERVICE_CHECK_RESULT;abc;def;2;test output" >> /usr/local/icinga2/var/run/icinga2/cmd/icinga2.cmd
```

```
[2017-02-08 16:10:09 +0100] warning/ExternalCommandListener: External command failed: Error: Cannot process passive service check result for non-existent service 'def' on host 'abc'
```
