### ISSUE TITLE
[dev.icinga.com #10381] ScheduledDowntime not being triggered

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3496]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10381

**Created by henti on 2015-10-16 07:04:44 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:58:44 +00:00 (in Redmine)_

    Icinga Version: v2.3.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

I have a 2 servers that needs to do a database reload daily. This will affect our sybase\_asa\_12 and apache checks, so I created the following downtime to set the sybase and apache server on hq-asa.gfs.domain.com and the sybase service on aclsms.gfs.domain.com down between 00h00 and 03h30. the expectation was for the services to go down, but not notify, however we still get notifications. Below is the config breakdown.

    apply ScheduledDowntime "aclsms-reload" to Service {
      author = "support"
      comment = "ACLSMS DB reload"

      ranges = {
        monday = "00:00-03:30"
        tuesday = "00:00-03:30"
        wednesday = "00:00-03:30"
        thursday = "00:00-03:30"
        friday = "00:00-03:30"
        saturday = "00:00-03:30"
        sunday = "00:00-03:30"
      }

      assign where host.name ==  "hq-asa.gfs.domain.com" && service.name == "sybase_asa_12"
      assign where host.name ==  "hq-asa.gfs.domain.com" && service.name == "apache2"
      assign where host.name ==  "aclsms.gfs.domain.com" && service.name == "sybase_asa_12"
    }

reload and objects show.

    Object 'aclsms.gfs.domain.com!sybase_asa_12!aclsms-reload' of type 'ScheduledDowntime':
      % declared in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * __name = "aclsms.gfs.domain.com!sybase_asa_12!aclsms-reload"
      * author = "support"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 37:3-37:20
      * comment = "ACLSMS DB reload"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 38:3-38:30
      * duration = 0
      * fixed = true
      * host_name = "aclsms.gfs.domain.com"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * name = "aclsms-reload"
      * ranges
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 40:3-48:3
        * friday = "00:00-03:30"
        * monday = "00:00-03:30"
        * saturday = "00:00-03:30"
        * sunday = "00:00-03:30"
        * thursday = "00:00-03:30"
        * tuesday = "00:00-03:30"
        * wednesday = "00:00-03:30"
      * service_name = "sybase_asa_12"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * templates = [ "aclsms-reload" ]
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * type = "ScheduledDowntime"
      * vars = null
      * zone = "aclsms.gfs.domain.com"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50

    Object 'hq-asa.gfs.domain.com!apache2!aclsms-reload' of type 'ScheduledDowntime':
      % declared in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * __name = "hq-asa.gfs.domain.com!apache2!aclsms-reload"
      * author = "support"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 37:3-37:20
      * comment = "ACLSMS DB reload"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 38:3-38:30
      * duration = 0
      * fixed = true
      * host_name = "hq-asa.gfs.domain.com"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * name = "aclsms-reload"
      * ranges
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 40:3-48:3
        * friday = "00:00-03:30"
        * monday = "00:00-03:30"
        * saturday = "00:00-03:30"
        * sunday = "00:00-03:30"
        * thursday = "00:00-03:30"
        * tuesday = "00:00-03:30"
        * wednesday = "00:00-03:30"
      * service_name = "apache2"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * templates = [ "aclsms-reload" ]
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * type = "ScheduledDowntime"
      * vars = null
      * zone = "hq-asa.gfs.domain.com"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50

    Object 'hq-asa.gfs.domain.com!sybase_asa_12!aclsms-reload' of type 'ScheduledDowntime':
      % declared in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * __name = "hq-asa.gfs.domain.com!sybase_asa_12!aclsms-reload"
      * author = "support"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 37:3-37:20
      * comment = "ACLSMS DB reload"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 38:3-38:30
      * duration = 0
      * fixed = true
      * host_name = "hq-asa.gfs.domain.com"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * name = "aclsms-reload"
      * ranges
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 40:3-48:3
        * friday = "00:00-03:30"
        * monday = "00:00-03:30"
        * saturday = "00:00-03:30"
        * sunday = "00:00-03:30"
        * thursday = "00:00-03:30"
        * tuesday = "00:00-03:30"
        * wednesday = "00:00-03:30"
      * service_name = "sybase_asa_12"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * templates = [ "aclsms-reload" ]
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50
      * type = "ScheduledDowntime"
      * vars = null
      * zone = "hq-asa.gfs.domain.com"
        % = modified in '/etc/icinga2/conf.d/downtimes.conf', lines 36:1-36:50

I looked in the DB at the scheduleddowntime and downtimehistory tables.

The scheduleddowntime had the below three matches, which seems to correspond with the three objects above.

    mysql> select downtime_type, entry_time, comment_data, scheduled_start_time, scheduled_end_time, was_started, actual_start_time, actual_start_time_usec trigger_time from icinga_scheduleddowntime where comment_data like '%ACLSMS%';
    +---------------+---------------------+------------------+----------------------+---------------------+-------------+---------------------+--------------+
    | downtime_type | entry_time          | comment_data     | scheduled_start_time | scheduled_end_time  | was_started | actual_start_time   | trigger_time |
    +---------------+---------------------+------------------+----------------------+---------------------+-------------+---------------------+--------------+
    |             1 | 2015-10-16 08:00:18 | ACLSMS DB reload | 2015-10-17 00:00:00  | 2015-10-17 03:30:00 |           0 | 0000-00-00 00:00:00 |            0 |
    |             1 | 2015-10-16 08:00:18 | ACLSMS DB reload | 2015-10-17 00:00:00  | 2015-10-17 03:30:00 |           0 | 0000-00-00 00:00:00 |            0 |
    |             1 | 2015-10-16 08:00:18 | ACLSMS DB reload | 2015-10-17 00:00:00  | 2015-10-17 03:30:00 |           0 | 0000-00-00 00:00:00 |            0 |
    +---------------+---------------------+------------------+----------------------+---------------------+-------------+---------------------+--------------+
    3 rows in set (0.00 sec)

I only took the last hours worth of history, but there is lots of history all the same.

    mysql> select downtime_type, entry_time, comment_data, scheduled_start_time, scheduled_end_time, was_started, actual_start_time, actual_start_time_usec, trigger_time from icinga_downtimehistory where comment_data like '%ACLSMS%' AND scheduled_start_time="2015-10-16 00:00:00" AND entry_time="2015-10-15 23:00:20";
    +---------------+---------------------+------------------+----------------------+---------------------+-------------+---------------------+------------------------+---------------------+
    | downtime_type | entry_time          | comment_data     | scheduled_start_time | scheduled_end_time  | was_started | actual_start_time   | actual_start_time_usec | trigger_time        |
    +---------------+---------------------+------------------+----------------------+---------------------+-------------+---------------------+------------------------+---------------------+
    |             1 | 2015-10-16 08:00:18 | ACLSMS DB reload | 2015-10-17 00:00:00  | 2015-10-17 03:30:00 |           0 | 0000-00-00 00:00:00 |                      0 | 0000-00-00 00:00:00 |
    |             1 | 2015-10-16 08:00:18 | ACLSMS DB reload | 2015-10-17 00:00:00  | 2015-10-17 03:30:00 |           0 | 0000-00-00 00:00:00 |                      0 | 0000-00-00 00:00:00 |
    |             1 | 2015-10-16 08:00:18 | ACLSMS DB reload | 2015-10-17 00:00:00  | 2015-10-17 03:30:00 |           0 | 0000-00-00 00:00:00 |                      0 | 0000-00-00 00:00:00 |
    +---------------+---------------------+------------------+----------------------+---------------------+-------------+---------------------+------------------------+---------------------+
    3 rows in set (0.01 sec)

Copy of mail recieved.

    ***** Icinga *****

    Notification Type: PROBLEM

    Service: sybase_asa_12
    Host: aclsms.gfs.domain.com
    Address:
    State: CRITICAL

    Date/Time: 2015-10-16 01:32:57 +0200

    Additional Info: PROCS CRITICAL: 0 processes with command name 'dbsrv12'

    Comment: [] 

**Attachments**

* [troubleshoot.tar.gz](https://dev.icinga.com/attachments/download/2785/troubleshoot.tar.gz) henti - _2015-10-16 07:04:22 +00:00_ - _icinga2 troubleshoot output_

**Comment by dnsmichi** [comment]
I believe this is fixed with the current supported version.
