### ISSUE TITLE
[dev.icinga.com #10403] Escaping $ not documented

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3511]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10403

**Created by jflach on 2015-10-20 09:28:02 +00:00**

Assignee: _mfriedrich_
Status: _Resolved_  (closed on _2015-10-21 20:50:38 +00:00_)
Target Version: _2.4.0_
Last Update: _2015-10-22 13:52:28 +00:00 (in Redmine)_

    Icinga Version: 2.3.11
    Backport?: No
    Include in Changelog: 1

---

Escaping $ in configuration files is not documented.

    $ (Dollar sign) can be escaped by adding an additional $. $$ is then resolved to $, to add two dollar signs you then have to use $$$$

**Changesets**

_2015-10-21 20:49:21 +00:00_ by _mfriedrich_ b4d592dc16bc4a77052c50f318d04158a167fa81

    Documentation: Fix missing dollar sign escaping, add troubleshooting hint
    
    This is a pretty common error for years and deserves
    a troubleshooting entry.
    
    fixes #10403

**Comment by reduardo7** [comment]
Just to document: You can escape `$` with `$$` ;-)

**Comment by minidisk1147** [comment]
Why is this bug "closed". I would expect this escape sequence here:
https://icinga.com/docs/icinga2/snapshot/doc/17-language-reference/#string-literals-escape-sequences

Can't find it.

**Comment by keithf4** [comment]
Confirmed, this still is not documented. Only reason I found this fix was by googling "icinga escape dollar" and this issue coming up.

**Comment by dnsmichi** [comment]
https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#runtime-macros
