### ISSUE TITLE
[dev.icinga.com #10405] Use Configwriter to write out zones.conf etc.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3513]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10405

**Created by jflach on 2015-10-20 10:39:27 +00:00**

Assignee: _jflach_
Status: _Assigned_ 
Target Version: _Backlog_
Last Update: _2016-03-18 16:59:32 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Configwriter &gt; current node wizard ~~Gefummel~~ fiddling

---

**Relations**:

* relates [#10405](https://dev.icinga.com/issues/10405)

**Comment by dnsmichi** [comment]
This could be something for @N-o-X to start with the cli and config.

**Comment by Crunsher** [comment]
This seems to be already implemented with b76fee5
