### ISSUE TITLE
[dev.icinga.com #10411] Documentation missing for icinga2 CLI commands.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3518]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10411

**Created by IcePic on 2015-10-20 20:54:14 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-12-08 00:11:30 +00:00_)
Target Version: _(none)_
Last Update: _2017-01-14 13:09:08 +00:00 (in Redmine)_

    Icinga Version: I noticed it on a box with 2.3.3, but the webpage version is to me unknown.
    Backport?: Not yet backported
    Include in Changelog: 1

---

prompt$ icinga2 add node
will complain about missing parameters (ie, the hostname), but the --help version just says <parameters> goes after the command and the webpage docs for icinga2 add node doesn't add any info to it, just shows what --help already told you.

From freenode IRC:
17:44 &lt; IcePic&gt; I sense a pattern. "icinga2 add node" says "needs argument",
add node --help does only say that arguments go after "add
node", and the webpage docs doesn't list what it takes either,
even if it was rather trivial to figure out it was the node
name.
17:47 &lt; shroud&gt; hm, you're right, this seems like something we should fix
17:47 &lt; shroud&gt; can you submit a ticket for that? :)
17:50 &lt; shroud&gt; in fact
17:51 &lt; shroud&gt; the positional arguments are missing for *all* commands (in
--help)

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Comment by dnsmichi** [comment]
#4799
