### ISSUE TITLE
[dev.icinga.com #10415] Implement log functionality for event streams

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3521]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10415

**Created by mfriedrich on 2015-10-21 10:34:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-25 16:07:53 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

---

**Relations**:

* relates [#10415](https://dev.icinga.com/issues/10415)

**Comment by dnsmichi** [comment]
We decided not to go there for now.
