### ISSUE TITLE
[dev.icinga.com #10476] Explain check_memorys and check_disks thresholds

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3560]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10476

**Created by jflach on 2015-10-28 14:22:55 +00:00**

Assignee: _jflach_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2015-11-26 07:52:38 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

They check against free ram/space.

**Comment by Crunsher** [comment]
Nobody saw me doing that, right?
