### ISSUE TITLE
[dev.icinga.com #10492] Figure out whether we still need scheduled_by

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3567]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10492

**Created by mfriedrich on 2015-10-29 16:18:15 +00:00**

Assignee: _gbeutner_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-03-18 16:43:13 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

It is checked but never set.

            BOOST_FOREACH(const Downtime::Ptr& downtime, GetCheckable()->GetDowntimes()) {
                    if (downtime->GetScheduledBy() != GetName() ||
                        downtime->GetStartTime() < Utility::GetTime())
                            continue;

**Comment by dnsmichi** [comment]
Actually it is set through AddDowntime() but only for ScheduledDowntime objects which call CreateNextDowntime().
