### ISSUE TITLE
[dev.icinga.com #10493] Create Icinga 2 packages for Solaris 11

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3568]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10493

**Created by ziaunys on 2015-10-29 18:03:33 +00:00**

Assignee: _crfriend_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-12-08 00:40:10 +00:00 (in Redmine)_

    Include in Changelog: 1

---

I'd just like to premise this ticket by saying how awesome the package support is on all of the Icinga related tools.

That said, it would be great if there were some hosted Solaris packages for Icinga2. I would prefer 11, but I've seen a few other Icinga users make this request for older versions. Since I'm using Icinga2 agent-based monitoring I need to deploy the agent on our Solaris nodes for consistency in how we configure checks across all our various OS platforms.

**Comment by dnsmichi** [comment]
The community takes care of it. Thanks @sysadmama
