### ISSUE TITLE
[dev.icinga.com #10541] Windows plugin check_perfmon: multiple indicators at once

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3603]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10541

**Created by DreiIT on 2015-11-04 18:37:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-18 16:32:12 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

It would be a handy feature to be able to monitor multiple Windows performance counters at once including their perfdata - in the same way it can be done with check\_disk.

**Attachments**

* [2015-11-05 11_25_05-Icinga Web.png](https://dev.icinga.com/attachments/download/2856/2015-11-05%2011_25_05-Icinga%20Web.png) DreiIT - _2015-11-05 10:36:14 +00:00_ - _perfdata from check_esxi_hardware.py_

**Comment by dnsmichi** [comment]
With the new Icinga for windows package developed by @LordHepipud this won't be taken into account for future development iterations. Learn more about this new project here: https://icinga.com/2019/11/05/icinga-for-windows-rc-available/
