### ISSUE TITLE
[dev.icinga.com #10586] Double quotes don't get passed to Windows remote command execution

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3637]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10586

**Created by chucker on 2015-11-09 21:59:56 +00:00**

Assignee: _jflach_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-02-24 21:58:46 +00:00 (in Redmine)_

    Icinga Version: 2.3.11
    Backport?: Not yet backported
    Include in Changelog: 1

---

I'm trying to pass a double quote on to a CheckCommand that's executed remotely (i.e., command\_endpoint is set and there's a satellite Icinga 2).

The command looks like this:

    object CheckCommand "Performance Counter" {
        import "plugin-check-command"

        command = [ PrefixDir + "/usr/lib/nagios/plugins/PerformanceCounter/PerformanceCounter.exe",
                    "--Category=\"$category$\"" ]
    }

With a sample service as such:

    apply Service "SQL Server: Batch Requests/sec" {
        import "generic-service"

        check_command = "Performance Counter"
        command_endpoint = host.name

        vars.category = "SQLServer:SQL Statistics"

        assign where "windows" in host.groups
    }

I've observed two behaviors, both incorrect:

-   with the master running 2.3.11 on Ubuntu 15.10 and the satellite running 2.3.8 on Windows, the double quotes become spaces.
-   at shroud's suggestion, I upgraded the satellite to 2.3.11 as well, due to \#10245. Now, it appears the double quotes instead get eaten altogether.

**Comment by Crunsher** [comment]
@dnsmichi Please explain why this got closed (hopefully because it magically solved itself ^_^)

**Comment by dnsmichi** [comment]
a.) the issue is >2 years old. no responses in here from others.
b.) I haven't seen it in my tests with 2.7 lately.
