### ISSUE TITLE
[dev.icinga.com #10595] /v1/objects/<type> doesn't allow to restrict attributes for sub-objects

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3644]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10595

**Created by tgelf on 2015-11-10 11:32:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-25 14:31:15 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

It's possible to get the whole last check result dictionary in attrs, but it's not possible to choose last\_check\_result.output. This adds 60-80% overhead in time and traffic for those who want to fetch just a very few status-related columns.

Cheers,
Thomas

**Comment by dnsmichi** [comment]
That's a missing feature and requires a sponsor.

**Comment by htriem** [comment]
There are no plans to support this.
