### ISSUE TITLE
[dev.icinga.com #10609] Ongoing reloads are blocking API requests

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3653]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10609

**Created by tgelf on 2015-11-11 16:47:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-24 21:57:40 +00:00 (in Redmine)_

    Icinga Version: 2.4.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Stages have been designed to avoid issues with multiple parallel config dump requests. That's their main and solely purpose. Currently they are pretty useless, as the core blocks farther requests unless a dumped config is fully parsed and even worse (at least that's what it feels like) dumped to IDO. Unfortunately, this could take a couple of minutes.

Once designing this feature we explicitly stated that an API client dumping a full stage is definitively NOT interested in hanging around, waiting for an eventual feedback. That's basically fine so far. But parallel or consecutive requests might not even know that another request happened a few seconds ago, they should not care. If our intent would have been "block when busy" we could have kept the far simpler variant with just two stages, "test" and "prod".

To fix this receiving a new config package would mean:

-   create a new stage
-   write files to disk
-   return the stage name
-   remember that a reload has been requested (like for a SIGHUP)
-   issue the reload as soon as possible

Nothing else, no dependency on state or other components. API client disconnected, others may do similar work in parallel. At any time for a reload a second process can be forked, should take it's time for config parsing, IDO dump, handover, removal of the former process - whatever. Only the latest available stage should be evaluated, the former one should continue to run in case it fails.

The core does not need to care about other intermediary stages, no state and startup.log is needed for them. API clients are already required to clear their stages up by themselves.

Cheers,
Thomas

**Comment by dnsmichi** [comment]
Should be fixed and handled with #3668 and #5547.
