### ISSUE TITLE
[dev.icinga.com #10612] Implement support for default function arguments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3655]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10612

**Created by gbeutner on 2015-11-12 05:58:08 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-18 16:19:07 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

    function f(e = 3) {

    }

    f()

**Comment by Crunsher** [comment]
This feature request saw no interaction in over two years. Closing.
