### ISSUE TITLE
[dev.icinga.com #10679] add "weight"- option / tag for nodes in cluster setup

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3686]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10679

**Created by yukibi on 2015-11-19 14:46:45 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-11-19 14:46:45 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

-   Please add a config option to nodes in order to make the nodes 'special' in a cluster setup
-   Please add an option to make some hosts / services 'prefer' the special node(s)

Possible use would be:

-   use preferred node(s) to check 'nearby' hosts in a multi-location hosting environment
-   execute long running service checks on a 'dedicated' node
-   configure anti-affinity for some hosts / services

---

**Relations**:

* relates [#10977](https://dev.icinga.com/issues/10977)
* relates [#10040](https://dev.icinga.com/issues/10040)
* relates [#10709](https://dev.icinga.com/issues/10709)

**Comment by Crunsher** [comment]
This feature request saw no interaction in over two years. Closing.
