### ISSUE TITLE
[dev.icinga.com #11256] Replace deprecated function SSLv23_method() with TLS_method()

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3692]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11256

**Created by tobiasvdk on 2016-02-29 07:20:42 +00:00**

Assignee: _tobiasvdk_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-03-18 11:01:53 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Since OpenSSL version &gt;1.0.2 the function `SSLv23_method()` is deprecated and `TLS_method()` should be used, see https://www.openssl.org/docs/manmaster/ssl/SSL\_CTX\_new.html
> TLS\_method(), TLS\_server\_method(), TLS\_client\_method()
> These are the general-purpose version-flexible SSL/TLS methods. The actual protocol version used will be negotiated to the highest version mutually supported by the client and the server. The supported protocols are SSLv3, TLSv1, TLSv1.1 and TLSv1.2. Most applications should use these method, and avoid the version specific methods described below.
> 
> SSLv23\_method(), SSLv23\_server\_method(), SSLv23\_client\_method()
> Use of these functions is deprecated. They have been replaced with the above TLS\_method(), TLS\_server\_method() and TLS\_client\_method() respectively. New code should use those functions instead.

---

**Relations**:

* relates [#11256](https://dev.icinga.com/issues/11256)

**Comment by dnsmichi** [comment]
Once we drop support for RHEL5 this certainly is an option. Not sure about SLES11 though. Guess it will never happen.
