### ISSUE TITLE
[dev.icinga.com #10709] New type of icinga cluster

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3700]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10709

**Created by smtalk on 2015-11-23 12:57:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-18 14:07:54 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Currently I don't see Icinga offering the type of cluster, which would work like that:
1) Main node monitoring all the servers/services
2) If any of the checks state changes to CRITICAL, start the check from the 2nd (slave) node for that particular service only

Then CRITICAL+CRITICAL would be CRITICAL, CRITICAL+OK=OK (or WARNING).

Why is that needed? When monitoring servers all around the world from a single place, network problems appear from time to time to some of them. Having a 2nd location for additional status checks would bring less false-positives (and not only for networking issues).

Waiting for the opinions :)

---

**Relations**:

* relates [#10977](https://dev.icinga.com/issues/10977)
* relates [#10709](https://dev.icinga.com/issues/10709)

**Comment by gunnarbeutner** [comment]
This sounds like something that could be implemented using the business process addon.
