### ISSUE TITLE
[dev.icinga.com #10734] Duplicate Index found

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3720]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10734

**Created by Tux12Fun on 2015-11-26 17:25:38 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-11 08:46:59 +00:00 (in Redmine)_

    Icinga Version: 2.4.0-1~ppa1~trusty1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

I found a Table with a duplicate Index.

=&gt; See Screenshot.

**Attachments**

* [icinga.PNG](https://dev.icinga.com/attachments/download/2910/icinga.PNG) Tux12Fun - _2015-11-26 17:24:22 +00:00_

**Comment by dnsmichi** [comment]
We won't modify the current schema unless the performance gain is considerably high, sorry.
