### ISSUE TITLE
[dev.icinga.com #10763] IDO check problems with command_endpoint

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3738]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10763

**Created by mfrosch on 2015-12-02 18:29:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-12-03 12:00:13 +00:00 (in Redmine)_

    Icinga Version: 2.4.1-snapshot
    Backport?: Not yet backported
    Include in Changelog: 1

---

In a large installation the IDO check seem to have problems with the vars.

The check worked from start, but threw that error about ~15 min later.

    => get_service("mon-icingamaster-02.example.com", "icinga ido")
    {
        __name = "mon-icingamaster-02.example.com!icinga ido"
        acknowledgement = 0.000000
        acknowledgement_expiry = 0.000000
        action_url = ""
        active = true
        check_attempt = 1.000000
        check_command = "ido"
        check_interval = 300.000000
        check_period = ""
        command_endpoint = "mon-icingamaster-02.example.com"
        display_name = "icinga ido"
        enable_active_checks = true
        enable_event_handler = true
        enable_flapping = false
        enable_notifications = true
        enable_passive_checks = true
        enable_perfdata = true
        event_command = ""
        extensions = {
            DbObject = {
                type = "Object"
            }
        }
        flapping = false
        flapping_last_change = 1449080492.045369
        flapping_negative = 2927.000000
        flapping_positive = 299.000000
        flapping_threshold = 30.000000
        force_next_check = false
        force_next_notification = false
        groups = [ ]
        ha_mode = 0.000000
        host = { [ ... ] }
        host_name = "mon-icingamaster-02.example.com"
        icon_image = ""
        icon_image_alt = ""
        last_check = 1449080492.033753
        last_check_result = {
            active = true
            check_source = "mon-icingamaster-02.example.com"
            command = null
            execution_end = 1449080492.033753
            execution_start = 1449080492.033710
            exit_status = 0.000000
            output = "Macro 'ido_name' must be set."
            performance_data = [ ]
            schedule_end = 1449080492.033753
            schedule_start = 1449080492.033753
            state = 3.000000
            type = "CheckResult"
            vars_after = {
                attempt = 1.000000
                reachable = true
                state = 3.000000
                state_type = 1.000000
            }
            vars_before = {
                attempt = 1.000000
                reachable = true
                state = 3.000000
                state_type = 1.000000
            }
        }
        last_hard_state = 3.000000
        last_hard_state_change = 1449080312.041679
        last_hard_state_raw = 3.000000
        last_in_downtime = false
        last_reachable = true
        last_state = 3.000000
        last_state_change = 1449080139.222801
        last_state_critical = 0.000000
        last_state_ok = 1449080121.286843
        last_state_raw = 3.000000
        last_state_type = 1.000000
        last_state_unknown = 1449080492.045362
        last_state_unreachable = 0.000000
        last_state_warning = 0.000000
        max_check_attempts = 3.000000
        name = "icinga ido"
        next_check = 1449080792.030000
        notes = ""
        notes_url = ""
        original_attributes = null
        package = "_cluster"
        pause_called = true
        paused = true
        resume_called = true
        retry_interval = 60.000000
        start_called = true
        state = 3.000000
        state_loaded = true
        state_raw = 3.000000
        state_type = 1.000000
        stop_called = false
        templates = [ "icinga ido", "agent-service", "generic-service" ]
        type = "Service"
        vars = {
            ido_name = "ido-mysql"
            ido_type = "IdoMysqlConnection"
            sla = "24x7"
        }
        version = 0.000000
        volatile = false
        zone = "master"
    }

**Comment by dnsmichi** [comment]
AFAIK this has been fixed in recent versions.
