### ISSUE TITLE
[dev.icinga.com #10764] Command Endpoint checks are not replicated when not-connected

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3739]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10764

**Created by mfrosch on 2015-12-02 19:08:35 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:52:20 +00:00 (in Redmine)_

    Icinga Version: 2.4.1-snapshot
    Backport?: Not yet backported
    Include in Changelog: 1

---

Setup: master-master

A command\_endpoint check can't be run, because the Endpoint is not connected.

This should also generate a check\_result, but 2 things are noticed:

-   no check result time stamp update
-   secondary master still shows pending state, but should be unknown on both

**Comment by Al2Klimov** [comment]
@dnsmichi "command_endpoint is **(ab)used** for pinning checks to a specific instance" => Isn't this the only way for check_disk/apt/load/... ?

**Comment by Al2Klimov** [comment]
Hello @lazyfrosch and thank you for reporting!

Is this problem still present in v2.10.2?

Best,
AK

**Comment by Al2Klimov** [comment]
In my fresh master/master + agent (which doesn’t actually exist and is "not connected") setup the not-connected check result is replicated in the master zone. I consider other possible scenarios not-working as expected, but let's hear the colleagues' opinions...

**Comment by julianbrost** [comment]
I don't really get the bug report. It sounds like maybe in an earlier version, when a command endpoint was not connected, no check result was generated. But from my understanding, this simply generates a check result just like any other result would do.

So from the description, I'd have tried exactly the same as @Al2Klimov and this seems to work. What are the other possible scenarios you had in mind?

**Comment by julianbrost** [comment]
Well ok, then there's no way to replicate the result (that's probably "not-working as expected" I guess).

So what's described in https://github.com/Icinga/icinga2/issues/3739#issuecomment-273094932 seems to no longer be a problem and I don't see anything else we should test/change based on this issue.
