### ISSUE TITLE
[dev.icinga.com #10799] Icinga2 WIndows Client not able to get values bigger than int32.maxvalue from master node

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3757]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10799

**Created by Isotop7 on 2015-12-09 09:24:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-03-18 15:12:40 +00:00 (in Redmine)_

    Icinga Version: r2.4.1.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

We use the check\_network.exe plugin to monitor the bandwith usage on our Windows Servers. The Hyper-V-Machines are connected to a virtual adapter with a bandwith of 10 gbit/s.

If i try to edit my service to get the warning value to 7gbit/s, which would be 7 \* 1024^3 bit/s (7,516,192,768), i always get a warning return since it fails to transmit this value and falls back to the negative border of int32 which is -2,147,483,648. It seems that it cant use values bigger than int32.maxvalue.

If i run the plugin on the monitored machine itself, it successfully converts the value and returns the right output. So i guess the problem is icinga2 daemon evaluating the value on the master node or the transmission to the client.

**Comment by dnsmichi** [comment]
@Crunsher @TheFlyingCorpse still a valid point with the x64 builds?

**Comment by TheFlyingCorpse** [comment]
First thought, why not send as string (use quotes on the data)?

I just tested this on 2.6.3 against a fresh 2016 VM with x86_64 agent.

No issues with the identical warn and critical as used in this ticket, I'd say this one is fixed, can close ticket.

Output from API to show it works:
```
...
    last_check_result: {
      active: true,
      check_source: "somewindowsbox08.labdomain.net",
      command: [
        "C:\\Program Files\\ICINGA2\\/sbin/check_network.exe",
        "-c",
        "8589934592",
        "-n",
        "-w",
        "7516192768"
      ],
      execution_end: 1490908505.155000,
      execution_start: 1490908503.905000,
      exit_status: 0,
      output: "NETWORK OK 1409B/s ",
      performance_data: [
        "network=1409B;7516192768;8589934592;0;",
        "\'Intel[R] 82574L Gigabit Network Connection_in\'=431B",
        "\'Intel[R] 82574L Gigabit Network Connection_out\'=978B",
        "\'Reusable ISATAP Interface {41787FA0-6C27-47E0-BDC8-17900422ECE9}_in\'=0B",
        "\'Reusable ISATAP Interface {41787FA0-6C27-47E0-BDC8-17900422ECE9}_out\'=0B"
      ],
...
    type: "Service",
    vars: {
      network_win_crit: "8589934592",
      network_win_warn: "7516192768"
    },
...
```
