### ISSUE TITLE
[dev.icinga.com #10827] Can't change default warning/critical thresholds for checks that have defaults set in ITL

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3772]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10827

**Created by elimat on 2015-12-11 15:09:23 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2016-03-18 15:08:58 +00:00_)
Target Version: _(none)_
Last Update: _2016-03-18 15:08:58 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

We have a problem where checks that have defaults values for Warning and Critical thresholds cant be set to something else.

I set a custom variable to the value I want. then the checks use this the next time it runs. How ever the next time it runs it uses the the default values from ITL.

I have some contrib checks and they does not have this problem. But "procs" and "load" checks have the same issue.

below is an example of how the apply rule for "load" check locks like

    apply Service "load" {
      import "generic-service"

      check_command = "load"
      command_endpoint = host.vars.remote_client

      vars.load_wload1 = 10.0
      vars.load_wload5 = 8.0
      vars.load_wload15 = 6.0
      vars.load_cload1 = 20.0
      vars.load_cload5 = 12.0
      vars.load_cload15 = 8.0

      assign where host.vars.remote_client && host.vars.os == "Linux"
    }

**Attachments**

* [debug.log](https://dev.icinga.com/attachments/download/2951/debug.log) elimat - _2015-12-14 08:40:37 +00:00_

**Comment by basdv98** [comment]
I also see custom thresholds are not working when I have the same service name as check command name. I tested this with proc and load and both not working, if I change the service name it works perfectly.

Is there any solution to this? I want to name my services as the check command..

**Comment by mambusskruj** [comment]
Same for me with Icinga2 2.8.1. I think this bug should be reopen.

**Comment by dnsmichi** [comment]
I don't think so, without any further problem description. Hop on the forums or mailing lists and share your problem and details.

**Comment by bornakke** [comment]
Same problem. Had to switch service names of procs and load and now it works.
