### ISSUE TITLE
[dev.icinga.com #10873] Intermittent behavior - ICINGA doesn't display HOST_GROUP

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3789]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10873

**Created by mgochhait on 2015-12-17 04:17:18 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_  (closed on _2016-03-18 10:46:36 +00:00_)
Target Version: _(none)_
Last Update: _2016-05-17 09:13:28 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Some more observations made on this.
1. All calls are made through REST API's
2. It is cluster - 2 node setup\[Master - Master\].
3. Configuration of zone.conf for Node1 and Node2 are pasted below

Step 1: create host\_grp and associate hosts ( host\_grp\_name="test\_1\_grp", host="192.168.1.11" )
Step 2: UI displays hostgrp and associated hosts
Step 3: create host\_grp and associate hosts( host\_grp\_name="test\_2\_grp", host="192.168.1.22" )
Step 4: UI displays hostgrp and associated hosts
Step 5: create host\_grp and associate hosts( host\_grp\_name="test\_3\_grp", host="192.168.1.33" )
Step 6: UI did not display this host\_group where as host is displayed for 192.168.1.33
Step 7: create host\_grp and associate hosts( host\_grp\_name="test\_4\_grp", host="192.168.1.44" )
Step 8: UI did not display this host\_group where as host is displayed for 192.168.1.44
However this time it showed Host\_GRP test\_3\_grp that was created on step 6

Node1. zone.conf
object Endpoint "icinga-1" {
host = "icinga-1"
}

object Endpoint "icinga-2" {
host = "icinga-2"
}

object Zone "config-ha-master" {
endpoints = \[ "icinga-1" , "icinga-2" \]
}

Node 2: zone.conf
object Endpoint "icinga-1" {
host = "icinga-1"
}

object Endpoint "icinga-2" {
host = "icinga-2"
}

object Zone "config-ha-master" {
endpoints = \[ "icinga-1" , "icinga-2" \]
}

ICINGA Installed version :
root@icinga-2:~\# dpkg -l |grep icinga
ii icinga2 2.4.1-1~ppa1~trusty1 amd64 host and network monitoring system
ii icinga2-bin 2.4.1-1~ppa1~trusty1 amd64 host and network monitoring system - daemon
ii icinga2-common 2.4.1-1~ppa1~trusty1 all host and network monitoring system - common files
ii icinga2-doc 2.4.1-1~ppa1~trusty1 all host and network monitoring system - documentation
ii icinga2-ido-mysql 2.4.1-1~ppa1~trusty1 amd64 host and network monitoring system - MySQL support
ii icingaweb2 2.1.0-2~~ppa1 all simple and responsive web interface for Icinga
ii icingaweb2-module-doc 2.1.0-2~~ppa1 all simple and responsive web interface for Icinga - documentation module
ii icingaweb2-module-monitoring 2.1.0-2~~ppa1 all simple and responsive web interface for Icinga - monitoring module
ii libicinga2 2.4.1-1~ppa1~trusty1 amd64 host and network monitoring system - internal libraries
ii php-icinga 2.1.0-2~~ppa1 all PHP library to communicate with and use Icinga

Please let me know if any other configuration you need to analyze.
Appreciate your help on this

---

**Relations**:

* relates [#11731](https://dev.icinga.com/issues/11731)
* relates [#11400](https://dev.icinga.com/issues/11400)

**Comment by dnsmichi** [comment]
Not able to reproduce this with 2.6.x.
