### ISSUE TITLE
[dev.icinga.com #10899] logrotate failing on Ubuntu Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3803]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10899

**Created by dbienapfl on 2015-12-21 17:48:56 +00:00**

Assignee: _formorer_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-11-11 09:28:30 +00:00 (in Redmine)_

    Icinga Version: (Backend r2.4.1-1) 
    Backport?: Not yet backported
    Include in Changelog: 1

---

Log rotate is failing for the following reason:

During the 'postrotate' function defined in the '/etc/logrotate.d/incinga2' a call is made to 'service status icinga2'

The status function in the init script calls an LSB library function 'status\_of\_proc'

The stock script submits the '$DAEMON' var which in this case is assigned to '/usr/sbin/icinga2'

the script found in the '/usr/sbin/icinga2' location is just a script to kick the actual binary into a daemon mode - the actual binary lives at '/usr/lib/x86\_64-linux-gnu/icinga2/sbin/icinga2'.

Based on the way the '$DAEMON' script calls the actual icinga2 binary the resulting process appears in the process tree with the 'real' full path:

nagios 31380 1 0 17:02 ? 00:00:06 /usr/lib/x86\_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daem......

As a result of this mismatch '/usr/sbin/icinga2' != '/usr/lib/x86\_64-linux-gnu/icinga2/sbin/icinga2' when 'pidof' is called by the LSB function it is called with the path to the script used to kick off the daemon:

'/bin/pidof -o %PPID -x /usr/sbin/icinga2'

NOT the path that is found in the process tree so the status command fails:

As an example, the following command returns cleanly:

'/bin/pidof -o %PPID -x /usr/lib/x86\_64-linux-gnu/icinga2/sbin/icinga2'

---

**Relations**:

* relates [#10899](https://dev.icinga.com/issues/10899)

**Comment by dnsmichi** [comment]
@lazyfrosch your thoughts on this? :)
