### ISSUE TITLE
[dev.icinga.com #10931] Exception stack trace on icinga2 client when the master reloads the configuration

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3816]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10931

**Created by seferovic on 2016-01-05 13:04:53 +00:00**

Assignee: _seferovic_
Status: _Resolved_  (closed on _2016-02-23 09:59:36 +00:00_)
Target Version: _2.4.2_
Last Update: _2016-02-23 09:59:53 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Already backported
    Include in Changelog: 1

---

In my test environment I have a master server which sends commands to icinga2 agents. On reload of the master server the connection to the agent is being destroyed (?!) and the icinga2 agent logs following

    [2016-01-05 13:53:11 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'master.monitoring': Error: std::exception

            (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7fbde1817a57]
            (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7fbde1817b00]
            (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7fbde17b646c]
            (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x7e) [0x7fbde17b65de]
            (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x55) [0x7fbde17c56e5]
            (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7fbde17d3dde]
            (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7fbde0e5d4ad]
            (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7fbde0e81555]
            (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7fbde0e9de68]
            (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1bb) [0x7fbde184a0ab]
            (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x27) [0x7fbde17faa17]
            (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3af) [0x7fbde17fae9f]
            (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7fbde17f7aca]
            (13) libboost_thread.so.1.53.0:  (+0xc5c3) [0x7fbde222c5c3]
            (14) libpthread.so.0:  (+0x7a51) [0x7fbdde99aa51]
            (15) libc.so.6: clone (+0x6d) [0x7fbddeea093d]

I am not sure if this should be considered a bug, but I don't expect to see such exceptions in main log only because the master reloaded the config... but I might be wrong, so please excuse the newbie ;)

Thx!

---

**Relations**:

* relates [#10931](https://dev.icinga.com/issues/10931)

**Comment by ricky33000** [comment]
'apt install chrony' on master, satellite and client hosts solve the  issue "Error while reading JSON-RPC message for identity 'example.com': Error: stream truncated" for me.
It seems that json rpc connexion need right ntp sync.
