### ISSUE TITLE
[dev.icinga.com #10946] Add missing options for the 'by_ssh' CheckCommand

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3825]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10946

**Created by ip1981 on 2016-01-10 17:29:58 +00:00**

Assignee: _mfriedrich_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-08 00:39:46 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

I managed to wrap almost any check command to run by ssh:

        apply Service "disk" {
          check_command = "by_ssh"
          assign where "disk" in host.vars.probes

          vars = get_check_command("disk").vars
          vars.by_ssh_identity = "${icingaSshKey}"
          vars.by_ssh_command = "check_disk"
          vars.by_ssh_arguments = get_check_command("disk").arguments
          vars.by_ssh_options = [
            "StrictHostKeyChecking=no",
            "UserKnownHostsFile=/dev/null" ]
        }

        object Host "dumpoo.zalora.com" {
          address = "dumpoo.zalora.com"
          check_command = "ssh"
          vars.probes = [ "disk" ]
        }

Since icinga is running as a homeless user check fails with a message "Could not create directory '/var/empty/.ssh'."
It can be avoided by the `-F` and `-E` options to `check_by_ssh`, but check command "by\_ssh" does not support them.
The above snippet could land in the documentation as well ;-)

    ...
            last_check_result = {
                    active = true
                    check_source = "icinga"
                    command = [ "/nix/store/5zc93cmcvdx5bhmykg6mq7s3njichk20-monitoring-plugins-2.1.2/libexec/check_by_ssh", "-C", "'check_disk' '-c' '5%' '-w' '15%' '-K' '5%' '-W' '10%' '-X' '
    none' '-X' 'tmpfs' '-X' 'sysfs' '-X' 'proc' '-X' 'devtmpfs' '-X' 'devfs' '-X' 'mtmfs' '-m'", "-H", "dumpoo.zalora.com", "-i", "/run/keys/icinga_ssh", "-o", "StrictHostKeyChecking=no", "-o",
     "UserKnownHostsFile=/dev/null" ]
                    execution_end = 1452445989.395826
                    execution_start = 1452445987.149218
                    exit_status = 3.000000
                    output = "Remote command execution failed: Could not create directory '/var/empty/.ssh'."
    ...

**Attachments**

* [by_ssh.png](https://dev.icinga.com/attachments/download/2997/by_ssh.png) ip1981 - _2016-01-10 18:22:46 +00:00_

**Comment by dnsmichi** [comment]
Won't happen anytime soon and did not receive a patch either.
