### ISSUE TITLE
[dev.icinga.com #10977] Different feature sets on endpoints in one HA Zone

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3846]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10977

**Created by twidhalm on 2016-01-18 12:08:37 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-01-29 09:27:34 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

Since having the option to run different features on nodes in one HA zone brings a lot of flexibility and was announced as one of the great features of Icinga 2 ( e.g, https://www.netways.de/fileadmin/images/Events\_Trainings/Events/OSMC/2014/Slides\_2014/Current\_state\_of\_Icinga\_Icinga\_Team.pdf ) I'd like to see this supported again in Icinga 2.

Some usecases (I can get more, if you need more to convince you ;-) )

-   Minimal HA Setup - One master with all Addons like IDO, Icinga Web 2, Grapher, etc. and one master only with checker and notification in case the real master breaks down.
-   Load balancing Checker. In case one (or more) master is not enough to run all desired check plugins, extra hosts with only checker active could help to balance the load. Running all other features would cause a lot of overhead.
-   Running features on a designated host within the HA / LB setup to handle writing performance data or to the IDO

For more information on this issue please refer to [\#10969](https://dev.icinga.com/issues/10969) , [\#7206](https://dev.icinga.com/issues/7206) and [\#9476](https://dev.icinga.com/issues/9476)

For some features I'd like to see the default behaviour to change so it works per default with different feature sets. e.g. checker and ido should first check what hosts it is running on to determine which hosts should activate and deactivate it to fulfill ha requirements. Right now the default behaviour of ido is that a host with ido running deactivates it if another host is in the same zone regardless of ido running there or not. (Which is not supported right now, as stated in the beforementioned issues)

Cheers,
Thomas

---

**Relations**:

* relates [#10977](https://dev.icinga.com/issues/10977)
* relates [#10977](https://dev.icinga.com/issues/10977)
* relates [#10977](https://dev.icinga.com/issues/10977)
* relates [#10977](https://dev.icinga.com/issues/10977)

**Comment by gunnarbeutner** [comment]
There are no plans to support this.
