### ISSUE TITLE
[dev.icinga.com #10978] Asymetric certificate signing like Puppet

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3847]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10978

**Created by twidhalm on 2016-01-18 12:25:32 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-08-31 12:49:26 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

When autosigning certificates is not secure enough and there is no way of adding an agent unattended I'd like to see at least a way to have assymetric certificate signing like e.g. in puppet. Having to work on the master and every new agent simultanously is annoying and in many cases not even possible.

I know, one could pre-generate tickets on the master and send them to the admins installing the agents but this is one step more for the users. "Send hostnames - generate tickets - install agents", while the other way would speed up installation with "install agents" - verify and sign certificates.

Cheers,
Thomas

---

**Relations**:

* relates [#10978](https://dev.icinga.com/issues/10978)

**Comment by dnsmichi** [comment]
@widhalmt this is implemented as part of #5450 for 2.8.0.
