### ISSUE TITLE
[dev.icinga.com #10980] icinga2 node update-config does not work well with indirect connected zones

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3849]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10980

**Created by formorer on 2016-01-18 14:47:30 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-14 13:05:56 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

I have the following setup

master &lt;- client &lt;- client\_of\_client where "client\_of\_client" is connected via client to my master instance.
I do propagate configuration files from my clients to the master with icinga2 update-config.

Unfortunately the generated configuration files for the client\_of\_client are wrong:

cat zones/client\_of\_client.test.lan.conf
object Zone "client\_of\_client.test.lan" {
endpoints = \[ "client.test.lan" \]
parent = "master.test.lan"
}

As you can see the parent is wrong. The hostcheck of the host is also wrong:

cat hosts/client\_of\_client.test.lan.conf :(
object Host "client\_of\_client.test.lan" {
import "satellite-host"
check\_command = "cluster-zone"
}

The check\_command is set to cluster-zone, which has the consequence that the hostcheck is always red. Dummy or something similar would work.

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Relations**:

* relates [#10980](https://dev.icinga.com/issues/10980)

**Comment by dnsmichi** [comment]
#4799
