### ISSUE TITLE
[dev.icinga.com #10987] Nested hostgroups do not work

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3856]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10987

**Created by cniemann on 2016-01-19 14:44:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-01-22 15:14:38 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

It's not possible to add nested hostgroups in icinga2.4.1.
The API knows about the hostGroup object and it's nested groups but the groups attribute of the host object will not be changed.

I added the objects.cache output to clearify this problem.

My testing environment is the current vagrant box with icinga2x single machine.

I added to "/etc/icinga2/conf.d/groups.conf"

object HostGroup "lin-win" {
display\_name = "Linux and Windows Servers"
groups = \[ "linux-servers", "windows-servers" \]
}

API Output:

    [root@icinga2 icinga2]# ICINGA2_API_PASSWORD=icinga icinga2 console --connect 'https://root@localhost:5665/' --eval 'get_host("c1-mysql-1").groups' | python -m json.tool
    [
        "bp-hosts-mysql",
        "linux-servers"
    ]

    [root@icinga2 icinga2]# ICINGA2_API_PASSWORD=icinga icinga2 console --connect 'https://root@localhost:5665/' --eval 'get_host_group("lin-win")' | python -m json.tool
    {
        "__name": "lin-win",
        "action_url": "",
        "active": true,
        "display_name": "Linux and Windows Servers",
        "extensions": {
            "DbObject": {
                "type": "Object"
            }
        },
        "groups": [
            "linux-servers",
            "windows-servers"
        ],
        "ha_mode": 0.0,
        "name": "lin-win",
        "notes": "",
        "notes_url": "",
        "original_attributes": null,
        "package": "_etc",
        "pause_called": false,
        "paused": false,
        "resume_called": true,
        "start_called": true,
        "state_loaded": true,
        "stop_called": false,
        "templates": [
            "lin-win"
        ],
        "type": "HostGroup",
        "vars": null,
        "version": 0.0,
        "zone": ""
    }

\[root@icinga2 icinga2\]\# icinga2 -V

    icinga2 - The Icinga 2 network monitoring daemon (version: v2.4.1-110-gda85c7a)

    Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
    License GPLv2+: GNU GPL version 2 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Application information:
      Installation root: /usr
      Sysconf directory: /etc
      Run directory: /run
      Local state directory: /var
      Package data directory: /usr/share/icinga2
      State path: /var/lib/icinga2/icinga2.state
      Modified attributes path: /var/lib/icinga2/modified-attributes.conf
      Objects path: /var/cache/icinga2/icinga2.debug
      Vars path: /var/cache/icinga2/icinga2.vars
      PID path: /run/icinga2/icinga2.pid

    System information:
      Platform: ME="cpe:/o:centos:centos:7
      Platform version: UPPORT_PRODUCT_VERSION="7
      Kernel: Linux
      Kernel version: 3.10.0-327.4.4.el7.x86_64
      Architecture: x86_64

- from /var/cache/icinga2/objects.cache

    define hostgroup {
            hostgroup_name  lin-win
            alias   Linux and Windows Servers
            members 
            }
    define hostgroup {
            hostgroup_name  linux-servers
            alias   Linux Servers
            members c1-mysql-1,c1-web-1,c2-mysql-2,icinga2
            }
    define hostgroup {
            hostgroup_name  windows-servers
            alias   Windows Servers
            members c2-web-1
            }

**Comment by dnsmichi** [comment]
Seems only relevant to compat, which we won't fix anymore.
