### ISSUE TITLE
[dev.icinga.com #11015] Provide a way to reliable discover lagging endpoint connections

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3867]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11015

**Created by tgelf on 2016-01-22 14:52:13 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-05 13:20:20 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

I found no way to accomplish what the subject asks for.

Cheers,
Thomas

**Comment by dnsmichi** [comment]
I honestly don't remember the problem. If there's still the need for it, please open a new issue with more details.
