### ISSUE TITLE
[dev.icinga.com #11025] Not all local checks executed when running a HA-cluster

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3873]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11025

**Created by rddisc on 2016-01-23 14:37:44 +00:00**

Assignee: _jflach_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:52:16 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

I work in a company that is using a non-clustered Icinga1. Now we would like to switch to HA-Icinga2. I created a test setup with two maschines and initialized the cluster. Clustering works fine and the "cluster-zone" check is green. We're using Debian Jessie (8.2) and the current Icinga2 version from the debmon repository (2.4.1-1).

In the docs there is a statement that the "cluster" and the "cluster-zone" check should be configured locally. So I created a separate directory, configured it in icinga2.conf and added the check conf files.

Now my problem is, that some local tests stalls after a few checks (ssh, cluster) while others (cluster-zone, icinga) are running. There are no errors in the debug log and I see the output of e.g. the ssh checks running successfully several times:

    [2016-01-22 09:14:40 +0100] debug/CheckerComponent: Executing check for 'icinga2!ssh'
    [2016-01-22 09:14:40 +0100] notice/Process: Running command '/usr/lib/nagios/plugins/check_ssh' '192.168.110.102': PID 24903
    [2016-01-22 09:14:40 +0100] debug/CheckerComponent: Check finished for object 'icinga2!ssh'
    [2016-01-22 09:14:40 +0100] notice/Process: PID 24903 ('/usr/lib/nagios/plugins/check_ssh' '192.168.110.102') terminated with exit code 0
    [2016-01-22 09:14:40 +0100] debug/Checkable: No origin or local origin for object 'icinga2!ssh', setting icinga2 as check_source.
    [2016-01-22 09:14:40 +0100] notice/Checkable: State Change: Checkable icinga2!ssh hard state change from UNKNOWN to OK detected.
    [2016-01-22 09:16:47 +0100] debug/CheckerComponent: Executing check for 'icinga2!ssh'
    [2016-01-22 09:16:47 +0100] notice/Process: Running command '/usr/lib/nagios/plugins/check_ssh' '192.168.110.102': PID 25116
    [2016-01-22 09:16:47 +0100] debug/CheckerComponent: Check finished for object 'icinga2!ssh'
    [2016-01-22 09:16:47 +0100] notice/Process: PID 25116 ('/usr/lib/nagios/plugins/check_ssh' '192.168.110.102') terminated with exit code 0
    [2016-01-22 09:16:47 +0100] debug/Checkable: No origin or local origin for object 'icinga2!ssh', setting icinga2 as check_source.

But after a while some checks stall and are not executed anymore. If I stop the ssh daemon, there is no state change.

My config files look like that:

**zones.conf**

    object Endpoint "icinga1" {
        host = "192.168.110.101"
    }

    object Endpoint "icinga2" {
        host = "192.168.110.102"
    }

    object Zone "monitor-cluster" {
      endpoints = [ "icinga1", "icinga2" ]
    }

**icinga.conf**

    include "constants.conf"
    include "zones.conf"
    include 
    include 
    include "features-enabled/*.conf"
    include_recursive "repository.d"
    include_recursive "local.d"

**local.d/icinga1.conf**

    object Host "icinga1" {
        check_command = "hostalive"
        address = "192.168.110.101"
    }

    object Service "cluster-zone" {
        check_command = "cluster-zone"
        check_interval = 5s
        retry_interval = 1s
        vars.cluster_zone = "monitor-cluster"
        host_name = "icinga1"
    }

    object Service "cluster" {
        check_command = "cluster"
        check_interval = 5s
        retry_interval = 1s
        host_name = "icinga1"
    }

    object Service "icinga" {
        check_command = "icinga"
        check_interval = 30s
        retry_interval = 10s
        host_name = "icinga1"
    }

    object Service "ssh" {
        check_command = "ssh"
        check_interval = 20s
        retry_interval = 10s
        host_name = "icinga1"
    }

I created a test setup a while ago and had the same problem. I asked the same question in monitoring portal forum then, but got no answer. After some googling I think I'm not alone with this problem. See:

https://monitoring-portal.org/index.php?thread/32800-icinga-2-cluster-setup-not-all-local-checks-are-executed/
https://monitoring-portal.org/index.php?thread/33066-icinga2-cluster-node-local-checks-not-executing/
https://monitoring-portal.org/index.php?thread/32409-checks-going-stale/
https://dev.icinga.org/issues/8052

But no solution was given. Today I created two virtual maschines with a bare Icinga cluster configuration. The same problems occured. I tried to execute the daemons from the command line. Same problem (so probably nor Debian 'infrastructure-ä problem). Classic UI shows that the next execution time of the tests is in the past.

I discussed this problem with dnsmichi on:

http://monitoring-portal.org/wbb/index.php?page=Thread&threadID=35118&s=695ee70222b136e7ff55c085492aae2a0c5f0873

I add a few files: debug logs, check logs and a troubleshoot file. I failed to create the backtrace - too many errors and the output looks useless.

Can you help me. If I should provide more information please let me know.

Thanks, Dieter

**Attachments**

* [debug1.log](https://dev.icinga.com/attachments/download/3028/debug1.log) rddisc - _2016-01-23 14:30:51 +00:00_
* [debug2.log](https://dev.icinga.com/attachments/download/3029/debug2.log) rddisc - _2016-01-23 14:30:51 +00:00_
* [icinga1.log](https://dev.icinga.com/attachments/download/3030/icinga1.log) rddisc - _2016-01-23 14:30:52 +00:00_
* [icinga2.log](https://dev.icinga.com/attachments/download/3031/icinga2.log) rddisc - _2016-01-23 14:30:52 +00:00_
* [trouble.txt](https://dev.icinga.com/attachments/download/3032/trouble.txt) rddisc - _2016-01-23 14:30:52 +00:00_
* [gdb-output.txt](https://dev.icinga.com/attachments/download/3033/gdb-output.txt) rddisc - _2016-01-23 20:08:19 +00:00_

**Comment by dnsmichi** [comment]
Unfortunately there was no further feedback received. I'm closing here.
