### ISSUE TITLE
[dev.icinga.com #11036] Cluster config sync does not sync empty files

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3877]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11036

**Created by mfriedrich on 2016-01-26 11:25:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-09 14:52:16 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

It must not sync the ".authoritative" file which is empty by default.

Steps to reproduce:

    cd /etc/icinga2/zones.d/master
    touch hosts.conf
    service icinga2 restart

---

**Relations**:

* relates [#11036](https://dev.icinga.com/issues/11036)

**Comment by dnsmichi** [comment]
Not a bug.
