### ISSUE TITLE
[dev.icinga.com #11097] Recheck host status if host is DOWN and service check changes to OK

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3901]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11097

**Created by ricardo on 2016-02-05 08:21:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-18 14:08:31 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

As far as I can remember Icinga1 schedules a host Check if a Service Check changes to OK in case the Host is in State != UP

This would be very helpful for faster host recovery.

Cheers
Ricardo

**Comment by dnsmichi** [comment]
Imagine that you have 50 services for a single host. Should all services which are checked every 5 seconds enforce an asynchronous host check? That would cause a) too many host checks b) events and state history confusion by frontend users.

The old world used to depend and wait on a host check, which Icinga 2 does not.

**Comment by dnsmichi** [comment]
See #4879.
