### ISSUE TITLE
[dev.icinga.com #11102] Enhance development docs w/ gdb pretty printers

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3904]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11102

**Created by mfriedrich on 2016-02-05 19:30:47 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-11-25 14:29:34 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

-   use expandpath instead of hardcoded paths
-   update gdbinit
-   Explain regression on RHEL7 with gdb (https://bugzilla.redhat.com/show\_bug.cgi?id=1085576)

    [root@e4e752bf970b v6]# gdb --version
    GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    For bug reporting instructions, please see:
    .

    [root@e4e752bf970b v6]# diff -ur /usr/share/gdb/python/gdb/command/type_printers.py.orig /usr/share/gdb/python/gdb/command/type_printers.py
    --- /usr/share/gdb/python/gdb/command/type_printers.py.orig 2016-02-05 16:40:44.968643929 +0000
    +++ /usr/share/gdb/python/gdb/command/type_printers.py  2016-02-05 16:40:52.138836651 +0000
    @@ -47,7 +47,7 @@
             sep = ''
             for objfile in gdb.objfiles():
                 if objfile.type_printers:
    -                print ("%sType printers for %s:" % (sep, objfile.name))
    +                print ("%sType printers for %s:" % (sep, objfile.filename))
                     self.list_type_printers(objfile.type_printers)
                     sep = '\n'
             if gdb.current_progspace().type_printers:

Though that does not entirely solve the issue.

      m_SSLContext = (boost::shared_ptr) (count 1, weak count 1) 0x7fffd001fa70,
    Python Exception  'gdb.Type' object has no attribute 'name':
      m_Servers = std::set with 0 elements,
    Python Exception  'gdb.Type' object has no attribute 'name':
      m_AnonymousClients = std::set with 0 elements,
    Python Exception  'gdb.Type' object has no attribute 'name':
      m_HttpClients = std::set with 0 elements,
      m_Timer = (boost::intrusive_ptr) 0x0,

**Comment by dnsmichi** [comment]
It's not that relevant anymore, since gdb on el7 is still buggy in terms of pretty printing.
