### ISSUE TITLE
[dev.icinga.com #11121] Old service not deleted with 'node update-config'

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3914]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11121

**Created by GreenRover on 2016-02-09 13:33:41 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-14 13:05:57 +00:00 (in Redmine)_

    Icinga Version: r2.4.1-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello i have a central icinga2 with some icinga2 nodes.
The central has no own services. All services are configured at the single nodes.

Here is a screenshot of my central.
![Auswahl_099.png](https://dev.icinga.com/attachments/download/3080/Auswahl_099.png)

But this services is dont exist any more on my node.

This is from central icinga:

    icinga2 node list | grep "portal-***'" -A 10
        * Host 'portal-***'
            * Service 'Linux CPU'
            * Service 'Linux Disk /disk'
            * Service 'Linux Mem 1G free'
            * Service 'Linux SSH'
            * Service 'Linux Uptime'
            * Service 'Portal 2'
            * Service 'Portal 3 P1 watchdogServer'
            * Service 'Portal 3 WebsocketServer'
            * Service 'Portal 3 in 2'
        * Host 'portal-***-nortel'

    {
        attrs: {
            __name: "portal-HOST!Linux Mem 500M free",
            acknowledgement: 0,
            acknowledgement_expiry: 0,
            action_url: "",
            active: true,
            check_attempt: 1,
            check_command: "dummy",
            check_interval: 300,
            display_name: "Linux Mem 500M free",
            enable_active_checks: true,
            enable_event_handler: true,
            enable_flapping: false,
            enable_notifications: true,
            enable_passive_checks: true,
            enable_perfdata: true,
            flapping: false,
            flapping_last_change: 1454565216.141664,
            flapping_negative: 300,
            flapping_positive: 0,
            flapping_threshold: 30,
            force_next_check: true,
            force_next_notification: false,
            groups: [],
            ha_mode: 0,
            host_name: "portal-HOST",
            icon_image: "",
            icon_image_alt: "",
            last_check: 1454565245.830987,
            last_check_result: {
                active: true,
                check_source: "portal-***",
                command: [
                    "/usr/lib/nagios/plugins/check_netsnmp_memory.pl",
                    "--perfparse",
                    "-2",
                    "-A",
                    "user,cached,buffer,avail_real,%used_real,%user_real,%cached_real,%avail_real",
                    "-C",
                    "public",
                    "-H",
                    "172.18.8.167",
                    "-L",
                    "'Memory Utilization",
                    "-a",
                    "free_real",
                    "-c",
                    "^<250",
                    "-w",
                    "<500"
                ],
                execution_end: 1454565245.830855,
                execution_start: 1454565235.59128,
                exit_status: 3,
                output: "ERROR: snmp get_request failed - No response from remote host "
                172.18 .8 .167 ".",
                performance_data: [],
                schedule_end: 1454565245.830987,
                schedule_start: 1454565535.5900002,
                state: 3,
                type: "CheckResult",
                vars_after: {
                    attempt: 1,
                    reachable: true,
                    state: 3,
                    state_type: 1
                },
                vars_before: {
                    attempt: 1,
                    reachable: true,
                    state: 3,
                    state_type: 1
                }
            },
            last_hard_state: 3,
            last_hard_state_change: 1454506506.628859,
            last_in_downtime: false,
            last_reachable: true,
            last_state: 3,
            last_state_change: 1454505606.697552,
            last_state_critical: 0,
            last_state_ok: 1454504448.802882,
            last_state_type: 1,
            last_state_unknown: 1454565216.141649,
            last_state_unreachable: 0,
            last_state_warning: 1454419550.286034,
            max_check_attempts: 3,
            name: "Linux Mem 500M free",
            next_check: 1455023727,
            notes: "",
            notes_url: "",
            original_attributes: null,
            package: "_etc",
            paused: false,
            retry_interval: 60,
            state: 3,
            state_type: 1,
            templates: [
                "Linux Mem 500M free",
                "satellite-service"
            ],
            type: "Service",
            vars: {
                notification: {
                    mail: {
                        groups: [
                            "icingaadmins"
                        ]
                    }
                }
            },
            version: 0,
            volatile: false,
            zone: "portal-***"
        },
        joins: {},
        meta: {},
        name: "portal-HOST!Linux Mem 500M free",
        type: "Service"
    },

I have done allready: "icinga2 node update-config" without improvement.

**Attachments**

* [Auswahl_099.png](https://dev.icinga.com/attachments/download/3080/Auswahl_099.png) GreenRover - _2016-02-09 13:26:50 +00:00_
* [repository.tgz](https://dev.icinga.com/attachments/download/3202/repository.tgz) GreenRover - _2016-03-14 09:00:25 +00:00_

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Relations**:

* relates [#11121](https://dev.icinga.com/issues/11121)
* relates [#11121](https://dev.icinga.com/issues/11121)

**Comment by dnsmichi** [comment]
#4799
