### ISSUE TITLE
[dev.icinga.com #11124] Node wizard behaviour with public and private key

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3917]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11124

**Created by jflach on 2016-02-09 15:26:11 +00:00**

Assignee: _jflach_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-03-18 13:37:35 +00:00 (in Redmine)_

    Icinga Version: 2.5.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

When one runs 'icinga2 node wizard' without a certificate but with a private key in /etc/icinga2/pki, it does nothing and there is no helpful error message

**Comment by dnsmichi** [comment]
Rough edge case, nothing we should worry about for the time being.
