### ISSUE TITLE
[dev.icinga.com #11125] Commenting out objects causes critical/config: Error: memory exhausted

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3918]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11125

**Created by sebastic on 2016-02-09 16:06:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-06 14:33:27 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Validating the configuration with \`@icinga2 daemon -C@\` reports "`critical/config: Error: memory exhausted`" when several objects are commented out in a configuration file.

Uncommenting the objects allows the validation to succeed.

The attached configuration triggers this issue with icinga2 2.4.1 from the icinga-stable-release repository.

**Attachments**

* [comment-test.conf](https://dev.icinga.com/attachments/download/3084/comment-test.conf) sebastic - _2016-02-09 16:02:45 +00:00_

**Comment by dnsmichi** [comment]
Acknowledged, but this isn't easy to fix.
