### ISSUE TITLE
[dev.icinga.com #11134] Add threshold(s) to "ido" CheckCommand

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3924]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11134

**Created by tobiasvdk on 2016-02-10 20:39:33 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _Backlog_
Last Update: _2016-12-16 17:16:35 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Currently the [ido](http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/icinga-template-library#itl-icinga-ido) CheckCommand has no threshold. It would be nice to be able to configure the following thresholds:

-   warning: queue is empty in more then X seconds
-   critical: queue is empty in more then X seconds / or empty in infinite time

**Changesets**

_2016-06-24 09:42:20 +00:00_ by _mfriedrich_ 046807ef108f7acc22b487e83e7c1b6ae0227134

    WIP: Thresholds for the 'ido' check
    
    refs #11134

**Comment by dnsmichi** [comment]
Re-evaluation needed after the WQ changes in 2.7.0.
