### ISSUE TITLE
[dev.icinga.com #11135] Removed checks no longer in config persisting in UI

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3925]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11135

**Created by vsakhart on 2016-02-10 22:09:00 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2016-08-08 15:41:09 +00:00_)
Target Version: _(none)_
Last Update: _2016-08-08 15:41:09 +00:00 (in Redmine)_

    Icinga Version: 2.4.1

---

Hello,

Recently, we updated several of our service checks in the config and renamed some of the checks. After that happened we noticed that a lot of our old checks continued to be seen in the UI and stuck in a warning or pending state despite no longer being in the config any more.

For some of the checks we renamed, the old checks remain in the UI and are stuck in the pending state. If I try to acknowledge this check and click on the check when the service is critical, the option is not available in the UI. I can only set downtime because the UI will only direct me to the old, non functional check that is stuck in pending.

Note: I am not having any of these issue with the classic-ui, as the classic-ui does not show any old checks as pending/warning as seen in the screenshots below

The Icinga cluster has 2 nodes, each running icinga2 and icingaweb2 in a high availability set up. The icinga2 web version is 2.1.2 and icinga2 version is 2.4.1.

**Attachments**

* [icinga2pending.png](https://dev.icinga.com/attachments/download/3087/icinga2pending.png) vsakhart - _2016-02-10 22:08:11 +00:00_
* [icingaclassic1.png](https://dev.icinga.com/attachments/download/3088/icingaclassic1.png) vsakhart - _2016-02-10 22:08:20 +00:00_
* [icinga2warning.png](https://dev.icinga.com/attachments/download/3089/icinga2warning.png) vsakhart - _2016-02-10 22:08:29 +00:00_
* [icingaclassicnowarning.png](https://dev.icinga.com/attachments/download/3090/icingaclassicnowarning.png) vsakhart - _2016-02-10 22:08:43 +00:00_

---

**Relations**:

* relates [#11400](https://dev.icinga.com/issues/11400)

**Comment by relgames** [comment]
Hi, what is the progress on this issue? It happens for us as well.
Checks are gone from Icinga API but are still visible on Icinga UI.

**Comment by dnsmichi** [comment]
Please don't bump 3 year old closed issues, join the community forums first with your question: https://community.icinga.com

**Comment by relgames** [comment]
Thanks, I made a new topic https://community.icinga.com/t/icinga-web-shows-checks-which-are-deleted-from-icinga-backend-api/1231

**Comment by relgames** [comment]
Most likely related to https://github.com/Icinga/icinga2/issues/6012
