### ISSUE TITLE
[dev.icinga.com #11146] Unit test for LegacyTimePeriod

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3931]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11146

**Created by atj on 2016-02-11 15:06:51 +00:00**

Assignee: _atj_
Status: _Assigned_  (closed on _2016-05-11 07:26:41 +00:00_)
Target Version: _(none)_
Last Update: _2016-05-20 10:17:08 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Whilst fixing [\#11132](https://dev.icinga.com/issues/11132) I wrote a unit test for LegacyTimePeriod, which I have attached. The patch includes some additional tests for the "day X" and "day -X" timespecs, which are currently failing:

    Test project /home/ajames/Sources/icinga2/build
    Constructing a list of tests
    Done constructing a list of tests
    Checking test dependency graph...
    Checking test dependency graph end
    test 58
        Start 58: base-icinga_legacytimeperiod/simple

    58: Test command: /home/ajames/Sources/icinga2/build/Bin/Release/boosttest-test-base "--run_test=icinga_legacytimeperiod/simple" "--catch_system_error=yes"
    58: Test timeout computed to be: 1500
    58: Running 1 test case...
    58: /home/ajames/Sources/icinga2/test/icinga-legacytimeperiod.cpp(82): error: in "icinga_legacytimeperiod/simple": check mktime(&beg) == (time_t) 1343689200 has failed [1343520000 != 1343689200]
    58: /home/ajames/Sources/icinga2/test/icinga-legacytimeperiod.cpp(83): error: in "icinga_legacytimeperiod/simple": check mktime(&end) == (time_t) 1346367600 has failed [1343606400 != 1346367600]
    58: /home/ajames/Sources/icinga2/test/icinga-legacytimeperiod.cpp(88): error: in "icinga_legacytimeperiod/simple": check mktime(&beg) == (time_t) 1456704000 has failed [1456531200 != 1456704000]
    58: /home/ajames/Sources/icinga2/test/icinga-legacytimeperiod.cpp(89): error: in "icinga_legacytimeperiod/simple": check mktime(&end) == (time_t) 1456790400 has failed [1456617600 != 1456790400]
    58: 
    58: *** 4 failures are detected in the test module "icinga2_test"
    1/1 Test #58: base-icinga_legacytimeperiod/simple ...***Failed    0.05 sec

    0% tests passed, 1 tests failed out of 1

    Total Test time (real) =   0.05 sec

    The following tests FAILED:
         58 - base-icinga_legacytimeperiod/simple (Failed)
    Errors while running CTest

The returned values are the second to last day of the month. A separate issue will be created to address this.

Please review the patch and confirm if it is acceptable. I will write some additional tests if so as it seems like there are some bugs lurking in the code.

**Attachments**

* [legacytimeperiod-unit-test.patch](https://dev.icinga.com/attachments/download/3094/legacytimeperiod-unit-test.patch) atj - _2016-02-11 15:06:40 +00:00_ - _Version 1_
* [0001-Add-unit-test-for-LegacyTimePeriod.patch](https://dev.icinga.com/attachments/download/3383/0001-Add-unit-test-for-LegacyTimePeriod.patch) atj - _2016-05-20 10:10:52 +00:00_

**Changesets**

_2016-05-11 07:23:39 +00:00_ by _atj_ 1246d7dda334859ee136198b8285f5f4f9504b59

    Implement unit tests for the time period parser
    
    fixes #11146

_2016-05-11 16:12:20 +00:00_ by _(unknown)_ fc889eb9ad1e16aa06eb84369931ea9372f05563

    Revert "Implement unit tests for the time period parser"
    
    This reverts commit 1246d7dda334859ee136198b8285f5f4f9504b59.
    
    refs #11146

---

**Relations**:

* relates [#11146](https://dev.icinga.com/issues/11146)

**Comment by Crunsher** [comment]
Fixed #11146
