### ISSUE TITLE
[dev.icinga.com #11150] Allow downtimes to apply on child hosts

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3935]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11150

**Created by Napsty on 2016-02-12 07:15:20 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-03-04 14:39:51 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

In my setup I have created a child-parent-dependency like this:

    #################################################################
    ## APPLY RULES FOR CHILD-PARENT-DEPENDENCY
    ## http://www.claudiokuenzler.com/blog/607/icinga2-multiple-parents-dependency-apply-rule
    #################################################################
    apply Dependency "Parent" for (parent in host.vars.parents) to Host {
      parent_host_name = parent
      assign where host.vars.parents
    }

    object Host "childhost1" {
      import "host-linux-test"
      address = "x.x.x.x"
      vars.parents = ["parent1"]

This works correctly with one or more parent entries in the array.

Now what I'd like to achieve is to apply a downtime to the parent and use a flag to apply the downtime to the children, too.
It would be great to add a flag (e.g. apply\_on\_children = true) and then Icinga 2 applies the downtime to the child hosts, too.
In Nagios this was/is already the case when creating a new downtime (for ex: Child Hosts: Schedule triggered downtime for all child hosts).

**Comment by Crunsher** [comment]
Related #6244

**Comment by dnsmichi** [comment]
![img_0446](https://user-images.githubusercontent.com/382049/39237317-774cda0e-487b-11e8-9573-e31fefdad0a9.jpg)

**Comment by netphantm** [comment]
I think this can be closed, as it's already implemented?

**Comment by dnsmichi** [comment]
True, thanks for bringing this up 👍
