### ISSUE TITLE
[dev.icinga.com #11172] Lots of close(*) = -1 EBADF (Bad file descriptor)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3943]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11172

**Created by tgelf on 2016-02-17 07:31:40 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2016-02-23 13:34:43 +00:00_)
Target Version: _(none)_
Last Update: _2016-02-23 14:38:22 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

icinga-app/icinga.cpp does:

        if (getrlimit(RLIMIT_NOFILE, &rl) >= 0) {
            rlim_t maxfds = rl.rlim_max;

            if (maxfds == RLIM_INFINITY)
                maxfds = 65536;

            for (rlim_t i = 3; i < maxfds; i++) {
                int rc = close(i);

This results in a lot of noise:

    getrlimit(RLIMIT_NOFILE, {rlim_cur=16*1024, rlim_max=16*1024}) = 0
    close(3)                                = -1 EBADF (Bad file descriptor)
    close(4)                                = -1 EBADF (Bad file descriptor)
    close(5)                                = -1 EBADF (Bad file descriptor)
    close(6)                                = -1 EBADF (Bad file descriptor)
    close(7)                                = -1 EBADF (Bad file descriptor)
    ...
    close(16380)                            = -1 EBADF (Bad file descriptor)
    close(16381)                            = -1 EBADF (Bad file descriptor)
    close(16382)                            = -1 EBADF (Bad file descriptor)
    close(16383)                            = -1 EBADF (Bad file descriptor)

Thanks to kobmaki for pointing me to this.

Cheers,
Thomas

**Comment by bobapple** [comment]
I have the same issue with the current master

```shell
[...]
brk(NULL)                               = 0x17fa000
brk(0x182c000)                          = 0x182c000
futex(0x7f314c4061ac, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f314c4061b8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(0x184d000)                          = 0x184d000
getrlimit(RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=1024*1024}) = 0
close(3)                                = -1 EBADF (Bad file descriptor)
close(4)                                = -1 EBADF (Bad file descriptor)
close(5)                                = -1 EBADF (Bad file descriptor)
close(6)                                = -1 EBADF (Bad file descriptor)
close(7)                                = -1 EBADF (Bad file descriptor)
close(8)                                = -1 EBADF (Bad file descriptor)
close(9)                                = -1 EBADF (Bad file descriptor)
close(10)                               = -1 EBADF (Bad file descriptor)
close(11)                               = -1 EBADF (Bad file descriptor)
close(12)                               = -1 EBADF (Bad file descriptor)
close(13)                               = -1 EBADF (Bad file descriptor)
close(14)                               = -1 EBADF (Bad file descriptor)
close(15)                               = -1 EBADF (Bad file descriptor)
close(16)                               = -1 EBADF (Bad file descriptor)
close(17)                               = -1 EBADF (Bad file descriptor)
close(18)                               = -1 EBADF (Bad file descriptor)
close(19)                               = -1 EBADF (Bad file descriptor)
close(20)                               = -1 EBADF (Bad file descriptor)
close(21)                               = -1 EBADF (Bad file descriptor)
close(22)                               = -1 EBADF (Bad file descriptor)
close(23)                               = -1 EBADF (Bad file descriptor)
close(24)                               = -1 EBADF (Bad file descriptor)
close(25)                               = -1 EBADF (Bad file descriptor)
close(26)                               = -1 EBADF (Bad file descriptor)
close(27)                               = -1 EBADF (Bad file descriptor)
[...]
```

**Comment by dnsmichi** [comment]
I'm following @gunnarbeutner here, this is not a bug. We really need to ensure to close all file descriptors, especially on a reload. Otherwise we would leak them.
