### ISSUE TITLE
[dev.icinga.com #11191] On satellite: Error while reading JSON-RPC message

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3951]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11191

**Created by Napsty on 2016-02-19 14:31:35 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-03-18 12:57:30 +00:00_)
Target Version: _(none)_
Last Update: _2016-03-18 13:29:43 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

I created a new distributed monitoring setup with a master (icinga-master) and a satellite server icinga-satellite . I followed the following howtos:
https://wiki.icinga.org/display/howtos/Icinga2+Distributed+Cluster+Install+with+CentOS+6
http://docs.icinga.org/icinga2/latest/doc/module/icinga2/toc\#!/icinga2/latest/doc/module/icinga2/chapter/distributed-monitoring-high-availability#cluster-scenarios-distributed-zones
https://redmine.sberg.net/projects/open-sberg-wiki/wiki/Icinga2\_Checker\_Satellite\_und\_Master

I got it working that the zone's configuration was sent to the satellite server, but not the global-templates. They never appear on the satellite, hence causing errors that the template for the host is not found.

As soon as I reload the config on the master, I get the following error message on the satellite. It looks like there is an error in the information sent from the master which the satellite is unable to read:

    [2016-02-19 15:21:05 +0100] information/ApiListener: New client connection for identity 'icinga-master'
    [2016-02-19 15:21:10 +0100] information/ApiListener: New client connection for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'icinga-master': Error: std::exception

        (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7f6e59434c67]
        (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7f6e59434d10]
        (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7f6e593d1d2c]
        (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x83) [0x7f6e593d1eb3]
        (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x7c) [0x7f6e593e19ac]
        (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7f6e593f00ce]
        (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7f6e568f8cad]
        (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7f6e569199f5]
        (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7f6e56936848]
        (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1cc) [0x7f6e59468f2c]
        (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x30) [0x7f6e59417620]
        (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3a8) [0x7f6e59417b08]
        (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7f6e594146aa]
        (13) libboost_thread.so.1.54.0:  (+0xba4a) [0x7f6e59d7da4a]
        (14) libpthread.so.0:  (+0x8182) [0x7f6e596ea182]
        (15) libc.so.6: clone (+0x6d) [0x7f6e5855747d]

    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'icinga-master': Error: std::exception

        (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7f6e59434c67]
        (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7f6e59434d10]
        (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7f6e593d1d2c]
        (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x83) [0x7f6e593d1eb3]
        (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x7c) [0x7f6e593e19ac]
        (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7f6e593f00ce]
        (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7f6e568f8cad]
        (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7f6e569199f5]
        (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7f6e56936848]
        (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1cc) [0x7f6e59468f2c]
        (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x30) [0x7f6e59417620]
        (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3a8) [0x7f6e59417b08]
        (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7f6e594146aa]
        (13) libboost_thread.so.1.54.0:  (+0xba4a) [0x7f6e59d7da4a]
        (14) libpthread.so.0:  (+0x8182) [0x7f6e596ea182]
        (15) libc.so.6: clone (+0x6d) [0x7f6e5855747d]

    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'icinga-master': Error: std::exception

        (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7f6e59434c67]
        (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7f6e59434d10]
        (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7f6e593d1d2c]
        (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x83) [0x7f6e593d1eb3]
        (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x7c) [0x7f6e593e19ac]
        (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7f6e593f00ce]
        (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7f6e568f8cad]
        (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7f6e569199f5]
        (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7f6e56936848]
        (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1cc) [0x7f6e59468f2c]
        (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x30) [0x7f6e59417620]
        (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3a8) [0x7f6e59417b08]
        (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7f6e594146aa]
        (13) libboost_thread.so.1.54.0:  (+0xba4a) [0x7f6e59d7da4a]
        (14) libpthread.so.0:  (+0x8182) [0x7f6e596ea182]
        (15) libc.so.6: clone (+0x6d) [0x7f6e5855747d]

    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'icinga-master': Error: std::exception

        (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7f6e59434c67]
        (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7f6e59434d10]
        (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7f6e593d1d2c]
        (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x83) [0x7f6e593d1eb3]
        (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x7c) [0x7f6e593e19ac]
        (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7f6e593f00ce]
        (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7f6e568f8cad]
        (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7f6e569199f5]
        (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7f6e56936848]
        (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1cc) [0x7f6e59468f2c]
        (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x30) [0x7f6e59417620]
        (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3a8) [0x7f6e59417b08]
        (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7f6e594146aa]
        (13) libboost_thread.so.1.54.0:  (+0xba4a) [0x7f6e59d7da4a]
        (14) libpthread.so.0:  (+0x8182) [0x7f6e596ea182]
        (15) libc.so.6: clone (+0x6d) [0x7f6e5855747d]

    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'icinga-master': Error: std::exception

        (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7f6e59434c67]
        (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7f6e59434d10]
        (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7f6e593d1d2c]
        (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x83) [0x7f6e593d1eb3]
        (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x7c) [0x7f6e593e19ac]
        (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7f6e593f00ce]
        (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7f6e568f8cad]
        (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7f6e569199f5]
        (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7f6e56936848]
        (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1cc) [0x7f6e59468f2c]
        (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x30) [0x7f6e59417620]
        (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3a8) [0x7f6e59417b08]
        (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7f6e594146aa]
        (13) libboost_thread.so.1.54.0:  (+0xba4a) [0x7f6e59d7da4a]
        (14) libpthread.so.0:  (+0x8182) [0x7f6e596ea182]
        (15) libc.so.6: clone (+0x6d) [0x7f6e5855747d]

    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'icinga-master': Error: std::exception

        (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7f6e59434c67]
        (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7f6e59434d10]
        (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7f6e593d1d2c]
        (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x83) [0x7f6e593d1eb3]
        (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x7c) [0x7f6e593e19ac]
        (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7f6e593f00ce]
        (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7f6e568f8cad]
        (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7f6e569199f5]
        (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7f6e56936848]
        (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1cc) [0x7f6e59468f2c]
        (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x30) [0x7f6e59417620]
        (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3a8) [0x7f6e59417b08]
        (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7f6e594146aa]
        (13) libboost_thread.so.1.54.0:  (+0xba4a) [0x7f6e59d7da4a]
        (14) libpthread.so.0:  (+0x8182) [0x7f6e596ea182]
        (15) libc.so.6: clone (+0x6d) [0x7f6e5855747d]

    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'icinga-master': Error: std::exception

        (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7f6e59434c67]
        (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7f6e59434d10]
        (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7f6e593d1d2c]
        (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x83) [0x7f6e593d1eb3]
        (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x7c) [0x7f6e593e19ac]
        (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7f6e593f00ce]
        (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7f6e568f8cad]
        (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7f6e569199f5]
        (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7f6e56936848]
        (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1cc) [0x7f6e59468f2c]
        (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x30) [0x7f6e59417620]
        (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3a8) [0x7f6e59417b08]
        (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7f6e594146aa]
        (13) libboost_thread.so.1.54.0:  (+0xba4a) [0x7f6e59d7da4a]
        (14) libpthread.so.0:  (+0x8182) [0x7f6e596ea182]
        (15) libc.so.6: clone (+0x6d) [0x7f6e5855747d]

    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'icinga-master': Error: std::exception

        (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7f6e59434c67]
        (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7f6e59434d10]
        (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7f6e593d1d2c]
        (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x83) [0x7f6e593d1eb3]
        (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x7c) [0x7f6e593e19ac]
        (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7f6e593f00ce]
        (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7f6e568f8cad]
        (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7f6e569199f5]
        (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7f6e56936848]
        (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1cc) [0x7f6e59468f2c]
        (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x30) [0x7f6e59417620]
        (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3a8) [0x7f6e59417b08]
        (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7f6e594146aa]
        (13) libboost_thread.so.1.54.0:  (+0xba4a) [0x7f6e59d7da4a]
        (14) libpthread.so.0:  (+0x8182) [0x7f6e596ea182]
        (15) libc.so.6: clone (+0x6d) [0x7f6e5855747d]

    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: Error while reading JSON-RPC message for identity 'icinga-master': Error: std::exception

        (0) libbase.so: void boost::throw_exception(icinga::openssl_error const&) (+0x97) [0x7f6e59434c67]
        (1) libbase.so: void boost::exception_detail::throw_exception_(icinga::openssl_error const&, char const*, char const*, int) (+0x40) [0x7f6e59434d10]
        (2) libbase.so: icinga::TlsStream::HandleError() const (+0xbc) [0x7f6e593d1d2c]
        (3) libbase.so: icinga::TlsStream::Read(void*, unsigned long, bool) (+0x83) [0x7f6e593d1eb3]
        (4) libbase.so: icinga::StreamReadContext::FillFromStream(boost::intrusive_ptr const&, bool) (+0x7c) [0x7f6e593e19ac]
        (5) libbase.so: icinga::NetString::ReadStringFromStream(boost::intrusive_ptr const&, icinga::String*, icinga::StreamReadContext&, bool) (+0xce) [0x7f6e593f00ce]
        (6) libremote.so: icinga::JsonRpc::ReadMessage(boost::intrusive_ptr const&, boost::intrusive_ptr*, icinga::StreamReadContext&, bool) (+0x3d) [0x7f6e568f8cad]
        (7) libremote.so: icinga::JsonRpcConnection::ProcessMessage() (+0x65) [0x7f6e569199f5]
        (8) libremote.so: icinga::JsonRpcConnection::DataAvailableHandler() (+0x38) [0x7f6e56936848]
        (9) libbase.so: boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (+0x1cc) [0x7f6e59468f2c]
        (10) libbase.so: icinga::Stream::SignalDataAvailable() (+0x30) [0x7f6e59417620]
        (11) libbase.so: icinga::TlsStream::OnEvent(int) (+0x3a8) [0x7f6e59417b08]
        (12) libbase.so: icinga::SocketEvents::ThreadProc() (+0x23a) [0x7f6e594146aa]
        (13) libboost_thread.so.1.54.0:  (+0xba4a) [0x7f6e59d7da4a]
        (14) libpthread.so.0:  (+0x8182) [0x7f6e596ea182]
        (15) libc.so.6: clone (+0x6d) [0x7f6e5855747d]

    [2016-02-19 15:21:12 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga-master'
    [2016-02-19 15:21:12 +0100] information/ApiListener: New client connection for identity 'icinga-master'
    [2016-02-19 15:21:17 +0100] information/ApiListener: New client connection for identity 'icinga-master'

Can anyone confirm?

Version information on master:

    icinga2 - The Icinga 2 network monitoring daemon (version: r2.4.1-1)

    Copyright (c) 2012-2015 Icinga Development Team (https://www.icinga.org)
    License GPLv2+: GNU GPL version 2 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Application information:
      Installation root: /usr
      Sysconf directory: /etc
      Run directory: /run
      Local state directory: /var
      Package data directory: /usr/share/icinga2
      State path: /var/lib/icinga2/icinga2.state
      Modified attributes path: /var/lib/icinga2/modified-attributes.conf
      Objects path: /var/cache/icinga2/icinga2.debug
      Vars path: /var/cache/icinga2/icinga2.vars
      PID path: /run/icinga2/icinga2.pid

    System information:
      Platform: _NAME="Ubuntu 14.04.4 LTS
      Platform version: ID="14.04
      Kernel: Linux
      Kernel version: 3.16.0-55-generic
      Architecture: x86_64

Version information on satellite:

    icinga2 - The Icinga 2 network monitoring daemon (version: r2.4.1-1)

    Copyright (c) 2012-2015 Icinga Development Team (https://www.icinga.org)
    License GPLv2+: GNU GPL version 2 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Application information:
      Installation root: /usr
      Sysconf directory: /etc
      Run directory: /run
      Local state directory: /var
      Package data directory: /usr/share/icinga2
      State path: /var/lib/icinga2/icinga2.state
      Modified attributes path: /var/lib/icinga2/modified-attributes.conf
      Objects path: /var/cache/icinga2/icinga2.debug
      Vars path: /var/cache/icinga2/icinga2.vars
      PID path: /run/icinga2/icinga2.pid

    System information:
      Platform: _NAME="Ubuntu 14.04.4 LTS
      Platform version: ID="14.04
      Kernel: Linux
      Kernel version: 3.19.0-25-generic
      Architecture: x86_64

**Comment by ricky33000** [comment]
'apt install chrony' on master, satellite and client hosts solve the  issue "Error while reading JSON-RPC message for identity 'example.com': Error: stream truncated" for me.
It seems that json rpc connexion need right ntp sync.
