### ISSUE TITLE
[dev.icinga.com #11208] CMake does not find MySQL libraries on Windows

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3960]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11208

**Created by jflach on 2016-02-23 15:02:43 +00:00**

Assignee: _jflach_
Status: _Resolved_  (closed on _2016-02-23 15:09:09 +00:00_)
Target Version: _2.4.4_
Last Update: _2016-03-15 13:37:00 +00:00 (in Redmine)_

    Icinga Version: 2.5.0
    Backport?: Already backported
    Include in Changelog: 0

---

To fix in third-party/CMake

**Changesets**

_2016-02-23 15:08:58 +00:00_ by _jflach_ 0c837e30e81859dcdd4cefbe4483f525d1cb91ff

    Fix CMake not finding mysql libs on Windows
    
    fixes #11208

_2016-03-11 14:59:23 +00:00_ by _jflach_ 397c0ada954042ddf4d70dc0c2c51686a10e4685

    Fix CMake not finding mysql libs on Windows
    
    fixes #11208

**Comment by dsutherland1492** [comment]
There doesn't appear to be steps in the development guide for enabling MYSQL and PGSQL for cmake without receiving the above error.  Is it possible to build with these modules enabled on Windows?  If so, what exactly needs to be installed library wise.

**Comment by dnsmichi** [comment]
Please don't bump old issues, rather ask at https://community.icinga.com

In all shortness - Windows is only supported as agent, and as such we've stopped looking into specific feature support or development guides in this regard.
