### ISSUE TITLE
[dev.icinga.com #11285] Enhance CSR-Autosigning error handling

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3994]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11285

**Created by mfriedrich on 2016-03-03 09:33:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:52:19 +00:00 (in Redmine)_

    Icinga Version: 2.4.3
    Backport?: Not yet backported
    Include in Changelog: 1

---

Do not send an empty certificate body, but instead catch the thrown error (e.g. serial.txt cannot be written, or certificate cannot be signed). The client sould receive those errors in a readable format.

---

**Relations**:

* relates [#11200](https://dev.icinga.com/issues/11200)

**Comment by dnsmichi** [comment]
Part of #5450
