### ISSUE TITLE
[dev.icinga.com #11291] Add minimal version to icinga check

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3998]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11291

**Created by twidhalm on 2016-03-03 13:26:07 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _Backlog_
Last Update: _2016-11-09 14:52:18 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

Please add a possibility to the embedded `icinga` check command to set a minimum version via argument so the check becomes warning when the version is lower than given.

This could be very handy if a critical bug is found in a version and users don't have a way to automatically update but use Icinga 2 to check which nodes still need upgrading.

Cheers,
Thomas

---

**Relations**:

* duplicates [#11291](https://dev.icinga.com/issues/11291)

**Comment by dnsmichi** [comment]
Versions are set through packages and differ.

- the default uses `v2.7.1`
- Debian packages use `r2.7.1`
- git compiled versions add `-COMMITCOUNT-gCOMMIT; debug`

If one adds comparisons, how should one treat snapshot versions?

**Comment by dgoetz** [comment]
Version comparison for packages compare the character at the same position and if additional characters are added it is a newer version, so a snapshot should be newer than the releases before it.

For comparing snapshots it would require knowledge of git which adds to much of a complexity I think so I would not bother about older or newer, only about exact match. I think this would also match typical support scenarios where you want to have everywhere the snapshot which fixes the problem or newer releases.

**Comment by dnsmichi** [comment]
Utility::CompareVersion() already exists, the rest is more or less string parsing.

**Comment by dnsmichi** [comment]
<img width="620" alt="screen shot 2018-01-08 at 19 31 04" src="https://user-images.githubusercontent.com/382049/34686010-885b36bc-f4aa-11e7-8414-af3ca2a4fdc7.png">

**Comment by dnsmichi** [comment]
Hm, I think I adjust the output a bit.
