### ISSUE TITLE
[dev.icinga.com #11327] Windows wizard error "too many arguments"

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4008]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11327

**Created by setswei on 2016-03-08 05:35:15 +00:00**

Assignee: _jflach_
Status: _Resolved_  (closed on _2016-03-30 09:03:47 +00:00_)
Target Version: _2.4.4_
Last Update: _2016-06-28 17:55:23 +00:00 (in Redmine)_

    Icinga Version: 2.4.3
    Backport?: Already backported
    Include in Changelog: 1

---

Currently i am trying to setup icinga2 agent on Windows 10 Pro to monitor some specific services and i get this error " critical/cli: Too many arguments. At most 0 arguments may be specified. "

Is this currently a Bug with icinga2 on windows 10 or is it a OS issue/Configuration problem that i cant seem to find

i have checked the icinga2 logs and they dont show any errors and the service is running

any help here would be appreciated

**Attachments**

* [ScreenShot 1.jpg](https://dev.icinga.com/attachments/download/3189/ScreenShot%201.jpg) setswei - _2016-03-08 05:28:35 +00:00_ - _Agent Setup_
* [ScreenShot 2.jpg](https://dev.icinga.com/attachments/download/3190/ScreenShot%202.jpg) setswei - _2016-03-08 05:29:33 +00:00_ - _Agent Error_
* [ici1.jpg](https://dev.icinga.com/attachments/download/3210/ici1.jpg) dennie - _2016-03-15 12:41:09 +00:00_
* [ici2.jpg](https://dev.icinga.com/attachments/download/3212/ici2.jpg) dennie - _2016-03-15 12:41:47 +00:00_
* [ici3.jpg](https://dev.icinga.com/attachments/download/3213/ici3.jpg) dennie - _2016-03-15 12:43:17 +00:00_

**Changesets**

_2016-03-14 15:37:15 +00:00_ by _jflach_ 8f875dd51ff75591be17d0366234cbe5a620f93a

    Fix Windows Agent failing with special characters
    
    refs #11327

---

**Relations**:

* relates [#11327](https://dev.icinga.com/issues/11327)

**Comment by gr4ssi** [comment]
I just experienced this error with the version Icinga2-v2.6.3-x86_64.msi.
The reason seems to be, that when your instance name contains a blank (Icinga 2), then I get the error.
I switched my instance name to Icinga2 without a blank, then it worked.
@dnsmichi  , should I open a new  issue?
