### ISSUE TITLE
[dev.icinga.com #11335] Add HA support for the GelfWriter feature

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4013]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11335

**Created by bjoern812 on 2016-03-09 06:41:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-09 10:15:41 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

In a ha-cluster, if you enable the gelf writer on all nodes, each node is writing to the graylog server.
So messages are duplicated in the graylog-server. It would be nice, if only one node is writing.
If that node fails, another node should takeover and write to the graylog-server.

---

**Relations**:

* relates [#9117](https://dev.icinga.com/issues/9117)

**Comment by dnsmichi** [comment]
Same as #2941.
