### ISSUE TITLE
[dev.icinga.com #11353] Scheduled Downtime wrong dates in database

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4020]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11353

**Created by stefanwolff on 2016-03-10 13:22:30 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:58:51 +00:00 (in Redmine)_

    Icinga Version: 2.4.3.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Sorry for my bad English :)
I have defined scheduled downtimes and these downtimes are commited wrong to the database (mysql).

**icinga2 --version**

    System information:
      Platform: Ubuntu
      Platform version: 14.04.4 LTS, Trusty Tahr
      Kernel: Linux
      Kernel version: 3.19.0-51-generic
      Architecture: x86_64

**icinga2 feature list**
Disabled features: debuglog gelf icingastatus livestatus opentsdb perfdata syslog
Enabled features: api checker command compatlog graphite ido-mysql mainlog notification statusdata

**icinga2 daemon --validate**

    information/cli: Icinga application loader (version: r2.4.3-1)
    information/ConfigCompiler: Compiling config file: /etc/icinga2/icinga2.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/constants.conf
    information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/nscp
    information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-nscp-local.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.conf
    information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/itl
    information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command.conf
    information/Utility: Loading library 'libmethods.so'
    information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-icinga.conf
    information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/timeperiod.conf
    information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins
    information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-plugins.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/api.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/checker.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/command.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/compatlog.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/graphite.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/ido-mysql.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/mainlog.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/notification.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/statusdata.conf
    information/Utility: Loading library 'libchecker.so'
    information/Utility: Loading library 'libcompat.so'
    information/Utility: Loading library 'libcompat.so'
    information/Utility: Loading library 'libperfdata.so'
    information/Utility: Loading library 'libdb_ido_mysql.so'
    information/Utility: Loading library 'libnotification.so'
    information/Utility: Loading library 'libcompat.so'
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/DMZ/dmz-client-zones.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/DMZ/hosts.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/INTERN/hosts.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/api-users.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/app.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/apt.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/commands.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/downtimes.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/groups.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/notifications.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/satellite.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/services.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/templates.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/timeperiods.conf
    information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.d/global-templates/users.conf
    information/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/_api/include.conf
    information/ConfigItem: Committing config items
    information/ApiListener: My API identity: icinga-server-1
    warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/zones.d/global-templates/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
    warning/ApplyRule: Apply rule 'apt' (in /etc/icinga2/zones.d/global-templates/apt.conf: 1:0-1:18) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'Check_ArcGIS_Service18' (in /etc/icinga2/zones.d/global-templates/services.conf: 465:1-465:38) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'Check Prozess alternate ip 6' (in /etc/icinga2/zones.d/global-templates/services.conf: 674:1-674:44) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'datadisk2' (in /etc/icinga2/zones.d/global-templates/services.conf: 740:1-740:25) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'datadisk3' (in /etc/icinga2/zones.d/global-templates/services.conf: 750:1-750:25) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'status_flex_lizensserver3' (in /etc/icinga2/zones.d/global-templates/services.conf: 843:1-843:41) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'status_tomcat_application15' (in /etc/icinga2/zones.d/global-templates/services.conf: 1224:1-1224:43) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'status_tomcat_application16' (in /etc/icinga2/zones.d/global-templates/services.conf: 1244:1-1244:43) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'status_tomcat_application17' (in /etc/icinga2/zones.d/global-templates/services.conf: 1264:1-1264:43) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'status_tomcat_application18' (in /etc/icinga2/zones.d/global-templates/services.conf: 1284:1-1284:43) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'status_tomcat_application19' (in /etc/icinga2/zones.d/global-templates/services.conf: 1304:1-1304:43) for type 'Service' does not match anywhere!
    warning/ApplyRule: Apply rule 'status_tomcat_application20' (in /etc/icinga2/zones.d/global-templates/services.conf: 1324:1-1324:43) for type 'Service' does not match anywhere!
    information/ConfigItem: Instantiated 1 FileLogger.
    information/ConfigItem: Instantiated 1 ApiUser.
    information/ConfigItem: Instantiated 1 ApiListener.
    information/ConfigItem: Instantiated 4 Zones.
    information/ConfigItem: Instantiated 3 Endpoints.
    information/ConfigItem: Instantiated 1 IdoMysqlConnection.
    information/ConfigItem: Instantiated 76 CheckCommands.
    information/ConfigItem: Instantiated 2 NotificationCommands.
    information/ConfigItem: Instantiated 800 Notifications.
    information/ConfigItem: Instantiated 1 IcingaApplication.
    information/ConfigItem: Instantiated 82 Hosts.
    information/ConfigItem: Instantiated 11 HostGroups.
    information/ConfigItem: Instantiated 1 User.
    information/ConfigItem: Instantiated 6 UserGroups.
    information/ConfigItem: Instantiated 718 Services.
    information/ConfigItem: Instantiated 4 TimePeriods.
    information/ConfigItem: Instantiated 3 ServiceGroups.
    information/ConfigItem: Instantiated 718 ScheduledDowntimes.
    information/ConfigItem: Instantiated 1 CompatLogger.
    information/ConfigItem: Instantiated 1 StatusDataWriter.
    information/ConfigItem: Instantiated 1 ExternalCommandListener.
    information/ConfigItem: Instantiated 1 GraphiteWriter.
    information/ConfigItem: Instantiated 1 CheckerComponent.
    information/ConfigItem: Instantiated 1 NotificationComponent.
    information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
    information/cli: Finished validating the configuration file(s).

**Excerpt from Downtimes.conf**

    apply ScheduledDowntime "Wartungstag" to Service {
      author = "Stefan"
      comment = "Wartungstag"

      ranges = {
        "2016-03-11" = "12:30-23:00"
        "2016-04-20" = "12:30-23:00"
        "2016-05-17" = "12:30-23:00"
      }

      assign where service.name
    }

**Example Single Database Entry in table scheduled\_downtimes:**

    1   167 2016-03-04 14:58:57 Stefan  Wartungstag 6   0   1   0   2016-03-10 12:30:00 2016-03-10 23:00:00 0   0000-00-00 00:00:00 0   0   0000-00-00 00:00:00 IcingaServer!load!icinga-server-1-1457099937-5  1288

**Problems:**

-   Downtime was setup for 11.03.2016, in database it is set for 10.03.2016 and so on. Problem is the ssame, when i create a downtime by icingaweb2 gui or api.
-   every time i start icinga2 service my scheudled downtimes are redefined, so my table scheduled\_downtimes is growing every time i start or restart icinga2 daemon.

Details are in this Post:

https://monitoring-portal.org/index.php?thread/35470-icinga2-mysql-downtime-problem/#post226159

**Attachments**

* [logfiles.zip](https://dev.icinga.com/attachments/download/3194/logfiles.zip) stefanwolff - _2016-03-10 13:06:38 +00:00_
* [bug_web2_gui.PNG](https://dev.icinga.com/attachments/download/3255/bug_web2_gui.PNG) stefanwolff - _2016-03-30 13:46:53 +00:00_ - _IcingaWeb2 Multi Downtime April_

---

**Relations**:

* relates [#11382](https://dev.icinga.com/issues/11382)

**Comment by dnsmichi** [comment]
I believe this is fixed in 2.7.
