### ISSUE TITLE
[dev.icinga.com #11400] Problem with object activation inside the IDO database

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4040]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11400

**Created by fugstrolch on 2016-03-17 08:37:08 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:58:10 +00:00 (in Redmine)_

    Icinga Version: V2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

first: sorry for my english - you can find the german version here:
https://monitoring-portal.org/index.php?thread/35555-icingaweb2-neue-servicegruppen-aktualisierung-erst-nach-2maligem-prozess-restart
I'll try it :)

I want to create a new ServiceGroup with:

    object ServiceGroup "gruppenname" {
            assign where match("*checkProg*", service.display_name)
    }

After restarting the icinga2-process the servicegroup-table has been created in our mysql-db.
But there are no hosts in this mysql-table.

    select * from icinga_servicegroup_members where servicegroup_id = '';

Result:

    Empty set (0.00 sec)

With (only) restarting icinga2-process again we achieve the right result:

    3 rows in set (0.00 sec)

I'd like to get the changes after ONE restart.

I hope the description is good enough...
Thank you very much.

---

**Relations**:

* relates [#11400](https://dev.icinga.com/issues/11400)
* relates [#11400](https://dev.icinga.com/issues/11400)
* relates [#11400](https://dev.icinga.com/issues/11400)

**Comment by dnsmichi** [comment]
I'm closing this in favor of #5205
