### ISSUE TITLE
[dev.icinga.com #11428] Please stop showing parse errors after...

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4049]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11428

**Created by tgelf on 2016-03-21 19:11:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-03-22 20:45:29 +00:00 (in Redmine)_

    Icinga Version: 2.4.3
    Backport?: Not yet backported
    Include in Changelog: 1

---

...the first few catches. Today I got 70 MB startup log for a single deployment. As the root cause hasn't been solved immediately this summed up to a lot of data after a few deployment attempts. Not hard-crafted but by accident in a real-live environment. Just because of an erroneous time-period. Every single (resolved) Notification object (44k) decided to put this information in a redundant way to the log.

Cheers,
Thomas

---

**Relations**:

* relates [#10754](https://dev.icinga.com/issues/10754)

**Comment by dnsmichi** [comment]
Closing this in favour of #3732.
