### ISSUE TITLE
[dev.icinga.com #11442] Duplicated notifications for cluster check in zones.d w/ command_endpoint

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4060]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11442

**Created by mfriedrich on 2016-03-23 14:36:06 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:52:22 +00:00 (in Redmine)_

    Icinga Version: 2.4.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

-   2 nodes inside a HA cluster
-   2 hosts and a cluster health check inside the "master" zone
-   try to pin the "cluster-ha" check onto a specific endpoint

For some reason when a critical HARD state is triggered for the service, both nodes will send notifications.

I guess that the problem is somewhere with checking for the checkable-&gt;IsPaused() inside the notification component.

-   master01 initiates the command endpoint check (responsible for checkable)
-   master02 executes the check with a dummy object, sends back to master01
-   master01 processes the check result and triggers notifications
-   master01 replicates the check result to the master02

-   master02 notifies as well? ---&gt; requires reproducing the issue

    cat /etc/icinga2/master/health.conf
    object Host "master02" {
    import "generic-host"

    display_name = "master02"
    address = "1.2.3.4"
    vars.os = "Linux"
    vars.icinga = true

    vars.notification["mail"] = {
    groups = [ "icingaadmins" ]
    }
    }
    object Host "master01" {
    import "generic-host"

    display_name = "master01"
    address = "1.2.3.5"
    vars.os = "Linux"
    vars.icinga = true

    vars.notification["mail"] = {
    groups = [ "icingaadmins" ]
    }
    }
    /* CLUSTER CHECK */
    apply Service "cluster-ha" {
    check_command = "cluster"
    check_interval = 5s
    retry_interval = 1s
    /* make sure host.name is the same as endpoint name */
    command_endpoint = host.name

    assign where regex("^master0[1|2]*", host.name)
    }

**Comment by dnsmichi** [comment]
I honestly don't remember the issue or what I was testing there.
