### ISSUE TITLE
[dev.icinga.com #11456] Crash of windows service w/ 'node list' cli command

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4067]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11456

**Created by sru on 2016-03-26 13:01:44 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-03-29 15:05:51 +00:00 (in Redmine)_

    Icinga Version: 2.4.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

doing sbin/icinga2 node list crashes the running windows service.
both 2.4.3 and 2.4.4 are crashing.

    D:\Program Files\ICINGA2\sbin>icinga2 --version
    icinga2 - The Icinga 2 network monitoring daemon (version: v2.4.4)

    Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
    License GPLv2+: GNU GPL version 2 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Application information:
      Installation root: d:\Program Files\ICINGA2
      Sysconf directory: d:\Program Files\ICINGA2\etc
      Run directory: d:\Program Files\ICINGA2\var\run
      Local state directory: d:\Program Files\ICINGA2\var
      Package data directory: d:\Program Files\ICINGA2\share\icinga2
      State path: d:\Program Files\ICINGA2\var/lib/icinga2/icinga2.state
      Modified attributes path: d:\Program Files\ICINGA2\var/lib/icinga2/modified-attributes.conf
      Objects path: d:\Program Files\ICINGA2\var/cache/icinga2/icinga2.debug
      Vars path: d:\Program Files\ICINGA2\var/cache/icinga2/icinga2.vars
      PID path: d:\Program Files\ICINGA2\var\run/icinga2/icinga2.pid

    System information:
      Platform: Windows
      Platform version: Vista SP2
      Kernel: Windows
      Kernel version: 6.0
      Architecture: x86

**Attachments**

* [report.1458996824.582](https://dev.icinga.com/attachments/download/3251/report.1458996824.582) sru - _2016-03-26 13:00:20 +00:00_
* [report.1458996963.7030001](https://dev.icinga.com/attachments/download/3252/report.1458996963.7030001) sru - _2016-03-26 13:00:20 +00:00_

---

**Relations**:

* relates [#11530](https://dev.icinga.com/issues/11530)

**Comment by dnsmichi** [comment]
`node list` has been deprecated, so this is a wont-fix.
