### ISSUE TITLE
[dev.icinga.com #11459] Crash of Windows service after connection drops

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4068]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11459

**Created by sru on 2016-03-28 07:08:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-03-28 07:08:16 +00:00 (in Redmine)_

    Icinga Version: 2.4.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

    icinga2 - The Icinga 2 network monitoring daemon (version: v2.4.4)

    Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
    License GPLv2+: GNU GPL version 2 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Application information:
      Installation root: d:\Program Files\ICINGA2
      Sysconf directory: d:\Program Files\ICINGA2\etc
      Run directory: d:\Program Files\ICINGA2\var\run
      Local state directory: d:\Program Files\ICINGA2\var
      Package data directory: d:\Program Files\ICINGA2\share\icinga2
      State path: d:\Program Files\ICINGA2\var/lib/icinga2/icinga2.state
      Modified attributes path: d:\Program Files\ICINGA2\var/lib/icinga2/modified-attributes.conf
      Objects path: d:\Program Files\ICINGA2\var/cache/icinga2/icinga2.debug
      Vars path: d:\Program Files\ICINGA2\var/cache/icinga2/icinga2.vars
      PID path: d:\Program Files\ICINGA2\var\run/icinga2/icinga2.pid

    System information:
      Platform: Windows
      Platform version: Vista SP2
      Kernel: Windows
      Kernel version: 6.0
      Architecture: x86

* linux master 2.4.4, windows satelite 2.4.4 (2.4.3 affected as well)

* setup: master - router - satelite

* connection drop forced at router:

    $ route add -host satelite gw 127.0.0.1 

satelite service crashes, see crash reports.
reproduceable.
2.4.3 crashes as well but does not write a crash report.

*Note:* eventvwr.msc reports the crash at 28.03.2016 08:14:46 whereas icinga2.log reports its last entry at 2016-03-28 08:15:34 which is not to be trusted.

*last lines in icina2.log:*

    [2016-03-28 08:14:46 Mitteleuropäische Sommerzeit] warning/TlsStream: TLS stream was disconnected.
    [2016-03-28 08:14:46 Mitteleuropäische Sommerzeit] critical/ApiListener: Client TLS handshake failed
    Context:
        (0) Handling new API client connection

    [2016-03-28 08:15:34 Mitteleuropäische Sommerzeit] information/Application: We jumped forward in time: 48.236 seconds 

The "Jumped forward" is about 50 seconds for each crash.

*Windows Event log:*

    Protokollname: Application
    Quelle:        Application Error
    Datum:         28.03.2016 08:14:46
    Ereignis-ID:   1000
    Aufgabenkategorie:(100)
    Ebene:         Fehler
    Schlüsselwörter:Klassisch
    Benutzer:      Nicht zutreffend
    Computer:      satelite.my.domain.com
    Beschreibung:
    Fehlerhafte Anwendung icinga2.exe, Version 1.0.0.0, Zeitstempel 0x56e921cd, fehlerhaftes Modul ntdll.dll, Version 6.0.6002.19594, Zeitstempel 0x56ac29d2, Ausnahmecode 0xc0000374, Fehleroffset 0x000b13ac, Prozess-ID 0x1f88, Anwendungsstartzeit 01d188b70d98b28d.
    Ereignis-XML:

      
        
        1000
        2
        100
        0x80000000000000
        
        12041
        Application
        Workstation21.administration.nanotron.com
        
      
      
        icinga2.exe
        1.0.0.0
        56e921cd
        ntdll.dll
        6.0.6002.19594
        56ac29d2
        c0000374
        000b13ac
        1f88
        01d188b70d98b28d
      

**Attachments**

* [report.1459143163.4649999](https://dev.icinga.com/attachments/download/3253/report.1459143163.4649999) sru - _2016-03-28 07:05:00 +00:00_
* [report.1459145734.6719999](https://dev.icinga.com/attachments/download/3254/report.1459145734.6719999) sru - _2016-03-28 07:05:00 +00:00_

**Comment by dnsmichi** [comment]
@N-o-X similar thing for the other connection related issues on Windows. Please reproduce at first glance.

**Comment by dnsmichi** [comment]
I believe this has been fixed, we did not see this during our investigation in the linked issue.
