### ISSUE TITLE
[dev.icinga.com #11472] Encrypted Constants

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4071]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11472

**Created by dsutherland1492 on 2016-03-29 18:35:49 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-08-05 06:41:26 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Sometimes constants are used for passwords / credentials or any configuration information you may wish to have encrypted. A method of encryption should be developed much like Chef's vault encryption of databags. https://www.chef.io/blog/2016/01/21/chef-vault-what-is-it-and-what-can-it-do-for-you/

**Comment by lippserd** [comment]
I also think that we should integrate one the existing tools out there.

**Comment by jwilliams-shadowsoft** [comment]
Yes, Vault would be an excellent choice for a more secure level of secrets management. This is something I've had a lot of people asking for, especially for database and API client connection passwords.

**Comment by carraroj** [comment]
ref/IP/11083

**Comment by dnsmichi** [comment]
The consolidated ticket is #6404.

**Comment by julianbrost** [comment]
Closing this one in favor of #6404.
