### ISSUE TITLE
[dev.icinga.com #11500] icinga2.exe daemon -C crashes on a freshly installed windows client

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4083]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11500

**Created by trehberg on 2016-04-01 10:01:59 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-08 15:32:57 +00:00 (in Redmine)_

    Icinga Version: 2.4.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

After a fresh installation of the Icinga2-v2.4.4.exe on an Windows Server 2012 R2 Standard, a config validation fails with this output:

c:\\Program Files (x86)\\ICINGA2&gt;sbin\\icinga2.exe daemon -C
information/cli: Icinga application loader (version: v2.4.4)
critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in 'C:\\Program Files (x86)\\ICINGA2\\var/log/icinga2/crash/report.1459502729.187'

The mentioned dir with the crash report remains empty, no crash report.

The Logfile shows, directly after installation, before the first startup of the daemon:

\[2016-04-01 11:32:14 W. Europe Daylight Time\] information/ConfigItem: Activated all objects.
\[2016-04-01 11:32:14 W. Europe Daylight Time\] information/ConfigCompiler: Compiling config file: C:\\Program Files (x86)\\ICINGA2\\var/lib/icinga2/api/packages/\_api/SW-HAMLHIND-003-1459503134-1/conf.d/downtimes/SW-HAMLHIND-003.ads.dlh.de![](load)SW-HAMLHIND-003-1459503134-0.conf
\[2016-04-01 11:32:14 W. Europe Daylight Time\] information/ConfigItem: Committing config items
\[2016-04-01 11:32:14 W. Europe Daylight Time\] warning/ApplyRule: Apply rule 'satellite-host' (in C:\\Program Files (x86)\\ICINGA2\\etc\\icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
\[2016-04-01 11:32:14 W. Europe Daylight Time\] information/ConfigItem: Instantiated 1 Downtime.
\[2016-04-01 11:32:14 W. Europe Daylight Time\] information/ConfigItem: Triggering Start signal for config items
\[2016-04-01 11:32:14 W. Europe Daylight Time\] information/ConfigItem: Activated all objects.
\[2016-04-01 11:37:14 W. Europe Daylight Time\] information/ConfigObject: Dumping program state to file 'C:\\Program Files (x86)\\ICINGA2\\var/lib/icinga2/icinga2.state'

This behaviour occurs also if the daemon is running.
The daemon itsself runs successfully and is also not affected, if one tries a config test during runtime.

Additional Information from Windows:
Problem signature:
Problem Event Name: APPCRASH
Application Name: icinga2.exe
Application Version: 1.0.0.0
Application Timestamp: 56e921cd
Fault Module Name: KERNELBASE.dll
Fault Module Version: 6.3.9600.18202
Fault Module Timestamp: 569e72bb
Exception Code: e06d7363
Exception Offset: 00015b68
OS Version: 6.3.9600.2.0.0.272.7
Locale ID: 1031
Additional Information 1: 5861
Additional Information 2: 5861822e1919d7c014bbb064c64908b2
Additional Information 3: 1318
Additional Information 4: 13181ae637ac2592fac0ca2dd662cdcc

Environment:
VMware Workstation VM
Server 2012 R2
Intel Core i7
4 GB RAM

**Attachments**

* [etc.zip](https://dev.icinga.com/attachments/download/3266/etc.zip) trehberg - _2016-04-01 11:26:16 +00:00_
* [Icinga-Issue-11500_VS-Screenshot.png](https://dev.icinga.com/attachments/download/3272/Icinga-Issue-11500_VS-Screenshot.png) trehberg - _2016-04-04 09:45:27 +00:00_

---

**Relations**:

* relates [#11530](https://dev.icinga.com/issues/11530)

**Comment by dnsmichi** [comment]
Same issue as #5515, closing here.
