### ISSUE TITLE
[dev.icinga.com #11526] allow command execution on parent zone using command_endpoint

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4090]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11526

**Created by moritzfriedrich on 2016-04-05 11:25:20 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-04-22 09:52:10 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

We have two self-contained Icinga Servers and will check the other for full functionality (Icingaservice, MTA, Database, Diskspace, ...).
Thats actually not possible with the parent-child trustmodel. So we need to use another way like NRPE or SSH or third Server.
But I would prefer to use the Icinga Client as Command Execution Bridge.

![icinga-command-execution-feature-request.jpg](https://dev.icinga.com/attachments/download/3274/icinga-command-execution-feature-request.jpg)

Is it possible to add an option, that a parent endpoint also can act as an Command Execution Bridge of a child endpoint.

**Attachments**

* [icinga-command-execution-feature-request.jpg](https://dev.icinga.com/attachments/download/3274/icinga-command-execution-feature-request.jpg) moritzfriedrich - _2016-04-05 11:23:32 +00:00_

**Comment by htriem** [comment]
There are no plans to support this.
