### ISSUE TITLE
[dev.icinga.com #11530] Check for permissions on Windows shell

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4091]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11530

**Created by twidhalm on 2016-04-05 15:22:11 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-06 17:40:50 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

When running `icinga2 daemon -C` from a Windows Commandline that was not startet as `administrator` the command fails with a message that Icinga 2 terminated unexpectedly and that a crash report was written.

The crash report does not get written because when not running as administrator icinga2 is not allowed to write into the crash directory.

Please use a check and a more helpful error message when running a command fails just because of missing permissions. And maybe check if the crash reported was actually written before the telling the user it was.

Thanks and Cheers!

---

**Relations**:

* relates [#11530](https://dev.icinga.com/issues/11530)
* relates [#11530](https://dev.icinga.com/issues/11530)

**Comment by dnsmichi** [comment]
Same as #5515 and reported by the same user @widhalmt ;-)
