### ISSUE TITLE
[dev.icinga.com #11573] Allow to reset modified attributes by command and API

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4112]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11573

**Created by dgoetz on 2016-04-12 09:42:38 +00:00**

Assignee: _gbeutner_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-28 13:24:35 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Icinga 1.x knows the command CHANGE\_SVC\_MODATTR to reset modified attributes of a service (and similar command for hosts and contacts).

This is really helpful if someone disabled and/or enabled active checks for example and you want to get all the services simply back to the option of your configuration files. If no such command exists changing the configuration only affects the unmodified services and all others have to be identified and set manually to the other option and doing so again when the default changes again.

**Comment by Hitokun** [comment]
Bump. This would be pretty cool.

**Comment by Crunsher** [comment]
This feature is a bit far removed from the current focus of development sady, but help is always welcome!
