### ISSUE TITLE
[dev.icinga.com #11608] Unable to remove scheduled downtime

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4126]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11608

**Created by pit on 2016-04-18 11:49:52 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2016-04-19 09:59:15 +00:00_)
Target Version: _(none)_
Last Update: _2016-04-21 15:15:35 +00:00 (in Redmine)_

    Icinga Version: 2.4.4-1.el7
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

we installed a new Incinga 2 Server and encountered the following bug:

**Current result**

* Problem 1
In the default config, the local server has a check "load" with a scheduled downtime associated.
We tried to remove this downtime, so we removed this lines from /etc/icinga2/conf.d/services.conf:

    <   /* Used by the ScheduledDowntime apply rule in `downtimes.conf`. */
    <   vars.backup_downtime = "02:00-03:00"

Unfortunately the downtime was not removed in the webinterface after restarting the incinga2 service.
"icinga2 object list" didn't show the entry any more.

* Problem 2
When trying to remove the downtime using the webinterface the following error is logged in /var/log/icinga2/icinga2.log:

    information/ExternalCommandListener: Executing external command: [1460964637] DEL_SVC_DOWNTIME;1
    warning/Downtime: Cannot remove downtime '!load!-1460964226-0'. It is owned by scheduled downtime object '!load!backup-downtime'

**Expected result**

-   Removing the downtime from the configuration should remove it everywhere
-   Removing a downtime in the webinterface should work or create a error message why it is not working

**Workaround**
When deleting the entry manually from the mySQL database, the problem was gone:

    delete from icinga_scheduleddowntime where scheduleddowntime_id = ;

**Version Info**
CentOS 7.0

    [root@vls071 ~]# rpm -qa | grep -i icinga
    icingaweb2-vendor-Parsedown-1.0.0-1.el7.centos.noarch
    icinga2-2.4.4-1.el7.centos.x86_64
    icingaweb2-vendor-JShrink-1.0.1-1.el7.centos.noarch
    php-Icinga-2.3.1-1.el7.centos.noarch
    icinga2-bin-2.4.4-1.el7.centos.x86_64
    icinga2-ido-mysql-2.4.4-1.el7.centos.x86_64
    icingaweb2-vendor-dompdf-0.6.2-1.el7.centos.noarch
    icingaweb2-vendor-lessphp-0.4.0-1.el7.centos.noarch
    icingacli-2.3.1-1.el7.centos.noarch
    icingaweb2-2.3.1-1.el7.centos.noarch
    icinga2-common-2.4.4-1.el7.centos.x86_64
    icingaweb2-vendor-HTMLPurifier-4.7.0-1.el7.centos.noarch
    icingaweb2-common-2.3.1-1.el7.centos.noarch

---

**Relations**:

* duplicates [#11423](https://dev.icinga.com/issues/11423)

**Comment by 8la** [comment]
Any updates on this?

**Comment by holderg** [comment]
comment out 
vars.backup_downtime = "02:00-03:00"
in /etc/icinga2/conf.d/services and restart

**Comment by fireheadman** [comment]
This still appears to be a valid issue.
I have a brand new install.
I have commented out var.backup_downtime and restarted... no dice
Then moved downtimes.conf to downtimes.conf.DISABLE and restarted.... still no dice.

I created a Test Downtime and I could remove it successfully.
Something is different with this pre-canned downtime.

**Comment by dnsmichi** [comment]
Please don't bump 3 year old closed issues. Runtime downtimes created from ScheduledDowntime config objects cannot be deleted by the user, they are either deleted with a) expiry b) the checkable object where they are bound to, are gone.
