### ISSUE TITLE
[dev.icinga.com #11621] icinga agent causing high CPU usage, futex/gettimeofday loop

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4133]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11621

**Created by branoz on 2016-04-19 14:44:37 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-21 14:25:58 +00:00 (in Redmine)_

    Icinga Version: 2.4.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

On my production deploy, three Icinga nodes are causing high user CPU usage. Upon closer investigation, there are 2-3 threads that are endlessly looping in some futex()/gettimeofday() calls. This is happening right after node starts up.

Example from "top -u nagios -H"

    top - 11:58:55 up 368 days, 17:44,  3 users,  load average: 1.20, 0.95, 0.81
    Tasks: 110 total,   6 running, 104 sleeping,   0 stopped,   0 zombie
    Cpu(s): 33.3%us, 33.3%sy,  0.0%ni,  0.0%id,  0.0%wa, 33.3%hi,  0.0%si,  0.0%st
    Mem:   3840336k total,  3738492k used,   101844k free,     9228k buffers
    Swap:        0k total,        0k used,        0k free,   433252k cached

      PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                          
    15714 nagios    20   0  756m  12m  10m R  101  0.3   0:06.06 icinga2                                                                                          
    15697 nagios    20   0  756m  12m  10m R   73  0.3   0:05.41 icinga2                                                                                          
    15698 nagios    20   0  756m  12m  10m R   62  0.3   0:02.50 icinga2                                                                                          
    15685 nagios    20   0  756m  12m  10m S    0  0.3   0:00.09 icinga2                                                                                          
    15693 nagios    20   0  756m  12m  10m S    0  0.3   0:00.00 icinga2                                                                                          
    15694 nagios    20   0  756m  12m  10m S    0  0.3   0:00.00 icinga2                                                                                          
    15695 nagios    20   0  756m  12m  10m S    0  0.3   0:00.00 icinga2                                                                                          

Example strace from thread1:

    futex(0x7ff8b075726c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 3361332, {1461066838, 926429000}, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
    futex(0x7ff8b075726c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 3361340, {1461066838, 926429000}, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
    futex(0x7ff8b075726c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 3361350, {1461066838, 926429000}, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
    ...

Example strace from thread2:

    futex(0x7ff8b075589c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 3395555, {1461066848, 707005000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
    futex(0x7ff8b0755870, FUTEX_WAKE_PRIVATE, 1) = 0
    gettimeofday({1461066848, 207243}, NULL) = 0
    gettimeofday({1461066848, 207318}, NULL) = 0
    gettimeofday({1461066848, 207394}, NULL) = 0
    gettimeofday({1461066848, 207468}, NULL) = 0
    gettimeofday({1461066848, 207543}, NULL) = 0
    gettimeofday({1461066848, 207618}, NULL) = 0
    futex(0x7ff8b075589c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 3395557, {1461066848, 707618000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
    futex(0x7ff8b0755870, FUTEX_WAKE_PRIVATE, 1) = 0
    gettimeofday({1461066848, 207855}, NULL) = 0
    gettimeofday({1461066848, 207932}, NULL) = 0
    ...

This is a brand new Icinga2 deploy in AWS. One master and 12 agents nodes, all on the same version 2.4.4-1. There is a mix of Ubuntu versions (Precise, Trusty) and kernels.

Only three of the twelve agents are misbehaving. What they have in common is that they are all

-   Ubuntu Precise 12.04.4
-   kernel 3.2.0-25-virtual
-   c3.large paravirtual instance, 2x CPUs

I wasn't able to reproduce this problem in our dev environment. I cannot get *exactly* the same image/kernel/libraries/cpuflags etc.

Configuration:
Surprisingly, it does not depend on any configuration. I was able to reproduce it (on Prod) with minimal config (rm -rf /var/lib/icinga2/\* /var/cache/icinga2/\* /etc/icinga2/\*; echo &gt; /etc/icinga2/icinga2.conf)

Started with
/usr/lib/icinga2/sbin/icinga2 daemon -x notice

I'm also attaching strace from the startup.

Has any of the developers seen this issue ? What is the root cause ? I assume that the problem would disappear if the node would be reinstalled with newer Ubuntu (but I cannot afford that atm). Is there any workaround ?

Thanks,

Brano Zarnovican

**Attachments**

* [top.txt](https://dev.icinga.com/attachments/download/3305/top.txt) branoz - _2016-04-19 14:34:29 +00:00_
* [version.txt](https://dev.icinga.com/attachments/download/3306/version.txt) branoz - _2016-04-19 14:34:40 +00:00_
* [thread1_strace.out](https://dev.icinga.com/attachments/download/3307/thread1_strace.out) branoz - _2016-04-19 14:34:55 +00:00_
* [thread2_strace.out](https://dev.icinga.com/attachments/download/3308/thread2_strace.out) branoz - _2016-04-19 14:35:00 +00:00_
* [icinga.trace.broken.out](https://dev.icinga.com/attachments/download/3309/icinga.trace.broken.out) branoz - _2016-04-19 14:35:52 +00:00_

**Comment by dnsmichi** [comment]
We need to wait here, since there's a limit of max concurrent checks applied. Such futex calls happen in many places not directly visible, e.g. when a thread waits for a lock being freed, or a specific object lock. 

The overall behaviour seems to be coming from something else. Since 12.04 LTS is EOL and we haven't had any reports on Ubuntu kernels with 14 or 16 LTS, I'll close here.
