### ISSUE TITLE
[dev.icinga.com #11631] Incorrect status code, when api-user filter is incorrent

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4137]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11631

**Created by bazz on 2016-04-20 12:20:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:54:31 +00:00 (in Redmine)_

    Icinga Version: r2.4.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Very strange:
I have api user, with incorrect filter:
object ApiUser "SendmailAgentd" {
password = "pass!"
// client\_cn = ""

permissions = \[
{
permission = "actions/process-check-result"
filter = {{ regex("IncorrectServiceName$", service.name) }}
}
\]
}
When i sent this results, i receive 404 error, instead of 401.

> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mon.localdomain:5665/v1/actions/process-check-result?service=del-81host.com!SendmailAgentd

**Comment by dnsmichi** [comment]
404 is correct as it does not allow attackers to test whether the objects are there or just permissions are missing. Such things should be logged, and there's a recent issue for that already.
