### ISSUE TITLE
[dev.icinga.com #11633] Duplicate SQL statements avoid IDO connection

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4138]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11633

**Created by mwaldmueller on 2016-04-20 13:14:13 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-11-09 14:58:11 +00:00 (in Redmine)_

    Icinga Version: 2.4.5
    Backport?: Not yet backported
    Include in Changelog: 1

---

For some reasons Icinga2 sends **equal** SQL INSERT-statements, e.g. for custom variables. If this occurs the connection of the icinga2 daemon to the IDO is re-established again and again until the missing statements of the SQL-block are executed manually.

    Error "Duplicate entry '10081-1-view_gateways' for key 'object_id_2'" when executing query "INSERT INTO icinga_customvariables (config_type, instance_id, is_json, object_id, session_token, varname, varvalue) VALUES ('1', 2, '0', 10081, 1461151941, 'view_gateways', 'ALL');INSERT INTO icinga_customvariablestatus (instance_id, is_json, object_id, session_token, status_update_time, varname, varvalue) VALUES (2, '0', 10081, 1461151941, FROM_UNIXTIME(1461151944), 'view_gateways', 'ALL');INSERT INTO icinga_customvariables (config_type, instance_id, is_json, object_id, session_token, varname, varvalue) VALUES ('1', 2, '0', 10081, 1461151941, 'view_gateways', 'ALL');INSERT INTO icinga_customvariablestatus (instance_id, is_json, object_id, session_token, status_update_time, varname, varvalue) VALUES (2, '0', 10081, 1461151941, FROM_UNIXTIME(1461151944), 'view_gateways', 'ALL');UPDATE icinga_commands SET command_line = ' \"/etc/icinga2/scripts/mail-host-notification.sh\"',  config_type = '1',  instance_id = 2,  object_id = 2480421 WHERE object_id = 2480421" 

Comparison of the statements for better understanding:

    Error "Duplicate entry '10081-1-view_gateways' for key 'object_id_2'" when executing query "
    INSERT INTO icinga_customvariables (config_type, instance_id, is_json, object_id, session_token, varname, varvalue) VALUES ('1', 2, '0', 10081, 1461151941, 'view_gateways', 'ALL');
    INSERT INTO icinga_customvariablestatus (instance_id, is_json, object_id, session_token, status_update_time, varname, varvalue) VALUES (2, '0', 10081, 1461151941, FROM_UNIXTIME(1461151944), 'view_gateways', 'ALL');
    INSERT INTO icinga_customvariables (config_type, instance_id, is_json, object_id, session_token, varname, varvalue) VALUES ('1', 2, '0', 10081, 1461151941, 'view_gateways', 'ALL');
    INSERT INTO icinga_customvariablestatus (instance_id, is_json, object_id, session_token, status_update_time, varname, varvalue) VALUES (2, '0', 10081, 1461151941, FROM_UNIXTIME(1461151944), 'view_gateways', 'ALL');
    UPDATE icinga_commands SET command_line = ' \"/etc/icinga2/scripts/mail-host-notification.sh\"',  config_type = '1',  instance_id = 2,  object_id = 2480421 WHERE object_id = 2480421" 

Maybe this could be avoided through adding "ON DUPLICATE KEY" (see: https://dev.mysql.com/doc/refman/5.5/en/insert-on-duplicate.html). At the moment we don't know why this duplicate entries occur. The problem was exists with Icinga 2.4.3 too.

**Comment by dnsmichi** [comment]
This should be fixed in 2.7.
