### ISSUE TITLE
[dev.icinga.com #11654] Flapping detection enabled but notifications sent

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4150]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11654

**Created by jamacias on 2016-04-21 23:20:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-05 09:32:40 +00:00 (in Redmine)_

    Icinga Version: 2.4.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

I upgraded Icinga to version 2.4.4 and learned that bug [\#9969](https://dev.icinga.com/issues/9969) is still present. I used the rpm repository to upgrade. I get PROBLEM
emails after the flapping has been turned on. However, I did stop receiving RECOVERY messages. This is my configuration and tools I used:

max\_check\_attempts = 3
check\_interval = 1m
retry\_interval = 30s

flapping\_threshold = 3

this is the simple script that I used at the host in order to trigger the alert:

\#!/bin/sh
while \[ true \]
do
stress -c 2 -t 300
sleep 120
done

I'm also attaching the script used at the server

**Attachments**

* [check_cpu_snmp.bash](https://dev.icinga.com/attachments/download/3318/check_cpu_snmp.bash) jamacias - _2016-04-21 23:17:56 +00:00_
* [clean-debug.log](https://dev.icinga.com/attachments/download/3323/clean-debug.log) jamacias - _2016-04-23 00:05:07 +00:00_
* [API-OUTPUT](https://dev.icinga.com/attachments/download/3324/API-OUTPUT) jamacias - _2016-04-23 00:05:09 +00:00_
* [debug.log](https://dev.icinga.com/attachments/download/3325/debug.log) jamacias - _2016-04-23 00:05:10 +00:00_

**Changesets**

_2016-05-31 15:51:45 +00:00_ by _(unknown)_ b2e77470037c661793dc20ffe764a6a084a0e731

    WIP: Make change to OK always a hard state
    
    refs #11654

_2016-06-09 12:28:46 +00:00_ by _(unknown)_ 754638ee1b954e2ac93c9399d122b3a6f7c987be

    WIP: Make change to OK always a hard state
    
    refs #11654

_2016-06-13 08:43:57 +00:00_ by _(unknown)_ 8808e709c9f3e83f5dd9098f0282c6cafdb6b9ce

    Make change to OK always a hard state
    
    refs #11654

---

**Relations**:

* relates [#11654](https://dev.icinga.com/issues/11654)
* relates [#11654](https://dev.icinga.com/issues/11654)
* relates [#11654](https://dev.icinga.com/issues/11654)
* relates [#11654](https://dev.icinga.com/issues/11654)
* relates [#11654](https://dev.icinga.com/issues/11654)

**Comment by dnsmichi** [comment]
Will be continued in #4982.
