### ISSUE TITLE
[dev.icinga.com #11656] systemd: run icinga2 in foreground

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4152]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11656

**Created by phil_fry on 2016-04-22 08:42:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-22 09:19:57 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

as icinga2 2.4.6 died with a segfault for me yesterday, I'd suggest to replace the systemd service file in order to restart the daemon automagically.

    [Unit]
    Description=Icinga host/service/network monitoring system
    After=syslog.target network.target postgresql.service mariadb.service carbon-cache.service

    [Service]
    Type=simple
    ExecStartPre=@CMAKE_INSTALL_PREFIX@/lib/icinga2/prepare-dirs @ICINGA2_SYSCONFIGFILE@
    ExecStart=@CMAKE_INSTALL_FULL_SBINDIR@/icinga2 daemon
    ExecReload=@CMAKE_INSTALL_PREFIX@/lib/icinga2/safe-reload @ICINGA2_SYSCONFIGFILE@
    Restart=always
    User=@ICINGA2_USER@
    Group=@ICINGA2_GROUP@
    PermissionsStartOnly=1

    [Install]
    WantedBy=multi-user.target

Kind regards

Philippe

**Comment by Crunsher** [comment]
I'm closing this ticket as I'm not sure what's required.
We won't add restart=Always by default, we won't have systemd write to your console and whatever this segfault the ticket refers to is hopefully long fixed.
