### ISSUE TITLE
[dev.icinga.com #11669] Parse perfdata in eventstreams

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4161]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11669

**Created by bsheqa on 2016-04-25 08:26:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _2.7.0_
Last Update: _2016-12-08 00:36:11 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

When calling https://localhost:5665/v1/events most perfdata is not beeing parsed.
They should be parsed in the way Graphite feature does it.

**Comment by dnsmichi** [comment]
We discussed it, and updated the requirements. This will be continued in #4940.
