### ISSUE TITLE
[dev.icinga.com #11671] CMake (in specific cases) finds wrong libmysql

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4163]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11671

**Created by jflach on 2016-04-25 13:39:34 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-16 08:15:23 +00:00 (in Redmine)_

    Icinga Version: 2.5.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

This bug is essentially the same as [\#11634,](https://dev.icinga.com/issues/11634) but it occurs only when you run cmake a second time in a populated build directory.

---

**Parent Task:** [#11634](https://dev.icinga.com/issues/11634)

**Comment by dnsmichi** [comment]
@Crunsher is this still relevant?
