### ISSUE TITLE
[dev.icinga.com #11697] Icinga2 is directly jumping to hard state

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4174]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11697

**Created by Emanuel on 2016-04-28 09:55:20 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-08-08 16:01:51 +00:00_)
Target Version: _(none)_
Last Update: _2016-11-07 14:55:52 +00:00 (in Redmine)_

    Icinga Version: 2.4.7
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,
we experience a lot of times, when icinga2 is directly going to a hard state, instead of first going to a soft state.

**Attachments**

* [Hard-State.jpg](https://dev.icinga.com/attachments/download/3340/Hard-State.jpg) Emanuel - _2016-04-28 08:53:37 +00:00_

---

**Relations**:

* duplicates [#7354](https://dev.icinga.com/issues/7354)

**Comment by gitmirko** [comment]
Hi,
how could I bring this topic up again?

**Comment by dnsmichi** [comment]
I have no idea what happen in the last few comments in this ticket. I'd suggest opening a new one.
