### ISSUE TITLE
[dev.icinga.com #11698] Add a function to ITL to flatten a dictionary

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4175]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11698

**Created by LarsEngels on 2016-04-28 11:39:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-28 11:39:18 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Given a host object which has a nested dictionary as host variable, it would be very handy to have a way to have an "apply for" service defintion which creates a service for all sub parts of the dictionary.

An example:

    object Host "dbserver" {
      import "generic-host"

      vars.database = {
        oracle = {
          myschema = [
              SYSAUX = {
                wlimit = 150,
                climit = 100,
              },
              SYSTEM = {
                wlimit = 150,
                climit = 100,
              },
              TOOLS = {
                wlimit = 150,
                climit = 100,
              },
            ],
          },
        }
    }

Then, with the following functions written by Gunnar (thanks again!) you flatten the database.oracle dictionary and can use it in the apply for definition:

    globals.flatten_dictionary_recursive = function(dict, keys, index) {
      if (typeof(dict) != Dictionary) {
        return null
      }

      var result = {}

      for (key => value in dict) {
        if (index + 1 >= keys.len()) {
          var item = value.clone()
          item[keys[index]] = key
          result.set(key, item)
        } else {
          for (skey => svalue in flatten_dictionary_recursive(value, keys, index + 1)) {
            var item = svalue.clone()
            item[keys[index + 1]] = skey
            result.set(key + "-" + skey, item)
          }
        }
      }

      return result
    }

    globals.make_dictionary_flattener = function(keys) {
      return function(dict) use (keys) {
        return flatten_dictionary_recursive(dict, keys, 0)
      }
    }

    globals.flatten_database_def = make_dictionary_flattener([ "db", "schema" ])

    apply Service "by_ssh_dbschema_" for (dbfullname => dbconfig in flatten_database_def(host.vars.database.oracle)) {
      import "pnp-service"

      display_name = "Oracle Schema " + dbconfig.db + " " + dbconfig.schema
      check_command = "by_ssh_dbschema"

      vars.by_ssh_dfm_dbname     = dbconfig.db
      vars.by_ssh_dfm_tablespace = dbconfig.schema
      vars.by_ssh_dfm_wlimit     = dbconfig.wlimit
      vars.by_ssh_dfm_climit     = dbconfig.climit
    }

**Comment by dnsmichi** [comment]
This requires a more general decision whether to include functions for global usage inside the ITL or not.

I'll link to #4890 and close here.
