### ISSUE TITLE
[dev.icinga.com #11740] .conf file will remain in apifolder if the zonesfolder in zones.d is removed or the last .conf-file is removed from /zones.d/zonefolder.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4191]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11740

**Created by rafael.voss on 2016-05-08 09:47:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-18 14:08:56 +00:00 (in Redmine)_

    Icinga Version: 2.4.7
    Backport?: Not yet backported
    Include in Changelog: 1

---

As long there is more than one conf file in the zonefolder there is no problem, but if there is only one .conf-file in a zonefolder in /etc/icinga2/zones.d and this file is deleted (folder is empty now), the .conf-file will remain in the api folder in /var/lib/icinga2/api/zones/.

I have the same problem when i delete the entire zonefolder in zones.d.

i use the debmon packages on Debian Jessi.

As a workaround i have placed a dummy.conf with no content in the zonefolder.

---

**Relations**:

* relates [#10000](https://dev.icinga.com/issues/10000)

**Comment by NeverUsedID** [comment]
Looks like this bug still exists in 2.8.0

Just moved the last .conf file from one global zone to another. ALL Icinga2 agents failed to reload, because now the command "is predefined" in both zones. To solve this, a simple "touch dummy.conf"  in the "empty" old zone at the master, followed by a reload solved the problem.

**Comment by l13t** [comment]
+1 for this issue. I had a need to remove one zone from our distributed configuration, but after change of configuration and restart of main master zone still existed in `/var/lib/icinga2/api/zones` .

**Comment by Al2Klimov** [comment]
@NeverUsedID What about v2.10.2?

**Comment by dnsmichi** [comment]
I will deal with this as part of #6716.

**Comment by dnsmichi** [comment]
I'm closing this in favor of #6716.
