### ISSUE TITLE
[dev.icinga.com #11741] add information to event stream

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4192]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11741

**Created by kowallix on 2016-05-09 06:53:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-05-09 06:53:27 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi!

Is it possible to add
- the group information (hostgroup, servicegroup)
- and maybe even custom variables
to the event stream?

That would make it easier to filter/process/direct events.

Thanks!

Hans

**Comment by dnsmichi** [comment]
Adding that to any event that happens will increase the payload of each message. That information is sort of redundant (e.g. group memberships do not change over time) and therefore should be pulled on-demand. Basically you would have two methods - an event stream receiver and a status/config poller. 

Thinking in bigger environments, adding such meta information will probably kill your monitoring box. So I'll deny that request for that reason.

**Comment by jficz** [comment]
I'd like to revisit this issue - we use Icingabeat + Event Stream + ELK and we need some of the custom event data in the stream, namely a single custom variable which tells us the internal priority of the event.

I could not find any way to include that information in the event stream as payload fields seem to be hard-coded. 

I disagree with the reasoning "adding such meta information will probably kill your monitoring box" - if the feature would be configurable, it is the sole responsibility of the service owner to make sure the load and box spec are in sync. In our case, on top of that, including  a single variable would only add a few bytes to the message increasing the payload for less than 1 %.

Contrary, on-demand pulling of that information would obviously be incomparably and absurdly more expensive as we need to have the info for each event that we pull from the stream.
