### ISSUE TITLE
[dev.icinga.com #11756] API: Extend log message which objects depend on to-be-deleted object

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4201]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11756

**Created by mfriedrich on 2016-05-10 13:03:58 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-05-10 13:03:58 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

    bool ConfigObjectUtility::DeleteObjectHelper(const ConfigObject::Ptr& object, bool cascade, const Array::Ptr& errors)
    {
            std::vector parents = DependencyGraph::GetParents(object);

            if (!parents.empty() && !cascade) {
                    if (errors)
                            errors->Add("Object cannot be deleted because other objects depend on it. "
                                "Use cascading delete to delete it anyway.");

                    return false;
            }

**Comment by dnsmichi** [comment]
Since I'm the requestor, I don't need it anymore.
