### ISSUE TITLE
[dev.icinga.com #11801] Error: Function call 'rename' for file '/var/spool/icinga2/tmp/service-perfdata' failed with error code 2, 'No such file or directory'

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4221]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11801

**Created by Dynatomic on 2016-05-18 05:16:26 +00:00**

Assignee: _gbeutner_
Status: _Resolved_  (closed on _2016-05-18 12:35:03 +00:00_)
Target Version: _2.4.9_
Last Update: _2017-01-13 15:16:35 +00:00 (in Redmine)_

    Icinga Version: 2.4.8
    Backport?: Not yet backported
    Include in Changelog: 1

---

systemctl status icinga2
icinga2.service - Icinga host/service/network monitoring system
Loaded: loaded (/usr/lib/systemd/system/icinga2.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Wed 2016-05-18 04:42:02 UTC; 3min 33s ago
Process: 9285 ExecStart=/usr/sbin/icinga2 daemon -d -e ${ICINGA2\_ERROR\_LOG} (code=exited, status=1/FAILURE)
Process: 9224 ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/sysconfig/icinga2 (code=exited, status=0/SUCCESS)
Main PID: 22141 (code=exited, status=0/SUCCESS)

May 18 04:42:02 icinga.ns-pos.com icinga2\[9285\]: Context:
May 18 04:42:02 icinga.ns-pos.com icinga2\[9285\]: (0) Activating object 'icinga-status' of type 'IcingaStatusWriter'
May 18 04:42:02 icinga.ns-pos.com icinga2\[9285\]: \[2016-05-18 04:42:02 +0000\] information/LivestatusListener: Created UNIX socket in '/run/icinga2/cmd/livestatus'.
May 18 04:42:02 icinga.ns-pos.com icinga2\[9285\]: \[2016-05-18 04:42:02 +0000\] critical/ConfigItem: Error: Function call 'rename' for file '/var/spool/icinga2/tmp/service-perfdata' failed with error code 2, 'No such file or directory'
May 18 04:42:02 icinga.ns-pos.com icinga2\[9285\]: \[2016-05-18 04:42:02 +0000\] critical/ConfigItem: 1 error
May 18 04:42:02 icinga.ns-pos.com icinga2\[9285\]: \[2016-05-18 04:42:02 +0000\] critical/cli: Error activating configuration.
May 18 04:42:02 icinga.ns-pos.com systemd\[1\]: icinga2.service: control process exited, code=exited status=1
May 18 04:42:02 icinga.ns-pos.com systemd\[1\]: Failed to start Icinga host/service/network monitoring system.
May 18 04:42:02 icinga.ns-pos.com systemd\[1\]: Unit icinga2.service entered failed state.
May 18 04:42:02 icinga.ns-pos.com systemd\[1\]: icinga2.service failed.

icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.4.8)

Copyright © 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later &lt;http://gnu.org/licenses/gpl2.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
Installation root: /usr
Sysconf directory: /etc
Run directory: /run
Local state directory: /var
Package data directory: /usr/share/icinga2
State path: /var/lib/icinga2/icinga2.state
Modified attributes path: /var/lib/icinga2/modified-attributes.conf
Objects path: /var/cache/icinga2/icinga2.debug
Vars path: /var/cache/icinga2/icinga2.vars
PID path: /run/icinga2/icinga2.pid

System information:
Platform: CentOS Linux
Platform version: 7 (Core)
Kernel: Linux
Kernel version: 3.10.0-327.18.2.el7.x86\_64
Architecture: x86\_64

**Changesets**

_2016-05-18 12:01:32 +00:00_ by _gbeutner_ bb69540b32c833720ed69318fb04572e64ffaee7

    Fix exception in PerfdataWriter::RotateFile
    
    fixes #11801

_2016-05-19 07:50:55 +00:00_ by _gbeutner_ 0e76876228fadda025b0e1ac4b82e37b96f384e9

    Fix exception in PerfdataWriter::RotateFile
    
    fixes #11801

---

**Relations**:

* relates [#9236](https://dev.icinga.com/issues/9236)

**Comment by frankiejol** [comment]
This happens to me too.
This is icinga 2.6.0-2 installed from Debian Stretch packages.
When I restart icinga2 it complains about the perfdata-files.

```
critical/ConfigItem: Error: Function call 'rename' for file '/var/spool/icinga2/tmp/host-perfdata' failed with error code 2, 'No such file or directory'
	(0) Activating object 'perfdata' of type 'PerfdataWriter'
 critical/ConfigItem: 1 error
critical/cli: Error activating configuration.

```


To successfully restart icinga2 I have to do:
`rm /var/spool/icinga2/tmp/*-perfdata ; /etc/init.d/icinga2 restart`

Please let me know if you need more information.

**Comment by dazed51** [comment]
Ran into this issue on icinga2  2.10.5-1.stretch, debian 9

 critical/Application: Error: Function call 'rename' for file '/var/spool/icinga2/tmp/service-perfdata' failed with error code 2, 'No such file or directory'

Ran the suggested fix and worked. Have not had an issue with restarting services since I last had to restart them prior to the last patch of the application.
