### ISSUE TITLE
[dev.icinga.com #11833] Does not validate certificates by sub-CAs

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4235]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11833

**Created by towo on 2016-05-24 12:04:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-05-24 12:38:33 +00:00 (in Redmine)_

    Icinga Version: 2.4.7
    Backport?: Not yet backported
    Include in Changelog: 1

---

Cheers,

currently rolling out icinga2 in an AD-based environment where there is an offline root CA that's signed the certificates for two different zones.

I have yet to find any way to make icinga2 recognize that all certificates signed by sub-CAs of the root CA should be accepted.

Methods I've tried:
1.) Use the root certificate for ca\_path.
2.) Use a bundle CA certificate with all relevant CAs catted together for ca\_path.
3.) Try to setup multiple ApiListeners.

All without avail.

**Comment by dnsmichi** [comment]
In 2.11 we will be using boost::asio::ssl which likely solves the issue. If not, please create a new issue then.
