### ISSUE TITLE
[dev.icinga.com #11846] Empty Zone object string causes Windows Agent to go crazy

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4237]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11846

**Created by cstein on 2016-05-25 16:15:44 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-05-25 16:15:44 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

If you configure a zone object on the Windows-Agent with an empty string by accident

object Zone "" {}

the Agent will consume about 50% of your CPU and keeps using more and more memory of the system, resulting in crash.
The Icinga 2 config validation does not recognice this.

The interesting part: This behaviour will also happen by trying to validate the config with 'icinga2 daemon -C' and 'freeze' on information/ApiListener: My API identity:
From this part on, the Agent continues to consume CPU and Memory until either stopped or the system died.

Not sure if this issue appears on Linux systems as well. Tested only on Windows with Agent 2.4.10 x64

**Comment by dnsmichi** [comment]
This has been fixed with newer versions of Icinga 2. Right now you'll get a zone loop detection error.
