### ISSUE TITLE
[dev.icinga.com #11860] Default mail notification from header

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4242]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11860

**Created by bsheqa on 2016-05-30 15:26:28 +00:00**

Assignee: _elippmann_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-05 10:10:07 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

By default notification emails have "nagios" in their from header. This is because the icinga2 process is running as user nagios.
Since nobody is willing to change that username, I propose at least change the from header in the mail-notification scripts.

    --- mail-host-notification.sh   2016-04-05 15:22:53.000000000 +0000
    +++ mail-host-notification.sh.new   2016-05-30 15:20:32.924207565 +0000
    @@ -15,6 +15,7 @@
     Comment: [$NOTIFICATIONAUTHORNAME] $NOTIFICATIONCOMMENT
     TEMPLATE
     `
    +hostname=`hostname -f`

    -/usr/bin/printf "%b" "$template" | mail -s "$NOTIFICATIONTYPE - $HOSTDISPLAYNAME is $HOSTSTATE" $USEREMAIL
    +/usr/bin/printf "%b" "$template" | mail -a "From: Icinga " -r icinga@$hostname -s "$NOTIFICATIONTYPE - $HOSTDISPLAYNAME is $HOSTSTATE" $USEREMAIL

**Attachments**

* [mail-notification-from-header.patch](https://dev.icinga.com/attachments/download/3423/mail-notification-from-header.patch) bsheqa - _2016-06-09 07:53:20 +00:00_

---

**Relations**:

* relates [#11860](https://dev.icinga.com/issues/11860)

**Comment by dnsmichi** [comment]
This should be solved by this PR: #5170

**Comment by dnsmichi** [comment]
Merged with #5170
