### ISSUE TITLE
[dev.icinga.com #11861] Document flapping

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4243]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11861

**Created by mfrosch on 2016-05-31 14:51:24 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-02 11:41:58 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

We need to document flapping, so a user understands what is going on, and what to expect from the available configuration.

---

**Relations**:

* relates [#11654](https://dev.icinga.com/issues/11654)
* duplicates [#11861](https://dev.icinga.com/issues/11861)

**Comment by dnsmichi** [comment]
Will be continued in #4982.
