### ISSUE TITLE
[dev.icinga.com #11864] Kernel panic/oops 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4245]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11864

**Created by erikandersonmx on 2016-05-31 18:02:31 +00:00**

Assignee: _erikandersonmx_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-07 18:00:13 +00:00 (in Redmine)_

    Icinga Version: 2.4.10-1~ppa1~precise1
    Backport?: Not yet backported
    Include in Changelog: 1

---

From here https://www.reddit.com/r/icinga/comments/4i0vf1/kernel\_panic\_on\_ubuntu\_1204/

I can't reliably reproduce but it happens on restart of service after a config change.

**Attachments**

* [po-qa-wormhole1_crashlog](https://dev.icinga.com/attachments/download/3402/po-qa-wormhole1_crashlog) erikandersonmx - _2016-05-31 18:01:39 +00:00_

**Comment by dnsmichi** [comment]
I believe it's not.
