### ISSUE TITLE
[dev.icinga.com #11868] boost::thread_resource_error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4249]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11868

**Created by erikandersonmx on 2016-05-31 23:39:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-30 14:34:21 +00:00 (in Redmine)_

    Icinga Version: 2.4.10-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Error: boost::thread\_resource\_error: Resource temporarily unavailable

(0) libbase.so: void boost::throw\_exception<boost::thread_resource_error>(boost::thread\_resource\_error const&) (+0x151) \[0x7f897aa2ce21\]
(1) libbase.so: icinga::WorkQueue::Enqueue(boost::function<void ()> const&, icinga::WorkQueuePriority, bool) (+0x560) \[0x7f897a9eadf0\]
(2) libconfig.so: icinga::ConfigItem::CommitNewItems(boost::intrusive\_ptr<icinga::ActivationContext> const&, icinga::WorkQueue&, std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> &gt; &gt;&) (+0x38f) \[0x7f897a69a95f\]
(3) libconfig.so: icinga::ConfigItem::CommitItems(boost::intrusive\_ptr<icinga::ActivationContext> const&, icinga::WorkQueue&, std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> &gt; &gt;&) (+0xa5) \[0x7f897a69f3a5\]
(4) libcli.so: icinga::DaemonUtility::LoadConfigFiles(std::vector<std::string, std::allocator<std::string> &gt; const&, std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> &gt; &gt;&, icinga::String const&, icinga::String const&) (+0xab) \[0x7f897a395f9b\]
(5) libcli.so: icinga::DaemonCommand::Run(boost::program\_options::variables\_map const&, std::vector<std::string, std::allocator<std::string> &gt; const&) const (+0x299) \[0x7f897a3a5559\]
(6) /usr/lib/x86\_64-linux-gnu/icinga2/sbin/icinga2() \[0x411acd\]
(7) /usr/lib/x86\_64-linux-gnu/icinga2/sbin/icinga2() \[0x40f17a\]
(8) libc.so.6: \_\_libc\_start\_main (+0xf5) \[0x7f8979a72f45\]
(9) /usr/lib/x86\_64-linux-gnu/icinga2/sbin/icinga2() \[0x40f270\]

**Comment by dnsmichi** [comment]
@N-o-X we've discussed to add a better error message here. This could come in handy to learn more about the thread pool and available resources.

**Comment by dnsmichi** [comment]
I'm moving this into a more clear issue with #6600.
