### ISSUE TITLE
[dev.icinga.com #11944] Icinga should log HTTP bodies for API requests

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4282]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11944

**Created by tclh123 on 2016-06-15 09:05:50 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-05 06:39:22 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Should icinga provide access log whiich logging api requests?

---

**Relations**:

* relates [#11944](https://dev.icinga.com/issues/11944)

**Comment by dnsmichi** [comment]
HttpUtility::FetchRequestParameters() contains the request body logging already, but only for debug builds. Could become spam-ish if we enable that for the LogInformation level.

**Comment by Crunsher** [comment]
Is this something we really want? I'm itching to close this

**Comment by ClemensBW** [comment]
yes, for development or logging what other api users reqest with his access. Enable the icinga2 debug option is very chatty in big stages.

**Comment by dnsmichi** [comment]
That really depends on more advanced log filters.

Then you may have the chance to add specific logger objects which filter only API requests on a defined level. I wouldn't go the route to just add and log it to the debug log now. The next feature request is probably to log entire cluster messages for debugging.

That also may decrease the overall performance in large setups with many requests and messages.

**Comment by dnsmichi** [comment]
Actually I don't care much anymore whether the debug log is flooded or not. The patch just removes the debug build ifdefs, I always had that enabled here.
