### ISSUE TITLE
[dev.icinga.com #11950] http command definition does not permit use of vhost

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4286]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11950

**Created by davidc on 2016-06-15 17:41:59 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-09 15:08:35 +00:00 (in Redmine)_

    Icinga Version: r2.4.10-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

The default http check in /usr/share/icinga2/include/command-plugins.conf does not permit the use of vhosts unless they happen to be on the server's own IP.

If you specify vars.vhost and vars.http\_address, the check\_http plugin will prefer to connect to the http\_address rather than resolving the http\_vhost

If you specify vars.vhost without vars.http\_address, the CheckCommand definition will forcibly insert http\_address due to this line:

vars.http\_address = "$check\_address$"

which I believe should be amended to:

if (vars.http\_vhost != null) {
vars.http\_address = "$check\_address$"
}

**Comment by htriem** [comment]
Closed, #4965 is dealing with the same issue.
