### ISSUE TITLE
[dev.icinga.com #11994] global_templates not working when enabling later

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4301]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11994

**Created by snoopy1978 on 2016-06-20 15:28:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-21 11:30:00 +00:00 (in Redmine)_

    Icinga Version: 2.4.7
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi everyone,

just playing aroung with icinga2 and clustering and came across this issue:

I have a ha cluster of 2 icinga2 nodes up and running, different hosts and services resides in the zone. At this point the "global-template" zone is commented out at all nodes, everything working fine as expected.
Now I want to enable global templates. Therefore I un-commented the global-template objects in both zones.conf on each node. Afterwards I moved the template object config file from the master zone config dir to a newly created "global-zone" config dir (under ..../zones.d). Then I restarted the master config node which works fine.
Afterwards I restarted the second node which fails. In the log file during compiling the config files, icinga2 errors out with the message, the "generic-host" template does not exist.

My assumption:
The global-templates arn't initially synced when icinga2 comes to compiling the config files with existing hosts and therefore fails to start. But for syncing the global templates it has to start completely...
Right?

Thx in advance
Snoopy

---

**Relations**:

* relates [#10000](https://dev.icinga.com/issues/10000)

**Comment by dnsmichi** [comment]
Imho this should be taken into account when looking at #4354.
