### ISSUE TITLE
[dev.icinga.com #12025] Apply rule in zone affects other zones

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4315]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12025

**Created by alexbs on 2016-06-23 08:05:16 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _Backlog_
Last Update: _2016-07-25 14:36:53 +00:00 (in Redmine)_

    Icinga Version: 2.4.7
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi everyone,

while configuring an Icinga2 distributed setup with multiple zones we found the following bug:

Setup:
- setup with a configuration master for distributing the configuration to other zones.

Expected behavior for apply rules:
- when you setup a service by using an apply rule inside the configuration folder of one child zone
this rule should only effect objects (Hosts) also defined inside this configurationfolder (zone)
- That is what the documentation says: "Apply rules specified inside zone directories will only affect endpoints in the same zone or below."

Real behavior:
- when i setup a normal apply rule like the following inside the configuration folder of one child zone:
apply Service "MYping4" {
import "generic-service"
check\_command = "ping4"
assign where host.address
}
ALL Hosts with an address from all Zones get this service assigned.
As workaround you can use 'assign where ( host.zone=="satellite")' but this is kind of dirty.

This bug was was allready discussed in the following german forum:
https://monitoring-portal.org/index.php?thread/36515-zonen-werden-bei-services-ignoriert/

kind regards
Alex

---

**Relations**:

* relates [#12025](https://dev.icinga.com/issues/12025)
* relates [#10000](https://dev.icinga.com/issues/10000)

**Comment by gunnarbeutner** [comment]
There are no plans to support this.
