### ISSUE TITLE
[dev.icinga.com #12026] External Commands are not synced between nodes of a zone

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4316]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12026

**Created by mwaldmueller on 2016-06-23 08:15:10 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-06-23 09:02:01 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

External commands like "CHANGE\_CUSTOM\_USER\_VAR" should be synced from one node (e.g. master01) to other nodes of the same zone (e.g. master02).

**Comment by dnsmichi** [comment]
Please use the REST API as primary transport, where this problem does not exist.
