### ISSUE TITLE
[dev.icinga.com #12042] API should provide CORS Header

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4326]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12042

**Created by rhillmann on 2016-06-25 17:14:59 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-09-07 11:39:52 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

I am missing cross origin header for the API, this will help to use the API directly within javascript in the Browser.

**Comment by dnsmichi** [comment]
- Requires tests for all request methods (GET, POST, etc.)

**Comment by cinek810** [comment]
quice easy solution would be to setup nginx in front of icinga API, with config like this:
<code>
server {

 listen *:5660;
 location / {
 add_header 'Access-Control-Allow-Origin' 'http://X.Y.Z.Z:3000' always;
 add_header 'Access-Control-Allow-Methods' 'GET' always;
 add_header 'Access-Control-Allow-Headers' "Authorization" always;

 if ( $request_method = OPTIONS )
 {
     add_header 'Access-Control-Allow-Origin' 'http://X.Y.Z.Z:3000' always;
     add_header 'Access-Control-Allow-Methods' 'GET' always;
     add_header 'Access-Control-Allow-Headers' "Authorization" always;
     add_header 'Content-Length' 0 always;
     return 200;
   }
   proxy_pass         https://127.0.0.1:5665/;
   proxy_redirect     off;
 }
}
</code>

**Comment by gunnarbeutner** [comment]
Oh, why's that? Requiring yet another external component (in this case: nginx) seems unnecessary.

**Comment by dnsmichi** [comment]
You could still use your own http proxy for older versions. Grafana provides CORS too, and imho it is a good idea to provide such inside the REST API as well (i.e. for JS clients as browser widgets).

**Comment by cinek810** [comment]
First - Icinga2 is very nice software and I'm really thankful that you're doing it. It's always nice to have a feature, but because it's for JS in browsers (I'm using it in grafana text panel ) it's probably not the majority of API applications. There are always some "external" components web interface, database, plugins etc. I just thought that every line of code requires maintenance effort in the future and wanted to be on your side... :)
