### ISSUE TITLE
[dev.icinga.com #12076] Explain how to register functions into the globals scope

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4336]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12076

**Created by mfriedrich on 2016-06-30 09:54:16 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-06-30 09:54:16 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Using that over here already: http://docs.icinga.org/icinga2/latest/doc/module/icinga2/toc\#!/icinga2/latest/doc/module/icinga2/chapter/advanced-topics#use-functions-assign-where

**Comment by dnsmichi** [comment]
Duplicated by #6075
