### ISSUE TITLE
[dev.icinga.com #12118] Evaluate cluster scenario w/ 2 masters and agent and outdated config

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4353]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12118

**Created by mfriedrich on 2016-07-06 14:00:24 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-06 14:00:24 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

-   1st master has the current config (v1 config)
-   2nd master got an error, keeps the old config (v2 config)
-   agent receives config from either 1st or 2nd master

Check whether the .timestamp file works correctly or the client keeps disconnecting or restarting.

**Comment by dnsmichi** [comment]
This sources from an ongoing analysis in 2016, and was found invalid after finding the root cause for the config sync restarts.
