### ISSUE TITLE
[dev.icinga.com #12119] Use config staging for cluster config sync

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4354]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12119

**Created by mfriedrich on 2016-07-06 14:34:24 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-28 13:37:11 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Master syncs a "complete" config to its /var/lib directory.
Config sync partially syncs the zone to the satellite.
Satellite is missing config parts.
Satellite restarts - cannot start again due to config errors.

Idea: Use a staging system which validates the configuration after syncing it. Do not override the active stage if the validation process fails. If everything is ok, restart the satellite.

Hint: Update the "icinga" check with the last failed reload timestamp - which would be the last failed validation then (!) if existing, otherwise the reload.

**Comment by dnsmichi** [comment]
I'm closing this in favor of #6716.
