### ISSUE TITLE
[dev.icinga.com #12128] Windows 2016 installer package (WSA)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4357]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12128

**Created by cstein on 2016-07-07 16:53:13 +00:00**

Assignee: _TheFlyingCorpse_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-04 14:58:41 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

As far as I can tell atleast Windows 2016 Nano Server is no longer supporting MSI packages for installing software.
Microsoft switched to Windows Server App (WSA) for their Nano server.

We would require such packages in order to install the agent on these systems.

**Changesets**

_2016-08-03 22:11:06 +00:00_ by _TheFlyingCorpse_ ea4335e7df906b39d26b62808a94d80c06ccdd23

    Add an option to control wether to include the ClrCheckTask functionality in methods
    
    refs #12128

_2016-08-03 22:11:15 +00:00_ by _TheFlyingCorpse_ c938d2ba4990376ceeb2de31e7a69202e799314c

    Remove dependency on Msi lookup with a function based on the path of the exe file
    
    refs #12128

_2016-08-04 01:49:56 +00:00_ by _TheFlyingCorpse_ 2f38fda1894be39d83b0d27c072e707675d74524

    Add an option to include the Msi function with its headers or not when compiling.
    
    refs #12128

_2016-08-05 07:48:18 +00:00_ by _TheFlyingCorpse_ 973737e93785bd4c8de541c5ae1d4bd6bfb7faaa

    Replace MSI lookup with a relative path one for the GetIcingaInstallPath
    
    refs #12128

_2016-08-05 09:36:51 +00:00_ by _TheFlyingCorpse_ 799a05232d3879bb4741d501a832af04c988d297

    Replace MSI lookup with a relative path one for the GetIcingaInstallPath
    
    refs #12128

_2016-08-05 23:20:36 +00:00_ by _TheFlyingCorpse_ 662a1340560e203a804e66f93cf155a918dd14f0

    Add a fallback incase Msi.dll is not available
    
    refs #12128

_2016-08-06 09:28:44 +00:00_ by _TheFlyingCorpse_ 7651a62d2f3f7d76ee30ce32ecda935e55702205

    Update ScriptUtils::MsiGetComponentPathShim to be only called on demand
    
    refs #12128

_2016-08-08 13:54:33 +00:00_ by _TheFlyingCorpse_ b38b367c34082f059d07fc141107f9e5e1a6f7e1

    Add a fallback incase Msi.dll is not available
    
    refs #12128

_2016-08-08 13:54:40 +00:00_ by _TheFlyingCorpse_ 205d0628a4c976729327c65b2feffe6c06cb3d0d

    Update ScriptUtils::MsiGetComponentPathShim to be only called on demand
    
    refs #12128

_2016-08-18 10:53:34 +00:00_ by _TheFlyingCorpse_ c0573c9c8c0bb413c10c825e70fe9cd519ea0e96

    Add a fallback incase Msi.dll is not available
    
    refs #12128

_2016-08-18 10:53:34 +00:00_ by _TheFlyingCorpse_ d73efc5191a702aff9e523bc5ec25a346d64ac9f

    Update ScriptUtils::MsiGetComponentPathShim to be only called on demand
    
    refs #12128

_2016-08-18 10:53:34 +00:00_ by _TheFlyingCorpse_ 70a25c35a2e85ee85d75d42fc2a7b4df8d3c6f4e

    Add an option to control wether to include the ClrCheckTask functionality in methods
    
    refs #12128

**Comment by TheFlyingCorpse** [comment]
Subscribed

**Comment by dnsmichi** [comment]
Similar thing with #4957, we'll have to wait for a new strategy.
