### ISSUE TITLE
[dev.icinga.com #12143] doc: missing information how to set up pgsql unix socket connections with IDO

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4360]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12143

**Created by calestyo on 2016-07-12 21:28:02 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2016-09-30 13:38:02 +00:00_)
Target Version: _(none)_
Last Update: _2016-09-30 13:38:02 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hey.

I think the docs should tell how to properly set up a unix socket configuration for IDO with postgresql.

I.e. at least here:
http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/object-types#objecttype-idopgsqlconnection
that one can apparently simply set host="" and it will use UNIX sockets instead of TCP.

Perhaps also a more secure version of pg\_hba, something like:
local icinga icinga peer
is enough if the db-name AND psql.username AND system username are icinga.
If the system username differs, then e.g. the following is needed:
local icingaDB icingaUSER peer map=icinga
with the following in pg\_ident:
icinga nagios icingaUSER
(nagios being here the system-username)

Actually, I think, for security reasons, using UNIX sockets should be advertised as the default, when the DB server is local.

Cheers,
Chris.

**Comment by Victor-D** [comment]
Hello 2022 here :) 
Is there a way to use a unix socket path with IdoPgsqlConnection ?
