### ISSUE TITLE
[dev.icinga.com #12148] Checks should not result in "terminated" when restarting an Icinga node

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4364]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12148

**Created by tgelf on 2016-07-13 16:38:35 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-07-25 15:37:39 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

Restarting a busy Icinga instance results in lots of checked objects turning there state into unknown, with a plugin output of:

This should neither have an influence on current state nor on state history at all.

**Comment by dnsmichi** [comment]
Should also take into account that rescheduling the next check might be needed.

**Comment by dnsmichi** [comment]
fix/do-not-return-unknown-on-restart holds an incomplete untested fix. This needs further adoption, e.g. to somehow signal the scheduler to ignore the check result and reschedule the check.

**Comment by dnsmichi** [comment]
This might need larger changes with check execution, similar to how #5988 is now implemented. I'll put this on hold for now @lippserd

**Comment by Crunsher** [comment]
@dnsmichi fix works for not giving the "Terminated" Unknown check result.
TODO is now rescheduling the checks for after the restart.
