### ISSUE TITLE
[dev.icinga.com #12174] Add nrpe check commands for nsclient++

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4373]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12174

**Created by lbetz on 2016-07-18 18:08:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-28 14:54:45 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

These commands can use to migrate windows monitoring from nrpe-server to icinga2 agent.

depends on:

commit 73d0e75f6f715e3f177ca2181ba3605f8d19e23a
Author: Gunnar Beutner &lt;gunnar.beutner@netways.de&gt;
Date: Mon Jul 18 13:47:53 2016 +0200

Update AUTHORS

refs [\#11063](https://dev.icinga.com/issues/11063)

**Attachments**

* [0001-add-nrpe-check-commands-to-monitor-nsclient.patch](https://dev.icinga.com/attachments/download/3503/0001-add-nrpe-check-commands-to-monitor-nsclient.patch) lbetz - _2016-07-18 18:06:05 +00:00_

**Comment by dnsmichi** [comment]
It won't help much, and since the existance of nscp_api it becomes even more easy.
