### ISSUE TITLE
[dev.icinga.com #12181] Overwriting global type variables crashes Icinga

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4377]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12181

**Created by pef on 2016-07-20 05:23:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-05 06:35:14 +00:00 (in Redmine)_

    Icinga Version: 2.4.10-530
    Backport?: Not yet backported
    Include in Changelog: 1

---

On our distributed setup the satellite crashes, although we're using an Icinga2 version which includes the patch from [\#11946](https://dev.icinga.com/issues/11946) (we're using snapshots on the satellite). The backtrace looks like this:

    # gdb /usr/lib64/icinga2/sbin/icinga2
    GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    For bug reporting instructions, please see:
    ...
    Reading symbols from /usr/lib64/icinga2/sbin/icinga2...Reading symbols from /usr/lib/debug/usr/lib64/icinga2/sbin/icinga2.debug...done.
    done.
    (gdb) run daemon
    Starting program: /usr/lib64/icinga2/sbin/icinga2 daemon
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    [New Thread 0x7ffff0c90700 (LWP 12955)]
    [New Thread 0x7ffff048f700 (LWP 12956)]
    [New Thread 0x7fffefc8e700 (LWP 12957)]
    [New Thread 0x7fffef48d700 (LWP 12958)]
    [New Thread 0x7fffeec8c700 (LWP 12959)]
    [New Thread 0x7fffee48b700 (LWP 12960)]
    [Thread 0x7fffee48b700 (LWP 12960) exited]
    [Thread 0x7fffef48d700 (LWP 12958) exited]
    [Thread 0x7fffefc8e700 (LWP 12957) exited]
    [Thread 0x7ffff048f700 (LWP 12956) exited]
    [Thread 0x7ffff0c90700 (LWP 12955) exited]
    [Thread 0x7fffeec8c700 (LWP 12959) exited]
    process 12951 is executing new program: /usr/lib64/icinga2/sbin/icinga2
    Missing separate debuginfos, use: debuginfo-install boost-program-options-1.53.0-25.el7.x86_64 boost-regex-1.53.0-25.el7.x86_64 boost-system-1.53.0-25.el7.x86_64 boost-thread-1.53.0-25.el7.x86_64 glibc-2.17-106.el7_2.6.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libcom_err-1.42.9-7.el7.x86_64 libedit-3.0-12.20121213cvs.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 ncurses-libs-5.9-13.20130511.el7.x86_64 openssl-libs-1.0.1e-51.el7_2.5.x86_64 pcre-8.32-15.el7_2.1.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 yajl-2.0.4-4.el7.x86_64 zlib-1.2.7-15.el7.x86_64
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    [New Thread 0x7ffff7fd7700 (LWP 12961)]
    [New Thread 0x7ffff7f96700 (LWP 12962)]
    [New Thread 0x7ffff7f55700 (LWP 12963)]
    [New Thread 0x7ffff7f14700 (LWP 12964)]
    [New Thread 0x7ffff7ed3700 (LWP 12965)]
    [New Thread 0x7ffff7e92700 (LWP 12966)]
    Detaching after fork from child process 12967.
    Detaching after fork from child process 12969.
    Detaching after fork from child process 12971.
    [2016-07-20 05:16:20 +0000] information/cli: Icinga application loader (version: v2.4.10-530-g959e250)
    [2016-07-20 05:16:20 +0000] information/cli: Loading configuration file(s).
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Committing config item(s).
    [New Thread 0x7ffff7e51700 (LWP 12973)]
    [New Thread 0x7ffff00dc700 (LWP 12974)]
    [2016-07-20 05:16:20 +0000] information/ApiListener: My API identity: satellite.example.com
    [2016-07-20 05:16:20 +0000] warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 ApiListener.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 2 Zones.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 2 FileLoggers.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 2 Endpoints.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 53 CheckCommands.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 2 NotificationCommands.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 12 Notifications.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 UserGroup.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 Host.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 2 HostGroups.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 Downtime.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 3 TimePeriods.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 User.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 3 ServiceGroups.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 11 Services.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 ScheduledDowntime.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 PerfdataWriter.
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Instantiated 1 ExternalCommandListener.
    [2016-07-20 05:16:20 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
    [Thread 0x7ffff7e51700 (LWP 12973) exited]
    [Thread 0x7ffff00dc700 (LWP 12974) exited]
    [2016-07-20 05:16:20 +0000] information/ConfigItem: Triggering Start signal for config items
    [New Thread 0x7ffff00dc700 (LWP 12975)]
    [New Thread 0x7ffff7e51700 (LWP 12976)]
    [2016-07-20 05:16:20 +0000] information/ApiListener: Adding new listener on port '5665'
    [New Thread 0x7ffff009b700 (LWP 12977)]
    [New Thread 0x7ffff005a700 (LWP 12979)]
    [New Thread 0x7fffe37d9700 (LWP 12978)]

    Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7ffff7f55700 (LWP 12963)]
    icinga::Zone::GetParent (this=0x0) at ../remote/zone.cpp:50
    50              return m_Parent;
    Missing separate debuginfos, use: debuginfo-install boost-program-options-1.53.0-25.el7.x86_64 boost-regex-1.53.0-25.el7.x86_64 boost-system-1.53.0-25.el7.x86_64 boost-thread-1.53.0-25.el7.x86_64 glibc-2.17-106.el7_2.6.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libcom_err-1.42.9-7.el7.x86_64 libedit-3.0-12.20121213cvs.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 ncurses-libs-5.9-13.20130511.el7.x86_64 openssl-libs-1.0.1e-51.el7_2.5.x86_64 pcre-8.32-15.el7_2.1.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 yajl-2.0.4-4.el7.x86_64 zlib-1.2.7-15.el7.x86_64
    (gdb) bt

    #0  icinga::Zone::GetParent (this=0x0) at ../remote/zone.cpp:50
    #1  0x00007ffff6815238 in icinga::ApiListener::ApiTimerHandler (this=0x7fffcc000c50) at ../remote/apilistener.cpp:491
    #2  0x00007ffff71ec7b3 in operator() (a0=..., this=) at /usr/include/boost/function/function_template.hpp:767
    #3  m_invoke&)>, 0u, const boost::intrusive_ptr&> (args=..., func=..., this=)

at /usr/include/boost/signals2/detail/variadic\_slot\_invoker.hpp:89

    #4  operator()&)>, const boost::intrusive_ptr&> (args=..., func=..., this=)

at /usr/include/boost/signals2/detail/variadic\_slot\_invoker.hpp:78

    #5  m_invoke >, boost::signals2::slot&), boost::function&)> >, boost::signals2::mutex> > > (connectionBody=..., this=)

at /usr/include/boost/signals2/detail/variadic\_slot\_invoker.hpp:114

    #6  operator() >, boost::signals2::slot&), boost::function&)> >, boost::signals2::mutex> > > (connectionBody=..., this=)

at /usr/include/boost/signals2/detail/variadic\_slot\_invoker.hpp:107

    #7  dereference (this=0x7ffff7f54680) at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:82
    #8  dereference&>, std::_List_iterator >, boost::signals2::slot&), boost::function&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body >, boost::signals2::slot&), boost::function&)> >, boost::signals2::mutex> > > (f=...) at /usr/include/boost/iterator/iterator_facade.hpp:514
    #9  operator* (this=0x7ffff7f54680) at /usr/include/boost/iterator/iterator_facade.hpp:639
    #10 operator()&>, std::_List_iterator >, boost::signals2::slot&), boost::function&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body >, boost::signals2::slot&), boost::function&)> >, boost::signals2::mutex> > > (last=..., first=..., this=) at /usr/include/boost/signals2/optional_last_value.hpp:55
    #11 operator(), boost::signals2::detail::slot_call_iterator_t&>, std::_List_iterator >, boost::signals2::slot&), boost::function&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body >, boost::signals2::slot&), boost::function&)> >, boost::signals2::mutex> > > (last=..., first=..., combiner=..., this=)

at /usr/include/boost/signals2/detail/result\_type\_wrapper.hpp:64

    #12 boost::signals2::detail::signal_impl const&), boost::signals2::optional_last_value, int, std::less, boost::function const&)>, boost::function const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr const&) (this=, args#0=...) at /usr/include/boost/signals2/detail/signal_template.hpp:246
    #13 0x00007ffff71965a4 in operator() (args#0=..., this=0x7fffcc03b618) at /usr/include/boost/signals2/detail/signal_template.hpp:695
    #14 icinga::Timer::Call (this=0x7fffcc03b600) at ../base/timer.cpp:94
    #15 0x00007ffff7192f58 in operator() (this=0x7ffff7f54930) at /usr/include/boost/function/function_template.hpp:767
    #16 icinga::ThreadPool::WorkerThread::ThreadProc (this=0x7ffff7449f50 , queue=...) at ../base/threadpool.cpp:138
    #17 0x00007ffff7bd124a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
    #18 0x00007ffff4802dc5 in start_thread () from /lib64/libpthread.so.0
    #19 0x00007ffff452fced in clone () from /lib64/libc.so.6

</pre>
The relevant zones.conf looks like this:

    /*
     * Endpoint and Zone configuration for a cluster setup
     * This local example requires `NodeName` defined in
     * constants.conf.
     */

    object Endpoint "master.example.com" {

    }

    object Zone "master-zone" {
      Endpoint = "master.example.com"
    }

    object Endpoint "satellite.example.com" {
      host = "satellite.example.com"
    }

    object Zone "satellite" {
      endpoints = [ "satellite.example.com ]
      parent = "master-zone"
    }

Any idea?

Best regards,
Stephan

**Comment by dnsmichi** [comment]
No, there isn't.
