### ISSUE TITLE
[dev.icinga.com #12195] Don't try to reconnect to all other endpoints at the same time

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4382]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12195

**Created by mfriedrich on 2016-07-21 11:51:58 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-21 11:51:58 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

**Comment by gunnarbeutner** [comment]
AFAIK this has already been fixed.
