### ISSUE TITLE
[dev.icinga.com #12241] Clients should gracefully report to the parent endpoint if not configured

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4406]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12241

**Created by mfriedrich on 2016-07-27 08:59:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-07-28 14:51:08 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Helps debugging why clients do not execute checks with command\_endpoint for example.

**Comment by dnsmichi** [comment]
I don't remember what exactly we were trying to solve here. Also, the issue lacks quality.
