### ISSUE TITLE
[dev.icinga.com #12242] Kernel Oops followed by server crash

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4407]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12242

**Created by ajoaugustine on 2016-07-27 09:23:17 +00:00**

Assignee: _ajoaugustine_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-07 18:31:25 +00:00 (in Redmine)_

    Icinga Version: 2.4.10-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Ubuntu 14.04 production box having Icinga2 version 2.4.10-1 crashed with the following Kernel Oops

`kernel: [581429.462692] BUG: unable to handle kernel NULL pointer dereference at 0000000000000018
kernel: [581429.462763] IP: [<ffffffff810988aa>] set_task_cpu+0xba/0x1c0
kernel: [581429.462791] PGD a9e6c067 PUD 211c4067 PMD 0
kernel: [581429.462811] Oops: 0000 [#1] SMP
kernel: [581429.463056] CPU: 2 PID: 11402 Comm: icinga2 Not tainted 3.13.0-79-generic #123-Ubuntu`

Crash dump is attached.

**Attachments**

* [icinga-node-crash-syslog.txt](https://dev.icinga.com/attachments/download/3513/icinga-node-crash-syslog.txt) ajoaugustine - _2016-07-27 09:16:46 +00:00_
* [cpu-1.png](https://dev.icinga.com/attachments/download/3634/cpu-1.png) ajoaugustine - _2016-09-16 14:46:42 +00:00_
* [cpu-2.png](https://dev.icinga.com/attachments/download/3635/cpu-2.png) ajoaugustine - _2016-09-16 14:46:51 +00:00_

**Comment by dnsmichi** [comment]
No further feedback received.
