### ISSUE TITLE
[dev.icinga.com #12243] Database StatsLogger too noisy

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4408]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12243

**Created by iustin on 2016-07-27 21:31:00 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-27 21:31:00 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

I've recently enable a database module and since then I see in the logs every 15 seconds:

    Jul 27 22:03:28 debian icinga2[6926]: [2016-07-27 21:56:13 +0200] information/IdoPgsqlConnection: Query queue items: 0, query rate: 3.65/s (219/min 1141/5min 3393/15min);

Looking at the sources, it seems that this log message is generated unconditionally at info severity, with no method to disable. Note that in my syslog features I have:

    object SyslogLogger "syslog" {
        severity = "warning"
    }

But this still doesn't stop the logging from the db module. Is it really needed to log that often an informational message? It would make sense to only log when the database can't keep up, but just for the query rate it seems somewhat pointless (compared to actually sending this to a stats system).

---

**Relations**:

* duplicates [#12243](https://dev.icinga.com/issues/12243)

**Comment by dnsmichi** [comment]
It helps debugging. Since the log itself is an application log, it doesn't hurt to keep these log entries.
