### ISSUE TITLE
[dev.icinga.com #12248] Better Debugging for InfluxdbWriter

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4411]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12248

**Created by spjmurray on 2016-07-28 13:04:58 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-28 14:00:28 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

In response to [\#12228](https://dev.icinga.com/issues/12228) where I can't see anything wrong with the debug logs straight off the bat I've concluded it may be beneficial/more economical to parse the 4XX responses and print out the error messages from InfluxDB. In my setup I don't see anything logged on the server side, and have to do a packet capture to grab the JSON. This obviously doesn't work if the stream is over TLS.

This adds in support to read the response body, parse the JSON and extract the error message and print it to give first-time data capture e.g. when it happens we can derive why and not have to mess about with recreates.

**Attachments**

* [0001-Verbose-InfluxDB-Error-Logging.patch](https://dev.icinga.com/attachments/download/3518/0001-Verbose-InfluxDB-Error-Logging.patch) spjmurray - _2016-07-28 14:00:20 +00:00_

**Comment by dnsmichi** [comment]
I totally missed this patch, sorry.
