### ISSUE TITLE
[dev.icinga.com #12253] /usr/lib/icinga2/prepare-dirs does not create /var/cache/icinga2 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4414]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12253

**Created by haasn on 2016-07-28 15:40:48 +00:00**

Assignee: _(none)_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-08-03 08:26:12 +00:00 (in Redmine)_

    Icinga Version: r2.4.10-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

The /usr/lib/icinga2/prepare-dirs script does not seem to ensure /var/cache/icinga2 is present and writable. This causes a freshly installed icinga2 to crash out of the box on my end:

    -- Unit icinga2.service has begun starting up.
    Jul 28 17:10:04 nanodesu icinga2[8534]: [2016-07-28 17:10:04 +0200] information/cli: Icinga application loader (version: r2.4.10-1)
    Jul 28 17:10:04 nanodesu icinga2[8534]: [2016-07-28 17:10:04 +0200] critical/Application: Error: Function call 'mkstemp' for file '/var/cache/icinga2/icinga2.debug.XXXXXX' failed with error code 2, 'No such file or directory
    Jul 28 17:10:04 nanodesu icinga2[8534]: Additional information is available in '/var/log/icinga2/crash/report.1469718604.3545589'
    Jul 28 17:10:04 nanodesu icinga2[8534]: [2016-07-28 17:10:04 +0200] information/cli: Icinga application loader (version: r2.4.10-1)
    Jul 28 17:10:04 nanodesu icinga2[8534]: [2016-07-28 17:10:04 +0200] critical/Application: Error: Function call 'mkstemp' for file '/var/cache/icinga2/icinga2.debug.XXXXXX' failed with error code 2, 'No such file or directory
    Jul 28 17:10:04 nanodesu icinga2[8534]: Additional information is available in '/var/log/icinga2/crash/report.1469718604.3545589'
    Jul 28 17:10:04 nanodesu systemd[1]: icinga2.service: Control process exited, code=killed status=6
    Jul 28 17:10:04 nanodesu systemd[1]: Failed to start Icinga host/service/network monitoring system.
    -- Subject: Unit icinga2.service has failed

I have fixed the issue by appending the following lines to prepare-dirs:

    ICINGA2_CACHE_DIR=$ICINGA2_STATE_DIR/cache/icinga2
    mkdir -p $ICINGA2_CACHE_DIR
    chown $ICINGA2_USER:$ICINGA2_GROUP $ICINGA2_CACHE_DIR
    chmod 750 $ICINGA2_CACHE_DIR

Icinga2 works correctly on my end with these changes present.

**Comment by ekohl** [comment]
The best solution would be to ship a tmpfiles.d file. Locally I've created ```/etc/tmpfiles.d/icinga2.conf``` with ```d /var/cache/icinga2 0750 icinga icinga``` as content to ensure the directory exists.

**Comment by ekohl** [comment]
I implemented the simple fix in the references PR by extending the current method using the code suggested by the author.
