### ISSUE TITLE
[dev.icinga.com #12335] dpkg creates invalid ido-mysql.conf when users chooses not to use dbconfig

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4448]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12335

**Created by gbeutner on 2016-08-09 09:24:41 +00:00**

Assignee: _mfrosch_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-08-09 09:24:41 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

Steps to reproduce:

Install icinga2-ido-mysql in a Docker container:

    Configuring icinga2-ido-mysql
    -----------------------------

    The icinga2-ido-mysql package must have a database installed and configured before it can be used.  This can be optionally handled with dbconfig-common.

    If you are an advanced database administrator and know that you want to perform this configuration manually, or if your database has already been installed and configured, you
    should refuse this option.  Details on what needs to be done should most likely be provided in /usr/share/doc/icinga2-ido-mysql.

    Otherwise, you should probably choose this option.

    Configure database for icinga2-ido-mysql with dbconfig-common? n

    Please specify whether Icinga 2 should use MySQL.

    You may later disable the feature by using the "icinga2 feature disable ido-mysql" command.

    Enable Icinga 2's ido-mysql feature? y

    dbconfig-common: writing config to /etc/dbconfig-common/icinga2-ido-mysql.conf

    Creating config file /etc/dbconfig-common/icinga2-ido-mysql.conf with new version

    Creating config file /etc/icinga2/features-available/ido-mysql.conf with new version

    /**
     * The db_ido_mysql library implements IDO functionality
     * for MySQL.
     */

    library "db_ido_mysql"

    object IdoMysqlConnection "ido-mysql" {
      user = "",
      password = "",
      host = "localhost",
      database = ""
    }

**Comment by dnsmichi** [comment]
#5109 could be related.

**Comment by dnsmichi** [comment]
Copied to Icinga/icinga-packaging/issues/34
