### ISSUE TITLE
[dev.icinga.com #12337] Icinga2 randomly crashes using the API

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4450]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12337

**Created by s1c on 2016-08-09 10:51:00 +00:00**

Assignee: _s1c_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-19 08:49:52 +00:00 (in Redmine)_

    Icinga Version: r2.4.10-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

we want to move our environment to icinga2 using the API for host/service creation and passive checks. We have small c\# client which gets installed on a win machine. It creates the host and services and submits checkresult via API.
In our Testing environment i enrolled it on 80 Machines with 457 Services.

A signed certificate is used for API Authentication.

Icinga2 is running for a while, then it crashes randomly. Sometimes after 1 minute, sometimes after several hours.
Also when creating a lot of Hosts/Services in a short time, the API seem to "hang" and newly created hosts wont show up in icinga2. When i restart icinga2 Hosts/Services can be created again.

Couldnt find very helpful information in debug.log. Also error messages seem to differ.
Sometimes a crash report is written, sometimes its not. I attached the latest crash reports from today.

Here is example from syslog when a crash happened:

`Aug  9 08:26:54 devmon icinga2[14580]: [2016-08-09 08:26:54 +0200] critical/ApiListener: Client TLS handshake failed
Aug  9 08:26:54 devmon icinga2[14580]: Context:
Aug  9 08:26:54 devmon icinga2[14580]: (0) Handling new API client connection
Aug  9 08:26:54 devmon icinga2[14580]: [2016-08-09 08:26:54 +0200] information/ApiListener: New client connection for identity 'foo.bar'
Aug  9 08:26:54 devmon icinga2[14580]: [2016-08-09 08:26:54 +0200] warning/TlsStream: TLS stream was disconnected.
Aug  9 08:26:54 devmon icinga2[14580]: [2016-08-09 08:26:54 +0200] information/ApiListener: New client connection for identity 'foo.bar'
Aug  9 08:26:54 devmon icinga2[14580]: [2016-08-09 08:26:54 +0200] information/ApiListener: New client connection for identity 'foo.bar'
Aug  9 08:26:54 devmon icinga2[14580]: [2016-08-09 08:26:54 +0200] information/ApiListener: New client connection for identity 'foo.bar'
Aug  9 08:26:54 devmon icinga2[14580]: [2016-08-09 08:26:54 +0200] information/HttpServerConnection: Request: GET /v1 (root)
Aug  9 08:26:55 devmon kernel: [  953.769667] icinga2[14621]: segfault at 0 ip           (null) sp 00007f7b432cd408 error 14 in icinga2[400000+24000]
Aug  9 08:26:55 devmon icinga2[14580]: [2016-08-09 08:26:54 +0200] information/ApiListener: New client connection
Aug  9 08:26:55 devmon systemd[1]: icinga2.service: main process exited, code=killed, status=11/SEGV
Aug  9 08:26:55 devmon systemd[1]: Unit icinga2.service entered failed state.`

Also sometimes i get the following error in log:

`` Error in `/usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2': corrupted double-linked list: 0x00007fae0802f970 *** ``

When this happens, i cannot start/stop/restart icinga2. Number of threads according to

`` watch -n1 ps -o nlwp `pidof icinga2` ``

are growing until limit is reached and the whole system hangs. Only help is to kill the icinga2 processes and start it after.

If u need any further information, please tell me and i will gladly try to provide them.

**Attachments**

* [report.1470723948.1957381](https://dev.icinga.com/attachments/download/3553/report.1470723948.1957381) s1c - _2016-08-09 10:43:52 +00:00_ - _crash report_
* [report.1470724643.543637](https://dev.icinga.com/attachments/download/3554/report.1470724643.543637) s1c - _2016-08-09 10:43:52 +00:00_ - _crash report_
* [report.1470729782.569571](https://dev.icinga.com/attachments/download/3555/report.1470729782.569571) s1c - _2016-08-09 10:43:52 +00:00_ - _crash report_
* [report.1470730546.564126](https://dev.icinga.com/attachments/download/3556/report.1470730546.564126) s1c - _2016-08-09 10:43:52 +00:00_ - _crash report_
* [report.1470730967.9664049](https://dev.icinga.com/attachments/download/3557/report.1470730967.9664049) s1c - _2016-08-09 10:43:52 +00:00_ - _crash report_
* [report.1470732224.7442291](https://dev.icinga.com/attachments/download/3558/report.1470732224.7442291) s1c - _2016-08-09 10:43:52 +00:00_ - _crash report_
* [report.1470734951.7326691](https://dev.icinga.com/attachments/download/3559/report.1470734951.7326691) s1c - _2016-08-09 10:43:52 +00:00_ - _crash report_
* [report.1470742523.329860](https://dev.icinga.com/attachments/download/3560/report.1470742523.329860) s1c - _2016-08-09 11:38:13 +00:00_
* [valgrind.zip](https://dev.icinga.com/attachments/download/3566/valgrind.zip) s1c - _2016-08-11 07:47:09 +00:00_
* [report.1470899562.665251](https://dev.icinga.com/attachments/download/3567/report.1470899562.665251) s1c - _2016-08-11 07:58:27 +00:00_ - _Crash report Icinga v2.4.10-616-gf3bb628_
* [report.1470899063.587378](https://dev.icinga.com/attachments/download/3568/report.1470899063.587378) s1c - _2016-08-11 07:58:27 +00:00_ - _Crash report Icinga v2.4.10-616-gf3bb628_

**Comment by dnsmichi** [comment]
Thanks for the feedback 👍
