### ISSUE TITLE
[dev.icinga.com #12397] serialize checks

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4459]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12397

**Created by cheetah on 2016-08-10 17:12:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-18 14:09:46 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

I have the problem that I have one test disturb other ones. So I'm locking for a mechanism to serialize (separate) this test.
I'm thinking for a feature I can give a serialize attribute (Context) to a check and so only one check with this context is running at the same time.
for example:
- check-A1: serialize\_ctx = "A"
- check-A2: serialize\_ctx = "A"
- check-B: serialize\_ctx = "B"

-&gt; check-A1 and check-A2 never run on the same time but the can probably run on the same time as check-B.

**Comment by dnsmichi** [comment]
Closing in favor of #7160 for a more refined concept and discussion.
