### ISSUE TITLE
[dev.icinga.com #12419] Don't allow more than one IDO config object

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4473]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12419

**Created by gbeutner on 2016-08-13 21:43:06 +00:00**

Assignee: _gbeutner_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-28 13:27:37 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

**Comment by dnsmichi** [comment]
Imho it doesn't really matter, and does not solve the underlaying problem (which is generally speaking the database layout).
