### ISSUE TITLE
[dev.icinga.com #12420] Icinga fails with obscure "Function call failed" error message when first perfdata file rotation fails

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4474]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12420

**Created by gbeutner on 2016-08-13 22:30:48 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-28 13:37:12 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

    [2016-08-14 00:27:00 +0200] critical/ConfigItem: Error: Function call failed

    [2016-08-14 00:27:00 +0200] critical/ConfigItem: 1 error
    [2016-08-14 00:27:00 +0200] critical/cli: Error activating configuration.

**Comment by dnsmichi** [comment]
Logging has been improved, I doubt this exists any longer.
