### ISSUE TITLE
[dev.icinga.com #12427] Add more CheckCommand definitions

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4480]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12427

**Created by mfriedrich on 2016-08-14 16:13:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-14 16:13:46 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

http://www.dokuwiki.tachtler.net/doku.php?id=tachtler:icinga2\_-\_plugins

**Comment by dnsmichi** [comment]
If anyone takes onto porting the patches, PRs are welcome. But I won't do it.
