### ISSUE TITLE
[dev.icinga.com #12429] Move command_endpoint-specific check functionality into a separate method

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4482]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12429

**Created by gbeutner on 2016-08-14 17:33:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-14 17:33:46 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

This would allow us to remove the resolvedMacros and useResolvedMacros arguments from the execute method - which in turn would make the execute method more user-friendly.

**Comment by Crunsher** [comment]
Closing this as outdated.
