### ISSUE TITLE
[dev.icinga.com #12480] Restrict User from listing certain object parameters from API query

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4515]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12480

**Created by darmagan on 2016-08-18 13:07:34 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-18 14:42:05 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

It would be a nice feature, if specific lines/vars could be filtered from the API query of certain users.

regards

**Comment by dnsmichi** [comment]
We decided against the example above, and as such, the Icinga 2 API serves as programmatic API. There shouldn't be fine granular restriction filters which would generally slow down any request. This enforces the user to write an application which only fetches the data it needs (if the user requires that).
