### ISSUE TITLE
[dev.icinga.com #12496] Remove static_casts in VariableExpression::DoEvaluate/VariableExpression::GetReference

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4527]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12496

**Created by gbeutner on 2016-08-21 06:08:14 +00:00**

Assignee: _gbeutner_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-08-21 06:08:21 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

**Comment by dnsmichi** [comment]
Not relevant anymore.
