### ISSUE TITLE
[dev.icinga.com #12501] ScheduledDowntime sometimes stops being "rescheduled"

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4531]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12501

**Created by mnardin on 2016-08-22 09:39:34 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-18 14:10:05 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,
I have defined the following ScheduledDowntime-object:

    [root@icingam01-p ~]# cat /etc/icingaweb2/modules/fileshipper/icinga-config/objects-ris-global/downtimes/lbsignatur.conf
    apply ScheduledDowntime "lbsignatur-http-downtime" to Service {
      author = "icinga-config"
      comment = "reccuring scheduled downtime"

      ranges = {
        monday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
        tuesday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
        wednesday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
        thursday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
        friday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
      }

      assign where host.name == "lbsignatur.localdomain" && service.name == "http-status"
    }
    [root@icingam01-p ~]# icinga2 object list --name 'lbsignatur.localdomain!http-status!*' --type ScheduledDowntime
    Object 'lbsignatur.localdomain!http-status!lbsignatur-http-downtime' of type 'ScheduledDowntime':
      % declared in '/var/lib/icinga2/api/packages/director/icingam01-p-1471851653-0/zones.d/ris-global/custom-objects/downtimes/lbsignatur.conf', lines 1:0-1:60
      * __name = "lbsignatur.localdomain!http-status!lbsignatur-http-downtime"
      * author = "icinga-config"
        % = modified in '/var/lib/icinga2/api/packages/director/icingam01-p-1471851653-0/zones.d/ris-global/custom-objects/downtimes/lbsignatur.conf', lines 2:3-2:26
      * comment = "reccuring scheduled downtime"
        % = modified in '/var/lib/icinga2/api/packages/director/icingam01-p-1471851653-0/zones.d/ris-global/custom-objects/downtimes/lbsignatur.conf', lines 3:3-3:42
      * duration = 0
      * fixed = true
      * host_name = "lbsignatur.localdomain"
        % = modified in '/var/lib/icinga2/api/packages/director/icingam01-p-1471851653-0/zones.d/ris-global/custom-objects/downtimes/lbsignatur.conf', lines 1:0-1:60
      * name = "lbsignatur-http-downtime"
      * package = "director"
        % = modified in '/var/lib/icinga2/api/packages/director/icingam01-p-1471851653-0/zones.d/ris-global/custom-objects/downtimes/lbsignatur.conf', lines 1:0-1:60
      * ranges
        % = modified in '/var/lib/icinga2/api/packages/director/icingam01-p-1471851653-0/zones.d/ris-global/custom-objects/downtimes/lbsignatur.conf', lines 5:3-11:3
        * friday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
        * monday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
        * thursday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
        * tuesday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
        * wednesday = "08:45-09:02,09:45-10:02,10:45-11:02,11:45-12:02,12:45-13:02,13:45-14:02,14:45-15:02,15:45-16:02,16:45-17:02"
      * service_name = "http-status"
        % = modified in '/var/lib/icinga2/api/packages/director/icingam01-p-1471851653-0/zones.d/ris-global/custom-objects/downtimes/lbsignatur.conf', lines 1:0-1:60
      * templates = [ "lbsignatur-http-downtime" ]
        % = modified in '/var/lib/icinga2/api/packages/director/icingam01-p-1471851653-0/zones.d/ris-global/custom-objects/downtimes/lbsignatur.conf', lines 1:0-1:60
      * type = "ScheduledDowntime"
      * vars = null
      * zone = "RZ"
        % = modified in '/var/lib/icinga2/api/packages/director/icingam01-p-1471851653-0/zones.d/ris-global/custom-objects/downtimes/lbsignatur.conf', lines 1:0-1:60

The current Downtime-object looks like this:

    [root@icingam01-p ~]# icinga2 object list --name 'lbsignatur.localdomain!http-status!*' --type Downtime
    Object 'lbsignatur.localdomain!http-status!icingam01-p-1471848340-366' of type 'Downtime':
      % declared in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 1:0-1:59
      * __name = "lbsignatur.localdomain!http-status!icingam01-p-1471848340-366"
      * author = "icinga-config"
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 2:2-2:25
      * comment = "reccuring scheduled downtime"
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 3:2-3:41
      * config_owner = "lbsignatur.localdomain!http-status!lbsignatur-http-downtime"
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 4:2-4:77
      * duration = 0
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 5:2-5:20
      * end_time = 1471852920
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 6:2-6:29
      * fixed = true
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 7:2-7:13
      * host_name = "lbsignatur.localdomain"
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 8:2-8:37
      * name = "icingam01-p-1471848340-366"
      * package = "_api"
      * scheduled_by = "lbsignatur.localdomain!http-status!lbsignatur-http-downtime"
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 9:2-9:77
      * service_name = "http-status"
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 10:2-10:29
      * start_time = 1471851900
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 11:2-11:31
      * templates = [ "icingam01-p-1471848340-366" ]
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 1:0-1:59
      * triggered_by = ""
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 12:2-12:18
      * type = "Downtime"
      * zone = "RZ"
        % = modified in '/var/lib/icinga2/api/packages/_api/icingam01-p-1453216567-1/conf.d/downtimes/lbsignatur.localdomain!http-status!icingam01-p-1471848340-366.conf', lines 14:2-14:12

It seems that the re-scheduling sometimes doesn't happen anymore. Even a restart of the icinga2-service fixes the problem.

Strangely enough there seems to be a downtime scheduled for tomorrow:

    "scheduleddowntime_id","instance_id","downtime_type","object_id","entry_time","author_name","comment_data","internal_downtime_id","triggered_by_id","is_fixed","duration","scheduled_start_time","scheduled_end_time","was_started","actual_start_time","actual_start_time_usec","is_in_effect","trigger_time","name","endpoint_object_id"
    "354111","1","1","14594","2016-08-22 09:45:00","icinga-config","reccuring scheduled downtime","252","0","1","0","2016-08-23 08:45:00","2016-08-23 09:02:00","0","0000-00-00 00:00:00","0","0","0000-00-00 00:00:00","lbsignatur.localdomain!http-status!icingam01-p-1471851900-0","5"

Best regards
Mirko

**Comment by Al2Klimov** [comment]
Hello @mnardin,

did you create the issue? (Unfortunately we can only guess.)

If yes, is this problem still present in v2.10.2?

Best,
AK
