### ISSUE TITLE
[dev.icinga.com #12504] Icinga 2 "hangs" if the GelfWriter cannot send messages

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4532]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12504

**Created by bjoern812 on 2016-08-22 13:31:05 +00:00**

Assignee: _mariussturm_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-08-24 10:26:49 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

If the feature GelfWriter is enabled and the writer cannot deliver messages (in my case, the harddrive of the graylog server was full),
it seems that icinga2 does not execute checks anymore. Icingaweb2 says after few minutes that the backend is not running.

The debuglog prints messages that a pool is full:
\[2016-08-22 09:55:25 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.429644%
\[2016-08-22 09:55:40 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.190732%
\[2016-08-22 09:55:55 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 1ms; Threads: 4; Pool utilization: 0.224008%
\[2016-08-22 09:56:10 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.119098%
\[2016-08-22 09:56:25 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.105793%
\[2016-08-22 09:56:40 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.125531%
\[2016-08-22 09:56:55 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 26; Average latency: 334ms; Threads: 4; Pool utilization: 11.4048%
\[2016-08-22 09:57:10 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.769205%
\[2016-08-22 09:57:25 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.212043%
\[2016-08-22 09:57:40 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.133359%
\[2016-08-22 09:57:55 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.268299%
\[2016-08-22 09:58:10 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.169474%
\[2016-08-22 09:58:25 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.157764%
\[2016-08-22 09:58:40 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.109028%
\[2016-08-22 09:58:55 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.208077%
\[2016-08-22 09:59:10 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.152603%
\[2016-08-22 09:59:25 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.209654%
\[2016-08-22 09:59:40 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.19039%
\[2016-08-22 09:59:55 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.131424%
\[2016-08-22 10:00:10 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.139583%
\[2016-08-22 10:00:25 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.319848%
\[2016-08-22 10:00:40 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.179756%
\[2016-08-22 10:00:55 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.150974%
\[2016-08-22 10:01:10 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.147511%
\[2016-08-22 10:01:25 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 9; Average latency: 0ms; Threads: 4; Pool utilization: 8.64095%
\[2016-08-22 10:01:40 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 18; Average latency: 0ms; Threads: 15; Pool utilization: 66.6248%
\[2016-08-22 10:01:55 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 7; Average latency: 2ms; Threads: 45; Pool utilization: 72.1214%
\[2016-08-22 10:02:10 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 19; Average latency: 0ms; Threads: 57; Pool utilization: 84.5766%
\[2016-08-22 10:02:25 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 44; Average latency: 0ms; Threads: 58; Pool utilization: 91.1936%
\[2016-08-22 10:02:40 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 73; Average latency: 0ms; Threads: 61; Pool utilization: 93.2089%
\[2016-08-22 10:02:55 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 96; Average latency: 0ms; Threads: 64; Pool utilization: 94.3776%
\[2016-08-22 10:03:10 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 109; Average latency: 0ms; Threads: 64; Pool utilization: 96.2982%
\[2016-08-22 10:03:25 +0200\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pending tasks: 143; Average latency: 0ms; Threads: 64; Pool utilization: 98.2954%

Look also here (german): https://monitoring-portal.org/index.php?thread/37157-icinga2-2-4-10-h%C3%A4ngt-sich-auf-ursache-gelf-feature/&postID=234854#post234854

Thanks

**Comment by dnsmichi** [comment]
@mariussturm ping? :)

**Comment by dnsmichi** [comment]
Same as #5132 and #5232

**Comment by dnsmichi** [comment]
Should get the same WQ as for #5219 and #5132.

**Comment by dnsmichi** [comment]
Note: The GelfWriter feature does not have a StatsFunction(), will be added too.

**Comment by dnsmichi** [comment]
```
mbmif /usr/local/icinga2 (master *) # icinga2 daemon -x debug | grep Gelf
[2017-06-06 19:18:45 +0200] information/ConfigItem: Instantiated 1 GelfWriter.
[2017-06-06 19:18:45 +0200] debug/ConfigObject: Restoring object 'gelf' of type 'GelfWriter'.
[2017-06-06 19:18:45 +0200] debug/ConfigItem: Setting 'active' to true for object 'gelf' of type 'GelfWriter'
[2017-06-06 19:18:45 +0200] debug/ConfigItem: Activating object 'gelf' of type 'GelfWriter'
[2017-06-06 19:18:45 +0200] information/GelfWriter: 'gelf' started.
[2017-06-06 19:18:45 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'GelfWriter, gelf'
[2017-06-06 19:18:45 +0200] notice/GelfWriter: Reconnecting to Graylog Gelf on host '127.0.0.1' port '12201'.
[2017-06-06 19:18:45 +0200] information/GelfWriter: Finished reconnecting to Graylog Gelf in 0.000432014 second(s).
[2017-06-06 19:18:49 +0200] debug/GelfWriter: Processing check result for 'many-test-1!icinga'
```

**Comment by dnsmichi** [comment]
<img width="523" alt="screen shot 2017-06-06 at 19 23 02" src="https://user-images.githubusercontent.com/382049/26842582-9b836488-4aed-11e7-835e-17c3fbec0749.png">
