### ISSUE TITLE
[dev.icinga.com #12512] Zone checks stay in PENDING state

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4539]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12512

**Created by jhon287 on 2016-08-23 08:01:36 +00:00**

Assignee: _jhon287_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-11-11 14:34:35 +00:00 (in Redmine)_

    Icinga Version: 2.5.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

I have some check zones that stays in PENDING state.
And seems to be executed only when I restart the icinga2 process and never after again.
Do you have any idea why I have this strange behaviour ?

Thank you in advance.
Best regards.

\[root@icinga-a icinga2\]\# icinga2 -V
icinga2 - The Icinga 2 network monitoring daemon (version: v2.5.0)

Copyright © 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later &lt;http://gnu.org/licenses/gpl2.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
Installation root: /usr
Sysconf directory: /etc
Run directory: /run
Local state directory: /var
Package data directory: /usr/share/icinga2
State path: /var/lib/icinga2/icinga2.state
Modified attributes path: /var/lib/icinga2/modified-attributes.conf
Objects path: /var/cache/icinga2/icinga2.debug
Vars path: /var/cache/icinga2/icinga2.vars
PID path: /run/icinga2/icinga2.pid

System information:
Platform: CentOS Linux
Platform version: 7 (Core)
Kernel: Linux
Kernel version: 3.10.0-327.28.2.el7.x86\_64
Architecture: x86\_64

Build information:
Compiler: GNU 4.8.5
Build host: unknown

**Comment by dnsmichi** [comment]
Any updates?

**Comment by dnsmichi** [comment]
If there's further feedback we might reopen the issue.
