### ISSUE TITLE
[dev.icinga.com #12531] Updating Icinga 2 overwrites configuration files

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4552]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12531

**Created by Emanuel on 2016-08-24 13:36:32 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-24 13:36:32 +00:00 (in Redmine)_

    Icinga Version: 2.5.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

I did an update of icinga2 from 2.4.10 to 2.5.1.
Afterwards the configuration from /etc/icinga2/icinga2.conf was overwritten with the default of 2.5.1 and no backup file availeble.
Is this a known behavour?

Thanks

**Comment by dnsmichi** [comment]
Haven't seen this, and we did not reproduce it back then either. I guess this was just a purge and install instead of an update.
