### ISSUE TITLE
[dev.icinga.com #12532] Make it possible to use templates of the parent Zone

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4553]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12532

**Created by dupondje on 2016-08-24 14:43:55 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2016-08-31 14:26:32 +00:00_)
Target Version: _(none)_
Last Update: _2016-08-31 14:59:32 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

Today I wanted to add a satellite system in my environment.
This because I wanted to monitor multiple servers in our office, but those servers don't have a public IP and are only reachable from the satellite system.

Now I created the following Zones:
1) 'global-templates' Zone that is global=true
2) 'Infrastructure' Zone with parent 'global-templates'
3) 'Office' Zone with parent 'Infrastructure'

The global-templates zone only contains a few CheckCommands that can safely be synced to all icinga2 agents. This as we don't want our HostTemplates synced to all customer servers that run icinga2.
Then we have the Infrastructure Zone that contains almost everything, specific CheckCommands, HostTemplates etc.

I added a 'Office' zone, that used a server as Satellite. This server has then access to all other servers in the 'Office' Zone.

Now I added a server (lets say 'office-server001' to the Office zone).
For the configuration I used the template 'linux-host' which resides in the 'Infrastructure' Zone.

But there we hit the problem. The Office Zone doesn't know any template from its parent zone. Only the global-templates.
And as we don't want all our templates synced, the only solution at this moment seems to be to copy the templates to the Office zone AND rename them, cause template names need to be globally unique over all templates.

Also the apply rules from the Infrastructure Zone seems to be applied to the hosts in the Office Zone?

**Comment by dnsmichi** [comment]
My conclusion is that this won't happen from our side.
