### ISSUE TITLE
[dev.icinga.com #12539] Thoughts about a new diagnostic tool

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4560]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12539

**Created by sru on 2016-08-25 05:43:21 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-04 13:02:07 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

**current situation:**

*icinga2 object list*
+ easy to use
+ can be filtered with textutils
+ can be piped into a file that can be mailed to support / forum
+ shows in which file an object has been declared / modified
- incomplete regarding api created objects

*api query via curl*
+ is considered to show complete config object information
+ can be filtered with textutils
+ can be piped into a file that can be mailed to support / forum
- hard to use
- does not show in which file an object has been declared / modified
? does not show the content of templates (but doc states it is possible)

*icinga studio as a frontend to api query*
+ is considered to show complete config object information
+ easy to use
- can not be filtered with textutils
- can not be piped into a file that can be mailed to support / forum
- does not show in which file an object has been declared / modified
- does not show the content of templates

**verdict:**

* currently, we have no single tool to gather diagnostic information

* icinga2 object list does not inform the user that its information is valid but may be incomplete.
* api query from the commandline is too complex to be used occasionally and misses templates ? and physical locations

**additional features:**

* Benchmark function to answer the question: "how much checks per minute is my box able to handle ?"
that being done for the following scenarios:

* Master with ido feature but not checking itself (perhaps with a switch to enable multible masters)

* Satellite standalone running synthetic checks - the later configureable to produce a delay in ms and / or a load per core in %cpu.
* Two satellites in a load sharing scenario, two see the impact of different hardware / decreasing system resources (cpu, ram, nic)
* list "status" api call output and system hardware

---

**Relations**:

* relates [#12566](https://dev.icinga.com/issues/12566)

**Comment by dnsmichi** [comment]
I'll hand that to @lippserd for further planning on such a tool.

**Comment by gunnarbeutner** [comment]
There are no plans to support this.
