### ISSUE TITLE
[dev.icinga.com #12548] IDO: entry_time of all comments is set to the date and time when Icinga 2 was restarted (Regression)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4565]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12548

**Created by elippmann on 2016-08-25 13:18:42 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2016-08-25 15:03:45 +00:00_)
Target Version: _(none)_
Last Update: _2016-11-18 14:11:48 +00:00 (in Redmine)_

    Icinga Version: 2.5.3
    Backport?: Not yet backported
    Include in Changelog: 1

---

This should've been fixed w/ 2.5.0. Unfortunately this is not the case.

The entry\_time of all comments is set to the date and time when Icinga 2 was restarted. This affects acks, comments and downtimes.

**Steps to reproduce:**

-   Add a comment
-   Wait some seconds
-   Restart Icinga 2
-   Notice that the entry\_time of all comments has been reset

---

**Relations**:

* copied_to [#12548](https://dev.icinga.com/issues/12548)

**Comment by sbancal** [comment]
:+1:

**Comment by dnsmichi** [comment]
I haven't seen this for a year now and consider this resolved.
