### ISSUE TITLE
[dev.icinga.com #12581] Improve cmake support for MySQL/PostgreSQL when using MacPorts

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4592]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12581

**Created by gbeutner on 2016-08-29 08:47:13 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-29 08:47:13 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

**Comment by Crunsher** [comment]
Since you two use macports, did you run into this issue recently? @gunnarbeutner @N-o-X

**Comment by gunnarbeutner** [comment]
This was already fixed by #5934.
