### ISSUE TITLE
[dev.icinga.com #12584] Add notification scheduler (similar to check scheduler)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4594]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12584

**Created by mfriedrich on 2016-08-29 13:13:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-29 13:13:42 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Instead of the current timer implementation.

**Comment by Crunsher** [comment]
The issue #6221 has a few more details on why this is a valid feature request.

**Comment by N-o-X** [comment]
This is not something we will implement in the near feature. We'll keep this in mind for when we start work on the Notification Manager (NoMa 2).
