### ISSUE TITLE
[dev.icinga.com #12593] Log meaningful error when ca is not readable

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4600]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12593

**Created by elippmann on 2016-08-30 12:39:08 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-30 12:39:08 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

In case Icinga 2 can't read its ca, nodes/agents fail to request the certificate from the master on setup. Unfortunately the master only logs "Error while processing message for identity...".

**Comment by dnsmichi** [comment]
That has been fixed for a while now, I cannot remember which commit did it.
