### ISSUE TITLE
[dev.icinga.com #12629] Downtime delete after reload or reload icinga2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4614]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12629

**Created by dreierg on 2016-09-02 10:47:59 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-02 10:47:59 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

when i set the downtime and reload/restart the icinga 2 then the downtime ist deleted.
I have version Icinga Classic UI 1.13.3 (Backend v2.5.4)

**Comment by dnsmichi** [comment]
Guess that's the same issue as #3668. I believe the downtime is still there, but something weird happens. Please check the workaround mentioned in that issue.
