### ISSUE TITLE
[dev.icinga.com #12615] Segfault error

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4617]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12615

**Created by azhaguprabu on 2016-09-01 11:33:59 +00:00**

Assignee: _azhaguprabu_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-07 21:45:02 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

When i start the icinga2 service getting the segfault on /var/log/message

Aug 31 17:04:21 icingam-tdphob-02o kernel: icinga2\[29180\]: segfault at 28 ip 00002afe24ccbe42 sp 00002afed01fec20 error 4 in libbase.so\[2afe24b7e000+1df000\]

**Attachments**

* [icinga_debug.txt](https://dev.icinga.com/attachments/download/3620/icinga_debug.txt) azhaguprabu - _2016-09-06 10:51:31 +00:00_

**Comment by dnsmichi** [comment]
I think this one has been addressed with v2.6.0.
