### ISSUE TITLE
[dev.icinga.com #12624] Satellite sends config updates to master on reload/restart

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4623]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12624

**Created by hvhaugwitz on 2016-09-02 07:06:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-02 07:06:46 +00:00 (in Redmine)_

    Icinga Version: 2.5.3
    Backport?: Not yet backported
    Include in Changelog: 1

---

On reloads/restarts of a satellite the master logs the following warnings for some hosts:

    warning/ApiListener: Ignoring config update for object '...' of type 'Host'. 'api' does not accept config.

**Comment by dnsmichi** [comment]
Presumingly the same as discussed in #4969.
