### ISSUE TITLE
[dev.icinga.com #12647] OpenSSL: RSA_generate_key is deprecated

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4635]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12647

**Created by mfrosch on 2016-09-05 11:12:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-05 11:12:18 +00:00 (in Redmine)_

    Icinga Version: 2.5.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Please replace.

    /home/markus/devel/icinga/icinga2/lib/base/tlsutility.cpp: In function ‘int icinga::MakeX509CSR(const icinga::String&, const icinga::String&, const icinga::String&, const icinga::String&, bool)’:
    /home/markus/devel/icinga/icinga2/lib/base/tlsutility.cpp:327:13: warning: ‘RSA* RSA_generate_key(int, long unsigned int, void (*)(int, int, void*), void*)’ is deprecated [-Wdeprecated-declarations]
      RSA *rsa = RSA_generate_key(4096, RSA_F4, NULL, NULL);
                 ^~~~~~~~~~~~~~~~
    In file included from /usr/include/openssl/x509.h:31:0,
                     from /usr/include/openssl/ssl.h:50,
                     from /home/markus/devel/icinga/icinga2/lib/base/tlsutility.hpp:26,
                     from /home/markus/devel/icinga/icinga2/lib/base/tlsstream.hpp:27,
                     from /home/markus/devel/icinga/icinga2/lib/base/tlsstream.cpp:20,
                     from /home/markus/devel/icinga/icinga2/build/lib/base/base_unity.cpp:60:
    /usr/include/openssl/rsa.h:193:6: note: declared here
     DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
          ^~~~~~~~~~~~~~~~

**Comment by Crunsher** [comment]
Closed by #5555
