### ISSUE TITLE
[dev.icinga.com #12649] Allow increasing resource limits

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4637]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12649

**Created by jonan on 2016-09-06 04:17:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-18 14:01:15 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

My environment is hitting the file descriptor resource limit. This appears to be hard coded in Application::SetResourceLimits() . Please provide a method to increase this beyond 16384.

The problem manifests as failed API connections or checks failing with: "Error: Function call 'pipe2' failed with error code 24, 'Too many open files'"

FYI, I have tried increasing with ulimit as well as recompiling with increased limit for RLIMIT\_NOFILE but the limit never increases beyond 16384. My usage is mostly from the API which receives 10 - 15k connections per minute.

Running Ubuntu 14.04 and Icinga 2.5.3

**Comment by dnsmichi** [comment]
That's already implemented and can be adjusted with environment variables.
