### ISSUE TITLE
[dev.icinga.com #12663] Directory /var/lib/icinga2/api/log is not created if missing

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4640]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12663

**Created by Emanuel on 2016-09-07 09:21:04 +00:00**

Assignee: _jflach_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-07 14:49:19 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,
after an update I discovered that if the directory /var/lib/icinga2/api/log is missing icinga2 only complains in the logfile but continues.
Is this expected?

---

**Relations**:

* relates [#12643](https://dev.icinga.com/issues/12643)

**Comment by Crunsher** [comment]
Closed in favor of #4977
