### ISSUE TITLE
[dev.icinga.com #12666] Node wizard for master setup does create only a zone named like the fqdn

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4643]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12666

**Created by dgoetz on 2016-09-07 12:17:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-07 12:38:38 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

When you run the node wizard to setup a master it creates only a zone ZoneName which is set to the FQDN. This is not good for future expansion and it also does not match the configuration created when running as agent.

**Comment by dnsmichi** [comment]
Closing this in favour of #4966.
