### ISSUE TITLE
[dev.icinga.com #12668] InfluxdbWriter - support for writing performance data unit into InfluxDB

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4645]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12668

**Created by Corbyn on 2016-09-07 12:34:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-12 16:50:21 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

InfluxdbWriter already has the option 'enable\_send\_thresholds' that writes warn/crit and min/max values (if available in the performance data) as field values into InfluxDB.

Same should be possible for units (InfluxDB natively supports strings as data type for fields and tags).
This would allow to build graphs on the data that automatically use and display the correct unit based on the data stored in InfluxDB.

Without this feature the unit always has to be added manually to the graphs.

**Comment by friesoft** [comment]
Here's a list of all units currently supported by Grafana:

https://github.com/grafana/grafana/blob/014f6d5a75757ba69041a086d8e025c05d978777/public/app/core/utils/kbn.ts#L789-L1017

**Comment by lazyfrosch** [comment]
What we can and should do maybe is map the supported Nagios Plugin units to Grafana units, and write them to InfluxDB.

Problem is: that is a Grafana unique feature, so probably we should call the field `grafana_unit`

Grafana than can use that field as unit with an input like `$grafana_unit`

Anyone wanna build a PR for this?

**Comment by dnsmichi** [comment]
That's already merged with #5675.
