### ISSUE TITLE
[dev.icinga.com #12680] Add "stats" metrics from the IcingaApplication itself to metric writers (Graphite, InfluxDB, GELF, etc.)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4652]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12680

**Created by mfriedrich on 2016-09-08 17:47:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-08 17:47:33 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Similar to carbon-cache which provides its own stats by default. This will help us in a similar fashion as we already dump "programstatus" but in historical view without any user interaction.

**Comment by dnsmichi** [comment]
This basically is what the "icinga" check does in #5266 which we will have with 2.7. I'm closing this as duplicate.
