### ISSUE TITLE
[dev.icinga.com #12683] Windows wizard node setup cli call problems

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4655]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12683

**Created by mfriedrich on 2016-09-09 10:56:35 +00:00**

Assignee: _(none)_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-09-09 10:56:35 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

https://monitoring-portal.org/index.php?thread/37306-windows-server-2012r2-agent-critical-cli-too-many-arguments/&postID=235584#post235584

**Comment by dnsmichi** [comment]
Not reproducible anymore with 2.6.x.
