### ISSUE TITLE
[dev.icinga.com #12687] update of icinga_timeperiod_timeranges after config change

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4659]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12687

**Created by mdetrano on 2016-09-09 22:37:15 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-09 22:37:15 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

I've noticed some problems getting the IDO table icinga\_timeperiod\_timeranges to update following changes to the configuration of timeperiods. This table is useful to us for doing some timeperiod-aware reporting from the database.

I could work around the issue a bit if I manually ran:

update icinga\_timeperiods set config\_hash=-1;

against the DB prior to doing a restart.

I suspect the way that hash value is checked on startup is related to the issue.

**Comment by dnsmichi** [comment]
Parent ticket for solving these problems is #6012.
