### ISSUE TITLE
[dev.icinga.com #12690] ITL - check_oracle_health - report option to shorten output

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4661]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12690

**Created by tontonitch on 2016-09-10 14:22:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-10 14:27:17 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,
Addition of the --report option to shorten the plugin output.
Particularly useful for checks producing long outputs, i.e. tablespace-usage
Indeed, default is "long"
Cheers,
Yannick

**Attachments**

* [0001-check_oracle_heath-report-option-to-shorten-output.patch](https://dev.icinga.com/attachments/download/3628/0001-check_oracle_heath-report-option-to-shorten-output.patch) tontonitch - _2016-09-10 14:27:12 +00:00_

**Comment by Tontonitch** [comment]
Any news?

**Comment by Crunsher** [comment]
@Tontonitch Could you resubmit your patch as a pull request referencing this issue?

I'm sorry for the inconvenience but the move to Github we had to change our workflow. Rest assured it won't be forgotten.

**Comment by Tontonitch** [comment]
Pull request finally created

**Comment by dnsmichi** [comment]
Thanks 👍
