### ISSUE TITLE
[dev.icinga.com #12694] Send Recovery notification after downtime expires if problem was notified before downtime started

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4662]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12694

**Created by greatexpectations on 2016-09-12 07:15:49 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-07 17:11:25 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

this is more of a feature request since I don't think this is currently implemented in Icinga2...

Imagine the following situation:

- service X on host Y enters a hard problem state and a notification is sent out
- some time later, the host and all of it's services enter a downtime period
- service X recovers still within the downtime period
- the downtime period ends

What we would like to have from Icinga2 is to get a recovery notification for the recovered service after the downtime period has expired.

This would require Icinga to keep track of sent problem notifications and send out recovery notifications in those cases when the problem notification was sent outside of a downtime period.

This is probably a duplicate of issue [\#6228,](https://dev.icinga.com/issues/6228) but there is not much context provided in that issue so it may not be apparent to viewers what it is all about.

Kind regards

---

**Relations**:

* relates [#12293](https://dev.icinga.com/issues/12293)
* relates [#12529](https://dev.icinga.com/issues/12529)

**Comment by dnsmichi** [comment]
This will be solved with 2.11.
