### ISSUE TITLE
[dev.icinga.com #12825] Set expiry date on comments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4663]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12825

**Created by twidhalm on 2016-09-29 09:04:49 +00:00**

Assignee: _elippmann_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-25 08:54:29 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

A customer of mine uses a sophistaced setup for Issue/Ticket creation via Icinga 2 Notifications: Notifications on some special services do not just send e-mails but another notification runs a script that creates an issue in the internal issue tracker of the customer. This script receives the issue number back from the issue tracker and creates a comment with the number. So Icinga Web 2 shows a list of issues that were created for this service.

While this is a very neat feature, some services create lots of issues and all of the comments have to be deleted manually. So it would be nice to have the option to create comments with an expiry date to have Icinga 2 clean up the comment list.

Cheers,
Thomas

**Comment by widhalmt** [comment]
Just leaving a +1 from a training attendee. :slightly_smiling_face:

**Comment by dnsmichi** [comment]
## Tasks

- [ ] API action attribute & docs
- [ ] Extend the comment timer handler to check this globally, not only for Acknowledgement != None type comments
- [ ] Tests

**Comment by dnsmichi** [comment]
@lippserd I'll show @htriem the insights to make this happen for 2.12.

**Comment by lippserd** [comment]
Sounds good.

**Comment by lippserd** [comment]
@dnsmichi Do we have a related Icinga 2 issue here?

**Comment by lippserd** [comment]
Web 2 Issue: https://github.com/Icinga/icingaweb2/issues/3447
