### ISSUE TITLE
[dev.icinga.com #12740] eventhandler depends on the service/host-status

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4673]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12740

**Created by starflighter on 2016-09-16 21:52:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-16 21:52:56 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,
it would be great if the start of the eventhandlers could be define by the current state of host/service like the notifications.
For example:

service.conf
.....
eventhandler\_state = \[ Critical, Unknown \]
.....

or with an host:

host.conf
.....
eventhandler\_state = \[ Down \]
.....

**Comment by dnsmichi** [comment]
Imho that state handling should be dealt with inside the eventhandler's code itself. That way you're free to ignore UNKNOWN states at one central location for example. I don't think it is worth the hassle of an extra configuration attribute, but please discuss.

**Comment by starflighter** [comment]
Sure, you can do it in the eventhandler. But as I know it its unusal to use it with state OK and UNKNOWN. So this might be a good thing if you could do that with a icinga-template, otherwise you must define this in every eventhander, or? 

And it would be clearer if any icinga-configuration that needs/depends on a state (notifications, dependencies, eventhandler, ..) can be configured on the "same way". (I hope you know what I mean xD).

But one disadvantage I found, with this config you can't use soft states, or?

**Comment by dnsmichi** [comment]
It feels incomplete. As you've said there's no state specific filter then. You would actually need to create sort of an event handler "condition" when a script is being fired. While we could add that somehow to the configuration attributes, I don't think it is the right location inside the core itself. Firing a script and passing required command arguments is very easy, and leaves the decision to the user, external as resource. Similar to how check plugins analyse data based on given parameters, event handlers should be as simple as they are. I like your idea, but I don't think this should be added into the core logic itself.

**Comment by starflighter** [comment]
OK, you`re right. It is a possible scenario to do that in the core, but I think, at the moment it isn`t well thought out. 
So, let everything as it is ;-).

**Comment by dnsmichi** [comment]
Thanks for your feedback, much appreciated :) If we ever come up with our own solution for event handlers, we may consider adding such filter conditions. But I guess that won't happen anytime soon ;)

**Comment by tobiasvdk** [comment]
Actually I find the idea of having a filter for events triggering an event command very useful.
My use case is triggering an "auto-remediation-script" in case of a host down event (where the host alive check is done every 10 seconds for hundreds - or thousands - of hosts). Doing this inside the core is much less cheaper then executing a script every time.
