### ISSUE TITLE
[dev.icinga.com #12742] ITL - Support of complex thresholds for nscp checks

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4675]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12742

**Created by tontonitch on 2016-09-18 13:03:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-18 13:03:14 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

Currenty, the ITL commands for nscp checks don't support complex thresholds.
For exemple, for nscp-local-cpu, if I want to
vars.nscp\_cpu\_arguments += \[
"warn=( load&gt;$nscp\_cpu\_warning$ and time not in ('1m'))",
"crit=( load&gt;$nscp\_cpu\_critical$ and time not in ('1m'))"
\]
it doesn't work because:

* there is a default value for nscp\_cpu\_warning nscp\_cpu\_critical
* --warning and --critical arguments are defined with a "formatted" string "i.e. load&gt;80"

    object CheckCommand "nscp-local-cpu" {
        import  "nscp-local"

        arguments += {
            "--time" = {
                value = "$nscp_cpu_time$"
                repeat_key = true
            }
            "--warning" = {
                value = "load>$nscp_cpu_warning$"
            }
            "--critical" = {
                value = "load>$nscp_cpu_critical$"
            }
            "-a" = {
                value = "$nscp_cpu_arguments$"
                skip_key = true
            }
        }

        vars.nscp_query = "check_cpu"
        vars.nscp_showall = "$nscp_cpu_showall$"

        vars.nscp_cpu_time = [ "1m", "5m", "15m" ]
        vars.nscp_cpu_showall = true
        vars.nscp_cpu_warning = 80
        vars.nscp_cpu_critical = 90
    }

Hereunder a manual check where I specify complex warning and critical thresholds:

    C:\Program Files\NSClient++>"C:\Program Files\NSClient++\nscp.exe" client --load-all --log critical --show-all --time 1m --time 5m --time 15m -b -q check_cpu --warning "( load>0 and time not in ('1m'))" --critical "( load>2 and time not in ('1m'))"
    OK: 1m: 1%, 5m: 0%, 15m: 0%|'total 1m'=1%;0;2 'total 5m'=0%;0;2 'total 15m'=0%;0;2

    C:\Program Files\NSClient++>

I would be great to have the ability to specify complex thresholds, via an adaptation of the current ITL commands definition, or by new ones. That would be easy, what would be the best and maintained solution?

Regards,
Yannick

**Comment by Crunsher** [comment]
Closing this as we are going a new way by running checks through the API
