### ISSUE TITLE
[dev.icinga.com #12746] Notifications are send out too late if service outage happens out of notification period

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4676]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12746

**Created by pstiffel on 2016-09-19 11:48:19 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-11 13:36:48 +00:00 (in Redmine)_

    Icinga Version: 2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

System: icinga2 - The Icinga 2 network monitoring daemon (version: r2.5.4-1), ha-cluster with 2 nodes

We have several checks which are checked 24x7, but should notify only during work-hours (9-17).
Now, e.g. if a service outage happens at 8:50, the notification should occur at 9 or close to that. BUT the notifications get send a lot later (sometimes an hour later or so)(couldn't find a pattern here).

We created the following testcase:

A service is checking 24x7 but notifying only from 10-13 with an interval of 1800 seconds.

    Object 'icinga2a.localtest!local-files-testfile.txt!mail-service-notification' of type 'Notification':
      % declared in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 44:1-44:57
      * __name = "icinga2a.localtest!local-files-testfile.txt!mail-service-notification"
      * command = "mail-service-notification"
        % = modified in '/etc/icinga2/zones.d/config-ha-master/templates.conf', lines 656:2-656:39
      * command_endpoint = ""
      * host_name = "icinga2a.localtest"
        % = modified in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 44:1-44:57
      * interval = 1800
        % = modified in '/etc/icinga2/zones.d/config-ha-master/templates.conf', lines 631:2-631:14
        % = modified in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 71:3-71:47
      * name = "mail-service-notification"
      * package = "_etc"
        % = modified in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 44:1-44:57
      * period = "10to13"
        % = modified in '/etc/icinga2/zones.d/config-ha-master/templates.conf', lines 632:2-632:17
        % = modified in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 53:17-53:58
      * service_name = "local-files-testfile.txt"
        % = modified in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 44:1-44:57
      * states = [ "OK", "Critical" ]
        % = modified in '/etc/icinga2/zones.d/config-ha-master/templates.conf', lines 626:9-626:38
        % = modified in '/etc/icinga2/zones.d/config-ha-master/templates.conf', lines 658:4-658:30
      * templates = [ "mail-service-notification", "mail-service-notification", "generic-notification" ]
        % = modified in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 44:1-44:57
        % = modified in '/etc/icinga2/zones.d/config-ha-master/templates.conf', lines 652:1-652:49
        % = modified in '/etc/icinga2/zones.d/config-ha-master/templates.conf', lines 624:1-624:44
      * times = null
      * type = "Notification"
      * types = [ "Problem", "Acknowledgement", "Recovery", "Custom", "FlappingStart", "FlappingEnd", "DowntimeStart", "DowntimeEnd", "DowntimeRemoved" ]
        % = modified in '/etc/icinga2/zones.d/config-ha-master/templates.conf', lines 627:9-629:73
      * user_groups = [ "" ]
        % = modified in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 89:17-89:73
      * users = [ "xxxxxx", "yyyyyy" ]
        % = modified in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 97:17-97:70
      * vars = null
      * zone = "config-ha-master"
        % = modified in '/etc/icinga2/zones.d/config-ha-master/notifications.conf', lines 44:1-44:57

    Object '10to13' of type 'TimePeriod':
      % declared in '/etc/icinga2/zones.d/config-ha-master/timeperiods.conf', lines 302:1-302:26
      * __name = "10to13"
      * display_name = "10to13"
        % = modified in '/etc/icinga2/zones.d/config-ha-master/timeperiods.conf', lines 305:9-305:31
      * excludes = [ ]
      * includes = [ ]
      * name = "10to13"
      * package = "_etc"
      * prefer_includes = true
      * ranges
        % = modified in '/etc/icinga2/zones.d/config-ha-master/timeperiods.conf', lines 307:9-313:9
        * friday = "10:00-13:00"
        * monday = "10:00-13:00"
        * thursday = "10:00-13:00"
        * tuesday = "10:00-13:00"
        * wednesday = "10:00-13:00"
      * templates = [ "10to13", "legacy-timeperiod" ]
        % = modified in '/etc/icinga2/zones.d/config-ha-master/timeperiods.conf', lines 302:1-302:26
        % = modified in 'icinga-itl.conf', lines 23:2-23:56
      * type = "TimePeriod"
      * update
        % = modified in 'icinga-itl.conf', lines 24:3-24:37
        * type = "Function"
      * vars = null
      * zone = "config-ha-master"

We made the service Critical at 9:55:59 (see Screenshot 1).
The first notification was sent out at 11:23:01 and every 30 minutes since then(which is as expected) (see Screenshot 2)

We can't explain the initial delay before the first notification.

Any ideas?

**Attachments**

* [2016-09-19_13h19_17.png](https://dev.icinga.com/attachments/download/3642/2016-09-19_13h19_17.png) pstiffel - _2016-09-19 11:45:59 +00:00_
* [2016-09-19_13h26_33.png](https://dev.icinga.com/attachments/download/3643/2016-09-19_13h26_33.png) pstiffel - _2016-09-19 11:45:59 +00:00_
* [12746_Screenshot_1.png](https://dev.icinga.com/attachments/download/4021/12746_Screenshot_1.png) pstiffel - _2017-01-11 13:19:53 +00:00_
* [12746_Screenshot_2.png](https://dev.icinga.com/attachments/download/4023/12746_Screenshot_2.png) pstiffel - _2017-01-11 13:19:53 +00:00_
* [12746_Screenshot_3.png](https://dev.icinga.com/attachments/download/4025/12746_Screenshot_3.png) pstiffel - _2017-01-11 13:19:54 +00:00_
* [mail_service_notification_object.txt](https://dev.icinga.com/attachments/download/4027/mail_service_notification_object.txt) pstiffel - _2017-01-11 13:34:39 +00:00_
* [omnitracker_service_notification_object.txt](https://dev.icinga.com/attachments/download/4029/omnitracker_service_notification_object.txt) pstiffel - _2017-01-11 13:34:39 +00:00_
* [sms_service_notification_object.txt](https://dev.icinga.com/attachments/download/4031/sms_service_notification_object.txt) pstiffel - _2017-01-11 13:34:40 +00:00_

**Comment by edpstiffel** [comment]
Just an addendum: the same error occurs with the current 2.6 version.

**Comment by mickenordin** [comment]
We are also seeing this behaviour with the latest release.

**Comment by JamesForman** [comment]
We are experiencing this issue on 2.8.1.

We had a service go critical at midnight. The host/service is set to have emails sent 24x7, however notifications to the on-call person happen in an 0800 to 1730 time period. A notification went out via email at 0811 however the on-call person was not notified until 0824 (another email went out as well).

Unfortunately, this directly impacted a customer. We're working around this by adding an additional 30 minutes to the start of all our business hours time periods, however this isn't exactly ideal.

**Comment by edpstiffel** [comment]
I opened an issue with a better error description here:
https://github.com/Icinga/icinga2/issues/4676
maybe you can take part there.

**Comment by Al2Klimov** [comment]
@edpstiffel @mickenordin @JamesForman What about v2.10.2?

**Comment by mickenordin** [comment]
We are running 

r2.10.3-1 and this is still happening for us, I can see delays between 9 minutes and 57 minutes in our logs.

**Comment by Al2Klimov** [comment]
Would any of you like to test #7816? If yes, please tell your OS.

**Comment by JamesForman** [comment]
Hi @Al2Klimov 

I can test this on Ubuntu the easiest, in particular 18.04 and 20.04.

**Comment by Al2Klimov** [comment]
https://git.icinga.com/packaging/deb-icinga2/-/jobs/50939/artifacts/download

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
