### ISSUE TITLE
[dev.icinga.com #12751] Dummy object not honoring check_interval/retry_interval

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4680]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12751

**Created by barry.quiel on 2016-09-19 17:33:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-19 18:09:48 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

It looks like the scheduling issue for "real" hosts and services was fixed in 11226. Thanks for that!!

We've started using hosts that have the check\_command = dummy for composite/cluster alerting. It appears that the check\_interval and retry\_interval are not being honored for those host objects.

Here is the config for the host object. You may recognize most of it. I stole the idea from the Icinga docs.

    template Host "avvc-vcendpoint-composite" {
       import "avvc-device"
       check_command = "dummy"
       check_interval = 2m
       retry_interval = 2m
       max_check_attempts = 5
       enable_perfdata = false
       enable_flapping = false

       vars.meta["entity"] = name
       vars.meta["key"] = "Icinga.GroupDown"
       vars.meta["amalert"] = "AVVC Mass Endpoints Down"
       vars.level = "P2"

       vars.dummy_state = {{
          var down_count = 0
          var cluster_nodes = macro("$cluster_nodes$")

          for (node in cluster_nodes) {
             if( get_host(node).state > 0 ) {
                down_count += 1;
             }
          }

          if( down_count / len(cluster_nodes) > Number(".2") ) {
             return 2
          } else {
             return 0
          }
       }}

       vars.dummy_text = {{
          var output = "List of Enpoints down for site " + macro("$host.vars.meta.site_code$") + ":\n"
          var cluster_nodes = macro("$cluster_nodes$")

          for (node in cluster_nodes) {
             if(get_host(node).state == 1) {
                   var node_data = get_host(node)
                   output += node_data.display_name + "(" + node_data.address + ")" + " connected to "
                   output += node_data.vars.nexthop + " on interface " + node_data.vars.nexthop_interface + " - "
                   output += node_data.last_check_result.output + "\n"
             }
          }

          return output
       }}
    }

    object Host "bue1-vcendpoints" {
       vars.cluster_nodes = [ "vcendpoint_empanadas.bue1","vcendpoint_astor.bue1","vcendpoint_gardel.bue1","vcendpoint_troilo.bue1","vcendpoint_churros.bue1" ]
       import "avvc-vcendpoint-composite"
       }

I've attached a screen shot from the event log. You can see that within a few seconds it went through all the max\_check\_attempts and got to a hard state.

Running Cent7 with 2.5.4 packages from the Icinga repo. There is a master zone which is basically empty. All of the these objects are defined in a child zone called "avvc"

**Attachments**

* [2016-09-19 10_21_09-Icinga_ frc3-icinga-master01.png](https://dev.icinga.com/attachments/download/3646/2016-09-19%2010_21_09-Icinga_%20frc3-icinga-master01.png) barry.quiel - _2016-09-19 17:21:49 +00:00_

**Comment by dnsmichi** [comment]
I could imagine the following: either more than 2 endpoints in a zone and too many check results, or the final host object really has those low intervals specified. Verification with "object list" would be good. Please also upgrade to 2.6.3 and test the scenario again.

**Comment by dnsmichi** [comment]
Closing as there was no feedback.
