### ISSUE TITLE
[dev.icinga.com #12756] Stopping Icinga2 client freezes the server

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4682]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12756

**Created by ajoaugustine on 2016-09-21 04:17:38 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-21 04:18:20 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Icinga2 2.5.4-1 has crashed on around 8 production machines with Ubuntu 14.04 while issuing a restart. The command issued was 'service icinga2 restart'. The kernel versions are:

3.13.0-85-generic
3.16.0-30-generic
3.13.0-79-generic

The machines are vmware virtual machines and there is no trace in any of syslog/kern.log for the time. here is the last few lines from the icinga log:

\[2016-09-15 11:10:35 +0000\] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
\[2016-09-15 11:15:35 +0000\] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
\[2016-09-15 11:16:09 +0000\] information/Application: Received request to shut down.
\[2016-09-15 11:16:09 +0000\] information/Application: Shutting down...
\[2016-09-15 11:16:09 +0000\] information/CheckerComponent: Checker stopped.

After this the server become un-responsive and needed a reboot. All the server cpu's show 100% cpu usage during the restart time.

The command 'pkill -9 icinga2' also has brought down a few servers. The command makes the server hung and vcentre performance monitor shows an instant cpu spike of 100% at this time in all the affected servers.

**Comment by dnsmichi** [comment]
We haven't observed this with 2.6, so please upgrade your environment.
