### ISSUE TITLE
[dev.icinga.com #12763] Consider switching from OpenSSL to mbedTLS (formerly PolarSSL)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4685]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12763

**Created by davekempe on 2016-09-22 06:05:28 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-22 06:05:28 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

While I was checking out the way Icinga2 does API communication, I learned that it uses the libssl library of each distribution. This is fine and probably important for compatibility.

However, I wanted to get you guys to consider switching to mbedTLS, formally PolarSSL, which has been audited and is a much smaller replacement for OpenSSL. More background can be read about here:
https://openvpn.fox-it.com/about.html

To get to the point that we are happy to expose Icinga2 API connections over the internet, we need to be able to have the best security possible.

Please consider switching to polarssl so we have another point which we can make during a potential security audit.

https://tls.mbed.org/

Probably not a huge amount of work, for a useful increase in potential security, given that openssl bugs seem to be more common.

**Comment by dnsmichi** [comment]
Discussed that - given that the majority of platforms we support do endorse openssl as primary lib, we'll stick with it for the time being. There's no plans to ship our own ssl package as dependency (that's security hell and not acceptable).
