### ISSUE TITLE
[dev.icinga.com #12768] UNKNOWN notifications ignore retry_interval and max_check_attempts

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4688]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12768

**Created by elasto on 2016-09-22 09:30:57 +00:00**

Assignee: _elasto_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-11-18 15:35:49 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello.

CentOS 6.8 x86\_64

template Service "generic-service" {
check\_interval = 3m
enable\_flapping = 1
flapping\_threshold = 20
max\_check\_attempts = 5
retry\_interval = 1m
}

From compat log:

1.  checks are performed every second, instead 'retry\_interval'
    \[1474533889\] SERVICE ALERT: cpanel7.test.com;disk /;UNKNOWN;SOFT;1;Remote Icinga instance 'cpanel7.test.com' is not connected to 'mon.test.com'
    \[1474533890\] SERVICE ALERT: cpanel7.test.com;disk /;UNKNOWN;SOFT;2;Remote Icinga instance 'cpanel7.test.com' is not connected to 'mon.test.com'
    \[1474533891\] SERVICE ALERT: cpanel7.test.com;disk /;UNKNOWN;SOFT;3;Remote Icinga instance 'cpanel7.test.com' is not connected to 'mon.test.com'
    \[1474533891\] SERVICE ALERT: cpanel7.test.com;disk /;UNKNOWN;SOFT;4;Remote Icinga instance 'cpanel7.test.com' is not connected to 'mon.test.com'
    \[1474533892\] SERVICE ALERT: cpanel7.test.com;disk /;UNKNOWN;HARD;1;Remote Icinga instance 'cpanel7.test.com' is not connected to 'mon.test.com'
    \[1474533892\] SERVICE NOTIFICATION: user;cpanel7.test.com;disk /;UNKNOWN;mail-service-notification;Remote Icinga instance 'cpanel7.test.com' is not connected to 'mon.test.com';

1.  goes to HARD state, avoiding SOFT
    \[1474533893\] SERVICE ALERT: cpanel14.test.com;eximq;UNKNOWN;HARD;1;Remote Icinga instance 'cpanel14.test.com' is not connected to 'mon.test.com'
    \[1474533893\] SERVICE NOTIFICATION: user;cpanel14.test.com;eximq;UNKNOWN;mail-service-notification;Remote Icinga instance 'cpanel14.test.com' is not connected to 'mon.test.com';

It happens when icinga restarting/reloading on endpoints. Not every time, but quite often.

**Attachments**

* [cpanel7.conf](https://dev.icinga.com/attachments/download/3667/cpanel7.conf) elasto - _2016-09-27 13:01:51 +00:00_ - _cpanel7.conf_

**Comment by dnsmichi** [comment]
The topic is misleading, it should read as:

- service is HARD CRITICAL, sends out notification (user receives email)
- service changes to UNKNOWN, triggers notification which gets filtered away by notification state filters (user does not receive any email)
- services changes to CRITICAL, notifies again (user gets the second CRITICAL email)

That way it looks like intervals are ignored, but actually it is about notification filters suppressing various types.

**Comment by KoffeinKaio** [comment]
Hey, posting here as this issue seems like the one I have.


A server's icinga daemon stopped and the main host set it to unknown and notifies me, all fine.
Except for the fact that every few minutes icinga checks again, sees that the server is not connected and repeats this whole "set to unknown and notify" thing. 
Results in a few hundred mails per hour.
Seems like this is really not a notifcation interval issue rather than a "everytime its a new fresh hard state"

> NOTIFICATION [User Name] Remote Icinga instance 'sub.xxxx.xx' is not connected to 't2.xxxx.xx'
> UNKNOWN      [ 1/5 ] Remote Icinga instance 'sub.xxxx.xx' is not connected to 't2.xxxx.xx'
> NOTIFICATION [User Name] Remote Icinga instance 'sub.xxxx.xx' is not connected to 't2.xxxx.xx'
> UNKNOWN      [ 1/5 ] Remote Icinga instance 'sub.xxxx.xx' is not connected to 't2.xxxx.xx'
> NOTIFICATION [User Name] Remote Icinga instance 'sub.xxxx.xx' is not connected to 't2.xxxx.xx'
> UNKNOWN      [ 1/5 ] Remote Icinga instance 'sub.xxxx.xx' is not connected to 't2.xxxx.xx'
