### ISSUE TITLE
[dev.icinga.com #12799] Log Macro warnings for command arguments?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4690]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12799

**Created by mfrosch on 2016-09-26 11:42:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-26 11:42:41 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

We encountered an interesting problem regarding macro resolving in command arguments.

When a macro for an argument can not be resolved, or macros in the macro, the full argument is dropped. Here is an example with a typo in "notifcation".

The problem is that we can't really log an error about it at the moment, because this would log an error for **every** argument that is not used/present.

Is there a way to properly tell the user the macro is invalid?

    object NotificationCommand "sms-service-notification" {
      import "plugin-notification-command"

      command = [ SysconfDir + "/icinga2/scripts/sendsms.pl" ]

      arguments = {
        //...
        "-m" = {
          value = "$sms_service_message$"
        }
      }

      //...
      vars.sms_service_message = "$notifcation.type$: $host.name$ - $service.name$ is $service.state$: $service.output$"
    }

**Comment by gunnarbeutner** [comment]
I don't think there's anything we can do here.
