### ISSUE TITLE
[dev.icinga.com #12816] Permissions on /var/log/icinga2/compat

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4695]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12816

**Created by pstiffel on 2016-09-28 08:29:01 +00:00**

Assignee: _formorer_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-11-17 10:55:05 +00:00 (in Redmine)_

    Icinga Version: 2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

We're on Debian Jessie with packages from debmon.org.

Since our update to 2.5.4-1, we always get the following error message when trying to browse the alert history or notification history in the Classic-UI:

Log file "/var/log/icinga2/compat/icinga.log" invalid! No timestamp found within first 16 bytes!

It turns out that the permissions on the file /var/log/icinga2/compat/icinga.log are set to

    -rw-rw---- 1 nagios adm 2076882 Sep 27 11:05 icinga.log

So www-data has no permission to access the file. The same problem exists for older files that were moved to /var/log/icinga2/compat/archives.

The quick & dirty fix is to add www-data to the adm-group, but that's surely not the way to go.

**Comment by dnsmichi** [comment]
@lazyfrosch your thoughts on that please? :)

**Comment by lazyfrosch** [comment]
@dnsmichi I think this changed with the internal umask settings a while back, no real logrotate is involved here, since the files are written by Icinga itself...

We should use 0644 permissions for the logs, and control access via the directory permissions...

#3963 ?

**Comment by dnsmichi** [comment]
Hm, ok, so a more general problem with missing directories. Guess that's #4634 then.

**Comment by lazyfrosch** [comment]
Not missing directories, but the wrong umask when creating such log files...

**Comment by dnsmichi** [comment]
#5102

**Comment by dnsmichi** [comment]
Since we've dropped the Classic UI package, I'll also close here as wontfix.
