### ISSUE TITLE
[dev.icinga.com #12818] API configuration loop

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4697]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12818

**Created by azhaguprabu on 2016-09-28 11:14:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-28 11:14:33 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

If configuration master enabled api accept\_config in multiple master zone setup, the zones file get loop, file are get delete, other server may distribute the file and same will update configuration master using api,

is there any option to black the zone file loop, only accept the package api objects like ( object creation by icingaweb2 downtime, ack )

**Comment by dnsmichi** [comment]
That only happens if more than one node holds config files in zones.d/ and that is explicitly explained in the docs.
