### ISSUE TITLE
[dev.icinga.com #12819] Allow setting a zone as command_endpoint esp. for host objects

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4698]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12819

**Created by twidhalm on 2016-09-28 11:55:08 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-28 11:55:08 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

When checking hosts from an upstream zone of masters or satellites setting a command\_endpoint to one of the endpoints in the zone makes the high availability and load balancing almost useless for this usecase. I'd like to see a way to check a service or hostobject from the upstream hosts. I know of the possibility to set the `zone` option but if use the Icinga Agent on the monitored host I can't add the zone option to the host object because this would move all checks for the host to the upstream servers.

Maybe this approach is not implementable or it's too complicated. All I want is to run the `hostalive` command of a host object and some services not on a host with the Icinga agent but on one of the masters or satellites the host depends on. And I want to use the full high-availability and load-balancing features of Icinga 2 when running more than one endpoint in the master or satellite zone.

**Comment by Crunsher** [comment]
Closing this as this is extremely hard to realize and the issue has seen no attention in two years.
