### ISSUE TITLE
[dev.icinga.com #12829] non-UTF-8 characters creates broken JSON

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4703]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12829

**Created by TheSeal on 2016-09-29 14:36:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-29 15:06:24 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

I wrote about this on icinga-users without any response.
Since we still thinks this is a bug this is the bug rapport.

We have a check that returns non-UTF-8 characters in its output.
That seems to be just fine for Icinga since it stores the string as is
in the database. But when to access the data through the API things
break since JSON requires strict UTF-8(or higher…).
This also effects livestatus.

We will in our implementation fix this on the client side, but it would be neat if
Icinga would do the sanitation on the server side as you can't always control
the input.

**Comment by theseal** [comment]
Since I was reminded of this issue, any update?

**Comment by dnsmichi** [comment]
That referenced patch is pretty expensive on its own, I doubt that we should add it this way.

**Comment by Al2Klimov** [comment]
@dnsmichi Why "pretty expensive"?

**Comment by dnsmichi** [comment]
Look where JSON::Encode is called. That's a fundamental function and as such shouldn't be slowed down for the cost of fixing this bug.
