### ISSUE TITLE
[dev.icinga.com #12830] Send recovery notification even if the host or service is handled (and a problem notification was sent before)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4704]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12830

**Created by elippmann on 2016-09-30 08:19:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-30 08:19:01 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

I did not check Icinga 2's behavior here, but I think it's the same as in Icinga 1.x: If a host or service problem becomes handled after a problem notification has been sent and the problem recovers, Icinga won't send a recovery notification. From a notification client point of view, e.g. mail or sms it seems that the information sent from Icinga is incomplete.
I think we should send a recovery notification whenever a problem notification was sent regardless of the host or service being handled.

**Comment by Al2Klimov** [comment]
@lippserd #7270 sends the recovery _after_ the downtime ends. Can we close this one?

**Comment by lippserd** [comment]
> @lippserd #7270 sends the recovery _after_ the downtime ends. Can we close this one?

@Al2Klimov Aren't we still missing acked objects and services where the host is in a non-ok state?

**Comment by Al2Klimov** [comment]
1. No.
2. No as AFAIK we don't even suppress them.

**Comment by Al2Klimov** [comment]
I was wrong with (2), but no, we don't miss them.
