### ISSUE TITLE
[dev.icinga.com #12835] Posting config stage fails on FreeBSD

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4709]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12835

**Created by andrem on 2016-09-30 13:14:54 +00:00**

Assignee: _andrem_
Status: _Feedback_  (closed on _2016-10-13 13:09:55 +00:00_)
Target Version: _(none)_
Last Update: _2016-12-07 20:21:25 +00:00 (in Redmine)_

    Icinga Version: 2.5.4

---

Hi All,

when i deploy a config from Director to my Icinga2, I get this :

/usr/local/www/icingaweb2/modules/director/library/Director/Core/RestApiClient.php:194:string '{[error](500.0,"status":"Stage) creation failed."}' (length=49)

The Versions are : Icinga2 (v.r2.5.4-1) und Icingaweb2 (v.2.3.4) Director 1.1.0 (Git from 30.09.2016) mySQL 56 php56 Nginx FreeBSD 10.3

Icinga2 debug.log show this :

\[2016-09-30 15:11:50 +0200\] information/ApiListener: New client connection from \[::ffff:172.16.1.54\]:17538 (no client certificate)
\[2016-09-30 15:11:50 +0200\] notice/ApiListener: New HTTP client
\[2016-09-30 15:11:50 +0200\] debug/HttpRequest: line: GET /v1/config/packages HTTP/1.1, tokens: 3
\[2016-09-30 15:11:50 +0200\] notice/WorkQueue: Spawning WorkQueue threads for 'HttpServerConnection'
\[2016-09-30 15:11:50 +0200\] information/HttpServerConnection: Request: GET /v1/config/packages (from \[::ffff:172.16.1.54\]:17538, user: root)
\[2016-09-30 15:11:50 +0200\] debug/HttpServerConnection: Http client disconnected
\[2016-09-30 15:11:50 +0200\] notice/WorkQueue: Stopped WorkQueue threads for 'HttpServerConnection'
\[2016-09-30 15:11:51 +0200\] debug/IdoMysqlConnection: Query: COMMIT
\[2016-09-30 15:11:51 +0200\] debug/IdoMysqlConnection: Query: BEGIN
\[2016-09-30 15:11:52 +0200\] debug/IdoMysqlConnection: Query: COMMIT
\[2016-09-30 15:11:52 +0200\] debug/IdoMysqlConnection: Query: BEGIN
\[2016-09-30 15:11:53 +0200\] debug/IdoMysqlConnection: Query: COMMIT
\[2016-09-30 15:11:53 +0200\] debug/IdoMysqlConnection: Query: BEGIN
\[2016-09-30 15:11:54 +0200\] debug/IdoMysqlConnection: Query: COMMIT
\[2016-09-30 15:11:54 +0200\] debug/IdoMysqlConnection: Query: BEGIN
\[2016-09-30 15:11:54 +0200\] information/ApiListener: New client connection from \[::ffff:172.16.1.54\]:10582 (no client certificate)
\[2016-09-30 15:11:54 +0200\] notice/ApiListener: New HTTP client
\[2016-09-30 15:11:54 +0200\] debug/HttpRequest: line: GET /v1/config/packages HTTP/1.1, tokens: 3
\[2016-09-30 15:11:54 +0200\] notice/WorkQueue: Spawning WorkQueue threads for 'HttpServerConnection'
\[2016-09-30 15:11:54 +0200\] information/HttpServerConnection: Request: GET /v1/config/packages (from \[::ffff:172.16.1.54\]:10582, user: root)
\[2016-09-30 15:11:54 +0200\] debug/HttpRequest: line: DELETE /v1/config/stages/director/icinga2-tb.XXX.de-1475240554-51 HTTP/1.1, tokens: 3
\[2016-09-30 15:11:54 +0200\] information/HttpServerConnection: Request: DELETE /v1/config/stages/director/icinga2-tb.XXX.de-1475240554-51 (from \[::ffff:172.16.1.54\]:10582, user: root)
\[2016-09-30 15:11:54 +0200\] debug/HttpRequest: line: GET /v1/config/packages HTTP/1.1, tokens: 3
\[2016-09-30 15:11:54 +0200\] information/HttpServerConnection: Request: GET /v1/config/packages (from \[::ffff:172.16.1.54\]:10582, user: root)
\[2016-09-30 15:11:54 +0200\] debug/HttpRequest: line: POST /v1/config/stages/director HTTP/1.1, tokens: 3
\[2016-09-30 15:11:54 +0200\] information/HttpServerConnection: Request: POST /v1/config/stages/director (from \[::ffff:172.16.1.54\]:10582, user: root)
\[2016-09-30 15:11:54 +0200\] information/ConfigPackageUtility: Updating configuration file: /var/lib/icinga2/api/packages/director/icinga2-tb.XXX.de-1475241114-52/zones.d/director-global/001-director-basics.conf
\[2016-09-30 15:11:54 +0200\] information/ConfigPackageUtility: Updating configuration file: /var/lib/icinga2/api/packages/director/icinga2-tb.XXX.de-1475241114-52/zones.d/director-global/commands.conf
\[2016-09-30 15:11:54 +0200\] information/ConfigPackageUtility: Updating configuration file: /var/lib/icinga2/api/packages/director/icinga2-tb.XXX.de-1475241114-52/zones.d/director-global/host\_templates.conf
\[2016-09-30 15:11:54 +0200\] debug/HttpServerConnection: Http client disconnected
\[2016-09-30 15:11:54 +0200\] notice/WorkQueue: Stopped WorkQueue threads for 'HttpServerConnection'

Logfiles from php-fpm und nginx Show no Errors.

Best Regards.

https://monitoring-portal.org/index.php?thread/37556-icinga2-director-und-freebsd/&s=b8c3e7cf8c686b98975218ae43a1559b34f9ecef

**Attachments**

* [curl.PNG](https://dev.icinga.com/attachments/download/3709/curl.PNG) andrem - _2016-10-18 14:59:01 +00:00_

**Comment by dnsmichi** [comment]
@larsengels please have a look into the Vagrant boxes. You're the FreeBSD pro and might see the difference in minutes.

**Comment by nkfilis** [comment]
I started the Vagrant box, ran 

> curl -k -s -u root:icinga -H 'Accept: application/json' -X POST -d '{ "files": { "conf.d/test.conf": "object Host \"cmdb-host\" { chec_command = \"dummy\" }" } }' 'https://localhost:5665/v1/config/stages/example-cmdb' | python -m json.tool
and get 
`{
    "error": 500.0,
    "status": "Stage creation failed."
}`

**Comment by dnsmichi** [comment]
Strange. Can you modify the request body and add 

```
"verboseErrors": true
```

to get a more verbose error message?

**Comment by nkfilis** [comment]
here you go:
{
    "diagnostic information": "Error: Could not determine executable path.\n\n\n\t(0) 0x80222715c <_ZN6icinga6SocketD2Ev+0xe69c> at /usr/local/lib/icinga2/libbase.so.2.6.1\n\t(1) 0x8021ab24a <_ZN6icinga11Application10GetExePathERKNS_6StringE+0x78a> at /usr/local/lib/icinga2/libbase.so.2.6.1\n\t(2) 0x801b7f3fc <_ZN6icinga20ConfigPackageUtility21AsyncTryActivateStageERKNS_6StringES3_+0xac> at /usr/local/lib/icinga2/libremote.so.2.6.1\n\t(3) 0x801b83872 <_ZN6icinga19ConfigStagesHandler10HandlePostERKN5boost13intrusive_ptrINS_7ApiUserEEERNS_11HttpRequestERNS_12HttpResponseERKNS2_INS_10DictionaryEEE+0x3c2> at /usr/local/lib/icinga2/libremote.so.2.6.1\n\t(4) 0x801b82131 <_ZN6icinga19ConfigStagesHandler13HandleRequestERKN5boost13intrusive_ptrINS_7ApiUserEEERNS_11HttpRequestERNS_12HttpResponseERKNS2_INS_10DictionaryEEE+0x141> at /usr/local/lib/icinga2/libremote.so.2.6.1\n\t(5) 0x801b98245 <_ZN6icinga11HttpHandler14ProcessRequestERKN5boost13intrusive_ptrINS_7ApiUserEEERNS_11HttpRequestERNS_12HttpResponseE+0x775> at /usr/local/lib/icinga2/libremote.so.2.6.1\n\t(6) 0x801b9615c <_ZN6icinga20HttpServerConnection19ProcessMessageAsyncERNS_11HttpRequestE+0xbec> at /usr/local/lib/icinga2/libremote.so.2.6.1\n\t(7) 0x802217d31 <_ZN6icinga9WorkQueue16WorkerThreadProcEv+0x531> at /usr/local/lib/icinga2/libbase.so.2.6.1\n\t(8) 0x80084be94 <_ZN5boost6thread21start_thread_noexceptEv+0x184> at /usr/local/lib/libboost_thread.so.1.63.0\n\t(9) 0x8047d8b95 <pthread_create+0x915> at /lib/libthr.so.3\n\n\n",
    "error": 500.0,
    "status": "Stage creation failed."
}

**Comment by gunnarbeutner** [comment]
That's rather unusual. Can you please show us the output of the following two commands:

    cat /proc/<PID>/environ; echo
    cat /proc/<PID>/cmdline; echo

The error message you're getting implies that Icinga is unable to figure out the path for the "icinga2" executable - which should never happen. :)

**Comment by nkfilis** [comment]
Not finding things isn't very uncommon on FreeBSD, since many Linux-y assumptions regarding paths and PATH environments often fail.

`cat /proc/<PID>/cmdline ; echo`
returns
`/usr/local/lib/icinga2/sbin/icinga2daemon-d-e/var/log/icinga2/error.log-c/usr/local/etc/icinga2/icinga2.conf`

unfortunately, there is no /proc/<PID>/environ, there isn't even procfs if you don't enable it ;)

**Comment by gunnarbeutner** [comment]
Oh, I only just realized you were using FreeBSD (should've read the subject!). What I'd be interested in is the value of the PATH environment variable. Maybe there's another way to figure that out for a currently-running process. :)

**Comment by nkfilis** [comment]
yes, that's procstat -e: 
`  PID COMM             ENVIRONMENT                                          
 1117 icinga2          PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin PWD=/ HOME=/ RC_PID=1064`

so I guess, /usr/local/sbin is missing here, since the icinga2 binary lives there, and tadaah:

`{
    "results": [
        {
            "code": 200.0,
            "package": "example-cmdb",
            "stage": "icinga2-freebsd-1487665472-0",
            "status": "Created stage."
        }
    ]
}
`

**Comment by gunnarbeutner** [comment]
This should now be fixed in the master branch. Thanks for reporting this problem. :)

**Comment by dnsmichi** [comment]
Seems @larsengels pushed a workaround to the FreeBSD package.

https://github.com/bsd-hacker/freebsd-ports/commit/7312bf0264e106bf4834897f7e9812af1bf8240b

**Comment by vercotux** [comment]
I had the same issue when trying to configure Director. Turns out the API user needed an extra permission called `"console"` which I did not see mentioned anywhere in the documentation (might have missed it), but the problem was the import just failed, made a mess in the DB to the point where I had to drop the schema and re-do the process, whilst just showing me this error:

    API request failed: Unhandled exception (RestApiResponse.php:108)

**Comment by FruechteBini** [comment]
@vercotux i am getting the same error message currently. Did you have to remove your database completely? In the activity log I can see all the commands imported & everything imported, but deploying gives me the error (RestApiResponse.php:108). 

API works via curl in command line strangely enough. Tried to add the "console" permission to my api user, did not work unfortunately, here is how it looks currently:

if the permissions are set to: 
`["actions/*", "objects/modify/hosts", "objects/modify/services", "objects/modify/icingaapplication", "console"] `
 I get the error message: 
`"API request failed: Unhandled exception (RestApiResponse.php:108)"`
 when trying to deploy. 

If I set the permissions to :
 `["*", "console"]`
 the error changes to : 
`API request failed: Could not create package 'director'. (RestApiResponse.php:108)`

Would appreciate a hint, thanks!

**Comment by vercotux** [comment]
@FreuchteBini

>Did you have to remove your database completely?
Indeed.

>In the activity log I can see all the commands imported & everything imported, but deploying gives me the error (RestApiResponse.php:108).
I had the same issue. The reason was that everything was actually *not* imported. It looked like the import was successful, but about half of the stuff was missing in the DB.

Try with the following permissions: `[ "status/query", "actions/*", "objects/modify/*", "objects/query/*", "console", "config/query", "config/modify" ]`.

Also make sure your config file & directory permissions are correct.

Hope it helps.

**Comment by FruechteBini** [comment]
Hey @vercotux ! Thanks for the fast answer. I was on holiday, got to try your suggestion yesterday. However, it is still not working unfortunately. 

I set up a new database "director" to use it in icinga2. This is how i imported the resource:
![image](https://user-images.githubusercontent.com/33086953/58860908-80cea000-86ad-11e9-8c42-f180c865c4e6.png)

I then configured the director module:

![image](https://user-images.githubusercontent.com/33086953/58860959-9fcd3200-86ad-11e9-8085-49e05716080e.png)

This is my api-users.conf:

![image](https://user-images.githubusercontent.com/33086953/58861426-a1e3c080-86ae-11e9-9226-94dfc6fcc8f5.png)

Kickstart looks like this:

![image](https://user-images.githubusercontent.com/33086953/58861576-f5eea500-86ae-11e9-8856-199e1cdb238c.png)

--> endpoint name is same as icinga host 
--> the config seems to be valid

this is the error i get:
![image](https://user-images.githubusercontent.com/33086953/58862173-60ecab80-86b0-11e9-95e1-72a4627d0e89.png)

I would be very thankful if anyone has more tips. No idea where to start atm

Thanks & cheers

**Comment by dnsmichi** [comment]
Please move this discussion to https://community.icinga.com 

This issue was closed in 2016, no need to bump it again and again. Thanks.
