### ISSUE TITLE
[dev.icinga.com #12840] Downtimes deleted after restart

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4711]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12840

**Created by wols on 2016-10-02 21:11:30 +00:00**

Assignee: _wols_
Status: _Feedback_  (closed on _2016-08-08 14:23:36 +00:00_)
Target Version: _(none)_
Last Update: _2016-12-07 22:50:09 +00:00 (in Redmine)_

    Icinga Version: 2.5.4-r1
    Backport?: Not yet backported
    Include in Changelog: 1

---

IcingaWeb2 shows all downtimed host as problems after restart.

A query...

    mysql -p icinga2 -B -e "select * from icinga_scheduleddowntime sd join icinga_objects sdo on sd.object_id=sdo.object_id where sd.internal_downtime_id=1;"

...shows all downtimes after icinga2 'stop' - but was empty after icinga2 'start'.

---

**Relations**:

* copied_to [#12840](https://dev.icinga.com/issues/12840)

**Comment by marcofl** [comment]
This usually is related to a damaged _api config package. Can you try remove the /var/lib/icinga2/api/packages/_api directory completely (backup it first), restart icinga2, create new downtime, restart icinga2 -> downtime should still be there.

**Comment by marcofl** [comment]
actually I found out, that downtimes and comments get deleted from the IDO database (which is the source for icingaweb2) on every icinga2 start and then icinga2 immediately recreates them from the _api config package - looks like this is intended behaviour. if the config package or a config inside it is broken, it gets ignored and the downtime / comment is not created again. 

same goes for ACKs. as far as I found out, ACKs are just comments in the database which have a `type`-field set to ACK. if a service gets acked there is a flag "problem_acknowleged" on the servicestatus or hoststatus table entry.  on expire of the ACK, icinga2 ido will reset that flag to 0. 

now if you have a damaged _api package config, the comment does not get recreated (as described above) but the acked flag stays on the hoststatus / servicestatus and you end up with a ACKed service / host in icingaweb2 which does not show the ACK comment, author or expire time anymore. fortunately the ACK is still working and gets expired at the time set during created of the ACK. 

please, can anyone tell me if all this is actually true? as this is not well funded knowledge I got during debugging of some issue.

**Comment by dnsmichi** [comment]
Seems directly related to #3668. Your analysis is correct about that. I'll continue in the linked ticket which should serve as fix issue.

**Comment by mwtzzz** [comment]
FYI I was able to fix this on my 2.5.4 system by following marcofl's suggestion to blow away /var/lib/icinga2/api/packages/_api and restart icinga. This resulted in my missing files (active.conf, etc) being recreated automatically.
