### ISSUE TITLE
[dev.icinga.com #12841] printf-style formatting for String type

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4712]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12841

**Created by nlm on 2016-10-03 15:35:15 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-04 07:01:42 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

It would be nice to have a new String function which would behave like sprintf

Example:

      "Hello, %s".format("World") /* Returns "Hello, World" */
      "host-%s-%02d".format("worker", 2) /* Returns "host-worker-02" */

Rationale: make it easy to generate configuration objects with for loops when string concatenation ("host-" + name + "-02") is not sufficient (ex: zero-padding for Numbers)

**Comment by dnsmichi** [comment]
We can either go for boost::format or if we are into better performance, fmt which also is used in Ceph.

https://www.boost.org/doc/libs/1_66_0/libs/format/doc/format.html 
https://github.com/fmtlib/fmt

@htriem This is one for later this year, learning more about the DSL and functions.

**Comment by dnsmichi** [comment]
boost::format is somehow slow compared to other libraries.

Since C++ 20 incorporates fmt as basis for `std::format`, I'd suggest going there: http://www.zverovich.net/2019/07/23/std-format-cpp20.html

**Comment by htriem** [comment]
This will be implemented with #7395. Therefore I'm closing this ticket.
