### ISSUE TITLE
[dev.icinga.com #12854] Please document Icingaweb2 Installation for distributed monitoring

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4715]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12854

**Created by MarcusCaepio on 2016-10-05 04:53:03 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-10-05 09:00:10 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi All,

as suggested by michi in https://monitoring-portal.org/index.php?thread/37589-ha-cluster-with-icingaweb2-and-performance-graphics/&postID=236741#post236741
I want to create a ticket for the documentation of Icingaweb2 (or another gui) in distributed monitoring setups.
Nice to have would be:
- how and on which server to install Icingaweb2 in several distributed setups (master-master, master with clients and so on)
- how to configure Icingaweb2, especially in master-master HA setup
- how to install and configure performance data solutions like PNP4 Nagios or Grafana

Thanks in advance

**Comment by fireheadman** [comment]
+1 for me...

**Comment by dnsmichi** [comment]
Should be done "howto style", and doesn't fit into Icinga 2's docs itself.
