### ISSUE TITLE
[dev.icinga.com #12866] Strange issue with ApiUser object definition

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4719]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12866

**Created by greatexpectations on 2016-10-06 15:33:00 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2016-10-07 15:58:02 +00:00_)
Target Version: _(none)_
Last Update: _2016-10-07 15:58:02 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Greetings,

I am in the process of evaluating Director on a test Icinga2 instance, and had previously set up the neccessary ApiUser object by manually editing a configuration file /etc/icinga2/conf.d/api-users.conf:

    /**
     * The APIUser objects are used for authentication against the API.
     */
    object ApiUser "director" {
      password = "password"
      permissions = [ "*" ]
    }

Now the same configuration file is being generated with Ansible, and looks like this:

    // Ansible managed: /.../conf.d/api-users.conf modified on 2016-10-06 16:33:59 by ansible on ansible...

    object ApiUser "director" {
        password = "password"
        permissions = [ "*" ]
    }

Unfortunately, now Icinga2 fails to validate the configuration:

    # icinga2 daemon --validate
    information/cli: Icinga application loader (version: v2.5.4)
    information/cli: Loading configuration file(s).
    critical/config: Error: Object 'director' of type 'ApiUser' re-defined: in /etc/icinga2/conf.d/api-users.conf: 3:1-3:25; previous definition: in /etc/icinga2/conf.d/api-users.conf: 3:1-3:25
    Location: in /etc/icinga2/conf.d/api-users.conf: 3:1-3:25

Any idea on what I have to do to get it working again would be much appreciated...

Regards

**Comment by Mayaamir** [comment]
> **Updated by greatexpectations on 2016-10-06 18:12:39 +00:00**
> 
> Never mind, there was a stupid error in our Ansible setup that resulted in the conf.d/api-users.conf file being included twice from icinga2.conf.
> 
> All is good now :-)



> **Updated by greatexpectations on 2016-10-06 18:12:39 +00:00**
> 
> Never mind, there was a stupid error in our Ansible setup that resulted in the conf.d/api-users.conf file being included twice from icinga2.conf.
> 
> All is good now :-)

Hi,
Could you please post the steps with commands, how did you resolve it?

**Comment by N-o-X** [comment]
Hi @Mayaamir,

this issue is closed since 2016 and no one will get notified, because of our migration from Redmine.

If you haven't found a solution yet, create a new topic at https://community.icinga.com/. There you'll find a community that's always willing to help. Creating a topic over there might also help users with similar issues!

Greetings
Noah
