### ISSUE TITLE
[dev.icinga.com #12874] check_nscp

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4721]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12874

**Created by jflach on 2016-10-07 13:25:37 +00:00**

Assignee: _jflach_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-10-10 14:20:03 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

**Changesets**

_2016-10-07 13:29:45 +00:00_ by _jflach_ a8c13c3bfc1a809f34fac06a79ef34a61a5eba4f

    Start working on check_nscp
    
    refs #12874

_2016-10-07 13:49:56 +00:00_ by _jflach_ fc1b645d0f1445af86a4fc0b4ace0e6329ede89c

    Improve HTTP Handler error message
    
    refs #12874

_2016-10-07 14:06:20 +00:00_ by _jflach_ a2fcd55c6e57d0cf5458a8272c9fc2c653450dc9

    Check_nscp v0.1
    
    refs #12874

_2016-10-07 14:25:06 +00:00_ by _jflach_ 486ad6cbec8b4e0c49142c6b52b0472a410da4fc

    Add CheckCommand for check_nscp.exe
    
    Currently Windows only
    
    refs #12874

_2016-10-10 15:35:09 +00:00_ by _jflach_ d18770a78f19a31c625ea928918181d52330188b

    Fix itl entry for check_nscp
    
    refs #12874

_2016-10-11 13:35:22 +00:00_ by _jflach_ da3fb2eb7caaabcaa8c75b9ec909555acfd6006c

    Format changes to check_nscp
    
    refs #12874

_2016-10-11 13:36:39 +00:00_ by _jflach_ cf17ea99e78612f1431a2fe04e21ebaeb3cd64a3

    Add additional error checking to check_nscp
    
    refs #12874

_2016-10-11 14:52:30 +00:00_ by _jflach_ 7b2663b42643f201564b7af2ef16247ca839a330

    Add informational error output
    
    refs #12874

_2016-10-13 16:18:08 +00:00_ by _jflach_ 8c08956cdad048a6df547d271d9e64d9097f69c4

    Update ITL for check_nscp
    
    refs #12874

_2016-10-13 16:19:15 +00:00_ by _jflach_ 39752b7d62c56792d13be9dc09307c443a737003

    Build check_nscp on Linux too
    
    refs #12874

_2016-10-14 11:15:28 +00:00_ by _jflach_ 8eb1983c42ab57bea8259c81e6c11b7fd3703573

    Fix Cmake for check_nscp
    
    refs #12874

_2016-10-14 13:53:29 +00:00_ by _jflach_ a654be0b64d5bea5043686acd209d7f8609c2657

    Add comments and debug mode to check_nscp
    
    refs #12874

_2016-10-14 13:53:29 +00:00_ by _jflach_ 380db55a1bffec9f25dbd499c46b2c11107feb5f

    Fix CMake
    
    refs #12874

_2016-10-14 13:54:34 +00:00_ by _jflach_ 81e7189c09a4489da74701ab8e077fda7b575673

    Fix compiler error
    
    VS allows void main
    
    refs #12874

_2016-10-27 11:53:27 +00:00_ by _jflach_ f89e4a2b677e92f6b2dd8d7950c538d9ce603cad

    Remove check_nscp from command-plugins
    
    Otherwise it breaks the windows default conf and since we probably won't
    have check_nscp on Linux it's better to remove it for now
    
    refs #12874

_2016-12-08 11:24:40 +00:00_ by _jflach_ 21737a78dede538a26d78d4a267c60b2faa949ff

    Fix Url parser when using path only
    
    refs #12874

_2016-12-08 12:48:15 +00:00_ by _jflach_ 115d4b5a67d9824a55d84af84293e3e1fff48015

    Add docs for check_nscp
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ 5340582e1796146ec18f19aa66028ba80139d2ec

    Start working on check_nscp
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ 6db3c9b04dd76ce50aa2997880fdcad6bc3fe45d

    Improve HTTP Handler error message
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ acbe618d66643a04769867be1fd1e051faf88f22

    Check_nscp v0.1
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ bc1bc63be3cf3655b1534d071fbef6be7f8fb785

    Add CheckCommand for check_nscp.exe
    
    Currently Windows only
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ b91314b67efc3e98fe1f877631c76ced54bfeb16

    Fix itl entry for check_nscp
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ 9fd9daa486ad892271b456e7797197e5ef4b15e1

    Format changes to check_nscp
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ e1c883f9fadbc3e7c3b88a3ea1eda3da29b0cacc

    Add additional error checking to check_nscp
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ e2c26d1e09bc3ddcc01ff01291ad51bff0848583

    Add informational error output
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ a15d26257791c9b8509997b312c0dfb9e391e54a

    Update ITL for check_nscp
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ 1d18b2c7edc89da89c3821588df62d783fafdf30

    Build check_nscp on Linux too
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ 08dd7220a4c2f2f8f8e473d6747fb9ae41b81411

    Fix Cmake for check_nscp
    
    refs #12874

_2016-12-08 13:02:41 +00:00_ by _jflach_ 116ffdbc21fd64bddac61d108b4b3027a0beb73a

    Add comments and debug mode to check_nscp
    
    Also update cmake
    
    refs #12874

_2016-12-08 13:03:06 +00:00_ by _jflach_ 354e75f72f311cac48036179264c8dd743f4f035

    Remove check_nscp from command-plugins
    
    Otherwise it breaks the windows default conf and since we probably won't
    have check_nscp on Linux it's better to remove it for now
    
    refs #12874

_2016-12-08 13:03:06 +00:00_ by _jflach_ ce0acb2e6506ce12b883a9aec7d4eef0ffc5dc56

    Add docs for check_nscp
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ acb9fa981e1e31996bd037df97dfa9e9c2b8359f

    Start working on check_nscp
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ 379662bbd853afe02ed1f6ccb556bf8d6677b5b1

    Improve HTTP Handler error message
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ e8e6c6a6cea2eb4b925ebde303c293155eea9fe2

    Check_nscp v0.1
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ d05f832664505cdc833c7251dd412048d032e99a

    Add CheckCommand for check_nscp.exe
    
    Currently Windows only
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ 97bdfd76a1269bdd34bb2fb1afde3ce56cb5ab70

    Fix itl entry for check_nscp
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ d049da5af7aa687c6c0752db2679e7baf9c5f9ce

    Format changes to check_nscp
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ 6ae743f8b65591a727c1ff93cc8f0ab182b11076

    Add additional error checking to check_nscp
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ 3b596d3fba4f0d5854996744ecc1130168833fd4

    Add informational error output
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ 431133a9ee8a159b958fb17c01fb4fc561fc8519

    Update ITL for check_nscp
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ aebc28a0500534d7481c37b41ccb1848ce912347

    Build check_nscp on Linux too
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ c2235fa2534245469ddd87ad55864a672e92708f

    Fix Cmake for check_nscp
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ 331668423284ad316077fb3d717e7e1da957bf1f

    Add comments and debug mode to check_nscp
    
    Also update cmake
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ 276d51a43d61c5b31fecd7eb90662b9ad750c1c0

    Remove check_nscp from command-plugins
    
    Otherwise it breaks the windows default conf and since we probably won't
    have check_nscp on Linux it's better to remove it for now
    
    refs #12874

_2016-12-08 13:30:12 +00:00_ by _jflach_ 02d81cc46c526f6092959144428176c88e7366bd

    Add docs for check_nscp
    
    refs #12874

_2016-12-08 14:35:21 +00:00_ by _jflach_ d265c851bb119db4301c81e34f4177a0cf9daefb

    Add image for check_nscp doc
    
    refs #12874

---

**Subtasks**:

* [Bug 12883 - Url Does not format query parts without value correctly](https://dev.icinga.com/issues/12883)

**Comment by dnsmichi** [comment]
Contains a reference to #4725 - which is merged to master partially. Any ideas @Crunsher ?

I've rebased the branch against current master, as well as edited the commit id references.

Before we start a review to merge we should discuss the following

- rename check_nscp to check_nscp_api or check_nscp_http to better reflect its purpose. This also avoids name collisions with nsclient itself, and our ITL CheckCommand `nscp` which actually is using check_nt.
- Decide whether to build and ship it on Linux too (would be a nice addition, but not a requirement for now).

The patches contain a couple of whitespace fixes too but weren't causing trouble during rebase.

**Comment by Crunsher** [comment]
>rename check_nscp to check_nscp_api or check_nscp_http to better reflect its purpose. This also avoids name collisions with nsclient itself, and our ITL CheckCommand nscp which actually is using check_nt.

Renaming the plugin is a sound idea. I like 'check_nscp_api' for the binary and 'nscp-api' for the ITL.

>Decide whether to build and ship it on Linux too (would be a nice addition, but not a requirement for now).

At the time I decided against building it for Linux because we didn't ship any plugins with the Linux version of Icinga 2. I thought about shipping it separately (Icinga Exchange) but as it uses Icinga 2 libraries dropped the idea :D This is a decision we should also involve @gunnarbeutner in, as it would set precedence.

>The patches contain a couple of whitespace fixes too but weren't causing trouble during rebase.

Damn, I need to be more careful about what I commit

**Comment by gunnarbeutner** [comment]
After a very brief discussion @dnsmichi and I have decided not to provide the plugin in the *nix version. :)

**Comment by dnsmichi** [comment]
Continuing in #5239 in favor of this old working ticket.
