### ISSUE TITLE
[dev.icinga.com #12877] Define mandatory variable to host object

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4722]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12877

**Created by siyalrach on 2016-10-09 21:36:45 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-10 06:34:41 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Does any one know how to define a mandatory variable to a host object.

I have a scenario where all our hosts must have a custom variable with their location added to the object, but how do I check if it is satisfied before a deployment?

**Comment by dnsmichi** [comment]
That's a thing for #3520

**Comment by gunnarbeutner** [comment]
PR #6030 would fix this.

**Comment by dnsmichi** [comment]
That could also be a thing for "special" object types we've talked earlier this year @bobapple

**Comment by htriem** [comment]
There are no plans to implement this feature.
