### ISSUE TITLE
[dev.icinga.com #12898] icinga2 process crash 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4727]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12898

**Created by ebisu on 2016-10-12 12:54:32 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-21 10:18:00 +00:00 (in Redmine)_

    Icinga Version: r2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

after some hours my Icinga2 Instance is crashing. In the error log is:
icinga2: /usr/include/boost/smart\_ptr/intrusive\_ptr.hpp:162: T\* boost::intrusive\_ptr<T>::operator-&gt;() const \[with T = icinga::Stream\]: Assertion \`px != 0' failed.
Caught SIGABRT.

This happend after the last update. I use the latest version from:
http://ppa.launchpad.net/formorer/icinga/ubuntu

Icinga2 version:
icinga2 - The Icinga 2 network monitoring daemon (version: r2.5.4-1)

System information:
Platform: Ubuntu
Platform version: 14.04.5 LTS, Trusty Tahr
Kernel: Linux
Kernel version: 3.13.0-96-generic
Architecture: x86\_64

When I keep restarting it with a cronjob it never crashes.

If there is any Info you need just ask.

Thanks for the help!

---

**Relations**:

* relates [#12667](https://dev.icinga.com/issues/12667)

**Comment by Nebelwolf** [comment]
In the latest Version (r2.6.0-1) this seems to be fixed. 
No more crashes since 22.12.2016.

Before it crashed at least once or twice a week.
