### ISSUE TITLE
[dev.icinga.com #12907] SCHEDULE_HOST_SVC_DOWNTIME equivalent

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4730]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12907

**Created by aklimov on 2016-10-13 08:13:11 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-13 08:14:49 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

**Comment by dnsmichi** [comment]
AFAIK we discussed that with @lippserd and came to the conclusion that two API calls are sufficient for Icinga Web 2 as API client.
