### ISSUE TITLE
[dev.icinga.com #12925] Open firewall during Icinga 2 Windows agent

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4733]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12925

**Created by twidhalm on 2016-10-14 11:40:40 +00:00**

Assignee: _elippmann_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-17 13:01:25 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

I just learned from a Windows admin at a customers that it's best practice that Windows install routines should open firewall ports and bind them to the corresponding .exe file no matter if the firewall is running on the host or not.

It might be a good idea to make the Windows install routine accord to the Microsoft best practices.

Cheers,
Thomas

**Comment by dnsmichi** [comment]
Ask @lippserd directly for a raised priority on this.

**Comment by dnsmichi** [comment]
https://github.com/wixtoolset/issues/issues/5869

**Comment by dnsmichi** [comment]
With the new Icinga for windows package developed by @LordHepipud this won't be taken into account for future development iterations. Learn more about this new project here: https://icinga.com/2019/11/05/icinga-for-windows-rc-available/
