### ISSUE TITLE
[dev.icinga.com #12954] Schedule downtime for big hostgroups takes very long

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4743]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12954

**Created by koudis on 2016-10-21 12:07:11 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-21 12:07:11 +00:00 (in Redmine)_

    Icinga Version: 2.3.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,
we have three issues with schedule downtime for Icinga 2.
1/ It is not possible to set it for 1000 services from UI as select of all services in UI will kill your browser.
2/ While you try to set it via API. It takes about 15-20 minutes to set it.
3/ API call sometimes miss few services and downtime is not set properly and no error is reported back to user

Our curl calls used for downtime:
export RELEASE\_FROM=$(date +%s -d "23 Jul 2016 8:45")
export RELEASE\_TO=$(date +%s -d "23 Jul 2016 12:15")
export RELEASE\_DURATION=$(expr $RELEASE\_TO - $RELEASE\_FROM)
export DOWNTIME\_AUTHOR=$(whoami)
\#service downtime
curl -H 'Accept: application/json' -X POST -d '{ [start\_time]() '$RELEASE\_FROM', [end\_time]() '$RELEASE\_TO', [duration]() '$RELEASE\_DURATION', [author]() "'$DOWNTIME\_AUTHOR'", [comment]() "Release" }' -k -u : --negotiate 'https://icinga2-master:8443/v1/actions/schedule-downtime?type=Service&filter=%22Cluster%2051%22%20in%20host.groups%20%7C%7C%20%22Cluster%20101%22%20in%20host.groups'
\#host downtime
curl -H 'Accept: application/json' -X POST -d '{ [start\_time]() '$RELEASE\_FROM', [end\_time]() '$RELEASE\_TO', [duration]() '$RELEASE\_DURATION', [author]() "'$DOWNTIME\_AUTHOR'", [comment]() "Release" }' -k -u : --negotiate 'https://icinga2-master:8443/v1/actions/schedule-downtime?type=Host&filter=%22Cluster%2051%22%20in%20host.groups%20%7C%7C%20%22Cluster%20101%22%20in%20host.groups'

**Comment by milan-koudelka** [comment]
We have a new record. Because set downtime action often fail for few hosts, we set that separately for each host and then verify, if it is really set. Set downtime action took 40 minutes in last try. 
It's probably easier to reconfigure all host/services to disable notifications, instead of using downtime. It will be faster.
Can you confirm this issue ? Do you have any suggestion how to workaround this ?

**Comment by dnsmichi** [comment]
Could be related to #5080. Please check again with v2.6.3.

**Comment by dnsmichi** [comment]
Haven't heard anything, closing this issue.
