### ISSUE TITLE
[dev.icinga.com #12961] Retention policy on Configuration stages / deleting inactive stages

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4745]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12961

**Created by james_rahul2002 on 2016-10-24 04:15:36 +00:00**

Assignee: _james_rahul2002_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-11-11 08:45:46 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi Icinga Team,

This is with respect to the discussion that we had in the forum

https://monitoring-portal.org/index.php?thread/38255-how-to-delete-inactive-stages-for-a-package/

There is no configuration available where we can define the number of stages to be maintained apart from active stage for an icinga node , or some kind of retention policy on old stages or invalid stages. As of now it is taken care by custom scripts to delete stages which are not active.

Thanks
Rahul

**Comment by Crunsher** [comment]
Is this going to happen anytime soon? Is this an issue for anybody?

I would like to close this as it's very niche and old

**Comment by dnsmichi** [comment]
I don't think we will implement this in the near or far future. Applications which use the packages themselves can also clean them up via the REST API.

Cheers,
Michael
