### ISSUE TITLE
[dev.icinga.com #12963] Flapping start notifications not always sent

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4746]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12963

**Created by tontonitch on 2016-10-24 13:38:36 +00:00**

Assignee: _tontonitch_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2017-01-02 18:33:41 +00:00 (in Redmine)_

    Icinga Version: 2.5.4

---

Hi,

As I have some issues with flapping detection (missing flapping start and maybe notifications during flapping period), I'm trying to figure out how the flapping detection works and how to configure it correctly.
For the missing flappingstart notifications, please find an extract of the received emails from icinga2. As you can see, there are lots of flappingend but only a few flappingstart.

Trying to figure out how the flapping detection works and how to configure it correctly, I didn't find lots of information on that subject in the official documentation.
I found some discussions and issues,
https://monitoring-portal.org/index.php?thread/33068-benachrichtigungen-trots-flapping/&postID=214764&highlight=flapping\_thresh#post214764
https://lists.icinga.org/pipermail/icinga-users/2015-June/009657.html
https://dev.icinga.org/issues/11899
https://dev.icinga.org/issues/9642

So I guess the default value for flapping\_thresh is 30. What does it mean exactly? In order to calculate the adequate value to set here.

Also, unfortunately the icingaweb2 interface doesn't handle flapping notification yet (https://dev.icinga.org/issues/12766). So the only way to check that flapping detection and notification behavior during flapping period are working correctly is to check icinga2 log file.

Best regards,
Yannick

**Attachments**

* [missing_flappingstart_notifications.png](https://dev.icinga.com/attachments/download/3724/missing_flappingstart_notifications.png) tontonitch - _2016-10-24 13:37:12 +00:00_

**Comment by dnsmichi** [comment]
Will be continued in #4982.
