### ISSUE TITLE
[dev.icinga.com #12992] Add check_md_raid to ITL

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4751]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12992

**Created by twidhalm on 2016-10-27 08:24:29 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 00:27:56 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

This patch adds `check_md_raid` to the ITL. This is a very minimalistic plugin and does not need any configuration. The main reason I want this in the ITL is that there is no mdadm check plugin so far and the documentation could use a reference to a working one. If you have a better alternative, I'll be glad to change the request to incorporate another mdadm check plugin.

Cheers,
Thomsa

**Attachments**

* [0001-Add-check_md_raid-to-ITL.patch](https://dev.icinga.com/attachments/download/3739/0001-Add-check_md_raid-to-ITL.patch) twidhalm - _2016-10-27 08:24:23 +00:00_
* [0001-Add-check_md_raid-to-ITL.patch](https://dev.icinga.com/attachments/download/3740/0001-Add-check_md_raid-to-ITL.patch) twidhalm - _2016-10-27 08:35:16 +00:00_

**Comment by dnsmichi** [comment]
@widhalmt can you please update the patch against current master and send a PR?

**Comment by widhalmt** [comment]
Will do as soon as I find the time. Hopefully this or next week. Sorry for the delay.

**Comment by dnsmichi** [comment]
Ping :)

**Comment by gunnarbeutner** [comment]
Pong.

**Comment by dnsmichi** [comment]
Closing as no updated patch was received.
