### ISSUE TITLE
[dev.icinga.com #13006] windows check_update doesn't work on Server 2012

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4755]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13006

**Created by nti on 2016-10-28 16:49:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-28 16:49:42 +00:00 (in Redmine)_

    Icinga Version: r2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

On different windows server 2012 installation "check\_update.exe" hangs for *hours* without response

starzig check\_update.exe with -d:

    Initializing COM library
    Creating UpdateSession and UpdateSearcher
    Querrying updates from server

I've startet the microsoft DebugDiag2 tool:

1) check\_update.exe is waiting with that messages

    ntdll!ZwWaitForMultipleObjects+a
    KERNELBASE!WaitForMultipleObjectsEx+e5
    user32!MsgWaitForMultipleObjectsEx+144
    combase!CCliModalLoop::BlockFn+12f
    combase!ClassicSTAThreadWaitForHandles+106
    combase!CoWaitForMultipleHandles+f9
    wuapi!Ordinal1+2e302
    wuapi!Ordinal1+287f3
    check_update+4694
    check_update+69ba
    check_update+2004b
    kernel32!BaseThreadInitThunk+1a
    ntdll!RtlUserThreadStart+21

2) Windows Update is hanging around with that:
​

    msvcrt!memset+3c
    wuaueng!CUpdateDetectInfoList::FindNewestUpdate+9d
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+d4
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::AddSupersedenceInfoIfNeeded+11f
    wuaueng!CUpdatesToPruneList::PopulateSupersedenceInfo+b4
    wuaueng!CAgentUpdateManager::PrepareSearchCallbackInfo+250
    wuaueng!CAgentUpdateManager::FindUpdates+276d
    wuaueng!CSearchCall::Execute+5c
    wuaueng!CClientCallRecorder::ProcessWorkItem+ef
    wuaueng!CWorkItemManager::ExecuteNonCallbackWorkItem+cc
    wuaueng!CWorkItemManager::ExecuteWorkItemWrapper+43
    kernel32!BaseThreadInitThunk+1a
    ntdll!RtlUserThreadStart+21

I've written the dumps every 5 minutes, but the states are all the same.

In addition the process manager from Sysinternals shows a lot of growing "RtlUserThreadStart+21" threads.

I'm not a programmer and I'm not able to interpret this stuff.

**Comment by dnsmichi** [comment]
@Crunsher please have a look into this.

**Comment by Crunsher** [comment]
I'm closing this, pointing anybody who wants to check updates on Windows server 2012 (EOL October 2018) to NSClient++
