### ISSUE TITLE
[dev.icinga.com #13018] Tabulation and CLI command

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4757]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13018

**Created by tofu00 on 2016-10-31 10:57:12 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2016-12-07 22:41:38 +00:00_)
Target Version: _(none)_
Last Update: _2017-01-14 13:05:59 +00:00 (in Redmine)_

    Icinga Version: 2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,
When I type the command "icinga2 repository host add ", and then I type the tab key, this error appears:

    icinga2: /usr/include/boost/smart_ptr/intrusive_ptr.hpp:162: T* boost::intrusive_ptr::operator->() const [with T = icinga::Type]: Assertion `px != 0' failed.
    Caught SIGABRT.
    Current time: 2016-10-31 11:48:22 +0100

    icinga2: /usr/include/boost/smart_ptr/intrusive_ptr.hpp:162: T* boost::intrusive_ptr::operator->() const [with T = icinga::Type]: Assertion `px != 0' failed.
    Caught SIGABRT.
    Current time: 2016-10-31 11:48:22 +0100

    +0100]                                             critical/Application:                              information
    11:48:22                                           --define                                           --library
    2                                                  found                                              --log-level
    [2016-10-31                                        has                                                --script-debugger
    Additional                                         --help                                             terminated
    --app                                              Icinga                                             unexpectedly.
    be                                                 --import                                           '/var/log/icinga2/crash/report.1477910902.932653'
    can                                                in                                                 --version
    --color                                            --include

It seems to be only present with the "add" option.

Icinga2 --version:

    icinga2 - The Icinga 2 network monitoring daemon (version: r2.5.4-1)

    Application information:
      Installation root: /usr
      Sysconf directory: /etc
      Run directory: /run
      Local state directory: /var
      Package data directory: /usr/share/icinga2
      State path: /var/lib/icinga2/icinga2.state
      Modified attributes path: /var/lib/icinga2/modified-attributes.conf
      Objects path: /var/cache/icinga2/icinga2.debug
      Vars path: /var/cache/icinga2/icinga2.vars
      PID path: /run/icinga2/icinga2.pid

    System information:
      Platform: Debian GNU/Linux
      Platform version: 8 (jessie)
      Kernel: Linux
      Kernel version: 3.16.0-4-amd64
      Architecture: x86_64

    Build information:
      Compiler: GNU 4.9.2
      Build host: smithers

---

**Parent Task:** [#13257](https://dev.icinga.com/issues/13257)

**Relations**:

* relates [#13018](https://dev.icinga.com/issues/13018)

**Comment by dnsmichi** [comment]
#4799
