### ISSUE TITLE
[dev.icinga.com #13032] Server crash - general protection fault:

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4762]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13032

**Created by piotr on 2016-11-02 19:48:25 +00:00**

Assignee: _piotr_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-11-11 14:55:30 +00:00 (in Redmine)_

    Icinga Version: r2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Client node with simple configuration crash radomly:

Log:

    Nov  2 20:16:57 localhost kernel: [ 2504.772475] general protection fault: 0000 [#1] SMP
    Nov  2 20:16:57 localhost kernel: [ 2504.772487] CPU 2
    Nov  2 20:16:57 localhost kernel: [ 2504.772489] Modules linked in: nfsd nfs lockd fscache auth_rpcgss nfs_acl sunrpc lp parport
    Nov  2 20:16:57 localhost kernel: [ 2504.772503]
    Nov  2 20:16:57 localhost kernel: [ 2504.772507] Pid: 5193, comm: icinga2 Not tainted 3.2.0-34-generic #53-Ubuntu
    Nov  2 20:16:57 localhost kernel: [ 2504.772514] RIP: e030:[]  [] effective_load.isra.57+0x12/0xa0
    Nov  2 20:16:57 localhost kernel: [ 2504.772526] RSP: e02b:ffff8801eef15d08  EFLAGS: 00010006
    Nov  2 20:16:57 localhost kernel: [ 2504.772530] RAX: 0000000000000400 RBX: ffff8801f147c500 RCX: 0000000000000400
    Nov  2 20:16:57 localhost kernel: [ 2504.772536] RDX: 0000000000000002 RSI: 000000000000fe05 RDI: 55e055e00100007f
    Nov  2 20:16:57 localhost kernel: [ 2504.772541] RBP: ffff8801eef15d08 R08: 0000000000000400 R09: 00000000000137c0
    Nov  2 20:16:57 localhost kernel: [ 2504.772546] R10: 00000000000137c0 R11: 0000000000000000 R12: 0000000000000002
    Nov  2 20:16:57 localhost kernel: [ 2504.772551] R13: ffff8801ee60c400 R14: ffff8801f225da00 R15: 0000000000000001
    Nov  2 20:16:57 localhost kernel: [ 2504.772561] FS:  00007f5e354d5700(0000) GS:ffff8801ffd00000(0000) knlGS:0000000000000000
    Nov  2 20:16:57 localhost kernel: [ 2504.772567] CS:  e033 DS: 0000 ES: 0000 CR0: 000000008005003b
    Nov  2 20:16:57 localhost kernel: [ 2504.772572] CR2: 00007f088f869f9f CR3: 00000001eedf7000 CR4: 0000000000002660
    Nov  2 20:16:57 localhost kernel: [ 2504.772577] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
    Nov  2 20:16:57 localhost kernel: [ 2504.772583] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
    Nov  2 20:16:57 localhost kernel: [ 2504.772588] Process icinga2 (pid: 5193, threadinfo ffff8801eef14000, task ffff8801effadc00)
    Nov  2 20:16:57 localhost kernel: [ 2504.772596] Stack:
    Nov  2 20:16:57 localhost kernel: [ 2504.772599]  ffff8801eef15d88 ffffffff8104fbc9 00000000000137c0 00000000000137c0
    Nov  2 20:16:57 localhost kernel: [ 2504.772608]  7fffffff00000000 000000000000038f 0000000000000400 0000000100000000
    Nov  2 20:16:57 localhost kernel: [ 2504.772617]  0000000000007274 00000000000001e9 ffffffff00000002 ffff8801f147c500
    Nov  2 20:16:57 localhost kernel: [ 2504.772626] Call Trace:
    Nov  2 20:16:57 localhost kernel: [ 2504.772631]  [] wake_affine+0xf9/0x310
    Nov  2 20:16:57 localhost kernel: [ 2504.772638]  [] select_task_rq_fair+0x1bc/0x340
    Nov  2 20:16:57 localhost kernel: [ 2504.772646]  [] try_to_wake_up+0x124/0x200
    Nov  2 20:16:57 localhost kernel: [ 2504.772652]  [] default_wake_function+0x12/0x20
    Nov  2 20:16:57 localhost kernel: [ 2504.772659]  [] __wake_up_common+0x58/0x90
    Nov  2 20:16:57 localhost kernel: [ 2504.772664]  [] __wake_up_locked+0x18/0x20
    Nov  2 20:16:57 localhost kernel: [ 2504.772673]  [] ep_modify+0xcf/0xe0
    Nov  2 20:16:57 localhost kernel: [ 2504.772678]  [] sys_epoll_ctl+0x210/0x3e0
    Nov  2 20:16:57 localhost kernel: [ 2504.772686]  [] system_call_fastpath+0x16/0x1b
    Nov  2 20:16:57 localhost kernel: [ 2504.772690] Code: 40 01 00 00 48 85 d2 75 d8 e9 11 ff ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 55 48 89 e5 66 66 66 66 90 48 63 d2 48 85 f6 48 89 c8 <48> 8b 3c d7 74 78 48 85 ff be 02 00 00 00 75 2f eb 6c 0f 1f 40
    Nov  2 20:16:57 localhost kernel: [ 2504.772745] RIP  [] effective_load.isra.57+0x12/0xa0
    Nov  2 20:16:57 localhost kernel: [ 2504.772753]  RSP 
    Nov  2 20:16:57 localhost kernel: [ 2504.772759] ---[ end trace a1fa7b5547021411 ]---

Icinga version:

    icinga2 - The Icinga 2 network monitoring daemon (version: r2.5.4-1)

    Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
    License GPLv2+: GNU GPL version 2 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Application information:
      Installation root: /usr
      Sysconf directory: /etc
      Run directory: /var/run
      Local state directory: /var
      Package data directory: /usr/share/icinga2
      State path: /var/lib/icinga2/icinga2.state
      Modified attributes path: /var/lib/icinga2/modified-attributes.conf
      Objects path: /var/cache/icinga2/icinga2.debug
      Vars path: /var/cache/icinga2/icinga2.vars
      PID path: /var/run/icinga2/icinga2.pid

    System information:
      Platform: Ubuntu
      Platform version: 12.04.1 LTS, Precise Pangolin
      Kernel: Linux
      Kernel version: 3.2.0-34-generic
      Architecture: x86_64

    Build information:
      Compiler: GNU 4.6
      Build host: lgw01-51

**Comment by dnsmichi** [comment]
Pending feedback, reopen if any.
