### ISSUE TITLE
[dev.icinga.com #13054] API filters with custom attributes problem

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4766]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13054

**Created by moritz on 2016-11-05 15:25:25 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2016-11-07 07:13:50 +00:00_)
Target Version: _(none)_
Last Update: _2016-11-25 14:28:22 +00:00 (in Redmine)_

    Icinga Version: 2.3.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Some of our hosts have custom variables that are arrays, and I've tried to create a downtime for a all hosts that have a particular string as element in such a variable. There doesn't seem to be a way to do that, and if there is, then that documentation at http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/icinga2-api fails to mention it.

Things I have tried:

-   `filter="thestring" in host.vars.thevariable`, inspired by the example `filter="linux-servers" in host.groups` in the API docs. Result: no downtime created.
-   `filter=match("thestring",host.vars.thevariable)`. Result: No downtime created
-   `filter=match("*thestring*",host.vars.thevariable)`. Result: Hosts where host.vars.thevariable contain "thestringbutlonger" also get the downtime created.

**Comment by dnsmichi** [comment]
The match() functionality for arrays has been added in 2.7.0 ( #5264 ).
