### ISSUE TITLE
[dev.icinga.com #13069] Allow to replicate console commands

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4768]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13069

**Created by tgelf on 2016-11-08 10:53:57 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-08 10:53:57 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

### User story

As a user I want to manage monitoring for a large amount of systems with Icinga 2 and Icinga Director while still being able to modify/add/remove hosts or services within a fraction of a second.

### Requirements for Icinga 2

-   Provide a method \_\_run\_distributed\_with\_activation\_context()
-   We might settle on an "official" method name later on, once this has proven to work fine
-   This method should behave like \_\_run\_with\_activation\_context (which works perfectly, but lacks replication)
-   This method must additionally require a second parameter specifying the target zone
-   This command should be sent as a fake file through our replication mechanism
-   Other nodes should parse and evaluate that snippet like any other replicated config file
-   These should be throwaway "config files", they should not be persisted at all

As an alternative it would also be pretty cool to add a 'zone' parameter to console/execute-script. Similar functionality might eventually be helpful for other tasks too.

### Requirements for Icinga Director

Live creation has been implemented as an experimental feature quite some time ago and still works fine. We can however not really release this feature as long as it lacks replication support. In addition to what we have today, the following must be implemented:

-   A more flexible white-listing mechanisms. Currently only "create a new host" is hardcoded allowed to be executed immediately.
-   In future this should check all applied changed and validate whether a live modification is possible
-   Related objects like inherited or applied services, notifications and more should be deployed as single flat (fully resolved) objects

---

**Relations**:

* relates [#13069](https://dev.icinga.com/issues/13069)

**Comment by dnsmichi** [comment]
The console cli command is for debugging purposes only. As such internal functions for activating objects are highly experimental and shouldn't be used in production environments. A proper design for runtime modifications is needed here, but not part of this issue.
