### ISSUE TITLE
[dev.icinga.com #13070] Validate and activate config package stages without triggering a reload

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4769]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13070

**Created by tgelf on 2016-11-08 10:54:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-08 10:54:09 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

When I currently deploy a new stage to a config package, Icinga immediately performs validation, switches the active stage and reloads itself. I'd like to have something like a boolean 'reload' flag which should default to true. Setting this to false should still validate the config and switch the stage name, but do not reload yet. This would allow to prepare a configuration for later deployment and to make sure that config after a planned or unplanned restart would reflect what live modification changed on our objects.

---

**Relations**:

* relates [#13069](https://dev.icinga.com/issues/13069)

**Comment by dnsmichi** [comment]
Amended doc and code style fixes. Thanks for the patch 👍

**Comment by dnsmichi** [comment]
Ups. Wrong issue.
