### ISSUE TITLE
[dev.icinga.com #13127] Icinga2 can crash when hitting nproc limit

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4772]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13127

**Created by nlm on 2016-11-10 10:24:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-10 16:22:26 +00:00 (in Redmine)_

    Icinga Version: r2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

I've lately had some problems with a pretty large icinga2 cluster,
one of my nodes kept crashing.

Issue came from icinga2 hitting the max process limit. Raising the limit solved the problem.
Definately not a memory problem.

The issue somtimes raises an unhandled exception and makes icinga crash.
I suppose this is not intended since the crash doesn't happen all the time.
At the beginning i got fork error messages from plugins reported in the icingaweb2 interface,
and after adding more checks, the icinga2 daemon started to crash.

I'm not sure the concurrent\_checks setting could have changed anything about this, since it's default is 512
and the initial limit for nprocs is about 65k. I'm not sure why this limit is hit, though.

    $ ulimit -u
    64057
    $ ulimit -Hu
    64057

This is the content of one of the crash files :

    Caught unhandled exception.
    Current time: 2016-11-09 15:39:37 +0000

    Application information:
      Application version: r2.5.4-1
      Installation root: /usr
      Sysconf directory: /etc
      Run directory: /run
      Local state directory: /var
      Package data directory: /usr/share/icinga2
      State path: /var/lib/icinga2/icinga2.state
      Modified attributes path: /var/lib/icinga2/modified-attributes.conf
      Objects path: /var/cache/icinga2/icinga2.debug
      Vars path: /var/cache/icinga2/icinga2.vars
      PID path: /run/icinga2/icinga2.pid

    System information:
      Platform: Ubuntu
      Platform version: 16.04 LTS (Xenial Xerus)
      Kernel: Unknown
      Kernel version: sh: 1: Cannot fork
      Architecture: Unknown

    Build information:
      Compiler: GNU 5.4.0
      Build host: lgw01-29

    Error: boost::thread_resource_error: Resource temporarily unavailable

        (0) libbase.so: void boost::throw_exception(boost::thread_resource_error const&) (+0x200) [0x7febb0f6e6c0]
        (1) libbase.so: icinga::ThreadPool::Queue::SpawnWorker(boost::thread_group&) (+0x32d) [0x7febb0f0a1ad]
        (2) libbase.so: icinga::ThreadPool::ManagerThreadProc() (+0xafb) [0x7febb0f0c11b]
        (3) libboost_thread.so.1.58.0:  (+0x115d5) [0x7febb1ebc5d5]
        (4) libpthread.so.0:  (+0x76fa) [0x7febb18136fa]
        (5) libc.so.6: clone (+0x6d) [0x7febb05b3b5d]

    ***
    * This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
    * please submit a bug report at https://dev.icinga.org/ and include this stack trace as well as any other
    * information that might be useful in order to reproduce this problem.
    ***

Hope this helps,
Thanks

**Comment by dnsmichi** [comment]
This has been solved in the package builds already.
