### ISSUE TITLE
[dev.icinga.com #13141] Object types oddities

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4774]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13141

**Created by nlm on 2016-11-10 14:29:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-10 14:29:14 +00:00 (in Redmine)_

    Icinga Version: 2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

I was coding some functions in my icinga2 configuration, when I remarked that there are some oddities in object types:
- most objects have a type field (Object, User, Type, ...)
- Array has a type ("Array")
- Dictionnary has a type field but a null type (null)
- Number, String have no type field

=&gt; Type.type
"Type"
=&gt; Object.type
"Type"
=&gt; Object().type
"Object"
=&gt; User().type
"User"
=&gt; UserGroup().type
"UserGroup"
=&gt; \[\].type
"Array"
=&gt; {}.type
null
=&gt; {test = 123}.type
null
=&gt; Dictionary().type
null
=&gt; 0.type
<sup></sup>
Invalid field access (for value of type 'Number'): 'type'
=&gt; Number().type
<sup></sup>^
Invalid field access (for value of type 'Number'): 'type'
=&gt; "Hello".type
<sup></sup>
Invalid field access (for value of type 'String'): 'type'

It seems it's not intentional

**Comment by gunnarbeutner** [comment]
Maybe we should just remove the `.type` attribute because there's no way we can make it work for the `Dictionary` class.

**Comment by Al2Klimov** [comment]
I'd not remove it as that would be a breaking change, but I'd throw it out of the docs.

There's literally no use case for this – we have `typeof()` after all.

**Comment by Al2Klimov** [comment]
Wait as sec... there isn't anything to throw out as the doc only mentions `#type` for `Object` and the config objects, but **not** for any "JSON type". IMO it's not too bad that there are non-intentionally exposed things as long as they're not documented.
