### ISSUE TITLE
[dev.icinga.com #13167] Improve SELinux Policy

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4781]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13167

**Created by dgoetz on 2016-11-11 14:20:31 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-11 14:26:23 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Improve the SELinux policy after changes in the last versions of icinga2, add interface for api connections and enable httpd to connect it, set policy to enforcing by default so admin can decide on its own to run it permissive.

**Comment by dnsmichi** [comment]
The docs require certain changes and wording improvements, but that's to be done in a separate ticket,
