### ISSUE TITLE
[dev.icinga.com #13197] API: Command process-check-result fails if it contains performance data

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4786]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13197

**Created by elippmann on 2016-11-15 09:33:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-15 09:33:16 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Icinga 2 fails w/ the following error: Error: Cannot convert value of type 'String' to an object.

**Comment by dnsmichi** [comment]
```
$ curl -k -s -u root:icinga 'https://localhost:5665/v1/actions/process-check-result' -X POST -H 'Accept: application/json' -d '{ "type": "Service", "filter": true, "plugin_output": "abc", "performance_data": "key1=9", "exit_status": 2 }'
```

**Comment by dnsmichi** [comment]
![screen shot 2018-02-06 at 15 22 51](https://user-images.githubusercontent.com/382049/35864320-be1850c4-0b51-11e8-826e-36f4c8312bd3.png)
![screen shot 2018-02-06 at 15 22 56](https://user-images.githubusercontent.com/382049/35864321-be309918-0b51-11e8-9aaa-66ebf71f5ec1.png)
