### ISSUE TITLE
[dev.icinga.com #13203] IDO MySQL - delete statement creates high load and locks tabe after enabling cleanup

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4788]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13203

**Created by winem_ on 2016-11-15 13:24:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-15 13:24:10 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

We run this icinga instance for some months now and initially enabled the cleanup in the IdoMySqlConnection configuration today:

cleanup = {
downtimehistory\_age = 31d
contactnotifications\_age = 31d
statehistory\_age = 31d
externalcommands\_age = 14d
}

This was fine for contactnotifications, statehistory and downtimehistory but caused a high load when running the delete statement on the externalcommands table.

Query: DELETE FROM icinga\_externalcommands WHERE instance\_id = 1 AND entry\_time &lt; FROM\_UNIXTIME(1477991035)

This is fine, but, in this case, more than 50 million rows are affected. So the delete statement was running for a almost an hour, when I killed it, increased the load and prevented table locks by other queries.

The solution that came into my mind is to run the delete query with a limit in a loop and fetch the number of affected rows from the response. Exit the loop when 0 rows have been deleted.

**Comment by dnsmichi** [comment]
I'd say it would be a good idea to not log externalcommands anymore beforehand, but for the deleting algorithm - yep, nice idea. Patches welcome.

**Comment by dnsmichi** [comment]
I'm removing the default categories setting in a separate PR. If you come up with a solution for batched deletes, please send in a PR and we can reopen this issue.
