### ISSUE TITLE
[dev.icinga.com #13237] Icinga2 won't run in background, only foreground

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4794]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13237

**Created by andyb2000 on 2016-11-18 08:53:06 +00:00**

Assignee: _andyb2000_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-07 21:22:10 +00:00 (in Redmine)_

    Icinga Version: r2.5.4-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Icinga2 running for weeks without issues (in background, using init script /etc/init.d/icinga2 start), this morning process won't start, but it will run in foreground.

No configuration changes were made between the normal running and failure.

When trying to start with the init script (/etc/init.d/icinga2 start), no startup.log written, no log files written, no crash files written. Just no process running.
If I then run with /etc/init.d/icinga2 foreground it starts and works without issue.

I suspect the start of the crash was logged in the icinga2.err:
icinga2: /usr/include/boost/smart\_ptr/intrusive\_ptr.hpp:174: T\* boost::intrusive\_ptr<T>::operator-&gt;() const \[with T = icinga::Stream\]: Assertion \`px != 0' failed.
Caught SIGABRT.
Current time: 2016-11-17 21:35:52 +0000

icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.5.4-1)

Copyright © 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later &lt;http://gnu.org/licenses/gpl2.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
Installation root: /usr
Sysconf directory: /etc
Run directory: /run
Local state directory: /var
Package data directory: /usr/share/icinga2
State path: /var/lib/icinga2/icinga2.state
Modified attributes path: /var/lib/icinga2/modified-attributes.conf
Objects path: /var/cache/icinga2/icinga2.debug
Vars path: /var/cache/icinga2/icinga2.vars
PID path: /run/icinga2/icinga2.pid

System information:
Platform: Ubuntu
Platform version: 16.04.1 LTS (Xenial Xerus)
Kernel: Linux
Kernel version: 3.16.0-77-generic
Architecture: x86\_64

Build information:
Compiler: GNU 5.4.0
Build host: lgw01-29

Disabled features: compatlog debuglog gelf graphite icingastatus influxdb opentsdb perfdata syslog
Enabled features: api checker command ido-mysql livestatus mainlog notification statusdata

information/cli: Icinga application loader (version: r2.5.4-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: myhost
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 2 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 16 NotificationCommands.
information/ConfigItem: Instantiated 21988 Notifications.
information/ConfigItem: Instantiated 222 CheckCommands.
information/ConfigItem: Instantiated 10 Downtimes.
information/ConfigItem: Instantiated 840 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 345 HostGroups.
information/ConfigItem: Instantiated 183 Comments.
information/ConfigItem: Instantiated 26 UserGroups.
information/ConfigItem: Instantiated 27 Users.
information/ConfigItem: Instantiated 10155 Services.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 ServiceGroup.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 LivestatusListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 StatusDataWriter.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

Please advise what else I can test/carry out to further diagnose.
I carried out the \#development instructions got gdb, etc, etc, however running under gdb it works fine (again I suspect because it's running in foreground).

---

**Relations**:

* relates [#12667](https://dev.icinga.com/issues/12667)

**Comment by dnsmichi** [comment]
I think it is related to #5148 and #4910. I'm closing here since it is an old issue, and not fully debugged. Might have resolved itself already.
