### ISSUE TITLE
[dev.icinga.com #13251] api/packages/_api/stagename/include.conf might get removed over restarts?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4797]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13251

**Created by mfriedrich on 2016-11-18 15:22:44 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-12-07 22:40:15 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

This is a strange behaviour where we should ensure that the file is there (and explicitly thrown an error if not). I'm not able to reproduce it locally but it happened once in a while.

Background: This might be a reason for missing downtimes/comments created at runtime. If the include.conf file is missing those are not included anymore on a restart.

**Comment by dnsmichi** [comment]
Duplicates #3668.
