### ISSUE TITLE
[dev.icinga.com #13323] Cluster syncs API deleted objects from a node which down and was not aware of the deletion

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4808]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13323

**Created by geds on 2016-11-24 16:06:25 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-29 08:17:33 +00:00 (in Redmine)_

    Icinga Version: v2.5.4-206-gb028ff2
    Backport?: Not yet backported
    Include in Changelog: 1

---

Icinga2 version: v2.5.4-206-gb028ff2 (icinga2.x86\_64 2.5.4-1.snapshot201611221649.el7.centos @ICINGA-snapshot).
Cluster resyncs everything even if some objects were deleted on one node while other was down.

To reproduce this issue:
1. Spin up vagrant with icinga2x-cluster
> git clone https://github.com/Icinga/icinga-vagrant.git
> cd icinga-vagrant/icinga2x-cluster
> vagrant up

2. Stop Icinga2 instances on both cluster servers

3. Edit /etc/icinga2/zones.conf on both 'icinga2a' and 'icinga2b' to enable config replication
> object Endpoint "icinga2a" {
> host = "192.168.33.10"
> }
> 
> object Endpoint "icinga2b" {
> host = "192.168.33.20"
> }
> 
> object Zone "master" {
> endpoints = \[ "icinga2a", "icinga2b" \]
> }
> 
> object Zone "checker" {
> }
> 
> object Zone "global-templates" {
> global = true
> }

4. Start Icinga2 on both 'icinga2a' and 'icinga2b'

5. Create a host/service via API
> curl -k -s -u "aws:$PASSWORD" -H 'Accept: application/json' -X PUT "https://192.168.33.10:5665/v1/objects/hosts/host1" -d "{ \\[templates\\]() \[ \\"generic-host\\" \], \\[attrs\\]() { \\[address\\]() \\"127.0.0.1\\", \\[check\_command\\]() \\"hostalive\\" } }"
> curl -k -s -u "aws:$PASSWORD" -H 'Accept: application/json' -X PUT "https://192.168.33.10:5665/v1/objects/services/host1!service1" -d "{ \\[attrs\\]() { \\[check\_command\\]() \\"passive\\", \\[enable\_active\_checks\\]() \\"0\\" } }"

6. Stop Icinga2 on 'icinga2b'

7. Delete an object from 'icinga2a' using API:
> curl -k -s -u "aws:$PASSWORD" -H 'Accept: application/json' -X DELETE "https://192.168.33.10:5665/v1/objects/services/host1!service1"

8. Start Icinga2 on 'icinga2b'

At this point 'service1' gets synced to Icinga2a from Icinga2b because the object was still present there while it was down

**Comment by Al2Klimov** [comment]
Hello @geds,

did you create the issue? (Unfortunately we can only guess.)

If yes, is this problem still present in v2.10.3?

Best,
AK

**Comment by dnsmichi** [comment]
Yes, that's still a problem without any solution. I'm inclined to mark this as a wontfix though after the many years.

**Comment by dnsmichi** [comment]
Closing in favor of #7136.
