### ISSUE TITLE
[dev.icinga.com #13331] Icinga2 crashes sometimes

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4810]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13331

**Created by prdatur on 2016-11-26 12:53:42 +00:00**

Assignee: _prdatur_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-02 10:02:03 +00:00 (in Redmine)_

    Icinga Version: r2.5.3-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello I have added another message to the closed Ticket [\#11061](https://dev.icinga.com/issues/11061) It is the same error. After adding the post, the ticket is still closed so I created this one to get an open one. The crashlog is attached.

**Attachments**

* [report.1480161857.482280](https://dev.icinga.com/attachments/download/3855/report.1480161857.482280) prdatur - _2016-11-26 12:53:36 +00:00_

**Comment by gunnarbeutner** [comment]
No feedback received. Feel free to submit a new bug report if this problem still occurs.
