### ISSUE TITLE
[dev.icinga.com #13341] Group members are missing in the IDO for newly-created groups

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4811]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13341

**Created by gbeutner on 2016-11-28 10:20:47 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-07 22:39:52 +00:00 (in Redmine)_

    Icinga Version: 2.5.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Steps to reproduce:

1. Create a few hosts.
2. Restart Icinga.
3. Create a new host group with "assign where true"
4. Restart Icinga.

The new group won't have any group members.

**Comment by dnsmichi** [comment]
Parent ticket for solving these problems is #6012.
