### ISSUE TITLE
[dev.icinga.com #13343] Groups which are created at runtime don't have any members

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4812]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13343

**Created by gbeutner on 2016-11-28 10:22:08 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-28 10:22:45 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Steps to reproduce:

1. Create a new group with the API
2. Check group memberships with lldb.

**Comment by Al2Klimov** [comment]
@dnsmichi Wasn't there a customer who want(ed) to pay this one? If yes, please leave a ref/XX/YYYYYY

**Comment by dnsmichi** [comment]
No, not really. Since this issue has gone stale without any further comments, I'll close here. If the problem still exists, one should create a new one.
