### ISSUE TITLE
[dev.icinga.com #13355] Show which host is running the scheduler for a check

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4814]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13355

**Created by twidhalm on 2016-11-29 15:08:50 +00:00**

Assignee: _twidhalm_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-08 00:26:05 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

I'd really like to see which Icinga 2 instance scheduled a check I can see in Icinga Web 2. Since the behaviour of "check source" changed, I miss this information.

I spoke to Eric wether this is an issue for Icinga Web 2 or Icinga 2 and he told me, Icinga Web 2 has no access to this information.

Cheers,
Thomas

**Comment by dnsmichi** [comment]
@widhalmt ping?

**Comment by dnsmichi** [comment]
No feedback, I'm leaving this here for suggestions and PRs. Should be easy to implement inside the CheckResult class following check_source. Might need checks for older versions which do not provide the new attribute.

**Comment by widhalmt** [comment]
* scheduler
* scheduling_endpoint
* scheduling_node

Sorry I didn't give feedback. I might not be creative enough for creating new attributes.
