### ISSUE TITLE
[dev.icinga.com #13361] Rotate Icinga log files on Windows

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4815]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13361

**Created by gbeutner on 2016-11-30 09:23:19 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-30 09:23:43 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

**Comment by MaBauMeBad** [comment]
+1

**Comment by carraroj** [comment]
ref/NC/722507

**Comment by julianbrost** [comment]
Would logging to Windows Event Log be an alternative to rolling our own log rotation? (see #8710)

**Comment by Al2Klimov** [comment]
I consider "Prefer feature X or Y?" another construction area than "Does feature X work as expected?".

**Comment by phil-or** [comment]
Any news on this issue?
We still disabled logging, otherwise the disk space would fill up.
