### ISSUE TITLE
[dev.icinga.com #13373] Add an upsert mode for post/put API queries

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4817]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13373

**Created by mfriedrich on 2016-11-30 14:51:08 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-30 14:51:08 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Details to be added by Michael Medin ;-)

**Comment by Crunsher** [comment]
No details in about two years ^_^ I'm closing this.
