### ISSUE TITLE
[dev.icinga.com #13389] bash command output available in configuration files

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4819]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13389

**Created by pooh on 2016-12-02 18:15:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-06 18:37:28 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

I'd like to have a function which I can call in a configuration file to get the output of a bash command.

Specific example: I define hosts by their FQDN; I'd like to be able to create a template which says "define 'address' if there is an IPv4 A record for that FQDN" and "define 'address6' if there is an IPv6 AAAA record for that FQDN", so that it's automatic for all hosts (and also updates on reloads if a record gets added or removed, for example).

I'm sure there are other use cases, but this is what I was trying to do when I found out there's no "system()" call, or backtick notation, in icinga2 configuration files.

**Comment by dnsmichi** [comment]
There's no progress here, nor would we want to implement it. Closed.
