### ISSUE TITLE
[dev.icinga.com #13397] OpenSSL 1.1 support for Windows

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4822]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13397

**Created by TheFlyingCorpse on 2016-12-03 20:37:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-03 21:47:22 +00:00 (in Redmine)_

    Icinga Version: 2.5.4-master
    Backport?: Not yet backported
    Include in Changelog: 1

---

Fix the CMakeLists.txt to properly include the correct DLL's for OpenSSL 1.1 when it is present for Windows packages.

Patch incoming, verifying for both 32bit and 64bit.

**Attachments**

* [0004-Use-OpenSSL-1.1-binaries-on-Windows-if-available.patch](https://dev.icinga.com/attachments/download/3867/0004-Use-OpenSSL-1.1-binaries-on-Windows-if-available.patch) TheFlyingCorpse - _2016-12-03 21:44:19 +00:00_

**Comment by Crunsher** [comment]
I completly overlooked this issues content and did not notice @TheFlyingCorpse already had a PR for it.
Sorry ;_;

My solution only differs by checking the openssl minor version instead of the file paths
