### ISSUE TITLE
[dev.icinga.com #13405] Prepare icingacli-businessprocess for next release

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4826]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13405

**Created by dgoetz on 2016-12-05 12:40:00 +00:00**

Assignee: _dgoetz_
Status: _Assigned_ 
Target Version: _2.7.0_
Last Update: _2016-12-05 15:23:46 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

For next release syntax has changed, additional parameter statetype was added and for itl a workaround for parameter order has to be introduced. Patch will be up shortly after, please do apply after next release of businessprocess module.

**Changesets**

_2016-12-05 12:40:11 +00:00_ by _dgoetz_ c0feff32a4f489da8796f698f116294f3928ec8b

    addresses changes in businessprocess module
    
    changes syntax
    adds statetype
    adds parameter ordering
    
    refs #13405

**Comment by gunnarbeutner** [comment]
@Crunsher: Can you check whether we can merge this? :)

**Comment by dnsmichi** [comment]
According to @Thomas-Gelf the old syntax is still supported by BP 2.0.0 but it might be worthwhile to test whether the updated CheckCommand still works or not.

**Comment by dnsmichi** [comment]
Hm, the patch uses spaces instead of tabs. Please keep that in mind when sending in patches.

Some vim magic... http://stackoverflow.com/questions/9104706/how-can-i-convert-spaces-to-tabs-in-vim-or-linux

```
:set ts=8
:set noet

<mark the lines in visual mode - shift+V, cursor ...>

:'<,'>retab!
```

@dgoetz I've rebased the branch into a new feature branch **feature/itl-icingacli-bp-4826**. I'd like to link to the BP docs for the cli commands, but unfortunately this is not yet there @Thomas-Gelf - can you please help? :)

https://github.com/Icinga/icingaweb2-module-businessprocess#monitoring

**Comment by dnsmichi** [comment]
`--color` does not make much sense. One thing which is tricky - if `/etc/icingaweb2` is not world readable, you can't execute the cli command as icinga user. Any suggestions on that @dgoetz ?

**Comment by dnsmichi** [comment]
A sample config is prepared here, which works for both variants of the CheckCommand. That one introduces the permission issue on CentOS 7.

https://github.com/Icinga/icinga-vagrant/tree/feature/bp-cli

**Comment by dgoetz** [comment]
Forget to answer, sorry about that.
I simply add the icinga user to the icingaweb2 group to get permissions right for running the check.

**Comment by dnsmichi** [comment]
Thanks @dgoetz - I've talked with @Thomas-Gelf the other day and cleared that up too. After this has been adopted I'll prepare a PR for the BP docs too.

**Comment by dnsmichi** [comment]
Merged the Icinga 2 related changes, I'll deal with the rest in separate issues: Icinga/icingaweb2-module-businessprocess#120 and icinga/icinga-vagrant#39.
