### ISSUE TITLE
[dev.icinga.com #13417] Config validation should check the schema version

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4830]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13417

**Created by mfrosch on 2016-12-06 09:26:01 +00:00**

Assignee: _mfrosch_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 08:18:47 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

When running Icinga config validation, we should actually check if the IDO connection works (not sure if this is tested now).

But especially we should check if the database schema is correct.

Currently this only bails out on the daemon start, and not on validation.

**Comment by dnsmichi** [comment]
Continue in #4440.
