### ISSUE TITLE
[dev.icinga.com #13429] MSI Installer Window Issue

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4834]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13429

**Created by dokon on 2016-12-06 16:11:43 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-06 16:11:43 +00:00 (in Redmine)_

    Icinga Version: Icinga2-v2.5.4-x86_64.msi
    Backport?: Not yet backported
    Include in Changelog: 1

---

MSI Installer Package Window is not properly resized and Buttons are out of the visual area.

Might be a Virtualbox Graphics Driver Problem/Issue.
Have no real Windows Server Box to check if it happens there as well.

Windows Server R2 2012 Evaluation Version.

**Attachments**

* [Bildschirmfoto vom 2016-12-06 16-40-04.png](https://dev.icinga.com/attachments/download/3871/Bildschirmfoto%20vom%202016-12-06%2016-40-04.png) dokon - _2016-12-06 16:10:54 +00:00_

**Comment by dnsmichi** [comment]
Closing in favour of #4959.
