### ISSUE TITLE
[dev.icinga.com #13453] EC/ECDSA elliptic curve not usable on Debian jessie

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4844]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13453

**Created by mfrosch on 2016-12-07 10:25:50 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-12 13:04:31 +00:00 (in Redmine)_

    Icinga Version: 2.6.0-dev
    Backport?: Not yet backported
    Include in Changelog: 1

---

Tested the cipher\_list feature on a Debian 8.

When you set a cipher list like this:

    cipher_list = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"

Icinga 2 can't connect to each other:

    2016-12-07 10:22:14 +0000] warning/TlsStream: OpenSSL error: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
    [2016-12-07 10:22:14 +0000] critical/ApiListener: Client TLS handshake failed (from [192.168.33.12]:59739)

Apache httpd on the same system uses ECDSA with my browser.

When I use an intermediate list like follows, the first non-EC cipher gets used.

    cipher_list = "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"

From Wireshark:

    Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)

---

**Relations**:

* relates [#13453](https://dev.icinga.com/issues/13453)

**Comment by Crunsher** [comment]
Closed via #5555
