### ISSUE TITLE
[dev.icinga.com #13469] Command escape is broken for Windows

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4849]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13469

**Created by jflach on 2016-12-08 10:11:02 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 10:11:02 +00:00 (in Redmine)_

    Icinga Version: 2.6.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Windows has special needs when it comes to escaping:

For a Programm to receive "foo bar" (with ") the correct shell escaped string would be <sup>"foo</sup> bar^", yet icinga creates the string "\\"foo bar\\"".

**Comment by Al2Klimov** [comment]
Note:

I asked @LordHepipud to evaluate what's the right escaping algo.

My guess: Put a `^` before every character.

**Comment by Al2Klimov** [comment]
Note:

`CreateProcess()` seems not to parse the command line string, but to call the exe with that string and let it parse it by itself.

See http://www.daviddeley.com/autohotkey/parameters/parameters.htm

**Comment by Al2Klimov** [comment]
And here's how the exe parses the string: https://docs.microsoft.com/de-de/cpp/cpp/parsing-cpp-command-line-arguments?view=vs-2019
