### ISSUE TITLE
[dev.icinga.com #13489] Downtime end notified when downtime has been cancelled before starting

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4850]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13489

**Created by mfrosch on 2016-12-08 15:50:53 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-09 10:31:07 +00:00 (in Redmine)_

    Icinga Version: 2.6.0-dev
    Backport?: Not yet backported
    Include in Changelog: 1

---

In addition to [\#12549](https://dev.icinga.com/issues/12549)

When I cancel a downtime that starts in the future, a DOWNTIMEEND notification is send.

    [2016-12-08 15:46:22] [test] [test-simple!test-critical] [DOWNTIMEEND] [CRITICAL] CRITICAL: This check is always CRITICAL.
     Author: icingaadmin
     Comment: TEST

Also not sure if the actual dates should be filled for a downtime that never started:

        downtimehistory_id: 2
               instance_id: 1
             downtime_type: 1
                 object_id: 235
                entry_time: 2016-12-08 15:42:23
               author_name: icingaadmin
              comment_data: TEST
      internal_downtime_id: 2
           triggered_by_id: 0
                  is_fixed: 1
                  duration: 0
      scheduled_start_time: 2016-12-09 15:42:12
        scheduled_end_time: 2016-12-09 16:42:12
               was_started: 0
         actual_start_time: 2016-12-09 15:42:12
    actual_start_time_usec: 0
           actual_end_time: 2016-12-08 15:46:22
      actual_end_time_usec: 790323
             was_cancelled: 1
              is_in_effect: 0
              trigger_time: NULL
                      name: test-simple!test-critical!master1-1481211743-1
        endpoint_object_id: 174

---

**Relations**:

* relates [#12549](https://dev.icinga.com/issues/12549)

**Comment by dnsmichi** [comment]
There's no difference for the notification type here. As said, if this comes into SLA play, ignore everything which is `was_cancelled=1`.
