### ISSUE TITLE
[dev.icinga.com #13493] Add Array#match method

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4852]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13493

**Created by mfriedrich on 2016-12-09 12:05:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-09 12:05:23 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Similar to what you can achieve with a custom global function, but marked as safe and built-in (therefore usable in API filters in sandbox mode).

    globals.array_match = function(pattern, arr) {
      for (el in arr) {
        // type safety for strings
        if (typeof(el) != String) {
          continue
        }

        if (match(pattern, el)) {
          return true
        }
      }

      return false
    }

**Changesets**

_2016-12-12 12:44:49 +00:00_ by _mfriedrich_ 1b03484e4a763d7dd7b50c7599fbf253e25c21e5

    Implement Array#match
    
    refs #13493

**Comment by gunnarbeutner** [comment]
Shouldn't we call this 'match_any'?

**Comment by dnsmichi** [comment]
I'm still undecided whether we really should add it. I'm thinking of the discussion we had a while ago to allow user defined function being marked as safe for the API calls.

If we call it `match_any` should it accept only arrays or dictionaries as well?

**Comment by gunnarbeutner** [comment]
Moved to #5263.
