### ISSUE TITLE
[dev.icinga.com #13497] ido mysql getting overloaded

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4853]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13497

**Created by azhaguprabu on 2016-12-09 13:36:03 +00:00**

Assignee: _azhaguprabu_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-09 13:43:21 +00:00 (in Redmine)_

    Icinga Version: 2.4.10
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

we have below mentioned number of object we configured for monitoring through icinga2 version v2.4.10

information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 13 Endpoints.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 92 CheckCommands.
information/ConfigItem: Instantiated 191 Comments.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 42695 Notifications.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1242 Hosts.
information/ConfigItem: Instantiated 117 HostGroups.
information/ConfigItem: Instantiated 21 Users.
information/ConfigItem: Instantiated 15 UserGroups.
information/ConfigItem: Instantiated 59 Downtimes.
information/ConfigItem: Instantiated 41406 Services.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 CompatLogger.
information/ConfigItem: Instantiated 1 StatusDataWriter.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 NotificationComponent.

and installed icingaweb2 web on the same server in apache application.

IDO mysql getting more load and lot update the mysql db

it keep on increasing the query count, if i stop the httpd (apache) service the count will be reduce after 10min.

and also restarting time will take around 7min

------------------------------------------------------------------------

solution need to find.

*) please recommented object size icinga2 will handle and specification of the MySQL db.

*) need to speed up the database cleanup process.
*) need to start and restart process on icinga2 service.

**Comment by dnsmichi** [comment]
No feedback in a reasonable amount of time. Please re-test with 2.6.2 and report back, we might then reopen the issue.
