### ISSUE TITLE
[dev.icinga.com #13503] improve documentation of InfluxDbWriter when used in a distributed scenario

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4855]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13503

**Created by lesinigo on 2016-12-09 15:53:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-09 15:53:51 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

We found ourselves asking which Icinga process can / will write data to InfluxDB in a distributed monitoring setup:
- if I configure InfluxDbWriter on a client/satellite node, will it send data to InfluxDB for checks that are scheduled from another node (Top/Down Command Endpoint)?
- still a client/satellite node, but will it send data for checks that it is scheduling by itself as a result of Top/Down Config Sync?
- if I configure InfluxDbWriter on a master node, will it send data to InfluxDB for checks that it is scheduling for execution on other nodes (Top/Down Command Endpoint)?
- still a master, but checks are sent down through Config Sync and the master is just receiving results: will it write those to InfluxDb?

Documentation should be improved to explicitly state if InfluxDbWriter sends out data about all checks that "happen to flow" through that Icinga instance, or just the ones that are being scheduled on that specific instance, or whatever.

I didn't check documentation for similar plugins (eg. GraphiteWriter) but I guess the same questions would apply there.

**Comment by dnsmichi** [comment]
I'm partially addressing this with a PR, for the rest I kindly invite you to write a howto over at https://community.icinga.com
