### ISSUE TITLE
[dev.icinga.com #13507] ApiListener perfdata format is different from perfdata of other objects in /v1/status

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4857]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13507

**Created by lesinigo on 2016-12-10 00:53:06 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-10 00:53:06 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Querying `/v1/status` I get a bunch of objects in "results" and most of them follow this scheme *<span class="brevity for omitted fields many"></span>*:

    "name": "IdoPgsqlConnection",
    "perfdata": [
        {
            "counter": false,
            "crit": null,
            "label": "idopgsqlconnection_ido-pgsql_queries_rate",
            "max": null,
            "min": null,
            "type": "PerfdataValue",
            "unit": "",
            "value": 3.2,
            "warn": null
        }
    ]

The only exception I've seen on the particular Icinga2 instance I'm playing with is the ApiListener object which has perfdata in a different format, actually a single string for each key/value pair:

    "name": "ApiListener",
    "perfdata": [
        "'api_num_conn_endpoints'=5",
        "'api_num_endpoints'=5",
        "'api_num_not_conn_endpoints'=0"
    ]

I'm not 100% sure, but shouldn't it be desirable / enforced to have the same scheme for all objects, to help keep consumers of the API simple? If so, ApiListener should look something like this:

    "name": "ApiListener",
    "perfdata": [
        {
            "counter": false,
            "crit": null,
            "label": "apilistener-api_num_conn_endpoints",
            "max": null,
            "min": null,
            "type": "PerfdataValue",
            "unit": "",
            "value": 5,
            "warn": null
        }
    ]

**Comment by dnsmichi** [comment]
Note: We cannot link against libicinga/PerfdataValue from libremote. Moving the PerfdataValue class into libbase might cause trouble with the customvarobject inclusion in perfdatavalue.ti.

**Comment by dnsmichi** [comment]
This has been corrected and fixed with 2.7.
