### ISSUE TITLE
[dev.icinga.com #13509] CPU overload on each "service icinga2 reload"

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4858]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13509

**Created by ralph_b on 2016-12-10 09:38:14 +00:00**

Assignee: _ralph_b_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-14 10:18:17 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

why does icinga2 launch all service checks at once, when a "service icinga2 reload" is applyied?.

In our case there are 3100 service checks which are fired at once by icinga2, so a 16 CPUs box get in trouble with the load and some checks run into timeouts.

Tasks: 1072 total, 6 running, 1066 sleeping, 0 stopped, 0 zombie
Cpu(s): 5.6%us, 28.1%sy, 62.4%ni, 3.0%id, 0.3%wa, 0.0%hi, 0.6%si, 0.0%st
Mem: 16332300k total, 14051692k used, 2280608k free, 286320k buffers
Swap: 7872508k total, 175680k used, 7696828k free, 6310496k cached

PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
16931 icinga 35 15 6626m 66m 12m S 120.4 0.4 0:29.18 icinga2
17225 postgres 20 0 320m 134m 131m S 43.6 0.8 0:04.59 postmaster
27003 apache 20 0 495m 24m 5064 S 6.9 0.2 9:44.87 httpd
25061 postgres 20 0 321m 26m 22m S 6.6 0.2 0:19.78 postmaster
12270 apache 20 0 497m 26m 5056 S 5.6 0.2 10:21.18 httpd
19635 icinga 39 19 151m 12m 2192 D 5.6 0.1 0:00.17 check\_oracle\_he
19561 icinga 39 19 151m 12m 2196 D 5.3 0.1 0:00.18 check\_oracle\_he
14634 apache 20 0 490m 19m 5056 S 4.9 0.1 0:43.44 httpd
23921 apache 20 0 494m 23m 5064 S 4.9 0.2 1:56.94 httpd
31582 apache 20 0 494m 23m 5056 S 4.9 0.2 1:44.58 httpd
14315 apache 20 0 499m 28m 5044 S 4.6 0.2 0:42.23 httpd
19629 icinga 39 19 151m 12m 2192 D 4.6 0.1 0:00.14 check\_oracle\_he
19657 icinga 39 19 151m 12m 2192 D 4.6 0.1 0:00.14 check\_oracle\_he
25053 apache 20 0 499m 28m 5056 S 4.6 0.2 1:56.98 httpd
19448 icinga 39 19 151m 12m 2196 D 3.9 0.1 0:00.16 check\_oracle\_he
19529 icinga 39 19 151m 12m 2192 D 3.9 0.1 0:00.13 check\_oracle\_he
19582 icinga 39 19 151m 12m 2192 D 3.3 0.1 0:00.11 check\_oracle\_he
19691 icinga 39 19 151m 12m 2196 D 3.3 0.1 0:00.10 check\_oracle\_he
19692 icinga 39 19 151m 12m 2196 D 3.3 0.1 0:00.10 check\_oracle\_he
19706 icinga 39 19 151m 12m 2192 D 3.3 0.1 0:00.10 check\_oracle\_he
19344 icinga 39 19 151m 12m 2252 S 3.0 0.1 0:00.16 check\_oracle\_he
19556 icinga 39 19 151m 12m 2192 D 3.0 0.1 0:00.10 check\_oracle\_he
19610 icinga 39 19 151m 12m 2192 D 3.0 0.1 0:00.09 check\_oracle\_he
19650 icinga 39 19 151m 12m 2192 D 3.0 0.1 0:00.09 check\_oracle\_he
69 root 20 0 0 0 0 S 2.6 0.0 3:01.92 events/2
19368 icinga 39 19 151m 12m 2196 D 2.6 0.1 0:00.14 check\_oracle\_he
19559 icinga 39 19 151m 12m 2192 D 2.6 0.1 0:00.10 check\_oracle\_he
19638 icinga 39 19 151m 12m 2192 D 2.6 0.1 0:00.08 check\_oracle\_he
19328 icinga 39 19 151m 12m 2196 D 2.3 0.1 0:00.14 check\_oracle\_he
19333 icinga 39 19 151m 12m 2192 D 2.3 0.1 0:00.14 check\_oracle\_he
19489 icinga 39 19 151m 12m 2196 D 2.3 0.1 0:00.09 check\_oracle\_he
19528 icinga 39 19 151m 12m 2192 D 2.3 0.1 0:00.08 check\_oracle\_he
19540 icinga 39 19 151m 12m 2192 D 2.3 0.1 0:00.09 check\_oracle\_he
19581 icinga 39 19 151m 12m 2196 D 2.3 0.1 0:00.08 check\_oracle\_he
67 root 20 0 0 0 0 S 2.0 0.0 12:56.41 events/0
73 root 20 0 0 0 0 S 2.0 0.0 3:27.92 events/6
19316 icinga 39 19 151m 12m 2196 D 2.0 0.1 0:00.14 check\_oracle\_he
19322 icinga 39 19 151m 12m 2192 D 2.0 0.1 0:00.14 check\_oracle\_he
19334 icinga 39 19 151m 12m 2192 D 2.0 0.1 0:00.13 check\_oracle\_he
16305 root 20 0 15952 2128 920 R 1.6 0.0 0:00.80 top
19256 icinga 39 19 151m 12m 2192 D 1.6 0.1 0:00.14 check\_oracle\_he
19266 icinga 39 19 151m 12m 2192 D 1.6 0.1 0:00.14 check\_oracle\_he
19294 icinga 39 19 151m 12m 2192 D 1.6 0.1 0:00.14 check\_oracle\_he
19298 icinga 39 19 151m 12m 2192 D 1.6 0.1 0:00.14 check\_oracle\_he
19301 icinga 39 19 151m 12m 2196 D 1.6 0.1 0:00.14 check\_oracle\_he
19306 icinga 39 19 151m 12m 2196 D 1.6 0.1 0:00.14 check\_oracle\_he
19318 icinga 39 19 151m 12m 2196 D 1.6 0.1 0:00.12 check\_oracle\_he
19410 icinga 39 19 151m 12m 2192 D 1.6 0.1 0:00.08 check\_oracle\_he
19435 icinga 39 19 151m 12m 2192 D 1.6 0.1 0:00.09 check\_oracle\_he
19471 icinga 39 19 151m 12m 2192 D 1.6 0.1 0:00.08 check\_oracle\_he
31784 root 20 0 10.0g 1.3g 6068 S 1.6 8.5 42:20.39 java
17979 icinga 39 19 153m 12m 2272 S 1.3 0.1 0:00.17 check\_oracle\_he

and so on...

icinga2 - The Icinga 2 network monitoring daemon (version: v2.5.4)

Copyright © 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later &lt;http://gnu.org/licenses/gpl2.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
Installation root: /usr
Sysconf directory: /etc
Run directory: /var/run
Local state directory: /var
Package data directory: /usr/share/icinga2
State path: /var/lib/icinga2/icinga2.state
Modified attributes path: /var/lib/icinga2/modified-attributes.conf
Objects path: /var/cache/icinga2/icinga2.debug
Vars path: /var/cache/icinga2/icinga2.vars
PID path: /var/run/icinga2/icinga2.pid

System information:
Platform: Red Hat Enterprise Linux Server
Platform version: 6.7 (Santiago)
Kernel: Linux
Kernel version: 2.6.32-573.18.1.el6.x86\_64
Architecture: x86\_64

Build information:
Compiler: GNU 4.8.2
Build host: 10525b1d9830

**Attachments**

* [10-12-2016 10-28-20.png](https://dev.icinga.com/attachments/download/3903/10-12-2016%2010-28-20.png) ralph_b - _2016-12-10 09:33:48 +00:00_
* [output.txt](https://dev.icinga.com/attachments/download/3915/output.txt) ralph_b - _2016-12-14 10:16:34 +00:00_

**Comment by dnsmichi** [comment]
We've changed certain things in 2.6 to not fire those checks immediately.
