### ISSUE TITLE
[dev.icinga.com #13521] ApiLister, option for key exchange with DH, ECDH

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4863]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13521

**Created by kobmaki on 2016-12-11 18:18:43 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-11 18:18:43 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

The ApiListener doesn't support key exchange with DH (Diffie-Hellman) nor ECDH (Elliptic curve Diffie-Hellman).

Look at the corresponding issue https://dev.icinga.com/issues/13453

Possible keywords in the ApiListener to set the used DH file and the ECDH file could be:

    object ApiListener "api" {
      ...
      dhparam_path = SysconfDir + "/icinga2/pki/" + NodeName + ".dhparam.pem"
      ecparam_path = SysconfDir + "/icinga2/pki/" + NodeName + ".ecparam.pem"
      ...
     }

Creating the files:

    cd `icinga2  variable get SysconfDir`/icinga2/pki

Creating a dhparam key with 2048 length:

    openssl dhparam -out `icinga2 variable get Nodename`.dhparam.pem 2048

Creating the ecparam pem file:

    openssl ecparam -name secp256k1 -out `icinga2 variable get Nodename`.ecparam.pem

The ec-param command is *not usable* and is only used as an example.

---

**Relations**:

* relates [#13453](https://dev.icinga.com/issues/13453)

**Comment by dnsmichi** [comment]
Won't be added anytime soon.
