### ISSUE TITLE
[dev.icinga.com #13549] Missing function definition in PostgreSQL Db Schema Upgrade Script

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4864]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13549

**Created by greatexpectations on 2016-12-13 15:11:32 +00:00**

Assignee: _elippmann_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-12-16 13:01:00 +00:00 (in Redmine)_

    Icinga Version: 2.6.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

after updating Icinga2 to version 2.6.0 today, I found that the PostgreSQL log file was being spammed with this message:

    SELECT CASE WHEN (CASE WHEN ((programstatus.status_update_time) < '1970-01-03 00:00:00+00'::timestamp with time zone) THEN 0 ELSE UNIX_TIMESTAMP((programstatus.status_update_time)) END + 60 > CASE WHEN ((NOW()) < '1970-01-03 00:00:00+00'::timestamp with time zone) THEN 0 ELSE UNIX_TIMESTAMP((NOW())) END) THEN 1 ELSE 0 END AS is_currently_running FROM icinga_programstatus AS programstatus ORDER BY programstatus_id DESC

It seems that after running the DDL script for updating the database schema for 2.6.0, my database is missing a definition of the unix\_timestamp() function that accepts a "timestamp with time zone" parameter (which is the data type returned by the NOW () function). The script drops the function, but then creates a unix\_timestamp() function that accepts a "timestamp" (without time zone) parameter:

    DROP FUNCTION IF EXISTS unix_timestamp(timestamp WITH TIME ZONE);
    CREATE OR REPLACE FUNCTION unix_timestamp(timestamp) RETURNS bigint AS '
      SELECT CAST(EXTRACT(EPOCH FROM $1) AS bigint) AS result;
    ' LANGUAGE sql;

Since I have no idea whether or not the correct function variant existed before the update or whether or not the variant with a timestamp (without time zone) parameter is actually being used, I manually defined a additional function, like this:

    CREATE OR REPLACE FUNCTION unix_timestamp(timestamp WITH TIME ZONE) RETURNS bigint AS $$
      SELECT CAST(EXTRACT(EPOCH FROM $1) AS bigint) AS result;
    $$ LANGUAGE sql;

That stopped the error messages.

Kind regards

**Attachments**

* [Bildschirmfoto 2016-12-15 um 16.15.52.jpg](https://dev.icinga.com/attachments/download/3943/Bildschirmfoto%202016-12-15%20um%2016.15.52.jpg) slith76 - _2016-12-15 15:17:30 +00:00_

**Comment by dnsmichi** [comment]
That should be fixed with #4874 and icinga/icingaweb2#2651.

**Comment by aanriot** [comment]
@dnsmichi ,

The fix works only when using:

```
FUNCTION unix_timestamp(timestamp WITH TIME ZONE).
```

So the fix in the SQL schema should also be commited, no?

We tried with icinga2 2.6.0+snapshot2016.12.13+2~jessie which does not embed any SQL patch.

Thanks!

**Comment by lippserd** [comment]
@aanriot Which version of Web 2 are you using? Web 2 caches the schema version in the user sessions. So after upgrading you have to logout and log in to Web 2.

**Comment by aanriot** [comment]
@lippserd You are right, thanks a a lot.
