### ISSUE TITLE
[dev.icinga.com #13567] SIGPIPE shutdown on config reload

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4867]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13567

**Created by Markus on 2016-12-14 14:05:27 +00:00**

Assignee: _gbeutner_
Status: _Resolved_  (closed on _2017-01-12 09:55:02 +00:00_)
Target Version: _2.6.1_
Last Update: _2017-01-12 09:55:38 +00:00 (in Redmine)_

    Icinga Version: 2.6.0-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Today we updated our icinga2 from v2.5.4 to the latest 2.6.0-1.

We have master &lt;-&gt; satellite config with one master, one satellite in a remote site and multiple clients connected.

On every config reload icinga2 does a shutdown but does not start up again. When we start icinga2 again everything works as it did with version 2.5.4. We have not made any config changes during the update.

The same happens when we do a restart (not reload!) after config changes on the satellite. Satellite becomes reload signal via API call and does a shutdown.

Any help is welcome.
Markus

------------------------------------------------------------------------

    #/etc/init.d/icinga2 checkconfig
    [ ok ] checking Icinga2 configuration.
    #
    # /etc/init.d/icinga2 reload
    [ ok ] checking Icinga2 configuration.
    [ ok ] icinga2 is running.
    [ ok ] Reloading icinga2 monitoring daemon: icinga2.

**icinga.log on master**

    [2016-12-14 14:34:47 +0100] information/Application: Got reload command: Starting new instance.
    [2016-12-14 14:34:47 +0100] information/Application: Received request to shut down.
    [2016-12-14 14:34:48 +0100] information/Application: Shutting down...
    [2016-12-14 14:34:48 +0100] information/CheckerComponent: Checker stopped.

    # /etc/init.d/icinga2 status
    [FAIL] icinga2 is not running ... failed!

**icinga.log on satellite**

    [2016-12-14 14:34:48 +0100] warning/TlsStream: TLS stream was disconnected.
    [2016-12-14 14:34:48 +0100] warning/JsonRpcConnection: API client disconnected for identity 'zipsmon2001.siepha.net'
    [2016-12-14 14:34:48 +0100] warning/ApiListener: Removing API client for endpoint 'zipsmon2001.siepha.net'. 0 API clients left.
    [2016-12-14 14:34:58 +0100] information/JsonRpcConnection: Reconnecting to API endpoint 'zipsmon2001.siepha.net' via host 'zipsmon2001.siepha.net' and port '5665'
    [2016-12-14 14:34:58 +0100] critical/TcpSocket: Invalid socket: Connection refused

**icinga.log on satellite after config change**

    [2016-12-14 13:51:47 +0100] information/ApiListener: Restarting after configuration change.
    [2016-12-14 13:51:47 +0100] information/Application: Got reload command: Starting new instance.
    [2016-12-14 13:51:48 +0100] information/Application: Received request to shut down.
    [2016-12-14 13:51:48 +0100] information/Application: Shutting down...
    [2016-12-14 13:51:48 +0100] information/CheckerComponent: Checker stopped.

**Version informations of master system:**

    icinga2 --version
    icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.0-1)

    Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
    License GPLv2+: GNU GPL version 2 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Application information:
      Installation root: /usr
      Sysconf directory: /etc
      Run directory: /run
      Local state directory: /var
      Package data directory: /usr/share/icinga2
      State path: /var/lib/icinga2/icinga2.state
      Modified attributes path: /var/lib/icinga2/modified-attributes.conf
      Objects path: /var/cache/icinga2/icinga2.debug
      Vars path: /var/cache/icinga2/icinga2.vars
      PID path: /run/icinga2/icinga2.pid

    System information:
      Platform: Debian GNU/Linux
      Platform version: 8 (jessie)
      Kernel: Linux
      Kernel version: 3.16.0-4-amd64
      Architecture: x86_64

    Build information:
      Compiler: GNU 4.9.2
      Build host: smithers

**Version informations of satellite system:**

    icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.0-1)

    Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
    License GPLv2+: GNU GPL version 2 or later 
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Application information:
      Installation root: /usr
      Sysconf directory: /etc
      Run directory: /run
      Local state directory: /var
      Package data directory: /usr/share/icinga2
      State path: /var/lib/icinga2/icinga2.state
      Modified attributes path: /var/lib/icinga2/modified-attributes.conf
      Objects path: /var/cache/icinga2/icinga2.debug
      Vars path: /var/cache/icinga2/icinga2.vars
      PID path: /run/icinga2/icinga2.pid

    System information:
      Platform: Debian GNU/Linux
      Platform version: 8 (jessie)
      Kernel: Linux
      Kernel version: 3.16.0-4-amd64
      Architecture: x86_64

    Build information:
      Compiler: GNU 4.9.2
      Build host: smithers

**Attachments**

* [strace.log](https://dev.icinga.com/attachments/download/3931/strace.log) mfrosch - _2016-12-14 16:54:57 +00:00_

**Changesets**

_2016-12-15 10:47:07 +00:00_ by _mfriedrich_ fb8f4105ad9b72b58305b79f830d5e2b9a8128f4

    Block SIGPIPE signal for check processes
    
    refs #13567

_2017-01-12 09:50:43 +00:00_ by _gbeutner_ 751ca67e0a96d3d76d51ef86e235e6f9f421b6b6

    Ignore SIGPIPE earlier in the start-up process
    
    fixes #13567

---

**Relations**:

* relates [#8900](https://dev.icinga.com/issues/8900)
* duplicates [#13567](https://dev.icinga.com/issues/13567)
* duplicates [#13567](https://dev.icinga.com/issues/13567)
* duplicates [#13567](https://dev.icinga.com/issues/13567)

**Comment by Dark-o** [comment]
Hi,
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)

on Ubuntu 14.04.5 LTS 

Since about a week I'm experiencing the same problem that is driving me crazy.

In the init script I've found:

# Block/ignore SIGPIPE inside Icinga2
# Workaround for a known bug in 2.6.0
# see https://dev.icinga.com/issues/13567#note-19
trap '' 13 # SIGPIPE
 
But the problem still there. 
Any Suggestion? 
thx.
