### ISSUE TITLE
[dev.icinga.com #13587] only notify users on recovery which have been notified before (return bug)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4872]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13587

**Created by shaunsmiley on 2016-12-14 19:31:43 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-14 19:31:43 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

A bug that I found already has been addresses has returned for me: https://dev.icinga.com/issues/7579

Here is an account of the last time it happened this morning (some data sanitized).

CRITICAL 07:38:58 \[ 1/5 \] HTTP CRITICAL: HTTP/1.1 404 Not Found - string 'Authentication' not found on ...
CRITICAL 07:39:27 \[ 2/5 \] ...
CRITICAL 07:39:58 \[ 3/5 \] ...
CRITICAL 07:40:27 \[ 4/5 \] ...
NOTIFICATION 07:40:58 \[immediate\_user\] HTTP CRITICAL: HTTP/1.1 404 Not Found - string 'Authentication' not found on ...
CRITICAL 07:40:58 \[ 1/5 \] HTTP CRITICAL: HTTP/1.1 404 Not Found - string 'Authentication'
OK 07:51:10 \[ 1/5 \] HTTP OK: HTTP/1.1 200 OK - 3021 bytes in 0.171 second response time
NOTIFICATION 07:51:10 This notification was not sent out to any contact.
NOTIFICATION 07:51:10 \[delayed\_user\] HTTP OK: HTTP/1.1 200 OK - 3021 bytes in 0.171 second response time
NOTIFICATION 07:51:10 This notification was not sent out to any contact.
NOTIFICATION 07:51:10 \[immediate\_user\] HTTP OK: HTTP/1.1 200 OK - 3021 bytes in 0.171 second response time
NOTIFICATION 07:51:10 This notification was not sent out to any contact.

Note that the delayed\_user was never sent a critical notification, but it was sent an OK notification.

Unfortunately, I'm unable to reproduce, so it seems intermittent (or rather, I haven't identified the exact conditions which caused it). I have a "check\_file\_test" check to test whether a random file exists. I can remove the file to cause it to go into alert. I tried every different way I could think of, but was unable to reproduce a notification sent out to users

**Comment by dnsmichi** [comment]
I think that is related to a recent fix in 2.6.3 and #5024. That is something we can't fix with the current backend, the schema requires such weird insert ids which may cause the incomplete data representation.
