### ISSUE TITLE
[dev.icinga.com #13635] Force host check at service state change

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4879]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13635

**Created by ybinnenweg on 2016-12-16 10:29:28 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-16 10:29:28 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

In Icinga 1 and Nagios there was a feature which would force a host check when a service changed state:
Icinga 1:
"On-demand when a service associated with the host changes state."
Source: https://docs.icinga.com/latest/en/hostchecks.html

Nagios:
"On-demand when a service associated with the host changes state."
Source: https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/hostchecks.html

I have been searching for functionality like this in Icinga 2 and couldn't find it. When I asked about it on the IRC channel, it was confirmed that this functionality is indeed not present in Icinga 2:
@
<X> by the way Y, if you're not too busy, would you mind trying to answer another question I have? In Icinga 1 (and Nagios) the behaviour for host checks included the following: "On-demand when a service associated with the host changes state." (https://docs.icinga.com/latest/en/hostchecks.html). How is this handled in Icinga 2? It doesn't seem as if the behaviour is the same, but I'm not entirely sure
<Y> X: yes, one of the weird trickery things Nagios had
<Y> unfortunatly that hasn't been implemented yet in I2
---
<Y> basically what we have to do internally is to issue an "check now" command every time a service state is bad
@

It would be great if this feature could be added to Icinga 2! :)

**Comment by dnsmichi** [comment]
You can do so by using an event handler which forces that via REST API. Since check execution is asynchronous in Icinga 2, there's no such thing with "on-demand" checks with wait times, and we're not going to change that.
