### ISSUE TITLE
[dev.icinga.com #13643] Automatic schema upgrades for RPM releases

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4880]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13643

**Created by diftraku on 2016-12-16 12:36:53 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-16 12:36:53 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Currently, when you upgrade to a newer version of Icinga2, the schema upgrades are not handled automatically and you need to do it manually. On the DPKG-based releases, dbconfig-common is used to handle these.

After upgrading the installed version, icinga2 fails to start with an error stating the schema is out of date.

**Comment by dnsmichi** [comment]
v2.7.0 will log a warning, but not prevent startup. In terms of RPMs doing automagic database upgrades - won't happen.
