### ISSUE TITLE
[dev.icinga.com #13645] API queries with lots of data causes memory leak

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4881]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13645

**Created by nicolasbigler on 2016-12-16 13:06:49 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-16 13:06:49 +00:00 (in Redmine)_

    Icinga Version: 2.6.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

We wanted to use part of https://github.com/Icinga/dashing-icinga2 for our dashboard and noticed a memory leak issue in Icinga.
API queries that return a lot of data will causes a memory leak.

One example query that is affected by this behaviour is /v1/objects/services. In our case the returned json output is about 17MB (we currently have 6000 services).

Running the following loop shows how the memory usage rises slowly over time:

    echo -e "Mem%\tVSZ"; for i in {1..1000}; do curl -k https://@localhost:5665/v1/objects/services > /dev/null 2>&1 && ps aux | grep "no-stack" | grep sl | awk '{ print $4 "%\t" $5 "KiB"; }';sleep 5; done
    Mem%    VSZ
    5.4%    1216676KiB
    5.9%    1233020KiB
    6.6%    1233020KiB
    7.4%    1234480KiB
    10.8%   1315452KiB
    10.4%   1298880KiB
    10.8%   1315452KiB
    13.0%   1364416KiB
    16.4%   1446524KiB
    16.4%   1446524KiB
    18.0%   1446524KiB
    18.1%   1446524KiB
    15.5%   1380988KiB
    15.1%   1364416KiB
    17.1%   1380988KiB
    16.7%   1364416KiB
    16.7%   1364416KiB
    17.2%   1380988KiB
    17.2%   1380988KiB
    18.6%   1380988KiB
    18.6%   1380988KiB
    19.9%   1446524KiB
    19.5%   1429952KiB
    19.9%   1446524KiB
    20.3%   1512060KiB
    20.4%   1512060KiB
    20.0%   1446524KiB
    20.3%   1446524KiB
    22.5%   1495488KiB
    23.5%   1561024KiB
    26.1%   1626560KiB
    29.1%   1692096KiB
    31.1%   1772740KiB
    31.1%   1772740KiB
    34.1%   1838276KiB
    34.1%   1838276KiB
    34.1%   1838276KiB
    34.1%   1838276KiB
    34.2%   1838276KiB
    34.2%   1838276KiB
    34.2%   1838276KiB
    34.2%   1838276KiB
    34.2%   1838276KiB
    34.2%   1838276KiB
    34.2%   1838276KiB
    34.2%   1838276KiB
    34.2%   1838276KiB
    37.1%   1903812KiB
    38.5%   1969348KiB
    38.5%   1969348KiB
    38.5%   1969348KiB
    38.5%   1969348KiB
    41.2%   2034884KiB
    41.2%   2034884KiB
    41.2%   2034884KiB
    41.2%   2034884KiB
    41.2%   2034884KiB
    41.2%   2034884KiB
    41.2%   2034884KiB
    41.2%   2034884KiB
    41.2%   2034884KiB
    41.2%   2034884KiB

At some point (between 30-60 Minutes) the OOM Killer will start to kill processes (mostly icinga2).
We were able to reproduce the error on Icinga 2.5 as well as on the latest 2.6 version.

The memory usage will also not go down after stopping the API queries and waiting a few hours. This further suggest that there is a memory leak in the API.

**Comment by yoshi314** [comment]
I am not seeing this on 2.6.1, perhaps the latest updates fixed something.

Mem%	VSZ
3.5%	2370444KiB
3.5%	2370444KiB
3.5%	2370444KiB
3.5%	2370444KiB


Can you reverify ?

**Comment by Bigluu** [comment]
We just updated to icinga 2.6.1 last night and I tested it again. The leak is still present:
```
Mem%    VSZ
6.2%    2511364KiB
8.7%    2707972KiB
11.2%   2904580KiB
11.2%   2904580KiB
13.7%   3101188KiB
16.2%   3297796KiB
16.2%   3297796KiB
16.2%   3297796KiB
18.7%   3494404KiB
21.1%   3625476KiB
22.2%   3691012KiB
24.7%   3887620KiB
24.7%   3887620KiB
27.2%   4084228KiB
29.4%   4280836KiB
29.4%   4280836KiB
29.4%   4280836KiB
29.4%   4280836KiB
29.4%   4280836KiB
29.4%   4281168KiB
31.9%   4477776KiB
```
At 31.9% OOM killed of the mysql process at which point I stopped the command.
So currently we can't use the icinga2 dashing dashboard with the Icinga2 API.

**Comment by dnsmichi** [comment]
On a related note - https://svn.boost.org/trac/boost/ticket/12818
