### ISSUE TITLE
[dev.icinga.com #13671] SLES 12 SP2 libboost_thread package requires libboost_chrono

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4885]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13671

**Created by styk on 2016-12-19 10:35:37 +00:00**

Assignee: _jflach_
Status: _Resolved_  (closed on _2017-01-09 15:40:02 +00:00_)
Target Version: _2.6.1_
Last Update: _2017-01-12 14:16:44 +00:00 (in Redmine)_

    Icinga Version: 2.6.0-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

I'm unable to install icinga2 on a fresh installed SLES 12 SP2 system due to a missing dependency. I'm using the steps described in the "Getting Started" part of the documentation.

~\# cat /etc/os-release
NAME="SLES"
VERSION="12-SP2"
VERSION\_ID="12.2"
PRETTY\_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI\_COLOR="0;32"
CPE\_NAME="cpe:/o:suse:sles:12:sp2"

~\# zypper ar http://packages.icinga.org/SUSE/ICINGA-release.repo
Adding repository 'ICINGA (stable release for SUSE 12.2)'
..............................................................................................................................................................................\[done\]
Repository 'ICINGA (stable release for SUSE 12.2)' successfully added
Enabled : Yes
Autorefresh : No
GPG Check : Yes
Priority : 99
URI : http://packages.icinga.org/SUSE/12.2/release/
<servername>:~ \# zypper ref
Repository 'SLES12-SP2-12.2-0' is up to date.
Retrieving repository 'ICINGA (stable release for SUSE 12.2)' metadata --------------------------------------------------------------------------------------------------------------------------------------------------------------------\[\\\]
File 'repomd.xml' from repository 'ICINGA (stable release for SUSE 12.2)' is signed with an unknown key 'C6E319C334410682'. Continue? \[yes/no\] (no): yes
Retrieving repository 'ICINGA (stable release for SUSE 12.2)' metadata .................................................................................................................................................................\[done\]
Building repository 'ICINGA (stable release for SUSE 12.2)' cache ......................................................................................................................................................................\[done\]
All repositories have been refreshed.

~\# zypper install icinga2
Loading repository data...
Reading installed packages...
Resolving package dependencies...
Problem: nothing provides libboost\_chrono.so.1.54.0()(64bit) needed by icinga2-bin-2.6.0-1.x86\_64
Solution 1: do not install icinga2-2.6.0-1.x86\_64
Solution 2: break icinga2-bin-2.6.0-1.x86\_64 by ignoring some of its dependencies
Choose from above solutions by number or cancel \[1/2/c\] ©:

~ \# zypper search libboost
Loading repository data...
Reading installed packages...
S | Name | Summary | Type
-~~*-------------------------------~~+-------------------------------------------~~*-------~~

| libboost\_atomic1\_54\_0 | Run-Time component of boost atomic library | package
| libboost\_date\_time1\_54\_0 | Boost::Date.Time Runtime libraries | package
| libboost\_iostreams1\_54\_0 | Boost::IOStreams Runtime Libraries | package
| libboost\_program\_options1\_54\_0 | Boost::ProgramOptions Runtime libraries | package
| libboost\_random1\_54\_0 | The Boost::Random runtime library | package
i | libboost\_regex1\_54\_0 | The Boost::Regex runtime library | package
| libboost\_signals1\_54\_0 | Boost::Signals Runtime Libraries | package
i | libboost\_system1\_54\_0 | Boost::System Runtime Libraries | package
i | libboost\_thread1\_54\_0 | Boost::Thread Runtime Libraries | package

Is there something wrong with the package?

Best regards,
Styk

**Changesets**

_2017-01-09 15:37:59 +00:00_ by _jflach_ d2e2e6117761753db298402f30954d076c121dd9

    Document SLES 12 installation requirement
    
    fixes #13671

**Comment by radioactive9** [comment]
Sorry what is the solution to this. I do not have access to SDK. I could not find the dependency or rpm anywhere online :(

**Comment by dgoetz** [comment]
Asking the question in https://community.icinga.com would be better than in two year old issue. Access to SDK should not be limited further than to the normal repositories, so you should have access.

**Comment by radioactive9** [comment]
fixed using https://software.opensuse.org/ymp/server:monitoring/SLE_12_SP2/icinga2.ymp
Thanks and sorry for opening old thread
