### ISSUE TITLE
[dev.icinga.com #13689] Mysql deadlock

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4887]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13689

**Created by Zl0 on 2016-12-19 16:23:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-19 16:23:09 +00:00 (in Redmine)_

    Icinga Version: 2.6.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Time-to-time in log this messages and monitoring does not respound in icingaweb2

    [2016-12-19 19:00:56 +0300] critical/IdoMysqlConnection: Error "Lock wait timeout exceeded; try restarting transaction" when executing query "UPDATE icinga_programstatus SET active_host_checks_enabled = '1',  ac
    tive_service_checks_enabled = '1',  daemon_mode = '1',  endpoint_name = 'master1.icinga.teka',  event_handlers_enabled = '1',  flap_detection_enabled = '1',  instance_id = 1,  is_currently_running = '1',  last_c
    ommand_check = FROM_UNIXTIME(1482163205),  notifications_enabled = '1',  passive_host_checks_enabled = '1',  passive_service_checks_enabled = '1',  process_id = '24807',  process_performance_data = '1',  program
    _start_time = FROM_UNIXTIME(1482163042),  program_version = 'r2.6.0-1',  status_update_time = FROM_UNIXTIME(1482163205) WHERE instance_id = 1;COMMIT;BEGIN;DELETE FROM icinga_runtimevariables WHERE instance_id = 
    1;INSERT INTO icinga_runtimevariables (instance_id, varname, varvalue) VALUES (1, 'total_services', '14685');INSERT INTO icinga_runtimevariables (instance_id, varname, varvalue) VALUES (1, 'total_scheduled_servi
    ces', '14685');INSERT INTO icinga_runtimevariables (instance_id, varname, varvalue) VALUES (1, 'total_hosts', '217');INSERT INTO icinga_runtimevariables (instance_id, varname, varvalue) VALUES (1, 'total_schedul
    ed_hosts', '217')"
    Context:
            (0) Reconnecting to MySQL IDO database 'ido-mysql'

    [2016-12-19 19:00:56 +0300] critical/IdoMysqlConnection: Exception during database operation: Verify that your database is operational!

**Comment by dnsmichi** [comment]
I'm not able to reproduce this with various sized test environments. Please upgrade to 2.6.3.
