### ISSUE TITLE
[dev.icinga.com #13805] Windows Agent: performance data of check_perfmon

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4896]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13805

**Created by mwe on 2016-12-28 07:18:06 +00:00**

Assignee: _jflach_
Status: _Assigned_  (closed on _2017-01-12 15:02:19 +00:00_)
Target Version: _(none)_
Last Update: _2017-01-15 18:50:18 +00:00 (in Redmine)_

    Icinga Version: 2.6.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

The fix for change described in Bug [\#10489](https://dev.icinga.com/issues/10489) breaks performance data when using graphite. Current graphite release 0.9.15 cannot deal with special characters like quotes or brackets. Skipping "perfmon" string leads to missing graphite graphs in Icingaweb2 (as you can see in attached image). Also via graphite gui its not possible to add metrics with special graphs.
Solution might be possible in two different approches:

-   change every plugin to deliver valid performance data labels
-   extend graphitewriter.cpp to escape all special chars except allowed chars

Second approach might be easier to use, since you solve to problem for all plugins with one change. graphite release 0.10.0 also has some bugfixes regading rrd paths and special chars in metric names - but there is no estimated relase date right now.

**Attachments**

* [2016-12-27 11_52_11-Icinga Web.png](https://dev.icinga.com/attachments/download/3983/2016-12-27%2011_52_11-Icinga%20Web.png) mwe - _2016-12-28 07:11:57 +00:00_

**Changesets**

_2017-01-12 14:55:26 +00:00_ by _jflach_ 7b2723a53c8a7e004aec60dcce18f1010d037fbd

    Add --perf-syntax option to check_perfmon
    
    fixes #13805

**Comment by andrewrmoore** [comment]
Also would be very interested in the --perf-syntax addition.
