### ISSUE TITLE
[dev.icinga.com #13825] Inverse Switch for snmp-interface added

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4897]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13825

**Created by weiti on 2016-12-29 11:12:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-29 11:12:27 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

As the underlying plugin is able to do inverse interface checks, the command configuration and docs aren't aware of this
feature. I added the needed config/docs and create an pull request on github:

https://github.com/Icinga/icinga2/pull/115

regards,
tim

**Comment by dnsmichi** [comment]
#115 was merged already.
