### ISSUE TITLE
[dev.icinga.com #13827] documentation for flapping

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4898]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13827

**Created by ClemensBW on 2016-12-29 15:10:49 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-03 21:03:21 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hello,

can you please add a few more documentation for the flapping option @ https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/advanced-topics?highlight-search=flapping\_threshold#check-flapping

Ref: https://github.com/Icinga/icinga2/blob/master/lib/icinga/checkable-flapping.cpp

**Attachments**

* [8-advanced-topics.md.patch](https://dev.icinga.com/attachments/download/3993/8-advanced-topics.md.patch) sru - _2017-01-02 11:38:03 +00:00_
* [flapping.png](https://dev.icinga.com/attachments/download/3995/flapping.png) sru - _2017-01-02 11:38:13 +00:00_
* [8-advanced-topics.md](https://dev.icinga.com/attachments/download/3997/8-advanced-topics.md) sru - _2017-01-02 11:39:01 +00:00_
* [flapping-m.png](https://dev.icinga.com/attachments/download/4003/flapping-m.png) sru - _2017-01-03 21:01:38 +00:00_

---

**Relations**:

* relates [#11654](https://dev.icinga.com/issues/11654)

**Comment by dnsmichi** [comment]
Will be continued in #4982.
