### ISSUE TITLE
[dev.icinga.com #13847] void Checkable::UpdateFlappingStatus(bool stateChange) not working as expected

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4899]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13847

**Created by sru on 2017-01-01 19:26:52 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2017-01-11 17:10:47 +00:00 (in Redmine)_

    Icinga Version: 2.6.0-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

icinga2 version 2.6.0-1.

In file lib/icinga/checkable-flapping.cpp line 49 shows:

            if (positive + negative > FLAPPING_INTERVAL) {
                    double pct = (positive + negative - FLAPPING_INTERVAL) / FLAPPING_INTERVAL;
                    positive -= pct * positive;
                    negative -= pct * negative;
            }

This seems to shoot in huge "jumps" in the StateChangeRate.

In the Screenshot below, exactly at 3674 seconds both values positive and negative are trimmed down to 0 but the flapping rate should still remain over the 'flapping\_threshold' of 30%.
It normally would stay at 0 but at 3829 seconds the service started flapping again.

These values have been aquired by modifying above function to log them. Excerpt:

            if (negative < 0)
                    negative = 0;

            FlappingOld= GetFlappingCurrent();

            SetFlappingLastChange(now);
            SetFlappingPositive(positive);
            SetFlappingNegative(negative);

            FlappingNew= GetFlappingCurrent();

            if (!GetEnableFlapping() || !IcingaApplication::GetInstance()->GetEnableFlapping())
                    return;
            Log(LogInformation, "Notification")
                << "Flapping counter for '" << GetName() << "'|" << stateChange << "|" << now << "|" << positive << "|" << negative << "|" << FlappingOld << "|" << FlappingNew;
    }

**Attachments**

* [FlappingGap.txt](https://dev.icinga.com/attachments/download/3989/FlappingGap.txt) sru - _2017-01-01 19:30:03 +00:00_
* [Flapping.png](https://dev.icinga.com/attachments/download/3991/Flapping.png) sru - _2017-01-01 19:30:04 +00:00_
* [checkable-flapping.cpp.patch](https://dev.icinga.com/attachments/download/3999/checkable-flapping.cpp.patch) sru - _2017-01-02 11:54:55 +00:00_
* [flapping3.txt](https://dev.icinga.com/attachments/download/4007/flapping3.txt) sru - _2017-01-06 09:11:54 +00:00_
* [flapping3.log](https://dev.icinga.com/attachments/download/4009/flapping3.log) sru - _2017-01-06 09:11:54 +00:00_

---

**Relations**:

* relates [#11654](https://dev.icinga.com/issues/11654)

**Comment by dnsmichi** [comment]
Will be continued in #4982.
