### ISSUE TITLE
[dev.icinga.com #13851] High load icinga2 master and client

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4900]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13851

**Created by balu on 2017-01-02 10:13:49 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-12 09:48:33 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

I've got Icinga2 with master-satellite (node) setup only in a small environment. There are about 26 hosts with about 300 services configured. Since 01.01.2017 01:00 am the load of 2 vms are near 100%. Unfortunately I don't know why.

Master:

    ============== GENERAL INFORMATION ==============

            Application version: v2.5.4
            Installation root: /usr
            Sysconf directory: /etc
            Run directory: /run
            Local state directory: /var
            Package data directory: /usr/share/icinga2
            State path: /var/lib/icinga2/icinga2.state
            Objects path: /var/cache/icinga2/icinga2.debug
            Vars path: /var/cache/icinga2/icinga2.vars
            PID path: /run/icinga2/icinga2.pid

    Enabled features:
            api checker command debuglog ido-pgsql mainlog notification perfdata
    Disabled features:
            compatlog gelf graphite influxdb livestatus opentsdb statusdata syslog

Node

    ============== GENERAL INFORMATION ==============

            Application version: v2.4.10
            Installation root: /usr
            Sysconf directory: /etc
            Run directory: /run
            Local state directory: /var
            Package data directory: /usr/share/icinga2
            State path: /var/lib/icinga2/icinga2.state
            Objects path: /var/cache/icinga2/icinga2.debug
            Vars path: /var/cache/icinga2/icinga2.vars
            PID path: /run/icinga2/icinga2.pid

    Enabled features:
            api checker mainlog
    Disabled features:
            command compatlog debuglog gelf graphite icingastatus livestatus notification opentsdb perfdata statusdata syslog

On both there is CentOS 7 installed (x86\_64).

What I have tested to solve this issue:

-   Update to actual version (2.6.x)
-   Enable debuglog for messages in critical and warning status
-   Reinstall all packages and reinstall on node (remove all folders and execute icinga2 wizard again)
-   Run icinga2 daemon with debug

There was no message with a hint to a configuration error or something like that. Nothing were changed on the system since 26.12.2016.

Thank you,
Ludwig

**Comment by dnsmichi** [comment]
Doesn't happen on Linux clients, and for Windows we do have one issue open.
