### ISSUE TITLE
[dev.icinga.com #13881] Registering past downtimes fail

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4905]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13881

**Created by kunsjef on 2017-01-04 18:03:19 +00:00**

Assignee: _kunsjef_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2017-01-13 09:04:04 +00:00 (in Redmine)_

    Icinga Version: r2.6.0-1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Registering past downtimes in Icingaweb2 is not supported, but there seems to be no restrictions doing this either via the External Commands or the API if I am not mistaken. Anyway this works only partly. The start of the downtime is set correctly, but the end time is disregarded, and is set to the exact time the command is run. Both External Commands and API has the same result.

Example from running the API command:

@curl -k -s -u root:icinga -H 'Accept: application/json' -X POST 'https://icinga2:5665/v1/actions/schedule-downtime?type=Host&filter=host.name==%22test-host%22' -d '{ [start\_time]() 1483225200, [end\_time]() 1483239600, [duration]() 14400, [author]() "Test", [comment]() "Test of downtime" }'

Output: {[results]([{"code":200.0,"legacy_id":2.0,"name":"test-host!icinga2-1483551785-1","status":"Successfully) scheduled downtime 'test-host!icinga2-1483551785-1' for object 'test-host'."}\]}
@

The linux timestamps for downtime end and start are both on January 1st, but the actual downtime end was set to the current time today.

**Comment by dnsmichi** [comment]
You can start with a patch in this function.
https://github.com/Icinga/icinga2/blob/master/lib/db_ido/dbevents.cpp#L577

The database column you're querying is called `actual_end_time`, taking the timestamp of the removal event (which is "now", as the signal gets called inside RemoveDowntime() by a timer).

The thing is - you'll need to find a way to decide a) this downtime was "faked" in the past setting `downtime->GetEndTime()` b) this is a "real" expired downtime which requires the current timestamp.

**Comment by iaasen** [comment]
We realize that the SLA exceptions we try to accomplish and the downtime history in Icinga is very similar but not the same. We didn't consider that background processing happening in Icinga. Knowing what the actual_end_time is actually about; we agree that this issue cannot be considered a bug. The simple solution for a hackish SLA would be to just use scheduled_end_time in stead. Only consideration left would be to allow for past downtimes to be registered in the web interface.

We also noticed that the rows in icinga_downtimehistory seems to be automatically deleted after a few days although we have not investigated where that is actually happening.

Our conclusion is to make the SLA solution in a non-hackish way separate from Icinga2 and just utilize the icinga_statehistory as a data source.

PS: I am the colleague of kunsjef

**Comment by dnsmichi** [comment]
Might be worth it to consider it when changing the IDO backend at some time, but since those `actual_*_time` columns are virtually calculated just for that backend, it is really hard to "fix" that in a certain way. I'm closing this issue as requested, and am looking forward to future backends.
