### ISSUE TITLE
[dev.icinga.com #13903] icinga2 feature disable fails on already disabled feature

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4909]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13903

**Created by bebehei on 2017-01-06 18:45:34 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-11 18:22:48 +00:00 (in Redmine)_

    Icinga Version: 2.6.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

If I disable a feature in icinga2, which is already disabled, Icinga2 fails to disable it:

    root@mon-dev:/# icinga2 feature disable graphite
    critical/cli: Cannot disable feature 'graphite'. Target file '/etc/icinga2/features-enabled/graphite.conf' does not exist.
    critical/cli: Cannot disable feature(s): graphite
    root@mon-dev:/# echo $?
    1

Wouldn't it be better to make icinga2 exit with good state and tell me "Feature already disabled"? Otherwise you would have to additionally check, if icinga2 has the feature already disabled.

**Comment by dnsmichi** [comment]
@bebehei you mean for enabling modules? I guess that @lippserd will agree on such a patch, sure :)
