### ISSUE TITLE
[dev.icinga.com #13927] Notifications for few hosts and services are not being sent

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4911]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13927

**Created by rnekkanti on 2017-01-09 22:02:58 +00:00**

Assignee: _rnekkanti_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2017-01-11 16:56:47 +00:00 (in Redmine)_

    Icinga Version: 2.6.0-2
    Backport?: Not yet backported
    Include in Changelog: 1

---

Icinga logs says it is checking the notifications for a host but it is not sending notifications later. It is sending notifications only for a few hosts and not all which are having issues.

\[2017-01-09 21:54:53 +0000\] information/ExternalCommandListener: Executing external command: \[1483998893\] SEND\_CUSTOM\_HOST\_NOTIFICATION;rnekkanti-ip-10-16-40-155;2;icingaadmin;test
\[2017-01-09 21:54:53 +0000\] information/Checkable: Checking for configured notifications for object 'rnekkanti-ip-10-16-40-155'
\[2017-01-09 21:54:53 +0000\] information/Notification: Sending 'Custom' notification 'rnekkanti-ip-10-16-40-155!notification\_elastic\_host\_downtime for user 'elastic'
\[2017-01-09 21:54:53 +0000\] information/Notification: Sending 'Custom' notification 'rnekkanti-ip-10-16-40-155!notification\_elastic\_host for user 'elastic'
\[2017-01-09 21:54:53 +0000\] information/Notification: Sending 'Custom' notification 'rnekkanti-ip-10-16-40-155!notification\_host\_rnekkanti for user 'rnekkanti'
\[2017-01-09 21:54:53 +0000\] information/ExternalCommandListener: Executing external command: \[1483998893\] SEND\_CUSTOM\_HOST\_NOTIFICATION;rnekkanti-ip-10-16-40-33;2;icingaadmin;test
\[2017-01-09 21:54:53 +0000\] information/Checkable: Checking for configured notifications for object 'rnekkanti-ip-10-16-40-33'
\[2017-01-09 21:54:53 +0000\] information/ExternalCommandListener: Executing external command: \[1483998893\] SEND\_CUSTOM\_HOST\_NOTIFICATION;rnekkanti-ip-10-16-41-141;2;icingaadmin;test
\[2017-01-09 21:54:53 +0000\] information/Checkable: Checking for configured notifications for object 'rnekkanti-ip-10-16-41-141'
\[2017-01-09 21:54:53 +0000\] information/Notification: Sending 'Custom' notification 'rnekkanti-ip-10-16-41-141!notification\_elastic\_host for user 'elastic'
\[2017-01-09 21:54:53 +0000\] information/Notification: Sending 'Custom' notification 'rnekkanti-ip-10-16-41-141!notification\_elastic\_host\_downtime for user 'elastic'
\[2017-01-09 21:54:53 +0000\] information/Notification: Sending 'Custom' notification 'rnekkanti-ip-10-16-41-141!notification\_host\_rnekkanti for user 'rnekkanti'
\[2017-01-09 21:54:53 +0000\] information/ExternalCommandListener: Executing external command: \[1483998893\] SEND\_CUSTOM\_HOST\_NOTIFICATION;rnekkanti-ip-10-16-41-89;2;icingaadmin;test
\[2017-01-09 21:54:53 +0000\] information/Checkable: Checking for configured notifications for object 'rnekkanti-ip-10-16-41-89'
\[2017-01-09 21:54:53 +0000\] information/Notification: Completed sending 'Custom' notification 'rnekkanti-ip-10-16-40-155!notification\_elastic\_host\_downtime' for checkable 'rnekkanti-ip-10-16-40-155' and user 'elastic'.
\[2017-01-09 21:54:53 +0000\] information/Notification: Completed sending 'Custom' notification 'rnekkanti-ip-10-16-40-155!notification\_elastic\_host' for checkable 'rnekkanti-ip-10-16-40-155' and user 'elastic'.
\[2017-01-09 21:54:53 +0000\] information/Notification: Completed sending 'Custom' notification 'rnekkanti-ip-10-16-41-141!notification\_elastic\_host\_downtime' for checkable 'rnekkanti-ip-10-16-41-141' and user 'elastic'.
\[2017-01-09 21:54:53 +0000\] information/Notification: Completed sending 'Custom' notification 'rnekkanti-ip-10-16-41-141!notification\_host\_rnekkanti' for checkable 'rnekkanti-ip-10-16-41-141' and user 'rnekkanti'.
\[2017-01-09 21:54:53 +0000\] information/Notification: Completed sending 'Custom' notification 'rnekkanti-ip-10-16-40-155!notification\_host\_rnekkanti' for checkable 'rnekkanti-ip-10-16-40-155' and user 'rnekkanti'.
\[2017-01-09 21:54:53 +0000\] information/Notification: Completed sending 'Custom' notification 'rnekkanti-ip-10-16-41-141!notification\_elastic\_host' for checkable 'rnekkanti-ip-10-16-41-141' and user 'elastic'.

**Comment by rnekkanti** [comment]
The issue was in HA setup the notifications feature or the other icinga2 node in the HA pair was disabled. After enabling the notifications we started receiving notifications. The issue can be closed. It would be great if we have log messages less confusing because it was telling checking notifications only. The logs had no indication of the other icinga2 node in the HA pair had notifications feature disabled.
