### ISSUE TITLE
[dev.icinga.com #13933] new function get_services(host_name)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4912]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13933

**Created by KurdBahr on 2017-01-10 16:24:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2017-01-11 17:09:28 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

To get all services that are currently assigned to a host a new function get\_services(host\_name) would be useful.
This should be more efficient than iterating over all services returned by get\_objects(Service) and checking the host\_name.

**Comment by marcofl** [comment]
+1 for this. I'm currently using something like this:
```
...
    var hostname = macro("$hostname$");
    var filter_fn = function(svc) use(hostname) {
      var max_last_check = Math.min(86400, Math.max(300, svc.max_check_attempts * svc.check_interval))
      (svc.host_name == hostname && svc.last_check < (get_time() - max_last_check))
    }

    var res = [];
    for (s in get_objects(Service).filter(filter_fn)) {
       res.add(s.__name)
    };
...
```
which looks hacky and getting all our 50k services and then filtering down to the 30 services for the host does not make much sense. We think it's basically exposing `Host::GetServices` to the script language.

**Comment by dnsmichi** [comment]
The main problem is that Host::GetServices() is located in libicinga, where libbase cannot link against. So there are specific script functions for libicinga required (correct me if I am wrong @gunnarbeutner :)).

**Comment by gunnarbeutner** [comment]
I don't see a problem with adding a script function in lib/icinga/host.cpp or lib/icinga/objectutils.cpp.

**Comment by dnsmichi** [comment]
Draft:

```
michi@mbmif ~/coding/icinga/exchange (master=) $ icinga2 console --connect 'https://root:icinga@localhost:5665/'
Icinga 2 (version: v2.7.0-73-gdfcd3ef11)
<1> => get_services(get_host(NodeName).name)
[ "5265-metrics", "disk", "disk /", "http", "icinga", "load", "pending", "ping4", "ping6", "procs", "ssh", "users" ]
```

**Comment by dnsmichi** [comment]
```
<2> => get_services(NodeName).map(x => x.name)
[ "5265-metrics", "disk", "disk /", "http", "icinga", "load", "pending", "ping4", "ping6", "procs", "ssh", "users" ]
<3> => get_services(NodeName).map(x => x.last_check_result.check_source)
[ "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de" ]
<4> => get_services(get_host(NodeName)).map(x => x.last_check_result.check_source)
[ "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de", "mbmif.int.netways.de" ]


<6> => get_service(get_host(NodeName), "ssh").__name
"mbmif.int.netways.de!ssh"
```

**Comment by marcofl** [comment]
works perfectly, thank you @dnsmichi
