### ISSUE TITLE
[dev.icinga.com #13955] Use systemd on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4915]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13955

**Created by twidhalm on 2017-01-12 09:31:04 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-12 09:35:57 +00:00 (in Redmine)_

    Icinga Version: 2.6.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

The packages from package.icinga.org still seem to use init.d scripts instead of systemd what leads to problems starting Icinga 2. This is especially true when binding Icinga 2 to a specific IP address.

Please change to systemd.

Cheers,
Thomas

---

**Relations**:

* copied_to [#14007](https://dev.icinga.com/issues/14007)

**Comment by dnsmichi** [comment]
@lazyfrosch Please have a look :)

**Comment by lazyfrosch** [comment]
I think the systemd integration for the ubuntu branches is still incorrect. (The systemd file is missing)

Debian: https://anonscm.debian.org/cgit/pkg-nagios/pkg-icinga2.git/tree/debian
Ubuntu: https://anonscm.debian.org/cgit/pkg-nagios/pkg-icinga2.git/tree/debian?h=ubuntu

File `	icinga2-common.icinga2.service` is missing...

**Comment by formorer** [comment]
Fixed in 4b87bb3c89a6695121fbc8ebd1ba730fa52e9544

**Comment by lazyfrosch** [comment]
Thanks @formorer: https://anonscm.debian.org/cgit/pkg-nagios/pkg-icinga2.git/commit/?h=ubuntu&id=4b87bb3c89a6695121fbc8ebd1ba730fa52e9544

**Comment by formorer** [comment]
51409 N + 08.02.17 Launchpad PPA   (   0) [~formorer/ubuntu/icinga/yakkety] icinga2 2.6.1-1~ppa1~yakkety2 (Accepted)
51410 N + 08.02.17 Launchpad PPA   (   0) [~formorer/ubuntu/icinga/xenial] icinga2 2.6.1-1~ppa1~xenial2 (Accepted)
51411 N + 08.02.17 Launchpad PPA   (   0) [~formorer/ubuntu/icinga/trusty] icinga2 2.6.1-1~ppa1~trusty2 (Accepted)

**Comment by sahnd** [comment]
I think there is a typo in the systemd service file:
Line 3, "yslog.target" should probably be "syslog.target".

In addition there should be a dependency for "network-online.target" or "network.target", because otherwise Icinga2 will fail to start after reboot, when api is bound to a specific IP.

**Comment by lazyfrosch** [comment]
@formorer said:

> ubuntu, fixed in: 7268104
> debian , fixed in: 16eb968
>
> I won't do a an upload for that, since we have a bugfix release next week
