### ISSUE TITLE
[dev.icinga.com #14007] No network dependency for /etc/init.d/icinga2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4921]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/14007

**Created by sahn on 2017-01-13 15:42:13 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-13 15:43:32 +00:00 (in Redmine)_

    Icinga Version: 2.6.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

the packages from package.icinga.org do not have "$network" in "Required-Start" and "Required-Stop" in the Icinga2 init-script in /etc/init.d/icinga2.
Therefore Iciniga2 will fail to start api, when it is bind to a specific IP address.

Cheers,
Sebastian

**Attachments**

* [init.d-network.patch](https://dev.icinga.com/attachments/download/4049/init.d-network.patch) sahn - _2017-01-13 15:43:16 +00:00_

---

**Relations**:

* copied_to [#14007](https://dev.icinga.com/issues/14007)

**Comment by dnsmichi** [comment]
Thanks 👍
