### ISSUE TITLE
[dev.icinga.com #14009] icinga2 merges different service checks together

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4922]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/14009

**Created by bebehei on 2017-01-13 20:47:30 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-14 13:03:19 +00:00 (in Redmine)_

    Icinga Version: 2.6.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

we use icinga2 on Ubuntu 14/16.04 with deb-packages from packages.icinga2.org.
All nodes have the same packages and are connected to an icinga2-master, which syncs the CheckCommand definitions to all client-nodes.
All checks are initiated from master.

after latest upgrade[1], some of our services started flapping in our installation.
They flap twice a minute although the check\_interval is set to 1m and the configured warn/crit-values defined on master are not reached.
Also all services are self-defined, only some with common names are flapping.

We had been able to hunt it down now:

In the deb-packages, there are default-configurations deployed to `/etc/icinga2/conf.d/`, where some common checks are defined. (`swap`, `load` ...)
We previously deleted these files with our script, which configures our client-nodes. But after the current upgrade, these files got installed by apt again.

And finally we've got services defined on the icinga2 client with name "swap" and on the icinga2 master with name "swap". Same name, but different objects.

And for some reasons, the check-result of the client-defined "swap" service gets reported back to the icinga2 master, too.
But the CheckCommand and warn/crit-values may be different.

How to reproduce:
1. Install two machines and connect them together as client/master.
2. On client edit `/etc/icinga2/conf.d/services.conf` and change the "load"-service to execute "procs"-check instead of "load"-check.
3. On master, add a service called "load" with "load"-check and apply it to your client.
4. See screenshot.

[1] Important: It's only the upgrade, I had not been able to bind it to a specific icinga2-version yet.

**Attachments**

* [Screenshot from 2017-01-13 21-39-05.png](https://dev.icinga.com/attachments/download/4051/Screenshot%20from%202017-01-13%2021-39-05.png) bebehei - _2017-01-13 20:44:14 +00:00_

---

**Relations**:

* relates [#13257](https://dev.icinga.com/issues/13257)

**Comment by dnsmichi** [comment]
I've added that to the troubleshooting docs recently: #5487. The rest will be resolved once we purge away the bottom up mode and make conf.d inclusion optional (defaults to no for client setups then).
