### ISSUE TITLE
Feature Request: allow to define timeperiod ranges by specifying a starting point and a duration

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icinga2#4935]
While the current implementation of timeperiods already allows for some flexibility, there are still some cases that are not covered. For example, one of our customers has a system on which they will perform scheduled maintenance every last sunday in a month, starting at 22:45 until 06:00 the next day (monday).

From looking at the documentation for 2.6.0, it seems this cannot be expressed using predefined Timeperiod objects.

I think it would be nice if it was possible (in addition to the current syntax) to define a timeperiod range by specifying a starting point and a duration, in order to escape the limitation of having to stay within the "00:00-24:00" boundary of a single day.

**Comment by Crunsher** [comment]
This is a very specific case, while it is possible to access the last sunday of every month easily:
`ranges = { "sunday -1" = "23:45-24:00" }` 

But I'm not sure how to get to the monday after that. Even after checking the [icinga 1 docs](https://docs.icinga.com/latest/en/objectdefinitions.html#objectdefinitions-timeperiod) I could not find an easy solution.

That being said, I don't think there is need for a different kind of Timeperiod syntax.

**Comment by dnsmichi** [comment]
Even if there is, I'd like to see a formal proposal of the configuration attributes (obviously something in `ranges`), how it could look like.

**Comment by terra-nova** [comment]
@Crunsher Yes, I am aware of the "day-of-week -1" syntax. But I disagree with the notion that Icinga does not need to consider "very specific cases". A general-purpose monitoring tool/platform should be capable of modelling such, admittedly more estoreric, scenarios as well.

@dnsmichi It is hard for me to formulate what configuration attributes should look like as I am not aware of how these things are actually implemented in the code, but here goes...

I propose to extend the syntax for ranges to allow for a syntax "<starttime>+<interval>" in addition to the currently implemented "<starttime>-<endtime>" syntax. If that were the case, one could specify my use case like this:

"sunday -1" = "22:45+435m" (or maybe even "22:45+7h15m " ;-)

**Comment by Crunsher** [comment]
@terra-nova I wasn't aware that I was calling for ignoring specific cases. I said I don't think it's worth to draft up a new syntax for timeperiods which might lead to more problematic "specific cases".

I propose a more conservative approach to this issue: Extend the syntax in a way that allows one to have more freedom over the left hand of the range.

**Comment by terra-nova** [comment]
@Crunsher No offense meant -- I was merely trying to make the point that an extension of the syntax is needed because certain time ranges cannot be represented with the current schema. So basically I don't think we have a fundamental disagreement here.

My argument boils down to this: restricting the Timeperiod to a list of "per-day" time slices makes it impossible to precisely formulate certain time ranges, and in the long run it would be desirable to be able to specify "any" time range.

**Comment by terra-nova** [comment]
I have learned of a workaround that does the trick. By simply adding the desired downtime duration to the start time, ignoring the "mental" 24:00 boundary, I can finally achieve what I was aiming for.

For example, to generate a 20 hour downtime every last friday in a month starting a 22:00, I can specify a range like this:

```
"friday -1" = "22:00-42:00"
```

which does the job (42:00 = 22:00 + 20h here, as you might have guessed).

I don't find this syntax particularly appealing, but whatever works... I guess.
