### ISSUE TITLE
V2.6.0 icinga2.exe crashes on a freshly installed windows client

### ISSUE THREAD

**Issue by chubchubsancho** [Icinga/icinga2#4937]
icinga2.exe crash on freshly installed windows client.

Faulting application name: icinga2.exe, version: 1.0.0.0, time stamp: 0x584fd71a
Faulting module name: KERNELBASE.dll, version: 6.1.7601.17514, time stamp: 0x4ce7c78c
Exception code: 0xe06d7363
Fault offset: 0x000000000000a49d
Faulting process id: 0x2818
Faulting application start time: 0x01d272fdf027a1e2
Faulting application path: C:\Program Files\ICINGA2\sbin\icinga2.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 300d9935-def1-11e6-8a61-001018ab96b6

you can find crash report file 
[report.1484903814.515000.zip](https://github.com/Icinga/icinga2/files/719029/report.1484903814.515000.zip)

**Comment by dnsmichi** [comment]
Which user is configured for the icinga2 service, and does that user have permission to write to %ProgramData%?

**Comment by chubchubsancho** [comment]
AppCrash before adding icinga2 as service. 
here you can find Screen Capture of setup wizard
![image](https://cloud.githubusercontent.com/assets/25243995/22146265/5b132bb8-df04-11e6-8587-591f86e50241.png)
![image](https://cloud.githubusercontent.com/assets/25243995/22146370/ba6bf43c-df04-11e6-97ba-b40dc22b5cfa.png)

**Comment by dnsmichi** [comment]
Permissions for `%ProgramData%\icinga2`?

**Comment by chubchubsancho** [comment]
No problem with permission conf file are writen.
![image](https://cloud.githubusercontent.com/assets/25243995/22149720/b0542f12-df15-11e6-9973-0998d631a35d.png)

**Comment by dnsmichi** [comment]
Quoting for better readability.

```
Application information:
  Application version: v2.6.0
  Installation root: C:\Program Files\ICINGA2\
  Sysconf directory: C:\ProgramData\icinga2\etc
  Run directory: C:\ProgramData\icinga2\var\run
  Local state directory: C:\ProgramData\icinga2\var
  Package data directory: C:\Program Files\ICINGA2\\share\icinga2
  State path: C:\ProgramData\icinga2\var/lib/icinga2/icinga2.state
  Modified attributes path: C:\ProgramData\icinga2\var/lib/icinga2/modified-attributes.conf
  Objects path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.debug
  Vars path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.vars
  PID path: C:\ProgramData\icinga2\var\run/icinga2/icinga2.pid

System information:
  Platform: Windows
  Platform version: 7 SP1 (Server)
  Kernel: Windows
  Kernel version: 6.1
  Architecture: x86_64

Build information:
  Compiler: MSVC 18.0.40629.0
  Build host: ICINGA-BUILD-WI
Caught unhandled SEH exception.
Current time: 2017-01-20 10:16:54 Romance Standard Time

Stacktrace:

	(0): icinga::ConfigCompilerContext::FinishObjectsFile+403
	(1): icinga::DaemonUtility::LoadConfigFiles+327
	(2): icinga::BlackAndWhitelistCommand::Run+8320
	(3): (unknown function)
	(4): (unknown function)
	(5): (unknown function)
	(6): BaseThreadInitThunk+13
	(7): RtlUserThreadStart+33
***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://dev.icinga.org/ and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***
```

**Comment by dnsmichi** [comment]
@chubchubsancho did you run the cli command for `node blacklist` somehow triggering this crash?

**Comment by smarsching** [comment]
I get exactly the same error with Icinga 2.6.2:

> Application information:
>   Application version: v2.6.2
>   Installation root: C:\Program Files\ICINGA2\
>   Sysconf directory: C:\ProgramData\icinga2\etc
>   Run directory: C:\ProgramData\icinga2\var\run
>   Local state directory: C:\ProgramData\icinga2\var
>   Package data directory: C:\Program Files\ICINGA2\\share\icinga2
>   State path: C:\ProgramData\icinga2\var/lib/icinga2/icinga2.state
>   Modified attributes path: C:\ProgramData\icinga2\var/lib/icinga2/modified-attributes.conf
>   Objects path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.debug
>   Vars path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.vars
>   PID path: C:\ProgramData\icinga2\var\run/icinga2/icinga2.pid
> 
> System information:
>   Platform: Windows
>   Platform version: 8.1 or greater (Server)
>   Kernel: Windows
>   Kernel version: 6.2
>   Architecture: x86_64
> 
> Build information:
>   Compiler: MSVC 18.0.40629.0
>   Build host: ICINGA-BUILD-WI
> Caught unhandled SEH exception.
> Current time: 2017-03-05 11:52:34 W. Europe Standard Time
> 
> Stacktrace:
> 
> 	(0): icinga::ConfigCompilerContext::FinishObjectsFile+403
> 	(1): icinga::DaemonUtility::LoadConfigFiles+327
> 	(2): icinga::BlackAndWhitelistCommand::Run+8320
> 	(3): (unknown function)
> 	(4): (unknown function)
> 	(5): (unknown function)
> 	(6): BaseThreadInitThunk+34
> 	(7): RtlUserThreadStart+52
> ***
> * This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
> * please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
> * information that might be useful in order to reproduce this problem.
> ***

This error happens everytime I run `icinga2.exe daemon --validate`, unless I run it from a privileged command prompt ("Run as administrator"). The Icinga 2 service also starts fine. Therefore, I believe that this bug is triggered when Icinga 2 tries to access a file, but does not have sufficient permissions. Of course, it should not crash in such a case, but display a proper error message instead.

**Comment by dnsmichi** [comment]
You'll need to run config validation from a privileged account, as this not only involves reading the configuration but updating cache files (such as icinga2.debug which is updated by calling `ConfigCompilerContext::FinishObjectsFile()`). The exception is ugly, but the stacktrace shows that this is coming from a different CLI command.

You're actually calling `icinga2 node blacklist ...` aren't you? (which is deprecated)

**Comment by smarsching** [comment]
@dnsmichi 
> You're actually calling `icinga2 node blacklist ...` aren't you? (which is deprecated)

I cannot speak for @chubchubsancho, but in my case I am definitely only running `icinga2 daemon --validate`. I do not know why calling this command ends up in `icinga::BlackAndWhitelistCommand::Run`.

What you say about the privileges for updating the cache makes sense to me, in particular because the exception occurs at the end (when the validation seems to have already finished successfully).

**Comment by dnsmichi** [comment]
Seen that myself today when running config validation from a non-privileged account.

Seems the stacktrace function isn't correctly returning the symbols for called functions.

```
Application information:
  Application version: v2.6.3-353-gba0498e
  Installation root: C:\Program Files (x86)\ICINGA2\
  Sysconf directory: C:\ProgramData\icinga2\etc
  Run directory: C:\ProgramData\icinga2\var\run
  Local state directory: C:\ProgramData\icinga2\var
  Package data directory: C:\Program Files (x86)\ICINGA2\\share\icinga2
  State path: C:\ProgramData\icinga2\var/lib/icinga2/icinga2.state
  Modified attributes path: C:\ProgramData\icinga2\var/lib/icinga2/modified-attributes.conf
  Objects path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.debug
  Vars path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.vars
  PID path: C:\ProgramData\icinga2\var\run/icinga2/icinga2.pid

System information:
  Platform: Windows
  Platform version: 8
  Kernel: Windows
  Kernel version: 6.2
  Architecture: x86_64

Build information:
  Compiler: MSVC 18.0.40629.0
  Build host: ICINGA-BUILD-WI
Caught unhandled SEH exception.
Current time: 2017-06-13 15:28:13 W. Europe Daylight Time

Stacktrace:

	(0): icinga::ConfigCompiler::Compile+106163
	(1): icinga::ConfigCompiler::Compile+106472
	(2): icinga::ConfigCompilerContext::FinishObjectsFile+284
	(3): icinga::DaemonUtility::LoadConfigFiles+365
	(4): icinga::BlackAndWhitelistCommand::Run+6122
	(5): (unknown function)
	(6): (unknown function)
	(7): (unknown function)
	(8): BaseThreadInitThunk+36
	(9): RtlUnicodeStringToInteger+595
	(10): RtlUnicodeStringToInteger+542
***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***

```

`icinga2 --version` needs an update too, `Platform version: 8` isn't correct for Windows 10.

**Comment by dnsmichi** [comment]
Closing in favour of the linked issue.
