### ISSUE TITLE
Problem with StatusDataWriter in v2.6.0

### ISSUE THREAD

**Issue by wiede78** [Icinga/icinga2#4938]
Hello

When we install the Version 2.6 we have always the message "Warning: Status data OUTDATED!..."
As I see the file /var/cache/icinga2/status.dat will not touch any more after the restart.
I made a downgrade to 2.5.4 again and now it works again.
So maybe a problem with the StatusDataWriter?

**Comment by dnsmichi** [comment]
Please show the output of

- `icinga2 --version`
- `icinga2 feature list`

**Comment by wiede78** [comment]
we switch back to 2.5.4, so:
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.5.4)

Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.6.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

-icinga2 feature list
Disabled features: debuglog gelf graphite influxdb livestatus opentsdb syslog
Enabled features: api checker command compatlog ido-mysql mainlog notification perfdata statusdata

**Comment by dnsmichi** [comment]
Could be related to #4867 - I'm not able to reproduce it with v2.6.0 nor the current git master.

**Comment by choonming** [comment]
@dnsmichi not sure if this is relevant to this issue but I have similar issue here. It happened when Icinga Director was issuing API calls to deploy a new config.

https://github.com/Icinga/icingaweb2-module-director/issues/747

**Comment by wiede78** [comment]
I tried it aain...run the update to 2.6 at yesterday afternoon and today morning...the same :(
# date
Thu Jan 26 08:58:24 CET 2017

 ll -rtl  /var/cache/icinga2/
total 168592
-rw-r--r-- 1 icinga icinga      3932 Aug 23 21:41 status.json
-rw------- 1 icinga icinga 122009004 Jan 25 17:02 icinga2.debug
-rw------- 1 icinga icinga      5903 Jan 25 17:02 icinga2.vars
-rw-r--r-- 1 icinga icinga  21292018 Jan 25 17:02 objects.cache
-rw-r--r-- 1 icinga icinga  29318043 Jan 25 17:11 status.dat

 ll -rtl  /var/log/icinga2/icinga2.log
-rw-r--r-- 1 icinga icingacmd 1511086 Jan 26 08:58 /var/log/icinga2/icinga2.log

**Comment by kobmaki** [comment]
What shows the output of the command:

`icinga2 object list --type=StatusDataWriter`

Should looks like:

```
Object 'status' of type 'StatusDataWriter':
  % declared in '/etc/icinga2/features-enabled/statusdata.conf', lines 9:1-9:32
  * __name = "status"
  * name = "status"
  * objects_path = "/var/cache/icinga2/objects.cache"
  * package = "_etc"
  * status_path = "/var/cache/icinga2/status.dat"
  * templates = [ "status" ]
    % = modified in '/etc/icinga2/features-enabled/statusdata.conf', lines 9:1-9:32
  * type = "StatusDataWriter"
  * update_interval = 15
  * zone = ""
```

**Comment by wiede78** [comment]
Yes, it looks the same for us. 
But by the way....we did the upgrade to 2.6.1 now and until now...it looks good.

**Comment by gunnarbeutner** [comment]
I'm unable to reproduce this with 2.6.1. Is this still an issue? :)

**Comment by choonming** [comment]
I've upgraded to 2.6.1 and seems to resolve my issues on the icinga director as well.
