### ISSUE TITLE
Counter for currently running concurrent checks

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icinga2#4939]
A counter for max concurrent checks would be nice, maybe in the built-in icinga check.

**Comment by dnsmichi** [comment]
Partially solved by adding feature stat metrics into the icinga check including the checker component for 2.7.

**Comment by dnsmichi** [comment]
@N-o-X this could be one for you as well.

**Comment by dnsmichi** [comment]
#5509

**Comment by dnsmichi** [comment]
@N-o-X this might be handy when debugging the other issue we talked about today.
