### ISSUE TITLE
missing lib, Problem: nothing provides libcrypto.so.1.0.0()(64bit) needed by icinga2-bin-2.6.0-1.x86_64

### ISSUE THREAD

**Issue by ich2016** [Icinga/icinga2#4943]
requested Library libcrypto.so.1.0.0()(64bit is not provided by rpm packages for icinga2-bin-2.6.0-1.x86_64 on sles11-sp4-custom-x86_64

http://packages.icinga.com/SUSE/11.4/release/

# zypper ar http://packages.icinga.com/SUSE/ICINGA-release.repo

# zypper lr
Refreshing service 'spacewalk'.
# | Alias                               | Name                                        | Enabled | Refresh
--+-------------------------------------+---------------------------------------------+---------+--------
1 | icinga-stable-release               | ICINGA (stable release for SUSE 11.4)       | Yes     | No <-------
2 | spacewalk:sles11-sp4-custom-x86_64  | MASTER - SLES 11.4 custom packages (x86_64) | Yes     | Yes
3 | spacewalk:sles11-sp4-pool-x86_64    | MASTER - SLES 11.4 (x86_64)                 | Yes     | Yes
4 | spacewalk:sles11-sp4-updates-x86_64 | MASTER - SLES 11.4 Updates (x86_64)         | Yes     | Yes

# zypper in icinga2-bin
Refreshing service 'spacewalk'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libcrypto.so.1.0.0()(64bit) needed by
icinga2-bin-2.6.0-1.x86_64  Solution 1: do not install
icinga2-bin-2.6.0-1.x86_64  Solution 2: break
icinga2-bin-2.6.0-1.x86_64 by ignoring some of its dependencies

**Comment by dnsmichi** [comment]
Did you enable the Security Repository for SLES11 as written in the docs?

https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/getting-started#package-repositories-sles-security

**Comment by dnsmichi** [comment]
Closed by OP request.
