### ISSUE TITLE
No hint for missing permissions in Icinga2 log for API user

### ISSUE THREAD

**Issue by darmagan** [Icinga/icinga2#4945]
Hi,

Icinga2 version: r2.6.0-1

If there are permissions given for a API-User, there are no entrys in the log that permissions for a API-Query where denied because of missing permissions. Example:
```
object ApiUser "root" {
  password = "root"

 permissions = [ "objects/query/Service" ]
}
```

```
curl -k -s -u root:root 'https://localhost:5665/v1/objects/hosts' | python -m json.tool
{
    "error": 404.0,
    "status": "No objects found."
}
```

Logs:
```
[2017-01-23 17:13:33 +0100] information/ApiListener: New client connection from [127.0.0.1]:58230 (no client certificate)
[2017-01-23 17:13:33 +0100] information/HttpServerConnection: Request: GET /v1/objects/hosts (from [127.0.0.1]:58230, user: root) <--- no hint that permissions are missing 
[2017-01-23 17:13:41 +0100] information/IdoMysqlConnection: Query queue items: 0, query rate: 4.53333/s (272/min 801/5min 801/15min);
```

Regards

**Comment by lazyfrosch** [comment]
I guess it would also make sense to present the user a 403 status when he's trying to retrieve data he is not allowed to...

**Comment by gunnarbeutner** [comment]
The problem with differentiating between "no objects found" and "you don't have permissions for the objects that were found" is that this would allow users to guess what objects exist.

For example the following set of filters could be used to guess exact names for objects:

1. match("a*", host.name) -> add another letter depending on whether you get 403 or 404
2. match("ab*", host.name)... and so on

For this reason alone I am strongly opposed to adding another HTTP status code for this. Sorry. :)

**Comment by Thomas-Gelf** [comment]
Nay to the HTTP status code. However, @darmagan asked for log entries mentioning that access has been denied. That would be very useful. But please only for attempts to access a specific object, not for any wildcard that would eventually match an "invisible" object.

**Comment by lazyfrosch** [comment]
I would like to see a 403 status code when you don't have the permission, not if you want to query a specific host.

If I want to query `objects/services` and don't have `objects/query/Service` that should be 403.

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: absolutely makes sense

**Comment by darmagan** [comment]
From the security perspective I need to distinguish between a query that failed because of a wrong permission and a query that failed 'cause of  a non existing object in the logs.

> I would like to see a 403 status code when you don't have the permission, not if you want to query a specific host.
> 
> If I want to query objects/services and don't have objects/query/Service that should be 403.

That's right for the user but I am talking about the 'admin' and the log entry not the API error entry.

**Comment by dnsmichi** [comment]
### Tests

```
object ApiUser "nix" {
  password = "nix"
}
```

```
curl -k -s -u nix:nix 'https://localhost:5665/v1/objects/services'
{"error":404.0,"status":"No objects found."}
```

```
[2017-02-08 17:04:16 +0100] information/HttpServerConnection: Request: GET /v1/objects/services (from [::1]:64871, user: nix)
[2017-02-08 17:04:16 +0100] warning/FilterUtility: Missing permission: objects/query/service
```
