### ISSUE TITLE
Comments disappear after a reload/restart

### ISSUE THREAD

**Issue by edpstiffel** [Icinga/icinga2#4946]
We have a strange problem: all persistent service and host comments disappear with a reload/restart of the icinga2-daemon.
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.0-1)
The ido-database is a PostgreSQL.

We are not sure whether this started AFTER the update to 2.6 which we did last week.

It is easy to reproduce: Insert a comment via the gui. Do a reload/restart, and the comment disappears.

We watched it also while looking at the IDO-database: at first, the comment is shown in table icinga_comments and icinga_commenthistory. After the reload, the entry in the icinga_comments table disappears.

**Comment by dnsmichi** [comment]
Do you query for a specific comment id, or is that true for any comments?

**Comment by edpstiffel** [comment]
it's true for any comments.
I just inserted a comment via classic-ui or web2. The comment was shown.
Then after reloading icinga daemon, and the comment is gone.
It is still in the icinga_commenthistory, but it has been erased from icinga_comments.

**Comment by dnsmichi** [comment]
So there is no timespan when this comment gets re-inserted?

Question aside - does the comment still exist in /var/lib/icinga2/api/packages/_api/... (recursive grep)

Standalone master or HA? If the latter, central DB IDO or anything else?

**Comment by edpstiffel** [comment]
We are HA with two nodes and with one central IDO DB.

We looked at the mentioned directory and found lots of comments there.
There are about 60 .conf-Files with comments. Now, if we issue a comment for a service that has already a file in that directory, we get an error message in the icinga2.log after a reload:

[2017-01-26 07:41:35 +0100] critical/ApiListener: Configuration file '/var/lib/icinga2/api/packages/_api/icinga2a-1448959042-1/conf.d/comments/icinga2a.gold!load!icinga2a-1485272581-1.conf' already exists.

And the comment is gone in the UI and in the icinga_comments-DB-table.

Now, we issue a comment for a new service which has no .conf-File in the mentioned api-dir.
Same behaviour: there is a new .conf -File created and a database entry and the comment is visible in the UI.

After a icinga2 reload, the file is still there, the database entry has disappeared and the comment is no longer visible in the UI.
And we get the same error message:

[2017-01-26 07:50:38 +0100] critical/ApiListener: Configuration file '/var/lib/icinga2/api/packages/_api/icinga2a-1448959042-1/conf.d/comments/icinga2a.bronze!load!icinga2a-1485413379-0.conf' already exists.

Is there a sync problem in the cluster?

**Comment by dnsmichi** [comment]
That's fairly strange since you cannot modify the name of a comment from the API/command pipe. How did you achieve that test case? I'm asking because I'd like to get to know how to reproduce the issue.

**Comment by edpstiffel** [comment]
It's our production system. We updated to 2.6 last week. But I cannot tell whether the problem started then or whether it was there before.
All I do is entering a comment to a service via Classic-UI or Icingaweb2-GUI, then do a Reload/Restart of the Icinga-Core.
The comment disappears and the mentioned error message appears in the icinga2.log.

**Comment by edpstiffel** [comment]
Is there any chance of debugging deeper in this issue?
I would be happy to provide any logs or the like.

As a side note: after the update to V2.6, our "slave" ha cluster machine does not synchronize some of the states from the master machine. All of our passive Checks are shown as Pending on the slave machine, while they are marked ok on the master machine.

Is there maybe a correlation between these issues?

**Comment by dnsmichi** [comment]
You can enable the debuglog feature and compare both ends, e.g. if both try to sync the Downtime objects and thus creating an error.

**Comment by edpstiffel** [comment]
We turned on the debuglog on both nodes.
After a restart, we got the following situation:

On the A (master) node, we get many errors like:

`[2017-02-23 09:23:31 +0100] notice/ApiListener: Received update for object: {"config":"object Comment \"icinga2a-1485163239-0\" ignore_on_error {\n\tauthor = \"DCi\"\n\tentry_time = 1485163239.412912\n\tentry_type = 1.000000\n\texpire_time = 0.000000\n\thost_name = \"xxx.firma.yyy.de\"\n\ttext = \"Serversteckbrief:  https://bla.blubb.de/x/P4IuAg\"\n\tversion = 1485163239.412965\n\tzone = \"config-ha-master\"\n}\n","modified_attributes":{},"name":"xxx.firma.yyy.de!icinga2a-1485163239-0","original_attributes":[],"type":"Comment","version":1485163239.4129650593}
[2017-02-23 09:23:31 +0100] notice/ApiListener: Replaying log: /var/lib/icinga2/api/log/1487837905
[2017-02-23 09:23:31 +0100] critical/ApiListener: Could not create object 'xxx.firma.yyy.de!icinga2a-1485163239-0':
[2017-02-23 09:23:31 +0100] critical/ApiListener: Configuration file '/var/lib/icinga2/api/packages/_api/icinga2a-1448959042-1/conf.d/comments/xxx.firma.yyy.de!icinga2a-1485163239-0.conf' already exists.
`
On the B node, we get no error at all concerning the syncing the comments/downtimes directories.

Comparing the two directories
/var/lib/icinga2/api/packages/_api/icinga2a-1448959042-1/conf.d/
/var/lib/icinga2/api/packages/_api/icinga2b-1448960224-1/conf.d/

On icinga2a, the comments directory contains 93 files, on icinga2b 31 files.
The downtime directory on icinga 2a 641 files, on icinga2b 226.

As a side note: **downtimes also vanish after a reload of icinga2a**.

Could we safely clean both the comments and downtime directory on both machines or on one machine to get a consistent state? At the moment, it is very hard to work with our production system since losing the downtimes after a reload always leads to massive mail storms.

We are still on V2.6.0.

**Comment by dnsmichi** [comment]
At first glance I'd suggest to upgrade to 2.6.2. 2.6.0 contains a bug which could lead into crashes.

The difference in the _api package storage is somewhat strange. Maybe that sources from a bug in older versions where those objects do not have been synced. 

I'd manually rsync the missing configuration objects and then check again if the problem persists.

By chance - are there any cronjobs or scripts in place which fiddle with /var/lib/icinga2/api/packages? I saw that in a different setup this week, just asking.

**Comment by edpstiffel** [comment]
Here's what we did:
- Update to V2.6.2 on both nodes
- with stopped icinga nodes cleaned the comments/downtimes directory on both machines
- created a new comment
- comment is synced in the comments dir on both nodes
- reload config on node A
- the same error message as before:

`[2017-02-23 13:12:56 +0100] critical/ApiListener: Could not create object 'icinga2a.gold!icinga2a-1487851538-0':
[2017-02-23 13:12:56 +0100] critical/ApiListener: Configuration file '/var/lib/icinga2/api/packages/_api/icinga2a-1448959042-
1/conf.d/comments/icinga2a.gold!icinga2a-1487851538-0.conf' already exists.`

and the comment is gonein the classic-ui and also in the IDO-db / icinga_comments-table.

the same happens with Downtimes after a reload:
`[2017-02-23 13:29:45 +0100] critical/ApiListener: Could not create object 'icinga2a.gold!icinga2a-1487852938-0':
[2017-02-23 13:29:45 +0100] critical/ApiListener: Configuration file '/var/lib/icinga2/api/packages/_api/icinga2a-1448959042-1/conf.d/downtimes/icinga2a.gold!icinga2a-1487852938-0.conf' already exists.`

So, the problem persists.

I am clueless.
We don't fiddle with the /var/lib/icinga2/api/packages directory.

Any further suggestions...?

**Comment by dnsmichi** [comment]
Those object creations only happen if Icinga 2 itself does not know about about the config object in memory. It then attempts to create the object, but there's a file already there. Which could be a pointer.

Can you please show me the content of the `var/lib/icinga2/api/packages/_api` directory recursively? You can obfuscate any host or service name, and I am also not interested in conf.d/{comments,downtimes} dirs.

```
find . -path '*downtimes*' -prune -o -path '*comments*' -prune -o -type f
```

**Comment by edpstiffel** [comment]
root@icinga2a:/var/lib/icinga2/api/packages/_api# find . -path '*downtimes*' -prune -o -path '*comments*' -prune -o -type f
./icinga2a-1448959042-1/conf.d/downtimes
./icinga2a-1448959042-1/conf.d/comments
./active.conf
./conf.d/comments
./include.conf
./active-stage

**Comment by dnsmichi** [comment]
Crap. I don't like it when my guesses are correct.

Mine looks like this:

```
mbmif /usr/local/icinga2/var/lib/icinga2/api/packages (master *) # find . -path '*downtimes*' -prune -o -path '*comments*' -prune -o -type f
./_api/active-stage
./_api/active.conf
./_api/include.conf
./_api/mbmif.int.netways.de-1442309540-1/conf.d/checkcommands/api-cmd.conf
./_api/mbmif.int.netways.de-1442309540-1/conf.d/checkcommands/mytest.conf
./_api/mbmif.int.netways.de-1442309540-1/conf.d/comments
./_api/mbmif.int.netways.de-1442309540-1/conf.d/downtimes
./_api/mbmif.int.netways.de-1442309540-1/conf.d/hosts/11686-host.conf
./_api/mbmif.int.netways.de-1442309540-1/conf.d/hosts/db-server-01.conf
./_api/mbmif.int.netways.de-1442309540-1/conf.d/hosts/generic-db-server.conf
./_api/mbmif.int.netways.de-1442309540-1/conf.d/hosts/shtest.conf
./_api/mbmif.int.netways.de-1442309540-1/include.conf
```

Something borked the `_api` package in your setup. `conf.d/comments` is on the wrong level, and as such, `./icinga2a-1448959042-1/include.conf` is missing entirely.

(reference note: #3668 )

To manually fix that - create that file and put the following content inside, similar to mine.

Mine:
```
mbmif /usr/local/icinga2/var/lib/icinga2/api/packages (master *) # cat ./_api/mbmif.int.netways.de-1442309540-1/include.conf
include "../active.conf"
if (ActiveStages["_api"] == "mbmif.int.netways.de-1442309540-1") {
  include_recursive "conf.d"
  include_zones "_api", "zones.d"
}
```

Yours:

```
vim ./icinga2a-1448959042-1/include.conf

include "../active.conf"
if (ActiveStages["_api"] == "icinga2a-1448959042-1") {
  include_recursive "conf.d"
  include_zones "_api", "zones.d"
}
```

If that file is missing, the files are there but not included on startup (you can verify that by running icinga2 in foreground with notice level, icinga2 daemon -x notice), but still on disk. 

I'll have to investigate why such a scenario may happen.

**Comment by edpstiffel** [comment]
Just to be sure:
do I have to make the changes on both nodes?

**Comment by edpstiffel** [comment]
You saved my day/week/month!!! Thank you so much.

It's working, the comments and the downtimes survive a reload/restart.

One last question: can I move the comments and downtimes, which I moved to a different place earlier, back to the /var/lib/icinga2/api/packages/_api/icinga2a-1448959042-1/conf.d/comments resp. downtimes and they are available in the system again?

**Comment by dnsmichi** [comment]
Yep, shouldn't be an issue.

I'd continue in #3668 for fixing the remaining issue with the missing include.conf and close here, ok?

**Comment by edpstiffel** [comment]
Import of old comments and downtimes was successful.
Please go ahead and close this issue.

Thanks again for your time and expertise.

**Comment by dnsmichi** [comment]
❤️
