### ISSUE TITLE
check_mongodb CheckCommand not working with extension on Ubuntu/Debian

### ISSUE THREAD

**Issue by Bigluu** [Icinga/icinga2#4949]
The mongodb CheckCommand uses the check_mongodb.py command in the object definition.
The check itself is distributed by the nagios-plugins-contrib package. The Debian/Ubuntu package strips the file extension from the check. Hence the CheckCommand is referencing to a non-existent file and is currently not working.
One solution would be to fix the CheckCommand to also strip the file extension.
This approach can however break systems that use the upstream version of the check (which contains the extension).
I'm not sure how to solve this issue right now. I think the nagios-plugins-contrib package should be changed to use the correct upstream file name or at least create a symlink to the original filename.
I don't know how flexible the Debian maintainers are regarding such changes.

**Comment by lazyfrosch** [comment]
The point is that it would make sense to call all checks like `check_something_fancy` and not like `check_something_fancy.py`

**Comment by dnsmichi** [comment]
Debian is not the only distribution where these plugins are required being installed. In case you're using CentOS for example you'll need to install it manually, and the project source calls it "check_mongodb.py". That's what the contributed CheckCommand is referring to. 

Imho this isn't an issue we may solve with Icinga 2 and how plugin sources are called. That is endless and opinion driven, and shouldn't take place here. The best and easiest bet is a custom symlink. Doesn't hurt and can be managed with Puppet/etc. 

One thing which I recognised is that the URL on docs.icinga.com is somewhat malformed. I'll fix that in a new issue later. In terms of this issue, this is - unfortunately - a wont-fix.
