### ISSUE TITLE
IDO schema update is not compatible to MySQL 5.7

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga2#4950]
I missed to fix the schema upgrades for #4877

The problem happens when upgrading to MySQL >= 5.7, and then applying the schema update.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851585

Will try to push a PR later, we should be able to include it in 2.6.1

**Comment by dnsmichi** [comment]
Review by @lippserd and myself. Ran a local import of the newly fetched mysql file on MariaDB, I do believe you've tested that on MySQL 5.7 by yourself.

Exception discussed for the freeze window for 2.6.1 since it properly fixes #4877.
