### ISSUE TITLE
Windows Agent Wizard Window resizes with screen, hiding buttons

### ISSUE THREAD

**Issue by alarmschaben** [Icinga/icinga2#4959]
When executing the Icinga 2 Agent Wizard in a VM and the screen size is reduced below a certain point (as it happens with VMs running on desktops), the wizard window shrinks, too.

This has the effect that the wizard control buttons (i.e. "Next", etc.) are hidden and can only be accessed via the keyboard. There is no way to grow the window again.

**Comment by dnsmichi** [comment]
AFAIK David had the same issue a while, but I cannot find the migrated ticket.

**Comment by lazyfrosch** [comment]
#4834 ?

**Comment by alarmschaben** [comment]
Almost. It's not the MSI installer but the wizard itself.

Probably just some flag...

**Comment by alarmschaben** [comment]
And I concur that this might be VirtualBox specialty. My observation was also made using that hypervisor.

**Comment by dnsmichi** [comment]
Thanks @lazyfrosch exactly what I was looking for. The subject is misleading, the screenshot is the important bit.

**Comment by dnsmichi** [comment]
![bildschirmfoto vom 2016-12-06 16-40-04](https://cloud.githubusercontent.com/assets/382049/22335069/77fa5da4-e3dd-11e6-94be-2b54624cb9a9.png)
