### ISSUE TITLE
Icinga2 Service on RHEL5 Satellite/Agent stops after reload/config change from master

### ISSUE THREAD

**Issue by sahnd** [Icinga/icinga2#4961]
I have noticed a problem after adding a RHEL5 based satellite of icinga2 (2.6.0) to a distributed setup. Every time I do a reload of Icinga2 (service icinga2 reload) or do a config deployment from master via icinga-director (causing a reload on this satellite), Icinga2 on this RHEL5 node is stopped. I.e. the new instance, which should come up by the reload, does not do so.

I am a bit stuck with debugging this.
It somehow seems to be related to a nested host-template (os -> linux -> redhat) attached to this host, because if I change the host-template to a more general level (os -> linux), the problem seems to be gone.
I have added another host-template (os -> linux -> test-distri) and applied it to the host. The problem is back again. I have several other hosts (redhat/centos 6 & 7) having the host-template "redhat" applied, which do not show this problem. So I guess it somehow has to do with RHEL5 in combination of my host-template tree.
icinga2.log and debug.log do not show any errors. Neither do /var/log/messages or dmesg.
I have already rebooted the whole server and wiped /var/lib/icinga2/api/* without success.

Does anyone has any idea how to debug this or some hint how to resolve this?

**Comment by dnsmichi** [comment]
That's presumingly fixed with #4867 and targets v2.6.1.
