### ISSUE TITLE
ITL: assignment of check_adress in check_http (and other check) blocks check by vhost/hostname

### ISSUE THREAD

**Issue by bcogel** [Icinga/icinga2#4965]
check_http originally allows to check a webserver by IP (-I) and by hostname (-H). 

I think in some scenarios it's more common to check a webserver by its servername than to check by IP: 
- If you're using an apache with several vhosts defined. 
- Sometimes you want to check a server that is represented by round robin DNS and a number of different IPs (for example if you want to check your outbound connection by checking google.com or heise.de...). 
- Sometimes webservices are migrated to other hosts. And you don't want to readjust the check configuration each time...

Because of the assignment of check_address in the definition of check_http in the ITL, it's impossible to use check_http with -H. To define a service only with -H is simply impossible at least when you're using the director.  If I'm setting http_vhost= www.heise.de, leaving the hostaddress blank, I'm getting this in the debug log:

notice/Process: PID 17776 ('/usr/lib/nagios/plugins/check_http' '-H' 'www.heise.de' '-I' '') terminated with exit code 2

The same happens for some other checks (check_ping....). The host is regarded 'down'...

I can set the hostname as host adress in the host configuration and leave http.vhost blank. This will work because my icinga server will resolve the hostname. Check_ping will work in most cases. And also check_http will give a positive result in most cases. But sometimes I get something like 'HTTP WARNING: HTTP/1.1 400 Bad Request' in the checks for some webservers (try www.heise.de).

Ok...I can add my own definiton of all affected commands  to make hostnames work... but I don't know if this is the correct way to do things...

Regards
Berthold Cogel

**Comment by BerndWi** [comment]
Hi, we have this issue as well. 
We use the check_http check with the -sni option to check the certificate. However, the vhost option is just ignored, because icinga always adds the -I option with the IP. So adding different checks with different vhosts will all end up to check the same certificate, which is the first one for the given IP Address.

**Comment by htriem** [comment]
@Al2Klimov
