### ISSUE TITLE
Icinga 2.6.1 crashes repeatedly with "function call 'fork' failed"

### ISSUE THREAD

**Issue by geotekberlin** [Icinga/icinga2#4971]
After upgrading our 2.5.4 installation to 2.6.1 it crashes repeatedly a few minutes after start. Web frontend says "Backend icinga is not running", the main icinga2 process seems to be still running, however. 

The same thing happened in December when we tried upgrading to 2.6.0, so this bug is still not fixed. Very frustrating.

> Feb 01 18:11:05 geotek-icinga-replica systemd[1]: icinga2.service: Main process exited, code=killed, status=6/ABRT
> Feb 01 18:11:05 geotek-icinga-replica systemd[1]: icinga2.service: Unit entered failed state.
> Feb 01 18:11:05 geotek-icinga-replica systemd[1]: icinga2.service: Failed with result 'signal'.
> Feb 01 18:11:06 geotek-icinga-replica systemd-coredump[11732]: Process 10924 (icinga2) of user 489 dumped core.
> Feb 01 18:11:57 geotek-icinga-replica systemd-coredump[11743]: Process 11742 (icinga2) of user 489 dumped core.

[report.1485969065.428405.txt](https://github.com/Icinga/icinga2/files/745636/report.1485969065.428405.txt)

**Comment by dnsmichi** [comment]
SLES12? Sounds like a similar issue in #4918. Please show the output of `icinga2 --version` as well as additional icinga2 log files.

**Comment by geotekberlin** [comment]
OpenSuse Leap uses the SLES12 code base. Here is the version output:
geotek-icinga-replica:~ # icinga2 --version

> icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.1-1)
> 
> Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
> License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Application information:
>   Installation root: /usr
>   Sysconf directory: /etc
>   Run directory: /run
>   Local state directory: /var
>   Package data directory: /usr/share/icinga2
>   State path: /var/lib/icinga2/icinga2.state
>   Modified attributes path: /var/lib/icinga2/modified-attributes.conf
>   Objects path: /var/cache/icinga2/icinga2.debug
>   Vars path: /var/cache/icinga2/icinga2.vars
>   PID path: /run/icinga2/icinga2.pid
> 
> System information:
>   Platform: openSUSE Leap
>   Platform version: 42.2
>   Kernel: Linux
>   Kernel version: 4.4.36-8-default
>   Architecture: x86_64
> 
> Build information:
>   Compiler: GNU 4.8.5
>   Build host: build70
> geotek-icinga-replica:~ #
> 

If you need the debug log, please tell me a way to send it privately to you, for privacy reasons I can't post it publicly here

**Comment by dnsmichi** [comment]
Can you please verify that it is (not) the same issue as described in #4918 - DefaultMaxTasks might be set to a too small default.

**Comment by geotekberlin** [comment]
Michael, you pointed me into the right direction. I had already added **TaskMax=infinity** a long time ago because I was aware about this issue, but the 2.6.1 Yast package update overwrote **/etc/systemd/system/multi-user.target.wants/icinga2.service** with the default icinga file where this statement is missing. I double-checked that refreshing Icinga2 in Yast always causes all manually updated systemd options to be overwritten without warning, it does not even leave a backup of the original file.

I will leave Icinga 2.6.1 running now for a couple of days to see if it is stable and will then report back here.

In case this will indeed solve our issue we could live with the workaround to always manually patch icinga2.server after each update, but this is not an ideal solution IMO. Maybe you should add this line to the icinga default installation until a more elegant solution has been found?

Thanks for your help!

**Comment by dnsmichi** [comment]
Icinga 2 just installs the systemd service file underneath /usr/lib/systemd/system. I guess multi-user.target.wants is just a symlink generated by systemd itself.

If you prefer to override specific systemd service units, I'd add them in /etc/systemd/system and then reload systemd (systemctl daemon-reload IIRC). Quick google leads to https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html

**Comment by geotekberlin** [comment]
There is indeed a symlink in **/etc/systemd/system/multi-user.target.wants/** pointing to the Icinga created config file which gets overwritten with every new Icinga version. I would have to create an explicit override file for systemd in order to make the TaskMax setting persistent as I don't want to tinker with the global systemd defaults just because one specific application needs special entries. Even though it is heavily devated, there are good reasons for limiting the number of tasks in the linux kernel. 

I still think it would be nice if Icinga2 would work out of the box in systemd environments and without the need for special treatment in systemd config files and with the awareness that these fixes may not be persistent.

Anyway, my Icinga2 installation seems to run stable now so you may close this issue.

**Comment by dnsmichi** [comment]
To be honest, I have no idea why and how those systemd configs are symlinked in /etc. Although I do believe that the linked article I posted earlier easily allows to override specific systemd settings. Done manually or via config management tools.

Those TaskMax configuration settings seem to be relatively new and are not used in RHEL for instance. Why they are set in SUSE by default - no idea, but as you said there's probably some discussion going on about that, and I just don't follow everything.

I further do believe that OpenSUSE Leap isn't really a target distribution where one should put the monitoring server on, but that's my sole personal opinion. If you happen to have suggestions and patches on how to make things work for *all* supported platforms (this includes Debian, RHEL, SUSE based, Gentoo, ArchLinux, BSD based, etc) which use Systemd, please go on.

**Comment by dnsmichi** [comment]
If there's others running into the same problem, the mentioned workaround should solve the issue. PRs for docs welcome.
