### ISSUE TITLE
nrpe timeout doesn't appear to work

### ISSUE THREAD

**Issue by andrewmiskell** [Icinga/icinga2#4972]
I see that in https://github.com/Icinga/icinga2/issues/2285 that the nrpe timeout value was increased to 5 minutes. However this doesn't appear to be working properly.

I had to edit the /usr/share/icinga2/include/command-plugins.conf file to change

timeout = 5m 

to

vars.nrpe_timeout = 5m 

in order for the timeout to actually be passed to the command line for check_nrpe.

I believe this is because the argument in the configuration for the nrpe command is **"-t" = "$nrpe_timeout$"** which doesn't match the **timeout** variable so it's simply ignored.

**Comment by andrewmiskell** [comment]
Actually, timeout = 5m sets how long it'll take before icinga2 will timeout the command, but nrpe_timeout is still undefined so it defaults to 10 seconds. 

Probably should look a bit more like below:

        vars.nrpe_timeout = 5m
        timeout = 5m

Both values set to the same limit so the command doesn't timeout prematurely.

**Comment by dnsmichi** [comment]
You'll need to specify `vars.nrpe_timeout` in your service definition to properly override that value for specific services.

The global `timeout` attribute for that CheckCommand is there for safety reasons (a check which takes more than 5 minutes to finish is a somewhat different problem). Although you can override the global timeout using the `check_timeout` if you prefer a limit more than 5m. I would change such checks to an external job and send the check results via REST API in that case.
