### ISSUE TITLE
Explain why system requirements & sizing are difficult

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#4974]
Mention why system requirements are fairly impossible to tell.

https://monitoring-portal.org/index.php?thread/39763-system-requirements-for-icinga2-server/

**Comment by terrytibbles** [comment]
Did anything happen on this? It's still difficult to find any sort of sizing guide.

**Comment by dnsmichi** [comment]
https://community.icinga.com is a good platform to ask things like this, as every environment varies. Provide as much detail as possible on your plans and community members will gladly help you.
