### ISSUE TITLE
icingaweb2 on master node is not able to talk to icinga in distributed monitoring setup in icinga version 2.6.1

### ISSUE THREAD

**Issue by rnekkanti** [Icinga/icinga2#4975]
Icingaweb2 is not able to talk to icinga2 running on the master node from where configs are deployed. We had the same issue in version 2.6.0. Looks like it has not been still fixed. Icingaweb2 says back end icinga is not running.

**Comment by Crunsher** [comment]
What does 'not able to talk' mean? And if you had this problem in 2.6.0 too please link to that ticket.

**Comment by dnsmichi** [comment]
Please add more details such as

- `icinga2 --version`
- `zones.conf`
- IDO feature MySQL or PostgreSQL
- Screenshot of Icinga Web 2 Monitoring Health & About/Info

**Comment by l3ksm** [comment]
Hi all!

I was have Ubuntu 16.04 with Icinga2 2.6.0 and IcingaWeb2 2.4.0. All packages installed from http://packages.icinga.org/ubuntu
IDO feature is PostgreSQL
After update Icinga2 to 2.6.1 in IcingaWeb2 I see error 
> Backend icinga is not running

Screenshots:
<img width="367" alt="screenshot at feb 06 19-30-00" src="https://cloud.githubusercontent.com/assets/5788224/22655911/be9f631c-eca2-11e6-906e-4c14980a5a20.png">
<img width="446" alt="screenshot at feb 06 19-31-50" src="https://cloud.githubusercontent.com/assets/5788224/22656001/fdb92ef2-eca2-11e6-8a57-d16b74faba33.png">

Here is my `zones.conf`:
>/*
> * Generated by Icinga 2 node setup commands
> * on 2017-01-30 19:43:54 +0300
> */
>
>object Endpoint NodeName {
>}
>
>object Zone ZoneName {
>	endpoints = [ NodeName ]
>}

And `icinga2 --version`:
>icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.1-1)
>
> Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
> License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Application information:
>   Installation root: /usr
>   Sysconf directory: /etc
>   Run directory: /run
>   Local state directory: /var
>   Package data directory: /usr/share/icinga2
>   State path: /var/lib/icinga2/icinga2.state
>   Modified attributes path: /var/lib/icinga2/modified-attributes.conf
>   Objects path: /var/cache/icinga2/icinga2.debug
>   Vars path: /var/cache/icinga2/icinga2.vars
>   PID path: /run/icinga2/icinga2.pid
> 
> System information:
>   Platform: Ubuntu
>   Platform version: 16.04.1 LTS (Xenial Xerus)
>   Kernel: Linux
>   Kernel version: 4.4.0-62-generic
>   Architecture: x86_64
> 
> Build information:
>   Compiler: GNU 5.4.0
>   Build host: lcy01-35

**Comment by l3ksm** [comment]
@dnsmichi then I have this issue - https://github.com/Icinga/icingaweb2/issues/2715

**Comment by rnekkanti** [comment]
@Crunsher @dnsmichi  From my understanding what is happening is in a HA master setup IDO runs on only one of the two master servers. In my case IDO is not running on the config master server from where the configs are deployed. I am also deploying a few configurations using icinga director which relies on icingaweb2. I want all configs to be deployed from the config master server. In my case IDO is not running on the config master. I am able to install icingaweb2 and director on config master and deploy configs using icinga director but I am not able to see any hosts and services as IDO is not running on the config master. When I install icingaweb2 on the other master server in the HA pair I am able to install it successfully. I was not able to find any documentation on how to move the IDO to the config master. I see we can run IDO on both icinga master hosts by disabling the IDO HA but it is not recommended. Currently I have disabled HA and running one icinga host per zone. I will enable HA and send you the details by tomorrow.

**Comment by dnsmichi** [comment]
@rnekkanti What exactly is your issue then? Is it about the IDO database backend (which somehow uses two local databases, please show your ido-mysql.conf file)? Or are you referring to sending external commands from the Icinga Web 2 interface to one/both instances?

**Comment by gunnarbeutner** [comment]
@lippserd This looks like an Icinga Web 2 issue rather than a problem with Icinga 2 itself. Can you please have a look at this? :)

**Comment by dnsmichi** [comment]
I'm still waiting for feedback @rnekkanti ... otherwise I'll close the issue, as I do believe everything is working as intended.

**Comment by rnekkanti** [comment]
@dnsmichi  Go ahead and close it.
