### ISSUE TITLE
Error with check_snmp_process.pl and useless spaces

### ISSUE THREAD

**Issue by darkounet** [Icinga/icinga2#4976]
Hi,

I have an error with check_snmp_process.pl define in icinga2 manubulon plugin, I can't specify warning or critical with negative values like -1,20

ie : 

I want to check the number of process for smtp, and this number can be 0

so I run this check : 

``` shell
 /usr/lib/nagios/plugins/check_snmp_process.pl -C public -H toto -2 -n smtp -c -1,100 -w -1,20
No process matching smtp found : YOU told me it was : OK
```

But icinga run it like : 

``` shell
/usr/lib/nagios/plugins/check_snmp_process.pl -C public -H toto -2 -n smtp -c -1,100 -w -1,20
Unknown option: 1
Unknown option: ,
Unknown option: 1
Unknown option: 0
Unknown option: 0
Unknown option: 1
Unknown option: ,
Unknown option: 0
Use of uninitialized value $num in pattern match (m//) at /usr/lib/nagios/plugins/check_snmp_process.pl line 89.
Numerical values for warning and critical
Usage: /usr/lib/nagios/plugins/check_snmp_process.pl [-v] -H <host> -C <snmp_community> [-2] | (-l login -x passwd) [-p <port>] -n <name> [-w <min_proc>[,<max_proc>] -c <min_proc>[,max_proc] ] [-m<warn Mb>,<crit Mb> -a -u<warn %>,<crit%> -d<delta> ] [-t <timeout>] [-o <octet_length>] [-f -A -F ] [-r] [-V] [-g]
```

The problem is the space betwen -c or -w  and value, must be **-c-1,100** not **-c(space)-1,100**

Do you know how can I remove this useless space for this two args ? 

I'm using icinga2 2.6.1-1~debmon70+1

Thanks

**Comment by dnsmichi** [comment]
That plugin is not maintained by the Icinga project, you might want to open an issue on the manubulon bug tracker. Is there anything specific to the ITL CheckCommand which does not work, or just a manual plugin call?

**Comment by dnsmichi** [comment]
Aha, crossposted already in dnsmichi/manubulon-snmp#24 .. so I'm closing this one.
