### ISSUE TITLE
icinga2/api/log directory is not created

### ISSUE THREAD

**Issue by helgein** [Icinga/icinga2#4977]
had to create it manually as you can see from the timestamp:

[root@LibSrv api]# pwd && ll
/var/lib/icinga2/api
insgesamt 12
drwx------ 2 icinga icinga 4096  3. Feb 15:52 log
drwx------ 3 icinga icinga 4096 20. Jan 13:37 packages
drwx------ 4 icinga icinga 4096 20. Jan 13:37 zones

found it by looking in the log:
[2017-02-03 15:26:10 +0100] warning/ApiListener: Could not open spool file: /var/lib/icinga2/api/log/current
Context:
        (0) Replaying log for Endpoint 'master'

[2017-02-03 15:26:10 +0100] warning/ApiListener: Could not open spool file: /var/lib/icinga2/api/log/current
Context:
        (0) Replaying log for Endpoint 'master'

**Comment by Crunsher** [comment]
This is the same as #4640, I have been sitting on an untested fix for this for a while and forgot about it ^^
I'll close the old one in favor of this.

**Comment by dnsmichi** [comment]
There's a missing call to MkDirP() inside OpenLogFile().
