### ISSUE TITLE
Icinga 2.6.1 packages for Ubuntu 12.04 Precise?

### ISSUE THREAD

**Issue by sahnd** [Icinga/icinga2#4978]
Hi,

I see Icinga 2 Packages for Ubuntu 12.04 are stuck at 2.5.4 due to build errors with 2.6.1. Is there any chance this will be fixed or will 2.5.4 be the latest available version for Ubuntu 12.04 precise?

**Comment by formorer** [comment]
On Mon, 06 Feb 2017, sahnd wrote:

> Hi,
> 
> I see Icinga 2 Packages for Ubuntu 12.04 are stuck at 2.5.4 due to build errors with 2.6.1. Is there any chance this will be fixed or will 2.5.4 be the latest available version for Ubuntu 12.04 precise?
As soon as I find some time. Probably today or tomorrow. 

Alex

**Comment by sahnd** [comment]
The new packages are available and have been installed successfully.

Thanks, ticket can be closed!
