### ISSUE TITLE
Failure to kill check command after exceeding timeout is not reported

### ISSUE THREAD

**Issue by hansmi** [Icinga/icinga2#4981]
We're invoking a number of check commands via `sudo` as they require privileges not given to the standard user for Icinga. Depending on the command the target user may be `root` or another dedicated user. We're using a configuration using this layout:

```
template CheckCommand "docker-check-command" {
  timeout = 60
  command = ["/usr/bin/sudo", "-n", "-u", "$sudo_user$"]
  vars.sudo_user = "root"
}

object CheckCommand "docker_daemon" {
  import "plugin-check-command"
  import "docker-check-command"
  command += [PluginDir + "/check_docker_daemon"]
}
```

When the command, `check_docker_daemon` in this case, runs for more than a minute Icinga is supposed to kill the command. Unfortunately that fails as `sudo` is setuid and the Icinga user can't send signals.

```
recvmsg(11, {msg_name(0)=NULL, msg_iov(1)=[{"{\"command\":\"kill\",\"pid\":-11637.0,\"signum\":9.0}", 4096}], msg_controllen=0, msg_flags=0}, 0) = 46
kill(4294955659, SIGKILL) = -1 EPERM (Operation not permitted)
```

(4294955659 is `2**32 - 11637` as an unsigned integer with 11637 being the group leader PID)

Now, all of this is obvious. Unfortunately Icinga and Icingaweb do not give any indication of this happening. Instead the check's “last check” keeps growing and no alert is ever sent.

Could you please extend Icinga to produce an UNKNOWN status when killing a check command fails?

**Comment by jkroepke** [comment]
Our current hacky workaround for this problem:

```
command = [ "/bin/bash", "-c", "sudo $$*; wait $$!", "--" ]
```

Because icinga now kill the bash instead sudo. :-1:
