### ISSUE TITLE
Typo in livestatus key worst_services_state for hostgroups table

### ISSUE THREAD

**Issue by mickenordin** [Icinga/icinga2#4983]
In the icinga2 implementation of the livestatus api, there is a typo. The key is called worst_service**s**_state instead of worst_service_state like it is called in mk_livestatus, naemon livestatus and shinken livestatus:

see e.g.: http://www.naemon.org/documentation/usersguide/livestatus.html
https://github.com/shinken-monitoring/mod-livestatus

This causes compatibility issues when using Thruk or other guis and when querying the the live status api directly. 

 I propose that the key be renamed to worst_service_state like it is called in the other implementations, or at least that both keys be supported so that Icinga2 doesn't loose compatibilty with the api.

**Comment by dnsmichi** [comment]
Nice catch, fixed 👍
