### ISSUE TITLE
Wrong response type when unauthorized

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#4984]
The API responds to
`$ curl -v -X POST -H 'Accept: application/json' -k -u 'notexistinguser':'123456' -d '{"next_check":1486570586,"force_check":true,"service":"localhost!check_multi"}' https://127.0.0.1:5665/v1/actions/reschedule-check`
with
`<h1>Unauthorized</h1>`
.

As an API user I'd like my `Accept` header to be honored anyway.

**Comment by dnsmichi** [comment]
```
michi@mbmif ~/coding/icinga/icinga2 (master *=) $ curl -k -s -u foo:bar 'https://localhost:5665/v1/objects/hosts'
<h1>Unauthorized. Please check your user credentials.</h1>

michi@mbmif ~/coding/icinga/icinga2 (master *>) $ curl -k -s -u foo:bar 'https://localhost:5665/v1/objects/hosts' -H 'Accept: application/json'
{"results":[{"info":"Unauthorized. Please check your user credentials."}]}
```
