### ISSUE TITLE
Review `dummy` entry in ITL

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#4987]
The `dummy` entry in the ITL has commandline arguments as part of the `command` attribute. While this is perfectly ok for Icinga 2 it keeps tools like Icinga Director from finding the macros.

It would be better to declare them as arguments with `skip_key` to true.

If done carefully changing this will not change the default behaviour and therefore not break existing installations. On the other hand it will allow to use Director to set both commandline arguments which should give a lot more flexibility.

**Comment by dnsmichi** [comment]
Waiting for your PR :)

**Comment by widhalmt** [comment]
I just wanted to talk to some people if they think this is a good idea. :-)

But if you do, I'll get a PR ready. Maybe today, maybe Monday.

**Comment by widhalmt** [comment]
Here you are. :-D
