### ISSUE TITLE
Icinga daemon runs with nice 5 after reload

### ISSUE THREAD

**Issue by sadziu82** [Icinga/icinga2#4989]
After reloading configuration Icinga daemon is running with nice 5 not 0

Before reload:
```
# ps -e -o pid,nice,args | grep icinga
 9419   5 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/icinga2.err --reload-internal 5851
14113   0 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/icinga2.err
14123   0 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/icinga2.err
24513   0 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/icinga2.err
24693   0 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit console --connect https://root@localhost:5665/
25024   0 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit console --connect https://root@localhost:5665/

```

After reload:
```
# ps -e -o pid,nice,args | grep icinga
 9419   5 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/icinga2.err --reload-internal 5851
24513   0 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/icinga2.err
24693   0 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit console --connect https://root@localhost:5665/
25024   0 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit console --connect https://root@localhost:5665/
31980   5 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/icinga2.err --reload-internal 14123
32101   5 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/icinga2.err --reload-internal 14123
```

Icinga info:
```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.1 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 3.13.0-45-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.4
  Build host: lgw01-55
```

**Comment by nE0sIghT** [comment]
Confirming. In my case nice value is more

**Comment by mzac** [comment]
Confirmed on 2.6.2-1 on my Raspberry Pi.. it increases by 5 on each reload..

0 -> 5 -> 10

<pre>
root@pi3:~# ps -e -o pid,nice,args | grep icinga
26337   0 /usr/lib/arm-linux-gnueabihf/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e /var/log/icinga2/error.log
26361   0 /usr/lib/arm-linux-gnueabihf/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e /var/log/icinga2/error.log

root@pi3:~# systemctl reload icinga2

root@pi3:~# ps -e -o pid,nice,args | grep icinga
26547   5 /usr/lib/arm-linux-gnueabihf/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e /var/log/icinga2/error.log --reload-internal 26337
26560   5 /usr/lib/arm-linux-gnueabihf/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e /var/log/icinga2/error.log --reload-internal 26337

root@pi3:~# systemctl reload icinga2

root@pi3:~# ps -e -o pid,nice,args | grep icinga
26631  10 /usr/lib/arm-linux-gnueabihf/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e /var/log/icinga2/error.log --reload-internal 26547
26645  10 /usr/lib/arm-linux-gnueabihf/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e /var/log/icinga2/error.log --reload-internal 26547

root@pi3:~# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.2-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Raspbian GNU/Linux
  Platform version: 8 (jessie)
  Kernel: Linux
  Kernel version: 4.4.38-v7+
  Architecture: armv7l

Build information:
  Compiler: GNU 4.9.2
  Build host: cubietruck
</pre>

**Comment by gunnarbeutner** [comment]
This should now be fixed in the master branch. I'd greatly appreciate it if you were to find a moment to test this. :)
