### ISSUE TITLE
state transitions after first hard state are always hard

### ISSUE THREAD

**Issue by gitmirko** [Icinga/icinga2#4994]
Hi,
here is some context from a previous issue (https://github.com/Icinga/icinga2/issues/4174)
In our case we have the following situation:
- disk-check is currently in a hard warning state (already got a notification for this problem)
- we lose "some" udp packages during the snmp-request for the disk-check and we return unknown from our plugin
- icinga changes the state of this service from hard warning to hard unknown. ( Is this the right behavior? I thought it will enter the logic with retry_interval and max_check_attempts.)
- I will not get any notification, because I've filtered the unknown state for my notification object
- a couple seconds later the plugin has no more problems with snmp and returns warning again. The service will enter hard warning again and sends another notification.
- this kind of scenario could happen a couple of times during the night when the network is busy replicating data between datacenters.

```
"statehistory_id","instance_id","state_time","state_time_usec","object_id","state_change","state","state_type","current_check_attempt","max_check_attempts","last_state","last_hard_state","output","long_output","check_source","endpoint_object_id"
"2774272","1","2016-09-13 22:07:59","757132","13173","1","2","0","1","3","0","0","SUN Hardware CRITICAL - zpool",,"icingas01-d","5"
"2774277","1","2016-09-13 22:09:05","481417","13173","1","2","0","2","3","2","0","SUN Hardware CRITICAL - zpool",,"icingas01-d","5"
"2774279","1","2016-09-13 22:10:11","23310","13173","1","2","1","1","3","2","2","SUN Hardware CRITICAL - zpool",,"icingas01-d","5"
"2774767","1","2016-09-14 00:06:32","501343","13173","1","3","1","1","3","2","3","",,"icingas01-d","5"
"2774814","1","2016-09-14 00:09:47","894563","13173","1","2","1","1","3","3","2","SUN Hardware CRITICAL - zpool",,"icingas01-d","5"
"2775004","1","2016-09-14 00:23:48","922825","13173","1","3","1","1","3","2","3","SUN Hardware UNKNOWN - snmpwalk NOT OK",,"icingas01-d","5"
"2775055","1","2016-09-14 00:27:09","374936","13173","1","2","1","1","3","3","2","SUN Hardware CRITICAL - zpool",,"icingas01-d","5"
"2777582","1","2016-09-14 08:27:40","732753","13173","1","0","1","1","3","2","0","SUN Hardware OK - no_errors",,"icingas01-d","5"
```
The transitions from critical -> unknown -> critical -> unknown -> critical -> ok are all hard states on the first check_attempt.
In my opinion only the last state change critical -> ok should be treated as hard right away.

Mirko

**Comment by dnsmichi** [comment]
retry_interval and max_check_attempts only kicks in for SOFT states. HARD states are a different state type, and as such will trigger notifications independent from max_check_attempts. The other observed behaviour with filtered notifications and basically 2x critical notifications is the same issue described in #4688 - works as designed but may need some enhancements. I'm closing this one.
