### ISSUE TITLE
documentation: mixed up host names in 6-distributed-monitoring.md

### ISSUE THREAD

**Issue by mejo-** [Icinga/icinga2#4996]
The examples in 6-distributed-monitoring.md have slightly mixed up host names: sometimes the docs talk about `icinga2-client2.localdomain` while they mean `icinga2-client1.localdomain`. Actually there's no `client2` at all in the examples. Should be easy to fix: ```:%s/icinga2-client2/icinga2-client1/g```

**Comment by dnsmichi** [comment]
Can you point out exactly what you mean? client2 is added on purpose in specific chapters.

**Comment by mejo-** [comment]
I went through the whole document `docs/6-distributed-monitoring.md` and double-checked all occurrences of `icinga2-client[12]`.

You're right, that `icinga2-client2` exists on purpose in chapter *6.10 Scenarios* and some subchapters of *6.12 Advanced Hints*. But in all other places, only one Icinga2 client is mentioned and this should be `icinga2-client1` in order to be consistent.

I created a pull request which fixes the Icinga2 client hostnames according to to that: #5001

**Comment by dnsmichi** [comment]
Thanks for the patch, but I'll change that in a different way. command endpoint will use client1, config sync client2 and the deprecated bottom up mode will use client3. The other examples which are found down below in the scenarios are valid on their own, but certain smaller issues are there too.
