### ISSUE TITLE
failed to open stream: No such file or directory in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17

### ISSUE THREAD

**Issue by merdna** [Icinga/icinga2#4998]
OS : FreeBSD 11.0
Icinga Version: r2.6.1-1
Icingaweb2 Version 2.4.1
Director 1.3

got this : 
 ./icingacli director test php
PHP Warning:  require_once(Icinga/Application/Cli.php): failed to open stream: No such file or directory in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17
PHP Fatal error:  require_once(): Failed opening required 'Icinga/Application/Cli.php' (include_path='.:/usr/local/share/ZendFramework/library') in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17

Warning: require_once(Icinga/Application/Cli.php): failed to open stream: No such file or directory in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17

Fatal error: require_once(): Failed opening required 'Icinga/Application/Cli.php' (include_path='.:/usr/local/share/ZendFramework/library') in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17

any Ideas?

**Comment by gunnarbeutner** [comment]
This looks like a problem with the director module. Please make sure to report this against the right project (https://github.com/Icinga/icingaweb2-module-director).
