### ISSUE TITLE
API process-check-result allow setting timestamp

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icinga2#5002]
If API action process-check-result would allow setting timestamp, it would be possible to use it to import results with its original timestamp. So having an additional field timestamp (or similar) and setting the provided value as execution time falling back to now if now value is provided would be nice.

**Comment by dnsmichi** [comment]
I would only allow to specify more CheckResult attributes.
https://github.com/Icinga/icinga2/blob/master/lib/icinga/checkresult.ti#L62

**Comment by dgoetz** [comment]
Seems fine to me. So execution_start would be the field which meets my requirement if I am correct.

**Comment by dnsmichi** [comment]
`execute_end` is what you're looking for. I'll take a note for the docs.

**Comment by dgoetz** [comment]
Could this be backported as it is only a small addition or will it only hit 2.8.0 and later?

**Comment by dnsmichi** [comment]
API changes/additions should only be released in major versions, so it will be 2.8.x.
