### ISSUE TITLE
Notification interval vs timeperiod

### ISSUE THREAD

**Issue by fir3wall** [Icinga/icinga2#5003]
Hello,
I've just hit an issues and wonders can Icinga2 team can somehow improve it in "official way" in code or I just need to do some magic interval=0 notifications.

Problem is that on object Notification interval is actual interval between actions that causing my deployments issues with timeperiods and sending emails on time. Example:
* Notification set up for timeperiod 06:00 - 22:00 with interval 60 min
* Service goes down at 21:30 
* Notification is triggered at 21:30
* Next one (service still down) is not sent as it's already not in timeperiod (22:30)
* My users expect notification to be sent straight at 06:00 as it's already way after 60 min period ... however it's not "time" period it's "action period"
* Notification is sent on 06:30

So what I'm missing here is notifications to be kick straight away on beggining of timeperiod if interval time already pased (compared to actual time not action time). 

Any feedback on possibly doing that in code and programming as some kind of switch on/off? Otherwise I can think about creating new notification on timeperiod 06:00 - 06:05 with interval = 0 that will kick these emails straight away ... however if something goes down at 21:01 then I will get 2 x emails next to each other on 6AM (interval=0 and interval=60)

Thanks for any feedback and guidance

**Comment by dnsmichi** [comment]
The notification interval kicks in and will attempt to trigger notifications in the given 1h interval. The notification period checks will reject those hourly attempts to send notifications, and thus the next interval will be 06:30 as you've correctly analysed. There's currently no way to reschedule the next notification into X timespan into the future. That is also dependant on the time period segment calculation which is done only for one day in the future. You would need to calculate the end of the notification period window and set the next_notification timestamp to that date + 1s.

**Comment by fir3wall** [comment]
Thank you for feedback, I think easier option for me would be create this separate notification with interval=0 at begging of my time period ... I'm risking duplication but it's easier for me.

**Comment by dnsmichi** [comment]
Okidoki.
