### ISSUE TITLE
offset in PDF

### ISSUE THREAD

**Issue by pcasis** [Icinga/icinga2#5004]
Hi, 

I exported in PDF the hosts. I get the following result : 

![selection_034](https://cloud.githubusercontent.com/assets/25147189/22971781/2c5f8672-f377-11e6-93dd-5c19544f6f3f.png)

As you can see there is an offset on the first line.

Regards

**Comment by gunnarbeutner** [comment]
If anything this would be a bug in Icinga Web 2. Please report the issue against the right project. :)

**Comment by pcasis** [comment]
My bad, sorry.
