### ISSUE TITLE
[Documentation] Missing parameter for SNMPv3 auth

### ISSUE THREAD

**Issue by Niflou** [Icinga/icinga2#5010]
Hi there !

I didn't find a documentation related repo so I'm posting here, if I should move my post elsewhere please let me know.

It took me some time to figure out that one parameter is mandatory and not documented to manage to auth properly using manubulon's snmp commands : `snmp_v3_use_authprotocol` ( you have to set it to true to get icinga pass the `snmp_authprotocol` to `check_snmp_load.pl` )

Source : https://github.com/Icinga/icinga2/blob/master/itl/command-plugins-manubulon.conf#L46

Every other parameters are documented so I think this one has been forgotten.

Thx

**Comment by dnsmichi** [comment]
Can you edit that online and send PR please? :)

**Comment by Niflou** [comment]
I tried.

**Comment by dnsmichi** [comment]
See my comment in #5012.
