### ISSUE TITLE
Support the in operator for strings

### ISSUE THREAD

**Issue by lippserd** [Icinga/icinga2#5018]
Icinga 2 should support the in operator for strings, e.g. `"a" in "abc"`.

**Comment by Thomas-Gelf** [comment]
My first thought was "Cool, this will make things easier". Then I came to this example:

```
object Host "host1" {
  import "default"
  vars.location = [ "Nuremberg", "Berlin", "Frankfurt" ]
}

object Host "host2" {
  import "default"
  vars.location = [ "Frankfurt (Oder)" ]
}

object Host "host3" {
  import "default"
  vars.location = "Frankfurt (Oder)"
}

apply Service "Tests in Frankfurt" {
  import "tests"
  assign where "Frankfurt" in vars.location
}
```

And now?

**Comment by dnsmichi** [comment]
Imho the first and the third host would get a service object applied. But I get your point, a doubled-up contains check is pretty mind blowing (the second host object). I guess it is undefined what happens here.

**Comment by lippserd** [comment]
Did not read your updates until now. Maybe we should just not support the in operator for strings. What do you guys think?

**Comment by dnsmichi** [comment]
Since we don't have a clear vision on how it could work, I would close it.

The referenced issue might need some more error and type handling to prevent user inputs resulting in unsupported Icinga 2 DSL. That should imho solve the problem.

**Comment by lippserd** [comment]
I second this.
