### ISSUE TITLE
CheckCommand swap should be changed

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icinga2#5023]
The CheckCommand "swap" for check_swap should be changed, because at the moment there's if/else in it and Director (1.3.1) is not able to fetch the function trough the API.

<img width="551" alt="bildschirmfoto 2017-02-23 um 08 09 35" src="https://cloud.githubusercontent.com/assets/3973350/23248395/7551b408-f99f-11e6-922c-aa29038ff71b.png">

**Comment by gunnarbeutner** [comment]
What kind of impact does this issue have on your setup?

**Comment by dnsmichi** [comment]
I don't think we should change the ability to use functions inside the ITL CheckCommands. That removes certain possibilities to allow different plugin options in a single command. AFAIK there's an open issue for the Icinga Director to implement a) functions b) conditionals.

**Comment by gunnarbeutner** [comment]
I agree, if anything this is a limitation in Director and should be addressed there. We should not artificially limit the feature set we can use in the ITL.

**Comment by dgoetz** [comment]
I also agree, but actual its a limitation of the API.

**Comment by dnsmichi** [comment]
Thanks for note, that was not clear to me from the initial question.

Actually this request should be to export the function's config snippets, and afaik we had that discussion already somewhere.

![screen shot 2017-02-23 at 12 20 32](https://cloud.githubusercontent.com/assets/382049/23257111/a9dfe424-f9c2-11e6-9752-5f6a56bab00d.png)

**Comment by lazyfrosch** [comment]
I guess we can close this, there is no good way to expose this via the API so that Director could use it...
