### ISSUE TITLE
Hosts that are re-build X Times via API are not show in icingaweb2 until reload

### ISSUE THREAD

**Issue by christianVLC** [Icinga/icinga2#5045]
Hi,

we want start to register the hosts/hostgroups/etc via API, and I found one little bug. 
If I create one host and delete (with cascade) and re-create it x times, then icingaweb2 cant find it.
When this happens, I can see the Host and it services via API, but not in icingaweb2. The services are checked without any problem and I can see that via API.

For fix it, I must do one reload of icinga2 and after icingaweb2 can find the host.
I think that has to do with the connection of the IDO-Mysql because the host is sync in every icinga2 satellite.

PS: The Transport of our icingaweb2 is the API, not more the command file.

Icinga2 version: r2.6.1-1
Icingaweb2 version: 2.4.1

Regards,
Christian Moreno

**Comment by dgoetz** [comment]
Can you verify that the host is not set to is_active=1 in the IDO after recreating it via API, but after restarting Icinga2? Then you hit issue https://github.com/Icinga/icinga2/issues/4040

**Comment by christianVLC** [comment]
Hi Dirk,

yes, I checked just now and after create the host via API, host&services are in the IDO like is_active=0.

After the reload, then is_active is updated.

Many Thanks, I will follow the other issue.

**Comment by dnsmichi** [comment]
I'll close this one.
