### ISSUE TITLE
Add querytype to dns check

### ISSUE THREAD

**Issue by mzac** [Icinga/icinga2#5046]
I would like to recomend adding the 'querytype' to the 'dns' check in the command-plugins.conf

 -q, --querytype=TYPE
    Optional DNS record query type where TYPE =(A, AAAA, SRV, TXT, MX, ANY)
    The default query type is 'A' (IPv4 host entry)

<pre>
"-q" = {
    value = "$dns_query_type"
    description = "Optional DNS record query type where TYPE =(A, AAAA, SRV, TXT, MX, ANY)"
}
</pre>

**Comment by dnsmichi** [comment]
Can you please send a PR including the patch and documentation? :)

**Comment by mzac** [comment]
Changes added in #5047

**Comment by gunnarbeutner** [comment]
Merged, thank you. :)

**Comment by towolf** [comment]
@gunnarbeutner @mzac please read:

From all I can see on the Icinga docs about ITL, Icinga2 supports the monitoring-plugins suite, and not the nagios-plugins suite.

But only the latter supports the `-q` flag. Why did you add this when the supported plugin suite does not support it?

https://www.monitoring-plugins.org/doc/man/check_dns.html
https://nagios-plugins.org/doc/man/check_dns.html

**Comment by towolf** [comment]
cf: https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/plugin-check-commands?highlight-search=dns#plugin-check-command-dns

**Comment by gunnarbeutner** [comment]
There's no harm in supporting additional arguments. Plus I'm assuming that the two projects are at least somewhat interested in keeping their argument names compatible, as in... there's a fairly low chance that monitoring-plugins would introduce a `-q` option that does something entirely different from what nagios-plugins does.

**Comment by towolf** [comment]
The check fails for us now. We wanted to try the 2.6.4 snapshot for the downtime reload notification spam, that we a re suffering from.

**Comment by towolf** [comment]
![image](https://user-images.githubusercontent.com/345210/27635955-863c4a2c-5c09-11e7-838e-55a3d8d2e981.png)

**Comment by gunnarbeutner** [comment]
Oh, I see, can you submit a bug report for this please? This ticket is already closed.

**Comment by towolf** [comment]
@gunnarbeutner done:

https://github.com/Icinga/icinga2/issues/5383
