### ISSUE TITLE
API Query endpoint object shows version 0.0

### ISSUE THREAD

**Issue by helgein** [Icinga/icinga2#5049]
I can not find a description of the endpoint object properties in the docs.

Luckily, the number of andpoints in my environment increase,
Thus a need arises to find out all icinga2 daemon version numbers so that i can track which nodes to update.

If i misunderstand the version field below, i still feel that this information should be exactly in that location - for the above reason.

```
# curl -k -s -u director:test 'https://localhost:5665/v1/objects/endpoints' | python2.7 -m json.tool
...
        {
            "attrs": {
                "__name": "workstation02l",
                "active": true,
                "connected": true,
                "connecting": false,
                "ha_mode": 0.0,
                "host": "",
                "local_log_position": 1488621327.313225,
                "log_duration": 86400.0,
                "name": "workstation02l",
                "original_attributes": null,
                "package": "_etc",
                "paused": false,
                "port": "5665",
                "remote_log_position": 1488621327.311926,
                "syncing": false,
                "templates": [
                    "workstation02l"
                ],
                "type": "Endpoint",
                "version": 0.0,              # < i feel here should be the version 2.6.2
                "zone": ""
            },
            "joins": {},
            "meta": {},
            "name": "workstation02l",
            "type": "Endpoint"
        }
    ]
}

```

**Comment by dnsmichi** [comment]
That's the config object version which is described here: https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/object-types
It's initialised to 0 if its package was `_etc` (a static compiled config file).

**Comment by helgein** [comment]
> If i misunderstand the version field below, i still feel that this information should be exactly in that location - for the above reason.

- Would it really be that hard to add this information here ?
- Why do you think it is not wise to have that information here ?
- Any better way to aquire the daemons version number ?

**Comment by dnsmichi** [comment]
`version` works as described, this is the internal's object's version. You can fetch the application's version by querying /v1/status or /v1/objects/icingaapplications/app
