### ISSUE TITLE
Feature, environment, variable, ICINGA_CONFIGDIR

### ISSUE THREAD

**Issue by kobmaki** [Icinga/icinga2#5050]
Feature: An environment variable ICINGA_CONFIGDIR which points to the directory where all configurations for icinga2 is located. The default value should be /etc/icinga2 on unix like systems.	

Use cases are:

* Training
* Automated tests with one installation
* Run an instance with a configuration which is not below the /etc/icinga2  directory

This is similiar to the icingaweb2 posibility by setting the enviroment variable ICINGAWEB_CONFIGDIR to the used config directory.

**Comment by dnsmichi** [comment]
Why don't you just use SysconfDir?

**Comment by kobmaki** [comment]
When you try to run an icinga2 command you have to add always more options then the SysconfDir to the command. Some commands requires the definition for the SysconfigDir other the LocalStateDir and of course the option for the user and group. This makes it difficult to run from the "plain" icinga2 command.

Following enviroment: 
* Installation from the repo
* Running as non-root and not as nagios user
* Add the /usr/sbin path to your PATH variable
`export PATH=/usr/sbin:$PATH`
* Make some directories
`mkdir -p ${HOME}/etc/icinga2/features-available/`
`mkdir -p ${HOME}/var/cache/icinga2`
`mkdir -p ${HOME}/var/log/icinga2/crash`
`mkdir -p ${HOME}/var/run`
* Create a dummy feature
  `touch ${HOME}/etc/icinga2/features-available/newfeature.conf`
* Create a minmalistic icinga2.conf:
`echo 'LocalStateDir="'$(echo ${HOME})/etc/icinga2/icinga2.conf'"' >> ${HOME}/etc/icinga2/icinga2.conf`
`echo 'PidPath="'${HOME}/var/run/icinga2.pid'"' >> ${HOME}/etc/icinga2/icinga2.conf`
* create minimal init.conf, but it doesn't helps here:
`echo 'const RunAsUser = "'$(id -un)'"'  > ${HOME}/etc/icinga2/init.conf`
`echo 'const RunAsGroup = "'$(id -gn)'"'  >> ${HOME}/etc/icinga2/init.conf`
Run command icinga2 feature list:
`icinga2 feature list -DSysconfDir=${HOME}/etc`
<pre>
critical/cli: setgroups() failed with error code 1, "Operation not permitted"
critical/cli: Please re-run this command as a privileged user or using the "nagios" account.</pre>


Run command feature list with all options:
`icinga2 feature list -DSysconfDir=$(echo ${HOME})/etc -DRunAsGroup=$(id -ng) -DRunAsUser=$(id -un)`
<pre>
Disabled features: newfeature
Enabled features: 
</pre>

Run command daemon with all options:
`icinga2 daemon -c $(echo ${HOME})/etc/icinga2/icinga2.conf -DSysconfDir=$(echo ${HOME})/etc/icinga2 -DRunAsGroup=$(id -ng) -DRunAsUser=$(id -un) -DLocalStateDir=$(echo ${HOME})/var`

Now you have a minimal running installation.

Run command object list:
`icinga2 object list -DSysconfDir=$(echo ${HOME})/etc/icinga2 -DRunAsGroup=$(id -ng) -DRunAsUser=$(id -un)  -DLocalStateDir=$(echo ${HOME})/var`

<pre>
Object 'app' of type 'IcingaApplication':
  % declared in '', lines 0:0-0:0
  * __name = "app"
  * enable_event_handlers = true
  * enable_flapping = true
  * enable_host_checks = true
  * enable_notifications = true
  * enable_perfdata = true
  * enable_service_checks = true
  * name = "app"
  * package = ""
  * templates = [ "app" ]
    % = modified in '', lines 0:0-0:0
  * type = "IcingaApplication"
  * vars = null
  * zone = ""
</pre>

Wouldn't it be easier by simple define one variable:
`export ICINGA_CONFIGDIR=${HOME}/etc/icinga2`

**Comment by dnsmichi** [comment]
Well, maybe. I'm not a fan of supporting custom handmade setups. Instead I suggest to run monitoring on a dedicated server and use packages wherever possible. So yeah, I understand your issue but that's nothing I'd like to support except for the things already there. Just as SysconfDir and other constants.

**Comment by Thomas-Gelf** [comment]
:+1:

@kobmaki: I like the idea. A combination of `ICINGA_CONFIGDIR` & `ICINGA_STATEDIR` would be great. As you mentioned, perfect for testing, trainings, spinning up "distributed" environments in a lab, containerized setups. I agree, the current way makes things more complicated than required
@dnsmichi: this does not conflict with using packages. In modern environments packages should ship the software and everything you need to run it. In addition to this, our packages currently ship an opinionated way of running the software. This makes it easy for newbies trying to get a quick first result. But it makes it hard for people trying to run custom/distributed/scaling/volatile environments. Modern scalable software should try to follow best practices like [The Twelve-Factor App](https://12factor.net/). Sure, not everybody using Icinga would see any benefit in this. Still, providing everything one needs to run a containerized and/or environment-driven Icinga would IMHO be a valuable feature for those who need such

**Comment by dnsmichi** [comment]
Closing in favour of #5084.
