### ISSUE TITLE
Feature, ImpersonateLevel, all defined levels, configureable

### ISSUE THREAD

**Issue by kobmaki** [Icinga/icinga2#5051]
The icinga2 source code  has three different user levels (https://github.com/Icinga/icinga2/blob/master/lib/cli/consolecommand.cpp):

<pre>
enum ImpersonationLevel
{
        ImpersonateNone,
        ImpersonateRoot,
        ImpersonateIcinga
};
</pre>

It is not possible to set the ImpersonateNone and ImpersonateRoot. Neither as user nor as group.
The ImpersonateIcinga is actuall configure by `RunAsUser` and `RunAsGroup`.

Would be nice to configure the ImpersonateRoot by `RootAsUser` and `RootAsGroup` and the ImpersonateNone by `NoneAsUser` and `NoneAsGroup`.

This will help in solving "Allow to run cli without root" https://github.com/Icinga/icinga2/issues/4947 but gives also the possibilty to set the "none level" or restrict something on group level.

The possible new values should be in the /etc/icinga2/init.conf

Default behavior should be like it is today. RootAsUser => root, RootAsGroup => root.
The ImpersonateNone is used only on console command. Today there is no real restriction on the user or group in ImpersonateNone.

**Comment by dnsmichi** [comment]
I really do not understand that feature request, especially the naming with `RootAsUser` is misleading from a user's perspective. How would that solve #4947?

**Comment by Crunsher** [comment]
As we are reworking a lot of the init system and want to phase out init.conf, there will be changes to this.

I'll close this because it is old and it won't apply anymore.

**Comment by kobmaki** [comment]
Is the working on the init system the issue https://github.com/Icinga/icinga2/issues/5904 "Reference Icinga2 daemon environment in configuration"?

**Comment by gunnarbeutner** [comment]
Nah, that'd be #5850. I'll have a look at #5904 though. 😊
