### ISSUE TITLE
Replay log not working with Windows client

### ISSUE THREAD

**Issue by pcasis** [Icinga/icinga2#5052]
(Issue created regarding this thread : https://monitoring-portal.org/index.php?thread/40004-replay-logs-not-working-when-windows-server-client-reconnect/)
____

Hey,

Replay log is not working with Windows client. :cry: 
The current file is correctly created while the connection is down.
After reconnection, the file is replayed.

However, data is missing in InfluxDB or Graphite.
There isn't special mechanism in place.

Tested with : 
- 2.6.2 Master.
- 2.6.0, 2.6.1 and 2.6.2 Windows client.

Regards

**Comment by helgein** [comment]
Can confirm the above using
master: 2.6.2
Win10 Agent: 2.6.0

No special mechanisms in place.
"current" file captured before replayed and attached.

First screenshot taken with graphite feature enabled, influxdb feature disabled.
Second screenshot taken with graphite feature disabled, influxdb feature enabled.
Both backends do not get the data.

No time issues (both machines are virtual boxes at the same notebook...),
even if graphite seems to have it's own timezone.
![2017-03-06 05_01_23-greenshot](https://cloud.githubusercontent.com/assets/14905554/23604927/f71b7e1a-025a-11e7-8139-587ec134df92.png)
![virtualbox_win2012r2 - debian 8 6 uefi_04_03_2017_20_21_23](https://cloud.githubusercontent.com/assets/14905554/23604926/f71963be-025a-11e7-80a7-fe7f0dcb2877.png)
![virtualbox_win2012r2 - debian 8 6 uefi_04_03_2017_21_06_29](https://cloud.githubusercontent.com/assets/14905554/23604928/f71c0678-025a-11e7-8bdf-5168dae33b26.png)
[current.zip](https://github.com/Icinga/icinga2/files/820713/current.zip)

**Comment by dnsmichi** [comment]
Could be related:

```
(void) rename(oldpath.CStr(), newpath.CStr());
```

might need an additional _unlink similar to other rename operations inside the code.

@N-o-X can you please have a look into this too? :)
