### ISSUE TITLE
Missing documentation for macro()

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5060]
https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/library-reference#global-functions

**Comment by gunnarbeutner** [comment]
macro() is *not* a global function though.

**Comment by dnsmichi** [comment]
Offline chat: macro() only is available in functions which are specified for custom attributes.
