### ISSUE TITLE
Database freeze on multiple GUI queries

### ISSUE THREAD

**Issue by Simnol** [Icinga/icinga2#5066]
Hi,

Not sure if this is the correct place to report, but happy to update/move if needed.

I've noticed in our test instance that a database lockup can happen, if there are multiple failures/notifications in the database being queried (in the region of 21000 over the last few days.) 

The system trundles along happily with these failures usually, but if you try and use any of the three panels in the Web GUI:

Event Overview, Notification, or Timeline - (Under History)

It can cause the system to become completely unresponsive.

This seems to be bacause of the various queries used, which creates tmp tables:
```
MariaDB [(none)]> show processlist;
+------+--------+-----------+---------+---------+------+----------------------+------------------------------------------------------------------------------------------------------+----------+
| Id   | User   | Host      | db      | Command | Time | State                | Info                                                                                                 | Progress |
+------+--------+-----------+---------+---------+------+----------------------+------------------------------------------------------------------------------------------------------+----------+
|  686 | icinga | localhost | icinga2 | Sleep   |    1 |                      | NULL                                                                                                 |    0.000 |
| 3140 | root   | localhost | NULL    | Query   |    0 | NULL                 | show processlist                                                                                     |    0.000 |
| 3145 | icinga | localhost | icinga2 | Query   |    4 | Copying to tmp table | SELECT eh.type AS name, eh.timestamp AS time FROM (SELECT sth.timestamp, sth.output, sth.type, sth.s |    0.000 |
| 3146 | icinga | localhost | icinga2 | Query   |    1 | Copying to tmp table | SELECT COUNT(*) AS cnt FROM ((SELECT h.display_name COLLATE latin1_general_ci AS host_display_name,  |    0.000 |
+------+--------+-----------+---------+---------+------+----------------------+------------------------------------------------------------------------------------------------------+----------+
```

The page eventually loads, and the database finishes working, but if you're an end user, and you keep hitting refresh, or try to open all three in succession, it can cause /tmp to fill up quickly. (Reproduced reliably a few times.) 

Seems related to this bug from MariaDB:

https://jira.mariadb.org/browse/MDEV-5258?workflowName=MariaDB+v3&stepId=1

**Comment by Simnol** [comment]
Obviously in a real world example, you wouldn't expect to have a few hundred host failures (as is the case in this lab) but I could forsee larger instances having this problem, especially as it can be caused by any end-user that might have access to those specific panes.

I hit them a couple more times:

```
```

Here's the output of /tmp (still growing.)

```

**Comment by dnsmichi** [comment]
Those queries are effectively fired by Icinga Web 2 which uses the same database credentials as Icinga 2. I'd suggest opening a new issue over at icinga/icingaweb2.

**Comment by Simnol** [comment]
Thanks, I'll close this here and will raise it under Icinga2web
