### ISSUE TITLE
Missing doc on how folders are handled

### ISSUE THREAD

**Issue by pcasis** [Icinga/icinga2#5071]
Hi,

Issue opened regarding this forum thread : 
[https://monitoring-portal.org/index.php?thread/40101-how-is-the-etc-icinga2-folder-handled-when-updated/](https://monitoring-portal.org/index.php?thread/40101-how-is-the-etc-icinga2-folder-handled-when-updated/)

It might be a good think to add some informations about how holders are handled.
In other words : 

- Is it possible to create folder inside Icinga2's default folder ?
- Are custom folders deleted or saved when Icinga2 is updated ?
- ...

Regards

**Comment by dgoetz** [comment]
For RPM:
All Files under /etc/icinga2 are marked as %config(noreplace) which will result in on update:
* files / folders unchanged -> nothing happens
* files changed -> file from package will be created as .rpmnew
* files / folders deleted -> file from package will be reinstalled
* files / folders permissions changed -> permissions will be restored
* additional files / folders created -> nothing happens

On uninstall:
* files folders unchanged/changed/deleted -> nothing special happens, everything is deleted
* additional files created -> files will be keeped including required folder structure (this is also true for files like symlinks for feature activation as long as they are not marked as ghost and so "included" in the package)

**Comment by dnsmichi** [comment]
Feel free to send in a docs PR.

**Comment by Al2Klimov** [comment]
At the moment [the doc](https://github.com/Icinga/icinga2/blob/d9422feb5e40d91c59635b75a6e70f369df63164/doc/04-configuration.md#your-configuration-) clearly states the validity of the custom directory tree opinion.

@pcasis Doesn’t this imply that our packages handle this (a non-surprising way)?

**Comment by Al2Klimov** [comment]
All quiet on the western front = all good on the western front.
