### ISSUE TITLE
Livestatus hostsbygroup and servicesbyhostgroup do not work

### ISSUE THREAD

**Issue by gitmopp** [Icinga/icinga2#5078]
As you can see in the example below the Icinga 2 Livestatus only reports the other hostgroup and not the hostgroup from the Filter "My Test Group".
If the host of "My Test Group" is only in one hostgroup Livestatus will report the hostgroup "My Test Group".
If the host is in two hostgroups it will only report "My other Testhostgroup".
The same problem applys also to servicesbyhostgroup.
Tools like NagVis will not work with Icinga2 Livestatus in this case. The chec_mk livestatus will always report the group you filter for, in this case "My Test Group" and then it will report any additional group. Icinga2 skips the primary group "My Test Group" if the host is also member in "My other Testhostgroup"

This is the query NagVis runs:
```
GET hostsbygroup
Filter: groups >= My Test Group
Stats: has_been_checked = 0
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 4
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 4
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth > 0
StatsAnd: 3
Stats: state = 1
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 4
Stats: state = 1
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 4
Stats: state = 1
Stats: acknowledged = 1
StatsAnd: 2
Stats: state = 1
Stats: scheduled_downtime_depth > 0
StatsAnd: 2
Stats: state = 2
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 4
Stats: state = 2
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 4
Stats: state = 2
Stats: acknowledged = 1
StatsAnd: 2
Stats: state = 2
Stats: scheduled_downtime_depth > 0
StatsAnd: 2
Columns: hostgroup_name hostgroup_alias
OutputFormat: json
KeepAlive: on
ResponseHeader: fixed16

200          77
[["My other Testhostgroup","My other Testhostgroup0,9,0,0,0,0,0,0,0,0,0,0]]
```

**Comment by dnsmichi** [comment]
If you've got a patch, we'll review and merge it. Please be aware that this not only involves fixing the result set, but also requires making the aggregator code "stats"-aware.

**Comment by dnsmichi** [comment]
https://raw.githubusercontent.com/NagVis/nagvis/master/share/server/core/classes/GlobalBackendmklivestatus.php

```
        // Get host information
        $q = "GET hosts".$host_suffix."\n" .
            $host_filter.
            // Count UNCHECKED
            "Stats: has_been_checked = 0\n" .
            // Count UP
            "Stats: ".$stateAttr." = 0\n" .
            "Stats: has_been_checked != 0\n" .
            "Stats: scheduled_downtime_depth = 0\n" .
            "Stats: staleness < ".$staleness_thresh."\n" .
            "StatsAnd: 4\n" .
            // Count UP(STALE)
            "Stats: ".$stateAttr." = 0\n" .
            "Stats: has_been_checked != 0\n" .
            "Stats: scheduled_downtime_depth = 0\n" .
            "Stats: staleness >= ".$staleness_thresh."\n" .
            "StatsAnd: 4\n" .
            // Count UP (DOWNTIME)
            "Stats: ".$stateAttr." = 0\n" .
            "Stats: has_been_checked != 0\n" .
            "Stats: scheduled_downtime_depth > 0\n" .
            "StatsAnd: 3\n" .
            // Count DOWN
            "Stats: ".$stateAttr." = 1\n" .
            "Stats: acknowledged = 0\n" .
            "Stats: scheduled_downtime_depth = 0\n" .
            "Stats: staleness < ".$staleness_thresh."\n" .
            "StatsAnd: 4\n" .
            // Count DOWN(STALE)
            "Stats: ".$stateAttr." = 1\n" .
            "Stats: acknowledged = 0\n" .
            "Stats: scheduled_downtime_depth = 0\n" .
            "Stats: staleness >= ".$staleness_thresh."\n" .
            "StatsAnd: 4\n" .
            // Count DOWN(ACK)
            "Stats: ".$stateAttr." = 1\n" .
            "Stats: acknowledged = 1\n" .
            "StatsAnd: 2\n" .
            // Count DOWN(DOWNTIME)
            "Stats: ".$stateAttr." = 1\n" .
            "Stats: scheduled_downtime_depth > 0\n" .
            "StatsAnd: 2\n" .
            // Count UNREACHABLE
            "Stats: ".$stateAttr." = 2\n" .
            "Stats: acknowledged = 0\n" .
            "Stats: scheduled_downtime_depth = 0\n" .
            "Stats: staleness < ".$staleness_thresh."\n" .
            "StatsAnd: 4\n" .
            // Count UNREACHABLE(STALE)
            "Stats: ".$stateAttr." = 2\n" .
            "Stats: acknowledged = 0\n" .
            "Stats: scheduled_downtime_depth = 0\n" .
            "Stats: staleness >= ".$staleness_thresh."\n" .
            "StatsAnd: 4\n" .
            // Count UNREACHABLE(ACK)
            "Stats: ".$stateAttr." = 2\n" .
            "Stats: acknowledged = 1\n" .
            "StatsAnd: 2\n" .
            // Count UNREACHABLE(DOWNTIME)
            "Stats: ".$stateAttr." = 2\n" .
            "Stats: scheduled_downtime_depth > 0\n" .
            "StatsAnd: 2\n".
            $host_grouping;
        $l = $this->queryLivestatus($q);
```

```
            foreach($l as $e) {
                // Workaround for Icinga 2 which answers stats queries for not existing objects with
                // 0 stats but with missing host_name and host_alias columns. So the number of answer
                // columns is different leading to an exception in the code below.
                if (count($e) != 12+$hoffset)
                    continue;
```

**Comment by dnsmichi** [comment]
Some ongoing tests inside the Vagrant box:

![screen shot 2017-08-14 at 16 17 55](https://user-images.githubusercontent.com/382049/29275729-5b780696-810c-11e7-9e3c-0a6e9b8cc886.png)
![screen shot 2017-08-14 at 16 17 47](https://user-images.githubusercontent.com/382049/29275731-5c0eaca4-810c-11e7-9ab5-9cf9b7e5b99d.png)
![screen shot 2017-08-14 at 16 17 43](https://user-images.githubusercontent.com/382049/29275730-5b78b2b2-810c-11e7-87e1-111e23d27dc5.png)

**Comment by dnsmichi** [comment]
## Tests

The required NagVis configuration will be made available inside the Vagrant box "icinga2x" soon.

### 2.7.0


NagVis and Livestatus without the patch just say, that they cannot find the hostgroups.

```
vim get_hosts

GET hosts
Filter: groups >= linux-servers
Columns: name groups
ResponseHeaders: fixed16

```

```
[root@icinga2 local]# nc -U /var/run/icinga2/cmd/livestatus < get_hosts
c1-mysql-1;bp-hosts-mysql,linux-servers
c2-mysql-2;bp-hosts-mysql,linux-servers
c1-web-1;bp-hosts-mysql,bp-hosts-web,linux-servers
icinga2;linux-servers
```

![screen shot 2017-08-15 at 15 01 42](https://user-images.githubusercontent.com/382049/29317115-d89e0490-81ca-11e7-8cb2-8ed9cb3222d9.png)


### Fix

![screen shot 2017-08-15 at 15 11 01](https://user-images.githubusercontent.com/382049/29317408-1ec82698-81cc-11e7-9379-20736ecdb661.png)

![screen shot 2017-08-15 at 15 13 26](https://user-images.githubusercontent.com/382049/29317455-51678238-81cc-11e7-9f06-80a52bf9c299.png)

**Comment by dnsmichi** [comment]
# Test notes

Whoever may test the issue being resolved, please continue like this.

**Write a test protocol including screenshots**

- Clone a fresh Vagrant box or use a seperate VM with snapshot packages of Icinga 2 and Icinga Web 2, including Nagvis+module setup.

```
git clone https://github.com/icinga/icinga-vagrant
cd icinga-vagrant/icinga2x
vagrant destroy -f && vagrant up
```

- Ensure that `icinga2 --version` is more recent than `v2.7.0-49` (49 is a running number)

## Manual queries

- Install netcat i.e. on CentOS `yum -y install nc`
- Build your own queries and also test the example queries

Docs: https://mathias-kettner.de/checkmk_livestatus.html

Queries:

```
GET hostsbygroup
Filter: groups >= linux-servers
Stats: state = 0
Stats: state != 0
Columns: hostgroup_name
OutputFormat: json
KeepAlive: on
ResponseHeader: fixed16

```

```
GET hostsbygroup
Filter: groups >= linux-servers
Stats: has_been_checked = 0
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 4
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 4
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth > 0
StatsAnd: 3
Stats: state = 1
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 4
Stats: state = 1
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 4
Stats: state = 1
Stats: acknowledged = 1
StatsAnd: 2
Stats: state = 1
Stats: scheduled_downtime_depth > 0
StatsAnd: 2
Stats: state = 2
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 4
Stats: state = 2
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 4
Stats: state = 2
Stats: acknowledged = 1
StatsAnd: 2
Stats: state = 2
Stats: scheduled_downtime_depth > 0
StatsAnd: 2
Columns: hostgroup_name hostgroup_alias
OutputFormat: json
KeepAlive: on
ResponseHeader: fixed16

```


Run example:

```
(cat test_hg ; sleep 1) | nc -U /var/run/icinga2/cmd/livestatus
```


## NagVis

- Start the Vagrant box
- Navigate into Icinga Web 2 - Maps - NagVis

- Options - Manage Backends - Select `livestatus` from the dropdown and save it

![screen shot 2017-08-16 at 14 50 58](https://user-images.githubusercontent.com/382049/29364030-7da4b5de-8292-11e7-9c51-036fcb1e2b92.png)
![screen shot 2017-08-16 at 14 51 08](https://user-images.githubusercontent.com/382049/29364031-7da6e8ea-8292-11e7-8512-57bfe3d4b96e.png)
![screen shot 2017-08-16 at 14 51 19](https://user-images.githubusercontent.com/382049/29364029-7da422d6-8292-11e7-866a-a6fd04033e84.png)

- Reload the page and navigate into the 2 demo maps.

- Create your own maps with hostgroups/servicegroups and ensure that every stats popup is working fine (screenshots as proof).

## Thruk

- Install Thruk somewhere applicable and point it to the Icinga 2 livestatus socket.

https://labs.consol.de/repo/stable/#_7

```
rpm -Uvh "https://labs.consol.de/repo/stable/rhel7/i386/labs-consol-stable.rhel7.noarch.rpm"
yum -y makecache
yum -y install thruk
systemctl restart httpd

```

Thruk webserver doesn't like our auth, but that doesn't matter for tests. Fake REMOTE_USER needed.

```
vim /etc/httpd/conf.d/thruk.conf

  <Directory /usr/share/thruk>

    SetEnv REMOTE_USER "thrukadmin"

systemctl restart httpd
systemctl restart thruk
```

- Navigate to http://192.168.33.5/thruk into `Configuration`
- Add a new backend pointing to `/var/run/icinga2/cmd/livestatus` (test the connection)

![screen shot 2017-08-16 at 15 14 12](https://user-images.githubusercontent.com/382049/29364995-af1e3e48-8295-11e7-82eb-d456a93bd961.png)




- Test all views from inside the left menu and report them working (screenshot as proof)

## Multisite

This is out of scope, since CheckMK regularly adds new columns without further notice (aka not compatible).

**Comment by mwaldmueller** [comment]
The patch works as expected and should be planned for the next release.
