### ISSUE TITLE
Windows client: Running multiple instances per node

### ISSUE THREAD

**Issue by xenuser** [Icinga/icinga2#5084]
I have an unusual feature request and I am sorry if this feature either was already built in (and thrown out) before. I searched GitHub and the web but did not find any clues, which is why I write this feature request.

I have an Icinga2 installation with several hundred nodes to be monitored (mostly Windows servers).
There are multiple "groups of interests" (e.g. several different service providers), all of them running their own monitoring system. Icinga2 is one of them and all nodes are monitored by multiple systems.

In this case, another Icinga2 installation popped up and suddenly some Windows nodes have to be monitored by two Icinga2 installations.

I tried to setup two Icinga2 agents/clients on a Windows test system, but it doesn't work. I am not able to configure the name of the Icinga2 service and the path of the working dir, so there are duplicates and I can't install/run two Icinga2 installations on the same node at the same time.

In my opinion, it should be possible to lunch multiple Icinga2 agents per node, in order to have some sort of multi-tenancy-ability.

I know that this specific scenario sounds weird and normally, you would try to decide for only one monitoring solution (and instance). However, sometimes you have to deal with the way things are.

Btw: I tried to create a copy of the Icinga2 service:

```
sc.exe create Icinga2-littlebrother binPath= "D:\ICINGA2\sbin\icinga2.exe --scm """daemon""""
```

This actually works, but as soon as I start the new service, Windows throws me an error saying that I am trying to run an interactive service which is not supported. Both services seem to be configured identically, though... And there are no entries within the Icinga2 logs or the Windows Event Viewer.

PS: I am also thinking about running two Icinga2 agents per Linux node...

**Comment by dnsmichi** [comment]
Related: #5050 #4947

**Comment by TheFlyingCorpse** [comment]
For windows, the Nano server PR is almost ready with this, it's binaries work relatively to where it is stored. You would only need to override the SysConf directory which is by default `%PROGRAMDATA%\Icinga2`, that might be a patch away if it is not already supported.

**Comment by xenuser** [comment]
Thanks you @TheFlyingCorpse  for informing me about the upcoming change!
Can you please get more into detail regarding the SysConf directory override - where would one do that?
Is that related to the Windows env var or will one be able to configure this somewhere?

Sorry if this is a dumb questions, I am not really much into Windows..

**Comment by TheFlyingCorpse** [comment]
The arguments are the same on Linux.

The current version of Icinga2 will allow you to run with an alternative SysconfDir and LocalStateDir, while the PR I have waiting for feedback on will allow you to have a separate copy of the binaries entirely as well.

To run Icinga2 with an alternative configuration and statedir (you ought to do both) while using the already present one:
`"C:\Program Files\ICINGA2\sbin\icinga2.exe" daemon -D SysconfDir=D:\ProgramData\icinga2\etc -D LocalStateDir=D:\ProgramData\icinga2\var`

This of course means that you have the relevant folders on D: for this, set the correct permissions and have the correct skeleton in place.
This does not mean you have a valid Windows Service registered, if you want it to run as its own Windows Service, this must be registered as well, it will very likely conflict here with a different installation of itself (as it doesnt register with a new name but what it already uses) so you might end up going down the route of using NSSM to run a "icinga2.exe daemon <params>" per instance.
I have a powershell module that I tinker with that will create the skeleton, it remains to set the proper ACL's.

Do also note these clients will likely require NetworkService, if not LocalSystem privileges. With the separation you have proposed by it being separate instances of the same service, if remote config sync is planned to be used, you do own basically own the _entire_ system, so both this features needs to be investigated if it will not make the attack surface too big. If they can modify locally, this is another risk factor.

**Comment by xenuser** [comment]
Thank you for elaborating! I appreciate it.

**Comment by dnsmichi** [comment]
Keep in mind that those setups are hard to troubleshoot and maintain, and generally remain unsupported.
