### ISSUE TITLE
flapping entry in history/DB for every reload

### ISSUE THREAD

**Issue by darmagan** [Icinga/icinga2#5086]
Hi,

Icinga2 is writing a flapping entry for every reload even if there is no state change.

Icinga 2.6.0

Regards

**Comment by dnsmichi** [comment]
Hi Deniz,

I'd appreciate it if you could add additional logs and configs to reproduce the issue. It is probably related to #4982 which is still pending being fixed.

Is the issue reproducible with v2.6.2 instead of v2.6.0?

Kind regards,
Michael

**Comment by ClemensBW** [comment]
Hello,

we use Icinga 2.6.2. Looks like this happens only if the check source is not localhost (but in the same HA  cluster, if you use a icinga2 agent in a other dmz, is not part of the ha cluster we don't have this behave.

(for example service "ping quality" not have only single flapping if we reload Icinga2, for other (active and passive) services we have, for every icinga2 reload, a single flapping event ("Flapping with a 0,00% state change rate")

Config for both example services at the same host:

Note that Service: "ping quality" has a other check source as Service "XYZ Checker".

History for Service: "ping quality" (check source at custer1):

> Donnerstag, Februar 16, 2017
> OK
> 13:57:56
> 	
> 
> [ 1/3 ] OK - 10.X.X.11: rta 13.561ms, lost 0%

History for Service: "XYZ Checker" (check source at custer2):
> Dienstag, März 21, 2017
> FLAPPING BEENDET
> 09:48:01
> 	
> 
> Flapping with a 0,00% state change rate
> FLAPPING BEENDET
> 09:47:20
> 	
> 
> Flapping with a 0,00% state change rate
> Montag, März 20, 2017
> FLAPPING BEENDET
> 17:55:15
> 	
> 
> Flapping with a 0,00% state change rate
> FLAPPING BEENDET
> 17:54:35
> 	
> 
> Flapping with a 0,00% state change rate
> FLAPPING BEENDET
> 17:54:30
> 	
> 
> Flapping with a 0,00% state change rate
> FLAPPING BEENDET
> 09:51:28
> 	
> 
> Flapping with a 0,00% state change rate
> Freitag, März 17, 2017
> FLAPPING BEENDET
> 16:43:12
> 	
> 
> Flapping with a 0,00% state change rate
> FLAPPING BEENDET
> 16:42:10
> 	
> 
> Flapping with a 0,00% state change rate
> FLAPPING BEENDET
> 16:42:06
> 	
> 
> Flapping with a 0,00% state change rate
> FLAPPING BEENDET
> 15:16:23
> 	
> 
> Flapping with a 0,00% state change rate
> FLAPPING BEENDET
> 14:39:00
> 	
> 
> Flapping with a 0,00% state change rate
> FLAPPING BEENDET
> 14:38:14
> 	
> 
> Flapping with a 0,00% state change rate
> [...]

**Comment by darmagan** [comment]
Hi,

I have tested it in following scenarios and can just reproduce it on the 2.6.1 version:
2.6.2:
local check -> works (1 entry, several restarts and reloads)
remote -> same
master-master, local check -> same
master-master, remote check(check-source other master) -> works
2.6.1:
If I look in the history on the other Master(2.6.1 version) there are multiply flapping entries for every scenario.

I have attached the logs.

[2.6.1.log.tar.gz](https://github.com/Icinga/icinga2/files/857983/2.6.1.log.tar.gz)


[2.6.2.log.tar.gz](https://github.com/Icinga/icinga2/files/857986/2.6.2.log.tar.gz)

zones.conf on both nodes
```
object Endpoint "box6.int.netways.de" {
  host = "192.168.33.16"
}

object Endpoint "box16.int.netways.de" {
  host = "192.168.33.26"
}
object Zone "master" {
  endpoints = [ "box6.int.netways.de", "box16.int.netways.de" ]
}

```

**Comment by darmagan** [comment]
Hi,

I have tested again with both nodes on 2.6.2. And the behavior  is the same. So the problem is not the version of the node. The Issue is only reproducible on the not-config-master node.

How to reproduce:
-Master zone with two nodes
-Check object in master zone
-Restart Icinga2 service on the check source 2 times with 1-2 seconds between
-Reload history. Another flapping entry will be written

![auswahl_012](https://cloud.githubusercontent.com/assets/25243900/24245394/fc3fd89e-0fc2-11e7-8a77-6686d12d3a32.png)
 
[box17.debug.log.tar.gz](https://github.com/Icinga/icinga2/files/864470/box17.debug.log.tar.gz)
[box18.debug.log.tar.gz](https://github.com/Icinga/icinga2/files/864469/box18.debug.log.tar.gz)

Zones.conf
```
/*
 * Endpoint and Zone configuration for a cluster setup
 * This local example requires `NodeName` defined in
 * constants.conf.
 */

object Endpoint "box17.int.netways.de" {
  host = "192.168.33.27"
}
object Endpoint "box18.int.netways.de" {
  host = "192.168.33.28"
}

object Zone "master" {
  endpoints = [ "box18.int.netways.de", "box17.int.netways.de"]
}

/*
 * Defines a global zone containing templates,
 * etc. synced to all nodes, if they accept
 * configuration. All remote nodes need
 * this zone configured too.
 */

object Zone "global-templates" {
  global = true
}
```

**Comment by dnsmichi** [comment]
Okidoki, thanks for all the details :)

**Comment by dnsmichi** [comment]
Please test the snapshot packages.

**Comment by cbnorman** [comment]
2.8.0 seems to have resolved this problem, however i have so many flapping items in history now the db has become very slow and the history tab in icingaweb2 takes minutes to load. looking at the db `icinga=> select * from icinga_flappinghistory;` is huge and i dont really care for these, is it possible to delete these old items?

**Comment by dnsmichi** [comment]
Sure, it is your database. Just ensure you purge away with a selected time range. And have a backup beforehand.

Thanks for testing and the feedback 👍

**Comment by dgoetz** [comment]
Instead of manual clean up of the database you could also use the corresponding cleanup dictionary of the [IdoMySqlConnection](https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#idomysqlconnection).

**Comment by dnsmichi** [comment]
If that table contains a lot of entries, the cleanup job might take ages. I'd suggest to manually purge it during offline maintenance.
