### ISSUE TITLE
Downtime didn't work, Notifications were sent.

### ISSUE THREAD

**Issue by dhampel** [Icinga/icinga2#5088]
There are two Masterservers for our Icinga Landscape.
We had the problem that our Masterserver couldn't handle a downtime for a host. 

User sets downtime for host on Masterserver1. Masterserver1 tells Masterserver2 that there is a new downtime. Masterserver2 is working with the downtime without problems. Masterserver1 can't handle the downtime and we found following error in the logs.

[2017-03-21 15:22:37 +0100] critical/ApiListener: Could not create object '---Host---!---Service---!mgtmon043-1490105921-362':
[2017-03-21 15:22:37 +0100] critical/ApiListener: Configuration file '/var/lib/icinga2/api/packages/_api/mgtmon043-1448534702-1/conf.d/downtimes/---Host---!---Service---!mgtmon043-1490105921-362.conf' already exists

[root@mgtmon043:/icingalog] icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.6.1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: SLES
  Platform version: 12-SP2
  Kernel: Linux
  Kernel version: 4.4.21-90-default
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: d78601deca57

**Comment by dnsmichi** [comment]
Can you verify that the `_api` package on master1 is read on startup? It sounds like it is not, and as such master2 sends in a DowntimeAdded event, but storing then fails (as in, the file is already there). 

```
icinga2 daemon -x notice -C| grep _api
```

Please share the file tree like so (you can remove sensitive information). If it's too long just attach it as txt file here.

```
ls -lR /var/lib/icinga2/api/packages/_api
```

Details on the issue I'm thinking of: https://github.com/Icinga/icinga2/issues/3668#issuecomment-282365453

**Comment by dhampel** [comment]
Sorry for my late response. Thanks for your help!

When I send the first command, there is following output:

notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/_api/mgtmon043-1448534702-1/conf.d/downtimes/'Hostname'!mgtmon043-1490784462-202.conf

Is it possible to share the file with you directly? It is too large to remove the sensitive data and its not possible to upload this file with all these informations.

**Comment by dnsmichi** [comment]
I'm not particularly interested in the file contents of Downtime objects (or any other files underneath conf.d/ itself). You can use `find` instead and define and adjust the `-maxdepth` parameter as follows.

```
find /var/lib/icinga2/api/packages/_api/ -maxdepth 3
```

I'm also interested in the package handling config above, so pasting its content will help analyse the issue.

```
cat /var/lib/icinga2/api/packages/_api//active-stage
cat /var/lib/icinga2/api/packages/_api//active.conf
cat /var/lib/icinga2/api/packages/_api//include.conf
cat /var/lib/icinga2/api/packages/_api//$(cat /var/lib/icinga2/api/packages/_api//active-stage)/include.conf
```

**Comment by dhampel** [comment]
**find /var/lib/icinga2/api/packages/_api/ -maxdepth 3**

`/var/lib/icinga2/api/packages/_api/
/var/lib/icinga2/api/packages/_api/include.conf
/var/lib/icinga2/api/packages/_api/active.conf
/var/lib/icinga2/api/packages/_api/mgtmon043-1448534702-1
/var/lib/icinga2/api/packages/_api/mgtmon043-1448534702-1/conf.d
/var/lib/icinga2/api/packages/_api/mgtmon043-1448534702-1/conf.d/comments
/var/lib/icinga2/api/packages/_api/mgtmon043-1448534702-1/conf.d/downtimes
/var/lib/icinga2/api/packages/_api/mgtmon043-1448534702-1/zones.d
/var/lib/icinga2/api/packages/_api/mgtmon043-1448534702-1/include.conf
/var/lib/icinga2/api/packages/_api/active-stage
`
**cat /var/lib/icinga2/api/packages/_api//active-stage**

`mgtmon043-1448534702-1`

**cat /var/lib/icinga2/api/packages/_api//active.conf**

`if (!globals.contains("ActiveStages")) {
  globals.ActiveStages = {}
}

if (globals.contains("ActiveStageOverride")) {
  var arr = ActiveStageOverride.split(":")
  if (arr[0] == "_api") {
    if (arr.len() < 2) {
      log(LogCritical, "Config", "Invalid value for ActiveStageOverride")
    } else {
      ActiveStages["_api"] = arr[1]
    }
  }
}

if (!ActiveStages.contains("_api")) {
  ActiveStages["_api"] = "mgtmon043-1448534702-1"
}
`
**cat /var/lib/icinga2/api/packages/_api//include.conf**

`include "*/include.conf"`

**cat /var/lib/icinga2/api/packages/_api//$(cat /var/lib/icinga2/api/packages/_api//active-stage)/include.conf**

`include "../active.conf"
if (ActiveStages["_api"] == "mgtmon043-1448534702-1") {
  include_recursive "conf.d"
  include_zones "_api", "zones.d"
}
`

**Comment by dnsmichi** [comment]
Ok, thanks, so your downtime configuration is still included. Hm, another guess - the _api package is not in sync between the two master nodes. Can you check that by i.e. counting the files on conf.d/downtimes?

**Comment by dhampel** [comment]
The numbers of downtimes are on both masters the same. Seems like the sync is working. Since the last failure, we didn't see the problem again. 

Do you think its possible that the problem is generated by a bug?

**Comment by dhampel** [comment]
Ok we had the same problem 10 minutes ago, we checked the conf.d/downtimes immediately, but the numbers were the same.

**Comment by dnsmichi** [comment]
Can you add some logs, when the user sets the downtime via rest api / command pipe, from both masters? I still don't really know what's happened in your system.

**Comment by dhampel** [comment]
We located the problem. Everytime when the problem was there, there was a reload on the master.

For example:
Master1 started a reload at 15:43:38 (finished 15:45:10) and the sync to Master2 was started at 15:45:20.
At 15:45:55 Master1 was trying to sync a downtime to Master2, but there was still the reload running (finished 15:47). We had this problem yesterday several times and everytime it was the same scenario.

The downtime was triggered by a external command and this is not working over the API right now.

**Comment by Skap81** [comment]
After updating to 2.6.3, we have done more tests.
We tried to set the downtime through the external command pipe and the api. Both ways show the same results.

Because of the many service dependencies the Icinga2 relaod takes for the master1 about 3 minutes and then the master2 gets the reload command and the reload also takes about 3 minutes.

If a downtime is set in the time of the relaod, the error messages with the "already exists" appear after the reload on the master. Then the downtimes are not syncronous on the two master systems.

master1:

```
[2017-04-04 13:33:58 +0200] information/Application: Got reload command: Starting new instance.
...
[2017-04-04 13:36:53 +0200] information/Application: Received request to shut down.
[2017-04-04 13:36:53 +0200] information/Application: Shutting down...
[2017-04-04 13:36:53 +0200] information/CheckerComponent: Checker stopped.
...
[2017-04-04 13:37:13 +0200] information/HttpServerConnection: Request: POST /v1/actions/schedule-downtime (from [xxx.xxx.xxx.xxx]:17329, user: icinga2)
```

master2:
```
[2017-04-04 13:37:05 +0200] information/Application: Got reload command: Starting new instance.
...
[2017-04-04 13:39:46 +0200] information/ConfigItem: Committing config item(s).
[2017-04-04 13:39:46 +0200] information/ConfigItem: Instantiated 1 Downtime.
[2017-04-04 13:39:46 +0200] information/ConfigItem: Triggering Start signal for config items
[2017-04-04 13:39:46 +0200] information/ConfigItem: Activated all objects.
...
[2017-04-04 13:40:43 +0200] information/Application: Received request to shut down.
[2017-04-04 13:40:44 +0200] information/Application: Shutting down...
[2017-04-04 13:40:44 +0200] information/CheckerComponent: Checker stopped.
...
[2017-04-04 13:40:55 +0200] information/ApiListener: Syncing runtime objects to endpoint 'mgtmon033.a41mgt.local'.
[2017-04-04 13:40:55 +0200] critical/ApiListener: Could not create object 'HOST!master1-1491305832-0':
[2017-04-04 13:40:55 +0200] critical/ApiListener: Configuration file '/var/lib/icinga2/api/packages/_api/master2-1447691349-1/conf.d/downtimes/HOST!master1-1491305832-0.conf' already exists.
```

**Comment by dhampel** [comment]
Hey,

ist there something new to this issue?

**Comment by dnsmichi** [comment]
Partially this issue happened at other sites too, which was investigated on in 2.7 and later 2.8. I would believe this one is fixed.

Cheers,
Michael

**Comment by anan80** [comment]
Is there any work around for notification issue when downtime is set, we did upgrade from 2.6 to 2.7 to 2.8 to address this issue, so far it is not yet fixed.

**Comment by Crunsher** [comment]
@anan80 Please open a new issue with all the relevant information
