### ISSUE TITLE
icinga2: Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": Permission denied.

### ISSUE THREAD

**Issue by fedex29** [Icinga/icinga2#5096]
Hello, when I run the command to update it gives the following error:

```
icinga2: Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": Permission denied.

#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php(70): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleServiceCheckCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1152): Icinga\Module\Monitoring\Forms\Command\Object\CheckNowCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(63): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(64): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->showAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}

The file in the path "/var/run/icinga2/cmd/icinga2.cmd" does not exist
```

**Comment by gunnarbeutner** [comment]
Can you please show us the output of `icinga2 feature list` and `ls -l /var/run/icinga2/cmd`?

**Comment by fedex29** [comment]
Yes:

icinga2 feature list:

root@intranet:~# icinga2 feature list
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql ido-pgsql mainlog notification
root@intranet:~#

ls -l /var/run/icinga2/cmd:
root@intranet:~# ls -l /var/run/icinga2/cmd
total 0
root@intranet:~#

**Comment by gunnarbeutner** [comment]
That seems unusual. The "command" feature is enabled but the command pipe file is missing. Can you please also show me the output of `icinga2 object list --type ExternalCommandListener` and `cat /etc/icinga2/features-enabled/command.conf`?

**Comment by fedex29** [comment]
Yes:

root@intranet:~ icinga2 object list --type ExternalCommandListener
root@intranet:~

_____________________

root@intranet:~ cat /etc/icinga2/features-enabled/command.conf
/**
 * The ExternalCommandListener implements support for the external
 * commands pipe.
 */

library "compat"

object ExternalCommandListener "command" { }

root@intranet:~

**Comment by gunnarbeutner** [comment]
Uh, what about `cat /etc/icinga2/icinga2.conf`?

**Comment by fedex29** [comment]
root@intranet:~# cat /etc/icinga2/features-enabled/command.conf
/**
 * The ExternalCommandListener implements support for the external
 * commands pipe.
 */

library "compat"

object ExternalCommandListener "command" { }

root@intranet:~# cat /etc/icinga2/icinga2.conf
/**
 * Icinga 2 configuration file
 * - this is where you define settings for the Icinga application including
 * which hosts/services to check.
 *
 * For an overview of all available configuration options please refer
 * to the documentation that is distributed as part of Icinga 2.
 */

/**
 * The constants.conf defines global constants.
 */
include "constants.conf"

/**
 * The zones.conf defines zones for a cluster setup.
 * Not required for single instance setups.
 */
include "zones.conf"

/**
 * The Icinga Template Library (ITL) provides a number of useful templates
 * and command definitions.
 * Common monitoring plugin command definitions are included separately.
 */
include <itl>
include <plugins>
include <plugins-contrib>
include <manubulon>

/**
 * This includes the Icinga 2 Windows plugins. These command definitions
 * are required on a master node when a client is used as command endpoint.
 */
include <windows-plugins>

/**
 * This includes the NSClient++ check commands. These command definitions
 * are required on a master node when a client is used as command endpoint.
 */
include <nscp>

/**
 * The features-available directory contains a number of configuration
 * files for features which can be enabled and disabled using the
 * icinga2 feature enable / icinga2 feature disable CLI commands.
 * These commands work by creating and removing symbolic links in
 * the features-enabled directory.
 */
include "features-enabled/*.conf"

/**
 * The repository.d directory contains all configuration objects
 * managed by the 'icinga2 repository' CLI commands.
 */
include_recursive "repository.d"

/**
 * Although in theory you could define all your objects in this file
 * the preferred way is to create separate directories and files in the conf.d
 * directory. Each of these files must have the file extension ".conf".
 */
include_recursive "conf.d"
root@intranet:~#

**Comment by gunnarbeutner** [comment]
Did you restart Icinga 2 after enabling the "command" feature? Try restarting it and check if the output for `icinga2 object list --type ExternalCommandListener` changes.

**Comment by fedex29** [comment]
Yes, I restart it several times, I have turned the service on and off several times and it still does not work.

root@intranet:~ service icinga2 restart
root@intranet:~ icinga2 object list --type ExternalCommandListener
root@intranet:~

**Comment by gunnarbeutner** [comment]
What about `ls -l /etc/icinga2/features-enabled`?

**Comment by dnsmichi** [comment]
Please also add the output of `icinga2 --version`.

**Comment by fedex29** [comment]
Yes:

root@intranet:~ ls -l /etc/icinga2/features-enabled
total 0
lrwxrwxrwx 1 root root 30 Mar 24 18:27 api.conf -> ../features-available/api.conf
lrwxrwxrwx 1 root root 34 Mar 24 17:41 checker.conf -> ../features-available/checker.conf
lrwxrwxrwx 1 root root 34 Mar 27 17:04 command.conf -> ../features-available/command.conf
lrwxrwxrwx 1 root root 36 Mar 24 17:50 ido-mysql.conf -> ../features-available/ido-mysql.conf
lrwxrwxrwx 1 root root 36 Mar 24 18:06 ido-pgsql.conf -> ../features-available/ido-pgsql.conf
lrwxrwxrwx 1 root root 34 Mar 24 17:41 mainlog.conf -> ../features-available/mainlog.conf
lrwxrwxrwx 1 root root 39 Mar 24 17:41 notification.conf -> ../features-available/notification.conf

root@intranet:~ icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.2-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.1 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-66-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.4.0
  Build host: lgw01-08
root@intranet:~

**Comment by dnsmichi** [comment]
Hm, hard to tell. Can you run a config validation and grep for command to see whether the feature is being loaded?

```
icinga2 daemon -x notice -C | grep -i command
```

Furthermore please check your syslog for errors during Icinga 2 startup.

Oh, and you can format your source code, config and log blocks with three backticks. We've edited your initial posting, but appreciate it if you could take care yourself.

**Comment by fedex29** [comment]
Ok, sorry i'm new in github

```
root@intranet:~# icinga2 daemon -x notice -C | grep -i command
notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-icinga.conf
notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-plugins.conf
notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-plugins-manubulon.conf
notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-plugins-windows.conf
notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-nscp-local.conf
notice/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/command.conf
root@intranet:~#
```
results in /var/log/syslog
```
Mar 29 11:53:59 intranet systemd[1]: Stopped Icinga host/service/network monitoring system.
Mar 29 11:53:59 intranet systemd[1]: Starting Icinga host/service/network monitoring system...
Mar 29 11:53:59 intranet systemd[1]: Started Icinga host/service/network monitoring system.
Mar 29 11:53:59 intranet icinga2[2488]: [2017-03-29 11:53:59 +0000] information/cli: Icinga application loader (version: r2.6.2-1)
Mar 29 11:53:59 intranet icinga2[2488]: [2017-03-29 11:53:59 +0000] information/cli: Loading configuration file(s).
Mar 29 11:53:59 intranet icinga2[2488]: [2017-03-29 11:53:59 +0000] critical/config: Error: Error while evaluating expression: Could not load library 'libdb_ido_pgsql.so.2.6.2': libdb_ido_pgsql.so.2.6.2: cannot open shared object file: No such file or directory
Mar 29 11:53:59 intranet icinga2[2488]: Location: in /etc/icinga2/features-enabled/ido-pgsql.conf: 6:1-6:22
Mar 29 11:53:59 intranet icinga2[2488]: /etc/icinga2/features-enabled/ido-pgsql.conf(4):  */
Mar 29 11:53:59 intranet icinga2[2488]: /etc/icinga2/features-enabled/ido-pgsql.conf(5):
Mar 29 11:53:59 intranet icinga2[2488]: /etc/icinga2/features-enabled/ido-pgsql.conf(6): library "db_ido_pgsql"
Mar 29 11:53:59 intranet icinga2[2488]:                                                  ^^^^^^^^^^^^^^^^^^^^^^
Mar 29 11:53:59 intranet icinga2[2488]: /etc/icinga2/features-enabled/ido-pgsql.conf(7):
Mar 29 11:53:59 intranet icinga2[2488]: /etc/icinga2/features-enabled/ido-pgsql.conf(8): object IdoPgsqlConnection "ido-pgsql" {
Mar 29 11:53:59 intranet systemd[1]: icinga2.service: Main process exited, code=exited, status=1/FAILURE
Mar 29 11:53:59 intranet systemd[1]: icinga2.service: Unit entered failed state.
Mar 29 11:53:59 intranet systemd[1]: icinga2.service: Failed with result 'exit-code'.
```

**Comment by dnsmichi** [comment]
Ok, so Icinga 2 isn't started and running. That explains why the command pipe isn't created.

You've somehow managed to enable the feature `ido-pgsql` but did not install the corresponding package binaries for that. 

```
root@intranet:~ icinga2 feature list
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql ido-pgsql mainlog notification
root@intranet:~
```

Since you've enabled `ido-mysql` - which database backend are you using for the IDO database and Icinga Web 2?

Quickfix: Disable the ido-pgsql feature and restart again.

**Comment by fedex29** [comment]
Yes, it works! 

I disabled the ido-pgsql feature and it's works.

Thanks!

**Comment by gunnarbeutner** [comment]
We should evaluate whether moving the feature config file to the icinga2-ido-* packages makes sense in Debian in order to avoid this problem in the future. @lazyfrosch, can you please have a look at this and check whether this change is feasible?

**Comment by lazyfrosch** [comment]
@gunnarbeutner The config files are shipped by the respective packages.

I guess the problem is related to:
* A config file would only be removed by purge
* The feature is not disable on removal of a package (features-enabled)

**Comment by dnsmichi** [comment]
Oh, I did not see your comment, sorry @lazyfrosch.

I've created a follow-up issue #5109 since the original topic doesn't explain what's going on here.
