### ISSUE TITLE
Deprecate the icinga2-classicui-config package

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5102]
We should push users to start using Icinga Web 2 instead of the old 1.x interface world. The documentation does not explain its installation anymore, and neither should the release tarball provide the configuration files or separate packages.

My proposal: 2.7 - deprecation, 2.9 - removal.

**Comment by lazyfrosch** [comment]
This is a rather unimportant change in my eyes. If one wants to use it, he should use it.

**Comment by dnsmichi** [comment]
I'd like to get rid of it in the sources (asked @lippserd & @gunnarbeutner), and reduce any support to zero. It will have an impact on package builds, so announcing this as soon as possible is a good thing imho.

**Comment by Thomas-Gelf** [comment]
I'd suggest to announce ClassicUI EOL together with the IcingaDB release announcement. Whether we agree or not, users who are still working solely with Classic UI might have their reasons. We shouldn't forcibly push them into IDO while something way better is just around the corner ;-)

**Comment by dnsmichi** [comment]
I don't mind users installing Icinga 1.x and the Classic UI and living with it. My concern is just Icinga 2 + Classic UI, which is horrible to support. The package I am talking about just provides the required configuration changes to adjust paths for Icinga 2 instead of Icinga 1.x as core. You still can manage that manually after package removal; similar to the node update-config mode where users will build their own workarounds.

**Comment by dnsmichi** [comment]
Deprecation in 2.7, removal in git master after release for 2.8. This also breaks builds on Amazon Linux e.g.

**Comment by dnsmichi** [comment]
I'm not sure if there are changes needed for Debian packages, @lazyfrosch ? :)

**Comment by lazyfrosch** [comment]
No, since it merely documentation

**Comment by lazyfrosch** [comment]
@dnsmichi close?

**Comment by dnsmichi** [comment]
If you take care about the Debian bits, I'm fine with it. icinga/icinga2 is completed :)
