### ISSUE TITLE
Send notification about downtime

### ISSUE THREAD

**Issue by milan-koudelka** [Icinga/icinga2#5107]
Hi,
is it possible to implement feature, which will send notification to contact about downtime start and end ?

**Comment by dnsmichi** [comment]
That's already possible and you can filter such as notification type. 

https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics#notification-filters-state-type
