### ISSUE TITLE
Windows client version format

### ISSUE THREAD

**Issue by leeclemens** [Icinga/icinga2#5110]
After upgrading to 2.6.3 Windows x86_64, the version is displayed as `v2.6.3-2-g9d26a9c` (by icinga troubleshoot and the icinga service check result). Whereas the Linux client displays `v2.6.3` (keeping with the same format as previous versions).

Is this an intentional change for only the Windows client? Or was the installer published from a debug build?

https://packages.icinga.org/windows/Icinga2-v2.6.3-x86_64.msi
Icinga2-v2.6.3-x86_64.msi	2017-03-30 11:25	31M

**Comment by dnsmichi** [comment]
Chocolatey upload of v2.6.3 required some package specific changes in #5100. Otherwise we wouldn't have been able to upload the recent release and wait for the next one. It is intentional, but an exception for Windows builds only.
