### ISSUE TITLE
Evaluate DB IDO indexes

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5112]
Summary of index changes reported by @Thomas-Gelf a while ago. @lippserd please consider evaluating them.

### Create redundant bidirectional index on host/servicegroup tables

It's often hard for developers to build joins according available indexes, because of multiple reasons (too many layers of abstraction, not enough DB knowledge or even pure ignorance :p ). I'd opt for creating the grpmbrs_oid_gid index twice, oid_gid and gid_oid. This is redundant but helps to speed up joins in any direction.

### indices on icinga_{host,service}dependencies make no sense

No idea what they could be useful for. Has low impact, as most frontends are afaik not using those tables.

### index display_name and alias

We should at least partially index those tables, they are often involved in search requests. Not sure whether it makes sense to combine that index with object_id.

### drop a bunch of indexes on icinga_{host,service}status

Namely indexes like those:
```
  KEY "hoststatus_stat_upd_time_idx" ("status_update_time"),
  KEY "hoststatus_check_type_idx" ("check_type"),
  KEY "hoststatus_notif_enabled_idx" ("notifications_enabled"),
  KEY "hoststatus_problem_ack_idx" ("problem_has_been_acknowledged"),
  KEY "hoststatus_act_chks_en_idx" ("active_checks_enabled"),
  KEY "hoststatus_pas_chks_en_idx" ("passive_checks_enabled"),
  KEY "hoststatus_event_hdl_en_idx" ("event_handler_enabled"),
  KEY "hoststatus_flap_det_en_idx" ("flap_detection_enabled"),
  KEY "hoststatus_is_flapping_idx" ("is_flapping"),
  KEY "hoststatus_p_state_chg_idx" ("percent_state_change"),
  KEY "hoststatus_latency_idx" ("latency"),
  KEY "hoststatus_ex_time_idx" ("execution_time"),
  KEY "hoststatus_sch_downt_d_idx" ("scheduled_downtime_depth")
```

I'm aware of no single query able to make any use of those, similar for servicesstatus. Those two tables get by far the most write requests while Icinga is running, modifying so many indices again and again really hurts.

### icinga_customvariables lacks important index

An index on (object_id, varname) is missing. This doesn't really hurt as we usually select only from icinga_customvariablestatus. Nonetheless, this should be fixed to have both tables showing similar performance.

### icinga_comments and icinga_acknowledgements have no object_id index

That's the most relevant index, as comments and acknowledgements are rarely if ever queried without a relation to their object.

### Use CI collation on search fields (alias, display_name)

alias and display_name are non-unique fields, there solely purpose are display reasons - and they are also often involved in search requests. Search is always case insensitive, so instead of casting data at search time (expensive) we should do so at index time (cheap).

**Comment by leeclemens** [comment]
I ran `pt-index-usage` against my small Icinga setup: https://pastebin.com/dxeyJUVk

Thanks to using `userstat=on` in MySQL, the list of **used** indexes is much smaller (granted I don't have many events or use some other features, etc in this environment):

```
MariaDB [information_schema]> SELECT TABLE_NAME,INDEX_NAME FROM INDEX_STATISTICS where table_schema='icinga';
+------------------------------+------------------------------------+
| TABLE_NAME                   | INDEX_NAME                         |
+------------------------------+------------------------------------+
| icinga_servicestatus         | object_id                          |
| icinga_objects               | PRIMARY                            |
| icinga_hosts                 | host_object_id                     |
| icinga_service_contactgroups | scgrps_sid_cgoid                   |
| icinga_dbversion             | dbversion                          |
| icinga_programstatus         | instance_id                        |
| icinga_hoststatus            | object_id                          |
| icinga_programstatus         | PRIMARY                            |
| icinga_instances             | PRIMARY                            |
| icinga_servicegroups         | PRIMARY                            |
| icinga_contactnotifications  | contact_notification_idx           |
| icinga_objects               | sla_idx_obj                        |
| icinga_objects               | objects_name2_idx                  |
| icinga_customvariablestatus  | object_id_2                        |
| icinga_customvariables       | object_id_2                        |
| icinga_services              | services_host_object_id_idx        |
| icinga_servicegroup_members  | idx_servicegroup_members_object_id |
| icinga_endpointstatus        | idx_endpointstatus_object_id       |
| icinga_comments              | instance_id                        |
| icinga_runtimevariables      | runtimevariables_i_id_idx          |
| icinga_services              | services_combined_object_idx       |
| icinga_host_contactgroups    | hstcntgrps_hid_cgoid               |
| icinga_service_contacts      | idx_service_contacts_service_id    |
| icinga_notifications         | notification_object_id_idx         |
| icinga_objects               | objecttype_id                      |
| icinga_services              | service_object_id                  |
| icinga_hostgroup_members     | hstgrpmbrs_hgid_hoid               |
| icinga_host_contacts         | idx_host_contacts_host_id          |
| icinga_statehistory          | statehist_state_idx                |
+------------------------------+------------------------------------+
29 rows in set (0.00 sec)
```

**Comment by lippserd** [comment]
I played around with schema and query changes a little bit here: https://github.com/Icinga/icingaweb2/tree/feature/optimize-ido-mysql
But honestly this is nowhere complete and requires more time than creating a whole new schema 😆 
I would not bother to dramatically change DB IDO indices and focus on Icinga DB.
