### ISSUE TITLE
Load status dump from Redis

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icinga2#5114]
In case the Redis feature is enabled, we do not need to dump state to disk. Redis should be configured in a way doing so from time to time, in addition to that a `BGSAVE` should be fired from Icinga before shutting down.

This feature request does explicitly NOT try to target config persistance for modified attributes or downtimes. They might be tackled in a similar way later on in case this feature holds it's premises.

**Comment by Crunsher** [comment]
refs #5073

**Comment by dnsmichi** [comment]
I'm closing this in favour of a global project concept and plan. TBD.
