### ISSUE TITLE
Figure out whether we want to store objects "the Redis way"

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icinga2#5118]
Currently our objects look like this:

    icinga:object:Host
        "localhost": "{ __name: ...}"

Those properties are not accessible "the Redis way" as long as one doesn't write custom LUA scripts. We probably want to keep the Redis feature as an feature that should be usable in a "standalone way", even without IcingaDB.

Our current data structure is perfectly suitable for a config sync, but would make life hard for that target audience. Think of "Dashing" or similar tools, they would probably prefer to be able to filter objects by property. Moving our object keys to the global keyspace would help them:

    icinga:object:Host:localhost
        __name: "localhost"
        address: "127.0.0.4"

This is a prio low feature and can be postponed.

**Comment by Crunsher** [comment]
We can not guarantee the type of the value of an attribute, for this reason it would look like this
 ```
icinga:object:Host:localhost
    __name: "\"localhost" \"'
    address: '\"127.0.0.4\"'
    zones: "[ \"a\", \"b\" ]"
```
