### ISSUE TITLE
Trim event queue

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icinga2#5119]
We currently do not trim our event queues, this should be implemented before going public. This is a low prio feature, as the queuing mechanism might still be subject to change.

**Comment by Crunsher** [comment]
Implementation redis command:
```
MULTI
LPUSH $QUEUE $VALUE
LTRIM $QUEUE 0 $LIMIT-1
EXEC
```

Something we have to think about is if we want this limit to be global or per queue, if it's per queue we also need to think about how to safe this.
