### ISSUE TITLE
Specify perl for manubulon command wrapper

### ISSUE THREAD

**Issue by moix** [Icinga/icinga2#5128]
When running a distributed setup with master/satellites is very useful to synch all configuration data and scripts from master to satellites by using the global zone as documented at https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/distributed-monitoring#distributed-monitoring-top-down

When using manubulon scripts, the wrapper defines the commands as:
command = [ ManubulonPluginDir + "/check_snmp_load.pl" ]
which means that scripts must have exec permissions which doesn't happen when syncing data in top-down strategy.

It will be useful to have the perl interpreter specified in the CheckCommand definitions so it work out of the box in master/satellites architecture and with centralized configuration via global zone:
command = [ "perl", ManubulonPluginDir + "/check_snmp_load.pl" ]

**Comment by dnsmichi** [comment]
Syncing plugin scripts and binaries is not supported. That should be dealt with a real management system just as Puppet or Ansible. Those can also handle file permissions and the required execute bit. Icinga 2 and its cluster config sync is not designed to replace such, or handle scripts and their dependencies (i.e. Net-SNMP as Perl library for manubulon scripts).

I totally understand the requirement, but I don't believe that Icinga 2 should take care about plugin sync. As such I'll close here.
