### ISSUE TITLE
Problem with Icinga2 and the icinga windows client

### ISSUE THREAD

**Issue by micha-09** [Icinga/icinga2#5131]
Hello everybody,
We use icinga and on our windows servern the icinga client 2.6.3. As soon as a windows server is included in the icinga configuration and icinga connects to the corresponding icinga client, the icinga client service on the server jumps to 100% cpu performance. On this level remains the service. If you restart the service then it runs again normal.
Is this problem known? What can we do?

Thank you

**Comment by Crunsher** [comment]
Are you using Windows as a master? I'm a bit confused by your usage of client, service and server

**Comment by dnsmichi** [comment]
I believe this is a duplicate, unfortunately no feedback received.
