### ISSUE TITLE
Verify cluster zone log information

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga2#5134]
I noticed a difference in terms of the cluster zone lag displayed.

In a master-master setup with satellites all the core zones had a log lag of 0 in `/v1/status`, but the `cluster-zone` check had shown about 39 days on the first master (for the master zone).

Which couldn't be a correct indication.

Will have a look on it myself.

**Comment by dnsmichi** [comment]
Reopen if this becomes relevant again.
