### ISSUE TITLE
Documentation should explain that runtime modifications are not immediately updated for "object list"

### ISSUE THREAD

**Issue by xenuser** [Icinga/icinga2#5140]
I noticed that `icinga2 object list` only shows modifiations or new objects when Icinga2 was reloaded. But when I create new objects via API, `icinga2 object list` won't be up to date.

IMHO the documentation should therefore warn in red latters that the state between API and `icinga2 object list `might differ in some situations. If you are not aware of this, you begin to wonder why some things work and some don't because you might create stuff via API and check for it via `icinga2 object list`.

**Comment by dnsmichi** [comment]
I'll add a note to the docs while working on #5137.

**Comment by xenuser** [comment]
Thanks a lot!!
