### ISSUE TITLE
active checks stop executing

### ISSUE THREAD

**Issue by DBMatthias** [Icinga/icinga2#5147]
Hi,

I'm using a standalone icinga2 r2.6.3-1 on Debian 8
Enabled features: api checker debuglog ido-mysql mainlog notification perfdata

After some time, icinga stops executing active checks.
passive checks are processed and even the "dummy" check works.
But no check_icmp or check_ping and no other active service check
icingaweb2 shows a negative time for "next check". 

reschedule the check doesn't help. The checks becomes executed only after a restart of the icinga2 service.

In the attached debug log, you can see the last active check was executed at 10:06:34. 
I can't see any error in the icinga log nor in other logs (e.g. syslog)

Debug-Log:
[debug.txt](https://github.com/Icinga/icinga2/files/902246/debug.txt)

Icingaweb2 Screenshot: (next check should be executed 34 minutes ago)
![image](https://cloud.githubusercontent.com/assets/26961869/24749595/f0cdbf42-1ac3-11e7-9b3e-a7c83ebec284.png)

Icingaweb2 Screenshot: (dummy check works)
![image](https://cloud.githubusercontent.com/assets/26961869/24749577/e01b9912-1ac3-11e7-8587-029e033fd426.png)

**Comment by dnsmichi** [comment]
- is the time in sync (i.e. ntpd running)
- any insights into heavy load or performance issues on your systems - see https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/troubleshooting#troubleshooting-analyze-environment
- query the service object via REST API and post the json output here
- is the DB IDO feature running, any insights in the logs and mysql if there's something hanging?
- in case of a deadlock, please generate a gdb backtrace from the running process - see https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/development#development-debug-gdb-backtrace-running

**Comment by dnsmichi** [comment]
No feedback received.
