### ISSUE TITLE
Invalid links in documentation

### ISSUE THREAD

**Issue by andreasscherbaum** [Icinga/icinga2#5150]
The following links in the documentation no longer work:

* http://www.graylog2.org/resources/gelf (doc/14-features.md)
* http://www.graylog2.org/ - redirects to https://www.graylog.org/ (doc/14-features.md)
* http://www.logstash.net - redirects to https://www.elastic.co/products/logstash (doc/14-features.md)

**Comment by dnsmichi** [comment]
Thanks 👍
