### ISSUE TITLE
IDODB contains deleted contacts, Icingaweb2 displays contact group member count wrong

### ISSUE THREAD

**Issue by xenuser** [Icinga/icinga2#5152]
I noticed multiple occasions of inconsistencies regarding actual config states and the content of IDODB. Furthermore I noticed that Icingaweb2 reacts on these inconsistencies in a strange way.

## Expected Behavior
When deleting a contact, it should disappear also from IDODB.
Furthermore Icingaweb2 should show the correct member count.

## Current Behavior
One particular example I can easily documentate:
I have the contact group contact_ group3 with 3 members: user_a, user_b, user_c

They are imported by Director.
I deleted a contact within the file which is imported by Director.
Looking in Icingaweb2, only the two remaining contacts are shown as members of the contact group, which is correct.
BUT: The member count on the left shows "3".

Looking into IDODB, I can see that the recently deleted contact is still there and a member of the service group.

So, Icingaweb2 shows the correct members, but displays the wrong member count from IDODB at the same time (which is another bug IMHO).

See screenshot as a proof. Sorry for the black bars on the screenshot, I had to make sure that no one can read any sensitive data.

![auswahl_028](https://cloud.githubusercontent.com/assets/2216868/24791926/4fe03e02-1b7c-11e7-8e41-14e98b85a8ba.png)

## Steps to Reproduce (for bugs)
I deleted a contact within the file which is imported by Director.

## Context
I saw many other occasions where IDODB is not updated, although new objects are added or old ones are deleted. As a consequence, Icingaweb2 shows wrong things.
While it is hard to proove that this happens, I try to describe this issue using the contact group example.

## Your Environment
- SLES 12 SP1
- Icinga2 2.6.1
- icinga2-ido-mysql 2.6.1
- Icingaweb2 2.4.1
- Director: latest version
- Fileshipper: latest version

**Comment by dnsmichi** [comment]
Please be so kind and fill in the required sections next time. "see text above" isn't really the idea about an issue template ...

Can you extract the database backend data for those contact group members? That screenshot does not tell much.

Furthermore, if you turn on the debug log, you should see those query updates coming from icinga2. Since you've removed anything from the screenshot, pick those hidden object names and look for such updates inside the logs. Post your findings here.

**Comment by xenuser** [comment]
Since the required information is already within the description, it is only a matter of text structure. However, it is not really an issue to restructure (which I just did).

> Can you extract the database backend data for those contact group members?
> That screenshot does not tell much.

Sure. Please note that I will have to obfuscate :(

> Furthermore, if you turn on the debug log, you should see those query updates coming from icinga2. Since you've removed anything from the screenshot, pick those hidden object names and look for such updates inside the logs. Post your findings here

Will do so.

**Comment by xenuser** [comment]
As promised, I uploaded the relevant content of IDODB:
[contact_groups.txt](https://github.com/Icinga/icinga2/files/910668/contact_groups.txt)

I had to obfuscate the values, otherwise I won't be able to post this excerpt from the database here.

Regarding the debuglog:
As wished, I enabled the debuglog feature and even re-deployed via Director. However, I did not see any of the related objects (contact group, contact group members) within the log file which is why I think posting here does not make sense (in addition, I won't be allowed to post the log file here).

**Comment by dnsmichi** [comment]
Can you repeat those queries to involve the objects table?

Something like this:
```
select * from icinga_contacts c join icinga_objects oc on c.contact_object_id=oc.object_id where oc.object_id in (35806, 35809, 35812);
```

If you're not allowed to post any log files, that's a pity. Ensure to provide anything else which allows to reproduce the issue more easily then. Can you add the runtime details fetched from the /v1/objects/users API endpoint too?

**Comment by xenuser** [comment]
I ran the provided query:

[contact_groups_extended.txt](https://github.com/Icinga/icinga2/files/930075/contact_groups_extended.txt)

I notived that one of the users is disabled, which is interesting.


> If you're not allowed to post any log files, that's a pity.
I agree that this is something which makes things harder. Please know that many companie have some sort of policy which prevents service providers to relay information, especially when the information relates to specific emloyees (I am sure you encountered something like this before).

> Ensure to provide anything else which allows to reproduce the issue more easily then.
I will do my best.

> Can you add the runtime details fetched from the /v1/objects/users API endpoint too?
I dumped the requested information, unfortunately it contains user data and custom variables which are not allowed to be disclosed ("personenbezogene Daten"). Therefore I am not allowed to upload the file :(

But I will be able to answer to specific questions, e.g. "what is the value of the attribute "paused" of the user "user_c"? I hope this helps a bit.

Again, I am sorry that I can not provide log files and data dumps.

**Comment by dnsmichi** [comment]
The user which has `is_active` set to 0 is the same user which is incorrectly shown inside Icinga Web 2 in that screenshot, right?

**Comment by xenuser** [comment]
Indeed. And this user is missing in the data which was obtained from calling  /v1/objects/users.

**Comment by dnsmichi** [comment]
So Icinga 2 marks the user (contact) as "is_active=0". As such, Icinga Web 2 should take that into account when querying data. I do believe that this is a bug in Icinga Web 2 then. Please open a new issue over there.

**Comment by xenuser** [comment]
Ok, will do so. Thanks a lot!
