### ISSUE TITLE
openSUSE 4.2 repo packages for leap 42.2

### ISSUE THREAD

**Issue by goosemaster** [Icinga/icinga2#5154]
Hello,

I am currently trying to install  icinga2 from the repo but have discovered the following:

# zypper --verbose ref
Verbosity: 1
Initializing Target
Specified repositories:
Checking whether to refresh metadata for Main Repository (NON-OSS)
Retrieving: content ......................................................[done]
Retrieving: media ........................................................[done]
Repository 'Main Repository (NON-OSS)' is up to date.
Checking whether to refresh metadata for Update Repository (Non-Oss)
Retrieving: repomd.xml ...................................................[done]
Repository 'Update Repository (Non-Oss)' is up to date.
Checking whether to refresh metadata for Main Repository (OSS)
Retrieving: content ......................................................[done]
Retrieving: media ........................................................[done]
Repository 'Main Repository (OSS)' is up to date.
Checking whether to refresh metadata for Main Update Repository
Retrieving: repomd.xml ...................................................[done]
Repository 'Main Update Repository' is up to date.
Checking whether to refresh metadata for ICINGA (stable release for openSUSE1)
Retrieving repository 'ICINGA (stable release for openSUSE1)' metadata ..[error]
Repository 'ICINGA (stable release for openSUSE1)' is invalid.
[icinga-stable-release|http://packages.icinga.com/openSUSE/42.2/release/] Valid metadata not found at specified URL
History:
- [icinga-stable-release|http://packages.icinga.com/openSUSE/42.2/release/] Repository type can't be determined.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'ICINGA (stable release for openSUSE1)' because of the above error.
Checking whether to refresh metadata for Networking services and related tools (openSUSE_Leap_42.1)
Retrieving: repomd.xml .........................................[done (551 B/s)]
Repository 'Networking services and related tools (openSUSE_Leap_42.1)' is up to

Skipping disabled repository 'openSUSE-42.2-0'
Skipping disabled repository 'openSUSE-Leap-42.2-Debug'
Skipping disabled repository 'openSUSE-Leap-42.2-Debug-Non-Oss'
Skipping disabled repository 'openSUSE-Leap-42.2-Update-Debug'
Skipping disabled repository 'openSUSE-Leap-42.2-Update-Debug-Non-Oss'
Skipping disabled repository 'openSUSE-Leap-42.2-Source'
Skipping disabled repository 'openSUSE-Leap-42.2-Source-Non-Oss'
Checking whether to refresh metadata for SaltStack, dependencies, and addons (openSUSE_Leap_42.2)
Retrieving: repomd.xml ...................................................[done]
Repository 'SaltStack, dependencies, and addons (openSUSE_Leap_42.2)' is up to d

Some of the repositories have not been refreshed because of an error.

# zypper search icinga2
Error building the cache:
[icinga-stable-release|http://packages.icinga.com/openSUSE/42.2/release/] Valid metadata not found at specified URL
Warning: Skipping repository 'ICINGA (stable release for openSUSE1)' because of the above error.
Some of the repositories have not been refreshed because of an error.

# cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.2"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.2"
PRETTY_NAME="openSUSE Leap 42.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

per the admin response at monitoring-portal.org:

"We are currently only building packages for 42.1. Could you create a ticket over at https://github.com/icinga/icinga2 for this please, we'll get on it sometime soon."

Regards,

**Comment by Crunsher** [comment]
Sadly we are dependent on tickets like these to be informed when certain distributions (ie. the ones we don't use) are phased out.

**Comment by Crunsher** [comment]
Packages now exist (for 42.3 also)

**Comment by goosemaster** [comment]
Thanks Guys!
