### ISSUE TITLE
3.5. Apply Rules topic in the docs needs work.

### ISSUE THREAD

**Issue by zogness** [Icinga/icinga2#5155]
The opening sentence does not "scan," or is more or less unreadable.

"Instead of assigning each object (Service, Notification, Dependency based on attribute identifiers for example host_name objects can be applied."

I can't figure out what that's supposed to mean but at the very least it's missing a closing parens.

https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics#using-apply

<!-- Formatting tips:

**Comment by dnsmichi** [comment]
Yep, missed that lately, thanks.
