### ISSUE TITLE
Change of host attribute "zone" via API not honored by Icinga2

### ISSUE THREAD

**Issue by bb-Ricardo** [Icinga/icinga2#5159]
When updating a host object via API and moving a host from one zone to another Icinga does not move the host.

## Your Environment

* Version used: v2.6.2
* Operating System and version: CentOS 7.3
* Enabled features: api graphite mainlog perfdata

**Comment by dnsmichi** [comment]
That's correct and should imho be documented that this does not work, or is not supported. Adding such a functionality would require a) deletion messages for the old zone attribute and involved instances b) object creation messages. I do believe that this isn't easy to implement and might cause troubles with existing setups. If one comes up with a patch for that, long-term tests are mandatory for resolving this issue.

**Comment by dnsmichi** [comment]
If you modify an object attribute like zone or any custom attribute, you'll also need to take care about re-evaluating apply rules in #4084. This request is also similar to modifying groups in #4895.

**Comment by bb-Ricardo** [comment]
Pretty much like deleting, adding a Host but with state retention?

**Comment by Al2Klimov** [comment]
> That's correct and should imho be documented that this does not work, or is not supported.

You have already documented it:

https://github.com/Icinga/icinga2/commit/e4ae789a7c7b4d224072b73b97b4e434033f6c74#diff-f6707e8b513c6169b5a990baf6c112d5R634-R635
