### ISSUE TITLE
assign on service fails on vars set in service definition

### ISSUE THREAD

**Issue by bb-Ricardo** [Icinga/icinga2#5160]
Hi,

I try to assign services to hosts by checking a service var which has been set in an service template. Conditional statements in the service can access the var but assign fails.

## Expected Behavior
That the validation check accepts this configuration

## Current Behavior
Validation check Throws error: Tried to access undefined script variable 'vars'

## Steps to Reproduce (for bugs)
1. Add Config snippet:
```
apply Service "TEST123" {

	import "generic-service"
	vars.dbs = [ "DEV", "TEST", "PROD" ]

	assign where host.name == "localhost" && "DEV" in vars.dbs
 }
```
2. run `icinga2 daemon -C`
3. Output
```
critical/config: Error: Error while evaluating expression: Tried to access undefined script variable 'vars'
Location: in ./icinga2/zones.d/global-templates/services/services_application_database.conf: 136:51-136:54
./icinga2/zones.d/global-templates/services/services_application_database.conf(134):  vars.dbs = [ "DEV", "TEST", "PROD" ]
./icinga2/zones.d/global-templates/services/services_application_database.conf(135):
./icinga2/zones.d/global-templates/services/services_application_database.conf(136):  assign where host.name == "localhost" && "DEV" in vars.dbs
                                                                                                                                        ^^^^
./icinga2/zones.d/global-templates/services/services_application_database.conf(137): }
./icinga2/zones.d/global-templates/services/services_application_database.conf(138):

        (0) Evaluating 'apply' rule (in ./icinga2/zones.d/global-templates/services/services_application_database.conf: 131:1-131:23)
        (1) Evaluating 'apply' rules for host 'localhost'


```

## Your Environment

* Version used : 2.6.2
* Operating System and version: CentOS 7.3
* Enabled features: api graphite mainlog perfdata

**Comment by dnsmichi** [comment]
Hi,

what's the purpose of specifying `vars.dbs` on the service level? Even if that would work, the assign where expression will always evaluate to `true`. Such custom attribute pattern match would make more sense if you'd specify `host.vars.dbs` for instance.

Kind regards,
Michael

**Comment by dnsmichi** [comment]
@bb-Ricardo ping :)

**Comment by bb-Ricardo** [comment]
ahh, god damn it, sorry.

you are right, defining it on service level doesn't really make sense. I also changed it in my setup to the host level.

Confusing for the user is that it can be used in a "if" statement and var assignment and it works.

It doesn't really help that it works in some parts of the same service configuration and in others (assign) not.

That's what has thrown me off.

**Comment by dnsmichi** [comment]
Ok, then it is a scoping problem, which somehow should be documented. It is hard to explain after all. Suggestions where to put it? :)

**Comment by dnsmichi** [comment]
If you come up with a PR, I'll merge it. 

Cheers,
Michael
