### ISSUE TITLE
Deactivate servicecheck until date/time

### ISSUE THREAD

**Issue by friesoft** [Icinga/icinga2#5171]
## Context
Two teams monitoring the same server - one service is continuously flapping between ok, warning and critical. We want to disable the active check of this service for the next 4 weeks as the other team is handling the issue. Atm we have to create a reminder to enable the active check in 4 weeks again.
We can't simply acknowledge the service until in 4 weeks because of the state changes.

## Your Environment
* Version used (`icinga2 --version`): 2.5.4
* Operating System and version: CentOS 7.2
* Icinga Web 2 version and modules (System - About): 2.3.4

**Comment by dnsmichi** [comment]
How about using a downtime?

**Comment by friesoft** [comment]
We can't use a downtime as only this single servicecheck on the host is effected and all others are operating as intended and shall be monitored.

**Comment by lazyfrosch** [comment]
You can set the downtime for a specific service for a specific time. Setting a downtime for a host and all services needs only to be done when needed.

The service will be checked, but marked as in downtime, any notification is suppressed.

**Comment by friesoft** [comment]
Oh I didn't know this. Thanks. I'll close this request then :) Thanks for your support and fast reaction +1
