### ISSUE TITLE
Issues Packing icinga 2.6.3 tar.gz to RPM (centos 7)

### ISSUE THREAD

**Issue by Esteban2812** [Icinga/icinga2#5179]
## General Summary
Trying to reach the same as [issue](https://github.com/Icinga/icinga2/issues/5177) (create RPM) but in centos 7 distribution.

## Expected Behavior
Have RPM files created.

## Current Behavior
In 26% progress failed.

## Steps to Reproduce (for bugs)

1. rpmdev-setuptree
2. mkdir ~/tar; cd ~/tar; wget https://github.com/Icinga/icinga2/archive/v2.6.3.tar.gz
3. cd ~/tar; tar -xvzf v2.6.3.tar.gz
4. cp ~/tar/icinga2-2.6.3/icinga2.spec ~/rpmbuild/SPECS
5. cp ~/tar/v2.6.3.tar.gz ~/rpmbuild/SOURCES
6. rpmbuild -ba icinga2.spec

Error log: (full log is attached)

> [ 26%] Building CXX object lib/base/CMakeFiles/base.dir/base_unity.cpp.o
> cd /root/rpmbuild/BUILD/icinga2-2.6.3/lib/base && /usr/bin/c++   -DI2_BASE_BUILD -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -g -pthread -flto -fvisibility=hidden -std=c++0x -O2 -g -DNDEBUG -fPIC -I/root/rpmbuild/BUILD/icinga2-2.6.3/third-party/yajl/include -I/root/rpmbuild/BUILD/icinga2-2.6.3 -I/root/rpmbuild/BUILD/icinga2-2.6.3/lib -I/root/rpmbuild/BUILD/icinga2-2.6.3/third-party/execvpe -I/root/rpmbuild/BUILD/icinga2-2.6.3/third-party/mmatch -I/root/rpmbuild/BUILD/icinga2-2.6.3/third-party/socketpair    -o CMakeFiles/base.dir/base_unity.cpp.o -c /root/rpmbuild/BUILD/icinga2-2.6.3/lib/base/base_unity.cpp
> In file included from /root/rpmbuild/BUILD/icinga2-2.6.3/lib/base/base_unity.cpp:38:0:
> /root/rpmbuild/BUILD/icinga2-2.6.3/lib/base/scriptframe.cpp: In destructor 'icinga::ScriptFrame::~ScriptFrame()':
> /root/rpmbuild/BUILD/icinga2-2.6.3/lib/base/scriptframe.cpp:70:15: warning: unused variable 'frame' [-Wunused-variable]
>   ScriptFrame *frame = PopFrame();
>                ^
> {standard input}: Assembler messages:
> {standard input}:544748: Warning: end of file not at end of a line; newline inserted
> {standard input}:544926: Error: unknown pseudo-op: `.uleb1'
> c++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <http://bugzilla.redhat.com/bugzilla> for instructions.
> make[2]: *** [lib/base/CMakeFiles/base.dir/base_unity.cpp.o] Error 4
> make[2]: Leaving directory `/root/rpmbuild/BUILD/icinga2-2.6.3'
> make[1]: *** [lib/base/CMakeFiles/base.dir/all] Error 2
> make[1]: Leaving directory `/root/rpmbuild/BUILD/icinga2-2.6.3'
> make: *** [all] Error 2
> error: Bad exit status from /var/tmp/rpm-tmp.bKxCBR (%build)
> 
> 
> RPM build errors:
>     Bad exit status from /var/tmp/rpm-tmp.bKxCBR (%build)

[full_log.txt](https://github.com/Icinga/icinga2/files/948397/full_log.txt)
[rpm-tmp.bKxCBR.txt](https://github.com/Icinga/icinga2/files/948398/rpm-tmp.bKxCBR.txt)

## Context

Create RPM file from tar.gz in centos 7 environment.

> cat /etc/centos-release
> CentOS Linux release 7.2.1511 (Core)

## Your Environment

* Version used (`icinga2 --version`):2.6.3
* Operating System and version:

> cat /proc/version
> Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Nov 19 22:10:57 UTC 2015

**Comment by dnsmichi** [comment]
```
 Error: unknown pseudo-op: .uleb1' c++: internal compiler error: 
```
sounds like a compiler issue to me, nothing related to Icinga 2 itself. I'd check the gcc and g++ versions on your build host.

Quick test inside docker:

```
docker run -ti centos bash
yum  -y install rpmdevtools wget
rpmdev-setuptree
cd /root/rpmbuild
mkdir ~/tar; cd ~/tar; wget https://github.com/Icinga/icinga2/archive/v2.6.3.tar.gz
cd ~/tar; tar -xvzf v2.6.3.tar.gz
cp ~/tar/icinga2-2.6.3/icinga2.spec ~/rpmbuild/SPECS
cp ~/tar/v2.6.3.tar.gz ~/rpmbuild/SOURCES
cd ~/rpmbuild
yum-builddep SPECS/icinga2.spec
rpmbuild -ba SPECS/icinga2.spec
```

**Comment by lazyfrosch** [comment]
Our guess is a possible out-of-memory that doesn't get catched correctly in c++.

Please check how much memory the machine has.

You can try to disable unity builds in the spec file, by adding a line here.

https://github.com/Icinga/icinga2/blob/e630614c79690cdf5dc1e95e899e40bf869da39e/icinga2.spec#L279

```
  -DICINGA2_UNITY_BUILD=OFF \
```

**Comment by Esteban2812** [comment]
Thanks Icinga Guys
This issue is solved thanks to your suggestions:

- Increase memory of my virtual box machine
- Also worked following docker steps

> [root@centos7 ~]# tree -L 3 rpmbuild_ok_1/
> rpmbuild_ok_1/
> ├── BUILD
> │   └── icinga2-2.6.3
> │       ├── agent
> │       ├── AUTHORS
> │       ├── Bin
> │       ├── ChangeLog
> │       ├── changelog.py
> │       ├── choco
> │       ├── cmake
> │       ├── CMakeCache.txt
> │       ├── CMakeFiles
> │       ├── cmake_install.cmake
> │       ├── CMakeLists.txt
> │       ├── config.h
> │       ├── config.h.cmake
> │       ├── contrib
> │       ├── COPYING
> │       ├── COPYING.Exceptions
> │       ├── CPackConfig.cmake
> │       ├── CPackSourceConfig.cmake
> │       ├── CTestTestfile.cmake
> │       ├── DartConfiguration.tcl
> │       ├── debugfiles.list
> │       ├── debuglinks.list
> │       ├── debugsources.list
> │       ├── doc
> │       ├── elfbins.list
> │       ├── etc
> │       ├── icinga2.spec
> │       ├── icinga-app
> │       ├── icinga-installer
> │       ├── icinga-spec-version.h
> │       ├── icinga-spec-version.h.cmake
> │       ├── icinga-studio
> │       ├── icinga-version.h
> │       ├── icinga-version.h.cmake
> │       ├── install_manifest.txt
> │       ├── INSTALL.md
> │       ├── itl
> │       ├── lib
> │       ├── LICENSE.txt
> │       ├── Makefile
> │       ├── mkdocs.yml
> │       ├── NEWS
> │       ├── pick.py
> │       ├── plugins
> │       ├── README.md
> │       ├── RELEASE.md
> │       ├── test
> │       ├── Testing
> │       ├── third-party
> │       └── tools
> ├── BUILDROOT
> ├── RPMS
> │   └── x86_64
> │       ├── icinga2-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── icinga2-bin-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── icinga2-classicui-config-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── icinga2-common-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── icinga2-debuginfo-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── icinga2-doc-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── icinga2-ido-mysql-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── icinga2-ido-pgsql-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── icinga2-libs-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── icinga2-selinux-2.6.3-1.el7.centos.x86_64.rpm
> │       ├── nano-icinga2-2.6.3-1.el7.centos.x86_64.rpm
> │       └── vim-icinga2-2.6.3-1.el7.centos.x86_64.rpm
> ├── SOURCES
> │   └── v2.6.3.tar.gz
> ├── SPECS
> │   └── icinga2.spec
> └── SRPMS
>     └── icinga2-2.6.3-1.el7.centos.src.rpm
>
