### ISSUE TITLE
doc: Required SELinux packages for building RPMs are missing

### ISSUE THREAD

**Issue by leeclemens** [Icinga/icinga2#5180]
## Expected Behavior
List them, as other required packages are listed for building Icinga2.

## Current Behavior
SELinux packages required for building the SELinux policy module are not listed, although they are checked as requirements.

## Possible Solution
List the required packages for installation ahead of time.

## Context
Make it easier to install required packages ahead of attempting to build an RPM

## Your Environment
CentOS 7.  Verified package names on CentOS 6.

**Comment by dnsmichi** [comment]
Apparently that's a shortcoming of missing package requirements inside the spec file. Otherwise yum-builddep will automatically fetch them. See #5153

**Comment by leeclemens** [comment]
Installing `policycoreutils-python` won't satisfy those requirements:

```
error: Failed build dependencies:
	checkpolicy is needed by icinga2-2.6.3-1.el7.centos.x86_64
	selinux-policy-devel is needed by icinga2-2.6.3-1.el7.centos.x86_64
	/usr/share/selinux/devel/policyhelp is needed by icinga2-2.6.3-1.el7.centos.x86_64
```

Are you suggesting change the spec file to install them automatically instead of documenting them in `INSTALL.md` ? Or Both?

**Comment by leeclemens** [comment]
In case it helps clarify, these are requirements to _build_ the RPM - not necessarily to _install_ the RPM. My PR adds the requirements to the `Building Icinga 2 RPMs` section, just as `cmake` and `openssl-devel` are listed under the `Build Requirements` section.
