### ISSUE TITLE
Icinga2 director, checks are pending forever

### ISSUE THREAD

**Issue by zyzwizki** [Icinga/icinga2#5185]
Hi!

I am working with icinga2 version r2.6.3-1, icingaweb2 version 2.4.1 and icinga director version 1.3.1. 
When trying to use icinga director to create my first checks, I ran into a problem: While the host is up, the checks just show pending, even when applying a forced check.
The commands were defined in the director. These are all previews from the config-files:

```
object CheckCommand "check_hostname" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_by_ssh" ]
    arguments += {
        "-C" = "hostname"
        "-H" = "$address$"
        "-i" = "/var/lib/nagios/.ssh/id_rsa"
        "-l" = "monitoring"
    }
}
```

the service:

```
template Service "Current Hostname" {
    check_command = "check_hostname"
    enable_perfdata = false
}
```

the template:

```
template Host "Test" {
    check_command = "hostalive"
    check_interval = 1m
    retry_interval = 30s
}
```

the host:

```
object Host "Testserver" {
    import "Test"
    address = "XXX.XXX.XXX.XXX"
}
```

and finally:

```
apply Service "Current Hostname" {
   import "Current Hostname"
    assign where "Test" in host.templates
    import DirectorOverrideTemplate
}
```

What (if anything) am I doing wrong?
Thanks for your help!

**Comment by gunnarbeutner** [comment]
Hi,

thanks for your ticket. This doesn't exactly look like a bug report though. Can you please post your question on one of the community support channels (e.g. the mailing list or the forum, see https://www.icinga.com/community/get-involved/ for details)?

Kind regards
Gunnar
