### ISSUE TITLE
Document boolean values understood by set_if

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#5186]
Macros work differently from the Icinga 2 config language when resolving values to boolean

    Type             | Example | Result
    -------------------------------------
    Zero             | 0.0     | false
    Non-Zero         | 60.0    | true
    True             | true    | true
    False            | false   | false
    Empty String     | ""      | false
    Non-empty String | "foo"   | Outputs warning, false
    String true      | "true"  | true
    String false     | "false" | false

This should be documented

**Comment by shiz0** [comment]
Where would be a good place to put this?

**Comment by dnsmichi** [comment]
I'm not sure. It might need a specific section which explains set_if in commands (somewhere in the advanced topics) and puts the table there. It doesn't fit into object-types.md though. 

We also should move the runtime-macro section somewhere else, that does not fit into where it is now.

**Comment by shiz0** [comment]
There already is a similiar table in language-reference.md, which explains how boolean values are converted in the config: https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/language-reference#boolean-values
Though I'm not really sure if it would make sense to add it there, it would somehow fit in topic wise.

**Comment by dnsmichi** [comment]
Strings are generally not supported here, one should note that only boolean and number value types will work. That's the thing I'll add to the docs.
