### ISSUE TITLE
Mysql migration objects error

### ISSUE THREAD

**Issue by ekimike** [Icinga/icinga2#5192]
Cannot import objects from: /usr/share/icinga2-ido-mysql/schema/mysql.sql

## Expected Behavior

After executing script,  tables in icinga database must be created. What I get instead is:

ERROR 1060 (42S21) at line 1436: Duplicate column name 'endpoint_object_id' 

What I did:

#mysql -u root -
>mysql> CREATE DATABASE icinga;
>mysql>  GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icinga.* TO 'icinga'@'localhost' IDENTIFIED BY 'icinga';
>mysql> quit
#mysql -u root -p icinga < /usr/share/icinga2-ido-mysql/schema/mysql.sql
ERROR 1060 (42S21) at line 1436: Duplicate column name 'endpoint_object_id'

That line contains:

ALTER TABLE icinga_servicestatus ADD COLUMN endpoint_object_id bigint default NULL;

This was the first time command was lunched, so no reason for detecting Duplicate column name.

## Your Environment

* Version used (`icinga2 --version`): icinga2-6.6.3
* Operating System and version: Red Hat Enterprise Linux Server release 6.7 (Santiago)

**Comment by dnsmichi** [comment]
I'm not able to reproduce this. I do believe that you've run the schema import twice.

**Comment by ekimike** [comment]
Hi Michael, 


I did it once, what I did was delete database and run again script, it worded.

Thanks for your support.

**Comment by dnsmichi** [comment]
Does that mean this issue is resolved?

**Comment by ekimike** [comment]
Yes, issue is resolved now.

Thanks for your support.
