### ISSUE TITLE
Review GitHub labels

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5195]
Might be a good idea to add sort of `area/abc` and `type/bug`, or not.

Other projects:

https://github.com/ansible/ansible/issues
https://github.com/docker/compose/issues
https://github.com/influxdata/influxdb/issues
https://github.com/elastic/kibana/issues

**Comment by lazyfrosch** [comment]
Please keep in mind: Use only labels the maintainers need to filter / sort issues

**Comment by Crunsher** [comment]
An idea In regards to this specific issue: A "meta" tag for these specific issues that fit nowhere but regard the project itself or its organization

**Comment by dnsmichi** [comment]
We'll discuss this with @lippserd soon.
