### ISSUE TITLE
Issues changing /usr path in icinga2.spec v2.6.3 tar.gz to create RPM (centos 7)

### ISSUE THREAD

**Issue by Esteban2812** [Icinga/icinga2#5197]
## General Summary

Trying to create RPMs files from tar.gz changing spec file. So during RPM installation it locate files in different path.

## Expected Behavior

Have RPM files created.
## Current Behavior

Fail with no File/Directory not found error messages.

## Steps to Reproduce (for bugs)

1. Removing following line from ~/.rpmmacros
> case "${QA_CHECK_RPATHS:-}" in [1yY]*) /usr/lib/rpm/check-rpaths ;; esac \
[rpmmacros.txt](https://github.com/Icinga/icinga2/files/959627/rpmmacros.txt)
2. rpmdev-setuptree
3. mkdir ~/tar; cd ~/tar; wget https://github.com/Icinga/icinga2/archive/v2.6.3.tar.gz
4. cd ~/tar; tar -xvzf v2.6.3.tar.gz
5. cp ~/tar/icinga2-2.6.3/icinga2.spec ~/rpmbuild/SPECS
6. mkdir -p /apps/opt/icinga2/usr
6. change icinga2.spec file in line [278](https://github.com/Icinga/icinga2/blob/e630614c79690cdf5dc1e95e899e40bf869da39e/icinga2.spec#L278) to:
`CMAKE_OPTS="-DCMAKE_INSTALL_PREFIX=/apps/opt/icinga2/usr \`
[icinga2.spec.txt](https://github.com/Icinga/icinga2/files/959641/icinga2.spec.txt)

6. cp ~/tar/v2.6.3.tar.gz ~/rpmbuild/SOURCES
7. rpmbuild -ba icinga2.spec

> symlinked /usr/lib/debug/apps/opt/icinga2/usr/lib64/icinga2/libperfdata.so.2.6.3.debug to /usr/lib/debug/apps/opt/icinga2/usr/lib64/icinga2/libperfdata.so.debug
> 8641 blocks
> + '[' '%{buildarch}' = noarch ']'
> + QA_CHECK_RPATHS=1
> + /usr/lib/rpm/check-buildroot
> + /usr/lib/rpm/redhat/brp-compress
> + /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
> + /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
> + /usr/lib/rpm/redhat/brp-python-hardlink
> + /usr/lib/rpm/redhat/brp-java-repack-jars
> Processing files: icinga2-2.6.3-1.el7.centos.x86_64
> Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.Rsx6Lw
> + umask 022
> + cd /root/rpmbuild/BUILD
> + cd icinga2-2.6.3
> + DOCDIR=/root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-2.6.3
> + export DOCDIR
> + /usr/bin/mkdir -p /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-2.6.3
> + cp -pr COPYING /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-2.6.3
> + exit 0
> Provides: icinga2 = 2.6.3-1.el7.centos icinga2(x86-64) = 2.6.3-1.el7.centos
> Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
> Processing files: icinga2-bin-2.6.3-1.el7.centos.x86_64
> error: File not found:  /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/sbin/icinga2
> 						/root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/apps/opt/icinga2/usr/sbin/icinga2
> error: Directory not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/lib64/icinga2/sbin
> error: File not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/lib64/icinga2/sbin/icinga2
> error: File not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/icinga2
> warning: File not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/icinga2/include
> error: File not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/man/man8/icinga2.8.gz
> Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.BzPfkl
> + umask 022
> + cd /root/rpmbuild/BUILD
> + cd icinga2-2.6.3
> + DOCDIR=/root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-bin-2.6.3
> + export DOCDIR
> + /usr/bin/mkdir -p /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-bin-2.6.3
> + cp -pr COPYING /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-bin-2.6.3
> + cp -pr COPYING.Exceptions /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-bin-2.6.3
> + cp -pr README.md /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-bin-2.6.3
> + cp -pr NEWS /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-bin-2.6.3
> + cp -pr AUTHORS /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-bin-2.6.3
> + cp -pr ChangeLog /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/doc/icinga2-bin-2.6.3
> + exit 0
> 
> 
> RPM build errors:
>     File not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/sbin/icinga2
>     Directory not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/lib64/icinga2/sbin
>     File not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/lib64/icinga2/sbin/icinga2
>     File not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/icinga2
>     File not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/icinga2/include
>     File not found: /root/rpmbuild/BUILDROOT/icinga2-2.6.3-1.el7.centos.x86_64/usr/share/man/man8/icinga2.8.gz
[full_log.txt](https://github.com/Icinga/icinga2/files/959651/full_log.txt)

## Context

Create RPM file from tar.gz in centos 7 environment.

> cat /etc/centos-release
> CentOS Linux release 7.2.1511 (Core)

## Your Environment

* Version used (`icinga2 --version`):2.6.3
* Operating System and version:

> cat /proc/version
> Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Nov 19 22:10:57 UTC 2015

**Comment by lazyfrosch** [comment]
We are not supporting custom paths for Icinga 2.

The support tries to keep as close as it makes sense to LSB paths.

When you want to use custom paths, feel free to patch the buildsystem and scripts. I think we'll be open for patches.

But please don't expect support for this :crying_cat_face:
