### ISSUE TITLE
Missing documentation for defining sort order of "by_ssh_arguments"

### ISSUE THREAD

**Issue by tackerm** [Icinga/icinga2#5198]
I have a legacy Ubuntu 12.04 client that I need to monitor using the `by_ssh` check command. 

## Service definition:
```
object Service "Disk Space /" {
  import "generic-service"

  check_command = "by_ssh"

  vars.by_ssh_command = [ "/usr/lib/nagios/plugins/check_disk" ]
  vars.by_ssh_arguments = {
    "-w" = "20%"
    "-c" = "10%"
    "-p" = "/"
  }

  host_name = "my.host.tld"
}
```

## Expected Behavior
Execute the `check_disk` plugin on the remote host with the arguments in the correct order (i.e. the order I define in the arguments dictionary)

## Current Behavior
According to `/var/log/icinga2/debug.log`, the above service gets executed like this:
```
[2017-04-27 11:27:57 +0200] notice/Process: Running command '/usr/lib/nagios/plugins/check_by_ssh' '-C' ''/usr/lib/nagios/plugins/check_disk' '-c' '10%' '-p' '/' '-w' '20%'' '-H' 'my.host.tld' '-i' '/etc/icinga2/secure/id_rsa' '-l' 'nagios': PID 5172
```

This is problematic, because the `check_disk` plugin expects the `-p` argument to be defined AFTER the `-c` and `-w` arguments - otherwise, it returns wrong results:

```
> /usr/lib/nagios/plugins/check_by_ssh -C '/usr/lib/nagios/plugins/check_disk -c 10% -p / -w 20%' -H my.host.tld -i /etc/icinga2/secure/id_rsa -l nagios
DISK OK - free space: / 981 MB (11% inode=73%);| /=7252MB;;7829;0;8699

> /usr/lib/nagios/plugins/check_by_ssh -C '/usr/lib/nagios/plugins/check_disk -c 10% -w 20% -p /' -H my.host.tld -i /etc/icinga2/secure/id_rsa -l nagios
DISK WARNING - free space: / 981 MB (11% inode=73%);| /=7252MB;6959;7829;0;8699
```

## Possible Solution
Add / document a way to enforce a particular order of `by_ssh_arguments`...?

## Environment

Icinga master:
```
> icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.2 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-1016-aws
  Architecture: x86_64

Build information:
  Compiler: GNU 5.4.0
  Build host: lcy01-31
```

Client:
```
> /usr/lib/nagios/plugins/check_disk -h
check_disk v1.4.15 (nagios-plugins 1.4.15)
(...)
```

**Comment by dnsmichi** [comment]
That's unfortunately a common problem with check_disk requiring arguments in a specific order.

Though it should be possible according to the documentation, if you build the by_ssh_arguments the same way as command arguments.

```
by_ssh_arguments| **Optional.** A dictionary with arguments for the command. This works exactly like the 'arguments' dictionary for ordinary CheckCommands.
```

```
vars.by_ssh_arguments = {
  "-p" = {
     value = "/",
     order = 0
   }
  "-w" = {
     value = "10%",
     order = 1
   }
  "-c" = {
     value = "20%",
     order = 2
   }
}
```

I haven't it tested though. If it works, I'll happily merge a documentation patch from yours :)

**Comment by tackerm** [comment]
Thanks for the hint, it works like a charm! 

The "ordering" is actually documented in chapter [9.3.1](https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/object-types#objecttype-checkcommand-arguments), but silly me only looked at [19.2.7](https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/language-reference#dictionary) (and gave up when I read "unordered list" :man_facepalming: )

I'll be happy to provide a patch, but I'll need some time to figure out what, when and where... ;)

**Comment by dnsmichi** [comment]
We do have a chapter for check_by_ssh which would need some love: https://github.com/Icinga/icinga2/blob/master/doc/7-agent-based-monitoring.md#-ssh

If you need help on how to start with your own patch, please kindly check out the new contribution guide: https://github.com/Icinga/icinga2/blob/master/CONTRIBUTING.md

**Comment by dnsmichi** [comment]
PRs welcome. Closing this as reference.
