### ISSUE TITLE
rename() errors are hidden while rotating logs

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#5199]
Both `compatlogger.cpp:476` and `apilistener.cpp:890` seem to intentionally hide any errors which could happen while `rename()`ing.

## Expected Behavior
Either log a message or throw an exception like `git ls-files -z |grep -zEe $'\\.[ch]pp$' |xargs -0 grep --color=always -nFwe rename` do. (I could fix this (PR), but you should make the design decision.)

## Current Behavior
Both `compatlogger.cpp:476` and `apilistener.cpp:890` seem to intentionally hide any errors which could happen while `rename()`ing.

## Possible Solution
Either log a message or throw an exception like `git ls-files -z |grep -zEe $'\\.[ch]pp$' |xargs -0 grep --color=always -nFwe rename` do. (I could fix this (PR), but you should make the design decision.)

## Steps to Reproduce (for bugs)
1. be a C/C++ programmer
2. look at the code at `compatlogger.cpp:476` and `apilistener.cpp:890`

## Context
Randomly stumbled over this while analysing #4660.

## Your Environment
* Version used (`icinga2 --version`): 2.6.3
* Operating System and version: Ubuntu 16.04

**Comment by dnsmichi** [comment]
That's true, that is intentional at this stage. Exceptions are not an option.

**Comment by Al2Klimov** [comment]
Is logging an option?
