### ISSUE TITLE
Kaspersky incorrectly identifies Icinga as malware

### ISSUE THREAD

**Issue by gr4ssi** [Icinga/icinga2#5200]
Kaspersky Endpoint Security 10.2.5.3201 (mr3) with database from 27.4.2017 recognizes the Icinga 2 Windows Agent as very suspicious and wants to quarantine it:

![image](https://cloud.githubusercontent.com/assets/19840345/25482776/7ac4e474-2b53-11e7-999a-0070c85c2633.png)

## Possible solution
Add icinga2.exe to allowed executables (a.k.a. exception).

**Comment by dnsmichi** [comment]
It's a false positive, I've seen that a while ago somewhere too. There's not much we can do about it, the icinga2 service requires network traffic and also runs checks. It might be a good idea to report that to Kaspersky via their application if possible.

**Comment by gr4ssi** [comment]
I wrote them an email, but am not sure if a human is going to read it. ;-)

I also declared the icinga2.exe as trustworthy and whitelisted the folder.

**Comment by gunnarbeutner** [comment]
Have you heard back from Kaspersky at all?

**Comment by gr4ssi** [comment]
Hi Gunnar,
when I scan it directly on KAV website, it says it's safe. Yay!
I think it's just the heuristics going ballistic.
Since everything is automated at Kaspersky (i.e. reporting, etc.) you don't really get a usefule reply. 
I'd recommend to whitelist the folder or exe in Kaspersky Admin Panel / Admin-Server for the server group.

**Comment by dnsmichi** [comment]
Ok, thanks, so we'll keep this as "we know it but cannot do anything about it".
