### ISSUE TITLE
Icinga2 Setup Wizard on Windows fails, if Instance Name contains a blank

### ISSUE THREAD

**Issue by gr4ssi** [Icinga/icinga2#5201]
The setup wizard doesn't like blanks in the instance name.

Exe used: http://packages.icinga.org/windows/Icinga2-v2.6.3-x86_64.msi

![image](https://cloud.githubusercontent.com/assets/19840345/25489734/0e7616c2-2b6b-11e7-8325-60a771d2d61f.png)

Error at "--endpoint Icinga 2,":

> Running command 'icinga2.exe node setup --master_host icinga2.domain.local,5665 --endpoint Icinga 2,icinga2.domain.local,5665 --listen ::,5665 --accept-config --accept-commands --ticket "81ba756a51f555a85010428ae3e823e221a280f8" --trustedcert "C:\Users\mgr\AppData\Local\Temp\tmpB4C1.tmp" --cn "nb-mgr8" --zone "nb-mgr8"' produced the following output:
> critical/cli: Too many arguments. At most 0 arguments may be specified.

## Solution
Delete and recreate the instance without a "blank" in the name. Maybe, an edit button would be nice.
I'd recommend to check the "Instance Name" field for non commandline appropriate symbols and give a warning.

**Comment by Crunsher** [comment]
Edit button refs #4128

**Comment by dnsmichi** [comment]
Was solved with v2.8.

**Comment by slalomsk8er** [comment]
I had the some error message on the CLI with the current version on Windows 2012 r2 while on 2016 it worked.
Turns out I had to quote all arguments containing commas for PowerShell - hope this message helps someone
