### ISSUE TITLE
Icinga2 service reload (on master server) creates tcp connection pileup

### ISSUE THREAD

**Issue by jmcmellen** [Icinga/icinga2#5204]
## Expected Behavior
Reloading the icinga2 service on the server should check the config and continue allowing normal connections from clients.

## Current Behavior
Running service icinga2 reload on the server checks the config and logs the SIGHUP, but within minutes each client that attempts to connect stalls out with what appears to be an incomplete TLS connection, resulting in hundreds or thousands of services in "Unknown" status. During this time, the total number of established tcp connections jumps up as if none of the old connections have closed. Fully stopping the icinga2 service and starting again results in normal behavior, clients can complete their connections and the tcp connections go back to a normal level.

## Possible Solution
I've noticed similar symptoms in issues #5007, #3902 and #3881.

## Steps to Reproduce (for bugs)

1. service icinga2 reload
This happens pretty much consistently every time we run a reload, rather than a restart. I'm not sure what pieces of config or debug logs are most relevant, any suggestions are welcome.

## Context

When the config is 'reloaded' after an update, the system doesn't function

## Your Environment

* Version used (`icinga2 --version`): r2.6.3-1
* Operating System and version: Ubuntu 14.04
* Enabled features (`icinga2 feature list`): api checker command graphite ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.4.0
* Config validation (`icinga2 daemon -C`): no errors
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by ghouscht** [comment]
Any updates on this? We see the same issue on a clustered Icinga2 installation (dual master running version 2.6.3) with about ~1550 Hosts and nearly 75000 services.

**Comment by dnsmichi** [comment]
This will be fixed with 2.11, you can test the snapshot packages.
