### ISSUE TITLE
Typo in Getting Started Guide

### ISSUE THREAD

**Issue by chrkli193** [Icinga/icinga2#5206]
Hello,

in the Getting started guide:
https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/getting-started
below
"RHEL/CentOS 7:"
There is one "s" to much at https
"yum install https**s**://packages.icinga.com/epel/7/release/noarch/icinga-rpm-release-7-1.el7.centos.noarch.rpm"

**Comment by dnsmichi** [comment]
Thanks 👍

**Comment by dnsmichi** [comment]
#5203 fixes this thanks to @Tontonitch :) I'm closing this one.

@chrkli193  In case you want to contribute a docs patch, please kindly follow our new contributing guide :)

https://github.com/Icinga/icinga2/blob/master/CONTRIBUTING.md

It also includes a description for running a local markdown viewer instance. Please let us know if anything's unclear there.
