### ISSUE TITLE
Add additional logging for config sync (master)

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#5213]
- [ ] Log the new timestamp version on config master
- [ ] Log also file deletions during sync
- [ ] There is no clear indication in log when the new Icinga daemon took over (only the exit of the old one)

**Comment by dnsmichi** [comment]
@Crunsher wasn't there another ticket for v2.7.0 which already solves this?

**Comment by Crunsher** [comment]
No, the ticket was split into two. One is done and in 2.7, but this one kind of got forgotten :(

**Comment by dnsmichi** [comment]
Not relevant anymore.
