### ISSUE TITLE
Allow Graphite Writer to write Tags to Grafana database

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#5214]
Hi,

It would be nice to use the new Tagging feature of Grafana. ( http://docs.grafana.org/reference/templating/ ) For this to work the Icinga 2 Graphite Writer would have to communicate with the Grafana database, as far as I can see.

This would allow to forward customvariables of Icinga 2 objects to Grafana so one could easily build dashboards that include groups of hosts/services only identified by customvariabls/tags.

Cheers,
Thomas

**Comment by friesoft** [comment]
That would be really cool :)

**Comment by dnsmichi** [comment]
That would need a separate client implementation handling the Grafana requests, and might lead into performance issues (i.e. updating the tags on each metric, or periodically?). Please stop by and refine that idea together with @lippserd :)

**Comment by dnsmichi** [comment]
I'm closing this in favour of #6144.
