### ISSUE TITLE
icingaweb2 is showing backend icinga2 process is not running

### ISSUE THREAD

**Issue by Aamr10** [Icinga/icinga2#5217]
hello,

I have a big probleme with icinga2 .

I have this message in my page web icinga2 : icingaweb2 is showing backend icinga2 process is not running .   And now nothings is working :( 

Please what can i do to resolve this issue ?

**Comment by gunnarbeutner** [comment]
This does not look like a bug. Please use one of our other support channels (e.g. IRC, forum, etc.) for this: https://www.icinga.com/community/get-involved/
