### ISSUE TITLE
Error when compiling in centos6

### ISSUE THREAD

**Issue by Esteban2812** [Icinga/icinga2#5233]
## Expected Behavior

As following step performed success:
`cmake .. -DCMAKE_INSTALL_PREFIX=/apps/opt/icingadir -DICINGA2_WITH_PGSQL=OFF`
I expect the "`make`" step perform without issues.

## Current Behavior

When compiling following using next command:
`make`
This error is show:
[ 31%] Building CXX object lib/base/CMakeFiles/base.dir/base_unity.cpp.o
In file included from /usr/include/boost/range/iterator.hpp:19:0,
                 from /usr/include/boost/range/begin.hpp:24,
                 from /usr/include/boost/range/functions.hpp:18,
                 from /usr/include/boost/range/iterator_range.hpp:34,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/case_conv.hpp:19,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/string.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/type.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:213,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/range/mutable_iterator.hpp: In instantiation of ‘struct boost::range_mutable_iterator<boost::intrusive_ptr<icinga::Array> >’:
/usr/include/boost/mpl/eval_if.hpp:60:31:   required from ‘struct boost::mpl::eval_if_c<false, boost::range_const_iterator<boost::intrusive_ptr<icinga::Array> >, boost::range_mutable_iterator<boost::intrusive_ptr<icinga::Array> > >’
/usr/include/boost/range/iterator.hpp:63:63:   required from ‘struct boost::range_iterator<boost::intrusive_ptr<icinga::Array> >’
/usr/include/boost/range/begin.hpp:96:55:   required by substitution of ‘template<class T> typename boost::range_iterator<C>::type boost::begin(T&) [with T = boost::intrusive_ptr<icinga::Array>]’
/apps/opt/icingainstall/icinga2-master/lib/base/array-script.cpp:125:27:   required from here
/usr/include/boost/range/mutable_iterator.hpp:37:52: error: no type named ‘iterator’ in ‘class boost::intrusive_ptr<icinga::Array>’
         typedef BOOST_DEDUCED_TYPENAME C::iterator type;
                                                    ^
In file included from /usr/include/boost/range/iterator.hpp:20:0,
                 from /usr/include/boost/range/begin.hpp:24,
                 from /usr/include/boost/range/functions.hpp:18,
                 from /usr/include/boost/range/iterator_range.hpp:34,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/case_conv.hpp:19,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/string.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/type.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:213,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/range/const_iterator.hpp: In instantiation of ‘struct boost::range_const_iterator<boost::intrusive_ptr<icinga::Array> >’:
/usr/include/boost/mpl/eval_if.hpp:60:31:   required from ‘struct boost::mpl::eval_if_c<true, boost::range_const_iterator<boost::intrusive_ptr<icinga::Array> >, boost::range_mutable_iterator<const boost::intrusive_ptr<icinga::Array> > >’
/usr/include/boost/range/iterator.hpp:63:63:   required from ‘struct boost::range_iterator<const boost::intrusive_ptr<icinga::Array> >’
/usr/include/boost/range/begin.hpp:107:61:   required by substitution of ‘template<class T> typename boost::range_iterator<const T>::type boost::begin(const T&) [with T = boost::intrusive_ptr<icinga::Array>]’
/apps/opt/icingainstall/icinga2-master/lib/base/array-script.cpp:125:27:   required from here
/usr/include/boost/range/const_iterator.hpp:37:58: error: no type named ‘const_iterator’ in ‘class boost::intrusive_ptr<icinga::Array>’
         typedef BOOST_DEDUCED_TYPENAME C::const_iterator type;
                                                          ^
In file included from /usr/include/boost/range/iterator.hpp:19:0,
                 from /usr/include/boost/range/begin.hpp:24,
                 from /usr/include/boost/range/functions.hpp:18,
                 from /usr/include/boost/range/iterator_range.hpp:34,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/case_conv.hpp:19,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/string.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/type.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:213,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/range/mutable_iterator.hpp: In instantiation of ‘struct boost::range_mutable_iterator<boost::intrusive_ptr<icinga::Dictionary> >’:
/usr/include/boost/mpl/eval_if.hpp:60:31:   required from ‘struct boost::mpl::eval_if_c<false, boost::range_const_iterator<boost::intrusive_ptr<icinga::Dictionary> >, boost::range_mutable_iterator<boost::intrusive_ptr<icinga::Dictionary> > >’
/usr/include/boost/range/iterator.hpp:63:63:   required from ‘struct boost::range_iterator<boost::intrusive_ptr<icinga::Dictionary> >’
/usr/include/boost/range/begin.hpp:96:55:   required by substitution of ‘template<class T> typename boost::range_iterator<C>::type boost::begin(T&) [with T = boost::intrusive_ptr<icinga::Dictionary>]’
/apps/opt/icingainstall/icinga2-master/lib/base/dictionary-script.cpp:76:36:   required from here
/usr/include/boost/range/mutable_iterator.hpp:37:52: error: no type named ‘iterator’ in ‘class boost::intrusive_ptr<icinga::Dictionary>’
         typedef BOOST_DEDUCED_TYPENAME C::iterator type;
                                                    ^
In file included from /usr/include/boost/range/iterator.hpp:20:0,
                 from /usr/include/boost/range/begin.hpp:24,
                 from /usr/include/boost/range/functions.hpp:18,
                 from /usr/include/boost/range/iterator_range.hpp:34,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/case_conv.hpp:19,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/string.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/type.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:213,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/range/const_iterator.hpp: In instantiation of ‘struct boost::range_const_iterator<boost::intrusive_ptr<icinga::Dictionary> >’:
/usr/include/boost/mpl/eval_if.hpp:60:31:   required from ‘struct boost::mpl::eval_if_c<true, boost::range_const_iterator<boost::intrusive_ptr<icinga::Dictionary> >, boost::range_mutable_iterator<const boost::intrusive_ptr<icinga::Dictionary> > >’
/usr/include/boost/range/iterator.hpp:63:63:   required from ‘struct boost::range_iterator<const boost::intrusive_ptr<icinga::Dictionary> >’
/usr/include/boost/range/begin.hpp:107:61:   required by substitution of ‘template<class T> typename boost::range_iterator<const T>::type boost::begin(const T&) [with T = boost::intrusive_ptr<icinga::Dictionary>]’
/apps/opt/icingainstall/icinga2-master/lib/base/dictionary-script.cpp:76:36:   required from here
/usr/include/boost/range/const_iterator.hpp:37:58: error: no type named ‘const_iterator’ in ‘class boost::intrusive_ptr<icinga::Dictionary>’
         typedef BOOST_DEDUCED_TYPENAME C::const_iterator type;
                                                          ^
In file included from /usr/include/boost/thread/pthread/recursive_mutex.hpp:11:0,
                 from /usr/include/boost/thread/recursive_mutex.hpp:16,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/thread/locks.hpp: In instantiation of ‘boost::unique_lock<Mutex>& boost::unique_lock<Mutex>::operator=(boost::unique_lock<Mutex>&&) [with Mutex = boost::mutex]’:
/usr/include/boost/thread/future.hpp:414:33:   required from here
/usr/include/boost/thread/locks.hpp:269:22: error: cannot bind ‘boost::unique_lock<boost::mutex>’ lvalue to ‘boost::unique_lock<boost::mutex>&&’
             swap(temp);
                      ^
/usr/include/boost/thread/locks.hpp:279:14: error:   initializing argument 1 of ‘void boost::unique_lock<Mutex>::swap(boost::unique_lock<Mutex>&&) [with Mutex = boost::mutex]’
         void swap(unique_lock&& other)
              ^
make[2]: *** [lib/base/CMakeFiles/base.dir/base_unity.cpp.o] Error 1
make[1]: *** [lib/base/CMakeFiles/base.dir/all] Error 2
make: *** [all] Error 2

**In a second try, I got this error:**

[ 23%] Building CXX object lib/base/CMakeFiles/base.dir/base_unity.cpp.o
In file included from /usr/include/boost/range/iterator.hpp:19:0,
                 from /usr/include/boost/range/begin.hpp:24,
                 from /usr/include/boost/range/functions.hpp:18,
                 from /usr/include/boost/range/iterator_range.hpp:34,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/case_conv.hpp:19,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/string.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/type.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:213,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/range/mutable_iterator.hpp: In instantiation of ‘struct boost::range_mutable_iterator<boost::intrusive_ptr<icinga::Array> >’:
/usr/include/boost/mpl/eval_if.hpp:60:31:   required from ‘struct boost::mpl::eval_if_c<false, boost::range_const_iterator<boost::intrusive_ptr<icinga::Array> >, boost::range_mutable_iterator<boost::intrusive_ptr<icinga::Array> > >’
/usr/include/boost/range/iterator.hpp:63:63:   required from ‘struct boost::range_iterator<boost::intrusive_ptr<icinga::Array> >’
/usr/include/boost/range/begin.hpp:96:55:   required by substitution of ‘template<class T> typename boost::range_iterator<C>::type boost::begin(T&) [with T = boost::intrusive_ptr<icinga::Array>]’
/apps/opt/icingainstall/icinga2-master/lib/base/array-script.cpp:125:27:   required from here
/usr/include/boost/range/mutable_iterator.hpp:37:52: error: no type named ‘iterator’ in ‘class boost::intrusive_ptr<icinga::Array>’
         typedef BOOST_DEDUCED_TYPENAME C::iterator type;
                                                    ^
In file included from /usr/include/boost/range/iterator.hpp:20:0,
                 from /usr/include/boost/range/begin.hpp:24,
                 from /usr/include/boost/range/functions.hpp:18,
                 from /usr/include/boost/range/iterator_range.hpp:34,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/case_conv.hpp:19,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/string.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/type.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:213,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/range/const_iterator.hpp: In instantiation of ‘struct boost::range_const_iterator<boost::intrusive_ptr<icinga::Array> >’:
/usr/include/boost/mpl/eval_if.hpp:60:31:   required from ‘struct boost::mpl::eval_if_c<true, boost::range_const_iterator<boost::intrusive_ptr<icinga::Array> >, boost::range_mutable_iterator<const boost::intrusive_ptr<icinga::Array> > >’
/usr/include/boost/range/iterator.hpp:63:63:   required from ‘struct boost::range_iterator<const boost::intrusive_ptr<icinga::Array> >’
/usr/include/boost/range/begin.hpp:107:61:   required by substitution of ‘template<class T> typename boost::range_iterator<const T>::type boost::begin(const T&) [with T = boost::intrusive_ptr<icinga::Array>]’
/apps/opt/icingainstall/icinga2-master/lib/base/array-script.cpp:125:27:   required from here
/usr/include/boost/range/const_iterator.hpp:37:58: error: no type named ‘const_iterator’ in ‘class boost::intrusive_ptr<icinga::Array>’
         typedef BOOST_DEDUCED_TYPENAME C::const_iterator type;
                                                          ^
In file included from /usr/include/boost/range/iterator.hpp:19:0,
                 from /usr/include/boost/range/begin.hpp:24,
                 from /usr/include/boost/range/functions.hpp:18,
                 from /usr/include/boost/range/iterator_range.hpp:34,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/case_conv.hpp:19,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/string.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/type.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:213,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/range/mutable_iterator.hpp: In instantiation of ‘struct boost::range_mutable_iterator<boost::intrusive_ptr<icinga::Dictionary> >’:
/usr/include/boost/mpl/eval_if.hpp:60:31:   required from ‘struct boost::mpl::eval_if_c<false, boost::range_const_iterator<boost::intrusive_ptr<icinga::Dictionary> >, boost::range_mutable_iterator<boost::intrusive_ptr<icinga::Dictionary> > >’
/usr/include/boost/range/iterator.hpp:63:63:   required from ‘struct boost::range_iterator<boost::intrusive_ptr<icinga::Dictionary> >’
/usr/include/boost/range/begin.hpp:96:55:   required by substitution of ‘template<class T> typename boost::range_iterator<C>::type boost::begin(T&) [with T = boost::intrusive_ptr<icinga::Dictionary>]’
/apps/opt/icingainstall/icinga2-master/lib/base/dictionary-script.cpp:76:36:   required from here
/usr/include/boost/range/mutable_iterator.hpp:37:52: error: no type named ‘iterator’ in ‘class boost::intrusive_ptr<icinga::Dictionary>’
         typedef BOOST_DEDUCED_TYPENAME C::iterator type;
                                                    ^
In file included from /usr/include/boost/range/iterator.hpp:20:0,
                 from /usr/include/boost/range/begin.hpp:24,
                 from /usr/include/boost/range/functions.hpp:18,
                 from /usr/include/boost/range/iterator_range.hpp:34,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/case_conv.hpp:19,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/string.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/type.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:213,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/range/const_iterator.hpp: In instantiation of ‘struct boost::range_const_iterator<boost::intrusive_ptr<icinga::Dictionary> >’:
/usr/include/boost/mpl/eval_if.hpp:60:31:   required from ‘struct boost::mpl::eval_if_c<true, boost::range_const_iterator<boost::intrusive_ptr<icinga::Dictionary> >, boost::range_mutable_iterator<const boost::intrusive_ptr<icinga::Dictionary> > >’
/usr/include/boost/range/iterator.hpp:63:63:   required from ‘struct boost::range_iterator<const boost::intrusive_ptr<icinga::Dictionary> >’
/usr/include/boost/range/begin.hpp:107:61:   required by substitution of ‘template<class T> typename boost::range_iterator<const T>::type boost::begin(const T&) [with T = boost::intrusive_ptr<icinga::Dictionary>]’
/apps/opt/icingainstall/icinga2-master/lib/base/dictionary-script.cpp:76:36:   required from here
/usr/include/boost/range/const_iterator.hpp:37:58: error: no type named ‘const_iterator’ in ‘class boost::intrusive_ptr<icinga::Dictionary>’
         typedef BOOST_DEDUCED_TYPENAME C::const_iterator type;
                                                          ^
In file included from /usr/include/boost/thread/pthread/recursive_mutex.hpp:11:0,
                 from /usr/include/boost/thread/recursive_mutex.hpp:16,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/object.hpp:25,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/application.thpp:4,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.hpp:24,
                 from /apps/opt/icingainstall/icinga2-master/lib/base/application.cpp:20,
                 from /apps/opt/icingainstall/icinga2-master/build/lib/base/base_unity.cpp:1:
/usr/include/boost/thread/locks.hpp: In instantiation of ‘boost::unique_lock<Mutex>& boost::unique_lock<Mutex>::operator=(boost::unique_lock<Mutex>&&) [with Mutex = boost::mutex]’:
/usr/include/boost/thread/future.hpp:414:33:   required from here
/usr/include/boost/thread/locks.hpp:269:22: error: cannot bind ‘boost::unique_lock<boost::mutex>’ lvalue to ‘boost::unique_lock<boost::mutex>&&’
             swap(temp);
                      ^
/usr/include/boost/thread/locks.hpp:279:14: error:   initializing argument 1 of ‘void boost::unique_lock<Mutex>::swap(boost::unique_lock<Mutex>&&) [with Mutex = boost::mutex]’
         void swap(unique_lock&& other)
              ^
make[2]: *** [lib/base/CMakeFiles/base.dir/base_unity.cpp.o] Error 1
make[1]: *** [lib/base/CMakeFiles/base.dir/all] Error 2
make: *** [all] Error 2

## Steps to Reproduce (for bugs)

1. Install requirements as it is stated in (https://github.com/Icinga/icinga2/blob/master/INSTALL.md)
2. In order to fullfil with GCC version, devtools is installed as is stated in this [link](https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b)
```
wget http://linuxsoft.cern.ch/cern/slc6X/x86_64/RPM-GPG-KEY-cern -O RPM-GPG-KEY-cern
wget -O /etc/yum.repos.d/slc6-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo
yum install devtoolset-2
```
3. useradd icinga;su - icinga
4. scl enable devtoolset-2 bash
5. mkdir -p /apps/opt/icingadir ; mkdir -p cd /apps/opt/icingainstall; cd  /apps/opt/icingainstall
6. wget https://github.com/Icinga/icinga2/archive/master.zip -O icinga2.zip
7. unzip -uo icinga2.zip -d .
8. cd /apps/opt/icingainstall/icinga2-master/build
9. cmake .. -DCMAKE_INSTALL_PREFIX=/apps/opt/icingadir
10. make

## Your Environment

* Operating System and version:
Linux version 2.6.32-642.11.1.el6.x86_64 (mockbuild@c1bm.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Fri Nov 18 19:25:05 UTC 2016

**Comment by dnsmichi** [comment]
@lazyfrosch raised the requirement to 1.48 in #5188 that may solve the compiling issue.

**Comment by lazyfrosch** [comment]
Yes your errors are related with a Boost Requirement >= 1.48

Please see:
* https://github.com/Icinga/icinga2/commit/4a1186d46f322ee4ea60b1cfc09aa0b869d0a7b3

Also helpful for you might be:
* https://github.com/Icinga/icinga2/commit/712c526e31be155d4d2337b70ab09bebced373f9
