### ISSUE TITLE
Icinga2: InfluxDB Writer should buffer metrics when InfluxDB is not available

### ISSUE THREAD

**Issue by xenuser** [Icinga/icinga2#5234]
The InfluxDB Writer doesn't buffer metrics when InfluxDB is not available (and comes back later).

## Expected Behavior
InfluxDB Writer should buffer metrics for the case that InfluxDB is not available. In addition, one should be able to configure the "amount" of buffered metrics (e.g. in max. memory being used or max. time waiting).

## Current Behavior
At the moment, the InfluxDB Writer "discards" failed writes, which means that all metrics for this time period (when InfluxDB is down) are lost.

## Possible Solution
It would be great to see that the InfluxDB writer itself is able to buffer. In addition, InfluxDB Writer should log failed writes somewhere (maybe in an own log file).

## Steps to Reproduce (for bugs)
1. Activate InfluxDB Writer
2. Shut down InfluxDB
3. Wait 5 Minutes
4. Start InfluxDB
5. Check e.g. in Grafana for gaps in the metrics graphs

## Context
When having a distributed master setup, it makes sense to let InfluxDB run on every master and let InfluxDB Writer send metrics to all of these InfluxDB instances. Now, when e.g. rebooting/updating some of the master nodes, the InfluxDB data becomes inconsistant because some InfluxDB instances still receive metrics, others don't.

## Your Environment
* Icinga 2.6.3
* Operating System and version: SLES 12 SP1
* Enabled features (`icinga2 feature list`): Depends on the master...

**Comment by nlm** [comment]
Buffering the metrics would require more memory allocations, and it could become quite large overtime, provided you have a large amount of hosts and checks on your monitoring system, don't you think ? I agree that having your influxdb instance down for a long period of time is usually not intended, but you never know.

At least it should be optional, with a limit on the number of metrics in the queue or on the memory usage. Moreover, i think that losing few metrics is not that critical.

**Comment by xenuser** [comment]
Surely buffering metrics would require some memory. In my eyes, this can be "controlled" by making this feature optional and configurable. In addition, the configuration should limit the amount of buffered metrics.

Regarding the importance of metrics: It depends, really. As you know, there are many use cases for Icinga2 and InfluxDB out there. In most cases, customers just want to see fancy graphs (based on InfluxDB and Grafana, for example). But even if we have this "simple" situation, customers/users might get irritated by gaps within the graphs.

But I see also other scenarios. In some cases, customers base their reporting tools on the metrics. I know that IDO DB should contain most data, but as you might know, Icinga2 might move away from storing everything in IDO DB. So having InfluxDB as a basis for reporting is one of the many valid reasons to say: Loosing metrics is bad.

This is why I just propose the feature of metric buffering. And I agree with you to make this feature optional, so nobody would be forced to sacrifice memory or performance.

**Comment by nlm** [comment]
That sounds reasonable. Didn't know that icinga2 was considering moving away from storing everything in ido db. Good news ! In some setups, for the ephemeral data, alternatives would be welcome, as the db operations can be quite intensive when the number of hosts grows. I didn't find any reference to this, though. Mind to give me some links to the relevant articles ? Thanks

**Comment by dnsmichi** [comment]
Icinga isn't moving away from the database approach. It opens up for writing metrics and events to multiple backends. Though I doubt that state based SLA reporting is doable with only TSDBs.

**Comment by dnsmichi** [comment]
If you want to see such a feature, please sponsor a patch for it.

**Comment by xenuser** [comment]
Building a good reporting system on basis of performance data is absolutely possible. You just need some tweaks. But I believe this is off-topic.

Regarding the patch sponsoring: I think that this feature should be mandatory for Icinga2, so I hoped you would give this a certain priority.

However, if you'd accept such a feature when someone external provides a pull request, I would at least evaluate a sponsoring option.

Is there any way you recommend for doing this? Something like patreon.com ?

**Comment by dnsmichi** [comment]
Re-iterating this request. Given the responsibility a monitoring core has - to reliably check, notify and maybe replicate - it shouldn't be bloated with an in-memory queue. We've made that mistake for DB IDO already, and I doubt that OOM just because of an InfluxDB buffer is a thing users would like or we would like to support.

An external daemon which listens on metric events sounds more reasonable to me, and probably would need adoptions to the API event streams, or a different buffer in the middle.

**Comment by voiprodrigo** [comment]
Why not just put Telegraf in the middle? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dnsmichi** [comment]
Thanks, that's actually a pretty nice idea, and leverages this into a proxy mode up in front of InfluxDB. 2.11 also provides HA aware features were just one endpoint will be actively writing to Telegraf then. 

https://community.influxdata.com/t/telegraf-forwarding/4635

That being said, I'll close this feature request as it won't happen from our side, and sponsoring wasn't a thing either.
