### ISSUE TITLE
CheckCommand mongodb does not expose authdb option

### ISSUE THREAD

**Issue by abienkowski** [Icinga/icinga2#5260]
check_mongodb.py has an authdb option to specify the authentication database to be used for the connection to mongodb. In some providers this database name is different from the default "admin" name; Heroku addon mlab free tier authdb is the same name as the database itself.

This has worked in the passed however when I recently upgraded to latest version I've started seeing Username/Password incorrect log message.

                "--authdb" = {
                        value = "$mongodb_authdb$"
                        description = "Database to be used for authentication."
                }

**Comment by gunnarbeutner** [comment]
If you have some spare time maybe you can also submit a pull request for this. :)

**Comment by abienkowski** [comment]
Will do.

**Comment by dnsmichi** [comment]
Ping :)

**Comment by lazyfrosch** [comment]
Is this an ITL / Icinga issue or is it a problem of the plugin itself??

**Comment by dnsmichi** [comment]
I think it is a feature request for adding this option to the ITL. Did cost me 2 minutes, still I would love to see PRs in the future.

Cheers,
Michael
