### ISSUE TITLE
Search function in docs.icinga.com

### ISSUE THREAD

**Issue by chrnie** [Icinga/icinga2#5267]
Hi,

It's not possible to find something on docs.icinga.com .

When searching for "icinga2.conf" the expected result is: "4.3.1 icinga2.conf", because it's a headline with my search term. Now everything else but not this article appears.

When searching for "icinga2 port" I expect to get an entry with the word "port" on the top of the page. 
Now the first entries are "reporting" and "support"

It would be nice if the blue hyperlinks inside the documents worked.

**Comment by dnsmichi** [comment]
Please open an issue over at https://github.com/icinga/icingaweb2-module-doc for future reference (cc @lippserd). This is nothing we can fix within icinga2.
