### ISSUE TITLE
Let "icinga" user do a config reload

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#5268]
Could you add an option to `icinga2 daemon` to reload the configuration. Some customers of mine are not allowed to use `root` on their hosts so they need to work with unprivileged personal users or the `icinga` user (or whatever user Icinga 2 runs with).

(I know one could use `sudo` but that's sometimes not allowed, too)

Cheers,
Thomas

**Comment by gunnarbeutner** [comment]
This seems somewhat out of scope for the official packages, however you can send a `SIGHUP` signal to Icinga 2 to tell it to reload itself.
