### ISSUE TITLE
check_load.exe & check_network.exe on Windows 2008 SP 1 64bit

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icinga2#5270]
Hi,

I installed Icinga 2 agent on a Win 2008 host. It's the only host where check_load and check_network are failing. When I run these commands from command line, it looks like this:

```
PS C:\Program Files\ICINGA2\sbin> .\check_network.exe
Failed to format error message, last error was: 3221228472
PS C:\Program Files\ICINGA2\sbin> .\check_load.exe
The operation completed successfully.
```

I have other Windows clients (Windows 2012 Server) which do not fail.

icinga2-2.6.3-2-g9d26a9c 

Cheers,
  Marianne

![screen shot 2017-05-17 at 12 20 37](https://cloud.githubusercontent.com/assets/11242139/26149676/6c66131e-3afb-11e7-95be-14de6512d640.jpg)

**Comment by gunnarbeutner** [comment]
IIRC the minimum supported version is Windows Server 2012 thanks to some functions for IPv6 we're using in the Windows plugins. @Crunsher (Hi!) probably knows more about this.

**Comment by Crunsher** [comment]
General support for 2008 ended sometime two years ago. But extended support still goes on as long as somebody continues to throw money at Microsoft :(

But judging from the docs, installer and tickets #2967, we do somehow still support it. 

Prepare for ugly preprocessor version checking! (Ipv6 will not be supported for check_ping on 2008.)

**Comment by gunnarbeutner** [comment]
#ifdef wouldn't work in this case because that would require us to build multiple sets of Icinga binaries for different Windows versions. :)

**Comment by Crunsher** [comment]
@gunnarbeutner was unable to reproduce this using Windows 2008 R2.
1. Are your servers localized? (ie not english)
2. Could you run both commands with --debug and provide the output?

**Comment by sysadmama** [comment]
Sure I'll do - when I'm back from vacation :)

**Comment by sysadmama** [comment]
Hi,

sorry, lots of todos... :(

I just updated the box to 2.8.1.
* `check_network.exe` now does what it's intended to do
* after `lodctr /r`, also `check_load.exe` works perfectly

That why I'll close the issue. Thanks a lot for your help.

Cheers,
  Marianne

**Comment by mmartinello** [comment]
Hi, I'm still having the same error:

![Screenshot 2022-02-24 at 16 56 08](https://user-images.githubusercontent.com/3822398/155559877-35cba3b6-6ad8-49a5-96bf-d8ee7cdbeda6.png)

The server is **Windows Server 2019** and I upgraded Icinga to **v2.13.1**.

I've already tried to execute `lodctr /r` without success.
