### ISSUE TITLE
Enhance notification command chapter in the docs

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5273]
https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics#notification-commands

Should include changes from #5170

**Comment by sysadmama** [comment]
I'm working on that :-)

**Comment by dnsmichi** [comment]
Thanks, closing in favor of #5333 :-)
