### ISSUE TITLE
nsca-ng package not in icinga repository

### ISSUE THREAD

**Issue by majales** [Icinga/icinga2#5276]
Package nsca-ng is no longer to be found in icinga repository. 
I have installed icinga one year ago together with nsca-ng from icinga repository today I found nsca-ng is no longer part of repository. What have changed? Is there any other rpm/deb source of nsca-ng?

Exact path of package was: http://packages.icinga.org/epel/7/release/x86_64/nsca-ng-server-1.4-1.el7.centos.x86_64.rpm

**Comment by dnsmichi** [comment]
This package wasn't officially maintained by the Icinga project and has been sitting there for testing reasons. Recent changes in the build system removed the package. nsca-ng is an external project, so your best bet is to build it from the spec file. You'll need to look into the `redhat` branch: https://github.com/weiss/nsca-ng/tree/redhat
