### ISSUE TITLE
Config directory outside icinga2 install dir.

### ISSUE THREAD

**Issue by mamiral** [Icinga/icinga2#5281]
I have encountered strange behaviour when building rpm from source, I'm using my own .spec file.

## Expected Behavior

I expect when setting -DCMAKE_INSTALL_SYSCONFDIR with an absolute path all etc/ content from icinga2 gets installed into that path.

## Current Behavior

Current behavior is such, that if I specify -DCMAKE_INSTALL_SYSCONFDIR with an absolute path then some parts of etc/ directory get installed to right place and some (e.g. icinga2/features-available directory) gets instaled to CMAKE_INSTALL_PREFIX/CMAKE_INSTALL_SYSCONFDIR.

For example:
```
CMAKE_INSTALL_PREFIX = /home/user/monsys/icinga2
CMAKE_INSTALL_SYSCONFDIR = /home/user/monsys/config
```

I get some parts of etc/ directory installed to
`/home/user/monsys/config/icinga2/{features-enabled,...}`
and some parts to
`/home/user/monsys/icinga2/home/user/monsys/config/icinga2/{features-available,...}`
I have shown example for features-anabled and features-available because I know they get installed wrong (or right).

## Possible Solution

Soution I found is to set CMAKE_INSTALL_SYSCONFDIR as a relative path (regarding to MAKE_INSTALL_PREFIX). I couldn't find this documented anywhere.

E.g.
`CMAKE_INSTALL_SYSCONFDIR=../config`

## Steps to Reproduce (for bugs)

1. Set -DCMAKE_INSTALL_PREFIX
2. Set -DCMAKE_INSTALL_SYSCONFDIR to outside of install directory as absolute path
3. etc/ gets installed into two different locations in two parts.

## Context

I'm building custom RPM for our new monitoring system and our wish is to have all config files in one place (icinga2, icingaweb2, pnp4nagios...).

## Your Environment

Centos 6.8, icinga 2.6.3
* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by mamiral** [comment]
Have also found out that the **mainlog** module SEGFAULTS without any explanation if RW permissions on CMAKE_INSTALL_LOCALSTATEDIR directory are not set properly.

**Comment by dnsmichi** [comment]
Packages set those permissions accordingly. Source installations sometimes lack these and are therefore not officially supported.
