### ISSUE TITLE
acknowledge_expire = 1 does not show Expire Time date/time-picker

### ISSUE THREAD

**Issue by pinkgothic** [Icinga/icinga2#5282]
When setting "acknowledge_expire = 1" in `/etc/icingaweb2/modules/monitoring/config.ini`, the "Use Expire Time" checkbox is checked, but the "Expire Time" date/time-picker is not visible. (The checkbox needs to be unchecked and re-checked before it appears.)

See also https://monitoring-portal.org/index.php?thread/39979-defaults-when-acknowledging-problems-sticky-acknowledgement-expiry-time/

## Expected Behavior

I expect that when the "Use Expire Time" checkbox is ticked on initial page load, that the "Expire Time" date/time-picker is also visible.

## Current Behavior

The "Expire Time" date/time-picker is not visible, unless the checkbox is unchecked and then checked aain.

## Possible Solution

In the file `/usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php`, change:

```
        if (isset($formData['expire']) && (bool) $formData['expire'] === true) {
```
...to:

```
        if (
           ((bool) $config->get('settings', 'acknowledge_expire', false))
           || (isset($formData['expire']) && (bool) $formData['expire'] === true)
        ) {
```

## Steps to Reproduce (for bugs)

1. edit `/etc/icingaweb2/modules/monitoring/config.ini`
2. add `[settings]` section into the file if it does not yet exist
3. add `acknowledge_expire = 1` to the file, in the `[settings]` section
4. restart icinga
5. click into a currently broken service
6. click 'Acknowledge'
7. notice that the 'Expire Time' date/time-picker is missing even though the 'Use Expire Time' checkbox is ticked

## Context

The setting `acknowledge_expire` is currently not effective for what we wanted to use it for - namely reduce the mad clicking that needs to happen if there's a larger-scale infrastructural problem (that we definitely don't want to acknowledge forever). Our desired defaults are:

```
acknowledge_expire = 1
acknowledge_sticky = 1
acknowledge_notify = 0
```

...but currently only help to a limited degree.

## Your Environment

* Version used (`icinga2 --version`): `v2.6.2`
* Operating System and version:
```
System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.10.2.el7.x86_64
  Architecture: x86_64
```
* Enabled features (`icinga2 feature list`):
```
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification
```
* Icinga Web 2 version and modules (System - About):
** Version: 2.4.1
** Loaded modules: businessprocess, director, fileshipper, monitoring
* Config validation (`icinga2 daemon -C`): Validates.
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
Unfortunately you've created the issue in the wrong project. Please edit your issue and copy it to icinga/icingaweb2.

**Comment by pinkgothic** [comment]
Interesting, I thought icingaweb2 was about the frontend - whoops. :) Thanks for the kind nudge! I've moved it to https://github.com/Icinga/icingaweb2/issues/2848.
