### ISSUE TITLE
centos5 snapshot builds bring up unknown OpenSSL symbols

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga2#5289]
https://build.icinga.com/job/icinga2-snapshot/job/rpm-centos-5-1binary/arch=x86_64/1/consoleFull

* icinga2-2.6.3.296.g60b45ae
* openssl-devel-0.9.8e-27.el5_10.4.x86_64

```
In file included from /home/jenkins/workspace/icinga2-snapshot/rpm-centos-5-1binary/arch/x86_64/rpmbuild/BUILD/icinga2-2.6.3.296.g60b45ae/lib/base/base_unity.cpp:62:0:
/home/jenkins/workspace/icinga2-snapshot/rpm-centos-5-1binary/arch/x86_64/rpmbuild/BUILD/icinga2-2.6.3.296.g60b45ae/lib/base/tlsutility.cpp: In function 'int icinga::MakeX509CSR(const icinga::String&, const icinga::String&, const icinga::String&, const icinga::String&, bool)':
/home/jenkins/workspace/icinga2-snapshot/rpm-centos-5-1binary/arch/x86_64/rpmbuild/BUILD/icinga2-2.6.3.296.g60b45ae/lib/base/tlsutility.cpp:412:5: error: 'stack_st_X509_EXTENSION' was not declared in this scope
     stack_st_X509_EXTENSION *exts = sk_X509_EXTENSION_new_null();
     ^
/home/jenkins/workspace/icinga2-snapshot/rpm-centos-5-1binary/arch/x86_64/rpmbuild/BUILD/icinga2-2.6.3.296.g60b45ae/lib/base/tlsutility.cpp:412:30: error: 'exts' was not declared in this scope
     stack_st_X509_EXTENSION *exts = sk_X509_EXTENSION_new_null();
                              ^
```

**Comment by lazyfrosch** [comment]
CentOS 5 is not supported anymore, but we should still not break with OpenSSL 0.9.8, right?

**Comment by dnsmichi** [comment]
Change coming from #5194 & #5246

**Comment by dnsmichi** [comment]
Pfuh. I will be more than happy when we can drop support for openssl < 1.0.0.

Adding an extension as SubjectAltName to a CSR behaves differently than signing a self-signed certificate (as we do with csr auto-signing for clients). The original patch in #5246 uses the sample proposed by openssl itself: https://stackoverflow.com/a/15966312

Then 11 year old code base for el5 uses that in a different fashion.
https://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=demos/x509/mkreq.c;h=3dfc65f16435f7056af02f4f00c473028f1593a0;hb=d2cb94952abb3e4d9fbdc5eb57dbac156f56110f#l92

Recent examples also propose to use `STACK_OF(X509_EXTENSION)`, so I've slightly modified the original patch.

**Comment by lazyfrosch** [comment]
I guess we can close this then.

I dropped CentOS 5 from the Buildserver, since its only in extended support, and nobody should really run it anymore...
