### ISSUE TITLE
Docs: Powershell plugins

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5290]
I'm leaving this here as reminder for howtos and docs. Still undecided where to add such.

https://it-wiki.eu/monitoring/icinga2/windows
https://blog.netways.de/2017/04/27/monitoring-powershell-scripts-with-icinga-2/
https://monitoring-portal.org/index.php?thread/32754-icinga2-and-powershell-checks-tutorial/

**Comment by Insurgentes** [comment]
This little article (not written by me) is also very nice and simple to use, might serve as a good starter for those embarking on Powershell with Icinga2:

https://monitoringlab.wordpress.com/monitoring-with-icinga-2-x-and-powershell/

**Comment by RogerSik** [comment]
Would it be a way to add this powershell command into the basic Icinga2 commands.conf (Windows)?

**Comment by dnsmichi** [comment]
http://www.it-wiki.eu/monitoring/icinga2/windows

**Comment by dnsmichi** [comment]
Moving this into the "howto desired" list.
