### ISSUE TITLE
Missing apostrophe in notification log

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga2#5294]
Hi,

there is a missing apostrophe in notification log, after `notification '***` 

```
[2017-05-26 17:27:11 +0200] information/Notification: Sending 'Problem' notification '*** for user '***'
```

PR coming :)

**Comment by gunnarbeutner** [comment]
Thank you very much. Btw, you can save a tiny bit of time by just submitting the PR, i.e. you don't really need **this** ticket at all. There's no harm in creating a separate ticket though. :)
