### ISSUE TITLE
Calendar selector does not show up in Firefox

### ISSUE THREAD

**Issue by andrej-mitrovic-sociomantic** [Icinga/icinga2#5296]
When attempting to select a start time / end time of a `schedule service downtime`, there are no drop-down icons when hovering over the start time / end time fields. They seem to work fine in Chrome, but not in Firefox. 

Tested with Firefox v53.0.2, on Ubuntu Xenial.

Screenshots below.

Chrome v58.0.3029.110:

![chrome](https://cloud.githubusercontent.com/assets/7713325/26502596/a8cf8580-423d-11e7-91ed-fa47c08e9efc.jpg)

Firefox v53.0.2:

![firefox](https://cloud.githubusercontent.com/assets/7713325/26502609/b008e17a-423d-11e7-848b-ef801e494b00.jpg)

**Comment by mcktr** [comment]
Hi,

this issue is more related to [icingaweb2](https://github.com/Icinga/icingaweb2). I would suggest that you are reopen your issue in the icingaweb2 project.

**Comment by lazyfrosch** [comment]
There is already an issue for this here: https://github.com/Icinga/icingaweb2/issues/1199

Still this issue here has been opened in the wrong project.
