### ISSUE TITLE
Monitoring health in API

### ISSUE THREAD

**Issue by yasa1987** [Icinga/icinga2#5300]
Hello,
in Icingaweb2 there is the page called "Monitoring health" that has a submenu named "Feature commands". On this page it's possible to see, for example, if notifications are globally enabled or not (and to change that)

Unfortunately it seems not possible to get this information through the API. It'd be great to have it in order to monitor the state of Icinga2 from another tool (to detect if the monitoring system is in good health or not)

Can it be added to the API ? 

I presume yes as Icingaweb2 can have this information and the following SQL query returns the data :
`select * from icinga_programstatus where instance_id=1;`

**Comment by dnsmichi** [comment]
That's already there, please head over to the documentation: https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/icinga2-api#icinga2-api-status

If need to modify global configuration, look into the actions chapter: https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/icinga2-api#icinga2-api-actions
