### ISSUE TITLE
Host recovery does not clear held back notifications

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icinga2#5318]
A host recovery occurred during a scheduled downtime, but after the downtime ended, a problem notification was generated.

![unbenannt](https://cloud.githubusercontent.com/assets/16338849/26714147/7ea57e76-4770-11e7-9df7-1f49f5ee9094.PNG)

This may be due to our somewhat complicated configuration with regards to notifications, but I can't pinpoint the problem if there is one.

Apply rules for notifications:

```
apply Notification "OTRS-Host-Notification" to Host {
    users = [ "OTRS" ]
    command = "OTRS-Host-Notification"
    
    // default values
    vars.otrs_service = "blahblah"

    // disable re-notifications by default
    interval = 0

    period = "24x7"
    types = [ Custom, Acknowledgement, Problem, Recovery, FlappingStart, FlappingEnd ]
    
    // restrict notification to check_period if set
    if(host.check_period) {
        period = host.check_period
    }

    assign where true
    ignore where host.vars.otrs_enabled == false
}

apply Notification "OTRS-Service-Notification" to Service {
    users = [ "OTRS" ]
    command = "OTRS-Service-Notification"
    
    // default values
    vars.otrs_service = "blahblah"

    // disable re-notifications by default
    interval = 0

    period = "24x7"
    types = [ Custom, Acknowledgement, Problem, Recovery, FlappingStart, FlappingEnd ]

    // restrict notification to check_period if set
    if(service.check_period) {
        period = service.check_period
    } else if(host.check_period) {
        period = host.check_period
    }

    // Delay service notifications for at least one check interval so that we do not spam
    // service notifications after a downtime window ends or a host recovers without
    // having rerun the service check afterwards.
    if(service.retry_interval) {
        times.begin = service.check_interval + 5
    }

    assign where true	
    ignore where service.vars.otrs_enabled == false
    ignore where host.vars.otrs_enabled == false
}
```

Additionally, this apply rule is meant to halt service checks until the host object is back online:

```
apply Dependency "service-to-host-dependency" to Service {
    disable_checks = true
    disable_notifications = true
    ignore_soft_states = false

    assign where true
}
```

## Expected Behavior

A recovery of a host or service should clear any pending notifications.

## Current Behavior

Notifications  are sent out for already resolved problems.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`): v2.6.3
* Operating System and version: CentOS Linux release 7.3.1611 (Core)
* Enabled features (`icinga2 feature list`): api checker command graphite ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.4.1
* Config validation (`icinga2 daemon -C`): valid config
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
I would believe that the downtime is not active in that time, even if the web interface history suggests otherwise. This thing will be solved with 2.9.
