### ISSUE TITLE
output based notifications

### ISSUE THREAD

**Issue by michaeleino** [Icinga/icinga2#5321]
I want to trigger notification only if the plug-in output changed, I used to disable the re notification... but if the output changed while we are on the same state (problem & hard state), we will receive only one notification....

whether further output should be very helpful how to achieve that, or this is not possible  
right now?

* Version used (`icinga2 version:`):  r2.6.3-1
* Operating System and version: ubuntu 16.04.2
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification perfdata
* Icinga Web 2 version and modules (System - About): 2.4.1

**Comment by lazyfrosch** [comment]
No thats not a feature of Icinga, the plugin would have to determine the state and we trigger notifications and our whole state logik around the status of a check changing.

**Comment by dnsmichi** [comment]
I remember that this was called "stalking" in Icinga 1.x and was not working well. Therefore we've never implemented it in 2.x.

If you come up with a proper design specification (how would one configure it, and underlaying code changes) we can discuss further.

**Comment by michaeleino** [comment]
the plugin checks for a big number of issues around 50 up to 100 for each host... that can't be separately monitored.

thus, during any warning or critical states... if any problem occurs it will not be notified.

what is the best way to do that?

**Comment by dnsmichi** [comment]
If the plugin output is that big, I'd store it in a full text database instead, similar to log messages. Icinga 2 isn't built managing and comparing text blobs, the output is rather informative and helps understand the logical state.

Once there are changes in message columns (output, state, etc.) detected, you'll trigger an alert which is then sent to Icinga 2 via its REST API. Possible candidates are Elastic Stack w/ icingabeat & logstash ouput or Graylog & the GelfWriter feature.

**Comment by widhalmt** [comment]
Maybe you should have a look into the `is_volatile` setting. Maybe you can do what you need with this.

**Comment by yoshi314** [comment]
I think you should make a separate check via icinga2 api and check for output changes of a service. Alert if different.

**Comment by Stefar77** [comment]
You could also give the current state (and ack-state) as parameters to your plugin and act accordingly/unack stuff when needed or change state.

**Comment by lippserd** [comment]
@dnsmichi Are we ever going to implement this? Wrapper scripts or is_volatile sound sufficient to me here.

**Comment by dnsmichi** [comment]
As discussed, this was one of the 1.x features we never considered for being compatible, as they are really complicated to implement, document and support. After many years, this is something we are never gonna add into the core. External applications which can receive the event streams and do further calculations are a better choice here. Consider this something for NoMa or variants later.
