### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by terrytibbles** [Icinga/icinga2#5323]
Hello,

Where are the system requirements for Icinga? Minimum requirements, plus software required, etc.

Thanks.

**Comment by lazyfrosch** [comment]
https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/getting-started

For technical reasons:

https://github.com/Icinga/icinga2/blob/master/INSTALL.md

You could have found that yourself looking through our documentation...

**Comment by dnsmichi** [comment]
In terms of system requirements, we do have a reminder ticket with #4974. Feel free to suggest possible documentation updates over there.

**Comment by terrytibbles** [comment]
I did look through your documentation and that's why I raised the case on GitHub. Nowhere does it mention the hardware specs and the software prerequisites. If I'm installing Icinga on an already configured and working server, from source, then I need to know what the software requires to work. If I'm installing it from packages (which seems to be recommended), I also need to know what software it requires to work. Some idea of the hardware requirements would also be useful, even if it is just an example (10 hosts, polling every 3 minutes, with 5 monitors, keeping the data for 6 months). I still don't know what databases are supported, what PHP modules are required, what web servers are supported, and what additional packages are required. This could easily be put in your documentation.

**Comment by dnsmichi** [comment]
The hardware specs are hard to measure as they really depend on the system you are about to build. The best way to design such an environment is to ask community members how their experience and recommendations are. Best on the forums, mailing lists or IRC.

In terms of the software package requirements, your statement is not true. There is documentation for Icinga 2, Icinga Web 2 and each module which explicitly lists the requirements. If you are uncertain where to look - each project provides a `doc/` directory and can be searched on GitHub as well.

**Comment by doublemcz** [comment]
https://github.com/Icinga/icinga2/blob/master/INSTALL.md - Page Not found

**Comment by lazyfrosch** [comment]
@doublemcz why commenting on such an old issue, see the docs:

* https://icinga.com/docs/icinga2/latest/doc/02-installation/
* details on requirements: https://icinga.com/docs/icinga2/latest/doc/21-development/
* for every other question: https://community.icinga.com/
