### ISSUE TITLE
Request for possible renaming  a host in REST API

### ISSUE THREAD

**Issue by adnae** [Icinga/icinga2#5327]
Hi,

currently I'm migrate my monitoring from static config file to dynamic configuration per Icinga 2 REST API.

But my problem is, I can't rename a host. We are using an internal server database and here is it possible, that the customer can change the servername.

**Comment by dnsmichi** [comment]
That's not supported for now, and has similar problems like #4084.

An immediate workaround is to use DELETE and PUT. You might also consider another layer in front of Icinga 2 which is capable of keeping track for object name changes, i.e. the Icinga Director and import sources.

**Comment by Al2Klimov** [comment]
No one will pay not to have a such simple workaround (GET, DELETE, PUT).
