### ISSUE TITLE
ga2 -V

### ISSUE THREAD

**Issue by TinajaLabs** [Icinga/icinga2#5328]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
?

**Comment by TinajaLabs** [comment]
Wow.  Apologies.  All I can think is that I fell asleep at the computer and my head hit the keyboard.  I will be more careful in the future.
