### ISSUE TITLE
 - Web 2 claims that PostgreSQL IDO backend is not running when reloading active endpoint

### ISSUE THREAD

**Issue by aledr** [Icinga/icinga2#5338]
Related to #3616.
Still happens on Icinga 2.6.3.

"Backend icinga2_ido is not running."

**Comment by dnsmichi** [comment]
I'd appreciate it if you could fill in the issue template which was shown upon creation and provide more details about your environment, and your troubleshooting steps. 

https://raw.githubusercontent.com/Icinga/icinga2/master/.github/ISSUE_TEMPLATE.md

**Comment by aledr** [comment]
Hi!

I was getting the information required and it simply started to work again.
It was not working for a couple of weeks with no reason and now ...

Thanks anyway!
