### ISSUE TITLE
command_endpoint = host.name from template only works with apply rule

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#5342]
Hi,

I use a template to set command_endpoint to host.name on many Services. This works with Apply rules but it seems not to work with Service objects.

    template Service "agent-service" {
      import "generic-service"
      command_endpoint = host.name
    }
    apply Service "icinga" {
      import "agent-service"
      check_command = "icinga"
      assign where host.vars.os == "Linux"
      ignore where host.vars.noagent
    }
    object Service "Redis" {
      import "agent-service"
      host_name = "sally.widhalm.or.at"
      check_command = "redis"
      [...]
    }

This results in the following:

    # icinga2 object list --name sally*icinga --type Service
    Object 'sally.widhalm.or.at!icinga' of type 'Service':
      % declared in '/etc/icinga2/zones.d/global-satellite/services-agent.conf', lines 18:1-18:22
      * __name = "sally.widhalm.or.at!icinga"
    [...]
      * command_endpoint = "sally.widhalm.or.at"
        % = modified in '/etc/icinga2/zones.d/global-satellite/services-agent.conf', lines 3:3-3:30
    [...]
    # icinga2 object list --name *Redis --type Service
    Object 'sally.widhalm.or.at!Redis' of type 'Service':
      % declared in '/etc/icinga2/zones.d/master/sally.conf', lines 70:1-70:22
      * __name = "sally.widhalm.or.at!Redis"
    [...]
      * command_endpoint = ""
        % = modified in '/etc/icinga2/zones.d/global-satellite/services-agent.conf', lines 3:3-3:30

## Your Environment

* Version used (`icinga2 --version`): icinga2-2.6.3-1.el6.x86_64
* Operating System and version: CentOS 6 x86_64

**Comment by dnsmichi** [comment]
The `host` and `service` object references are only available inside apply rules, since they are evaluated at a later point in the config compiler. Similar example with Notification and Dependency objects. I'd suggest to use an apply rule here.

**Comment by Thomas-Gelf** [comment]
@widhalmt: I faced this issue more then once. It is irritating, as it would either force you to:

* duplicate all involved templates (and there can by many)
* use only apply rules, even for single objects (not very efficient)
* use only single service objects (even worse)

One way allowing you to work around all this would be doing as follows:
```
template Service "agent-service" {
  import "generic-service"
  if (host) {
    command_endpoint = host.name
  } else {
    command_endpoint = host_name
  }
}
```

In case you need more host properties like vars or so, a snippet like this might help:
```
template Service "agent-service" {
  if (! host) {
    var host = get_host(host_name)
  }
  import "generic-service"
  command_endpoint = host.vars.endpoint_name
}
```
Less efficient, but more powerful. Those examples also try to make sure to not break your config once this issue eventually gets fixed. It's a DSL, so please also note that ordering matters. Using the shown templates, I guess this would work:
```
object Service "Redis" {
  host_name = "sally.widhalm.or.at"
  import "agent-service"
  [...]
}
```

While this wouldn't:
```
object Service "Redis" {
  import "agent-service"
  host_name = "sally.widhalm.or.at"
  [...]
}
```

Cheers,
Thomas

**Comment by pandian912** [comment]
Facing the same issues where setting the command_endpoint within a service object fails if its not an apply ..
