### ISSUE TITLE
Update URL for Icinga v1 docs for clarity

### ISSUE THREAD

**Issue by xurizaemon** [Icinga/icinga2#5346]
This is a website update suggestion, I'm happy for this to be moved to another forum if this isn't the right place.

Currently search results for Icinga2 docs often include results from the Icinga v1 docs. The URL can be misleading: Icinga v1 docs URLs are https://docs.icinga.com/latest/en/ while Icinga v2 docs URLs are https://docs.icinga.com/icinga2/latest/en/

Some approaches to clarifying the separation would be:

* Insert a banner across the top of the Icinga1 docs which state "These docs are for Icinga v1, for updated docs check out Icinga 2 at <url>"
* Move Icinga v1 docs to include icinga1 and/or remove "latest" from their URL.

I understand that these are the *latest Icinga v1 docs*, and I see that there's an "Icinga version 1.14" text on the front page of the Icinga v1 docs (but not on deep-linked pages as frequently found in search results).

Even if current installs favour keeping Icinga v1 docs prominent, I think clarifying the distinction would be beneficial to people making occasional use of docs and coming in from web searches.

**Comment by dnsmichi** [comment]
Hi,

for historical reasons we have to support these URLs. The docs platform will be overhauled in the future, and as such we will certainly take care about more visible differences (or entirely hide the 1.x docs for example). The entry page should be much more clear as well. 

`icinga2` isn't the right place for docs.icinga.com suggestions though. 

Kind regards,
Michael
