### ISSUE TITLE
Possibility to reload a single zone from a master 

### ISSUE THREAD

**Issue by arcadesolutions** [Icinga/icinga2#5355]
Hey,

We are running a three way setup with master - satellite - clients with currently 30 different zones each with 100 - 1000 host/service objects. As for now, everytime you change something (which happens kinda often in our environment) in one zone only, the whole stack gets reloaded eventhough nothing changed for the rest of the zones. This generates a lot of unnecessary traffic as every client has to reconnect to the his satellite and it looks messy in the webgui too. 

Because of that, it would be a amazing to just reload a single zone in which the new config gets pushed to the specific satellite.

I'm not sure if its even possible to do something like this, also you need some consideration in case you make changes on a global-zone which gets pushed to all satellites anyway.

**Comment by dnsmichi** [comment]
A config deployment works like this:

- master reload the process after successful config validation
- satellites reconnect and sync the configuration
- if there are updates received, a validation/reload is triggered

How exactly does your current setup and behaviour look like? Seems you are pushing updates to satellites all the time, which causes them to restart quite often.

**Comment by arcadesolutions** [comment]
You are totally right, it works like you described, we do the same here. 

It can happen that we make changes (e.g adding hosts/services) in different zones without instantly reloading the master process. So what overwhelmed me was probably the fact that at the end of the day there were a lot of changes so all zones (correctly) reloaded their config. 

Thanks for the clarification
