### ISSUE TITLE
Icinga2 Reload - Notifications are sent before downtimes are loaded

### ISSUE THREAD

**Issue by Duffkess** [Icinga/icinga2#5361]
Hi toghether,

I currently have a bug that is like #3864 and #4891, I did the workaround mentioned in the cases.

When I do a reload I get notifications for hosts and services which are in downtime.
When I take a look at the downtimes in the GUI they are there.
I have a standalone server, I create the downtimes via the Icingaweb2 interface.

So it seems like it takes a moment from reloading the configuration and applying the downtimes. In this gap it sends out notifications.

The reload itself is fast but it takes around 20 Seconds to see the changes in the GUI (which is ok for me).

I have ~250 hosts and ~10.000 services

Environment
Version: v2.6.3
Operating System: CentOS Linux 7
Disabled features: compatlog debuglog gelf influxdb opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-mysql livestatus mainlog notification
Icinga Web 2 version: 2.4.1

Thank you in advance.

**Comment by lpoujol** [comment]
Hi, I've the same kind issue.

Just after a reload, some notifications are sent even if they were disabled through the Web UI. 
This seems to happen on hosts/services with disabled notifications or when notifications are disabled globally

It's as if the notification disable setting (per host/service or even globally) isn't directly applied/loaded right before icinga2 starts really working and sending notifications :/

I have +600hosts and +10 000Services

Environment :
OS : Debian Jessie
Icinga2 Version: v2.6.0-2 - From backports
Icingaweb2 Version:  v2.4.1
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification

**Comment by dnsmichi** [comment]
Please see #4696 and #5224 and test that with the snapshot packages.

**Comment by dnsmichi** [comment]
I believe this is fixed with 2.7.0.
