### ISSUE TITLE
Sending a Summary Report per Service

### ISSUE THREAD

**Issue by gabrieleiannetti** [Icinga/icinga2#5362]
Hello there,

as far as I can see Icinga2 may send a notification mail per host.

We would like to retrieve an email which lists multiple hosts for a specific service instead of retrieving multiple notifications for each hosts (its about hundreds of machines affected).

So its not like a notification instead its more an idea of a summary report per service, which would show which hosts are in e.g. CRITICAL state and since when.

Such a summary report could do a periodical check if an interested service state is e.g. CRITICAL of the hosts and would send an proper email. As soon the hosts service state changes to OK the summary report would contain that hosts just one more time to show that its OK again (similar to the notification mechanism but just aggregating the information for multiple hosts).

Are you interested to provide such an reporting mechanism in the Icinga2 Web in the near future or will it be rather not the case?

Regards,
Gabriele

**Comment by dnsmichi** [comment]
That sounds more like an Icinga Web 2, or CLI module specific task. Icinga 2 already provides the interfaces (IDO, API) for that, you'll then need sort of a visualization. You can of course write your own script too, which sends an email based on e.g. the users configured for notifications you'll retrieve via the API. 

Anyhow, if that's something for Icinga Web 2, please create a corresponding issue over there.

**Comment by gabrieleiannetti** [comment]
Ok, thanks.
