### ISSUE TITLE
service to host dependancies not working

### ISSUE THREAD

**Issue by cbnorman** [Icinga/icinga2#5368]
dependency doesnt seem to work for service to hosts. basically i don't want my switch interface checks going critical when the host is down. ie i only want the server team notified that a host is down, not the network team when the server team may have simply turned off a host.

here is my config
```
object Host "test-switch"{
  vars.address = "8.8.8.8"
  check_command = "ping4"
  }

object Host "test-host-02"{
  check_command = "ping4"
  }

object Service "test-interface" {
  host_name = "test-switch"
  check_command = "ping4"
  vars.address = "121.134.243.242"
  vars.parent_host_name = "test-host-02"
  }


apply Dependency "switch_interface_to_host" to Service {
  parent_host_name = service.vars.parent_host_name
  assign where service.name == "test-interface"
}
```

here i can see icinga2 has accepted the config
```
# icinga2 object list --type dependency --name "switch_interface_to_host"
Object 'test-switch!test-interface!switch_interface_to_host' of type 'Dependency':
  % declared in '/etc/icinga2/zones.d/master/dependancies.conf', lines 23:1-23:54
  * __name = "test-switch!test-interface!switch_interface_to_host"
  * child_host_name = "test-switch"
    % = modified in '/etc/icinga2/zones.d/master/dependancies.conf', lines 23:1-23:54
  * child_service_name = "test-interface"
    % = modified in '/etc/icinga2/zones.d/master/dependancies.conf', lines 23:1-23:54
  * disable_checks = false
  * disable_notifications = true
  * ignore_soft_states = true
  * name = "switch_interface_to_host"
  * package = "_etc"
    % = modified in '/etc/icinga2/zones.d/master/dependancies.conf', lines 23:1-23:54
  * parent_host_name = "test-host-02"
    % = modified in '/etc/icinga2/zones.d/master/dependancies.conf', lines 23:1-23:54
    % = modified in '/etc/icinga2/zones.d/master/dependancies.conf', lines 24:3-24:50
  * parent_service_name = ""
  * period = ""
  * states = null
  * templates = [ "switch_interface_to_host" ]
    % = modified in '/etc/icinga2/zones.d/master/dependancies.conf', lines 23:1-23:54
  * type = "Dependency"
  * vars = null
  * zone = "master"
    % = modified in '/etc/icinga2/zones.d/master/dependancies.conf', lines 23:1-23:54
```

## Expected Behavior
I would expect the switch interface service to go in an unreachable state

## Current Behavior
switch interface service shows critical down
![image](https://user-images.githubusercontent.com/10809716/27323168-84b4d4c0-5598-11e7-946e-693d63bb2880.png)

## Possible Solution
not sure why the dependency is not taking affect

## Steps to Reproduce (for bugs)
use config above

## Your Environment

* Version used (`icinga2 --version`):
[root@elkmon132 ~]# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.6.3-151-g46900ce)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-327.22.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Operating System and version:
[root@elkmon132 ~]# hostnamectl
   Static hostname: elkmon132.suntradingllc.com
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 53cc3ca755e749bf94f2e4e98374ea66
           Boot ID: 9c4e2673006f409c9aa37e5878e784b0
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.22.2.el7.x86_64
      Architecture: x86-64

* Enabled features (`icinga2 feature list`):
[root@elkmon132 ~]# icinga2 feature list
Disabled features: compatlog debuglog gelf graphite logstash opentsdb perfdata redis statusdata syslog
Enabled features: api checker command ido-pgsql influxdb livestatus mainlog notification

* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: v2.6.3-151-g46900ce)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: elkmon132.suntradingllc.com
information/ConfigItem: Instantiated 5 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 301 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 299 Endpoints.
information/ConfigItem: Instantiated 744 Notifications.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 78 CheckCommands.
information/ConfigItem: Instantiated 2 Downtimes.
information/ConfigItem: Instantiated 60 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1920 Hosts.
information/ConfigItem: Instantiated 25 Comments.
information/ConfigItem: Instantiated 7 Users.
information/ConfigItem: Instantiated 303 Dependencies.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 4 ServiceGroups.
information/ConfigItem: Instantiated 4491 Services.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 LivestatusListener.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
i do run zones but can see how its relevant in this case with the config applied in the master zone, can run if needed.

**Comment by dnsmichi** [comment]
"unreachable" is not a state itself, just an indication and seperate field calculated from dependencies. 

Can you extract the runtime state of this service object via the REST API please?

**Comment by cbnorman** [comment]
is this what your looking for?
```{"results":[{"attrs":{"__name":"test-switch!test-interface","acknowledgement":0.0,"acknowledgement_expiry":0.0,"action_url":"","active":true,"check_attempt":1.0,"check_command":"ping4","check_interval":300.0,"check_period":"","check_timeout":null,"command_endpoint":"","display_name":"test-interface","downtime_depth":0.0,"enable_active_checks":true,"enable_event_handler":true,"enable_flapping":false,"enable_notifications":true,"enable_passive_checks":true,"enable_perfdata":true,"event_command":"","flapping":false,"flapping_last_change":1498057274.9216530323,"flapping_negative":3123.0,"flapping_positive":0.0,"flapping_threshold":30.0,"force_next_check":false,"force_next_notification":false,"groups":[],"ha_mode":0.0,"host_name":"test-switch","icon_image":"","icon_image_alt":"","last_check":1498057274.9215500355,"last_check_result":{"active":true,"check_source":"elkmon132.suntradingllc.com","command":["/usr/lib64/nagios/plugins/check_ping","-4","-H","121.134.243.242","-c","200,15%","-w","100,5%"],"execution_end":1498057274.9213910103,"execution_start":1498057264.9181671143,"exit_status":2.0,"output":"PING CRITICAL - Packet loss = 100%","performance_data":["rta=200.000000ms;100.000000;200.000000;0.000000","pl=100%;5;15;0"],"schedule_end":1498057274.9215500355,"schedule_start":1498057264.9178650379,"state":2.0,"type":"CheckResult","vars_after":{"attempt":1.0,"reachable":false,"state":2.0,"state_type":1.0},"vars_before":{"attempt":1.0,"reachable":false,"state":2.0,"state_type":1.0}},"last_hard_state":2.0,"last_hard_state_change":1497942087.2876040936,"last_reachable":false,"last_state":2.0,"last_state_change":1497942087.2876040936,"last_state_critical":1498057274.9216370583,"last_state_ok":0.0,"last_state_type":1.0,"last_state_unknown":1497942038.0261249542,"last_state_unreachable":1498057274.9216380119,"last_state_warning":0.0,"max_check_attempts":3.0,"name":"test-interface","next_check":1498057569.2016539574,"notes":"","notes_url":"","original_attributes":null,"package":"_etc","paused":false,"retry_interval":60.0,"state":2.0,"state_type":1.0,"templates":["test-interface"],"type":"Service","vars":{"address":"121.134.243.242","parent_host_name":"test-host-02"},"version":0.0,"volatile":false,"zone":"master"},"joins":{},"meta":{},"name":"test-switch!test-interface","type":"Service"}]}```

**Comment by dnsmichi** [comment]
`reachable` is `false` as I expected. That will be shown in the service detail view then. Services generally do not change their state to unreachable, or similar. So this isn't an issue, just needed clarification.

Cheers,
Michael
