### ISSUE TITLE
getting problem while starting icinga2 for first time 

### ISSUE THREAD

**Issue by manjitp46** [Icinga/icinga2#5382]
attach crash report:

```Caught unhandled exception.
Current time: 2017-06-28 16:26:42 +0530

Application information:
  Application version: r2.6.3-1
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.2 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.8.0-54-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.4.0
  Build host: lcy01-31

Error: Function call 'std::ifstream::open' for file '/etc/icinga2/icinga2.conf' failed with error code 2, 'No such file or directory'

	(0) Compiling configuration file '/etc/icinga2/icinga2.conf'

***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***

[Failed to launch GDB: No such file or directory]
```

> `icinga2.conf file is not creating automatically`

**Comment by gunnarbeutner** [comment]
Please attach the output of 'apt-cache policy icinga2' to the ticket.

**Comment by manjitp46** [comment]
Output of 'apt-cache policy icinga2'
------------------------------------------------------------
icinga2:
  Installed: 2.6.3-1~ppa1~xenial1
  Candidate: 2.6.3-1~ppa1~xenial1
  Version table:
 *** 2.6.3-1~ppa1~xenial1 500
        500 http://packages.icinga.org/ubuntu icinga-xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.1-2ubuntu1 500
        500 http://in.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

**Comment by gunnarbeutner** [comment]
That's highly unusual. An example 'icinga2.conf' should be installed when you install the icinga2 package. When did this problem start to occur? As in, did your setup work before, did you upgrade things? Please provide a more detailed description of your issue.

Also, `dpkg -l | grep icinga2`, please.

**Comment by manjitp46** [comment]
previously it was working after updating my system it stopped working so i try to reinstall this
since that time it stopped working 

'dpkg -l | grep icinga2 output'
ii  icinga2                                                     2.6.3-1~ppa1~xenial1                          amd64        host and network monitoring system
ii  icinga2-bin                                                 2.6.3-1~ppa1~xenial1                          amd64        host and network monitoring system - daemon
ii  icinga2-common                                              2.6.3-1~ppa1~xenial1                          all          host and network monitoring system - common files
ii  icinga2-doc                                                 2.6.3-1~ppa1~xenial1                          all          host and network monitoring system - documentation
ii  libicinga2                                                  2.6.3-1~ppa1~xenial1                          amd64        host and network monitoring system - internal libraries

**Comment by gunnarbeutner** [comment]
Did you by any chance remove your /etc/icinga2 directory?

**Comment by manjitp46** [comment]
yes i deleted all the directory any tried to reinstall.
But the constant.conf and other conf files are not  coming

**Comment by gunnarbeutner** [comment]
That's the default behavior of dpkg, i.e. this is not a bug. Please use one of the support channels to further diagnose this problem.

**Comment by lazyfrosch** [comment]
@manjitp46 you have to purge the package to ensure it can be fully reinstalled:

    apt purge icinga2-common

Also see:
* https://askubuntu.com/questions/66533/how-can-i-restore-configuration-files
* https://serverfault.com/questions/484342/i-manually-deleted-my-etc-php5-config-files-and-now-they-dont-reinstall
