### ISSUE TITLE
check_nrpe throws massive logentries in /var/log/messages

### ISSUE THREAD

**Issue by cadtobias** [Icinga/icinga2#5391]
Hi there,

this might be an Icinga2 bug

## Expected Behavior

Little to no logentries.

## Current Behavior

we've got an issue while running Icinga 2 Master/Satellite toplogy.
We've got a massive amount of logentries like on each Icinga2 server:
Nov 14 13:23:00 satellite check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 2 Packet
Nov 14 13:23:00 satellite check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Nov 14 13:23:00 satellite check_nrpe: Remote xxx.xxx.xxx.xxx does not support Version 3 Packets
Nov 14 13:23:00 satellite check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Nov 14 13:23:00 satellite check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 2 Packet
Nov 14 13:23:00 satellite check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Nov 14 13:23:00 satellite check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet

## Possible Solution

Exclude the part given in the link in check_nrpe and recompile icinga2 package. (Dirty way)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

At first we blamed nagiors-nrpe-server package being the cause because of this article:
[https://support.nagios.com/forum/viewtopic.php?f=7&t=41115](url)

We already excluded the part given in the source and recompiled the nagios package. We also backported Buster nagios-nrpe-server 3.1.1. without fixing it. (Even though the nagios community promissed having it fixed)

So we found the exact same part in check_nrpe for Icinga2 and we assume this being the cause for the massive amount og logentries.

I kindly ask you to have a look into this.

## Your Environment

Our running OS:
Debian 8.8
4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.25-1~bpo8+1 (2017-05-19) x86_64 GNU/Linux

Our used Icinga version:
`ii  icinga2                              2.6.3-1~debmon8+1                  amd64        host and network monitoring system
ii  icinga2-bin                          2.6.3-1~debmon8+1                  amd64        host and network monitoring system - daemon
ii  icinga2-common                       2.6.3-1~debmon8+1                  all          host and network monitoring system - common files
ii  icinga2-doc                          2.6.3-1~debmon8+1                  all          host and network monitoring system - documentation
ii  libicinga2                           2.6.3-1~debmon8+1                  amd64        host and network monitoring system - internal libraries`

**Comment by gunnarbeutner** [comment]
check_nrpe is not distributed as part of Icinga 2. What makes you think that this is a problem with _Icinga_ as opposed to check_nrpe?

**Comment by cadtobias** [comment]
Hi @gunnarbeutner,

thanks for the fast response.

The reason ist that we found the following file on our systems:
/usr/local/icinga/libexec/check_nrpe

with the explained content.

**Comment by gunnarbeutner** [comment]
Despite the 'icinga' bit in the path this file is not part of the Icinga project. You might want to google for 'check_nrpe' or check out https://exchange.nagios.org/directory/Addons/Monitoring-Agents/NRPE--2D-Nagios-Remote-Plugin-Executor/details .
