### ISSUE TITLE
Malformed characters - invalid continuation byte

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icinga2#5395]
Hi,

we use SNMP to check our Ricoh printers; "Unabhängiger Tonerzulieferer" seems to be a value that comes from the printer itself. At least snmpwalk gives answers like this:

```
...
iso.3.6.1.2.1.43.17.6.1.5.1.1 = STRING: "Power"
iso.3.6.1.2.1.43.17.6.1.5.1.2 = STRING: "Fehler am Drucker"
iso.3.6.1.2.1.43.17.6.1.5.1.3 = STRING: "Datenempfang"
...
```

Running the check on console:
```
...
OK - Unabh�ngiger Tonerzulieferer {30136}( 4 5 10 1 30136 1)
```

I can do a curl API query for my "Alerts" service object like this, and it gives me the result I expected:
```
# curl -k -s -u root:<password> 'https://localhost:5665/v1/objects/services/miro!Alerts'
{"results":[{"attrs":{"__name":"miro!Alerts","acknowledgement":0.0,"acknowledgement_expiry":0.0,"action_url":"","active":true,"check_attempt":1.0,"check_command":"dfki_printer","check_interval":300.0,"check_period":"","check_timeout":null,"command_endpoint":"","display_name":"Alerts","downtime_depth":0.0,"enable_active_checks":true,"enable_event_handler":true,"enable_flapping":false,"enable_notifications":true,"enable_passive_checks":true,"enable_perfdata":true,"event_command":"","flapping":false,"flapping_last_change":1499159071.3040699959,"flapping_negative":1485.0,"flapping_positive":0.0,"flapping_threshold":30.0,"force_next_check":false,"force_next_notification":false,"groups":["toner"],"ha_mode":0.0,"host_name":"miro","icon_image":"","icon_image_alt":"","last_check":1499159071.3040030003,"last_check_result":{"active":true,"check_source":"<icingamaster>","command":["/usr/lib/nagios/plugins/check_printer3","a.b.c.d","xxx","1","alerts"],"execution_end":1499159071.3038980961,"execution_start":1499159071.2458488941,"exit_status":0.0,"output":"OK - Unabh�ngiger Tonerzulieferer {30136}( 4 5 10 1 30136 1)","performance_data":[],"schedule_end":1499159071.3040030003,"schedule_start":1499159071.2455990314,"state":0.0,"type":"CheckResult","vars_after":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0},"vars_before":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0}},"last_hard_state":0.0,"last_hard_state_change":1499142615.2016129494,"last_reachable":true,"last_state":0.0,"last_state_change":1499142615.2016129494,"last_state_critical":1496313811.382529974,"last_state_ok":1499159071.3040568829,"last_state_type":1.0,"last_state_unknown":1491035429.6507360935,"last_state_unreachable":1482921137.0362250805,"last_state_warning":1499142555.3537349701,"max_check_attempts":3.0,"name":"Alerts","next_check":1499159368.364071846,"notes":"","notes_url":"","original_attributes":null,"package":"director","paused":false,"retry_interval":60.0,"state":0.0,"state_type":1.0,"templates":["Alerts","DFKI Printer Check","Printer Queries","DFKI Service","host var overrides (Director)"],"type":"Service","vars":{"grafana_graph_disable":true,"printer_command":"alerts"},"version":0.0,"volatile":false,"zone":"<icingamaster>"},"joins":{},"meta":{},"name":"miro!Alerts","type":"Service"}]}
```

However - the same query with python -m json.tool fails:
```
# curl -k -s -u root:<password> 'https://localhost:5665/v1/objects/services/miro!Alerts' | python -m json.tool
'utf8' codec can't decode byte 0xe4 in position 10: invalid continuation byte
```

This seems to be the reason why clicking "Inspect" leads to a stacktrace:
```
Parsing JSON result failed: Malformed UTF-8 characters, possibly incorrectly encoded
```
![screen shot 2017-06-30 at 13 31 57](https://user-images.githubusercontent.com/11242139/27823715-6068c3ac-60aa-11e7-85c5-8e36e9322d2a.jpg)

Seems to be a bigger issue than I thought? So closing [#987](https://github.com/Icinga/icingaweb2-module-director/issues/987) now and opening this one instead. Feel free to contact me in case you need further information.

Cheers,
  Marianne

## Steps to Reproduce (for bugs)

In this case:
1. Take a printer with weird software.
2. Tell him so speak German.
3. Do SNMP queries with umlaut results.

But as Thomas said: _"Related data should either not be accepted or normalized when "entering" the core. Shipping invalid JSON with any kind of "graceful" JSON parsing is not an option at all, no matter where it appears."_

## Context

Users think the whole monitoring is broken always when they see stacktraces.

## Your Environment

* Director version (System - About): 1.3.1 // 4d240976a3e1ffe1eb9555fa23067da4aed25a58
* Icinga Web 2 version and modules (System - About): 2.4.0 // 7a2d8eda8dd8c37198d0e754218cdedd12e3fde4
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Ubuntu 16.04.2 LTS
* Webserver, PHP versions: apache2-2.4.18, php7-7.0.18

**Comment by Stefar77** [comment]
@sysadmama Is #5014 a working solution?

**Comment by sysadmama** [comment]
@Stefar77 I will check this :-)

**Comment by sysadmama** [comment]
Just for completeness: #5014 closed without merge; issue I described persists.

* Director version (System - About): 1.4.0 // 942ab420a24061e67ffe379300f8ff720b9df0c0
* Icinga Web 2 version and modules (System - About): 2.4.2 // d11775a6b8f6483b18f4e9875cdc258f55a8da9e
* Icinga 2 version (icinga2 --version): r2.7.1-1
* Operating System and version: Ubuntu 16.04.2 LTS
* Webserver, PHP versions: apache2-2.4.18, php7-7.0.22

**Comment by dnsmichi** [comment]
Please re-test this with 2.9.0.

**Comment by sysadmama** [comment]
Made my upgrades to `2.9.0-1.xenial` this morning :) Icinga Web 2 is still 2.5.3
But `Inspect` still fails for this check – is it a core or a director issue? Using director `1e7f0f962bf83be4590a211e96ab146ba3d0a65a` which is really old.

That's my feedback, hope it helps? I'm on vacation now :)

Cheers,
  Marianne

![screen shot 2018-07-18 at 11 53 31](https://user-images.githubusercontent.com/11242139/42876735-e69cb688-8a87-11e8-89db-7043052a28b5.jpg)

**Comment by Al2Klimov** [comment]
No idea about Director, but IMO the Python-JSON thing would be fixed with #6809.

**Comment by Thomas-Gelf** [comment]
Director accepts correctly encoded JSON. The proposed fix should address this, just: I'm not sure whether this is the right place. It's hard to maintain a software that's in doubt about the encoding of it's internal objects. A similar problem might then arise on other interfaces. It's also risky from a security perspective.

IMO a stricter policy would make things easier. Icinga should be able to be 100% sure that it's internal objects are 100% valid JSON. Invalid data must be rejected (config files) or sanitized (check results) when entering the core.

**Comment by Al2Klimov** [comment]
No, a stricter policy would make a lot of people ranting in the monitoring forum and here. Nobody who uses e.g. Windows w/ latin1/cp866 wants to re-write all their config despite UTF-8 is cool – for the same reason that nobody who uses plain config objects wants to re-write their config to apply rules despite apply rules are cool.

IMAO how we store the config has literally nothing to do with how users query the config – the Icinga 2 config language has nothing to do with HTTP/JSON.

**Comment by Thomas-Gelf** [comment]
Sure, you can also sanitize configuration formats if you want to be friendly. But you shouldn't carry invalid data into the core. It doesn't help the user if you accept UTF32, cp* or whatever without understanding the encoding. Otherwise as a result there could be wrongly (and differently) encoded data in Graphite, IDO, PNP - all those many tools we're in some way talking to.

Icinga's internal data representation should be 100% UTF8, data MUST be sanitized before entering the core.

For related questions please ask @lippserd directly for guidance, we shouldn't spam this issue.

**Comment by dnsmichi** [comment]
I'm evaluating possible methods for sanitizing with a new JSON library integration, since YAJL also has some other flaws. It is an ongoing effort with fixing #6684.

**Comment by Thomas-Gelf** [comment]
@dnsmichi: but that would also only work for JSON outputs. We would still ship invalid data to the IDO, to Perfdata files or via the InfluxDB Line Format. I'd strongly suggest to tackle this from the other side: make sure that we have no doubt about how our internal data is encoded. Sanitize all the inputs, then there are zero doubt on the outputs.

**Comment by Al2Klimov** [comment]
@Thomas-Gelf OK, assumed we do it like you suggested... what about already present data in config, IDO, Influx, ... ?

**Comment by dnsmichi** [comment]
@Thomas-Gelf I'm with you and my patches will reflect that for further discussion. I still need to find a time slot as always :)

**Comment by Thomas-Gelf** [comment]
When reading from sources you cannot trust (all the above): sanitize the data. We cannot reject data that has formerly been written by ourselves. Sources where the protocol is strict -> be strict. Invalid JSON via REST API -> reject. Invalid JSON via JSON-RPC -> reject.

But be careful with JSON-RPC. We must assume to have older Agents or Satellites that might ship invalid data. So there should be a grace period involving quite some version steps, during that time we are forced to sanitize our own cluster protocol :-/

Configuration files: sanitize them when reading them. "Internal" configuration files (`/var/lib/icinga2/api`): we must write only valid UTF-8. That's a no-brainer once all our internal data is correctly encoded, so no big issue here. You might face existing files with wrongly-encoded names that might result in unexpected changes. Imagine a Downtime object name with invalid encoding. Sanitation is the way to go, but eventually for such a specific example a little bit more effort should be invested - like automagically fixing the existing file.

I'd really love to see this fixed. So if in doubt and looking for ideas how to tackle specific tricky edge-cases please let me know.
