### ISSUE TITLE
Problem with displaying Cyrillic characters in icingaweb2

### ISSUE THREAD

**Issue by arthur-den** [Icinga/icinga2#5403]
## Expected Behavior
Showing cyrillic symbols

## Current Behavior

```
conf.d/users.conf:
object UserGroup "net-admins" {
display_name = "Сетевые администраторы"
}
```
icingaweb2 showing - net-admins	Ð¡ÐµÑ‚ÐµÐ²Ñ‹Ðµ Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€Ñ‹

It seems the problem in icinga2:
```
base/string.hpp:
class I2_BASE_API String
....
private:
std::string m_Data;
```
So all text data in latin1 encoding

## Your Environment

* Version used (`icinga2 --version`): 2.6.3-1.stretch
* Operating System and version: Debian 9.0 amd64
* Enabled features (`icinga2 feature list`):checker command ido-mysql mainlog notification syslog
* Icinga Web 2 version and modules (System - About):2.4.1-2.stretch

**Comment by arthur-den** [comment]
In general, I used single-byte cp1251 encoding instead of utf8.

**Comment by 6bIBAET** [comment]
can you tell us in more detail?
