### ISSUE TITLE
One check command for multiple services

### ISSUE THREAD

**Issue by arthur-den** [Icinga/icinga2#5404]
I would like to have the option in the active mode to perform one check_command to check multiple services. Sometimes it is convenient.

For example, one command of check modbus devices reads dozens of parameters. Now I have to use passive mode.

**Comment by Crunsher** [comment]
You can use the same check command in multiple services, I'm not sure I understand your problem

**Comment by arthur-den** [comment]
Maybe I did not exactly put it.
Executing of one command must return results for the set of services.
Output is this command likely to be similar to the output of the command for passive mode:
<host_0>;<service_0>;<result_0>
<host_1>;<service_1>;<result_1>
...
<host_N>;<service_N>;<result_N>

**Comment by Crunsher** [comment]
So you have multiple Service objects (on the same or different hosts) and you want a new Service that aggregates these services? There is the business process module which can do that, or you could write a custom check that runs against the API.

But currently we do not plan to implement into Icinga 2 as a native feature.

**Comment by arthur-den** [comment]
No, I have the expensive and long check_command, which returns many values.
I want to Icinga run this command onсe and used results for many services.
Now I use passive check.

**Comment by Crunsher** [comment]
Ohhh, now I understand. But that's not an intended design... You can use a check script that does that for you - actually only running the check every hour or so but saving the result to return it

**Comment by tutanhamon** [comment]
@Crunsher, the periodical check script configured manually on a remote host actually ruins the idea of monitoring automation.

The suggested concept sounds reasonable exactly for the specified reasons: when the check script call is expensive but returns a lot of info regarding multiple services.
