### ISSUE TITLE
IDO statehistory table does not show hosts going to "UNREACHABLE" state.

### ISSUE THREAD

**Issue by mdetrano** [Icinga/icinga2#5405]
If a host goes into an "unreachable" state, due to a problem host check and a down parent host as defined by a Dependency, the "state" in the statehistory table of IDO will not be set to "2" as is suggested in the IDO Database model documentation ( https://docs.icinga.com/latest/en/db_model.html#dbm_statehistory ).  The state in the hoststatus table is set at 2...but the history does not log the event as a change to "unreachable".

## Expected Behavior

The change to state "UNREACHABLE" for a host should get logged to the statehistory table with the state field set to "2".

## Current Behavior

The state is logged as "1" == DOWN, and if the host was already down, nothing is logged to statehistory.

## Steps to Reproduce (for bugs)

1. Create two hosts in monitoring, and a Dependency object with one host being depended on by another.

2. Take both hosts down (or simulate this).

3. check records in statehistory table in Icinga IDO for the child host...the record corresponding to the "DOWN" event will have state: 1 

4. check record in hoststatus table .... current_state there will be correctly shown as "2"

## Context

This will affect availability reporting that uses the statehistory table where it is desired to differentiate between a host being down and a host being unreachable.

## Your Environment

* Version used (`icinga2 --version`):
2.6.3
* Operating System and version:
Centos 7.3

**Comment by dnsmichi** [comment]
UNREACHABLE is a somewhat compat state, and does not really exist in Icinga 2.

**Comment by mdetrano** [comment]
Ok, 

I now see that there was a desire to separate out the concept of "reachability", from "state".  However, I don't *think* there is yet any other tracking in IDO history tables for changes in the reachability.  If I'm right on that...is this being considered (possibly by adding an "is_reachable" column in the statehistory table to track changes in this same column from the host and servicestatus tables).

As I mentioned...this is useful for certain types of availability reports where someone wants to differentiate between a host having a problem, or some other connectivity device between the monitor and the host having the problem.

**Comment by dnsmichi** [comment]
That was only a comment for anyone fixing the issue. There's a state calculation required similar to the hoststatus table.

```
CompatUtility::GetHostCurrentState()
```

**Comment by dnsmichi** [comment]
I'll push a fix soon, please test it then.

**Comment by dnsmichi** [comment]
Same problem for 

- acknowledgements
- notifications
- eventhandlers (not used in Web 2, disabled by default)
