### ISSUE TITLE
Balance check execution between multiple command endpoint clients

### ISSUE THREAD

**Issue by Cicero-Zhao** [Icinga/icinga2#5406]
## how to support multiple remote clients when execute check

I setup an icinga2 in 3 level distributed monitor mode following by https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/distributed-monitoring.

Then I found all check commands are executed on satellite nodes, not on client nodes.

And I found this "Once the clients have successfully connected, you are ready for the next step: execute a remote check on the client using the command endpoint."

Does it mean, we must assign a service be executed on a specified client node? I tested, it is true, if I set a remote client to one client, it works.

But it is not reasonable, I have more than one client nodes, how can I distribute these checks to specified client node? how can I ensure load balance among so many client nodes?

There must be some good method to let icinga2 schedule check on client node by itself.

## Expected Behavior

icinga2 can schedule a check on remote clients by itself

## Current Behavior

a check can only be assign to one remote client endpoint manually

## Possible Solution

support command_endpoints = ["client1", "client2", "client3"] and it schedule by itself.

or support command_zone = "client_zone", this zone contains more than one clients.

## Steps to Reproduce (for bugs)
Not bug, no reproduce steps

## Your Environment

* icinga2 2.6.3
* CentOS7
* Enabled features (`icinga2 feature list`):
    api checker command debuglog ido-mysql mainlog syslog
* Icinga Web 2 version and modules (System - About):
    2.4
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

Thanks.

**Comment by Cicero-Zhao** [comment]
In fact, I see this warning message:
`warning/Zone: The Zone object 'DC1' has more than two endpoints. Due to a known issue this type of configuration is strongly discouraged and may cause Icinga to use excessive amounts of CPU time.
warning/Zone: The Zone object 'DC2' has more than two endpoints. Due to a known issue this type of configuration is strongly discouraged and may cause Icinga to use excessive amounts of CPU time.`

Hm.. maybe my icinga2 version is too old which does not support 3 endpoints.

However, I hope icinga2 can add more satellites or checkers to reduce master's node load, otherwise, there must be a upper limit of monitored objects.

What is your scale? I have 7000+ hosts and 40000+ services monitored by one icinga2 cluster, including:
  1. 2 icinga2 masters
  2. 13 zones, two zones have 3 satellites (which has warning above)

I dare not to get performance data or snmptrap on icinga2 for performance worrying.

Now, the icinga master's load is a little high, considering to split to multiple icinga2 clusters.

Hope I can get suggestions ;)

Thanks.

**Comment by Sec42** [comment]
Has there been any progress on this? Being able to specify multiple endpoints to "load-balance" and archive higher reliability on checks would be very useful.

**Comment by Al2Klimov** [comment]
Hello @Cicero-Zhao and thank you for reporting!

Couldn't you just assemble two clients to a zone and put the stuff to be load-balanced into that zone?

Best,
AK

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
