### ISSUE TITLE
Allow changing of installation path of Windows Agent

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#5411]
To be policy-compliant a customer of mine needs to change the installation path of the Icinga Agent to another Drive on Windows. Please make the path configurable so the Powershell Module can use it.

This issue was created per request in issue Icinga/icinga2-powershell-module#43

**Comment by LordHepipud** [comment]
Made some research on the MSI file and the required argument is 'INSTALL_ROOT'

**Comment by LordHepipud** [comment]
This issue can be closed.
