### ISSUE TITLE
"Plugin Check Commands" section inside ITL docs needs adjustments

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5428]
Right now it is basically `<h1>` and therefore missing in the right TOC.

![screen shot 2017-07-24 at 09 32 48](https://user-images.githubusercontent.com/382049/28512708-46a746b0-7053-11e7-9309-8f025ccee96e.png)

We should either move it one level down, or make it a dedicated chapter on its own. I prefer to reorganize the structure a bit, which includes `<itl>`, `<plugins>`, etc. similar to the icinga2.conf includes.

**Comment by Crunsher** [comment]
I made a ticket (over there)[https://github.com/Icinga/icinga-docs-tools/issues/1], not knowing there was one for this problem here already.

@bobapple Which repo do you prefer for problems with the doc rendering on icinga.com?

**Comment by dnsmichi** [comment]
I prefer to fix it here, since it is our content inside doc/. mkdocs can't properly deal with it afaik.

**Comment by dnsmichi** [comment]
I'll refactor the introduction into the ITL which is confusing too.

**Comment by dnsmichi** [comment]
docs.icinga.com is uptodate as well.

![screen shot 2017-08-08 at 14 49 56](https://user-images.githubusercontent.com/382049/29072671-e8496150-7c48-11e7-961a-c45c6b99ee81.png)
