### ISSUE TITLE
check_fortigate.pl - new CheckCommand definition

### ISSUE THREAD

**Issue by riskersen** [Icinga/icinga2#5429]
[0001-Add-Fortinet-CheckCommand-definition.txt](https://github.com/Icinga/icinga2/files/1172126/0001-Add-Fortinet-CheckCommand-definition.txt)
Hi all,

as I'm now working on a test, possible prod, environment, I was required to write a CheckCommand definition for my Fortinet plugin (https://github.com/riskersen/Monitoring/blob/master/fortigate/check_fortigate.pl) 

Please check file attached.

Best regards
Oliver

**Comment by riskersen** [comment]
[0001-Add-Fortinet-CheckCommand-definition.txt](https://github.com/Icinga/icinga2/files/1172124/0001-Add-Fortinet-CheckCommand-definition.txt)

**Comment by Crunsher** [comment]
It would be better if you supplied the CheckCommand with your own check plugin as we don't want to bloat the ITL up too much. So we are keeping it to packaged plugins/suits only.

Are your plugins on the [Icinga Exchange](https://exchange.icinga.com/)?

**Comment by Crunsher** [comment]
Missunderstanding~

My info was about something else and I mixed things up. But we do need documentation for the new CheckCommand in the docs and a Pull request would be appreciated.

**Comment by riskersen** [comment]
Hi Crunsher,

documentation is also inside of the patch.

I followed the contribution guide: https://github.com/Icinga/wiki-archive/blob/master/community/01_contribute_icinga_2_itl_plugin_check_command_definitions.md 

BR
Oliver

**Comment by dnsmichi** [comment]
A certain misunderstanding - I'll reopen the issue for further review, thanks 👍

**Comment by dnsmichi** [comment]
@riskersen an up-to-date guide for contributions is found in the CONTRIBUTING.md file here: https://github.com/Icinga/icinga2/blob/master/CONTRIBUTING.md - the wiki archive is outdated.

**Comment by riskersen** [comment]
Thanks @dnsmichi
