### ISSUE TITLE
icinga2 command help text clarification

### ISSUE THREAD

**Issue by noobcontrol** [Icinga/icinga2#5431]
# icinga2 list

Icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)

Usage:
  icinga2 <command> [<arguments>]

Supported commands:
  * api setup (setup for api)
  * console (Icinga console)
  * daemon (starts Icinga 2)
  * feature disable (disables specified feature)
  * feature enable (enables specified feature)
  * feature list (lists all enabled features)

The 'icinga feature list' help text isn't right. It not just lists all enabled features but also shows disabled features.

**Comment by mcktr** [comment]
Hi,

I had sent a patch that changes the text to `feature list (lists all available features)`.

```
icinga2 - The Icinga 2 network monitoring daemon (version: v2.6.3-408-g3e54e34; debug)

Usage:
  icinga2 <command> [<arguments>]

Supported commands: 
  * api setup (setup for api)
  * console (Icinga console)
  * daemon (starts Icinga 2)
  * feature disable (disables specified feature)
  * feature enable (enables specified feature)
  * feature list (lists all available features)
  * node add (add node) (DEPRECATED)
```

Thanks for reporting :)
