### ISSUE TITLE
psql: FATAL:  Peer authentication failed for user "icinga"

### ISSUE THREAD

**Issue by naisanza** [Icinga/icinga2#5436]
Installer script: [install-icinga.sh.txt](https://github.com/Icinga/icinga2/files/1178558/install-icinga.sh.txt)
Contents of the installer script was created from following, https://www.icinga.com/docs/icinga2/latest/doc/02-getting-started/

## Expected Behavior
Install without errors

## Current Behavior
Encounters errors

## Steps to Reproduce (for bugs)

1. Run Installer script: [install-icinga.sh.txt](https://github.com/Icinga/icinga2/files/1178558/install-icinga.sh.txt)
2. Fails at https://github.com/Icinga/icinga2/blame/support/2.6/doc/2-getting-started.md#L634

## Your Environment

* Proxmox 4.4-1/eb2d6f1e

**Comment by lazyfrosch** [comment]
This is not a help forum, this is an issue tracker for Icinga 2

Please use the community channels for help:
https://www.icinga.com/support/ (Section: Community Support)
