### ISSUE TITLE
icinga2 install: icinga user is not created

### ISSUE THREAD

**Issue by naisanza** [Icinga/icinga2#5438]
Installer script: [install-icinga.sh.txt](https://github.com/Icinga/icinga2/files/1178558/install-icinga.sh.txt)
Contents of the installer script was created from following, https://www.icinga.com/docs/icinga2/latest/doc/02-getting-started/

## Expected Behavior
Install without errors

## Current Behavior
Encounters errors

## Steps to Reproduce (for bugs)

1. Run Installer script: [install-icinga.sh.txt](https://github.com/Icinga/icinga2/files/1178558/install-icinga.sh.txt)
2. 
```
root@icinga:~# id icinga
id: 'icinga': no such user
```

## Your Environment

* Proxmox 4.4-1/eb2d6f1e

**Comment by lazyfrosch** [comment]
For historic and compatibility reasons Icinga is running under `nagios` on Debian and Ubuntu.

You could have find that out stating `ps -ef | grep icinga` in a shell...

**Comment by dnsmichi** [comment]
Side note: Please don't use installer scripts which silently ignore error messages. This could lead into unwanted installation states you'll never can recover from. Better use a lifecycle tool for software and configuration management (Foreman, Puppet, Ansible, etc.).
