### ISSUE TITLE
Display endpoints in the second line of the ClusterCheckTask output

### ISSUE THREAD

**Issue by stokkie90** [Icinga/icinga2#5444]
## Expected Behavior
I would like to see the output of the Cluster check displayed in 2 rows to keep IcingaWeb2 cleaner, if allot of endpoints (clients) are configured. 

## Current Behavior
All output of the check is displayed in 1 row, including all the endpoint names.

## Possible Solution
Output Lines:
1. Icinga2 Cluster is running: Connected Endpoints: 500
2. Connected Endpoints:
4.    - endpoint1.local
5.    - endopint2.local
6. ....

## Context
File where problem is in: https://github.com/Icinga/icinga2/blob/0a77f7033e466a74254c2bacdfb81738f074920c/lib/methods/clusterchecktask.cpp

## Environment

* Version used (`icinga2 --version`):  v2.6.3
* Operating System and version: Centos 7
* Enabled features (`icinga2 feature list`):  api checker command debuglog ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About): v2.4.1
* Satellite Zones: 6
* Clients/Endpoints: 1500

**Comment by dnsmichi** [comment]
Since you've already looked into the code, you might just create a patch based on the details found inside https://github.com/Icinga/icinga2/blob/master/lib/remote/apilistener.cpp#L1077 - can you please send in a PR? :)

**Comment by stokkie90** [comment]
@dnsmichi, I would like to, but have no idea how to write it in C++.

**Comment by mcktr** [comment]
@dnsmichi @stokkie90 

I will see what I can do on this issue and might create a patch. :)

If I understand you correct, the output should be a sort of the following? 
```
Icinga 2 Cluster is running: Connected Endpoints: 10 
Connected Endpoints: 
- host1
- host2
- host3
- ...
```

**Comment by stokkie90** [comment]
@mcktr, Yes.

**Comment by mcktr** [comment]
@stokkie90 Here is a preview, I should be able to send a PR within the next days :)

![screenshot at 2017-08-01 20 40 03](https://user-images.githubusercontent.com/18580278/28841293-0a734b1e-76fa-11e7-93e3-f1d574629c5a.png)

**Comment by stokkie90** [comment]
@mcktr, That look very nice. Exactly wat I meant. Is the output also like this when the check is "OK". Because that was my initial issue. ;)

**Comment by mcktr** [comment]
@stokkie90 Of course, the OK state output has the same formatting. :)

![screenshot at 2017-08-02 20 33 19](https://user-images.githubusercontent.com/18580278/28889353-0da9ac54-77c4-11e7-8a30-a693635078f3.png)

PR is there :)

**Comment by dnsmichi** [comment]
Seen that in a production environment lately, and put on my TODO list.

![screen shot 2018-01-18 at 15 16 36](https://user-images.githubusercontent.com/382049/35102268-b713998a-fc62-11e7-867e-b826803a2697.png)
