### ISSUE TITLE
new Icinga2 install: Monitor checks are localhost values only

### ISSUE THREAD

**Issue by familyhead** [Icinga/icinga2#5445]
I installed Icinga2 and Icingaweb2 with postgresql backend using one of many guides available.

The interface loads and the 5 nodes configured (1 is the icinga instance itself) load with the basic checks (pings, ssh, disk etc.)

The issue though is that all checks, aside from ping, output results from the local icinga2 master node and not data from the nodes themselves.

A typical host node looks like this:

object Host "node1" {

  import "generic-host"
  address = "x.x.x.x"
  vars.os = "Linux"

  /* Define disks and attributes for service apply rules in `services.conf`. */
  vars.disks["disk"] = {
    /* No parameters. */
  }
  vars.disks["disk /"] = {
    disk_partitions = "/"
  }

  /* Define notification mail attributes for notification apply rules in `notifications.conf`. */
  vars.notification["mail"] = {

}
}

It's such a weird thing to have occur and I really need some help getting the checks to execute as top-down.

Thanks!

**Comment by dgoetz** [comment]
Have a look at the `command_endpoint` attribute of the service object. https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#service

You have to set this to the corresponding endpoint object, so best practice is to use fqdn for both host and endpoint object and simple add `command_endpoint = host.name` to the service.

If you are using different names, you can do something similar with an additional attribute like it is done in https://www.icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#master-with-clients with `client_endpoint`.

**Comment by lazyfrosch** [comment]
Exactly, you have to tell Icinga where to check, if it is not a network based check.
