### ISSUE TITLE
openSuSE 11.0 repo packages

### ISSUE THREAD

**Issue by Fiiti** [Icinga/icinga2#5446]
Two issues:
# **1.)**
Adding the repo will have an certificate error:
```
SERV01:~ # zypper ar https://packages.icinga.com/openSUSE/ICINGA-release.repo
Download (curl) error for 'https://packages.icinga.com//openSUSE/ICINGA-release.repo':
Error code: Unrecognized error
Error message: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Abort, retry, ignore? [A/r/i]: i
Problem encountered while trying to read the file at the specified URI:
Download (curl) error for 'https://packages.icinga.com//openSUSE/ICINGA-release.repo':
Error code: Unrecognized error
Error message: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

SERV01:~ #

```
With http:// it will work:
```
SERV01:~ # zypper ar http://packages.icinga.com/openSUSE/ICINGA-release.repo
Adding repository 'ICINGA (stable release for openSUSE1)' [done]
Repository 'ICINGA (stable release for openSUSE1)' successfully added
Enabled: Yes
Autorefresh: Yes
URI: http://packages.icinga.com/openSUSE/$releasever/release/

SERV01:~ #
```

# **2.)**
zypper ref cannot determine repository:
```
SERV01:~ # zypper ref
Error building the cache database:
Cannot determine type for repository icinga-stable-release.
Skipping repository 'ICINGA (stable release for openSUSE1)' because of the above error.
Repository 'Updates for 11.0' is up to date.
Repository 'openSUSE-11.0-Non-Oss' is up to date.
Repository 'openSUSE-11.0-Oss' is up to date.
Some of the repositories have not been refreshed because of an error.
SERV01:~ #
```
# **SuSE-release**
```
SERV01:~ # cat /etc/SuSE-release
openSUSE 11.0 (i586)
VERSION = 11.0
```

Is there the repo missing?
Regards in advanced.

**Comment by dnsmichi** [comment]
AFAIK openSUSE 11.0 is EOL for a while. Leap and 42.x is the newest support version.

**Comment by lazyfrosch** [comment]
## Regarding `1)`

SuSE 11.0 is not able to talk to current SSL webservers (encryption standards / SSLv3)

## Regarding `2)`

AFAIK we never had `11.0` packages, you can see the actual repos here: https://packages.icinga.com/SUSE/

Please don't just fire commands into your shell and expect it to "just work"

**Comment by Fiiti** [comment]
Regarding 2)
I am sorry - but there is an folder 11 and also i586 files.  I am wonder for what. Must be my mistake.

Please don't fire words to another people and expect that you are not understood as impolite.

**Comment by lazyfrosch** [comment]
> Regarding 2)
> I am sorry - but there is an folder 11 and also i586 files. I am wonder for what. Must be my mistake.

This is not really clear to see over the website, these folders are symlinks to the "latest" major.

Unfortunately this is not the best idea, since SLES service packs are not compatible to each other. I'd prefer to remove the links, but they might be used by a user...

> Please don't fire words to another people and expect that you are not understood as impolite.

You are right :disappointed:, I'm had bad experience with SuSE users in the past and projected them on you. I shouldn't have done that. Please accept my apology.

Regarding support for SLES 11, we hope to be able to keep it alive, but as of now we only can and want to support supported releases. Since we require a more recent OpenSSL, that's not even an option for SLES 11 SP3 or lower.
