### ISSUE TITLE
services.conf - Usage of Arrays in Custom Variables

### ISSUE THREAD

**Issue by adrianleineweber** [Icinga/icinga2#5452]
In a services.conf i am trying to generate a service for multiple instances. i know it is possible using host.vars as an array, but it seems that an array is not supported in a custom variable in services.

**NON Working Example:**
services.conf:
```
template Service "sessiondbmucA" {
vars.database = [ "db01", "db02t" ]
}
...
apply Service "Statistics-2 sessiondbmucA " for (database1 in vars.database) {
...
```
will lead to 
```
$ icinga2 daemon -C | grep Statistics-2
warning/ApplyRule: Apply rule 'Statistics-2 sessiondbmucA ' (in /etc/icinga2/zones.d/global-templates/instances/sessiondbmucA.conf: 201:1-201:76) for type 'Service' does not match anywhere!
```

**Working Example**
host.conf
```
Object Host "dbsessionA.mucA.tpi" {
...
  vars.database = [ "db10_alt", "db13_alt" ]
...
}
```
and services.conf
```
...
apply Service "Statistics-2 sessiondbmucA " for (database1 in host.vars.database) {
...

```
works as expected and generates two service checks.

So i think that arrays in custom variables are only supported as Host-Variables and not as Service Variables.

Please implement or tell me what i am doing wrong.
Thank you
Adrian

## Your Environment

* Version used (`icinga2 --version`): 2.4.10
* Operating System and version: CentOS 6.8
* Enabled features (`icinga2 feature list`): Disabled features: compatlog debuglog gelf icingastatus livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-pgsql mainlog notification

**Comment by dgoetz** [comment]
Problem is the template is imported later than the apply rule is validated. So custom variables of type array are valid but can not be used in your example use case.

I remember a similar issue where @dnsmichi gave some more in depth technical explanation but I can not find it.

**Comment by dnsmichi** [comment]
`vars.database` does not exist when the apply for rule is evaluated. Note that this is only for checking if there are applicable objects where this apply rule could match. The service template itself is the wrong location for specifying which services should be rendered or not.

I suggest to either generate services based on the host, or adjust your assign where expressions without any apply for loops. Nevertheless, this isn't really a bug, so please kindly discuss on the community channels next time.
