### ISSUE TITLE
Downtime does not end

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#5456]
## Current Behavior
(Static) downtimes which are past their scheduled_end would not set an actual_end_time or set is_active to 0 in the IDO. Which then would lead to no Downtime end event in icignaweb2

## Possible Solution
This only happens sometimes in HA setups, probably some cluster problem

## Steps to Reproduce (for bugs)

1. Create downtime
2. Wait
3. Hope the bug occurs
4. Profit

## Your Environment
This happened with 2.6.3 and newer snapshosts

**Comment by dnsmichi** [comment]
Might be related somehow: #5033

**Comment by Crunsher** [comment]
This is the same as #5458 and all the discussion is there. So I'm closing this as duplicate
