### ISSUE TITLE
Update to latest release

### ISSUE THREAD

**Issue by R00T88** [Icinga/icinga2#5459]
## Expected Behavior
Upgrade 2.6.3 to 2.7.0 on ubuntu 16_04

## Current Behavior
i'm trying update my Icinga2 v3.6.3 installation to 2.7.0 via apt-get update but it's says package is already at latest version 2.6.3
What i'm doing wrong?

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
@lazyfrosch can you please have a look? :)

@R00T88 for future reference, please open package related issues over at https://github.com/icinga/icinga-packaging

**Comment by lazyfrosch** [comment]
Looks like the package was not published correctly...

Only 2.6.3 is available:
http://packages.icinga.com/ubuntu/dists/icinga-xenial/main/binary-amd64/Packages

But the upload was successful:
https://build.icinga.com/job/icinga2-release/job/deb-ubuntu-xenial-3-publish/2/console

I'll check the logs...

**Comment by lazyfrosch** [comment]
I did a small mistake while migrating the repositories from mirror to local.

    * ubuntu/icinga-xenial [amd64, i386, source] publishes {main: [icinga-debian-xenial-release]}

The repo published still represented the last mirror state, new packages went to an unpublished repository.

**Comment by lazyfrosch** [comment]
I fixed the repository names, and re-uploaded the package.

It should be available to you right away:
http://packages.icinga.com/ubuntu/dists/icinga-xenial/main/binary-amd64/Packages

Thanks for reporting.

If you find anything else, this repo is the way to report packaging related issues: https://github.com/icinga/icinga-packaging

**Comment by lazyfrosch** [comment]
Same happened for the Ubuntu releases before xenial too :cry: 

But since we only update trusty now, I only restarted upload there.

Repo names have been fixed for all...
