### ISSUE TITLE
Reset icinga2 data

### ISSUE THREAD

**Issue by R00T88** [Icinga/icinga2#5464]
## Expected Behavior
Reset Icinga2 data in History tab (EventGrid, notification, ecc)
Is it possible to clear all data stored in db and start with a clean db?

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by gunnarbeutner** [comment]
Consider dropping the IDO database, then just re-create it and re-import the schema. This isn't really a bug though (or a feature request, for that matter).
