### ISSUE TITLE
409 Acknowledgement 'expiry' timestamp must be in the future for object after upgrade to 2.7.0

### ISSUE THREAD

**Issue by jschanz** [Icinga/icinga2#5481]
After upgrading to r2.7.0-1 I'm not able to acknowledge any objects without an expiry time. But it's not reproducible in any 2.7.0 installation we run, so I'm a bit confused.

## Expected Behavior

![bildschirmfoto vom 2017-08-09 07-38-15](https://user-images.githubusercontent.com/5750462/29106696-b10897ae-7cd6-11e7-9d14-7a5d68be7b81.png)

After acknowledging with "Problem bestätigen" an acknowledgment should be set. This works before 2.7.0-1.

## Current Behavior

An error will be thrown, if no expiry date is set. If an expiry date is set, everything will work as known.

![bildschirmfoto vom 2017-08-09 07-38-26](https://user-images.githubusercontent.com/5750462/29106729-d03a9276-7cd6-11e7-958b-ca17f6f23ff6.png)

## Possible Solution

Maybee the source of the problem is the change from https://github.com/Icinga/icinga2/issues/5250. A downgrade to the previous running 2.6.3-1 solves this problem.
Time on Client and Server is in sync, so this should not be the problem.

```
        if (params->Contains("expiry")) {
                timestamp = HttpUtility::GetLastParameter(params, "expiry");

                if (timestamp <= Utility::GetTime())
                        return ApiActions::CreateResult(409, "Acknowledgement 'expiry' timestamp must be in the future for object " + checkable->GetName());
        } else
                timestamp = 0;
```
![bildschirmfoto vom 2017-08-09 08-18-41](https://user-images.githubusercontent.com/5750462/29109189-6bfa2c3e-7ce2-11e7-96cd-edf55a62bd2b.png)

## Steps to Reproduce (for bugs)
1. Acknowledge a service and set no expiry date

## Your Environment

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 8 (jessie)
  Kernel: Linux
  Kernel version: 3.16.0-4-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.9.2
  Build host: f6aca561f47b
```
* Operating System and version:
Debian 8.8

* Enabled features (`icinga2 feature list`):
```
Disabled features: compatlog debuglog gelf influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-mysql mainlog notificatio
```
* Icinga Web 2 version and modules (System - About):
![bildschirmfoto vom 2017-08-09 08-29-06](https://user-images.githubusercontent.com/5750462/29107926-d422644e-7cdc-11e7-87ad-f5c69847a738.png)

* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: r2.7.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: host.domain
information/ConfigItem: Instantiated 5 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 692 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 691 Endpoints.
information/ConfigItem: Instantiated 7 NotificationCommands.
information/ConfigItem: Instantiated 825 Notifications.
information/ConfigItem: Instantiated 302 CheckCommands.
information/ConfigItem: Instantiated 113 Downtimes.
information/ConfigItem: Instantiated 782 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 34 HostGroups.
information/ConfigItem: Instantiated 263 Comments.
information/ConfigItem: Instantiated 4 UserGroups.
information/ConfigItem: Instantiated 6 TimePeriods.
information/ConfigItem: Instantiated 15 Users.
information/ConfigItem: Instantiated 24439 Services.
information/ConfigItem: Instantiated 35 ServiceGroups.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

**Comment by dnsmichi** [comment]
Sending `0` or `` as highlighted in icinga/icingaweb2#2911 is invalid. Only set the `expiry` field if you really want an expire time. There is no additional boolean field which would tell the API to explicitly enable this setting. 

Please test the patch in the referenced issue. Closing this one.

**Comment by jschanz** [comment]
Patch from https://github.com/Icinga/icingaweb2/pull/2914/commits/2c312adf94ef5a6e99967e156de0c513754bebdd works for me
