### ISSUE TITLE
check_snmp return CRITICAL

### ISSUE THREAD

**Issue by R00T88** [Icinga/icinga2#5489]
## Expected Behavior
return status OK on command snmp-uptime

## Current Behavior
snmp-uptime always return CRITICAL instead OK and not return date/time uptime but only timeticks

## Your Environment

* Version used (`icinga2 --version`): 2.7.0
* Operating System and version: Ubuntu 16:04
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`): Yes
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by gunnarbeutner** [comment]
Please provide additional information how this can be reproduced. Also, if you can reproduce this when running this check manually (i.e. without Icinga) this is likely not an issue in Icinga itself.

**Comment by R00T88** [comment]
if i run command directly
./check_snmp -H 10.0.0.1 -C public -o 1.3.6.1.2.1.1.3.0
i get as result OK and timeticks expressed in date time format

![image](https://user-images.githubusercontent.com/9050487/29157558-b3e4b81e-7da7-11e7-8206-28f255fcc595.png)

This do not happend if i run the same command trought icinga2

Service define
![image](https://user-images.githubusercontent.com/9050487/29157467-5fe06092-7da7-11e7-8409-ddcd4f4b77b4.png)

Result in icinga2
![image](https://user-images.githubusercontent.com/9050487/29157522-8959ee98-7da7-11e7-871c-80a7cd4c3731.png)

**Comment by gunnarbeutner** [comment]
Can you show me the exact command that Icinga ran? You can use the following commands to do that:

```
$ icinga2 console --connect https://user:passsword@icinga-host:5665/
Icinga 2 (version: v2.7.0-27-gfa702d377)
<1> => get_service("hostname", "snmp-uptime").last_check_result
```

**Comment by R00T88** [comment]
![image](https://user-images.githubusercontent.com/9050487/29158682-35a60bc4-7dac-11e7-91c1-1ffd6b853f67.png)

**Comment by gunnarbeutner** [comment]
That would imply that the service hasn't (ever) been checked yet. Did you run this with --connect?

**Comment by R00T88** [comment]
Nope because i get this error

![image](https://user-images.githubusercontent.com/9050487/29158989-5ede3fba-7dad-11e7-8055-4ef56cf1bf55.png)

**Comment by gunnarbeutner** [comment]
Your shell interprets $ characters. Consider putting the URL into quotes.

**Comment by dnsmichi** [comment]
Seems to be coming from here dnsmichi/manubulon-snmp#37

I'd guess the executed command line (also: don't test as root) does not match what Icinga 2 would execute. Please provide the requested details.

**Comment by R00T88** [comment]
i'm trying to retrive information but when type get_sservice command i got this

![image](https://user-images.githubusercontent.com/9050487/29164645-72098c6c-7dc0-11e7-8999-11702c6677a1.png)

**Comment by R00T88** [comment]
i got it! wrong passwod for api user :)

![image](https://user-images.githubusercontent.com/9050487/29164825-1ecbe878-7dc1-11e7-86a9-88e7b14379d0.png)

**Comment by dnsmichi** [comment]
The executed command line contains `-w` and `-c` arguments which will cause `check_snmp` to evaluate the thresholds and return a different state (as seen in your Icinga Web 2 screenshot).

Please also add the configuration for this service, i.e. by repeating the above command without `.last_check_result` at the end.

```
get_service("hostname", "snmp-uptime")
```

**Comment by R00T88** [comment]
i think it add -w e -c itself because i did not define them
i run the command as you request but ctoo much information and cannot save all screens
do you have an idea on how can print all information?

**Comment by dnsmichi** [comment]
Increase your terminal buffer and copy paste the output here. Screenshots aren't that helpful as we cannot copy paste your things, but need to re-type everything.

**Comment by dnsmichi** [comment]
Any updates here?

**Comment by dnsmichi** [comment]
No feedback received.
