### ISSUE TITLE
Acknowledgements from Icingaweb2 2.4.1 do not work with Icinga2 2.7.0

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icinga2#5493]
I am not really sure if this is an issue with Icinga2 or Icingaweb2, but since this used to work with the exact same Icingaweb2 version on Icinga2 v2.6.x, I suppose something changed on the Icinga2 side of things...

We have recently updated Icinga2 to release 2.7.0, and now cannot acknowledge hosts & services from Icingaweb2 any longer.

The error message we get is `Can't send external Icinga command: 409 Acknowledgement 'expiry' timestamp must be in the future for object XYZ`.

Database server is PostgreSQL 9.6.3.
OS is CentOS 7.3 x64.
Icinga2 version is 2.7.0
Icingaweb2 version is 2.4.1.

I have no idea if this matters, but the timezone for our database is **not** UTC:

```
postgres=# show timezone;
   TimeZone
---------------
 Europe/Berlin
(1 row)
```

## Expected Behavior

Acknowledgements work just like they did with Icinga2 < 2.7.0

## Current Behavior

Icingaweb2 gets an error message from Icinga2:

```
API: Can't send external Icinga command: 409 Acknowledgement 'expiry' timestamp must be in the future for object myhostname!myservicename.
```

## Steps to Reproduce (for bugs)

1. Select one or more hosts or services in problem states
2. Try to acknowledge them using Icingaweb2

## Your Environment

* Version used (`icinga2 --version`): r2.7.0-1
* Operating System and version: CentOS Linux release 7.3.1611 (Core)
* Enabled features (`icinga2 feature list`): api checker command graphite ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.4.1
* Config validation (`icinga2 daemon -C`): n/a
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
n/a

**Comment by dnsmichi** [comment]
Bug icinga/icingaweb2#2911 & Fix icinga/icingaweb2#2914
