### ISSUE TITLE
PNP template for the built-in icinga check

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icinga2#5505]
Hello,

Following the article https://www.icinga.com/2017/06/08/icinga-performance-monitoring-and-analysis/, I've adapted my custom PNP template for the built-in icinga check.
I can share it if you are interested, but don't know what would be the best place for such template. 

Could be a PR for the icinga2 project itself (as written for a built-in check), or a "project" on icingaexchange. What would be the best?

BR,
Yannick

[pnp_template_for_icinga_check_result.pdf](https://github.com/Icinga/icinga2/files/1223394/pnp_template_for_icinga_check_result.pdf)

[icinga.zip](https://github.com/Icinga/icinga2/files/1223399/icinga.zip)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by Tontonitch** [comment]
I can PR directly on the PNP project for the template addition, but I don't see any official release since a while...

**Comment by dgoetz** [comment]
For PNP Jörg is still excepting PRs but is not able to invest any time (and will not be able in the future if I understood him correctly) for development. I think this is why no release was published. As you are already required to use the unreleased version for multi format of perfdata, it will not hurt if the template goes there.

If we want to include this in Icinga 2 project, I vote for tools/pnp as location, so we could create a simple package providing the template as documentation or if we decide to include addons in the icinga repo as addition to pnp. 

@dnsmichi @gunnarbeutner: What's your opinion?

**Comment by dnsmichi** [comment]
I would avoid adding things to Icinga 2 itself. Either we find a location on exchange.icinga.com where this would fit, or directly inside PNP. I would prefer the latter if @lingej agrees on it :)

**Comment by Tontonitch** [comment]
PR created: https://github.com/lingej/pnp4nagios/pull/137

However, the icinga2 documentation says:

> Use your distribution’s package manager to install the pnp4nagios package.

Ok, but it will install the last stable release 0.6.25, which currently doesn't contain 34 commits fixing some bugs.
This version is not fully compatible with icinga2 (for example, as you know, the perfdata in check_multi format generated by icinga2 is supported only since commit 55a8c8e339b9c47e59fd7e3fbfcfadadd6d2a36a).

I would say that the icinga2 documentation should recommend the future PNP user to install PNP using the last devel to benefit from all the commits done since the last 0.6.25 release.

**Comment by dnsmichi** [comment]
Packages are always recommended. We cannot influence the release and package strategy of other projects. 

If we change the docs to install source, users will hit us with questions on how to do it (it is not so easy without a package). That's something I'd like to avoid. For advanced users, one might write a blog post showing exactly that. This can be spread in the community and everyone is happy.

**Comment by Tontonitch** [comment]
Sounds good to me.
If i have time I may propose such a post.
By the way, the PR has already been merged.
I m closing this issue.

**Comment by dnsmichi** [comment]
Cool 👍
