### ISSUE TITLE
check_wmi_plus command

### ISSUE THREAD

**Issue by R00T88** [Icinga/icinga2#5507]
Hi all,
i would share my check_wmi_plus command updated to latest version (1.62)
Maybe could be useful for someone 

Command gir repository:
https://github.com/R00T88/Icinga2-check-wmi-plus-command

Thanks

**Comment by dnsmichi** [comment]
First of all, thanks for sharing 👍 

Please incorporate that into the ITL in plugins-contrib.d, I would say "windows.conf" as a new file would suffice.

Then create a new docs section in doc/10-icinga-template-library.md underneath the Plugins Contrib section (sub sections are ordered alphabetically). This should include the same table as known from other plugin check commands.

The argument description should be copied from the --help output and parameter description. This should be added into a) the `description` field for arguments, next to the `value`. b) the table description field then too.

https://github.com/Icinga/icinga2/blob/master/doc/05-service-monitoring.md also references check_wmi_plus, a replaced link to the ITL chapter should then be added.

More hints on contributing CheckCommand definitions can be found here: https://github.com/Icinga/icinga2/blob/master/CONTRIBUTING.md#contributing-patches-itl-checkcommands

Some notes - the arguments should be changed into readable attributes.

```
    "-a" = "$wmi_arg1$"
    "-o" = "$wmi_arg2$"
    "-3" = "$wmi_arg3$"
    "-4" = "$wmi_arg4$"
    "-5" = "$wmi_arg5$"
```

This looks like a specific order is required here. `-a` and `-o` seem to be different, what's the purpose of these options?

Can you please share a command line output of one of your services to get a better idea? :)

**Comment by dnsmichi** [comment]
I've tried to setup WMI and the plugin, including some extra CLI tool called wmic. Apart from the complicated installation routine, the Windows parts are not good described as well. If anyone wants to write a community howto over at https://community.icinga.com please do so. But this command isn't something I'd like to officially support without getting it to work just once.
