### ISSUE TITLE
Downtime notification double

### ISSUE THREAD

**Issue by R00T88** [Icinga/icinga2#5508]
On downtimeend notification i always receive two same email.
Is it correct?

![image](https://user-images.githubusercontent.com/9050487/29357942-a42979ec-8279-11e7-8ac0-1eda9a41ef5b.png)

## Your Environment
* Version used (`icinga2 --version`): 2.7.0
* Operating System and version: Ubuntu 16:04
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`): yes
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
How does the underlaying notification and user objects look like? It seems that you've defined multiple notification objects which would trigger a DowntimeEnd type filter notification.

**Comment by R00T88** [comment]
![image](https://user-images.githubusercontent.com/9050487/29358495-888ece7e-827b-11e7-86fa-b2195b8d9621.png)
