### ISSUE TITLE
Add metrics about communication between endpoints

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#5509]
Hi,

I think it would be useful to have some information about how much data is transferred between Icinga 2 Endpoints, especially between masters and masters/satellites.

Could you add some metrics, so we can see a bit more what is going on between the different endpoins.
Current ideas for the API:
* rate of messages (increasing counter or per second) per connected endpoint
* rate of bytes (increasing counter or per secon) (please stick to bit or bytes and let users do the calculation for kilo/kibi, etc.) per connected endpoint
* last sent message per connected endpoit

Current ideas for the `icinga` Check:
* rate of messages or bytes (increasing counter or per second) total

rate per second would be easier to process for graphite while graphite and rrd can both handle increasing counters.

**Comment by dnsmichi** [comment]
@N-o-X keep this in mind when other priority issues are resolved please.

**Comment by dnsmichi** [comment]
#5523 adds some byte counting to the logs. The metrics here should only be added in a new major version.
