### ISSUE TITLE
Add build timestamp to "icinga2 --version"

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5512]
This tremendously helps to identify snapshot build versions and throw them at testers :)

**Comment by gunnarbeutner** [comment]
I'm not sure this is a good idea, for two reasons:

* It'll force a rebuild every time "make" is run which would be annoying for dev builds
* Build timestamps don't actually contain all the information we need to identify an exact build, that's where the Git hash would be _much_ more useful

**Comment by lazyfrosch** [comment]
Also relevant: https://reproducible-builds.org/docs/timestamps/

GIT reference would be the best identifier for the built version...

**Comment by gunnarbeutner** [comment]
Assuming that dpkg and rpm preserve timestamps for the Icinga binary we could also just report the mtime for the Icinga binary. This might however be unreliable depending on how the user installed Icinga.

Ideally we should really just _always_ include the Git hash in one of the build-time constants (Build*).

**Comment by lazyfrosch** [comment]
@gunnarbeutner I agree, probably we should also save the I a file on tarball export. To know the "git version" of a tarball.

See https://github.com/Icinga/icingaweb2/blob/master/.gitattributes#L11

And https://github.com/Icinga/icingaweb2/blob/master/application/VERSION

**Comment by dnsmichi** [comment]
Did not think of the dev environment rebuilds every time. So this issue isn't really helping here. I'd rather close it.

**Comment by gunnarbeutner** [comment]
Aye, agreed.
