### ISSUE TITLE
Icinga2 Library Reference documentation section is ambiguous

### ISSUE THREAD

**Issue by noobcontrol** [Icinga/icinga2#5514]
For the regex function it says

> function regex(pattern, text)
> 
> Returns true if the regular expression matches the text, false otherwise. The mode argument is optional and can be either MatchAll (in which case all elements for an array have to match) or MatchAny (in which case at least one element has to match). The default mode is MatchAll.

https://www.icinga.com/docs/icinga2/latest/doc/18-library-reference/

Unfortunately there is no mode argument documented. Also the difference between the regex and match function isn't really described.

**Comment by dnsmichi** [comment]
This has been fixed with #5496.
