### ISSUE TITLE
Recovery Notifications not sent after reload (satellite system)

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#5521]
Icinga Version 2.6.3
Alright, this one has not been reproduced but there are the steps for it:

1. Service goes into Problem
2. Problem Notification is sent
3. Icinga 2 gets reloaded
4. Service recovers
5. No Recovery Notification is sent

Icinga2 does not even check whether it needs to send a Recovery notification.
It works without the reload just fine.

Things to investigate:
* State/Api Possibly the Notification object gets changed during the reload
* Cluster?
* modified attributes?

**Comment by dnsmichi** [comment]
@lbetz please provide more details on this.

Enable debug logging for this period of tests.

- trigger a problem notification
- look into /v1/objects/notifications - notified_problem_users
- verify notified_problem_users inside the state file before and after the reload
- reload Icinga 2
- verify /v1/objects/notifications - notified_problem_users is still intact
- push an OK result to trigger a recovery
- attach the debug log

**Comment by lbetz** [comment]
Icinga2 v2.6.3
Master - Satellite - Checker (2x)

Notification will send from satellite only.
Notification object:
Object 'host!service!sms-icingaadmin' of type 'Notification':
  % declared in '/etc/icinga2/local.d/notifications.conf', lines 62:1-62:47
  * __name = "host!service!sms-icingaadmin"
  * command = "sms-service-notification"
    % = modified in '/var/lib/icinga2/api/zones/global-templates/_etc/templates.conf', lines 59:3-59:39
    % = modified in '/etc/icinga2/local.d/notifications.conf', lines 65:3-65:38
  * command_endpoint = ""
  * host_name = "host"
    % = modified in '/etc/icinga2/local.d/notifications.conf', lines 62:1-62:47
  * interval = 300
    % = modified in '/etc/icinga2/local.d/notifications.conf', lines 77:5-77:50
  * name = "sms-icingaadmin"
  * package = "_etc"
    % = modified in '/etc/icinga2/local.d/notifications.conf', lines 62:1-62:47
  * period = "24x7"
    % = modified in '/var/lib/icinga2/api/zones/global-templates/_etc/templates.conf', lines 66:3-66:17
  * service_name = "service"
    % = modified in '/etc/icinga2/local.d/notifications.conf', lines 62:1-62:47
  * states = [ "OK", "Warning", "Critical", "Unknown" ]
    % = modified in '/var/lib/icinga2/api/zones/global-templates/_etc/templates.conf', lines 61:3-61:45
  * templates = [ "sms-icingaadmin", "mail-service-notification" ]
    % = modified in '/etc/icinga2/local.d/notifications.conf', lines 62:1-62:47
    % = modified in '/var/lib/icinga2/api/zones/global-templates/_etc/templates.conf', lines 58:1-58:49
  * times = null
  * type = "Notification"
  * types = [ "Problem", "Acknowledgement", "Recovery", "Custom", "FlappingStart", "FlappingEnd", "DowntimeStart", "DowntimeEnd", "DowntimeRemoved" ]
    % = modified in '/var/lib/icinga2/api/zones/global-templates/_etc/templates.conf', lines 62:3-64:57
  * user_groups = [ "usergroup" ]
    % = modified in '/etc/icinga2/local.d/notifications.conf', lines 67:3-67:49
  * users = null
    % = modified in '/etc/icinga2/local.d/notifications.conf', lines 68:3-68:42
  * vars = null
  * zone = "zone2"
    % = modified in '/etc/icinga2/local.d/notifications.conf', lines 62:1-62:47

**Comment by lbetz** [comment]
Sorry @dnsmichi I've to send this private information to a private account...

**Comment by lbetz** [comment]
notified_problem_users is before and after reload still the same.

**Comment by dnsmichi** [comment]
Details: #523611

**Comment by torstenbunde** [comment]
Is there any new information on this?

At the moment we are running the systems on version 2.8.0-1 (Master, Satellite and both Checker) and the problem still exists.

Or is any more/new information needed?

**Comment by dnsmichi** [comment]
This is fixed with 2.11.
