### ISSUE TITLE
Packaging issues when built against openSUSE in OBS

### ISSUE THREAD

**Issue by thardeck** [Icinga/icinga2#5530]
Current icinga2.spec has some issues when built against openSUSE in the the [openSUSE Build Service](https://build.opensuse.org) .

The packages can not be built because some directories are not part of a package, there is a typo in the systemd clause and the dependency for the logger is missing.

I will submit a pull request which addresses those issues.

**Comment by dgoetz** [comment]
Please be aware that the upstream version is located in https://github.com/Icinga/icinga-packaging/tree/rpm/snapshot and the one in this repository is only copied here from time to time.

**Comment by thardeck** [comment]
@dgoetz Thanks for the hint.

**Comment by thardeck** [comment]
Should I recreate the issue under https://github.com/Icinga/icinga-packaging/?

This is the pr: https://github.com/Icinga/icinga-packaging/pull/36

**Comment by dnsmichi** [comment]
PR is sufficient, thanks. We'll treat them the same as issues with the bonus of a review. I'll close here.
