### ISSUE TITLE
InfluxdbWriter ignoring invalid Perfdata from NSCLIENT++

### ISSUE THREAD

**Issue by Tux12Fun** [Icinga/icinga2#5541]
## Expected Behavior

InfluxdbWriter should convert to valid values

## Current Behavior

```
Ignoring invalid perfdata value: 'paged bytes'=2.882G;5.46199;6.14499;0;6.828
```

## Steps to Reproduce (for bugs)

1. Any nsclient++ check with sizes of M G TB

## Your Environment

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.2 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 3.13.0-55-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.2
  Build host: e1e9a326f1b8
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by gunnarbeutner** [comment]
As per the specification for monitoring plugins (https://www.monitoring-plugins.org/doc/guidelines.html) 'G' is not a valid unit of measurement. The correct UOM would be "GB". Can you please report this to the NSClient++ project? :)
