### ISSUE TITLE
ITL: wrong argument config for CheckCommand ipmi-sensor

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icinga2#5542]
Some arguments of the "ipmi-sensor" CheckCommand wrongly uses "set_if" instead of "value":
<pre>
        "-ST" = {
            set_if = "$ipmi_sel_type$"
            description = "Limit SEL entries to specific types. (seperated by comma)"
        }
[...]
        "-xT" = {
            set_if = "$ipmi_exclude_sensor$"
            description = "Exclude sensors based on IPMI sensor type. (seperated by comma)"
        }
        "-xST" = {
            set_if = "$ipmi_exclude_sel$"
            description = "Exclude SEL entries of specific sensor types. (seperated by comma)"
        }
</pre>

Therefor the following error is logged:
<pre>
warning/PluginUtility: Error evaluating set_if value 'Session_Audit,Physical_Security' used in argument '-xT': Can't convert 'Session_Audit,Physical_Security' to a floating point number.
</pre>

The documentation (https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#checkcommand-arguments) correctly states that:
> Argument is added if the macro resolves to a defined numeric or boolean value. String values are not supported. [...]

## Steps to Reproduce (for bugs)

1. Configure a service that uses the ipmi-sensor CheckCommand and one of the mentioned arguments

## Your Environment

* Version used (`icinga2 --version`): 2.7.0
* Operating System and version: Debian stretch
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
Thanks. Please keep in mind for the next time - if you already have a patch and PR, you don't need an extra issue. Just keep the PR is primary issue for discussions and reviews.
