### ISSUE TITLE
New configuration is not applied on satellites

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icinga2#5544]
I have a distributed setup with one master and some satellites. Since upgrading to 2.7.0 I sometimes get the following error log when deploying a new configuration on the master via the Icinga Director:
<pre>
information/ApiListener: Cannot apply configuration file update for path '/var/lib/icinga2/api/zones/director-global'. Current timestamp '2017-09-01 12:32:03 +0000' (1504269123.361771) is more recent than received timestamp '2017-09-01 12:32:03 +0000' (1504269123.361771).
</pre>

This message also appears for all other zones. The strange thing is that the mentioned timestamps are identical.

## Expected Behavior

The new configuration is applied.

## Current Behavior

The new configuration is not applied.

## Steps to Reproduce (for bugs)

1. Create a distributed setup
2. Apply a new configuration via the Icinga 2 API, e.g. via Icinga Director

## Your Environment

* Version used (`icinga2 --version`): 2.7.0
* Operating System and version: Debian jessie + stretch
* Enabled features (`icinga2 feature list`): master: api checker command ido-mysql mainlog; satellite: api checker ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by tobiasvdk** [comment]
The code in question is https://github.com/Icinga/icinga2/blob/master/lib/remote/apilistener-filesync.cpp#L101

<pre>
    /* skip update if our configuration files are more recent */
    if (oldTimestamp >= newTimestamp) {
</pre>

**Comment by mcktr** [comment]
This is a known misbehavior, see #5484

**Comment by tobiasvdk** [comment]
Thanks, didn't found it.

**Comment by ziamler** [comment]
can anyone explain me how to setup satellites, im new in icinga
