### ISSUE TITLE
Re-notify on perf data change

### ISSUE THREAD

**Issue by matthenning** [Icinga/icinga2#5552]
In some cases it can be useful to receive notifications of already critical services if their performance data changes.

For example if a cumulative error count increases to an even worse value I want to be notified about this.

Like a volatile service but only if the performance value increases.

**Comment by dnsmichi** [comment]
I don't think that this is possible, as the performance data keys might change from check result to check result. This relies on the plugin returning the same every time, and that's nothing you can expect by default.

Furthermore, this requires the performance data being valid and parsed all the time. We've seen lots of performance data strings which do not follow the specs (i.e. they cannot be parsed), and as such you don't have key-value pairs to rely on.

If you want to give it a try yourself, look into the respective code parts in checkable-check.cpp and where the last check result is stored.

**Comment by dnsmichi** [comment]
As said before, I don't think this can/should happen inside Icinga 2. There's metric backends which may reliably queried for such.
