### ISSUE TITLE
Rest API Query should return 403 (not 404) if user has insufficient query permissions

### ISSUE THREAD

**Issue by ifischer** [Icinga/icinga2#5557]
When I query the Icinga2 Rest API and try to get objects my user does not have permissions for, the API returns ```404 not found```. It should return 403 instead to show that my API user does not have sufficient permissions to query the given object type.

## Expected Behavior
Querying the REST API for objects a user does not have query permissions returns a 403.

## Current Behavior
Querying the REST API for objects a user does not have query permissions for returns a 404.

## Steps to Reproduce (for bugs)
1. Restrict API user permissions of a user in ```/etc/icinga2/conf.d/api-users.conf``` and restart icinga, example:
```
object ApiUser "root" {
  password = "root"
  // client_cn = ""

  permissions = [ "objects/query/Host" ]
}
```
2. Perform a curl against API against an object type the user does not have permissions for:
```
$ curl -k -s -u root:root -H 'Accept: application/json' 'https://localhost:5665/v1/objects/services'
{"error":404.0,"status":"No objects found."}
```

## Your Environment

* Version used (`icinga2 --version`): 2.6.3-1, 2.7.0-1
* Operating System and version: Ubuntu 16.04
* Enabled features (`icinga2 feature list`): api checker mainlog notification

**Comment by dgoetz** [comment]
This was already discussed in https://github.com/Icinga/icinga2/issues/4945 and conclusion was for security reason it should not differentiate between not found and no permissions as it would allow guessing of objects.

**Comment by dnsmichi** [comment]
Dirk was faster than me, thanks. This is for security reasons, although harder to debug. I don't see a possible alternative here though. These requests are logged on the master, grep for `Missing permission`.
