### ISSUE TITLE
mixed up operator precedence in the documenation

### ISSUE THREAD

**Issue by ghost** [Icinga/icinga2#5573]
The operator precedence

https://www.icinga.com/docs/icinga2/latest/doc/17-language-reference/#expression-operators

in the operator precedence table is mixed up. The table should be in descending precedence but the 'Logical AND' with precedence 13 is before the 'Assignment' with precedence 12. The same is with the 'Logical OR'.

Most probably either the descending precedence or the precedence column is not right.

**Comment by gunnarbeutner** [comment]
Hey, thanks for noticing this problem. Can you please check which of the columns is incorrect and maybe provide a patch for this? :)

**Comment by noobcontrol** [comment]
I will do it if I have the time. I thought the guys who programmed it would be able to adjust it on the fly. ;)

**Comment by gunnarbeutner** [comment]
Well, we're all subject to the same time constraints like most other people. We do value external contributions though. :)

**Comment by noobcontrol** [comment]
Sure we are all very busy. ;)
I can check it out but it will take more time than someone who is already familiar with the code.

**Comment by dnsmichi** [comment]
It is just documentation, you can easily edit this on Github too. 

More instructions are collected here: https://github.com/Icinga/icinga2/blob/master/CONTRIBUTING.md#contributing-patches-documentation

**Comment by mcktr** [comment]
Does it make sense to split the table into multiple tables e.g assignment operators, comparison operators and mathematical operators? I didn't found a proper solution to see which operator has the higher/lower precedence e.g. precedence between operator `=` and operator `&&`.
