### ISSUE TITLE
ITL: ipmi-sensor missing argument

### ISSUE THREAD

**Issue by marcelfischer** [Icinga/icinga2#5579]
The option --nothresholds is missing in /usr/share/icinga2/include/plugins-contrib.d/ipmi.conf

## Expected Behavior
I would expect something like that:

                "--nothresholds" = {
                        set_if = "$ipmi_no_thresholds$"
                        description = "turn off performance data thresholds from output-sensor-thresholds"
                }

## Current Behavior
The option is missing

## Possible Solution
Change the ipmi.conf
[patch_ipmi_nothresholds.txt](https://github.com/Icinga/icinga2/files/1301966/patch_ipmi_nothresholds.txt)

## Your Environment

* Version used (`icinga2 --version`): r2.7.0-1
* Operating System and version: RHEL 7.4
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About):     2.4.1

**Comment by gunnarbeutner** [comment]
Hey, thanks for the ticket. Seeing how you've already figured out what needs to be added in the ITL can you please provide a pull request for this?
