### ISSUE TITLE
Make agent reconnect interval configurable

### ISSUE THREAD

**Issue by jkroepke** [Icinga/icinga2#5588]
If we have changes on global-templates, all agent will be disconnected from the master for a minute and our agents checks will be start flapping shortly.

I found the reconnection interval here: https://github.com/Icinga/icinga2/blob/master/lib/remote/apilistener.cpp#L198

At this time the interval it's hardcoded to 60 seconds. 

It's possible to define the reconnection interval for exmaple in the apilisten object? We want to choose a shorter reconnect interval.

## Expected Behavior
Agent reconnection interval is configuable via config file.

## Current Behavior
Agent reconnection interval is hardcoded

## Context
Like above. If a master reload with chages on global-zone happens, all agent gets disconnected.

## Your Environment

* Version used (`icinga2 --version`): r2.7.0-1
* Operating System and version: RHEL7

**Comment by dnsmichi** [comment]
What do you mean by "our agents checks will be start flapping shortly."?

**Comment by jkroepke** [comment]
If the agent get a config update it gets disconnected from the master. The master will wait 60 seconds for a reconnect attempt. 

This behavior appears on all 1100 endpoints if we changed our global-zone.

**Comment by mcktr** [comment]
The satellites will continue with the checks and store the received check results in the replay log, which is exchanged to the master on re-connected. When you getting a warning/critical status on the cluster status check, modify the check interval.

**Comment by jkroepke** [comment]
There are not satellites. Just Master -> Client and the Clients don't have the checker feature enabled.

**Comment by dnsmichi** [comment]
We won't implement a configuration flag for this, sorry. The current default works well for many instances, leaving such for each instance might make the whole setup hard to debug.

Cheers,
Michael

**Comment by Thomas-Gelf** [comment]
@dnsmichi: do we have another proposal to solve this issue? I experience this all the times when working with customer setups involving our Agent. Until now I always told them that the current behavior is just a temporary workaround that has been put in place at the time being (once we encountered severe issues with single failing connections being able to disconnect thousands of others), and that we where about to fix this sooner or later.

This really is a problem, every time someone applies changes affecting global zones (commands, templates and so on). You tweak a parameter, deploy and check the result. Just, you can click "Check now" as long as you want, nothing will happen within the first minute. Then, finally, a result - oh, wrong parameter, you fix it, deploy - and get angry again.

This is annoying for the few of us who understand WHY this is happening. And it is terrible for those who don't, as you get the feeling that the whole thing just "doesn't work reliably". It is unbelievably hard to debug, a more aggressive default would make things a lot easier. Just, it could of course become costly in very large environments. A few thousand reconnects a second shouldn't hurt, but who knows.

This affects every typical setup involving Icinga Agents where:

* the parent should connect to the Agent (default in most environments)
* the Agent has no checker is controlled via command_endpoint (most commonly used, as it's the only viable option for a reliable top-down deployment)

We could implement some logic that tries to trigger a reconnect every time a JSON-RPC request wants to reach a disconnected endpoint. In theory we should defer the command itself unless the "reconnect" promise fulfills or fails, but sure, this could be tricky and expensive. Most setups use `log_duration = 0` for Agents used via `command_endpoint`, so scheduled commands or actions would usually get lost.

We could remember the last connection attempt for every node and make the first 3-5 connection attempts with a delay of just 1-3 seconds, eventually limiting the amount of pending parallel reconnection attempts to 250 or so. Alternatively or in addition, we could add some logic for "faster reconnects during a 3min warm-up period after restarting". Like "start with a 3sec reconnection interval", go to 10secs after running for 15 seconds and to 60 seconds once being up for 3 minutes. Not very elegant, but probably a quick win and very easy to implement by throwing in two new timers.

Seen from a user perspective the use-case is: "When I deploy a new configuration that triggers an Agent reload, I want to get immediate feedback when clicking 'Check Now' afterwards".

Cheers,
Thomas

**Comment by dnsmichi** [comment]
Discuss that with @lippserd please before re-opening issues here.

Regards,
Michael

**Comment by jkroepke** [comment]
This describe our usecase and problem well. Thanks.

**Comment by Thomas-Gelf** [comment]
No problem, I can close it again. @lippserd: please let me know in case you need more details.

**Comment by KptnKMan** [comment]
@dnsmichi I'm trying to test this issue, by compiling from source, to verify the effect of modifying [this line](https://github.com/Icinga/icinga2/blob/master/lib/remote/apilistener.cpp#L242). I've successfully built deb packages using the source instructions.

I'm trying to find out which packages this code change affects?

Is there a way we can discuss how I can effectively test and replicate?
