### ISSUE TITLE
Update agent based monitoring with more examples

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5589]
## Expected Behavior

Better scenarios for additional agent based implementation.

## Current Behavior

https://www.icinga.com/docs/icinga2/latest/doc/07-agent-based-monitoring/

loosely connects other agents, some of them should be dropped, or explained with pros/cons.

## Possible Solution

- Add an example for local REST API check result feeding on the client
- Propose the REST API for "passive" check results instead of any other transport
- Move away from legacy software such as nsca/nrpe

**Comment by htriem** [comment]
Already updated.
