### ISSUE TITLE
Computed values are uncertain in definied services

### ISSUE THREAD

**Issue by KAMI911** [Icinga/icinga2#5596]
## Current Behavior
When I using a critical and warning threshold in services that is based on computed values they become uncertain. The thresholds are flipping between to set of values. I would like to create a load service where I can define thresholds based on number of cores. So in the host definitions I only specify this:
vars.cores = 5
and get computed thresholds for warning and critical limits.

For short period of time I got these limits and got alert: 
```
Label     Value    Warning              Critical
load15  5.23       3.00       4.00
load5     5.38       4.00       6.00
load1     4.79       5.00       10.00
```
Later I got these limits without alert:
```
Label     Value    Warning              Critical
load15  5.22       14.00     28.00
load5     5.34       28.00     42.00
load1     4.93       29.00     43.00
```
And the service monitoring is flapping around these two.
 
The code what I used is here:
```
apply Service "load" {
  import "generic-service"
  groups += [ "nomail" ]
  if ("nrpe" in host.groups) {
    check_command = "nrpe"
      vars.nrpe_command = "check_load_4"
  } else if ("ssh" in host.groups) {
    check_command = "by_ssh"
      vars.by_ssh_command = "/usr/local/nagios/libexec/check_load -w 8,6,4 -c 12,8,6"
      vars.by_ssh_timeout = 60
  } else {
    check_command = "load"
      command_endpoint = host.name
  vars.load_th = 0
  if (host.vars.load_wload1 != "") { vars.load_th = host.vars.load_wload1 } else if (host.vars.cores != "") { vars.load_th = host.vars.cores * 2 + 1 } else { vars.load_th = 5 }
  vars.load_wload1  = vars.load_th
  if (host.vars.load_wload5 != "") { vars.load_th = host.vars.load_wload5 } else if (host.vars.cores != "") { vars.load_th = host.vars.cores * 2 } else { vars.load_th = 4 }
  vars.load_wload5  = vars.load_th
  if (host.vars.load_wload15 != "") { vars.load_th = host.vars.load_wload15 } else if (host.vars.cores != "") { vars.load_th = host.vars.cores } else { vars.load_th = 2 }
  vars.load_wload15 = vars.load_th
  if (host.vars.load_cload1 != "") { vars.load_th = host.vars.load_cload1 } else if (host.vars.cores != "") { vars.load_th = host.vars.cores * 3 + 1 } else { vars.load_th = 7 }
  vars.load_cload1  = vars.load_th
  if (host.vars.load_cload5 != "") { vars.load_th = host.vars.load_cload5 } else if (host.vars.cores != "") { vars.load_th = host.vars.cores * 3 } else { vars.load_th = 6 }
  vars.load_cload5  = vars.load_th
  if (host.vars.load_cload15 != "") { vars.load_th = host.vars.load_cload15 } else if (host.vars.cores != "") { vars.load_th = host.vars.cores * 2 } else { vars.load_th = 4 }
  vars.load_cload15 = vars.load_th
  }

  assign where (host.address || host.address6) && host.vars.os == "Linux"
  ignore where "ignore" in host.groups
}
```
I am using currently this Icinga 2 version:

```
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.26.2.el7.x86_64
  Architecture: x86_64
Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```
## Expected Behavior
Use computed limits like host.vars.cores * 2 when vars.cores is specified. Do not flap between two limits.

**Comment by dnsmichi** [comment]
Those are static configuration values. What really matters is which values the executed plugin receives. Extract the command line from debug log, and analyze why the values don't match your requirements.

I don't see a bug in Icinga 2 here.

**Comment by KAMI911** [comment]
Hi Michael,
Thank you for your quick answer. I really expect that they get a fixed values during one run. The strange thing is at the limit values are changing. I am attaching the part of grepped debug log:

https://pastebin.com/S4nHK0Y1

At the GraphiteWriter part you can check the problem exactly:
One time the limits are:
[2017-09-20 17:05:43 +0200] debug/GraphiteWriter: Add to metric list:'icinga2.jenkins_example_net.services.load.load.perfdata.load15.warn 3 1505919943'.
in another time the limit values is different:
[2017-09-20 17:06:12 +0200] debug/GraphiteWriter: Add to metric list:'icinga2.jenkins_example_net.services.load.load.perfdata.load15.warn 14 1505919972'.

The example code of load service I really except 14 is the correct value, and 3 is bad. Usually I have the limit of 3 for few seconds then changes to 14. For me it is a bug. Or did I miss something? How can the one specify a limit based on some computed values?

**Comment by dnsmichi** [comment]
Icinga 2 doesn't do anything with these values. They come from user configuration attributes, and are just added to the check plugin which returns the performance data. The labels are parsed and then sent to e.g. Graphite. Nothing special in there which would change `3` to `14` and vice versa.

I'd verify if you happen to have any local checks with default thresholds. Maybe your client where you execute the checks (is it command_endpoint?) does have local configuration objects and this causes irritations here.

Something like https://www.icinga.com/docs/icinga2/latest/doc/15-troubleshooting/#check-thresholds-not-applied

**Comment by KAMI911** [comment]
Hi @dnsmichi!
That was the exact problem. I had local default checks. Probably it would be nice to make such local checks optional during the installation. Anyway, thank you for your help!

**Comment by KAMI911** [comment]
I am closing this.
