### ISSUE TITLE
Provide a plugin to check the state of an object via API for federated setups

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#5598]
Some of my customers want to set up Icinga 2 for each of their customers/teams/subcompanies but still want to have one centralised view on at least some of the objects.

Since Using Icinga Web 2 with multiple IDO backends a way to check an object via API might be a better idea.

I'd like to see a plugin which checks all information one can get from a monitoring plugin via API. Status, Status details, performance data.

**Comment by dnsmichi** [comment]
Sounds like a custom dashboard using the REST APi. Modify the existing dashing-icinga2 to support multiple backends? 

Not sure if this really fits into Icinga 2.

**Comment by widhalmt** [comment]
A custom dashboard might provide not enough information. I'm thinking about creating a plugin that just queries the REST-API. You're right, maybe that won't fit into Icinga 2. 

@bobapple thought about getting it into the `icinga` check. This could save a significant amount of resources when running lots of checks.

**Comment by dnsmichi** [comment]
The `icinga` check is imho not the right place for that. It is a generic metric collector, and as such you won't gain any additional things, like custom queries on "count all hosts where the service name pattern matches X and the state is Y but not acknowledged and not in downtime". That clearly is something which you can do in an external script using the REST API. Or you write your own custom function which uses the object accessors and prints some output.

Overall, I still think this should be moved. Start a discussion on the forums and hear what community members think, or how they've solved this specific problem.

**Comment by widhalmt** [comment]
Ok, thank you. You're right. I'll close this issue now and see if I'll create a solution or ask the community. Thanks for your time.
