### ISSUE TITLE
Icinga 2.7.1 IDO Unique Key Constraint Violation with PostgreSQL

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icinga2#5603]
I have updated Icinga2 to 2.7.1 and found that a unique key constraint violation causes the IDO database connection to be constantly closed and reopened, resulting in the master instance not retrieving satellite results. 

```
warning/IdoPgsqlConnection: Exception during database operation: Verify that your database is operational!
[2017-09-22 11:26:35 +0200] information/IdoPgsqlConnection: pgSQL IDO instance id: 1 (schema version: '1.14.2')
...
Context:
        (0) Reconnecting to PostgreSQL IDO database 'ido-pgsql'
```

The root cause seems to be this failed SQL statement:

```
[2017-09-22 10:41:20 +0200] critical/IdoPgsqlConnection: Error "ERROR:  duplicate key value violates unique constraint "uq_scheduleddowntime"
DETAIL:  Key (instance_id, object_id, entry_time, internal_downtime_id)=(1, 8331, 2017-09-22 07:49:50, 465) already exists.
" when executing query "UPDATE icinga_scheduleddowntime SET actual_start_time = TO_TIMESTAMP(1506106800) AT TIME ZONE 'UTC',  actual_start_time_usec = E'0',  author_name = E'icinga',  comment_data = E'Sicherung im eingeschränkten Zustand Mo-Fr 21:00-00:00',  downtime_type = E'2',  duration = E'0',  endpoint_object_id = 271,  entry_time = TO_TIMESTAMP(1506066590) AT TIME ZONE 'UTC',  instance_id = 1,  internal_downtime_id = E'465',  is_fixed = E'1',  is_in_effect = E'0',  name = E'xxx',  object_id = 8331,  scheduled_end_time = TO_TIMESTAMP(1506117600) AT TIME ZONE 'UTC',  scheduled_start_time = TO_TIMESTAMP(1506106800) AT TIME ZONE 'UTC',  session_token = 1506069482,  was_started = E'0' WHERE entry_time = TO_TIMESTAMP(1506066590) AT TIME ZONE 'UTC' AND instance_id = 1 AND name = E'xxx' AND object_id = 8331 AND scheduled_end_time = TO_TIMESTAMP(1506117600) AT TIME ZONE 'UTC' AND scheduled_start_time = TO_TIMESTAMP(1506106800) AT TIME ZONE 'UTC'"
```

The unique key constraint `uq_scheduleddowntime` on the table `icinga_scheduleddowntime` is defined as `btree (instance_id, object_id, entry_time, internal_downtime_id)`.

The UPDATE statement updates all of the constraints' fields (instance_id, object_id, entry_time, internal_downtime_id), but the WHERE clause only selects updatable rows by a subset of those fields (excluding `internal_downtime_id`). The UPDATE statement completes successfully if I fill in the addtional WHERE clause `AND internal_downtime_id=...`.

As a temporary workaround, and to ensure that service operations does not miss alarms, I dropped the unique key constraint:

```
alter table icinga_scheduleddowntime drop constraint uq_scheduleddowntime;
```

Can you please advice on how to proceed from here? Is the unique key constraint strictly neccessary? If so, how can we clean up our installation?

Thank you.

## Expected Behavior

Icinga continues to work as it did before the update.

## Current Behavior

Our central instance did not receive updates from satellites after the update.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`): 2.7.1
* Operating System and version: CentOS 7.4 x64
* Enabled features (`icinga2 feature list`): api checker command graphite ido-pgsql mainlog notification syslog
* Icinga Web 2 version and modules (System - About): 2.4.1
* Config validation (`icinga2 daemon -C`): yes
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
I'm not able to reproduce this unfortunately.

Can you please share more details such as:

- all SQL queries which are sent for this specific downtime before the error happens
- zones.conf and overview of your cluster. 
- is this a master-master setup?
- How can one reproduce the error reliably, i.e. is it one downtime created on the left master, but DB IDO PgSQL runs on the right master?

I'm wondering about the update statements too. Why would the WHERE clause only match if the internal_downtime_id is added ... it is key to see which UPDATE statement is run before the INSERT actually triggers the constraint error.

It might be related to existing data inside `icinga_scheduleddowntime`. Can you do a backup of your database, re-add the unique constraint, truncate the table, restart Icinga 2, and see whether it works with the constraint?

**Comment by dnsmichi** [comment]
Note: Tried to trigger the error with multiple downtimes scheduled in the same second. It does not fail.

```
for i in {1..10}; do curl -k -s -u root:icinga 'https://localhost:5665/v1/actions/schedule-downtime' -H 'Accept: application/json' -d '{  "author": "michi", "comment": "pgsql", "start_time": 1506330387, "end_time": 1506331387, "filter": "host.name == NodeName && service.name == \"disk\"", "type": "Service" }'; done
```

**Comment by terra-nova** [comment]
@dnsmichi Thank you for looking into the problem.

I, too, cannot reproduce the problem now. I have re-created the unique key constraint on the `icinga_scheduleddowntime` table (without restarting Icinga 2) and have no trouble in adding or cancelling downtimes. Restarting Icinga 2 works flawlessly as well. No error messages to be found in the log.

I have a suspiscion, though. We use an external PostgreSQL server with a pgbouncer connection concentrator (db session cache) in front of it, so the observed issue was possibly due to some mixup of db sessions from the stopped and newly-started Icinga 2 processes.

Other than the IDO db, our setup is as simple as it gets -- just a single master and some satellites reporting to it. Logging SQL statements is difficult because the DB server hosts not just Icinga's database, but a whole lot of other (small) databases at roughly 1500 transactions/s. We do not currently log all SQL transactions, just the ones that take longer than 0.1s to complete.

Sorry for wasting your time, I guess :-/

**Comment by lazyfrosch** [comment]
@terra-nova thanks for the feedback!

Just for the sake of saying it: If you have a big environment in Icinga 2 you want to avoid complex database clusters. We are pushing a lot of real-time data into the `*status` tables. So this can slow down your cluster massively.

**Comment by dnsmichi** [comment]
This is indeed an issue, and has been raised for MySQL in #5623 too. I'm reopening this.

**Comment by dnsmichi** [comment]
See my comment with further explanations: https://github.com/Icinga/icinga2/issues/5623#issuecomment-333134196
