### ISSUE TITLE
Disable conf.d inclusion in node setup wizards

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5605]
Once #4799 is merged this can be implemented for 2.8.

- [x] Setup Wizards: Disable conf.d by default and use the code from #5426 (thanks @mcktr )
- [x] Windows Wizard: Ensure conf.d is disabled
- [x] Allow to include api-users.conf (always do that)

**Comment by Crunsher** [comment]
We are not doing this in 2.8.0. See #5426

**Comment by dnsmichi** [comment]
Scheduled for today/tomorrow.
