### ISSUE TITLE
service notification script does not create valid url for services with blank in service name

### ISSUE THREAD

**Issue by stroetgen** [Icinga/icinga2#5607]
The service notification script does not create a valid url if the service name contains blanks.

My simple change in /etc/icinga2/scripts/mail-service-notification.sh to use urlencode:

```
$ICINGAWEB2URL/monitoring/service/show?host=$HOSTNAME&service=`urlencode $SERVICENAME`"
```

There might be other solutions without dependency to urlencode.

Robert

**Comment by dnsmichi** [comment]
Thanks, there already is an ongoing discussion in #5540.
