### ISSUE TITLE
Config file overwritten upon package update

### ISSUE THREAD

**Issue by nilasae** [Icinga/icinga2#5615]
Upon updating Icinga2 on my Ubuntu system I noticed that some config files are overwritten without diff/asking before. 

OS - Ubuntu 16.04LTS 
File in question - /usr/lib/icinga2/icinga2 
Package - icinga2-common (2.7.1-1.xenial in my case)

Expected Behavior
Update of package should show diff and ask if my modified config file should be overwritten

**Comment by gunnarbeutner** [comment]
The file `/usr/lib/icinga2/icinga2` is not a config file. If you're planning to modify any of the values in that file you should be using `/etc/defaults/icinga2` instead.

**Comment by nilasae** [comment]
Had issues with this in earlier versions it seems (adding environment variables), works now. Thanks!
