### ISSUE TITLE
Clean up garbage in status and config tables

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icinga2#5621]
IDO keeps old `icinga_objects` to be able to match related `statehistory` and other historic events. That's an overhead, but perfectly reasonable. We might want to add a cleanup job removing objects no longer used in history tables, but that's not what this issue is all about.

We should clean up state (and config) tables referring dead objects. The current behavior has two problems:

* Hosts vanishing from config and re-appearing months later start with a state they do not have at all
* Tables grow over time, especially in dynamic environments

Especially data growth hurts, as involved tables (states, vars) make part of most of our frontend queries:

```sql
SELECT COUNT(*) AS dead_hosts FROM icinga_hoststatus hs
  LEFT JOIN icinga_objects o ON hs.host_object_id = o.object_id
   AND o.is_active = 1
 WHERE o.object_id IS NULL;

SELECT COUNT(*) AS dead_services FROM icinga_servicestatus ss
  LEFT JOIN icinga_objects o ON ss.service_object_id = o.object_id
   AND o.is_active = 1
 WHERE o.object_id IS NULL;
```

For details, please check:

```sql
SELECT mo.name1 FROM icinga_objects mo WHERE mo.object_id IN (
  SELECT hs.host_object_id FROM icinga_hoststatus hs
    LEFT JOIN icinga_objects o ON hs.host_object_id = o.object_id
     AND o.is_active = 1
   WHERE o.object_id IS NULL
);

SELECT mo.name1, mo.name2 FROM icinga_objects mo WHERE mo.object_id IN (
  SELECT ss.service_object_id FROM icinga_servicestatus ss
    LEFT JOIN icinga_objects o ON ss.service_object_id = o.object_id
     AND o.is_active = 1
   WHERE o.object_id IS NULL
);
```

Similar for Custom Variables:

```sql
SELECT COUNT(*) FROM icinga_customvariables cvs
  LEFT JOIN icinga_objects o ON o.object_id = cvs.object_id
   AND o.is_active = 1
 WHERE o.object_id IS NULL;

SELECT COUNT(*) FROM icinga_customvariablestatus cvs
  LEFT JOIN icinga_objects o ON o.object_id = cvs.object_id
   AND o.is_active = 1
 WHERE o.object_id IS NULL;
```

These are only the most expensive ones, other object types are of course also affected.

**Comment by Al2Klimov** [comment]
@lippserd The current behavior is by design, isn't it?

**Comment by lippserd** [comment]
This will not be fixed for the IDO because the Icinga DB GA is on the way, which does not have this problem.
