### ISSUE TITLE
Consider running OPTIMIZE TABLE for volatile tables

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icinga2#5622]
State tables like icinga_servicestatus tend to be re-written again and again. Today I reduced the size of that table in a (relatively) small environment from 1,2GB to 26MB. So, running `OPTIMIZE TABLE icinga_service/hoststatus` in our housekeeping thread for MySQL might not hurt at all. Same for PostgreSQL/VACUUM - there it probably looks much worse.

**Comment by tobiasvdk** [comment]
I decreased "icinga_servicestatus" from 31GB to 208MB.
