### ISSUE TITLE
Empty result set with non-matching filters in Livestatus stats query

### ISSUE THREAD

**Issue by yoshi314** [Icinga/icinga2#5626]
I've detailed the problem in Thruk bug tracker : https://github.com/sni/Thruk/issues/762

Basically, i cannot connect via livestatus from the same host, but i can from remote host.

**Comment by dnsmichi** [comment]
Please fill in the issue template as proposed by GitHub next time.

Reading the linked issue makes me believe that Thruk cannot handle empty result values when a filter does not match.

Technically such a filter

```
GET services
ResponseHeader: fixed16
OutputFormat: json
Filter: check_type = 1
Filter: has_been_checked = 1
Stats: sum percent_state_change
Stats: min percent_state_change
Stats: max percent_state_change
```

could match or not. If it matches, the stats aggregators will calculate possible values. As seen in the other issue.

```
[[0.0000000000e+00,0.0000000000e+00,0.0000000000e+00]]
```

If nothing matches, there is no requirement to calculate anything. The caller must know that nothing matches and maybe re-adjust the filter.

```
[]
```

If we would return a fake zero result set here, this would indicate that something matches, but the stats calculation actually did not.

Imho the current implementation works as it should. The caller should check the returned values and decide upon them what to do.

**Comment by yoshi314** [comment]
I think you really should talk it out between yourselves. The thruk dev has responded that this seems to indeed to be a bug. (I just hate to be the middleman here)

https://github.com/sni/Thruk/issues/762#issuecomment-332836290

**Comment by dnsmichi** [comment]
I don't like ping-pong either, since every information is hidden in the linked issue, and not here. I'm open for discussions and a patch if this is indeed a bug. @gunnarbeutner 's opinion is also required on the matter :)

**Comment by theseal** [comment]
Any update in this issue? Having the same problem with thruk/lmd.

**Comment by dnsmichi** [comment]
I've looked into the code to implement a simple fix. Unfortunately it is not an easy one, so this requires one to find the time to create a patch. Feel free to investigate here, the code parts are found here

https://github.com/Icinga/icinga2/blob/master/lib/livestatus/livestatusquery.cpp#L514

Possible workaround - modify Thruk's code to accept empty results too, instead of accessing a key in a null object.
