### ISSUE TITLE
InfluxDBWriter: Send metric unit (perfdata)

### ISSUE THREAD

**Issue by froehl** [Icinga/icinga2#5627]
## Expected Behavior
The InfluxDBWriter send the unit of the perfdata to InfluxDB if enable_send_metadata is set and the vaule of the unit (pdv->GetUnit()) is available.

## Current Behavior
The InfluxDBWriter sends the following metrics:

- current_attempt: checkable->GetCheckAttempt()
- max_check_attempts: checkable->GetMaxCheckAttempts()
- state_type: checkable->GetStateType()
- reachable: checkable->IsReachable()
- downtime_depth: checkable->GetDowntimeDepth()
- acknowledgement: checkable->GetAcknowledgement()
- latency: cr->CalculateLatency()
- execution_time: cr->CalculateExecutionTime()

## Possible Solution
influxdbwriter.cpp:
fields->Set(String("unit"), pdv->GetUnit());

## Your Environment

* Version used: r2.7.0-1
* Operating System and version: Ubuntu 16.04.3 LTS (xenial)
* Enabled features: api checker command mainlog notification perfdata gelf influxdb

**Comment by dnsmichi** [comment]
@spjmurray your thoughts on that?

**Comment by spjmurray** [comment]
Comments in the pull request @dnsmichi, anyone else have any opinion? I know we've discussed this before at some length... probably lost in the ether after the switch to github
