### ISSUE TITLE
match() for arrays returns boolean true if array is empty

### ISSUE THREAD

**Issue by kalaksi** [Icinga/icinga2#5634]
## Expected Behavior
match() should return false when it compares the pattern to an empty array similar to how it returns false when comparing the pattern to an empty string.

## Current Behavior
match() always returns true when it compares the pattern to an empty array.

## Possible Solution
Either make it return false or clearly document the behaviour with empty arrays.

## Steps to Reproduce (for bugs)
```
<9> => match("test2", ["test2"])
true
<10> => match("test2", ["test2", "test3"])
false
<11> => match("test2", [])
true
<12> => match("test2", "")
false
```

## Context
When using apply-rules with host.groups to determine which services to assign, hosts with empty host.groups get assigned bunch of services incorrectly.

My understanding is that host.groups shouldn't be used with apply-rules this way and are meant for e.g. visual aid for icingaweb, but the configuration structure of this specific environment has not been up to me. This problem most likely won't be limited to this kind of setup as I'd imagine using host.vars in a similar way would cause the same issues.

This can be painful when upgrading icinga to 2.7 because matching used to work with empty arrays and it took quite some time to figure out the issue since the configuration was seemingly OK.

## Your Environment

* Version used (`icinga2 --version`): r2.7.1-1
* Operating System and version: CentOS 7 (3.10.0-693.2.2.el7.x86_64)
* Enabled features (`icinga2 feature list`): api checker command ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.4.2

**Comment by dnsmichi** [comment]
match() never supported arrays, only strings. We've added support for arrays in 2.7.x.

So this seems to be a new issue coming with array support.

**Comment by dnsmichi** [comment]
The code just falls through since `texts` does not contain any value. `MatchAll` is the default, which is why match() returns true.

https://github.com/Icinga/icinga2/blob/master/lib/base/scriptutils.cpp#L184

`MatchAny` returns `false` then. Does not make sense either, but explains the behaviour.

```
Icinga 2 (version: v2.7.1-215-gbdd432026)
<1> => var arr = []
null
<2> => match("foo", arr, MatchAny)
false
<3> => match("foo", arr, MatchAll)
true
```

**Comment by kalaksi** [comment]
Ah, okay. People that configured the setup this way probably just added a bunch of hostgroups, tested match() against those, saw it working and were content with it. If would probably have been better if match() just wouldn't have accepted arrays before or would've always returned false. But anyways, thanks for quick reply.

**Comment by dnsmichi** [comment]
Probably. That issue came up once, and we thought about finding a suitable feature enhancement before denying something which would be enabled later on again.

I do have a fix on disk for it already, just testing it.

```
Icinga 2 (version: v2.7.1-218-g0ca9a1a5b)
<1> => var arr = []
null
<2> => match("foo", arr, MatchAny)
false
<3> => match("foo", arr, MatchAll)
false
<4> => arr = [ "foobar", "bumsti" ]
null
<5> => match("foo*", arr, MatchAll)
false
<6> => match("foo*", arr, MatchAny)
true
```

**Comment by dnsmichi** [comment]
regex() and cidr_match() have the same problem.

**Comment by dnsmichi** [comment]
Edge case test: Empty patterns.

```
<16> => arr = [ "foobar", "" ]
null
<17> => match("", arr, MatchAny)
true
```

This worked before, just to be sure it is not affected by the patch.

**Comment by dnsmichi** [comment]
## regex() and cidr_match() broken

```
<1> => var arr = []
null
<2> => regex("^foo.*", arr, MatchAny)
false
<3> => regex("^foo.*", arr, MatchAll)
true
<4> => cidr_match("192.168.33.5/24", arr, MatchAny)
false
<5> => cidr_match("192.168.33.5/24", arr, MatchAll)
true
```

## Fixes

### regex()

```
<2> => var arr = []
null
<3> => regex("^foo.*", arr, MatchAny)
false
<4> => regex("^foo.*", arr, MatchAll)
false
```

### cidr_match()

```
<2> => var arr = []
null
<5> => cidr_match("192.168.33.5/24", arr, MatchAny)
false
<6> => cidr_match("192.168.33.5/24", arr, MatchAll)
false
```

**Comment by dnsmichi** [comment]
Re-assigning to v2.8 as it is not a critical bug.
