### ISSUE TITLE
Upgrading on Ubuntu changes command-plugins.conf without warning

### ISSUE THREAD

**Issue by Stretch96** [Icinga/icinga2#5644]
When I upgrade icinga2 via apt, the `/usr/share/icinga2/include/command-plugins.conf` file is changed without warning.

I have changed the 'hostalive' command, so when this is changed, it gets quite loud until I revert the
 file changes 😬 

## Expected Behavior
When upgrading it should ask if we wish to keep the currently-installed version, or install the package maintainer's version.

## Current Behavior
It overwrites any changes in /usr/share/icinga2/include/command-plugins.conf

## Possible Solution
Add /usr/share/icinga2/include/command-plugins.conf to conffiles

## Environment
Ubuntu 16.04
Upgrading to icinga2 version r2.7.1-1

**Comment by gunnarbeutner** [comment]
The ITL files (i.e. everything in /usr/share/icinga2/include) are not user-configurable. If you want a custom version of some specific *Command object you can use inheritance (in your own config files):

```
object CheckCommand "hostalive-stretch96" {
  import "hostalive"

  vars.xyz = ...
}
```

**Comment by Stretch96** [comment]
Cool thanks @gunnarbeutner, that worked nicely 👍
