### ISSUE TITLE
Function escape_shell_arg does not escape `

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icinga2#5645]
## Expected Behavior
Function escape_shell_arg escapes also `.

## Current Behavior
Service output including ` causes notification commands to fail.

## Possible Solution
Escape ` with \. If command substition is a legitimate use for Icinga 2 than implementation will be more complex.

## Steps to Reproduce (for bugs)
```
icinga2 console
<1> escape_shell_arg("`expand_path'")
"'`expand_path'\\'''"

echo "'`expand_path'\\'''"
>
```

```
icinga2 console
<1> escape_shell_arg("`expand_path': `~/.facter/facts.d'")
"'`expand_path'\\'': `~/.facter/facts.d'\\''''"

echo "'`expand_path'\\'': `~/.facter/facts.d'\\''''"
-bash: command substition: line 1: unexpected EOF while looking for match `''
-bash: command substition: line 2: syntax error: unexpected end of line
```

## Context
Output of plugins sending ruby stacktraces for example let Icinga 2 fail to send notifications.

## Your Environment
* Version used (`icinga2 --version`): 2.7.1
* Operating System and version: RHEL 7

**Comment by gunnarbeutner** [comment]
Note that "icinga2 console" escapes strings so that they're valid "Icinga" strings. I.e. the quotes at the start and end of the string are not actually part of the string. Also, there is only really one backslash in the "real" string:

```
<7> => log(escape_shell_arg("`expand_path'"))
information/config: '`expand_path'\'''
null
```

Which works as expected in sh and bash:

```
$ echo '`expand_path'\'''
`expand_path'
```
