### ISSUE TITLE
Request: AMQP output feature

### ISSUE THREAD

**Issue by dgacias** [Icinga/icinga2#5648]
## Expected Behavior
I think it would be useful to be able to output using AMQP to a rabbitmq exchange, so you can use exchanges to route messages to different queues and the have workers consume them and do stuff in reaction to whatever happened.

## Current Behavior
You can output to logstash, but you need to specify a static defined output or multiple outputs. I cannot use dynamic workers to pull the events and then do things based on them.
What you can do now is output to logstash, and then logstash output to rabbit, but it is another piece of software when you could just output to a rabbit directly.

## Possible Solution
Implement AMQP in an output plugin so you can use whatever solution uses AMQP like rabbitmq :)

## Context
Right now we are using icinga to output to influxdb, and then make static service dashboards on grafana. With a rabbitmq in the middle we could use dynamic workers to make dashboards and also we ensure the icinga output data is retained on a queue if not consumed, so no data is lost. Another downside is that if influxdb is down, icinga output data is lost because there is no avaliable target.
So that's why a middle stable rabbit should hang the messages until there's an avaliable consumer instead of losing them.

Thanks guys!

**Comment by Crunsher** [comment]
Thanks you for your ticket.

If I understand you want an additional feature like the gelf- or elasticwriter? The code of these two features is quite simple, most of it could probably be reused for crating such a amqp-writer

**Comment by dgacias** [comment]
Yes, something like these. You can even re-use the logic of the amqp output of logstash itself: https://github.com/logstash-plugins/logstash-output-rabbitmq/ :)

**Comment by dnsmichi** [comment]
This issue needs a more clear specification on

- the transport (protocol, auth, etc.)
- message types and their format
- specific purpose it should solve, including a scenario which can be built to see its benefits

There's already the API event streams where you can bind you own daemon onto. This could for example forward the messages to your RabbitMQ. Look into icingabeat how it is done there for example.

**Comment by dgacias** [comment]
Sorry, im not a programmer, i don't know how to make these.

**Comment by dnsmichi** [comment]
You can still propose the specification points. No need for actual code in the first steps.

**Comment by dnsmichi** [comment]
@lippserd MQTT might be a candidate for this.
