### ISSUE TITLE
Get hosts filtered by comments (API)

### ISSUE THREAD

**Issue by TimL20** [Icinga/icinga2#5649]
## Expected Behavior and Context
I had a handicap with my last use case with the Icinga API. I solved it with a workaround, but anyway: it would be fine to be able to filter hosts with attributes of their comments. Or be able to use "joins" with comments. Or both of course. The reason is, that I want to get all hosts, that don't have comments from a specific author somehow.

## Current Behavior
Currently it's not possible. I can understand, that using "joins" would be difficult to implement, as a Host/Service can have multiple comments. The workaround I use now, is to set host.notes; and add a comment each line with a specific text (like comments from a specific author) and a timestamp. The problem is, that there may be problems with asyncronous acces (my script has about 5 Threads...), as I need to read host.notes before I can "add" (set) something... And Comments are also better to see in Icingaweb2, but that's not a such important fact...

## Possible Solution
As I said, I can't imagine how to implement it with "joins"... Maybe somebody else has any idea.

Another workaround would be to fetch all Comments and their host_name and service_name attributes, and get the associated hosts/services this way... But I think that's not a better workaround.

**Comment by dnsmichi** [comment]
As you already figured, the relationship between host/service objects to comments is 1..n. There is no reliable way to do a group join and filter based on n joined objects if you go for /v1/objects/hosts.

I suggest to target /v1/objects/comments and use advanced filters which include host/service filters and also the author name. Examples for that can be found in the API documentation.

The result set needs to be dealt with in a programmatic fashion.
