### ISSUE TITLE
checksum scheme

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#5657]
Currently there is one key per type with a hash that contains keys which are the names of objects of said type and contain a json string dictionary of their different checksums. eg

```
> hgetall icinga:config:Host:checksum
1) "testo"
2) "{\"groups_checksum\":\"4921d837151d77b7fc0b982286f7ce3bfec3f93e\",\"name_checksum\":\"c0b333c1f24f1494026b629945f32305a1757722\",\"properties_checksum\":\"d30db37352e51215d5e7e59dfe891e4cae28b5db\",\"vars_checksum\":\"3fa47c8d283104f33043338f8e7ff49df1f3531f\"}"
```

The whole thing could be more abstracted into a scheme fitting redis by either moving the names or types out of the hash/dictionary into the key 

```
> hgetall icinga:config:Host:checksum:name
1) "testo"
2) "c0b333c1f24f1494026b629945f32305a1757722"
```

or

```
> hgetall icinga:config:Host:checksum:testo
1) "name"
2) "c0b333c1f24f1494026b629945f32305a1757722"
...
```

**Comment by Crunsher** [comment]
refs  #5118

**Comment by gunnarbeutner** [comment]
Option 1 seems like the most logical choice.
