### ISSUE TITLE
Downtime scheduling is flawed

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icinga2#5660]
We have a flexible scheduled downtime on a host. The downtime starts on the last saturday of a month between 23:50 and 24:00, and lasts for 400 minutes. Now guess what happened on Sat, 30th September 2017?

![unbenannt](https://user-images.githubusercontent.com/16338849/31391139-fcc143d2-add5-11e7-999e-b080228378e6.PNG)

Sat 2017-09-30 23:50 -- downtime starts as "saturday -1" evaluates to 2017-09-30
Sun 2017-10-01 00:00 -- Icinga rereads configuration files, "saturday -1" now evaluates to 2017-10-28
Sun 2017-10-01 00:00 -- downtime is removed, ticket is generated, 2nd level on-call-duty is activated for no reason

## Expected Behavior

Scheduled downtimes should just work.

## Current Behavior

You cannot expect scheduled downtimes to "just work". They will break in interesting ways on various edge cases that have not been given enough thought. For example, the syntax for legacy timeperiods allows for selecting the first (or last) day-of-week in a month, but does not allow for specifying downtimes that cross the 00:00-24:00 boundary of that day. And apparently, the `<day-of-week> <number>` syntax also breaks down with flexible downtimes, because there is some sort of hard-coded rereading of configuration at 00:00, as seen above. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`): 2.7.1
* Operating System and version: CentOS 7.4 x64
* Enabled features (`icinga2 feature list`): api checker command graphite ido-pgsql mainlog notification syslog
* Icinga Web 2 version and modules (System - About): 2.4.1
* Config validation (`icinga2 daemon -C`): works fine :-)
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
Your tone is pretty aggressive here. Do you happen to have a configuration which allows to reliably reproduce the issue you're describing in your screenshot?

**Comment by terra-nova** [comment]
> Your tone is pretty aggressive here.

Non intentionally. I'm not angry...  actually I found it quite funny... The flexible (scheduled) downtime in question was working without hassle for weeks and I was trying to find out why it was failing all of a sudden on that day until it occurred to me that the last saturday in the month was also the last day of the month... That was kind of a HEUREKA moment :-)

> Do you happen to have a configuration

We use the following apply statement for scheduling "flexible" downtimes... it's a bit of a hack because Director does not currently support defining downtimes. Basically we have a custom variable `scheduled_downtimes` for each host and service object that holds a list of timeperiod names (which can be edited using Director) and dynamically generate ScheduledDowntime objects from that.

```
apply ScheduledDowntime for (downtime in host.vars.scheduled_downtimes) to Host {
    var timeperiod = get_time_period(downtime)
    author = "icinga"
    comment = timeperiod.display_name
    ranges = timeperiod.ranges.clone()

    /* Work around Icinga Director's lack of support for flexible downtimes. If
     * the timeperiod object is derived from a template named "Flexibe Downtime",
     * we set the downtime type to flexible and convert the timeperiod object's
     * "display_name" property to downtime duration, in minutes.
     */
    if("Flexible Downtime" in timeperiod.templates) {
        comment = "Flexible Downtime, duration " + number(timeperiod.display_name) + " minutes" // display_name holds the downtime duration in minutes, not a comment
        fixed = false
        duration = number(timeperiod.display_name)
    }

    ignore where downtime == ""
}
```

The timeperiod for the host looks like this (copy & paste from Director "Preview" tab):

```
object TimePeriod "*** Monatssicherung" {
    import "legacy-timeperiod"
    import "Flexible Downtime"

    display_name = "400"
    ranges = {
        "saturday -1"	= "23:50-24:00"
    }
}
```

>  to reliably reproduce the issue you're describing in your screenshot?

I suspect it has something to do with the specific date (saturday -1 is also the last day of the month), as the downtime had been working correctly for weeks.

**Comment by dnsmichi** [comment]
Can you cut down the hacks into a "normal" configuration and reproduce it with that?

**Comment by terra-nova** [comment]
Let me try...

Host object (copy & paste from Director's "Preview" tab):

```
object Host "afflicted-host" {
    display_name = "afflicted-host"
    address = "10.0.0.1"
    check_command = "hostalive"
    max_check_attempts = "5"
    check_interval = 1m
    retry_interval = 30s
    zone = "master"
}
```

ScheduledDowntime object (reconstructed from output of `icinga2 object list -t scheduleddowntime -n '...'`):

```
object ScheduledDowntime "afflicted-host-downtime" {
    host_name = "afflicted-host"
    author = "icinga"
    comment = "Flexible Downtime, duration 400 minutes"
    duration = 400
    fixed = false
    ranges = {
        "saturday -1" = "23:50-24:00"
    }
}
```

**Comment by dnsmichi** [comment]
Any updates on this?

Cheers,
Michael
