### ISSUE TITLE
Service Apply for returns an error without setting the host variable

### ISSUE THREAD

**Issue by h3ge** [Icinga/icinga2#5661]
## Expected Behavior
Icinga should be able to handle the empty array and reload without an error

## Current Behavior
Error: Array iterator requires value to be an array.

## Steps to Reproduce (for bugs)
1. Fresh install of Icinga2
2. Add a apply service for rule
3. You should be able to see the error

## Your Environment

* Version used: r2.7.0-1
* Operating System and version: Ubuntu 16.04
* Enabled features: api checker command graphite ido-pgsql mainlog notification statusdata
* Config validation (`icinga2 daemon -C):

        information/cli: Icinga application loader (version: r2.7.0-1)
        information/cli: Loading configuration file(s).
        information/ConfigItem: Committing config item(s).
        information/ApiListener: My API identity: monitoring10.ad.hegedues.at
        critical/config: Error: Array iterator requires value to be an array.
        Location: in /etc/icinga2/conf.d/services.conf: 118:1-118:52
        /etc/icinga2/conf.d/services.conf(116):
        /etc/icinga2/conf.d/services.conf(117):
        /etc/icinga2/conf.d/services.conf(118): apply Service "disk" for (config in host.vars.disks) {
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        /etc/icinga2/conf.d/services.conf(119):     check_command = "nrpe"
        /etc/icinga2/conf.d/services.conf(120):     max_check_attempts = "3"

        (0) Evaluating 'apply' rule (in /etc/icinga2/conf.d/services.conf: 118:1-118:52)
        (1) Evaluating 'apply' rules for host 'monitoring10.ad.hegedues.at'

        critical/config: 1 error

**Comment by dnsmichi** [comment]
You're saying that `disks` is empty, but you did not attach the host configuration object unfortunately. Can you share more details on how to reproduce the error with the involved configuration snippets?

**Comment by h3ge** [comment]
Never mind, I redefined the disks variable inside the director triggered the error cause of the default host at  the node level...
