### ISSUE TITLE
crashing backend

### ISSUE THREAD

**Issue by loeken** [Icinga/icinga2#5673]
whenever i try to start icinga it seems to start fine and after around 1 minute and i see "backend not available" in the webui.

The error log seem to be completely emtpy, in the normal icinga2.log I do see some cricical/SOcketEvents,
that is the only thing that looks like an error messager to me.

critical/SocketEvents: Exception thrown in socket I/O handler:
Error: Tried to read/write from a closed socket.

	(0) libbase.so.2.7.1: <unknown function> (+0xe251f) [0x7f4e095f451f]
	(1) libbase.so.2.7.1: <unknown function> (+0xe25a9) [0x7f4e095f45a9]
	(2) libbase.so.2.7.1: icinga::SocketEventEngineEpoll::ChangeEvents(icinga::SocketEvents*, int) (+0x147) [0x7f4e09578487]
	(3) libbase.so.2.7.1: icinga::TlsStream::OnEvent(int) (+0x49e) [0x7f4e095d526e]
	(4) libbase.so.2.7.1: icinga::SocketEventEngineEpoll::ThreadProc(int) (+0x44b) [0x7f4e095d086b]
	(5) libboost_thread.so.1.54.0: <unknown function> (+0xba4a) [0x7f4e09f5fa4a]
	(6) libpthread.so.0: <unknown function> (+0x8184) [0x7f4e098cc184]
	(7) libc.so.6: clone (+0x6d) [0x7f4e087bcffd]

## Your Environment

* Version used (`icinga2 --version`):
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.5 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 4.4.0-97-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.2
  Build host: 02a0e862c14c

* Operating System and version:
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"

* Enabled features (`icinga2 feature list`):
 icinga2 feature list
Disabled features: command compatlog debuglog gelf graphite influxdb livestatus opentsdb statusdata syslog
Enabled features: api checker ido-mysql mainlog notification perfdata

* Icinga Web 2 version and modules (System - About):

Name | Version
director | master
monitoring | 2.4.2

* Config validation (`icinga2 daemon -C`):
# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.7.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: ccc-icinga.ccc-icinga.a7.internal.cloudapp.net
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 145 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 144 Endpoints.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 13 Notifications.
information/ConfigItem: Instantiated 211 CheckCommands.
information/ConfigItem: Instantiated 2 Downtimes.
information/ConfigItem: Instantiated 149 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 15 HostGroups.
information/ConfigItem: Instantiated 4 UserGroups.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 2 Users.
information/ConfigItem: Instantiated 613 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
Just 1 icinga2

**Comment by dnsmichi** [comment]
How's that related to Jira, a different application? Can you share more details on what's running on your Icinga 2 server? Did you analyse its performance already, i.e. by using the hints inside the troubleshooting docs?

**Comment by loeken** [comment]
I am sorry I ment to write icinga2 there, I updated the comment

**Comment by loeken** [comment]
I saw the <unknown function> and thought it was some bug. went through the .md again and tested performance, noticed that it was consuming a lot of memory. scaled up my vm and now its all fine. So lack of memory.

p.s. thanks for the awesome response time :)

**Comment by dnsmichi** [comment]
Glad you solved it by yourself 👍
