### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#5674]
While clicking around the github project I noticed this page: https://github.com/Icinga/icinga2/community

Which rightfully notes we don't have a code of conduct and I don't see why we should not have one, considering the project is steadily growing and we expect it to continue to do so.

The 'Contributor Covenant' looks good to me (we only have to put in a contact e-mail for abuse reports).

**Comment by dnsmichi** [comment]
Thanks, this should be discussed and applied to all projects, I was thinking about it already for a while. I'll put it onto Monday's meeting.

**Comment by Thomas-Gelf** [comment]
In theory a CoC is a good idea. Problematic side-effect with CoCs is that they attract people focused more on playing police than on technology. They attract troublemakers using your CoC as a weapon. While obligating project maintainers to maintain confidentiality they happily second their arguments with tweet storms and personal attacks. They insist on enforcement based on rules like this one:

> Project maintainers who do not follow or enforce the Code of Conduct in good
> faith may face temporary or permanent repercussions [..]

They tear personal/political opinions of random people on the web into your project. And then they want to force you to take action, as they feel offended. You have a different opinion? Good luck.

We should try to stay a strong, inclusive, welcoming community. I do not think that we need to follow this CoC-hype to achieve that. If I really had to choose one, I'd opt for [NCoC](https://github.com/domgetter/NCoC/blob/master/CODE_OF_CONDUCT.md) or similar. The [Python CoC](https://www.python.org/psf/codeofconduct/) is also a pretty good example.

Regards,
Thomas

**Comment by dnsmichi** [comment]
As said, we'll discuss this on the team. I'm closing here.
