### ISSUE TITLE
Update syntax highlighting support files: nano

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5683]
I'd guess they are old and also would highlight already deprecated attributes, or miss newer ones.

This only is a reminder to do so, nothing critical.

**Comment by dnsmichi** [comment]
Guess we'll just retire nano support, or wait for a PR. I don't like nano, so I won't deal with that.

**Comment by kingspride** [comment]
I tried to match the vim file for nano. please have a look at the PR and tell me if I can do something better :)
