### ISSUE TITLE
icinga2 2.7 and pagerduty integration script problem

### ISSUE THREAD

**Issue by strajansebastian** [Icinga/icinga2#5684]
There seems to be a problem with the pagerduty default integration with icinga2.
Here you can find a link to the official documentation used in my setup: https://www.pagerduty.com/docs/guides/icinga2-integration-guide/

## Expected Behavior

No errors should be generated in the notification log in case the email parameter is missing for a user.

This is the user defined by the pagerduty configuration file: 

```
object User "pagerduty" {
  pager = "SERVICE_API_KEY_HERE"
  groups = [ "icingaadmins" ]
  display_name = "PagerDuty Notification User"
  states = [ OK, Warning, Critical, Unknown, Up, Down ]
  types = [ Problem, Acknowledgement, Recovery ]
}
```
https://raw.githubusercontent.com/mdcollins05/PagerDuty-Icinga2/master/pagerduty-icinga2.conf

## Current Behavior

The problem is the fact that it generates error messages in the icinga2.log file.
The errors are because the -r flag (USEREMAIL) is not specified. When in the user configuration nothing is defined the icinga_contacts table doesn't contain anything in the email_address column.

Log error example:
```
[2017-10-17 17:09:43 +0000] warning/PluginNotificationTask: Notification command for object 'www.propertyshark.com!endpoint-https-www.propertyshark.com-path-mason-NY-New-York-City-Foreclosures' (PID: 1374289, arguments: '/etc/icinga2/scripts/mail-service-notification.sh' '-4' '10.101.101.2' '-6' '' '-b' '' '-c' '' '-d' '2017-10-17 17:09:43 +0000' '-e' 'endpoint-https-www.propertyshark.com-path-mason-NY-New-York-City-Foreclosures' '-l' 'www.propertyshark.com' '-n' 'www.propertyshark.com' '-o' 'HTTP OK: HTTP/1.1 200 OK - 93544 bytes in 0.629 second response time ' '-r' '' '-s' 'OK' '-t' 'RECOVERY' '-u' 'endpoint-https-www.propertyshark.com-path-mason-NY-New-York-City-Foreclosures' '-v' 'false') terminated with exit code 1, output: Requirement parameters are missing.

Required parameters:
  -d LONGDATETIME ($icinga.long_date_time$)
  -e SERVICENAME ($service.name$)
  -l HOSTNAME ($host.name$)
  -n HOSTDISPLAYNAME ($host.display_name$)
  -o SERVICEOUTPUT ($service.output$)
  -r USEREMAIL ($user.email$)
  -s SERVICESTATE ($service.state$)
  -t NOTIFICATIONTYPE ($notification.type$)
  -u SERVICEDISPLAYNAME ($service.display_name$)

Optional parameters:
  -4 HOSTADDRESS ($address$)
  -6 HOSTADDRESS6 ($address6$)
  -b NOTIFICATIONAUTHORNAME ($notification.author$)
  -c NOTIFICATIONCOMMENT ($notification.comment$)
  -i ICINGAWEB2URL ($notification_icingaweb2url$, Default: unset)
  -f MAILFROM ($notification_mailfrom$, requires GNU mailutils (Debian/Ubuntu) or mailx (RHEL/SUSE))
  -v ($notification_sendtosyslog$, Default: false)
```

## Possible Solution

Add an email address in order to send the email. Duplicated the email address from the icingaadmin user in my case because I don't want to generate errors in other locations because the emails couldn't be delivered.

## Steps to Reproduce (for bugs)

1. configure pagerduty integration - https://www.pagerduty.com/docs/guides/icinga2-integration-guide/
2. activate pagerduty for some services/hosts
```
vars.enable_pagerduty = true
```
3. define notification email for a host/service on which you want to make the check
```
  vars.notification["mail"] = {
    /* The UserGroup `icingaadmins` is defined in `users.conf`. */
    groups = [ "icingaadmins" ]
  }
```
4. you should get the error in the icinga2.log after a reboot and notification sent even if it is forced from the interface

## Context

Noticed this error only in the 2.7 version and I found that some major changes have been made to the notification scripts.
I had some problems with the pagerduty integration and because I saw the errors in the log I started to try to fix them because I taught that would be the cause, but in the end the integration wasn't working because of some bad templates that I was using which didn't had the pagerduty activation.
It would be nice if this is solved in one way or another. This should save hours of debugging in the future for others in case they notice the error.

Can you suggest a best course of action in order to solve this?
My ideas would be:
- add dummy/valid email
- implement in icinga2 to ignore/throw a warning in case no email is specified for a user in the configuration
- ignore notifications that don't have an email address specified for the user

## Your Environment

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.3 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-57-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: a9edf83df4f7
```
* Operating System and version: Ubuntu 16.04.3 LTS (Xenial Xerus)
* Enabled features (`icinga2 feature list`):
```
Disabled features: compatlog debuglog gelf influxdb opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-pgsql livestatus mainlog notification
```
* Icinga Web 2 version and modules (System - About): not relevant
* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: r2.7.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: prod-ops-icinga-01.propertyshark.lan
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 2495 Notifications.
information/ConfigItem: Instantiated 210 CheckCommands.
information/ConfigItem: Instantiated 205 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 45 HostGroups.
information/ConfigItem: Instantiated 1 Comment.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 2 Users.
information/ConfigItem: Instantiated 2185 Services.
information/ConfigItem: Instantiated 6 ServiceGroups.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
information/ConfigItem: Instantiated 1 LivestatusListener.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by strajansebastian** [comment]
Below you can find a log line from a icinga2 (version 2.4.10-1~ppa1~trusty1) install:

[2017-10-17 21:17:27 +0300] warning/PluginNotificationTask: Notification command for object 'prod-web-legacycorelocation-06!prod-service-snmp-server_check_all_disk_usage_space' (PID: 5748, arguments: '/etc/icinga2/scripts/mail-service-notification.sh') terminated with exit code 1, output: mail: You must specify direct recipients with -t when -s, -c, or -b is used

So it seems that this problem may be older than I taught, but it became more visible only recently due to the changes.

Some better validation on the email should be done in case it is missing if it is that critical.
What do you think about this?

**Comment by dgoetz** [comment]
This is not a problem of the software just of configuration I think. 

Your apply rules for mail notification match because you made the pagerduty user part of the icingaadmins usergroup. So you explicitly tell Icinga 2 to send mail notifications to the user, but you only want pagerduty notifications.

So please review your configuration. My idea would be to remove the groups attribute from the pagerduty user and assign him in a similar way like the icingaadmins usergroup but for pagerduty instead of mail.

**Comment by dnsmichi** [comment]
If you don't have any users with the `email` attribute set, it doesn't make sense to use the mail notification apply rules.

Drop those apply rules, and create proper `vars.notification` entries for pagerduty, e.g. by using a proper key.

This is a configuration problem, and not a bug. Please proceed on the community channels.

**Comment by strajansebastian** [comment]
In the end I created for the pagerduty user a custom UserGroup and this way no more duplicate mails are sent. Thanks for the help!

```
object User "pagerduty" {
        pager = "SERVICE_API_KEY_HERE"
        groups = [ "pagerdutyadmins" ]
        display_name = "PagerDuty Notification User"
        states = [ OK, Warning, Critical, Unknown, Up, Down ]
        types = [ Problem, Acknowledgement, Recovery ]
}

object UserGroup "pagerdutyadmins" {
        display_name = "Icinga 2 PagerDuty Admin Group"
}
```
