### ISSUE TITLE
Icinga2 status failed

### ISSUE THREAD

**Issue by StevieSun** [Icinga/icinga2#5685]
When I installed Icinga2 for the first time it worked without any problem. After i tried to edit the configurations something went wrong and the `systemctl status icinga2` showed `Active failed`. 
In the process of fixing the configurations, it was totally messed up. So I removed the package icinga2 and tried to install again.

In the installation steps, I executed `apt-get install icinga2` which was successful. 
Next i executed `icinga2 feature list` which gives the following output
`critical/cli: Cannot access path ''.`

Please help with proper approach to debug from here and fix the issue. I am able to successfully install in a differnt machine, but not able to fix the problem in the machine mentioned

Environment used
1. Ubuntu16.04 LTS

**Comment by dnsmichi** [comment]
Please explain which repositories are involved, which Icinga 2 version and the exact installation calls. That's also asked in the issue template.

**Comment by StevieSun** [comment]
1. curl -sSL https://packages.icinga.com/icinga.key | sudo apt-key add -

**Comment by StevieSun** [comment]
Sorry about that. The details are as follows.
ICINGA verion
icinga2 - The Icinga 2 network monitoring daemon (version: r2.4.1-1)

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: _CODENAME=xenia
  Platform version: ID="16.04
  Kernel: Linux
  Kernel version: 4.4.0-97-generic
  Architecture: x86_64
Installation procedure

1. curl -sSL https://packages.icinga.com/icinga.key | sudo apt-key add -
2. sudo nano /etc/apt/sources.list.d/icinga.list and added deb https://packages.icinga.com/ubuntu icinga-xenial main
3. apt-get update
4. sudo apt-get install icinga2 icinga2-ido-mysql
5. apt-get install icinga2
6. icinga2 feature list ( this gives the error mentioned above)

**Comment by dnsmichi** [comment]
2.4.1 is quite dated and not supported anymore. There seems to be a package priority problem on your end.

Ensure to use 2.7.x and test again.
