### ISSUE TITLE
icinga check does not report a warning 

### ISSUE THREAD

**Issue by lbetz** [Icinga/icinga2#5689]
## Expected Behavior

The icinga check has to report a warning if a reload fails.

## Current Behavior

The check returns an OK constantly

## Context

In a distributed environment I got no warning anymore if an agent or satellite doesn't got a valid configuration from config master

## Your Environment

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

* Operating System and version:
Linux CenOS 7.4

* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
Can you please verify that the icinga check was actually run, and provide insights in its check history? 

Which kind of setup is that, a single master and a satellite? How's the "icinga" check configured, command endpoint or top down config sync?

**Comment by lbetz** [comment]
Check was executed of course, command endpoint, generally the check doesn't work, on master, satellites, agents.

Icinga Service is defined like the example config does.

**Comment by dnsmichi** [comment]
Discussed it offline. @N-o-X please do me a favor and look into this after 2.8 has been released. I've assigned it to 2.9.0 now not being forgotten, possible bugfix releases can be considered.

This probably came in as regression in 2.6.0 or similar.

**Comment by dnsmichi** [comment]
According to @lbetz this doesn't occur with 2.8 anymore. Closing.
