### ISSUE TITLE
Improve documentation of cipher_list

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icinga2#5690]
## Expected Behavior
cipher_list is explained in more depth and has examples and recommendations.

## Current Behavior
cipher:list only tells "Optional. Cipher list that is allowed."

## Possible Solution
Perhaps something like https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html or https://cipherli.st/.

Feel free to assign it to myself and I will try to create some documentation.

**Comment by Crunsher** [comment]
>Feel free to assign it to myself and I will try to create some documentation.

Sure thing, have fun 🎉

**Comment by kobmaki** [comment]
The option cipher_list was introduced in #3888 "Implement SSL cipher configuration support for the API feature". In the issue you find information that are usefull for documentation. 

The cipher_list is used in die ApiListener object.

The option tls_protocolmin is also very important, as it restrict to the minimum allowed protocol. Actually the default tls_protocolmin is set to TLSv1.  All supported OS versions are do not requires TLSv1 and TLVSv1.1 works.

Wouldn't it be better to add more details to the chapter "19-technical-concepts.md".
