### ISSUE TITLE
Object list with services named "service" and spaces

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icinga2#5694]
Object list doesn't work correctly if services are named with "service" and spaces.

Works:
```
icinga2 object list --type Service --name Service*
% declared in '/etc/icinga2/zones.d/master/services.conf', lines 106:1-106:70
   __name = "testhost.localdomain!Service icinga2"
   ...

icinga2 object list --type Service --name Service\*
% declared in '/etc/icinga2/zones.d/master/services.conf', lines 106:1-106:70
   __name = "testhost.localdomain!Service icinga2"
   ...
```

Works also:
```
icinga2 object list --type Service --name service\*
% declared in '/etc/icinga2/zones.d/master/services.conf', lines 106:1-106:70
   __name = "testhost.localdomain!service icinga2"
   ...
```

Doesn't work:
```
icinga2 object list --type Service --name service*
```

# Environment
* Version used (`icinga2 --version`): r2.7.1-1
* Operating System and version: CentOS Linux release 7.4.1708 (Core)

**Comment by gunnarbeutner** [comment]
Please also attach the output of `ls service*` for the same directory you ran those other commands in.

**Comment by gunnarbeutner** [comment]
@mwaldmueller: Any news? 🤔

**Comment by mwaldmueller** [comment]
I'm not able to reproduce it any more and close the issue. I guess you were right and it was a overlap with the local files or shell configuration.

Thanks for your investigation!
