### ISSUE TITLE
delete comments with icinga cluster result in 404 No objects found

### ISSUE THREAD

**Issue by marcelfischer** [Icinga/icinga2#5697]
We have an icinga cluster running with two nodes and ido enable_ha=true.

## Expected Behavior
When I create a comment on node1, I should be able to see and delete that comment from node2 through the api.

## Current Behavior
When I create a comment in the icingaweb2 on node1 and try to delete it on node2 I get "404 No objects found".
I used the api on both nodes to check the current comments and the problem is that node2 doesn't see the comment from node1.
I have some troubles with the api call but here is the outcome:

node1:
`curl -k -s -u icingaweb2:***'https://localhost:5665/v1/objects/comments?attrs=text' | grep node2 --color=auto`
nothing

node2:
`curl -k -s -u icingaweb2:***'https://localhost:5665/v1/objects/comments?attrs=text' | grep node2 --color=auto`
...
,{"attrs":{"text":"node2"},
...

api-users.conf is identical on both nodes:
/etc/icinga2/conf.d/api-users.conf:
```
/**
 * The APIUser objects are used for authentication against the API.
 */
object ApiUser "root" {
  password = "***"
  // client_cn = ""

  permissions = [ "*" ]
}

object ApiUser "icingaweb2" {
  password = "***"
  permissions = [ "status/query", "actions/*", "objects/modify/*", "objects/query/*" ]
}
```

## Steps to Reproduce (for bugs)

1. Create a comment on node1
2. Try to delete the comment on node2

## Your Environment

* Version used (`icinga2 --version`): r2.7.1-1
* Operating System and version: RHEL 7.4
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About):     2.4.2
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
- Verify that both nodes are connected and syncing
- Ensure that the secondary master accepts config
- Look into the logs for object creation messages for comments
- Ensure that you're not bitten by #3668

**Comment by marcelfischer** [comment]
Okay one node (the one with the director) had accept_config = false
Sorry for that... Now I can delete the comments.
