### ISSUE TITLE
livestatus log query return empty host_name 

### ISSUE THREAD

**Issue by spaolo** [Icinga/icinga2#5698]
Livestatus returns empty host_name for log queries whend event type is HOST NOTIFICATION or CURRENT HOST STATE.

We are trying to set up a thruk installation mysql log cache wich runs a log query  to import logs from livestatus but import process  fails complaining about no host name.

After some troubleshooting we hit this strange beavior: running the following query the host_name column is not filled where the event type is HOST NOTIFICATION  or CURRENT HOST STATE

GET log
Columns: type host_name
Filter: type = HOST NOTIFICATION
Filter: type = CURRENT HOST STATE
Or: 2
OutputFormat: csv
ResponseHeader: fixed16

In my understanding the &LogTable::HostNameAccessor object set at line 74 gets rewritten by one of the following call HostsTable::AddColumns, ContactsTable::AddColumns, CommandsTable::AddColumns
at  https://github.com/Icinga/icinga2/blob/20e8fe5ed3dc0c361a3387df856746845f7a1be3/lib/livestatus/logtable.cpp#L78 
As a workaround we moved the AddColumns calsl before table->AddColumn(prefix + "host_name", call and all seems working fine.

#Steps to reproduce
1 restart icinga2 or wait an host notification
2 run the livestatus query described below.

## Your Environment
Icinga2 installed using puppet-icinga2 using:
deb http://packages.icinga.com/debian icinga-jessie main

icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 8 (jessie)
  Kernel: Linux
  Kernel version: 3.16.0-4-amd64
  Architecture: x86_64

icinga2 feature list
Disabled features: debuglog gelf graphite icingastatus opentsdb syslog
Enabled features: api checker command compatlog ido-mysql influxdb livestatus mainlog notification perfdata statusdata

**Comment by dnsmichi** [comment]
Unfortunately we won't put any effort into this feature anymore.

**Comment by spaolo** [comment]
Are you planning to drop livestatus plugin in future version ?

**Comment by dnsmichi** [comment]
Maybe, maybe not. The StatusDataWriter feature will be dropped in 2.10. Our entire stack is built upon different interfaces, we don't have the resources to keep up the pace with additional interfaces to the 1.x world which is slowly dying.
