### ISSUE TITLE
Minor documentation typos in flapping detection description

### ISSUE THREAD

**Issue by bascarsija** [Icinga/icinga2#5703]
from [doc/08-advanced-topics.md](https://github.com/Icinga/icinga2/blob/9ba5b4f4b7a8804b51ed5c172f4b543d6968319c/doc/08-advanced-topics.md):

> Icinga 2 supports optional detection of hosts and services that are "flapping".
> 
> Flapping occurs when a service or host changes state too frequently, which would result in a storm of problem and recovery notifications. With flapping enabled a flapping notification will be sent while other notifications are ~suppresed~ *suppressed* until it calms down after receiving the same status from checks a few times. ~flapping~ Flapping *detection* can help ~detecting~ *detect* configuration problems (wrong thresholds), troublesome services, or network problems.
> 
> Flapping detection can be enabled or disabled using the enable_flapping attribute. The flapping_threshold_high and flapping_threshold_low attributes allows to specify the thresholds that control when a host or service is considered to be flapping.
> 
> The default thresholds are 30% for high and 25% for low. If the computed flapping value ~excedes~ *exceeds* the high threshold a host or service is considered flapping until it drops below the low flapping threshold.
> 
> FlappingStart and FlappingEnd notifications will be sent out accordingly, if configured. See the chapter on notifications for details
> 
> Note: There is no distinctions between hard and soft states with flapping. All state changes count and notifications will be sent out regardless of the objects state.

**Comment by Crunsher** [comment]
Oh, thanks!

Go ahead and create a pull request when you are done, I'll merge it
