### ISSUE TITLE
check_perfmon.exe does not allow query of 32bit counters

### ISSUE THREAD

**Issue by paradxum** [Icinga/icinga2#5704]
In windows there are 2 sets of perfmon data. 64 and 32 bit, check_perfmon.exe only allows query of the 64 bit counters. This is problematic if you try to monitor a 32bit MSSQL instance.

## Expected Behavior
I would suggest an option -32 to switch to query the 32 bit counters

## Current Behavior
Checks the 64 bit counters. No way to query 32 bit.

## Possible Solution
I'm sure there is a method/way in the pdh library to switch over, but I don't know C well enough to know.

## Steps to Reproduce (for bugs)
1. Have a 32 bit SQL server install
2. run mmc /32 perfmon.msc to inspect list of 32 bit counters
3. run check_perfmon.exe --print-objects
32 bit counters are not there :)

## Context
Trying to monitor the perfmon data of a 32bit MSSQL install. (Cannot change to 64 due to vendor requirement.)

## Your Environment
* Version used (`icinga2 --version`): 2.6.3-2-g9d26a9c
* Operating System and version: Windows 2012 R2

**Comment by paradxum** [comment]
Anyone have a hint? If someone can point me in the right direction as to how to switch the pdh library over to 32 bit queries I'm happy to do the leg-work.

**Comment by dnsmichi** [comment]
Haven't done anything with performance counters yet, but this entry makes me think that you need sort of a 32 bit emulation mode. https://support.microsoft.com/en-us/help/891238/some-performance-counter-objects-are-not-available-for-a-32-bit-proces

Not sure if that's possible with outside of mmc.exe or variants. `PdhEnumObjectItems()` doesn't sound like it supports it.

This one mentions a workaround: http://www.codemag.com/article/080015
