### ISSUE TITLE
nscp_api - cannot use check_cpu with "time" argument used multiple times

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icinga2#5706]
Trying nscp_api, it seems that I cannot use check_cpu with time settings.
For example:
```
  vars.nscp_api_arguments += [
   "time=1m",
   "time=5m",
   "time=15m",
   "warn=(load>80 and time not in ('1m'))",
   "crit=(load>90 and time not in ('1m'))",
   "show-all",
  ]
```
will fail with 
`check_cpu Invalid command line: unrecognised option 'time[]=1m'`
looking at the log on the client, the following command is launched:
`check_nscp_api --password xxxx -H localhost -a time=1m -a time=5m -a time=15m -a "warn=(load>80 and time not in ('1m'))" -a "crit=(load>90 and time not in ('1m'))" -a show-all`

removing the time parameters make it work

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`): server is 2.7.0-1, client is 2.7.1-1
* Operating System and version: client is Windows 2012 R2
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by Crunsher** [comment]
Which version of NSClient are you using?

**Comment by Tontonitch** [comment]
The one bundled with icinga2, so version 0.5.0.62
I guess the issue can be easily reproduced.
This parameters have been tested via the nscp web interface and were working correctly.

**Comment by Tontonitch** [comment]
I've done some tests directly with check_nscp_api.exe

With one "time" argument, it works:
```
C:\Program Files\ICINGA2\sbin>check_nscp_api.exe --password xxxxx -H localhost -q check_cpu -a time=1m -a "warn=(load>80 and time not in ('1m'))" -a "crit=(load>90 and time not in ('1m'))" -a show-all
check_cpu OK: 1m: 74% | 'total 1m'=74%;80;90

C:\Program Files\ICINGA2\sbin>
```

With 3 times the "time" argument, it fails:
```
C:\Program Files\ICINGA2\sbin>check_nscp_api.exe --password xxxxx -H localhost -q check_cpu -a time=1m -a time=5m -a time=15m -a "warn=(load>80 and time not in ('1m'))" -a "crit=(load>90 and time not in ('1m'))" -a show-all
check_cpu Invalid command line: unrecognised option 'time[]=1m'
filter=core = 'total'                   Filter which marks interesting items.
warning=load > 80                       Filter which marks items which generates a warning state.
warn=                                   Short alias for warning
critical=load > 90                      Filter which marks items which generates a critical state.
crit=                                   Short alias for critical.
ok=                                     Filter which marks items which generates an ok state.
debug                                   Show debugging information in the log
show-all                                Show details for all matches regardless of status (normally details are only showed for warnings and criticals).
empty-state=ignored                     Return status to use when nothing matched filter.
perf-config=                            Performance data generation configuration
escape-html                             Escape any < and > characters to prevent HTML encoding
help                                    Show help screen (this screen)
help-pb                         Show help screen as a protocol buffer payload
show-default                            Show default values for a given command
help-short                              Show help screen (short format).
top-syntax=${status}: ${problem_list}   Top level syntax.
ok-syntax=%(status): CPU load is ok.    ok syntax.
empty-syntax=                           Empty syntax.
detail-syntax=${time}: ${load}% Detail level syntax.
perf-syntax=${core} ${time}             Performance alias syntax.
time=                                   The time to check
 |
```

So I would say that this issue affects any nscp_api related checks requiring a repetitive argument.

**Comment by dnsmichi** [comment]
It is the way how we pass URL parameters. Seems that the NSClient++ API doesn't support the array notation. I'm not sure if it even supports multiple parameters of the same key. That should be the first thing to try - querying the NSClient++ API directly, and how that format must look like.

**Comment by Tontonitch** [comment]
Specifying multiple times the "time" argument is the only way I know in order to change the default time settings from 5s/1m/5m to something else.
Just to show you that through the NSCP web UI it works:
![screenshot](https://user-images.githubusercontent.com/600025/32415336-a6242bda-c238-11e7-863c-14eab966b13a.png)

**Comment by dnsmichi** [comment]
Please try to find out which URL format is used. I don't have such a setup at hand currently.

**Comment by Tontonitch** [comment]
Not sure this is what you're requesting for: in the NSCP Web UI, with dev tools I can see
`https://localhost:8443/query/check_cpu?time=1m&time=5m&time=15m`

**Comment by dnsmichi** [comment]
Yep. check_nscp_api sends `time[]=1m&time[]=5m&time[]=15m` which then fails, I guess. Can you test this URL parameters too in your environment?

**Comment by dnsmichi** [comment]
Url::Format() would need to know whether it should print `[]` for arrays or not.

**Comment by Crunsher** [comment]
Yup, should be a simple enough change methinks. Using is `[]` for arrays is common but no rule.

**Comment by dnsmichi** [comment]
The Graylog REST API doesn't like that either. Repeating keys is sometimes not implemented, and you are forced into "strange" formats.

As for this issue, the Url::Format() function would need to know how to handle array formats. Does it qualify for the next boolean parameter, or are we up to a more generic approach?

**Comment by Crunsher** [comment]
I doubt a generic approach exists :G

**Comment by dnsmichi** [comment]
I don't mind. Should be fixed in 2.9 then, with possible backport candicates.

**Comment by Tontonitch** [comment]
I've checked if for my case I could simply change some default values inside the nscp config, but it seems to be not possible. See: https://docs.nsclient.org/checks/#implicit-defaults
So the use of the repeated "time" option is still the only way of changing this "default" check_cpu settings.

**Comment by Tontonitch** [comment]
I've finally found a workaround, using an alias in the NSCP external scripts feature:

Activated the CheckExternalScripts module:
`nscp settings --activate-module CheckExternalScripts --add-defaults`

Added the following alias in the [/settings/external scripts/alias] config part of the main config file:
`alias_cpu_ex = check_cpu time=1m time=5m time=15m "warn=$ARG1$" "crit=$ARG2$" show-all`

Now I can launch check_cpu with my custom time config:

```
C:\Program Files\ICINGA2\sbin>check_nscp_api.exe -H localhost --password xxx
S -q alias_cpu_ex -a "(load>80 and time not in ('1m','5s'))" -a "(load>90 and ti
me not in ('1m','5s'))"
check_cpu OK: 1m: 80%, 5m: 16%, 15m: 5% | 'total 1m'=80%;80;90 'total 5m'=16%;80
;90 'total 15m'=5%;80;90
```

For info, there is a bug with check_cpu which doesn't return performance data when specifying warn AND crit options.
It affects any queries using check_cpu, not only when changing the time option. So lots of users should be impacted. The bug is reported there: https://github.com/mickem/nscp/issues/499

```
C:\Program Files\ICINGA2\sbin>check_nscp_api.exe -H localhost --password xxxx
S -q check_cpu -a warn=80
check_cpu CRITICAL: 5s: 93% | 'total 5m'=62%;0;90 'total 1m'=80%;0;90 'total 5s'
=93%;0;90

C:\Program Files\ICINGA2\sbin>check_nscp_api.exe -H localhost --password xxxx
S -q check_cpu -a warn=80 -a crit=90
check_cpu OK: CPU load is ok. |

C:\Program Files\ICINGA2\sbin>check_nscp_api.exe -H localhost --password xxxx
S -q check_cpu -a warn=80 -a crit=90 -a show-all
check_cpu OK: 5m: 75%, 1m: 78%, 5s: 87% |
```

For that, I've found a workaround, using "complex" warn/crit:

```
C:\Program Files\ICINGA2\sbin>check_nscp_api.exe -H localhost --password xxxx
S -q check_cpu -a "warn=(load>80)" -a "crit=(load>90)" -a show-all
check_cpu WARNING: warning(1m: 82%, 5s: 86%), 5m: 75% | 'total 5m'=75%;80;90 'to
tal 1m'=82%;80;90 'total 5s'=86%;80;90
```

**Comment by santuari** [comment]
We are facing a strange behavior to check the CPU usage using the NSCP, but I do not know if this is related to this bug. 
The command in the Icinga2/Director is:

```
command: [
        "C:\\Program Files\\NSClient++\\nscp.exe",
        "client",
        "--critical",
        "load>90",
        "--log",
        "critical",
        "--module",
        "CheckSystem",
        "--show-all",
        "--time",
        "1m",
        "--time",
        "5m",
        "--time",
        "15m",
        "--warning",
        "load>80",
        "-b",
        "-q",
        "check_cpu"
      ]
```
It works but returns always values of 0.

If we run the command command locally (i.e., `C:\\Program Files\\NSClient++\\nscp.exe client --critical load>90 --log critical --module CheckSystem --show-all --time 1m --time 5m --time 15m --warning load>80 -b -q check_cpu`), the result is the same: values = 0.

At the contrary, the nscp_api (i.e., `C:\Program Files\ICINGA2\sbin> .\check_nscp_api.exe -H localhost --password password S -q check_cpu -a "warn=(load>80)" -a "crit=(load>90)"`) provides correct values.

**Comment by Tontonitch** [comment]
This is not related.

You cannot use the commands based on "nscp.exe client" to monitor cpu (nscp-local-cpu) or other metrics based on counters delta calculations. (https://forums.nsclient.org/t/check-cpu-showing-wrong-values-when-called-by-icinga-2-agent/3777)

So, forget nscp-local-cpu which produces incorrect results, and go for the NSCP API (check_nscp_api) or my way of monitoring via NSCP https://github.com/Icinga/icinga2/pull/5883 (https://monitoring-portal.org/woltlab/index.php?thread/42526-use-of-check-nrpe-exe-provided-by-nscp-with-the-icinga2-client/)
