### ISSUE TITLE
Extend Icinga check parameters and performance data

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icinga2#5712]
## Expected Behavior
Performancedata offers Icinga Version as output and an parameter offers to set an exspected version. if version does not match, the check is critical.

## Current Behavior
feature not present, but version is alsready checked

## Possible Solution
up to dev team

## Steps to Reproduce (for bugs)
n/a

## Context
Running statistics about the used version and forcing version upgrade/finding missed nodes made easy

## Your Environment
Icinga2 v2.7.1-1

**Comment by dnsmichi** [comment]
- Performance data cannot hold string values, but only floating point values. `v2.7.1` does not match here.
- The state should be changed, if the version is too old - we already have an issue for that in #3998
