### ISSUE TITLE
Problematic interaction between Downtime/Flapping and Notifications

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#5713]
There is currently an edge cases after Downtimes and Flapping where Notifications are sent out or not sent out the way they are supposed to.

The following behavior I could observe:
1. Host OK
2. Downtime/flapping start
3. Host critical
4. Downtime/flapping end -> No problem notification
6. Host OK -> Recovery notification

There have been other issues about this or similar problems (#4427, #4662, #5318). The notification handler needs to be looked over and streamlined to avoid such things in the future.

**Comment by dnsmichi** [comment]
Since there's a notification feature review ticket already, I'll close this.

**Comment by julianbrost** [comment]
For anyone else looking at this for some reason, "notification feature review ticket" probably is #7161
