### ISSUE TITLE
Influxdb writer using absolute path in writes

### ISSUE THREAD

**Issue by jarttori** [Icinga/icinga2#5726]
It is a best practice to use relative file paths (if possible).

To allow for transition to absoluteURIs in all requests in future versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI form in requests, even though HTTP/1.1 clients will only generate them in requests to proxies.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html

Correct post (telegraf agent):
```
POST /write?consistency=any&db=xxx HTTP/1.1
Host: perfdbvip.xxx.xxx.xxx:8080
Transfer-Encoding: chunked
Authorization: Basic a3VuZHVzZXI6a3VuZDEjdXMzcg==
Content-Type: text/plain
Accept-Encoding: gzip
```

Incorrect post (icinga2):
```
POST http://perfdbvip.xxx.xxx.xxx:8080/write?db=xxx&p=<>>&precision=s&u=ic
HTTP/1.1
host: perfdbvip.xxx.xxx.xxx:8080
transfer-encoding: chunked
user-agent: Icinga/r2.7.1-1
```

## Expected Behavior
```
/write?db=xxx&p=<>>&precision=s&u=ic
```

## Current Behavior
```
http://perfdbvip.xxx.xxx.xxx:8080/write?db=xxx&p=<>>&precision=s&u=ic
```

## Possible Solution
Use relative paths

## Steps to Reproduce (for bugs)
Enable influxdbwriter
Capture tcpdump and view the content with wireshark

## Context

We're using Icinga2 HA cluster with influxdb cluster combined with influxdb-relay for performance data.

https://github.com/influxdata/influxdb-relay

There is a F5 VIP infront of the influxdb cluster listening port 8080 with iRule:

```
/query redirected to backend port 8086
/write redirected to influxdb-relay port 9096
```

Currently has to be done with:

```
when HTTP_REQUEST {    switch -glob [HTTP::path] {       
"/write*" -        
"http://perfdbvip.xxx.xxx.xxx:8080/write*" 
{            pool test-perfdb-write-pool        }        
"/query*" -        
"http://perfdbvip.xxx.xxx.xxx:8080/query*" 
{            pool test-perfdb-query-pool        }        
```

If using other agents are also inserting data to influxdb this causes unnecessary work with network equipment.

"/write*" and "/query*" for all the other agents and absolute paths for icinga2

## Your Environment

icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)
InfluxDB shell version: 1.3.6

**Comment by gunnarbeutner** [comment]
Looks like we previously came across that problem while working on the elasticsearch feature. This was fixed as part of #5558 which is scheduled to be included in 2.8.
