### ISSUE TITLE
Source builds of release 2.7.2

### ISSUE THREAD

**Issue by cschug** [Icinga/icinga2#5737]
Looks like compiling release 2.7.2 from source requires one the setup a file like
```
echo '#define VERSION "r2.7.2-1"' >icinga-version.h.force
```
in order to unbreak the build. Otherwise `cmake` fails with
```
CMake Error at CMakeLists.txt:89 (string):
  string sub-command SUBSTRING requires four arguments.
```
The removal of the `icinga2.spec` file from the source tree might be to root cause ... or at least the release version cannot be extracted from that file any longer.

**Comment by gunnarbeutner** [comment]
Works for me. Please include information about your build environment so we can try to reproduce this.

**Comment by cschug** [comment]
I am compiling in a minimalistic chroot'ed environment using the release tarball (downloaded per `wget --content-disposition https://github.com/Icinga/icinga2/archive/v2.7.2.tar.gz`), i.e. no git clone of the source and no `git` command in place, therefore also the logic included as `GetGitRevisionDescription` does not have any effect.
With the `icinga2.spec` being just a dummy file now in 2.7.2, also the fallback logic at https://github.com/Icinga/icinga2/blob/v2.7.2/CMakeLists.txt#L86 doesn't seem to have effect.

**Comment by dnsmichi** [comment]
Thanks for letting us know. We'll take care for 2.8, please use your mentioned workaround meanwhile.

**Comment by gunnarbeutner** [comment]
Can you try this again with the new tarball (same URL)?

**Comment by cschug** [comment]
Thanks, I can confirm that the updated 2.7.2 release tarball (MD5 checksum  4a54675f23aaea4d554af81a0754cc55) containing following change compared to the original release tarball (MD5 checksum 506173d8c7cdcbcbb967c475051cd875)
```
--- icinga2.spec 2017-11-09 12:37:19.000000000 +0100
+++ icinga2.spec 2017-11-09 13:44:36.000000000 +0100
@@ -19,4 +19,5 @@
 
 # The spec file was moved to https://github.com/Icinga/icinga-packaging
 
+%define revision 1
 Version: 2.7.2
```
fixes the build, too. From release engineering point of view maybe not the sweetest solution to re-release with the same version number, but the fix actually does the job.

**Comment by dnsmichi** [comment]
Normally we wouldn't do it, but the release was still going on, and not yet publicly announced. So bear with us doing this quick fix :)

**Comment by cschug** [comment]
No worries, rather many thanks for the quick fix :-) From my point of view the issue is resolved and can be closed
