### ISSUE TITLE
How to add a client node when master is behind a firewall ?

### ISSUE THREAD

**Issue by lewer** [Icinga/icinga2#5751]
Hi,

I want to monitor a few servers. Some of them are accessible from the Internet, others are behind a firewall and I can't open port 5665. My master node is behind the firewall, and I'm trying to install a client node which is outside the firewall. The installation command 
```
icinga2 node setup --ticket $ticket --endpoint $icinga2_master --zone $fqdn --master_host $icinga2_master --trustedcert $pki_dir/trusted-master.crt  --accept-config --accept-command 
```
hangs at step "information/cli: Requesting a signed certificate from the master." (of course it cannot connect to the master)

Is there a way to manually sign a certificate on the master and transfer it to the client ? Otherwise, is there another solution for what I'm trying to do ?

Thanks.

**Comment by dnsmichi** [comment]
That question should be put into community support channels rather than this bug tracker. You didn't fill in the issue template either.

Here's a reference docs URL to start with: https://www.icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#manual-certificate-creation

**Comment by bobsheybani** [comment]
i have the same issue , i have hosts which are only accessible from https and i can not monitor them. i know solution is passive check but doesnt works. anybody can help me ???

**Comment by mcktr** [comment]
@bobsheybani the issue tracker is not the right place for such questions. Instead, please join https://community.icinga.com/ where you can ask such questions.
