### ISSUE TITLE
Graphite Performance Writer refusing to write custom perfdata

### ISSUE THREAD

**Issue by fir3wall** [Icinga/icinga2#5756]
## Expected Behavior
In my custom script I'm throwing my own perfdata by utilizing python code:
```
print '%s|%s' % (info, out)
where info = 'Everything is OK!'
and out = block_secs=0.0000 (%f in python)
```
I would like to write this perfdata to Graphite as for example icinga2.my_host.services.my_service.value

This, however, does not work 
## Current Behavior
Error in icinga2 file:
```
warning/GraphiteWriter: Ignoring invalid perfdata value: block_secs=0.000000, Context ...
```
Please note that I've always passing just label=value, simples combination ever (no unit [always float], no tresholds etc. 

Please also note that IcingaWeb2 displaying performance data corretly (Label block_secs, Value 0.00)

## Possible Solution
Don't know 

## Context
I'm trying to populate data from my custom check to Graphite and all what I'm doing is 'my_fancy_message'|my_label=0.00000

## Your Environment
* Version used: r2.7.2-1
* Operating System and version: Centos 7 (clean install after yum update)
* Enabled features (`icinga2 feature list`): api, checker, command, compactlog, graphite, ido-mysql, mainlog, notification, status data
* Icinga Web 2 version and modules (System - About): 242
* Config validation (`icinga2 daemon -C`): Passing trhough

**Comment by gunnarbeutner** [comment]
Can you please include an unabbreviated copy of your plugin's output (on stdout)?

**Comment by fir3wall** [comment]
Hello,
Apologies for trouble found issue - this comma that is on end of my perfdata was thinking this is actual log message separator ... turns out my python code is adding it. Removing it set perfdata correctly and it's now propagated.
