### ISSUE TITLE
Hardcoded dependecies limit to 20

### ISSUE THREAD

**Issue by factor-lg** [Icinga/icinga2#5762]
Hello
As it turned out, Icinga2 has a constraint on dependencies. The problem is that if there are more than 20 hosts in the chain of dependencies, then warning message " Too many nested dependencies for service 'xxx': Dependency failed." is writen to logfile and the active checks are not work for this hosts.

I found this limit in the code of **icinga2/lib/icinga/checkable-dependency.cpp**

```
bool Checkable::IsReachable(DependencyType dt, Dependency::Ptr *failedDependency, int rstack) const
{
	if (rstack > 20) {
		Log(LogWarning, "Checkable")
		    << "Too many nested dependencies for service '" << GetName() << "': Dependency failed.";

		return false;
	}
```

I actually have a network of 20+ parent hosts in the network configuration.
I propose to make this limit configurable through config file.

**Comment by dnsmichi** [comment]
I'd like to see the configuration. This sounds really odd to have more than 20 dependency layers.

**Comment by factor-lg** [comment]
The question is not in the configuration, but in building the network. We have chains of L2 switches connected in series and in some places the length of the chain exceeds 20 pieces

**Comment by dhooper6430** [comment]
I've got exactly the same problem, and have been banging my head on the desk with dependency problems until I found this issue, I agree it should be a configurable option.

**Comment by dnsmichi** [comment]
Propose a sane value please. A configuration option is a no-go here.

**Comment by apersonnaz** [comment]
Hi,
30 would be a working value for us.
Thanks!

**Comment by dnsmichi** [comment]
Well, but likely not for others. I won't change this to 30 and later to 50, you'll get my point hopefully.

**Comment by dnsmichi** [comment]
```
var child_host = "hc"

object Host child_host {
  check_command = "dummy"
}

for (i in range(1025)) {
  var parent_host = "hp" + i

  object Host parent_host {
    check_command = "dummy"
  }
  object Dependency "dp" use (parent_host, child_host) {
    parent_host_name = parent_host
    child_host_name = child_host
  }

  child_host = parent_host
}
```

**Comment by cberg2048** [comment]
I believe that 20 is a perfectly sane number. Especially considering that the maximum number of hops recommended in the [IEEE 802.1D](https://en.wikipedia.org/wiki/IEEE_802.1D) (switching and bridges) standard is 7. There is an interesting article on this [here](http://slaptijack.com/networking/max-spanning-tree-stp-diameter/) and tons of Cisco forum posts.

**Comment by Thomas-Gelf** [comment]
@cberg2048: that's technically a valid statement, but 802.1D has been written 30 years ago. People might want use Icinga to model systems spanning many layer 3 devices with a couple of layer 2 devices between them. Layer 2 itself evolved, VTP domains have been a thing 20 years ago and as of today even very cheap (managed) switches support MSTP.

Layer 3 has it's own considerations when it comes to hop limits, but it doesn't stop there. Dependencies might travel virtualization platforms for the network layer (MPLS) or your Server platforms. Imagine your VCenter, Host Systems, Virtual Machines and Applications running in Containers in those VMs. Dependencies could involve storage components or physical facilities.

You'll reach the limits of an Icinga system pretty fast when trying to model every leaf of every tree in your forest. Still, Icinga as a generic monitoring system shouldn't be too strict and allow for some creativity.

Cheers,
Thomas

**Comment by factor-lg** [comment]
I agree with Thomas!
We use MSTP, his limit is 40 hops, and core switch for this circuit maybe a part of network topology with XX hops to him.
I think limit in 256 hops will give enough freedom.

**Comment by dnsmichi** [comment]
Anything greater than 256 causes stack errors btw.
