### ISSUE TITLE
Check_oracle_health error

### ISSUE THREAD

**Issue by ManriqueGarcia** [Icinga/icinga2#5766]
cannot connect to ORABIPRO. install_driver(Oracle) failed: Can't load '/usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libclntsh.so.12.1: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190.
at (eval 13) line 3.
Compilation failed in require at (eval 13) line 3.
Perhaps a required shared library or dll isn't installed where expected
 at /usr/lib64/nagios/plugins/check_oracle_health line 6155.

## Expected Behavior

th check_oracle_health don't run in icinga2 but runs ok in console 

## Steps to Reproduce (for bugs)

1. Create a services for Oracle monitoring
apply Service "asm-disk-usage-" for (ddbb => config in host.vars.siddb) {
import "generic-service"
check_command = "oracle_health"

vars +=config

assign where host.vars.os == "Exadata-scan"
vars.oracle_health_connect = vars.DBSID
vars.oracle_health_username = userdb
vars.oracle_health_password = passdb
vars.oracle_health_mode = "asm-diskgroup-usage"

}
2. If I execute the command from command line with user icinga it's ok

-bash-4.2$ /usr/lib64/nagios/plugins/check_oracle_health --connect EDBIMUPA --username OCCAM_CONTROL --password QEimpC2j --mode enqueue-contention
CRITICAL - enqueue UL User-defined Locks: 33.33% of the requests must wait , enqueue TD : 33.33% of the requests must wait , enqueue TA Transaction Recovery: 50.00% of the requests must wait , enqueue PS Parallel Slave Synchronization: 17.95% of the requests must wait , enqueue JQ Job Queue: 100.00% of the requests must wait , enqueue TT Temporary Table: 9.80% of the requests must wait , enqueue ZH : 0.00% of the requests must wait 
........
3. ENV it's ok

-bash-4.2$ env
XDG_SESSION_ID=1
HOSTNAME=agmnag01
SHELL=/bin/bash
TERM=xterm
HISTSIZE=1000
http_proxy=http://dmanriqu:Dm04092017@10.110.8.42:8080
USER=icinga
LD_LIBRARY_PATH=/home/oracle/app/oracle/product/12.1.0/client_2/lib
..................
ORACLE_HOME=/home/oracle/app/oracle/product/12.1.0/client_2
....

4.

## Context

I'm trying to check Oracle but I have this issue 

## Your Environment

* Version used (`icinga2 --version`):  The Icinga 2 network monitoring daemon (version: r2.7.1-1)
* Operating System and version: Centos 7.4
* Enabled features (`icinga2 feature list`): api checker command graphite ido-mysql mainlog notification

* Icinga Web 2 version and modules (System - About): 

businessprocess | 2.1.0
director | master
doc | 2.4.2
monitoring | 2.4.2
translation | 2.4.2

* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.7.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: agmnag01
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule '' (in /etc/icinga2/conf.d/services.conf: 65:1-65:53) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Diskspace ' (in /etc/icinga2/conf.d/services.conf: 118:1-118:66) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 46 Notifications.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 214 CheckCommands.
information/ConfigItem: Instantiated 2 Downtimes.
information/ConfigItem: Instantiated 4 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 8 Hosts.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 64 Services.
information/ConfigItem: Instantiated 4 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
[root@agmnag01 conf.d]#

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
check_oracle_health is a plugin, and not related to Icinga 2 nor this bug tracker. Please ask your question on the community channels.

**Comment by ManriqueGarcia** [comment]
sorry but I think is a icinga bug because the environment vars don't run
well

thanks

On Wed, Nov 15, 2017 at 7:00 PM, Michael Friedrich <notifications@github.com

**Comment by dgoetz** [comment]
Icinga 2 cleans up the environment  and send environment variables to scripts only if you configure them. Oracle does not configure shared libraries in a good way and tells people to use environment variable for loading them to allow usage of multiple versions of the client tools. So the problem is indeed your configuration or the way Oracle is doing its stuff.

I recommend creating a configuration file for ldconfig as monitoring wont need multiple versions on the libraries. I typically create a file /etc/ld.so.conf.d/oracle-x86_64.conf with the following content (depending on the version and path installed):

```
/usr/lib/oracle/12.1/client64/lib/
```

And run `ldconfig` afterwards to activate the configuration. You can verify if the libraries can now be found with `ldd` run against the library or tool using it.

**Comment by KAMI911** [comment]
I would like to fix it with PR: #5805
