### ISSUE TITLE
Unable to pass notification.times.begin as a function value through = or += operator

### ISSUE THREAD

**Issue by yoshi314** [Icinga/icinga2#5771]
I have a following example : 

in a Host object : 
```
  vars.all_services.notification.times.begin = {{
      if (get_time_period("workhours").is_inside) {
        return 15m
      } else { 
        return 0
      }
    }}
```

In service template : 
```
  if (host.vars.all_services) {
    vars += host.vars.all_services
  }
```

in Notification template:

```
  if (service.vars.notification.times) {
    times = service.vars.notification.times
  }
```

This fails with error, most recent i had was 

```
critical/config: Error: Validation failed for object 'asterisk!check-snmp-memory!service-by-mail-v2' of type 'Notification'; Attribute 'times' -> 'begin': Invalid type.
```

So i altered it to be like this:

```
  vars.all_services.notification.times = {
     begin = {{
       if (get_time_period("workhours").is_inside) {
        return 15m
      } else { 
        return 0
      }
    }}
    }

```

And this also fails.

I also tried directly accessing elements of notification.times dictionary, to no avail : 
```
  if (service.vars.notification.times.begin) {
    times.begin = service.vars.notification.times.begin
  }

  if (service.vars.notification.times.end) {
    times.end = service.vars.notification.times.end
  }
```

Still getting the same error. 

It would seem i cannot have dynamic notification.times assignment . Setting times.begin to static 15m fixes all problems. Perhaps the problem is that the function is in service template?

This is with icinga-2.7.2 on debian jessie, official packages.

**Comment by dnsmichi** [comment]
You are doing forbidden things here. Runtime lamdba functions are only allowed for a defined scope, e.g. custom attributes. You cannot use such to modify object attributes such as `times`.

Still, such a question should be put on the community channels instead of this issue tracker.
