### ISSUE TITLE
Duplicate key name 'idx_downtimehistory_remove' Upgrade 2.7.2-1.trusty to 2.8.0-1.trusty

### ISSUE THREAD

**Issue by localguru** [Icinga/icinga2#5778]
## Expected Behavior

no Duplicate key name error when upgrading

## Current Behavior

When upgrading from from 2.7.2-1.trusty to 2.8.0-1.trusty I get the following error:

```
creating database backup in /var/cache/dbconfig-common/backups/icinga2-ido-mysql_2.7.2-1.trusty.mysql.
applying upgrade sql for 2.7.2-1.trusty -> 2.8.0.
error encountered processing /usr/share/dbconfig-common/data/icinga2-ido-mysql/upgrade/mysql/2.8.0:
mysql said: ERROR 1061 (42000) at line 68: Duplicate key name 'idx_downtimehistory_remove'
Es ist ein Fehler beim Upgrade der Datenbank aufgetreten:

mysql said: ERROR 1061 (42000) at line 68: Duplicate key name 'idx_downtimehistory_remove'

Glücklicherweise enthält /var/cache/dbconfig-common/backups/icinga2-ido-mysql_2.7.2-1.trusty.mysql ein Backup der Datenbank, das unmittelbar vor dem Upgrade erstellt wurde.
```

## Steps to Reproduce (for bugs)

1. just `aptitude save-upgrade`

## Your Environment

* Version used (`icinga2 --version`): 2.7.2 (before upgrade to 2.8.0)
* Operating System and version: Ubuntu 14.04 LTS
* Enabled features (`icinga2 feature list`): checker command compatlog ido-mysql mainlog notification perfdata statusdata
* Icinga Web 2 version and modules (System - About): Version 2.4.2, monitoring 2.4.2, pnp4nagios 0.0.0
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
That's probably the long lasting issue with Debian's dbconfig-common running the SQL upgrade twice. Please looking into icinga/icinga-packaging if an issue exists, or open a new one over there. There's nothing we can do about Debian packaging here. Thanks.
