### ISSUE TITLE
Upgrading to icinga2 is failing to find the my certs

### ISSUE THREAD

**Issue by paladox** [Icinga/icinga2#5779]
Hi, when i tryed upgrading to icinga2 i am getting this error

Nov 19 13:41:04 gerrit-mysql icinga2[21489]: [2017-11-19 13:41:04 +0000] critical/SSL: Error on bio X509 AUX reading pem file '/var/lib/icinga2/certs//gerrit-mysql.git.eqiad.wmflabs.crt': 33558530, "error:02001002:system library:fopen:No such file or directory"
Nov 19 13:41:04 gerrit-mysql icinga2[21489]: [2017-11-19 13:41:04 +0000] critical/config: Error: Cannot get certificate from cert path: '/var/lib/icinga2/certs//gerrit-mysql.git.eqiad.wmflabs.crt'.

My open source config is at https://github.com/wikimedia/labs-icinga2

## Expected Behavior

It to start icinga2 correctly and for it to find the new certs directory correctly.

## Current Behavior

failing with

Nov 19 13:41:04 gerrit-mysql icinga2[21489]: [2017-11-19 13:41:04 +0000] critical/SSL: Error on bio X509 AUX reading pem file '/var/lib/icinga2/certs//gerrit-mysql.git.eqiad.wmflabs.crt': 33558530, "error:02001002:system library:fopen:No such file or directory"
Nov 19 13:41:04 gerrit-mysql icinga2[21489]: [2017-11-19 13:41:04 +0000] critical/config: Error: Cannot get certificate from cert path: '/var/lib/icinga2/certs//gerrit-mysql.git.eqiad.wmflabs.crt'.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`): 2.8.0
* Operating System and version: debian stretch 9.2
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification perfdata syslog
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by paladox** [comment]
Directory seems it was not auto created

root@gerrit-mysql:/etc/icinga2/conf.d# ls -la /var/lib/icinga2/certs/
ls: cannot access '/var/lib/icinga2/certs/': No such file or directory

**Comment by mcktr** [comment]
During the update process did you override the file `/etc/icinga2/features-available/api.conf` with the new version? 

If so, Icinga can't find the certificates and will not migrate them to the new directory `/var/lib/icinga2/certs/`. The directory should be created during the migration.

**Comment by paladox** [comment]
Oh nope.

**Comment by mcktr** [comment]
Can you please show me your content of `/etc/icinga2/features-available/api.conf`.

What also should work is to copy the certificates by hand from `/etc/icinga2/pki/` to `/var/lib/icinga2/certs/`.

**Comment by paladox** [comment]
Yep thanks, i copied it manually :).

Also in /etc/icinga2/features-available/api.conf

it shows

```
/**
 * The API listener is used for distributed monitoring setups.
 */

object ApiListener "api" {
  //accept_config = false
  //accept_commands = false

  ticket_salt = TicketSalt
}
```

**Comment by dnsmichi** [comment]
That's the culprit - if "cert_path" and so on are not configured, Icinga 2 assumes you are running v2.8 already (those attributes are required in older versions). 

Therefore no "copy-in-place" event takes place, and your certificates in /etc/icinga2/pki remain untouched. You need to ensure that your gerrit script (or any other automation tool) puts the certificates in /var/lib/icinga2/certs already.

**Comment by dnsmichi** [comment]
I assume you've fixed the problem by copying the certificates, so closing here :)

**Comment by TinajaLabs** [comment]
This is from a long time ago, I know, but I'm having a similar issue...

I note that the original error above shows this path:

`/var/lib/icinga2/certs//gerrit-mysql.git.eqiad.wmflabs.crt`

which includes 2 back-slashes.

My setup seems similar in that it is looking here:

`/var/lib/icinga2/certs//ca.crt`

It is the same for the fqdn cert files.  What could be generating the double back-slash?

Thanks for any tips,
Chris.

**Comment by dnsmichi** [comment]
The code, which doesn't sanitize this. OSes don't care here, this is totally valid.

Please use https://community.icinga.com for this kind of questions instead of bumping closed issues.

**Comment by TinajaLabs** [comment]
Ok.  Apologies and thank you.
