### ISSUE TITLE
Error after upgrading (Debian)

### ISSUE THREAD

**Issue by crafter999** [Icinga/icinga2#5782]
I'm getting the following error after I upgraded to the latest version of icinga2 (r2.8.0-1) using apt on a Debian 9 system. I'm wondering why is there a double slash on the cert path?
```
...
critical/SSL: Error with private key file '/var/lib/icinga2/certs//master.key': 33558530, "error:02001002:system library:fopen:No such file or directory"
critical/config: Error: Cannot make SSL context for cert path: '/var/lib/icinga2/certs//master.crt' key path: '/var/lib/icinga2/certs//master.key' ca path: '/var/lib/icinga2/certs//ca.crt'.
Location: in /etc/icinga2/features-enabled/api.conf: 1:0-1:23
/etc/icinga2/features-enabled/api.conf(1): object ApiListener "api" {
...
```

**Comment by dnsmichi** [comment]
Seems you've adopted your api.conf to not set "cert_path" and so on anymore. This has been asked a couple of times now, therefore closing. Head over to monitoring-portal.org for more discussions on the topic.

Prior to ANY upgrade, you should read the release announcements and upgrade docs.

https://www.icinga.com/2017/11/17/icinga-2-v2-8-0-released/
https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/

Manual certificate path migration is described in there as well.

**Comment by crafter999** [comment]
OK thanks. I just thought Icinga2 was failing because of that double slash

**Comment by dnsmichi** [comment]
Linux and Windows do understand that, it's more cosmetic. 

This is explained here as well: https://monitoring-portal.org/index.php?thread/42395-icinga2-update-error/&postID=258894#post258894
