### ISSUE TITLE
feature/Api-Icinga2-programm-version

### ISSUE THREAD

**Issue by kobmaki** [Icinga/icinga2#5784]
With this feature it will be possible to gather information which icinga2 daemon/satellite is running. It helps in finding machines where icinga2 requires an update.

## Expected Behavior
When connection to Api-Listener the remote Icinga2 running version should be shown by a an api command.

## Current Behavior
There is no possiblity to get the remote running icinga2 version via api.

## Possible Solution
Implement a function or a constant that shows the running icinga2 version.

Example here an example against an with environment set for icinga2 user and password.  The remote icinga2 daemon  (r2.8.0-1) is a self compiled version with the patch:

```
root@kob-deb:~# icinga2 console --connect https://localhost:8665
Icinga 2 (version: v2.8.0-5-gdf10d2a29)
<1> => Version
"r2.8.0-1"
<2> =>
```

A patch look like
```
diff --git a/lib/base/scriptutils.cpp b/lib/base/scriptutils.cpp
index f71b1b869..289002e52 100644
--- a/lib/base/scriptutils.cpp
+++ b/lib/base/scriptutils.cpp
@@ -30,6 +30,7 @@
 #include "base/application.hpp"
 #include "base/dependencygraph.hpp"
 #include "base/initialize.hpp"
+#include "icinga-version.h"
 #include <boost/regex.hpp>
 #include <algorithm>
 #include <set>
@@ -88,6 +89,7 @@ void ScriptUtils::StaticInitialize(void)
 
 	ScriptGlobal::Set("GlobFile", GlobFile);
 	ScriptGlobal::Set("GlobDirectory", GlobDirectory);
+	ScriptGlobal::Set("Version",VERSION);
 }
 
 String ScriptUtils::CastString(const Value& value)
```

## Your Environment

* Version used Icinga 2 (version: r2.8.0-1)
* Operating System and version: debian stretch

**Comment by dnsmichi** [comment]
- Should use Application::GetAppVersion()
- Should be added to the IcingaApplication object

**Comment by gunnarbeutner** [comment]
Turns out we actually already have that. Well, at least the API part:

```
$ curl -s -k -u root:04b43fbcbe0cae48 -H 'Accept: application/json' https://localhost:5665/v1 | python -mjson.tool
{
    "results": [
        {
            "info": "More information about API requests is available in the documentation at https://docs.icinga.com/icinga2/latest.",
            "permissions": [
                "*"
            ],
            "user": "root",
            "version": "v2.8.0-24-g8dd7eebf7"
        }
    ]
}
```

I'm all for adding a constant though. However that should happen in libbase IMO.

**Comment by kobmaki** [comment]
When connected to the API, there is already a constant for the ApplicationType.
<pre>
Icinga 2 (version: r2.8.0-1)
<1> => ApplicationType
"IcingaApplication"
<2> => typeof(ApplicationType).name;
"String"
</pre>

If you search for ApplicationType in the repo:

https://github.com/Icinga/icinga2/search?q=ApplicationType

you find two files where **ScriptGlobal** is called for setting the value for ApplicationType.

So it makes sense to set the Version as **ApplicationVersion**. In this case the file icingaapplication.cpp might be the right position.

The patch in this case could looks like:
<pre>
diff --git a/lib/icinga/icingaapplication.cpp b/lib/icinga/icingaapplication.cpp
index ef7354393..4fce3db1f 100644
--- a/lib/icinga/icingaapplication.cpp
+++ b/lib/icinga/icingaapplication.cpp
@@ -34,6 +34,7 @@
 #include "base/initialize.hpp"
 #include "base/statsfunction.hpp"
 #include "base/loader.hpp"
+#include "icinga-version.h"
 
 using namespace icinga;
 
@@ -61,6 +62,7 @@ void IcingaApplication::StaticInitialize(void)
        ScriptGlobal::Set("NodeName", node_name);
 
        ScriptGlobal::Set("ApplicationType", "IcingaApplication");
+       ScriptGlobal::Set("ApplicationVersion", VERSION);
 }
 
 REGISTER_STATSFUNCTION(IcingaApplication, &IcingaApplication::StatsFunc);
</pre>

On the API (console) you see:
<pre>
Icinga 2 (version: r2.8.0-1)
<1> => ApplicationVersion 
"r2.8.0-1"
<2> => 
</pre>

If the version is in the API available, you can easy add a check that takes care about the versions.
An example to compare the versions on API with bool, where X is the an Endpoint version and AppicationVersion is the Version of the Master:
<pre>
Icinga 2 (version: r2.8.0-1)
<1> => ApplicationVersion
"r2.8.0-1"
<2> => X="r2.8.0-0"
null
<3> => bool(X>ApplicationVersion);
false
<4> => bool(ApplicationVersion>X);
true
<5> => 
</pre>
The use case is to add an check to see if all nodes have a required/correct/supported version. The check_dummy is the best way to do this, after the cool new dummy check in https://github.com/Icinga/icinga2/issues/5740 is available in the master branch.

**Comment by gunnarbeutner** [comment]
Note that the '>' operator does a textual comparison, e.g. "2.8.10" would be less than "2.8.5". We do have a function for that though: Utility::CompareVersion.

I'm OK with naming the variable 'ApplicationVersion', however I think it should be set in libbase because it also automatically is the version for all other supported application types (which, arguably... is not that important right now because there's only libicinga and libhello).

**Comment by gunnarbeutner** [comment]
Can you submit a PR for this, maybe even with a new function for version comparisons (compare_version?). 😊

**Comment by kobmaki** [comment]
I try for a pull-request, but takes some time. The PR should contains the documentation ;-)

The function CompareVersion should only be used for icinga version comparision.

- A version string starts with an "r" or and "v"
- Fields are seperated by "."
- If a field contains "-", it can be split in subfield by "-"
- Fields/subfield with either number or letters are compareable
- Fields/subfield are compared by ">"
- Mixed fields can not be compared (think of git version)

Is this starting definition for compare the version OK?

**Comment by dnsmichi** [comment]
I've implemented that, since nearly everything was there already. Except for some regex magic which allows to parse a version string. The agreement to leave away snapshot versions was done inside #5958 so `parse_version` as helper next to `compare_version` can sit there.

```
<2> => compare_version(AppVersion, "v2.9.0")
1.000000
<3> => compare_version(AppVersion, "v2.8.0")
-1.000000
<4> => compare_version(AppVersion, "v2.8.1")
0.000000
<5> => AppVersion
"v2.8.1-402-ge1e06ce76"
```

**Comment by dnsmichi** [comment]
Leaving this open as a reminder for a comparison version which does not follow C-style return values (no -1, 0, 1 values).
