### ISSUE TITLE
LUA Script doesn't work in the Icinga2 bundled version of NSClient++

### ISSUE THREAD

**Issue by killepitisch** [Icinga/icinga2#5788]
We have not been able to get LUA scripts running with NSClient++ which is bundled in Icinga2 for Windows 64bit. It is currently latest stable release of the 0.5.0 branch, NSCP-0.5.0.62-x64.

Although all required .DLL files seem to be installed properly, nscp is complaining about a missing LUAScript.dll library. `LUAScript = 1` is set in nsclient.ini.

No issues with NSCP 0.5.1.46 however.

## Expected Behavior

**NSCP 0.5.1.46 x64**

`C:\Program Files\NSClient++>nscp lua`

`Failed to execute script Failed to load script: C:\Program Files\NSClient++\scripts\lua: cannot open
C:\Program Files\NSClient++\scripts\lua: Permission denied`

Don't worry about the error message, this is alright as no script name is mentioned.

## Current Behavior

**NSCP 0.5.0.62 x64**

`C:\Program Files\NSClient++>nscp lua`

`E       core Module (LUAScript) was not found: Could not load library: 126: The specified module could not be found.
: LUAScript.dll
                    c:\source\master\service\NSClient++.cpp:479`
`E       core Module (LUAScript) was not found: Could not load library: 126: The specified module could not be found.
: LUAScript.dll
                    c:\source\master\service\NSClient++.cpp:1035`
`E       core Module (LUAScript) was not found: Could not load library: 126: The specified module could not be found.
: LUAScript.dll
                    c:\source\master\service\NSClient++.cpp:1035`
`Module (LUAScript) was not found: Could not load library: 126: The specified module could not be found.
: LUAScript.dll`
`Command not found:
Module (LUAScript) was not found: Could not load library: 126: The specified module could not be found.
: LUAScript.dll`

## Possible Solution

Bundle NSCP-0.5.1.46-x64 with Icinga 2 Windows package.

## Your Environment

* Icinga Version used: 2.7.2 & 2.8.0 incl. NSClient-0.5.0.62-x64
* Operating System and version: WindowsServer 2008 R2 SP1

**Comment by dnsmichi** [comment]
Thanks for the report. An update is discussed in #5633.
