### ISSUE TITLE
check_nscp_api - often face "Caught exception: Error: Tried to read/write from a closed socket."

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icinga2#5789]
Opening this issue here as I don't know if it could be related to check_nscp_api or NSCP directly.

Using the check_nscp_api  plugin to monitor the cpu usage of windows servers, I can see that the returned result of the service is:
UNKNOWN: Caught exception: Error: Tried to read/write from a closed socket.
![image](https://user-images.githubusercontent.com/600025/33072230-ebc489fe-cebe-11e7-91be-0681e218d749.png)

* I've set the log level of the icinga2 master to debug: I can just see the debug entry reporting the sql statement inserting the service output (among other info):
`[2017-11-20 16:15:40 +0100] debug/IdoMysqlConnection: Query: UPDATE icinga_servicestatus SET acknowledgement_type = '0',  active_checks_enabled = '1',  check_command = 'nscp_api',  check_source = 'xxxx',  check_type = '0',  current_check_attempt = '1',  current_notification_number = '0',  current_state = '3',  endpoint_object_id = 1,  event_handler = '',  event_handler_enabled = '1',  execution_time = '0.422000',  flap_detection_enabled = '1',  has_been_checked = '1',  instance_id = 1,  is_flapping = '0',  is_reachable = '1',  last_check = FROM_UNIXTIME(1511190940),  last_hard_state = '0',  last_hard_state_change = FROM_UNIXTIME(1511187540),  last_state_change = FROM_UNIXTIME(1511190940),  last_time_ok = FROM_UNIXTIME(1511190882),  last_time_unknown = FROM_UNIXTIME(1511190940),  last_time_warning = FROM_UNIXTIME(1510925731),  latency = '0',  long_output = '\\n\\n\\n\\n\\nUNKNOWN: No data received.',  max_check_attempts = '5',  next_check = FROM_UNIXTIME(1511191000),  normal_check_interval = '1',  notifications_enabled = '1',  original_attributes = 'null',  output = 'Caught exception: Error: Tried to read/write from a closed socket.',  passive_checks_enabled = '1',  percent_state_change = '5.900000',  perfdata = '',  problem_has_been_acknowledged = '0',  process_performance_data = '1',  retry_check_interval = '1',  scheduled_downtime_depth = '0',  service_object_id = 8032,  should_be_scheduled = '1',  state_type = '0',  status_update_time = FROM_UNIXTIME(1511190940) WHERE service_object_id = 8032`
To sum up:
output = 'Caught exception: Error: Tried to read/write from a closed socket.'
long_output = '\\n\\n\\n\\n\\nUNKNOWN: No data received.'

* I've set the log level of the icinga2 agent on the related windows server to debug: I can just see the debug entry reporting the check execution. But nothing else.

* I've set the log level of the NSCP agent on the related windows server to "trace": I don't see anything at the times of the issues.

So, is there anything else I can do to troubleshoot this issue? Is it related to check_nscp_api or NSCP?

## Expected Behavior

A valid check output / an answer from NSCP should be received

## Current Behavior

An invalid check output / no answer from NSCP is received

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`): 2.8.0-1 (server), 2.7.2 (client)
* Operating System and version: RHEL 7.4 (server), Windows Server 2012 R2 (client)
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by Crunsher** [comment]
Partially related:
#5633 will require us to rewrite check_nscp_api, it is currently set to 2.9.0

Does not mean we can just ignore this tho ^_^

**Comment by Tontonitch** [comment]
Ok, moreover, I've tested check_nscp_api with NSCP 0.5.2.20, and it doesn't work at all.

But for this issue, I use NSCP 0.5.0.62 which is the one provided with Icinga2. 
Consequently, it seems that using the check_nscp_api to monitor runtime statistics via NSCP, which is the only way to monitor CPU usage correctly on windows servers, is unfortunately not stable yet.

That's a pity. I wanted to secure the communications between the monitoring server and the windows servers, by limiting them to the communications between icinga2 master and agents. And I guess the only possibility to monitor correctly the CPU usage will be to put back the communication channel between icinga2 master and the NSCP service directly.

**Comment by Crunsher** [comment]
Seems that way, in the current version :(

**Comment by dnsmichi** [comment]
Requires a heck of work to upgrade to a new version and check all possible commands and integrations. And of course a rewrite of check_nscp_api to fully support nsclient's api v2.

**Comment by dnsmichi** [comment]
I think this one has been solved with #6242.

**Comment by jgrammen-agilitypr** [comment]
this appears to still be occuring as of version 2.10.2-1

![failing-periodic](https://user-images.githubusercontent.com/22965146/50307248-e0215680-0465-11e9-823a-f0215dd96574.png)
