### ISSUE TITLE
Test whether the elasticsearch feature works with Elasticsearch 6.0

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5801]
Depends on icinga/icinga-vagrant#113

**Comment by lcorsini** [comment]
At the moment it doesn't seems to work, you get a 400 response from the elastic node... it seems to be related to a malformed bulk request

**Comment by Crunsher** [comment]
Nope  #5795

**Comment by dnsmichi** [comment]
Meh. Configuration changes.

https://github.com/elastic/elasticsearch/commit/e9687622bd41b4390c5ace5c8fe20dafbd0cb194#diff-a828b6db7e16f8381bda4916363602bf

Cannot upgrade the Vagrant boxes for now, that requires a transition to Puppet 4/5.

**Comment by dnsmichi** [comment]
Closing this as duplicate of #5795.
