### ISSUE TITLE
icinga2 daemon -c - Cannot validate a conf while icinag2 is running

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [Icinga/icinga2#5802]
I would like to be able to validate a icinag2 configuration offline. While icinag2 is running.
this is particularly useful when doing automated deployments.

## Expected Behavior

be able to run "icinag2 daemon -c filename" and have it return whether the config validates (no syntax errors), even while icinag2 is already running

## Current Behavior

root@host:/etc/icinga2/conf.d# icinga2 daemon -c services.conf
[2017-11-24 10:54:50 -0500] information/cli: Icinga application loader (version: r2.6.3-1)
[2017-11-24 10:54:50 -0500] critical/cli: Another instance of Icinga already running with PID 32723

## Context

I am using puppet to automate my icinga2 configuration deployments, and would like to take advantage of the feature : validate_cmd
To do so a command needs to exist that can take a file name as input and return a 1 if the file has syntax errors and a 0 if it does not.

## Your Environment

* Version used (`icinga2 --version`): r2.6.3-1)
* Operating System and version: ubuntu 16.04
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
Your command lacks the `-C` parameter. You would be starting a new daemon without it.

**Comment by jgrammen-agilitypr** [comment]
If i understand you comment correctly, you are suggesting i run
"icinga2 daemon -C -c services.conf"
my issue with this is that it appears to validate the entire configuration of icinga2 which is not exactly what i am trying to do.

lets pretend i have a working and running icinga2 instance. I now want to deploy a new configuration for  services where i added a single new service to the services.conf file.
My puppet agent deploys the new config file and restarts the icinga2 service. And low and behold the service fails to restart due to a syntax error or typo in the new file.

now if i could take advantage of the puppet "validate_cmd" parameters, i could have the puppet agent verify the new config file has no syntax error in it before it deploy and restarts icinag2.

so the puppet agent sticks the file in a tmp directory and then tries to run the command specified in the validate_cmd parameter, it monitors the return value of that command. If the return value is not 0, it wont deploy the new configuration file.

to make this work I need to be able to run icinga2 daemon -c filename.
filename will be automatically pointed at the temp file by the puppet agent.
so i need a command I can run that will parse a single file and indicate if the file is syntactically correct and error free.

**Comment by dnsmichi** [comment]
You can't just evaluate a config snippet which could depend on other objects. It may be an idea to just parse it for spelling mistakes or object attributes, but not really something else. The config parser does way more than that right now, and therefore needs the entire configuration includes. The idea with partial validation was requested somewhere here already IIRC.

**Comment by jgrammen-agilitypr** [comment]
you are correct that partial validation is not a full validation.
and I am asking for basic spelling and object attribute checking.
a quick search didn't find the ticket about partial validation, but you are correct, I am asking for partial validation.

**Comment by gunnarbeutner** [comment]
You can use `icinga2 console -r <file> --syntax-only` to do that. Note that this really only does a syntax check. A lot of common mistakes (like invalid attribute names, incorrect function names, etc.) will not be detected that way.

```
gunnar@abyss ~ $ icinga2 console -r apply-test.conf --syntax-only 2>/dev/null
Location: in apply-test.conf: 34:35-35:0
apply-test.conf(32): assert(get_host("test").vars.type == "first")
apply-test.conf(33):
apply-test.conf(34): var service = get_service("test", "test)
                                                       ^^^^^^
apply-test.conf(35):

apply-test.conf(36): /* Pretend to submit a check result for the service. */
apply-test.conf(37): service.state_raw = 2 /* CRITICAL */
Unterminated string literal
gunnar@abyss ~ $
```

**Comment by jgrammen-agilitypr** [comment]
thank you for the feedback, I will be using that command with the awareness that it is not a full check, and only a basic syntax check.

**Comment by DisSsha** [comment]
> You can use `icinga2 console -r <file> --syntax-only` to do that. Note that this really only does a syntax check. A lot of common mistakes (like invalid attribute names, incorrect function names, etc.) will not be detected that way.
> 
> ```
> gunnar@abyss ~ $ icinga2 console -r apply-test.conf --syntax-only 2>/dev/null
> Location: in apply-test.conf: 34:35-35:0
> apply-test.conf(32): assert(get_host("test").vars.type == "first")
> apply-test.conf(33):
> apply-test.conf(34): var service = get_service("test", "test)
>                                                        ^^^^^^
> apply-test.conf(35):
> 
> apply-test.conf(36): /* Pretend to submit a check result for the service. */
> apply-test.conf(37): service.state_raw = 2 /* CRITICAL */
> Unterminated string literal
> gunnar@abyss ~ $
> ```

Thanks you that was exactly what I was looking for !
