### ISSUE TITLE
Upgrade issue from v2.7.1 to 2.8.0

### ISSUE THREAD

**Issue by R00T88** [Icinga/icinga2#5810]
Hello,
i upgrade from 2.7.1 to 2.8.0 but i have this error

![image](https://user-images.githubusercontent.com/9050487/33311932-a19a3618-d426-11e7-820e-dc488bd113d2.png)

if i type the command icinga2 daemon -C i got this output

![image](https://user-images.githubusercontent.com/9050487/33311981-c482bcae-d426-11e7-8547-8aa355b3976d.png)

How can i fix it?

Regards

**Comment by dnsmichi** [comment]
Please read the upgrade docs: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#upgrading-to-v28
