### ISSUE TITLE
extend the hostgroup api calls to integrate 'assign_where' / 'ignore_where' rules

### ISSUE THREAD

**Issue by bodsch** [Icinga/icinga2#5814]
as example the current cli call creates an hostgroup:
```
curl -k -s -u root:icinga -H 'Accept: application/json' -X PUT \
'https://localhost:5665/v1/objects/hostgroups/linux-servers' \
-d '{"attrs":{"display_name":"all Linux Servers"}}'
```
but, we can't add some assign ore ignore rules. :(

a possible solution can be an array for some assign and/or ignore rules.
```
curl -k -s -u root:icinga -H 'Accept: application/json' -X PUT \
'https://localhost:5665/v1/objects/hostgroups/linuxservers' \
-d '{"attrs":{"display_name":"all Linux Servers", "assign_where":["host.vars.os == \"Linux\""]}}'
```

**Comment by dnsmichi** [comment]
apply rules and assign/ignore are generally not supported by the API as it is an object based API. That needs a proper design and specification if such should be added.

**Comment by rygy** [comment]
is this something on the roadmap for the near future?

**Comment by dnsmichi** [comment]
No, currently I don't know how to make this happen nor have a specific design in mind. This follows the request to create apply rules via the REST API which currently also isn't possible - except for config packages with static configuration text.

**Comment by dnsmichi** [comment]
There won't be any efforts with moving the apply logic into the runtime REST API. The DSL is too complex and dynamic as it could fully solve a somewhat static interface. Transactions, rollbacks, affected object handling, recursive interactions are all a thing which generates an endless loop of dependencies here. Within the config packages, Director or static config files, this has gotten a safe interface with advanced staging and rollbacks even in a sandbox context.

Therefore I am closing this request.
