### ISSUE TITLE
mongodb_address vs mongodb_host

### ISSUE THREAD

**Issue by pgassmann** [Icinga/icinga2#5817]
The documentation and implementation of the mongodb plugin are inconsistent.
the plugin uses `$mongodb_address$` the documentation lists  `$mongodb_host$`

https://github.com/Icinga/icinga2/blame/21207724173691e6cfc368f077e633d1adb08f69/itl/plugins-contrib.d/databases.conf#L619
https://github.com/Icinga/icinga2/blame/21207724173691e6cfc368f077e633d1adb08f69/doc/10-icinga-template-library.md#L2334

## Expected Behavior

I suggest the name mongodb_host to be used, as it matches the actual parameter description of the check_mongodb.py
 ` -H HOST, --host=HOST  The hostname you want to connect to`

## Your Environment
Icinga 2.8.0

**Comment by gunnarbeutner** [comment]
Your ticket seems to be missing a description.

**Comment by pgassmann** [comment]
sorry, i submitted to early and you are too fast. The description is added now.

**Comment by dnsmichi** [comment]
Unfortunately the attribute was named `mongodb_address` and never got corrected to `mongodb_host` as the other CheckCommands imply as best practice. We should change the ITL CheckCommand in an upgrade safe fashion. Meanwhile use `mongodb_address`.
