### ISSUE TITLE
Missing Dependency libstdc++.so.6 and other RHEL5

### ISSUE THREAD

**Issue by marcelfischer** [Icinga/icinga2#5818]
## Expected Behavior
When I try to install icinga2 on RHEL 5.11 I would expected that the depencies are resolved automatically with icinga2 and epel repo.

## Current Behavior
I get Missing Dependency error messages by yum for libboost packages, because they want a version of libstdc++.so.6(GLIBCXX_3.4.9 and GLIBCXX_3.4.11) which is not provided by redhat.
I tried different version of icinga2 (2.6, 2.5.0, 2.4.10)

Error messages:
`Error: Missing Dependency: libstdc++.so.6(GLIBCXX_3.4.11)(64bit) is needed by package libboost_regex1_53_0-1.53.0-0.x86_64
Error: Missing Dependency: libstdc++.so.6(GLIBCXX_3.4.9)(64bit) is needed by package libboost_thread1_53_0-1.53.0-0.x86_64
Error: Missing Dependency: libicui18n.so.42()(64bit) is needed by package libboost_regex1_53_0-1.53.0-0.x86_64 
Error: Missing Dependency: libicuuc.so.42()(64bit) is needed by package libboost_regex1_53_0-1.53.0-0.x86_64 
Error: Missing Dependency: libicudata.so.42()(64bit) is needed by package libboost_regex1_53_0-1.53.0-0.x86_64 

## Possible Solution
Currently no real idea. Maybe some rpm packaging bug?

## Steps to Reproduce (for bugs)

1. yum install icinga2-2.6.3

## Context
Rollout Icinga2 on RHEL5.11 systems

## Your Environment

* Version used (`icinga2 --version`): 2.6.3 but also lower ones
* Operating System and version: Red Hat Enterprise Linux Server release 5.11 (Tikanga)
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by gunnarbeutner** [comment]
RHEL 5 is not a supported platform. Sorry.
