### ISSUE TITLE
Add and Remove Host using REST API

### ISSUE THREAD

**Issue by philcoder** [Icinga/icinga2#5822]
When I add and after remove the hosts using icinga2 REST API, the icinga2 database and tables icinga_hosts and icinga_objects did not remove host and objects, after DELETE? This is normal behavior for icinga2? The icinga2 control the registered hosts and objects using the colunm is_active on  table icinga_objects?

I just ask to understand the database operation with creation files in icinga2...

## Your Environment
* Version used (`icinga2 --version`): r2.8.0-1
* Operating System and version: Debian 8.9 x86_64
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Database: MySQL

**Comment by gunnarbeutner** [comment]
This is not a bug. Please use the community channels for support questions.
