### ISSUE TITLE
icinga2: depends on icinga2-bin (=2.7.0-1~debmon8+1) but should not be installed

### ISSUE THREAD

**Issue by Hack4Life** [Icinga/icinga2#5828]
## Expected Behavior

I'm trying to install icinga2 on my raspberry Pi 3 running NOOBS with raspbian installed. 
I run `apt-get install icinga2`. I have added all sources and the keys, made `apt-get update` and `apt-get upgrade` and then a reboot. 

## Current Behavior

After running `apt-get install icinga2 ` as root user I get the following output: 

> root@icingamonitoring:/var# apt-get install icinga2 -y
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:
> Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 icinga2 : Hängt ab von: icinga2-bin (= 2.7.0-1~debmon8+1) soll aber nicht installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

## Your Environment

* Operating System and version: PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

**Comment by dnsmichi** [comment]
Probably icinga2-bin is not available as package for this platform. Since debmon is an external community repository, please contact their maintainers.
