### ISSUE TITLE
icinga2 master does not switch when ido connection is lost on one node

### ISSUE THREAD

**Issue by tlo8640** [Icinga/icinga2#5832]
## Expected Behavior
If there is an Icinga2 Setup with two masters and an ido backend, I was expecting, that the active node is switching to the second one, when the currently active node loses it db-connection.

## Current Behavior
while testing failover of the icinga2 master nodes, we faound out, that when the db connection on the active icinga2 master node is lost, the cluster doesn't switch to the 2nd master node. It still keeps the node with the lost db connection as active node

## Possible Solution
don't  know a workaround

## Steps to Reproduce (for bugs)
1. create icinga2 setup with two master nodes and one ido backend
2. "destroy" db-connection on active node, for instance with an ip tables rule
3. wait for switching the active node
4. wait forever...

## Context
we were testing possible failure situations in our setup and howto avoid or work around or at least howto monitor and notify them. In this way try killed (iptables) the db connection on the active master node. It could happen in production mode if (for reasons) one node loses its db connection in case of network failures. We were expecting that the active node is changing to the second previously inactive master node, but the node with the not working db connection still stayed active. this was just surprising. During previous tests, when we killed the icinga2 proces on the active master node switching worked perfectly.

If this is expexcted behavior, could you please advice howto workaround these situations, when on master node loses its db connection?
It is possible to force the switch of the nodes?
is there an easy way to find out what node is the active master node?

## Your Environment
Iicnga2 with two master nodes in 2 different locations. IDO DB is a galera 5 Node Cluster with one VIP for accessing the cluster. 
* Version used (`icinga2 --version`):
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.5.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Enabled features (`icinga2 feature list`):
Disabled features: command compatlog debuglog gelf influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker graphite ido-mysql mainlog notification

## existing Bug?

Before opening this issue I was looking through already reported issues and found the following entrry:
https://github.com/Icinga/icinga2/issues/5271
This was closed and I didn't found any follow up...

**Comment by dnsmichi** [comment]
How exactly does the (debug) log on both instances look for this manner? 

If the cluster is not connected, aka in split brain mode, you'll need a way to prevent data duplication.
The quorum in the middle is the programstatus table which holds the status_update_time as well as the current endpoint_name who's actively writing. If one instance sees that the other one is actively writing, it will pause its functionality. That only works if the cluster is in **split brain** mode, aka not connected.

If the cluster is connected, and the active IDO feature is disconnected from the database, there's no active failover mechanism in place. It is purely dependent on the cluster's HA functionality.

More on that here: https://www.icinga.com/docs/icinga2/latest/doc/19-technical-concepts/#high-availability-db-ido

The linked issue ended up in a bad example for communication, that's dead.

**Comment by dnsmichi** [comment]
Closing as no feedback was received.

**Comment by Thomas-Gelf** [comment]
@dnsmichi: when you need more feedback here please let me know, eventually I can help you. What exactly are you missing? Like the older linked issue also @tlo8640 nailed the problem and explained how to reproduce it with very few simple steps. Your initial reply confirms the behavior he used to see. Setups with a floating IP (as it should be) are also affected.

While I can of course read from the linked docs that this is to be expected, we should still elaborate whether this is really what we want to happen in such a scenario. As of today while two nodes are connected, nobody will write to the IDO when the node primarily writing to the DB is no longer able to do so. 

Cheers,
Thomas

**Comment by devarti** [comment]
Does Icinga2 (version: 2.11.2-1) has issue in cluster mode? experiencing issue when master-01 is down the web UI shows 
"Backend icinga is not running"
