### ISSUE TITLE
Disable Certificate requests

### ISSUE THREAD

**Issue by camilo-schoeningh-sociomantic** [Icinga/icinga2#5834]
In our  environment we are using icinga2 and our own technique to roll out certificates. Because we are rolling out our own certificates we like to know, whether it is possible **to disable certificate requests** in icinga2. 
So in the end no longer such messages arise :
`[2017-11-23 13:19:56 +0000] information/JsonRpcConnection: Certificate request for CN 'exxx.xxx.com' is pending. Waiting for approval.
`
Thanks for your support

**Comment by dnsmichi** [comment]
Please fill in the issue template next time.

I'd investigate on the fact why your client actually thinks it should send a certificate signing request on its own. Likely the certificate appears to be self-signed, or it will expire in 30 days.

You cannot disable that mechanism, that's built-in as part of the CA-proxy design.

**Comment by dnsmichi** [comment]
No feedback received, I assume this resolved itself.
