### ISSUE TITLE
Icinga DB: make history linkable with the status info

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#5837]
## Expected Behavior

Any historical event (e.g. downtime start/end) provides the ID (or similar) of the related config/status object if any (e.g. the actual downtime).

## Current Behavior

With the current IDO schema I can't even use timestamps for such linking as the may differ a bit.

## Possible Solution

Make this better in Icinga DB.

## Steps to Reproduce (for bugs)

```
MariaDB [icinga]> desc icinga_downtimehistory; desc icinga_scheduleddowntime;
```

## Context

https://github.com/Icinga/icingaweb2/issues/3191

## Your Environment

Only the latest bleeding edge hipster stuff.

**Comment by dnsmichi** [comment]
Closing this in favour of a general project plan.
