### ISSUE TITLE
Possible incorrect handling of certificates when using icinga2 pki * commands

### ISSUE THREAD

**Issue by takeda** [Icinga/icinga2#5839]
So I'm trying to automate certificate authentication on Linux and either I'm missing something, or perhaps there's a mistake in the implementation.

So I'm doing this in 3 steps (this is what I expect to happen in the ideal implementation)

1. icinga2 pki new-cert - to generate key, csr & cert
2. icinga2 pki save-cert - fetching master node certificate
3. icinga2 pki request - to sign host certificate and download ca.crt

The current approach appears to be flawed:

- the first step requires to generate self signed certificate which will be overwritten in next steps 
- the second step requires visual inspection of key hash, and does no verification
- the third command writes signed certificate and populates ca.crt

The proper IMHO behavior would be:
- (outside of icinga2, perhaps using salt/chef/puppet etc) populating ca.crt
- generate new key and csr (icinga2 pki new-cert)
- generate signed certificate by using csr, ca.crt and a ticket (ca.crt proves that we are talking to real master, the ticket proves node's authenticity)
- fetch master certificates (if that's still needed) ca.crt can be used to verify they are authentic

**Comment by dnsmichi** [comment]
The procedure was designed with users in mind who don't have any sort of automation tools. Furthermore not everyone fully understands how TLS and certificates do work. It should be simple to a) use a self-signed certificate and start the daemon b) allow to send a certificate signing request to the parent node c) verify the parent's public certificate as a matter of trust.

At some point you'll see how it works, but generally speaking it is not mandatory to fully understand how TLS handshakes and certificates work. It is far more important to have it installed and running in a secure fashion.

On the other hand you have users who are TLS "pros" and want to do their own stuff. That's where those CLI commands propose just a way of doing such. I've seen many users reverse engineering the source code (hooray for open source). They've built their own solution based on that, e.g. by using a different CA and deploying the CSRs and signed certificates in a different fashion.

Keep in mind that v2.8 added the CA proxy capabilities, certificate renewal and on-demand ticket-less signing. This adds additional complexity whilst installing more possibilities for easier deployment. 

It is fairly up to you, which way you choose. Thanks for your input on that matter.

**Comment by takeda** [comment]
I think there's a confusion, what I'm trying to say is I believe the certificate signing mechanism using icinga2 commands is flawed.

To summarize, in order to securely sign a new certificate we need two things:

1. proof that we are talking with the master
2. proof that we are who we say we are

The second step is done through the ticket system (if we have the correct ticket it means it is us). The first part normally is done through ca.crt (e.g. there's no need to verify trusted-master.crt, because it should be signed by ca.crt):

```
$ openssl verify -CAfile ca.crt trusted-master.crt
trusted-master.crt: OK
```

Similarly ca.crt can be used to verify that we are talking to the right master:
```
$ curl --cacert ca.crt -u <credentials> https://<redacted>:5665/v1/; echo
<html><head><title>Icinga 2</title></head><h1>Hello from Icinga 2 (Version: r2.8.0-1)!</h1><p>You are authenticated as <b>salt</b>. Your user has the following permissions:</p> <ul><li>actions/generate-ticket</li></ul><p>More information about API requests is available in the <a href="https://docs.icinga.com/icinga2/latest" target="_blank">documentation</a>.</p></html>
```

After thinking about it I think the issue really just comes down to `icinga2 pki request` command and the `icinga2 pki save-cert` is redundant.

What I'm proposing is to change icinga2 pki request as follows:

- instead of accepting instance certificate (`--cert`) as an input it should accept `--csr` (Certificate Signing Request), `--cert` would still be used to output a signed certificate
- `--ca` should be used as an input to verify we are talking to the right master `--trustedcert` can be used to do that, but trusted cert is a certificate of a single master, and is a certificate that is immediately sent when connecting to the master. It is redundant, and `ca.crt` is enough to verify authenticity of any master
- as mentioned above `--trustedcert` is redundant

As far as I can tell the current icinga2 security mechanisms appear to be correct, just the `pki request` feels like it was written by someone who doesn't understand the subject and just tinkered with it until it started to work. I believe that this might be the reason why some people reverse engineer the signing and implement their own solution, because unless I'm missing something this model is broken.

**Comment by dnsmichi** [comment]
There were adoptions to the `node setup` CLI command where connection-less setups will be supported too in 2.9. For automation setups, this is the recommended way. If you happen to have a PR for save-cert and pki request, much appreciated. We won't change anything further here.
