### ISSUE TITLE
Use std::to_string for Convert::ToString()

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5842]
Another C++11 variant. 

Note: Convert::ToString(double) might still need some special handling. 

- [ ] Unit tests

**Comment by Al2Klimov** [comment]
`std::to_string` is locale aware, isn't it?

**Comment by dnsmichi** [comment]
Removing this, see https://github.com/Icinga/icinga2/pull/6904#issuecomment-478940334
