### ISSUE TITLE
Notification between host-recovery and service-recovery

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga2#5843]
*Not sure if there is any other related issue - if so please link it in a comment!*

Last night I had a setup with a host down, services where critical dues to outage.

## Expected Behavior

* Host recovery
* Next service check returns OK
* No notification is sent for services

(Unless the service stays on problem)

## Current Behavior

* Host recovers
* Services sends problem notification
* Next service check returns OK
* Recovery notification is sent for service

## Possible Solution

TODO
Wait for (re-) notification until the service was checked

## Steps to Reproduce (for bugs)

TODO

The notification rules involved use `times.begin` with `5m`.

## Your Environment

@cyberkov: Which version is running on masters right now?

* Version used (`icinga2 --version`): 2.7.1
* Operating System and version: Ubuntu xenial
* Enabled features (`icinga2 feature list`): ido-mysql ...

2 Master setup, multiple satellites.

## Screenshot

![bildschirmfoto von 2017-12-07 11-43-04](https://user-images.githubusercontent.com/121874/33723244-764e39d0-db6c-11e7-8ece-3f9b5141674a.png)

**Comment by lazyfrosch** [comment]
Will try to reproduce this!

**Comment by lazyfrosch** [comment]
I'm not able to reproduce this on a single master so far.

Either with and without `times.begin` the notification for a service like that would not immediately notify after the host returns from DOWN.

The service is only notified by re-notification after the interval runs out.

**Further candidate to test:**
cluster scenario, when host, service or notification objects are not active on the same side (handled by different nodes)

@cyberkov: Is there a chance to get another example screenshot like above? (for another host/service combo)

**Comment by lazyfrosch** [comment]
My test config so far:

```icinga2
object Host "notification-test-5843" {
  import "generic-host" 
 
  //address = "127.0.0.1"
 
  check_command = "dummy"

  check_interval = 1m
  retry_interval = 10s
  max_check_attempts = 2
  
  vars.dummy_state = {{ if (get_host("notification-test-5843").state > 0) { return 2; } else { return 0 } }}
  vars.dummy_text = {{ return get_host("notification-test-5843").last_check_result.output }}

  vars.test_issue = "5843"
}
  
object Service "service" {
  import "generic-service"
  host_name = "notification-test-5843"
  
  check_command = "dummy"
  
  check_interval = 5m
  retry_interval = 1m
  max_check_attempts = 1
  
  //vars.dummy_state = 0
  //vars.dummy_text = "Service OK"
  vars.dummy_state = {{ return get_service("notification-test-5843", "service").state }}
  vars.dummy_text = {{ return get_service("notification-test-5843", "service").last_check_result.output }}
}
  
apply Notification "test-5483" to Service {
  import "mail-service-notification"
  users = [ "icingaadmin" ]

  times.begin = 1m

  assign where host.vars.test_issue == "5843"
}
```

With this config you can play around with `submit check result`

**Comment by dnsmichi** [comment]
Any updates on this?

Cheers,
Michael

**Comment by lazyfrosch** [comment]
I wasn't able to reproduce it so far.

We should have a closer look once @cyberkov can provide more examples or reproduce it somehow.
