### ISSUE TITLE
check_service.exe from 2.8.0 Windows agent release returns warning as default

### ISSUE THREAD

**Issue by Duffkess** [Icinga/icinga2#5849]
Hi There,

I just installed the Windows Agent Version 2.8.0 and I used the check_service.exe just like before:

`check_service.exe -s servicename`

and it returned a warning state because the service was not running. I did not use the service_win_warn switch. 

Then I just copied the check_service.exe from the previos 2.7.2 Version and it returned critical state just fine.

So it seems that the default behavior changed to warning state but should be critical.

**Comment by mcktr** [comment]
I can reproduce the behavior. 

**v2.7.1:**

Service `w32time` running: 
```
C:\Program Files\ICINGA2\sbin>check_service.exe -s w32time
SERVICE OK RUNNING | service=4;;;1;7
```

Service `w32time` not running: 
```
C:\Program Files\ICINGA2\sbin>check_service.exe -s w32time
SERVICE CRITICAL NOT RUNNING | service=1;;;1;7
```
```
C:\Program Files\ICINGA2\sbin>check_service.exe -s w32time -w
SERVICE WARNING NOT RUNNING | service=1;;;1;7
```
**v2.8.0-5-gdf10d2a:**

Service `w32time` running: 
```
C:\Program Files\ICINGA2\sbin>check_service.exe -s w32time
SERVICE "w32time" OK RUNNING | service=4;;;1;7
```

Service `w32time` not running: 
```
C:\Program Files\ICINGA2\sbin>check_service.exe -s w32time
SERVICE "w32time"WARNING NOT RUNNING | service=1;;;1;7
```
```
C:\Program Files\ICINGA2\sbin>check_service.exe -s w32time -w
SERVICE "w32time"WARNING NOT RUNNING | service=1;;;1;7
```

I will look into the code once I have a bit time, in the next days.

**Comment by Crunsher** [comment]
We don't initialize `printInfo.warn` to false explicitly in the case it's not set.
According to the standard, this should not be a problem as it is to be default 0 -> False. But we did change our VS Compiler with 2.8 so I guess Microsoft again does what it wants :P
