### ISSUE TITLE
Livestatus log small time range query filter bad match

### ISSUE THREAD

**Issue by spaolo** [Icinga/icinga2#5852]
Querying livestatus log with a time range filter inside single log time boundaries return a wrong emtpy result, or in other words all events between the time filter start and the end of the logfile where it falls are discarded

## Expected Behavior
Querying current compat log with livestatus query using a time range starting after first row should match and return matching rows

## Current Behavior
Quering livestatus log using a range starting after first row matches no row

## Possible Solution
taking care about the end time of compat log files into LivestatusLogUtility::CreateLogCache at htps://github.com/Icinga/icinga2/blob/5af5d38c2691ddead3efbcb75b1e65da51be6299/lib/livestatus/livestatuslogutility.cpp#L87 should solve the problem

## Steps to Reproduce (for bugs)
1. prepare a compat log containing a four step time range like in the following example
```
[1513022400] CURRENT HOST STATE: host1;UP;HARD;1;host is up
[1513022401] CURRENT HOST STATE: host2;UP;HARD;1;host is up
[1513022402] CURRENT HOST STATE: host3;UP;HARD;1;host is up
[1513022403] CURRENT HOST STATE: host4;UP;HARD;1;host is up
```
2. run a livestatus log query to filter only inner rows on time basis
```
GET log
Filter: time >= 1513022401
Filter: time <= 1513022402
Stats: min time
Stats: max time
OutputFormat: csv
ResponseHeader: fixed16

```
3. see the null mapped to zero min and max time reply
```
0;0
```
instehad of the expected
```
1513022401;1513022402

## Context
this and with I #5698 are preventing us from using mysql log cache on our thruk installation

## Your Environment
* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)
Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Operating System and version:
System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux

**Comment by dnsmichi** [comment]
Unfortunately we won't put any effort into this feature anymore.
