### ISSUE TITLE
(Small) problem when building the OpenIndiana package

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icinga2#5869]
Hi folks :)

As some of you know I'm currently building an OpenIndiana / OpenSolaris package using `icinga2-2.8.0` sources. First of all: nearly everything is fine! I have a first package version which installs and runs without any problems so far.

So now my request: as you know we're using Icinga Director, and the OpenSolaris host will act as an agent. Icinga Director provides in tab "Agent" a "Linux commandline script" (should be renamed later on), and this script is based on `/usr/lib/icinga2/icinga2` or `ICINGA2_SYSCONFIGFILE`, so it is needed. As I defined in my userland framework `-DICINGA2_SYSCONFIGFILE` I was surprised that this setting seems to be ignored.

In fact it is: it is [CMakeLists.txt](https://github.com/Icinga/icinga2/blob/master/etc/CMakeLists.txt), it defines 82-84:
````
if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
  add_subdirectory(initsystem)
endif()
````

For testing purposes I simply used `add_subdirectory(initsystem)` without the if-statement; then a fully correct `icinga2.sysconfig` is generated in `build/amd64/etc/initsystem/initsystem/`, but it's not going to be installed - I didn't understand the condition for this. I moved it manually to `/usr/lib/icinga2` now and renamed it to `icinga2`, and I was able to run the kickstart script without any issues :)

Another question is: how to get the build showing a proper version number? In Icinga Web 2, it currently looks like this what is a bit misleading I think (adore the Sparkling Unicorn Theme):
![screen shot 2017-12-15 at 13 00 23](https://user-images.githubusercontent.com/11242139/34041370-1579ad10-e198-11e7-8c09-07b2612ef29c.jpg)

Would be nice to get some support at this two small issues :)

Have a nice weekend!

Cheers,
  Marianne

## Your Environment

* Version used (`icinga2 --version`): source 2.8.0
* Compiling: openindiana-userland, gcc4/g++4
* Operating System and version: 5.11 illumos-68d7704518

**Comment by gunnarbeutner** [comment]
Assigned to @N-o-X because he's playing around with OpenIndiana right now anyway. :)

**Comment by dnsmichi** [comment]
Note: CMake works with recursive trees. You'll find another CMakeLists.txt in the etc/initsystem/ directory, which takes care about installing things.

**Comment by gunnarbeutner** [comment]
By default Icinga 2 uses `git describe` to figure out its version number. You can use the CMake flag `ICINGA2_GIT_VERSION_INFO` to turn that off (e.g., `-DICINGA2_GIT_VERSION_INFO=false`). When turned off it'll use the version number from the `icinga2.spec` file instead.

**Comment by gunnarbeutner** [comment]
`if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")` was added with commit 9217ea3143. I guess I'll just enable that for Solaris.
