### ISSUE TITLE
DateTime macro extension 'short_date'

### ISSUE THREAD

**Issue by wols** [Icinga/icinga2#5870]
The DateTime macros in https://github.com/Icinga/icinga2/blob/master/lib/icinga/icingaapplication.cpp are `timet`, `long_date_time`, `short_date_time`, `date`, `time` and `uptime`.

I must check NTP stats files with a "short date" suffix, eg. `ntpstats.20171224`.

I want a new option `$icinga.short_date$` = `FormatDateTime("%Y%m%d", now)`.
Is this a possible (christmas) option?

**Comment by gunnarbeutner** [comment]
Well, looks like Christmas came early (again) 😇:

`vars.short_date = {{ DateTime().format("%Y%m%d") }}`

This will take the current timestamp and format it using the format string given to `format()`. You can format a specific timestamp by supplying an argument to the constructor for the `DateTime` type.

**Comment by wols** [comment]
Thanks! This is a cool gift ;-)
