### ISSUE TITLE
Full /var/ directory does not cause a warning/crash on CentOS6 

### ISSUE THREAD

**Issue by HristoMohamed** [Icinga/icinga2#5873]
Hey,
I found this by an unfortunate circumstances.
When setting up a new master and its zones, upon restart, the objects that are supposedly copied to /var/lib/icinga2/api/zones are never actually copied if the /var/ partition is full. I am also unable to locate an error about this in the log files.

**Comment by Crunsher** [comment]
I'll have too look at the code first, but could it be there is no log message because the icinga log is in /var/log and can't be written either?

**Comment by HristoMohamed** [comment]
My /var/log are mounted on another partition and I can see the logs being written.

**Comment by dnsmichi** [comment]
Uhm, that happens with any other application too when disk is running full - you really should put local monitoring in place which notifies you _before_ it happens.

https://www.icinga.com/docs/icinga2/latest/doc/08-advanced-topics/#monitoring-icinga-2

**Comment by HristoMohamed** [comment]
Huh?
A normal application should realize it is unable to copy contents of whatever it is trying to copy. Try for example to move a **destination** to a **source** with less space with rsync/cp and tell me what happens.
You should spit out an error message that Icinga was unable to do it.
Is it mandatory? No, it is not.
Is it polite for the user? Absolutely.

**Comment by Crunsher** [comment]
We can hardly log that we can't write to the log, right :D 
This is a problem reserved for the user to solve
