### ISSUE TITLE
Wrong result, when repeated creating of config packages over API

### ISSUE THREAD

**Issue by bodsch** [Icinga/icinga2#5875]
i try to create config packages over the API (to implement this in my ruby SDK)

the first call works as expected
```
$ curl -k -s -u root:icinga -H 'Accept: application/json' -X POST https://localhost:5665/v1/config/packages/test-package

{"results":[{"code":200.0,"status":"Created package."}]}
```

to test a error handling i repeat these command
```
$ curl -k -s -u root:icinga -H 'Accept: application/json' -X POST https://localhost:5665/v1/config/packages/test-package

{"error":500.0,"status":"Could not create package."}{"results":[{"code":200.0,"status":"Created package."}]}
```
these result are not a valid json and the second part (with the 'results' ) is wrong.

## Your Environment
* Version used (`icinga2 --version`): `icinga 2.8.0`
* Operating System and version: `Linux (gentoo)`

**Comment by dnsmichi** [comment]
Thanks, #5879 is the main working issue for that. Closing as duplicate.
