### ISSUE TITLE
Add pretty format to REST API parameters (for debugging)

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#5877]
Elasticsearch's API has the `pretty` parameter for debugging purposes. This helps to avoid `| python -m json.tool` and variants.

https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html

Maybe we consider this as well. But still, users tend to copy documentation examples - those should remain untouched. "pretty" formatted JSON is not parsable anymore.

@gunnarbeutner @Crunsher @N-o-X please add your opinions.

**Comment by gunnarbeutner** [comment]
Sounds like a good idea. JFDI. :)

**Comment by dnsmichi** [comment]
As discussed today, the SendJsonBody() function just needs the params and should figure it out. Otherwise we would need to handle all calls beforehand which duplicates the code.

**Comment by dnsmichi** [comment]
SendJsonError() requires the same changes.

**Comment by dnsmichi** [comment]
<img width="830" alt="screen shot 2018-01-08 at 20 33 12" src="https://user-images.githubusercontent.com/382049/34688702-49781e48-f4b3-11e7-96ba-240f2eab4572.png">

**Comment by dnsmichi** [comment]
<img width="1370" alt="screen shot 2018-01-08 at 20 42 45" src="https://user-images.githubusercontent.com/382049/34689071-88cdbe76-f4b4-11e7-8c43-a48bf59b4178.png">
