### ISSUE TITLE
REST API replys with strange answer when creating Configuration Package

### ISSUE THREAD

**Issue by Paraidomat** [Icinga/icinga2#5879]
The REST API seems to reply with two status codes at once, when sending a POST to create a configuration package  or configuration stage. 

### Configuration Insights:
- I'm using the vagrant box of `icinga2x`.
- Git Info:
```$ git log
commit e85495fee12d1bd2ce86ded08fed3939b3e2f5b4
Merge: 5eaa71a 160a76a
Author: Michael Friedrich <michael.friedrich@icinga.com>
Date:   Tue Nov 21 13:50:38 2017 +0100

    Merge pull request #111 from Icinga/fix/elasticsearch-module
    
    icingaweb2-module-elasticsearch: Use git master 
```

## Expected Behavior
- I expect the API to reply either a status 500 or status 200 message, but not both messages in one reply text. 
- For example: `{"error":500.0,"status":"Could not create package."}` if i made a mistake.
- And: `{"results":[{"code":200.0,"status":"Created package."}]}` if it worked.

## Current Behavior
- I receive the following JSON as a response:
```{"error":500.0,"status":"Could not create package."}{"results":[{"code":200.0,"status":"Created package."}]}```
- Because this is practically two JSON strings my JSON interpreter crashes with this exception:
```json.decoder.JSONDecodeError: Extra data: line 1 column 53 (char 52)```

## Steps to Reproduce (for bugs)
1. Start `icinga2x` vagrant box
2. Send the following request:
    - url: `https://192.168.33.5:5665/v1/config/packages/testpackage`
    - headers: `{'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'User-Agent': 'python-requests/2.9.1'}`
    - data: `null`

### What are you trying to accomplish?
I'm trying to use the Icinga2 REST API in order to apply dependencies using the configuration management features.

## Your Environment
- Icinga Version:
```icinga2 - The Icinga 2 network monitoring daemon (version: v2.8.0-45-g1f52e39)```
- Feature List:
```[root@icinga2 ~]# icinga2 feature list
Disabled features: command compatlog debuglog elasticsearch gelf influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker graphite ido-mysql mainlog notification
```
- `icinga2 daemon -C`
```information/cli: Finished validating the configuration file(s).```

**Comment by Paraidomat** [comment]
Also this is the debug-log of icinga2 for the time of the request:

```[2017-12-15 14:09:54 +0000] information/ApiListener: New client connection from [192.168.33.1]:36536 (no client certificate)
[2017-12-15 14:09:54 +0000] notice/ApiListener: New HTTP client
[2017-12-15 14:09:54 +0000] debug/HttpRequest: line: POST /v1/config/packages/testpackage HTTP/1.1, tokens: 3
[2017-12-15 14:09:54 +0000] notice/WorkQueue: Spawning WorkQueue threads for 'HttpServerConnection'
[2017-12-15 14:09:54 +0000] information/HttpServerConnection: Request: POST /v1/config/packages/testpackage (from [192.168.33.1]:36536, user: root)
[2017-12-15 14:09:54 +0000] warning/HttpResponse: Tried to set Http response status after headers had already been sent.
[2017-12-15 14:09:54 +0000] debug/HttpServerConnection: Http client disconnected```

**Comment by gunnarbeutner** [comment]
@Crunsher: Can you have a look at this please?

**Comment by gunnarbeutner** [comment]
Looks like we're missing a return here:

```
diff --git a/lib/remote/configpackageshandler.cpp b/lib/remote/configpackageshandler.cpp
index 0b41cd65b..1ee6cb409 100644
--- a/lib/remote/configpackageshandler.cpp
+++ b/lib/remote/configpackageshandler.cpp
@@ -93,6 +93,7 @@ void ConfigPackagesHandler::HandlePost(const ApiUser::Ptr& user, HttpRequest& re
        } catch (const std::exception& ex) {
                HttpUtility::SendJsonError(response, 500, "Could not create package.",
                        HttpUtility::GetLastParameter(params, "verboseErrors") ? DiagnosticInformation(ex) : "");
+               return;
        }

        result1->Set("code", 200);
```

(untested for now)
