### ISSUE TITLE
Remove unnecessary 'inline' keyword

### ISSUE THREAD

**Issue by gunnarbeutner** [Icinga/icinga2#5886]
The inline keyword is not necessary when a member function is defined in the class definition, e.g.:

```
class Z
{
  inline int f(void)
  {
    return 3
  }
};
```

**Comment by Crunsher** [comment]
Additional reading:
https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_71/rzarg/inline_member.htm

**Comment by Crunsher** [comment]
Might as well take that one as I refactor all the code
