### ISSUE TITLE
Ubuntu apt remove/purge not very successful.

### ISSUE THREAD

**Issue by tvanriper** [Icinga/icinga2#5896]
## Summary

On a xenial ubuntu server, the "apt remove icinga2", "apt purge icinga2', "apt autoremove" sequence leaves behind such a mess you cannot successfully "apt install icinga2" anymore.

## Expected Behavior

When the icinga2 package is purged, and perhaps /etc/icinga2 is deleted, one should be able to install icinga2 as if it had never existed on the system previously.

## Current Behavior
Instead, mysteriously, some of the configuration files within /etc/icinga2 do not get installed.

## Possible Solution
On an apt purge, do a more thorough job of removing what you can of icinga2, at least enough to permit a proper install.

At the very least, provide documentation for recovery.

## Steps to Reproduce (for bugs)
1. Start with a brand new, untouched Ubuntu Xenial server.
2. wget -O - https://packages.icinga.com/icinga.key | apt-key add -
3. echo 'deb https://packages.icinga.com/ubuntu icinga-xenial main' >/etc/apt/sources.list.d/icinga.list
4. apt install icinga2  # Note that we're simulating a mistake here.  Failed to apt update before this.
5. apt update
6. apt remove icinga2
7. apt purge icinga2
8. apt autoremove
9. apt install icinga2
10. icinga2 daemon -C # Note that it's missing a configuration file.
11. apt remove icinga2; apt purge icinga2; apt autoremove
12. rm -rf /etc/icinga2  # Note that you can remove all the folders mentioned in the Getting Started guide, but you will still have the same results.
13. apt install icinga2
14. icinga2 daemon -C # Note that now it's missing... more configuration files.

## Context
As the steps above simulate, if you make a mistake on installation (perhaps because all the machines are starting to blur together as you install the client on many of them), recovering from that mistake becomes heinous.

## Your Environment
* Ubuntu Xenial server.

**Comment by tvanriper** [comment]
Ah, this might be a non-issue, at least sort of.

To more properly purge this package, one must:

1. apt remove icinga2
2. apt purge icinga2
3. apt autoremove
4. apt purge icinga2-bin
5. apt purge icinga2-common
6. apt purge icinga2-doc
7. apt purge libicinga2

After these, you can successfully "apt install icinga2" again.

**Comment by dnsmichi** [comment]
Thanks for the findings. Please create such issues in the icinga-packaging repository in the future.
