### ISSUE TITLE
Icinga2 HA cluster comments not replicated from slave -> master

### ISSUE THREAD

**Issue by jarttori** [Icinga/icinga2#5910]
Icinga2 HA cluster with local databases, two local Icingaweb2 instances, comments not replicated from slave -> master.

## Expected Behavior
Add comment, it's replicated to both servers

## Current Behavior
Add comment to master, it's replicated to slave
Add comment to slave, it's NOT replicated to master

## Steps to Reproduce (for bugs)
1. Add comment to slave; select * from icinga_comments;
2. Check from master; select * from icinga_comments;

## Context
Icinga2 r2.7.1-1
Icingaweb2 2.4.1
postgresql-libs-9.2.23-1.el7_4.x86_64
postgresql-9.2.23-1.el7_4.x86_64
postgresql-server-9.2.23-1.el7_4.x86_64

library "db_ido_pgsql"

object IdoPgsqlConnection "ido-pgsql"  {
  host = "127.0.0.1"
  port = 5432
  user = "asdasd"
  password = "asdasd"
  database = "icinga2"
  table_prefix = "icinga_"
  instance_name = "default"
  enable_ha = false
  failover_timeout = 60s
}

**Comment by dnsmichi** [comment]
Please show the `api.conf` settings from both nodes.

**Comment by jarttori** [comment]
Master:

```
[root@monv07p features-enabled]# cat api.conf 
# This file is managed by Puppet. DO NOT EDIT.

object ApiListener "api"  {
  cert_path = "/etc/icinga2/pki/monv07p.prd.veikkaus.fi.crt"
  key_path = "/etc/icinga2/pki/monv07p.prd.veikkaus.fi.key"
  ca_path = "/etc/icinga2/pki/ca.crt"
  accept_commands = true
  accept_config = false
  ticket_salt = TicketSalt
}
```

Slave:

```
[root@monv08p features-enabled]# cat api.conf 
# This file is managed by Puppet. DO NOT EDIT.

object ApiListener "api"  {
  cert_path = "/etc/icinga2/pki/monv08p.prd.veikkaus.fi.crt"
  key_path = "/etc/icinga2/pki/monv08p.prd.veikkaus.fi.key"
  ca_path = "/etc/icinga2/pki/ca.crt"
  accept_commands = true
  accept_config = true
  ticket_salt = "asdasd"
}
```

**Comment by dnsmichi** [comment]
Both nodes needs to have `accept_config` set to true in HA-enabled master zones.

**Comment by jarttori** [comment]
Thank you and merry christmas. Verified fixed.
