### ISSUE TITLE
Unable to kill process group after check timeout if SElinux is enabled

### ISSUE THREAD

**Issue by pefmeister** [Icinga/icinga2#5916]
Hi guys,

sorry for the second SElinux issue, but that was the one that actually got me looking at the logs. I have an Icinga 2.8.0-1 installation on a current CentOs 7/x64 with SElinux enabled. I noticed after a host has been down, that the process counter of my I2 host did increase a lot. A quick look at the processes showed that there are hundreds of defunct "check_interfaces" processes. My I2 logfile gives me the following hint:

```
[2017-12-27 20:30:51 +0000] warning/Process: Killing process group 23378 ('/usr/lib64/nagios/plugins/contrib/check_interfaces' '--auth-phrase' 'XXXXXX' '--auth-proto' 'SHA' '--hostname' '192.168.10.230' '--lastcheck' '1514406531' '--priv-phrase' 'XXXXXX' '--priv-proto' 'AES' '--user' 'mon' '-N') after timeout of 60 seconds
[2017-12-27 20:30:51 +0000] warning/Process: Couldn't kill the process group 23378 ('/usr/lib64/nagios/plugins/contrib/check_interfaces' '--auth-phrase' 'XXXXXX' '--auth-proto' 'SHA' '--hostname' '192.168.10.230' '--lastcheck' '1514406531' '--priv-phrase' 'XXXXXX' '--priv-proto' 'AES' '--user' 'mon' '-N'): [errno 13] Permission denied
```

Again, permission denied, which leads me to SELinux. A quick glance through the audit log gives the following:

```
type=AVC msg=audit(1514407011.411:61680): avc:  denied  { sigkill } for  pid=13411 comm="icinga2" scontext=system_u:system_r:icinga2_t:s0 tcontext=system_u:system_r:nagios_unconfined_plugin_t:s0 tclass=process
type=SYSCALL msg=audit(1514407011.411:61680): arch=c000003e syscall=62 success=no exit=-13 a0=ffff9f5e a1=9 a2=ffffffff a3=fffffe00 items=0 ppid=13397 pid=13411 auid=4294967295 uid=996 gid=993 euid=996 suid=996 fsuid=996 egid=993 sgid=993 fsgid=993 tty=(none) ses=4294967295 comm="icinga2" exe="/usr/lib64/icinga2/sbin/icinga2" subj=system_u:system_r:icinga2_t:s0 key=(null)
```

PID 13411 is the ID of my Icinga 2 process. 13397 is its parent process:

```
icinga   13397     1  0 19:43 ?        00:00:17 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/error.log --reload-internal 31338
icinga   13411 13397  0 19:43 ?        00:00:03 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/error.log --reload-internal 31338
```

Unfortunately there seems to be no hint to the PID of the child process he wants to kill within the audit.log file.

Any idea how to cope with this instead of leaving SElinux disabled?

Many thanks,
Stephan

**Comment by pefmeister** [comment]
Some more info about my environment with regards to SElinux:

```
# rpm -q icinga2-selinux
icinga2-selinux-2.8.0-1.el7.icinga.x86_64
# semodule -l | grep -e icinga2 -e nagios -e apache
apache  2.7.2
icinga2 0.1.4
nagios  1.13.0
permissive_nagios_notification_plugin_t 1.0
# ps -eZ | grep icinga2
system_u:system_r:icinga2_t:s0  13397 ?        00:00:22 icinga2
system_u:system_r:icinga2_t:s0  13411 ?        00:00:04 icinga2
# semanage port -l | grep icinga2
icinga2_port_t                 tcp      5665
# audit2allow -li /var/log/audit/audit.log


#============= icinga2_t ==============
allow icinga2_t icinga2_etc_t:file execute;
allow icinga2_t nagios_unconfined_plugin_t:process sigkill;

#============= nagios_notification_plugin_t ==============
allow nagios_notification_plugin_t cert_t:file { getattr lock open read };
allow nagios_notification_plugin_t cert_t:lnk_file read;
allow nagios_notification_plugin_t http_port_t:tcp_socket name_connect;
allow nagios_notification_plugin_t net_conf_t:file { getattr open read };
allow nagios_notification_plugin_t self:netlink_route_socket { bind create getattr nlmsg_read };
allow nagios_notification_plugin_t self:tcp_socket { connect create getattr getopt setopt };
allow nagios_notification_plugin_t self:udp_socket { connect create getattr };
allow nagios_notification_plugin_t smsd_spool_t:dir { add_name write };
allow nagios_notification_plugin_t smsd_spool_t:file { create getattr open read setattr write };
```

**Comment by dgoetz** [comment]
So I see several issues:
* Icinga 2 not being allowed send a kill signal, which I have to allow at least in the policy or better get this fixed in the nagios policy containing the interface for the plugins.
* A mislabeled script in /etc/icinga2 which will not be executed, you should investigate on this and label it depending on the plugin type. Something like `ls -lZ /etc/icinga2/scripts` and `restorecon -Rv /etc/icinga2/scripts` I guess.
* An additional notification script which requires more permissions than the mail ones, which are not problematic so I will add them. Can you give we some information about the notification plugins in use so I can add some in-line docs at least?

If someone assigns this issue to me, I will create a fix after holidays. To not set the complete system to permissive you can set only the icinga2_t domain to permissive until a fix is available for testing `semanage permissive -a icinga2_t`.

**Comment by pefmeister** [comment]
Hi Dirk,

you can leave the notification scripts out of this, that's a seperate issue, since I'm playing with custom notifications that are sending SMS and I just started to fix the permissions there. As for the sigkill issue: should I move this over to the monitoring plugins project?

Best regards
Stephan

**Comment by dgoetz** [comment]
I had a look into and I can simply allow sigkill in the execstrans interface of the Icinga 2 policy, so Icinga 2 can kill all domains it is allowed to transition into. I think this will solve the issue.

**Comment by pefmeister** [comment]
Sounds good. Any packages that I can test drive?

**Comment by dgoetz** [comment]
Fix is in the pull request.

@pefmeister No packages for now, but you can already make and install the policy package your own to test drive it.
