### ISSUE TITLE
Make warning about not-matching apply rules optional

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#5941]
Hi,

A customer of mine has lots of Icinga 2 reloads with a massive amount of not-matching apply rules. Because they are using Director it's not that easy to split the rules into different global zones.
They complain about their logs filling up with `warning/ApplyRule: Apply rule 'XX' for type 'Service'` messages.
Could they be made optional?
I can think of a setting within the `service` object like  `complain_about_no_match` or a setting in the various log outputs to filter out specifically this message or maybe different messages with a configurable filters.
I think I'd like the option in a service object most but maybe you can think of even better solutions.
Setting the logging to critical might not be an option because they would miss any other warning as well.
I can think of several solutions with external log management tools but none to work with the `FileLogger` object.

Cheers,
Thomas

**Comment by dnsmichi** [comment]
If you put such into a service object, or apply rule respectively, this just bloats your configuration for nothing in return. You shouldn't create a dependency between libicinga and libbase either, the service object doesn't know anything about optional logging features. Imho this is a no-go, feels wrong.

Generally speaking, if an apply rule does not match, it is key to let the user know about it. It then can be disabled, removed or something else.

If the application which generates the configuration, is not able to split among different deployment zones, I would fix that over there. Icinga 2 on its own just sees what's configured. And that is obviously wrong with obsolete rules for just this instance.

**Comment by widhalmt** [comment]
Thanks for the feedback. I asked the user to step into the conversation so the both of you could discuss directly if this is a reasonable request or not. I could only transfer words from you to them and back which would only lengthen the process.

**Comment by Simkimdm** [comment]
Hi dnsmichi,

we use the director to distribute the config across our cluster and cant specify any deployment zones.
So the only solution is that director create the right config for each zone?

**Comment by dnsmichi** [comment]
I would suggest that, since it is more of an application-deploys-config problem, than to hide logs for a specific use case which maybe should be avoided. It also is a clean approach, and doesn't require any code patches. Just adoption with managed global zones and the Director.

If you consider a feature which allows to disable logging for warning and a specific sub class, see #4282 for a similar discussion. This requires major code rewrites, and a sponsor.

**Comment by dnsmichi** [comment]
Proceed with applying changes in your application. I'm closing this here.

Cheers,
Michael
