### ISSUE TITLE
Duplicate entry constraint violations in 2.8

### ISSUE THREAD

**Issue by ekeih** [Icinga/icinga2#5947]
Hi,

we are currently experiencing database related problems in our Icinga2 cluster. Unfortunately we are not able to reproduce this in a reliable manner but we will try to describe our preliminary findings as detailed as possible. Hopefully someone with a deeper understanding of the internals of Icinga2 is able to understand the problem or can assist us during our debugging.

Our setup consists of a master zone (`master01` and `master02`) and three satellite zones with two satellites in each zone. The masters write the state into a MySQL database. Additionally we have several icingaweb2 frontends behind a loadbalancer that run on different hosts.

Our complete configuration is generated by puppet but that is probably unrelated to the issue.

## Expected Behavior
Icinga2 should write all updates to the database and the updates should be visible in icingaweb2.

## Current Behavior
It only happens from time to time and we are not sure how to trigger it. We suspect that many fast restarts of both masters increases the chance of a failure but we are not sure about this.

We reach a state where Icinga2 tries to write data to the database and fails due to different constraints. The actual query is part of a huge (about 15mb) MySQL query. We were able to extract one of the failing queries:

```
UPDATE icinga_scheduleddowntime SET actual_start_time = FROM_UNIXTIME(1513993500),  actual_start_time_usec = 0,  author_name = AuthorName,  comment_data = daily downtime for host project
ERROR 1062 (23000) at line 1: Duplicate entry '1-31771-2017-12-22 02:45:54-20' for key 'instance_id'
```

In this case the violatet constraint is:

```
UNIQUE KEY `instance_id` (`instance_id`,`object_id`,`entry_time`,`internal_downtime_id`)
```

We were able to observe some of the database entries that could cause the issue:

```

mysql> select object_id,entry_time,scheduled_start_time,scheduled_end_time,comment_data,name,instance_id,session_token,internal_downtime_id from icinga_scheduleddowntime ORDER BY object_id;

+-----------+---------------------+----------------------+---------------------+---------------------------------+-------------------------------------------------------------+-------------+---------------+----------------------+
| object_id | entry_time          | scheduled_start_time | scheduled_end_time  | comment_data                    | name                                                        | instance_id | session_token | internal_downtime_id |
+-----------+---------------------+----------------------+---------------------+---------------------------------+-------------------------------------------------------------+-------------+---------------+----------------------+
|      2173 | 2017-12-22 16:27:42 | 2017-12-23 05:00:00  | 2017-12-23 06:00:00 | daily downtime for host project | company.host01!master02.stage.icinga2.company-1513956462-30 |           1 |    1513957233 |                   45 |
|      2173 | 2017-12-22 16:27:16 | 2017-12-23 05:00:00  | 2017-12-23 06:00:00 | daily downtime for host project | company.host01!master01.stage.icinga2.company-1513956436-53 |           1 |    1513957233 |                   44 |
|      2174 | 2017-12-22 16:27:43 | 2017-12-23 05:00:00  | 2017-12-23 06:00:00 | daily downtime for host project | company.host02!master02.stage.icinga2.company-1513956463-41 |           1 |    1513957233 |                   50 |
|      2174 | 2017-12-22 16:27:15 | 2017-12-23 05:00:00  | 2017-12-23 06:00:00 | daily downtime for host project | company.host02!master01.stage.icinga2.company-1513956435-27 |           1 |    1513957233 |                   48 |
|      2176 | 2017-12-22 16:27:16 | 2017-12-23 05:00:00  | 2017-12-23 06:00:00 | daily downtime for host project | company.host03!master01.stage.icinga2.company-1513956436-59 |           1 |    1513957233 |                   46 |
|      2176 | 2017-12-22 16:27:42 | 2017-12-23 05:00:00  | 2017-12-23 06:00:00 | daily downtime for host project | company.host03!master02.stage.icinga2.company-1513956462-22 |           1 |    1513957233 |                   47 |
|      2177 | 2017-12-22 16:27:43 | 2017-12-23 05:00:00  | 2017-12-23 06:00:00 | daily downtime for host project | company.host04!master02.stage.icinga2.company-1513956463-33 |           1 |    1513957233 |                   57 |
|      2177 | 2017-12-22 16:27:16 | 2017-12-23 05:00:00  | 2017-12-23 06:00:00 | daily downtime for host project | company.host04!master01.stage.icinga2.company-1513956436-61 |           1 |    1513957233 |                   53 |
```

After the first start we had every `object_id` only once while the `name` contained either `master01` or `master02`. After a lot of restarts of both masters we got the state you can see above where we have duplicate `object_ids`. One time with `master01` in `name` and another time with `master02`.
This alone should not be a problem (except the fact that it could couse duplicate downtime definitions). But later we can observe the following error:

```
[2017-12-22 12:37:44 +0100] critical/IdoMysqlConnection: Error "MySQL server has gone away" when executing query "DELETE FROM icinga_comments WHERE instance_id = 1 AND session_token <> 1513942336"
```

Our current guess is something like this:
- For some reason both masters appear in the names of the duplicate downtimes. As there can only be one active master we do not know how this happens.
- At some point Icinga2 decides to remove all existing downtimes and tries to write them into the database again. This is really just a guess based on the queries above.
- Now `instance_id`, `object_id` and `entry_time` are the same. Before there was a difference in `entry_time`. We do not know how `internal_downtime_id` is handled at this point but we assume that both inserts include the same value and as a result the constraint is violated.
- As a result no updates a written to the database. According to the logs of the masters and satellites the checks are still executed and notifications are sent. But without the database the icingaweb2 frontend is not updated anymore.

Today we observed a similar problem with the `icinga_customvariables` table:

```
INSERT INTO icinga_customvariables (config_type, instance_id, is_json, object_id, varname, varvalue) VALUES ('1', 1, '1', 795, 'check', '{some json blob}')
ERROR 1062 (23000) at line 1: Duplicate entry '795-1-check' for key 'object_id_2'
```

Which violates:
```
UNIQUE KEY `object_id_2` (`object_id`,`config_type`,`varname`)
```

## Possible Solution
We are not aware of a solution. As far as we understand the issue is that Icinga2 tries to write duplicate entries.
In some cases we were able to remove problematic database entries. But it was not always possible.

## Steps to Reproduce (for bugs)
Unfortunately we have currently no reliable way to reproduce the issue. But it happens often enough to block our go live with Icinga2 2.8. Many fast restarts of the masters seem to increase the chance to trigger the issue. If you have any idea how to test this more reliable we are happy to try it.

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:

```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.3 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 2.6.32-042stab125.5
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: e3e567db57ba
```

* Enabled features (`icinga2 feature list`):

```
# icinga2 feature list
Disabled features:
Enabled features: api checker command ido-mysql mainlog notification
```

* Icinga Web 2 version and modules (System - About):

```
Icinga Web 2 Version 2.5.0
```

We also have an additional internal icingaweb2 module that displays some additional information. It only reads from the database but it does not make any changes.

* Config validation (`icinga2 daemon -C`):

```
# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.8.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Please read the upgrading documentation for v2.8: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
information/ApiListener: My API identity: somehostname.icinga2.stage.master01
information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 22553, rate: 4019.23/s (241154/min 241154/5min 241154/15min);
information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 0, rate:  0/s (0/min 0/5min 0/15min);
warning/ApplyRule: Apply rule 'DOWNTIME NAME' (in /etc/icinga2/zones.d/globals.d/scheduleddowntimes.conf: 3:1-3:84) for type 'ScheduledDowntime' does not match anywhere!
=== We have about 30 of this warnings for downtimes and services which do not match anywhere. We will fix this during our migration but it should not be related to the actual issue ===
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 6 Zones.
information/ConfigItem: Instantiated 8 Endpoints.
information/ConfigItem: Instantiated 3 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 77120 Notifications.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 11 CheckCommands.
information/ConfigItem: Instantiated 234 Downtimes.
information/ConfigItem: Instantiated 395 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2047 Hosts.
information/ConfigItem: Instantiated 13138 Comments.
information/ConfigItem: Instantiated 229 UserGroups.
information/ConfigItem: Instantiated 36912 Dependencies.
information/ConfigItem: Instantiated 233 Users.
information/ConfigItem: Instantiated 43347 Services.
information/ConfigItem: Instantiated 1 ServiceGroup.
information/ConfigItem: Instantiated 100 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

Our actual amount of hosts and services is higher but they do not appear here because we tested our puppet configuration with a development branch.

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

Due to the amount of Icinga2 instances this is quite a bit of output and needs some proper cleanup to remove internal names and customer information. If you think this information is necessary to solve the issue, let us know and we will cleanup the output and post it as an update.

Thank you for any help in advance!

**Comment by dnsmichi** [comment]
That unique key doesn't exist in the 2.8.0 schema, are you sure that you've successfully upgraded the database?

https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/upgrade/2.8.0.sql

**Comment by ekeih** [comment]
Hi,
thank you for your response. We use the current version of the database schema:

```
mysql> select * from icinga_dbversion;
+--------------+----------+---------+---------------------+---------------------+
| dbversion_id | name     | version | create_time         | modify_time         |
+--------------+----------+---------+---------------------+---------------------+
|            1 | idoutils | 1.14.3  | 2018-01-02 14:46:42 | 2018-01-02 14:46:42 |
+--------------+----------+---------+---------------------+---------------------+
```

In your linked sql file the unique key is removed in https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/upgrade/2.8.0.sql#L57

But if you do a fresh installation instead of an upgrade https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/mysql.sql#L981 gets used where the unique key is still created.

Best regards

**Comment by dnsmichi** [comment]
Oh. This is a bug then, thanks for noticing. @lippserd seems this slipped into 2.8.0.

**Comment by ekeih** [comment]
Alright, thank you for confirming the issue. I am surprised that you scheduled this for 2.9.0 as this breaks all new installations.

As a note for other people with the same problem:
As a workaround we applied the https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/upgrade/2.8.0.sql file to remove the unique keys. You have to comment out the for `CREATE INDEX` statements at the end.

**Comment by dnsmichi** [comment]
I'm assigning tasks always to the next major version, as the merge happens to master. Then backports can happen. This has nothing to do with priorities, I'll discuss that with @lippserd once he returns from holiday.

Cheers,
Michael

**Comment by ekeih** [comment]
Thank you for the clarification :)
