### ISSUE TITLE
sort options for "icinga2 ca list"

### ISSUE THREAD

**Issue by cstegm** [Icinga/icinga2#5950]
## Expected Behavior
For the command "icinga2 ca list" options to sort the list should be provided

## Current Behavior
The list is not sorted or sorted by fingerprint. 

## Possible Solution
* Provide a timestamp format which can be used with sort
* Provide Filter options for "icinga2 ca list"

**Comment by Crunsher** [comment]
I don't think we should add all of this to the command, other tools like sort are best equipped to handle this. My suggestion is to add a switch like `--raw` which removes the column delimiters and headers and prints the timestamp in the first column. Maybe have them comma separated.

**Comment by dnsmichi** [comment]
`--json` already is implemented for those needing a programmatic approach.

The timestamp cannot be changed for now, the underlaying problem is an OpenSSL function which only is available in 1.0.2 but not 1.0.1. More details in #5572 

Thinking again about it, this likely isn't something we're gonna add. @Crunsher feel free to close.

**Comment by Crunsher** [comment]
Aye
