### ISSUE TITLE
Custom notifications are filtered by object state

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icinga2#5952]
I'm not sure if this is intended behaviour or a bug, but since the current behaviour does not seem to make much sense to me I'm opening this issue.

I have a user object that is used for phone notifications during the night and on holidays, which is defined like this: 

    object User "phone-alarm" {
        import "generic-user"

        display_name = "Phone Alarm"
        email = "phonealarm@example.org"

        enable_notifications = true
        states = [ Critical, Down ]
        types = [ Problem, Custom ]
    }

There are two cases in which a notification should be sent to this user: 

1. One of the services or hosts or services the a notification is configured for this user is in 'Critical' state
2. A custom notification is triggered via script (one example is a weekly test alert for the phone alert, but there are some others). 

## Expected Behavior
A notification is sent to the phone-alert user in both cases, particularly the custom notifications are sent regardless of the state the service or host is in

## Current Behavior
1. The first case (service/host goes into Critical/Down state) works as expected. 
2. The second case (custom notification) only is triggered when the service or host it is issued for is in Critical or Down state, respectively. When the service is in any other state, no custom notifications are triggered.

## Environment
Icinga 2.7.1-1 on CentOS 7.4, reproducable on other versions as well (2.8.0 is in the test environment).

**Comment by dnsmichi** [comment]
How does that script and the call look like for custom notifications?

Cheers,
Michael

**Comment by peteeckel** [comment]
Hi Michael, 

at the customer's site I'm using an internal Perl-based framework for the API connection (which would be quite difficult to reproduce here as it contains a couple of other functions as well), but the problem can easily be reproduced using any REST API client (i.e. PAW, curl).

The following Python code (generated by Paw and stripped of customer information) can be used to reproduce the issue:

```
import requests
import json

def send_request():
    try:
        response = requests.post(
            url="https://test.example.com:5665/v1/actions/send-custom-notification",
            headers={
                "Accept": "application/json",
                "Authorization": "Basic c2VjOk9rc1NUMVJFWGxLQzJPMj9vVEAqNlcnTg==",
                "Content-Type": "application/json; charset=utf-8",
            },
            data=json.dumps({
                "author": "sec",
                "filter": "host.name==\"host.example.com\"&&service.name==\"testalarm\"",
                "comment": "Test - bitte ignorieren",
                "type": "Service"
            })
        )
        print('Response HTTP Status Code: {status_code}'.format(
            status_code=response.status_code))
        print('Response HTTP Response Body: {content}'.format(
            content=response.content))
    except requests.exceptions.RequestException:
        print('HTTP Request failed')
```

**Comment by peteeckel** [comment]
Maybe curl is easier to use ad-hoc:

```
curl -X "POST" "https://test.example.com:5665/v1/actions/send-custom-notification" \
     -H 'Accept: application/json' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -u 'sec:verysecretpassword' \
     -d $'{
  "author": "sec",
  "filter": "host.name==\\"host.example.com\\"&&service.name==\\"testalarm\\"",
  "comment": "Test - bitte ignorieren",
  "type": "Service"
}'
```

**Comment by dnsmichi** [comment]
So the custom notification is not forced, nor broadcasted. Then it will only be sent if the `states` filter applies. If you want it to be sent all the time, you need to force it and overrule any specific filters, not only states but also period for example.

Works as designed, I'd say :)

**Comment by peteeckel** [comment]
I might be wrong, but won't forced Custom notifications be sent to users that do not have Custom notifications enabled as well?

**Comment by dnsmichi** [comment]
Oh. Yes, that's true. So you need a reliable states filter then, if you want to filter away those Custom notifications with OK, Warning, Critical. Why not doing that in the notification object instead, one especially made for this user?

**Comment by peteeckel** [comment]
That's the workaround I was considering, but it doesn't seem very elegant. 

Considering that custom notifications do not have any state associated with them and do not cause any state change, it does not seem very intuitive to filter them by the state the referenced object happens to have at the time of notification. Vice versa, I can't think of a use case where filtering a custom notification by the state of the object would make sense (which could be due to a lack of imagination, I admit :-)).

**Comment by dnsmichi** [comment]
I was reading this yesterday for an hour or so, and I think I now understand the main issue with Custom notifications here. I'm not entirely sure how to put this into the code right now. A defined `period` attribute should also filter away a `Custom` notification, right? It only is about the `states` filter which is only necessary for `Problem` notifications.

Need to read and test a bit more.

**Comment by peteeckel** [comment]
Yes, periods, downtimes etc. should definitely affect custom notifications as they are valid for an object as a whole.

I think the main idea is that a condition/filter based on object state should only affect notifications that are associated with a state as well. So while state change-initiated notifications such as Problem,  Recovery and probably FlappingStart/End notifications should be affected by the filter, others such as Acknowledgement, DowntimeStart/End/Removed, and Custom should not.

**Comment by dnsmichi** [comment]
I read a little more about it yesterday. I do have a patch in #6016, still it needs proper tests before merge. Put on my TODO list for the February tasks.
