### ISSUE TITLE
Disabling both active and passive checks on a host has no effect

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#5956]
## Expected Behavior

I configure a host for the first time and disable both active and passive checks – and it works OOTB.

## Current Behavior

I configure a host for the first time and disable both active and passive checks – and the agent doesn't care.

## Possible Solution

I'd like to hear one from you.

## Steps to Reproduce (for bugs)

1. Clone [my I2 master](https://github.com/Al2Klimov/graphite-web-div0) and do `vagrant up --provider=virtualbox`
2. Download [the Win10 VM w/ M$ Edge](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
3. Once (1) provisioned, install Icinga 2.8 on (2) and connect that agent to (1) via the graphical agent wizard:
    * FQDN: `MSEDGEWIN10`
    * Endpoints:
        1. :
            * Name: `ubuntu-xenial`
            * Connect: yes
            * Host: see `/sbin/ifconfig` (2nd NIC)
    * Listen: no
    * Accept config: yes
    * Accept commands: yes
    * Run as user: -/-
    * Install NSC++: yes (typical install)
4. Open [Icinga Web 2](http://localhost:8080/icingaweb2/monitoring/host/show?host=MSEDGEWIN10&service=network-windows) and wait...

## Context

https://github.com/Icinga/icingaweb2-module-graphite/issues/79#issuecomment-353642710

## Your Environment

See above.

**Comment by dnsmichi** [comment]
Please share the synced configuration files from `%ProgramData%\var\lib\icinga2\api\zones`.

Also, ensure that the sync actually took place. I could think of a local installation in `conf.d` with the exact same host name, which prevents the sync. The local configuration is still actively executed by the client then.

Such reload failures will be logged too.

**Comment by Al2Klimov** [comment]
```
alexanders-mbp:graphite-web-div0 aklimov$ ls -lhAR zones
total 0
drwxr-xr-x  4 aklimov  staff   128B  8 Jan 17:26 MSEDGEWIN10

zones/MSEDGEWIN10:
total 8
-rwxr-xr-x  1 aklimov  staff    17B  8 Jan 17:59 .timestamp
drwxr-xr-x  3 aklimov  staff    96B  8 Jan 17:26 _etc

zones/MSEDGEWIN10/_etc:
total 8
-rwxr-xr-x  1 aklimov  staff   253B  8 Jan 17:26 MSEDGEWIN10.conf
alexanders-mbp:graphite-web-div0 aklimov$ find zones -type f -print0 |xargs -0 head -n 1000
==> zones/MSEDGEWIN10/_etc/MSEDGEWIN10.conf <==
object Host "MSEDGEWIN10" {
	check_command = "hostalive"
	enable_active_checks = false
	enable_passive_checks = false
	vars.os = "Windows"
}

apply Service "network-windows" {
	check_command = "network-windows"
	assign where host.vars.os == "Windows"
}

==> zones/MSEDGEWIN10/.timestamp <==
1515430690.553567alexanders-mbp:graphite-web-div0 aklimov$
```

> I could think of a local installation in `conf.d` with the exact same host name

Good catch. Confirmed:

```
/*
 * (...)
 */

/*
 * (...)
 */

object Host NodeName {
  /* Import the default host template defined in `templates.conf`. */
  import "generic-host"

  /* Specify the address attributes for checks e.g. `ssh` or `http`. */
  address = "127.0.0.1"
  address6 = "::1"

  /* Set custom attribute `os` for hostgroup assignment in `groups.conf`. */
  vars.os = "Windows"

  /* Define disks and attributes for service apply rules in `services.conf`. */
  vars.disks["disk"] = {
    /* No parameters. */
  }
  vars.disks["disk C:"] = {
    disk_win_path = "C:"
  }

  /* Define notification mail attributes for notification apply rules in `notifications.conf`. */
  vars.notification["mail"] = {
    /* The UserGroup `icingaadmins` is defined in `users.conf`. */
    groups = [ "icingaadmins" ]
  }
}
```

... but IW2 shows the custom vars as defined by the cluster config. (OS only.)

> The local configuration is still actively executed by the client then.

But this would be a local host object whose check results shall not be synced over the cluster (at least I think so) especially if the agent doesn't know about the legally synced host object which would be the case in case of a failed sync.

**Comment by Al2Klimov** [comment]
Tested w/ empty `conf.d` – works as expected.

But the previous scenario doesn't work as expected. (Icinga should fail to sync.)

**Comment by dnsmichi** [comment]
Right, this functionality was required by the recently removed bottom up mode. Child zones generally trust parent zones and will sync check result message there. 

There are plans to remove the "conf.d" inclusion on clients in #5605 where this could be targeted as well. I don't think this is "side effect free", so this needs a deeper analysis there.

For now, this is documented inside the troubleshooting docs: https://www.icinga.com/docs/icinga2/latest/doc/15-troubleshooting/#check-thresholds-not-applied

Yours is a similar thing, not only thresholds but other attributes.

Sync won't fail, as it receives the configuration "live". The reload will fail, you see that in the logs.
To fix the sync, one needs staged config syncs in #4354 

I'm closing this one, thanks for the report.

Cheers,
Michael

**Comment by Al2Klimov** [comment]
> There are plans to remove the "conf.d" inclusion on clients

Of course this would be not "side effect free". I'd suggest to add a switch to node setup and a check box to the WinNT wizard.
