### ISSUE TITLE
Windows Service only warning

### ISSUE THREAD

**Issue by patrickwienecke** [Icinga/icinga2#5966]
Windows Service return false value

The Documentation explain, that Windows Service becomes critical, if service not running. 
Unfortunately, although we dont set the service_win_warn the return value is warning
https://www.icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#windows-plugins

Object 'xxxxxxx!Windows Service:xxxxxxxx' of type 'Service':
  % declared in '/etc/icinga2/zones.d/xxxxxx/services.conf', lines 414:1-414:69
  * __name = "xxxxxxx!Windows Service:xxxxxxx"
  * action_url = ""
  * check_command = "service-windows"
    % = modified in '/etc/icinga2/zones.d/xxxxxxx/services.conf', lines 416:3-416:35
  * check_interval = 60
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.conf', lines 31:3-31:22
  * check_period = ""
  * check_timeout = null
  * command_endpoint = "xxxxxxx"
    % = modified in '/etc/icinga2/zones.d/xxxxxxx/services.conf', lines 417:3-417:46
  * display_name = "Windows Service:xxxxxxx"
--
    * notes = "xxxx"
    * notification
      * mail
        % = modified in '/etc/icinga2/zones.d/global-templates/templates.conf', lines 34:4-36:1
        * groups = [ "icingaadmins" ]
    * service_win_service = "xxxxxxxxxxx"
  * volatile = false
  * zone = "master"
    % = modified in '/etc/icinga2/zones.d/xxxxxxx/services.conf', lines 414:1-414:69

   WARN  ├─ Windows Service:xxxxx(For 44m 2s)
   WARN  ├─ Windows Service:xxxxx (For 44m 2s

## Your Environment

* Version used (`icinga2 --version`):r2.8.0-1 
* Operating System and version: Linux Debian 8
* Enabled features (`icinga2 feature list`): 
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by mcktr** [comment]
Hi,

this is a known issue in the current version 2.8.0.

See #5849 for more details and the fix #5851 :)

Kind regards,
Michael
