### ISSUE TITLE
Why i cant run "icinga2 node list" as some topic which i have searched?

### ISSUE THREAD

**Issue by AkatsukiPain** [Icinga/icinga2#5975]
I have done the task "icinga2 node wizard" on client with no error. But when i run "icinga2 node list", nothing appear as the following picture:

![image](https://user-images.githubusercontent.com/14358073/34885198-c39aef7a-f7f1-11e7-9e18-e8a2d966b95d.png)

Can anyone help me about this problem ?

**Comment by AkatsukiPain** [comment]
This is a picture about the command which i have searched

![image](https://user-images.githubusercontent.com/14358073/34885260-f91ce0fe-f7f1-11e7-9d19-3de39ad2f45b.png)

**Comment by MaBauMeBad** [comment]
The functions you are trying tu use are deprectaed and was removed in the 2.8.0 release.

**Comment by lazyfrosch** [comment]
See
* [CHANGELOG.md](https://github.com/Icinga/icinga2/blob/master/CHANGELOG.md#260-2016-12-13)
* [Upgrading notes](https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#removed-bottom-up-client-mode)
* https://github.com/Icinga/icinga2/issues/4798
