### ISSUE TITLE
Missing #include <errno.h>

### ISSUE THREAD

**Issue by efuss** [Icinga/icinga2#6001]
I still have one more tiny pkgsrc [patch](https://github.com/Icinga/icinga2/files/1640313/patch-lib_base_unix.hpp.txt) in order to compile Icinga2 on NetBSD.
I seem to have forgotten to report this when pkgsrc'ing Icinga2, but stumbled over it during the update to 2.8 (all my other patches have become obsolete by being imported, thanks).

**Comment by Crunsher** [comment]
I just noticed you didn't include your information in the patch, if you want credit for the changes, please make a PR.

**Comment by efuss** [comment]
I don't do git (yet). My GitHub account is efuss.
I can live without credit for a one-line patch, though.

**Comment by Crunsher** [comment]
Alright, thanks for your contribution anyways 👍
