### ISSUE TITLE
Active Directory user backend is not available

### ISSUE THREAD

**Issue by riponbanik** [Icinga/icinga2#6002]
Configuration -> Application -> User Backends - Active Directory is not listed as backed - only database and external are listed.

## Expected Behavior
It should list LDAP and ActiveDirectory like as in User Group Backend

## Current Behavior
Configuring AD authentication via .ini file breaks default database authentication (does not allow log into console)

## Possible Solution
Allow configuration via console and show in the logs possible issue

## Steps to Reproduce (for bugs)
Followed the article below to configure ad authentication -

https://www.icinga.com/docs/icingaweb2/latest/doc/05-Authentication/

Sample config is -

sudo cat /etc/icingaweb2/authentication.ini

[auth_ad]
resource = "myad"
filter = "!(objectClass=computer)"
backend = "msldap"

sudo cat /etc/icingaweb2/groups.ini

[icingaweb2]
backend = "db"
resource = "icingaweb_db"

[auth_ad]
backend = "msldap"
resource = "myad"

sudo cat /etc/icingaweb2/resources.ini

[icingaweb_db]
type = "db"
db = "mysql"
host = "localhost"
port = ""
dbname = "icingaweb"
username = "icingaweb"
password = "xxxx"
charset = ""
persistent = "0"
use_ssl = "0"

[icinga_ido]
type = "db"
db = "mysql"
host = "localhost"
port = ""
dbname = "icinga"
username = "icinga"
password = "xx"
charset = ""
persistent = "0"
use_ssl = "0"

[myad]
type        = ldap
hostname    = xxxx
port        = 389
root_dn     = "DC=xxx,DC=xx,DC=gov,DC=xx"
bind_dn     = "CN=xxx,OU=AWS,OU=Service Accounts,DC=xxx,DC=xx,DC=xx,DC=xx"
bind_pw     = "xxxx#"

sudo cat /etc/icingaweb2/config.ini

[global]
show_stacktraces = "1"
config_backend = "db"
config_resource = "icingaweb_db"

[logging]
log = "php"
level = "ERROR"
application = "icingaweb2"

[authentication]
default_domain = "xxx"

## Context
Installed icinga2 using the ansible module https://github.com/Icinga/icinga2-ansible. 
During configuration authentication has been configured as Database. Wanted to configure AD authentication for users.

## Your Environment

* Version used (`icinga2 --version`):

icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.11.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Operating System and version:
* Enabled features (`icinga2 feature list`):
icinga2 feature list
Disabled features: api compatlog debuglog elasticsearch gelf influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: checker command graphite ido-mysql mainlog notification

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version
2.5.0
Git commit
ebe1917b152b786cc708abe5215fd0c4be7c4237
Git commit date
2017-11-27

* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.8.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApplyRule: Apply rule 'nrpe-users' (in /etc/icinga2/conf.d/custom/nepre_services.conf: 1:0-1:25) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'nrpe-disk-/' (in /etc/icinga2/conf.d/custom/nepre_services.conf: 9:1-9:27) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 2 UserGroups.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 79 Notifications.
information/ConfigItem: Instantiated 211 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 14 Hosts.
information/ConfigItem: Instantiated 6 HostGroups.
information/ConfigItem: Instantiated 16 Downtimes.
information/ConfigItem: Instantiated 5 TimePeriods.
information/ConfigItem: Instantiated 2 Users.
information/ConfigItem: Instantiated 1 Comment.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 166 Services.
information/ConfigItem: Instantiated 14 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by mcktr** [comment]
Hi,

this is the wrong issue tracker, your problem is related to Icinga Web 2. The correct issue tracker you can find here: [Icinga/icingaweb2](https://github.com/Icinga/icingaweb2/issues).

I also recommend to hop on the community channels for configuration questions.

Best regards
Michael

**Comment by riponbanik** [comment]
@mcktr - Thanks. I have opened it into that channel. It seems to me a bug, not a config issue since it does not show any error but breaks existing auth.
