### ISSUE TITLE
[ubuntu package] MySQL error during upgrade - illegal mix of collations

### ISSUE THREAD

**Issue by tackerm** [Icinga/icinga2#6003]
Hi guys

I am having an issue with upgrading our icinga packages to 2.8.1 (from `http://packages.icinga.com/ubuntu/`)

When I try to update the icinga2 packages, I get the following mysql error from dbconfig:
```
> apt-get dist-upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  icinga2 icinga2-bin icinga2-common icinga2-ido-mysql libicinga2
5 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/2'589 kB of archives.
After this operation, 6'144 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Preconfiguring packages ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
(Reading database ... 128533 files and directories currently installed.)
Preparing to unpack .../icinga2-ido-mysql_2.8.1-1.xenial_amd64.deb ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
Unpacking icinga2-ido-mysql (2.8.1-1.xenial) over (2.8.0-1.xenial) ...
Preparing to unpack .../icinga2_2.8.1-1.xenial_amd64.deb ...
Unpacking icinga2 (2.8.1-1.xenial) over (2.8.0-1.xenial) ...
Preparing to unpack .../icinga2-bin_2.8.1-1.xenial_amd64.deb ...
Unpacking icinga2-bin (2.8.1-1.xenial) over (2.8.0-1.xenial) ...
Preparing to unpack .../libicinga2_2.8.1-1.xenial_amd64.deb ...
Unpacking libicinga2 (2.8.1-1.xenial) over (2.8.0-1.xenial) ...
Preparing to unpack .../icinga2-common_2.8.1-1.xenial_all.deb ...
Unpacking icinga2-common (2.8.1-1.xenial) over (2.8.0-1.xenial) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu21) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up icinga2-common (2.8.1-1.xenial) ...
Setting up libicinga2 (2.8.1-1.xenial) ...
Setting up icinga2-bin (2.8.1-1.xenial) ...
Setting up icinga2-ido-mysql (2.8.1-1.xenial) ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
dbconfig-common: writing config to /etc/dbconfig-common/icinga2-ido-mysql.conf
creating database backup in /var/cache/dbconfig-common/backups/icinga2-ido-mysql_2.8.0-1.xenial.2018-01-18-06.29.44.
applying upgrade sql for 2.8.0-1.xenial -> 2.8.1.
error encountered processing /usr/share/dbconfig-common/data/icinga2-ido-mysql/upgrade/mysql/2.8.1:
mysql said: mysql: [Warning] mysql: Empty value for 'port' specified. Will throw an error in future versions ERROR 1267 (HY000) at line 56: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='
dbconfig-common: icinga2-ido-mysql configure: aborted.
dbconfig-common: flushing administrative password
dpkg: error processing package icinga2-ido-mysql (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up icinga2 (2.8.1-1.xenial) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Errors were encountered while processing:
 icinga2-ido-mysql
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Our mysql server is indeed configured to use `utf8_unicode_ci`:
```
[mysqld]
character-set-server=utf8
collation-server=utf8_unicode_ci
```
The mysql server was installed / configured _before_ installing icinga2 and hasn't been changed since, so I wonder why icinga tries to use a different collation.

So - how can I teach icinga to play nicely with the server's collation? 

(N.B: the `[Warning] mysql: Empty value for 'port' specified. Will throw an error in future versions` warning can be resolved by setting `dbc_dbport='0'` in `/etc/dbconfig-common/icinga2-ido-mysql.conf` - this should probably be fixed in the package too)

Many thanks!

**Comment by Crunsher** [comment]
We ran into troubles with collations and character sets more often than we should, pesky little things. For the warning you could create a new ticket (or a PR even!)


@dnsmichi Could you have a look at this? AFAIK you have the most experience dealing with this

**Comment by dnsmichi** [comment]
The 2.8.1.sql doesn't do anything with collations here, it just drops unneeded indexes if they exist in from a fresh 2.8.0 setup. 

The error seems to be coming from the underlaying database configuration.

Mine looks like this where I did the release tests and upgrade tests with:

```
MariaDB [(none)]> show VARIABLES LIKE 'coll%';
+----------------------+-----------------+
| Variable_name        | Value           |
+----------------------+-----------------+
| collation_connection | utf8_general_ci |
| collation_database   | utf8_general_ci |
| collation_server     | utf8_general_ci |
+----------------------+-----------------+
3 rows in set (0.02 sec)
```

utf8_unicode_ci isn't supported by the IDO schema.

**Comment by tackerm** [comment]
Thanks guys!

> utf8_unicode_ci isn't supported by the IDO schema.

Does this mean there is a requirement to use `utf8_general_ci`? I couldn't find anything in the [schema](https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/mysql.sql#L11), except that it stores a backup of the original `collation_connection` variable...

My config looks like this:
```
mysql> show VARIABLES LIKE 'coll%';
+----------------------+-----------------+
| Variable_name        | Value           |
+----------------------+-----------------+
| collation_connection | utf8_general_ci |
| collation_database   | utf8_unicode_ci |
| collation_server     | utf8_unicode_ci |
+----------------------+-----------------+
3 rows in set (0.00 sec)
```

I could pre-set the collation of the connection by setting something like `init_connect='SET collation_connection = utf8_unicode_ci'` in the mysql server config, but IMO it is the responsibility of the mysql client (i.e. icinga) to make sure that it uses the right collation - either by setting the collation to the same collation as the database after establishing the connection, or by converting values fetched from the DB when running collation-sensitive queries. 

This [SO article](https://stackoverflow.com/questions/3029321/troubleshooting-illegal-mix-of-collations-error-in-mysql?rq=1) suggests that the problem is somewhat typical for stored procedures, which [is the case here](https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/upgrade/2.8.1.sql#L56) too. Maybe a potential workaround could be to not use stored procedures, or to ensure the collation is correct before running the upgrade queries?

**Comment by tackerm** [comment]
So... is there any "official conclusion" on this issue? 😁 (asking because this is currently preventing me from doing a clean upgrade) 

Should I change the database to `utf8_general_ci`, or change the connection to `utf8_unicode_ci`, or is it perhaps something that could / should be fixed on the package's side?

**Comment by dnsmichi** [comment]
Take a snapshot of your current production VM and test those changes. Or you'll go with manually deleting the indexes and skipping the package upgrades (not sure if that works though). From Icinga 2's point of view it is safe to assume that we only test and support utf8_general_ci (but the schema isn't really utf8 ready, don't set that in your Icinga Web 2 resource.ini). Please move further discussion how others solve such things into the community channels.
