### ISSUE TITLE
Different ouput of the check

### ISSUE THREAD

**Issue by florinagios** [Icinga/icinga2#6011]
I've created a service template using the check command mssql_health to check the health of an availability group, mode availability-group-health.
There is a difference in the output of the check in the GUI (it shows just OK - no problems) and running from the command line it has the following output that i would like to see in the GUI

On primary:
OK - availability group XXX_AG has synch. status healthy
On secondary:
OK - This is a secondary replica of group XXX_AG. For a reliable status you have to ask the primary replica

## Expected Behavior
on a primary replica
OK - availability group XXX_AG has synch. status healthy 
or on  secondary
OK - This is a secondary replica of group XXX_AG. For a reliable status you have to ask the primary 

## Current Behavior
Output of the check is OK - no problems

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`): 2.8.0
* Operating System and version: CentOS
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About): 2.5.0
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

Command line used: 
./check_mssql_health --port=1433 --hostname=hostnameXXX --username=XXX --password=XXXpassword --mode=availability-group-health

**Comment by Crunsher** [comment]
I'm sorry but I fail to understand your problem :/

**Comment by florinagios** [comment]
When i'm checking this service in Overview i can see just "OK - no problems" as output but when i run the command in command line i receive OK - availability group XXX_AG has synch. status healthy

**Comment by dnsmichi** [comment]
That doesn't sound like a bug to me, but a configuration problem. Please continue on the community channels such as https://monitoring-portal.org

**Comment by dgoetz** [comment]
I have no mssql here at the moment, but ITL sets report to short by default (`vars.mssql_health_report = "short"`). You can verify this by adding to your commandline `--report short` and if this changes the output like you mentioned, set the variable to `long` in Icinga 2.

**Comment by florinagios** [comment]
Many thanks, that what i was looking for.
