### ISSUE TITLE
Add table header after "Add Columns to List Views"

### ISSUE THREAD

**Issue by doctore74** [Icinga/icinga2#6013]
After adding columns in list views there are no column headers. It is difficult to find out where the displayed values can be assigned. 

Used how-to:
https://www.icinga.com/docs/icingaweb2/latest/modules/monitoring/doc/11-Add-Columns-List-Views/

## Expected Behavior
Adding an additional column should provide a relating header.

## Current Behavior
No header information displayed.

## Possible Solution
...

## Steps to Reproduce (for bugs)
https://<IC-SERVER>/icingaweb2/monitoring/list/hosts?addColumns=host_name,host_address,host_state

## Context
I'am trying to customize the provided information for a better user experience.
If information like "is in downtime and f.e. host state, ..." is added you get just a output like "0 0 0 1".
This isn't very helpful.

## Your Environment
* Version used (`icinga2 --version`): r2.8.0-1
* Operating System and version: CentOS 7.4.1708
* Enabled features (`icinga2 feature list`): api checker debuglog graphite ido-mysql mainlog
* Icinga Web 2 version and modules (System - About): 2.5.0
* Config validation (`icinga2 daemon -C`): OK

**Comment by dnsmichi** [comment]
Not sure what you mean exactly. Either way, this is the wrong project. Please create an issue over at icinga/icingaweb2.
