### ISSUE TITLE
Move init configuration from getting-started

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#6018]
Chapter 2: Getting Started should not discuss the configuration of init systems imho. It should be moved into a different chapter, like 04 Configuring Icinga 2. Getting started could just have a quick overview over how to start the Icinga 2 service on different sytems and link to the detailed configuration.

Thoughts?

**Comment by dnsmichi** [comment]
It's overly bloated, yes. Getting Started should focus on the key elements, and explain that in short. I do have an idea for the Icinga Web 2 setup too.

**Comment by KalleDK** [comment]
I do agree also - thought I would also suggest adding the init.conf file, I can't seem to find any documentation on it - and it seems to be hardcoded

**Comment by dnsmichi** [comment]
What do you mean?

**Comment by dnsmichi** [comment]
I've moved the systemd watchdog thing into troubleshooting where this belongs. The rest is more or less cleaning things up in the linked PR.
