### ISSUE TITLE
Disk check for Windows

### ISSUE THREAD

**Issue by negirak1** [Icinga/icinga2#6021]
Hi ,
Did not get any platform to raise a query so raising an issue here.
@Admin you always suggest to refer icinga2 monitoring documents but i did not find anywhere ,any templates for windows disk check .How the host.conf,constant.conf and services.conf should look like in order to monitor remote Windows host.

I have googled also but did not get anything to work for .I am working on to monitor disk report disk usage/ my remote host which is window server.Please share any pointer for templates or share sample template how these conf should look like.
Also tried to check apache service of host machine and getting this result.
![apache check](https://user-images.githubusercontent.com/35619784/35181297-3a12d0d4-fde5-11e7-8198-ec774129d0b9.JPG)

**Comment by dnsmichi** [comment]
This isn't really the best location to ask for basic help, we discuss bugs and feature requests on GitHub. 

Please hop onto the community channels (lists.icinga.org, monitoring-portal.org) and kindly ask your question. Include more details about your setup too.
