### ISSUE TITLE
icinga repo doesn't see third party php packages

### ISSUE THREAD

**Issue by gitthismoney** [Icinga/icinga2#6027]
hello - having some trouble upgrading icinga from repo recently. yum fails looking for a rh-php* packages which are not available on my centos box. I run webtatic centos repo for php71. 

is there a recommended way to upgrade when not using official rh-php packages? 

cheers,
Josh

**Comment by mcktr** [comment]
Hi,

please create issues related to our packaging over here: [icinga/icinga-packaging](https://github.com/Icinga/icinga-packaging/issues).

Apart from that, please have a look at the following issues, I'll guess this is your problem and we are already aware of that, so you don't need to create an extra issue for it.

https://github.com/Icinga/icinga-packaging/issues/89
https://github.com/Icinga/icinga-packaging/issues/69

Best regards
Michael
