### ISSUE TITLE
cmake: ICINGA2_RUNDIR can be replaced with RUNSTATEDIR

### ISSUE THREAD

**Issue by orlitzky** [Icinga/icinga2#6035]
I was looking into recent improvements in autoconf and cmake's corresponding GNUInstallDirs module, and noticed that `RUNSTATEDIR` is now available to be used where `ICINGA2_RUNDIR` is currently:

* https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
* https://cmake.org/cmake/help/v3.9/module/GNUInstallDirs.html

It's not at all important, but will let everyone delete a line in their build scripts.

**Comment by dnsmichi** [comment]
Problem is that we still need to support older CMake versions, and cannot apply this change. Thanks for the heads-up though :+1:
