### ISSUE TITLE
Can not modify ICINGA2_SSL_DIR on Debian

### ISSUE THREAD

**Issue by deric** [Icinga/icinga2#6040]
## Expected Behavior
According to [upgrade guide](https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#db-ido-schema-update-to-280) after adding line to `/etc/default/icinga2`
```
ICINGA2_SSL_DIR="${ICINGA2_STATE_DIR}/lib/icinga2/certs"
```
and restarting service, `icinga2` should look for the certificates in `/var/lib/icinga2/certs`

## Current Behavior
`icinga2` is looking for certificates in `/var/lib/icinga2/ca`
```
icinga2 ca sign 72aa9890b9f...
critical/SSL: Could not open CA key file '/var/lib/icinga2/ca/ca.key': 33558530, "error:02001002:lib(2):func(1):reason(2)"
```

`icinga2` service sources 2 environment files:
```
EnvironmentFile=/usr/lib/icinga2/icinga2
EnvironmentFile=/etc/default/icinga2
```
`/etc/default/icinga2` seems to be the right way to update configuration.

## Possible Solution (workaround)
Creating symlinks between certificates resolves the issue:
```
ln -s /var/lib/icinga2/certs/$(hostname -f).key /var/lib/icinga2/ca/ca.key
...
```

## Context
upgrading to 2.8 release

## Your Environment

```

Application information:
  Application version: r2.8.1-1
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 8 (jessie)
  Kernel: Linux
  Kernel version: 3.16.0-4-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.9.2
  Build host: f2c8f704978a

```

**Comment by gunnarbeutner** [comment]
The upgrade documentation does not appear to mention `ICINGA2_SSL_DIR` as an icinga-specific variable:

<code>You are safe to use the existing configuration paths inside the api feature. If you plan your migration, look at the following <b>example taken from the Director Linux deployment script</b> for clients.</code>

* Ensure that the default certificate path is changed from /etc/icinga2/pki to /var/lib/icinga2/certs.

```-ICINGA2_SSL_DIR="${ICINGA2_CONF_DIR}/pki"
+ICINGA2_SSL_DIR="${ICINGA2_STATE_DIR}/lib/icinga2/certs"```
