### ISSUE TITLE
Generic SQL Writer

### ISSUE THREAD

**Issue by anayrat** [Icinga/icinga2#6041]
Hello,

I suggest to add a generic SQL Writer which call a SQL function to insert perfdata in a DBMS. For example, collectd call `collectd_insert` function : 

https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_postgresql

It allows user to create their own function: https://github.com/collectd/collectd/pull/2569

Regards,

**Comment by dnsmichi** [comment]
Which specific problem or use case of yours would this addition solve?

**Comment by anayrat** [comment]
It allows users to store Perfdata in a RDMBS instead of a TSDB. Some projects uses Postgres to store timeseries : 
  * https://github.com/timescale/timescaledb
  * http://opm.io/

Thus, users could use Grafana to display perfdata. Since version 4.6 Grafana is able to use Postgres as datasource.

**Comment by dnsmichi** [comment]
I do see several problems with that:

- you don't know the RDBMS driver, and we are not able to load "something" into Icinga 2's memory. Think of Oracle for example.
- SQL queries solely configured by the user may decrease performance, if they do anything else than pure inserts.
- Metric data must be accessed with variables and bind variables. That costs extra.
- Relational databases don't provide data retention and aggregation out of the box. Inserts may become slow overtime, without direct control by the writing application.

I'd suggest to use existing TSDBs and your preferred feature in Icinga 2. If you need a specific additional storage, you can create a new feature code patch for it, and we can consider adding such. 

Thanks for the your idea though, much appreciated 👍 

Cheers,
Michael
