### ISSUE TITLE
Provide API to run embedded check commands

### ISSUE THREAD

**Issue by Hipska** [Icinga/icinga2#6046]
It would be a nice feature to have some cli command to be able to run the embedded check commands like `icinga`, `cluster`, `cluster-zone` and `ido`.

## Expected Behavior
I would love to see a command like `icinga2 command icinga` which then returns the output like this:
> Icinga 2 has been running for 17 hours, 24 minutes and 56 seconds. Version: r2.8.1-1

Return code would be the respective return code according to the state. `-v` or something could be used to also output performance data.

## Context
This feature could be extremely useful to monitor the monitoring with another tool. It can also help to set up the services using these command as you will then be able to test them before configuring the actual service. Which also makes sure that misconfigurations do not result in notifications being sent, as you are able to test it first.

**Comment by dnsmichi** [comment]
What's missing inside the `/v1/status` API endpoint?

**Comment by Hipska** [comment]
Nothing is missing for the first scenario of the context. But doesn't provide cli testing and the same output as the actual checks for the second scenario.

**Comment by dnsmichi** [comment]
Which problem would that solve exactly? You'll have all the data, you may concatenate output strings to look like plugin output, and you actually get real time data from the REST API.

**Comment by dnsmichi** [comment]
There's no plans to implement this. You're better off with your own mini plugin which concatenates required details.
