### ISSUE TITLE
create service objects behind a satellite via api

### ISSUE THREAD

**Issue by fp306** [Icinga/icinga2#6052]
Hi,

I use the api to create service objects at the runtime. with a command like this. 

`curl -u user:pass -H ‘Accept: application/json’ -X PUT https://master-server:5665/v1/objects/services/host!service -d ‘{ “templates” : [ “temp1” ] }’`

this works fine as long as I send it directly to the master. But when I send the same request to a satellite api. It creates the service object there but does not path it up to the master. 

`curl -u user:pass -H ‘Accept: application/json’ -X PUT https://satellite-server:5665/v1/objects/services/host!service -d ‘{ “templates” : [ “temp1” ] }’`

## Expected Behavior

I would expect the service object to be pathed to the master. Since creating it on the satellite has basically no effect it won't show up in the IcingaWeb2 interface.

## Current Behavior

a service object is created on the satellite in the _api path but has no effect there.

But setting service states for services created on the master actually works. 

`curl -k -s -u user:pass -H 'Accept: application/json' -X POST 'https://'satellite':5665/v1/actions/process-check-result?service=host!service -d"{ "exit_status": 0, "plugin_output": "OK" }"`

So the api seems to be a bit inconsistent, since creating new objects does not work but altering existing ones does.

## Possible Solution

Would be great to be able to set a flag or something so the object is pathed up to the master

## Steps to Reproduce (for bugs)

1. create an service object via api on a satellite
2. it won’t show up in icingaweb2
3. set the state of an existing service object on a satellite
4. the new state shows up 

## Context

We use the api to create service objects and downtime objects at runtime which can't really be done somewhere else then on the client site. 

I know that bottom up configurations are no longer supported but imo it does not make much sense to have an api which is only usable from clients in the master zone

## Your Environment

* Version used (2.7.2-1):
* Operating System and version: rhel 7
* Enabled features (api checker graphite ido-mysql mainlog notification):
* Icinga Web 2 version and modules (2.4.2):

**Comment by Crunsher** [comment]
Currently there is no way to do this, all API config has to be directed at the master. There are a few (big and small) design questions regarding propagating config up. Something like bottom-up will likely be tried again in the future, but for now you are stuck with talking to the master.

>I know that bottom up configurations are no longer supported but imo it does not make much sense to have an api which is only usable from clients in the master zone
This has nothing to do with zones though.

**Comment by fp306** [comment]
ok. Would be greate to have this feature in the future again.

**Comment by dnsmichi** [comment]
That is merely a matter of security and trust. A master node shouldn't automatically trust objects created by a child satellite. I don't think that there's an easy solution for this, better proxy your requests directly to the configuration master.

**Comment by kolapapa** [comment]
@dnsmichi 
please help me  [https://github.com/Icinga/icinga2/issues/6069](url)

**Comment by fp306** [comment]
Of course I would not expect the master to trust everything he recieves. There should be some layers of trust. But ok I'll try to forward this requests directly to the master.

**Comment by t794104** [comment]
We have the same problem and solved it by installing apache as proxy on the satellite and proxing port 5668 to 5665 on the master. So we make the api calls to the satellite on port 5668 (whcih points to the master api port).

**Comment by dnsmichi** [comment]
I'd leave the decision of possible security flaws to the user here. As said, we shouldn't easily allow child zones to create objects, even inactive. This could lead into a lot of garbage, and the last one is OOM-ing the parent node.
