### ISSUE TITLE
ido-pgsql fails when trying to access sequence

### ISSUE THREAD

**Issue by dasJ** [Icinga/icinga2#6065]
When starting icinga2, it seems like it's trying to get the `CURRVAL` of a sequence. However, the currval has not been defined yet and the transaction fails.

## Expected Behavior
Icinga2 should start with a the ido-pgsql feature.

## Current Behavior
Repeatedly, both icinga2 and postgres log the same errors (this example is postgres log):
```
ERROR:  currval of sequence "icinga_objects_object_id_seq" is not yet defined in this session
STATEMENT:  SELECT CURRVAL(pg_get_serial_sequence(E'icinga_objects', E'object_id')) AS id
```

## Steps to Reproduce (for bugs)
1. Run a postgres-xl cluster
2. Try to connect Icinga2 to it

## Context
I'm trying to connect icinga2 to a postgres-xl installation for HA functionality.
Currently, I'm trying to get the first node to connect (no HA setup yet), but it fails with the error above.

## Your Environment
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.1-1)

System information:
  Platform: Ubuntu
  Platform version: 16.04.3 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-109-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: 5b0d1614aaa2
```

```
Enabled features: checker command ido-pgsql mainlog notification
```
ido-pgsql.conf:
```
library "db_ido_pgsql"

object IdoPgsqlConnection "ido-pgsql" {
  user = "icinga2",
  password = "dummy",
  host = "127.0.0.1",
  database = "icinga2"
}
```

**Comment by dasJ** [comment]
From a miling list:
```
This implies that currval('t_wedding_wedding_id_seq') is being called
before any nextval('t_wedding_wedding_id_seq') has been done in the
current session.  It has nothing to do with sequence cache properties;
it's an application programming error, plain and simple. 
```

**Comment by dnsmichi** [comment]
I don't think that there's a workaround. I haven't seen this for native PostgreSQL, and it really looks like that the XL cluster software does something wrong with sessions and sequence values. Did you modify the SQL schema file before importing it?

**Comment by dasJ** [comment]
Yes, I added added distribution information to the tables `DISTRIBUTE BY REPLICATION`. So do I have to remind the Postgres-XL people of this bug?

**Comment by dnsmichi** [comment]
It would be interesting if you can reproduce the issue with a standalone PostgreSQL instance many other users out there are already having in production. This seems to be a niche problem with an extra layer of software.

**Comment by dasJ** [comment]
I cannot reproduce it with a standalone installation of vanilla PostgreSQL. So if you want, you can close this issue, as Icinga 2 doesn't claim to be compatible with Postgres-XL. I doubt that the Postgres-XL team will fix this issue in a timely manner, so I'll just ditch it. Thank you for your support!

**Comment by dnsmichi** [comment]
It was the first time I've heard of this project. And you're right, we can only support a small set of integrations.
