### ISSUE TITLE
Why master's downtime configuration is synchronized to checker

### ISSUE THREAD

**Issue by kolapapa** [Icinga/icinga2#6069]
## Expected Behavior

The downtime configuration information should be only in the master node, and he only manages whether the notification is sent, and the checker node should only care about the check state

## Current Behavior

The master node has a large number of downtime configuration information and will synchronize to the checker node

## Possible Solution

I think the master node should cancel the synchronization of downtime configuration information to the checker node

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: CentOS 7.3

**Comment by dnsmichi** [comment]
If the downtimes belong to hosts/services inside the checker zone, it is totally valid that they are synced.

**Comment by kolapapa** [comment]
@dnsmichi Thank you for your answer！
If you think this synchronization is correct, that what method can not sync? We have about `15W ` service needs to be monitored, and `a large release may have hundreds of thousands of host by downtime` (about 1-2 minutes will remove downtime), this will lead you to the number of concurrent downtime side synchronization each other in the whole cluster, `leading to errors` (the number of downtime on each checker is different), `memory leaks` and so on. When we meet this situation, it can only be solved by reload. It will be a new year in a week. You say we do?


Let me show you some monitoring maps...

![downtime](https://user-images.githubusercontent.com/17918689/35795393-00ac5926-0a94-11e8-8b0e-b81e89dea6df.jpg)
![monitor](https://user-images.githubusercontent.com/17918689/35795399-06719286-0a94-11e8-98d0-e672c419c997.jpg)


If you want more detailed information, I can add to Git！

Thx~

**Comment by kolapapa** [comment]
I still want to say that the downtime synchronization to checker is no use, only the fearless increase of the load.And I'm not satisfied with your answer.
