### ISSUE TITLE
event API's ts is not equal configuration's $service.last_hard_state_change$

### ISSUE THREAD

**Issue by kolapapa** [Icinga/icinga2#6070]
## Expected Behavior

The script we call notifications：
`echo "$SERVICEOUTPUT" | /etc/icinga2/scripts/opsivr/bin/opsivr-icinga-cli $HOSTDISPLAYNAME $SERVICEDISPLAYNAME $SERVICESTATE $DURATION $USERLIST $SERVICELASTHARDCHANGETIME`

We collect the notification action timestamp with 
```shell
/etc/icinga2/zones.d/global-templates/commands.conf

object NotificationCommand "ivr-service-notification" {
  command = [ SysconfDir + "/icinga2/scripts/ivr-service-notification.sh" ]

  env = {
    NOTIFICATIONTYPE = "$notification.type$"
    SERVICEDESC = "$service.name$"
    HOSTALIAS = "$host.display_name$"
    HOSTADDRESS = "$address$"
    SERVICESTATE = "$service.state$"
    LONGDATETIME = "$icinga.long_date_time$"
    SERVICEOUTPUT = "$service.output$"
    NOTIFICATIONAUTHORNAME = "$notification.author$"
    NOTIFICATIONCOMMENT = "$notification.comment$"
    HOSTDISPLAYNAME = "$host.display_name$"
    SERVICEDISPLAYNAME = "$service.display_name$"
    SERVICELASTCHANGETIME = "$service.last_state_change$"
    SERVICELASTHARDCHANGETIME = "$service.last_hard_state_change$"
    USEREMAIL = "$user.email$"
    USERENAME = "$user.name$"
    USERLIST = "$notification.vars.userlist$"
  }
}
```

And we collect the event at 
`https://l-qicingam1.ops.cn2.qunar.com:5665/v1/events?queue=event&types=StateChange&filter=event.state_type==1`

We call `$SERVICELASTHARDCHANGETIME` is `action's TS`
We call `API return's ts`  is `event's TS`

It is equal most of the time, but when RPC work queue is piled up, it causes action's ts to cause delay。
For example：
`action's TS: 1517825329    (Mon Feb  5 18:08:49 CST 2018)`
`event's TS:  1517824408    (Mon Feb  5 17:53:28 CST 2018)`

![image](https://user-images.githubusercontent.com/17918689/35800101-ee63c934-0aa2-11e8-9f2f-5cb26f847c61.png)

## Possible Solution

Can these two times be equal at any time, not affected by any condition,Or add a field in API。

In Nagios its a same macro `$LASTSERVICESTATECHANGE$`.

## Your Environment

* Version used (`icinga2 --version`):r2.8.1-1
* Operating System and version:CentOS 7.3

**Comment by kolapapa** [comment]
And look at this question again https://github.com/Icinga/icinga2/issues/6069

**Comment by kolapapa** [comment]
This may be because the two master are not synchronized with each other. Notification sends through M1, and then the timestamp of API from M2 will lead to different timestamps. How to ensure `$service.last_hard_state_change$`  between the two master is the same.
I can't make sure the message is sent from the master, and I can't confirm which master will get the time stamp information.
Because `Nagios` is a `single point`, the problem does not exist, but `double master` will cause the timestamp to be inconsistent.

**Comment by dnsmichi** [comment]
> Can these two times be equal at any time, not affected by any condition,Or add a field in API。

What exactly do you mean with that?

**Comment by kolapapa** [comment]
I mean, when I have 2 master machines in the cluster pattern, when the RPC queue in the cluster is piled up, the last_hard_state_change in the two master API is different. My project is dependent on this field.

**Comment by dnsmichi** [comment]
State calculation happens locally on the node, it just receives the check result message via the cluster protocol. There's no extra message for state update events as this would duplicate the information.
That would explain your observed behaviour.

Question aside, why is the JSON-RPC queue that full? This sounds a bit like a performance or network issue.

**Comment by kolapapa** [comment]
We have a large number of machines on the line and offline operations, will call API to interact, when a large number of time will cause RPC accumulation problem.

**Comment by dnsmichi** [comment]
Ok, that's more clear now. I don't have any solution here other than to troubleshoot and analyse on why the nodes are syncing that slow. Could be CPU limitations, network latency, etc. Highly likely this gets better the more hardware you throw at the nodes.

**Comment by dnsmichi** [comment]
Summarizing here, the event's timestamp is from the local node which streams the event. The original timestamp may be in the past e.g. when synced from the other node. The network stack including json rpc message queues has been rewritten for 2.11 which should improve the situation. Everything is else is a matter of resources and event stream receiver logic to cope with timestamp deltas. Therefore I am closing here.
