### ISSUE TITLE
GraphiteWriter: Ignoring invalid perfdata value: voltage=1000000mV;;;

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#6071]
## Expected Behavior

All plugins' perfdata are written to graphite.

## Current Behavior

```
[2018-02-05 12:01:26 +0000] warning/GraphiteWriter: Ignoring invalid perfdata value: voltage=1000000mV;;;
Context:
	(0) Processing check result for 'netways.de!ups'

[2018-02-05 12:01:26 +0000] warning/GraphiteWriter: Ignoring invalid perfdata value: temp1=100degC;;;
Context:
	(0) Processing check result for 'netways.de!ups'

[2018-02-05 12:01:26 +0000] warning/GraphiteWriter: Ignoring invalid perfdata value: temp2=100degF;;;
Context:
	(0) Processing check result for 'netways.de!ups'
```

## Possible Solution

Accept all possible units (no whitelist).

## Steps to Reproduce (for bugs)

```
object Host "netways.de" {
	check_command = "hostalive"
	address = "netways.de"

	vars.demoperfdatasvcs = {
		"ups" = "voltage=1000000mV;;; battery=12%;;; load=12%;;; temp1=100degC;;; temp2=100degF;;;"
	}
}

object CheckCommand "demoperfdata" {
	command = [ "/usr/bin/printf", "Dummy perfdata |%s", "$demoperfdata$" ]
}

apply Service for (svc => perfdata in host.vars.demoperfdatasvcs) {
	check_interval = 10s
	check_command = "demoperfdata"
	vars.demoperfdata = perfdata
	vars.check_command = svc
}
```

## Context

https://github.com/Icinga/icingaweb2-module-graphite/issues/71

## Your Environment

* Version used (`icinga2 --version`): r2.8.1-1

**Comment by dnsmichi** [comment]
https://www.monitoring-plugins.org/doc/guidelines.html#AEN201

specifies a list of acceptable UOMs. Unless we break with the Plugin API, we cannot change anything here.

**Comment by Al2Klimov** [comment]
1. We'd only "break" something if we'd allow less than that spec
2. That perfdata is even written to the IDO, but just not to Graphite

**Comment by Crunsher** [comment]
I would not add additional UOMs, there are quite a few if want to support all/most of the commonly used ones and their metric prefixes. Once we start we'll have to add all of them :G

**Comment by Al2Klimov** [comment]
That's exactly my suggestion: "add all of them", but as wildcard not as whitelist

**Comment by dnsmichi** [comment]
As said, this breaks compatibility with the plugin API. This has been discussed in multiple tickets now, I won't start again.

**Comment by Al2Klimov** [comment]
As discussed w/ @dnsmichi (offline): We may ask @bobapple.

**Comment by Al2Klimov** [comment]
As discussed w/ @lippserd (offline): We should support custom UOMs (and derivatives thereof), configured per check command in a "new plugin API".

**Comment by theredcat** [comment]
@Al2Klimov @dnsmichi Hi ! Can you reopen this issue ? It would be nice to have this feature

**Comment by dnsmichi** [comment]
It is well known that this feature, next to a new plugin API, is greatly desired. It won't happen at this point though, and a "new plugin API" requires a proper design and concept. Such a thing will be added as an issue once the time is right.
