### ISSUE TITLE
Prometheus integration, metrics exporter scrape target

### ISSUE THREAD

**Issue by HariSekhon** [Icinga/icinga2#6073]
Feature Request to provide a [Prometheus](https://prometheus.io/) compatible metrics exporter to be used as a scrape target for sharing metrics to Prometheus.

This is low priority compared to [Dynamic Inventory integration](https://github.com/Icinga/icinga2/issues/6072) described in #6072 which I believe should be prioritised several levels over all other features.

**Comment by dnsmichi** [comment]
Can you please provide more details and a specification how such an exporter should look like? Which data do you want to have available at this HTTP endpoint?

**Comment by HariSekhon** [comment]
I think all metrics should be exported from all plugins perfdata to ```/metrics``` (configurable but this is Prometheus default).

Then a ```?filter=<expression>``` parameter could isolate to more specific hosts or service checks.

**Comment by dnsmichi** [comment]
I don't know how such trees must be organized. You seem to know that already, can you share the specification with examples how you would build it e.g. with a host - service - perfdata tree?

**Comment by dnsmichi** [comment]
After discussing this for a while, there's a huge impact on providing such an endpoint on an instance with say 500k services. If someone comes up with a reasonable specification and design, one could write a prototype for a possible integration here. Meanwhile, I'd rather consider writing metrics towards Prometheus itself, if it supports that. Similar to how InfluxDB is implemented for example.

**Comment by HariSekhon** [comment]
I also prefer sending to a metrics sink like Graphite or InfluxDB but unfortunately this is not how Prometheus works, although you can use a push gateway to send metrics to and have Prometheus scrape there:

https://github.com/prometheus/pushgateway

**Comment by ulfkosack** [comment]
@HariSekhon: Perhaps you can use PerfdataWriter (https://icinga.com/docs/icinga2/latest/doc/09-object-types/#objecttype-perfdatawriter) to write your performancedata to *.prom-Files for the pushgateway. So you have a local cache for your data on every icinga2 instance.

**Comment by nubenum** [comment]
One can also use the Icinga2 Graphite feature in conjunction with the Prometheus [graphite_exporter](https://github.com/prometheus/graphite_exporter). Just configure Icinga to send the performance data to the exporter as if it was a Graphite instance, the exporter is in turn exposing them to Prometheus. This seems like a detour, but as far as I can tell, it works quite well.

**Comment by dnsmichi** [comment]
Before looking into this, I'd like to have a stable REST API with 2.11 first. Then comes the hard part with finding the correct and unique metric format.

**Comment by htriem** [comment]
This will be evaluated with #6419.
