### ISSUE TITLE
icingaweb2 RHEL 7 rpm does not install all files

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icinga2#6074]
## Expected Behavior

Installing icingaweb2 for RHEL 7 should install the schema files into `/usr/share/doc/icingaweb2/schema`

## Current Behavior

Installation of icingaweb2 via the RHEL 7 repo does not install the schema files.

## Possible Solution

It appears that the binary is missing files, as the source rpm builds fine.

## Steps to Reproduce (for bugs)

try installing from the repostory on a fresh RHEL 7 docker image:
```
yum install -y https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
yum install -y icingaweb2
ls /usr/share/doc/icingaweb2/schema
<NULL>
ls /usr/share/doc/icingaweb2/schema | wc -l
0
```
Missing files paste: http://paste.debian.net/1008962/

Manual install 
```
mkdir temp && cd temp
yum install -y rpmrebuild yum-utils
yumdownloader --source icingaweb2
rpm --nomd5 -i icingaweb2*.el7.centos.src.rpm
yum install -y bash-completion php php-ZendFramework \
    php-ZendFramework-Db-Adapter-Pdo-Mysql php-ZendFramework-Db-Adapter-Pdo-Pgsql \
    php-gd php-intl php-pecl-imagick
rpmbuild -ba /root/rpmbuild/SPECS/icingaweb2.spec
rpm -i /root/rpmbuild/RPMS/noarch/*rpm

ls /usr/share/doc/icingaweb2/schema
mysql-upgrades  mysql.schema.sql  pgsql-upgrades  pgsql.schema.sql
```

## Context

This affects us trying to get our Docker instance of Icinga2 with Icingaweb2 up and running. We have been trying diligently to get this running, uncovering small pieces along the way that need done.

## Your Environment

* Version used (`icinga2 --version`): 2.8.1-1.el7.icinga
* Operating System and version: 
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
```

* Enabled features (`icinga2 feature list`): N/A
* Icinga Web 2 version and modules (System - About):  2.5.1-1.el7.icinga
* Config validation (`icinga2 daemon -C`):  N/A

**Comment by mcktr** [comment]
Hi,

please create issues related to our packaging in the [icinga-packaging repository](https://github.com/Icinga/icinga-packaging).

Best regards
Michael

**Comment by mtdeguzis** [comment]
Sure, will do
