### ISSUE TITLE
 Error: Object 'example.se' of type 'Host' re-defined: in [stage]/zones.d/example.se/hosts.conf: 1:0-1:41; previous definition: in /etc/icinga2/conf.d/hosts.conf

### ISSUE THREAD

**Issue by IbrahimSajer** [Icinga/icinga2#6084]
guys Ihave this problem with icinga2 director adding host every time i add a host and try to deploy it 
gives me this error :   
Error: Object 'example.se' of type 'Host' re-defined: in [stage]/zones.d/example.se/hosts.conf: 1:0-1:41; previous definition: in /etc/icinga2/conf.d/hosts.conf
other wise all configuration seems to be correct 

Deployment time | 2018-02-09 12:10:56
-- | --
example.se
4 files, 2 objects, 1 templates, 0 apply rules, 1454.00 B
Rendered in 0.07s, deployed in 1.01s
braveheart-1518174657-1
Failed

**Comment by Crunsher** [comment]
Take a look at `/etc/icinga2/conf.d/hosts.conf`, there should be a a Host name 'example.se'. Delete it if you don't need it or rename it.

**Comment by dnsmichi** [comment]
This isn't really a bug, but a configuration issue. Hop onto the community channels next time.

When using the Icinga Director, you should not mix it with local configuration included in your `icinga2.conf` file. Drop the line with `include_recursive "conf.d"` and restart Icinga 2.

**Comment by IbrahimSajer** [comment]
bro. it is there 
include "features-enabled/*.conf"

/**
 * Although in theory you could define all your objects in this file
 * the preferred way is to create separate directories and files in the conf.d
 * directory. Each of these files must have the file extension ".conf".
 */
include_recursive "conf.d"
~
~
the last line what you mean with drop the line ??

**Comment by IbrahimSajer** [comment]
bro. it is there
include "features-enabled/*.conf"

/**

Although in theory you could define all your objects in this file
the preferred way is to create separate directories and files in the conf.d
directory. Each of these files must have the file extension ".conf".
*/
include_recursive "conf.d"
~
~
the last line what you mean with drop the line ??
