### ISSUE TITLE
Sending check results to Elasticsearch 

### ISSUE THREAD

**Issue by rokka** [Icinga/icinga2#6087]
Hi,

I am searching for all way to transfer my check results to Elasticsearch. 

The easiest way would be if i can generate a log line for every check including the check result. 

Is there auch way to enable auch check logfile?

Greetings
Andre

**Comment by gunnarbeutner** [comment]
Sorry, this is not a forum. The IRC channel or https://monitoring-portal.org/ would be a more appropriate venue for this instead.
