### ISSUE TITLE
Mark child services from triggered dependencies as handled

### ISSUE THREAD

**Issue by marcofl** [Icinga/icinga2#6092]
When you create a dependency from one service to another and the parent service enters a not-ok state, the dependency will mark the child service "reachable: no" and can disable active checks and notification. This though does not prevent the child service from popping up as unhandled in icingaweb2 when it was in a not-ok state before the dependency paused active checks for it. Unlike the implicit service to host dependency, where when the host is down, all its services will automatically show as handled in icingaweb2. 

I'm currently not able to prove if this is a configuration issue from my side, a missing feature or a bug. On the other hand I could not find documentation about this.

## Expected Behavior
When a dependency is triggered the child service should be shown handled (independent from its state) as long as the parent service / host is in a not-ok state. 

## Current Behavior
Currently only notifications and active checks can be disabled by a dependency but child services will still pop up (in icingaweb2 for example) if they were critical before the dependency was triggered and paused active checks.

## Possible Solution
Dependencies should be able to put child services into "handled" state. Im actually not sure if this "handled" state is just an icingaweb2 thing or also exists in icinga2. 

## Steps to Reproduce (for bugs)
1. Add / apply some random services (define one as the "master")
```
apply Service "random1_icinga-server.vagrant.dev" to Host {
  import "generic-service"
  display_name = "random1"
  assign where host.name == "icinga-server.vagrant.dev"
  check_command = "random"
}
apply Service "random2_icinga-server.vagrant.dev" to Host {
  import "generic-service"
  display_name = "random2"
  assign where host.name == "icinga-server.vagrant.dev"
}
apply Service "random_master_icinga-server.vagrant.dev" to Host {
  import "generic-service"
  display_name = "random master"
  assign where host.name == "icinga-server.vagrant.dev"
}
```
2. create a dependency apply rule
```
apply Dependency "master_service" to Service {
  parent_service_name = "random_master_icinga-server.vagrant.dev"
  disable_checks = true
  ignore_soft_states = false

  assign where service.name.contains("random")
  ignore where service.name.contains("random_master")
}
```
3. watch the service changing states in icingaweb2 to observe the described problem. 

## Context
For example we have 100+ services on a host checking GlusterFS bricks, showing such services as not-ok or even alerting for them needs to be avoided when we know the GlusterFS main services is in a CRITICAL state. Currently a dependency could disable active checks and notifications for the 100+ services, but if 50 of them were in a not-ok state before the dependency was triggered (before the parent service went not-ok) we would still see 50 services not-ok in icingaweb2. 

## Your Environment

* Version used (`icinga2 --version`):  r2.8.1-1
* Operating System and version: Ubuntu 16.04
* Enabled features (`icinga2 feature list`): api checker command ido-mysql influxdb mainlog notification
* Icinga Web 2 version and modules (System - About): icingaweb2-module-monitoring-2.5.1-1.xenial, icingaweb2-2.5.1-1.xenial
* Config validation (`icinga2 daemon -C`): 
```
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Please read the upgrading documentation for v2.8: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
information/ApiListener: My API identity: icinga-server.vagrant.dev
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 212 CheckCommands.
information/ConfigItem: Instantiated 17 Downtimes.
information/ConfigItem: Instantiated 4 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2 Hosts.
information/ConfigItem: Instantiated 4 Dependencies.
information/ConfigItem: Instantiated 2 TimePeriods.
information/ConfigItem: Instantiated 79 Services.
information/ConfigItem: Instantiated 2 ServiceGroups.
information/ConfigItem: Instantiated 5 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
That's nothing related to Icinga 2, but Icinga Web 2. AFAIK there's already a similar request in icinga/icingaweb2#3212

**Comment by marcofl** [comment]
Thanks for the answer, but I don't fully agree yet. For example a dashboard which directly queries the icinga2 API to get a list of critical services should also be able to exclude services which are "handled" because of a triggered dependency. 

I'm okay with having this issue closed, but one last question: When I query the API, is there actually a indicator (attribute) that the service is handled by a dependency at the moment, because the parent service / host is not-ok?

**Comment by dnsmichi** [comment]
"handled" is a virtual state calculated by Icinga Web 2. This includes stateful attributes like acks, downtimes, direct host relation. 

Such a thing isn't available in Icinga 2 nor its API. The application caller needs to calculate that on their own.

**Comment by marcofl** [comment]
Okay, I see. Thanks for clarification. Let's discuss this further in https://github.com/Icinga/icingaweb2/issues/3212
