### ISSUE TITLE
OpenTsdbWriter dot not insert metric names with colon character :

### ISSUE THREAD

**Issue by jre3brg** [Icinga/icinga2#6096]
OpenTsdbWriter do not insert metric names with colon character. Metrics came from Windows agents include colon on disk drive letters !

Debug from icinga,
[2018-02-16 17:45:06 +0100] debug/OpenTsdbWriter: Add to metric list:'put icinga.service.disk.D:_ 1518799516 3221068185.600000  host=*****.

Debug from opentsdb,
17:48:54.802 DEBUG [PutDataPointRpc.execute] - put: illegal argument: Invalid metric name ("icinga.service.disk.D:_"): illegal character: :

Reported in the past,
https://github.com/Icinga/icinga2/issues/4723

Version,
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.3 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.11.6.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

**Comment by dnsmichi** [comment]
#4723 is still open, why did you create a duplicate issue?

Furthermore, I doubt this will be changed, as a colon is not in the list of allowed characters for tags and metrics.

http://opentsdb.net/docs/build/html/user_guide/writing/index.html#metrics-and-tags
