### ISSUE TITLE
Hosts created using API do not get vars set in templates

### ISSUE THREAD

**Issue by bardahlm** [Icinga/icinga2#6099]
## Expected Behavior

Hosts created using API should get vars from templates, even if some vars are set in the host object.

## Current Behavior

Host  created using API with vars set will not get vars set in templates

## Possible Solution

In the config generated, change from
```
        vars = {
                environment = "test"
                profile = "payments"
                system = "HR"
        }
```
to
```
        vars += {
                environment = "test"
                profile = "payments"
                system = "HR"
        }
```

## Steps to Reproduce (for bugs)

1.Create test object with curl:  
```
curl -v -k -s -u $ICINGA2_API_USERNAME:$ICINGA2_API_PASSWORD \
  -H 'Accept: application/json' -X PUT 'https://icinga-rest/v1/objects/hosts/TESTTEST4' \
  -d '{ "templates": [ "linux-host" ], "attrs": { "address": "199.199.199.199", "vars": {  "system":"HR", "profile":"payments", "environment":"test"}  } }' \
  | python -m json.tool
```
2. Find out that vars set in the imported template are not there and that the stored configfile use vars = { } and not vars += { }

## Context

We're currently having issues with hosts added via API, they miss some settings depending on how we create them. If we set variables during creating, we lose all vars set via template (vars.agent = by_ssh being the most important variable). If we do not set vars during creation, we lose host group assignments.

## Your Environment

* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: RHEL 7.4
* Enabled features (`icinga2 feature list`): Enabled features: api checker command ido-mysql influxdb livestatus mainlog notification

**Comment by bardahlm** [comment]
Workaround: Create host object with a "flattened" data structure:
 curl -v -k -s -u $ICINGA2_API_USERNAME:$ICINGA2_API_PASSWORD -H 'Accept: application/json' -X PUT 'https://icinga-rest/v1/objects/hosts/TESTTEST4' -d '{ "templates": [ "linux-host" ], "attrs": { "address": "199.199.199.199", "vars.system":"HR", "vars.profile":"payments", "vars.environment":"test"  } }' | python -m json.tool

**Comment by Crunsher** [comment]
Relevant: #4805

**Comment by dnsmichi** [comment]
Since templates cannot be created via the API, this really is an edge case. API users are expected to deploy the full object without any magic merging of dictionaries and nested attributes involved. Sorry for the late reply, but this is not going to be implemented.
