### ISSUE TITLE
Snapshot builds fail on livestatus tests

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#6105]
This issue only appears on the build server and seems only to hit Debian Jessie and Ununtu trusty.
I was not able to reproduce this locally on buster.
```
/usr/bin/ctest --force-new-ctest-process -j1
Test project /home/jenkins/workspace/icinga2-snapshot/deb-debian-jessie-1binary/arch/x86_64/icinga2/obj-x86_64-linux-gnu
[ . . . ]
      Start 84: livestatus-livestatus/hosts
84/89 Test #84: livestatus-livestatus/hosts .............................................***Failed    0.01 sec
Test setup error: std::exception: 'apply' cannot be used with type 'Service'

      Start 85: livestatus-livestatus/services
85/89 Test #85: livestatus-livestatus/services ..........................................***Failed    0.01 sec
Test setup error: std::exception: 'apply' cannot be used with type 'Service'

      Start 86: icinga_checkable-icinga_checkable_flapping/host_not_flapping
86/89 Test #86: icinga_checkable-icinga_checkable_flapping/host_not_flapping ............   Passed    0.01 sec
      Start 87: icinga_checkable-icinga_checkable_flapping/host_flapping
87/89 Test #87: icinga_checkable-icinga_checkable_flapping/host_flapping ................   Passed    0.01 sec
      Start 88: icinga_checkable-icinga_checkable_flapping/host_flapping_recover
88/89 Test #88: icinga_checkable-icinga_checkable_flapping/host_flapping_recover ........   Passed    0.01 sec
      Start 89: icinga_checkable-icinga_checkable_flapping/host_flapping_docs_example
89/89 Test #89: icinga_checkable-icinga_checkable_flapping/host_flapping_docs_example ...   Passed    0.01 sec

98% tests passed, 2 tests failed out of 89

Total Test time (real) =  17.58 sec

The following tests FAILED:
	 84 - livestatus-livestatus/hosts (Failed)
	 85 - livestatus-livestatus/services (Failed)
```
See also [here](https://build.icinga.com/job/icinga2-snapshot/job/deb-ubuntu-trusty-1binary/arch=x86_64/136/console) and [here](https://build.icinga.com/job/icinga2-snapshot/job/deb-debian-jessie-1binary/arch=x86/137/console)

**Comment by lazyfrosch** [comment]
Most likely an issue with Boost 1.55

Jessie: https://tracker.debian.org/pkg/boost1.55 \
Trusty: https://launchpad.net/ubuntu/+source/boost1.55

**Comment by Crunsher** [comment]
Hm, I'm thinking we should then deactivate the tests for this boost version. Obviously this is not a long term solution but with a full schedule I have neither the time nor the motivation to hunt down a version specific bug in tests for livestatus of all things :/

**Comment by dnsmichi** [comment]
Disable the livestatus tests entirely, they are not feature complete and neither help with known problems.

**Comment by Crunsher** [comment]
The problem does not exist in the support branch, we can put this on hold for now.

**Comment by lazyfrosch** [comment]
@dnsmichi I don't think the livestatus tests are the problem here...

But yes, 2.9

**Comment by lazyfrosch** [comment]
Looks like this was introduced by 1be285c53

It seems to be an issue or ordering problem in setting up Boost Global fixtures.
