### ISSUE TITLE
AppVeyor Windows builds are failing due exceeded artifact storage

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga2#6106]
## Current Behavior

All AppVeyor CI builds are currently failing because the storage size for artifacts is exceeded. The storage size is calculated over all builds and does not count per build. 

```
Collecting artifacts...
Found artifact 'build\choco\icinga2.nupkg' matching 'build\choco\*.nupkg' path
Found artifact 'build\Icinga 2-2.8.1-win64.msi' matching 'build\Icinga*.msi' path
Found artifact 'build\Test.xml' matching 'build\Test.xml' path
Uploading artifacts...
[1/3] build\choco\icinga2.nupkg (3,900 bytes)...100%
Maximum allowed artifact storage size of 1000 Mb will be exceeded.
```

## Possible Solution

Currently there seems to be no way to clean up the artifact storage. I found a conversation in the support channels of AppVeyor where a AppVeyor staff member reset/unblock the artifact storage limit.

https://help.appveyor.com/discussions/problems/10253-maximum-allowed-artifact-storage-size-of-1000-mb-will-be-exceeded

**Comment by dnsmichi** [comment]
Thanks, there's already a tracking issue in our infrastructure queue. This isn't icinga2 exclusive, more or less build system related.
