### ISSUE TITLE
Icinga Priority based notification - Reg

### ISSUE THREAD

**Issue by praveendcis** [Icinga/icinga2#6117]
@dnsmichi  Hi I just want to send notifications to two different groups based on priority.

For example, if I have two groups set 1. icingaadmins and 2. icingatest. If some service fails icinga should first send a notification to "**icingatest**" and if no action is taken with three consecutive notifications. Then icinga should send a notification to  "**icingaadmins**"

Please, can you help me.

**Comment by mcktr** [comment]
Sorry but this is not the right place to ask for basic help, this is an issue tracker where bugs and feature requests are discussed. 

Please join the community channels monitoring-portal.org or lists.icinga.org to ask your question.

**Comment by dnsmichi** [comment]
And please also stop highlighting me. That does not speed things up, this is just impolite.
