### ISSUE TITLE
Service vars override

### ISSUE THREAD

**Issue by aanriot** [Icinga/icinga2#6121]
Hello,

I'm currently managing several _Icinga 2.8.1_ (and Icingaweb2) nodes under Debian Stretch (amd64) and all the services are configured through apply rules.

In order to be able to override e.g. a threshold on a load check, I'm using configuration items similar to:

```
object Host "myserver" {
  import    "generic-service"
  address    = "myserver.domain.tld"
  vars.os    = "Linux"
  load_wload1  = 1.50
}

apply Service "load" {
  display_name      = "Load"
  check_command     = "load"
  vars.load_wload1  = 0.94
  vars.load_wload5  = 0.92
  vars.load_wload15 = 0.90
  vars.load_cload1  = 1.0
  vars.load_cload5  = 0.98
  vars.load_cload15 = 0.96
  vars.load_percpu  = true

  vars += host.vars.load

  assign where host.address
}
```
That means that I have to declare / populate a dict for each check on which I have to override thresholds.

I have read [03-monitoring-basics.md](https://github.com/Icinga/icinga2/blob/master/doc/03-monitoring-basics.md#apply-for-and-custom-attribute-override-) which appears to confirm that this kind of settings can be performed only on a custom and per-service basis.

Is there any existent way (or roadmap item) which could allow to use native and standard override directives, with something such as:

```
object Host "myserver" {
  import    "generic-service"
  address    = "myserver.domain.tld"
  vars.os    = "Linux"
  service.name_of_the_service_in_the_apply_rule.load_wload1  = 1.50
}
```
Thanks a lot.

Best regards,

**Comment by Crunsher** [comment]
There are multiple ways to deal with that, but all of them have to be done in the service. Why not use your first solution in conjunction with imports?
```
apply Service "load"
import "load_default" /* vars.load_wload1 = 0.94... */
vars.load_wload1 = 0.95
vars += host.vars.load /* vars.load_wload1 = 0.96 */
```

**Comment by aanriot** [comment]
Thank you for your reply @Crunsher.

Indeed, it could be possible but it's ok for me to keep them in the apply rule for now, I was only wondering if a more standard way (inheritance / native overrides) was planned.

**Comment by dnsmichi** [comment]
Host objects don't know anything about the service apply rules and objects created in a later config compile stage. 

You might want to subscribe to #6030 and #4722 in order to discuss possible "modifications after object creation".

**Comment by aanriot** [comment]
Thanks @dnsmichi, I just subscribed to both issues.

Do you want me to close this one?

**Comment by dnsmichi** [comment]
I was waiting for your feedback, as this one is a duplicate then :)
