### ISSUE TITLE
Force check has no effect

### ISSUE THREAD

**Issue by lippserd** [Icinga/icinga2#6140]
## Expected Behavior

If I schedule a forced check, the check must be scheduled regardless of time period restrictions or whether active checks are enabled.

## Current Behavior

If active checks are disabled or the scheduled check time is outside the check time period, the check is not scheduled/executed.

## Possible Solution

Respect the `force_check` flag.

## Steps to Reproduce (for bugs)

Scenario active checks disabled

1. Choose a monitored object in Web 2
2. Disable its active checks
3. Submit passive check result with a different state to quickly identify whether the check in question is going to be scheduled
4. Run Check Now
5. Notice that nothings has been changed

debug.log

> [2018-03-02 05:26:05 -0800] information/HttpServerConnection: Request: POST /v1/actions/reschedule-check (from [127.0.0.1]:47388, user: root)
[2018-03-02 05:26:05 -0800] notice/ApiActionHandler: Running action reschedule-check
[2018-03-02 05:26:05 -0800] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-03-02 05:26:05 -0800] notice/CheckerComponent: Skipping check for host 'example-host': active host checks are disabled

Scenario scheduled time outside check time period

1. Use the example time period never for a monitored object
2. Select the object in Web 2
3. Submit passive check result with a different state to quickly identify whether the check in question is going to be scheduled
4. Run Check Now
5. Notice that nothings has been changed

debug.log

> [2018-03-02 05:30:05 -0800] information/HttpServerConnection: Request: POST /v1/actions/reschedule-check (from [127.0.0.1]:47778, user: root)
[2018-03-02 05:30:05 -0800] notice/ApiActionHandler: Running action reschedule-check
[2018-03-02 05:30:05 -0800] notice/ApiListener: Relaying 'event::SetNextCheck' message.
[2018-03-02 05:30:05 -0800] notice/CheckerComponent: Skipping check for object 'example-host': not in check period 'never'

## Context

Run Check Now in Icinga Web 2 for hosts or services that either have active checks disabled or are currently not being checked because of time period restrictions. The command transport is the Icinga API.

## Your Environment

Single node test setup with the latest versions available.

**Comment by dnsmichi** [comment]
If the user explicitly disabled active checks in the object configuration, no-one should be able to actively force a check. That's not a bug imho.

In terms of the check period, I agree. Still the code respects `force`, so it would be interesting to see the http request params Icinga Web 2 is sending. It might omit the required `true`/`false` value.

# Test Config

```
object TimePeriod "test" {
  ranges = {
    "sunday" = "08:00-09:00"
  }
}

object Host "tp-host" {
  check_command = "hostalive"
  check_interval = 1h
  check_period = "test"
}
```

```

[2018-03-02 14:47:21 +0100] notice/CheckerComponent: Skipping check for object 'tp-host': not in check period 'test'
```

Actually, this is a bug in Icinga Web 2, see icinga/icingaweb2#3377

Applied the fix, works.

```
[2018-03-02 14:53:09 +0100] notice/Checkable: State Change: Checkable 'tp-host' soft state change from DOWN to DOWN detected.
```

**Comment by gunnarbeutner** [comment]
Our documentation incorrectly mentions `force_check` instead of `force`.

**Comment by dnsmichi** [comment]
Ah ok, thanks. I was already wondering because the command transport inside Icinga Web 2 used another command where `force` was correct.
