### ISSUE TITLE
Check Now not executed when satellite state is pending

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga2#6142]
I noticed a weird behavior regarding "Check Now", when I execute this for a host or services.

@Thomas-Gelf and I discussed this briefly. It needs some investigation.

## Your Environment

* Version used (`icinga2 --version`): 2.8.1
* Operating System and version: CentOS 7

**Comment by dnsmichi** [comment]
That may be related to icinga/icingaweb2#3377.

**Comment by dnsmichi** [comment]
I believe this is fixed in the snapshot packages. Please test them.

**Comment by dnsmichi** [comment]
I'm closing here for two reasons:

- I believe that's fixed from what I can guess from previous conversations.
- The issue description lacks of any detail on how to reproduce the problem. If there's a customer ticket involved, extract all the required details.

Cheers,
Michael
