### ISSUE TITLE
Multi Argument Syntax for check_ncsp_api and Nsclient

### ISSUE THREAD

**Issue by bmccorkle** [Icinga/icinga2#6150]
I can't seem to find syntax that works when trying to check the uptime of a server using the nsclient web api (check_nscp_api) command in Icinga2 when I want custom warning and critical values (multiple arguments listed)

## Expected Behavior
Return the uptime of the server with the custom warning and critical values applied.  From the command line, this works:

./check_nscp_api --host 172.23.2.10 --port 8445 --password password -q check_uptime -a "warn=uptime < 270m" "crit=uptime < 1h"

## Current Behavior
If I use a single argument without the quotes (crit=uptime < 1h) it works.  Only when I try to add a second argument do I get the error.  If I try the argument without quotes, Icinga gives:

check_uptime Failed to validate filter see log for details: Critical expression is not valid:uptime < 1h warn=uptime < 7d

If I try to place quotation marks around each argument, I get:

Icinga gives: check_uptime Invalid command line: unrecognized option '"crit=uptime < 1h" "warn=uptime < 6h"'

 I'm using Icinga Director to configure the system.  Preview of the service template shows the following which looks correct:

template Service "uptime-windows" {
    import "generic-service"

    check_command = "nscp_api"
    groups = [ "Uptime-Windows" ]
    vars.nscp_api_arguments = "\"crit=uptime < 1h\" \"warn=uptime < 6h\""
    vars.nscp_api_host = "$address$"
    vars.nscp_api_password = "password"
    vars.nscp_api_port = "8445"
    vars.nscp_api_query = "check_uptime"

The check_nscp_api command is defined as an external imported commmand:

object CheckCommand "nscp_api" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_nscp_api" ]
    timeout = 1m
    arguments += {
        "--password" = {
            description = "NSCP API password"
            value = "$nscp_api_password$"
        }
        "-H" = {
            description = "NSCP API host address"
            required = true
            value = "$nscp_api_host$"
        }
        "-P" = {
            description = "NSCP API host port. Defaults to 8443."
            value = "$nscp_api_port$"
        }
        "-a" = {
            description = "NSCP API Query arguments"
            repeat_key = true
            value = "$nscp_api_arguments$"
        }
        "-q" = {
            description = "NSCPI API Query endpoint to use"
            value = "$nscp_api_query$"
        }
    }
    vars.check_address = {
        arguments = [  ]
        deprecated = false
        name = "<anonymous>"
        side_effect_free = false
        type = "Function"
    }
    vars.check_ipv4 = false
    vars.check_ipv6 = false
    vars.nscp_api_host = "$check_address$"
}

## Steps to Reproduce (for bugs)
1.  Create check uptime service template using check_nscp_api
2. try to add argument "warn=uptime < 270m" "crit=uptime < 1h"

## Context
Unable to create nsclient++ uptime check using web api when using multiple arguments.  

## Your Environment

* Version used (`icinga2 --version`):  2.8.1
* Operating System and version:  FreeBSD 11.1-RELEASE-p6
* Enabled features (`icinga2 feature list`): api checker command debuglog ido-mysql influxdb mainlog notification
* Icinga Web 2 version and modules (System - About):  2.5.1
* Config validation (`icinga2 daemon -C`):  
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: bsd-07.gahanna.gov
information/ConfigItem: Instantiated 2 FileLoggers.
information/ConfigItem: Instantiated 3 ApiUsers.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 6 Services.
information/ConfigItem: Instantiated 211 CheckCommands.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 6 ServiceGroups.
information/ConfigItem: Instantiated 2 TimePeriods.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 1 HostGroup.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3 NotificationCommands.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by bmccorkle** [comment]
Anyone on this?   I've been trying everything I can think of.   Does anyone have a working example of a nslicient++ check using the Icinga2 nscp_api check command that has more than one argument in the syntax (that has spaces in the arguments)?

**Comment by Crunsher** [comment]
Can you give us the output of `icinga2 object list --name $servicename` for one of the services using these checks? There might be issues with the escaping of the arguments.

Also note that due to issues like #5633 and issues with our HTTP implementation we are going. for a rewrite of the plugin in the near future. But there is no date for this yet.

**Comment by bmccorkle** [comment]
I managed to find somewhat of a 'workaround' yesterday.   I cloned the command (ncsp_api) and created a new argument for the cloned command (exp: Argument name: '-a2',  Value: $nscp_api_arguments_2$, Skip Key = Yes).   I then set $nscp_api_arguments$ to crit=uptime < 1h and $nscp_api_arguments_2$ to warn=uptime <6h (without any quotes on either argument) and I was able to start getting uptime data back with working thresholds.   I'm assuming I could create several more arguments so the cloned command can handle more than just 2 arguments but I didn't experiment with it any further.  Of course if I didn't have to do this, that would be even better :)

Here's the requested output...

bsdSRV:/usr/home/test # icinga2 object list --name Uptime
Object 'WG.domain.com!Uptime' of type 'Service':
  % declared in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_apply.conf', lines 55:1-55:22
  * __name = "WG.domain.com!Uptime"
  * action_url = ""
  * check_command = "nscp_api"
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 83:5-83:30
  * check_interval = 60
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 4:5-4:23
  * check_period = "24x7"
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 3:5-3:25
  * check_timeout = 60
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 6:5-6:22
  * command_endpoint = ""
  * display_name = "Uptime"
  * enable_active_checks = true
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 8:5-8:31
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 7:5-7:31
  * enable_passive_checks = true
  * enable_perfdata = true
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 9:5-9:26
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ "Uptime-Windows" ]
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 84:5-84:33
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_apply.conf', lines 59:5-59:33
  * host_name = "WG.domain.com"
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_apply.conf', lines 55:1-55:22
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 5
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 2:5-2:28
  * name = "Uptime"
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_apply.conf', lines 55:1-55:22
  * notes = ""
  * notes_url = ""
  * package = "director"
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_apply.conf', lines 55:1-55:22
  * retry_interval = 60
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 5:5-5:23
  * source_location
    * first_column = 1
    * first_line = 55
    * last_column = 22
    * last_line = 55
    * path = "/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_apply.conf"
  * templates = [ "Uptime", "uptime-windows", "generic-service", "host var overrides (Director)" ]
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_apply.conf', lines 55:1-55:22
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 80:1-80:33
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 1:0-1:33
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/001-director-basics.conf', lines 7:1-7:41
  * type = "Service"
  * vars
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/001-director-basics.conf', lines 17:5-17:49
    * nscp_api_arguments = ""crit=uptime < 1h" "warn=uptime < 1d""
      % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 85:5-85:73
    * nscp_api_host = "$address$"
      % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 86:5-86:36
    * nscp_api_password = "password"
      % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 87:5-87:51
    * nscp_api_port = "8445"
      % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 88:5-88:31
    * nscp_api_query = "check_uptime"
      % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 89:5-89:40
  * volatile = true
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_templates.conf', lines 10:5-10:19
  * zone = "bsdSRV.domain.com"
    % = modified in '/var/lib/icinga2/api/packages/director/bsdSRV-1520616873-0/zones.d/director-global/service_apply.conf', lines 55:1-55:22

**Comment by dnsmichi** [comment]
This will be solved with #5633 requiring a rewrite of the plugin. Marking this as duplicate.
