### ISSUE TITLE
GelfWriter TLS support

### ISSUE THREAD

**Issue by marcofl** [Icinga/icinga2#6152]
Graylog supports TLS and Client certificate authentication on the TCP GELF Input. Icinga2's GelfWriter does not. 

## Expected Behavior
Support TLS and TLS auth in a similar way as https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#elasticsearchwriter does for example. 

## Current Behavior
No TLS support.

## Possible Solution
Implement TLS and new config options `enable_tls`, `ca_path`, `key_path`, `cert_path`, etc. in https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#gelfwriter

## Context
Logdata most likely includes kind of sensitive data and should not be transmitted in plain text to a logging system. 

## Your Environment

* Version used (`icinga2 --version`): r2.8.1-1

**Comment by dnsmichi** [comment]
Is there a guide around to configure a Graylog TLS input? I failed hard a while ago.

**Comment by marcofl** [comment]
to test TLS GELF you can use a stunnel config like this:
```
foreground = yes
[graylog]
verify = 0
client = yes
accept = <localport>
connect = <graylogserver>:<gelf tcp tls enabled input port>
```
then point icinga2 gelfwriter to localhost:<localport>

**Comment by dnsmichi** [comment]
Thanks. I could re-use the Icinga certificates inside the graylog Vagrant box for that some months ago.

Still, someone needs to look into the code portions for adding the TLS bits. Should be straight forward when looking into the similar things with the Elasticsearch feature.
