### ISSUE TITLE
disk_check plugin ignoring parameters

### ISSUE THREAD

**Issue by paddyjoy** [Icinga/icinga2#6156]
Hi,

I'm struggling to get the disk_check plugin to use the disk_wfree and disk_cfree parameters.

In my services.conf I have added the parameters:

```
apply Service "disk" {
  check_command = "disk"

  vars.disk_wfree = "5%"

  vars.disk_cfree = "2%"
  

  //specify where the check is executed
  command_endpoint = host.vars.client_endpoint

  assign where host.vars.client_endpoint
}
```
These paramaters can be seen in icingaweb and icingaweb is showing the correct critical/warning values for these thresholds however the plugin is showing a warning.

Any tips on how to track down where this is falling down would be appreciated.

Icinga installed is version 2.8.1

`icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.1-1)
`

Thanks

![selection_026](https://user-images.githubusercontent.com/78623/37251781-654bae5e-256a-11e8-8f8a-fdc021df1a65.png)

**Comment by mcktr** [comment]
Hi,

can you please show us your actual disk size/usage? :)

Best regards
Michael

**Comment by dnsmichi** [comment]
This sounds more like a configuration issue than a bug. Please start a new topic over at the forums or the mailing lists.
