### ISSUE TITLE
Renamed host now Icinga2 won't start

### ISSUE THREAD

**Issue by Fossil01** [Icinga/icinga2#6159]
Hi,

I have moved my monitoring VM and renamed it to fit the new convention. The hostname was changed and all occurences of the name in /etc/icinga2 were replaced with the new name.

Now whenever I try to start Icinga I get:

```
Mar 09 15:02:15 mon-ams7-01 icinga2[2076]: [2018-03-09 15:02:15 +0100] information/ApiListener: My API identity: OLD_HOSTNAME
Mar 09 15:02:15 mon-ams7-01 icinga2[2076]: [2018-03-09 15:02:15 +0100] critical/config: Error: Endpoint object for 'OLD_HOSTNAME' is missing.
```

Also `icinga2 variable get NodeName ` still returns te old hostname.

How can I change this to the new name and get everything back online again? I tried deleting all certs and running the node wizard again but that did not do it. Do I have to edit the MySQL database entries too?

**Comment by dnsmichi** [comment]
Please don't open issues for such questions, especially not when they are already discussed.

https://monitoring-portal.org/t/renamed-master-now-it-wont-start/1600
