### ISSUE TITLE
check_memory wrong return code, value and perfdata at unit GB

### ISSUE THREAD

**Issue by teclogi** [Icinga/icinga2#6161]
The check_memory.exe on a Windows host is returning a wrong exit code (and text) for example when the unit is set to GB and the memory is below 500 MB. In this case the warning and critical threshold are not taken into account.
This might be, because the check_memory is using integer values to calculate?

## Expected Behavior

If for example the unit is set to GB and the memory is below 500 MB free space, the check_memory should calculate with floating-point number instead of integer values.
The performance data should also return the floating-point number for better graphing.

## Current Behavior

If for example the unit is set to GB and the memory is below 500 MB free space, the check_memory returns critical even if the memory threshold is not broken.

## Possible Solution

Change the check_memory to use floating-point number for calculating and performance data returned. 

## Steps to Reproduce (for bugs)

Execute the check_memory.exe on a Windows server as follows.

Unit GB (wrong behavior)
```"C:\Program Files\ICINGA2\sbin\check_memory.exe" -w 0.2% -c 0.1% -u GB```

Return: ```MEMORY CRITICAL - 9.39357% free | memory=0GB;0.0080000000000000002;0.0040000000000000001;0;4```

Unit MB (correct behavior)
```"C:\Program Files\ICINGA2\sbin\check_memory.exe" -w 0.2% -c 0.1% -u MB```

Return: ```MEMORY OK - 9.40692% free | memory=385MB;8.1920000000000002;4.0960000000000001;0;4096```

## Your Environment

* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: Debian 9, Windows 2018 R2, Windows 2012 R2, Windows 2016
* Enabled features (`icinga2 feature list`): api checker command graphite ido-mysql livestatus mainlog notification

**Comment by mcktr** [comment]
After having a short look into the code, I think this is a rounding problem. We are rounding to whole numbers (except for the percentage data) and the exit code is calculated with the rounded number.
