### ISSUE TITLE
Check timeouts: gracefully terminate check by sending SIGTERM before SIGKILL

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#6162]
When a check command timeouts, Icinga2 currently sends it a SIGKILL, not allowing it to shut down gracefully. It should first send a SIGTERM and only if the process then doesn't terminate within a few seconds send a SIGKILL. This would for example allow checks to remove temporary files they created, which isn't really possible at the moment without implementing a separate timeout mechanism in the check and keeping the timeout values in sync so that the check's timeout fires a few seconds before Icinga would kill it.

This was also suggested on the icinga-users mailinglist a while ago but got no response there: https://lists.icinga.org/pipermail/icinga-users/2016-February/010822.html

**Comment by dnsmichi** [comment]
Plugins should implement their own timeout alarm, that's considered best practice. Icinga 2 provides only a safety mechanism to prevent plugins going crazy.
