### ISSUE TITLE
Windows Disk performance data broken in InfluxDB

### ISSUE THREAD

**Issue by dupondje** [Icinga/icinga2#6182]
Since the upgrade to Icinga 2.8.2, I get errors when sending metrics to InfluxDB of disk-windows:
partial write: unable to parse 'disk-windows,hostname=xxxx,service=disk,metric=C:\ crit=3758096384,max=75161927680,value=38654705664,warn=7516192768 1521812376': invalid tag format

Seems like the following commit broke it:
https://github.com/Icinga/icinga2/commit/7f92016e383252013e13aa3f17b7a6dc6424d3a0#diff-351369f332d56df0b38ba50ed7d32681L305

This breaks all our disks graphs for Windows!

**Comment by dupondje** [comment]
@N-o-X @gunnarbeutner

**Comment by dnsmichi** [comment]
There's no need to highlight devs, we get notifications for this project.

Can you elaborate on the error message, what exactly is causing the `invalid tag name` error?

**Comment by dupondje** [comment]
InfluxDB has issues with with slashes at the end. See https://github.com/influxdata/influxdb/issues/8587
These were changed to an underscore in 2.8.1, but the commit changes this. Which causes issues now :)

**Comment by dnsmichi** [comment]
I see. What a mess.

@lippserd we should evaluate that next week during the dev sprint.

**Comment by SimonHoenscheid** [comment]
Is there an option to issue an other 2.8.x release to fix this soon. we are affected by this too

**Comment by hypermagicmountain** [comment]
Same problem here. No disk-windows perfdata since last week, same error.
`unable to parse 'disk-windows,hostname=DC1\ XXXX,service=WindowsDisk,metric=D:\ crit=42949620531.200005,max=858992410624,value=618162814976,warn=85899241062.400009 1523420751': invalid tag format`

**Comment by dnsmichi** [comment]
Currently there are no plans for 2.8.x, this is why the issue targets 2.9.

**Comment by hypermagicmountain** [comment]
When is 2.9 coming out? Disk-Windows is actually one of our most frequently used data sources (and saved our ass big time once). We are already missing one week. Can we somehow make the change ourselves without breaking the next update?

**Comment by linuxmail** [comment]
Hi, @Crunsher 

I expecting a different performance output, but it looks like the same. c:\ 1234 B (1%); ....

cu denny

**Comment by Crunsher** [comment]
I see, I'm sorry. I thought this was a fix in the check_plugins, but actually we fixed the escaping in influxdb. You can install the snapshot packages on the Host that has the influxdb feature enabled, but the check_disk binaries provided by me do _not_ fix this.

**Comment by linuxmail** [comment]
hi,

O.K, than I have to wait for 2.9.x.

**Comment by hypermagicmountain** [comment]
Fixed in 2.8.3

Working for me again.

Thanks!
