### ISSUE TITLE
Documentation does not flow properly if default font size is changed

### ISSUE THREAD

**Issue by offsides** [Icinga/icinga2#6185]
I normally sent my default font size in Firefox to 14 instead of 16 to get a little more on each page.  However, when I do that the flow of the Icinga2 documentation is disrupted so that the main documentation section does not wrap properly and flows into the right sidebar, making it impossible to read.

## Expected Behavior
The text should wrap to the left of the right sidebar so that all of the text is visible, no matter what the font settings.

## Current Behavior
If the default font in Firefox is set smaller than 16, the text flows into the right sidebar unless the window is at least 1735 pixels wide, which leaves huge swaths of blank page on the outside of both sidebars (since the max width is set to 1255 pixels).

Here's what it looks like under 14-point default font:
![icinga2docs_font14](https://user-images.githubusercontent.com/5611731/37913819-cb1744ee-30e3-11e8-96e7-1c22e318c15d.png)

And under the default 16-point default font:
![icinga2docs_font16](https://user-images.githubusercontent.com/5611731/37913796-bbfeb1f4-30e3-11e8-8d1d-9525e1c7e7bf.png)

## Steps to Reproduce (for bugs)
1. Open Firefox
2. Set default font size to 14
3. Open Icinga2 Docs, see how the text doesn't flow properly

## Context
This has bugged me for a while, but I only just figured it out.  I would hope this is easy to fix, but I don't know CSS very much and this is beyond my knowledge.  It's made reading the docs a lot harder than it should have.

## Your Environment
Firefox ESR 52.6.0 (64-bit) on RHEL6 is my primary, but I've confirmed that it happens on other browsers where the default font is set smaller than the browser defaut.

**Comment by dnsmichi** [comment]
Thanks. Please copy that issue over to https://github.com/Icinga/icinga-docs-tools to let @bobapple handle it.

**Comment by offsides** [comment]
Done, thanks for the pointer.
