### ISSUE TITLE
Installaing 2.8.2 re-adds deleted configs to conf.d folder without asking

### ISSUE THREAD

**Issue by log1-c** [Icinga/icinga2#6188]
After installing icinga2 2.8.2 there were config files (e.g templates.conf) in my /etc/icinga2/conf.d folder again.

## Expected Behavior

The installation process should ask if the config should be placed there.
At least that was the case before (on Ubuntu)
## Current Behavior

The installation process just places the files there, resulting in an error on start up, if you removed the files previously and used Icinga Director to roll out configs.
## Possible Solution

Ask the user if the files should be installed.
## Steps to Reproduce (for bugs)

1. yum update (with icinga2 2.8.1 currently installed)
2. install updates to 2.8.2
3. systemctl status icinga2.service
4. startup failed (for me)

## Your Environment

* Version used (`icinga2 --version`): 2.8.2
* Operating System and version: CentOS Linux release 7.4.1708 (Core)
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification perfdata

**Comment by dgoetz** [comment]
This is not possible with RPM. 

Because of this it is recommended to replace the include of conf.d with your own directory (or if using distributed monitoring not using a local configuration at all).

**Comment by dnsmichi** [comment]
Has been asked many times, and @dgoetz is correct. Closed.

**Comment by log1-c** [comment]
@dgoetz thank you for clarifying :)
It's my first setup of icinga2 with CentOS, will keep it in mind!
