### ISSUE TITLE
Windows X509Certificate2 does not support sha256ECDSA

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#6200]
I'm running into the current exception when running the setup wizard on Windows, build from a recent master:
```
An unhandled exception of type 'System.NotSupportedException' occurred in System.Windows.Forms.dll

Additional information: Der Zertifikatsschlüsselalgorithmus wird nicht unterstützt.
```
TL: The certificate key algorithm is not supported

The algorithm in question is sha256ECDSA
My Openssl version on 1.0.2n

**Comment by dnsmichi** [comment]
Originates from #5555

**Comment by Crunsher** [comment]
According to [this](https://stackoverflow.com/a/38135590/9669693) ECDSA-sha256 requires .NET framework version 4.6.1, we are running 4.0.X on the build server.

**Comment by dnsmichi** [comment]
Note: If this raises the Windows client package dependency to a newer .NET package, we should discuss that.
