### ISSUE TITLE
IDO pgsql with TLS support

### ISSUE THREAD

**Issue by Holundermann** [Icinga/icinga2#6211]
## Expected Behavior
ido-pgsql supports TLS and authentication via x509 certificates against the PostgreSQL server

## Current Behavior
There is no support for TLS in the ido-pgsql feature

## Possible Solution
Implement TLS for secure connections to the PostgreSQL server.
Implement the use of certificates to authenticate against the PostgreSQL server.

## Steps to Reproduce (for bugs)
Try to use TLS for PostgreSQL connection

## Context
Tried to use TLS for the postgres ido connection.

## Your Environment

* Version used (`icinga2 --version`): 2.8.2-1
* Operating System and version: Debian 9.4
* Enabled features (`icinga2 feature list`): api checker command compatlog graphite ido-pgsql mainlog notification statusdata
* Icinga Web 2 version and modules (System - About): 
  * director | 1.4.3
  * monitoring | 2.5.1
  * puppetdb | 1.0.0

**Comment by Holundermann** [comment]
What is a PR?

**Comment by Crunsher** [comment]
A Pull Request, ie. a patch from you that adds TLS to the Postgres writer

**Comment by dnsmichi** [comment]
More details and hints can be found in the contributing guide: https://github.com/Icinga/icinga2/blob/master/CONTRIBUTING.md

**Comment by dnsmichi** [comment]
# PostgreSQL server with TLS

PostgreSQL is installed via Homebrew on macOS, Icinga 2 schema and setup is also already there.

```
cd /usr/local/var/postgres

sudo cp /usr/local/icinga2/etc/icinga2/pki/mbmif.int.netways.de.* .
sudo cp /usr/local/icinga2/etc/icinga2/pki/ca.crt .
sudo chown michi mbmif.int.netways.de.* ca.crt

vim postgresql.conf

ssl = on
ssl_cert_file = 'mbmif.int.netways.de.crt'
ssl_key_file = 'mbmif.int.netways.de.key'
ssl_ca_file = 'ca.crt'

brew services restart postgresql
```

https://www.postgresql.org/docs/9.3/static/libpq-connect.html#LIBPQ-CONNSTRING

```
michi@mbmif /usr/local/var/postgres $ psql "host=127.0.0.1 sslmode=require" icinga
psql (10.3)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: on)
Type "help" for help.

icinga=> \q

michi@mbmif /usr/local/var/postgres $ psql "host=127.0.0.1 sslmode=verify-full sslrootcert=ca.crt" icinga
psql: server certificate for "mbmif.int.netways.de" does not match host name "127.0.0.1"

michi@mbmif /usr/local/var/postgres $ psql "host=mbmif.int.netways.de sslmode=verify-full sslrootcert=ca.crt" icinga
psql (10.3)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: on)
Type "help" for help.

icinga=>
```

**Comment by dnsmichi** [comment]
In contrast to MySQL, PostgreSQL supports specific ssl modes, using `requiressl` is deprecated. This allows to proxy the decision to the user and just use the same strings for TLS support. There's no Icinga 2 validation here, but logs are pretty verbose on connect, also if libpq doesn't link against openssl.

```
mbmif /usr/local/icinga2 (master *) # cat etc/icinga2/features-enabled/ido-pgsql.conf
/**
 * The db_ido_pgsql library implements IDO functionality
 * for PostgreSQL.
 */

library "db_ido_pgsql"

object IdoPgsqlConnection "ido-pgsql" {
  //user = "icinga"
  //password = "icinga"
  //host = "localhost"
  //database = "icinga"

  host = "mbmif.int.netways.de"
  ssl_mode = "verify-full"
  ssl_cert = SysconfDir + "/icinga2/pki/mbmif.int.netways.de.crt"
  ssl_key = SysconfDir + "/icinga2/pki/mbmif.int.netways.de.key"
  ssl_ca = SysconfDir + "/icinga2/pki/ca.crt"
}
```

```
[2018-04-18 15:21:16 +0200] information/IdoPgsqlConnection: PGSQL IDO instance id: 1 (schema version: '1.14.3'), sslmode='verify-full'
```

**Comment by dnsmichi** [comment]
Rationale for implementing this: Adds a benefit for 2.9, and implemented in <30 min.
