### ISSUE TITLE
Reload-internal with unresolved shell variable

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#6214]
Just spotted this - not sure where this is coming from, but it looks wrong. @Crunsher any idea?

```
[2018-04-09 09:25:32 +0200] notice/Process: Running command '/usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2' '--no-stack-rlimit' 'daemon' '-e' '$ICINGA2_LOG_DIR/error.log' '--reload-internal' '122991': PID 123126
```

**Comment by Crunsher** [comment]
Where is this coming from? After a config reload?

**Comment by dnsmichi** [comment]
Just seen it in here, https://monitoring-portal.org/t/top-down-config-sync-communication-works-config-gets-synced-but-no-host-objects-on-client/1950/19?u=dnsmichi

>   Platform version: 16.04.4 LTS (Xenial Xerus)

I've checked the Ubuntu specific scripts but couldn't find a reference which would explain the shell variable being passed.

**Comment by Crunsher** [comment]
I don't believe this is coming from our code. The user might have edited their init scripts or have a something weird in their sysconfig.

**Comment by dnsmichi** [comment]
Ok, fine.

**Comment by v1dlak** [comment]
This is systemd "feature" with EnvironmentFile.
```
# grep EnvironmentFile /lib/systemd/system/icinga2.service
EnvironmentFile=/usr/lib/icinga2/icinga2
EnvironmentFile=/etc/default/icinga2
```

Because `Variable expansion is not performed inside the strings, and $ has no special meaning. `

So this is wrong for systemd
```
# cat /usr/lib/icinga2/icinga2
DAEMON=/usr/sbin/icinga2
ICINGA2_CONFIG_FILE=/etc/icinga2/icinga2.conf
ICINGA2_RUN_DIR=/run
ICINGA2_STATE_DIR=/var
ICINGA2_PID_FILE=$ICINGA2_RUN_DIR/icinga2/icinga2.pid
ICINGA2_LOG_DIR=/var/log/icinga2
ICINGA2_ERROR_LOG=$ICINGA2_LOG_DIR/error.log
ICINGA2_STARTUP_LOG=$ICINGA2_LOG_DIR/startup.log
ICINGA2_LOG=$ICINGA2_LOG_DIR/icinga2.log
ICINGA2_CACHE_DIR=$ICINGA2_STATE_DIR/cache/icinga2
ICINGA2_USER=nagios
ICINGA2_GROUP=nagios
ICINGA2_COMMAND_GROUP=www-data
```

**Comment by Crunsher** [comment]
[You are right](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment=)
I'll expand the defaults by hand. Maybe we can even get rid of some of them.

**Comment by dnsmichi** [comment]
a49a598eef is sitting there since 2014, this might explain some pid file problems with Systemd.
