### ISSUE TITLE
Notification Apply rules not working for certain services - might be an order of operations error

### ISSUE THREAD

**Issue by BirkirFreyr** [Icinga/icinga2#6222]
## Expected Behavior

Expected the notification rule to apply to the service as it has the correct vars set

## Current Behavior

Notification rule does not apply to services that have their variables rendered from the hosts variables.
(Perhaps this is just wishful behaviour on my end and this actually shouldn't work, please tell me if its so, so that i can fix my setup accordingly)

## Steps to Reproduce (for bugs)

This is all done through Director, so might be a Director problem, but i think it's more likely an Icinga problem with how it reads the config / in what order it loads the config

Commands / groups /templates may need to be stripped or switched out for this to work in your environment.
1. Create Host definition (This works):
```
object Host "uranus.example.com" {
    import "generic-host"

    address = "192.168.0.20"
    groups = [ "webservers" ]
    vars.SLA = "24x7"
    vars.department = [ "IT" ]
    vars.os = "Linux"
}
```
2. Create Service Apply rule definition (This also works, applying the hosts SLA and department vars to the service):
```
apply Service "Check disk(s)" {
    check_command = "check_disk"
    max_check_attempts = "5"
    check_interval = 4m
    retry_interval = 1m
    enable_active_checks = true
    enable_passive_checks = true
    zone = "zone"
    host.vars.os == "Linux"
    vars.SLA = host.vars.SLA
    vars.department = [ host.vars.department ]

    import DirectorOverrideTemplate
}
```
3. Create Notification apply rule (This does NOT work for services with vars rendered from host vars):
```
apply Notification "Bakvakt-Notifications-SMS-Services-24x7" to Service {
    command = "sms-utbakvakt-service-notification"
    interval = 30m
    period = "24x7"
    assign where service.vars.SLA == "24x7" && "IT" in service.vars.department 
    states = [ Critical ]
    types = [ Acknowledgement, Problem, Recovery ]
    users = [ "bakvakt" ]
}
```
4. Reload

## Context

We have multiple departments monitoring multiple different things, the hope was to just need to create the host with correct vars and the basic services (disks, load, mem etc.) would apply correctly on the hosts with the correct vars (which could be overridden on a per service level) so that the notification apply rules would then be applied on top of.

## Your Environment

* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: Debian 8
* Enabled features (`icinga2 feature list`): Enabled features: api checker ido-pgsql influxdb mainlog notification
* Icinga Web 2 version and modules (System - About): 
Icingaweb2: 2.5.1
businessprocess: 2.1.0
director: 1.4.2
grafana: 1.1.7
monitoring: 2.5.1
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga2.example.com
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'aot-gps-eldv' (in /etc/icinga2/zones.d/master/eldv-apply.conf: 1:0-1:43) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'UT-NAS-stale file handle' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/master/notification_apply.conf: 18:1-18:56) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'CPU load' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 401:1-401:24) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Operating System Disk' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 413:1-413:37) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'NSClient++ Version' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 425:1-425:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Physical Memory Usage' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 437:1-437:37) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Check Uptime' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 449:1-449:28) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Check disk(s)' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 461:1-461:29) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Check load' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 472:1-472:26) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Checking swap space' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 484:1-484:35) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'NTP check' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 496:1-496:37) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Check Network Traffic' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 508:1-508:37) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Check Memory Usage' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 520:1-520:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Check NRPE' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 532:1-532:26) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'ssh' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 543:1-543:19) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Check Uptime' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 554:1-554:28) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Check Web server status' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 619:1-619:39) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Scheduled observation has arrived later than 20 minutes' (in /var/lib/icinga2/api/packages/director/icinga2-1523529005-417/zones.d/director-global/service_apply.conf: 817:1-817:71) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 5 Zones.
information/ConfigItem: Instantiated 5 Endpoints.
information/ConfigItem: Instantiated 6 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 3147 Notifications.
information/ConfigItem: Instantiated 9 NotificationCommands.
information/ConfigItem: Instantiated 233 CheckCommands.
information/ConfigItem: Instantiated 177 Downtimes.
information/ConfigItem: Instantiated 33 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 711 Hosts.
information/ConfigItem: Instantiated 102 Comments.
information/ConfigItem: Instantiated 11 UserGroups.
information/ConfigItem: Instantiated 42 Users.
information/ConfigItem: Instantiated 2 TimePeriods.
information/ConfigItem: Instantiated 4622 Services.
information/ConfigItem: Instantiated 39 ServiceGroups.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
Not really a bug, but a configuration issue. Next time please ask such questions on the community support channels.

`host.vars.department` is an array. Then the service apply rule puts that array as value into another array, creating a nested array. Using the `in` operator to check for a string value in an array requires string elements in that array. That is not the case, as those elements are an array on its own.

Can be fixed with setting `host.vars.department = "stringvalue"`.
