### ISSUE TITLE
InfluxWriter is not passing data to influxDb from passive checks.

### ISSUE THREAD

**Issue by fabriciomrtnz** [Icinga/icinga2#6228]
I've setup a new VM as an icinga monitoring station. I've setup perfdata and influxdb. Problem I'm having is that I have also setup passive (remote) checks and while I do receive and see the data in Icinga this information is not passed on to the influxDB. In the influxDB I do find data for the local icinga machine.

**Comment by dnsmichi** [comment]
This isn't really a complete bug report, not sounds like one. For bugs and feature requests we do have an issue template you should fill in, for general usage questions and troubleshooting please use the community support channels such as lists.icinga.org or https://monitoring-portal.org

Cheers,
Michael
