### ISSUE TITLE
Icinga 2.8.2 on debian stretch OS doesn't put config issues in /var/log/icinga2/startup.log like icinga 2.6 does

### ISSUE THREAD

**Issue by gangamaha** [Icinga/icinga2#6245]
Icinga 2.8.2 on debian stretch OS doesn't put config issues in /var/log/icinga2/startup.log like icinga 2.6 does

I currently have icinga 2.8 installed on my dev and have no issues starting the systemd process and deploying monitors. However in previous version of icinga 2.6(which I was running on wheezy) the init script created startup.log and icinga2.err under /var/log/icinga2 directory showing configuration tests and any issues in icinga object configuration. But I don't see them in newer version of icinga2.8. I looked at the inbuilt systemd file and it has before process start
```
ExecStartPre=/usr/lib/icinga2/prepare-dirs /usr/lib/icinga2/icinga2
ExecStart=/usr/sbin/icinga2 daemon -e ${ICINGA2_ERROR_LOG}
```
The /usr/lib/icinga2/icinga2 has all the log file path set
```
DAEMON=/usr/sbin/icinga2
ICINGA2_CONFIG_FILE=/etc/icinga2/icinga2.conf
ICINGA2_RUN_DIR=/run
ICINGA2_STATE_DIR=/var
ICINGA2_PID_FILE=$ICINGA2_RUN_DIR/icinga2/icinga2.pid
ICINGA2_ERROR_LOG=/var/log/icinga2/error.log
ICINGA2_STARTUP_LOG=/var/log/icinga2/startup.log
ICINGA2_LOG=/var/log/icinga2/icinga2.log
ICINGA2_USER=nagios
ICINGA2_GROUP=nagios
ICINGA2_COMMAND_GROUP=www-data

```
 but I am not sure if /usr/lib/icinga2/prepare-dirs creates startup.log files. I tried various options to create them within prepare-dirs script and also modified systemd file to write the logs to another file but it looks like everything is going to /var/log/syslog.

Would like the configuration issues and other details go to /var/log/icinga2/startup.log (as icinga2.6 had) in new version icinga2.8. Routing icinga startup object config issues to syslog isn;t very helpful. Please advise

## Expected Behavior
Configuration issues during icinga startup should go to startup.log and not syslog

## Possible Solution
Incorporate startup.log in ExecStartPre or ExecStart systemd file
1. Install Icinga 2.8 .Version i have is icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-2. Start the icinga process with some bugs in icinga objects(like zone missing or anything)
3. Startup issues gets logs to /var/log/syslog. In icinga2.6 it usually goes to /var/log/icinga2/startup.log

## Context
We are upgrading from 2.6 to 2.8 and startup.log and icinga2.err have been very helpful in debugging configuration issues and to-go place for any team to debug whenever process has issues. Putting them to syslog is confusing since it's not a dedicated icinga log file

## Your Environment

root@ossipemasteradc0101a:/usr/lib/icinga2# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-6-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: 022328c363ac

* Enabled features (`icinga2 feature list`):
root@ossipemasteradc0101a:/usr/lib/icinga2# icinga2 feature list
Disabled features: elasticsearch gelf influxdb opentsdb perfdata statusdata syslog
Enabled features: api checker command compatlog debuglog graphite ido-mysql livestatus mainlog notification

* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
root@ossipemasteradc0101a:/usr/lib/icinga2# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.8.2-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: ossipemasteradc0101a.softlayer.local
warning/ApplyRule: Apply rule 'esDependency' (in /etc/icinga2/zones.d/global-templates/apply-rules/esDependency.conf: 1:0-1:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'COSdataPathSquadEmailHostNotification' (in /etc/icinga2/zones.d/global-templates/apply-rules/COSdataPathSquadEmailHostNotification.conf: 2:1-2:66) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'COSdataPathSquadEmailServiceNotification' (in /etc/icinga2/zones.d/global-templates/apply-rules/COSdataPathSquadEmailServiceNotification.conf: 2:1-2:72) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'OfferingSquadEmailHostNotification' (in /etc/icinga2/zones.d/global-templates/apply-rules/OfferingSquadEmailHostNotification.conf: 2:1-2:63) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'OfferingSquadEmailServiceNotification' (in /etc/icinga2/zones.d/global-templates/apply-rules/OfferingSquadEmailServiceNotification.conf: 2:1-2:69) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
warning/ApplyRule: Apply rule 'apt' (in /etc/icinga2/conf.d/apt.conf: 1:0-1:18) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-data0DiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-data0DiskUsage.conf: 2:1-2:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-data1DiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-data1DiskUsage.conf: 2:1-2:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-data2DiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-data2DiskUsage.conf: 2:1-2:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-data3DiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-data3DiskUsage.conf: 2:1-2:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-data4DiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-data4DiskUsage.conf: 2:1-2:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-data5DiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-data5DiskUsage.conf: 2:1-2:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-data6DiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-data6DiskUsage.conf: 2:1-2:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-data7DiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-data7DiskUsage.conf: 2:1-2:34) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-interfaceEth0ErrRx' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-interfaceEth0ErrRx.conf: 2:1-2:38) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-interfaceEth0ErrTx' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-interfaceEth0ErrTx.conf: 2:1-2:38) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-interfaceLoErrRx' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-interfaceLoErrRx.conf: 2:1-2:36) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-interfaceLoErrTx' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-interfaceLoErrTx.conf: 2:1-2:36) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-loadAvg' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-loadAvg.conf: 2:1-2:27) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-logsDiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-logsDiskUsage.conf: 2:1-2:33) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-ping4' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-ping4.conf: 2:1-2:25) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-rootDiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-rootDiskUsage.conf: 2:1-2:33) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cmr-ssh' (in /etc/icinga2/zones.d/global-templates/apply-rules/cmr-ssh.conf: 2:1-2:23) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'cosbenchProcess' (in /etc/icinga2/zones.d/global-templates/apply-rules/cosbenchProcess.conf: 2:1-2:31) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'datapath-ping4' (in /etc/icinga2/zones.d/global-templates/apply-rules/datapath-ping4.conf: 2:1-2:30) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'datapath-ssh' (in /etc/icinga2/zones.d/global-templates/apply-rules/datapath-ssh.conf: 2:1-2:28) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'es-health-check' (in /etc/icinga2/zones.d/global-templates/apply-rules/es-health-check.conf: 2:1-2:31) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'kafka-broker' (in /etc/icinga2/zones.d/global-templates/apply-rules/kafka-broker.conf: 2:1-2:28) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'ldapGroupCheck' (in /etc/icinga2/zones.d/global-templates/apply-rules/ldapGroupCheck.conf: 2:1-2:30) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'loadAvgcicd' (in /etc/icinga2/zones.d/global-templates/apply-rules/loadAvgcicd.conf: 2:1-2:27) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'pbj-interfaceEth0ErrRx' (in /etc/icinga2/zones.d/global-templates/apply-rules/pbj-interfaceEth0ErrRx.conf: 2:1-2:38) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'pbj-interfaceEth0ErrTx' (in /etc/icinga2/zones.d/global-templates/apply-rules/pbj-interfaceEth0ErrTx.conf: 2:1-2:38) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'pbj-interfaceLoErrRx' (in /etc/icinga2/zones.d/global-templates/apply-rules/pbj-interfaceLoErrRx.conf: 2:1-2:36) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'pbj-interfaceLoErrTx' (in /etc/icinga2/zones.d/global-templates/apply-rules/pbj-interfaceLoErrTx.conf: 2:1-2:36) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'pbj-loadAvg' (in /etc/icinga2/zones.d/global-templates/apply-rules/pbj-loadAvg.conf: 2:1-2:27) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'pbj-ping4' (in /etc/icinga2/zones.d/global-templates/apply-rules/pbj-ping4.conf: 2:1-2:25) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'pbj-rootDiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/pbj-rootDiskUsage.conf: 2:1-2:33) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'pbj-ssh' (in /etc/icinga2/zones.d/global-templates/apply-rules/pbj-ssh.conf: 2:1-2:23) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'pbj-varDiskUsage' (in /etc/icinga2/zones.d/global-templates/apply-rules/pbj-varDiskUsage.conf: 2:1-2:32) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'ping4cicd' (in /etc/icinga2/zones.d/global-templates/apply-rules/ping4cicd.conf: 2:1-2:25) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'rootDiskUsagecicd' (in /etc/icinga2/zones.d/global-templates/apply-rules/rootDiskUsagecicd.conf: 2:1-2:33) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'sshcicd' (in /etc/icinga2/zones.d/global-templates/apply-rules/sshcicd.conf: 2:1-2:23) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'zookeeper-avg-latency' (in /etc/icinga2/zones.d/global-templates/apply-rules/zookeeper-avg-latency.conf: 2:1-2:37) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'zookeeper-outstanding-request' (in /etc/icinga2/zones.d/global-templates/apply-rules/zookeeper-outstanding-request.conf: 2:1-2:45) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'zookeeper-service' (in /etc/icinga2/zones.d/global-templates/apply-rules/zookeeper-service.conf: 2:1-2:33) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 2 FileLoggers.
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 24 Notifications.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 218 CheckCommands.
information/ConfigItem: Instantiated 4 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2 Hosts.
information/ConfigItem: Instantiated 9 UserGroups.
information/ConfigItem: Instantiated 4 Users.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 22 Services.
information/ConfigItem: Instantiated 6 ServiceGroups.
information/ConfigItem: Instantiated 1 CompatLogger.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 2 LivestatusListeners.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by Crunsher** [comment]
Thank you for opening this issue, we have yet to investigate and reproduce this. If anybody else is having this problem, please don't hesitate to comment here.

**Comment by dnsmichi** [comment]
Likely related to #6255

**Comment by gangamaha** [comment]
We really would appreciate startup error logs to go into the startyp.log file. In the meantime I updated the systemd environment to have
ExecStartPre=/bin/sh -c "icinga2 daemon C" --> so it checks the configuration before starting the process and can exit if there are any issues (more like wrapper and protection until we get startup logs consolidated in the right file instead of syslog)

**Comment by dnsmichi** [comment]
Can you test the snapshot packages?
