### ISSUE TITLE
Typo in Example Apache Configuration - Centos 7

### ISSUE THREAD

**Issue by Silvenga** [Icinga/icinga2#6246]
There is a typo in the output of the `icingacli setup config webserver apache` command on Icinga `r2.8.2-1`.

I would love to make a pull request, although, not sure where to look. Github's search is failing me.

```
# Remove comments if you want to use PHP FPM and your Apache version
# is greater than or equal to 2.4
#    <IfVersion >= 2.4>
#        # Forward PHP requests to FPM
#        SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
#        <FilesMatch "\.php$">
#            SetHandler "proxy:fgci://127.0.0.1:9000"
#            ErrorDocument 503 /icingaweb2/error_unavailable.html
#        </FilesMatch>
#    </IfVersion>
```

The output line:

```
SetHandler "proxy:fgci://127.0.0.1:9000"
```

Should be 

```
SetHandler "proxy:fcgi://127.0.0.1:9000"
```

Note the `fcgi` vs `fgci`.

## Context
Spent a while trying to figure out why I was receiving the following:

```
 AH01144: No protocol handler was valid for the URL /index.php. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.
```

Turns out Google is great:
![image](https://user-images.githubusercontent.com/2753330/39023924-1a82d1a6-4403-11e8-8e30-351cd69e3fd9.png)

## Your Environment

```
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-1)

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 4.15.12-x86_64-linode105
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```

**Comment by mcktr** [comment]
Thanks. The `icingacli` is part of the icingaweb2 repository and it seems that the typo is already fixed, have a look here https://github.com/Icinga/icingaweb2/pull/3354.

I close here.
