### ISSUE TITLE
Unexpected HA behavior. Schedule checks only to connected master nodes

### ISSUE THREAD

**Issue by xschlef** [Icinga/icinga2#6247]
We are currently running a two master HA setup. What we experience is that our monitoring will go haywire when a single master is disconnected for time X. We are running cluster-zone checks for each connected client to have a dependency for child checks, which disable notifications and checks. The cluster-zone checks will instead start sending notifications to reduce notification spam. These checks are not assigned to a specific master and instead are scheduled by icinga2 over all masters.

Currently the cluster-zone checks will go down for the offline master and will not be scheduled to the still available master instead. This is unexpected, because I expect the monitoring to still work as long as a single master node is online and reachable.

## Expected Behavior

As long as a single master node can still be reached by a client, all checks should be executed and not just those that were scheduled to the connected master.

## Current Behavior

If a client can only reach a subset of the master nodes (for whatever reason), only the checks that are scheduled to the connected masters will be executed, leaving it to luck if the monitoring has a meaningful state.

## Possible Solution

- Create a configurable dependency to influence the internal scheduler of icinga2
- icinga2 should detect a possible connectivity issue by itself and move the scheduling to the connected master (I am aware that this has a meaningful performance impact, so make it available through a configuration option)
- in case of a graceful shutdown, inform the other master nodes that no checks can be executed at the moment and trigger the scheduler

## Steps to Reproduce (for bugs)

1. Create a HA Setup with multiple masters
2. Set up a client to connect to both masters (this step should be optional)
3. Then reconfigure the client to only connect to one of them
4. Several checks will now be in state UNKNOWN and not be checkable by icinga (I have not yet found out if they will ever be checked). This is because icinga2 schedules the checks over all masters and not just those that can reach this client.

## Context

We want a fully redundant setup where a single master can take over all the work and not just a subset of the checks. I am aware that this is a corner case and a client should always be able to connect to all masters, but when we are reloading configuration we get a lot of lost connections in monitoring (usually just soft states). This makes it seem like there is some kind of network issue. As we are deploying the configuration through a config management, we see this issue every time we make a configuration change.

## Your Environment

* Version used (`icinga2 --version`):
r2.8.2-1
* Operating System and version:
Debian Stretch (9.4)
* Enabled features (`icinga2 feature list`):
api checker command ido-mysql influxdb mainlog notification syslog
* Icinga Web 2 version and modules (System - About):
2.5.1, doc, grafana, monitoring
* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: r2.8.2-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: X
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 1 SyslogLogger.
information/ConfigItem: Instantiated 420 Zones.
information/ConfigItem: Instantiated 421 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 438 ApiUsers.
information/ConfigItem: Instantiated 19643 Notifications.
information/ConfigItem: Instantiated 7 NotificationCommands.
information/ConfigItem: Instantiated 146 CheckCommands.
information/ConfigItem: Instantiated 1585 Downtimes.
information/ConfigItem: Instantiated 37 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3 EventCommands.
information/ConfigItem: Instantiated 614 Hosts.
information/ConfigItem: Instantiated 260 Comments.
information/ConfigItem: Instantiated 4 UserGroups.
information/ConfigItem: Instantiated 5791 Dependencies.
information/ConfigItem: Instantiated 24 Users.
information/ConfigItem: Instantiated 5 TimePeriods.
information/ConfigItem: Instantiated 8498 Services.
information/ConfigItem: Instantiated 36 ServiceGroups.
information/ConfigItem: Instantiated 259 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

**Comment by Crunsher** [comment]
Are you using `command_endpoint` for all those checks? And please post the zone.conf from one of the masters and a client (master endpoints + zone and one client endpoint + zone from each)

**Comment by xschlef** [comment]
The checks entering UNKNOWN are all using command_endpoint pointing toward the client (hence the dependency). The cluster-zone checks are not using command endpoint, thus being scheduled to the master zone.

Zone configs are a little tricky as we are generating a single huge config file from our config management (we are not using director).

Client:
```
object Endpoint "<master1>" {
	host = "<master1>"
	port = "5665"
}
object Endpoint "<master2>" {
	host = "<master2>"
	port = "5665"
}
object Zone "master" {
	endpoints = [ "<master1>", "<master2>" ]
}
object Endpoint "<client>" {

}

object Zone "<client>" {
	endpoints = [ "<client>" ]
	parent = "master"
}
```

Master 1:
```
object Zone "master" {
	endpoints = [ "<master1>", "<master2>" ]
}

object Endpoint "<master2>" {
	host = "<master2>"
	port = "5665"
}

object Endpoint "<master1>" {
}
```

Config on master for client in seperate file:
```
object Host "<client>" {
...
}

object Endpoint "<client>" {
  log_duration = 0
}

object Zone "<client>" {
  endpoints = [ "<client>" ]
  parent = "master"
}
```

**Comment by Crunsher** [comment]
When you have both masters with the checker enabled they should switch over as one goes down. And since we have not had any other problems with that in 2.8.2 yet, I wouldn't rule out a miss-configuration just yet. So please excuse me asking more boring questions :stuck_out_tongue: 

What is this 'Config on master for client in separate file'? Do you have all your configuration in `/zones.d/` or are there also local configs?

**Comment by xschlef** [comment]
Both masters have `checker` enabled.

We are deploying CheckCommands locally through our config management as we need to push the corresponding binaries anyway. They are currently not defined in a global zone. But this will be changed in the future.

zones.conf, icinga2.conf and constants.conf are the only other config files deployed locally.

The masters sync their configuration (except the CheckCommands) through `zones.d/master` which is deployed through our config management to a single master.

Our icinga2.conf looks like this:
```
/**
 * Icinga 2 configuration file
 * - this is where you define settings for the Icinga application including
 * which hosts/services to check.
 *
 * For an overview of all available configuration options please refer
 * to the documentation that is distributed as part of Icinga 2.
 */

/**
 * The constants.conf defines global constants.
 */
include "constants.conf"

/**
 * The zones.conf defines zones for a cluster setup.
 * Not required for single instance setups.
 */
include "zones.conf"

/**
 * The Icinga Template Library (ITL) provides a number of useful templates
 * and command definitions.
 * Common monitoring plugin command definitions are included separately.
 */
include <itl>
include <plugins>
// include <plugins-contrib>

/**
 * The features-available directory contains a number of configuration
 * files for features which can be enabled and disabled using the
 * icinga2 feature enable / icinga2 feature disable CLI commands.
 * These commands work by creating and removing symbolic links in
 * the features-enabled directory.
 */
include "features-enabled/*.conf"

/**
 * The repository.d directory contains all configuration objects
 * managed by the 'icinga2 repository' CLI commands.
 */
//include_recursive "repository.d"

/**
 * Although in theory you could define all your objects in this file
 * the preferred way is to create separate directories and files in the conf.d
 * directory. Each of these files must have the file extension ".conf".
 */
include_recursive "commands.d"
```

**Comment by Crunsher** [comment]
Thanks, I'll have to try and reproduce this when I get the chance

**Comment by dnsmichi** [comment]
This isn't an issue, but a feature request to have sort of dynamic load balancing based on connections top-down. I don't think that we will add something on the future, for now both masters need a connection to the client, that is by design.

**Comment by Crunsher** [comment]
Oh my understanding was this is about balancing checks between masters, which should be mostly even.

**Comment by dnsmichi** [comment]
It is, which is ensured by the object's authority. The OP wants a dynamic object authority update in case an endpoint is not connected, and "move" the check to a different node. The key problem here is that HA enabled nodes don't know anything about the other one, and cannot easy "move object authorities". There's no logic for such balancing implemented, nor support for possible edge cases where they would play ping-pong on connection losses.

This is a dangerous field, and as such I doubt that we're gonna implement changes to it.

**Comment by dnsmichi** [comment]
After thinking and discussing this for a while, we've agreed to not implement this.
