### ISSUE TITLE
ITL command check_swap

### ISSUE THREAD

**Issue by xtruthx** [Icinga/icinga2#6248]
We should remove the command option "-n" from  the check_swap cause it did not exist any longer or actual.

#### itl-command:

> 

object CheckCommand "swap" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_swap" ]
    timeout = 1m
    arguments += {
        "-a" = {
            description = "Conduct comparisons for all swap partitions, one by one"
            set_if = "$swap_allswaps$"
        }
        "-c" = {{
            /* Unable to fetch function body through API */
        }}
        "-n" = {
            description = "Resulting state when there is no swap regardless of thresholds. Possible values are \"ok\", \"warning\", \"critical\", \"unknown\". Defaults to \"critical\""
            value = "$swap_noswap$"
        }
        "-w" = {{
            /* Unable to fetch function body through API */
        }}
    }
    vars.swap_allswaps = false
    vars.swap_cfree = 25
    vars.swap_integer = false
    vars.swap_wfree = 50
}

#### Affected file:
`
[root@localhost~]# less /usr/share/icinga2/include/command-plugins.conf
`
#### check output:
`
/usr/lib64/nagios/plugins/check_swap: invalid option -- 'n'
Usage:
 check_swap [-av] -w <percent_free>% -c <percent_free>%
  -w <bytes_free> -c <bytes_free>
`

>
[root@localhost~]# /usr/lib64/nagios/plugins/check_swap --help
check_swap v2.2.1 (nagios-plugins 2.2.1)
Copyright (c) 2000-2014 Nagios Plugin Development Team
        <devel@nagios-plugins.org>

Check swap space on local machine.

Usage:
 check_swap [-av] -w <percent_free>% -c <percent_free>%
  -w <bytes_free> -c <bytes_free>

Options:
 -h, --help
    Print detailed help screen
 -V, --version
    Print version information
 --extra-opts=[section][@file]
    Read options from an ini file. See
    https://www.nagios-plugins.org/doc/extra-opts.html
    for usage and examples.
 -w, --warning=INTEGER
    Exit with WARNING status if less than INTEGER bytes of swap space are free
 -w, --warning=PERCENT%%
    Exit with WARNING status if less than PERCENT of swap space is free
 -c, --critical=INTEGER
    Exit with CRITICAL status if less than INTEGER bytes of swap space are free
 -c, --critical=PERCENT%%
    Exit with CRITICAL status if less than PERCENT of swap space is free
 -a, --allswaps
    Conduct comparisons for all swap partitions, one by one
 -v, --verbose
    Show details for command-line debugging (Nagios may truncate output)

Notes:
 Both INTEGER and PERCENT thresholds can be specified, they are all checked.
 On AIX, if -a is specified, uses lsps -a, otherwise uses lsps -s.

Send email to help@nagios-plugins.org if you have questions regarding use
of this software. To submit patches or suggest improvements, send email to
devel@nagios-plugins.org

>
#### OS:
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Red Hat Enterprise Linux Server release 7.4 (Maipo)
cpe:/o:redhat:enterprise_linux:7.4:ga:server

#### Icinga 2 Version:
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.1.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

It seems that there is in the project a open merge request for it https://github.com/nagios-plugins/nagios-plugins/pull/369.

And may someone can tell me why it did not format the issue in the right beahviour?

Cheers

**Comment by Crunsher** [comment]
This was added with 3454cf88a77910c034c406d6d7d64cd5d714183a by @dnsmichi two years back.
The problem with the ITL and the monitoring plugins is that we can never be sure which version and, with that, arguments the user has. But if there never was a `-n` parameter we shouldn't support it :laughing:

**Comment by xtruthx** [comment]
Thats what i allready told the people around me and you are sure. Thats what i also thought it was never there but in the future maybe. As we can see nagios-plugins/nagios-plugins#369 .

**Comment by Crunsher** [comment]
Feel free to create a PR :)
But I will wait on @dnsmichi to comment on this before considering to merge.

**Comment by xtruthx** [comment]
Here is the pr #6249. I  hope the style is ok;)

**Comment by xtruthx** [comment]
No i am confused. I just wanted to remove the option from the documentation and however i followed the link to the documenation on monitoring-plugins.org https://www.monitoring-plugins.org/doc/man/check_swap.html.

>  -n, --no-swap=<ok|warning|critical|unknown>
    Resulting state when there is no swap regardless of thresholds. Default: CRITICAL

and as you can see they really have a reference for this option!

**Comment by mcktr** [comment]
You are comparing monitoring-plugins and nagios-plugins, this are two different things.

The check_swap plugin from monitoring-plugins supports the `-n` attribute as you can see here: https://www.monitoring-plugins.org/doc/man/check_swap.html. But the check_swap plugin from nagios-plugins do not support the `-n` support: http://nagios-plugins.org/doc/man/check_swap.html

Since we are mention the monitoring-plugins in the documentation I would stay with that version, but I don't know if all Linux distributions have the monitoring-plugins in their repositories, so it may makes sense to drop the parameter `-n` to support both versions.

**Comment by Crunsher** [comment]
We can't drop the parameter if it exists in the monitoring-plugins, which we base the ITL on.

**Comment by mcktr** [comment]
Should we than add a note to the ITL documentation? For example:

> The Icinga Template Library is based on the Monitoring Plugins. Please note that other Plugin collections might not support all attributes.

**Comment by Crunsher** [comment]
Yes, a note would make sense [here](https://www.icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#plugin-check-commands-for-monitoring-plugins)

**Comment by mcktr** [comment]
I'll take care of. 😃
