### ISSUE TITLE
Is there a way to change default directory of perfdata

### ISSUE THREAD

**Issue by meridian-admin** [Icinga/icinga2#6252]
Hello Experts,

I am trying to move the created perfdata directory from the default /var/spool/icinga2/perfdata to a custom one (a newly created partition). However when changed the perfdata.conf Icinga2 does not start. Can you help me determine the most likely silly mistake I have made?

library "perfdata"
object PerfdataWriter "perfdata" {

host_perfdata_path = "/icinga_perfdata"
service_perfdata_path = "/icinga_perfdata"

}

# df -h
Filesystem                                       Size  Used Avail Use% Mounted on
/dev/sda2                                         30G   24G  5.7G  81% /
/dev/mapper/icinga_perfdata-icinga_perfdata_lvm  100G   33M  100G   1% /var/icinga_perfdata

Also tried setting the directory to a /icinga_perfdata mounted drive 
# second try
# df -h
Filesystem                                       Size  Used Avail Use% Mounted on
/dev/sda2                                         30G   24G  5.7G  81% /
/dev/mapper/icinga_perfdata-icinga_perfdata_lvm  100G   33M  100G   1% /icinga_perfdata

icinga2 - The Icinga 2 network monitoring daemon (version: v2.6.3)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.26.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

**Comment by mcktr** [comment]
Hi,

ensure that the directory is writable by the `icinga` user.

Kind regards
Michael

**Comment by dnsmichi** [comment]
The error message is missing in your report.

**Comment by dnsmichi** [comment]
Closing since there wasn't any feedback.
