### ISSUE TITLE
Allow command path expansion with Windows %SystemRoot% etc aliases

### ISSUE THREAD

**Issue by flohoff** [Icinga/icinga2#6259]
Hi,
it would be nice to use the Windows Path Aliases aka %SystemRoot% %ProgramFiles% %ProgramData% and the like in command path and arguments.

I defined this in Icinga Director which fails for multiple reasons (Spaces in Command Path, Not detecting the absoluteness of %SystemRoot% etc)

So i am using this:

c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy ByPass -NonInteractive -NoProfile -Command "c:\windows\Program Files\icinga2\checks\countprocesses.ps1"

I like to replace the command with %ProgramFiles%\icinga2\checks\countprocesses.ps1

Icinga would need to expand/glob? Windows Path aliases in command path and arguments.

Flo

**Comment by Crunsher** [comment]
This is a good first issue for someone who hasn't worked much with icinga2 but knows their way around windows programming.

**Comment by Thomas-Gelf** [comment]
@Crunsher: are there plans to implement this? Eventually ask @LordHepipud in case you need related input.

**Comment by Crunsher** [comment]
Currently nobody is working on this issue.

**Comment by dnsmichi** [comment]
If you want to look into a patch, you can start with https://msdn.microsoft.com/en-us/library/ms724265.aspx inside the macro resolver or process class. It needs the win32 ifdefs too.

**Comment by dnsmichi** [comment]
@htriem We'll come back to this in the next week when we learn about Windows development.

**Comment by htriem** [comment]
@Al2Klimov

**Comment by Al2Klimov** [comment]
IMAO it makes no sense to expand `%X%` on Windows, while not expanding `$X` on \*nix.

@N-o-X @htriem Please comment.

@flohoff I'd recommend you `command = [ "cmd", "/C", "command with %X%" ]`.

**Comment by Al2Klimov** [comment]
@N-o-X @htriem Also what do you think about having `$env.VAR$` in addition to `$host.ATTR$`/`$service.ATTR$`?
