### ISSUE TITLE
High service checks degradation between satellite(s) and master

### ISSUE THREAD

**Issue by moix** [Icinga/icinga2#6269]
Hi, we are experiencing a high latency between service checks happen in satellites and when they are received/processed in master.

Description of the setup:
* master (4 cpu, 12GB memory, 2GB swap), centos 7
features enabled: Enabled features: api checker command ido-mysql influxdb livestatus mainlog notification
icingaweb 2.5.0
* multiple zones, only biggest is experiencing the degradation: 2 satellites 12cpu, 4GB. 7000 services checks 1m, 600 hosts load 1m. , centos 7

version is same in all of them:
```icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)```

zones.conf is standard, e.g. in master:
```
#
# master endpoint(s) definitions
#
object Endpoint NodeName {
       host = NodeName
       port = "5665"
}

object Zone ZoneName {
        endpoints = [ NodeName ]
}

object Zone "global" {
        global = true
}

object Zone "global-internal" {
        global = true
}

object Zone "global-external" {
        global = true
}

... #satellites definition
```

similar in the satellites, e.g. satellite-1:
```
object Endpoint "master" {
  //do not actively connect to the master by leaving out the 'host' attribute
  //host = "master"
  //port = "5665"
  log_duration = 0
}
object Endpoint NodeName {
       host = NodeName
       port = "5665"
}

object Zone ZoneName {
        endpoints = [ NodeName, "satellite-2" ]
        parent = "master"
}

object Zone "global" {
  global = true
}

object Zone "global-internal" {
  global = true
}
```

When we click on check now on node-1, service-n the check is triggered properly and send to the appropriate satellite to run, but result is received in master after a long time (if we leave it running the gap is increased with time)
This only happens in this zone, rests are processing and checks received immediately after execution.

I'm connected to the CheckResult api in satellites and in master where we see it clear: CheckResult event raise in satellites immediately but in master takes several minutes:

curl I run:
```
curl -v -k -s -u user:***** -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/events?queue=moix&types=CheckResult'  -d '{"filter":"match(\"node-1\",event.host) && match(\"service-n\",event.service)"}'
```

* CheckResult in satellite:
```
{"check_result":{"active":true,"check_source":"satellite-2","command":["python","/scripts/snmpnetstats.py","send-metrics","--protocol","tcp","--host","node-1","--snmpversion","2c","--snmpcommunity","********"],"execution_end":1524831677.7454760075,"execution_start":1524831677.6967289448,"exit_status":0.0,"output":"OK ","performance_data":["tcp_failed_attempts=169550","tcp_segments_sent=393768167","tcp_active_opens=2945018","tcp_invalid_segment_received=1","tcp_current_established_connections=109","tcp_segments_received=776748427","tcp_passive_opens=1800366","tcp_resets_sent=5586346","tcp_resets_of_established_connections=189901","tcp_segments_retransmitted=37131"],"schedule_end":1524831677.7455570698,"schedule_start":1524831639.325327158,"state":0.0,"type":"CheckResult","vars_after":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0},"vars_before":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0}},"host":"node-1","service":"net_stats","timestamp":1524831677.7456600666,"type":"CheckResult"}
```
timestamp: Fri Apr 27 2018 14:15:38 GMT+0200

* after a while, 12 mins in this case, in master:
```
{"check_result":{"active":true,"check_source":"satellite-2","command":["python","/scripts/snmpnetstats.py","send-metrics","--protocol","tcp","--host","node-1","--snmpversion","2c","--snmpcommunity","********"],"execution_end":1524831677.7454760075,"execution_start":1524831677.6967289448,"exit_status":0.0,"output":"OK ","performance_data":["tcp_failed_attempts=169550","tcp_segments_sent=393768167","tcp_active_opens=2945018","tcp_invalid_segment_received=1","tcp_current_established_connections=109","tcp_segments_received=776748427","tcp_passive_opens=1800366","tcp_resets_sent=5586346","tcp_resets_of_established_connections=189901","tcp_segments_retransmitted=37131"],"schedule_end":1524831677.7455570698,"schedule_start":1524831639.325327158,"state":0.0,"type":"CheckResult","vars_after":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0},"vars_before":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0}},"host":"node-1","service":"net_stats","timestamp":1524832066.5150918961,"type":"CheckResult"}
```
timestamp: Fri Apr 27 2018 14:27:46 GMT+0200

**Comment by dnsmichi** [comment]
This sounds more like a question for the community support channels. I don't see a specific bug here from the description. One thing you should try - upgrade to v2.8.4 and v2.5.3 and check whether your problems are already fixed.

**Comment by moix** [comment]
Hi, in order to mitigate the issue till we find a solution I have increased the default check_interval of some services from 1min to 2mins so the rate of checks is lower and master is able to process them.

Continuing with the investigation, I read the [Icinga performance monitoring and analysis](https://www.icinga.com/2017/06/08/icinga-performance-monitoring-and-analysis/) article thought I may be affected with the work queues scenario commented there: number of checkresults is higher than master capacity to process them.
So I have created a monitor to retrieve some stats from /v1/status as suggested, however I cannot find any remarkable metric confirming that queues are increasing.

Following screenshots are master host performance and idomysql, influx and rpm metrics.
At 13:15 I reapplied the 1min interval and left it running for 1 hour, bug appeared again and I had lot of late checks in the affected zone. 2min interval applied again at 14:45

master host behaviour:
![screenshot from 2018-04-30 15-21-40](https://user-images.githubusercontent.com/569132/39430495-862177a0-4c7d-11e8-9d7a-9f5882c2072d.png)

status of queues and workers:
![screenshot from 2018-04-30 15-16-18](https://user-images.githubusercontent.com/569132/39430528-98851604-4c7d-11e8-9164-1a771f745077.png)

Thanks /moi

**Comment by moix** [comment]
OK thanks @dnsmichi, will try to discuss my issue in the community portal. Only one question, where can I read about work queues and threading implementation in icinga2 and if it is possible to configure some settings like how many processes are spawned for checkresult processing, ...
