### ISSUE TITLE
Icinga nodes in pending mode and some executing checks still in pending

### ISSUE THREAD

**Issue by centosVenky** [Icinga/icinga2#6272]
I am using HA icinga2 with 2 master nodes, in 3 tier architecture where master--> satellite--> clients. I have recently added 5 clients, all in pending mode.Out of these 2 show check output but still show pending in WebUI, rest 3 remain in pending mode.

	Expected behavior should be all UP and OK state, if any errors then show WARNING/CRITICAL/UNKNOWN
  	All showing in pending, out of which 2 are working normal but in PENDING mode.
   

How was Icinga 2 installed (and which repository in case) and which distribution are you using:
		yum install icinga2 -y
icinga2 --version
			icinga2 - The Icinga 2 network monitoring daemon (version: v2.8.2-556-gfa615ec)
icinga2 feature list
```		
			Disabled features: checker compatlog debuglog elasticsearch gelf graphite influxdb livestatus mainlog notification opentsdb perfdata statusdata syslog
			Enabled features: api command
```
        icinga2 daemon -C
```		
		information/cli: Icinga application loader (version: v2.8.2-556-gfa615ec)
		information/cli: Loading configuration file(s).
		information/ConfigItem: Committing config item(s).
		information/ApiListener: My API identity: client_hostname
		information/ConfigItem: Instantiated 56 ServiceGroups.
		information/ConfigItem: Instantiated 4 NotificationCommands.
		information/ConfigItem: Instantiated 1 IcingaApplication.
		information/ConfigItem: Instantiated 7 HostGroups.
		information/ConfigItem: Instantiated 1 ApiListener.
		information/ConfigItem: Instantiated 4 Zones.
		information/ConfigItem: Instantiated 1 ExternalCommandListener.
		information/ConfigItem: Instantiated 2 Endpoints.
		information/ConfigItem: Instantiated 4 ApiUsers.
		information/ConfigItem: Instantiated 5 UserGroups.
		information/ConfigItem: Instantiated 215 CheckCommands.
		information/ConfigItem: Instantiated 3 TimePeriods.
		information/ConfigItem: Instantiated 5 Users.
		information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
		information/cli: Finished validating the configuration file(s).
```
        Icinga Web 2 version (screenshot from System - About)
		Icinga Web 2 Version
				2.5.1
			Git commit
			6f5d0a16f9cac2795d015323ad04024371449934
        Icinga Web 2 modules e.g. the Icinga Director (optional)
    Configuration insights:
        I have added 5 client nodes under satellite node, satellite zonename is satellitehostname, out of these 2 are working normally but have color BLUE and hence PENDING on webUI. But remaining 3 have PENDING state and check_source also blank in UI
        Your icinga2.conf file
		master, satellite, client icinga.conf:
```
			include "constants.conf"
			include "zones.conf"
			include <itl>
			include <plugins>
			include <plugins-contrib>
			include <manubulon>
			include <windows-plugins>
			include <nscp>
			include "features-enabled/*.conf"
```

        If you run multiple Icinga 2 instances, the zones.conf file (or icinga2 object list --type Endpoint and icinga2 object list --type Zone) from all affected nodes.
		 Output of "icinga2 object list --type Endpoint "
Master node:
```
Object 'clienthostname' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.d/satellitehostname/clienthostname.conf', lines 5:1-5:64
  * __name = "clienthostname"
  * host = ""
  * log_duration = 86400
  * name = "clienthostname"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 5
    * last_column = 64
    * last_line = 5
    * path = "/etc/icinga2/zones.d/satellitehostname/clienthostname.conf"
  * templates = [ "clienthostname" ]
    % = modified in '/etc/icinga2/zones.d/satellitehostname/clienthostname.conf', lines 5:1-5:64
  * type = "Endpoint"
  * zone = "satellitehostname"
```
  
Client node:
```
Object 'satellitehostname' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 9:1-9:30
  * __name = "satellitehostname"
  * host = "x.e.r.q"
    % = modified in '/etc/icinga2/zones.conf', lines 10:3-10:21
  * log_duration = 86400
  * name = "satellitehostname"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 9
    * last_column = 30
    * last_line = 9
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "satellitehostname" ]
    % = modified in '/etc/icinga2/zones.conf', lines 9:1-9:30
  * type = "Endpoint"
  * zone = ""

Object 'clienthostname' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 1:0-1:23
  * __name = "clienthostname"
  * host = ""
  * log_duration = 86400
  * name = "clienthostname"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 23
    * last_line = 1
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "clienthostname" ]
    % = modified in '/etc/icinga2/zones.conf', lines 1:0-1:23
  * type = "Endpoint"
  * zone = ""
```
    Logs
        Relevant output from your main and debug log in /var/log/icinga2. Please add step-by-step explanations with timestamps if required.
        The newest Icinga 2 crash log if relevant, located in /var/log/icinga2/crash
    Additional details
        If the check command failed, what's the output of your manual plugin tests?
        In case of debugging Icinga 2, the full back traces and outputs

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version
    2.5.1
Git commit
    6f5d0a16f9cac2795d015323ad04024371449934
Git commit date
    2018-01-22
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by MaBauMeBad** [comment]
I see 3 points.

1. if the feature List is from your Master instance, then the checker Feature ist missing
2. How did you manage the certificates for your clients ? if u didnt use the "icket" option, then you need so sign the csr (see on your master instance "icinga2 ca list"
3. Why have your client no zone assign ?

I think for a first step a Bugtracker like here is the wrong place. Sounds for me like an configuration issue und for those please use a community platform like https://monitoring-portal.org/.

**Comment by dnsmichi** [comment]
v2.8.2-556-gfa615ec is an old snapshot package, I wouldn't suggest using that. Other than that, please use the community channels for these types of questions.

**Comment by dnsmichi** [comment]
If this persists in v2.8.4 please collect the corresponding details from the issue template (icinga2 --version, zones.conf and your analysis of logs and performance).

**Comment by dnsmichi** [comment]
I've now seen that this going on already on the community channels. Let's stick there until the problem is fully analysed, no need for cross-postings all over the place.

https://monitoring-portal.org/t/icinga-working-service-checks-in-pending/2352
