### ISSUE TITLE
feature: add a option to skip recovery after acknowledgment/downtime

### ISSUE THREAD

**Issue by xam-stephan** [Icinga/icinga2#6273]
## Current Behavior
Please add a option to skip recovery for users after a acknowledgment/downtime.
After the acknoledgement and pass the incident to a other team the recovery maybe dont needed.
Even getting up for a confirmed problem is not helpful.

## Possible Solution
Is it posible to add a transition state for recovery (unhandelt)?
So the recovery can send to a tool (incident-management) and skip them for user-notifications

**Comment by dnsmichi** [comment]
Can you please draw a timeline with the specific actions being taken care of? I have a hard time understanding what you need.

**Comment by dnsmichi** [comment]
Could be related, but I don't understand that one either: #4662

**Comment by xam-stephan** [comment]
yes, it's the same idee like #4662 (for downtimes/flapping).

timeline:
1. icinga detects an error
	-> send alert to support-team
	-> create a ticket
2. support-team can't solve the problem themselve and
	-> acknowledge it (icinga)
	-> hands it over to another team
... some hours later ...
3. the other team solved the problem
4. icinga get a ok
	-> send the recovery to the support-team
	-> solve the ticket

icinga ist doing everithing right (as it is configured).

Is it possible that some contacts will only receive recovery messages if they are unhandled at the time of the recovery?

Maybe a Transition types "Recovery (unhandled)"?
Than users can used a other template to get just recovery-messages when they are not handled

**Comment by Al2Klimov** [comment]
Hello @xam-stephan!

Have you already tried to filter the events/states per [Notification](https://icinga.com/docs/icinga2/latest/doc/09-object-types/#notification)?

Best,
AK

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
