### ISSUE TITLE
Password hash format is not standard

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga2#6278]
I noticed some misalignment in terms of standards in password hash usage:

* `$5$` we are using is **not** compatible to `crypt(3)`, it is a PBKDF2 Implementation
* any other Crypt or similar hash can not be used. 

We should find a better way to handle this.

**Most important:** Change our default hash identifier to something like `$pbkdf2-sha256$`

See external resources:
* https://passlib.readthedocs.io/en/stable/lib/passlib.hash.pbkdf2_digest.html
* https://secure.php.net/manual/en/function.crypt.php

## Your Environment

* Version used (`icinga2 --version`): 2.8.4
* Operating System and version: RHEL 7.5

**Comment by dnsmichi** [comment]
According to what I've asked @Crunsher this is by design. I do not see a reliable way to change this at this stage, since the feature already slipped into the 2.8 release too.

**Comment by lazyfrosch** [comment]
This should be improved soonish, we should discuss this in person.

At least improve the CLI endpoints and the default hash type to be `$pbkdf2-sha256$`

I saw multiple users struggling to generate hashes... (Especially automated)

**Comment by dnsmichi** [comment]
Discuss it with @lippserd then please. 2.9 is frozen in terms of issues and resources planned in the next weeks.

Btw - code-quality as label only is for source code improvements, nothing I would add here.

**Comment by Crunsher** [comment]
Any change here would need to be backwards compatible, ie we continue to tread $5$ as pbkdf2-sha256 and if someone was to use sha256 it would just not work.

**Comment by dnsmichi** [comment]
Corresponding feature has been reverted, this one will be considered if we ever add a new one. See the linked issue, there's no pressure do it now though (we don't have time anyways).
