### ISSUE TITLE
Issue when using excludes in TimePeriod Objects

### ISSUE THREAD

**Issue by stefan7018** [Icinga/icinga2#6282]
When we use the Exclude option in  TimePeriod Objects the day after the exclude date also will be affected by not scheduling the assigned Services. 

![image](https://user-images.githubusercontent.com/14890242/39536543-34dcc4b0-4e37-11e8-86bd-5cc57a52c84b.png)

## Expected Behavior
The Excluded Timeperiod start at configured day and end when the day is over.
Or when it's more than one start at first day and end at the last configured day.

## Current Behavior
The Exclude for the TimePeriod starts at configured day as expected but ends one day after the configured exclude for this TimePeriod.

## Steps to Reproduce (for bugs)

1. create a Timeperiod Object like with an exclude for tomorrow;

```
object TimePeriod "1000_1800_business_times" {
  import "legacy-timeperiod"

  display_name = "Checks between 10:00 and 18:00 businness days 6x7  - excluded Feiertage_DE and xmas/newyear"
  ranges = {
    "monday" = "10:00-18:00"
    "tuesday" = "10:00-18:00"
    "friday" = "10:00-18:00"
    "wednesday" = "10:00-18:00"
    "thursday" = "10:00-18:00"
    "saturday" = "10:00-18:00"
  }
      excludes = ["Feiertage_DE"]
  }

  

object TimePeriod "Feiertage_DE" {
  import "legacy-timeperiod"

  display_name = "Feiertage DE"
  ranges = {
    "january 1" = "00:00-24:00"
    "december 26" = "00:00-24:00"
    "december 24" = "15:30-24:00"
    "december 25" = "00:00-24:00"
    "december 31" = "12:00-24:00"
    "may 1" = "00:00-24:00"
  }
```

2. assign to a service
3. check on the next day when exclude is over that the Service wasn't scheduled like here:
![image](https://user-images.githubusercontent.com/14890242/39536543-34dcc4b0-4e37-11e8-86bd-5cc57a52c84b.png)
or via api...

4. see that the check will be scheduled the next time two days after excluded TimePeriod

## Context
We use this to exclude local holidays in each country. To avoid false positives .

## Your Environment
* Version used (`icinga2 --version`): 2.8.2
* Operating System and version: CentOS release 6.9 
* Enabled features (`icinga2 feature list`):  api checker command ido-pgsql livestatus mainlog notification
* Icinga Web 2 version and modules (System - About): 2.5.1

**Comment by Crunsher** [comment]
Thank you for opening this issue, we have yet to investigate and reproduce this. If anybody else is having this problem, please don't hesitate to comment here.
I'd be especially interesting in this case if someone had this problem on a different scale (minutes/hours instead of days)

**Comment by dnsmichi** [comment]
@Reamer since you've contributed that feature, can you please have a look here?

**Comment by dnsmichi** [comment]
Thanks for the patch.
