### ISSUE TITLE
Icinga2 service start script does not report failures

### ISSUE THREAD

**Issue by plastikat** [Icinga/icinga2#6284]
Current Icinga2 systemd service file uses `Type=simple`. With this type systemd does not account for the process exit code when starting the service. In the result we don't know if the service has started (unless we explicitly check for service status afterwards), which is not a good thing in general and especially for an automated setup.

## Possible Solution
In contrast, with the `Type=forking` it is possible to report the exit code but an additional wrapper script would be required.

For more information please see [here](https://serverfault.com/a/833237)

## Your Environment
* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)
Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later http://gnu.org/licenses/gpl2.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
Installation root: /usr
Sysconf directory: /etc
Run directory: /run
Local state directory: /var
Package data directory: /usr/share/icinga2
State path: /var/lib/icinga2/icinga2.state
Modified attributes path: /var/lib/icinga2/modified-attributes.conf
Objects path: /var/cache/icinga2/icinga2.debug
Vars path: /var/cache/icinga2/icinga2.vars
PID path: /run/icinga2/icinga2.pid

System information:
Platform: Ubuntu
Platform version: 16.04.4 LTS (Xenial Xerus)
Kernel: Linux
Kernel version: 4.4.0-122-generic
Architecture: x86_64

Build information:
Compiler: GNU 5.3.1
Build host: 9c880c2f42f5

* Operating System and version:
Ubuntu 16.04.4 LTS

* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog elasticsearch gelf influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-pgsql mainlog notification

**Comment by Crunsher** [comment]
Would you consider opening a PR for this? All the initscripts are in [here](https://github.com/Icinga/icinga2/tree/master/etc/initsystem)

**Comment by plastikat** [comment]
Well, maybe some time in the future but not too soon - currently I am quite short on my spare time.

**Comment by htriem** [comment]
This is not relevant anymore since version 2.11. Closing.
