### ISSUE TITLE
Error while importing the Icinga 2 IDO schema in Cent OS 7 if PostgreSQL is used

### ISSUE THREAD

**Issue by lovepreetkaul** [Icinga/icinga2#6298]
## Expected Behavior
The following command should successfully execute and start importing the schema as shown in the screenshot in the documentation.  
`# psql -U icinga -d icinga < /usr/share/icinga2-ido-pgsql/schema/pgsql.sql` 

## Current Behavior
On a fresh Postgres installation, the command above fails with the following error
`psql: FATAL:  Peer authentication failed for user icinga`

## Possible Solution
The Postgres server needs to be restarted with the system-specific command. In this case
`# systemctl restart postgresql.service`

## Context
Documentation incomplete.

## Your Environment

* Version used (`icinga2 --version`): version: r2.8.4-1
* Operating System and version: Cent OS 7.4
* Enabled features (`icinga2 feature list`): checker ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About): N/A
* Config validation (`icinga2 daemon -C`): Valid
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes. N/A

**Comment by dnsmichi** [comment]
Sorry, that's documented.

> Locate your `pg_hba.conf` configuration file (Debian: `/etc/postgresql/*/main/pg_hba.conf`,
RHEL/SUSE: `/var/lib/pgsql/data/pg_hba.conf`), add the icinga user with `md5`
as authentication method and restart the postgresql server.

We're not attempting to clone the PostgreSQL documentation here though, the detailed docs with configuration are just for helping not-so-experienced users.

**Comment by lovepreetkaul** [comment]
Oh! Missed that. Apologies.
