### ISSUE TITLE
Timeout defined in NotificationCommand is ignored and uses check_timeout

### ISSUE THREAD

**Issue by jonbulica99** [Icinga/icinga2#6304]
The title is pretty self-explanatory. I'm trying to override the timeout value of a `NotificationCommand` to 5 minutes, but icinga defaults to 30s anyway for some reason.

## Expected Behavior

`NotificationCommand` should be allowed to run up to 5 minutes before getting killed.

## Current Behavior

`NotificationCommand` gets killed after 30 seconds.

## Possible Solution

Not really sure.

## Steps to Reproduce (for bugs)

1. I have the following `NotificationCommand`:
```
object NotificationCommand "otrs-notification-service" {
  command = [ SysconfDir + "/icinga2/scripts/otrs.pl" ]

  timeout = 5m

  arguments += {
    "--CheckType" = {
      required = true
      value = "$notification_checktype$"
    }
  [...]
  vars += {
    [...]
  }
}
```

2. This is the service template, which applies to all services:
```
template Notification "OTRS Service" {
    times = { begin = 0m }
    command = "otrs-notification-service"
    interval = 0s
    period = "work_periode"
    states = [ Critical, Warning ]
    types = [ Custom, Problem ]
}
```
3. Now if I let icinga run for a couple of minutes, the following appears on the debug logs:
```
[2018-05-15 09:12:05 +0200] notice/Process: Running command '/etc/icinga2/scripts/otrs.pl' '--CheckType' 'Service' '--Details' 'MEMORY WARNING - 5.51607% free ' '--Hostname' 'XXX-Eliserver3' '--Service' 'Icinga - Memory' '--Status' 'PROBLEM' '--Target' 'monitoring@foobar.net': PID 20712
[2018-05-15 09:12:35 +0200] warning/Process: Killing process group 20712 ('/etc/icinga2/scripts/otrs.pl' '--CheckType' 'Service' '--Details' 'MEMORY WARNING - 5.51607% free ' '--Hostname' 'XXX-Eliserver3' '--Service' 'Icinga - Memory' '--Status' 'PROBLEM' '--Target' 'monitoring@foobar.net') after timeout of 30 seconds
[2018-05-15 09:12:35 +0200] warning/PluginNotificationTask: Notification command for object 'XXX-Eliserver3!Icinga - Memory' (PID: 20712, arguments: '/etc/icinga2/scripts/otrs.pl' '--CheckType' 'Service' '--Details' 'MEMORY WARNING - 5.51607% free ' '--Hostname' 'XXX-Eliserver3' '--Service' 'Icinga - Memory' '--Status' 'PROBLEM' '--Target' 'monitoring@foobar.net') terminated with exit code 128, output: <Timeout exceeded.><Terminated by signal 9 (Killed).>
```
"*Killing process group 20712 [...] after timeout of 30 seconds*" leads me to this conclusion.

## Context

This is supposed to create a ticket in out ticket system, and then automatically acknowledge the issue in icinga. Given enough time, both of the these happen, but most of the time the acknowledgment doesn't go through because the script gets terminated. The former however happens almost always.

## Your Environment

* Version used (`icinga2 --version`): r2.8.4-1
* Operating System and version: Debian 8
* Enabled features (`icinga2 feature list`): api checker command debuglog ido-mysql influxdb mainlog notification perfdata
* Icinga Web 2 version and modules (System - About): irrelevant
* Config validation (`icinga2 daemon -C`): no problems here either

**Comment by dnsmichi** [comment]
30 seconds must be a user-defined setting, the internal (and documented) default are 60s. Verify the NotificationCommand object via `icinga2 object list --type NotificationCommand` and ensure that this notification object really uses the corresponding command, and not something else which is accidentally set to 30s.

**Comment by jonbulica99** [comment]
Thanks for the reply @dnsmichi. Here's the output from that command:
```
Object 'otrs-notification-service' of type 'NotificationCommand':
  % declared in '/etc/icinga2/zones.d/global-templates/commands.conf', lines 47:1-47:54
  * __name = "otrs-notification-service"
  * arguments
    % = modified in '/etc/icinga2/zones.d/global-templates/commands.conf', lines 52:3-77:3
    * --CheckType
      * required = true
      * value = "$notification_checktype$"
    * --Details
      * required = true
      * value = "$notification_serviceoutput$"
    * --Hostname
      * required = true
      * value = "$notification_hostdisplayname$"
    * --Service
      * required = true
      * value = "$notification_servicename$"
    * --Status
      * required = true
      * value = "$notification_type$"
    * --Target
      * required = true
      * value = "$notification_from$"
  * command = [ "/etc/icinga2/scripts/otrs.pl" ]
    % = modified in '/etc/icinga2/zones.d/global-templates/commands.conf', lines 48:3-48:55
  * env = null
  * execute
    % = modified in 'methods-itl.conf', lines 48:3-48:40
    * arguments = [ "notification", "user", "cr", "itype", "author", "comment", "resolvedMacros", "useResolvedMacros" ]
    * deprecated = false
    * name = "Internal#PluginNotification"
    * side_effect_free = false
    * type = "Function"
  * name = "otrs-notification-service"
  * package = "_etc"
  * source_location
    * first_column = 1
    * first_line = 47
    * last_column = 54
    * last_line = 47
    * path = "/etc/icinga2/zones.d/global-templates/commands.conf"
  * templates = [ "otrs-notification-service", "plugin-notification-command" ]
    % = modified in '/etc/icinga2/zones.d/global-templates/commands.conf', lines 47:1-47:54
    % = modified in 'methods-itl.conf', lines 47:2-47:83
  * timeout = 300
    % = modified in '/etc/icinga2/zones.d/global-templates/commands.conf', lines 50:3-50:14
  * type = "NotificationCommand"
  * vars
    % = modified in '/etc/icinga2/zones.d/global-templates/commands.conf', lines 79:3-94:3
    * notification_address = "$address$"
    * notification_address6 = "$address6$"
    * notification_author = "$notification.author$"
    * notification_checktype = "Service"
    * notification_comment = "$notification.comment$"
    * notification_date = "$icinga.long_date_time$"
    * notification_hostdisplayname = "$host.display_name$"
    * notification_hostname = "$host.name$"
    * notification_servicedisplayname = "$service.display_name$"
    * notification_servicename = "$service.name$"
    * notification_serviceoutput = "$service.output$"
    * notification_servicestate = "$service.state$"
    * notification_type = "$notification.type$"
    * notification_useremail = "$user.email$"
  * zone = "global-templates"
```
According to this, the timeout is correctly set to `300` (5m). But that just makes it even weirder. Any idea what might be interfering here?

**Comment by dnsmichi** [comment]
Systemd or any other global setting maybe?

**Comment by jonbulica99** [comment]
How would systemd affect the ability of a daemon to run a script for a specified amount of time?

**Comment by dnsmichi** [comment]
I don't know, I am guessing between a short amount of time when Icinga 2 is compiling :) I have never seen such a problem myself, so I doubt this really is a bug in Icinga.

**Comment by jonbulica99** [comment]
It is happening constantly though. Is there any way to monitor what's going on with child processes spawned by the icinga daemon?

**Comment by dnsmichi** [comment]
Hmmm. Another guess ... does your host/service for this notification object have the `check_timeout` variable set?

**Comment by jonbulica99** [comment]
Yes, the host has a `check_timeout` of 30s.

**Comment by dnsmichi** [comment]
It is a bug in pluginutility.cpp then where the notification command actually takes the check_timeout from the checkable object.
