### ISSUE TITLE
Check_cluster and sudo rights

### ISSUE THREAD

**Issue by r4a5a88** [Icinga/icinga2#6310]
Hello 
I have a icinga2web Server and two remote host it is monitoring all with debian. One of them has glusterfs-server installed.

## Expected Behavior
An icinga2 service with the check_cluster script form the icinga2 homepage monitores the server.

## Current Behavior
I get this wonderful message

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified

## Steps to Reproduce (for bugs)

1. copy check_cluster script into the /usr/lib/nagios/plugins folder
2. add a service for this server with thiis command:  command = [ "/usr/bin/sudo", PluginDir + "/check_cluster -s 1 -c 2 -d 0,0,0"
3. add sudo rights
Defaults:nagios !requiretty
nagios ALL=(ALL:ALL) NOPASSWD: /usr/sbin/gluster
nagios ALL=(ALL:ALL) NOPASSWD: /usr/lib/nagios/plugins/check_cluster
nagios ALL=(ALL:ALL) NOPASSWD: /usr/lib/nagios/plugins/check_cluster ""

## Context
I checked the commands locally on the server and it gave me the feedback I wanted but on the icinga2 website it gives the error

this is what the /var/log/auth.log showed me
sudo: pam_unix(sudo:auth): auth could not identify password for [nagios]
sudo:  nagios : command not allowed ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/nagios/plugins/check_cluster -s 1 -c 2 -d 0,0,0

## Your Environment
* Version used : r2.6.0-1
* Operating System and version: debian stretch
* Enabled features : api checker command mainlog

**Comment by dnsmichi** [comment]
GitHub is our bug tracker. This one sounds like a configuration problem with sudo, nothing related to an application problem itself. Please proceed on the community support channels.
