### ISSUE TITLE
Problem with clients using the same certificate

### ISSUE THREAD

**Issue by toxicvengeance** [Icinga/icinga2#6314]
## Expected Behavior

The icinga2 master should ignore data sent from another client using the same certificate in favour of a client that already exists or at least should complain in icinga2.log that there are two clients using the same certificate.

## Current Behavior

Icinga2 accepts check results from the client that recently connected and ignores data from a client that has already been there before.

## Possible Solution

Ignore a new client that presents itself with the same certificate in favour of an already existing client. The next step would be to reconfigure the cloned vm with a new certificate but it would be nice to be notified that there are two clients using the same certificate in the meantime.

## Steps to Reproduce (for bugs)

1. Clone an existing server
2. Open up icingaweb2
3. You can see the load,disk results etc. from the new vm instead of the old

## Context

From time to time we have to restore a vm from backup to extract data etc. We noticed that after the restored vm boots up Icinga seems to ignore the data sent by the original server as the restored vm has the same certificate. If a colleague forgets to run icinga2 node wizard on the cloned vm no one notices that the data displayed in icingaweb2 for the original vm is actually from the cloned vm.

## Your Environment

* Version used (`icinga2 --version`): r2.8.4-1
* Operating System and version: 16.04.4 LTS (Xenial Xerus)
* Enabled features (`icinga2 feature list`): api checker command graphite ido-mysql influxdb livestatus mainlog notification
* Icinga Web 2 version and modules (System - About): 2.5.3
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
That's more of a user problem here, Icinga 2 doesn't store connection information in combination with used certificates. If you clone the certificates to a different node, you're actively copying the trust relationship as well. I would install safety mechanisms on your end to not let this happen.

Your network would also have two IPs with the same FQDN then, which harms operations on a different level. If the connecting FQDN is different to what the certificates CN provides, Icinga will terminate the TLS handshake already.

I don't think that this can be dealt with on an application level, you really need to have this managed in your deployment and backup/restore procedure workflows.
