### ISSUE TITLE
Remove nscp-local-cpu from ITL

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icinga2#6315]
Remove nscp-local-cpu from ITL becuase it will never work like expected.
See https://github.com/mickem/nscp/issues/489

**Comment by mcktr** [comment]
Before removing `nscp-local-cpu` we should add a deprecation warning to it, then we can remove it in the following version.

**Comment by dnsmichi** [comment]
I wouldn't remove it, since the real problem lies within the check plugin. Removing it will break existing installations, especially on the client side. Users should be made aware of using the REST API plugin, or a different method, and that should be about it.

**Comment by Crunsher** [comment]
Aye, a note about this in the documentation and the template should suffice

**Comment by dnsmichi** [comment]
Documentation is sufficient in my opinion. Since this issue is about something else, I'm not explicitly assigning it to the next milestone.
