### ISSUE TITLE
SNMP Performance data warning and critical not shown

### ISSUE THREAD

**Issue by duhow** [Icinga/icinga2#6323]
I'm doing some checks to the cartridge levels of the printer by using the `snmp` command, I get the data without problem (OK, WARNING, CRITICAL), but **Performance data** levels Warning and Critical displays as 0.

I'm using the `:` filter, as the cartridge level does not increase, but decrease, and the alert should fire when reaching a low level (`<26` and `<11`)

![image](https://user-images.githubusercontent.com/1145001/40307430-cfe84748-5d02-11e8-9593-8498d7ce45b0.png)

```
object Host "HP-Laserjet" {
        import "generic-host"

        address = "192.168.1.240"

        vars.snmp_community = "public"
        vars.snmp_version = "2c"

        vars.cartridges["black"] = {
                cartridge_id = 1
        }
        vars.cartridges["cyan"] = {
                cartridge_id = 2
        }
        vars.cartridges["magenta"] = {
                cartridge_id = 3
        }
        vars.cartridges["yellow"] = {
                cartridge_id = 4
        }
        vars.cartridges["tambor"] = {
                cartridge_id = 5
        }
}

apply Service "cartridge " for (cartridge => config in host.vars.cartridges) {
        import "generic-service"

        check_command = "snmp"
        check_interval = 15m
        retry_interval = 2m
        max_check_attempts = 3

        vars.snmp_warn = "26:"
        vars.snmp_crit = "11:"
        vars.snmp_oid = "1.3.6.1.2.1.43.11.1.1.9.1." + config.cartridge_id
        vars.snmp_label = cartridge

        assign where (host.vars.cartridges && host.vars.snmp_community)
}
```

Running the command:
```
./check_snmp -H 192.168.1.240 -o 1.3.6.1.2.1.43.11.1.1.9.1.3 -w 26: -c 11: -l magenta
SNMP OK - magenta 100 | magenta=100;26:;11:
```

## Your Environment

* Version used (`icinga2 --version`): **r2.6.0-1**
* Operating System and version: **Debian 9.3 Linux 4.13.13-2-pve**
* Enabled features (`icinga2 feature list`):
```
Disabled features: api compatlog debuglog gelf graphite livestatus opentsdb perfdata statusdata syslog
Enabled features: checker command ido-mysql influxdb mainlog notification
```

**Comment by mcktr** [comment]
Currently we don't support threshold ranges for the performance data. Have a look into #909 for further details.

You could create a wrapper script for check_snmp to format the performance data properly.

**Comment by dnsmichi** [comment]
With the current plugin API, there's no chance we implement threshold range parsing. Use the mentioned workaround.
