### ISSUE TITLE
Monitoring Health: Backend icinga is not running  and other errors

### ISSUE THREAD

**Issue by Kasvan** [Icinga/icinga2#6332]
Hello, I am newbie in using Icinga2 of recent. But am facing a few errors as it will be explained in details as follows;
From the System Tab, The monitoring health notifies me that My Icinga Backend is not actually running and yet when I run service icinga2 status, everything seems fine also when I get warnings when I run icinga2 --version

## Steps to Reproduce (for bugs)

1. When I open the monitoring health tab from the Icinga2 web interface, The monitoring health reports that Backend icinga is not running  and when I tried to check the service status of icinga2, I actually found out that it was running. screenshot attached here  
![icinga22](https://user-images.githubusercontent.com/18504083/40474790-90a4b56c-5f05-11e8-9a1e-21cebd6ab52c.png)

2. When I run icinga2 --version, I get 2 warning as attached in the screenshot. I tried searching the solutions from the previous similar issues raised, I failed to get the solution. I also did an upgrade of my Linux host box, but no change
![screenshot from 2018-05-24 03-44-56](https://user-images.githubusercontent.com/18504083/40474534-e98aefee-5f04-11e8-927c-ef626716c4c3.png)

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version: 17.04 (Zesty Zapus)
* Enabled features (`icinga2 feature list`): pi checker command ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
Please continue on the community channels such as https://monitoring-portal.org (short hint: web says 2.4.1, version says 2.8.x - check the upgrading docs).
