### ISSUE TITLE
can I restrict api permissions?

### ISSUE THREAD

**Issue by benkeil** [Icinga/icinga2#6340]
In the documentation is written I can define multiple permissions for an api user. The easiest way is to define `*`. But I want to create an user who can do everything, except everything with apiUser objects.

https://www.icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#icinga2-api-permissions

Is there a way to say "everything except of apiUsers"? Something like:

    permissions = [
      {
        permission = "*"
      },
      {
        permission = "objects/*/ApiUser"
        restrict = true
      }
    ]

**Comment by dnsmichi** [comment]
I would appreciate such questions being asked on the community support channels instead.

Something like this works with specifying an advanced filter as function which filters away the specific scope for the `apiuser` object.

```
object ApiUser "no-api-user" {
  password = "foo"
  permissions = [
    {
      permission = "*"
    },
    {
      permission = "objects/*/ApiUser",
      filter = {{
        //if (apiuser.name != "") {
        if (apiuser.name != "no-api-user") {
          return false
        }
        return true
      }}
    }
  ]
}
```
