### ISSUE TITLE
Icinga 2 - Permission denied issue.

### ISSUE THREAD

**Issue by praveendcis** [Icinga/icinga2#6341]
I have configured a new Icinga satellite node and tried monitoring few services on a server. When monitoring the services I am getting the following error. Please help me to sort out this.
"**Remote command execution failed: Permission denied, please try again.**"

**Comment by dnsmichi** [comment]
The issue description lacks everything one needs to understand and reproduce the issue. Please fill in the issue template.

https://raw.githubusercontent.com/Icinga/icinga2/master/.github/ISSUE_TEMPLATE.md
