### ISSUE TITLE
(Built in) monitoring plugins should use [$status] for more eye-catching display

### ISSUE THREAD

**Issue by ulyszk** [Icinga/icinga2#6342]
I found that using [OK], [CRITICAL] form of status text (note brace) can create more eye-catching, color coded plugin output. I think this provides much better visual, where the one can find the problematic values faster. IMHO Icinga should provide such plugins, if possible.

**Comment by dnsmichi** [comment]
There are no built-in monitoring plugins ... not sure what you are talking about here. Can you provide a concrete example?

**Comment by ulyszk** [comment]
This type of plugin output looks very useful: ![wp_out](https://user-images.githubusercontent.com/39549260/40623964-1dec604e-62aa-11e8-8125-e9f36baa77c6.PNG)
Example is not perfect, it is much better when you have multiple mesaurement in plugin output like disks.

**Comment by mcktr** [comment]
Such a change must be made in the [monitoring-plugins](https://www.monitoring-plugins.org/), which Icinga 2 uses. We don't ship check plugins (except for our Windows Agent).
