### ISSUE TITLE
Persistent comments on Acknowledgments do not 'persist' when using API backend

### ISSUE THREAD

**Issue by mdetrano** [Icinga/icinga2#6345]
Acknowledgments submitted with "persistent" option for the comment see the comment disappear if using the API to create the acknowledgment and then the acknowledgment is removed.  The comment is preserved if the acknowledgment is created using the external command pipe.  This is possibly a regression of a bug that was marked as fixed in v. 2.7

## Expected Behavior

The comment submitted with an Acknowledgment should be preserved as a comment for the object after removing the acknowledgment is the persistent option was specified.  This is the behaviour seen if the acknowledgment is submitted via the external command pipe instead of using the icinga2 API.

## Current Behavior

On removing an acknowledgment that had been created with the API, the comment disappears as well.

## Steps to Reproduce (for bugs)

1. Setup Icinga Web2's monitoring module to use the API as command transport backend.
2. Acknowledge a problem state, checking the "persistent" box.
3. Verify the acknowledgment and comment.
4. Use interface to remove the Acknowledgment
5. The comment does not get preserved ... it is not present in the "comments" portion of the web interface for the object's details.

## Context

Consulting clients want the comments maintained as a sort of history to see what happened when a service had a problem and who took steps to resolve it.

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

icinga v 2.8.4, rpm's installed from the Icinga project repository on Centos 7
icingaweb2 v 2.5.3 , likewise using rpm's from the same repo.

**Comment by mdetrano** [comment]
You're right...sorry, its an Icingaweb2 issue.  The Api is fine.

**Comment by dnsmichi** [comment]
No worries :)
