### ISSUE TITLE
Icinga2 2.8.2 crashes with segfault in libstdc++.so.6.0.19

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga2#6351]
## Current Behavior
Sometimes our Icinga2 instances are crashing with segmentation faults.

Syslog:

```
Jun  5 15:36:41 systemname kernel: [4074847.135737] icinga2[45350]: segfault at 557fc8475c50 ip 00002abf909843b7 sp 00002abf954b1d70 error 4 in libstdc++.so.6.0.19[2abf90927000+e9000]
Jun  5 15:36:41 systemname kernel: icinga2[45350]: segfault at 557fc8475c50 ip 00002abf909843b7 sp 00002abf954b1d70 error 4 in libstdc++.so.6.0.19[2abf90927000+e9000]
Jun  5 15:36:41 systemname abrt-hook-ccpp: Process 45346 (icinga2) of user 992 killed by SIGSEGV - dumping core
Jun  5 15:36:44 systemname abrt-hook-ccpp: Failed to create core_backtrace: waitpid failed: No child processes
Jun  5 15:36:44 systemname systemd: icinga2.service: main process exited, code=killed, status=11/SEGV
Jun  5 15:36:44 systemname perl: *** Error in `perl': double free or corruption (!prev): 0x0000000003f264c0 ***
Jun  5 15:36:44 systemname perl: *** Error in `perl': double free or corruption (!prev): 0x00000000028fdd30 ***
Jun  5 15:36:44 systemname perl: *** Error in `perl': corrupted double-linked list: 0x0000000002c73360 ***
Jun  5 15:36:44 systemname abrt-hook-ccpp: Process 65012 (perl) of user 992 killed by SIGABRT - dumping core
Jun  5 15:36:44 systemname perl: *** Error in `perl': double free or corruption (!prev): 0x0000000003ecb0f0 ***
Jun  5 15:36:45 systemname abrt-hook-ccpp: Process 60758 (perl) of user 992 killed by SIGABRT - ignoring (repeated crash)
Jun  5 15:36:45 systemname abrt-hook-ccpp: Process 63247 (perl) of user 992 killed by SIGABRT - ignoring (repeated crash)
Jun  5 15:36:45 systemname abrt-hook-ccpp: Process 65905 (perl) of user 992 killed by SIGABRT - ignoring (repeated crash)
Jun  5 15:36:45 systemname systemd: Unit icinga2.service entered failed state.
Jun  5 15:36:45 systemname systemd: icinga2.service failed.
```

## Steps to Reproduce (for bugs)
As of now i can not reproduce the issure.

## Context
Icinga2 crashes sometimes.

## Your Environment
* Version used (`icinga2 --version`):

icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.21.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Operating System and version:

Red Hat Enterprise Linux Server release 7.4 (Maipo)

* Enabled features (`icinga2 feature list`):

Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus mainlog notification opentsdb perfdata statusdata
Enabled features: api checker syslog

* Icinga Web 2 version and modules (System - About):

Icinga Web 2 Version
    2.5.1
Git Commit
    6f5d0a16f9cac2795d015323ad04024371449934
Git Commit Datum
    2018-01-22

Geladene Module
Name 	Version
businessprocess 	2.1.0
monitoring 	2.5.1
pnp 	1.1.0 

* Config validation (`icinga2 daemon -C`):

information/cli: Icinga application loader (version: r2.8.2-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: systemname
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 1 SyslogLogger.
information/ConfigItem: Instantiated 5 Zones.
information/ConfigItem: Instantiated 4 Endpoints.
information/ConfigItem: Instantiated 243 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 9527 Hosts.
information/ConfigItem: Instantiated 20 HostGroups.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 25188 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lazyfrosch** [comment]
Since you have abrt running, is there any core dump or backtrace?

We try to put them in `/var/log/icinga2/crash` - when coredumps are enabled.

Also see:
* https://www.icinga.com/docs/icinga2/latest/doc/15-troubleshooting/
* https://www.icinga.com/docs/icinga2/latest/doc/21-development/#debug-requirements
* https://www.icinga.com/docs/icinga2/latest/doc/21-development/#core-dump

**Comment by lazyfrosch** [comment]
Also have you tried running 2.8.4?

https://github.com/Icinga/icinga2/blob/master/CHANGELOG.md#284-2018-04-25

**Comment by dnsmichi** [comment]
Never seen such an error before. This seems to involve Perl somehow, can you extract a list of plugins written in Perl running at this interval?

**Comment by lazyfrosch** [comment]
@dnsmichi looks like a different crash to me, maybe due to systemd cleanup on stop (check the timestamps)

**Comment by K0nne** [comment]
@lazyfrosch there was no core dump written.

/var/spool/abrt/last-ccpp, which was last modified at crash date, contains only "/usr/bin/perl".

@dnsmichi check_vmware_esx was running at this time. I also think this was a different crash.

For now i will look into the troubleshooting docs.

**Comment by lazyfrosch** [comment]
Please try to get a backtrace, and install the appropriate debug packages, also for libstdc++

Without it we have no way of finding the issue.

**Comment by dnsmichi** [comment]
Please test this with 2.9.0.

**Comment by K0nne** [comment]
Yesterday we updated to 2.9.1. So far everything looks fine, but it will look for it.
The crashes with 2.8.2 occured every 2 weeks or so.
