### ISSUE TITLE
GelfWriter and invalid perfdata causes icinga2 process to die

### ISSUE THREAD

**Issue by buschsalat** [Icinga/icinga2#6352]
As seen with icinga 2.7.2 and 2.8.2: as soon as one of your checks produces invalid perfdata and you have activated GelfWriter feature, processing of said perfdata causes icinga2 to die silently. (No mention of invalid perfdata in logs as expected from https://github.com/Icinga/icinga2/blob/v2.8.2/lib/perfdata/gelfwriter.cpp#L255)

## Expected Behavior
Invalid perfdata is processed, logged and discarded.

## Current Behavior
Invalid perfdata causes icinga2 to die silently.

## Possible Solution
Unknown. See issues #6191 and #6192 

## Steps to Reproduce (for bugs)
Create script with the following content
```
#!/bin/bash

echo "OK: Check successful! | 'invalidPerfdata='"

exit 0
```
Be aware of missing value of perfdata label "invalidPerfdata". This causes the perfdata to be considered as invalid.
Then create a CheckCommand using that script. After that, create a Service object associated with the just created CheckCommand, reload your icinga2 config and manually trigger a check or wait for the scheduled check.

## Context
A faulty check produced perfdata without values which caused icinga2 to die as soon as GelfWriter was activated. GelfWriter was activated in an attempt to migrate away from Graphite-Output.
Graphite feature successfully logs and discards invalid perfdata.

### Icinga 2 Diagnostics
Version: 0.0
Run on {hostname} at Fr 1. Jun 15:49:53 CEST 2018
Running as root

#### OS

OS Version: CentOS release 6.9 (Final)
Hypervisor: Running virtually on a VMware hypervisor
CPU cores: 12
RAM: 11G

##### Top output ###

top - 15:49:54 up 23 days,  1:58,  1 user,  load average: 2.16, 18.10, 72.94
Tasks: 264 total,   1 running, 263 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.8%us,  5.6%sy, 18.3%ni, 75.2%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  12328680k total,  1683264k used, 10645416k free,    19332k buffers
Swap:   524284k total,   306312k used,   217972k free,   838752k cached

SELinux: Permissive
Firewall: inactive

#### Icinga 2

Features:
Disabled features: compatlog debuglog elasticsearch graphite ido-pgsql influxdb livestatus notification opentsdb perfdata statusdata syslog
Enabled features: api checker command gelf ido-mysql mainlog

Check intervals:
   1908   * check_interval = 3600, Host
     89   * check_interval = 300, Host
     19   * check_interval = 900, Host
  49831   * check_interval = 900, Service
   8901   * check_interval = 3600, Service
   1611   * check_interval = 600, Service
     50   * check_interval = 86400, Service
     21   * check_interval = 60, Service
     20   * check_interval = 300, Service
     12   * check_interval = 43200, Service
      2   * check_interval = 5, Service
      2   * check_interval = 120, Service
      2   * check_interval = 10800, Service
      1   * check_interval = 1800, Service

Used commands (numbers are relative to each other, not showing configured objects):
grep: /var/log/icinga2/debug.log: Datei oder Verzeichnis nicht gefunden

information/cli: Icinga application loader (version: r2.8.2-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: {hostname}
information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 1416, rate: 117.85/s (7071/min 7071/5min 7071/15min); empty in 17683 days, 13 hours, 50 minutes and 32 seconds
information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 0, rate:  0/s (0/min 0/5min 0/15min);
information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 764, rate: 128.717/s (7723/min 7723/5min 7723/15min); empty in infinite time, your task handler isn't able to keep up
information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 117, rate: 139.5/s (8370/min 8370/5min 8370/15min);
information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 10613, rate: 1959/s (117540/min 117540/5min 117540/15min);
information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 25000, rate: 3526.3/s (211578/min 211578/5min 211578/15min); empty in 17 seconds
information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 7754, rate: 3892.92/s (233575/min 240065/5min 240065/15min);
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 5 Zones.
information/ConfigItem: Instantiated 4 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 4 ApiUsers.
information/ConfigItem: Instantiated 1357 Notifications.
information/ConfigItem: Instantiated 3 NotificationCommands.
information/ConfigItem: Instantiated 341 CheckCommands.
information/ConfigItem: Instantiated 7 Downtimes.
information/ConfigItem: Instantiated 107 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2 EventCommands.
information/ConfigItem: Instantiated 2016 Hosts.
information/ConfigItem: Instantiated 33 Comments.
information/ConfigItem: Instantiated 28 UserGroups.
information/ConfigItem: Instantiated 61 Users.
information/ConfigItem: Instantiated 9 TimePeriods.
information/ConfigItem: Instantiated 60453 Services.
information/ConfigItem: Instantiated 8 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/<PREFIX>/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by dnsmichi** [comment]
That was already fixed a while ago while investigating on the Elasticsearch feature with the same effect. #6193 is merged and targets 2.9.0. Closing here.
