### ISSUE TITLE
Analyse socket IO handling with HTTP/JSON-RPC

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#6361]
- DataAvailableHandler() and stream->IsEOF() might cause problems with IO threads
- open connections and requests are not terminated and leak memory
- limit parallel requests in a dynamic thread pool (as an idea at last)

More tasks soon.

**Comment by Al2Klimov** [comment]
Note: It seems the timer responsible for cleaning up dead connections stops doing its work...

**Comment by Al2Klimov** [comment]
The timer fires every 5s after previously finished. It checks all clients' liveness and disconnects them eventually – one by one. If closing one of them takes very long (or forever), the next timer fire is delayed respectively. (And the Icinga shutdown as well...)

**Comment by Al2Klimov** [comment]
`SocketEventEngine#WakeUpThread()` seems to block TLS stream closing by looping endlessly. On the first sight because `SocketEventEnginePoll#ThreadProc()` doesn't wake up...

**Comment by Al2Klimov** [comment]
Of course `SocketEventEnginePoll#ThreadProc()` is busy... with `TlsStream#OnEvent()` which keeps calling `Stream#SignalDataAvailable()` which seems not to invoke `HttpServerConnection#DataAvailableHandler()` – there is either no handler at all or a dummy handler.

At the first sight the subject TLS stream seems to have hit "No data received on new API connection." in `ApiListener#NewClientHandlerInternal()` which is clearly followed by a return which clearly destroys the TLS stream. This implies unregistration from any socket I/O thread which should effectively break the loop in `TlsStream#OnEvent()`. But then this would not loop as it does...

CC @Crunsher @gunnarbeutner

**Comment by Al2Klimov** [comment]
IMAO we should re-write all these $%&/( HTTP/JSONRPC black magic with thousands of threads and even more race conditions to a few threads each w/ an autonomous event loop (e.g. boost ASIO).
This would save us a lot of debugging time (= money) and memory (threads have constant stack size) in the future.

CC @lippserd

PS: Yes, **in the future**, I'd not include this one in v2.9.0.

**Comment by Al2Klimov** [comment]
@lippserd Just fixed one bug in the above commit. Now bad/dead sockets get definitely closed. This should fix

1. forever hanging shutdowns while looping in OnEvent
2. socket/memory leaks
3. unresponsive API due to blocked socket I/O threads

The client app still reports TLS handshake failures, but IMAO due to Icinga 2 has closed them too early due to timeouts.

I'll discuss w/ you (offline) about possible testers/early adopters...

**Comment by lippserd** [comment]
Thanks guys for the good work 👍

**Comment by Al2Klimov** [comment]
Yes, I am, but I definitively had not completed this w/o @Crunsher and @gunnarbeutner!

**Comment by dnsmichi** [comment]
Ok, I'll bring some more keksis the next time I'm in Austria :-)

One thing to mention - if there are too many requests, the connection times out. 

```
Cam't create host gleaming.gerbil.arab: Connection ended before receiving response [0]
```

That one can be dealt probably with only rate limiting and sending back a proper response status.

**Comment by dnsmichi** [comment]
# Review

## Setup

A Vagrant VM with Debian 9, local Icinga 2 debug build from source.

```
apt-get -y install gdb vim git cmake make ccache build-essential libssl-dev libboost-all-dev bison flex default-libmysqlclient-dev libpq-dev libyajl-dev libedit-dev

git clone https://github.com/icinga/icinga2.git
cd icinga2
mkdir debug release
cd debug
cmake .. -DCMAKE_BUILD_TYPE=Debug -DICINGA2_UNITY_BUILD=OFF -DCMAKE_INSTALL_PREFIX=/usr/local/icinga2 -DICINGA2_PLUGINDIR=/usr/local/sbin
cd ..
make -j2 install -C debug
groupadd icinga
groupadd icingacmd
useradd -c "icinga" -s /sbin/nologin -G icingacmd -g icinga icinga
chown -R icinga:icinga /usr/local/icinga2/var/

cd /usr/local/icinga2/
./lib/icinga2/prepare-dirs etc/sysconfig/icinga2
./sbin/icinga2 api setup
vim etc/icinga2/conf.d/api-users.conf

password = "icinga"
```

# Tests

### Terminal 1: Threads

```
watch -n 1 'for pid in $(pidof icinga2); do ps -T -p $pid | grep -F icinga2; done | wc -l'
```

### Terminal 2: Run with GDB

```
/usr/local/icinga2/sbin/icinga2 --version
/usr/local/icinga2/lib/icinga2/prepare-dirs
gdb --args /usr/local/icinga2/lib/icinga2/sbin/icinga2 daemon
(gdb) r
```

### Terminal 3: Create lots of hosts

```
cd /vagrant/icinga2-api-stampede
php -d memory_limit=512M bin/stampede.php  --hosts 1000 --verbose
```

## Result

### Start

![icinga2_api_thread_io_tests_01_start](https://user-images.githubusercontent.com/382049/41467496-0d5318d0-70a7-11e8-8484-edd4ea01fd3c.png)

### Run

![icinga2_api_thread_io_tests_02_running](https://user-images.githubusercontent.com/382049/41467498-0d7300b4-70a7-11e8-8454-2eba357fc150.png)

### Fire

![icinga2_api_thread_io_tests_03_fire](https://user-images.githubusercontent.com/382049/41467499-0d91119e-70a7-11e8-8526-98f7c2414c69.png)

### End

![icinga2_api_thread_io_tests_04_end](https://user-images.githubusercontent.com/382049/41467500-0db13d98-70a7-11e8-873f-9b6d5d669955.png)

### Second Run

![icinga2_api_thread_io_tests_05_second_run](https://user-images.githubusercontent.com/382049/41467501-0dd5c780-70a7-11e8-9d57-b777375ab9f9.png)
