### ISSUE TITLE
Notification interval should respect notification period

### ISSUE THREAD

**Issue by cycloon** [Icinga/icinga2#6363]
The notification interval should start in respect of the notification period and not in respect to the time the service is going down.

## Expected Behavior
If a service beeing down at the start of the notification period, then an immediate notification should be issued. 

## Current Behavior
Currently if I have a notification with `interval = 2h` and period set to start at 7 o'clock. A service that went down at 6 o'clock triggers the first notification at 8 o'clock.

## Possible Solution
The notification timer of the interval should start with the start of the notification period and not with the start of the failed check or hard state.

## Context
I have seen many questions and already some issues beeing raised about this problem. People expect the notification interval to be absolute and not respect the interval beeing started some time in the night.

**Comment by dnsmichi** [comment]
Can you please provide the following additional points from the issue template?

- steps to reproduce
- logs and configuration snippets
- versions involved

**Comment by dnsmichi** [comment]
```
..........6pm.................7pm...............8pm
          outside             starts              reminder notification, the second notification
```

The first notification is suppressed by the notification period. I'm not quite sure if we should change this behaviour, as this also changes the interval offset then.

**Comment by htriem** [comment]
Will be taken into account for the new notification manager project.
