### ISSUE TITLE
lib/base/workqueue.cpp:212: assertion failed: !m_Name.IsEmpty()

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#6364]
## Expected Behavior

No assertion errors at all.

## Current Behavior

`WorkQueue#WorkQueue()` never sets `WorkQueue#m_Name`, but unconditionally schedules `WorkQueue#StatusTimerHandler()`. During load peaks (IMO mostly while debugging) That timer may fire before someone calls `WorkQueue#SetName()` and... ciao icingad.

## Possible Solution

`WorkQueue#WorkQueue()` always sets `WorkQueue#m_Name`. (required constructor parameter)

## Steps to Reproduce (for bugs)

Overload the API. The much load the better.

## Context

#6361

## Your Environment

Latest master

**Comment by Al2Klimov** [comment]
@Crunsher Do you agree with my possible solution?

**Comment by Crunsher** [comment]
It makes sense, aye. Either as a new optional parameter (default random?) or we'll have to change the calls whereever they happen (API + Most of the *writer features)

**Comment by dnsmichi** [comment]
Right on the implementation differs in features with using the constructor (preferred way) and OnConfigLoaded() (which may happen after all config objects are loaded, too late for the timer started in the WQ constructor). Nice catch in finding, I sometimes have seen this as well.

The assert only happens in debug builds, release builds won't crash but log an empty string.

**Comment by dnsmichi** [comment]
Ok, forget about the constructor idea, at this point we don't have the object name anyways. We'll need to ensure that WQ timers kick off _after_ the configuration object has been loaded. Currently they are initialized during object construction already.
