### ISSUE TITLE
custom variables in zone objects

### ISSUE THREAD

**Issue by unix0r** [Icinga/icinga2#6366]
Hey guys, i want to separate all hosts in our monitoring (currently 1212 Hosts in 18 Zones) by the customer owning the zone.

Like we have zones for CustomerA and zones for CustomerB, a modifyed businessprocess module, that shows them in a special hierarchy and now we need to make seperated views for the customers.

CustomerA can only see the host objects of their zones and so on.

I think it would be cool, to add custom variables to the zone object type for this purpose (i think other users could use this feature too).

Otherwise all 1212 hosts would need an extra variable of the owning customer. But with the customer variable in the zone, the seperation of all hosts would be easy.

Thank you

**Comment by dnsmichi** [comment]
@bobapple @lippserd might be considered for our new backend, technically it already is possible in core. Won't be added to DB IDO though.

**Comment by lippserd** [comment]
Wouldn't it better to just have the zone filterable in Web 2?

**Comment by dnsmichi** [comment]
@lippserd Agreed, when used for roles and views, this sounds more reasonable than spilling the zone objects with metadata just for web based things.

**Comment by htriem** [comment]
This will be made available in future iterations of the Icinga DB backend. We won't add it to the existing IDO backend, closing therefore.
