### ISSUE TITLE
icinga2 console breaks the terminal on errors

### ISSUE THREAD

**Issue by sbraz** [Icinga/icinga2#6382]
When an errors occurs in icinga2 console, the terminal is broken and I have to run `reset`. This does not happen on normal exit.

## Steps to Reproduce (for bugs)

1. Run `icinga2 console --connect https://localhost:9999/` (choose an invalid IP/port)
2. Hit tab

The following error is displayed and the programme exits:
```
Icinga 2 (version: r2.8.4-1)
<1> => critical/TcpSocket: Invalid socket: Connection refused
critical/ConsoleCommand: HTTP query failed: std::exception
```
3. after that, the terminal is broken (the text that I type is not displayed), I have to run `reset` to fix it

## Context

I'm using bash, but I assume other shells are affected too. The problem is present both with and without libedit support.

## Your Environment

* Version used (`icinga2 --version`): r2.8.4-1
* Operating System and version: Gentoo

**Comment by dnsmichi** [comment]
I can confirm this behaviour.
