### ISSUE TITLE
Error while evaluating expression: Tried to access undefined script variable 'PluginContribDir'

### ISSUE THREAD

**Issue by nwonknutsitra** [Icinga/icinga2#6388]
Been trying the latest update 2.8.4-1 but was getting the error below. Any recommendations?

â icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/icinga2.service.d
           ââlimits.conf
   Active: failed (Result: exit-code) since Tue 2018-06-19 18:57:32 PHT; 8min ago
  Process: 1532 ExecStart=/usr/sbin/icinga2 daemon -e ${ICINGA2_ERROR_LOG} (code=exited, status=1/FAILURE)
  Process: 1524 ExecStartPre=/usr/lib/icinga2/prepare-dirs /usr/lib/icinga2/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 1532 (code=exited, status=1/FAILURE)

Jun 19 18:57:32 icinga icinga2[1532]: /usr/share/icinga2/include/plugins-contrib.d/operating-system.conf(76):  arguments = {
Jun 19 18:57:32 icinga icinga2[1532]: [2018-06-19 18:57:32 +0800] critical/config: Error: Error while evaluating expression: Tried to access undefined script variable 'PluginContribDir'
Jun 19 18:57:32 icinga icinga2[1532]: Location: in /usr/share/icinga2/include/plugins-contrib.d/vmware.conf: 25:14-25:29
Jun 19 18:57:32 icinga icinga2[1532]: /usr/share/icinga2/include/plugins-contrib.d/vmware.conf(23):
Jun 19 18:57:32 icinga icinga2[1532]: /usr/share/icinga2/include/plugins-contrib.d/vmware.conf(24): template CheckCommand "vmware-esx-command" {
Jun 19 18:57:32 icinga icinga2[1532]: /usr/share/icinga2/include/plugins-contrib.d/vmware.conf(25):  command = [ PluginContribDir + "/check_vmware_esx" ]
Jun 19 18:57:32 icinga icinga2[1532]:                                                                            ^^^^^^^^^^^^^^^^
Jun 19 18:57:32 icinga icinga2[1532]: /usr/share/icinga2/include/plugins-contrib.d/vmware.conf(26):
Jun 19 18:57:32 icinga icinga2[1532]: /usr/share/icinga2/include/plugins-contrib.d/vmware.conf(27):  arguments = {
Jun 19 18:57:32 icinga icinga2[1532]: [2018-06-19 18:57:32 +0800] critical/config: 191 errors

----Version----

root@icinga:/etc# icinga2 --version
[2018-06-19 19:40:37 +0800] warning/icinga-app: Sysconfig file '/etc/sysconfig/icinga2' cannot be read. Using default values.
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.3 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-87-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: 9c880c2f42f5

**Comment by dnsmichi** [comment]
`PluginContribDir` needs to be specified in constants.conf as written in the docs. Next time please ask on the community channels, this is not a bug.

**Comment by nwonknutsitra** [comment]
Thank you so much. Apologies as it was my first time writing here.
