### ISSUE TITLE
windows-uptime plugin - perfdata non guideline conform output

### ISSUE THREAD

**Issue by Gammenon** [Icinga/icinga2#6406]
## Expected Behavior
the plugin perfdata output should be usable for graphing with e.g. graphite.
In my case no graph is generated. With other plugins the behavior is like expected.

## Current Behavior
If the -u parameter is used, in my case to set the unit to "hour", an 'h' is append to the perfdata current value. No graph is available.

> "c:\Program Files\ICINGA2\sbin\check_uptime.exe" -c 840 -u h -w 768
UPTIME OK 352**h** | uptime=352h;768;840;0;

## Possible Solution
I think the reason for this could be, that graphite isn't able to generate a graph because the 'h' can't be handled. According to the Monitoring Plugin Guidelines the 'h' is not one of the UOM (unit of measurement)

## Steps to Reproduce (for bugs)
Use the plugin with the default command object an these parameters
uptime_win_crit: "840", uptime_win_unit: "h", uptime_win_warn: "768"

## Your Environment

* Version used (`icinga2 --version`): v2.8.4
* Operating System and version: Windows Server 2008r2 (agent) centos7 (server)
* Icinga Web 2 version and modules (System - About): 2.5.3 / graphite 1.0.1 / 
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by mcktr** [comment]
Thanks for the report, indeed `h` isn't a valid UOM.
