### ISSUE TITLE
icinga2 crashes due to undefined macro

### ISSUE THREAD

**Issue by unix0r** [Icinga/icinga2#6415]
Hey guys, im developing some new services etc. for our monitoring system and a couple of days ago a service was defined in global-templates and spread to the satellites. One of the satellite crashed now due to 

> [2018-06-22 15:48:13 +0200] warning/MacroProcessor: Macro 'vars._toPrint' is not defined.
> Context:
>         (0) Resolving macros for string 'echo $vars._toPrint$'
>         (1) Executing check for object 'pls-goeteborg1_10.46.8.143_Dispenser_2!Dispenser_print_something'
> 
> [2018-06-22 15:48:33 +0200] warning/JsonRpcConnection: API client disconnected for identity 'PLS-SERVER-DEV'
> [2018-06-22 15:49:08 +0200] warning/MacroProcessor: Macro 'vars._toPrint' is not defined.
> Context:
>         (0) Resolving macros for string 'echo $vars._toPrint$'
>         (1) Executing check for object 'pls-goeteborg1_10.46.8.141_Dispenser_1!Dispenser_print_something'
> 
> [2018-06-22 15:49:10 +0200] critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in '/var/log/icinga2/crash/report.1529675350.860962'

The icinga2 log is full with this warnings. But one day it was enough for icinga2 and it crashed.

Heres the crash log:

> Application information:
>   Application version: r2.8.2-1
>   Installation root: /usr
>   Sysconf directory: /etc
>   Run directory: /run
>   Local state directory: /var
>   Package data directory: /usr/share/icinga2
>   State path: /var/lib/icinga2/icinga2.state
>   Modified attributes path: /var/lib/icinga2/modified-attributes.conf
>   Objects path: /var/cache/icinga2/icinga2.debug
>   Vars path: /var/cache/icinga2/icinga2.vars
>   PID path: /run/icinga2/icinga2.pid
> 
> System information:
>   Platform: Ubuntu
>   Platform version: 16.04.3 LTS (Xenial Xerus)
>   Kernel: Linux
>   Kernel version: 4.4.0-112-generic
>   Architecture: x86_64
> 
> Build information:
>   Compiler: GNU 5.3.1
>   Build host: 86927c12b6d8
> Stacktrace:
> 
>         (0) libpthread.so.0: <unknown function> (+0x11390) [0x2abf8edc2390]
>         (1) libc.so.6: gsignal (+0x38) [0x2abf8fea8428]
>         (2) libc.so.6: abort (+0x16a) [0x2abf8feaa02a]
>         (3) libc.so.6: <unknown function> (+0x777ea) [0x2abf8feea7ea]
>         (4) libc.so.6: <unknown function> (+0x8037a) [0x2abf8fef337a]
>         (5) libc.so.6: cfree (+0x4c) [0x2abf8fef753c]
>         (6) libicinga.so.2.8.2: icinga::MacroProcessor::ResolveMacro(icinga::String const&, std::vector<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> >, std::allocator<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> > > > const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::Value*, bool*) (+0x2f2) [0x2abf95f6bb02]
>         (7) libicinga.so.2.8.2: icinga::MacroProcessor::InternalResolveMacros(icinga::String const&, std::vector<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> >, std::allocator<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> > > > const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String*, boost::function<icinga::Value (icinga::Value const&)> const&, boost::intrusive_ptr<icinga::Dictionary> const&, bool, int) (+0x58b) [0x2abf95f6c99b]
>         (8) libicinga.so.2.8.2: icinga::MacroProcessor::ResolveMacros(icinga::Value const&, std::vector<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> >, std::allocator<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> > > > const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String*, boost::function<icinga::Value (icinga::Value const&)> const&, boost::intrusive_ptr<icinga::Dictionary> const&, bool, int) (+0x1c8) [0x2abf95f6d558]
>         (9) libicinga.so.2.8.2: icinga::MacroProcessor::ResolveArguments(icinga::Value const&, boost::intrusive_ptr<icinga::Dictionary> const&, std::vector<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> >, std::allocator<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> > > > const&, boost::intrusive_ptr<icinga::CheckResult> const&, boost::intrusive_ptr<icinga::Dictionary> const&, bool, int) (+0xa6b) [0x2abf95f6e9cb]
>         (10) libicinga.so.2.8.2: icinga::PluginUtility::ExecuteCommand(boost::intrusive_ptr<icinga::Command> const&, boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&, std::vector<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> >, std::allocator<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> > > > const&, boost::intrusive_ptr<icinga::Dictionary> const&, bool, boost::function<void (icinga::Value const&, icinga::ProcessResult const&)> const&) (+0x10a) [0x2abf95f6faca]
>         (11) libmethods.so.2.8.2: icinga::PluginCheckTask::ScriptFunc(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&, boost::intrusive_ptr<icinga::Dictionary> const&, bool) (+0x63a) [0x2abf9633ad2a]
>         (12) libmethods.so.2.8.2: <unknown function> (+0x2295e) [0x2abf9634d95e]
>         (13) libmethods.so.2.8.2: <unknown function> (+0x1ad81) [0x2abf96345d81]
>         (14) libbase.so.2.8.2: icinga::Function::Invoke(std::vector<icinga::Value, std::allocator<icinga::Value> > const&) (+0x4a) [0x2abf8f5983ea]
>         (15) libicinga.so.2.8.2: icinga::CheckCommand::Execute(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&, boost::intrusive_ptr<icinga::Dictionary> const&, bool) (+0x139) [0x2abf95f15649]
>         (16) libicinga.so.2.8.2: icinga::Checkable::ExecuteCheck() (+0x4a5) [0x2abf95f95875]
>         (17) libchecker.so.2.8.2: <unknown function> (+0x14eab) [0x2abf9656feab]
>         (18) libbase.so.2.8.2: icinga::ThreadPool::WorkerThread::ThreadProc(icinga::ThreadPool::Queue&) (+0x3d8) [0x2abf8f5c6ce8]
>         (19) libboost_thread.so.1.58.0: <unknown function> (+0x115d5) [0x2abf9024e5d5]
>         (20) libpthread.so.0: <unknown function> (+0x76ba) [0x2abf8edb86ba]
>         (21) libc.so.6: clone (+0x6d) [0x2abf8ff7a41d]
> 
> ***
> * This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
> * please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
> * information that might be useful in order to reproduce this problem.
> ***

The service:
```
 apply Service "Dispenser_print_something" {
     import "generic-service"
     display_name = "Some Service"
     check_command = "printText"
     vars._toPrint = "Changed it now"
   assign where host.vars._Type == "Dispenser"
   assign where host.vars._Type == "Disp"
   assign where host.vars._Type == "dispenser"
 }
 
```

And the check Command
```
object CheckCommand "printText" {
    import "plugin-check-command"
    command = "echo $vars._toPrint$"
}
```

-->

## Expected Behavior
If the service/checkcommand is wrong, throw a warning and thats it.

## Current Behavior
A lot of warnings and one some day a crash.

## Your Environment
* Version used (`icinga2 --version`):

> icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-1)
> 
> Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
> License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Application information:
>   Installation root: /usr
>   Sysconf directory: /etc
>   Run directory: /run
>   Local state directory: /var
>   Package data directory: /usr/share/icinga2
>   State path: /var/lib/icinga2/icinga2.state
>   Modified attributes path: /var/lib/icinga2/modified-attributes.conf
>   Objects path: /var/cache/icinga2/icinga2.debug
>   Vars path: /var/cache/icinga2/icinga2.vars
>   PID path: /run/icinga2/icinga2.pid
> 
> System information:
>   Platform: Ubuntu
>   Platform version: 16.04.3 LTS (Xenial Xerus)
>   Kernel: Linux
>   Kernel version: 4.4.0-112-generic
>   Architecture: x86_64
> 
> Build information:
>   Compiler: GNU 5.3.1
>   Build host: 86927c12b6d8

* Operating System and version:
* Enabled features (`icinga2 feature list`):

> Disabled features: compatlog debuglog elasticsearch gelf graphite influxdb livestatus notification opentsdb statusdata syslog
> Enabled features: api checker command ido-pgsql mainlog perfdata

* Config validation (`icinga2 daemon -C`):

> information/cli: Icinga application loader (version: r2.8.2-1)
> information/cli: Loading configuration file(s).
> information/ConfigItem: Committing config item(s).
> information/ApiListener: My API identity: pls-goeteborg1
> warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'ping6' (in /etc/icinga2/conf.d/services.conf: 28:1-28:21) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule '' (in /etc/icinga2/conf.d/services.conf: 51:1-51:65) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule '' (in /etc/icinga2/conf.d/services.conf: 59:1-59:53) for type 'Service' does not match anywhere!
> information/ConfigItem: Instantiated 1 ApiListener.
> information/ConfigItem: Instantiated 4 Zones.
> information/ConfigItem: Instantiated 2 Endpoints.
> information/ConfigItem: Instantiated 1 FileLogger.
> information/ConfigItem: Instantiated 2 ApiUsers.
> information/ConfigItem: Instantiated 2 NotificationCommands.
> information/ConfigItem: Instantiated 243 CheckCommands.
> information/ConfigItem: Instantiated 58 Downtimes.
> information/ConfigItem: Instantiated 6 HostGroups.
> information/ConfigItem: Instantiated 1 IcingaApplication.
> information/ConfigItem: Instantiated 1 EventCommand.
> information/ConfigItem: Instantiated 117 Hosts.
> information/ConfigItem: Instantiated 1 UserGroup.
> information/ConfigItem: Instantiated 1 User.
> information/ConfigItem: Instantiated 3 TimePeriods.
> information/ConfigItem: Instantiated 708 Services.
> information/ConfigItem: Instantiated 5 ServiceGroups.
> information/ConfigItem: Instantiated 1 ExternalCommandListener.
> information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
> information/ConfigItem: Instantiated 1 PerfdataWriter.
> information/ConfigItem: Instantiated 1 CheckerComponent.
> information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
> information/cli: Finished validating the configuration file(s).

TopDown Zone Configuration

**Comment by dnsmichi** [comment]
Question aside - why don't you fix the macros aka custom attributes which are missing. This really is an error. The crash looks strange to me, can this be reproduced with 2.8.4 or the snapshot packages?

**Comment by unix0r** [comment]
The macros were by mistake wrong. We are planning an update soon, after that i could check the behavior with the new version.

**Comment by dnsmichi** [comment]
Please re-test this with 2.9.0 then.

**Comment by dnsmichi** [comment]
@unix0r did you see that again with recent versions?

**Comment by unix0r** [comment]
yeah, the crashes were gone with 2.9.1 i think.
so this bug is closed.

Thank you.
