### ISSUE TITLE
icinga2 node list or  icinga2 node update-config command not working 

### ISSUE THREAD

**Issue by sanjeet4u** [Icinga/icinga2#6425]
icinga2 node list or  icinga2 node update-config command not working >>>

Post configuration of Master and Client setup when I am firing below command I am getting output as :- 

[root@saim icinga2]# icinga2 node update-config
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Usage:
  icinga2 <command> [<arguments>]

Supported commands:
  * node setup (set up node)
  * node wizard (wizard for node setup)

Global options:
  -h [ --help ]             show this help message
  -V [ --version ]          show version information
  --color                   use VT100 color codes even when stdout is not a
                            terminal
  -D [ --define ] arg       define a constant
  -a [ --app ] arg          application library name (default: icinga)
  -l [ --library ] arg      load a library
  -I [ --include ] arg      add include search directory
  -x [ --log-level ] arg    specify the log level for the console log.
                            The valid value is either debug, notice,
                            information (default), warning, or critical
  -X [ --script-debugger ]  whether to enable the script debugger

**Comment by dnsmichi** [comment]
https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#removed-bottom-up-client-mode
