### ISSUE TITLE
API has an issue when recreating an object with different params

### ISSUE THREAD

**Issue by aflatto** [Icinga/icinga2#6431]
When creating an object, then deleting it, and recreating it again with same name but different parameter such as Zone.
Once the object has been recreated, it does not appear in the WEB.

## Expected Behavior
When creating an object, then deleting it, and recreating it with a new set of parameters, it should appear in the web as a new object .

## Current Behavior
When creating an object, then deleting it, and recreating it with a new set of parameters, it does not appear in the web as a new object .

## Steps to Reproduce (for bugs)

creation:
```
curl -k -s -u user:pass   \
     -H 'Accept: application/json' -X PUT \
                'https://localhost:5665/v1/objects/services/ash.customer.application.https-mc!chi.customer.application.https-mc.fullpath' \
     -d '{ "templates": [ "application-check.tmpl" ], "attrs": { "display_name": "", "vars.http_address": "1.1.1.1", "vars.http_vhost": "application.com", "vars.port": 443, "vars.http_ssl": true, "vars.http_sni" : true} }' | python -m json.tool
```
delete:
```
curl -k -s -u user:pass   \
     -H 'Accept: application/json' -X DELETE \
        'https://localhost:5665/v1/objects/services/ash.customer.application.https-mc!chi.customer.application.https-mc.fullpath'| python -m json.tool
```
Then recreate with added zone param:
```
curl -k -s -u user:pass   \
     -H 'Accept: application/json' -X PUT \
                'https://localhost:5665/v1/objects/services/ash.customer.application.https-mc!chi.customer.application.https-mc.fullpath' \
     -d '{ "templates": [ "application-check.tmpl" ], "attrs": { **"zone": "ASH"**, "display_name": "", "vars.http_address": "1.1.1.1", "vars.http_vhost": "application.com", "vars.port": 443, "vars.http_ssl": true, "vars.http_sni" : true} }' | python -m json.tool
```

The API is registering the object but it is not seen in the Icingaweb.
## Context

We are trying to register new hosts and create the service for them via the API, in initial stages the allocation of zone execution was not defined for a service and when trying to add the zone var to the deleted -> recreated object , the service did not appear on the Icinga web.

## Your Environment

* Version used (`icinga2 --version`): icinga 2.8.4
* Operating System and version: Centos 7.4 x86_64
* Enabled features (`icinga2 feature list`): api checker debuglog ido-mysql notification 
* Icinga Web 2 version and modules (System - About):2.6  Modules: Director, Cube,Monitoring,Docs,Graphite

**Comment by mcktr** [comment]
Hi,

just tested this in my demo setup, it works here. 

Have you check the API if the service is there? 

```
# curl -k -s -u root:icinga -H 'Accept: application/json' -X GET 'https://192.168.178.181:5665/v1/objects/services/test!test-service' | python -m json.tool
{
    "results": [
        {
            "attrs": {
                "__name": "test!test-service",
[...]
```

Are there any filters for your Icinga Web user that maybe hide the new created service?

**Comment by bardahlm** [comment]
I have a related experience:
Sometimes object created using the API do not show up in the web-gui. They are present in the API, though. If I restart Icinga the missing objects come to life and starts to be monitored. We're running 2.8.4.

**Comment by dnsmichi** [comment]
Next time, please provide a standalone copy paste reproducer. 

I'm not able to reproduce this here with 2.10.1.

```
curl -k -s -u root:icinga   \
     -H 'Accept: application/json' -X PUT \
                'https://localhost:5665/v1/objects/services/mbmif.int.netways.de!chi.customer.application.https-mc.fullpath' \
     -d '{ "templates": [ "generic-service" ], "attrs": { "check_command": "dummy", "display_name": "", "vars.http_address": "1.1.1.1", "vars.http_vhost": "application.com", "vars.port": 443, "vars.http_ssl": true, "vars.http_sni" : true} }' | python -m json.tool


curl -k -s -u root:icinga   \
    -H 'Accept: application/json' -X DELETE \
       'https://localhost:5665/v1/objects/services/mbmif.int.netways.de!chi.customer.application.https-mc.fullpath'| python -m json.tool  

curl -k -s -u root:icinga   \
    -H 'Accept: application/json' -X PUT \
               'https://localhost:5665/v1/objects/services/mbmif.int.netways.de!chi.customer.application.https-mc.fullpath' \
    -d '{ "templates": [ "generic-service" ], "attrs": { "zone": "master", "check_command": "dummy", "display_name": "", "vars.http_address": "1.1.1.1", "vars.http_vhost": "application.com", "vars.port": 443, "vars.http_ssl": true, "vars.http_sni" : true} }' | python -m json.tool                
```


```
michi@mbmif ~ $ curl -k -s -u root:icinga   \
>      -H 'Accept: application/json' -X PUT \
>                 'https://localhost:5665/v1/objects/services/mbmif.int.netways.de!chi.customer.application.https-mc.fullpath' \
>      -d '{ "templates": [ "generic-service" ], "attrs": { "check_command": "dummy", "display_name": "", "vars.http_address": "1.1.1.1", "vars.http_vhost": "application.com", "vars.port": 443, "vars.http_ssl": true, "vars.http_sni" : true} }' | python -m json.tool
{
    "results": [
        {
            "code": 200.0,
            "status": "Object was created"
        }
    ]
}
michi@mbmif ~ $      curl -k -s -u root:icinga   \
>           -H 'Accept: application/json' -X DELETE \
>              'https://localhost:5665/v1/objects/services/mbmif.int.netways.de!chi.customer.application.https-mc.fullpath'| python -m json.tool
{
    "results": [
        {
            "code": 200.0,
            "errors": [],
            "name": "mbmif.int.netways.de!chi.customer.application.https-mc.fullpath",
            "status": "Object was deleted.",
            "type": "Service"
        }
    ]
}
michi@mbmif ~ $ vim /usr/local/icinga2/etc/icinga2/zones.conf
michi@mbmif ~ $ curl -k -s -u root:icinga   \
>     -H 'Accept: application/json' -X PUT \
>                'https://localhost:5665/v1/objects/services/mbmif.int.netways.de!chi.customer.application.https-mc.fullpath' \
>     -d '{ "templates": [ "generic-service" ], "attrs": { "zone": "master", "check_command": "dummy", "display_name": "", "vars.http_address": "1.1.1.1", "vars.http_vhost": "application.com", "vars.port": 443, "vars.http_ssl": true, "vars.http_sni" : true} }' | python -m json.tool
{
    "results": [
        {
            "code": 200.0,
            "status": "Object was created"
        }
    ]
}
```

![screen shot 2018-10-30 at 10 26 57](https://user-images.githubusercontent.com/382049/47710024-fd8a2f00-dc31-11e8-8ac0-9159b0194b65.png)

![screen shot 2018-10-30 at 10 30 03](https://user-images.githubusercontent.com/382049/47710022-fd8a2f00-dc31-11e8-8e9d-33511186e3ee.png)

![screen shot 2018-10-30 at 10 31 40](https://user-images.githubusercontent.com/382049/47710020-fd8a2f00-dc31-11e8-95aa-73b8eeff4fa0.png)

**Comment by hanpeter** [comment]
Sorry to comment on a closed issue, but also experiencing similar issue. In my case, I can get the host re-appear on `icingaweb2` by reloading the config.

Let me know what information I can provide to help you.

Icinga version: `r2.9.2-1`
Operating system: `Ubuntu 14.04.5 LTS`
Enabled features: api checker command ido-mysql mainlog notification syslog
Icinga Web 2 version: `2.4.2`
Icinga Web 2 modules: setup, monitoring
