### ISSUE TITLE
Performance data threshold differs from check command

### ISSUE THREAD

**Issue by lbayerlein** [Icinga/icinga2#6432]
## Expected Behavior
Warnings and critical values are like in the configuration.

## Current Behavior
Missmatch of the configurations before and the actual configured values.

![image](https://cloud.bayerlein-networks.com/index.php/apps/files_sharing/ajax/publicpreview.php?x=1920&y=567&a=true&file=screenshot_36.png&t=qTgSLEZLdG5NQ59&scalingup=0)

## Possible Solution
Don't know. If I do a manual check, it pushes the right warnings and criticals. But on the next check (done via the system), the old values come back.

## Steps to Reproduce (for bugs)

1. Configure host, host group (with assignement), service template, service apply via Director
2. Take check_load as service check and do not set the warnings and criticals (or configure it with some values)
3. Now set some values or change the values to higher ones

## Your Environment

* Version used (`icinga2 --version`): r2.8.4-1
* Operating System and version: CentOS 7 (actual updates)
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.5.3
* Config validation (`icinga2 daemon `-C`):
```
information/cli:`` Icinga application loader (version: r2.8.4-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: mon.hering.lan
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 11 Zones.
information/ConfigItem: Instantiated 9 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 12 Notifications.
information/ConfigItem: Instantiated 211 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 9 Hosts.
information/ConfigItem: Instantiated 5 HostGroups.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 75 Services.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by MaBauMeBad** [comment]
PLease check if on the node self the conf.d directory is included.
If so, the values are overriden with local defined default values.

**Comment by mcktr** [comment]
You can run `icinga2 object list --type Service --name load` on the client to find out where the settings gets modified.

**Comment by lbayerlein** [comment]
Thanks for your answer.

@mcktr I did an object list, but there is no warning or critical threshold to see.

```
[root@hypervisor icinga2]# icinga2 object list --type Service --name load
Object 'hypervisor.localdomain!load' of type 'Service':
  % declared in '/etc/icinga2/conf.d/services.conf', lines 81:1-81:20
  * __name = "hypervisor.localdomain!load"
  * action_url = ""
  * check_command = "load"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 84:3-84:24
  * check_interval = 60
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 28:3-28:21
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "load"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "hypervisor.localdomain"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 81:1-81:20
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 5
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 27:3-27:24
  * name = "load"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 81:1-81:20
  * notes = ""
  * notes_url = ""
  * package = "_etc"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 81:1-81:20
  * retry_interval = 30
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 29:3-29:22
  * source_location
    * first_column = 1
    * first_line = 81
    * last_column = 20
    * last_line = 81
    * path = "/etc/icinga2/conf.d/services.conf"
  * templates = [ "load", "generic-service" ]
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 81:1-81:20
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 26:1-26:34
  * type = "Service"
  * vars
    * backup_downtime = "02:00-03:00"
      % = modified in '/etc/icinga2/conf.d/services.conf', lines 87:3-87:38
  * volatile = false
  * zone = ""
```

@MaBauMeBad Yes thats it. Thanks very much - the commands include was the reason, why it did not work as expected.

I mark it as solved.

**Comment by dnsmichi** [comment]
Next time please use the community channels for such questions. This has been asked quite often already, and also has a troubleshooting doc entry.

https://www.icinga.com/docs/icinga2/latest/doc/15-troubleshooting/#check-thresholds-not-applied

**Comment by lbayerlein** [comment]
sorry @dnsmichi for asking via github. I will use irc for future questions
