### ISSUE TITLE
Broken ssl certificate installation on packages.icinga.org

### ISSUE THREAD

**Issue by mjrider** [Icinga/icinga2#6441]
## Expected Behavior
a valid ssl certificate with CA chain included.

## Current Behavior
Only the cert itself is served, but the Letsencrypt chain is missing

## Possible Solution
Fix installation of ssl certificate

## Steps to Reproduce (for bugs)
`https://www.ssllabs.com/ssltest/analyze.html?d=packages.icinga.org&hideResults=on`
Result:
```
Additional Certificates (if supplied)
--
Certificates provided | 1 (1557 bytes)
Chain issues | Incomplete
```

or
` gnutls-cli packages.icinga.org`
results in:
```
- Status: The certificate is NOT trusted. The certificate issuer is unknown. 
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
*** handshake has failed: Error in the certificate.
```

Other sites with Letsencrypt certificates do not have this problem

The missing certificate is:
```
 - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="
```

## Context
Trying to install icinga packages fails because of a failing ssl checks

## Your Environment
Ubuntu xenial/ Ubuntu bionic

**Comment by dnsmichi** [comment]
We've already have an internal infrastructure ticket for that, thanks though.

Next time, please use info@icinga.com or the contact form on icinga.com for infrastructure related problems.

**Comment by robertknight** [comment]
Hello @dnsmichi - it would be helpful if this issue could be updated (eg. just with a comment) once the problem is resolved, so that other interested parties can subscribe to updates.

**Comment by dnsmichi** [comment]
Short update: Change your configuration and roles to use packages.icinga.com. The .org domain was deprecated a while ago and won't live forever, redirects are already in place.
