### ISSUE TITLE
icinga r2.9.0-1 init.d script overrides PATH variable

### ISSUE THREAD

**Issue by olegy89** [Icinga/icinga2#6449]
Hello,

after upgrading to 2.9, init script has been changed, so PATH variable declared in /etc/default/icinga2 or  /etc/sysconfig/icinga2 overriding in /etc/rc.d/init.d/functions.
And some custom plugins stop working.

icinga 2.9 init script:
```
...
     18 # load system specific defines
     19 SYSCONFIGFILE=/etc/sysconfig/icinga2
     20 if [ -f $SYSCONFIGFILE ]; then
     21     . $SYSCONFIGFILE
     22 else
     23     echo "Couldn't load system specific defines from $SYSCONFIGFILE. Using defaults."
     24 fi
...
     37 # Load extra environment variables
     38 if [ -f /etc/default/icinga2 ]; then
     39     . /etc/default/icinga2
     40 fi
...
     53 # Get function from functions library
     54 if [ -f /etc/rc.d/init.d/functions ]; then
     55     . /etc/rc.d/init.d/functions
     56 elif [ -f /etc/init.d/functions ]; then
     57     . /etc/init.d/functions
     58 fi

``` 

And icinga <2.9 init.d script:
```
     48 # Get function from functions library
     49 if [ -f /etc/rc.d/init.d/functions ]; then
     50     . /etc/rc.d/init.d/functions
     51 elif [ -f /etc/init.d/functions ]; then
     52     . /etc/init.d/functions
     53 fi
     54
     55 # Load extra environment variables
     56 if [ -f /etc/default/icinga2 ]; then
     57     . /etc/default/icinga2
     58 fi
```

## Your Environment
icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.0-1)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /var/run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /var/run/icinga2/icinga2.pid

System information:
  Platform: CloudLinux Server
  Platform version: 6.10 (Vladimir Lyakhov)
  Kernel: Linux
  Kernel version: 2.6.32-531.29.2.lve1.3.11.10.el6.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.2
  Build host: 5009d75245b1

**Comment by Crunsher** [comment]
At no point we overwrite or add to PATH, why do you suspect this or when did you notice this?

**Comment by Crunsher** [comment]
Looking at it in connection with #6448 this makes more sense. Possible the cause even.

**Comment by dnsmichi** [comment]
@olegy89 when you manually change the initscript and put functions first, does it actually solve your problem?

**Comment by olegy89** [comment]
@dnsmichi yes, changing the initscript manually, solve the problem but after another icinga update should I do that again? I expect to keep icinga updated, without each time to edit the initscript.

**Comment by dnsmichi** [comment]
I just wanted your confirmation prior to reviewing the linked PR. I'm currently debugging a different issue and am looking for a quick workarounds here which help for the moment.
