### ISSUE TITLE
Icinga clustercheck ignores host downtime

### ISSUE THREAD

**Issue by bmack94** [Icinga/icinga2#6453]
**Problem:**
icinga2 clustercheck reports a warning/critical if a host that is in a scheduled downtime is not connected (rebooting).

**Expected Behavior**
The clustercheck should ignore the host that has a dowtime set and report OK

**Current Behavior**
ClusterCheckTask is only checking if the host is connected or not, not if its in downtime
See: https://github.com/Icinga/pkg-icinga2-debian/blob/7e84a001b5812ac3f53c404b19666830c0f70766/lib/methods/clusterchecktask.cpp#L61

This has to do with the apilistener::getStatus()
This only counts up the connected/unconnected endpoints. This should also check, if a host is not connected, if it is in a scheduled downtime
See: https://github.com/Icinga/pkg-icinga2-debian/blob/7e84a001b5812ac3f53c404b19666830c0f70766/lib/remote/apilistener.cpp#L1077

**Possible Solution**
Check if the host is in downtime, if it is in downtime -> count variable "not_connected_endpoints"
in Apilistener::getStatus() add a var with "not_connected_endpoints_in_downtime"
Then in ClusterCheckTask substract the "not_connected_endpoints" with "not_connected_endpoints_in_downtime"

**Your Environment**
* Version used (`icinga2 --version`): 2.8.4-1
* Operating System and version: Debain Jessie
* Enabled features (`icinga2 feature list`): api checker command compatlog graphite ido-pgsql livestatus mainlog notofication statusdata
* Config validation (`icinga2 daemon -C`): All good, nor errors

**Comment by dnsmichi** [comment]
There‘s no 1:1 relation between a host and endpoint object. If you want to have the cluster-zone service check in a downtime, you‘ll need to schedule one, at the same time as with the host downtime.

**Comment by treibholz** [comment]
But if you schedule a downtime for one host and you always have to schedule a downtime for "cluster-zone service check", you are blind in the meantime for all other endpoints.
This is very unhandy if you have to schedule a downtime for  a longer time (e.g. if you have to wait for broken hardware-parts to be exchanged)

**Comment by dnsmichi** [comment]
I see. Likely cluster-zone is only sufficient for a single client then, not for satelitte zones.

**Comment by Z3po** [comment]
The Problem is if you have zone-checks installed to see if any of the endpoints is in an abnormal state and you always set the cluster zone check to "scheduled downtime" once you have a host maintenance, you won't recognize the rest of the endpoints going crazy.
Is there a better way to monitor an icinga instance if it's functional and connected to the cluster?

**Comment by bmack94** [comment]
@dnsmichi i don't see why this should be a question, in my eyes this is definitely a bug. No alarm should go critical if the host has a scheduled downtime.
If the check is not intended for this use, can you provide a better solution, that we can use?

**Comment by dnsmichi** [comment]
As said, there is no 1:1 relation between a host/service object and an endpoint in a zone. Therefore the sole purpose when executing `cluster-zone` is to check whether endpoints are connected, and return a check result. It does not have access to a specific host or service downtime in this scope.

Imho this is sort of a feature request, and not a bug. Probably one where we won't find a solution, to this point I have no idea how to solve this.

**Comment by dnsmichi** [comment]
I don't see how this can be implemented without breaking things, or "guessing" relations. I'll take a note for improving the cluster health views though.
