### ISSUE TITLE
Icinga2 Amazon Linux 2 installation - symbol lookup error

### ISSUE THREAD

**Issue by TacticalGrace** [Icinga/icinga2#6459]
## Expected Behavior
Expected to be able to execute ````icinga2```` binary for configuration of satellite.

## Current Behavior
Any execution of ````icinga2```` reults in the following error:

````/usr/lib64/icinga2/sbin/icinga2: symbol lookup error: /usr/lib64/icinga2/sbin/icinga2: undefined symbol: _ZN5boost15program_options3argE````

## Steps to Reproduce (for bugs)
Launch ````Amazon Linux 2```` instance and setup with the following:

````
cd /tmp && wget -O epel.rpm –nv https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum install -y ./epel.rpm
sudo rpm --import https://packages.icinga.com/icinga.key
sudo yum install https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
sudo sed -i -e 's/$releasever/7/g' /etc/yum.repos.d/ICINGA-release.repo
sudo yum makecache
sudo yum install icinga2 nagios-plugins-all
````

Then just try and execute the ````icinga2```` binary.

Any help gratefully received.

## Context
I'm setting up a new ````Amazon Linux 2```` server in and require satellite install. Icinga2 master and icingaweb2 already installed and working elsewhere on ````Amazon Linux (1)````.

## Your Environment

* Version used (`icinga2 --version`): 2.9.0-1.el7
* Operating System and version: Amazon Linux 2
* Enabled features (`icinga2 feature list`): Haven't get that far yet!
* Icinga Web 2 version and modules (System - About): N/A
* Config validation (`icinga2 daemon -C`):Haven't get that far yet!

**Comment by dnsmichi** [comment]
Amazon Linux is not the same as RHEL7, this has different binary build requirements and such you cannot use our official packages for it. You need to use the SPEC file or SRPM and rebuild that. We don't provide package support for Amazon Linux on our official mirrors.

**Comment by TacticalGrace** [comment]
Okay great, I understand. I guess I was just lucky getting icinga2 RHEL6 release working on ````Amazon Linux (1)````.

I'll go down the official Rehat 7 Enterprise instance in AWS.

Many thanks for your help!

**Comment by dnsmichi** [comment]
For the first version, we've added changes to the spec file (but still there was no 1:1 copy of rhel6 possible, at least for the user asking). I think Amazon Linux 2 isn't 100% binary compatible with el7 anymore, which is the problem here.

**Comment by ctrlaltca** [comment]
Since this is the first Google result for "icinga2 amazon linux 2", here's a quick update.

Installing a few libraries from epel it's possible to install icinga2-2.11 directly from Icinga's RHEL7 repo:
```
yum --enablerepo=epel install boost169-date-time boost169-program-options boost169-thread boost169-context boost169-regex boost169-coroutine boost169-system boost169-filesystem
yum install icinga2
```

**Comment by mafaul** [comment]
> Since this is the first Google result for "icinga2 amazon linux 2", here's a quick update.
> 
> Installing a few libraries from epel it's possible to install icinga2-2.11 directly from Icinga's RHEL7 repo:
> 
> ```
> yum --enablerepo=epel install boost169-date-time boost169-program-options boost169-thread boost169-context boost169-regex boost169-coroutine boost169-system boost169-filesystem
> yum install icinga2
> ```
Update 2021: I just get the following error:

failure: repodata/repomd.xml from icinga-stable-release: [Errno 256] No more mirrors to try.
https://packages.icinga.com/epel/2/release/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

**Comment by seffparker** [comment]
> Update 2021: I just get the following error:
> 
> failure: repodata/repomd.xml from icinga-stable-release: [Errno 256] No more mirrors to try.
> https://packages.icinga.com/epel/2/release/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

As per @ghost, the following will fix the 404-error:
```
sudo sed -i -e 's/$releasever/7/g' /etc/yum.repos.d/ICINGA-release.repo
```
bot not the `libboost` dependancy.
