### ISSUE TITLE
Icinga 2 not writing to IDO DB (mysql) after update to 2.9.0

### ISSUE THREAD

**Issue by draeklae** [Icinga/icinga2#6474]
After updating to 2.9.0, Icinga 2 no longer writes to or updates the mysql IDO DB database. In IcingaWeb 2 under "Monitoring Health" "icinga is currently not up and running" is shown.

Tried dropping IDO DB and creating new one, but without success. No information is written to the DB.

In the debug log only the following lines contain anything related to IDO:
```
[2018-07-23 18:44:08 +0200] information/IdoMysqlConnection: 'ido-mysql' resumed.
[2018-07-23 18:44:09 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'IdoMysqlConnection, ido-mysql'
```

## Your Environment
* Version used (`icinga2 --version`): r2.9.0-1
* Operating System and version: SLES 11.4
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification perfdata
* mysql  Ver 14.14 Distrib 5.5.60, for Linux (x86_64) using readline 5.2

**Comment by draeklae** [comment]
Issue appeared with update to 2.9.0. Worked fine with 2.8.4.

**Comment by linuxmail** [comment]
hi,

same for me, but for Debian Jessie.

**Comment by mcktr** [comment]
This is highly likely related to #6445 

Can you test the snapshot packages?

**Comment by draeklae** [comment]
Indeed related to #6445. Snapshot fixes it.

**Comment by mcktr** [comment]
That was fast, thanks for testing and the feedback :+1:
