### ISSUE TITLE
command-plugins.conf check_disk exclude squashfs

### ISSUE THREAD

**Issue by roccolord** [Icinga/icinga2#6481]
Hi, would be nice if squashfs could be added to the exclude list for check_disk in command-plugins. 

It's used on Ubuntu to mount snaps.

**Comment by dnsmichi** [comment]
Can you edit the corresponding ITL configuration and update the docs, put that into a PR?

https://github.com/Icinga/icinga2/blob/master/itl/command-plugins.conf
https://github.com/Icinga/icinga2/blob/master/doc/10-icinga-template-library.md

More instructions: https://github.com/Icinga/icinga2/blob/master/CONTRIBUTING.md
