### ISSUE TITLE
Icinga logs discarding messages still as warning and not as notice

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icinga2#6485]
Icinga in a ha cluster with satellites setup still logs "discarding config update object" messages within warning level.

## Expected Behavior
Discarding messages should be in notice level, see #4930

## Current Behavior
Icinga logs a million times this message when serverity is set to ìnformation`in mainlog.conf

## Possible Solution
set message to serverity = notice as fixed in #4930

## Steps to Reproduce (for bugs)
Setup a cluster with satellites and have `accept_config = true` in all api.conf set
Add a scheduleddowntime and reload the master

## Your Environment

* Version used (`icinga2 --version`): `2.9.1`
* Operating System and version: `SLES 12`
* Enabled features (`icinga2 feature list`): `api cheker ido-mysql influxdb mainlog notification`

**Comment by dnsmichi** [comment]
I've only fixed the one for creating objects, the delete handler was still logging the warning.

**Comment by dnsmichi** [comment]
No, that's clearly an error and would harden debugging otherwise.
