### ISSUE TITLE
Documentation doesn't mention IDO Database HA 

### ISSUE THREAD

**Issue by martinrw** [Icinga/icinga2#6492]
I was just reading through the docs regarding high availability and distributed monitoring.
One thing that seems to go unmentioned is the high availability of the IDO DB.
While there are many ways to achieve this and it's not really part of the documentation I think it would be good if it was mentioned in the docs even if it was just to say something like "Even though the examples show a single IDO DB, this represents what would normally be a clustered or replicated setup". Potentially with links to some resources or examples.

Cheers
Martin

**Comment by dnsmichi** [comment]
This is part of #5520 and more of a howto with external MySQL/PostgreSQL clusters, nothing we can officially support nor endorse. The third scenario mentions this already:

> One possibility is to use a dedicated MySQL cluster VIP (external application cluster)
and leave the IDO feature with enabled HA capabilities. Alternatively,
you can disable the HA feature and write to a local database on each node.
Both methods require that you configure Icinga Web 2 accordingly (monitoring
backend, IDO database, used transports, etc.).

**Comment by dnsmichi** [comment]
I'm leaving this issue open if someone wants to contribute a documentation PR.

**Comment by dnsmichi** [comment]
There's some good howtos in our community channels, which will be linked with a short note in each scenario. The feature documentation itself already contains many details about it.
