### ISSUE TITLE
API added downtimes 2 hours ahead

### ISSUE THREAD

**Issue by chas0rde** [Icinga/icinga2#6513]
When adding a scheduled downtime to a host via API the downtime is scheduled 2 hours ahead.
Manually adding the downtime results in correct time

## Expected Behavior

Correct time in downtime ;)

## Current Behavior

Downtime scheduled e.g. for 4am via API but results in 6am start time
## Possible Solution

add altered timestamp to workaround

## Steps to Reproduce (for bugs)

Do an API call like:

`curl -X POST \
  'https://monitoring.whatever.local:5665/v1/actions/schedule-downtime?type=host&host=testHost' \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic sdadfq345dsfsdf3245' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 84ed081e-0ecb-4c75-8c2c-dccce5145604' \
  -d '{
	"author": "username",
	"comment": "API Test",
	"start_time": 1533268800,
	"end_time": 1533270600,
	"fixed": 0,
	"duration": 1800
}'`
See that resulting start time is +2 hours (e.g. 6 am)

Server, client and browser are Europe/Berlin timezone.

6am Timestamp would also be in database if checking via 
`select * from icinga_scheduleddowntime order by scheduled_start_time desc limit 10;`
## Your Environment

* Version used (`icinga2 --version`):  r2.9.1-1
* Operating System and version: ubuntu lts 16.04
* Enabled features (`icinga2 feature list`):
Disabled features: elasticsearch gelf influxdb opentsdb perfdata statusdata syslog
Enabled features: api checker command compatlog debuglog graphite ido-mysql livestatus mainlog notification
* Icinga Web 2 version and modules (System - About): 2.6.0
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by Crunsher** [comment]
Icinga handles timestamps the same as date
```
$ date -d @1533268800                                             
Fri  3 Aug 06:00:00 CEST 2018
```
When all machines use the same timezone that should not be a problem. How did you create your timestamp?

**Comment by chas0rde** [comment]
created the timestamp in a powershell script.
The ps1 creates a timespan in seconds between planned downtime start-time and 01/01/1970 00:00:00 (so unix timestamp)
I assumed that a unix timestamp would be required in the API here as nothing else is suggested by the documentation

**Comment by Crunsher** [comment]
With unix epoch a timezone is still required for interpretation. Maybe you can tell your command to build the timestamp for a different timezone.

In any case, this is not a bug with icinga. When you take this problem to the monitoring portal we and other would probably be able to help you find a solution. Best if you post the command/script you use to create the timestamp too.
