### ISSUE TITLE
env vars not exported to "-e" switch (or error log is not written)

### ISSUE THREAD

**Issue by jschanz** [Icinga/icinga2#6516]
env vars are not exported, so switch "-e" in processlist is empty or shows an variable ( and no error log is written.)
Environment is a clean Debian 9.5, packages are from https://packages.icinga.com.

## icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)
```
nagios    5804     1  0 10:11 ?        00:00:00 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log
nagios    5848  5804  0 10:11 ?        00:00:00 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log
```

## icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)
```
nagios    7668     1  0 10:19 ?        00:00:00 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e
nagios    7702  7668  0 10:19 ?        00:00:00 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e
```
After uncommentig parameter ICINGA2_ERROR_LOG in /usr/lib/icinga2/icinga2, the "-e" will be expanded with the logfile, but error log will not be created after restart nor filled with any (startup) information if manually created.

```
nagios    7905     1  2 10:24 ?        00:00:00 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e /var/log/icinga2/error.log
nagios    7940  7905  0 10:24 ?        00:00:00 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e /var/log/icinga2/error.log
```
## Icinga2.9.x and Director
Please have also a look, if all the variables should be commented out by default in /usr/lib/icinga2/icinga2 as the director uses these values for the kickstart script:

```
#This is the default environment Icinga 2 runs with.
#Make your changes here.

#DAEMON=/usr/sbin/icinga2
#ICINGA2_CONFIG_FILE=/etc/icinga2/icinga2.conf
#ICINGA2_RUN_DIR=/run
#ICINGA2_STATE_DIR=/var
#ICINGA2_PID_FILE=/run/icinga2/icinga2.pid
#ICINGA2_LOG_DIR=/var/log/icinga2
#ICINGA2_ERROR_LOG=/var/log/icinga2/error.log
#ICINGA2_STARTUP_LOG=/var/log/icinga2/startup.log
#ICINGA2_LOG=/var/log/icinga2/icinga2.log
#ICINGA2_CACHE_DIR=/var/cache/icinga2
#ICINGA2_USER=nagios
#ICINGA2_GROUP=nagios
#ICINGA2_COMMAND_GROUP=www-data
```
If you run the kickstart script from director 1.4.3, the following error occurs:
```
> bash icinga2_kickstart.sh
check: icinga2 installed - OK
ERROR: $ICINGA2_USER has not been defined
```
```
+ ICINGA2_NODENAME=...
+ ICINGA2_CA_TICKET=...
+ ICINGA2_PARENT_ZONE=...
+ ICINGA2_PARENT_ENDPOINTS=...
+ ICINGA2_CA_NODE=...
+ echo -n 'check: icinga2 installed - '
check: icinga2 installed - + icinga2 --version
+ echo OK
OK
+ '[' '4.4.12(1)-release' ']'
+ RHEL_SYSCONFIG=/etc/sysconfig/icinga2
+ DEB_SYSCONFIG=/usr/lib/icinga2/icinga2
+ '[' -f /etc/sysconfig/icinga2 ']'
+ '[' -f /usr/lib/icinga2/icinga2 ']'
+ ICINGA2_SYSCONFIG_FILE=/usr/lib/icinga2/icinga2
+ . /usr/lib/icinga2/icinga2
++ ICINGA2_ERROR_LOG=/var/log/icinga2/error.log
+ '[' '' ']'
+ fail '$ICINGA2_USER has not been defined'
+ echo 'ERROR: $ICINGA2_USER has not been defined'
ERROR: $ICINGA2_USER has not been defined
+ exit 1
```

## Expected Behavior
Switch "-e" should be expanded with the error log by default. Error-Logfile should be created and written to the specifed path. A "message" should also written to the error log at startup.
Variables in /usr/lib/icinga2/icinga2 should be set to avoid problems.

## Current Behavior
See above ... "-e" is empty

## Possible Solution
Uncomment all variables in /usr/lib/icinga2/icinga2

## Steps to Reproduce (for bugs)
1. Fresh and clean Debian 9.5
2. Install latest Icinga2-2.9.1 from https://www.icinga.com/docs/icinga2/latest/doc/02-getting-started/
```
apt-get -y install apt-transport-https

wget -O - https://packages.icinga.com/icinga.key | apt-key add -
echo 'deb https://packages.icinga.com/debian icinga-stretch main' >/etc/apt/sources.list.d/icinga.list
apt-get update
apt install icinga2
```
3. Restart Icinga2 and have a look in the process list
4. Uncomment ICINGA2_ERROR_LOG in /usr/lib/icinga2/icinga2 and restart Icinga2 again. Grep process again, Switch "-e" is expanded, but nor error log is created
5. create error log manually and restart icinga2
6. have a look in you error log, nothing is written

## Your Environment

Fresh Debian-9.5 installation with latest Icinga-2.9 packages from packages.icinga.com

**Comment by dnsmichi** [comment]
@lazyfrosch can you please have a short look into this?

@jschanz in terms of the Director kickstart script, please create an issue over at https://github.com/icinga/icingaweb2-module-director (as you already did now). We didn't know that such a script exists and reads "our" env ...

**Comment by Thomas-Gelf** [comment]
ping @lippserd

**Comment by lippserd** [comment]
@Thomas-Gelf We already talked about that it's best to not read the variables in the kickstart script because the icinga2 CLI commands are able to determine the correct paths, right?

**Comment by Thomas-Gelf** [comment]
@dnsmichi: can you help with this? How to write a script that runs the cli commands correctly on 2.7.x, 2.8.x and 2.9.x?

**Comment by dnsmichi** [comment]
Let's move the discussion into the Director project's space, this issue here is about to fix Debian sysvinit / systemd files with wrong variable sources. Find my thoughts here: https://github.com/Icinga/icingaweb2-module-director/issues/1585#issuecomment-410208222

**Comment by Thomas-Gelf** [comment]
@lippserd: as suggested by @dnsmichi I added some thoughts to [#1585](https://github.com/Icinga/icingaweb2-module-director/issues/1585), so the discussion here can focus on the env-related part of the issue.

**Comment by dnsmichi** [comment]
`-e` is populated correctly in recent releases, so I'm closing here.
