### ISSUE TITLE
MariaDB IDO troubles since updating to 2.9.1

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icinga2#6523]
Hi,

since having updated our Icinga2 installation to 2.9.1, I have noticed the following error message in our MariaDB server log:

```
2018-08-06 17:23:42 139868692899584 [Warning] Aborted connection 3783 to db: 'icinga2_ido' user: 'icinga2_ido' host: 'xxx' (Got an error reading communication packets)
```

The SQL query in question (connection 3783) is a "multi statement" consisting of 222 UPDATEs to the `icinga_servicestatus` table, followed by `COMMIT; BEGIN`. The query text is 120,532 bytes. The `max_allowed_packet`  parameter of the MariaDB server is set to the default value of 16 M.

If I execute the query manually (using the `source` command from within the mysql client), the transaction completes in the fraction of a second; however the IDO connection fails with the above error message.

Now this may or may not be related, but I've also noticed that our IDO database is not in sync with the Icinga2 configuration; for example some hosts are not present in the `icinga_hosts` table, thus breaking our SLA reporting for some customers.

I would appreciate any indication on how to further investigate this issue... I'd really love to stay on 2.9.1 for some of the fixes, but if it breaks our SLA reporting then it's back to 2.8.4 for us.

## Expected Behavior

IDO database should be kept in sync with Icinga configuration.

## Current Behavior

We noticed some hosts (probably other objects, too) not being present in `icinga_hosts` table even though they are defined in the active Icinga2 configuration.

## Possible Solution

?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`): 2.9.1
* Operating System and version: CentOS 7.5 x86_64
* Enabled features (`icinga2 feature list`): api checker command graphite ido-mysql mainlog notification syslog
* Icinga Web 2 version and modules (System - About): 2.6.0
* Config validation (`icinga2 daemon -C`): success!
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
How can one imagine the setup, is this a separate MariaDB server where you connect via tcp, or is that locally with localhost/unix sockets involved? Any insights on the network side, is the data transmitted (e.g. verify via tcpdump) and received by the server? While upgrading Icinga, were there any system/mariadb updates involved too?

Which version of MariaDB is running there?

**Comment by terra-nova** [comment]
Yum history tells me the current version of the MariaDB server package was installed on April 4th. Our problems with the IDO started at the 27th of July, when we updated Icinga2 to version 2.9.1

**Comment by terra-nova** [comment]
Ok, so it turns out the IDO database does have all the hosts defined in the Icinga2 configuration after all. It's just that the `alias` column used to hold the Icinga2 object name, and now stores the same value as the `display_name` column, e.g. the Icinga2 host object attribute of the same name. The Icinga2 object name has moved to the `icinga_objects` table... or something.

The error message `Got an error reading communication packets` continues to occur whenever the Icinga2 configuration is updated, though.

**Comment by dnsmichi** [comment]
> Ok, so it turns out the IDO database does have all the hosts defined in the Icinga2 configuration after all. It's just that the alias column used to hold the Icinga2 object name, and now stores the same value as the display_name column, e.g. the Icinga2 host object attribute of the same name. The Icinga2 object name has moved to the icinga_objects table... or something.

`alias` doesn't exist in Icinga 2. If the `display_name` is set, this is used for the `alias` column in the IDO database schema for compatiblity reasons. If `display_name` is empty, the host object name is used.

The defined host object name always is stored in the icinga_objects table, being `name1` in that case. That has been sitting there since the very beginning of this schema many years ago. 

Not sure what you've been using for those SQL queries, but the mentioned "changes" of yours are there since 2.0.

In terms of the communication packets error, I'd be interested in a tcpdump capture.

**Comment by Al2Klimov** [comment]
Hello @terra-nova and thank you for reporting!

Please could you provide an Icinga 2 configuration scenario or configuration change scenario we can reliably reproduce your issue with?

Best,
AK

**Comment by Al2Klimov** [comment]
Note: `max_allowed_packet` doesn't matter at all. In the 2nd worst case Icinga 2 will fire 1 query at once, in the worst case you get [prominent error messages](https://github.com/Icinga/icinga2/pull/6530#issuecomment-411357023).

**Comment by terra-nova** [comment]
@Al2Klimov Thanks for your willingness to investigate but unfortunately we had to downgrade our Icinga2 installation to 2.8.4 because of a incompatibility of 2.9.x with Icinga Director's mechanism for managing custom variables (see Director issues 1579, 1580, 1601, 1602).

Btw, after downgrading Icinga2 to 2.8.4 our IDO database's `icinga_hosts` table now looks like this (as it did before the update to 2.9.1):

```
> select h.host_id, h.alias, h.display_name from icinga_hosts h inner join icinga_objects o on (h.host_id=o.object_id and o.is_active<>0);
+---------+------------------------------------------------------+---------------------------------------+
| host_id | alias                                                | display_name                          |
+---------+------------------------------------------------------+---------------------------------------+
...
|    2123 | TEST-objectname                                      | TEST-displayname                      |
...
```

```
object host "TEST-objectname" {
   ...
   display_name = "TEST-displayname"
   ...
}
```

The MySQL error message also disappeared after the downgrade.

**Comment by Al2Klimov** [comment]
Hello @terra-nova,

While it's good that you've found a solution/downgrade for your problem, IMO you shouldn't have to downgrade – i.e. v2.9 has to just work. Please provide an (example) Icinga 2 configuration scenario or configuration change scenario we can reliably reproduce your issue with. (Preferably working OOTB inside a standard Docker container.)

Best,
AK

PS: Another user [has already solved](https://github.com/Icinga/icinga2/issues/6522#issuecomment-411417765) the Director's problem for themselves.

**Comment by terra-nova** [comment]
@Al2Klimov Yes, I agree with everything you said. But I do not have the time to convert all of our service sets to apply rules at the moment. Besides, I would want to wait and see how the whole Director/get_host()/get_service() saga plays out before jumping ship.

**Comment by dnsmichi** [comment]
@terra-nova 

I'm hoping you can re-test this with 2.9.2 or 2.10 once released, and collect a tcpdump with all the queries. Details e.g. here: https://blog.netways.de/2013/06/20/mysql-queries-mit-wireshark-analysieren/

Specifically I'm interested in the amount of specific query types, as well as how one of these queries communicate with the master (best the one which causes the error, if reproducible).

**Comment by dnsmichi** [comment]
@terra-nova Could you test any further? I'd like to know what possible cause may influence the packet sizes here.

**Comment by terra-nova** [comment]
@dnsmichi 

I have since updated our Icinga master to 2.10, and the error message has returned, as well. Unfortunately, it is kind of hard to debug the issue because the error does not happen all the time, or even at regular intervals.

I think it's more of a DB server issue, as well, because I get the same error message for some other applications (JasperReports, for example).

So I think this issue can be closed.
