### ISSUE TITLE
Object activation order in 2.9.x

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icinga2#6534]
I'm still trying to understand #6522, so I prepared a simple example to ask for clarification:

```
object Service "dummy" {
  host_name = "localhost"
  check_interval = get_host("localhost").check_interval
  /* ... */
}

object Service "dummy2" {
  host_name = "localhost"
  if (get_host("localhost").vars.env == "production") {
    import "production-service"
  } else {
    import "test-service"
  }
  /* ... */
}
```

Here is another one:
```
template Service "agent-service" {
  if (! host) {
    var host = get_host(host_name)
  }
  import "generic-service"
  command_endpoint = host.vars.endpoint_name
}

object Service "cpu" {
  host_name = "agent.example.com"
  import "agent-service"
}
```

Are they considered to be broken and not supported at all since 2.9? Should `get_host` then throw an error when being executed at parse time? Does this mean that there is no more way to configure single Services based on Host properties?

Thanks,
Thomas

**Comment by dnsmichi** [comment]
These scenarios were never supported by any Icinga 2 version. More details [here](https://github.com/Icinga/icinga2/issues/6522#issuecomment-411040943).

Object accessors have been built for runtime object access, as stated in the documentation.
https://www.icinga.com/docs/icinga2/latest/doc/08-advanced-topics/#access-object-attributes-at-runtime

It is unfortunate that this is available in the static object context, where their behaviour is undefined and can lead to unexpected behaviour as seen with the mentioned issue. I'll take a note for the docs to make this more explicit.

Cheers,
Michael
