### ISSUE TITLE
Icina2 load balance only master or Satellite

### ISSUE THREAD

**Issue by pulord** [Icinga/icinga2#6535]
I am a new icinga2 user, now i have seted a monitor cluster. use config sync mode。
now i need a load balance solution which any client disconnect and other client of same Satellite can excute command checker
i confused by  [High-Availability with Checks ](https://www.icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#high-availability-with-checks),  it is only load balance on master or Satellite?
how to use it on client node? any doc?

**Comment by dnsmichi** [comment]
Please ask these kind of questions on the [community channels](https://www.icinga.com/community/) and not on the GH issue tracker.
