### ISSUE TITLE
check_nscp_api: Query arguments are sorted on Url::Format()

### ISSUE THREAD

**Issue by jomakay** [Icinga/icinga2#6536]
Hello,

I'm trying to check a APC UPS (10.10.10.202) from a Windows host with Icinga2 and NSClient++, but running an external perl-script with check_nscp_api.exe doesn't work.

## Expected Behavior

Calling the external perl-script over check_nscp_api.exe:
```
check_nscp_api.exe --host 127.0.0.1 --port 8443 --password aabbccddusw --query check_snmp_generic_pl --arguments 10.10.10.202 "Load" "%" 80 90 1.3.6.1.4.1.318.1.1.1.4.2.3.0
```
should give something like:
```
OK - Current Value: 18% |'Load'=18%;80;90
``` 

The arguments of the external perl-script have a fixed order:
; ARG1: host address
; ARG2: label
; ARG3: unit
; ARG4: warning
; ARG5: critical
; ARG6: oid

## Current Behavior
```
check_nscp_api.exe --host 127.0.0.1 --port 8443 --password aabbccddusw --query check_snmp_generic_pl --arguments 10.10.10.202 "Load" "%" 80 90 1.3.6.1.4.1.318.1.1.1.4.2.3.0
check_snmp_generic_pl UNKNOWN - Non-numeric value found: snmpget: Unknown host (%) (No such file or directory)   | '1.3.6.1.4.1.318.1.1.1.4.2.3.0'=0;80;90
```
Other internal scripts work fine:
```
check_nscp_api.exe --host 127.0.0.1 --port 8443 --password aabbccddusw --query check_cpu --arguments show-all warn="load>80" crit="load>90"
check_cpu OK: 5m: 11%, 1m: 13%, 5s: 3% | 'total 5m'=11%;80;90 'total 1m'=13%;80;90 'total 5s'=3%;80;90
```

Test the perl script itself works fine:
```
C:\Progra~1\Perl64\bin\perl.exe check_snmp_generic.pl -N "-v 1 -c public" -H 10.10.10.202 -l "Load" -u "%" -w 80 -c 90 1.3.6.1.4.1.318.1.1.1.4.2.3.0
OK - Current Value: 18% | Load=18%;80;90;;
```

Test the external script in the nscp cli works fine:
```
C:\Program Files\NSClient++\nscp.exe test
...
check_snmp_generic_pl 10.10.10.202 Load % 80 90 1.3.6.1.4.1.318.1.1.1.4.2.3.0
D ext-script Command line: "C:\Progra~1\Perl64\bin\perl.exe" scripts\custom\check_snmp_generic.pl -N "-v 1 -c public" -H 10.10.10.202 -l Load -u % -w 80 -c 90 1.3.6.1.4.1.318.1.1.1.4.2.3.0
L        cli OK: OK - Current Value: 18%
L        cli  Performance data: 'Load'=18%;80;90
exit
```

Test the external Script over nrpe works fine:
```
check_nrpe.exe -H 127.0.0.1 -c check_snmp_generic_pl -a 10.10.10.202 Load % 80 90 1.3.6.1.4.1.318.1.1.1.4.2.3.0
OK - Current Value: 18% |'Load'=18%;80;90
```

But running external script with check_nscp_api.exe doesn't work:
```
check_nscp_api.exe --host 127.0.0.1 --port 8443 --password aabbccddusw --query check_snmp_generic_pl --arguments 10.10.10.202 "Load" "proz" 80 90 1.3.6.1.4.1.318.1.1.1.4.2.3.0
check_snmp_generic_pl Value "Load" invalid for option c (real number expected) |
```

After trying random arguments for host, label, unit, oid, I think, that all arguments sorted by their value in alphanumeric order and then sent to check_nscp_api.exe.

So the line above is transformed to:
```
check_nscp_api.exe --host 127.0.0.1 --port 8443 --password aabbccddusw --query check_snmp_generic_pl 10.10.10.202 1.3.6.1.4.1.318.1.1.1.4.2.3.0 80 90 Load proz
```
And in this way, the value for "critical" $ARG5$ is "Load", not "90" and no longer a "real number"

I tested some fantasy-arguments:
```
check_nscp_api.exe --host 127.0.0.1 --port 8443 --password aabbccddusw --query check_snmp_generic_pl --arguments 1 2 3 4 5 6
check_nscp_api.exe --host 127.0.0.1 --port 8443 --password aabbccddusw --query check_snmp_generic_pl --arguments 4 1 5 6 2 3
```
The error is always the same, so there must be some kind of presorting arguments:
```
check_snmp_generic_pl UNKNOWN - Non-numeric value found: snmp_build: unknown failuresnmpget: Error building ASN.1 representation (Can't build OID for variable)   | '2'=3;4;5
```
My external script needs a fixed order of arguments, so this must not happen

Have I done something wrong or is this a bug?

## My Environment

Following Configuration:
nsclient.ini:
```
[/settings/default]
password = aabbccddusw
allowed hosts = 127.0.0.1,::1

[/settings/NRPE/server]
ssl options = no-sslv2,no-sslv3
insecure = false
allow arguments = true
allow nasty characters = true

[/settings/NRPE/client]
insecure = false

[/modules]
CheckExternalScripts = enabled
CheckHelpers = 1
CheckNSCP = 1
CheckDisk = 1
CheckSystem = 1
CheckEventLog = 1
NSCAClient = 1
WEBSErver = 1
NRPEServer = enabled
CheckNet = 1
 
[/settings/external scripts]
allow arguments = true

[/settings/external scripts/wrapped scripts]
check_snmp_generic_pl=scripts\custom\check_snmp_generic.pl -N "-v 1 -c public" -H $ARG1$ -l $ARG2$ -u $ARG3$ -w $ARG4$ -c $ARG5$ $ARG6$
; ARG1: host address
; ARG2: label
; ARG3: unit
; ARG4: warning
; ARG5: critical
; ARG6: oid

[/settings/external scripts/wrappings]
; Perl WRAPPING -
pl = "C:\Progra~1\Perl64\bin\perl.exe" %SCRIPT% %ARGS%
```

C:\Program Files\ICINGA2\sbin>icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.8.4-773-g79878ea)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: C:\Program Files\ICINGA2\
  Sysconf directory: C:\ProgramData\icinga2\etc
  Run directory: C:\ProgramData\icinga2\var\run
  Local state directory: C:\ProgramData\icinga2\var
  Package data directory: C:\Program Files\ICINGA2\\share\icinga2
  State path: C:\ProgramData\icinga2\var/lib/icinga2/icinga2.state
  Modified attributes path: C:\ProgramData\icinga2\var/lib/icinga2/modified-attributes.conf
  Objects path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.debug
  Vars path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.vars
  PID path: C:\ProgramData\icinga2\var\run/icinga2/icinga2.pid

System information:
  Platform: Windows
  Platform version: 8.1 or greater (Server)
  Kernel: Windows
  Kernel version: 6.2
  Architecture: x86_64

Build information:
  Compiler: MSVC 19.0.24215.1
  Build host: ICINGA-BUILD-WI

C:\Program Files\ICINGA2\sbin>icinga2 feature list
Disabled features: command compatlog debuglog elasticsearch gelf graphite ido-mysql ido-pgsql influxdb livestatus notification opent
sdb perfdata statusdata
Enabled features: api checker mainlog

C:\Program Files\ICINGA2\sbin>icinga2 daemon -C
[2018-08-09 10:10:57 +0200] information/cli: Icinga application loader (version: v2.8.4-773-g79878ea)
[2018-08-09 10:10:57 +0200] information/cli: Loading configuration file(s).
[2018-08-09 10:10:58 +0200] information/ConfigItem: Committing config item(s).
[2018-08-09 10:10:58 +0200] information/ApiListener: My API identity: ____________
[2018-08-09 10:10:59 +0200] information/ConfigItem: Instantiated 225 CheckCommands.
[2018-08-09 10:10:59 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2018-08-09 10:10:59 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2018-08-09 10:10:59 +0200] information/ConfigItem: Instantiated 4 Zones.
[2018-08-09 10:10:59 +0200] information/ConfigItem: Instantiated 6 Services.
[2018-08-09 10:10:59 +0200] information/ConfigItem: Instantiated 2 Endpoints.
[2018-08-09 10:10:59 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2018-08-09 10:10:59 +0200] information/ConfigItem: Instantiated 2 Hosts.
[2018-08-09 10:10:59 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2018-08-09 10:10:59 +0200] information/ScriptGlobal: Dumping variables to file 'C:\ProgramData\icinga2\var/cache/icinga2/icinga2.va
rs'
[2018-08-09 10:10:59 +0200] information/cli: Finished validating the configuration file(s).

C:\Program Files\NSClient++>nscp.exe --version
NSClient++, Version: 0.5.0.62 2016-09-14, Platform: x64

C:\perl -version
This is perl 5, version 26, subversion 1 (v5.26.1) built for MSWin32-x64-multi-thread

Thank you.

**Comment by dnsmichi** [comment]
I'm not yet convinced that this really is a bug. The discussion is still going on.

https://monitoring-portal.org/t/problem-with-check-nscp-api-exe-on-windows/3642

**Comment by Crunsher** [comment]
The plugin does not reorder arguments, they are appended to the URL as `?10.10.10.202&Load&%25&80&90&1.3.6.1.4.1.318.1.1.1.4.2.3.0`

See if you can get the plugin to work using the NSCP Api directly.

**Comment by dnsmichi** [comment]
I've changed some bits in the code with lazy debugging, and can now see the problem in Url::ParseQuery().

```
diff --git a/lib/remote/url.cpp b/lib/remote/url.cpp
index f6c84ece1..13fcab561 100644
--- a/lib/remote/url.cpp
+++ b/lib/remote/url.cpp
@@ -23,6 +23,7 @@
 #include "remote/url.hpp"
 #include "remote/url-characters.hpp"
 #include <boost/tokenizer.hpp>
+#include <iostream>
 
 using namespace icinga;
 
@@ -381,6 +382,8 @@ bool Url::ParseQuery(const String& query)
        boost::tokenizer<boost::char_separator<char> > tokens(queryStr, sep);
 
        for (const String& token : tokens) {
+               std::cout << "Token: " << token << "\n";
+
                size_t pHelper = token.Find("=");
 
                if (pHelper == 0)
@@ -418,6 +421,14 @@ bool Url::ParseQuery(const String& query)
                        m_Query[key].emplace_back(std::move(value));
        }
 
+       for (auto v : m_Query) {
+               std::cout << "Key: " << v.first;
+
+               for (auto k : v.second) {
+                       std::cout << " Value: " << k << "\n";
+               }
+       }
+
        return true;
 }

diff --git a/plugins/check_nscp_api.cpp b/plugins/check_nscp_api.cpp
index 1fd12209e..346030fa3 100644
--- a/plugins/check_nscp_api.cpp
+++ b/plugins/check_nscp_api.cpp
@@ -77,6 +77,23 @@ static void ResultHttpCompletionCallback(const HttpRequest& request, HttpRespons
 static Dictionary::Ptr QueryEndpoint(const String& host, const String& port, const String& password,
        const String& endpoint)
 {
+       Url::Ptr url;
+
+       try {
+               // Url() will call Utillity::UnescapeString() which will thrown an exception if it finds a lonely %
+               url = new Url(endpoint);
+               url->SetArrayFormatUseBrackets(false);
+
+               if (l_Debug) {
+                       std::cout << "Sending request to 'https://" << host << ":" << port << url->Format(false, false) << "'\n";
+               }
+       }
+       catch (const std::exception& ex) {
+               // Exceptions should only happen in extreme edge cases we can't recover from
+               std::cout << "Caught exception: " << DiagnosticInformation(ex, false) << '\n';
+               return Dictionary::Ptr();
+       }
+
        HttpClientConnection::Ptr m_Connection = new HttpClientConnection(host, port, true);
 
        try {
@@ -87,15 +104,11 @@ static Dictionary::Ptr QueryEndpoint(const String& host, const String& port, con
                std::shared_ptr<HttpRequest> req = m_Connection->NewRequest();
                req->RequestMethod = "GET";
 
-               // Url() will call Utillity::UnescapeString() which will thrown an exception if it finds a lonely %
-               req->RequestUrl = new Url(endpoint);
-
-               // NSClient++ uses `time=1m&time=5m` instead of `time[]=1m&time[]=5m`
-               req->RequestUrl->SetArrayFormatUseBrackets(false);
+               req->RequestUrl = url;
 
                req->AddHeader("password", password);
                if (l_Debug) {
-                       std::cout << "Sending request to 'https://" << host << ":" << port << req->RequestUrl->Format(false, false) << "'\n"
+                       std::cout << "Connected and now sending request to 'https://" << host << ":" << port << req->RequestUrl->Format(false, false) << "'\n"
                                << "Headers: " << JsonEncode(req->Headers) << "\n";
                }
 
@@ -310,6 +323,10 @@ int main(int argc, char **argv)
                }
        }
 
+       if (l_Debug) {
+               std::cout << "Querying endpoint '" << endpoint << "'\n";
+       }
+
        // This needs to happen for HttpRequest to work
        Application::InitializeBase();
 
```

```
michi@imagine ~/coding/icinga/icinga2 ((v2.9.1)) $ debug/Bin/Debug/check_nscp_api -H localhost --password icinga --query check_cpu --debug --arguments 4 5 6 3 2 1
Querying endpoint '/query/check_cpu?4&5&6&3&2&1&'
[2018-08-09 19:24:57 +0200] debug/ThreadPool: Spawning worker thread.
[2018-08-09 19:24:57 +0200] debug/ThreadPool: Spawning worker thread.
[2018-08-09 19:24:57 +0200] debug/ThreadPool: Spawning worker thread.
[2018-08-09 19:24:57 +0200] debug/ThreadPool: Spawning worker thread.
Token: 4
Token: 5
Token: 6
Token: 3
Token: 2
Token: 1
Key: 1 Value: 
Key: 2 Value: 
Key: 3 Value: 
Key: 4 Value: 
Key: 5 Value: 
Key: 6 Value: 
Sending request to 'https://localhost:8443/query/check_cpu?1&2&3&4&5&6'
[2018-08-09 19:24:57 +0200] critical/TcpSocket: Invalid socket: Connection refused
Caught exception: Error: std::exception

UNKNOWN: No data received.

```

```
                auto it = m_Query.find(key);

                if (it == m_Query.end()) {
                        m_Query[key] = std::vector<String> { std::move(value) };
                } else
                        m_Query[key].emplace_back(std::move(value));
```

doesn't respect the order, but will always insert based on the key sorted order.

`std::map<String, std::vector<String> > m_Query;` always provides the sorted query params, no matter what you do.

I'll leave that coding exercise and possible solutions to a first or second time contributor, it should be a small fix.
