### ISSUE TITLE
Feature Request: Apply 'variable' to Service/Host

### ISSUE THREAD

**Issue by Napsty** [Icinga/icinga2#6543]
I just came across a scenario, where certain services need an additional service variable. The variable can be added easily in a "Apply Service" rule. However for manually defined Service checks, this requires manual editing. 

The main question before I go into details is: **Is it possible to create an "Apply variable to" rule?** . The question goes of course to the developers behind the apply rule functions.

Here's a practical use case. Given you have several hosts and services already defined. Some services are applied using "Apply Service" rules. But here we have a special check, "hardcoded" into a config file:

```
object Service "MongoDB Backup" {
  import "service-2h-normal"
  host_name = "mongo001"
  check_command = "nrpe"
  vars.nrpe_command = "check_statusfile"
  vars.nrpe_arguments = [ "/usr/lib/nagios/plugins/backup.status", "OK" ]
}
```

Now I want to add a variable "group" to this service:

```
object Service "MongoDB Backup" {
  import "service-2h-normal"
  host_name = "mongo001"
  vars.group = "Backup"
  check_command = "nrpe"
  vars.nrpe_command = "check_statusfile"
  vars.nrpe_arguments = [ "/usr/lib/nagios/plugins/backup.status", "OK" ]
}
```

Instead of adding `vars.group = "Backup"` manually into each service checking a backup status, it would be handy to use an apply rule like this (pretty similar to "Apply Notification"):

```
apply Variable "group-var-backup" to Service {
  vars.group = "Backup"
  assign where match("*Backup", service.name)
}
```

**Comment by gunnarbeutner** [comment]
This is pretty much what #6030 is about. 😊

**Comment by Napsty** [comment]
Pretty much looks like it. And I spent 10mins to search through the issues and couldn't find (from the issue title) anything which would match my FR. 
Well - cool. Looking forward to this. Closing this in favor of https://github.com/Icinga/icinga2/pull/6030.

**Comment by gunnarbeutner** [comment]
Feel free to submit a comment there anyway so that @dnsmichi and others see that it should get merged. 😁
