### ISSUE TITLE
Check_DHCP more information (feature Request)

### ISSUE THREAD

**Issue by syswombat** [Icinga/icinga2#6545]
Hello
doing a 
> ./check_dhcp
 
you will get something like 
> OK: Received 1 DHCPOFFER(s), max lease time = 3600 sec.

doing a 
> ./check_dhcp -i ens18 -v 

you get much mor Results so a nice default output would be something like

> OK: Received 1 DHCPOFFER(s), max lease time = 3600 sec.
> offer from server @ 10.147.42.7 of IP address 10.147.42.196

to add the Hostname of 10.147.42.7 would more Perfect.
> offer from server @ 10.147.42.7 (Hostname) of IP address 10.147.42.196

have a nice day
vinc

**Comment by mcktr** [comment]
The plugin _check_dhcp_ is not part of the Icinga 2 project. Icinga 2 executs a check plugin with given parameter/attributes and processes the result (output and performance data). 

Please fill up your feature request in the corresponding project, for _check_dhcp_ this is [The Monitoring Plugins Project](https://www.monitoring-plugins.org/) (or on GitHub: [monitoring-plugins](https://github.com/monitoring-plugins/monitoring-plugins)).

Kind regards
Michael
