### ISSUE TITLE
Feature request: specify ssl-version with NRPE CheckCommand

### ISSUE THREAD

**Issue by cherdt** [Icinga/icinga2#6552]
## Expected Behavior

I would like to pass a variable to NRPE that would set/restrict the TLS version, e.g.

```
template Service "nrpe-service" {
    import "generic-service"
    check_command = "nrpe"
    vars.nrpe_ssl-version = "TLSv1.2+"
}
```

## Current Behavior

There is not currently a way to set the SSL/TLS version.

## Possible Solution

```
"-S" = {
    value = "$nrpe_ssl-version$"
    description = "Use this to set which SSL/TLS version to use"
}
```

(In the above, I'm not sure what would happen if no `nrpe_ssl-version` was specified.)

## Context

Recent versions of check_nrpe include an option to restrict which SSL/TLS versions are used:

`-S, --ssl-version=VERSION`

This option is not currently supported by the current nrpe CheckCommand object defined in `itl/command-plugins.conf`

## Your Environment

* Version used (`icinga2 --version`): r2.9.1-1
* Operating System and version: CentOS 7.5.1804
* Enabled features (`icinga2 feature list`): checker command graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.6.1, loaded modules: monitoring, setup
* Config validation (`icinga2 daemon -C`): checked

**Comment by cherdt** [comment]
It looks like dashes are not allowed in Icinga2 variable names, so the name would be `nrpe_ssl_version` instead.

In my tests this seems to work.

**Comment by Crunsher** [comment]
Which version of the NRPE plugin are you using? Does the `-S` argument work for newer/older and supported versions the same?

Other than that feel free to open a PR!

**Comment by dnsmichi** [comment]
AFAIK that was added in their v3 release. The problem I do see is that many options are not backwards compatible, or sometimes do not exist in the binary either. I'd say users are better off with creating their own CheckCommand definitions for NRPE and only use the ITL one as a basis.

```
object CheckCommand "my-nrpe-v3" {
  import "nrpe"

  arguments += {
     "schnurzi" = "$puh$"
  }
}
```

**Comment by cherdt** [comment]
I am using NRPE 3.2.1. Correct, this is available starting in the NRPE 3.x releases.

I understand the concern about maintaining backwards compatibility, although the current command definition assumes NRPE 3.x:

`vars.nrpe_version_2 = false`

**Comment by Al2Klimov** [comment]
@JochenFriedrich, you have created a PR which addresses this one. please could you leave an arbitrary comment here so I can assign you?

**Comment by JochenFriedrich** [comment]
PR has been submitted to address this feature request
