### ISSUE TITLE
api setup fails if conf.d is missing

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga2#6553]
Running the api setup fails in case `/etc/icinga2/conf.d` is missing.

> information/cli: Adding new ApiUser 'root' in '/etc/icinga2/conf.d/api-users.conf'.
> critical/Application: Error: Function call 'mkstemp' for file '/etc/icinga2/conf.d/api-users.conf.XXXXXX' failed with error code 2, 'No such file or directory'

## Expected Behavior
`conf.d` is automatically created.

## Current Behavior
It's not.

## Possible Solution
It is.

## Steps to Reproduce (for bugs)
- Have a config directory without `conf.d`
- Run the api setup

## Your Environment
* Version used (`icinga2 --version`): v2.9.1-90-g060a1eb
* Operating System and version: Ubuntu 16.04

**Comment by Crunsher** [comment]
I'm not sure recreating a directory a user deleted makes sense in this case. Logging an error and continuing/properly terminating is something I'd expect to see.

**Comment by N-o-X** [comment]
The `conf.d` directory should have been created during installation. Did you delete it manually?
I don't think recreating that directory during `api setup` would make sense.

**Comment by nilmerg** [comment]
Yes, has been left out intentionally. Just wondered about this since previously it didn't complain.

**Comment by dnsmichi** [comment]
I would simply call MkDirP() since the wizards are what the user called.
