### ISSUE TITLE
Master disconnects during signing process

### ISSUE THREAD

**Issue by bobapple** [Icinga/icinga2#6566]
During the signing process, the master closes the connection to the agent. This issue may reference to https://github.com/Icinga/icinga2/issues/6154

```
[2018-08-17 11:38:33 +0200] notice/ApiListener: New JSON-RPC client
[2018-08-17 11:38:33 +0200] notice/ApiListener: Ignoring anonymous JSON-RPC connection. Max connections exceeded.
[2018-08-17 11:38:33 +0200] warning/JsonRpcConnection: API client disconnected for identity 'example-1.com'
Context:
        (0) Handling new API client connection

[2018-08-17 11:38:33 +0200] warning/JsonRpcConnection: API client disconnected for identity 'example-1.com'
Context:
        (0) Handling new API client connection

...

[2018-08-17 11:38:45 +0200] notice/ApiListener: New JSON-RPC client
[2018-08-17 11:38:45 +0200] notice/ApiListener: Ignoring anonymous JSON-RPC connection. Max connections exceeded.
[2018-08-17 11:38:45 +0200] warning/JsonRpcConnection: API client disconnected for identity 'example-1.com'
Context:
        (0) Handling new API client connection

[2018-08-17 11:38:45 +0200] warning/JsonRpcConnection: API client disconnected for identity 'example-1.com'
Context:
        (0) Handling new API client connection

[2018-08-17 11:38:45 +0200] critical/SocketEvents: Exception thrown in socket I/O handler:
Error: Tried to read/write from a closed socket.

        (0) icinga2: icinga::SocketEventEngineEpoll::ChangeEvents(icinga::SocketEvents*, int) (+0x174) [0x772d04]
        (1) icinga2: icinga::TlsStream::OnEvent(int) (+0x139) [0xa81679]
        (2) icinga2: icinga::SocketEventEngineEpoll::ThreadProc(int) (+0x3d3) [0x806013]
        (3) libstdc++.so.6: <unknown function> (+0xb52a0) [0x7efd282c62a0]
        (4) libpthread.so.0: <unknown function> (+0x7dc5) [0x7efd27ae4dc5]
        (5) libc.so.6: clone (+0x6d) [0x7efd2781373d]
```

## Your Environment
* Version used (`icinga2 --version`): v2.9.1

refs NT: #561439

**Comment by nihuijun** [comment]
@bobapple 
Hi 
 I also met the same issue, but I run icinga2 as a satellite in the docker container, if the number of  my icinga2 client which connect to the same satellite reach to 520, then the satellite would throw out "Ignoring anonymous JSON-RPC connection. Max connections exceeded."

Now I'm not sure that it's the limitation of icinga2 or docker.
Can you share your comments? Thanks.

**Comment by bobapple** [comment]
@nihuijun we're currently still investigating the problem. Since we're seeing the issue in non-docker environment as well I assume it's an Icinga 2 problem. I would appreciate it if you could share logs or anything else that helps us reproduce this behaviour.

**Comment by dnsmichi** [comment]
Can only happen if there are multiple pki requests simultaneously, e.g. when an Ansible run installs multiple clients at once. Currently the limit for anonymous connections is hardcoded to 25.

We could implement a configuration attribute for the ApiListener object which allows to specify this limit, and set it to a default value of say 100. With a configuration option, this better qualifies for 2.10, what do you think @bobapple ?

**Comment by dnsmichi** [comment]
This is a possible candidate for 2.10 with configuration attributes involved. For better tracking, I'll leave this on 2.9.2 for now.

**Comment by dnsmichi** [comment]
First tests from the customer ticket look promising.

**Comment by dnsmichi** [comment]
Moving to 2.10 now, since the fix involves a new configuration option plus upgrading docs.

**Comment by dnsmichi** [comment]
Tests have been good so far, closing this for 2.10.
