### ISSUE TITLE
INSTALL.md ERROR

### ISSUE THREAD

**Issue by maxswjeon** [Icinga/icinga2#6582]
INSTALL.md has a wrong content

## Expected Behavior

Compiling icinga2, CMake Variable `PostgreSQL_LIBRARY_DIR` should be existing and reading variable as PATH

## Current Behavior

No such CMake Variable Named `PostgreSQL_LIBRARY_DIR`. Instead, there is a CMake Variable named `PostgreSQL_LIBRARY`, typed FILEPATH. If you set the variable like /usr/local/pgsql/lib, CMake tries to link the directory, not libpq.so file

## Possible Solution

1. Edit [INSTALL.md](INSTALL.md)  
 Edit [INSTALL.md](INSTALL.md). Change `PostgreSQL_LIBRARY_DIR` to `PostgreSQL_LIBRARY` and tell users to set their variables to libpq.so

2. Edit CMake Rules
 Edit CMake Rules to obay [INSTALL.md](INSTALL.md)

## Steps to Reproduce (for bugs)

1. Download Source. From source root, make `release` directory and go to there. (as [INSTALL.md](INSTALL.md) says)
2. run `cmake .. -DICINGA2_WITH_MYSQL=OFF -DPostgreSQL_INCLUDE_DIR=/usr/local/pgsql/include -DPostgreSQL_LIBRARY_DIR=/usr/local/pgsql/lib` from `release` directory
3. Get an Error
```
-- Could NOT find PostgreSQL (missing:  PostgreSQL_LIBRARY)
CMake Error at lib/CMakeLists.txt:55 (message):
  You have selected PostgreSQL support, but PostgreSQL could not be found.
  You can disable the PostgreSQL IDO module using -DICINGA2_WITH_PGSQL=OFF.
```
4. remove CMakeCache.txt by `rm CMakeCache.txt`
5. Try to run `cmake .. -DICINGA2_WITH_MYSQL=OFF -DPostgreSQL_INCLUDE_DIR=/usr/local/pgsql/include -DPostgreSQL_LIBRARY=/usr/local/pgsql/lib` from `release` directory
6. Configure Success! (It isn't, actually) run `make -C release` from Source root directory
7. Get a ld error
```
/usr/bin/ld: cannot find -lpq
```
8. Fail to Build, Google Hours, no solution, check CMakeCache.txt, Find something Interesting  
Hey, `PostgreSQL_LIBRARY` Variable Gets an file!
9. remove CMakeCache.txt by `rm CMakeCache.txt`
10. run `cmake .. -DICINGA2_WITH_MYSQL=OFF -DPostgreSQL_INCLUDE_DIR=/usr/local/pgsql/include -DPostgreSQL_LIBRARY=/usr/local/pgsql/lib/libpq.so.5.10` from `release` directory

## Context

I lost my several hours building this.. Compiling because RPi Repo isn't there.  

## Your Environment

* Version used (`icinga2 --version`):
Problem in Installation, No version with that command. However, I was trying with v2.9.1 from https://github.com/Icinga/icinga2/releases  

* Operating System and version:
`cat /etc/os-release`
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

`lsb_release -a`
```
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
```

`hostnamectl`
```
   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: 516ee9fc09204f46891ef1f18fda841f
           Boot ID: 76319d3c1f9248c1873bf3201c312e4a
  Operating System: Raspbian GNU/Linux 9 (stretch)
            Kernel: Linux 4.14.62-v7+
      Architecture: arm
```

* Enabled features (`icinga2 feature list`):
Nothing. Problem on Install.

* Icinga Web 2 version and modules (System - About):
Nothing. Problem on Install.

* Config validation (`icinga2 daemon -C`):
Nothing. Problem on Install.

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
Nope. Not my problem.

**Comment by dnsmichi** [comment]
Thanks for your finding :)
