### ISSUE TITLE
TasksMax not supported by old systemd versions

### ISSUE THREAD

**Issue by Hustokrutor** [Icinga/icinga2#6587]
Hello I have got a problem with icinga2 and icingaweb2 

Icinga2 is not responding and failed to strat. 
There is a log from icinga2. 

> ● icinga2.service - Icinga host/service/network monitoring system
>    Loaded: loaded (/lib/systemd/system/icinga2.service; enabled)
>   Drop-In: /etc/systemd/system/icinga2.service.d
>            └─limits.conf
>    Active: failed (Result: exit-code) since Mon 2018-09-03 16:25:34 CEST; 46min ago
>  Main PID: 1562 (code=exited, status=203/EXEC)
> 
> Sep 03 16:25:34 fejt-vxp systemd[1]: Started Icinga host/service/network monitoring system.
> Sep 03 16:25:34 fejt-vxp systemd[1]: icinga2.service: main process exited, code=exited, status=203/EXEC
> Sep 03 16:25:34 fejt-vxp systemd[1]: Unit icinga2.service entered failed state.
> Sep 03 16:33:21 fejt-vxp systemd[1]: [/etc/systemd/system/icinga2.service.d/limits.conf:6] Unknown lvalue 'TasksMax' in section 'Service'
>  back

There is a log from icingaweb2:

> ● icingaweb2.service
>    Loaded: not-found (Reason: No such file or directory)
>    Active: inactive (dead)

This is not once problem which i have got. When i have wrote some other commands as `systemctl start icinga2`, `systemctl reset icinga2`, `icinga2 feature list` , `/etc/init.d/apache2 start`,` icinga2 --version ` but without action. 

## Current Behavior
I have got a the right package with icinga2, icingaweb2 for debian8 Jesiie
This problem has started when i change password on /etc/icinga2/features-available/ido-mysql.conf
I tested on icingaweb2
Other application as Apache2, Mysql are ready, database is created. 

## Steps to Reproduce (for bugs)
1. I have wrote systemctl start icinga2   (without response)
2. I have wrote systemctl ststus icinga2  (this log is above)
3. systemctl reset icinga2   not help 
4.

## Context
If icinga2 is not ready, so other app as icingaweb2 not ready too.

## Your Environment
* Version used icinga2  (2.9.1-1.stretch) :
* Operating System and version: Linux 3.16.0-6-686-pae (i686), Debian 3.16.57-2 
  Distribution: Debian GNU/Linux 8.11
* Enabled features (`icinga2 feature list`): command not found (not respond)
* Icinga Web 2 version and modules (System - About):

> ● icingaweb2.service
>    Loaded: not-found (Reason: No such file or directory)
>    Active: inactive (dead)
> 

* Config validation (`icinga2 daemon -C`): command not found (not respond)

Thank you

**Comment by dnsmichi** [comment]
`Sep 03 16:33:21 fejt-vxp systemd[1]: [/etc/systemd/system/icinga2.service.d/limits.conf:6] Unknown lvalue 'TasksMax' in section 'Service'`

looks suspicious.

**Comment by Hustokrutor** [comment]
This is limit.conf

> # Icinga 2 sets some default values to extend OS defaults
> #
> # Please refer to our troubleshooting documentations for details
> # and reasons on these values.
> [Service]
> TasksMax=infinity
> 
> # May also cause problems, uncomment if you have any
> #LimitNPROC=62883

**Comment by Hustokrutor** [comment]
This is a limits.conf

```
# Icinga 2 sets some default values to extend OS defaults
#
# Please refer to our troubleshooting documentations for details
# and reasons on these values.
[Service]
TasksMax=infinity

# May also cause problems, uncomment if you have any
#LimitNPROC=62883
```

**Comment by Crunsher** [comment]
Googling lead me to https://github.com/ceph/ceph/pull/11133 which says `TasksMax` was introduced with systemd 226 - which is [too recent for jessie](https://packages.debian.org/jessie/systemd).

We should move this issue into the packaging repo.

**Comment by dnsmichi** [comment]
Ok, I see it. 

```
Version used icinga2 (2.9.1-1.stretch) :
Operating System and version: Linux 3.16.0-6-686-pae (i686), Debian 3.16.57-2
Distribution: Debian GNU/Linux 8.11
```

The stretch packages are installed on jessie (I'm wondering if that's even possible). Therefore you'll get the custom limits.conf but jessie's systemd cannot read it.

You'll have to fix your installation and use the proper repositories. I strongly recommend to purge the icinga2* packages, remove the stretch repository, add the jessie repository and install the packages again.
