### ISSUE TITLE
Implement and document a defined commit order for configuration objects

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#6589]
This sources from #6568.

Instead of looping through objects and config types and going the dependency route, we should commit configuration objects in a defined order, e.g. hosts before services, etc.

This idea follows the activation_priority we've implemented in #6270. 

In addition to this patch, we should document this behaviour in 2 ways:

- technical concepts where the config compiler is described
- a simple example for 1) a working get_host() example 2) a non-working get_service() example in apply rules, both with explanations on why this works and why it does not.

**Comment by Crunsher** [comment]
These are our current object dependencies, modeled after `load_after` from the .ti files
![icinga-graph](https://user-images.githubusercontent.com/4000359/45093753-aed08500-b119-11e8-8bc9-cc9ad205be40.png)

**Comment by dnsmichi** [comment]
I'm moving this into 2.11.
