### ISSUE TITLE
dns_check commandline options differ from icinga-director configuration

### ISSUE THREAD

**Issue by BerndWi** [Icinga/icinga2#6604]
The preview of the dns command (which maps to the check_dns script) in the icinga-director shows different commandline arguments from the actual script in the filesystem.

We use Icinga on a Debian 8 system.

Our Icinga2 shows the configuration as seen in the current git:
https://github.com/Icinga/icinga2/blob/master/itl/command-plugins.conf#L2013

The check_dns script is the following version:
/usr/lib/nagios/plugins/check_dns --version
check_dns v2.1.1 (monitoring-plugins 2.1.1)

The check_dns script does not offer the switch to choose which record type you want to query and this is quite useful. Icinga2 shows the "-q" switch but the script does not offer this switch, so my configured checks fail because of a syntax error.

Where do I get the check_dns script matching to the configuration in Icinga?

icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

### Further Information

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 8 (jessie)
  Kernel: Linux
  Kernel version: 3.16.0-4-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.9.2

**Comment by cstegm** [comment]
Hi, try dig/check_dig with the -T Argument for such DNS queries. I guess -q is only available in the nagios plugins check_dns.

**Comment by mcktr** [comment]
As you said the `-q` parameter is not supported by check_dns. The default value for `dns_query_type` should be removed with #5384 which was shipped with v2.7.0.

As long as you do not explicitly set a value for `dns_query_type` you should be fine. Can you provide a rendered configuration example for the check_dns CheckCommand from Director?

**Comment by BerndWi** [comment]
Hi,
@cstegm thank you for the hint. I checked out the dig command and it works fine!

@mcktr yes, it works when I do not set the -q parameter. The problem is that I want to use it, but it is not supported by the actual check_dns script that is doing the tests.

The configuration preview of the check_dns command in the Icinga Director looks like this:

```
object CheckCommand "dns" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_dns" ]
    timeout = 1m
    arguments += {
        "-A" = {
            description = "Optionally expect the DNS server to be authoritative for the lookup"
            set_if = "$dns_authoritative$"
        }
        "-H" = {
            description = "The name or address you want to query."
            value = "$dns_lookup$"
        }
        "-a" = {
            description = "Optional ip address or host you expect the DNS server to return. Host must end with a dot (.). This option can be repeated multiple times (Returns OK if any value match). If multiple addresses are returned at once, you have to match the whole string of addresses separated with commas (sorted alphabetically)."
            value = "$dns_expected_answers$"
        }
        "-c" = {
            description = "Return critical if elapsed time exceeds value."
            value = "$dns_ctime$"
        }
        "-n" = {
            description = "Optionally accept cname responses as a valid result to a query. The default is to ignore cname responses as part of the result"
            set_if = "$dns_accept_cname$"
        }
        "-q" = {
            description = "Optional DNS record query type where TYPE =(A, AAAA, SRV, TXT, MX, ANY). The default query type is 'A' (IPv4 host entry)"
            value = "$dns_query_type$"
        }
        "-s" = {
            description = "Optional DNS server you want to use for the lookup."
            value = "$dns_server$"
        }
        "-t" = {
            description = "Seconds before connection times out. Defaults to 10."
            value = "$dns_timeout$"
        }
        "-w" = {
            description = "Return warning if elapsed time exceeds value."
            value = "$dns_wtime$"
        }
    }
    vars.check_address = {
        arguments = [  ]
        deprecated = false
        name = "<anonymous>"
        side_effect_free = false
        type = "Function"
    }
    vars.check_ipv4 = false
    vars.check_ipv6 = false
    vars.dns_lookup = "$host.name$"
    vars.dns_timeout = 10
}
```

**Comment by dnsmichi** [comment]
That's just a preview, the Director cannot know about the actual plugin parameters. Even the ITL CheckCommand objects may not be 100% correct about what the plugin actually supports.

I'd suggest moving the best practice discussion into the forums, since the missing parameter has been explained by @mcktr
