### ISSUE TITLE
Master/client versions interoperability

### ISSUE THREAD

**Issue by nE0sIghT** [Icinga/icinga2#6612]
This is not bug report, but question.

Does different versions of Icinga2 supported in master/client configurations? Eg could I use version 2.8 for master and version 2.6 for clients?

**Comment by ekeih** [comment]
Hi, https://monitoring-portal.org/t/distributed-icinga2-with-different-versions-possible/2085 is the same question. The monitoring portal is a better place for questions.

**Comment by dnsmichi** [comment]
Thanks Max.

**Comment by nE0sIghT** [comment]
@ekeih

The link you provided doesn't contains answer for my question. Someone just said that "it is works for me now".

As you said - it's not covered by documentation and I want to hear about "developers policy" for supporting Icinga distributed configuration with different versions.

Also this issue may be treated as request to include this information in documentation.

@dnsmichi 
Could you please clarify if it's supported configuration?

**Comment by ekeih** [comment]
I agree that some kind of version-compatibility documentation would be useful.

**Comment by dnsmichi** [comment]
Feel free to send a PR, I thought it was a question which is normally best covered by the community channels.

**Comment by ekeih** [comment]
I guess neither @nE0sIghT nor me can provide such PR as we both do not know the official position to the question "Which versions work together and which versions will break your cluster?".
If you or someone else could provide this information I would be happy to send a PR for the docs. :)

**Comment by dnsmichi** [comment]
During compilation for some TLS timeout tests, I've updated the distributed monitoring chapter.
