### ISSUE TITLE
Building icinga2 on centos7.5

### ISSUE THREAD

**Issue by edgarm1964** [Icinga/icinga2#6614]
When trying to (test) build icinga2 2.9.1 from icinga2-2.9.1-1.el7.icinga.src.rpm on a centos 7.5 VM,
the build fails with C++ errors.

## Expected Behavior

The build should succeed.

## Current Behavior
The build fails with the following types of errors:

```
[ 38%] Building CXX object lib/remote/CMakeFiles/remote.dir/pkiutility.cpp.o
cd /opt/monitor/rpmbuild/BUILD/icinga2-2.9.1/lib/remote && /usr/bin/c++    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -g -pthread -Winvalid-pch -std=c++0x -O2 -g -DNDEBUG -I/opt/monitor/rpmbuild/BUILD/icinga2-2.9.1/third-party/yajl/include -I/opt/monitor/rpmbuild/BUILD/icinga2-2.9.1 -I/opt/monitor/rpmbuild/BUILD/icinga2-2.9.1/lib    -o CMakeFiles/remote.dir/pkiutility.cpp.o -c /opt/monitor/rpmbuild/BUILD/icinga2-2.9.1/lib/remote/pkiutility.cpp
In file included from /opt/monitor/rpmbuild/BUILD/icinga2-2.9.1/lib/remote/pkiutility.cpp:20:0:
/opt/monitor/rpmbuild/BUILD/icinga2-2.9.1/lib/remote/pkiutility.hpp:40:9: error: 'shared_ptr' in namespace 'std' does not name a type
  static std::shared_ptr<X509> FetchCert(const String& host, const String& port);
```

## Steps to Reproduce (for bugs)
1. On minimal install centos 7.5 VM, install the following and dependencies:

```
gcc
gcc-c++
bison
flex
cmake
boost
boost-devel
openssl-devel
libedit
libedit-devel
systemd-devel
mariadb-devel
postgresql-devel
checkpolicy
selinux-policy-devel
ncurses-devel
rpm-build
```

2. Create a path file to remove check for execinfo (cmakelists.txt.patch):

```
diff -Naurp icinga2-2.9.1-old/CMakeLists.txt icinga2-2.9.1/CMakeLists.txt
--- icinga2-2.9.1-old/CMakeLists.txt	2018-07-24 12:48:12.000000000 +0200
+++ icinga2-2.9.1/CMakeLists.txt	2018-09-13 14:01:39.070000000 +0200
@@ -312,7 +312,7 @@ check_function_exists(backtrace_symbols
 check_function_exists(pipe2 HAVE_PIPE2)
 check_function_exists(nice HAVE_NICE)
 check_library_exists(dl dladdr "dlfcn.h" HAVE_DLADDR)
-check_library_exists(execinfo backtrace_symbols "" HAVE_LIBEXECINFO)
+#check_library_exists(execinfo backtrace_symbols "" HAVE_LIBEXECINFO)
 check_include_file_cxx(cxxabi.h HAVE_CXXABI_H)

 if(HAVE_LIBEXECINFO)
```
Full log: (https://www.edgar-matzinger.nl/icinga2-build.txt)

3. Adjust icinga2.spec to use the patch file. Near Source:, add:

```
Patch0:         cmakelists.txt.patch
```

And in the %prep section, add:

```
%patch0 -p1
```

Next, switch off unity and LTO build:

```
-DICINGA2_LTO_BUILD=OFF \
-DICINGA2_UNITY_BUILD=OFF \
```

4. Run rpmbuild -ba icinga2.spec

## Context
I want to build an icinga2 environment that resides a different (/opt/monitor) location. So, I can update the icinga version without the need for a member of ICT staff with root access.

## Your Environment
VirtualBox VM: 1 CPU, 1GB
VirtualBox Version: 5.2.18 r124319
Host OS: HighSierra 10.13.6
Guest OS: Centos 7.5
Icinga2 source: icinga2-2.9.1-1.el7.icinga.src.rpm

Tools and versions:
gcc-4.8.5
gcc-c++-4.8.5
bison-3.0.4
flex-2.5.37
cmake-2.8.12.2
boost-1.53.0
boost-devel-1.53.0
openssl-devel-1.0.2k
libedit-3.0
libedit-devel-3.0
systemd-devel-219
mariadb-devel-5.5.60
postgresql-devel-9.2.24
checkpolicy-2.5
selinux-policy-devel-3.13.1
ncurses-devel-5.9
rpm-build-4.11.3

Of course, their dependencies have been installed too.

**Comment by dnsmichi** [comment]
This was fixed in #6539.
