### ISSUE TITLE
Oscillation of the treshold values between defaults and user-defined ones.

### ISSUE THREAD

**Issue by yakutovicha** [Icinga/icinga2#6628]
We have a system of 14 virtual machines where one host is setup as icinga2 master-host, and all the remaining hosts are icinga2-clients that are configured to accept configurations from the master. 

## Current Behavior
For one (quite a large machine, called dev-aiidalab) we increased the **procs** warning and critical thresholds from 250 and 400 to 1000 and 1500 respectively. What we observe, however, is that the actual thresholds start to oscillate between default and new-defined values: 

- _Default values_:

![screenshot_2018-09-19 icinga web](https://user-images.githubusercontent.com/13118485/45751775-a6954100-bc13-11e8-88f2-fd005aa0b2b8.png)

- _User-defined values_:

![screenshot_2018-09-19 icinga web 1](https://user-images.githubusercontent.com/13118485/45751852-eeb46380-bc13-11e8-9bd1-85d0aae54cd7.png)

Despite creating some discomfort when looking at the web-interface (as the procs service very often oscillates between states "CRITICAL" and "OK") the problem does not get erroneously reported by email, as for this to happen the check need to confirm the problem 5 times in a row.

The situation becomes very bad when the number of procs reaches the warning threshold defined by user, say 1005 processes. In that case the service status oscillates between "WARNING" (according to the user's settings and "CRITICAL" (according to the default settings). Icinga2, in turn, starts to bombard the responsible user with hundreds of repeating emails:
[PROBLEM] procs on aiidalab is WARNING!
[PROBLEM] procs on aiidalab is CRITICAL!
[PROBLEM] procs on aiidalab is WARNING!
[PROBLEM] procs on aiidalab is CRITICAL!
[PROBLEM] procs on aiidalab is WARNING!
[PROBLEM] procs on aiidalab is CRITICAL!
....

At the same time if we look at the output of:

>  icinga2 object list --type Service --name "procs"

` 
Object 'dev-aiidalab!procs' of type 'Service':
  % declared in '/etc/icinga2/zones.d/master/services.conf', lines 15:1-15:21
  * __name = "dev-aiidalab!procs"
  * action_url = ""
  * check_command = "procs"
    % = modified in '/etc/icinga2/zones.d/master/services.conf', lines 18:3-18:25
  * check_interval = 60
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 28:3-28:21
  * check_period = ""
  * check_timeout = null
  * command_endpoint = "dev-aiidalab"
    % = modified in '/etc/icinga2/zones.d/master/services.conf', lines 20:3-20:46
  * display_name = "procs"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "dev-aiidalab"
    % = modified in '/etc/icinga2/zones.d/master/services.conf', lines 15:1-15:21
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 5
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 27:3-27:24
  * name = "procs"
    % = modified in '/etc/icinga2/zones.d/master/services.conf', lines 15:1-15:21
  * notes = ""
  * notes_url = ""
  * package = "_etc"
    % = modified in '/etc/icinga2/zones.d/master/services.conf', lines 15:1-15:21
  * retry_interval = 30
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 29:3-29:22
  * source_location
    * first_column = 1
    * first_line = 15
    * last_column = 21
    * last_line = 15
    * path = "/etc/icinga2/zones.d/master/services.conf"
  * templates = [ "procs", "generic-service" ]
    % = modified in '/etc/icinga2/zones.d/master/services.conf', lines 15:1-15:21
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 26:1-26:34
  * type = "Service"
  * vars
    * procs_critical = 1500
      % = modified in '/etc/icinga2/zones.d/master/services.conf', lines 26:5-26:30
    * procs_warning = 1000
      % = modified in '/etc/icinga2/zones.d/master/services.conf', lines 25:5-25:30
  * volatile = false
  * zone = "master"
    % = modified in '/etc/icinga2/zones.d/master/services.conf', lines 15:1-15:21

So the values of procs_critical and procs_warning are correct and do not change with time.

Can someone help me to solve this issue? Is it a bug or am I doing something wrong?
## Small remark
if I do 
> icinga2 --version 

under any non-root user, I get the following warning:
[2018-09-19 14:58:32 +0200] warning/Application: Failed adjust resource limit for number of processes (RLIMIT_NPROC) with error "Operation not permitted"
[2018-09-19 14:58:32 +0200] warning/Application: Failed adjust resource limit for number of processes (RLIMIT_NPROC) with error "Operation not permitted"

However, the warning disappears if I switch to root user. Could it be somehow related to such an oscillation of the threshold values?

## My Environment
* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.5 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-134-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: 1b4c52bdc470

* Operating System and version:
> lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

> uname -a 
Linux server 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Enabled features (`icinga2 feature list`):

Disabled features: compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version    2.6.1
Modules:
monitoring 2.6.1

* Config validation (`icinga2 daemon -C`):
[2018-09-19 15:03:38 +0200] information/cli: Icinga application loader (version: r2.9.1-1)
[2018-09-19 15:03:38 +0200] information/cli: Loading configuration file(s).
[2018-09-19 15:03:38 +0200] information/ConfigItem: Committing config item(s).
[2018-09-19 15:03:38 +0200] information/ApiListener: My API identity: theossrv7
[2018-09-19 15:03:38 +0200] warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 147 Services.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 161 Notifications.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 14 Hosts.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 16 Zones.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 14 Endpoints.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 1 ApiUser.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 8 UserGroups.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 65 CheckCommands.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2018-09-19 15:03:38 +0200] information/ConfigItem: Instantiated 7 Users.
[2018-09-19 15:03:38 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2018-09-19 15:03:38 +0200] information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

content of zones.conf:
```
/*
 * Generated by Icinga 2 node setup commands
 * on 2018-09-03 19:44:06 +0200
 */

object Endpoint "theossrv7" {
}

object Zone "master" {
	endpoints = [ "theossrv7" ]
}

object Zone "global-templates" {
	global = true
}

object Zone "director-global" {
	global = true
}
```
icinga2 object list --type Endpoint (showing only dev-aiidalab):
```
Object 'dev-aiidalab' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.d/master/zones.conf', lines 2:1-2:30
  * __name = "dev-aiidalab"
  * host = "dev-aiidalab"
    % = modified in '/etc/icinga2/zones.d/master/zones.conf', lines 3:5-3:25
  * log_duration = 86400
  * name = "dev-aiidalab"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 2
    * last_column = 30
    * last_line = 2
    * path = "/etc/icinga2/zones.d/master/zones.conf"
  * templates = [ "dev-aiidalab" ]
    % = modified in '/etc/icinga2/zones.d/master/zones.conf', lines 2:1-2:30
  * type = "Endpoint"
  * zone = "master"
```

icinga2 object list --type Zone  (showing only dev-aiidalab):
```
Object 'dev-aiidalab' of type 'Zone':
  % declared in '/etc/icinga2/zones.d/master/zones.conf', lines 6:1-6:26
  * __name = "dev-aiidalab"
  * endpoints = [ "dev-aiidalab" ]
    % = modified in '/etc/icinga2/zones.d/master/zones.conf', lines 7:5-7:34
  * global = false
  * name = "dev-aiidalab"
  * package = "_etc"
  * parent = "master"
    % = modified in '/etc/icinga2/zones.d/master/zones.conf', lines 9:6-9:22
  * source_location
    * first_column = 1
    * first_line = 6
    * last_column = 26
    * last_line = 6
    * path = "/etc/icinga2/zones.d/master/zones.conf"
  * templates = [ "dev-aiidalab" ]
    % = modified in '/etc/icinga2/zones.d/master/zones.conf', lines 6:1-6:26
  * type = "Zone"
  * zone = "master"
```

Part of  /etc/icinga2/zones.d/master/services.conf defining procs service:

```
apply Service "procs" {
  import "generic-service"

  check_command = "procs"

  command_endpoint = host.vars.client_endpoint

  assign where host.vars.client_endpoint && host.vars.check_procs == true

  if (host.name == "dev-aiidalab" || host.name == "aiidalab") {
    vars.procs_warning =  1000
    vars.procs_critical = 1500
  }
}

```

**Comment by Crunsher** [comment]
The log of dev-aiidalab would be required, threshold changes can only happen through a config change (would mean a reload) or through the API (which would be logged).
Also, `icinga2 object list --name dev-aiidalab!procs` and the zone.conf from dev-aiidalab are interesting.

>However, the warning disappears if I switch to root user. Could it be somehow related to such an oscillation of the threshold values?

No, those are just resource limits for Icinga 2

**Comment by mcktr** [comment]
Did you disabled the inclusion of the `conf.d` directory on the dev-aiidalab client? In the default configuration there is also a service called `procs` which might influence the thresholds here.

**Comment by yakutovicha** [comment]
> Also, `icinga2 object list --name dev-aiidalab!procs` and the zone.conf from dev-aiidalab are interesting.

Here we go: 

- zones.conf
```
/*
 * Generated by Icinga 2 node setup commands
 * on 2018-09-04 11:45:49 +0200
 */

object Endpoint "theossrv7" {
	host = "xxx.xxx.xxx.xxx"
	port = "5665"
}

object Zone "master" {
	endpoints = [ "theossrv7" ]
}

object Endpoint "dev-aiidalab" {
}

object Zone "dev-aiidalab" {
	endpoints = [ "dev-aiidalab" ]
	parent = "master"
}

object Zone "global-templates" {
	global = true
}

object Zone "director-global" {
	global = true
}

```

- output of `icinga2 object list --name dev-aiidalab\!procs`
```
Object 'dev-aiidalab!procs' of type 'Service':
  % declared in '/etc/icinga2/conf.d/services.conf', lines 92:1-92:21
  * __name = "dev-aiidalab!procs"
  * action_url = ""
  * check_command = "procs"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 95:3-95:25
  * check_interval = 60
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 28:3-28:21
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "procs"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "dev-aiidalab"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 92:1-92:21
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 5
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 27:3-27:24
  * name = "procs"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 92:1-92:21
  * notes = ""
  * notes_url = ""
  * package = "_etc"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 92:1-92:21
  * retry_interval = 30
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 29:3-29:22
  * source_location
    * first_column = 1
    * first_line = 92
    * last_column = 21
    * last_line = 92
    * path = "/etc/icinga2/conf.d/services.conf"
  * templates = [ "procs", "generic-service" ]
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 92:1-92:21
    % = modified in '/etc/icinga2/conf.d/templates.conf', lines 26:1-26:34
  * type = "Service"
  * vars = null
  * volatile = false
  * zone = ""
```

logs and the other requested things will follow

**Comment by Crunsher** [comment]
It looks like @mcktr was right, go into `/etc/icinga2/icinga2.conf` and remove or comment the line that says `include_recursive conf.d`. Your local configuration is overwriting the one sent by the master.

**Comment by yakutovicha** [comment]
Thanks @Crunsher, @mcktr and @dnsmichi.

It worked!

I commented the line `include_recursive conf.d` in `/etc/icinga2/icinga2.conf` file on dev-aiidalab client and the problem has disappeared.

Have a nice day.
