### ISSUE TITLE
Analysis: Sockets and Communication

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#6637]
This should be a reminder ticket to evaluate different high level libraries like ASIO, and drop our custom low level code on the long run.

- [ ] ASIO: http://think-async.com/Asio/asio-1.12.1/doc/
- [ ] Poco project: https://github.com/pocoproject/poco
- [ ] cpp-netlib: https://github.com/cpp-netlib/cpp-netlib
- [ ] evpp: https://github.com/Qihoo360/evpp

`feature/asio` holds a WIP which bundles the header only standalone ASIO library, this can be used as a base for further evaluation.

**Comment by lippserd** [comment]
I do think that we go the ASIO way. Whoop whoop.
