### ISSUE TITLE
node wizard with configuration file

### ISSUE THREAD

**Issue by bodsch** [Icinga/icinga2#6645]
I like the Wizard. It simplifies the hazzle around the certificates considerably.

But couldn't it be extended to a configuration file that contains all necessary information instead of playing a question and answer game?
This would make it a bit easier to apply for a certificate.

## Expected Behavior
`icinga2 node wizard --file q_and_a.ini`

## Current Behavior
`icinga2 node wizard`
(followed by some questions)

## Context
In my current environment (container and automation) I use expect to get the desired result.

That's not really important.
But it would be a nice addition.

**Comment by Crunsher** [comment]
What about the node cli command? Does that not fill your automation needs?

**Comment by bodsch** [comment]
just `icinga2 node wizard` to create an (satellite) certificate.
currently i use `expect` for the needed answers: https://github.com/bodsch/docker-icinga2/blob/master/rootfs/init/node-wizard.expect

**Comment by bodsch** [comment]
Well, the node wizard creates a certificate request for a satellite.
I think that's what it's for.

But I have no idea to what extent you can change the node setup to meet my requirements.

We could meet in November for the OSMC ...

**Comment by dnsmichi** [comment]
I don't like the idea to add yet another method to run the setup wizards. Although a seed file similar to Debian packages sounds legit ... Still, I would advise to use `node setup` instead for automated setups.

**Comment by killepitisch** [comment]
As far as I understand it is not possible to configure a client using <node setup> without mentioning a ticket number. Without using puppet or similar configuration management tool it is a hassle to deploy a larger environment on Linux. Would be great to either enhance <node setup> to be used with ticketless On-Demand CSR Signing or <node wizard> with some kind of non-interactive mode.

**Comment by lippserd** [comment]
Unfortunately we have no plans to implement this.
