### ISSUE TITLE
Add more options and better output to check_update

### ISSUE THREAD

**Issue by codingwatermelon** [Icinga/icinga2#6648]
I think that the output of check_update could be improved.

## Current Behavior
Currently, you might get something like this:

`UPDATE CRITICAL 2`
`UPDATE OK 0`

## Suggested Behavior
**First of all**, it might not be immediately apparent what the `2` or `0` stands for. A simple reordering like:
`CRITICAL: 2 important updates`
`OK: 0 important updates`
would solve that problem.

**Secondly**, it would be nice to know how many non-critical (optional) updates there are on the system as well, maybe add a flag like "-o" and perhaps based on the assigned value (`crit`, `warn`, or default `none`) the output might look like this:
`check_update ... -o crit`
`CRITICAL: 2 important updates, 3 optional updates`

`check_update ... -o warn`
`WARNING: 0 important updates, 6 optional updates`
(warning if there are no "important" updates, otherwise critical even with `-o warn` flag)

`OK: 0 important updates, 0 optional updates`

What do you all think? I might write these changes in myself if others agree with them.

**Comment by dnsmichi** [comment]
I would prefer lower case (or typical wording), and only use `OK`, etc. for the state strings.

**Comment by codingwatermelon** [comment]
> I would prefer lower case (or typical wording), and only use `OK`, etc. for the state strings.

Updated the initial post to reflect those changes.

**Comment by lippserd** [comment]
We're open for PRs here.

**Comment by dnsmichi** [comment]
Will be superseded with Icinga for Windows developed by @LordHepipud 
https://icinga.com/2019/11/05/icinga-for-windows-rc-available/
