### ISSUE TITLE
Authentication director/filter/hostgroups doesnt work for inherit groups

### ISSUE THREAD

**Issue by tgruenert** [Icinga/icinga2#6650]
## Expected Behavior
Please use inherit information from templates also as a criteria in filters at role definition.

## Current Behavior
Filter on hostgroup in a role work only if hostgroup is set directly inside host definition.

## Steps to Reproduce (for bugs)

1. Define a host X based on a host template Xt. Host template is member of group A. So as far as i unterstand the host X is also member of hostgroup A. At GUI this is shown as inherit group. Nice feature.
2. I define a role with filter director/filter/hostgroups=A.
3. The user U based on this role see no hosts in director.
4. Change Host X and set hostgroup directly to A.
5. User U see the host inside director as expected.

## Environment
icinga2 --version
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)
System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.17.0-0.bpo.3-amd64
  Architecture: x86_64
.........
Build information:
  Compiler: GNU 6.3.0
  Build host: 83e7f59f33f0

```

Disabled features: debuglog elasticsearch gelf influxdb opentsdb perfdata statusdata syslog
Enabled features: api checker command compatlog graphite ido-mysql livestatus mainlog notification

**Comment by Crunsher** [comment]
This sounds like a icingaweb2/director issue, please open an issue [here](https://github.com/Icinga/icingaweb2-module-director)

**Comment by tgruenert** [comment]
did it in https://github.com/Icinga/icingaweb2-module-director/issues/1663
