### ISSUE TITLE
Icinga2 service always runs as "Network service account" after upgrade

### ISSUE THREAD

**Issue by AHeinlein** [Icinga/icinga2#6654]
After upgrading Icinga2 from 2.9.0 to 2.9.2 on several windows hosts, I noticed that all of them had the icinga2 service running under the "network service" account, even though I had configured them to start using the local system account.
The configuration was still there, "net stop icinga2; net start icinga2" made it run as local system again.

Apparently the MSI package causes it to start that way at the end of the upgrade.

**Comment by dnsmichi** [comment]
It would help if you fill in the issue template, especially the Windows version and environment.

**Comment by dnsmichi** [comment]
Closing here for the lack of feedback.
