### ISSUE TITLE
Zone requirements changed in 2.10 - Undocumented Change

### ISSUE THREAD

**Issue by dupondje** [Icinga/icinga2#6671]
Hi,

Since we update our nodes to the newest icinga2, they don't start anymore with the following error:
icinga2[15571]: [2018-10-12 09:37:05 +0200] critical/config: Error: Zone 'XXX' can not have a global zone as parent.

This is because we have:
object Zone "XXX" {
  endpoints = [ "master-server" ]
  parent = "global-templates"
}

The changelog doesn't mention this, but it might be worth to add it!

**Comment by dnsmichi** [comment]
That never worked and is now an error, previously it was hidden from the user. Can you send a PR for the upgrading docs? :)

**Comment by dnsmichi** [comment]
Merged to support/2.10 and triggered a doc generator update.
https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#stricter-configuration-validation
