### ISSUE TITLE
Icinga-common_2.10.0-1 Debian package is missing a file systemd ExecStartPre action needs to source

### ISSUE THREAD

**Issue by Z3po** [Icinga/icinga2#6675]
The actual Debian package (e.g. icinga2-common_2.10.0-1.jessie_all.deb) is missing the file /usr/lib/icinga2/icinga2 which was available in previous debian files.
Now the systemd units holds ExecStartPre action like the following:

    ExecStartPre=/usr/lib/icinga2/prepare-dirs /usr/lib/icinga2/icinga2

This now fails (as the executed script tries to source $1 which is unavailable) and the systemd unit is in Error state.
Therefore a package upgrade is not possible and the System is staying in a broken State.
This could cause production environments with autoupdate to completely fail.

    # icinga2 --version
    icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.0-1)
    
    Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
    License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

**Comment by dnsmichi** [comment]
Please continue in icinga/deb-icinga2#6.
