### ISSUE TITLE
Icinga 2 is not getting started when i tried with reinstallation

### ISSUE THREAD

**Issue by vivuu1989** [Icinga/icinga2#6680]
"icinga2[14268]: /usr/sbin/icinga2: line 29: /usr/lib64/icinga2/sbin/icinga2: No such file or directory"

just did a clean uninstallation by deleting all the files and now when i tried reinstallation, getting this error

sudo yum install icingaweb2.

systemctl start icinga2.service
Job for icinga2.service failed because the control process exited with error code. See "systemctl status icinga2.service" and "journalctl -xe" for details.

Oct 13 00:01:01 HOSTNAME run-parts(/etc/cron.hourly)[13926]: finished 0anacron
Oct 13 00:01:01 HOSTNAME systemd[1]: Removed slice User Slice of root.
-- Subject: Unit user-0.slice has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-0.slice has finished shutting down.
Oct 13 00:01:01 HOSTNAME systemd[1]: Stopping User Slice of root.
-- Subject: Unit user-0.slice has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-0.slice has begun shutting down.
Oct 13 00:01:06 HOSTNAME useradd[13949]: failed adding user 'apache', exit code: 9
Oct 13 00:01:07 HOSTNAME systemd[1]: Reloading.
Oct 13 00:01:07 HOSTNAME yum[13838]: Installed: httpd-2.4.6-80.el7.centos.1.x86_64
Oct 13 00:02:19 HOSTNAME systemd[1]: Reloading.
Oct 13 00:02:19 HOSTNAME systemd[1]: [/etc/systemd/system/icinga2.service.d/limits.conf:2] Unknown lvalue 'DefaultTasksMax' in section 'Service'
Oct 13 00:02:19 HOSTNAME yum[14100]: Installed: icinga2-2.10.0-1.el7.icinga.x86_64
Oct 13 00:02:31 HOSTNAME polkitd[768]: Registered Authentication Agent for unix-process:14201:12699258 (system bus name :1.1482 [/usr/bin/pkttyagent --no
Oct 13 00:02:31 HOSTNAME systemd[1]: Reloading.
Oct 13 00:02:32 HOSTNAME systemd[1]: [/etc/systemd/system/icinga2.service.d/limits.conf:2] Unknown lvalue 'DefaultTasksMax' in section 'Service'
Oct 13 00:02:32 HOSTNAME polkitd[768]: Unregistered Authentication Agent for unix-process:14201:12699258 (system bus name :1.1482, object path /org/freed
Oct 13 00:02:40 HOSTNAME polkitd[768]: Registered Authentication Agent for unix-process:14248:12700117 (system bus name :1.1483 [/usr/bin/pkttyagent --no
Oct 13 00:02:40 HOSTNAME systemd[1]: Starting Icinga host/service/network monitoring system...
-- Subject: Unit icinga2.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit icinga2.service has begun starting up.
Oct 13 00:02:40 HOSTNAME icinga2[14268]: /usr/sbin/icinga2: line 29: /usr/lib64/icinga2/sbin/icinga2: No such file or directory
Oct 13 00:02:40 HOSTNAME systemd[1]: icinga2.service: main process exited, code=exited, status=127/n/a
Oct 13 00:02:40 HOSTNAME systemd[1]: Failed to start Icinga host/service/network monitoring system.
-- Subject: Unit icinga2.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit icinga2.service has failed.
--
-- The result is failed.
Oct 13 00:02:40 HOSTNAME systemd[1]: Unit icinga2.service entered failed state.
Oct 13 00:02:40 HOSTNAME systemd[1]: icinga2.service failed.
Oct 13 00:02:40 HOSTNAME polkitd[768]: Unregistered Authentication Agent for unix-process:14248:12700117 (system bus name :1.1483, object path /org/freed
lines 3006-3048/3048 (END)

**Comment by vivuu1989** [comment]
any help here

**Comment by hemebond** [comment]
@vivuu1989 https://guides.github.com/features/mastering-markdown/

**Comment by dnsmichi** [comment]
Please help developers and contributors by filling in the issue template.

Specifically, your error is missing the distribution and specific icinga2 logs, e.g. on config validation as requested by the template.

**Comment by dnsmichi** [comment]
I'm closing for the lack of feedback, and a clear error description.
