### ISSUE TITLE
Chocolatey outdated version

### ISSUE THREAD

**Issue by seidler2547** [Icinga/icinga2#6683]
What is the update policy for chocolatey packages? Latest available version on https://chocolatey.org/packages/icinga2/ is 2.9.0 which was released almost 3 months ago.

**Comment by dnsmichi** [comment]
It is on my TODO list.

**Comment by dnsmichi** [comment]
![screen shot 2018-10-15 at 16 26 16](https://user-images.githubusercontent.com/382049/46957610-2f2ec200-d098-11e8-86d8-82b2147dd03c.png)

**Comment by dnsmichi** [comment]
The typical review is pending.

https://chocolatey.org/packages/icinga2/2.10.0

**Comment by dnsmichi** [comment]
Was approved yesterday evening, see Icinga's twitter.
