### ISSUE TITLE
by_ssh_arguments with order and with multiple excludes did not work

### ISSUE THREAD

**Issue by th3000** [Icinga/icinga2#6686]
Hi,

when using by_ssh_arguments and check_disk the requiring arguments must may be given in a specific order.

In check_disk some options, like -R, -r, -I, -i  can be used multiple like this:

./check_disk -w 15% -c 10% -R ".*" -I ".*path-1" -I ".*path-2"

But when using "ordering" in Icinga and trying to use an option multiple this did not work:

        vars.disk_by_ssh_arguments = {
        "-w" = { value = "15%", order = 0 }
        "-c" = { value = "10%", order = 1 }
        "-R" = { value = ".*", order = 2 }
        "-I" = { value = ".*path-1", order = 3}
        "-I" = { value = "..*path-2", order = 4}
        }

Only the last (order = 4) will be recognized, "oder = 3" will be "ignored".

![image](https://user-images.githubusercontent.com/44162608/46948202-79567a00-d07d-11e8-87eb-ec5f7f724c6b.png)

Disk By Ssh Arguments 
{
-I => {
     order => 4.0
     value => .*path-2}
-R => {
     order => 2.0
     value => .*}
-c => {
     order => 1.0
     value => 10%}
-w => {
     order => 0.0
     value => 15%}
}

So the question is, how to use multiple same options with "by_ssh_arguments" and ordering?

My system:
Icinga Icinga Web 2 Version 2.5.3
on Ubuntu 16.04.4 LTS

Thx.

**Comment by dnsmichi** [comment]
Multiple dictionary keys don't work, they need to be unique and the last one wins. If you want to use command argument keys with repeated values, you'd need to pass in an array for that value, and set `repeat_key` to true. 

```
 "-I" = {
    value = "$by_ssh_ignores$"
    repeat_key = true
    order = 3
  }
```

```
vars.by_ssh_ignores = [ "pattern1", "pattern2" ]
```

I'd say this is a question for the community channels. Please put it there next time prior to raising an issue.
