### ISSUE TITLE
Icinga Director Segmentation fault during configuring a check  command

### ISSUE THREAD

**Issue by ant0nwax** [Icinga/icinga2#6687]
Hi Icinga People

I tried to configure a check_tcp command (tcp) command
This tpc was present since installation of  Director imported the icinga2 commands via api

Now i wanted to set up something, and made most likely an unhandled error
now i cannot deploy anymore
if i click on the latest config edit in the activity log i get a red error:
GUI shows "The connection to icinga web server was lost"
apache/error_log says Segmentation fault

I had something like this once already and I remeber I need to clean some database, maybe duplicated data. please just help me to clean the database, I am sure this is again some database issue, just I forgot how to do this, no need to investigate the bug, we like buggy software today :)

Thanks for your support, thumbs up!

**Comment by ant0nwax** [comment]
okay, i will use the other one, too, if you would fix errors then keep this one open, if not please close it

**Comment by dnsmichi** [comment]
It isn't clear what exactly you're doing, and I would believe that this isn't Icinga 2 specific at all. As @ekeih said, the community channels fit better to first analyse a problem and then decide whether it is a bug or a missing feature. Therefore I am closing here.

Side note: When creating issues on GitHub, please always fill in the issue template. This helps developers and contributors to faster analyse the problem.
