### ISSUE TITLE
State file not updated on reload

### ISSUE THREAD

**Issue by west0rmann** [Icinga/icinga2#6689]
## Expected Behavior
Save current state to /var/lib/icinga2/icinga2.state after running "systemctl reload icinga2"

## Current Behavior
State file will be persisted every 5 minutes, on restart and on shutdown - but not on reload.

## Possible Solution
This was the reload behaviour in Icinga 2.8.4 (from debug log):

```
[2018-10-15 14:46:04 +0200] information/Application: Got reload command: Starting new instance.
[2018-10-15 14:46:06 +0200] information/Application: Received request to shut down.
[2018-10-15 14:46:07 +0200] information/Application: Shutting down...
```

This is the current reload behaviour in Icinga 2.10.1:

```
[2018-10-15 14:45:12 +0200] information/Application: Got reload command: Starting new instance.
[2018-10-15 14:45:12 +0200] information/Application: Reload requested, letting new process take over.
```

There is a new method "void Application::SigUsr2Handler(int)" in base/application.cpp that does not save the state file. If I add the shutdown code from the main loop, the state file is saved again:

```
void Application::SigUsr2Handler(int)
{
	Log(LogInformation, "Application", "Reload requested, letting new process take over.");
#ifdef HAVE_SYSTEMD
	sd_notifyf(0, "MAINPID=%lu", (unsigned long) m_ReloadProcess);
#endif /* HAVE_SYSTEMD */

	/* Write the PID of the new process to the pidfile before this
	 * process exits to keep systemd happy.
	 */
	Application::Ptr instance = GetInstance();
	try {
		instance->UpdatePidFile(Configuration::PidPath, m_ReloadProcess);
	} catch (const std::exception&) {
		/* abort restart */
		Log(LogCritical, "Application", "Cannot update PID file. Aborting restart operation.");
		return;
	}

	instance->ClosePidFile(false);

+	ConfigObject::StopObjects();
+	Application::GetInstance()->OnShutdown();

	Exit(0);
}
```

## Steps to Reproduce (for bugs)
1. acknowledge a service in a problem state
2. perform an reload after this operation
3. the service is not acknowledged anymore

## Your Environment
Icinga2 2.10.0 on Oracle Linux 7.5

**Comment by dnsmichi** [comment]
Awesome catch, thanks a lot 👍 ❤️ Can you provide me with your name/mail address, I'd like to credit you as commit author :)

**Comment by dnsmichi** [comment]
## Tests

Further steps to reproduce:

- Use a slightly large configuration which increases the reload time to at least 10s: 
[many.conf.zip](https://github.com/Icinga/icinga2/files/2482425/many.conf.zip)

- Terminal 1 watches the state file
- Terminal 2 sends a modify attribute POST Request against an existing host object, followed by a kill HUP signal.
- Terminal 3 watches the host object with GET in all states.

### Terminal 1: State file

```
watch -n 1 -c 'ls -la icinga2.state'
```

### Terminal 2: Modify attribute and reload

```
date; curl -k -s -u root:icinga -X POST -H 'Accept: application/json' 'https://localhost:5665/v1/objects/hosts/mbmif.int.netways.de' -d '{ "attrs": { "vars.reload_test": 1 } }' ; kill -HUP $(pidof icinga2); date
```

### Terminal 3: Watch modified attribute

```
watch -n 1 -c 'curl -k -s -u root:icinga https://localhost:5665/v1/objects/hosts/mbmif.int.netways.de?attrs=vars'
```

## Current behaviour

- Icinga 2 is running, prepare test case.

![screen shot 2018-10-16 at 11 09 14](https://user-images.githubusercontent.com/382049/47006071-643d2200-d135-11e8-87d1-832b504cc778.png)

- Modified attribute and reload triggered

![screen shot 2018-10-16 at 11 09 27](https://user-images.githubusercontent.com/382049/47006443-33a9b800-d136-11e8-9e19-58e0a7eddac2.png)

- Reload in progress

![screen shot 2018-10-16 at 11 09 42](https://user-images.githubusercontent.com/382049/47007052-a8c9bd00-d137-11e8-8e81-ed05d67935bd.png)

- Reload done, modified attribute gone

![screen shot 2018-10-16 at 11 10 09](https://user-images.githubusercontent.com/382049/47007066-b5e6ac00-d137-11e8-9e08-122a9f3ba490.png)


## Fix in place

- Prepare test case from running patched Icinga 2 instance

![screen shot 2018-10-16 at 11 41 17](https://user-images.githubusercontent.com/382049/47007558-d2371880-d138-11e8-9df0-1bec28357aa3.png)

- Modify the attribute and trigger the reload

![screen shot 2018-10-16 at 11 41 28](https://user-images.githubusercontent.com/382049/47007621-ed098d00-d138-11e8-95a5-e12e370d3683.png)

- Reload in progress, the state file has been updated.

![screen shot 2018-10-16 at 11 41 45](https://user-images.githubusercontent.com/382049/47007674-090d2e80-d139-11e8-81a1-971af59d3c81.png)

- Reload done, modified attribute is read and still there.

![screen shot 2018-10-16 at 11 43 16](https://user-images.githubusercontent.com/382049/47007718-2641fd00-d139-11e8-9f64-b05935d0ec7d.png)

- With the new log line, you'll see when the reload is finished.

![screen shot 2018-10-16 at 11 43 44](https://user-images.githubusercontent.com/382049/47007771-440f6200-d139-11e8-9776-2be67a88b174.png)

**Confirmed working.**

**Comment by kevinstiller** [comment]
Can confirm that acks disappear after I reload shortly after the ack. How can I help? 710 Hosts, 10K Services.

**Comment by dnsmichi** [comment]
@kevinstiller test the snapshot packages, please :)
