### ISSUE TITLE
2.10.0-1 upgrade Error from 2.9.2-1

### ISSUE THREAD

**Issue by hypermagicmountain** [Icinga/icinga2#6695]
Using `apt update && apt upgrade` will not upgrade to 2.10.0-1
Happens on Ubuntu Xenial and Bionic servers. The Master is running on Xenial, the satellites are mixed.

## Expected Behavior
Should upgrade to latest version. Never had issues with upgrading icinga2 before.

## Current Behavior
When I upgrade all packages I won't get an error, but 4 packages will not be upgraded:

- icinga2
- icinga2-bin
- icinga2-common
- icinga2-ido-mysql

So when i run `apt upgrade icinga2 icinga2-bin icinga2-common icinga2-ido-mysql` manually, I will get the message:

> Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

>The following packages have unmet dependencies:
 icinga2-bin : Breaks: libicinga2 but 2.9.2-1.xenial is to be installed
E: Broken packages

## Your Environment

* Version used (`icinga2 --version`): 2.9.2-1
* Operating System and version: Ubuntu Xenial, Ubuntu Bionic
* Enabled features (`icinga2 feature list`):>Disabled features: compatlog debuglog elasticsearch gelf graphite icingastatus livestatus opentsdb perfdata statusdata syslog
>Enabled features: api checker command ido-mysql influxdb mainlog notification
* Icinga Web 2 version and modules (System - About): 2.6.1 - doc, grafana and monitoring

## Additional Information

> cat /etc/apt/sources.list.d/icinga.list
> deb https://packages.icinga.com/ubuntu icinga-xenial main

>apt list | grep icinga2
icinga2/icinga-xenial 2.10.0-1.xenial amd64 [upgradable from: 2.9.2-1.xenial]
icinga2-bin/icinga-xenial 2.10.0-1.xenial amd64 [upgradable from: 2.9.2-1.xenial]
icinga2-classicui/icinga-xenial,icinga-xenial 2.9.2-1.xenial all
icinga2-common/icinga-xenial,icinga-xenial 2.10.0-1.xenial all [upgradable from: 2.9.2-1.xenial]
icinga2-dbg/icinga-xenial 2.10.0-1.xenial amd64
icinga2-doc/icinga-xenial,icinga-xenial,now 2.10.0-1.xenial all [installed,auto-removable]
icinga2-ido-mysql/icinga-xenial 2.10.0-1.xenial amd64 [upgradable from: 2.9.2-1.xenial]
icinga2-ido-pgsql/icinga-xenial 2.10.0-1.xenial amd64
icinga2-studio/icinga-xenial 2.8.4-1.xenial amd64
libicinga2/icinga-xenial,now 2.9.2-1.xenial amd64 [installed,automatic]
vim-icinga2/icinga-xenial,icinga-xenial,now 2.10.0-1.xenial all [installed]

**Comment by dnsmichi** [comment]
Please create such issues in icinga/icinga-packaging next time.

I would guess that "apt upgrade" cannot deal with removed packages (and dependencies). libicinga2 is gone for 2.10. Try it with a manual `apt-get install icinga2` to see if that works.

**Comment by hypermagicmountain** [comment]
@dnsmichi 
Yep, that worked, thank you. Apt said it would remove libicinga2 but it's still there. The rest is running on 2.10 now however.

**Comment by dnsmichi** [comment]
I know these problems with other packages in Debian/Ubuntu. Sometimes such things happen, still it is unfortunate. You might want to try to remove that old package, AFAIK autoremove or `apt-get remove <packagename>`.

**Comment by Thomas-Gelf** [comment]
IMHO such things shouldn't happen at all, we shouldn't ship packages that break straight upgrade paths. Guess we can do better here.

**Comment by dnsmichi** [comment]
Probably. For now, I am the only resource taking care of these releases, so it slipped through my release tests. Sorry for the problems, I'll mark this as solved.

**Comment by lazyfrosch** [comment]
The answer is pretty simple: we are removing deprecated packages with the upgrade.

APT does not remove packages on `apt upgrade` for safety reasons. You have to run: `apt full-upgrade` or `apt-get dist-upgrade`

This is **not** an issue with our packages, please see `man apt`.

**Comment by hypermagicmountain** [comment]
Ok thank you guys. I think I just misinterpreted the output of `apt list`. libicinga2 does show there, but is not marked as _installed_

>    apt list | grep icinga2
>icinga2/icinga-xenial,now 2.10.0-1.xenial amd64 [installed]
icinga2-bin/icinga-xenial,now 2.10.0-1.xenial amd64 [installed]
icinga2-classicui/icinga-xenial,icinga-xenial 2.9.2-1.xenial all
icinga2-common/icinga-xenial,icinga-xenial,now 2.10.0-1.xenial all [installed,automatic]
icinga2-dbg/icinga-xenial 2.10.0-1.xenial amd64
icinga2-doc/icinga-xenial,icinga-xenial 2.10.0-1.xenial all
icinga2-ido-mysql/icinga-xenial,now 2.10.0-1.xenial amd64 [installed]
icinga2-ido-pgsql/icinga-xenial 2.10.0-1.xenial amd64
icinga2-studio/icinga-xenial 2.8.4-1.xenial amd64
**libicinga2/icinga-xenial 2.9.2-1.xenial amd64**
vim-icinga2/icinga-xenial,icinga-xenial,now 2.10.0-1.xenial all [installed]

**Comment by Farfaday** [comment]
Seems that icinga2-classicui is also gone with 2.10.1...  maybe this could be added to that page : https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#upgrading-to-v210 :)

**Comment by crazy4chrissi** [comment]
Now the Icinga docs say: 

> Upgrading to v2.10
> [...]
> RPM packages dropped the Classic UI package in v2.8, Debian/Ubuntu packages were forgotten. This is now the case with this release. Icinga 1.x is EOL by the end of 2018, plan your migration to Icinga Web 2.

https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#upgrading-to-v210

This means in debian, the classic UI package got dropped with 2.10, which seems true for the icinga repository. Interestingly, there is a classicUI 2.10.3-2~bpo9+1 currently in Debian stretch-backports. This package seems to still work with the 2.10.3 from the backports repository. At least its dependecies can be satisfied. I have not tried it, as I am already on 2.10.4 and don't like to downgrade.
