### ISSUE TITLE
Unable to submit passive check results after upgrade to 2.10.0

### ISSUE THREAD

**Issue by leeclemens** [Icinga/icinga2#6698]
## Expected Behavior
`POST` to `/v1/actions/process-check-result` continues to work when submitting passive check results (returning 200)

## Current Behavior
`POST` to `/v1/actions/process-check-result` returns 404

## Possible Solution
Workaround was to downgrade back to 2.9.2-1 and the same command/script continued working again

## Steps to Reproduce (for bugs)
1. Create passive check on host
2. `POST` to `/v1/actions/process-check-result?service=servername!service_name` with json data
3. This is returned: `{"error":404.0,"status":"No objects found."}`

## Context
Submitting check result to passive check using `POST` to `/v1/actions/process-check-result`
The results include performance data

## Your Environment

* Version used (`icinga2 --version`):

> icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.0-1)
> 
> Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
> License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> System information:
>   Platform: CentOS Linux
>   Platform version: 7 (Core)
>   Kernel: Linux
>   Kernel version: 3.10.0-862.14.4.el7.x86_64
>   Architecture: x86_64
> 
> Build information:
>   Compiler: GNU 4.8.5
>   Build host: unknown
> 
> Application information:
> 
> General paths:
>   Config directory: /etc/icinga2
>   Data directory: /var/lib/icinga2
>   Log directory: /var/log/icinga2
>   Cache directory: /var/cache/icinga2
>   Spool directory: /var/spool/icinga2
>   Run directory: /run/icinga2
> 
> Old paths (deprecated):
>   Installation root: /usr
>   Sysconf directory: /etc
>   Run directory (base): /run
>   Local state directory: /var
> 
> Internal paths:
>   Package data directory: /usr/share/icinga2
>   State path: /var/lib/icinga2/icinga2.state
>   Modified attributes path: /var/lib/icinga2/modified-attributes.conf
>   Objects path: /var/cache/icinga2/icinga2.debug
>   Vars path: /var/cache/icinga2/icinga2.vars
>   PID path: /run/icinga2/icinga2.pid
> 

* Operating System and version:
> CentOS Linux release 7.5.1804 (Core)
* Enabled features (`icinga2 feature list`):
> Disabled features: command compatlog debuglog elasticsearch gelf influxdb livestatus opentsdb perfdata statusdata syslog
> Enabled features: api checker graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About):
> N/A
* Config validation (`icinga2 daemon -C`):
> Can provide something specific if it could help:
> [2018-10-17 22:59:28 -0400] information/cli: Finished validating the configuration file(s).
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by leeclemens** [comment]
Forgot to search closed, probably a duplicate of #6682

**Comment by dnsmichi** [comment]
You can test the snapshot packages :) Planning for 2.10.1 soon then.

**Comment by leeclemens** [comment]
Confirmed!
