### ISSUE TITLE
inconsistent documentation of type for last_state for service and host objects

### ISSUE THREAD

**Issue by rgevaert** [Icinga/icinga2#6706]
## Current Behavior

The documentation page [09-object-types.md](https://github.com/Icinga/icinga2/blob/master/doc/09-object-types.md) says the type of `service.last_state`. However [03-monitoring-basics.md](https://github.com/Icinga/icinga2/blob/master/doc/03-monitoring-basics.md) says it is "Can be one of OK, WARNING, CRITICAL and UNKNOWN." _It is implemented as OK, WARNING, CRITICAL and UNKNOWN._

The same is true for `host.last_state`

## Expected Behavior
The documentation should be consistent

## Possible Solution

I suggest to update the documentation in [09-object-types.md](https://github.com/Icinga/icinga2/blob/master/doc/09-object-types.md) to be consistent with the current implementation (replace the word _Number_ with _String_)

Another thing is that `host.last_hard_state` and `service.last_hard_state` are indeed implemented as Numbers. Which isn't really consistent with the type of last_state.

## Context

When debugging https://github.com/nisabek/icinga2-slack-notifications/issues/18 about notifications sent to slack I found an inconsistency in the documentation. And because of inconsistent typing between `last_state` and `last_hard_state` I need to do an translation :-(

## Your Environment

icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.0-1)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: 695473ceafaf

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

**Comment by dnsmichi** [comment]
```
<1> => get_host(NodeName).last_state
1.000000
<2> => get_host(NodeName).last_hard_state
1.000000
```

There's a difference with runtime macros though, their return value differs and provides the string representation of that state. Basically it overrides the default attributes, specifically for `last_state`. This was implemented to stay compatible with the 1.x world and scripts.

Therefore the documentation is correct about it, for the runtime macro section. I agree that it is a bit complex to understand, but still - raw object attributes are different to what the macro resolver returns, in specific cases (and all of them are documented).

**Comment by rgevaert** [comment]
Ok thanks. I get your point.
