### ISSUE TITLE
Icinga Agent Crash on Windows 2016 Essential

### ISSUE THREAD

**Issue by vdveldet** [Icinga/icinga2#6715]
After installing icinga2 on windows 2016 Essential, the daemon crashed when starting up

c:\Program Files\ICINGA2\sbin>icinga2.exe daemon -x debug
[2018-10-22 17:42:56 +0200] information/cli: Icinga application loader (version: v2.4.5)
[2018-10-22 17:42:56 +0200] critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in 'C:\ProgramData\icinga2\var/log/icinga2/crash/report.1540222976.023'

Application information:
  Application version: v2.4.5
  Installation root: C:\Program Files\ICINGA2\
  Sysconf directory: C:\ProgramData\icinga2\etc
  Run directory: C:\ProgramData\icinga2\var\run
  Local state directory: C:\ProgramData\icinga2\var
  Package data directory: C:\Program Files\ICINGA2\\share\icinga2
  State path: C:\ProgramData\icinga2\var/lib/icinga2/icinga2.state
  Modified attributes path: C:\ProgramData\icinga2\var/lib/icinga2/modified-attributes.conf
  Objects path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.debug
  Vars path: C:\ProgramData\icinga2\var/cache/icinga2/icinga2.vars
  PID path: C:\ProgramData\icinga2\var\run/icinga2/icinga2.pid

System information:
  Platform: Windows
  Platform version: 8 (Server)
  Kernel: Windows
  Kernel version: 6.2
  Architecture: x86_64
Caught unhandled SEH exception.
Current time: 2018-10-22 17:42:56 +0200

Stacktrace:

	(0): icinga::Utility::CreateTempFile+860
	(1): icinga::ConfigCompilerContext::OpenObjectsFile+148
	(2): icinga::DaemonUtility::ValidateConfigFiles+91
	(3): icinga::DaemonUtility::LoadConfigFiles+128
	(4): icinga::BlackAndWhitelistCommand::Run+6263
	(5): (unknown function)
	(6): (unknown function)
	(7): (unknown function)
	(8): BaseThreadInitThunk+20
	(9): RtlUserThreadStart+33
***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://dev.icinga.org/ and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***

**Comment by dnsmichi** [comment]
`Application version: v2.4.5` is long out of support. Please install the most recent 2.10 release.

**Comment by vdveldet** [comment]
Damn, had to scroll down much further, Thanks for helping out
