### ISSUE TITLE
Polish the Windows Agent design

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga2#6729]
I'd like to polish the Windows Agent design a bit. Below are some examples about what I imagined.

Left is the current state, right is my proposal.

**Installation wizard**

![compare-install-1](https://user-images.githubusercontent.com/18580278/47446134-dc04ef80-d7ba-11e8-97d1-8e9d653b6b70.png)
![compare-install-2](https://user-images.githubusercontent.com/18580278/47446141-ddceb300-d7ba-11e8-8386-b90708d05cc7.png)
![compare-install-3](https://user-images.githubusercontent.com/18580278/47446143-deffe000-d7ba-11e8-8169-fb3007003220.png)
![compare-install-4](https://user-images.githubusercontent.com/18580278/47446146-e0310d00-d7ba-11e8-92c1-9875f193b99b.png)
![compare-install-5](https://user-images.githubusercontent.com/18580278/47446149-e1fad080-d7ba-11e8-9ef9-bdb4ad168ad1.png)

**Agent**

![compare-app-2](https://user-images.githubusercontent.com/18580278/47446184-f8a12780-d7ba-11e8-8c13-b7d460054874.png)
![compare-app-1](https://user-images.githubusercontent.com/18580278/47446186-fb9c1800-d7ba-11e8-8574-a73cc68bc16b.png)
 
Before turning this in a PR I would like to hear your feedback. :)

**Comment by dnsmichi** [comment]
Go for it :-)
