### ISSUE TITLE
period attribute not updated in DB IDO

### ISSUE THREAD

**Issue by afeefghannam89** [Icinga/icinga2#6744]
Icinga2 core doesn't put the check_timeperiod_object_id in the daten bank on 0 after taking out Check period from a service 

## Expected Behavior
The Check Timeperiod must not be shown on the Icinga 2 Web, after it took out from a service. According to  "Icingacli object list" it emphasizes that the  Timeperiod = null. The Icinga data base shows that Timeperiod is active. That is why Icinga Web 2  displays wrongly that the Timeperiod still used. 

![screenshot from 2018-10-31 14-48-14](https://user-images.githubusercontent.com/39904920/47793110-d01aaf80-dd1d-11e8-94c6-f43241fd4915.png)
![screenshot from 2018-10-31 14-50-03](https://user-images.githubusercontent.com/39904920/47793111-d01aaf80-dd1d-11e8-933a-dab35f8c8f8f.png)
![screenshot from 2018-10-31 14-51-12](https://user-images.githubusercontent.com/39904920/47793112-d01aaf80-dd1d-11e8-869f-b44c82d27d97.png)
![screenshot from 2018-10-31 14-53-05](https://user-images.githubusercontent.com/39904920/47793114-d0b34600-dd1d-11e8-9a12-3970c0b298ef.png)

## Steps to Reproduce (for bugs)
1. I have created Timeperiod with the director 
2. I have used this Timeperiod with a one service "ping" 
3. I have deployed the changes. Then Icinga Web 2 shows this Timeperiod associated with  the "bing" service. Every thing is until now okay 
4. I have  took out the Timeperiod from "ping" service Template. Then i have deployed the changes another time. Although still  Timeperiod associated with the "ping" .

## Your Environment
* Version used (`icinga2 --version`): r2.9.1-1
* Operating System and version: CentOs 7
* Icinga Web 2 version and modules (System - About):   2.6.1, Director  1.5.1

**Comment by lippserd** [comment]
Closed in favor of #6744
