### ISSUE TITLE
Please provide rpm package for Fedora 29

### ISSUE THREAD

**Issue by spike77453** [Icinga/icinga2#6746]
There seems to be no pre-built rpm package available for Fedora 29 yet (checked https://packages.icinga.com/fedora/)

**Comment by mcktr** [comment]
Thanks for letting us know. I copied your issue in the [icinga-packaging](https://github.com/Icinga/icinga-packaging) repository where all packaging related issue are tracked.

I close here, please follow https://github.com/Icinga/icinga-packaging/issues/119.
