### ISSUE TITLE
GraphiteWriter: let the user configure wich thresholds/metadata are written to graphite

### ISSUE THREAD

**Issue by cstegm** [Icinga/icinga2#6772]
## Expected Behavior
I can configure wich metadata/threshold will be written when i enable the enable_send_thresholds/enable_send_metadata options.

## Current Behavior
Now we have an all or nothing configuration (bool) option but cannot specify the metrics.

## Possible Solution
let the user define an array of the metricnames (https://icinga.com/docs/icinga2/latest/doc/14-features/#graphite-carbon-cache-writer) in the graphitewriter object.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Some users need status, warn and crit metrics, but not the other metrics wich are send when i enable those options.

**Comment by dnsmichi** [comment]
Graphite/Carbon already allows you to define such patterns for black/whitelists.
https://graphite.readthedocs.io/en/latest/config-carbon.html#whitelist-and-blacklist

I don't think it is necessary to overly complicate the Icinga 2 feature configuration here, and we will stay with on/off for the time being.

**Comment by cstegm** [comment]
Example: If i enable enable_send_metadata a check writes this to graphite:

```
//normal
<prefix>.perfdata.<perfdata-label>.value

//enable_send_metadata
<prefix>.metadata.current_attempt
<prefix>.metadata.downtime_depth
<prefix>.metadata.acknowledgement
<prefix>.metadata.execution_time
<prefix>.metadata.latency
<prefix>.metadata.max_check_attempts
<prefix>.metadata.reachable
<prefix>.metadata.state
<prefix>.metadata.state_type
```
But the data that we really want in my use case is:
```
//normal
<prefix>.perfdata.<perfdata-label>.value
<prefix>.metadata.state
```
So why generating data & traffic only to blacklist later? 

I was not thinking of a filterengine. But i think the addtional metrics generated by icinga2 should be configurable. 

Instead of 
```
enable_send_metadata = true
```
The configuration could look like:
```
enable_send_metadata = [ 'state', 'execution_time' ]  
```

**Comment by dnsmichi** [comment]
I understand the requirement, I still don't like the extra config options. They're free form too in this example and would need proper config validators, and so on. Overall, it slows down the GraphiteWriter performance with each check whether the metric should be sent or not.

Let's see how others feel about this.
