### ISSUE TITLE
"OK" notification time.begin ignored

### ISSUE THREAD

**Issue by janklewicz** [Icinga/icinga2#6774]
Service Notification with OK state filter and time.begin set to 60s is triggered immediately after service hits OK state. Additionall history entry is created with "This notification was not sent out to any contact." information.

## Expected Behavior
OK notification should be triggerred after 60s after service hits OK state

## Current Behavior
As in summary.

## Steps to Reproduce (for bugs)

1. create "problem" notification and assign it to dummy service:

```
apply Notification "critical_delay_tester" to Service {
    times = {
        begin = 1m
    }
    command = "mail"
    interval = 0s
    period = "24x7"
    assign where host.name == "TEST"
    states = [ Critical ]
    users = [ "jaroslaw.anklewicz" ]
}
```

2. create "recovery" notification and assign it to dummy service:

```
apply Notification "ok_delay_tester" to Service {
    times = {
        begin = 1m
    }
    command = "mail"
    interval = 0s
    period = "24x7"
    assign where host.name == "TEST"
    states = [ OK ]
    users = [ "jaroslaw.anklewicz" ]
}

```

3. process critical check result for dummy service until it hits HARD - after ~60s critical notifiaction is triggerred [expected behavior]
4. process ok service check result for dummy service - result is as on image below:

![snipaste_2018-11-13_14-10-47](https://user-images.githubusercontent.com/12608728/48415606-23452700-e74e-11e8-9e54-504a16bf03ab.png)

## Context

The basic idea is that we want to send notification after service hits "OK" state but only if that state presists for 1 minute or any other defined value only once.

It's required for informing our HD Team that they should close the ticket in our ticketing system or in future maybe close them automaticaly but only if state is OK for a specified time.

## Your Environment

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.1-1)
* Operating System and version:
16.04.5 LTS (Xenial Xerus) and Debian 9 (tested on both with the same icinga2 version)
* Enabled features (`icinga2 feature list`):
Enabled features: api checker compatlog debuglog graphite ido-mysql livestatus mainlog notification
* Icinga Web 2 version and modules (System - About):
Director 1.5.1, Graphite 1.1.0, Monitoring 2.6.1
* Config validation (`icinga2 daemon -C`):
OK
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
Single instance

Service passive_test does not have any additional notificaions defined (checked with icinga2 object list)
Host TEST does not have any notifications defined
I'm creating 2 notification objects because in production there will be different notification command for Ciritcal and OK state.

**Comment by dnsmichi** [comment]
Recovery notifications cannot be delayed, this only is valid for the first problem notification.

**Comment by dnsmichi** [comment]
It is nothing which is planned being changed, users trust that `times.begin` only affects problem notifications. The idea is interesting, still I wouldn't attempt to solve that within Icinga 2, but with an external "proxy" which aggregates and delays such incidents. The most simple stupid thing is to have a  a cron script which picks that up from a local spool file and sleeps for 60s then before forwarding it. Or to have an external daemon running which wakes up after the event slept for 60s.

**Comment by janklewicz** [comment]
In that case we'll probably check if state of service is OK "for long enough" with every check run. Of course we will be limited by the check_interval but for this specific case it should be good enough. One more time - thank you for quick answers - now we know on which direction we should go.
