### ISSUE TITLE
GraphiteWriter not sending any data from icinga

### ISSUE THREAD

**Issue by effi-srs** [Icinga/icinga2#6778]
Hey there, I'm facing an issue with the graphite feature of icinga2.  From my perspective graphite isn't getting any data from icinga2.

## Expected Behavior
The installed Graphite feature of icinga2 should save the data automatically in the database, so I can display it with IcingaWeb2

## Current Behavior
The GraphiteWriter of Icinga2 isn't doing anything. If I look in the icinga log I can see three entries from the GraphiteWriter whitch say:

`[2018-11-15 14:28:25 +0100] information/GraphiteWriter: 'graphite' started.`
`[2018-11-15 14:28:25 +0100] information/GraphiteWriter: Finished reconnecting to Graphite in 0.000283003 second(s).`

And later on:

`[2018-11-15 14:28:35 +0100] information/WorkQueue: #7 (GraphiteWriter, graphite) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);`

Graphite feature is enabled in icinga2 as you can see. I rebooted and restarted the services, but Graphite wont get the data from icinga2.

graphite.conf in the enabled-features folder is the default one:
`object GraphiteWriter "graphite" {
  host = "127.0.0.1"
  port = 2003
}`

I checked the database config twice for user, password and database, but they are correct.

I'm getting the exact same issue with influxdb and the influxdWriter and couldn't solve it so I later removed it and switched to graphite, what makes me even more wondering whats going on...

## Steps to Reproduce (for bugs)

I know it's a german page, but I did exactly what is listet here: [https://dokuwiki.nausch.org/doku.php/centos:web_c7:icinga:graphite](https://dokuwiki.nausch.org/doku.php/centos:web_c7:icinga:graphite)

It's just the very basic stuff for graphite: configuring the default graphite installation to get it work properly, but I'm still wondering why there's no error message in the icinga log. It's just saying that there's no information transferred from icinga to graphite (If you know what I mean :))

## Your Environment
Icinga2 Version: r2.10.1-1 on CentOS 7
`Enabled features: api checker command debuglog graphite ido-mysql mainlog notification`
(Also tried the features perfdata and influx but it didn't work either, even though perfdata should't be used for both influxdb and graphite it just generates a lot of files :D)

**Comment by Crunsher** [comment]
Looks like Icinga2 is not finding anything to write to Graphite/Influx. Do you have a working config? Meaning Services and Hosts which run checks?

**Comment by effi-srs** [comment]
Thank you for your Idea Crunsher. I checked that and I've set up my test environment with the Icinga Director and made sure that the switch "Process Performance Data" was enabled in at least a few services. That should do the trick right, or do I have to set something manually via the CLI?

Everything else works perfect: Data is send from the windows servers and displayed correctly in IcingaWeb2, but every 5 minutes I get the messages:
`(GraphiteWriter, graphite) items: 0, rate: 0.333333/s (20/min 106/5min 224/15min);`
`(InfluxdbWriter, influxdb) items: 0, rate: 0.333333/s (20/min 106/5min 224/15min);`

I noticed the rates vary a little bit, but always with 0 items and I can't see anything in the database. Also the graph in IcingaWeb says "no data".

**Comment by dnsmichi** [comment]
Plugins need to provide valid performance data. Is that the case for one specific service you're having this error? 

Btw - such questions receive more attention in the community channels.

**Comment by effi-srs** [comment]
Thank you for the advice to post it in the community channels, I will do that in a minute with a link to this thread.

I can give you the code used for the Service teamplate in Icinga Director:
```
template Service "ServiceTemplate | CPU Load" {
    check_command = "load-windows"
    check_period = "24x7 TimePeriod"
    enable_notifications = false
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_flapping = false
    enable_perfdata = true
    volatile = false
    command_endpoint = host_name
    vars.load_win_crit = "5%"
    vars.load_win_warn = "1%"
}
```

I'm using the `load-windows` check command for this service, but there other services with for example the `disk-windows` check command as well. I'm only using the check commands provided with the default  nagios-plugins-all package mentioned at the [official icinga installation docs](https://icinga.com/docs/icinga2/latest/doc/02-getting-started/#setting-up-check-plugins).

I can try to enable the performance data processing in other services too, but it's not only the data of one service which should be saved by influx or graphite.

**Comment by dnsmichi** [comment]
> Almost forgot to put in the link to the community thread

By community channels I meant the Icinga community channels, not GitHub. Check https://icinga.com/community for insights.

Please proceed over there.
