### ISSUE TITLE
2.10.1 ignores -D ObjectsPath=/foo/bar command line arguments

### ISSUE THREAD

**Issue by wferi** [Icinga/icinga2#6779]
I'm "hosting" several Icinga2 setups on a server (Debian stretch). To do this, I pass the appropriate `-D` options to each daemon, giving the appropriate Unix users and filesystem paths. This worked fine with the 2.6.3-1 Debian packages, but fails with the 2.10.1-1 packages: the various path settings are just not taken into account anymore:

~~~
wferi@gum:~$ /usr/sbin/icinga2 daemon
critical/cli: setgroups() failed with error code 1, "Operation not permitted"
critical/cli: Please re-run this command as a privileged user or using the "nagios" account.
wferi@gum:~$ /usr/sbin/icinga2 daemon -D RunAsGroup=wferi
critical/cli: initgroups() failed with error code 1, "Operation not permitted"
critical/cli: Please re-run this command as a privileged user or using the "nagios" account.
wferi@gum:~$ /usr/sbin/icinga2 daemon -D RunAsGroup=wferi -D RunAsUser=wferi
[2018-11-15 16:42:23 +0100] information/cli: Icinga application loader (version: r2.10.1-1)
[2018-11-15 16:42:23 +0100] information/cli: Loading configuration file(s).
[2018-11-15 16:42:23 +0100] critical/cli: Could not create temporary objects file: Error: Function call 'mkstemp' for file '/var/cache/icinga2/icinga2.debug.XXXXXX' failed with error code 13, 'Permission denied'

wferi@gum:~$ /usr/sbin/icinga2 daemon -D RunAsGroup=wferi -D RunAsUser=wferi -D ObjectsPath=/foo/bar
[2018-11-15 16:42:33 +0100] information/cli: Icinga application loader (version: r2.10.1-1)
[2018-11-15 16:42:33 +0100] information/cli: Loading configuration file(s).
[2018-11-15 16:42:33 +0100] critical/cli: Could not create temporary objects file: Error: Function call 'mkstemp' for file '/var/cache/icinga2/icinga2.debug.XXXXXX' failed with error code 13, 'Permission denied'
~~~

The above progression does not hit a wall with 2.6.3: in the last step the `mkstemp` path changes according to the `-D ObjectsPath` setting, unlike above. Under gdb I observe that `Configuration::RunAsUser` changes before execution enters `DaemonCommand::Run()`, but `Configuration::ObjectsPath` does not, so its pristine value is passed to `DaemonUtility::LoadConfigFiles()` leading to the above failure. Decyphering the `SetExpression` logic looked demanding, so unfortunately I can't provide deeper insight into this discrepancy. Can you pinpoint the problem? This code changed a lot between 2.6.3 and 2.10.1.

**Comment by Crunsher** [comment]
Two major changes are related to this
A) Introduction of namespaces
B) Moving paths to sysconfig file

A work around that may help you: change `ICINGA2_CACHE_DIR`  in `/etc/sysconfig/icinga2` to `/foo`. The files will still be named `icinga2.debug.` etc.

**Comment by wferi** [comment]
Thanks for the info. I'm not sure about `ICINGA2_CACHE_DIR`, could you please point me to its documentation? The daemon code does not seem to reference it, so I wonder how it could be effective, but I'd like to give it a try. I have to move the `objects`, `variables`, `state` and `modattr` files into the same per-setup directory, which is unwieldy via defining `ObjectsPath`, `VarsPath`, `StatePath`, and `ModAttrPath` anyway. I also specify `PidPath` and the config file location on the command line. Some of these could probably live in the config file, but this central solution spares my "users" some mistakes, so I'd like to keep it. I can see the code read `ICINGA2_USER`, `ICINGA2_GROUP` and the three rlimit variables but no other seemingly relevant settings.

**Comment by Crunsher** [comment]
It was mentioned [here](https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#sysconfig-changes). But searching through the config I notice we seem to not mention it anywhere else :/

**Comment by wferi** [comment]
For me it looks like it's used exclusively in `prepare-dirs`, meaning that it probably won't help with my startup issues, where the directories are already present.

**Comment by wferi** [comment]
So what is the way to run several Icinga2 setups on the same operating system now that `-D` won't change the paths? (I'd like to stay away from container techniques if possible.)

**Comment by wferi** [comment]
Hi, could anybody please recommend a solution for running several Icinga2 daemons on the same system, now that the `-D` option can't change `ObjectsPath`, `VarsPath`, `StatePath`, `ModAttrPath` and `PidPath` anymore? Thanks.

**Comment by dnsmichi** [comment]
I'm using DataDir and ConfigDir for my tests during development. If you want to dig further into the code and the problem itself, here's some hints on developing Icinga 2: https://icinga.com/docs/icinga2/snapshot/doc/21-development/#develop-icinga-2

**Comment by wferi** [comment]
@dnsmichi According to https://icinga.com/docs/icinga2/latest/doc/17-language-reference/, `DataDir` and `ConfigDir` are both read-only. How can I use them to separate different configurations? I don't want to compile separate binaries for this, but use the same binary with different command line/environment to make it read/write different files/databases. I found a way for 2.6, but not for 2.10. I'm not doing this for development purposes, I'd like to upgrade a production system.
Maybe I miss the point of your comment totally, could you please expand on it a little? Thanks.

**Comment by dnsmichi** [comment]
They are read-only inside the configuration scope, e.g. inside an object or globally. Try them out with `-D`.

My comment in terms of the development docs suggests creating a patch which can be merged upstream in one of the next releases. I won't be looking into this very specific problem myself - if you require it, maybe you're up for a fix.

Cheers,
Michael

**Comment by Al2Klimov** [comment]
> I'm "hosting" several Icinga2 setups on a server

@wferi If this is still broken in v2.12.1, consider https://github.com/Icinga/docker-icinga2.

**Comment by Al2Klimov** [comment]
If this is still broken with the latest version and Docker isn't a suitable alternative, feel free to reopen this (and explain why Docker isn't a suitable alternative).
