### ISSUE TITLE
ca-proxy certificate request signing replication

### ISSUE THREAD

**Issue by Gammenon** [Icinga/icinga2#6788]
CA-Proxy requests signing should be synct between masters. (icinga2 ca sign/list ...)

## Expected Behavior

- A request comes up the line: agent -> satellite (cluster, 2 nodes) -> master (cluster, 2 nodes)
- On both masters i see the outstanding signing requests.
- the request is signed on master node 1
- master node 2 also "detects" this and marks the list entry as signed.

**new request arrives**
```
MASTER_01
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
8d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT |        | CN = new-host01.tld

MASTER_02
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
8d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT |        | CN = new-host01.tld

SATELLITE_01
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
8d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT |        | CN = new-host01.tld

SATELLITE_02
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
8d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT |        | CN = new-host01.tld
```
**request was signed**
```
MASTER_01
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
8d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT | *      | CN = new-host01.tld

MASTER_02
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
8d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT | *      | CN = new-host01.tld

SATELLITE_01
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
8d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT | *      | CN = new-host01.tld

SATELLITE_02
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
8d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT | *      | CN = new-host01.tld
```

## Current Behavior
when e certificate is signed on master node 1 only this an the currently attached satellite will be aware of the signing. The other master and satellites won't get that info.

- A request comes up the line: agent -> satellite (cluster, 2 nodes) -> master (cluster, 2 nodes)
- On both masters i see the outstanding signing requests.
- the request is signed on master node 1
- master node 2 did not know that and the list item stays unsigned

**new request arrives**
see above...
**request was signed**
```
MASTER_01
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
1d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT | *      | CN = new-host01.tld

MASTER_02
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
1d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT |        | CN = new-host01.tld

SATELLITE_01
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
1d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT | *      | CN = new-host01.tld

SATELLITE_02
Fingerprint        | Timestamp                | Signed | Subject
-------------------|--------------------------|--------|--------
1d3380f8a770cc81b2 | Nov 20 10:11:41 2018 GMT |        | CN = new-host01.tld
```
Sometimes, I think, when the second satellite will change der connection to another master node he will get aware of the signing as well.

## Possible Solution
Somehow sync the information within the signing request (-files).

## Context
We check the outstanding signing requests on both master nodes to be aware of unsigned requests.
Right now we will get different results from the checked (master) nodes, where one is technically wrong, because the signing was done and the connection will be accepted from both master (and satellite) nodes.

Just as additional question, can you explain, why and when a signed request ist removed from the list again? After some time the quests (which means the files) disappear and I wasn't able to figure out the logic behind this behaviour.

**Comment by dnsmichi** [comment]
There's only one master which holds the private CA key for signing the requests. Therefore the secondary master may have the CLI commands available, but those are not working similar to when invoked on a satellite or client.

I don't see a necessity to sync such read-only information to the secondary master. Also not for the reason as it exposes security relevant details from the primary CA master to the secondary master.

For the cleanup mechanism - stale unsigned and already signed requests are removed after 7 days. This is to ensure that retained and already working clients don't flood the directory with hundreds of files on disk. Keep in mind that this mechanism is not for audit logging nor preserves a history/inventory for signed CSRs. This is what #5556 is for requiring sponsors.

**Comment by Gammenon** [comment]
Ah, ok. I see your point. In this case the possibility to check the list on the secondary master is somehow missleading (at least for me :) ). On the other hand and in terms of a cluster and high availability, perhaps a mechanism should nevertheless be thought about here. Currently, the failure of node 1 would mean that no new hosts can be signed until it is restored.

So for now we will only check for unsigned requests on the first node.

**Comment by dnsmichi** [comment]
I do understand the intention, but copying the private CA key to a different host is something which shouldn't happen for obvious reasons. Syncing the "CA signing state" between cluster nodes is something I'd like to avoid also for performance reasons. A better approach would be to store this information somewhere else, external in a database or so (as discussed in the past with @lippserd @bobapple).

**Comment by Gammenon** [comment]
Thank you for the explanation. For now I'm fine with this background.
