### ISSUE TITLE
Attribute 'max_check_attempts': Value must be greater than 0

### ISSUE THREAD

**Issue by lxf1992521** [Icinga/icinga2#6789]
Icinga2 version: 2.10.2
System: CentOS 7.3
package: icinga2-2.10.1-1.el7.icinga.x86_64

When I create Host with icinga2 API, I got this error:"Attribute 'max_check_attempts': Value must be greater than 0".

After search, I found this issue https://github.com/Icinga/icinga2/issues/4832.

But what the problem is: How can I achieve run check command only once when every check interval ?
This's means: run check command with no retry with any return state.

**Comment by dgoetz** [comment]
`max_check_attempts = 1` will run the check once.

**Comment by dnsmichi** [comment]
That's by design, when a state changes to NOT-OK to continue retrying the checks. Setting max_check_attempts to 1 will immediately lead into a HARD state and be your desired behaviour.

For future questions, please head over to the community channels.
