### ISSUE TITLE
satellite zone with two endpoint have config sync problem, only one has host/service config.

### ISSUE THREAD

**Issue by lxf1992521** [Icinga/icinga2#6793]
Version: 2.10.2
System: CentOS 7.3

My scene:
- master zone with two endpoint(host_m1, host_m2), all config define zone.d directory
- satellite zone with two endpoint(host_s1, host_s2), parent zone is master, accept config sync and remote check
- client zone(host_s1, host_s2,.....), parent zone is  satellite, allow remote check.

The problem is: if I add a host object in master's zone.d/satellite/host_s1.conf, this config will only sync to host_s1 in satellite zone, host_s2 has no config.

If I stop host_s1, host_s2 still has no config about host_s1.conf, then reload host_s2, it has.

if I start host_s1, then delete host_s1.conf in master zone, host_s1 will also delete, but host_s2 will not.

so, two endpoints in satellite zone, load-balance and high-availability not working !!!

**Comment by dnsmichi** [comment]
Please fill in the issue template, including configuration snippets and (debug) logs from your analysis. Especially zones.conf from all involved instances will be interesting.

**Comment by lxf1992521** [comment]
thank rapidly reply, i have using icinga 4 years starting with 2.3.0 version, will not make low-level mistakes.

The primary is: if satellite zone have two endpoints, they will not load-balance and high-availability.

here is the master zone.conf: /etc/icinga2/zones.d/master/zones.conf
————————————————————————————————————
object Endpoint "host_s1" {
	host = "host_s1"
}
object Endpoint "host_s2" {
	host = "host_s2"
}
object Zone "satellite" {
        endpoints = [ "host_s1", "host_s2" ]
        parent = "master"
}
————————————————————————————————————

by the way, i do all create/delete operate by API.

**Comment by dnsmichi** [comment]
> here is the master zone.conf: /etc/icinga2/zones.d/master/zones.conf

Why is this configuration snippet located in `zones.d`? This will cause trouble on the secondary master.

**Comment by lxf1992521** [comment]
sorry, expression is not clear, master(host_m1, host_m2) have same zones.conf: /etc/icinga2/zones.conf.

/etc/icinga2/zones.d/master/zones.conf : this file is config sync  with master endpoint, which tell them children zone infomation.

**Comment by dnsmichi** [comment]
Ok, then please prove this by debug logs and a taken example host/service. Also include runtime states from the REST API.

> The primary is: if satellite zone have two endpoints, they will not load-balance and high-availability.

**Comment by lippserd** [comment]
Closed because the lack of feedback. If you still have problems, please open a new issue with all the details we ask for.
