### ISSUE TITLE
Roadmap  / Reporting

### ISSUE THREAD

**Issue by sqanto** [Icinga/icinga2#6804]
Hello 

Sorry i know its not the right Place to ask this kind of Question but i was not sure where it is. 

I am looking for are propper reporting tool in icinga2 i found jasper but its not supporting  anymore and feels like over Engineering.

Than i found this awesome Video https://youtu.be/H0873evMP70?t=959  
And i was very happy to hear that are new reporting module is coming. 

My Question is have you somewhere are Roadmap  that we can checkout when its coming?

Thanks and Awesome work 

Greetings

**Comment by dnsmichi** [comment]
Yep, the community channels fit better for this.

There is a reporting module in the making scheduled for the coming months, future announcements will happen on https://icinga.com/blog and related (social media) channels.

Cheers,
Michael
