### ISSUE TITLE
ElasticSearch Writer - Limit of total fields in index

### ISSUE THREAD

**Issue by devopstt** [Icinga/icinga2#6805]
## Expected Behavior
Dont add a new fields for every single perfdata label. Maybe it would be a better idea, to write down the labels as value with a static field like "perfdata".

## Current Behavior
Icinga2 creates the perfdata label as new field in ES. This leads to a huge number of fields. Especial if the output of a plugin has an effect on the performance label, like in check_disk.

## Possible Solution
Write down perfdata labels as a value. Not sure how we can avoid a breaking change.

## Steps to Reproduce (for bugs)
1. Add check_disk service to a host
2. enable ES Writer feature
3. If you have many mount points (not very uncommon with docker, for example), you get a new field in ES for every mount mount. In large environments you will easily end up with thousands of fields.

## Context
ES can only handle 1000 different fields as default. You can increase the limit, but this will only shift the issue to a later moment. It is also very hard to handle the different perfdata labels in Grafana for example, because I can not just get all perfdata labels for a specific host. With template variables I could query all values with perfdata for a specific host. This is not possible with the current field-solution. See also my issue on the grafana module https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/141#issuecomment-439081681

## Your Environment

* Version used (`icinga2 --version`): r2.10.2-1
* Operating System and version: Ubuntu 18.04.1 LTS - Kernel: 4.15.0-36-generic
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification elasticsearch
* Icinga Web 2 version and modules (System - About): 
   * Icinga Web 2 Version 2.6.1
   * grafana 1.3.1
   * monitoring 2.6.1

**Comment by dnsmichi** [comment]
I don't really know how good or bad Elasticsearch/Lucene can be used as time series database. There is no clear path visible on the horizon, especially for data retention. Before changing anything here, I will wait how well this develops with the beats ecosystem - especially when breaking schema changes come into play.

**Comment by wols** [comment]
ES is the preferred solution in my daily work. I consider the [mapping-limit-settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#mapping-limit-settings) in a separate Icinga2 mapping. Also the [icingaweb2-module-grafana](https://github.con/Mikesch-mp/icingaweb2-module-grafana) is suitable for me [now](https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/188) - Grafana uses the Icinga2 ES index via own datasource.

My plan B, but not my wish (who ElasticsearchWriter sees nothing on the horizon): status + perfdata -> Logstash -> ES

**Comment by devopstt** [comment]
Thanks for your thoughts @wols 
Logstash should work. I think an Ingest Pipeline is even better. I will give it a try later. But I dont think I can publish a solution this year.
If you allready have a working example with a logstash filter, please let me know.

**Comment by lippserd** [comment]
Unfortunately we neither have a solution for this nor is it on our roadmap. If you come up with a possible solution which does not break existing setups, feel free to open a new issue.
