### ISSUE TITLE
Windows check_memory never gets critical

### ISSUE THREAD

**Issue by idandr** [Icinga/icinga2#6810]
## Expected Behavior

When free memory passes critical threshold, status and output should change to CRITICAL.

## Current Behavior

If a warning threshold is given, the check never changes to a crtitical status.

## Possible Solution

As far as I understand the code in master, one should check for critical threshold first. At the moment, warning threshold is checked first and if the condition is met, the check for critical threshold is never reached. The same conditions are used in check_swap, so it is affected too, probably.

## Steps to Reproduce (for bugs)

1. Set a warning threshold that is above free memory to get a critical status:
    > .\check_memory.exe -u mb -c 55%
    MEMORY CRITICAL - 52.8615% free| 'memory'=17321.4MB;;18022.1525;0;32767.5
2. Add a warning threshold:
    > .\check_memory.exe -u mb -c 55% -w 60%
    MEMORY WARNING - 52.7642% free| 'memory'=17289.5MB;19660.529999999999;18022.1525;0;32767.5

Status changes from critical to warning instead of staying critical.

**Comment by mcktr** [comment]
Also visible in check_swap.

```
.\check_swap.exe -u mb -w 90%
SWAP WARNING - 85.7978% free | 'swap'=1027MB;1077.3;;0;1197

.\check_swap.exe -u mb -w 90% -c 95%
SWAP WARNING - 87.9699% free | 'swap'=1053MB;1077.3;1137.1499999999999;0;1197

.\check_swap.exe -u mb -w 10% -U
SWAP WARNING - 12.782% used | 'swap'=153MB;119.7;;0;1197

.\check_swap.exe -u mb -w 10% -c 11% -U
SWAP WARNING - 12.782% used | 'swap'=153MB;119.7;131.66999999999999;0;1197
```
