### ISSUE TITLE
Problem if using same variable in CheckCommand and EventCommand

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga2#6818]
## Expected Behavior

If using the same named variable in checkcommand and eventcommand (e.g. to pass a filename), the value in the variable of the eventcommand should not been overwritten. 

## Current Behavior

We defined a checkCommand to start a PowerShell-Script on Windows agents. The file name is passed to the command via variable "powershell_script". We use the same for the eventcommand. Every snippset is rendered by the director.

This is the defination of the checkcommand:
```
object CheckCommand "powershell" {
    import "plugin-check-command"
    command = [
        "C:\\\\Windows\\\\system32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe"
    ]
    arguments += {
        "-ServiceAttempt" = {
            order = 4
            required = true
            value = "$service.check_attempt$"
        }
        "-ServiceState" = {
            order = 2
            required = true
            value = "$service.state$"
        }
        "-ServiceStateType" = {
            order = 3
            required = true
            value = "$service.state_type$"
        }
        "-command" = {
            order = 1
            required = true
            value = "$powershell_script$"
        }
        ";exit" = {
            order = 99
            required = true
            value = "$$LASTEXITCODE"
        }
    }
}
```

this is the eventcommand:
```
object EventCommand "SetCRLKey" {
    import "plugin-event-command"
    command = [
        "C:\\\\Windows\\\\system32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe"
    ]
    arguments += {
        "-command" = {
            order = -1
            required = true
            value = "$powershell_script$"
        }
        ";exit" = {
            order = 99
            required = true
            value = "$$LASTEXITCODE"
        }
    }
    vars.powershell_script= "C:\\\\icingascripts\\\\SetCRLKey.ps1"
}
```

this is the service: 
```
apply Service "check_xy_http" {
    import "template_generic-service_powershell"

    max_check_attempts = "1"
    check_interval = 3m
    retry_interval = 0s
    enable_event_handler = true
    event_command = "SetCRLKey"
    assign where host.name == "ServerXX"
    vars.grafana_graph_disable = true
    vars.powershell_script = "C:\\\\icingascripts\\\\check_xy_http.ps1"

    import DirectorOverrideTemplate
}
```

With this configuration icinga don't starts the script `C:\\\\icingascripts\\\\SetCRLKey.ps1` defined in the eventcommand. Instead the eventcommand starts the same script defined in the checkcommand again. 

If the variables are named diffrent. e.g. `vars.powershell_script` in the checkcommand and `vars.powershell_script_event` it work fine. 

I tested this also on Linux by using echo in the bash script. It's the same behaviour:
```
object CheckCommand "test_check" {
    import "plugin-check-command"
    command = [ "/etc/icingascripts/test.sh", "$powershell_script$" ]
    vars.powershell_script = "Test - Check"
}

object EventCommand "test_event" {
    import "plugin-event-command"
    command = [ "/etc/icingascripts/test.sh", "$powershell_script$" ]
    vars.powershell_script = "Test - Event"
}
```

## Possible Solution

If this is a wanted behaviour, a hint in the docs would be nice :-). 
Or fix it, that it is possible to use the same named variable in event- and checkcommands. 

## Steps to Reproduce (for bugs)

1. Write a script with an ouput. 
2. Create a check- and a eventcommandlike and a service like above
3. provoke a state change of the service. Like using "Exit 2" in the script. 
3. look at the logs when the icinga starts the eventcommand and whatch for the Output.

## Your Environment

* Version used (`icinga2 --version`): 2.10.2
* Operating System and version: CentOS 7.5 and Windows Server 2016

**Comment by dnsmichi** [comment]
The macro resolver doesn't care about its context, e.g. it won't divide a custom variable from the scope of an Event, Notification or Check Command object. If you fall into the trap of using a custom variable with the same name for different purposes, design and use a different naming schema. 

I don't think that this is a bug, nor would I updated the documentation in this regard. A better fit would be a small tutorial or howto.

**Comment by stevie-sy** [comment]
In my eyes everything is appreciated. I think we should prevent other people to look many hours or days, why the eventcommand don't work correctly - like me the last days. And it was such a simple thing: use different variables to pass the script name. A tutorial or howto would is also a good idea. Like you prefer.

**Comment by dnsmichi** [comment]
If you have your own private blog, blog about it. Put such questions onto the community forums, and discuss with others. Create a small howto based on your real installation, tweet and share it.

My main point is that us developers cannot do much about it, and I would not want to become the documentation as bloated as for every specific use case.

**Comment by stevie-sy** [comment]
Ok, For the Moment I'll document this internal.

**Comment by ops-bitmotive** [comment]
@stevie-sy I think the solution here is a simple `"$this.powershell_script$"`. 

As long as you're defining `vars.powershell_script` on the service and referencing it with `"$powershell_script$"` in the EventCommand, the resolver will pull that value from the Service object because Service objects are always checked _before_ Command objects. This is described in https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#evaluation-order. Essentially what you have with `vars.powershell_script= "C:\\\\icingascripts\\\\SetCRLKey.ps1"` on your EventCommand becomes is a default value. This value will only ever be used if the _Service does not define it_. 

You can use a scope specifier like `this.` to work around this and get the effect you want. (I'm honestly not sure how to do that with Director, sorry.)

**Comment by b33rcity** [comment]
@stevie-sy Have a read of https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#evaluation-order. This is actually doing exactly what you're telling it to.

`"$powershell_script$"` will always resolve to the value set on the service. If you set a value for the same variable on the Command object (any type), that becomes a _default_ value, as Command objects are always referenced last (not counting Globals). 

Change your event command to use `this.powershell_script` instead (no macro syntax) and it should behave as you expected.
