### ISSUE TITLE
New field in Event Stream Type: Notification

### ISSUE THREAD

**Issue by eprogres** [Icinga/icinga2#6824]
For my point of view new field "notification_method" in Notification Event Stream structure would be very nice feature.
We made some periodic analytics in Kibana about our monitoring performance and we really need to divide notifications statistics based on notification method (sms, email, growl etc). Now we have as many events as notification methods for one problem - and that distorts our analysis.

#current Notification Event structure
Name | Type | Description
type | String | Event type Notification.
timestamp | Timestamp | Unix timestamp when the event happened.
host | String | Host name.
service | String | Service name. Optional if this is a host notification.
users | Array | List of notified user names.
notification_type | String | $notification.type$ runtime macro value.
author | String | $notification.author$ runtime macro value.
text | String | $notification.comment$ runtime macro value.
check_result | CheckResult | Serialized CheckResult value type.

we need new field
notification_method | String | script or method used to make this notification

**Comment by dnsmichi** [comment]
`method` doesn't exist for a notification object, would the `command` object name reference fulfil that?

**Comment by eprogres** [comment]
YES, "command" would be perfect
