### ISSUE TITLE
Configurable plugin output charset

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#6832]
Most plugins (especially on \*nix) yield UTF-8 encoded strings. But some work with different encodings, e.g. #5395.

What about a few new properties:

* Command#charset
* Service#charset
* Host#charset
* IcingaApplication#charset

Every of them is a string telling the plugin output charset – either *utf8*/*latin1*/*cp866* or *native* (UTF-8 on \*nix and... I-don't-know-but- @LordHepipud -may-know on WinNT).

Once an active check result is computed on the checking node, the output is re-coded to UTF-8 immediately.

**Comment by Al2Klimov** [comment]
As @LordHepipud explained to me (offline):

The plugin author may (but is not likely to) explicitly set the codepage inside the binary (or PS script). If they don't do it (like us), the codepage defaults to the global one: Latin1 on a DE system, 866 on a RU one, etc.. So *native* would be the the global codepage.

**Comment by lippserd** [comment]
Our strategy is to support/use UTF-8 only. Also this would be a burden for users to configure their charsets right. I'll close this.

**Comment by Al2Klimov** [comment]
What a luck (not!) that

1. Windows' default charset/codepage depends on the OS' initial language
2. All exes/scripts/... use that codepage by default
3. Literally none of the Windows check plugins there even care about codepages
4. We, team Icinga, are "the bad example" itself by using `int wmain(int, WCHAR**)` in our plugins and not caring about codepages either.

What exactly would be wrong in auto-detecting the OS' default codepage and re-coding the plugin output from that to UTF-8 just after reading the check result? This wouldn't be any burden for users nor plugin authors.

**Comment by dnsmichi** [comment]
Please move this into a meeting next time. Such discussions shouldn't be done here.
