### ISSUE TITLE
Dependency doesn't always mark service as unreachable

### ISSUE THREAD

**Issue by blodan** [Icinga/icinga2#6834]
```
apply Dependency "ops-elasticsearch" to Service {

    parent_host_name = "parent_host"
    parent_service_name = "parent_service"
    
    states = [ OK ]
    
    ignore_soft_states = false
    disable_checks = true
    disable_notifications = true
    
    assign where service.name == "graylog-api.mydomain.net"
    assign where service.name == "kibana.mydomain.net"
}
```

With the above service dependency, if the graylog-api.mydomain.net or kibana.mydomain.net service is executed before the parent_service is executed they are not marked as either active = 0, paused = true

For example with this flow:
1. Everything is up
2. The real service goes down
3. graylog-api.mydomain.net check is executed and is put in soft warning
4. parent_service is executed and put in soft warning and the dependency is from now enforced
5. both kibana.mydomain.net and graylog-api.mydomain.net service checks are disabled
6. There is now no way to see that the graylog-api.mydomain.net has been disabled or is unreachable because its in a soft warning state and the check isn't executed anymore, and the last_reachable attribute is still set to true as the last executed check was still reachable.

## Expected Behavior
Service that has been disabled through a dependency should have an attribute saying it is disabled, such as active = 0 or paused = true

## Current Behavior
active = 1 and paused is false

## Possible Solution
change active to 0 or paused to true when a dependency disabled_check = true is enforced on a service

## Context
I can't create a proper dashboard and alert bot with the data from the API as I can't see when a check is disabled or not by a dependency

## Your Environment
Version: r2.9.1-1

**Comment by dnsmichi** [comment]
`active` and `paused` are Icinga 2 internal object states and only important for HA and active events. There's no relationship with dependency and the reachable logic here. The attribute you're looking for is `last_reachable` exposed by the API for host/service URL endpoints.

**Comment by lippserd** [comment]
You may also use the Web 2 API w/ `service_is_reachable=0&format=json` as query parameter.

I'll close this.
