### ISSUE TITLE
Configure Manual Notification Only

### ISSUE THREAD

**Issue by Bassysta** [Icinga/icinga2#6835]
Hi.
I want to configure notification to send mail only when i press the button "Send Notification" on icingaweb2 service page, my goal is to be able to send a mail to my ticket system when i need it, i not need frequently automatic notification. Is that possible? i try to search around but with not luck, can you put me in the right way?

Tnks for your help.

**Comment by slalomsk8er** [comment]
Hi,

Icinga uses scripts to send the mails. You can filter, process and format data to your heart's content there. Your goal is even easier as you can just remove all but custom from the template:

```
template Notification "generic-notification" {
  interval = 15m

  command = "mail-service-notification"

  states = [ Warning, Critical, Unknown ]
  types = [ Problem, Acknowledgement, Recovery, Custom, FlappingStart,
            FlappingEnd, DowntimeStart, DowntimeEnd, DowntimeRemoved ]

  period = "24x7"
}
```

Care full, you also need to check the objects that inherit this template - test it well.

BTW, this is not a issue and you can find all the details in the documentation https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#alert-notifications - if you need help with understanding the documentation, https://monitoring-portal.org/woltlab/index.php?board/117-icinga-2/ is a great place to ask questions.

Regards
Dominik

**Comment by lazyfrosch** [comment]
You can filter by `types` `Custom` then.

It would be better to ask those kind of questions in a user forum: https://icinga.com/support/#community (scroll down to community support)

**Comment by Bassysta** [comment]
Thanks all for your time, i'll try slalom tip and, if i not figured out, i'll make this question to community. 

Thanks again.
