### ISSUE TITLE
Support host and service templates to send variables to Elasticsearch

### ISSUE THREAD

**Issue by wols** [Icinga/icinga2#6837]
It would be great if we could select host.vars and service.vars additional sent to Elasticsearch using the [ElastichsearchWriter.](https://github.com/Icinga/icinga2/blob/master/doc/09-object-types.md#elasticsearchwriter) The idea was inspired by #6213.

This should follow the template logic of [InfluxdbWriter](https://github.com/Icinga/icinga2/blob/master/doc/09-object-types.md#objecttype-influxdbwriter):
```
object ElasticsearchWriter "elasticsearch" {
  # other options...

  host_template = {
    tags = {
      location = "$host.vars.geodata$"
    }
  }
  service_template = {
    tags = {
      snmp_oid = "$service.vars.snmpv3_oid$"
    }
  }
}
```
See also [Tags vs Fields](https://discuss.elastic.co/t/tags-vs-fields/24014)

**Comment by lippserd** [comment]
Unfortunately there are no plans to implement this at moment. If you're still interested in this feature, please contact us via https://icinga.com for sponsoring.

**Comment by ngoeddel-openi** [comment]
Since we also need this feature now we are working on implementing this in a fork and want to create a pull request if we are ready.
