### ISSUE TITLE
Icinga2 Compatibility matrix doc

### ISSUE THREAD

**Issue by Copis** [Icinga/icinga2#6838]
Hi Team,

In some situations we need to verify if icinga2 is comatible or not with some sistems. In that case i was seeking for compatibility matrix for icinga2 builds and OS versions but i cannot find any information.

I think it was great to have a compatibility matrix page in documentation to check.

Regards,

**Comment by mcktr** [comment]
Hi,

there is a support matrix, located here: https://icinga.com/support/ (you need to scroll down a bit).

Is this what you needed? 

Kind regards
Michael

**Comment by lazyfrosch** [comment]
There is also:
https://github.com/Icinga/icinga2/blob/master/doc/21-development.md

Could you specify your question?

**Comment by Copis** [comment]
Hi Team, 

Thanks for your fast response, I need to confirm if icinga2 is compatible with Windows Server 2016 Core (no GUI) but according requirements i cannot validate this.

In https://icinga.com/support/ i can see compatibility with 2008 and 2012, i tested myself icinga2 on Windows Server 2016 and works as expected but never used icinga2 agent into Windows Core versions.

In any case i was asking for full compatiblility matrix like minim os, icinga agent version and recomended versions for each os like these:

OS   Version \ Icinga Agent | Minimum   version | Recommended   version
-- | -- | --
Windows   server 2003 | Unsupported | NA
Windows   server 2008 | 2.6.3 and   above | 2.10.2
Windows   server 2012 | 2.7.0 and   above | 2.10.2
Windows   server 2012 Core | ??? | 2.10.2
Windows   server 2016 | 2.9.0 and   above | 2.10.2
Windows   server 2016 Core | 2.9.0 and   above | 2.10.2
Windows   server 2019 | Unsupported | NA
Windows   server 2019 Core | Unsupported | NA

**Comment by mjbrooks** [comment]
The matrix on /support seems to be outdated. I also think the format @Copis posted as an example is a bit easier to read.

**Comment by dnsmichi** [comment]
@bobapple was so kind to update the matrix including 2016. 

In terms of "core" and no gui - I'd say if you can manage Windows without a GUI, it should work without the graphical setup wizard. There's no dev I know who will be able to support you in case of troubleshooting etc. though.

Server 2019 needs to be tested and added, separate task.

In terms of other questions and discussions, please continue in icinga/icinga-packaging. This is the wrong place.
