### ISSUE TITLE
r2.10.2-1 downtime clearing on restart

### ISSUE THREAD

**Issue by jon2jay** [Icinga/icinga2#6839]
Hello,
Just a quick introduction, I have looked at all previous problems with such, and was unable to find a solution -- any which were suggested have not worked.

This has been reported previously by users, but it still appears to be re-occurring (in my case) I am hoping to get further insight towards resolution. Besides this Icinga has been Excellent. Amazing platform thusfar.

 icinga2 -V
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.1.3.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Icinga & Icingaweb2 have been installed via the official repos. Additionally, I do have director installed (only used for the excellent 'Inspect' feature for hosts. And this is a simple single node setup w/ DB local.

Thank you in advance.

**Comment by jon2jay** [comment]
The downtime conf's are being added in /var/lib/icinga2/api/packages/_api/overwatch.XXX.com-1519335553-1/conf.d/downtimes

icinga2 daemon -C -x notice shows the conf files being polled. I do see this, but unsure if its an actual issue:
[2018-12-14 13:33:01 -0500] warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!

**Comment by dnsmichi** [comment]
- How are these downtimes being created/managed?
- Is there anything visible in Icinga 2's log itself which would indicate a deletion of that downtime?
- Are you using any additional ScheduledDowntime objects?
- Is the data deleted/missing in Icinga Web 2 only, and as such, missing in the IDO database?

**Comment by lippserd** [comment]
I'll close this ticket because of the lack of feedback. If you still face this problem, please open a new issue with the additional details requested by dnsmichi and provide a more precise error description.

**Comment by lippserd** [comment]
#6879 may be related.
