### ISSUE TITLE
icinga2 daemon: deprecate -d

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#6845]
AFAIK most (if not all?) OSes we support have systemd which does the daemonizing stuff for us.

Without -d there would be less to maintain and to worry about in e.g. #5230.

**Comment by dnsmichi** [comment]
RHEL6 & SLES11 do not have it, and those are just are officially supported platforms. There's other distributions around (*BSD, Gentoo) which allow to run without Systemd. Debian 9 also allows to fall back to Sysvinit. 

Up until EOL of the major distributions, we cannot remove this. The soonest may be 2020 with el6 becoming EOL, but still there's no guarantee here. Therefore closing this.

**Comment by Al2Klimov** [comment]
I'm afraid it's even worse on *BSD as (I heard that) systemd uses Linux-specific APIs.
