### ISSUE TITLE
Expand valid UOMs for InfluxDBWriter

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icinga2#6849]
Hi all, 
I want to start a discussion about the valid UOMs for the InfluxDBWriter.
I know, according to the Nagios Dev Guide, there a several UOMs defined, which are accepted by the InfluxDBWriter. Here and there I am using plugins from centreon-plugins, which sometimes send "invalid" UOMs and so, they are dropped. This results in no PerfData at all and your only note for this are the icinga logs saying "Ignoring invalid Perfdata....".

I have two wishes here:
- expand the UOMs for more datatypes. Referring to the centreon-plugins dev, they don't have a problem with these UOMs (see https://github.com/centreon/centreon-plugins/issues/1117) and InfluxDB.

- a check or sth. else, that we can see directly dropped PerfData. Currently I am using check_logfiles on the icinga log to check for Invalid PerfData.

## Expected Behavior
More UOMs should be accepted from the InfluxDBWriter or at least, only the not supported UOMs should be dropped, but the data itself should go into the InfluxDB

## Current Behavior
The whole performance data entry is dropped which ends in no PerfData at all for this service.

## Possible Solution
See above

## Steps to Reproduce (for bugs)
1. Use a plugin from centreon-plugins with "non nagios UOMs". For excample "/centreon-plugins/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin"
2. Implement it in your Icinga2
3. See the "Ignoring invalid PerfData" entries in the /var/log/icinga2.log
4. See, that your InfluxDB has no PerfData for this Service

## Context
I have to re-write the plugins or filter the UOMs by "filter options" which are given in the plugin itself.

## Your Environment
* icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)
* Ubuntu 16.04

**Comment by cstegm** [comment]
Same issues with the GraphiteWriter. I ran into this, too and we are monitoring our logs "Ignoring invalid PerfData" too. I would prefer that the list of accepted UOMs should be expanded. As the Guidelines for plugins are very old. 

In our case we had issues with common Hardware units:
- W
- V
- A
- rpm
- C = °C

**Comment by N-o-X** [comment]
The valid UoMs have been greatly improved with #7871 in 2.13.0. If you think it's still missing some important ones, please open a new issue for that.
