### ISSUE TITLE
Wrong data on the dashboard

### ISSUE THREAD

**Issue by kolapapa** [Icinga/icinga2#6866]
## Current Behavior

dashboard:
![image](https://user-images.githubusercontent.com/17918689/50443814-ed47b500-093f-11e9-8695-679b6fd1e56f.png)
API:
![image](https://user-images.githubusercontent.com/17918689/50443821-f46ec300-093f-11e9-829a-aa2556decfdb.png)

**When I execute `systemctl reload icinga2`， This wrong data will disappear.**

## Your Environment

```shell
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-862.11.6.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

**Comment by kolapapa** [comment]
I tried it again today and found that it was only when put, it would cause this problem, and then it would be fine to execute `systemctl reload icinga2`

**Comment by dnsmichi** [comment]
Is the object still available in the IDO database?

**Comment by kolapapa** [comment]
yes.
![image](https://user-images.githubusercontent.com/17918689/51608398-4fe99c00-1f52-11e9-8f58-d88a299b547b.png)

when i execute `systemctl icinga2 reload`, everything is ok.
![image](https://user-images.githubusercontent.com/17918689/51608773-5d535600-1f53-11e9-945b-727ca2c3fd55.png)

this is the error page.
![image](https://user-images.githubusercontent.com/17918689/51608386-46f8ca80-1f52-11e9-83c0-774724a2f838.png)


Will it have anything to do with my deletion of the service?
like this:`DELETE https://127.0.0.1:5665/v1/objects/hosts/test1.dev.ops.bj1?cascade=1`

**Comment by dnsmichi** [comment]
Ok, that's the same issues as described in #6012 (which is our tracking issue for activation/deactivation problems like this). I'm linking over there and closing here.
