### ISSUE TITLE
Performance data units "m" and "h" are not interpreted by parser

### ISSUE THREAD

**Issue by ix-dev** [Icinga/icinga2#6867]
Some check plugins return the performance value in minutes. This is not interpreted by Icinga2 and rejected as "invalid perfdata value".

## Expected Behavior
Icinga2 should handle the units "m" for minutes and "h" for hours.

## Current Behavior
Performance values with "m" and "h" units are rejected and the performance value is dropped.

## Possible Solution
Add handling of these time units in PerfdataValue::Parse()

## Steps to Reproduce (for bugs)
Have a check plugin that returns a performance value with unit "m" or "h", e.g., the uptime check in check_nwc_health.

## Context
Imho there is no reason to reject performance values with time units "m" and "h".

## Your Environment
Version used: Icinga2: r2.10.2-1, IcingaWeb2: 2.5.0, Director 1.3.1
Operating Systems: Debian 8

This issue is opened to submit a pull request.

**Comment by wnieder** [comment]
https://www.monitoring-plugins.org/doc/guidelines.html#AEN201 shows the 
(original) definition of performance data. AFAIK this definition hasn't 
been changed ever since.
Valid UOMs contain "s - seconds (also us, ms)" for time measurements 
only. If any plugin outputs minutes, hours, or other units, they'll be 
rejected. You can request the plugin to be changed (or change it 
yourself) to comply with the definitions.


Am 28.12.2018 um 09:51 schrieb ix-dev:

**Comment by ix-dev** [comment]
Well the proposed patch just adds some units to the ones specified in the monitoring plugin guidelines, it does not change anything to the existing UOM.

What is the criterion for a unit to be supported by Icinga2? For example regarding bytes, the unit "GB" is also not defined as UOM but supported by Icinga2.

Of course we can also adjust the check plugins, but imho the proposed additions are safe and the units are widely used.

**Comment by lazyfrosch** [comment]
I guess it will not hurt to "covert" them so seconds.

Question is: Do we re-render the perf-data after parsing the values. Or do we pass the original text anywhere?

**Comment by MarcusCaepio** [comment]
related to #6849 ?

**Comment by dgoetz** [comment]
ref/NC/597391

**Comment by dgoetz** [comment]
As the design ticket by @bobapple is now scheduled for 2.13, can we perhaps fix the windows_uptime check from the Icinga 2 agent plugins earlier?

**Comment by N-o-X** [comment]
This has been fixed with #7871 in 2.13.0
