### ISSUE TITLE
2.10 is unstable (Windows Agent)

### ISSUE THREAD

**Issue by Stefar77** [Icinga/icinga2#6872]
After a couple of days vacation I noticed all Icinga Windows Agents are 'down' with 'Remote Icinga Instance 'xxx' is not connected to 'yyy'
Before the upgrade from 2.8 to 2.10 I never had any issues with reloading or crashing.

## Expected Behavior

It should not crash/hang.

## Current Behavior

2.10.x Agents randomly die and deploying without the sleep(1); patch on FreeBSD kills the master.

## Possible Solution

-

## Steps to Reproduce (for bugs)

1. Keep the agent running a couple of days until it hangs.

## Context

Trying to take vacation....

## Your Environment

^^ This is all the same as my FreeBSD/Director reload issue.

I'll try the latest version, if it fails I may try and downgrade back to 2.8 ...

**Comment by lippserd** [comment]
@Stefar77 since #6901 is merged, could you please test the snapshot packages?

**Comment by Stefar77** [comment]
Removed and completely reinstalled with the latest binary installer and it seems it's stable now.
Sorry for the delay in the reply.
