### ISSUE TITLE
Possible useful check commands

### ISSUE THREAD

**Issue by fpoulain** [Icinga/icinga2#6876]
Hi,

As said in https://icinga.com/docs/icinga2/latest/doc/05-service-monitoring/#create-a-new-plugin, 
"If you have created your own CheckCommand definition, please kindly send it upstream."

I am a very happy user of icinga2 for some years. I created some CheckCommand which, I suppose, may be considered upstream.

### Grep

It is fine to use Icinga to make some sanitary check. I use it e.g. to verify git repos, and to verify consistencies into a given cluster. Grep is useful for this.
```C
object CheckCommand "grep" {
	command = ["grep", "-q"]
	arguments = {
        "pattern" = {
            value = "$pattern$"
            required = true
            skip_key = true
            order = -1
        }
        "file" = {
            value = "$file$"
            required = true
            skip_key = true
        }
    }
}
```
Example of use:
```C
apply Service "Check mailname" {
  import "generic-service"

  check_command = "grep"
  command_endpoint = host.vars.client_endpoint

  vars.pattern = "^example.com$$"
  vars.file = "/etc/mailname"

  assign where host.address && !host.vars.external
}
```

### check zone

For bind9 users. Bind9 comes with a zone verificator.
```C
object CheckCommand "checkzone" {
	command = ["/usr/sbin/named-checkzone", "-S", "fail", "-k", "fail", "-M", "fail", "-m", "fail", "-n", "fail"]

	arguments = {
		"fqdn" = {
			value = "$fqdn$"
			description = "fqdn"
			required = false
            skip_key = true
            order = -1
		}
		"file" = {
			value = "$file$"
			description = "fichier de zone"
			required = true
            skip_key = true
		}
	}
}
```
Example of use:
```C
apply Service "Zone " for (zone => config in host.vars.zones) {
  import "generic-service"

  check_command = "checkzone"
  command_endpoint = host.vars.client_endpoint

  vars.view = config.view
  vars.file = config.file
  vars.fqdn = config.fqdn
}
```

Using named-checkconf may also be useful.

### Whois

check_whois comes with monitoring plugins contrib into debian.

```C
object CheckCommand "whois" {
	command = [ PluginDir + "/check_whois" ]
	arguments = {
        "fqdn" = {
            value = "$fqdn$"
            required = true
            skip_key = true
        }
    }
}
```
Example of use:
```C
apply Service "Domaine " for (zone => config in host.vars.zones) {
  import "generic-service"

  check_command = "whois"
  command_endpoint = host.vars.client_endpoint

  vars.fqdn = config.fqdn
  assign where config.view == "external"
}
```

### Sudo

I don't have code, but defacto I developed some specifics CheckCommand in order to use sudo. It is helpful for some plugin which may be executed by different users depending on the context. So it would be nice if possible to have a way to switch any CheckCommand into a sudoed one.

**Comment by fpoulain** [comment]
> You should create one PR for each CheckCommand, every new CheckCommand needs documentation next to its definition. With each in its separate PR we can more easily review your changes and suggest edits.

I Will be happy to do so. A criticism I see is that those CheckCommand are based on shell tools rather than monitoring plugins. As a consequence, there is only one compliant return code: 0. It isn't actually a problem for me, but it is a limitation. Maybe using negate could be a workaround.

**Comment by Crunsher** [comment]
I see, if thresholds would make sense for check, they should be supported and if a plugin can fail (e.g. grep returning nothing) I'd expect something other than OK.

The issue with that being that we often end up with a wrapper script to support this :/

But this is best discussed for each command by itself ^_^

**Comment by dnsmichi** [comment]
Note for `whois` checks: This literally is dead with the European GDPR and missing public APIs. 

In terms of the shell commands, I would appreciate a plugin skeleton which implements better parameter handling, output parsing and exit code calculations. This plugin can then be published on GitHub/Icinga Exchange and linked from the ITL docs then.

**Comment by dnsmichi** [comment]
@fpoulain any updates on this? Meanwhile I've improved the plugin docs: https://icinga.com/docs/icinga2/latest/doc/05-service-monitoring/

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.
