### ISSUE TITLE
Which command can i you to check open port?

### ISSUE THREAD

**Issue by lncan** [Icinga/icinga2#6891]
Hi guys, I wanna check open port but don't know which command to excute it? Can you please tell me this. I'm using icinga director module.

**Comment by dgoetz** [comment]
Such questions are better asked in the community channels, but you perhaps want to have a look at check_tcp/check_udp depending the protocol used.

**Comment by lncan** [comment]
> Such questions are better asked in the community channels, but you perhaps want to have a look at check_tcp/check_udp depending the protocol used.

Yeah. Thanks for your reply.
