### ISSUE TITLE
Problem with notification

### ISSUE THREAD

**Issue by Bassysta** [Icinga/icinga2#6895]
Hi.
I'm trying to set up notification using Director, here the screenshot of my configuration:

apply Notification "Service Notification" to Service {
    command = "mail-service-notification"
    period = "Always1"
    zone = "icinga2.local"
    assign where service.enable_notifications == "true"
    states = [ Critical, Unknown, Warning ]
    user_groups = [ "helpdesk" ]
    users = [ "Helpdesk" ]
}

But when i try to send a notification manually from a service page, i receive this on log file:

[2019-01-11 17:43:15 +0100] information/Checkable: Checking for configured notifications for object 'Service_Name'
[2019-01-11 17:43:15 +0100] information/Checkable: Checkable 'Service_Name' does not have any notifications.

What i'm doing wrong?

Tnk for your time.

**Comment by mcktr** [comment]
You must ensure that the assign rule actually applies. Your notification assign rule applies when the `enable_notifications` is set to true. Try to set `enable_notifications` to true in your service object. 

For further questions please join the community channels https://icinga.com/support/ (scroll down to _Community Support_).
