### ISSUE TITLE
API action restart-process fails on FreeBSD

### ISSUE THREAD

**Issue by joachimmathes** [Icinga/icinga2#6898]
If I run the API action `restart-process`, Icinga2 won't restart. The same happens when `curl -k -s -u user:password -H 'Accept: application/json' -X POST \
'https://localhost:5665/v1/config/packages/example-cmdb?pretty=1'` tries to restart Icinga2.

## Expected Behavior
```
curl -k -s -u user:password -H 'Accept: application/json' -X POST 'https://172.17.28.120:5665/v1/actions/restart-process?pretty=1'
```
should restart Icinga2

## Current Behavior
```
curl -k -s -u user:password -H 'Accept: application/json' -X POST 'https://172.17.28.120:5665/v1/actions/restart-process?pretty=1'
```
does not restart Icinga2. Icinga2 log says:
```
[2019-01-16 10:52:38 +0100] critical/TcpSocket: Invalid socket: Address already in use
Context:
        (0) Activating object 'api' of type 'ApiListener'

[2019-01-16 10:52:38 +0100] critical/ApiListener: Cannot bind TCP socket for host '172.17.28.120' on port '5665'.
Context:
        (0) Activating object 'api' of type 'ApiListener'

[2019-01-16 10:52:38 +0100] critical/ApiListener: Cannot add listener on host '172.17.28.120' for port '5665'.
Context:
        (0) Activating object 'api' of type 'ApiListener'
```

## Context
I want to avoid ssh access to Icinga2 master for dedicated hosts, that should be allowed to modify the Icinga2 configuration. As https://icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#configuration-management tells me, access control and authorization via Icinga2 API is the way to go.

## My Environment
* Version used (`icinga2 --version`): `r2.10.2-1`
* Operating System and version: `FreeBSD 11.2-RELEASE-p7`
* Enabled features (`icinga2 feature list`):
  ```
  Disabled features: command compatlog debuglog elasticsearch gelf ido-pgsql influxdb livestatus opentsdb perfdata statusdata syslog
  Enabled features: api checker graphite ido-mysql mainlog notification
  ```
* Config validation (`icinga2 daemon -C`): _is valid_

**Comment by Al2Klimov** [comment]
Dear core devs,

AFAIK `TcpSocket#Bind()` does [`setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, ...)`](https://github.com/Icinga/icinga2/blob/e2169f17f2a1e5fb5a192ea6474fa9cd47451e46/lib/base/tcpsocket.cpp#L93) so this can't happen, can it?

**Comment by dnsmichi** [comment]
https://twitter.com/bsdlme/status/1093889864859336704
