### ISSUE TITLE
Client certificate validation failed

### ISSUE THREAD

**Issue by zevilz** [Icinga/icinga2#6902]
## Expected Behavior
I add icinga clients via ansible playbook with `pki` and `node` commands. I use this a long time.

## Current Behavior
Now i receive error with client certificate validation:
```information/ApiListener: New client connection for identity 'client.com' from [123.123.123.123]:35344 (certificate validation failed: code 18: self signed certificate)```
```warning/ApiListener: No data received on new API connection for identity 'client.com'. Ensure that the remote endpoints are properly configured in a cluster setup.```
I reproduce this manually but same error.

## Steps to Reproduce
Generate new cert for client.com (executed on client.com)
```icinga2 pki new-cert --cn client.com --key /etc/icinga2/pki/client.com.key --cert /etc/icinga2/pki/client.com.crt```

Save new cert (executed on client.com)
```icinga2 pki save-cert --key /etc/icinga2/pki/client.com.key --cert /etc/icinga2/pki/client.com.crt --trustedcert /etc/icinga2/pki/trusted-master.crt --host server.com```

Get ticket on server for client (executed on server.com)
```icinga2 pki ticket --cn client.com```

Add client to server (executed on client.com, deprecated `master_host` parameter has changed to `parent_host`)
```icinga2 node setup --ticket ticket_from_previous_step --endpoint server.com --zone client.com --parent_host server.com --trustedcert /etc/icinga2/pki/trusted-master.crt```

## Environment
Version used: r2.10.2-1 (in all servers)
Operating System and version: Debian 9.6 amd64 (in all servers)
Enabled features (server.com): api checker command ido-mysql influxdb mainlog notification
Enabled features (client.com): checker mainlog notification
Config validation: ok

**Comment by zevilz** [comment]
I reinstalled icinga in server and generate new certs via `icinga2 node wizard`. Now i have this error while generate certs on all client servers (including using wizard).

**Comment by mcktr** [comment]
I am closing here in favor of https://monitoring-portal.org/t/client-certificate-validation-failed/5732. We can come back and reopen here if the analysis show that this is indeed a bug.
