### ISSUE TITLE
BUG : service checks are not refreshed if last check has a timestamp in the future

### ISSUE THREAD

**Issue by ruleant** [Icinga/icinga2#6903]
## Expected Behavior
When a service check is done where the last result is logged in the future, it should still allow to run recheck.
Either automatically (by ignoring the time of the last check in the future), or by allowing to force a recheck (that is actually executed).
At least show an error that the last status update is run in the future, and thus : 
- something is wrong on the client host
- the check status is inaccurate or unrelyable.

## Current Behavior
When a service check, using icinga daemon, is run on a host with date/time in the future, the result of that check is logged with the time of the host. That service is not rechecked until that moment in the future is reached.
Forcing a recheck has no effect (check is not rechecked, status is not updated) 

## Possible Solution
There are a few possible solutions:
- don't use the timestamp of the icinga daemon of the remote host, but the local time of the icinga server, as a timestamp for a status update (the ntp service check should check if there is an ntp offset)
- ignore the timestamp of the last check if it is in the future
- force a recheck if a last status update has a timestamp in the future
- display an error if there is an update with a timestamp in the future

## Steps to Reproduce (for bugs)
1. set the time of a host to a moment in the future (a few hours, fe. 4 hours) 
2. wait until icinga2 does a new service check (using the icinga2 daemon)
3. the status of the check is set to a moment in the future (4 hours from now)
4. icinga2 doesn't update the service check until that moment in the future is reached
5. using force check doesn't initiate a check

## Context
Accidentally, the time of a server was set to a time in the future. On the next service checks for this host, all checks using the icinga2 daemon, where updated with a timestamp in the future, including the ntp check, reporting an ntp offset.
After ntpd corrected the time, these checks were not updated until that moment in the future was reached.
The ntp-offset check/warning was not updated (and remained in warning), even though the problem was resolved (ntpd fixed the time on the remote host).
After forcing a recheck, this check was not executed.

### Client
* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.0-1)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 6.6 (Santiago)
  Kernel: Linux
  Kernel version: 2.6.32-504.8.1.el6.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.2
  Build host: 24f6eee03681

### Server
* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.0-1)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: 695473ceafaf

* Icinga Web 2 version and modules (System - About): 2.6.1

**Comment by MaBauMeBad** [comment]
Related to #6797 ?

**Comment by dnsmichi** [comment]
Thanks, indeed this is discussed in the linked issue already.
