### ISSUE TITLE
ApiUser objects violate security policies because password must be given in clear text

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [Icinga/icinga2#6905]
Corporate security policies, in general, ban the use of clear text passwords, especially on an authenticating server (like the Icinga Master when using the Icinga 2 API and an ApiUser object). Some sort of secure password store must be implementing so that the ApiUser accounts can be created without specifying their passwords in clear text.

## Expected Behavior
It must be possible to create ApiUser accounts with providing the password in clear text in a config file.

## Current Behavior
It is not currently possible to create an ApiUser object without giving the password in clear text. The only possible means of meeting corporate security policies is to use the `password_hash` attribute, which is apparently scheduled for deprecation (based on the removal from the documentation and a new warning in the 2.10.2 release).

```
warning/ApiUser: Attribute `password_hash` for object 'xyz of type 'ApiUser' is deprecated and should not be used.
```

This attribute must be preserved until an alternate means of secure password storage is implemented.

## Workaround
Continue to support `password_hash` until secure server-side password storage for ApiUser is implemented.

## Possible Solution
A simple solution would be to provide a mechanism similar to the Linux /etc/shadow file where the password is stored as a OpenSSL-based hash. This should also be supported in LDAP and AD.

## Context
See abstract above about corporate security policies.

## Your Environment

* Version used (`icinga2 --version`): Icinga 2.10.2
* Operating System and version: All
* Enabled features (`icinga2 feature list`): api
* Icinga Web 2 version and modules (System - About): Not applicable
* Config validation (`icinga2 daemon -C`): See "Current Behavior" above.

**Comment by Al2Klimov** [comment]
@Crunsher This is a dup of #6404, isn't it?

**Comment by Al2Klimov** [comment]
Hello @jwilliams-shadowsoft and thank you for reporting!

If you have strong sec policies, I'd recommend you to use client certs instead. They're even more secure than hashed passwords.

Best,
AK

**Comment by jwilliams-shadowsoft** [comment]
Thanks @Al2Klimov -- I'll check that out and see if that meets my needs. I totally missed that option!

**Comment by jwilliams-shadowsoft** [comment]
I think the issues mentioned in #6404 remain -- and I know there is desire out there to be able to manage ApiUser logins using LDAP/AD as well. So a general strategy here is needed.

**Comment by Al2Klimov** [comment]
You mean... authn backends like e.g. the Icinga Web 2 ones?

**Comment by Al2Klimov** [comment]
@jwilliams-shadowsoft I've outsourced this discussion to #6907.

**Comment by dnsmichi** [comment]
While I agree that a general strategy is needed here, I don't think it is reasonable to create yet another issue for this (and a second one).

I've have removed the `password_hash` capability as its implementation broke many things (refer to the changelog, it also affected customers). Also, it was added by accident into 2.8.2 and does not comply with our feature-only-in-major-releases policy.

#6404 is the tracking ticket, and requires a design spec as well as one willing to sponsor its implementation then. Please continue in there.
