### ISSUE TITLE
Authentication plugins

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#6907]
At the moment one has to store all API users with their cleartext passwords in the Icinga 2 config.

[Not all of the users like this](https://github.com/Icinga/icinga2/issues/6905#issuecomment-456860196) as some would like to manage the users of their whole infrastructure centrally.

My suggestion: **Generic authn/z backends** like already possible e.g. in Icinga Web 2, configurable like any other Icinga 2 object:

```
object AuthnCommand "msad" {
    command = [ PluginDir + "/authn_msad.py", "$url$" ]
}

object AuthnBackend "msad-192.0.2.1" {
    command = "msad"
    vars.url = "ldap://192.0.2.1"
}
```

Icinga 2 would unconditionally invoke `/usr/lib/nagios/plugins/authn_msad.py ldap://192.0.2.1` and communicate with that process via std I/O.

If a user with the credentials `root:123456` can't be authenticated as usual, Icinga 2 sends `"root:123456\n"` and expects either `/(0|[1-9][0-9]*)\n/` with $1 being the amount of seconds `root:123456` doesn't have to be re-validated for or `"-1\n"` in case of an invalid username or password (or an error).

**Comment by dnsmichi** [comment]
This is tracked and part of #6404. Closing as duplicate.

**Comment by Al2Klimov** [comment]
No. I've read #6404 completely and IMO it's all about hashing API credentials. This issue has literally **nothing** to do with hashing, nor even with storing ApiUser objects on disk.

**Comment by dnsmichi** [comment]
>  Discuss this idea as password store with other feature requests.
