### ISSUE TITLE
Export only some hostgroups metrics to influxdb 

### ISSUE THREAD

**Issue by jsensada** [Icinga/icinga2#6909]
Is it possible to export icinga2 metrics to influxdb for only an unique hostgroup?

## Context

We implemented Icinga2 monitoring on a large organization where there are different working groups which are no relation between them. They have restricted access to icinga2web by host groups. One of them request us to export metrics to influxdb in order to install a custom grafana.
 
## Expected Behavior

On the influxdb module configuration shoud be interesting to define a variable to select which hostgroups wants to be exported to the influxdb.

## Possible Solution

On the influxdb module configuration shoud be interesting to define a variable to select which hostgroups wants to be exported to the influxdb.
```
object InfluxdbWriter "influxdb" {
  host = "remoteinfluxhost"
  port = 8086
  database = "icinga2"
  username = "icinga2"
  password = "icinga2"
  host_goups_only = ["workinggroup_hostgroup"]
  host_template = {
    measurement = "$host.check_command$"
    tags = {
      hostname = "$host.name$"
    }
  }
  service_template = {
    measurement = "$service.check_command$"
    tags = {
      hostname = "$host.name$"
      service = "$service.name$"
    }
  }
}
```

## Your Environment

* Version used (`icinga2 --version`): 2.6.2
* Operating System and version: Linux Ubuntu 18.04.

**Comment by dnsmichi** [comment]
There's no plans to restrict written data, you'll either get everything or nothing. Same applies to other metrics writers such as Graphite. I'd suggest to filter these metrics away on the receiver end, or with a proxy in the middle.

**Comment by lippserd** [comment]
There are no plans to support filters in our writers at the moment. But we're open to this if someone is willing to sponsor.
