### ISSUE TITLE
Resetting SIGPIPE for checkcommand child processes

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icinga2#6912]
hi
Duplicating https://monitoring-portal.org/t/sigpipe-in-checkcommands/5801 here, since by now I am pretty sure this is a bug.

## Expected Behavior
A check command called by Icinga2 should behave identical to one called from the cli.
## Current Behavior
In  icinga2/lib/base/application.cpp a handler to ignore SIGPIPE is set, afterwards any process that is forked off inherits this handler. This breaks any check command the depends on a normal SIGPIPE behaviour.

## Possible Solution
After forking, but before exec the SIGPIPE handler should be reset.

## Steps to Reproduce (for bugs)
Call the following script as a check command:
```

#!/bin/bash
trap
exit 0
```

## Context
Check commands that depend on SIGPIPE throw unessary errors / don't terminate in time. 

## Your Environment

* Version used (`icinga2 --version`): r2.10.2-1
* Operating System and version: Debian stretch
* Enabled features (`icinga2 feature list`): api, checker, mainlog

**Comment by dnsmichi** [comment]
Not blocking the signal leaves the child process spawning the processes in a broken state, so this is intentionally blocked. What kind of plugin is executed here that would need to work with SIGPIPE on its own?

**Comment by mphilipps** [comment]
In this case it is part of dmesg check.

```
#!/bin/bash
dmesg_output="$(dmesg)"
first="$(echo "${dmesg_output}" | sed -n 's/^\[ *\([0-9]\+\)\.[0-9]\+].*$/\1/p;q')"
```

What do you mean with "leaves the child process spawning the process in a broken state"?

**Comment by dnsmichi** [comment]
Oh, I just remembered that we had problems with that, and the newly introduced child process spawning the check execution. If you're interested in this, #4867 holds a good analysis (and is one of the reasons why I don't want to change anything in here).

**Comment by mphilipps** [comment]
From what I have gathered while reading #4867 the report was about the communication between the main icinga2 process and the process replacing it. I am not exactly sure which pipe is used for that, but it appears you went with aptly titled "quick&dirty" solution.

In regards my possible solution, I only want the sigpipe handler unset for the check command child process, not all of them. Also in the linked systemd mailing list post ( https://lists.freedesktop.org/archives/systemd-devel/2014-August/021982.html ), it is mentioned that sigpipe is primarily for shell scripts, which check commands tend to be, and that for example the python guys reset sigpipe before they execute something.

**Comment by Al2Klimov** [comment]
Hello @mphilipps and thank you for reporting!

As far as I understand the issue @dnsmichi pointed out is about Icinga 2 itself receives SIGPIPE which isn't desired.

On the one hand Icinga 2 could reset all signals (not just pipe) just before execve(2)ing any plugin.

On the other hand Alexander Wirt [explained](https://www.youtube.com/watch?v=nNkLGp_fyG8) at the OSMC '14 that it doesn't matter whether *you* can execute the plugin successfully – *the monitoring core* must be able to execute it. So I wouldn't rely on any well-known quasi-standards of the shells (especially while they're interactive), but optimize the plugin for it's actual purpose – being run inside Icinga 2 – and set the signals which matter [by myself](https://github.com/Al2Klimov/check_golang_dep/blob/a053c85a222ef39d37359029b4564f096ba76d2c/main.go#L40).

Best,
AK

PS: [Literally all of my own check plugins](https://exchange.icinga.com/Grandmaster) (intentionally) behave completely different while being executed on a terminal – the terminal is a completely different environment than Icinga 2 after all.

**Comment by Al2Klimov** [comment]
By the way I couldn't reproduce your issue:

```
object CheckCommand "pipe" {
        command = [ "/bin/bash", "-c", "trap; exit 0" ]
}
```

```
...
                    "command": [
                        "/bin/bash",
                        "-c",
                        "trap; exit 0"
                    ],
                    "execution_end": 1548960572.945171,
                    "execution_start": 1548960572.936954,
                    "exit_status": 0.0,
                    "output": "",
                    "performance_data": [],
...
```

**Comment by mphilipps** [comment]
> As far as I understand the issue @dnsmichi pointed out is about Icinga 2 itself receives SIGPIPE which isn't desired.

I understand that.


> On the other hand Alexander Wirt [explained](https://www.youtube.com/watch?v=nNkLGp_fyG8) at the OSMC '14 that it doesn't matter whether _you_ can execute the plugin successfully – _the monitoring core_ must be able to execute it. 
Unfortunately I have no sound at work, so that video isn't that useful to me.

> So I wouldn't rely on any well-known quasi-standards of the shells (especially while they're interactive), but optimize the plugin for it's actual purpose – being run inside Icinga 2 – and set the signals which matter [by myself](https://github.com/Al2Klimov/check_golang_dep/blob/a053c85a222ef39d37359029b4564f096ba76d2c/main.go#L40). 

To my current knowledge I can't reset the SIGPIPE behaviour my self. Usually `trap - SIGPIPE` would reset it to the default, but due to how it inherited the handler this just resets it to ignoring it.

> PS: [Literally all of my own check plugins](https://exchange.icinga.com/Grandmaster) (intentionally) behave completely different while being executed on a terminal – the terminal is a completely different environment than Icinga 2 after all.

I just had a glance at your check check_systemd_needrestart check plugin, what do you gain from behaving different?  I find it quite convenient for a locally  called check to behave the same as one run through Icinga.


Also I just run your checkCommand and it does print 'trap -- '' SIGPIPE' for me.

**Comment by Al2Klimov** [comment]
> To my current knowledge I can't reset the SIGPIPE behaviour my self.

Of course you can! It's *your process* after all..

> what do you gain from behaving different?

Conforming to law as easy as possible – for details please consult the manual.

> Also I just run your checkCommand and it does print 'trap -- '' SIGPIPE' for me.

Please could you test both release and snapshot packages (and report the results)?

**Comment by Al2Klimov** [comment]
By the way I agree that it's important to test check plugins before production, but for this I have Docker images with Icinga 2, Icinga Web 2, IDO, InfluxDB, ... for all of my plugins which don't require Windows/BSD/bare metal.

**Comment by dnsmichi** [comment]
Should be re-evaluated after 2.11 has been released.

**Comment by lippserd** [comment]
2.12.0 RC1 outputs:

> trap -- '' SIGPIPE
> trap -- '' SIGXFSZ

**Comment by Al2Klimov** [comment]
@N-o-X Shall we reset all signals to the default for check plugins?

**Comment by lippserd** [comment]
> @N-o-X Shall we reset all signals to the default for check plugins?

A common workflow is to block signals, fork, reset signals and finally to unblock signals.

**Comment by N-o-X** [comment]
> > @N-o-X Shall we reset all signals to the default for check plugins?
> 
> A common workflow is to block signals, fork, reset signals and finally to unblock signals.

Yes please 👍
