### ISSUE TITLE
Checks don't use new address after host is re-created using API

### ISSUE THREAD

**Issue by VtG242** [Icinga/icinga2#6929]
## Issue description
Most of time (except [#6927](https://github.com/Icinga/icinga2/issues/6927)) there is no problem with following procedure:

1) delete host using API:
```
9/02/05 11:50:51
[root@icinga2-master01:~] curl -k -s -u 'xxx:xxx' -H 'Accept: application/json' -X POST -H 'X-HTTP-Method-Override: DELETE' 'https://localhost:5665/v1/objects/hosts/stg2-k8s-worker02.int.na.intgdc.com?cascade=1' | jq .
{
  "results": [
    {
      "code": 200,
      "errors": [],
      "name": "stg2-k8s-worker02.int.na.intgdc.com",
      "status": "Object was deleted.",
      "type": "Host"
    }
  ]
}
```
2) adding host back using API by application usually started from cron - here is debug log from the app:
```
2019-02-05 12:08:32,717 - DEBUG - Icinga2 API create host stg2-k8s-worker02.int.na.intgdc.com
2019-02-05 12:08:32,717 - DEBUG - Request Icinga2 API with args:
{
  'url': 'https://localhost:5665/v1/objects/hosts/stg2-k8s-worker02.int.na.intgdc.com',
  'verify': False,
  'json': {
    'templates': [
      'develop-host'
    ],
    'attrs': {
      'zone': 'na-dev',
      'vars.gdc_subcluster': u'k8s',
      'vars.gdc_groups': [
        'all',
        'k8s'
      ],
      'vars.gdc_type': 'k8s',
      'vars.gdc_services': [
        'cpu-stats',
        'dmesg'
      ],
      'address': '172.26.35.57',
      'enable_notifications': True
    }
  },
  'timeout': 300
}
```

## Expected Behavior
Host is added into icinga2 configuration and for all checks is used the new address - in this case 172.26.35.57.

## Current Behavior
It seems that an old address (172.26.35.215) is used for checks despite of the fact that host object has the new address correctly assigned:
```
19/02/05 14:00:39
[root@icinga2-master01:~] curl -u 'xxx:xxx'  -s -k "https://localhost:5665/v1/objects/hosts/stg2-k8s-worker02.int.na.intgdc.com" | jq '.'
{
  "results": [
    {
      "attrs": {
        "__name": "stg2-k8s-worker02.int.na.intgdc.com",
        "acknowledgement": 0,
        "acknowledgement_expiry": 0,
        "action_url": "",
        "active": true,
        "address": "172.26.35.57",
        "address6": "",
        "check_attempt": 1,
        "check_command": "hostalive",
        "check_interval": 1800,
        "check_period": "",
        "check_timeout": null,
        "command_endpoint": "",
        "display_name": "stg2-k8s-worker02.int.na.intgdc.com",
        "downtime_depth": 0,
        "enable_active_checks": true,
        "enable_event_handler": true,
        "enable_flapping": true,
        "enable_notifications": true,
        "enable_passive_checks": true,
        "enable_perfdata": true,
        "event_command": "",
        "flapping": false,
        "flapping_current": 5.6000000000000005,
        "flapping_last_change": 0,
        "flapping_threshold": 0,
        "flapping_threshold_high": 30,
        "flapping_threshold_low": 25,
        "force_next_check": false,
        "force_next_notification": false,
        "groups": [
          "all",
          "k8s"
        ],
        "ha_mode": 0,
        "icon_image": "",
        "icon_image_alt": "",
        "last_check": 1549370179.01081,
        "last_check_result": {
          "active": true,
          "check_source": "icinga2-satellite02.int.na.intgdc.com",
          "command": [
            "/usr/lib64/nagios/plugins/check_ping",
            "-H",
            "172.26.35.215",
            "-c",
            "5000,100%",
            "-w",
            "3000,80%"
          ],
          "execution_end": 1549370179.010751,
          "execution_start": 1549370174.004499,
          "exit_status": 0,
          "output": "PING OK - Packet loss = 40%, RTA = 0.37 ms",
          "performance_data": [
            "rta=0.373000ms;3000.000000;5000.000000;0.000000",
            "pl=40%;80;100;0"
          ],
          "schedule_end": 1549370179.01081,
          "schedule_start": 1549370174.0041869,
          "state": 0,
          "ttl": 0,
          "type": "CheckResult",
          "vars_after": {
            "attempt": 1,
            "reachable": true,
            "state": 0,
            "state_type": 1
          },
          "vars_before": {
            "attempt": 1,
            "reachable": true,
            "state": 0,
            "state_type": 1
          }
        },
        "last_hard_state": 0,
        "last_hard_state_change": 1549364932.399337,
        "last_reachable": true,
        "last_state": 0,
        "last_state_change": 1549364932.399337,
        "last_state_down": 0,
        "last_state_type": 1,
        "last_state_unreachable": 0,
        "last_state_up": 1549370179.011269,
        "max_check_attempts": 240,
        "name": "stg2-k8s-worker02.int.na.intgdc.com",
        "next_check": 1549371890.991276,
        "notes": "",
        "notes_url": "https://confluence.intgdc.com/display/plat/Host+Status+-+check+description",
        "original_attributes": null,
        "package": "_api",
        "paused": false,
        "retry_interval": 55,
        "severity": 8,
        "source_location": {
          "first_column": 0,
          "first_line": 1,
          "last_column": 48,
          "last_line": 1,
          "path": "/var/lib/icinga2/api/packages/_api/1c0a0907-1d55-4873-b88d-f4edc7d29f28/conf.d/hosts/stg2-k8s-worker02.int.na.intgdc.com.conf"
        },
        "state": 0,
        "state_type": 1,
        "templates": [
          "stg2-k8s-worker02.int.na.intgdc.com",
          "develop-host",
          "generic-host"
        ],
        "type": "Host",
        "vars": {
          "check_interval": 60,
          "enable_pagerduty": true,
          "gdc_groups": [
            "all",
            "k8s"
          ],
          "gdc_services": [
            "cpu-stats",
            "dmesg"
          ],
          "gdc_subcluster": "k8s",
          "gdc_type": "k8s",
          "nrpe_service": true,
          "retry_interval": 55,
          "type": "develop-host"
        },
        "version": 1549364912.727441,
        "volatile": false,
        "zone": "na-dev"
      },
      "joins": {},
      "meta": {},
      "name": "stg2-k8s-worker02.int.na.intgdc.com",
      "type": "Host"
    }
  ]
}
```
Also everything seems to be OK in configuration file:
```
19/02/05 14:01:33
[root@icinga2-master01:~] cat /var/lib/icinga2/api/packages/_api/1c0a0907-1d55-4873-b88d-f4edc7d29f28/conf.d/hosts/stg2-k8s-worker02.int.na.intgdc.com.conf
object Host "stg2-k8s-worker02.int.na.intgdc.com" {
	import "develop-host"

	address = "172.26.35.57"
	enable_notifications = true
	vars["gdc_groups"] = [ "all", "k8s" ]
	vars["gdc_services"] = [ "cpu-stats", "dmesg"]
	vars["gdc_subcluster"] = "k8s"
	vars["gdc_type"] = "k8s"
	version = 1549364912.727441
	zone = "na-dev"
}
```
I have tried to delete and create this host (using API) two times but the result is still the same.
Also reload of icinga didn't help.

UPDATE:
It seems that workaround is to delete affected host via API, create classic configuration  file for such host and perform restart of icinga. 
 
## Your Environment
The environment is almost the same like in [#6927](https://github.com/Icinga/icinga2/issues/6927).
Please let me know in case that any other information is needed.

**Comment by dnsmichi** [comment]
What happens if you force a re-check of this specific host? The `address` attribute has been modified at runtime, the files in the `_api` package do not reflect that as being stored on PUT requests only.

**Comment by VtG242** [comment]
I have tried "Check now" button in UI and basically nothing happened respectively host remained in red. But  a weird thing is that even I have deleted the affected host and added it back so the issue persisted. Is it possible that not all state information has been cleaned for such host after DELETE?

Maybe I didn't understand your note well but I would say that I have used PUT method for creating host. Via API we are updating only state of notifications but in case that address of host is changed so the host is deleted and created again. What do you mean by  "address attribute has been modified at runtime"?

Probably unrelated questions:
Could it be somehow related to size of icinga2.state file?
What is causing a state that UI is showing a different IP (modified-attributes.conf?) for host than is an address in _api package? (I assume that it's caused by UPDATE of attribute address of host object but I'm not sure)

**Comment by VtG242** [comment]
A little bit different but similar issue happening right now:

Host deleted at:
```
[2019-02-12 13:39:34 +0100] information/HttpServerConnection: Request: DELETE /v1/objects/hosts/ossec-server01.int.na3.intgdc.com?cascade=1 (from [127.0.0.1]:54518), user: root)
```
Host re-created at:
```
[2019-02-12 13:55:19 +0100] information/HttpServerConnection: Request: PUT /v1/objects/hosts/ossec-server01.int.na3.intgdc.com (from [127.0.0.1]:34758), user: root)
```
Correct address for host is 10.7.128.53 but in UI it's flapping between 10.7.128.53 and 10.7.128.65
See pictures below:
[Host UP](https://www.dropbox.com/s/y1bf1jzcdpk3d9b/ok.png?dl=0l)
[Host DOWN](https://www.dropbox.com/s/9ucksf996w1mhv3/ko.png?dl=0)

I have deleted and re-created host via API but the problem persists.
How could I debug it further?

**Comment by VtG242** [comment]
We have stopped using API for managing hosts and we have returned to generating static configuration files but it seems that this issue happens time to time in case that ip address is changed for host object (redeploy of the host)

Symptoms are still the same:
1) host within static configuration file  has correct IP
2) icinga2 object list --type=host --name=host  shows correct IP
3) in UI is showed old IP
4) in modified-attributes.conf is old IP for the host
5) listing host object via API - shows old IP

The result is that checks are going to old IP.

The solution:
Remove object from configuration
Reload icinga
Add object to configuration
Reload icinga

Is this bug or is something wrong with our setup?

**Comment by dnsmichi** [comment]
You're still modifying the IP address at runtime, this is what is stored inside the modified-attributes file. Since you're missing static config objects with API modifications, I would recommend to avoid such scenarios. Either do one or the other. Delete the modified-attributes.conf file to restore the old behaviour.

**Comment by VtG242** [comment]
Maybe I don't understand your note well but I would say that we don't modify IP address at runtime now  as we only reload icinga with updated configuration files so no API actions are done.
