### ISSUE TITLE
Correct required Boost version

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#6933]
## Expected Behavior

As a packager I can build Icinga 2 with just [the dependencies named in our docs](https://github.com/Icinga/icinga2/blob/4339240b46b0232082446c50f8cb5b93cb427208/doc/21-development.md#package-builds-).

## Current Behavior

At least on CentOS 6 I have to install Boost v1.53 (from https://packages.icinga.com/ !) which is higher than the documented v1.48 not to get any compiler errors.

## Possible Solution

Evaluate the available/provided Boost versions on our supported OSes' versions and raise the version in our docs respectively.

## Steps to Reproduce (for bugs)

1. Get a fresh CentOS 6.10
2. Clone the Icinga 2 master
3. `yum install -y centos-release-scl epel-release`
4. `yum install -y bison boost148-devel cmake devtoolset-6-gcc-c++ flex libedit-devel make mysql-devel openssl-devel postgresql-devel yajl-devel`
5. `cmake -DCMAKE_C_COMPILER=/opt/rh/devtoolset-6/root/usr/bin/gcc -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-6/root/usr/bin/g++ -DBOOST_INCLUDEDIR=/usr/include/boost148 -DBOOST_LIBRARYDIR=/usr/lib64/boost148 ..`
6. `make`

## Context

For developing a bigger change to Icinga 2 I'm setting up a build environment with the-older-the-better versions of the build deps. While performing the *Steps to Reproduce* I discovered that something was broken on CentOS and @lazyfrosch pointed out the *Current Behavior*.

## Your Environment

See *Steps to Reproduce*.

**Comment by Al2Klimov** [comment]
IMO a list of the build deps' versions per OS version would be helpful for both issues like this and raising the deps' versions on OS version EOL.

**Comment by dnsmichi** [comment]
You can add such in the 21-development.md section which incorporates the old INSTALL.md content.
