### ISSUE TITLE
Integer overflow when converting large unsigned integer Values to String

### ISSUE THREAD

**Issue by ix-dev** [Icinga/icinga2#6936]
We faced some integer overflow issue when we try to store large performance data values in InfluxDB via the influxdbwriter.
These integer values are returned by a check plugin, but we noticed that the problem is more general: when a Value object holding an integer > `INT64_MAX` (signed) is converted to a string it will overflow.

## Expected Behavior

If we store a value of `UINT64_MAX` (unsigned) in a `Value` object we expect to get the same value back when converted to a String.
Since `Value` objects internally store any number as double, we can expect some inaccurracy, i.e., if we store `UINT64_MAX` (18446744073709551615) it will be rounded to 18446744073709551616.0

## Current Behavior

`UINT64_MAX` stored in as Value object wraps in the `Convert::ToString()` function due to a `static_cast<long long>`. The output string is "-9223372036854775808".

## Possible Solution

Will propose a patch as solution/workaround.

## Steps to Reproduce (for bugs)

Will provide unittests for this issue.

## Context

We try to store counter values which are part of the performance data from our check plugins in InfluxDB.
The bug only occurs if some intermediate representation as `Value` object is involved. The data stored in the IDO DB for example is not affected.

## Your Environment

* Version used (`icinga2 --version`): v2.10.2-216-g9ce12978c
* Operating System and version: Debian GNU/Linux 8 x86_64, unit testing on Darwin 18.2.0 x86_64
* Enabled features (`icinga2 feature list`): api checker command ido-mysql influxdb mainlog notification perfdata
* Icinga Web 2 version and modules (System - About): 2.5.0, director, fileshipper, grafana, monitoring
* Config validation (`icinga2 daemon -C`): not related to any particular configuration

**Comment by Al2Klimov** [comment]
Hello @ix-dev and thank you for both reporting and fixing the issue!

If the commits you linked are ready for production, please create a pull request.

Best,
AK

**Comment by htriem** [comment]
- Test whether the REST API output with numbers is still the same (int vs. float). This is especially important for Golang libraries. 
- Figure out whether a different implementation is available in the boost libraries, avoiding static casts
