### ISSUE TITLE
MSSQL resource type

### ISSUE THREAD

**Issue by swizzly** [Icinga/icinga2#6938]
Hi
Is it possible to use MSSQL as a Icinga2 resource?
I would like to extract objects from SCOM MSSQL DB and create Icinga2 Objects using the Director module. I know the SCOM plugin for Icinga2, but it is missing a couple of features that director comes with.
The SCOM plugin connects to the SCOM MSSQL DB through freetds.
cheers

**Comment by dgoetz** [comment]
Yes, it is possible. It is directly supported by Icinga Web 2 if the php driver is installed, but I found documentation lacking for this. So can you please open a feature request in the Icinga Web 2 repository as this one is for Icinga 2. Also the community channels would be better for such questions next time.

**Comment by Thomas-Gelf** [comment]
Hi @swizzly,

you should make sure to have the `php-sybase` package installed, using the DB type `mssql` should then be fine. Depending on your Linux distribution this will require `libsybdb5` which requires `freetds`. There should be no need to add connections to your `freetds.conf`, just define a resource in Icinga Web 2 and connect to (usually) port 1433. Raising ```[global] tds version = ..` to `8.0` might help when connecting to modern MSSQL servers - you'll otherwise face various encoding issues.

Hope this helps!

Cheers,
Thomas
