### ISSUE TITLE
icinga2 repository is deprecated but no changelog

### ISSUE THREAD

**Issue by bef0re** [Icinga/icinga2#6948]
When running `icinga2 repository host list` I get the following warning:

`Warning: CLI command 'repository host list' is DEPRECATED! Please read the Changelog.`

I read the entire changelog but I didn't find anything useful. Why is repository deprecated and what should I use instead?

**Comment by mcktr** [comment]
The command was part of the deprecated and meanwhile removed bottom up mode. I guess you are using an outdated version, the bottom up mode was deprecated in v2.6 and removed in v2.8.  

https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#removed-bottom-up-client-mode

Use the top down mode instead: https://icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#top-down

For further questions to this topic and upgrade paths please join https://community.icinga.com/

Best regards
Michael
