### ISSUE TITLE
Check validity of endpoint configuration through zone-api

### ISSUE THREAD

**Issue by angottwa** [Icinga/icinga2#6962]
Steps: 
•	Build a Master-Satellite-Zone-Configuration. 
•	Keep some old configuration files on the satellite. 
•	Push new configuration from Master.
•	Now the Satellite has an invalid configuration due to duplicate entries. 
•	After trying to restart the satellite, it fails due to configuration errors.

What is currently possible:
•	API check if endpoints and zones are connected with each other
•	API check to do pretty much anything we want, except this

What I’d like to be implemented:

Check to see if an endpoint has an invalid configuration and some sort of alert on the master, when that isn’t the case.

Icinga2 daemon -C does that on a manual basis, on larger monitoring environments – especially with several zones, which are not connected, this would be very helpful. 

It should be fairly easy to have a background task on endpoints running, which daemonizes those configuration validity checks. Now Icinga just needs to call the result of that and offer it through the API. 

This way it would be possible to directly get notified, when a problem occurs.

**Comment by Al2Klimov** [comment]
Hello @angottwa and thank you for reporting!

1. AFAIK it's state of the art *not* to have any config on any node ex. one master (the "config master"). IMO having config in either both conf.d and zones.d or zones.d in more than one node in a cluster (is this the case in your setup?) is a bad idea – whether it works or not.
2. AFAIK the config master won't share broken config with its sats – so in case of any invalid config you'll have to correct it only once.
3. Validating config periodically before actually switching to it doesn't make any sense and wastes CPU – especially in large setups.

@dnsmichi Please correct me if I'm wrong.

Best,
AK

**Comment by dnsmichi** [comment]
The `icinga` check reports such a thing already when the satellite's last reload failed, changing the state.

The problem with the satellite having invalid production configuration will be dealt with #6716 amongst other improvements. Therefore closing this as a partial duplicate.
