### ISSUE TITLE
GraphiteWriter not writing Performance Data to Carbon-Cache

### ISSUE THREAD

**Issue by ArMar87** [Icinga/icinga2#6965]
Hello together,

Icinga2 does not send Performance Data to Carbon-Cache.
Is there a known issue related to RHEL 7.4?

tcpdump -n port 2003 
Does not show up any packets. Only the connection is established by Icinga.
Manual sending performance data to carbon-cache works as expected and will be shown up in the graphite web ui.

In the folder /var/spool/icinga2/perfdata all files are empty.

To verify it is not an issue with the custom checks I have added the localhost with a ping check.
But still the same issue.

Best Regards
ArMa

## Your Environment

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.17.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
* Enabled features (`icinga2 feature list`):
Disabled features: compatlog elasticsearch gelf influxdb opentsdb perfdata statusdata syslog
Enabled features: api checker command debuglog graphite ido-mysql livestatus mainlog notification
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
[2019-02-22 10:36:24 +0100] information/cli: Icinga application loader (version: r2.10.2-1)
[2019-02-22 10:36:24 +0100] information/cli: Loading configuration file(s).
[2019-02-22 10:36:24 +0100] information/ConfigItem: Committing config item(s).
[2019-02-22 10:36:24 +0100] information/ApiListener: My API identity: xxx-xxxx.xxx-xx.com
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 2299 Services.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 LivestatusListener.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 737 Hosts.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 2 FileLoggers.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 2 NotificationCommands.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 6 HostGroups.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 GraphiteWriter.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 3 Zones.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 2 Endpoints.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 3 ApiUsers.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 User.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 296 CheckCommands.
[2019-02-22 10:36:24 +0100] information/ConfigItem: Instantiated 1 ServiceGroup.
[2019-02-22 10:36:24 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-02-22 10:36:24 +0100] information/cli: Finished validating the configuration file(s).
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
Object 'xxxx-xxxx1.xxx-xx.com' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 1:0-1:42
  * __name = "xxxx-xxxx1.xxx-xx.com"
  * host = "xx"
    % = modified in '/etc/icinga2/zones.conf', lines 2:3-2:23
  * log_duration = 86400
  * name = "xxxx-xxxx1.xxx-xx.com"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 42
    * last_line = 1
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "xxxx-xxxx1.xxx-xx.com" ]
    % = modified in '/etc/icinga2/zones.conf', lines 1:0-1:42
  * type = "Endpoint"
  * zone = ""

Object 'xxxx-xxxx2.xxx-xx.com' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 5:1-5:43
  * __name = "xxxx-xxxx2.xxx-xx.com"
  * host = "xx"
    % = modified in '/etc/icinga2/zones.conf', lines 6:3-6:23
  * log_duration = 86400
  * name = "xxxx-xxxx2.xxx-xx.com"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 5
    * last_column = 43
    * last_line = 5
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "xxxx-xxxx2.xxx-xx.com" ]
    % = modified in '/etc/icinga2/zones.conf', lines 5:1-5:43
  * type = "Endpoint"
  * zone = ""

Object 'master' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 9:1-9:20
  * __name = "master"
  * endpoints = [ "xxxx-xxxx1.xxx-xx.com", "xxxx-xxxx2.xxx-xx.com" ]
    % = modified in '/etc/icinga2/zones.conf', lines 10:3-10:74
  * global = false
  * name = "master"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 9
    * last_column = 20
    * last_line = 9
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "master" ]
    % = modified in '/etc/icinga2/zones.conf', lines 9:1-9:20
  * type = "Zone"
  * zone = ""

Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 14:1-14:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 15:3-15:15
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 14
    * last_column = 30
    * last_line = 14
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 14:1-14:30
  * type = "Zone"
  * zone = ""

Object 'director-global' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 18:1-18:29
  * __name = "director-global"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 19:3-19:15
  * name = "director-global"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 18
    * last_column = 29
    * last_line = 18
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "director-global" ]
    % = modified in '/etc/icinga2/zones.conf', lines 18:1-18:29
  * type = "Zone"
  * zone = ""

**Comment by dnsmichi** [comment]
`/var/spool/icinga2/perfdata` is used by a different feature called `perfdata`, and not required by the `graphite` feature.

Metrics will only be sent when a check execution happens, and the graphite feature is able to parse such performance data. Host/services also need `enable_perfdata` being enabled (the default).

**Comment by ArMar87** [comment]
Hello dnsmichi,

this is the inspected service via the director. The enable_perfdata is set to true but still not performance data is sent to carbon.

Carbon-Cache would create a new *.wsp file for every data incoming, right?
So if I search for *.wsp files they should be listed up.

Config for the GraphiteWriter:
`/**
 * The GraphiteWriter type writes check result metrics and
 * performance data to a graphite tcp socket.
 * library "perfdata"
 */
library "perfdata"

object GraphiteWriter "graphite" {
  host = "127.0.0.1"
  port = 2003
  enable_send_thresholds = true
  enable_send_metadata = true
}` 

`__name | "localhost"
-- | --
0
0
""
true
"127.0.0.1"
""
1
hostalive
60
""
60
""
"localhost"
0
true
true
false
true
true
true
""
false
0
0
0
30
25
false
false
 
0
""
""
1550831353.000965
0
1550829497.966173
true
0
1550829497.966173
0
1
0
1550831353.000977
3
"localhost"
1550831410.110985
""
""
{ enable_event_handler: true, enable_notifications: false, enable_passive_checks: false }
"director"
false
10
8
0
1
"Host"
null
1550824982.380267
false
"master"

`

**Comment by dnsmichi** [comment]
Please format output properly, i.e. with using 3 backticks enclosing it, or with a 4 space indent. I cannot see `last_check_result` in there, so it is impossible to tell.

Likely this question should be moved to https://community.icinga.com instead, I'm not convinced this being a bug.

**Comment by ArMar87** [comment]
![lastcheckresultismissing](https://user-images.githubusercontent.com/2519892/53238644-18c5f200-369a-11e9-9055-9f781a54be0d.PNG)
The last_check_result field seems to be missing.
There is a last_check which is 1550833250.324364

**Comment by ArMar87** [comment]
I have reopend the issue in the community forum:
https://community.icinga.com/t/issue-graphitewriter-not-writing-performance-data-to-carbon-cache/441
