### ISSUE TITLE
EventCommand forks thousands of processes

### ISSUE THREAD

**Issue by b33rcity** [Icinga/icinga2#6969]
An EventCommand applied to a Service and the Host the Service is on is triggering thousands of times.

## Expected Behavior

The EventCommand should only call its script once per change in the conditions described in https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#event-commands

## Current Behavior

The script called by EventCommand command gets run in thousands of processes, most of which hang until Icinga reaches a timeout value and kills them, or I restart Icinga via systemd. The load on the machine increases rapidly, and the load on the other machine in the HA cluster also rises.

Two of the script's functions are to post a message to slack, and email the same message to us. What happens during these episodes is we receive messages that have only portions of the content, as if the script ran halfway, skipped a few lines, then got to the `mail` and `curl` lines. Which bits of content do come through aren't consistent. We receive hundreds of these messages at a time, and in one instance received a total in the thousands after just a couple minutes. 

Reviewing `atop` and Icinga2 logs, I was able to determine that in the worst instance so far the script was called no less than sixty-thousand times in the space of three minutes. 

## Steps to Reproduce (for bugs)

1. HA cluster contains the config master. 
2. The Host check is `dummy`, with its state determined by a function which polls the state of a set of Services and returns a state based on the proportion of OK/not OK states.
3. The Service check is a ping check. There is a group of similar ping checks on the same host (set with `apply for`), but one in particular appears to be the culprit.
4. The EventCommand is applied to both the Host (`dummy`) and to each Service. (Admittedly not ideal for what the EC does, but this behavior is still strange.)
5.  One Node is checking the Host, the other node is checking the Service. 
6. The Service fails first. The EventCommand runs as expected on the node which checked it.
7. After other Services also fail, the `dummy` check returns DOWN and the Host fails.
8. The node which checks the Host runs the EventCommand and the problem occurs.

## Your Environment

* Version used (`icinga2 --version`): 2.10.2-1
* Operating System and version: Debian 9.6

The function used by `dummy`:
```
globals.allServiceStates = function(svc_name, hst_name) {
    // Tally up services in each state
    var okay = 0          
    var warn = 0
    var crit = 0
    var unkn = 0
    var total = 0 // For Edge routers, total is rarely more than 4 when counting
                  // circuits for both IP versions. 6 if we include loopback.
    for (svc in get_services(hst_name)) {
        if (regex(svc_name, svc.name)) {
            this.state = svc.last_check_result.state
            if (state == 3) {
                unkn = unkn + 1
            } else if (state == 2) {   
                crit = crit + 1
            } else if (state == 1) { 
                warn = warn + 1
            } else if (state == 0) {      
                okay = okay + 1
            }       
            total = total + 1
        } 
    }
    // This function is meant for `dummy_state`, so we need to return a float
    var state = 3       # Unknown until we know otherwise

    // Compare the tallies to the total and return a state
    // Change the proportion for routers with lots of circuits vs a few
    if (total > 5) { # 6 or more
        if (crit >= total / 3) {
            state = 2
        } else if (unkn == total) {
            state = 2
        } else if (crit + warn + unkn >= total / 2) {
            state = 2
        } else if (crit >= total / 5) {
            state = 1
        } else if (warn >= total / 2) {
            state = 1
        } else if (unkn >= total * 0.66) {
            state = 1
        } else if (crit + warn + unkn >= total / 3) {
            state = 1
        } else {
            state = 0
        }
    } else {
        if (crit + warn + unkn >= total / 2) { # 5 or less
            state = 2
        } else if (crit + warn + unkn >= total / 4) {
            state = 1
        } else {
            state = 0
        }
    }
    return state
}
```

The Host definition:
```
object Host "<>" {
    import "generic-router"   # Adds the event command
    address = "<>"
    address6 = "<>"
    groups += [ "routers" ]
    check_command = "dummy"
    
    // This is an edge router, so let's loop through some important interfaces and make services
    vars.interfaces = {
        "<>" = { address = "<>",
                     address6 = "<>" }
        "<>" = { address = "<>",
                     address6 = "<>" }
        "loopback"        = { address = "<>",
                                      address6 = "<>" }
    }
    vars.ping_wrta = "190, 20%"
    vars.ping_crta = "230, 40%"

    // With the interfaces configured, let's count up which ones are good and alert accordingly
    vars.dummy_state = {{ return allServiceStates("iface-ping.*", host.name) }}
    vars.dummy_text = {{ return allServiceOuts("iface-ping.*", host.name) }}
}
```

The Service definition:
```
apply Service "iface-ping: " for (iface => addrs in host.vars.interfaces) {
    import "generic-service"
    vars += addrs
    event_command = "automtr"
    display_name = "circuit: " + iface.upper()
    check_command = "ping"
    if (host.command_endpoint) {
        command_endpoint = host.command_endpoint
    }
    vars.ping_address = addrs["address"]
    assign where host.vars.interfaces
}
```

The EventCommand definition:
```
object EventCommand "automtr" {
    /* 
     * Runs an MTR and posts it to slack and email whenever the
     * Check goes into Hard Down/Critical state.
     */
    command = [ "/etc/icinga2/scripts/run_mtr_ici.bash",
                "$state$",
                "$name$",
                "$address$",
                "$state_type$",
                "$check_source$",
                "$host.name$"
              ]
}
```

The bash script:
```
ICINGA_STATE=$1
ICINGA_NAME=$2
ICINGA_ADDRESS=$3
ICINGA_STATETYPE=$4
ICINGA_INSTANCE=$5
ICINGA_HOST=$6

#                        host                        service
if [[ "$ICINGA_STATE" = "DOWN" || "$ICINGA_STATE" = "CRITICAL" ]]; then
  if [[ "$ICINGA_STATETYPE" = "HARD" ]]; then
    if [ -f /tmp/handler.$ICINGA_ADDRESS ]; then
     echo "/tmp/handler.${ICINGA_ADDRESS} exists, skipping"
    else
      date > /tmp/handler.$ICINGA_ADDRESS
      if [[ "$ICINGA_NAME" != "$ICINGA_HOST" ]]; then
          ICINGA_NAME="Service ${ICINGA_NAME} on ${ICINGA_HOST}"
      fi
      echo -e "${ICINGA_NAME} has failed!\nMTR *from* ${ICINGA_INSTANCE} _to_ ${ICINGA_ADDRESS}:" >> /tmp/handler.$ICINGA_ADDRESS

      echo "---------------------------------" >> /tmp/handler.$ICINGA_ADDRESS
      echo '```' >> /tmp/handler.$ICINGA_ADDRESS
      /usr/bin/mtr -rwc 10 $ICINGA_ADDRESS >> /tmp/handler.$ICINGA_ADDRESS
      echo '```' >> /tmp/handler.$ICINGA_ADDRESS
      echo " " >> /tmp/handler.$ICINGA_ADDRESS

      mail -s "MTR $ICINGA_NAME: $NAGIOS_STATETYPE" <address> -r <address> < /tmp/handler.$ICINGA_ADDRESS

      curl -X POST -H 'Content-type: application/json' --data "{\"text\":\" `cat /tmp/handler.$ICINGA_ADDRESS`\"}" <webhook>
    fi
  fi
elif  [[ "$ICINGA_STATE" = "UP" || "$ICINGA_STATE" = "OK" ]]; then
  if [ -f /tmp/handler.$ICINGA_ADDRESS ]; then
    rm -rf /tmp/handler.$ICINGA_ADDRESS
  fi
fi
```

**Comment by dnsmichi** [comment]
Since your script handles the typical hard-state-notify-or-recover logic, I'm wondering why you aren't using the notification objects and commands for this kind of events forwarded to Slack channels, etc.

The script is always run in SOFT state changes, and if those services start to flap between OK and NOT-OK states, it is always executed. Also, each service executes this handler, and depending on the host count and defined interfaces in `vars`, this may be a lot of them.

The services look valid though. The host which includes that mega function with state calculations leads me to the assumption that this changes quite often between UP and DOWN, triggering the event command every time. 

Since you didn't share the `generic-router` template, I'll blindly guess - frequent check and retry intervals, and this isn't the only host using this, but there are also many hosts which are defined as routers. 

Please add the following:

- `icinga2 object list --type Host --count`
- `icinga2 object list --type Host --name <nameofthathostabove>`

**Comment by b33rcity** [comment]
### Changes since then

To work around the problem, I removed the `event_command` from the router Host objects, but left it in place on the `iface-ping: ` service. The issue hasn't returned, of course, but I would like to reenable it on the Host due to another change, that being moving the `dummy`-based check into its own Service object and using `hostalive` for the Host `check_command`. I haven't tested the event with this new check configuration on account of other things coming up after I was able to end the email barrage.

We also moved the master node to a more powerful machine and decommissioned the HA node.

### More info

My bad, I should have included the relevant templates, also. I'll paste them below, but for ease of reading, here are some relevant attributes:

- all Hosts:
  - `max_check_attempts = 3`
  - `check_interval = 1m`
  - `retry_interval = 30s`
- all Services:
  - `max_check_attempts = 5`
  - `check_interval = 1m`
  - `retry_interval = 30s`

>each service executes this handler, and depending on the host count and defined interfaces in vars, this may be a lot of them. 

These are good points to consider, definitely. I've been averaging 4 of these Services per router. This particular router has exactly 4. If I'm understanding the docs and my own configuration correctly, the event handler would be called 6 times on a failure: once on the first state change, 4 times on each successive retry, and once more on the change to hard state (and once more on recovery for a final count of 7). 

This adds up to 24 calls to the event handler--not 63,000. Even adding in the calls for the Host check, that adds only an additional 4 calls and leaves us a few zeroes short. 

> The host which includes that mega function with state calculations leads me to the assumption that this changes quite often between UP and DOWN, triggering the event command every time.

Generally this has not been the case for Services relying on that function. This particular router, however, is in Brazil--where connectivity issues seem to be the norm. It does enter Warning state somewhat regularly as one or another of the circuits monitored by this Service flaps. The script is programmed to just exit when the state is not Critical or Down, though; even if the Icinga event handler is getting called on each state change, that still doesn't account for the script running all the way through as many times as it did.

I'm also still wondering why the Services would run the event handler without any problems at all until the Host's state changed. It really was like flipping a switch: I watched the MTR results come in like normal on Slack, with Icingaweb open right next to it. One or two more Service MTRs rolled in, probably already running when the state change happened, then every MTR after that, from either the Host or the Service, was incomplete and they came in by the hundreds.  

The generic host and service templates (imported by everything):
```
template Host "generic-host" {
// This gets imported by generic-router and none of these are changed
// (except, at the time, check_command)
  max_check_attempts = 3 
  check_interval = 1m
  retry_interval = 30s
  enable_flapping = true
  check_command = "hostalive" 
  vars.enable_pagerduty = true
  vars.slack_notifications = true
  vars.ping_wpl = "20%"
  vars.ping_cpl = "40%"
}
template Service "generic-service" {
  max_check_attempts = 5
  check_interval = 1m
  retry_interval = 30s
  enable_flapping = true
  vars.slack_notifications = host.vars.slack_notifications
  vars.enable_pagerduty = host.vars.enable_pagerduty
}
```
The info you actually asked for:
```
# icinga2 object list --type Host --count | tail -n 1
Found 1049 Host objects.

# icinga2 object list --type Host --name <>
Object '<host>' of type 'Host':
  % declared in '/etc/icinga2/zones.d/<satellite_zone>/<host>.conf', lines 1:0-1:23
  * __name = "<>"
  * action_url = ""
  * address = "<>"
    % = modified in '/etc/icinga2/zones.d/<satellite-zone>/<host>.conf', lines 3:5-3:29
  * address6 = "<>"
    % = modified in '/etc/icinga2/zones.d/<satellite-zone>/<host>.conf', lines 4:5-4:33
  * check_command = "dummy" ##### since changed to "hostalive"
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 24:3-24:29
  * check_interval = 60
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 20:3-20:21
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "<>"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = true
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 22:3-22:24
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = "automtr"
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/infra-templates.conf', lines 8:5-8:29
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ "routers", "routers" ]
    % = modified in '/etc/icinga2/zones.d/<satellite-zone>/<host>.conf', lines 5:5-5:34
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 19:3-19:24
  * name = "<>"
  * notes = ""
  * notes_url = ""
  * package = "_etc"
  * retry_interval = 30
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 21:3-21:22
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 23
    * last_line = 1
    * path = "/etc/icinga2/zones.d/<satellite-zone>/<host>.conf"
  * templates = [ "<host>", "generic-router", "generic-infra", "generic-host" ]
    % = modified in '/etc/icinga2/zones.d/<satellite-zone>/<host>.conf', lines 1:0-1:23
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/infra-templates.conf', lines 13:1-13:30
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/infra-templates.conf', lines 6:1-6:29
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 18:1-18:28
  * type = "Host"
  * vars
    * enable_pagerduty = true
      % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 26:3-26:30
      % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/infra-templates.conf', lines 10:5-10:32
      % = modified in '/etc/icinga2/zones.d/<satellite-zone>/<host>.conf', lines 9:5-9:32
    * env
      % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/infra-templates.conf', lines 18:5-21:5
      * checkEnv = true
      * type = "juniper"
    * interfaces
      % = modified in '/etc/icinga2/zones.d/<satellite-zone>/<host>.conf', lines 11:5-16:5
      * iface0
        * address = "<>"
        * address6 = "<>"
      * iface1
        * address = "<>"
        * address6 = "<>"
    * peers
      % = modified in '/etc/icinga2/zones.d/<satellite-zone>/<host>.conf', lines 17:5-23:5
      * peer0 = "<>"
      * peer1 = "<>"
      * peer2 = "<>"
      * peer3 = "<>"
      * peer4 = "<>"
    * ping_cpl = "40%"
      % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 32:3-32:23
    * ping_crta = "230, 40%"
      % = modified in '/etc/icinga2/zones.d/<satellite-zone>/<host>.conf', lines 8:5-8:31
    * ping_wpl = "20%"
      % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 31:3-31:23
    * ping_wrta = "190, 20%"
      % = modified in '/etc/icinga2/zones.d/<satellite-zone>/<host>.conf', lines 7:5-7:31
    * slack_notifications = true
      % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/generic-templates.conf', lines 28:3-28:33
    * slack_renotification_interval = 1800
      % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/infra-templates.conf', lines 9:5-9:44
    * snmp_community = "<>"
      % = modified in '/etc/icinga2/zones.d/global-templates/templates.d/infra-templates.conf', lines 23:5-23:36
  * volatile = false
  * zone = "<satellite-zone>"
```

And a sample log entry from an event, which I should have also included in my original post:
```
[2019-02-22 01:45:22 -0500] warning/Process: Killing process group 27135 ('/etc/icinga2/scripts/run_mtr_ici.bash' 'CRITICAL' 'iface-ping6: <>' '<IP>' 'HARD' '<master's name>' '<host's name>') after timeout of 60 seconds
[2019-02-22 01:45:22 -0500] warning/Process: PID 27135 was terminated by signal 9 (Killed)
```

The master has hundreds of these. The HA endpoint had 1000s, but unfortunately I didn't think to backup the logs before we destroyed that VM.

**Comment by dnsmichi** [comment]
I would leverage the calculation and purpose of that event handler into an external script or daemon, which implements that behaviour. I don't know why you're exactly having this for the host check state itself, but an external check result via REST API should do the trick as well.

Since the intervals for the host check are 30 to 60 seconds, that's really frequent and can be done with a cronjob or scheduler anyways. That scheduler can fetch all involved objects via REST API, and do the calculations. Or it can also listen to the API event streams and wait for state changes, simulating somehow what event handlers do.

Similar to that approach, you'll calculate the overall state then. Error handling and preventing fork bombs should be included there.

I just don't think that the monitoring core and DSL and event handlers and custom scripts with state machines are a safe way of implementing this.

Cheers,
Michael

PS: This asks for community experience and should be put onto https://community.icinga.com next time.

**Comment by b33rcity** [comment]
I've been looking at this again more closely over the weekend; I actually agree, most of the problem I ran into is probably coming from the script itself and my own inexperience with the EventCommand (this was the first I've made). I'm reworking the whole thing and, at least for my own purposes, can say case closed. 

It does still strike me as strange that the external script was called so many times in such a short time in the first place and I'm reluctant to say "case closed" as far as that goes. Like, if instead of running `mtr` the bash script just ran `echo "running"; sleep 30`, would I get 63,000+ lines of "running" on STDOUT? 

I realize I should try to at least reproduce this in a test environment on my own before insisting it must be a bug. I appreciate your feedback so far and will share whatever I learn if I find time to do some real testing.

**Comment by dnsmichi** [comment]
The combination of custom DSL functions for state calculations plus the state machine logic with firing event handlers is a pretty much advanced usage. There are no safety handlers in between, and I truly won't recommend that to anyone, especially not with solving a problem like yours. I consider EventCommands for simple things, not for sort of event streaming or daemonized analysis. 

Since we don't know how often that event command was run, nor the exact state change history, I'd say that I would expect these 63k lines and don't see a bug or problem here.

Anyhow, I truly recommend to rethink the strategy and maybe implement my suggested solution above instead. As said as well, let's discuss solutions like this on the community channels with a more broader audience. 

As such, I'm closing here.

Cheers,
Michael
