### ISSUE TITLE
[2.10.2] Icinga satellite update to latest version 2.10.2, connections fails on TLS handshakes

### ISSUE THREAD

**Issue by dolefi** [Icinga/icinga2#6973]
## Expected Behavior

Satellite or master should connect to clients without the TLS handshake problem, issue is probably on CLOSE_WAIT connection.
## Current Behavior

Once Icinga satellite is updated to version 2.10.2 all connections to master and clients are reseted after restart of Icinga process. Once this restart is done all connections to clients and to master fails on TLS handshake, and as such all services are moved to Unknown. All connections than hangs on CLOSE_WAIT and are duplicated per every try.
## Possible Solution

Rollback to 2.9.2 on satellite fixes this issues.
## Steps to Reproduce (for bugs)

1.Master on version 2.10.2
2.Update satellite to 2.10.2
3.Restart satellite instance

## Context

Once the satellite is updated and the icinga process is restarted all the connections to clients and even master are reseted to SYN_SENT. Expected is to move to ESTABLISHED, but all connections are moved to CLOSE_WAIT and all TLS handshakes are either timeouted after 10s on Clients or, on Satellite error Socked closed during TLS handshake. This behaviour than runs every minute.

Once at least one connection is ESTABLISHED to server all CLOSE_WAIT connections are than removed and only the one remains.  

Also host attribute is in host definition and in zones.conf on client, changing the direction does not help

## Your Environment

* Version used (`icinga2 --version`): 
     version: **r2.10.2-1** -> Master
     version: **r2.10.2-1** -> Satellite
     Clients are version **2.8.4**, but even their update to **2.10.2** does not help 
* Operating System and version:
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-327.36.3.el7.x86_64
  on Satellite and Master
* Enabled features (`icinga2 feature list`):
Enabled features: api checker command ido-mysql influxdb mainlog notification on **Master**
Enabled features: api checker mainlog on **Satellite**
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
validation is without any issues
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by dnsmichi** [comment]
Hi, any chance you'll test the current snapshot packages?

**Comment by dolefi** [comment]
Hi, yes I can test it out. I will try it out tommorow and hopefully will let you know the outcome of that.

**Comment by dolefi** [comment]
So, I've had time to test it out this evening. 
Unfortunately no meaningfull change happened. The snapshot still behaves the same, it is true, that I updated only satellite server to the snapshot build, but even than it should not do this as the rollback to 2.9.2 still helps. 

After rollback and startup the unknown services move to different state within 2 minutes and no TLS handshakes in logs present and no CLOSE_WAIT present while _lsof -i_ after satellite restart and all SYN_SENT are ESTABLISHED within approximately 90s.

here are some logs from testing the snapshot.
icinga version
```
lv420001 yum.repos.d # icinga2 -V
icinga2 - The Icinga 2 network monitoring daemon (version: v2.10.2-247-g4238b61)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-327.36.3.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: `/run/icinga2/icinga2.pid
```

how is the satellite behaving in icinga2 logs (only part):
```
[2019-02-25 21:39:01 +0100] critical/ApiListener: Client TLS handshake failed (from [10.233.136.9]:53082): Error: Socket was closed during TLS handshake.

        (0) Handling new API client connection

Context:
        (0) Handling new API client connection

[2019-02-25 21:39:01 +0100] warning/TlsStream: TLS stream was disconnected.
[2019-02-25 21:39:01 +0100] critical/ApiListener: Client TLS handshake failed (from [10.233.138.116]:28417): Error: Socket was closed during TLS handshake.

        (0) Handling new API client connection

Context:
        (0) Handling new API client connection

[2019-02-25 21:39:01 +0100] warning/TlsStream: TLS stream was disconnected.
[2019-02-25 21:39:01 +0100] critical/ApiListener: Client TLS handshake failed (from [10.233.136.45]:53398): Error: Socket was closed during TLS handshake.

        (0) Handling new API client connection

Context:
        (0) Handling new API client connection

[2019-02-25 21:39:01 +0100] warning/TlsStream: TLS stream was disconnected.
[2019-02-25 21:39:01 +0100] critical/ApiListener: Client TLS handshake failed (from [10.233.138.203]:38025): Error: Socket was closed during TLS handshake.

        (0) Handling new API client connection

Context:
        (0) Handling new API client connection
```

and how the output of lsof -i looks, the number sticks to around 1300 CLOSE_WAIT connections for approx 400 servers with 6000 services
```
icinga2    7849    icinga  489u  IPv4 536674      0t0  TCP lv420001.XXX.cz:5665->lv423035.xxx.XXX.cz:50629 (CLOSE_WAIT)
icinga2    7849    icinga  491u  IPv4 466179      0t0  TCP lv420001.XXX.cz:5665->lv422014.xxx.XXX.cz:39399 (CLOSE_WAIT)
icinga2    7849    icinga  492u  IPv4 475902      0t0  TCP lv420001.XXX.cz:5665->lv421035.xxx.XXX.cz:58117 (CLOSE_WAIT)
icinga2    7849    icinga  493u  IPv4 465372      0t0  TCP lv420001.XXX.cz:5665->lv421050.xxx.XXX.cz:64728 (CLOSE_WAIT)
icinga2    7849    icinga  495u  IPv4 467861      0t0  TCP lv420001.XXX.cz:5665->lv421077.xxx.XXX.cz:12715 (CLOSE_WAIT)
icinga2    7849    icinga  497u  IPv4 534863      0t0  TCP lv420001.XXX.cz:5665->lv421041.xxx.XXX.cz:62114 (CLOSE_WAIT)
icinga2    7849    icinga  498u  IPv4 538939      0t0  TCP lv420001.XXX.cz:5665->lv421010.xxx.XXX.cz:9142 (CLOSE_WAIT)
icinga2    7849    icinga  499u  IPv4 499749      0t0  TCP lv420001.XXX.cz:5665->lv422015.xxx.XXX.cz:61779 (CLOSE_WAIT)
icinga2    7849    icinga  501u  IPv4 502519      0t0  TCP lv420001.XXX.cz:5665->lv421071.xxx.XXX.cz:22280 (CLOSE_WAIT)
icinga2    7849    icinga  503u  IPv4 504197      0t0  TCP lv420001.XXX.cz:5665->lv423080.xxx.XXX.cz:9564 (CLOSE_WAIT)
icinga2    7849    icinga  504u  IPv4 541571      0t0  TCP lv420001.XXX.cz:5665->lv422003.xxx.XXX.cz:42908 (CLOSE_WAIT)
icinga2    7849    icinga  505u  IPv4 478065      0t0  TCP lv420001.XXX.cz:5665->lv422039.xxx.XXX.cz:10818 (CLOSE_WAIT)
icinga2    7849    icinga  506u  IPv4 469661      0t0  TCP lv420001.XXX.cz:5665->lv423041.xxx.XXX.cz:61103 (CLOSE_WAIT)
icinga2    7849    icinga  508u  IPv4 469989      0t0  TCP lv420001.XXX.cz:5665->lv422016.xxx.XXX.cz:28787 (CLOSE_WAIT)
icinga2    7849    icinga  509u  IPv4 469058      0t0  TCP lv420001.XXX.cz:5665->lv423063.xxx.XXX.cz:26258 (CLOSE_WAIT)
icinga2    7849    icinga  510u  IPv4 534869      0t0  TCP lv420001.XXX.cz:5665->bastion-azb.xxx.XXX.cz:25069 (CLOSE_WAIT)
icinga2    7849    icinga  515u  IPv4 540717      0t0  TCP lv420001.XXX.cz:5665->lv423012.xxx.XXX.cz:64330 (CLOSE_WAIT)
icinga2    7849    icinga  516u  IPv4 469746      0t0  TCP lv420001.XXX.cz:5665->lv421004.xxx.XXX.cz:53070 (CLOSE_WAIT)
icinga2    7849    icinga  517u  IPv4 469206      0t0  TCP lv420001.XXX.cz:5665->lv421065.xxx.XXX.cz:21369 (CLOSE_WAIT)
icinga2    7849    icinga  518u  IPv4 477543      0t0  TCP lv420001.XXX.cz:5665->lv422005.xxx.XXX.cz:58922 (CLOSE_WAIT)
icinga2    7849    icinga  519u  IPv4 501770      0t0  TCP lv420001.XXX.cz:5665->lv422020.xxx.XXX.cz:62214 (CLOSE_WAIT)
icinga2    7849    icinga  520u  IPv4 538891      0t0  TCP lv420001.XXX.cz:5665->lv422022.xxx.XXX.cz:60139 (CLOSE_WAIT)
icinga2    7849    icinga  522u  IPv4 500261      0t0  TCP lv420001.XXX.cz:5665->lv423047.xxx.XXX.cz:26284 (CLOSE_WAIT)
icinga2    7849    icinga  523u  IPv4 501811      0t0  TCP lv420001.XXX.cz:5665->lv423049.xxx.XXX.cz:10324 (CLOSE_WAIT)
icinga2    7849    icinga  524u  IPv4 465838      0t0  TCP lv420001.XXX.cz:5665->lv421060.xxx.XXX.cz:12426 (CLOSE_WAIT)
icinga2    7849    icinga  527u  IPv4 508739      0t0  TCP lv420001.XXX.cz:5665->lv421035.xxx.XXX.cz:58323 (CLOSE_WAIT)
icinga2    7849    icinga  528u  IPv4 534936      0t0  TCP lv420001.XXX.cz:5665->lv421065.xxx.XXX.cz:23414 (CLOSE_WAIT)
icinga2    7849    icinga  529u  IPv4 469990      0t0  TCP lv420001.XXX.cz:5665->lv421016.xxx.XXX.cz:16988 (CLOSE_WAIT)
icinga2    7849    icinga  530u  IPv4 502593      0t0  TCP lv420001.XXX.cz:5665->lv422019.xxx.XXX.cz:10855 (CLOSE_WAIT)
icinga2    7849    icinga  532u  IPv4 500398      0t0  TCP lv420001.XXX.cz:5665->lv423061.xxx.XXX.cz:17810 (CLOSE_WAIT)
icinga2    7849    icinga  533u  IPv4 504903      0t0  TCP lv420001.XXX.cz:5665->lv421080.xxx.XXX.cz:28436 (CLOSE_WAIT)
icinga2    7849    icinga  534u  IPv4 550746      0t0  TCP lv420001.XXX.cz:5665->lv421074.xxx.XXX.cz:49873 (CLOSE_WAIT)
```

any suggestions would be appreciated.
BR,
Filip

**Comment by dnsmichi** [comment]
Thanks for testing. We're working on resolving problems similar to this with the network stack in 2.11. @Al2Klimov please consider this while testing.

**Comment by Al2Klimov** [comment]
Feel free to assign all such tickets to me. Once we've got new snapshot packages I'll let the issue authors test.

**Comment by dolefi** [comment]
Hello guys, 
so I've tested the latest version of Icinga (2.10.3) on our satellite server and the behaviour is still the same as in the 2.10.2 with the CLOSE_WAIT connections. 
Do you have any information, or idea, when can we expect the 2.11 version of the icinga (from the milestone) ?

Thank you :)

**Comment by Al2Klimov** [comment]
Don't worry, I'll let all authors of such issues (@dnsmichi assigned to me) know once there's something to know.

**Comment by dolefi** [comment]
Ok, thank you very much :)

**Comment by Al2Klimov** [comment]
This issue seems to have been addressed by #7005.

**Comment by dnsmichi** [comment]
Hi @dolefi,

snapshot packages are available for testing. Additional details can be found here: https://icinga.com/docs/icinga2/snapshot/doc/21-development/#snapshot-packages-nightly-builds

Thanks,
Michael

**Comment by dnsmichi** [comment]
I consider this resolved with the rewrite. In any attempt, please test the snapshot packages and report any problems here or in a new GitHub issue. Thanks.

**Comment by dolefi** [comment]
Hello, I've had time to test these new snapshot packages yesterday. It seems, that till yesterday everything is working as expected. 
I've ran couple of tests to see, if I would be able to replicate problematic behaviour, and the only time, when the snapshot failed was while attempting to reload the configuration on satellite while the server was under heavy load (2 cpus but load average between 60 and 100) which I do not consider as standard situation. 

The only thing, that I am curious about is error in logs while master reloads itself and its zones:
![image](https://user-images.githubusercontent.com/17765008/57135825-0c04ff00-6dab-11e9-8fc1-9587cae6ff8e.png)
it seems that that is not handled correctly.

Also on the fully loaded server while testing the logs were containing a lot of these errors, and in the end the application failed with sigsegv. (unfortunetely I was not able to get the error)
![image](https://user-images.githubusercontent.com/17765008/57135978-8fbeeb80-6dab-11e9-9d8f-d8384a2d46a2.png)

Other than that, the snapshot package is running as expected for the last 24 hours without any issue. 

Thank you :)

**Comment by dnsmichi** [comment]
Thanks for testing, I'll take a note in the main todo list for the error handling bits which changed and need some love :-)
