### ISSUE TITLE
Re-write thread pool

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#6985]
According to @lippserd we have several issues originated by the thread pool. I shall try to make a better one.

Edit by @dnsmichi: Add details below.

## Usage

The TP is used literally everywhere in Icinga:

```
michi@mbpmif ~/dev/icinga/icinga2 (master=) $ grep -r Utility::QueueAsync lib/
lib//checker/checkercomponent.cpp:		Utility::QueueAsyncCallback(std::bind(&CheckerComponent::ExecuteCheckHelper, CheckerComponent::Ptr(this), checkable));
lib//icinga/scheduleddowntime.cpp:		Utility::QueueAsyncCallback(std::bind(&ScheduledDowntime::CreateNextDowntime, this));
lib//icinga/notification.cpp:		Utility::QueueAsyncCallback(std::bind(&Notification::ExecuteNotificationHelper, this, type, user, cr, force, author, text));
lib//livestatus/livestatuslistener.cpp:				Utility::QueueAsyncCallback(std::bind(&LivestatusListener::ClientHandler, this, client), LowLatencyScheduler);
lib//base/process.cpp:			Utility::QueueAsyncCallback(std::bind(callback, m_Result));
lib//base/process.cpp:		Utility::QueueAsyncCallback(std::bind(m_Callback, m_Result));
lib//base/timer.cpp:		Utility::QueueAsyncCallback(std::bind(&Timer::Call, ptimer));
lib//base/utility.cpp:void Utility::QueueAsyncCallback(const std::function<void ()>& callback, SchedulerPolicy policy)

gmichi@mbpmif ~/dev/icinga/icinga2 (master=) $ grep -r EnqueueAsyncCallback lib/
lib//remote/apilistener.cpp:void ApiListener::EnqueueAsyncCallback(const std::function<void ()>& callback, SchedulerPolicy policy)
lib//remote/apilistener.cpp:			EnqueueAsyncCallback(std::bind(&ApiListener::NewClientHandler, this, client, String(), RoleServer), LowLatencyScheduler);
lib//remote/apilistener.cpp:			EnqueueAsyncCallback(std::bind(&ApiListener::AddConnection, this, endpoint), LowLatencyScheduler);
lib//remote/apilistener.hpp:	static void EnqueueAsyncCallback(const std::function<void ()>& callback, SchedulerPolicy policy = DefaultScheduler);
```

Global Application TP:

* Check execution
* Notification and event command execution
* Process spawning
* Timmer calls
* SD Downtime creation and Livestatus client handling

Dedicated TP instance:

* since 2.10: Incoming client connections and active outbound connection attempts

## Problems

- The original TP implementation targets a global thread pool for everything. With 2.10 we've created another instance inside the ApiListener with high priority schedules. This might overlap or cause troubles with context switches and tasks.
- The code implements locks, waits and starving on its own and doesn't abstract that much. Meaning to say, fixing a bug or analysing a problem has been black magic for many years now.

- The TP sort of rate limits incoming connections (different problem handled with the network I/O rewrite) and might not reliably close threads.
- TP initialization must take place after daemonize() with systems not running systemd. 

## Future Benefits

- Use boost thread, mutex, functions, etc. again in an abstracted way
  * Note: I suspect the move to std::thread and variants with 2.9 being the culprit with different behaviour and bugs caused by different compiler versions. With just relying on one packaged boost version also for the TP, we can consolidate the mixed code again.
- Library code abstracted and tested by many
- Boost Asio's thread_pool can be used with network I/O resources too

https://stackoverflow.com/questions/14265676/using-boostasio-thread-pool-for-general-purpose-tasks

**Comment by Crunsher** [comment]
For our understanding it would be very helpful if you were to explain those issues, their impact and how you plan to remedy them. This will help us understand the PR you are working on.

**Comment by Al2Klimov** [comment]
@lippserd, you didn't tell me *which* issues we have – and I didn't care.. but now @Crunsher does.

**Comment by dnsmichi** [comment]
I'll take care of this.

**Comment by Al2Klimov** [comment]
Note: I've got rid of the one thread pool (64b2ac4b3) and the other one is already being managed daemonize-awarely.
