### ISSUE TITLE
base-base_utility/comparepasswords_issafe test fails on i386

### ISSUE THREAD

**Issue by sebastic** [Icinga/icinga2#6987]
The Debian package build for 2.10.3 failed on i386 due to a test failure:
```
 99/101 Test  #64: base-base_utility/comparepasswords_issafe ...............................***Failed    1.45 sec
Running 1 test case...
/<<PKGBUILDDIR>>/test/base-utility.cpp(67): [1;31;49merror: in "base_utility/comparepasswords_issafe": check 0.9 <= diff && diff <= 1.1 has failed[0;39;49m

[1;31;49m*** 1 failure is detected in the test module "Master Test Suite"
[0;39;49m
```
[Full buildlog](https://buildd.debian.org/status/fetch.php?pkg=icinga2&arch=i386&ver=2.10.3-1&stamp=1551426309&raw=0)

**Comment by Al2Klimov** [comment]
This have already been fixed by #6977.

**Comment by sebastic** [comment]
Thanks, I'll add your change as patch to the Debian package.

**Comment by sebastic** [comment]
This issue is hard to reproduce, only on my 4th try did I manage. The debug output I added shows:
```
duration1: 1095376.000000
duration2: 906042.000000
diff:      1.208968
```

Increasing the range may also be an option to fix this issue.

**Comment by dnsmichi** [comment]
Didn't see this upfront, it only happened with many parallel builds on release day. Therefore the patch was incorporated into the packages as a new revision, and will be part of 2.10.4 / 2.11 later.
