### ISSUE TITLE
resetting admin login on icingaweb

### ISSUE THREAD

**Issue by lloydwilke** [Icinga/icinga2#6994]
## Expected Behavior
reset password from within the database or icingacli setup command

## Current Behavior
icingacli setup token create doesnt work and the openssl passwd -1 "yoursecurepassword" command doesnt generate a working password
## Steps to Reproduce (for bugs)

1. openssl passwd -1 "yoursecurepassword"
2. Login to mysql 
3. create a new account in icingaweb_user
4.

## Your Environment

icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.3-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.5.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

**Comment by mcktr** [comment]
Hi,

thanks for opening this issue. The CLI tool `icingacli` is part of Icinga Web 2, please open the issue over here: [Icinga/icingaweb2](https://github.com/Icinga/icingaweb2/issues).

Kind regards
Michael
