### ISSUE TITLE
Replace boost/std::bind with C++11 lambdas

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7006]
They're more flexible, easier to read and avoid issues like #7004.

**Comment by Al2Klimov** [comment]
Will do that after #7005 not to create a hell of merge conflicts.

**Comment by Al2Klimov** [comment]
@dnsmichi Shall I do this or keep it as training task for HT?

**Comment by dnsmichi** [comment]
That's a good idea, I will look into this with @htriem in the coming weeks :-)

**Comment by dnsmichi** [comment]
I'm considering this a possible fix for problems with std::bind and intrusive_ptrs. Let's see how far we get with #6737.

**Comment by dnsmichi** [comment]
FYI @lippserd

**Comment by dnsmichi** [comment]
Some research:

https://github.com/peter-can-write/cpp-notes/blob/master/prefer-lambdas-over-std::bind.md
https://shaharmike.com/cpp/lambdas-and-functions/
http://www.sdowney.org/2017/06/why-stdbind-cant-be-formally-deprecated/
https://stackoverflow.com/questions/49246242/efficiency-of-stdbind-vs-lambda

> Another difference is that arguments to bind must be copied or moved, while a lambda can use variables captured by reference. 

https://stackoverflow.com/questions/17363003/why-use-stdbind-over-lambdas-in-c14/17545183

**Comment by dnsmichi** [comment]
Some reference I've found lately while looking into things, unrelated to the progress here: https://studiofreya.com/cpp/boost/an-introduction-to-boost-signals/#Signals-with-lambdas
