### ISSUE TITLE
ElasticsearchWriter not closing SSL connections on  Icinga2 2.10.3.1

### ISSUE THREAD

**Issue by latuannetnam** [Icinga/icinga2#7018]
## Expected Behavior

I would expect Icinga2 to close connections to Elasticsearch rather than keeping them open and opening additional ones.

## Current Behavior

This issue is as the same as #6989 but for ElasticsearchWriter with SSL connections. For non-SSL connections, Icinga2 closes connection as normal.
## Possible Solution

I think to solution would be the same as #6990 but I'm not sure about that.
## Steps to Reproduce (for bugs)

1. Turn on elasticsearch feature with SSL configuration and monitor established TCP connections. The connection count increases after each data flush (for example 10 seconds in my case)
2. Disable SSL in configuration. The connection count does not increase.

## Context

This issue is causing Icinga2 to run out of file descriptor and every check will fail. 
## Your Environment

* Version used (`icinga2 --version`): 2.10.3-1
* Operating System and version: Ubuntu 16.04
* Enabled features (`icinga2 feature list`): api checker elasticsearch ido-mysql influxdb mainlog syslog
* Icinga Web 2 version and modules (System - About): Icinga Web 2 Version 2.6.2
* Config validation (`icinga2 daemon -C`):
[2019-03-15 15:27:33 +0700] information/cli: Icinga application loader (version: r2.10.3-1)
[2019-03-15 15:27:33 +0700] information/cli: Loading configuration file(s).
[2019-03-15 15:27:34 +0700] information/ConfigItem: Committing config item(s).
[2019-03-15 15:27:34 +0700] information/ApiListener: My API identity: REMOVED
.....
[2019-03-15 15:27:35 +0700] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-03-15 15:27:35 +0700] information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
* ElasticseachWriter configuration: /etc/icinga2/features-enabled/elasticsearch.conf
object ElasticsearchWriter "elasticsearch" {
  host = "127.0.0.1"
  port = 9200
  index = "icinga2_testbed"
  enable_tls = true
  username = "icinga2"
  password = "REMOVED"
  enable_send_perfdata = true
  flush_threshold = 1024
  flush_interval = 10s
}

* Elasticsearch:  elasticsearch-6.6.2-1

**Comment by latuannetnam** [comment]
Thank you very much for quick fix. Hope next version will be released soon!
At the moment, my workaround is to (1) reduce flush_interval and (2) restart Icinga2 everyday to reset connection count.

**Comment by dnsmichi** [comment]
Thought so after reading #6989 that's why I wanted to wait a bit and analyse the problem further. I'll merge the linked PRs after testing them.

**Comment by dnsmichi** [comment]
# Tests

The test setup is a bit more easy with ES, since the Vagrant box `elastic` already provides TLS on port 9203.

```
sudo icinga2 feature enable elasticsearch

vim /usr/local/icinga/icinga2/etc/icinga2/features-enabled/elasticsearch.conf

object ElasticsearchWriter "elasticsearch" {
  host = "192.168.33.7"
  port = 9203
  enable_tls = true
  username = "icinga"
  password = "icinga"
  //host = "127.0.0.1"
  //port = 9200
  //index = "icinga2"
  //enable_send_perfdata = false
  //flush_threshold = 1024
  //flush_interval = 10s
}

icinga2 daemon
```

```
watch -n 1 'for p in $(pidof icinga2); do lsof -p $p | grep TCP; done'
```

![Screen Shot 2019-03-18 at 15 03 38](https://user-images.githubusercontent.com/382049/54535551-084e2200-498f-11e9-93e2-7706856f85fa.png)


# Fix

![Screen Shot 2019-03-18 at 16 37 49](https://user-images.githubusercontent.com/382049/54542508-3128e400-499c-11e9-9699-23df21ab7aa5.png)
