### ISSUE TITLE
Ubuntu, libreadline6 but it is not installable

### ISSUE THREAD

**Issue by ucola** [Icinga/icinga2#7023]
## Expected Behavior

I want to try out icinga2. For the installation i was try to use it on a ubuntu server (blank Ubuntu Server 18.04.2 LTS and also on a blank Ubuntu Server 18.10) and for this i user the following instructions. https://icinga.com/docs/icinga2/latest/doc/02-getting-started/

## Current Behavior

The following packages have unmet dependencies:
 icinga2 : Depends: icinga2-bin (= 2.10.3-2.xenial) but it is not going to be installed
           Recommends: libreadline6 but it is not installable
E: Unable to correct problems, you have held broken packages.

## Steps to Reproduce (for bugs)

1. apt-get update
2. apt-get upgrade
3. apt-get install icinga2
4. 

## Context

The libreadline6-dev exists and can be installed, but the bin search the libreadline6 and this is not awailable on ubuntu. Any ideas? 

## Your Environment

* Blank Ubuntu Server 18.04.2 LTS and also on a blank Ubuntu Server 18.10

**Comment by ucola** [comment]
I don't add the icinga repository, i used the ubuntu repository for installation. now is working!

**Comment by ricardosaracino** [comment]
Having the same issue. i ran `icinga2` and installation still fails
