### ISSUE TITLE
Add unreserved_port_type attribute to icinga2_port_t

### ISSUE THREAD

**Issue by Elias481** [Icinga/icinga2#7029]
## Expected Behavior
It would be fine to have port 5665 labelled with icinga2_port_t to have defaults as other selinux port type definitions so include attribute unreserved_port_type.

## Current Behavior
```
$ seinfo  -ticinga2_port_t -x
   icinga2_port_t
      port_type
$ seinfo -tgit_port_t -x
   git_port_t
      defined_port_type
      port_type
      unreserved_port_type
```
(Possibly also defined_port_type should be added? Did not find information about that and did not actually need that but I think it could be fine to add that attribute, too...)

## Possible Solution
add correspondig lines to icinga2.te:
```
require {
    attribute unreserved_port_type;
}
typeattribute icinga2_port_t unreserved_port_type;
```
Result:
```
$ seinfo -ticinga2_port_t -x
   icinga2_port_t
      port_type
      unreserved_port_type
```

## Context
Some applications have deault policies in place that refer for instance to unreserved_port_type (and use this permissions in a generic way) and should be able to handle icinga ports the same way as most other / all default port labels without explicit additional permission for icinga2_port_type.

**Comment by dgoetz** [comment]
Thanks for bringing this up, pull request is open.
