### ISSUE TITLE
http status codes in icinga mainlog

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icinga2#7053]
hi,
It would be nice if the mainlog lines for API requests would also include the http status code of the response. Took me forever to figure out why process-check-result would sometimes fail.

Instead of:
`[2019-03-27 03:30:01 +0100] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [x.x.x.x]:58974), user: someuser)`

something like:
`[2019-03-27 03:30:01 +0100] information/HttpServerConnection: Request: "POST /v1/actions/process-check-result" 200 (from [x.x.x.x]:58974), user: someuser)`

**Comment by dnsmichi** [comment]
At the time this request is logged, there's no response available. So even if this would be added, it will be a new log line asynchronously. The response code is sent back to the caller, including the error message ... does your script handle this properly?

**Comment by mphilipps** [comment]
Kinda, at least unless it is called from php and something eats the error output. 

I can see that an asynchronous status code wouldn't be to useful.

**Comment by dnsmichi** [comment]
A separate log line may be useful, but you'd need a unique request ID, which we don't have that clearly. It may be an idea though when overhauling the network stack. It follows the same principle with executed processes logging the PID, and once completed, logging the PID again.

Which application are you developing? Error handling is one of the first things you should consider when working with data fetching from APIs, maybe it needs improvements. If so, please move the topic over to https://community.icinga.com where others can share their thoughts too :)

**Comment by mphilipps** [comment]
It is not exactly an application I am developing, at least not one with any value for Icinga. 

We just have a small shell script for passive notifications that is used for activly informing the monitoring that something went wrong in a cronjob. In this case the cronjob was written in php. Originally the cronjob was using nsca for nagios and now is just calling the Icinga api with a minimal wrapper and poor error handling.

**Comment by dnsmichi** [comment]
Guess you're doing something like status checks already, similar to what https://icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#example-api-client-in-php shows :)

**Comment by Al2Klimov** [comment]
We could also just log the message once we've got the response. This would save the UID.

**Comment by PedroMSantosD** [comment]
I'm having a similar issue (icinga2-2.11.3-1.el7.icinga.x86_64),  I'm unable to tell why the client gets a 200 OK reponse from icinga API, but the service state and output are not updated to mysql Backend.

When following Icinga logs (mainLog), I can find the POSTs, the user, the agent; but I'm unable to tell what else happens. Example:
```
--
[2020-04-28 11:12:41 -0400] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [10.160.8.62]:54678), user: externalchecker, agent: Python-icinga2api/0.6.1). 
[2020-04-28 11:12:41 -0400] information/Checkable: Acknowledgement cleared for checkable 'Matching-Service-Name'.
--
[2020-04-28 11:13:03 -0400] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [10.160.8.62]:49148), user: externalchecker, agent: Python-icinga2api/0.6.1).
[2020-04-28 11:13:03 -0400] information/HttpServerConnection: HTTP client disconnected (from [10.160.8.62]:49148)
--
[2020-04-28 11:13:05 -0400] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [10.160.8.62]:49154), user: externalchecker, agent: Python-icinga2api/0.6.1).
[2020-04-28 11:13:05 -0400] information/HttpServerConnection: HTTP client disconnected (from [10.160.8.62]:49154)
```

On first log, I was lucky to see that Icinga2 has cleared an ACK matching a passive service; but otherwise I can not tell what was received by Icinga, so for subsequent logs, which hosts/services were affected?

-> Logging the filter component from the payload to the api call, would help resolve this

if you also Add a hash to the request an a subsequent new line with icinga API response code for said payload then superb!
