### ISSUE TITLE
check_tcp does not report performance data when certificate expire is not OK

### ISSUE THREAD

**Issue by kogaba** [Icinga/icinga2#7055]
## Describe the bug
No performance data when certificate expiration time is not OK

./check_tcp -H example.org -p 443 -S -D 200,10
OK - Certificate 'www.example.org' will expire on Wed 02 Dec 2020 12:00:00 PM GMT +0000.
TCP OK - 0,326 second response time on example.org port 443|time=0,326211s;;;0,000000;10,000000

./check_tcp -H example.org -p 443 -S -D 2000,10
WARNING - Certificate 'www.example.org' expires in 615 day(s) (Wed 02 Dec 2020 12:00:00 PM GMT +0000).

./check_tcp -H example.org -p 443 -S -D 2000,800
CRITICAL - Certificate 'www.example.org' expires in 615 day(s) (Wed 02 Dec 2020 12:00:00 PM GMT +0000).

## Your Environment
Debian 9.8 
monitoring-plugins 2.2-3

**Comment by dnsmichi** [comment]
Please report that problem at https://github.com/monitoring-plugins
