### ISSUE TITLE
Icinga URL/Port monitroing throwing false alarm.

### ISSUE THREAD

**Issue by basheerbabu007** [Icinga/icinga2#7067]
## Describe the bug
False alarm in URL/Port monitroing in Icinga below is the alert cotent. Plese help us to resolve the issue.

HTTP CRITICAL -   Status line output matched HTTP/1.1 200

**Comment by dnsmichi** [comment]
We're using GitHub as bug tracker and for feature requests, not for general community support. Please collect all the details required to understand and reproduce your problem, and ask your question over at https://community.icinga.com

**Comment by basheerbabu007** [comment]
thanks @dnsmichi
