### ISSUE TITLE
 critical/icinga-app: Error while parsing command-line options: unrecognised option '--disable-confd'

### ISSUE THREAD

**Issue by HLA-systeem** [Icinga/icinga2#7083]
When running `icinga2 node setup --master --disable-confd`

* Version used: `r2.8.4-1`
* Operating System and version: `Alpine Linux 3.8.4`
* Enabled features: `ido-pgsql, checker, command, api`
* Icinga Web 2 version and modules: `2.4.2 , setup, director`
* Config validation: `Finished validating the configuration file(s) (no problems)`
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes: `no`

Also tried without the `--` but `"0 arguments may be specified"`
Everything works fine without `--disable-confd` as well.

**Comment by mcktr** [comment]
Hi,

the option `--disable-confd` was introduced in v2.9.0, therefore it is not possible with v2.8.4. Please update to a newer version of Icinga 2.

Kind regards
Michael
