### ISSUE TITLE
How to display script output on Icingaweb2

### ISSUE THREAD

**Issue by aspryne** [Icinga/icinga2#7098]
## Is your feature request related to a problem? Please describe.
I want display on icingaweb2 a script result's. I got latest version of icinga2/web/Centos7

## Describe the solution you'd like
I got a script that use parameters to display the number of mail I have in my mailbox.

## Describe alternatives you've considered
I don't know how to plug this script with icinga, maybe i must only modify commande.conf ? or service.conf too ? or anything else ? I don't know =/
## Additional context

its a ruby script, and this is an exemple of output :

You got  101 mail(s)
Latest mail received at: 2019-04-09 07:08:28 +0000

thanks for your help.

**Comment by dnsmichi** [comment]
Hi,

this is our bug and issue tracker. Please ask such questions on https://community.icinga.com

Cheers,
Michael
