### ISSUE TITLE
Is there any features available in Icinga to Monitor GitHub Appliance

### ISSUE THREAD

**Issue by vivuu1989** [Icinga/icinga2#7104]
Hi Experts,
 Looking for available features in ICinga to monitor GitHub Appliance . Right now
 We dont have a proper monitoring system for monitoring the appliance GitHub, there we are looking for a single monitoring solution instead of different monitoring solutions, use a central one with a well defined notification / processes

Is Icinga have features to monitor these things as  a single point of monitoring solution.. 

We tried with different monitoring solutions but that is distributed.. cant relay in one tool.

**Comment by dnsmichi** [comment]
Hi,

this is our issue and bug tracker. For specific project questions, please join our community channels at https://community.icinga.com 

Further include all relevant URLs and descriptions so that everyone knows what exactly a "GitHub appliance" will be.

Cheers,
Michael
