### ISSUE TITLE
Re-write ObjectLock's implementation details

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7123]
Don't ask for the motivation, just look at ObjectLock.cpp. It's hell-on-earth.

**Comment by dnsmichi** [comment]
On a more serious note: We try to avoid compiler optimizations such as `likely`, and also the implemented spinlock wait uses compiler macros. There should be a way to use C++11 alongside atomic here.

https://stackoverflow.com/questions/26583433/c11-implementation-of-spinlock-using-atomic
https://gist.github.com/jhaberstro/32e7f18b3c1878c945a1bd34efe412ad
http://anki3d.org/spinlock/
