### ISSUE TITLE
Comment sync in HA Setup not working properly (deleted comments are recreated)

### ISSUE THREAD

**Issue by mattef92** [Icinga/icinga2#7136]
## Describe the bug

In my HA-Setup I got two masters in a Zone. When a comment is created via Icingaweb2 and one node is down, the comment is deleted only on one node. When the second one is started again, the comment is created on the other node again. Result is the comment existing on both nodes.

This is also visible in the history. After startup of the second master, the history shows two "created comment" entries and only one has a date when it was deleted.

## To Reproduce

1. Create an Icinga2 ha setup with two masters
2. Both masters get "accept config" and "accept commands" in the api.conf
3. Enable "command transport" in icingaweb2 for both instances
4. Create a comment in icingaweb2
5. Shutdown one of the nodes
6. Delete the comment
7. Startup the node again
8. Watch the comment appearing again with a history showing 2 create comment entries on the same date

## Expected behavior
The comment should be deleted on the host that was not available at the time of deletion. The comment **shouldn't** be copied to the more current node. 

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.10.3
* Enabled features (`icinga2 feature list`): api
* Icinga Web 2 version and modules (System - About): 2.6.1 and Monitoring Module

Icinga2 api.conf:
* accept commands = true
* accept config = true

Icingaweb2 commandtransport.ini
* Both master nodes as different instances

**Comment by dnsmichi** [comment]
That's a partial duplicate from #4808 and a follow-up problem with making downtimes/comments a config object, stored in a different location than the state file. There's no solution thus far.

**Comment by Al2Klimov** [comment]
@dnsmichi Haven't you solved this together with @bobapple?

**Comment by bobapple** [comment]
The issue we've been working on was about a "downtime loop" where downtimes were ping-ponged between two masters. It's documented in https://github.com/Icinga/icinga2/issues/7198

I'm not sure if this is the same issue.

**Comment by Al2Klimov** [comment]
The fix is object type agnostic, so it fixes comments as well.

**Comment by Al2Klimov** [comment]
The PR which fixed #7198 is included in v2.11.0 and seems pretty type-agnostic to me, so I consider this being fixed as well.

@mattef92 Please try v2.11.6 (just to be sure).

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
