### ISSUE TITLE
Windows build fails on latest git master

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga2#7138]
## Describe the bug
I can't build the current master on my Windows development VM. I get the following build errors:

```
  C:\Users\Michael\source\repos\icinga2\lib\base/object.cpp(31): error C2065: 'm_LockOwner': undeclared identifier [C:\
Users\Michael\source\repos\icinga2\build\lib\base\base.vcxproj]
  C:\Users\Michael\source\repos\icinga2\lib\base/value.cpp(22): error C2665: 'boost::variant<boost::blank,double,bool,i
cinga::String,icinga::Object::Ptr>::variant': none of the 3 overloads could convert all the argument types [C:\Users\Mi
chael\source\repos\icinga2\build\lib\base\base.vcxproj]
  C:\Users\Michael\source\repos\icinga2\lib\base/value.cpp(26): error C2665: 'boost::variant<boost::blank,double,bool,i
cinga::String,icinga::Object::Ptr>::variant': none of the 3 overloads could convert all the argument types [C:\Users\Mi
chael\source\repos\icinga2\build\lib\base\base.vcxproj]
  C:\Users\Michael\source\repos\icinga2\lib\base/value.cpp(30): error C2665: 'boost::variant<boost::blank,double,bool,i
cinga::String,icinga::Object::Ptr>::variant': none of the 3 overloads could convert all the argument types [C:\Users\Mi
chael\source\repos\icinga2\build\lib\base\base.vcxproj]
  C:\Users\Michael\source\repos\icinga2\lib\base/value.cpp(34): error C2665: 'boost::variant<boost::blank,double,bool,i
cinga::String,icinga::Object::Ptr>::variant': none of the 3 overloads could convert all the argument types [C:\Users\Mi
chael\source\repos\icinga2\build\lib\base\base.vcxproj]
  C:\Users\Michael\source\repos\icinga2\lib\base/value.cpp(38): error C2665: 'boost::variant<boost::blank,double,bool,i
cinga::String,icinga::Object::Ptr>::variant': none of the 3 overloads could convert all the argument types [C:\Users\Mi
chael\source\repos\icinga2\build\lib\base\base.vcxproj]
  C:\Users\Michael\source\repos\icinga2\lib\base/value.cpp(42): error C2665: 'boost::variant<boost::blank,double,bool,i
cinga::String,icinga::Object::Ptr>::variant': none of the 3 overloads could convert all the argument types [C:\Users\Mi
chael\source\repos\icinga2\build\lib\base\base.vcxproj]
  C:\Users\Michael\source\repos\icinga2\lib\base/value.cpp(46): error C2665: 'boost::variant<boost::blank,double,bool,i
cinga::String,icinga::Object::Ptr>::variant': none of the 3 overloads could convert all the argument types [C:\Users\Mi
chael\source\repos\icinga2\build\lib\base\base.vcxproj]
  C:\Users\Michael\source\repos\icinga2\lib\base/value.cpp(50): error C2665: 'boost::variant<boost::blank,double,bool,i
cinga::String,icinga::Object::Ptr>::variant': none of the 3 overloads could convert all the argument types [C:\Users\Mi
chael\source\repos\icinga2\build\lib\base\base.vcxproj]
```

## To Reproduce
I use the PowerShell scripts to configure/build Icinga 2 on Windows.

1. Open _Developer Command Prompt for VS 2017_
2. Switch into the icinga2 directory
3. Run the configure script

```
powershell tools\win32\configure.ps1
```

4. Run the build script

```
powershell tools\win32\build.ps1
```

## Your Environment

* Windows 10
* MSVC 19.16.27026.1
* current git master
* tried boost v1.69.0 and v1.67.0

## Additional context

If I revert the changes from #7128 locally Icinga 2 builds successfully. 

Full log from the configure script:
[configure.txt](https://github.com/Icinga/icinga2/files/3108511/configure.txt)

Full log from the build script:
[build.txt](https://github.com/Icinga/icinga2/files/3108510/build.txt)

**Comment by mcktr** [comment]
I look into the changes from #7128 and I maybe found the reason for the build failure:

https://github.com/Icinga/icinga2/blob/d0e94c8efc488affd67eb7fe0444e7c4da87950a/lib/base/object.cpp#L28-L32

Here we call `m_LockOwner.store()`. Looking in the header file `m_LockOwner` seems only to be available in debug builds.

https://github.com/Icinga/icinga2/blob/d0e94c8efc488affd67eb7fe0444e7c4da87950a/lib/base/object.hpp#L197-L200

So either we need to make `m_LockOwner` not only available in debug builds or we need to add the `#ifdef I2_DEBUG` / `#endif` to the `m_LockOwner.store()` call.

Since I don't know which impact this change would have, I'll just leave this here for discussion.

**Comment by dnsmichi** [comment]
Only happens with release builds, I'm using debug builds mainly. Thanks.

**Comment by lazyfrosch** [comment]
GitLab CI also complained :) https://git.icinga.com/packaging/windows-icinga2/-/jobs/10314
