### ISSUE TITLE
Build on Fedora29 (aarch64) fails on latest git master

### ISSUE THREAD

**Issue by georg-h** [Icinga/icinga2#7139]
as there are no icinga2 packages for aarch64 in icinga-rpm-release-29-latest.noarch.rpm
I've tried to compile it myself following the instructions from https://icinga.com/docs/icinga2/latest/doc/21-development/#development-linux-dev-env

## Expected Behavior
successful build 

## Current Behavior
build stops with 

> [ 17%] Building CXX object lib/base/CMakeFiles/base.dir/object.cpp.o
>[ 17%] Building CXX object lib/base/CMakeFiles/base.dir/object-script.cpp.o
>/root/icinga2/lib/base/object.cpp: In constructor ‘icinga::Object::Object()’:
>/root/icinga2/lib/base/object.cpp:31:2: error: ‘m_LockOwner’ was not declared in this scope
 > m_LockOwner.store(decltype(m_LockOwner.load())());
 > ^~~~~~~~~~~
>make[2]: *** [lib/base/CMakeFiles/base.dir/build.make:676: lib/base/CMakeFiles/base.dir/object.cpp.o] Error 1
>make[2]: *** Waiting for unfinished jobs....
>make[2]: Leaving directory '/root/icinga2/release'
>make[1]: *** [CMakeFiles/Makefile2:1391: lib/base/CMakeFiles/base.dir/all] Error 2
>make[1]: Leaving directory '/root/icinga2/release'
>make: *** [Makefile:163: all] Error 2
>make: Leaving directory '/root/icinga2/release'
>compilation terminated.

## Steps to Reproduce (for bugs)
follow the steps from documentation

## Your Environment
* Version used (`icinga2 --version`): latest Git master
* Operating System and version: Fedora 29 aarch64 (Raspberry pi 3 B)
see attached cmake + build.txt with complete output

kind regards 
Georg

**Comment by georg-h** [comment]
[icinga2_build.txt](https://github.com/Icinga/icinga2/files/3109297/icinga2_build.txt)
[icinga2_cmake.txt](https://github.com/Icinga/icinga2/files/3109298/icinga2_cmake.txt)

**Comment by dnsmichi** [comment]
Thanks, my mistake. I'm using debug builds only, same as #7138.
