### ISSUE TITLE
Random very high satellites CPU load

### ISSUE THREAD

**Issue by janklewicz** [Icinga/icinga2#7167]
## Describe the bug
After each configuration deploy CPU load on 2 Satelites seems to go up or down randomly (sometimes 3x higher/lower than before) without any particular reason. Until now it was not affecting check latency but after last deploy  CPU load on both satellites (sometimes only on one satellite) went up to around ~300 for 28/32 cores and average check_latency started to go up (now around 5-10 seconds)

We have a distributed monitoring setup with one configuration Master in zone master and 2 Satellites in dedicated satellites zone. Configuration is synced top down from master to satellites.
All checks are performed on satellites. Master holds and deploys the configuration, sends perf datata to graphite, serves as web server for icingaweb2 and sends the notifications. We have no problem with master CPU Load.

Our host checks are doing a lot of API requests locally to satellite on which check is performed to get/change host configuration (eg. change check interval, get comments, change passive service state etc.)

Currently we have 36897 hosts and 18451 services (services with passive checks only).

## Expected behavior
CPU Load on satelites after each deploy should not  be 2x/3x times higher without significant change of hosts count. Short load spike is expected but 2x3x higher load for days is something really wrong.

## Screenshots
Each red bar is a configuration deploy perfomed on master and synced with satelites.
![image](https://user-images.githubusercontent.com/12608728/57359801-da0fe600-7178-11e9-8c6f-b38a9386adc8.png)

![image](https://user-images.githubusercontent.com/12608728/57359992-66220d80-7179-11e9-8235-5091694a75e1.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)
* Operating System and version:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-8-amd64
  Architecture: x86_64
 
* Enabled features (`icinga2 feature list`):
  MASTER: api checker graphite ido-mysql mainlog notification
  SATELITES: api checker mainlog
* Icinga Web 2 version and modules (System - About): not relevant
* Config validation (`icinga2 daemon -C`):
  OK On all nodes
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
  zones.conf attached with gdb stack for satelites.

  [MASTER.zip](https://github.com/Icinga/icinga2/files/3156325/MASTER.zip)
  [SAT1.zip](https://github.com/Icinga/icinga2/files/3156326/SAT1.zip)
  [SAT2.zip](https://github.com/Icinga/icinga2/files/3156327/SAT2.zip)

* SAT1 HW:
  ![image](https://user-images.githubusercontent.com/12608728/57361383-94edb300-717c-11e9-8043-79dcc08c9516.png)

* SAT2 HW:
  ![image](https://user-images.githubusercontent.com/12608728/57361346-86070080-717c-11e9-95c2-f8cc100d89a4.png)

## Additional context
Our first shot was that other virtual machines are consuming CPU but problem occurs after every config deploy so it's not related to virtual environment. Despite this we checked load on other machines and it's negligible.

**Comment by janklewicz** [comment]
For better overview below you'll find hosts count and load graph from the beginning of migration:

![image](https://user-images.githubusercontent.com/12608728/57517528-550f0300-7317-11e9-9d6e-83a72e787ea8.png)

**Comment by Al2Klimov** [comment]
Hello @janklewicz and thank you for reporting!

Please could you test v2.12-rc1?

Best,
AK

**Comment by lippserd** [comment]
Hi @janklewicz,

This may be related to #7590. What is the `log_duration` of your agent endpoints?
We recommend to set this to 0 for agents that are just command endpoints.

All the best,
Eric

**Comment by lippserd** [comment]
#5465 might be related too.

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
