### ISSUE TITLE
Language:Add Chinese

### ISSUE THREAD

**Issue by mm8m6m7m** [Icinga/icinga2#7182]
In the settings, add Chinese display.

**Comment by Crunsher** [comment]
This is probably an issue for icingaweb2, icinga2 has no display.
Open this issue here again: https://github.com/Icinga/icingaweb2

**Comment by dgoetz** [comment]
CLI has also output, so perhaps internationalization for this would be also a good idea for the future?

**Comment by Crunsher** [comment]
The only way this sounds feasible to me would be to offer localized packages, or building a new framework for the cli to support localized in and output

**Comment by dnsmichi** [comment]
I see some problems here:

- First off, a suitable framework which allows users and developers to generate statements for C++ code and re-generated on each release. 
- Second, you'll need to rewrite all CLI commands (don't underestimate the effort)
- Third, the CLI commands use the logger facility combined with stdout - this could reach the logging too with the demand to translate that as well
- Fourth, we cannot guarantee that everything which gets translated, is fully correct and not scam or anything evil.
- Fifth, CI which takes care of translation, builds, and what not. Eventually pulling additional package dependencies not available everywhere.

That being thought about, we would need a team just maintaining the translation stuff. Currently this is not doable with a small team of 3 core developers and 2 trainees. And even if there are, I don't think it is worth the effort - English is a global language, and one should cope with it on the CLI as well.

Cheers,
Michael
