### ISSUE TITLE
Agent notifies cluster of config reload and disconnect

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icinga2#7186]
## Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always using this feature but am missing [...]

This is a Feature Request

## Describe the solution you'd like

In bigger setups I have often seen the following behavior: admin/user deploys new config on the master and the master validates it and starts distributing it inside the cluster. Depending on which Zone the Change was in, it will have more or fewer agents the change will affect. Every agent which is in the updated distributed zone, will receive the update via the API and will validate the config and reload itself. And this is the moment, the agent disconnects. It is no longer available and reachable. This is expected behavior, but the cluster is not aware of that. If I have a Service and/or host check running with a low check and recheck interval, I will definitely get notifications. And yes we could discuss now, if the check and recheck interval is properly and could be longer. 

In larger setups with distributed zones, I regularly had users complaining they get false positive notifications after a config update from their hosts and services.

Missing Feature: 
The cluster is aware that the host will reload itself shortly and disables notifications for host and service objects until the agent has disconnected.
This could look like that:

1. The agent receives the config
2. It is validated and OK
3. The host sends a "I got a valid config update and will reload myself shortly" to the next node which sends it up to the next until the master is aware of this change, acts like described and disables the notifications
4. The master sends a 200 OK to the cluster and the node reloads itself
5. After reload, the node checks in again, master re enables the notifications

The user should decide if the cluster uses the feature (Turn on/off)

**Comment by dnsmichi** [comment]
@lippserd I've had a chat at OSDC with Simon about this. Not sure yet if it is doable, but that could be a good candidate for more config sync improvements.

**Comment by Al2Klimov** [comment]
@SimonHoenscheid Do you find it reasonable to work the notifications around by using `Checkable#max_check_attempts` and `Checkable#retry_interval`?

**Comment by SimonHoenscheid** [comment]
@Al2Klimov Like you wrote, this is a workaround, and I am pretty sure it might work. I am no longer managing a setup, which is big enough to experience this type of issue. I saw your response yesterday and had a look at the description again. This was considered this a feature request, what I still do. But this is a design problem. The cluster works as exspected, but this floods the user with false positive errors. I am still seeing the need to implement this feature.

**Comment by Al2Klimov** [comment]
> Do you find it reasonable to work the notifications around by using `Checkable#max_check_attempts` and `Checkable#retry_interval`?

And you, colleagues?

**Comment by julianbrost** [comment]
I don't think this will be implemented any time soon as proposed. The notification code is already quite complex and just adding yet another check certainly won't improve things there.

But when thinking about it, I had an idea for another workaround that would still allow frequent checks with a small number of rechecks to get notified fast during normal operation: you should be able to use [cluster-zone](https://icinga.com/docs/icinga-2/latest/doc/10-icinga-template-library/#cluster-zone) to check if an agent is connected and use this as a dependency for the other services that can't be checked while the agent is reloading.
