### ISSUE TITLE
check_service.exe has an ambiguous parameter in the ITL

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icinga2#7188]
## Describe the bug
When using check_service.exe which is part of the icinga2 windows agent package I have the following problem: when using the `-d` parameter in order to check for the service description instead of the service name of the windows service I want to check, it tells me:
```
C:\Program Files\ICINGA2\sbin> .\check_service.exe -s W32Time -d
option '-d' is ambiguous and matches '--debug', and '--description'
  -h [ --help ]         Print help message and exit
  -V [ --version ]      Print version and exit
  -D [ --debug ]        Verbose/Debug output
  -s [ --service ] arg  Service name to check
  -d [ --description ]  Use "service" to match on description
  -w [ --warn ]         Return warning (1) instead of critical (2),
                         when service is not running
```
So obviously ist mixes up the upper- and lowercase short parameters for `--debug` and `--description`.

My solution to fix this is to change the definition of the CheckCommand `service-windows` which comes from the ITL by replacing the `-d` there with the long form `--description`.

**Comment by mcktr** [comment]
Thanks :+1: 

I created #7190 to fix the underlying issue in check_service.
