### ISSUE TITLE
Icinga2 - Check result is late but not warning / error

### ISSUE THREAD

**Issue by Quentinvarquet** [Icinga/icinga2#7191]
## Describe the bug
Hello,

I am using icinga2 since many years but now i am using it with passive checks.

My check are coming to my icinga2 server every 5 minutes. 

When the resultat is late, i would like to see an error / warning on my services. For now I just have a " check resust is late " but the services it's still "OK".

Here is an example : 

![image](https://user-images.githubusercontent.com/7962157/58091267-74d0e180-7bc9-11e9-8874-76bd7e8468e5.png)

If my check is late, I want to get a critical or warning (even unknown why not ...) 
## To Reproduce
Create a host and a fake service with passive check and an interval 1 minute 

## Expected behavior
Warning / Error Or unknown state

## Screenshots
![image](https://user-images.githubusercontent.com/7962157/58091373-b792b980-7bc9-11e9-817e-50700777dc1e.png)

## Your Environment

* Version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.4.1-1)
* Operating System and version: Ubuntu 16.04
* Enabled features (`icinga2 feature list`): Enabled features: api checker command ido-mysql livestatus mainlog notification
* Icinga Web 2 version and modules (System - About): 2.1
* Config validation (`icinga2 daemon -C`): information/cli: Finished validating the configuration file(s).
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by MaBauMeBad** [comment]
What you are looking for is "check freshness", which require active checks.

Take a look at the Docs https://icinga.com/docs/icinga2/latest/doc/08-advanced-topics/#check-result-freshness

**Comment by dnsmichi** [comment]
Ah, @MaBauMeBad was faster than me, thanks.

Please also note that 2.4.1 is not supported anymore, please use the official packages from https://packages.icinga.com

Such configuration or behaviour questions should also be asked over at https://community.icinga.com  and as such, I am closing here.
