### ISSUE TITLE
Notification error stops notifications for other users for the same object

### ISSUE THREAD

**Issue by Duffkess** [Icinga/icinga2#7193]
## Describe the bug
I Have 2 different Icinga2 users that get notified by 2 different scripts.
(I used PowerShell and .NET Core)

UserA > Notification via ScriptA.ps1
UserB > Notification via ScriptB.ps1

I Noticied that sometimes UserA did not receive the notification.

I checked in the log and found out that there was a problem when parsing the comment to the PowerShell ScriptB saying:
`Unhandled Exception: System.ArgumentNullException: Value cannot be null.`
When there was a notification without a comment.
That was ok for me, because this was just experimental test.

But then I saw it looks like the error in ScriptB stops the notification process for this object completely and dont notify UserA with ScriptA.

Only when the ScriptA runned first the notification for UserA worked, then ScriptB got into the error and stopped the notifications.

## Expected behavior
I think it should be a complete indipendend process, a failure in one notification to one user should not affect other notifications for other users.

## Screenshots
In the log I see this:
`[2019-05-20 13:47:54 +0200] information/Notification: Completed sending 'Problem' notification 'myhost!myservice!NotifyA' for checkable 'myhost!myservice' and user 'UserA'.
[2019-05-20 13:47:54 +0200] information/Notification: Completed sending 'Problem' notification 'myhost!myservice!NotifyB' for checkable 'myhost!myservice' and user 'UserB'.
[2019-05-20 13:47:55 +0200] warning/Process: PID 8941 was terminated by signal 6 (Aborted)
[2019-05-20 13:47:55 +0200] warning/PluginNotificationTask: Notification command for object 'myhost!myservice' (PID: 8941, arguments: '/etc/icinga2/scripts/ScriptB.ps1' '-c' '') terminated with exit code 128, output:
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at Microsoft.PowerShell.CommandLineParameterParser.MatchSwitch(String switchKey, String match, String smallestUnambiguousMatch)
   at Microsoft.PowerShell.CommandLineParameterParser.EarlyParseHelper(String[] args)
   at Microsoft.PowerShell.CommandLineParameterParser.EarlyParse(String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)
   at Microsoft.PowerShell.ManagedPSEntry.Main(String[] args) in /PowerShell/src/powershell/Program.cs:line 22
<Terminated by signal 6 (Aborted).>`

When the ScriptB was triggered first, ScriptA is never mentioned in the logs.

## Your Environment
* Version used (`icinga2 --version`): r2.10.4-1
* Operating System and version: CentOS Linux release 7.6.1810 (Core)
* Enabled features (`icinga2 feature list`):  api checker command ido-mysql influxdb mainlog notification

PS: The problem about the PowerShell Script itself is not the Bug I'm complaining about, its just the dependency of the notification order.

**Comment by dnsmichi** [comment]
That's not possible, the notification is executed by the thread pool in an asynchronous fashion. The code doesn't wait for the execution itself, neither would it return before all users are notified.

Are you really sure that both users are notified from the same Notification object?

Please share additional debug logs and also the configuration snippets to reproduce the problem.

**Comment by dnsmichi** [comment]
Any updates here?

**Comment by Duffkess** [comment]
Its defenitly the same object that sends the notification.
The code snippets:

Thats the notification that was failing:

    apply Notification "notify-mail-service" to Service {
        command = "notificationcommand-mail-service"
        assign where host.address
        user_groups = ["usergroup-notification"]
        types = ["Problem","Custom","Acknowledgement","Recovery"]
        states = [ OK, Warning, Critical, Unknown ]
        period = "timeperiod-all"
        interval = "0"
    }

Thats the notification that worked only when it was the first processed notification:

    apply Notification "notify-xxx-service" to Service {
        command = "notificationcommand-xxx-service"
        period = "timeperiod-workhours-long"
        interval = "0"
        assign where service.notes
        users = ["xxx"]
    }

The command objects:

    object NotificationCommand "notificationcommand-mail-service" {
        import "plugin-notification-command"

        command = [ SysconfDir + "/icinga2/scripts/mail-service.ps1" ]

        arguments = {
            "-h" = "$host.name$"
            "-v" = "$service.name$"
            "-s" = "$service.state$"
            "-k" = "$service.vars.inet_customername$"
            "-f" = "$service.vars.inet_customeraddress$"
            "-o" = "$service.output$"
            "-d" = "$icinga.long_date_time$"
            "-t" = "$user.email$"
            "-i" = "$notification.type$"
            "-n" = "$service.notes$"
            "-c" = "$notification.comment$"
        }
    }

    object NotificationCommand "notificationcommand-xxx-service" {
        import "plugin-notification-command"
        command = [ SysconfDir + "/icinga2/scripts/xxx.ps1" ]
        arguments = {
                ..
        }
    }

You need to use PowerShell Core 6 on Linux to reproduce this, because of the error that says the parameter has to contain a value which is false when there is no comment.

I currently cant give you debug logs because I'm running on a production environment.

Dont know if its possible to reproduce with other scripts (it should be I guess actually..)

Thanks for you patience in this.

**Comment by dnsmichi** [comment]
The only real difference I can see is that one notification uses `users` while the other one focuses on `user_groups`.

In order to proceed here, we really need the logs. Especially lines with `Attempting to send` and others from the notice level for this notification name.

**Comment by dnsmichi** [comment]
Closing as no feedback was provided here.
