### ISSUE TITLE
Failed to delete "old active stage" when "new active stage" have created, icinga api return 500 status.

### ISSUE THREAD

**Issue by lxf1992521** [Icinga/icinga2#7194]
Icinga Version: r2.10.4-1

After create new package stages , and immediately delete "old active stage",  icinga api return 500 status.
Before I delete "old active stage" , the package active stage have changed, and point to "new active stage" already.

**Comment by dnsmichi** [comment]
Please take the time to fill in the issue template and provide the steps to reproduce the problem. Also, attach debug logs from the master to better see what's going on.

**Comment by lxf1992521** [comment]
What I do is to add zone/endpoint objetc by packages and stages api, and clean inactive stages automatically.

But After reading https://github.com/Icinga/icinga2/issues/6716 and https://github.com/Icinga/icinga2/pull/6473, I plan to give up achieving that add zone/endpoint objetc by packages and stages api, and waiting for developer to merge this features next release.

**Comment by dnsmichi** [comment]
Since you're ignoring my questions, I don't know what exactly the problem is. As such, if you want to elaborate in more detail, we may re-open this.

Cheers,
Michael
