### ISSUE TITLE
CheckerComponent error at installation

### ISSUE THREAD

**Issue by larsverp** [Icinga/icinga2#7195]
I'm not able to figure this bug out, and it's making me crazy..

Running command 'icinga2.exe daemon --validate' produced the following output:
information/cli: Icinga application loader (version: v2.6.2)
information/cli: Loading configuration file(s).
critical/config: Error: The type 'CheckerComponent' is unknown
Location: in C:\ProgramData\icinga2\etc\icinga2\features-enabled\..\features-available/checker.conf: 5:1-5:33
C:\ProgramData\icinga2\etc\icinga2\features-enabled\..\features-available/checker.conf(3):  */
C:\ProgramData\icinga2\etc\icinga2\features-enabled\..\features-available/checker.conf(4): 
C:\ProgramData\icinga2\etc\icinga2\features-enabled\..\features-available/checker.conf(5): object CheckerComponent "checker" { }
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
C:\ProgramData\icinga2\etc\icinga2\features-enabled\..\features-available/checker.conf(6):

**Comment by dnsmichi** [comment]
Hi,

would appreciate a full issue template including the full output of `icinga2 --version`. Two things: 1) 2.6.2 is not supported anymore 2) Windows as satellites with the checker feature are not supported. 

What's your intention with that?

Cheers,
Michael
