### ISSUE TITLE
libcrypto.so.1.1 segfault during director deployment

### ISSUE THREAD

**Issue by winem** [Icinga/icinga2#7207]
## Describe the bug
Icinga2 crashed during a deployment via the director. Just the `Additional Properties - Notes` of a service template was set. 

Unfortunately, as this was in production, I do not have a core dump I could provide. 

## To Reproduce
Repro is currently unknown but I will do some tests later today.

## Expected behavior
Successful deployment of the Service notes. 

## Your Environment
Icinga director v1.6.2

```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.5-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 18.04.2 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 4.15.0-47-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 7.4.0
  Build host: 8b8700ecb474

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

```
Disabled features: command compatlog debuglog elasticsearch gelf influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker graphite ido-mysql mainlog notification
```

## Additional context
Dmesg output: 
```
[Wed May 29 07:50:17 2019] icinga2[23229]: segfault at 48 ip 000014cf7be10d40 sp 000014cf54fe5e98 error 4 in libcrypto.so.1.1[14cf7bc23000+29c000]
```

Syslog:
```
May 29 07:52:47 do-ffm-icinga-01 systemd[1]: icinga2.service: Supervising process 23128 which is not our child. We'll most likely not notice when it exits.
May 29 07:52:57 do-ffm-icinga-01 kernel: [1793166.693184] icinga2[23229]: segfault at 48 ip 000014cf7be10d40 sp 000014cf54fe5e98 error 4 in libcrypto.so.1.1[14cf7bc23000+29c000]
```

I know this is not much as there is no repro (yet), no core dump and not much in the logs but it might be that someone has an idea. I will try to repro it later today, latest tomorrow.

**Comment by winem** [comment]
All my tests to reproduce the issue and find a reliable repro failed.

@dnsmichi to me, this looks like a quite unqualified issue that will probably just lay around until the end of time. So closing this issue would be "fine" for me unless you want to keep this open to do your own research or tests.

Just let me know if there is anything else I could provide that would be helpful.

**Comment by dnsmichi** [comment]
Well, if there's no reproducer, there's not much we can do about it. At least we can re-open it when you or someone else finds out more. Since 2.11 is on the horizon things may change sooner or later as well.
