### ISSUE TITLE
Allow more UoMs for perfdata

### ISSUE THREAD

**Issue by bobapple** [Icinga/icinga2#7225]
## Is your feature request related to a problem? Please describe.
Currently we support the UoMs for perfdata as described in the [Monitoring Plugins Guidelines](https://www.monitoring-plugins.org/doc/guidelines.html#AEN201). The guidelines are old and lack a lot of UoM's that should be supported by Icinga. The reason why we pay attention to the UoM is because some plugins change their perfdata output depending on the collected metric. Therefore we convert some values to a basic unit (eg. we convert `kb` to `bytes`)

## Describe the solution you'd like
My suggestion is to extend our support for UoM's and support the following units:
(Some of them are already supported)

|  Category       | UoM                          | Description |
|--------------|---------------------|-------------|
| Data               |                                    |                      |
|                        | b                                 | Bit                |
|                        | B                                 | Byte             |
|                        | KB                              | Kilobyte        |
|                        | MB                             | Megabyte    |
|                        | GB                              | Gigabyte     |
|                        | TB                              | Terrabyte    |
|                        | PB                              | Petabyte      |
|                        | KiB                             | Kibibyte       |
|                        | MiB                            | Mebibyte     |
|                        | GiB                            | Gibibyte       |
|                        | TiB                             | Tebibyte      |
|                        | PiB                             | Pebibyte     |
| Data Rate       |                                    |                      |
|                        | packets                     |  |
|                        | bits                            |  |
|                        | bytes                         | |
|                        | kilobytes                   | |
|                        | kilobits                      | |
|                        | megabytes               | |
|                        | megabits                  | |
|                        | gigabytes                 | |
|                        | gigabits                    | |
|                        | kbit                           | |
|                        | kbyte                        | |
|                        | mbit                          | |
|                        | mbyte                       | |
|                        | gbit                           | |
|                        | gbyte                        | |
| Time               |                                    |                      |
|                        | ns                              | Nanoseconds |
|                        | µs                              | Microseconds |
|                        | ms                             | Milliseconds |
|                        | s                                | Seconds |
|                        | m                               | Minutes |
|                        | h                                | Hours |
|                        | d                                | Days |
| Energy           |                                   |                        |
|                        | mW                           | Milliwatt         |
|                        | W                              | Watt               |
|                        | kW                            | Kilowatt |
|                        | Wh                            | Watt-hour |
|                        | Wm                           | Watt-minute |
|                        | mA                            | Milliampere |
|                        | A                               | Ampere |
|                        | kA                             | Kiloampere |
|                        | mV                            | Millivolt |
|                        | V                               | Volt |
|                        | kV                             | kiloVolt |
|                        | Lm                            | Lumens |
|                        | _O_                            | Ohm |
|                        | dBm                          | Decibel-Milliwatt |
| Mass              |                                     |                      |
|                        | mg                            | Milligram |
|                        | g                               | Gram |
|                        | kg                             | Kilogram |
| Length           |                                    |                      |
|                        | mm                           | Millimeter |
|                        | cm                            | Centimeter |
|                        | m                              | Meter |
|                        | km                            | Kilometer |
|                        | mi                             | Miles |
|                        | ft                              | Feet |
| Temperature |                                    |                      |
|                        | C / °C                       | Celsius |
|                        | F / °F                        | Farenheit |
|                        | K                               | Kelvin |
| Volume          |                                    |                      |
|                        | mL                             | Milliliters |
|                        | L                                | Liters |
| Throughput  |                                     |                      |
|                        | ops                           | ops/sec |
|                        | rps                           | requests/sec |
|                        | wps                          | writes/sec |
|                        | iops                          | I/O ops/sec |
|                        | rpm                          | reads/min |
|                        | wpm                         | writes/min |

Independently from the UoM,  we should always allow a time unit such as `*/s`, `*/sec`, `*/m`, `*/min`, `*/h`, `*/hour`, `*/d` and `*/day`

Instead of dropping values with unknown UoM's, we should rather just pass the values and give the user at least the chance to view the values.

## Things to consider
* We can not change the current conversion of values, this may break graphs in existing setups
* We need to find and verify a suitable conversion for each UoM
* I'm aware that there are tons of other UoM's, this should be a decent extension for the current state. We may consider more UoM's later.

## Additional context
Referred issues:
* https://github.com/Icinga/icinga2/issues/6849
* https://github.com/Icinga/icinga2/issues/6867

/cc @dnsmichi @lippserd

**Comment by bardahlm** [comment]
It would be nice if there was a method for telling performance data backends (like influxdb) which UoM being used, so that in turn Grafana can select the correct one.

**Comment by ohrly** [comment]
I would love to see this customizable. Like a feature to be enabled and than customize it with the config under /etc/icinga/feature-enabled/.
Anyways would be great if Icinga2 will support the units mentioned above!
For completion sake:
- Sound (dB, sone, Hz)
- Light (lumen)

**Comment by bobapple** [comment]
To eliminate potential errors with special character we should avoid using them. This applies specifically to the following UoMs:

* Microseconds (µs) -> us
* Ohm (O) -> O
* Celsius (°C) -> C
* Farenheit (°F) -> F

**Comment by Al2Klimov** [comment]
@lippserd We try case sensitive first, fall back to case insensitive and fall back to no normalization (as if UoM empty). We also silently turn kb into kilobits, but document that. Right?

**Comment by Al2Klimov** [comment]
@bobapple I'd like:

* Data: `echo {,{K,M,G,T,P,E,Z,Y}{,i}}B` – i.e.: B KB KiB MB MiB GB GiB TB TiB PB PiB EB EiB ZB ZiB YB YiB
* Data rate:
  * packets
  * `echo {,{k,m,g,t,p,e,z,y}{,i}}b` – i.e.: b kb kib mb mib gb gib tb tib pb pib eb eib zb zib yb yib
* Time: ns us ms s m h d
* Energy: `echo {m,,k}{{W,A}{,m,h},V}` – i.e.: mW mWm mWh mA mAm mAh mV W Wm Wh A Am Ah V kW kWm kWh kA kAm kAh kV
  * O
  * dBm
* Mass, Length, Volume, Throughput: (unchanged)
* Temperature: C F K

OK?

**Comment by Al2Klimov** [comment]
@bobapple What's m? Minutes or meters?

**Comment by lippserd** [comment]
> @lippserd We try case sensitive first, fall back to case insensitive and fall back to no normalization (as if UoM empty). We also silently turn kb into kilobits, but document that. Right?

Affirmative.

**Comment by bobapple** [comment]
> @bobapple I'd like:
> 
> * Data: `echo {,{K,M,G,T,P,E,Z,Y}{,i}}B` – i.e.: B KB KiB MB MiB GB GiB TB TiB PB PiB EB EiB ZB ZiB YB YiB
> * Data rate:
>   
>   * packets
>   * `echo {,{k,m,g,t,p,e,z,y}{,i}}b` – i.e.: b kb kib mb mib gb gib tb tib pb pib eb eib zb zib yb yib
> * Time: ns us ms s m h d
> * Energy:
>   
>   * `echo {m,,k}{{W,A}{,m,h},V}` – i.e.: mW mWm mWh mA mAm mAh mV W Wm Wh A Am Ah V kW kWm kWh kA kAm kAh kV
>   * O
>   * dBm
> * Mass, Length, Volume, Throughput: (unchanged)
> * Temperature: C F K
> 
> OK?

Agree

**Comment by bobapple** [comment]
> @bobapple What's m? Minutes or meters?

For now I would prefer m to be minutes. For the future we should leave the option open to categorize plugins and decide based on the plugin category/tag/label/whatever.

**Comment by Al2Klimov** [comment]
@bobapple So I'd put the length ones on ice.

**Comment by Al2Klimov** [comment]
@bobapple The normalized unit for mW/W/kW would be W, but for Wm/Wh? Should we add Ws as s are the normalized time unit?

**Comment by Al2Klimov** [comment]
@mxhash What's your opinion on this?

**Comment by Al2Klimov** [comment]
@lippserd Just discovered that we interpret e.g. MB (factor 1000) as MiB (factor 1024) which is wrong. May we break this – i.e. change the factor 1024 -> 1000?

**Comment by lippserd** [comment]
> @lippserd Just discovered that we interpret e.g. MB (factor 1000) as MiB (factor 1024) which is wrong. May we break this – i.e. change the factor 1024 -> 1000?

I'd say yes.

**Comment by Al2Klimov** [comment]
@mxhash I mean your opinion on this:

> @bobapple The normalized unit for mW/W/kW would be W, but for Wm/Wh? Should we add Ws as s are the normalized time unit?

**Comment by lippserd** [comment]
> @mxhash I mean your opinion on this:
> 
> > @bobapple The normalized unit for mW/W/kW would be W, but for Wm/Wh? Should we add Ws as s are the normalized time unit?

I opt for Wh here. Do we add MWh and so on as well?

**Comment by Al2Klimov** [comment]
I'd say yes.

**Comment by lippserd** [comment]
> I'd say yes.

😆 perfect. I had a little conversation with @mxhash and we agreed that Wh as normalised base unit makes sense.

**Comment by Al2Klimov** [comment]
@bobapple Shall we support the *things per time period* ones explicitly? Or can we just support them implicitly as an unknown UoM – as if no UoM given?

**Comment by bobapple** [comment]
> @bobapple Shall we support the _things per time period_ ones explicitly? Or can we just support them implicitly as an unknown UoM – as if no UoM given?

I would rather leave those values "untouched". Any calculation or normalization we would apply to this could lead to confusion. I think supporting them implicitly should be sufficient

**Comment by Wintermute2k6** [comment]
Hi ! 
Sorry for interrupting the peace but as far as i can tell we have an upcoming issue here where several customers that unknowingly update the actual nagios plugins to 2.3.2 (check_disk: Change unit calculations to always use binary units for backward compatibility (#518)) where the unit description suddenly changed from MB to MiB.

This resolves then in GraphiteWriter to drop those perfdata entirely
```
[2021-02-03 08:55:53 +0100] warning/GraphiteWriter: Ignoring invalid perfdata for checkable 'localhost!disks' and command 'nrpe' with value: /dev=0MiB;7137;7534;0;7931
Context:
	(0) Processing check result for 'localhost!disks'

[2021-02-03 08:55:53 +0100] warning/GraphiteWriter: Ignoring invalid perfdata for checkable 'localhost!disks' and command 'nrpe' with value: /dev/shm=0MiB;7147;7544;0;7942
Context:
	(0) Processing check result for 'localhost!disks'

[2021-02-03 08:55:53 +0100] warning/GraphiteWriter: Ignoring invalid perfdata for checkable 'localhost!disks' and command 'nrpe' with value: /run=104MiB;7147;7544;0;7942
Context:
	(0) Processing check result for 'localhost!disks'

[2021-02-03 08:55:53 +0100] warning/GraphiteWriter: Ignoring invalid perfdata for checkable 'localhost!disks' and command 'nrpe' with value: /sys/fs/cgroup=0MiB;7147;7544;0;7942
Context:
	(0) Processing check result for 'localhost!disks'

[2021-02-03 08:55:53 +0100] warning/GraphiteWriter: Ignoring invalid perfdata for checkable 'localhost!disks' and command 'nrpe' with value: /=2753MiB;72477;76504;0;80531
Context:
	(0) Processing check result for 'localhost!disks'
```

Question should be how we avoid such circumstances in existing setups .. maybe an ITL update , or at least some disclaimer for the used plugins ??

ref/nc701259

**Comment by Al2Klimov** [comment]
v2.13.0 with #7871 should do it.
