### ISSUE TITLE
Consider migrating to Boost fibers

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7228]
I.e. instead of threads and coroutines we'd spawn fibers (doing the same things) and all mutexes and CVs would be replaced with their equivalents from Boost fibers. Async operations' completion handlers would be not a yield context copied around, but a global yield_t from Boost fibers.

This way we would waste much less CPU cycles during locking and could just drop all these CpuBoundWork stuff w/o refactoring every single method signature.

To do before all of the above:

* [x] #7041

**Comment by dnsmichi** [comment]
I'm not sure whether Fibers are that mature in Boost 1.66, so this is something for the later future.

**Comment by Al2Klimov** [comment]
Even #7821 would be easier.
