### ISSUE TITLE
External REST service called on alarm

### ISSUE THREAD

**Issue by ric79** [Icinga/icinga2#7243]
Hello,
when an alarm is fired I need also to call an external service (REST) for healing that server.

Is it possibile?

Rr

**Comment by dgoetz** [comment]
This is not a question for a bug tracker, but have a look at [EventCommands](https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#event-commands) and get in touch with the [Community](https://community.icinga.com/).
