### ISSUE TITLE
Certificate requests not always in sync in a HA-setup

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icinga2#7246]
## Describe the bug
In a HA-Setup certificate requests are send to both masters, but if you sign a request the state is not always in sync so `icinga2 ca list` shows different state for the signed column. State is sometimes in sync without further action, sometimes reloading seems to sync the data, sometimes removing content of `/var/lib/icinga2/certificate-requests` is required.

## To Reproduce
No real way to reproduce, HA-setup and use of certificate signing proxy is required.

## Expected behavior
State is synced when signing a certificate (or at least periodically) 

## Screenshots
See the line marked in yellow.
![image](https://user-images.githubusercontent.com/3658213/59678895-d76bcc00-91cd-11e9-80fa-4c104f65c1cd.png)

We enabled debug logging but there are no entries for this. There is only a message that it sends the signed certificate to the satellite.

## Your Environment
* Version used (`icinga2 --version`): 2.10.5
* Operating System and version: CentOS 7
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql infkluxdb mainlog notification
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
![image](https://user-images.githubusercontent.com/3658213/59678865-c622bf80-91cd-11e9-99ef-a15bf438886a.png)

**Comment by dnsmichi** [comment]
Ah, the signed status, not the certificate request itself. Well, that is not supported by design - one should not have 2 Icinga CAs floating around. Each `ca list/sign` environment is sandboxed. As discussed a while ago with @bobapple, the on-demand signing feature is not to be used as inventory, now also stated in the docs.

**Comment by dgoetz** [comment]
Ok, we will move the feature and relevant checks from master role to config master role, so it is also a single point of failure like the director communication which can only be manually moved to the other node.

But it would be great to have this as a future feature.

**Comment by dnsmichi** [comment]
Not inside the core, such inventory tasks should be moved into an external component. Catch up with @bobapple in terms of sponsoring, this has been discussed a while ago already.

**Comment by Al2Klimov** [comment]
> Well, that is not supported by design - one should not have 2 Icinga CAs floating around.

I agree.

> Not inside the core, such inventory tasks should be moved into an external component.

I.e. _other construction area_ ™
