### ISSUE TITLE
Icinga2 Agent stuck in an infinite config sync loop

### ISSUE THREAD

**Issue by siklosipeter** [Icinga/icinga2#7258]
## Describe the bug
After installing and configuring the agent on two Windows Server 2016 hosts, the agents remain in a config sync loop.

I attached a relevant part of the agent's [debug.log](https://github.com/Icinga/icinga2/files/3321345/satellite.debug.log) and the [hosts config](https://github.com/Icinga/icinga2/files/3321378/satellite.icinga2.conf.txt) on the master, but the relevant (to me) part is here:

> [2019-06-24 14:23:04 +0200] information/ApiListener: Applying configuration file update for path 'C:\ProgramData\icinga2\var\lib\icinga2/api/zones/global-templates' (0 Bytes). Received timestamp '2019-06-24 14:23:04 +0200' (1561378984.461000), Current timestamp '2019-06-24 14:22:58 +0200' (1561378978.351000).
> [2019-06-24 14:23:10 +0200] information/ApiListener: Applying configuration file update for path 'C:\ProgramData\icinga2\var\lib\icinga2/api/zones/global-templates' (0 Bytes). Received timestamp '2019-06-24 14:23:10 +0200' (1561378990.575000), Current timestamp '2019-06-24 14:23:04 +0200' (1561378984.461000).
> [2019-06-24 14:23:16 +0200] information/ApiListener: Applying configuration file update for path 'C:\ProgramData\icinga2\var\lib\icinga2/api/zones/global-templates' (0 Bytes). Received timestamp '2019-06-24 14:23:16 +0200' (1561378996.766000), Current timestamp '2019-06-24 14:23:10 +0200' (1561378990.575000).
> [2019-06-24 14:23:22 +0200] information/ApiListener: Applying configuration file update for path 'C:\ProgramData\icinga2\var\lib\icinga2/api/zones/global-templates' (0 Bytes). Received timestamp '2019-06-24 14:23:22 +0200' (1561379002.910000), Current timestamp '2019-06-24 14:23:16 +0200' (1561378996.766000).

## To Reproduce

1. Defined a host with the required [host](https://github.com/Icinga/icinga2/files/3321378/satellite.icinga2.conf.txt)
2. Deployed a configuration
3. Installed Icinga2 Agent on satellite
2. Configured agent using the Setup Wizard and the Token from the directors Host / Agent panel
3. Waited
4. Enabled debug log, waited, disabled debug log, saved log

During the whole process, I neither changed anything on the master nor did not deploy non-existing changes.

## Expected behavior
The agent realizes that the config has not changed and keep using it without restarting

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Operating System and version: Windows Server 2016 (up-to-date)

### `icinga2 --version`
> icinga2 - The Icinga 2 network monitoring daemon (version: v2.10.5)
> 
> Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
> License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> System information:
>   Platform: Windows
>   Platform version: 8 (Server)
>   Kernel: Windows
>   Kernel version: 6.2
>   Architecture: x86_64
> 
> Build information:
>   Compiler: MSVC 19.0.24215.1
>   Build host: ICINGA-BUILD-WI
> 
> Application information:
> 
> General paths:
>   Config directory: C:\ProgramData\icinga2\etc\icinga2
>   Data directory: C:\ProgramData\icinga2\var\lib\icinga2
>   Log directory: C:\ProgramData\icinga2\var\log\icinga2
>   Cache directory: C:\ProgramData\icinga2\var\cache\icinga2
>   Spool directory: C:\ProgramData\icinga2\var\spool\icinga2
>   Run directory: C:\ProgramData\icinga2\var\run\icinga2
> 
> Old paths (deprecated):
>   Installation root: C:\Program Files\ICINGA2\
>   Sysconf directory: C:\ProgramData\icinga2\etc
>   Run directory (base): C:\ProgramData\icinga2\var\run
>   Local state directory: C:\ProgramData\icinga2\var
> 
> Internal paths:
>   Package data directory: C:\Program Files\ICINGA2\\share\icinga2
>   State path: C:\ProgramData\icinga2\var\lib\icinga2/icinga2.state
>   Modified attributes path: C:\ProgramData\icinga2\var\lib\icinga2/modified-attributes.conf
>   Objects path: C:\ProgramData\icinga2\var\cache\icinga2/icinga2.debug
>   Vars path: C:\ProgramData\icinga2\var\cache\icinga2/icinga2.vars
>   PID path: C:\ProgramData\icinga2\var\run\icinga2/icinga2.pid

### `icinga2 feature list`
> Disabled features: command compatlog debuglog elasticsearch gelf graphite ido-mysql ido-pgsql influxdb livestatus notification opentsdb perfdata statusdata
> Enabled features: api checker mainlog

### `icinga2 daemon -C`

> [2019-06-24 13:44:44 +0200] information/cli: Icinga application loader (version: v2.10.5)
> [2019-06-24 13:44:44 +0200] information/cli: Loading configuration file(s).
> [2019-06-24 13:44:44 +0200] information/ConfigItem: Committing config item(s).
> [2019-06-24 13:44:44 +0200] information/ApiListener: My API identity: HOSTNAME
> [...]
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 1 ApiListener.
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 2 ServiceGroups.
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 5 TimePeriods.
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 2 Endpoints.
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 11 HostGroups.
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 4 Zones.
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 231 CheckCommands.
> [2019-06-24 13:44:46 +0200] information/ConfigItem: Instantiated 1 FileLogger.
> [2019-06-24 13:44:46 +0200] information/ScriptGlobal: Dumping variables to file 'C:\ProgramData\icinga2\var\cache\icinga2/icinga2.vars'
> [2019-06-24 13:44:46 +0200] information/cli: Finished validating the configuration file(s).

**Comment by dnsmichi** [comment]
The timestamps look a bit out of sync, are you sure that the time service on Windows in running in sync (NTP)?

**Comment by siklosipeter** [comment]
> The timestamps look a bit out of sync, are you sure that the time service on Windows in running in sync (NTP)?

Both the client and the master runs as a vm under VMware. The VMware servers have the NTP service enabled. The only difference I found that they use different ntp servers, but according to my tests, the difference between the two servers are under 0.004 seconds:

> 25 Jun 17:02:11 ntpdate[8157]: adjust time server x.x.x.10 offset 0.003673 sec 
> 25 Jun 17:02:11 ntpdate[8156]: adjust time server y.y.y.23 offset 0.003819 sec

**Comment by siklosipeter** [comment]
What I don't understand (in this cleaned up part of the log) is that it seems like the timestamp is constantly updated in the config that the agent receives from the master. 

> [14:23:04] Apply config for global-templates'. Received timestamp '14:23:04', Current timestamp '14:22:58'
> [14:23:10] Apply config for global-templates'. Received timestamp '14:23:10', Current timestamp '14:23:04'
> [14:23:16] Apply config for global-templates'. Received timestamp '14:23:16', Current timestamp '14:23:10'
> [14:23:22] Apply config for global-templates'. Received timestamp '14:23:22', Current timestamp '14:23:16'

Can somebody point me to the relevant part of docs/code ?

**Comment by siklosipeter** [comment]
Source is your best friend. 
I think I found the issue, somehow the `.timestamp` in the `global-templates` got deleted:

> [user@host ~]# ls -l /var/lib/icinga2/api/zones/global-templates/
> total 0
> [user@host ~]# 

Thus the client did not receive a valid timestamp and simply [defaulted to NOW](https://github.com/Icinga/icinga2/blob/v2.10.5/lib/remote/apilistener-filesync.cpp#L96) instead of doing the sane thing and rejecting the config with: _You idiot, you have a problem in your config!_ 

I created the `.timestamp` manually and this seemingly terminated the sync loop. 
I'll do some changes/deployments and monitor this for a while.

**Comment by dnsmichi** [comment]
I've been giving a GitLab training in the past 2 days, so here's an additional thought on this: I'm not sure why exactly the `.timestamp` file isn't properly synced, likely a race condition inside the cluster config sync. Such scenarios are dealt with #6716 in the upcoming 2.11 release, which also changes the config change detection to checksums instead of timestamp offsets.

**Comment by gasmick** [comment]
Same behaviour with Linux and the latest snapshot packages 2.10.5+859.g3b7cf5b9b.2019.07.02

**Comment by dnsmichi** [comment]
There indeed was a bug which was fixed yesterday. Can you retry please, and also post the adjusted logs from that?

**Comment by dnsmichi** [comment]
RC packages are available for testing, do you have any chance to fire them again please? https://icinga.com/2019/07/25/icinga-2-11-release-candidate/

**Comment by dnsmichi** [comment]
I consider this fixed, the config sync has been tested in various scenarios now.
