### ISSUE TITLE
InfluxDBWriter should write reason for response code 400

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icinga2#7274]
## Is your feature request related to a problem? Please describe.
InfluxDBWriter logs "Unexpected response code: 400" which means Bad request and should contain a body with details according to InfluxDB. ([InfluxDB API docs](https://docs.influxdata.com/influxdb/v1.7/tools/api/): 400 Bad Request - Unacceptable request. Can occur with a syntactically incorrect query. The returned JSON offers further information.)

## Describe the solution you'd like
I would like to see a more detailed log entry to help with debugging.

## Describe alternatives you've considered
At the moment you would not to look into the logs on InfluxDB.

**Comment by dnsmichi** [comment]
> Can occur with a syntactically incorrect query. 

Example for a metric which causes this? Also, which version of Icinga are you using now?

I believe this works in the snapshot packages for 2.11 already, since we've changed parts in there originating from the network stack rewrite. InfluxDB now uses Boost ASIO & Beast as well.

**Comment by dgoetz** [comment]
> Example for a metric which causes this? 

Error seams very random to me in this environment. If log lines are really connected, some have no perfdata at all, others have multiple and work fine for a different host with the same check and perfdata. This was the reasons why I created the feature request to help me (and others) in similar cases in the future. And if this is already in 2.11 because of newer Boost, it makes me even more happy. :smile: 

> Also, which version of Icinga are you using now?

The environment is still pinned to 2.8.2 because of SLES 11. (I think you know which one I am talking about.) :disappointed:

**Comment by dnsmichi** [comment]
Ah, 2.8. Well, I remember this being changed a while ago since it annoyed us while testing customer specific requests in that feature. It should work with 2.10 already but I don't have the time to test it now. 

SLES11 is unsupported, but your customer knows that already :-) 

Anyhow, closing this.
