### ISSUE TITLE
Docs don't clearly tell whether/how freshness checks can be disabled

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7278]
## Describe the bug

Do I just have to disable active checks? Or just to set the check interval to 0? Or both?

**Comment by dnsmichi** [comment]
check_interval=0 is forbidden by the config compiler, just disable active checks.

**Comment by dnsmichi** [comment]
@Al2Klimov Since you've reported the issue, please fix this in the documentation from my explanation.
