### ISSUE TITLE
Setting up the PostgreSQL database

### ISSUE THREAD

**Issue by haniballl** [Icinga/icinga2#7285]
## Expected Behavior

export PGPASSWORD=icinga
psql -U icinga -d icinga < /usr/share/icinga2-ido-pgsql/schema/pgsql.sql

## Current Behavior

 psql -U icinga -d icinga < /usr/share/icinga2-ido-pgsql/schema/pgsql.sql
psql: FATAL:  Peer authentication failed for user "icinga"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by haniballl** [comment]
/var/lib/pgsql/data/pg_hba.conf

# icinga
local   icinga      icinga                                    md5
host    icinga      icinga      127.0.0.1/32          md5
host    icinga      icinga      ::1/128                   md5

**Comment by dnsmichi** [comment]
Hi,

please stop this. Join https://community.icinga.com and ask a precise question including all the details.

Regards,
Michael
