### ISSUE TITLE
Use Boost.Locale for date/time operations (TPs, formatting, etc.)

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#7288]
## Is your feature request related to a problem? Please describe.

Unit tests and timeperiod parsing code relies on C functions and different handling between Linux, Unix and Windows.

## Describe the solution you'd like

Replace tm structs with https://www.boost.org/doc/libs/1_66_0/doc/html/date_time.html

**Comment by dnsmichi** [comment]
I'll have a look for 2.11, since those unit tests are really really annoying AF.

**Comment by dnsmichi** [comment]
Unit tests will use this already for 2.11, the rest is changing the interfaces a lot and therefore scheduled for 2.12. Obvious benefit: Readable and better structured code than the C based implementation.

Affects:

- Utility::FormatDateTime (likely the format functionality as well)
- TimePeriod class
- SDs
- Compat-Features (don't fix them, they're deprecated anyways)

**Comment by Al2Klimov** [comment]
> Boost.DateTime's time zone support is broken.

– https://www.boost.org/doc/libs/1_72_0/libs/locale/doc/html/dates_times_timezones.html

**Comment by Al2Klimov** [comment]
After a treasure hunt through Boost.Locale's and its deps' code I finally got how to use it for our needs. @lippserd

**Comment by Al2Klimov** [comment]
Yes,

1. the lib is quite usable (if you know how)
2. it solves some problems more elegant
3. it's OOP

but

1. at the end of the day it's the same set year, set month, ... and do something
2. it silently breaks things which tm handles, e.g.:

```
Icinga 2 (version: v2.12.0-rc1)
Type $help to view available commands.
<1> => DateTime(2020, 2, 31, 17, 20, 1).format("%Y-%m-%dT%H-%M-%S")
"2020-03-02T17-20-01"
<2> =>
```

vs.

```
Icinga 2 (version: v2.12.0-rc1-6-g5f5d947a6)
Type $help to view available commands.
<1> => DateTime(2020, 2, 31, 17, 20, 1).format("%Y-%m-%dT%H-%M-%S")
"2020-03-31T17-20-01"
<2> =>
```

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icinga2/issues/7066#issuecomment-607196672
