### ISSUE TITLE
systemd unexpectedly kills Icinga root process

### ISSUE THREAD

**Issue by dasJ** [Icinga/icinga2#7291]
## Describe the bug

The default systemd unit file for icinga2 sets `KillMode=mixed`. According to the man page, this means that `the SIGTERM signal (see below) is sent to the main process while the subsequent SIGKILL signal (see below) is sent to all remaining processes of the unit's control group.`. This works well until icinga2 is reloaded. Then, the main process dies and a child process takes over. When using `systemctl stop`, icinga2 is killed with SIGKILL instead of SIGTERM

## To Reproduce

1. Have icinga running
2. Reload icinga
3. Stop icinga and watch the journal

## Expected behavior
Icinga2 should either keep the main process around or not set the KillMode to mixed

**Comment by MaBauMeBad** [comment]
See #7118 for details

**Comment by Al2Klimov** [comment]
It *is* the best choice as the others aren't an option. The problem is not the KillMode, but the wrong top process.

**Comment by Al2Klimov** [comment]
# How to reproduce

* fresh CentOS 7
* fresh Icinga 2 snapshot, single-node with nothing in `/etc/icinga2/conf.d/`
* `/lib/icinga2/safe-reload` #7301-patched (see below)

Run this one:

```bash
set -x; \
systemctl start icinga2.service; \
sleep 1; \
cat /run/icinga2/icinga2.pid; \
systemctl status icinga2.service; \
systemctl reload icinga2.service; \
sleep 1; \
cat /run/icinga2/icinga2.pid; \
systemctl status icinga2.service; \
systemctl stop icinga2.service; \
systemctl status icinga2.service; \
set +x
```

... and Icinga 2 will be killed w/o any warnings before:

```
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/usr/lib/systemd/system/icinga2.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Tue 2019-07-09 09:08:53 MDT; 13ms ago
  Process: 1573 ExecReload=/usr/lib/icinga2/safe-reload /etc/sysconfig/icinga2 (code=exited, status=0/SUCCESS)
  Process: 1619 ExecStart=/usr/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG} (code=killed, signal=KILL)
  Process: 1517 ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/sysconfig/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 1619 (code=killed, signal=KILL)
```

... unless you set `KillMode=none` and `ExecStop=/bin/bash -c 'set -e; /bin/kill $MAINPID; while /bin/kill -0 $MAINPID >/dev/null 2>&1; do /bin/sleep 1; done'`. (@dnsmichi Guess once what solution I'm about to suggest. 😄)

## `/lib/icinga2/safe-reload` patch

```patch
--- /lib/icinga2/safe-reload
+++ /lib/icinga2/safe-reload
@@ -47,5 +47,9 @@
 	exit 7
 fi

+while kill -0 $pid >/dev/null 2>&1; do
+	sleep 1
+done
+
 echo "Done"
 exit 0
```

**Comment by dasJ** [comment]
If introducing a depdency to libsystemd (for systemd builds), is okay, maybe a [notifying service](https://www.freedesktop.org/software/systemd/man/sd_notify.html) would be the proper solution.
This way, we can make it wait for reloads (write RELOADING=1 and READY=1, maybe even STATUS=), as well as notifying about a new PID (MAINPID=):
```
sd_notifyf(0, "READY=1\n"
        "STATUS=Processing requests…\n"
        "MAINPID=%lu",
        (unsigned long) getpid());
```

At a future point, FDs for client API connections could be passed to the new process (FDSTORE=1), so they won't get interrupted on reload.
Also, using the provided watchdog functionality could be a great benefit for reliability.

**Comment by Al2Klimov** [comment]
AFAIK we already depend on libsystemd and are already using `sd_notify()`.

**Comment by dasJ** [comment]
Yes, `lib/base/application.cpp`

**Comment by dasJ** [comment]
So parts are already implemented. `READY=1`, `RELOADING=1`, and `WATCHDOG=1`. To fix this issue, it should be enough to set `MAINPID=`

**Comment by dasJ** [comment]
Also, the service should be set to `Type=notify`

**Comment by Al2Klimov** [comment]
Both are already done.

**Comment by dasJ** [comment]
That's what you get from using an old unit file :( Thank you

**Comment by dnsmichi** [comment]
Happens here as well, we debugged this yesterday.

KillMode=process won't help much here.
Neither does type=forking, -d and Killmode=mixed.

The way we spawn processes upon reload is broken, the chain of

```
main -> process spawn helper -> reload main -> process spawn helper
```

gets broken during reload. The sd_notify logic doesn't help here. The warnings about "Supervising a child" are for real, and to my knowledge they started happening after either

1) Introducing the secondary process spawn helper process with 2.6
or
2) The changed reload handler with SIGUSR2 in 2.9

Either way, only a reload in the middle causes the STOP signal to kill everything. 

@Al2Klimov will evaluate an improved umbrella reload handling.
