### ISSUE TITLE
Expose SetActiveStage through API

### ISSUE THREAD

**Issue by darkweaver87** [Icinga/icinga2#7304]
Hello,

The packages/stages API is really usefull but I was thinking about for instance rollback/management process.
If you push a valid config but which breaks your monitoring - and you don't have your packages on git and so unable to push the old config - as far as I know you have to manually edit the active-stage file and put the older UUID and restart master. It may be useful to have a PUT method which simply allows you to do it.
Also, it might be interesting to have the informations of who and when the stage creation was done when you call GET /v1/config/stages/<package_name>/<stage_id>.

It's an open question, don't hesitate to challenge it :-)

Rémi

**Comment by dnsmichi** [comment]
The idea is to fetch the old stage which worked before, and re-deploy it again. This was mainly modeled for the Director in this regard. I'm not a friend of exposing the stage activation as a single action when the combined stage deployment ensures that integrity checks happen.

**Comment by darkweaver87** [comment]
Yes this is the idea :-)
OK I understand your point.
Actually when asking for such a method, I was thinking about triggering the stage validation the same way as in the POST method because we may encounter two failure cases:
- stage was already invalid -> don't activate it
- stage was valid at t but at t+1 someone pushed conflicting stuff and when activating at t+2 the stage is then not valid anymore -> don't activate it

**Comment by dnsmichi** [comment]
You can not only fetch the config content from the stage, but also the state and log files. Of course one needs to do a little tracking of deployed stages, the Director does that in a database table. 

- With using the state of a deployed stage, one can solve the first point with activate/not active.
- With storing the deployed stage history somewhere, you always know the last deployed stage which worked, and do a "rollback" in the way that you're pushing the working configuration again.

Can you provide some insights on your script/tool you're using the packages for?

**Comment by darkweaver87** [comment]
Hello,

Sorry for the delay :-)
Actually I have a CICD workflow which pushes config on git changes but I also have users who have the permission to push configs.
I managed to do what I wanted (global icinga configuration versionning) by implementing a python daemon which registers all changes through API using inotify on /var/lib/icinga2/api/packages and pushing it to a git.
When opening this "open question" I was thinking about users who don't git their config and use package/stage API and simply want to rollback a change without having to download "good" stage files and re-push it.

Rémi

**Comment by dnsmichi** [comment]
#7535 solves this in a different, more elegant way.
