### ISSUE TITLE
reserved words for filter_vars

### ISSUE THREAD

**Issue by jyoung15** [Icinga/icinga2#7324]
When using filter_vars as explained [here](https://icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#filter-variables), certain variable names are overwritten, causing unexpected results.

This was observed with variable names "host" and "service", but there may be more.  This should be documented or checked during config parsing.

## To Reproduce

Example to reproduce (replace "localhost" and "uptime" with valid host/service name):

```
curl -k -s -u root:icinga -H 'Accept: application/json' \
  -H 'X-HTTP-Method-Override: GET' -X POST \
  https://localhost:5665/v1/objects/services \
  -d '{ "filter": "host.name==host && service.name==service", "filter_vars": { "host": "localhost", "service": "uptime" }, "pretty": true }'
```
Empty result will be returned.

## Expected behavior
API call returns details about the host/service.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):  v2.10.5
* Operating System and version:  Gentoo
* Enabled features (`icinga2 feature list`):  api checker ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About):  2.6.3 / monitoring
* Config validation (`icinga2 daemon -C`): OK
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

I added some debugging in FilterUtility::EvaluateFilter to identify where the values are overwritten.  It appears the filter_vars values are overwritten [here](https://github.com/Icinga/icinga2/blob/master/lib/remote/filterutility.cpp#L98) (`frameNS->Set(varName, target);`).

**Comment by dnsmichi** [comment]
Scoped specific variables are always forbidden, same goes for apply rule expressions. There's not explicitly checked though since this varies in their actual usage, the config validation stage is too early. At this point the expression was not compiled nor run. The only way to catch the error is to run the expression resulting in "garbage" or 404 no objects found.

If you find a specific location where this can be documented, please send a PR.

**Comment by jyoung15** [comment]
Thank you for the clarification.  It took me a while to figure out why my filter was returning an empty value with no errors, so I thought I'd report this so other users don't waste time troubleshooting the same issue.  I will consider a PR to update the documentation as suggested.
