### ISSUE TITLE
Icinga web dashboard is not opening after setting up the same node as master node 

### ISSUE THREAD

**Issue by mayankkhullar** [Icinga/icinga2#7325]
ICINGA DASHBOARD NOT OPENING AFTER MASTER NODE SETUP , PREVIOUSLY IT WAS WORKING
Hi Dev's,

I have successfully installed icinga web , cli, api on RHEL 7.6 centos system and after that i setup my icinga dashboard with all the steps and my dashboard was running since last couple of weeks and 

Today I have started to setup master node on same ICinga web node and my icinga master node setup went successful but after restarting all the necessary components , my dashboard is not opening and i am getting "Connection timed out"

## To Reproduce
icinga node wizard 

Setup my node as a master node and provided all the necessary details.

1.Have Checked logs , restarted icinga2 but stil lsame issue
2.Nothing suspicious in logs
3.Restarted httpd , rh-php-fpm , icinga2

## Expected behavior
It should open my dashboard 

## Screenshots
Service status output 

### []# systemctl status icinga2.service
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/usr/lib/systemd/system/icinga2.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-07-15 07:24:42 PDT; 43min ago
  Process: 23668 ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/sysconfig/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 23678 (icinga2)
   CGroup: /system.slice/icinga2.service
           ├─23678 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
           └─23716 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log

 [2019-07-15 07:24:42 -0700] information/FileLogger: 'main-log' started.
 [2019-07-15 07:24:42 -0700] information/ApiListener: 'api' started.
 [2019-07-15 07:24:42 -0700] information/ApiListener: Started new listener on '[0.0.0.0]:5665'
 [2019-07-15 07:24:42 -0700] information/NotificationComponent: 'notification' started.
 [2019-07-15 07:24:42 -0700] information/ExternalCommandListener: 'command' started.
 [2019-07-15 07:24:42 -0700] information/CheckerComponent: 'checker' started.
 [2019-07-15 07:24:42 -0700] information/DbConnection: 'ido-mysql' started.
 [2019-07-15 07:24:42 -0700] information/ConfigItem: Activated all objects.
 [2019-07-15 07:24:42 -0700] information/cli: Closing console log.
 systemd[1]: Started Icinga host/service/network monitoring system. 

## Your Environment
RHEL 7.6 centos

* Icinga Web 2 version and modules (System - About):
* Web browser used:
* Icinga 2 version used (`ir2.10.5-1`):
* PHP version used (`7.1.8`):
* RHEL 7.6 centos:

**Comment by lippserd** [comment]
Hi,

Do you have problems with Icinga Web 2 or with Icinga 2? I don't get your issue.

Best,
Eric

**Comment by mayankkhullar** [comment]
firstly i have installed icinga 2 , icinga web and dashboard was working fine .

When i tried to install master/client setup , I ran icinga2 node wizard to make my same server(Icinga web ) as master node, my icinga web dashboard is not opening even after restarting all services

**Comment by lippserd** [comment]
What's your icinga web dashboard? Icinga Web 2? Could please post a screenshot of the error.

**Comment by mayankkhullar** [comment]
Yeah , Its icinga web 2 as per below url , th eone we use after setting up icinga web dashboard 

http://*************/icingaweb2/dashboard 

Error : Connection timed out

**Comment by lippserd** [comment]
This indicates problems w/ `max_execution_time`. Though PHP-FPM would give you a different error message. So thanks for NOT posting a screenshot. Please check your logs. There MUST be something. Since this is a configuration issue and not a bug, please head to the our community channels.

**Comment by mayankkhullar** [comment]
But previously It was working fine well , after node setup what happened ?

**Comment by dnsmichi** [comment]
Please join https://community.icinga.com and attach the requested screenshot and further logs and configs from your FPM service.
