### ISSUE TITLE
FeatureRequest: Allow array in arguments for CheckCommand objects

### ISSUE THREAD

**Issue by Z3po** [Icinga/icinga2#7326]
## The Problem I currently have
When migrating checks from simple-string (passing the command and the arguments in a single string) to command and arguments I've hit the problem when defining an argument multiple times. This has been implemented by the repeat_key attribute which can handle arrays and this way specify the parameter multiple times.

This currently only works if it's abstracted through a host or service variable.
This does neither work with CheckCommand variables nor with specifying an array in the arguments value.

The documentation suggests it works: https://icinga.com/docs/icinga2/latest/doc/09-object-types/#checkcommand-arguments

    Define argument array:
    value = "[ 'one', 'two', 'three' ]"

but it isn't. If i specify an arguments value like this it's passed as is as a parameter to my command.
The following CheckCommand:

    object CheckCommand "my_simple_checkcommand" {
        command = [ "/tmp/checkcommand" ]
        arguments = {
            "-a" = { value = "['one', 'two']" }
        }
    }

Results in the following execution (from the icinga debug log):

    notice/Process: Running command '/tmp/checkcommand' '-a' '['one','two']': PID 12478

## Describe the solution you'd like
I'd like to be able to specify an array within a specific argumentkey like described in the documentation

    object CheckCommand "my_simple_checkcommand" {
        command = [ PluginDir + "/check_http" ]
        arguments = {
            "-a" = { value = "['one', 'two']" }
        }
    }

or alternatively as a real array

    object CheckCommand "my_simple_checkcommand" {
        command = [ PluginDir + "/check_http" ]
        arguments = {
            "-a" = { value = ["one", "two"] }
        }
    }

Just let me know if I forgot any necessary information in this feature request.

## Why is this necessary

I'm using a setup where I configure Icinga2 through puppet and the icingaweb2 director.
There I can easily deploy services and commands. I specify my checks in puppet at the same place where I configure my services.
This is why I'd like to have a possibility to configure this in e.g. checkcommands only without the need to change e.g. the service definition.
Switching back and forth using the former or the newly generated checkcommand is just "easier".

While I know this is not completely "best practice" it's the solution we can easily use.
The current behaviour is from my perspective inconsistent and wrongly documented.
You may proof me wrong here because I misconfigured something or misunderstood the documentation...

By the way: I'm a fan of icinga2. Thanks a lot for what you've done!!

**Comment by dnsmichi** [comment]
The examples are somewhat unclear and don't allow simple copy paste. The first example you've put isn't of the array type, the double quotes render this of the string type. Use the debug console to test such values, use `typeof(value) == Array` for instance.

```
object CheckCommand "my_simple_checkcommand" {
    command = [ PluginDir + "/check_http" ]
    arguments = {
        "-a" = { value = "$foobar$" }
    }
    vars.foobar = [ 'one', 'two' ]
}
```

Should work perfectly fine. The latter is done inside ITL check commands already which require repeated arguments, either with the key repeated (repeat_key = true, default), or not.

**Comment by dnsmichi** [comment]
PS: That question qualifies better for https://community.icinga.com being a configuration question, not really a bug.

**Comment by dnsmichi** [comment]
Yeah, the docs need improvements here. Unfortunately the object types chapter is bloated already, so this needs short examples with a link to somewhere else where one can explain this in detail (if needed).

The preferred way of passing such values of the array type is done via host/service custom variables/attributes, hardcoding them into the command argument doesn't allow for much overrides. The command attribute instead allows for overriding this from the host/service level.

**Comment by Z3po** [comment]
Uh...when testing checkcommand-variables again, it just works that way....
I'm Sorry I don't know why that didn't work in the first place....

I still think it would be a nice feature to have the possibility to pass them directly in the argument definition. It would remove possibility to overwrite them in service/host definitions, but in my usecase that's not helpfull at all :)

I might be doing it wrong, but it just works for me this way...

**Comment by dnsmichi** [comment]
I see. I have never used the raw value inside the argument key, that's why I didn't understand your question.

The config compiler doesn't allow raw values here, it always needs a placeholder with a runtime macro references. If you want to specify a default value, you need to create one at the CheckCommand level.

The example below uses the longer bracket syntax, since the custom variable starts with a number - therefore quoting the key is required, and the indexer . doesn't work.

```
object CheckCommand "7326" {
  command = [ "/bin/echo" ]

  arguments = {
    "--test" = {
      value = "$7326_test$"
      skip_key = true
    }
  }

  vars["7326_test"] = [ "arr1", "arr2" ]
}

object Host "7326" {
  check_command = "7326"
  check_interval = 1s
}
```

```
$ icinga2 console --connect 'https://root:icinga@localhost:5665/'
Icinga 2 (version: v2.10.5-927-ge1314ca80)
Type $help to view available commands.
<1> => get_host("7326").last_check_result.command
[ "/bin/echo", "arr1", "arr2" ]
```

There you can see that I'm using `skip_key` to avoid printing the key at all.

If you modify the example to

```
-      skip_key = true
+      repeat_key = true
```

It will add the key and repeat it in front of every value inside the passed array.

```
$ icinga2 console --connect 'https://root:icinga@localhost:5665/'
Icinga 2 (version: v2.10.5-927-ge1314ca80)
Type $help to view available commands.
<1> => get_host("7326").last_check_result.command
[ "/bin/echo", "--test", "arr1", "--test", "arr2" ]
````

If you again modify this to `repeat_key = false`, only the first parameter is added, the array elements come up after that. 

```
$ icinga2 console --connect 'https://root:icinga@localhost:5665/'
Icinga 2 (version: v2.10.5-927-ge1314ca80)
Type $help to view available commands.
<1> => get_host("7326").last_check_result.command
[ "/bin/echo", "--test", "arr1", "arr2" ]
```

That highly depends on the plugin/script being called. Some implement getopts in the way they expect a list of values, others may detect multiple keys and merge them into a list. AFAIK Python's argparser allows for that.

In terms of your initial request, I'm not a friend of allowing this. Storing the values as custom variable inside the CheckCommand is a good way, and allows for easier debugging as well. 

Cheers,
Michael

**Comment by dnsmichi** [comment]
I've now largely rewritten the docs for command arguments and thrown away the old wrong examples. There are parts inside the docs which have never been touched for years now, well. Hard to get contributors for writing docs.

In terms of the feature request, I'll have to deny it. Use the proposed way with a custom variable on the command object, with the later opportunity to override this on the host/service level.
