### ISSUE TITLE
Consider automatically prefixing log messages with the current PID

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7328]
## Is your feature request related to a problem? Please describe.

We already have multiple Icinga processes at once during reload. With #7320 we'll have even more ones.

## Describe the solution you'd like

```
[2019-07-10 07:44:15 -0600] information/cli: icinga2[12964]: Closing console log.
```

## Describe alternatives you've considered

Put the PID earlier, but this would break the Director.

**Comment by dnsmichi** [comment]
Next to the Director parsing the format (should be possible with notifying @Thomas-Gelf asap when the patch is ready), our logstash grok patterns might need updates as well. I think we should evaluate this after 2.11.

**Comment by julianbrost** [comment]
See https://github.com/Icinga/icinga2/pull/7872#issuecomment-869847179 and the following comment.
