### ISSUE TITLE
Removing endpoint without removing dependant services messes up modified-attributes.conf

### ISSUE THREAD

**Issue by ricsil** [Icinga/icinga2#7333]
## Describe the bug

Not 100% sure if all of this is correct but here it goes:
If you delete endpoint file from Icinga (endpoint has to be used by some service, in our case services are  created via API), it will correctly report that configuration is broken. If you then remove those service files from Icinga too and restart it, modified-attributes.conf will become messed up -  contents of that file become seemingly randomly deleted. 

I assume it finds modified attributes of host/service that doesn't exist anymore and tries to delete it, but deletes too much? Would like a clarification.

## To Reproduce

1. Create new endpoint by creating `/etc/icinga2/zones.d/master/hosts/HOSTNAME.conf`:
````
object Host "HOSTNAME" {
  vars.cluster_zone = "HOSTNAME"
  check_command = "cluster-zone"
}
object Endpoint "HOSTNAME" {
  host = "HOSTNAME"
}
object Zone "HOSTNAME" {
  endpoints = [ "HOSTNAME" ]
  parent = "master"
}
````
2. Create a dummy host
````
curl -s -u USERNAME:PASSWORD -k -H "Accept: application/json" -X PUT https://icinga-master:5665/v1/objects/hosts/dummyhost -d '{ "templates": [ "generic-host" ], "attrs": { "address": "127.0.0.1", "check_command": "hostalive"} }'
````
3. Add dummy services to that host, command_endpoint set to that new endpoint
````
curl -s -u USERNAME:PASSWORD -k -H "Accept: application/json" -X PUT https://icinga-master:5665/v1/objects/services/dummyhost!dummyservice -d '{ "attrs": { "check_command": "disk", "command_endpoint": "HOSTNAME", "vars.disk_partitions": [ "/var", "/var/log" ]} }' 
````
4. Modify some attributes so modified-attributes.conf is not empty (for example, enable active checks, etc.) (Not sure if this counts, if you do this via WebUI it works 100%)
````
curl -s -u USERNAME:PASSWORD -k -H "Accept: application/json" -X POST https://icinga-master:5665/v1/objects/services/dummyhost!dummyservice -d '{ "attrs": { "enable_active_checks": "1"} }' 
````
5. Delete `/etc/icinga2/zones.d/master/hosts/HOSTNAME.conf` , run `icinga2 daemon -C`
6. Delete files that are highlighted but validator, restart Icinga

Modified attributes should now be toast.

## Expected behavior
Only wrong modified attributes should be deleted from modified-attributes.conf

## Additional context
Alternatively, Icinga should just not start with bad modified-attributes.conf file, so we can figure out what's wrong and go from there?

**Comment by dnsmichi** [comment]
> Modified attributes should now be toast.

Can you clarify on this, what exactly happens in there? Can you post its content?

**Comment by ricsil** [comment]
Sure. I'll try to recreate this so I can have concrete examples, but generally we're talking about losing 90% of its file size, so somehow the content gets nuked.

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
