### ISSUE TITLE
Unit tests for checkresult are unstable

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga2#7334]
Possible follow up for #7257 

There still seem to be some issues with `icinga_checkresult/service_1attempt`

Happens not every time, with a retry it worked fine.

```
 76/106 Test  #76: base-icinga_checkresult/service_1attempt ................................***Exception: SegFault  2.01 sec
Running 1 test case...
Before first check result (ok, hard)
First check result (unknown)
Notification triggered: Problem
Second check result (ok)
Notification triggered: Recovery
Third check result (critical)
Notification triggered: Problem
Fourth check result (ok)
Notification triggered: Recovery

*** No errors detected
```

* First try failed: https://git.icinga.com/packaging/deb-icinga2/-/jobs/13894
* Retry worked: https://git.icinga.com/packaging/deb-icinga2/-/jobs/13908

**Comment by dnsmichi** [comment]
Not able to reproduce this in Docker.

https://github.com/Icinga/icinga2/pull/7336 + 

```
root@c171693adefe:/icinga2# ./debug/Bin/Debug/boosttest-test-base --run_test=icinga_checkresult/service_1attempt
Running 1 test case...
Before first check result (ok, hard)
First check result (unknown)
Notification triggered: Problem
Second check result (ok)
Notification triggered: Recovery
Third check result (critical)
Notification triggered: Problem
Fourth check result (ok)
Notification triggered: Recovery

*** No errors detected
```

**Comment by dnsmichi** [comment]
Might be related #2292

**Comment by dnsmichi** [comment]
Seems the compiler on bionic is very unstable, it crashes with a segfault.
https://git.icinga.com/packaging/deb-icinga2/-/jobs/14020

**Comment by dnsmichi** [comment]
Something influences the compiler on Bionic x86 between `git diff f9f86e3f2 1fc660dcd33993d054ee2f10ea4857b89c6f07f4`.
