### ISSUE TITLE
Bootstraping of new satellite doesn't respect object dependencies - configuration not synced

### ISSUE THREAD

**Issue by dansmith-it** [Icinga/icinga2#7362]
Hello,
if I try to start a new satellite, the initial configuration sync fails, because the objects aren't sent in proper order, the hosts are sent before hostgroups:

`[2019-07-26 10:31:45 +0200] critical/config: Error: Validation failed for object 'example-NAS' of type 'Host'; Attribute 'groups': Object 'example-group' of type 'HostGroup' does not exist.`

and second later

`[2019-07-26 10:31:46 +0200] information/ConfigObjectUtility: Created and activated object 'example-group' of type 'HostGroup'.`

now the API sends the services, but white the hosts are missing no service is created.

Expected behavior will be at least to send hostgroups before hosts, but the dependency can be more complicated in another setup.

## Environment

Icinga2 version r2.10.5-1 from debian package - packages.icinga.com

**Comment by dnsmichi** [comment]
Notes for later fixing this: Similar object dependency tree as within the config compiler.

**Comment by Al2Klimov** [comment]
Hello @dansmith-it and thank you for reporting!

* Does this still occur with v2.11rc1?
* Please provide a minimal cluster structure, config and steps to reproduce.
* What's your OS version?

Best,
AK

**Comment by dnsmichi** [comment]
@Al2Klimov I've looked into the code already, there are no measurements taken to influence the order of objects being synced. That being said, if notification objects reach the master before their service objects, they won't be created.

This is a rare occasion which we never tested, or probably only with host-service objects in an alpha-numeric order.

**Comment by htriem** [comment]
@Al2Klimov

**Comment by Al2Klimov** [comment]
Sound like #7936.

@dansmith-it Please could you test the latest snapshot packages?

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
