### ISSUE TITLE
Icinga 2.11.0 RC1/Icingaweb 2.6.3: Icinga Web 2 does not properly detect Icinga 2

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icinga2#7367]
Same setup as in #7366 (CentOS 7.6, Icinga 2.11.0 RC1) with Icinga Web 2.6.3.

Works fine in general, but in the "Feature Commands" panel there are checkboxes for "Obsessing over Hosts"/"Obsessing over Services" (and some other features that weren't there before) that result in PHP stack dumps:

```
#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Instance/ToggleInstanceFeaturesCommandForm.php(269): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Instance\ToggleInstanceFeatureCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1161): Icinga\Module\Monitoring\Forms\Command\Instance\ToggleInstanceFeaturesCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/application/controllers/HealthController.php(99): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HealthController->infoAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}
```

**Comment by peteeckel** [comment]
Sorry, I was in a bit of a hurry yesterday and so here's some additional explanation of the issue and why I'm reporting it here instead of in the Icinga Web 2 project.

With Icinga 2.10.5, the "Feature Commands" panel looked like this:
![Screenshot 2019-07-28 at 11 51 26](https://user-images.githubusercontent.com/6815386/62005088-2fcbad00-b12e-11e9-9f5a-829a284f92f4.png)

With 2.11.0 RC1, the panel changed to this:
![Screenshot 2019-07-28 at 11 45 46](https://user-images.githubusercontent.com/6815386/62005084-22162780-b12e-11e9-906e-8cc124fcff12.png)

Same Icinga Web 2 version, same system, everything is unchanged except for the Icinga 2 version. So - without having looked at the code of Icinga Web 2, I admit - my assumption is that there is some way for Icinga Web 2 to detect what features can be enabled or disabled in Icinga 2, and that there is something wrong with that detection mechanism. 

The presence of the Nagios 1/Icinga 1 "obsess_over_{hosts, services}" feature selectors indicates that somehow Icinga Web 2 incorrectly assumes that it is talking to an Icinga 1 instance, and since Icinga Web 2 was not upgraded in any way this is most likely an Icinga 2.11.0 RC1 issue.

**Comment by peteeckel** [comment]
Had a look at the PHP code that leads to the old features being displayed. This is the part where it goes wrong in `ToggleInstanceFeaturesCommandForm.php`:
```
    public function createElements(array $formData = array())
    {
        $notificationDescription = null;
        $isIcinga2 = $this->getBackend()->isIcinga2($this->status->program_version);

        if (! $isIcinga2) {
            if ((bool) $this->status->notifications_enabled) {
                if ($this->hasPermission('monitoring/command/feature/instance')) {
```

So the observed behaviour happens when `$this->getBackend()->isIcinga2($this->status->program_version)` does not resolve to true. This is defined in `MonitoringBackend.php` as
```
    public function isIcinga2($programVersion = null)
    {
        if ($programVersion === null) {
            $programVersion = $this->select()->from('programstatus', array('program_version'))->fetchOne();
        }
        return (bool) preg_match(
            '/^[vr]2\.\d+\.\d+.*$/',
            $programVersion
        );
    }
```
Where the regex match expects either a `v` or an `r` in the first character of the version string. And the version string in the IDO DB is `r2.10.5-1` for 2.10.5 and `2.11.0-0.rc1.1` in 2.11.0 RC1, lacking the first character `v` or `r`.

**Comment by lippserd** [comment]
Thanks for the heads up @peteeckel 👍 Since we're about to release version 2.7.0 today, I made a PR for this: https://github.com/Icinga/icingaweb2/pull/3881

**Comment by dnsmichi** [comment]
Thanks. I'd prefer not to have those r and v variants anyways, seems that the Windows version semantics for the RC broke things here. Web 2.7.0 has a patch for this, so we're safe in the future.
