### ISSUE TITLE
Windows agent: Capture 'save-cert' output and allow to toggle verbose mode

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#7378]
## Is your feature request related to a problem? Please describe.

I wanted to see which TLS cipher and version is used when the setup wizard is fetching the parent public certificate.

This isn't possible since the connection is not made from within the C# app, but icinga2.exe and its CLI commands.

## Describe the solution you'd like

- `icinga2.exe save-cert` should log a bit more verbose including the TLS handshake and selected ciphers.
- The setup wizard captures the process output
- Allow to toggle between short and long output in the certificate step

![Screen Shot 2019-07-31 at 15 21 03](https://user-images.githubusercontent.com/382049/62215289-f356b600-b3a6-11e9-8335-8e22eb47cdc3.png)
![Screen Shot 2019-07-31 at 15 21 53](https://user-images.githubusercontent.com/382049/62215290-f3ef4c80-b3a6-11e9-9402-788ad12e0f9e.png)

**Comment by htriem** [comment]
Not relevant anymore, therefore I'm closing this ticket.
