### ISSUE TITLE
2.11.0 rc1 - An error occurred while upgrading the database

### ISSUE THREAD

**Issue by mzac** [Icinga/icinga2#7393]
## Describe the bug
Just did a apt upgrade on my Ubuntu 18.04.02 system from 2.11rc to 2.11rc1 and got an error

## Screenshots
```
An error occurred while upgrading the database:
 │
 │ mysql said: ERROR 1091 (42000) at line 10: Can't DROP
 │ 'commands_i_id_idx'; check that column/key exists
 │
 │ Fortunately,
 │ /var/cache/dbconfig-common/backups/icinga2-ido-mysql_2.11.0~rc1-1.bionic
 │ .2019-08-02-14.15.45 should hold a backup of the database, made just
 │ before the upgrade (unless the error occurred during backup creation, in
 │ which case no changes will have been applied yet). Your options are:
 │  * abort - Causes the operation to fail; you will need to downgrade,
 │    reinstall, reconfigure this package, or otherwise manually intervene
 │    to continue using it. This will usually also impact your ability to
 │

root@black:~# cat /var/log/apt/history.log

Start-Date: 2019-08-01  07:38:07
Commandline: apt upgrade
Upgrade: ubuntu-standard:amd64 (1.417.2, 1.417.3), ubuntu-minimal:amd64 (1.417.2, 1.417.3)
End-Date: 2019-08-01  07:38:08

Start-Date: 2019-08-02  14:15:40
Commandline: apt upgrade
Upgrade: icinga2-bin:amd64 (2.11.0~rc1-1.bionic, 2.11.0+rc1.26.g5d6649222.20190802.0724+bionic-0), icinga2-doc:amd64 (2.11.0~rc1-1.bionic, 2.11.0+rc1.26.g5d6649222.20190802.0724+bionic-0), icinga2-ido-mysql:amd64 (2.11.0~rc1-1.bionic, 2.11.0+rc1.26.g5d6649222.20190802.0724+bionic-0), icinga2-common:amd64 (2.11.0~rc1-1.bionic, 2.11.0+rc1.26.g5d6649222.20190802.0724+bionic-0), icinga2:amd64 (2.11.0~rc1-1.bionic, 2.11.0+rc1.26.g5d6649222.20190802.0724+bionic-0)
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2019-08-02  14:16:21
```

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):  v2.11.0-rc1-26-g5d6649222
* Operating System and version: Ubuntu 18.04.02
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`): No errors

**Comment by mzac** [comment]
Same error when I try and upgrade the schema manually

```
root@black:~# mysql -u root -p icinga2  < /usr/share/icinga2-ido-mysql/schema/upgrade/2.11.0.sql
Enter password:
ERROR 1091 (42000) at line 10: Can't DROP 'commands_i_id_idx'; check that column/key exists
```

**Comment by dnsmichi** [comment]
That's an update from 2.11.0rc from the testing repository back to snapshot package repo, undefined state reached. Is there a specific reason doing that?

**Comment by mzac** [comment]
Good question.... All I did was an apt update then apt upgrade... I didn't do anything out of the ordinary...

When I wanted to test 2.11 RC I commented out my old apt package file and added just the testing one.

However, I see that I have two apt repos setup for some reason, this could be my mistake?

```
-rw-r--r-- 1 root root  120 Jul 25 11:02 bionic-icinga.list
-rw-r--r-- 1 root root  136 Jul 25 11:02 bionic-icinga-testing.list
```

```
root@black:/etc/apt/sources.list.d# more bionic-icinga.list
deb https://packages.icinga.com/ubuntu icinga-bionic main
deb-src https://packages.icinga.com/ubuntu icinga-bionic main

root@black:/etc/apt/sources.list.d# more bionic-icinga-testing.list
deb https://packages.icinga.com/ubuntu icinga-bionic-testing main
deb-src https://packages.icinga.com/ubuntu icinga-bionic-testing main
```

**Comment by dnsmichi** [comment]
Not sure about the update here, the repos say stable and RC11 testing. `2.11.0+rc1.26.g5d6649222.20190802.0724+bionic-0` says that you're installing snapshot packages. Maybe the snapshot repo was configured but `apt-get update` was missing after its removal and you're doing a cached install.

Anyhow, I forgot that 2.11 drops some indexes. Merged that PR a while ago, and only Debian packages cover that actively.

The patch lacks some sanity checks though. This needs a rework similar to https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/upgrade/2.8.1.sql with the check if exists procedures. I'll look into this on Monday.
