### ISSUE TITLE
Windows agent - Default to lower case FQDN

### ISSUE THREAD

**Issue by bitboy85** [Icinga/icinga2#7407]
As described here https://community.icinga.com/t/windows-agent-hostname-case-sensitive/1899 the Setup Wizard of the Windows Agent might default to a FQDN where where lower and upper case letters are mixed. This might be a problem as icinga identifies host case sensitive. In my case using SNMP traps are complicated to handle because dnsresolver usually gives the fqdn in lower case.

**Comment by dnsmichi** [comment]
@LordHepipud do you see any problems with this, or how does the PS module handle this? Thanks.

**Comment by LordHepipud** [comment]
You can define on how the module will handle the FQDN - either per direct argument or by using the SelfService API of the Director.

The module will then either
* Leave the FQDN as it is
* Transform it to upper case
* Transform it to lower case

The argument for this is described here: https://github.com/Icinga/icinga2-powershell-module/blob/master/doc/10-Basic-Arguments.md#-transformhostname-optional

By using the SelfService API, you simply have to configure it to use the intended one:
![Director_SelfService](https://user-images.githubusercontent.com/5050288/62691690-7d1e0900-b9cf-11e9-9586-384ea5b54f7e.png)


Once the hostname is transformed to lower case for example, the certificate and endpoints are configured that way. Which means if within Icinga 2 directly the host object is set with a lower case FQDN everything will simply just work.

**Comment by dnsmichi** [comment]
Okidoki, thanks a lot. While looking into the module, I've seen https://github.com/Icinga/icinga2-powershell-module/issues/22 as well where different PS versions would return different host names. 

Since our form is free form, and the users may edit this anyways (I always do that), the suggestion could just use the lower case variant. I'd like to avoid a configuration knob, this complicates things. 

I did a little research how to retrieve this with C#, we're using an approach where DNS is not active. Alternatively one can just use Dns.GetHostName().

https://docs.microsoft.com/en-us/dotnet/api/system.net.dns.gethostname?redirectedfrom=MSDN&view=netframework-4.8#System_Net_Dns_GetHostName

I'll have a patch already, but no time this week.

**Comment by R-Sommer** [comment]
I'd also vote for Dns.GetHostName() as stated here [#84](https://github.com/Icinga/icinga2-powershell-module/issues/84#issuecomment-441240274)

**Comment by LordHepipud** [comment]
As we are going to get rid of PowerShell 2.x we can use

```
[System.Net.Dns]::GetHostEntry("localhost").HostName
```

entirely in the future and get proper results as outcome. On some hosts with older PowerShell Versions the output is either wrong or throws exceptions. So the goal is to require atleast PowerShell 3.x being installed on the system which is no problem on newer systems and shouldn't be either on older ones.

**Comment by dnsmichi** [comment]
https://icinga.com/2019/11/05/icinga-for-windows-rc-available/

**Comment by R-Sommer** [comment]
[System.Net.Dns]::GetHostEntry("localhost").HostName delivers fqdn whereas [System.Net.Dns]::GetHostName() delivers hostname only.

(But, will there be any progress once the framework is released? - I'd assume no)

**Comment by dnsmichi** [comment]
It should not take much time to implement, but our task list is quite long these days. Creating a Windows Dev environment is [documented](https://icinga.com/docs/icinga2/latest/doc/21-development/#windows-dev-environment), so if you'd like to lend a hand, much appreciated.

**Comment by R-Sommer** [comment]
I'd like to do so if I had enough knowledge.

**Comment by LordHepipud** [comment]
The actual idea would be to finish the Windows Framework and polish it as much as possible before the first release.

Once this is done, I will have a look on the old module issues and fix as many as possible and release 1.3.0 there. We will however not move forward with new features there, as the Framework is the new way to go.

**Comment by htriem** [comment]
@Al2Klimov
