### ISSUE TITLE
API: remove-downtime returns wrong status code/message if it fails

### ISSUE THREAD

**Issue by froehl** [Icinga/icinga2#7408]
## Describe the bug
/v1/actions/remove-downtime returns wrong status code/message if it fails

## To Reproduce
1. Create an ScheduledDowntime
2. Remove an Downtime-Instance from the ScheduledDowntime via API

icinga2.log:
`[..] warning/Downtime: Cannot remove downtime '005b!002r!f35dcced-7ca9-4a04-b7ec-8b195acd7638'. It is owned by scheduled downtime object '005b!recurring_downtime_ddd80655-10f7-5c73-8964-6a366b4ce814_524cc7dd-90ce-4d23-9041-0e3b8684cd2d'`

API-Response with Status **200**:
`{
    "results": [
        {
            "code": 200.0,
            "status": "Successfully removed downtime '005b!002r!f35dcced-7ca9-4a04-b7ec-8b195acd7638'."
        }
    ]
}`

## Expected behavior
API-Response with Status **400**:
`{
    "results": [
        {
            "code": 400.0,
            "status": "Cannot remove downtime '005b!002r!f35dcced-7ca9-4a04-b7ec-8b195acd7638'. It is owned by scheduled downtime object '005b!recurring_downtime_ddd80655-10f7-5c73-8964-6a366b4ce814_524cc7dd-90ce-4d23-9041-0e3b8684cd2d'."
        }
    ]
}`

or similar...

## Your Environment
* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: v2.11.0-rc1-26-g5d6649222)

* Operating System and version:
System information:
  Platform: Ubuntu
  Platform version: 18.04.3 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 4.15.0-55-generic
  Architecture: x86_64

* Enabled features (`icinga2 feature list`):
Enabled features: api checker command influxdb mainlog notification perfdata

**Comment by dnsmichi** [comment]
Error handling inside apiactions.cpp - Remove::Downtime() needs to be improved. The ScheduledDowntime with config_owner checks don't return an error to the caller.

I'll put this aside for a sprint with @htriem in the coming weeks.

**Comment by mtdeguzis** [comment]
@dnsmichi is this likely the same issue I am hitting with Icinga 2.7.0? If I try to remove a schedule downtime from overview > downtimes in Icingaweb, I get:

```
[2019-08-13 14:35:22 -0400] warning/Downtime: Cannot remove downtime 'host.domain.com!70dd2af0-d06d-43ba-9f7c-766476e5ca58'. It is owned by scheduled downtime object 'host.domain.com!sunday-downtime'
```

I've tried to find an open issue on this.

**Comment by dnsmichi** [comment]
That works by design, runtime downtimes created by ScheduledDowntime objects have a "config_owner" and as such cannot be deleted by the user via API actions.

This issue is solely to improve the error message returned to the caller.

**Comment by htriem** [comment]
@Al2Klimov
