### ISSUE TITLE
Zones in zones don't work well

### ISSUE THREAD

**Issue by dasJ** [Icinga/icinga2#7410]
I have a high-availability master setup (with 2.11). One of the hosts (A) holds `/etc/icinga2/zones.d`, while the other one (B) does not. Both are in the `master` zone, so everything **should** be replicated to B.
So what I decided to do was to create `/etc/icinga2/zones.d/master/zones.conf` which holds all zones. This gets properly replicated to B, as expected.
However, the objects in these zones (Hosts in my case) don't get instantiated properly. Some hosts get instantiated, some do not. It's not really logical what does and what does not.
Additionally, instantiation only takes place on A, so if B writes to the IDO, those objects are hidden from icingaweb and no check results are written to DB.

While this setup may seem pretty strange, it makes a lot of sense if you think of a config management perspective. This way, when adding hosts, zones, or services, only A needs to be applied so I really see this use case. Or maybe it's not the icinga way and I'm doing everything wrong. Either way, it would be a great help if someone could explain to me whether I stumbled over a bug or whether I deploy icinga wrong.

**Comment by dnsmichi** [comment]
> So what I decided to do was to create /etc/icinga2/zones.d/master/zones.conf which holds all zones. 

Such a scenario is not supported. You really need to define the zones outside of the cluster config sync. 

The things you **can** do - define the indirectly connected zones/endpoints in a cluster config sync zone, e.g. agents inside the satellite zone. This doesn't harm the **direct** communication between Icinga endpoints, being the master syncing the config to the satellite.

That being said, with the current design and its options, there's no sane way to detect and log this and tell the user to avoid this. If you're unsure about its behaviour, keep zones.conf outside of the cluster config sync and manage that with a tool of your choice. E.g. look into the Puppet module how things done there.

From a config management perspective, you don't push everything on the master - there are certain parts for setting up a satellite or an agent which are defined by roles or profiles. This includes deploying the zones and endpoint configuration to all nodes where needed.

In terms of the observed behaviour - I guess that Icinga loops somewhere with connections and the zone tree is not intact anymore. Without logs - hard to guess.

**Comment by dnsmichi** [comment]
Long and exhausting discussion in #7530.
