### ISSUE TITLE
2.11 rc1: built-in check command "icinga" doesn't work with version compare

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga2#7415]
## Describe the bug
At our test Cluster (2 master, 4 satellite in 2 zones) the built-in check  command "icinga" with the performance-data doen't work like before:
![image](https://user-images.githubusercontent.com/38723488/62943245-50f0f680-bdda-11e9-8e95-57995f434e43.png)
this error we got on every node.

## To Reproduce

define the build in check-command "icinga" on the icinga Server and after a check you get this message.
## Expected behavior
The check should work like before. e.g. 2.10.5
![image](https://user-images.githubusercontent.com/38723488/62943479-db395a80-bdda-11e9-9fe9-9c42be9156cd.png)

BTW: Other built-in check commands like "ido", "cluster" work like before. 

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.11.0-0.rc1.1
* Operating System and version: CentOS 7.6.1810

**Comment by dnsmichi** [comment]
Try removing icinga_min_version while testing the RC with a different version format. Seems the version detector needs a fix in there for "abnormal" versions.

**Comment by stevie-sy** [comment]
perfect, that's it (y). Whithout the variable "icinga_min_version" it works like before.

**Comment by dnsmichi** [comment]
Only happens with the RC packages, with a specific version.

```
[root@icinga2 demo]# icinga2 console --connect 'https://root:icinga@localhost:5665/'
Icinga 2 (version: 2.11.0-0.rc1.1)
Type $help to view available commands.

<7> => System.ApplicationVersion
"2.11.0-0.rc1.1"
```

<img width="1552" alt="Screen Shot 2019-08-13 at 17 37 52" src="https://user-images.githubusercontent.com/382049/62955539-85bc7800-bdf1-11e9-9899-b375335a916d.png">

**Comment by dnsmichi** [comment]
Fixed this in the proper way with using regex and adding unit tests for all functions involved.
