### ISSUE TITLE
unable to install from bionic-snapshots

### ISSUE THREAD

**Issue by maximo1610** [Icinga/icinga2#7426]
## Describe the bug
I am unable to install icinga2 using the bionic-snapshots repository due to dependency issues.

## To Reproduce
1. Install Ubuntu Server 18.04 LTS from cd and provide IP
2. Add Icinga2 repository following documentation from here (https://icinga.com/docs/icinga2/snapshot/doc/02-installation/) using the ubuntu method
3. Modify bionic-icinga.list to include '-snapshots' as I want to test 2.11
4. apt update && apt install icinga2

## Expected behavior
I would expect all dependencies to be met and the installation to complete.

## Output

```
apt install icinga2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 icinga2 : Depends: icinga2-bin (= 2.11.0+rc1.8.ga9d5fe431.20190730.1543+bionic-0) but it is not going to be installed
           Recommends: libreadline6 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

## Your Environment
bionic-icinga.list
```deb https://packages.icinga.com/ubuntu icinga-bionic-snapshots main```

## Additional context
libreadline6 is not available in the ubuntu repositories for bionic according to: https://packages.ubuntu.com/search?keywords=libreadline6

**Comment by sounddudenz** [comment]
Looks like libreadline6 has deleted and libreadline7 is now used.

Someone will need to update the dependices for the Bionic packages and rebuild

libreadline6  is no longer in universe or backports :-(

**Comment by maximo1610** [comment]
icinga2-bin should also be installed but will not be - that would be the main issue.

**Comment by maximo1610** [comment]
I just realised I should be making this post in the icinga-packaging repo. Closing - Sorry.
