### ISSUE TITLE
Powershell checks with a persistent session

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#7430]
TBD, just an ideas collection.

## Describe the solution you'd like

Run a persistent Powershell with specific loaded modules.

```
powershell -C { Use-Icinga; }
```

A special check command e.g. `powershell_session` may then run powershell commands.
Retrieve the returned state. 

Note: This doesn't work with normal powershell checks which automatically close the session.

## Describe alternatives you've considered

Workaround from https://community.icinga.com/t/windows-powershell-checks-with-icinga2/712

```
object CheckCommand "powershell_check" {
  import "plugin-check-command"
  command = [ "C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe" ]
  arguments = {
    "-command" = {
    value = "$ps_command$"
    order = -1
    }
    "-warn" = {
    value = "$ps_warn$"
    }
    "-crit" = {
    value = "$ps_crit$"
    }
    ";exit" = {
    value = "$$LastExitCode"
    }
  }
}
```

**Comment by lippserd** [comment]
Icinga for Windows already provides a daemon and in the future it will be mandatory to allow Icinga to perform checks using the daemon’s API.
