### ISSUE TITLE
incompatibility with mysql-connector-c-8.x.x

### ISSUE THREAD

**Issue by prometheanfire** [Icinga/icinga2#7436]
## Describe the bug
Tried to compile against mysql-connector-c-8.0.17, failed.  Tried icinga2-2.10.6.

## To Reproduce
Try to compile icinga2-2.10.6 against mysql-connector-c-8.0.17

## Expected behavior
I expect the compilation to succeed and the resulting application to 'work'.

## Screenshots
N/A

## Your Environment
Gentoo, it's best to look here at our bug.  Attached to it is a build log and `emerge --info`.  Let us know if there's more info needed.

https://bugs.gentoo.org/692654

**Comment by dnsmichi** [comment]
Please try with 2.11.0-rc1 where it is fixed with #7152.
