### ISSUE TITLE
No reconnect after connection loss with 2.11 RC1

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#7444]
Hi,

In short:

Two agents don't reconnect when the connection is broken due to network issues.

The long story:

I have a single master running in a datacenter and two agents as VM at another hoster. (In fact there are more agents, but I face the problem with these two). The hoster where the master is placed was under heavy ddos attacks lately and so the connection to the agents broke. When the attacks were over, the agents did not reconnect. The `icinga-zone` check showed that they are still disconnected.

Restarting the `icinga2` service on the agents restored the connection.

The problem is, I didn't see anything in the logs which might give a hint what was going wrong.

I now activated the debuglog and have another look.

All of the hosts involved run CentOS7 and Icinga 2 2.11 RC1.

If I can provide you with any more information, just go ahead and ask. I'm sorry, I can not provide you with anything which gives more insight.

**Comment by widhalmt** [comment]
I tried to reproduce the issue with the following:

```
firewall-cmd --add-rich-rule='rule family="ipv4" source address="[agent-ip]" reject'
tcpkill host [agent-ip]
firewall-cmd --remove-rich-rule='rule family="ipv4" source address="[agent-ip]" reject'
```

But to no success.

I don't know how long the attacks lasted in the past but I will try to reproduce the behaviour with a longer waittime between destroying the connection and reenabling it.

**Comment by widhalmt** [comment]
I extracted the logs from the other agent. I didn't have the debuglog active back then. I have it now and I will add logs as soon as I get anything useful.

Here's what I have by now.

These logs were written just before the last disconnect.

<img width="1597" alt="logs-before-disconnect" src="https://user-images.githubusercontent.com/504849/63598773-88bd2280-c5c0-11e9-9962-b3ceda8cec9a.png">

These are the interesting before the disconnect before the last

<img width="1312" alt="logs-before-last-disconnect" src="https://user-images.githubusercontent.com/504849/63598774-88bd2280-c5c0-11e9-90ea-1674145862f2.png">

This is what the icinga history looks like

<img width="887" alt="icinga-history" src="https://user-images.githubusercontent.com/504849/63598775-88bd2280-c5c0-11e9-9f03-2164cba68c6b.png">

These are the only logs I get now. I filtered them out in the above screenshots

<img width="1337" alt="remaining-logs" src="https://user-images.githubusercontent.com/504849/63598834-a8ece180-c5c0-11e9-83c9-50f83a36af7e.png">

**Comment by widhalmt** [comment]
I tried it with `drop` instead of `reject`, too. (thanks for the hint @Al2Klimov ). The client still reconnects. But I have to admit I just did try to block it for about 10 minutes. I'll give it another try with, say, 2 hours.

**Comment by widhalmt** [comment]
I applied the update to one of my testing hosts. "Unfortunately" the DDOS-attacks did not reoccur and I didn't manage to break the connection in a way that they won't reconnect. I'll keep you posted.

**Comment by Al2Klimov** [comment]
Maybe you could DoS your host by yourself from the same net so there aren't any collateral damages?
