### ISSUE TITLE
Service in neverending PENDING state

### ISSUE THREAD

**Issue by erik911** [Icinga/icinga2#7454]
## Describe the bug

- I have HA master setup with several zones. Master zone is parent zone for the ESX zone, and ESX zone is parent for the other zones.
- Whole service configuration is stored in global-zone.
- Some hosts are defined in the master zone, because we have direct connection between master zone and the checked servers via our backend network. 
- Only ESX zone is connected to frontend network. 
- I want to have ping check ( for the frontend IP ) executed on the ESX zone for servers which are defined in the master zone. I have this service in ESX zone already, but this check is in PENDING state forever. I understand that it is probably caused because host objects from the master zone are not propagated to its child zone ESX. 
- Is there any other way how to do it without separate host object with this service in the child zone?  

## To Reproduce
1. host object in the parent zone
2. service configuration in the global zone

apply Service "WIN_OS_Ping4" {
  import "generic-service"
  check_command = "ping4"
  zone = "ESX"
  vars += {
        ping_address = host.vars.customer_ip
        ping_wrta = "300"
        ping_crta = "350"
        }
  display_name  = "WIN_OS_Ping4"
  assign where host.vars.os == "Windows" && host.vars.customer_ip

}

## Expected behavior
Warning or error during compilation.

## Screenshots
![ping4](https://user-images.githubusercontent.com/54624632/63851098-da392900-c995-11e9-840b-055ac0b79395.JPG)

## Your Environment

* Version used (`icinga2 --version`): r2.10.5-1
* Operating System and version: SLES 12-SP4

**Comment by dnsmichi** [comment]
I'm not sure if that's really a bug or just a configuration problem with manually setting the `zone` attribute. In any case, this sounds like something other community members already have taken into account. Please ask such topics on our community channels at https://community.icinga.com
