### ISSUE TITLE
Draft: Embedded Python interpreter

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#7468]
TBD.

# Purpose 

- Compile and cache the plugin's code into core process memory
- Run the cached plugin in memory
- Save an entire fork-start-interpreter-compile-run-return chain

## Ideas

Provide access to Icinga's runtime state to plugins, e.g. through a PythonObject or function call. 

# Resources

The idea similar to Perl's package and subroutine handler is a good one, should be evaluated here as well.

## Python Docs

https://docs.python.org/3/extending/embedding.html
https://docs.python.org/3/c-api/index.html

## Libraries

https://www.boost.org/doc/libs/1_66_0/libs/python/doc/html/index.html
https://github.com/pybind/pybind11
https://github.com/lava/wrappy

## References

https://github.com/mickem/nscp/tree/master/modules/PythonScript
https://www.medin.name/blog/2012/02/12/embedding-python-inside-a-multithreaded-c-program/

**Comment by julianbrost** [comment]
I don't think that this will happen. This would add quite some complexity to the icinga2 process and make debugging issues even harder. In #8995 I suggested an alternative that could probably achieve the same goal but would require way less complexity within the icinga2 process.
