### ISSUE TITLE
Documentation Error/node setup flag not working.

### ISSUE THREAD

**Issue by madtempest** [Icinga/icinga2#7498]
## Describe the bug

The snippet [root@icinga2-master1.localdomain /]# icinga2 node setup --master --disable-confd from https://icinga.com/docs/icinga2/snapshot/doc/06-distributed-monitoring/#node-setup-on-the-master-node is generating the following error:

user@host:# icinga2 node setup --master --disable-confd
[2019-09-13 19:23:39 +0800] critical/icinga-app: Error while parsing command-line options: unrecognised option '--disable-confd'

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1. Install icinga2 from the icinga2 repo on fully patched Ubuntu 16.04
2. Run the command "icinga2 node setup --master --disable-confd" with the appropriate rights

## Expected behavior

As per https://icinga.com/docs/icinga2/snapshot/doc/06-distributed-monitoring/#node-setup-on-the-master-node the snippet [root@icinga2-master1.localdomain /]# icinga2 node setup --master --disable-confd should work.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 
icinga2 - The Icinga 2 network monitoring daemon (version: r2.4.1-1)

Copyright (c) 2012-2015 Icinga Development Team (https://www.icinga.org)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: _CODENAME=xenia
  Platform version: CODENAME=xenia
  Kernel: Linux
  Kernel version: 4.4.0-87-generic
  Architecture: x86_64

* Operating System and version:
Linux host 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Enabled features (`icinga2 feature list`):
Disabled features: api command compatlog debuglog gelf graphite icingastatus livestatus opentsdb perfdata statusdata syslog
Enabled features: checker mainlog notification

* Icinga Web 2 version and modules (System - About): N/A
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.4.1-1)
information/ConfigCompiler: Compiling config file: /etc/icinga2/icinga2.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/constants.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/zones.conf
information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/itl
information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command.conf
information/Utility: Loading library 'libmethods.so'
information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-icinga.conf
information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/timeperiod.conf
information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins
information/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-plugins.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/checker.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/mainlog.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/notification.conf
information/Utility: Loading library 'libchecker.so'
information/Utility: Loading library 'libnotification.so'
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/api-users.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/app.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/apt.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/commands.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/downtimes.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/groups.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/hosts.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/notifications.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/satellite.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/services.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/templates.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/timeperiods.conf
information/ConfigCompiler: Compiling config file: /etc/icinga2/conf.d/users.conf
information/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/_api/include.conf
information/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/_api/cherry-1568373732-1/include.conf
information/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/_api/cherry-1568373732-1/../active.conf
information/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/_api/cherry-1568373732-1/conf.d/downtimes/cherry.erebusnyx.net!load!cherry-1568373732-0.conf
information/ConfigItem: Committing config items
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 Zone.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 53 CheckCommands.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 13 Notifications.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 12 Services.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by K0nne** [comment]
Your Icinga package is quite old. I'm not sure if it's supported anymore. You should upgrade to the current release and test again.

**Comment by dnsmichi** [comment]
Yep, somehow you're using Ubuntu's old stale package and not what packages.icinga.com provides.

r2.4.1-1 vs 2.10.5
