### ISSUE TITLE
Unable to install Icinga 2.11.0-1 on Debian Stretch

### ISSUE THREAD

**Issue by sharkyzz** [Icinga/icinga2#7512]
## Describe the bug

Icinga 2.11 became available recently, but unable to install on Stretch

apt-get -s install icinga2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 icinga2 : Depends: icinga2-bin (= 2.11.0-1.stretch) but it is not going to be installed
           Recommends: libreadline6 but it is not installable
E: Unable to correct problems, you have held broken packages.

apt-get -s upgrade     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  icinga2-doc
Use 'apt autoremove' to remove it.
The following packages have been kept back:
  icinga2 icinga2-bin icinga2-common icinga2-ido-mysql
The following packages will be upgraded:
  icinga2-doc tzdata vim-icinga2
3 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Inst tzdata [2019b-0+deb9u1] (2019c-0+deb9u1 Debian:oldstable-updates [all])
Inst icinga2-doc [2.10.5-1.stretch] (2.11.0-1.stretch debian icinga-stretch:icinga-stretch [all])
Inst vim-icinga2 [2.10.5-1.stretch] (2.11.0-1.stretch debian icinga-stretch:icinga-stretch [all])
Conf tzdata (2019c-0+deb9u1 Debian:oldstable-updates [all])
Conf icinga2-doc (2.11.0-1.stretch debian icinga-stretch:icinga-stretch [all])
Conf vim-icinga2 (2.11.0-1.stretch debian icinga-stretch:icinga-stretch [all])

## To Reproduce

Upgrading from 2.10.5-1 -> 2.11.0-1

**Comment by sharkyzz** [comment]
libreadline6 is not available in the Repo of Stretch

**Comment by mcktr** [comment]
You need to enable the `stretch-backports` repository.

Add this to your sources.list:

```
deb http://ftp.de.debian.org/debian/ stretch-backports main
deb-src http://ftp.de.debian.org/debian/ stretch-backports main
```

Run `apt-get update`. Now you have to update Icinga 2 via `apt-get dist-upgrade`.

**Comment by sharkyzz** [comment]
That did it. Thanks a lot Michael!
