### ISSUE TITLE
New memcached check command but no plugin ready to install

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icinga2#7515]
With Icinga 2.11 a new check command "memcached" was implemented in the contributed plugins section. 

It's not a problem that it clashes with a check command I wrote for the check_memcached.pl plugin written by William Leibzon:

```
# ============================== SUMMARY =====================================
#
# Program : check_memcached.pl
# Version : 0.83
# Date    : Mar 23, 2013
# Author  : William Leibzon - william@leibzon.org
# Licence : GPL  (main code) summary below and full text at http://www.fsf.org/licenses/gpl.txt
#           LGPL (library functions) full text at http://www.fsf.org/licenses/lgpl.txt
#
# =========================== PROGRAM LICENSE =================================
```

Such things happen, and I'll gladly give the plugin the new check command uses a try. 

The problem is that there is neither a yum repository (at least not for EL6/7) that actually provides that plugin, nor a binary file on Icinga Exchange. 

Given the fact that it is at least cumbersome for the normal IT guy to have to build and install that plugin, would it be an option to either supply the plugin in binary and RPM-installable form or use the Perl plugin by William Leibzon instead? The way it is, the upgrade to Icinga 2.11 breaks a couple of my installations and probably some of other users as well.

**Comment by dnsmichi** [comment]
Adding such ITL commands is a matter of trust in the user that he/she has tested this very well. During review, we do not test these plugins as typically we don't have access to such an infrastructure.

I don't know what's best here, except than following the GitHub PRs and screaming "alarm, it breaks my setups" before reaching a release.

**Comment by peteeckel** [comment]
I don't doubt it has been tested, just not in every possible setup ... the main issue I have here is not that it doesn't work, it's that there is no easy way to get at the plugin (let alone to find out which one of the four or so memcached plugins it actually is :-)). 

It would probably be a good addition to the best practices to require at least that the plugin that is referenced in a check command is identified in a way that allows the users to find it, and ideally contains a pointer to installation media for the supported platforms. 

Meanwhile, I found the right one and installed it on a couple of test instances, and it seems to work really well. Building it is not such a big deal as well. I'm now looking into building RPMs for at the very least EL6 and EL7 (possibly EL8 in the near future as well), which I can then publish for anyone interested. Don't hold your breath, though ... it might take a couple of days.

**Comment by peteeckel** [comment]
OK, it wasn't that much work after all. I published a set of RPMs and SRPMs for EL6 and EL7 for testing on https://hindenburgring.com/check-memcached/.

Feedback is welcome. If anyone wants to use this as a base for "proper" packaging, please go ahead.

**Comment by Al2Klimov** [comment]
Hello @peteeckel and thank you for reporting!

So finally *you* more or less have created the "plugin ready to install"?

If yes, is this issue resolved?

Best,
AK

**Comment by peteeckel** [comment]
Regarding my specific environment (consisting mainly of CentOS/RHEL 6/7 servers) I'm fine, and if someone wants to use or host my RPMs they're very welcome to do so.

I'm not sure about other distributions of OS's, though. The memcached plugin referenced by the check command works very fine so far, and I will probably migrate all systems I'm currently monitoring to it, but it would be fine if at least plugins that are used for the check commands shipped with Icinga 2 should be available in ready-to-use form (ideally as an RPM, deb or whatever) for the supported platforms. 

I'm aware that it's not easy to keep track of this. One idea I had is to deliver plugin integrations in disabled form unless there is a valid link to a plugin in the Icinga Exchange, but I don't know if that would be feasible.

**Comment by dnsmichi** [comment]
Ah. Now I get it. The command docs refer to a Debian package. I'll take on my hat, I did not see this during PR reviews. Well, we better adjust the documentation and add the raw URL for the plugin then (if that exists).

Plugin packaging is something which is discussed, but someone needs to take the maintainer hat. Let's see about this in the future.

**Comment by peteeckel** [comment]
The download link in Icinga Exchange https://exchange.icinga.com/exchange/check_memcached/files/725/13-09-16_02-39-11_check_memcached.l points at the source for the plugin.

I've built some RPMs for plugins in the past, but in most cases they were RPMs for customers containing their required sets of plugins, not for specific single plugins. When I find the time I'll rework that stuff and build one RPM per plugin, which I can then contribute to whatever repository will be created down the road.
