### ISSUE TITLE
icinga2-2.11.0 fails to compile with boost-1.71.0

### ISSUE THREAD

**Issue by prometheanfire** [Icinga/icinga2#7525]
## Describe the bug

Cmake fails to find boost at all, which is odd...  1.70.0 works.

## To Reproduce

1. Install boost-1.71.0
2. try to compile icinga2

## Expected behavior

Compiles at least

## Your Environment

https://bugs.gentoo.org/695270 is the best refrence (has a bunch of logs, etc).

## Additional context

As a side note, requiring boost with context and coroutines support means dropping support for ppc ppc64 and arm on gentoo at least.  I've poked the boost maintainer about it for details (would be good to at least get ppc64 back).

**Comment by dnsmichi** [comment]
I've read the linked issue, but I don't quite understand why cmake cannot detect Boost 1.71. I've been using it on Windows lately. Maybe you need to explicitly pass the Boost include and library dirs.

**Comment by prometheanfire** [comment]
The boost error was my error.  1.71 does work (was missing the use flag on my first test).  Thanks for checking though.
