### ISSUE TITLE
Applied Dependency with ignore_on_error may survive despite bad parent

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7536]
## Describe the bug

I have some Dependency apply rules with `ignore_on_error` for the case the desired parent is absent in a particular case.

And in at least one such case the Dependency object survives silently with a bad parent set so `m_Parent==nullptr` and `IsAvailable()` crashes (#7531).

## To Reproduce

Build and run this:

```Dockerfile
FROM debian:10-slim
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

RUN apt-get update ;\
	DEBIAN_FRONTEND=noninteractive apt-get install --no-install-{recommends,suggests} -y \
		gnupg2 dirmngr ca-certificates ;\
	apt-get clean ;\
	rm -vrf /var/lib/apt/lists/* ;\
	apt-key adv --fetch-keys \
		'https://packages.icinga.com/icinga.key' \
	DEBIAN_FRONTEND=noninteractive apt-get purge -y gnupg2 dirmngr ca-certificates ;\
	DEBIAN_FRONTEND=noninteractive apt-get autoremove --purge -y

RUN echo 'deb https://packages.icinga.com/debian icinga-buster main' >/etc/apt/sources.list.d/icinga.list

RUN apt-get update ;\
	DEBIAN_FRONTEND=noninteractive apt-get install --no-install-{recommends,suggests} -y \
		icinga2-bin ;\
	apt-get clean ;\
	rm -vrf /var/lib/apt/lists/*

RUN echo 'apply Dependency "lolcat" to Service ignore_on_error { parent_host_name = host.name; parent_service_name = "lolcat"; disable_checks = true; assign where true }' >/etc/icinga2/conf.d/lolcat.conf

CMD /usr/lib/icinga2/prepare-dirs /etc/default/icinga2 ;\
	exec icinga2 daemon
```

## Expected behavior

The Dependency object shall be dropped silently on startup.

## Your Environment

See above Dockerfile.

**Comment by dnsmichi** [comment]
Note: `ignore_on_error` is something we only use internally. We don't suggest users to use this config directive as being only used in special occasions. Especially with apply, this never has been tested. Imho low priority.
