### ISSUE TITLE
Plugin returns other value as console call (check_by_ssh)

### ISSUE THREAD

**Issue by jakobroehrl** [Icinga/icinga2#7537]
## Describe the bug
Plugin returns
Remote command execution failed: bash: g:/nagios/check_cpu -c 100 -w 90 -U %: No such file or directory

If I trigger it from the console I get a return:
nagios@nagios-1:/usr/lib/nagios/plugins$ ./check_by_ssh -l user -H host -C "g:/nagios/check_cpu -c 100 -w 90 -U %"                           
CPU OK - CPU0 = 6%|'CPU0'=6%;90;100;;

All other checks an plugins are working properly.

## Your Environment
* Version used (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu 16.04
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.4.1

**Comment by dnsmichi** [comment]
Please move this question over to https://community.icinga.com

Before doing so, ensure that you upgrade to latest stable. 2.7.0 is EOL already.
