### ISSUE TITLE
Icinga2 Cluster functionality doesnt work with Icinga2 2.11

### ISSUE THREAD

**Issue by bahrpatrick** [Icinga/icinga2#7542]
Hello,

we noticed a bug in our Icinga2 cluster environment.
The active endpoint is not able to distribute the configuration to the passive endpoint.
The passive endpoint refuses the configuration updates, as we can see in the icinga2.log file.
We noticed this behavior since updating to Icinga2 v2.11.

`
[2019-09-26 12:18:03 +0200] information/ApiListener: Ignoring config update from endpoint 'IPSNBG6SRV01' for zone 'global-templates' because we have an authoritative version of the zone's config. 
`

In case of shutting down the Icinga agent on the active master the out of date config from the passive endpoint will be shown in icingaweb2.

Versions:
Centos 7.7 x64
Icinga2 2.11
IcingaWeb2 2.7.1

Modules:
Director 1.6.2
graphite 1.1.0
idoreports 0.9.1
incubator v0.3.0
ipl v0.3.0
monitoring 2.7.1
pdfexport 0.9.1
reactbundle v0.6.0
reporting 0.9.1
vspheredb master
x509 1.0.0

**Comment by ocstaron** [comment]
Additional information:

in /var/lib/icinga2/api/zones-stage/startup.log we found, that doesn't find the settings, which are configured in a config file under /etc/icinga2/zones.d/global-templates.

So it seems at this point during the validation the global-templates are ignored, which causes the main problem.

**Comment by dnsmichi** [comment]
Please share the full zones.conf to see how the two masters are configured.

Also, the authoritative copy sounds suspicious, can you enable the debug log on both sides and extract the parts where it says to sync a file named `.authoritative`?

Also, please add the output of `ls -lahR /var/lib/icinga2/api/zones*` from both sides.

Ensure to replace sensitive details in the output above.

Thanks.

**Comment by bahrpatrick** [comment]
Hi Michael,

here´s the output of both zones.conf:

Master1
`
/*
 * Generated by Icinga 2 node setup commands
 * on 2018-03-28 11:55:38 +0200
 */

object Endpoint NodeName {
}

object Endpoint "MASTER2" {
        host = "IP of MASTER2"
        port = "5665"
}

object Zone "master" {
        endpoints = [ "MASTER1", "MASTER2" ]
}

object Zone "global-templates" {
        global = true
}

object Zone "director-global" {
        global = true
}`

Master2
`/*
 * Generated by Icinga 2 node setup commands
 * on 2018-03-28 11:11:02 +0200
 */

object Endpoint "MASTER1" {
        host = "IP of MASTER1"
        port = "5665"
}

object Zone "master" {
        endpoints = [ "MASTER1", "MASTER2" ]
}

object Zone "global-templates" {
        global = true
}

object Zone "director-global" {
        global = true
}

object Endpoint NodeName {
}
`

I´ve changed Endpoint names and removed the IP adresses.


Output of "ls -lahR /var/lib/icinga2/api/zones*" on Master1:

/var/lib/icinga2/api/zones:
total 0
drwxr-x---. 7 icinga icinga 131 Sep 26 17:08 .
drwxr-x---. 6 icinga icinga  65 Sep 27 05:59 ..
drwx------  3 icinga icinga  80 Sep 26 17:08 director-global
drwx------  3 icinga icinga  76 Sep 26 17:08 global-templates
drwx------  3 icinga icinga  80 Sep 26 17:08 CUSTOMER1SAT
drwx------  3 icinga icinga  80 Sep 26 17:08 CUSTOMER2SAT
drwx------  3 icinga icinga  80 Sep 26 17:08 master

/var/lib/icinga2/api/zones/director-global:
total 8.0K
drwx------  3 icinga icinga   80 Sep 26 17:08 .
drwxr-x---. 7 icinga icinga  131 Sep 26 17:08 ..
-rw-r--r--  1 icinga icinga    0 Sep 26 17:08 .authoritative
-rw-r--r--  1 icinga icinga 1.2K Sep 26 17:08 .checksums
drwxr-xr-x  2 icinga icinga  334 Sep 26 17:08 director
-rw-r--r--  1 icinga icinga   17 Sep 26 17:08 .timestamp

/var/lib/icinga2/api/zones/director-global/director:
total 324K
drwxr-xr-x 2 icinga icinga  334 Sep 26 17:08 .
drwx------ 3 icinga icinga   80 Sep 26 17:08 ..
-rw-r--r-- 1 icinga icinga 1.5K Sep 26 17:08 001-director-basics.conf
-rw-r--r-- 1 icinga icinga 104K Sep 26 17:08 commands.conf
-rw-r--r-- 1 icinga icinga  752 Sep 26 17:08 command_templates.conf
-rw-r--r-- 1 icinga icinga 2.9K Sep 26 17:08 dependency_apply.conf
-rw-r--r-- 1 icinga icinga  104 Sep 26 17:08 dependency_templates.conf
-rw-r--r-- 1 icinga icinga 2.7K Sep 26 17:08 hostgroups.conf
-rw-r--r-- 1 icinga icinga 7.9K Sep 26 17:08 host_templates.conf
-rw-r--r-- 1 icinga icinga 127K Sep 26 17:08 service_apply.conf
-rw-r--r-- 1 icinga icinga 8.3K Sep 26 17:08 servicegroups.conf
-rw-r--r-- 1 icinga icinga  38K Sep 26 17:08 service_templates.conf
-rw-r--r-- 1 icinga icinga 6.8K Sep 26 17:08 timeperiods.conf
-rw-r--r-- 1 icinga icinga  192 Sep 26 17:08 user_templates.conf

/var/lib/icinga2/api/zones/global-templates:
total 8.0K
drwx------  3 icinga icinga  76 Sep 26 17:08 .
drwxr-x---. 7 icinga icinga 131 Sep 26 17:08 ..
-rw-r--r--  1 icinga icinga   0 Sep 26 17:08 .authoritative
-rw-r--r--  1 icinga icinga  94 Sep 26 17:08 .checksums
drwxr-xr-x  2 icinga icinga  31 Sep 26 17:08 _etc
-rw-r--r--  1 icinga icinga  17 Sep 26 17:08 .timestamp

/var/lib/icinga2/api/zones/global-templates/_etc:
total 8.0K
drwxr-xr-x 2 icinga icinga   31 Sep 26 17:08 .
drwx------ 3 icinga icinga   76 Sep 26 17:08 ..
-rw-r--r-- 1 icinga icinga 5.2K Sep 26 17:08 icinga2hacks.conf

/var/lib/icinga2/api/zones/CUSTOMER1SAT:
total 8.0K
drwx------  3 icinga icinga  80 Sep 26 17:08 .
drwxr-x---. 7 icinga icinga 131 Sep 26 17:08 ..
-rw-r--r--  1 icinga icinga   0 Sep 26 17:08 .authoritative
-rw-r--r--  1 icinga icinga 487 Sep 26 17:08 .checksums
drwxr-xr-x  2 icinga icinga 132 Sep 26 17:08 director
-rw-r--r--  1 icinga icinga  17 Sep 26 17:08 .timestamp

/var/lib/icinga2/api/zones/CUSTOMER1SAT/director:
total 24K
drwxr-xr-x 2 icinga icinga  132 Sep 26 17:08 .
drwx------ 3 icinga icinga   80 Sep 26 17:08 ..
-rw-r--r-- 1 icinga icinga  267 Sep 26 17:08 agent_endpoints.conf
-rw-r--r-- 1 icinga icinga  351 Sep 26 17:08 agent_zones.conf
-rw-r--r-- 1 icinga icinga 4.9K Sep 26 17:08 hosts.conf
-rw-r--r-- 1 icinga icinga  507 Sep 26 17:08 service_apply.conf
-rw-r--r-- 1 icinga icinga  293 Sep 26 17:08 service_templates.conf

/var/lib/icinga2/api/zones/CUSTOMER2SAT:
total 8.0K
drwx------  3 icinga icinga  80 Sep 26 17:08 .
drwxr-x---. 7 icinga icinga 131 Sep 26 17:08 ..
-rw-r--r--  1 icinga icinga   0 Sep 26 17:08 .authoritative
-rw-r--r--  1 icinga icinga 487 Sep 26 17:08 .checksums
drwxr-xr-x  2 icinga icinga 132 Sep 26 17:08 director
-rw-r--r--  1 icinga icinga  17 Sep 26 17:08 .timestamp

/var/lib/icinga2/api/zones/CUSTOMER2SAT/director:
total 24K
drwxr-xr-x 2 icinga icinga  132 Sep 26 17:08 .
drwx------ 3 icinga icinga   80 Sep 26 17:08 ..
-rw-r--r-- 1 icinga icinga  267 Sep 26 17:08 agent_endpoints.conf
-rw-r--r-- 1 icinga icinga  351 Sep 26 17:08 agent_zones.conf
-rw-r--r-- 1 icinga icinga 4.9K Sep 26 17:08 hosts.conf
-rw-r--r-- 1 icinga icinga  507 Sep 26 17:08 service_apply.conf
-rw-r--r-- 1 icinga icinga  293 Sep 26 17:08 service_templates.conf

/var/lib/icinga2/api/zones/master:
total 8.0K
drwx------  3 icinga icinga   80 Sep 26 17:08 .
drwxr-x---. 7 icinga icinga  131 Sep 26 17:08 ..
-rw-r--r--  1 icinga icinga    0 Sep 26 17:08 .authoritative
-rw-r--r--  1 icinga icinga 1.2K Sep 26 17:08 .checksums
drwxr-xr-x  2 icinga icinga  316 Sep 26 17:08 director
-rw-r--r--  1 icinga icinga   17 Sep 26 17:08 .timestamp

/var/lib/icinga2/api/zones/master/director:
total 220K
drwxr-xr-x 2 icinga icinga  316 Sep 26 17:08 .
drwx------ 3 icinga icinga   80 Sep 26 17:08 ..
-rw-r--r-- 1 icinga icinga 6.9K Sep 26 17:08 agent_endpoints.conf
-rw-r--r-- 1 icinga icinga 7.2K Sep 26 17:08 agent_zones.conf
-rw-r--r-- 1 icinga icinga  542 Sep 26 17:08 endpoints.conf
-rw-r--r-- 1 icinga icinga 139K Sep 26 17:08 hosts.conf
-rw-r--r-- 1 icinga icinga  29K Sep 26 17:08 notification_apply.conf
-rw-r--r-- 1 icinga icinga 1.1K Sep 26 17:08 notification_templates.conf
-rw-r--r-- 1 icinga icinga  315 Sep 26 17:08 scheduled_downtime_apply.conf
-rw-r--r-- 1 icinga icinga 2.9K Sep 26 17:08 service_apply.conf
-rw-r--r-- 1 icinga icinga 1.7K Sep 26 17:08 service_templates.conf
-rw-r--r-- 1 icinga icinga  726 Sep 26 17:08 usergroups.conf
-rw-r--r-- 1 icinga icinga 2.5K Sep 26 17:08 users.conf
-rw-r--r-- 1 icinga icinga  445 Sep 26 17:08 zones.conf

/var/lib/icinga2/api/zones-stage:
total 0
drwx------  2 icinga icinga  6 Sep 27 05:59 .
drwxr-x---. 6 icinga icinga 65 Sep 27 05:59 ..


On Master2:

/var/lib/icinga2/api/zones:
total 0
drwx------ 7 icinga icinga 131 Sep 27 05:58 .
drwx------ 6 icinga icinga  65 Sep 27 05:59 ..
drwx------ 3 icinga icinga  58 Sep 27 05:58 director-global
drwx------ 3 icinga icinga  54 Sep 27 05:58 global-templates
drwx------ 3 icinga icinga  58 Sep 27 05:58 CUSTOMER1SAT
drwx------ 3 icinga icinga  58 Sep 27 05:58 CUSTOMER2SAT
drwx------ 3 icinga icinga  58 Sep 27 05:58 master

/var/lib/icinga2/api/zones/director-global:
total 8.0K
drwx------ 3 icinga icinga   58 Sep 27 05:58 .
drwx------ 7 icinga icinga  131 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga 1.2K Sep 27 05:58 .checksums
drwx------ 2 icinga icinga  334 Sep 27 05:58 director
-rw-r--r-- 1 icinga icinga   17 Sep 27 05:58 .timestamp

/var/lib/icinga2/api/zones/director-global/director:
total 324K
drwx------ 2 icinga icinga  334 Sep 27 05:58 .
drwx------ 3 icinga icinga   58 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga 1.5K Sep 27 05:58 001-director-basics.conf
-rw-r--r-- 1 icinga icinga 104K Sep 27 05:58 commands.conf
-rw-r--r-- 1 icinga icinga  752 Sep 27 05:58 command_templates.conf
-rw-r--r-- 1 icinga icinga 2.9K Sep 27 05:58 dependency_apply.conf
-rw-r--r-- 1 icinga icinga  104 Sep 27 05:58 dependency_templates.conf
-rw-r--r-- 1 icinga icinga 2.7K Sep 27 05:58 hostgroups.conf
-rw-r--r-- 1 icinga icinga 7.9K Sep 27 05:58 host_templates.conf
-rw-r--r-- 1 icinga icinga 127K Sep 27 05:58 service_apply.conf
-rw-r--r-- 1 icinga icinga 8.3K Sep 27 05:58 servicegroups.conf
-rw-r--r-- 1 icinga icinga  38K Sep 27 05:58 service_templates.conf
-rw-r--r-- 1 icinga icinga 6.8K Sep 27 05:58 timeperiods.conf
-rw-r--r-- 1 icinga icinga  192 Sep 27 05:58 user_templates.conf

/var/lib/icinga2/api/zones/global-templates:
total 8.0K
drwx------ 3 icinga icinga  54 Sep 27 05:58 .
drwx------ 7 icinga icinga 131 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga  94 Sep 27 05:58 .checksums
drwx------ 2 icinga icinga  31 Sep 27 05:58 _etc
-rw-r--r-- 1 icinga icinga  17 Sep 27 05:58 .timestamp

/var/lib/icinga2/api/zones/global-templates/_etc:
total 8.0K
drwx------ 2 icinga icinga   31 Sep 27 05:58 .
drwx------ 3 icinga icinga   54 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga 5.2K Sep 27 05:58 icinga2hacks.conf

/var/lib/icinga2/api/zones/CUSTOMER1SAT:
total 8.0K
drwx------ 3 icinga icinga  58 Sep 27 05:58 .
drwx------ 7 icinga icinga 131 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga 487 Sep 27 05:58 .checksums
drwx------ 2 icinga icinga 132 Sep 27 05:58 director
-rw-r--r-- 1 icinga icinga  17 Sep 27 05:58 .timestamp

/var/lib/icinga2/api/zones/CUSTOMER1SAT/director:
total 24K
drwx------ 2 icinga icinga  132 Sep 27 05:58 .
drwx------ 3 icinga icinga   58 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga  267 Sep 27 05:58 agent_endpoints.conf
-rw-r--r-- 1 icinga icinga  351 Sep 27 05:58 agent_zones.conf
-rw-r--r-- 1 icinga icinga 4.9K Sep 27 05:58 hosts.conf
-rw-r--r-- 1 icinga icinga  507 Sep 27 05:58 service_apply.conf
-rw-r--r-- 1 icinga icinga  293 Sep 27 05:58 service_templates.conf

/var/lib/icinga2/api/zones/CUSTOMER2SAT:
total 8.0K
drwx------ 3 icinga icinga  58 Sep 27 05:58 .
drwx------ 7 icinga icinga 131 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga 487 Sep 27 05:58 .checksums
drwx------ 2 icinga icinga 132 Sep 27 05:58 director
-rw-r--r-- 1 icinga icinga  17 Sep 27 05:58 .timestamp

/var/lib/icinga2/api/zones/CUSTOMER2SAT/director:
total 24K
drwx------ 2 icinga icinga  132 Sep 27 05:58 .
drwx------ 3 icinga icinga   58 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga  267 Sep 27 05:58 agent_endpoints.conf
-rw-r--r-- 1 icinga icinga  351 Sep 27 05:58 agent_zones.conf
-rw-r--r-- 1 icinga icinga 4.9K Sep 27 05:58 hosts.conf
-rw-r--r-- 1 icinga icinga  507 Sep 27 05:58 service_apply.conf
-rw-r--r-- 1 icinga icinga  293 Sep 27 05:58 service_templates.conf

/var/lib/icinga2/api/zones/master:
total 8.0K
drwx------ 3 icinga icinga   58 Sep 27 05:58 .
drwx------ 7 icinga icinga  131 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga 1.2K Sep 27 05:58 .checksums
drwx------ 2 icinga icinga  316 Sep 27 05:58 director
-rw-r--r-- 1 icinga icinga   17 Sep 27 05:58 .timestamp

/var/lib/icinga2/api/zones/master/director:
total 220K
drwx------ 2 icinga icinga  316 Sep 27 05:58 .
drwx------ 3 icinga icinga   58 Sep 27 05:58 ..
-rw-r--r-- 1 icinga icinga 6.9K Sep 27 05:58 agent_endpoints.conf
-rw-r--r-- 1 icinga icinga 7.2K Sep 27 05:58 agent_zones.conf
-rw-r--r-- 1 icinga icinga  542 Sep 27 05:58 endpoints.conf
-rw-r--r-- 1 icinga icinga 139K Sep 27 05:58 hosts.conf
-rw-r--r-- 1 icinga icinga  29K Sep 27 05:58 notification_apply.conf
-rw-r--r-- 1 icinga icinga 1.1K Sep 27 05:58 notification_templates.conf
-rw-r--r-- 1 icinga icinga  315 Sep 27 05:58 scheduled_downtime_apply.conf
-rw-r--r-- 1 icinga icinga 2.9K Sep 27 05:58 service_apply.conf
-rw-r--r-- 1 icinga icinga 1.7K Sep 27 05:58 service_templates.conf
-rw-r--r-- 1 icinga icinga  726 Sep 27 05:58 usergroups.conf
-rw-r--r-- 1 icinga icinga 2.5K Sep 27 05:58 users.conf
-rw-r--r-- 1 icinga icinga  445 Sep 27 05:58 zones.conf

/var/lib/icinga2/api/zones-stage:
total 0
drwx------ 7 icinga icinga 131 Sep 27 05:59 .
drwx------ 6 icinga icinga  65 Sep 27 05:59 ..
drwx------ 3 icinga icinga  58 Sep 27 05:59 director-global
drwx------ 3 icinga icinga  54 Sep 27 05:59 global-templates
drwx------ 3 icinga icinga  58 Sep 27 05:59 LSFOR-SKYPORT-ICINGA2SAT
drwx------ 3 icinga icinga  58 Sep 27 05:59 LSPOA-SKYPORT-ICINGA2SAT
drwx------ 3 icinga icinga  58 Sep 27 05:59 master

/var/lib/icinga2/api/zones-stage/director-global:
total 8.0K
drwx------ 3 icinga icinga   58 Sep 27 05:59 .
drwx------ 7 icinga icinga  131 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga 1.2K Sep 27 05:59 .checksums
drwxr-xr-x 2 icinga icinga  334 Sep 27 05:59 director
-rw-r--r-- 1 icinga icinga   17 Sep 27 05:59 .timestamp

/var/lib/icinga2/api/zones-stage/director-global/director:
total 324K
drwxr-xr-x 2 icinga icinga  334 Sep 27 05:59 .
drwx------ 3 icinga icinga   58 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga 1.5K Sep 27 05:59 001-director-basics.conf
-rw-r--r-- 1 icinga icinga 104K Sep 27 05:59 commands.conf
-rw-r--r-- 1 icinga icinga  752 Sep 27 05:59 command_templates.conf
-rw-r--r-- 1 icinga icinga 2.9K Sep 27 05:59 dependency_apply.conf
-rw-r--r-- 1 icinga icinga  104 Sep 27 05:59 dependency_templates.conf
-rw-r--r-- 1 icinga icinga 2.7K Sep 27 05:59 hostgroups.conf
-rw-r--r-- 1 icinga icinga 7.9K Sep 27 05:59 host_templates.conf
-rw-r--r-- 1 icinga icinga 127K Sep 27 05:59 service_apply.conf
-rw-r--r-- 1 icinga icinga 8.3K Sep 27 05:59 servicegroups.conf
-rw-r--r-- 1 icinga icinga  38K Sep 27 05:59 service_templates.conf
-rw-r--r-- 1 icinga icinga 6.8K Sep 27 05:59 timeperiods.conf
-rw-r--r-- 1 icinga icinga  192 Sep 27 05:59 user_templates.conf

/var/lib/icinga2/api/zones-stage/global-templates:
total 8.0K
drwx------ 3 icinga icinga  54 Sep 27 05:59 .
drwx------ 7 icinga icinga 131 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga  94 Sep 27 05:59 .checksums
drwxr-xr-x 2 icinga icinga  31 Sep 27 05:59 _etc
-rw-r--r-- 1 icinga icinga  17 Sep 27 05:59 .timestamp

/var/lib/icinga2/api/zones-stage/global-templates/_etc:
total 8.0K
drwxr-xr-x 2 icinga icinga   31 Sep 27 05:59 .
drwx------ 3 icinga icinga   54 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga 5.2K Sep 27 05:59 icinga2hacks.conf

/var/lib/icinga2/api/zones-stage/CUSTOMER1SAT:
total 8.0K
drwx------ 3 icinga icinga  58 Sep 27 05:59 .
drwx------ 7 icinga icinga 131 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga 487 Sep 27 05:59 .checksums
drwxr-xr-x 2 icinga icinga 132 Sep 27 05:59 director
-rw-r--r-- 1 icinga icinga  17 Sep 27 05:59 .timestamp

/var/lib/icinga2/api/zones-stage/CUSTOMER1SAT/director:
total 24K
drwxr-xr-x 2 icinga icinga  132 Sep 27 05:59 .
drwx------ 3 icinga icinga   58 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga  267 Sep 27 05:59 agent_endpoints.conf
-rw-r--r-- 1 icinga icinga  351 Sep 27 05:59 agent_zones.conf
-rw-r--r-- 1 icinga icinga 4.9K Sep 27 05:59 hosts.conf
-rw-r--r-- 1 icinga icinga  507 Sep 27 05:59 service_apply.conf
-rw-r--r-- 1 icinga icinga  293 Sep 27 05:59 service_templates.conf

/var/lib/icinga2/api/zones-stage/CUSTOMER2SAT:
total 8.0K
drwx------ 3 icinga icinga  58 Sep 27 05:59 .
drwx------ 7 icinga icinga 131 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga 487 Sep 27 05:59 .checksums
drwxr-xr-x 2 icinga icinga 132 Sep 27 05:59 director
-rw-r--r-- 1 icinga icinga  17 Sep 27 05:59 .timestamp

/var/lib/icinga2/api/zones-stage/CUSTOMER2SAT/director:
total 24K
drwxr-xr-x 2 icinga icinga  132 Sep 27 05:59 .
drwx------ 3 icinga icinga   58 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga  267 Sep 27 05:59 agent_endpoints.conf
-rw-r--r-- 1 icinga icinga  351 Sep 27 05:59 agent_zones.conf
-rw-r--r-- 1 icinga icinga 4.9K Sep 27 05:59 hosts.conf
-rw-r--r-- 1 icinga icinga  507 Sep 27 05:59 service_apply.conf
-rw-r--r-- 1 icinga icinga  293 Sep 27 05:59 service_templates.conf

/var/lib/icinga2/api/zones-stage/master:
total 8.0K
drwx------ 3 icinga icinga   58 Sep 27 05:59 .
drwx------ 7 icinga icinga  131 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga 1.2K Sep 27 05:59 .checksums
drwxr-xr-x 2 icinga icinga  316 Sep 27 05:59 director
-rw-r--r-- 1 icinga icinga   17 Sep 27 05:59 .timestamp

/var/lib/icinga2/api/zones-stage/master/director:
total 220K
drwxr-xr-x 2 icinga icinga  316 Sep 27 05:59 .
drwx------ 3 icinga icinga   58 Sep 27 05:59 ..
-rw-r--r-- 1 icinga icinga 6.9K Sep 27 05:59 agent_endpoints.conf
-rw-r--r-- 1 icinga icinga 7.2K Sep 27 05:59 agent_zones.conf
-rw-r--r-- 1 icinga icinga  542 Sep 27 05:59 endpoints.conf
-rw-r--r-- 1 icinga icinga 139K Sep 27 05:59 hosts.conf
-rw-r--r-- 1 icinga icinga  29K Sep 27 05:59 notification_apply.conf
-rw-r--r-- 1 icinga icinga 1.1K Sep 27 05:59 notification_templates.conf
-rw-r--r-- 1 icinga icinga  315 Sep 27 05:59 scheduled_downtime_apply.conf
-rw-r--r-- 1 icinga icinga 2.9K Sep 27 05:59 service_apply.conf
-rw-r--r-- 1 icinga icinga 1.7K Sep 27 05:59 service_templates.conf
-rw-r--r-- 1 icinga icinga  726 Sep 27 05:59 usergroups.conf
-rw-r--r-- 1 icinga icinga 2.5K Sep 27 05:59 users.conf
-rw-r--r-- 1 icinga icinga  445 Sep 27 05:59 zones.conf

It seems like the files located in /etc/icinga2/zones.d/global-templates disrupt the start of the icinga2 agent on the passive master. We´ve removed the config directory now the agent can start, but we have still a problem with syncing all the zones especcially the customer satellite zones.
Right after the startup Icingaweb2 chooses the passive node as active endpoint and so the shown data is not correct.

Thanks for your support!

**Comment by bahrpatrick** [comment]
In the logfile of the MASTER2 i found the following message:

`[2019-09-27 05:54:44 +0200] warning/ApiListener: Ignoring config update from endpoint 'IPSNBG6SRV01' for unknown zone 'CUSTOMER1SAT'.
[2019-09-27 05:54:44 +0200] warning/ApiListener: Ignoring config update from endpoint 'IPSNBG6SRV01' for unknown zone 'CUSTOMER2SAT'. `

The zones config files are present in the /var/lib/icinga2/api/zones/ and /var/lib/icinga2/api/zones-stage/ diretories.

Thanks for your support!

**Comment by dnsmichi** [comment]
Ok, thanks for the all the details. I can see where you are coming from, it is the same problem as with https://github.com/Icinga/icinga2/issues/7533#issuecomment-535559611

I'll summarize this for this issue as well:

- The cluster config sync is designed in the way that you put configuration files into zones.d/<zonename> (either in etc, or via the Director cluster zone setting).
- The required Zone object which tells Icinga to automatically include this directory, needs to be configured outside of zones.d. The documentation recommends to put everything into zones.conf for example. The CLI node wizard/setup also suggest to do that.
  - That being said, the master-satellite zone hierarchy must be defined in zones.conf in order to sync both, the master zones.d content and the satellite zones.d content to endpoints in the same zone (master2) as well as the child zone (satellite*).
  - Your configuration doesn't show that, instead you are managing this from inside the Director

Versions til 2.11 silently included everything, which caused problems with renamed zones and other things. This has been fixed by only syncing zones where a Zone object already exists. Outside in zones.conf is the safe place.

In order to fix your configuration, follow along with the instructions in https://github.com/Icinga/icinga2/issues/7533#issuecomment-535559611 and keep the Zone configuration for master and satellite objects outside of the Director. Just import the externally defined zones via kickstart then again.

More details: 

https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#config-sync-zones-in-zones
https://icinga.com/docs/icinga2/latest/doc/15-troubleshooting/#zones-in-zones-doesnt-work

**Comment by bahrpatrick** [comment]
Hi @dnsmichi 

this worked for us.
We removed the zones configuration from the icinga2director and created the entries in the local zones.conf on both master nodes.

Thanks for your very helpful support and have a nice weekend!

**Comment by sharkyzz** [comment]
> Hi @dnsmichi
> 
> this worked for us.
> We removed the zones configuration from the icinga2director and created the entries in the local zones.conf on both master nodes.
> 
> Thanks for your very helpful support and have a nice weekend!

hi @bahrpatrick 

I'm wondering: did you encounter any issues while removing the zones in director ? When I try to remove a zone in director:

![image](https://user-images.githubusercontent.com/1429655/65768659-da158000-e131-11e9-9675-38a8a021be32.png)

The only way to fix this is that I have to move all my endpoints to the master zone before I can remove it. Then I can remove it and do the import with Kickstart. After that I have to place all the endpoints in the associated zone. Can you confirm @dnsmichi this is the way to go for us ? Requires a bit of preparation on our production platform..

**Comment by ocstaron** [comment]
Hello @sharkyzz,

yes, we also had to modify all objects to use the master zone and afterwards back to their zones. Thank god - we had only 8 objects to modify. :-)

Kind regards,
Oliver (collegue of bahrpatrick)

**Comment by sharkyzz** [comment]
Thanks a lot @ocstaron for your confirmation! Well, unfortunately our setup is much bigger. I'm preparing now to do so using the Director API. Or maybe @dnsmichi knows a better trick :)

**Comment by R-Sommer** [comment]
I'm struggling with same stuff and my idea would be a simple change of object_type in table icinga_zone of the director database from object to external_object as this is the only difference I've been identifying yet. Of course, I'd try this first in my test environment. But I'd love to hear a go or no-go from @dnsmichi or @Thomas-Gelf.

**Comment by Thomas-Gelf** [comment]
@R-Sommer: you could do so, yes. Works for Icinga Director as follows:

* backup your database, just to be on the safe side
* create all non-external Zone/Endpoint-Objects on all related Icinga Master/Satellite-Nodes (manually in your local zones.conf)
* while doing so please do NOT restart Icinga, no deployments
* change the type in the Director DB:

```sql
UPDATE icinga_zone SET object_type = 'external_object' WHERE object_type = 'object';
UPDATE icinga_endpoint SET object_type = 'external_object' WHERE object_type = 'object';
```

* render and deploy a new configuration in the Director. It will state that there are no changes. Ignore it, deploy anyways

That's it. All nodes should automatically restart, triggered by the deployed configuration via cluster protocol. Please note that I'll unfortunately be offline for the next 48 hours, so you're on your own in case it doesn't work out as expected.

Alternatively you could stick with the latest 2.10.x and wait with 2.11.x unless this issue has been fixed. That's what I would do. Your configuration isn't wrong, it just fails on 2.11.0. Sure, Director always advised against creating Zones and Endpoints, unless "you know what you're doing". Those who knew have been bitten, we're sorry for that. But still, it should work, this is a bug. We're already working on it, it will be fixed.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
Two more hints:

* in case you opt for the configuration change, there should be no need to manually touch `/var/lib/something` on any node. That's important, because wiping that data could mean loosing state like downtimes, comments or similar.

* if you opt for the downgrade please better do so with all your nodes. I don't know whether and how #7544 might affect a setup, but the pull request suggests that mixing those versions is not a good idea right now.

**Comment by R-Sommer** [comment]
@Thomas-Gelf: I had some discussions (in the icinga community and with NETWAYS consultants) with similar results e.g. misunderstandings and confusing about my "mixed" setup (endpoints and zones configured partially in conf files and director). Therefore, I decided to "repair" my setup by following your described steps here and could successful apply them in my test environment and at one of our customer. Thank you so much!
