### ISSUE TITLE
icinga2-bin dependency error on Debian Stretch

### ISSUE THREAD

**Issue by thehunmonkgroup** [Icinga/icinga2#7550]
## Describe the bug

When trying to install the ```icinga2-bin``` package for Debian Stretch from the Icinga Debian repository, errors occur because of ```libboost-*``` dependency mismatches:

## To Reproduce

```
[roott] # aptitude install icinga2-bin
The following NEW packages will be installed:
  icinga2-bin{b} icinga2-common{a} 
0 packages upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,300 kB of archives. After unpacking 16.4 MB will be used.
The following packages have unmet dependencies:
 icinga2-bin : Depends: libboost-context1.67.0 which is a virtual package and is not provided by any available package

               Depends: libboost-coroutine1.67.0 which is a virtual package and is not provided by any available package

               Depends: libboost-date-time1.67.0 which is a virtual package and is not provided by any available package

               Depends: libboost-filesystem1.67.0 which is a virtual package and is not provided by any available package

               Depends: libboost-program-options1.67.0 which is a virtual package and is not provided by any available package

               Depends: libboost-regex1.67.0 which is a virtual package and is not provided by any available package

               Depends: libboost-system1.67.0 which is a virtual package and is not provided by any available package

               Depends: libboost-thread1.67.0 which is a virtual package and is not provided by any available package
```

## Expected behavior

The package should install successfully.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Operating System and version:
```
[roott] # lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
```
* Repository config:
```
[root] # cat /etc/apt/sources.list.d/icinga.list 
deb http://packages.icinga.com/debian icinga-stretch main
```

## Additional context

Upstream package shows older ```libboost-*``` packages: https://packages.debian.org/stretch/icinga2-bin

So guessing this is a packaging issue in the Icinga repository.

I *could* install newer ```libboost-*``` packages from ```stretch-backports```, but guessing y'all would rather fix this in the packaging?

**Comment by mcktr** [comment]
On Debian stretch you need to add the `stretch-backports` repository, this is intended since 2.11 raises the required Boost version to a newer on (>= 1.66). 

More details in the documentation:

* https://icinga.com/docs/icinga2/latest/doc/02-installation/#debianubunturaspbian-repositories
* https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#upgrading-to-v211
