### ISSUE TITLE
2.11 - Debian 10: Systemd seems to kill the unit if error in the configuration during reload

### ISSUE THREAD

**Issue by Lebvanih** [Icinga/icinga2#7553]
## Describe the bug
We have upgraded some of our instance from a quite "old" version to the 2.11, and since then we noticed that if there is any error in the configuration, the unit will enter a failed state instead of logging the issue and keeping the process alive. I checked around a bit, and didn't see anything mentioning a behavior change for this..

As we have upgraded the OS and Icinga2 at the same time we are quite unsure if this is coming from the upgrade of Icinga2 or from the OS (Systemd version)...

We tried a reload with a configuration error in a Debian 8 + Icinga 2.8.4 setup, and this is the output from systemd (Icinga2 wasn't killed):

> Oct 02 12:28:02 tool-3 systemd[1]: icinga2.service: control process exited, code=exited status=1
> Oct 02 12:28:02 tool-3  systemd[1]: Reload failed for Icinga host/service/network monitoring system.

On a debian 10 with Icinga 2.11 we are getting one extra line (Icinga was killed):
> Oct 02 10:07:51 monitoring systemd[1]: icinga2.service: Control process exited, code=exited, status=1/FAILURE
> Oct 02 10:08:12 monitoring systemd[1]: icinga2.service: Failed with result 'exit-code'.
> Oct 02 10:08:12 monitoring systemd[1]: Reload failed for Icinga host/service/network monitoring system.

In both case the error was the same in the configuration (just added "test" at the start of the icinga2.conf file.

I am also having this behavior on a fresh instance running Debian 10 + Icinga2 2.11 (the only configuration is the zone configuration).
Running manually (outside of systemd) the safe-reload command doesn't kill icinga2, only display the configuration error..

## To Reproduce
I haven't tried the full process as I already had some configuration on my "fresh install", but this should allow to reproduce the issue.
1. Install a fresh Debian 10
2. Install Icinga2 2.11 from official repo and make sure it's running.
3. Add an error in the configuration
4. Reload the service via systemd
Icinga2 will be killed after the reload.

## Expected behavior

We expect the process to not be killed on a configuration error if the reload command is used..

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.11.0-1
* Operating System and version: Debian 10.1
* Enabled features (`icinga2 feature list`):
Enabled features: api checker command ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About): Not Applicable
* Config validation (`icinga2 daemon -C`): Not really applicable as the issue is when there is an issue on validation.

**Comment by dnsmichi** [comment]
Can you please share the systemd service configuration file?

**Comment by Lebvanih** [comment]
Hello,
There you go:

> # cat /lib/systemd/system/icinga2.service
> [Unit]
> Description=Icinga host/service/network monitoring system
> Requires=network-online.target
> After=syslog.target network-online.target postgresql.service mariadb.service carbon-cache.service carbon-relay.service
> 
> [Service]
> Type=notify
> Environment="ICINGA2_ERROR_LOG=/var/log/icinga2/error.log"
> EnvironmentFile=/etc/default/icinga2
> ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/default/icinga2
> ExecStart=/usr/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG}
> PIDFile=/run/icinga2/icinga2.pid
> ExecReload=/usr/lib/icinga2/safe-reload /etc/default/icinga2
> TimeoutStartSec=30m
> KillMode=mixed
> 
> # Systemd >228 enforces a lower process number for services.
> # Depending on the distribution and Systemd version, this must
> # be explicitly raised. Packages will set the needed values
> # into /etc/systemd/system/icinga2.service.d/limits.conf
> #
> # Please check the troubleshooting documentation for further details.
> # The values below can be used as examples for customized service files.
> 
> #TasksMax=infinity
> #LimitNPROC=62883
> 
> [Install]
> WantedBy=multi-user.target
>

**Comment by JB1985** [comment]
same here:

`icinga2-common (2.11.0-2.stretch) wird eingerichtet ...
Job for icinga2.service failed because the control process exited with error code.
See "systemctl status icinga2.service" and "journalctl -xe" for details.
invoke-rc.d: initscript icinga2, action "start" failed.
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/icinga2.service.d
           └─limits.conf
   Active: failed (Result: exit-code) since Tue 2019-10-08 09:55:11 CEST; 7ms ago
  Process: 16420 ExecStart=/usr/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG} (code=exited, status=203/EXEC)
  Process: 16410 ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/default/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 16420 (code=exited, status=203/EXEC)

Okt 08 09:55:11 server3.jaba.hosting systemd[1]: Starting Icinga host/service/network monitoring system...
Okt 08 09:55:11 server3.jaba.hosting systemd[1]: icinga2.service: Main process exited, code=exited, status=203/EXEC
Okt 08 09:55:11 server3.jaba.hosting systemd[1]: Failed to start Icinga host/service/network monitoring system.
Okt 08 09:55:11 server3.jaba.hosting systemd[1]: icinga2.service: Unit entered failed state.
Okt 08 09:55:11 server3.jaba.hosting systemd[1]: icinga2.service: Failed with result 'exit-code'.
dpkg: Fehler beim Bearbeiten des Paketes icinga2-common (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zurück
`

**Comment by mattrose** [comment]
Seeing the same thing here with Ubuntu 18.04 and the Icinga 2 (version: r2.11.0-1) installed from the Icinga packages repository.  I've started collecting information.

I have the debug log, and it seems to just ... stop in the middle of running a postgresql update (debug/IdoPgsqlConnection) and doesn't even end the line, which suggests to me that it was killed quite harshly (with SIGKILL).  It contains sensitive information, so I won't attach it here, but suffice to say that everything looked entirely normal up until it stops.

The systemd log (journalctl -xe) just says this:

```
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Main process exited, code=exited, status=134/n/a
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4780 (check_ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4781 (ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4782 (check_ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4783 (check_ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4785 (check_ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4786 (ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4787 (check_dig) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4788 (check_ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4789 (ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4790 (ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4791 (dig) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Killing process 4792 (ping) with signal SIGKILL.
Oct 09 12:43:17 icinga-master systemd[1]: icinga2.service: Failed with result 'exit-code'.
```

**Comment by mattrose** [comment]
```
root@icinga-master.servers.fr:~# icinga2 feature list
Disabled features: command compatlog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker debuglog ido-pgsql mainlog notification
```

**Comment by dnsmichi** [comment]
@JB1985 I don't think that yours is related to here, the package installation just fails in your log. Since you've mentioned Debian 9 Stretch, there may be some dependencies missing to fully install icinga2-common (Backports repo).

@mattrose What happens if you run `icinga2 daemon` in foreground and sending a HUP signal? To me, it seems that some checks are running too long, and after the reload timeout is hit, a hard kill is enforced.

Also, please add the output of `icinga2 daemon -C` and add some hardware numbers to get a better idea about your system.

**Comment by Lebvanih** [comment]
Hello,

Below the following requested information. I removed from the first output all the warning from Apply rules not matching (as they do no match anything on that instance, but are pushed from the global zone by the master).
The output below is when there is no error in the configuration:
```
root@sa-east-1-icinga-01:~# icinga2 daemon -C
[2019-10-11 06:53:35 +0000] information/cli: Icinga application loader (version: r2.11.0-1)
[2019-10-11 06:53:35 +0000] information/cli: Loading configuration file(s).
[2019-10-11 06:53:35 +0000] information/ConfigItem: Committing config item(s).
[2019-10-11 06:53:35 +0000] information/ApiListener: My API identity: sa-east-1-icinga-01
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 1 FileLogger.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 2 NotificationCommands.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 6 Notifications.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 20 HostGroups.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 2 Hosts.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 4 Zones.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 6 Endpoints.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 1 ApiUser.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 4 UserGroups.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 259 CheckCommands.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 1 TimePeriod.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 4 Users.
[2019-10-11 06:53:35 +0000] information/ConfigItem: Instantiated 4 Services.
[2019-10-11 06:53:35 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-10-11 06:53:35 +0000] information/cli: Finished validating the configuration file(s).
```
The next one is when I add on purpose the error:
```
root@sa-east-1-icinga-01:~# icinga2 daemon -C
[2019-10-11 06:54:07 +0000] information/cli: Icinga application loader (version: r2.11.0-1)
[2019-10-11 06:54:07 +0000] information/cli: Loading configuration file(s).
[2019-10-11 06:54:07 +0000] critical/config: Error: Value computed is not used.
Location: in /etc/icinga2/icinga2.conf: 10:1-10:4
/etc/icinga2/icinga2.conf(8):  */
/etc/icinga2/icinga2.conf(9): 
/etc/icinga2/icinga2.conf(10): test
                               ^^^^
/etc/icinga2/icinga2.conf(11): /**
/etc/icinga2/icinga2.conf(12):  * The constants.conf defines global constants.

[2019-10-11 06:54:07 +0000] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
```
And the last one is the result of safe reload + exit code (the safe-reload alone doesn't kill the instance, only if called via the unit..):
```
root@sa-east-1-icinga-01:~# /usr/lib/icinga2/safe-reload
Validating config files: Failed
[2019-10-11 06:55:34 +0000] information/cli: Icinga application loader (version: r2.11.0-1)
[2019-10-11 06:55:34 +0000] information/cli: Loading configuration file(s).
[2019-10-11 06:55:34 +0000] critical/config: Error: Value computed is not used.
Location: in /etc/icinga2/icinga2.conf: 10:1-10:4
/etc/icinga2/icinga2.conf(8):  */
/etc/icinga2/icinga2.conf(9): 
/etc/icinga2/icinga2.conf(10): test
                               ^^^^
/etc/icinga2/icinga2.conf(11): /**
/etc/icinga2/icinga2.conf(12):  * The constants.conf defines global constants.

[2019-10-11 06:55:34 +0000] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
root@sa-east-1-icinga-01:~# echo $?
1
```
All the instance on which I tested are in a distributed monitoring setup. I had this issue on the master but also on the satellite.
Bellow the zones.conf file of the satellite:
```
object Endpoint "icinga-master-1" {
  host = "10.251.3.52"
}

object Endpoint "icinga-master-2" {
  host = "10.251.3.53"
}

object Zone "an-ha-master" {
  endpoints = [ "icinga-master-1", "icinga-master-2" ]
}

object Zone "global-templates" {
        global = true
}

object Endpoint "an-rd-icinga-01" {
  host = "10.252.0.28"
}

object Endpoint "an-rd-icinga-02" {
  host = "10.252.4.28"
}

object Zone "an-rd-ha-master" {
  parent = "an-ha-master"
  endpoints = [ "an-rd-icinga-01","an-rd-icinga-02" ]
}

object Endpoint "sa-east-1-icinga-01" {
  host = "10.253.8.8"
}

object Endpoint "sa-east-1-icinga-02" {
  host = "10.253.8.9"
}

object Zone "sa-east-1-ha-satellite" {
  parent = "an-rd-ha-master"
  endpoints = [ "sa-east-1-icinga-01","sa-east-1-icinga-02" ]
}
```
Regarding the hardware:
On the instance on which I did the test above:
2 vCPU, 1.9G of Ram (System show 100Mi used only).

If you need more informations please let me know.

Kr,

**Comment by cite** [comment]
We are suffering from the same problem as initially described - on CentOS 8, when the `safe-reload` script exits with a failure code, `systemd` seems to think that something went critically wrong and instead restarts the service.

We had some faulty code deployed by Puppet (my fault):

```
2020-01-15 15:33:18 +0100 /Stage[main]/Icinga2::Client/File[/etc/icinga2/global-configuration.d/services/active/hypervisor.conf]/content (notice): content changed '{md5}5c527439ee2d2aa236b23f36c1eda545' to '{md5}b639459b18c46bf40db1b0c3cbdcbbfc'
2020-01-15 15:33:20 +0100 /Stage[main]/Icinga2/Exec[icinga2-reload]/returns (notice): Redirecting to /bin/systemctl reload icinga2.service
2020-01-15 15:33:20 +0100 /Stage[main]/Icinga2/Exec[icinga2-reload]/returns (notice): Job for icinga2.service failed because the control process exited with error code.
2020-01-15 15:33:20 +0100 /Stage[main]/Icinga2/Exec[icinga2-reload]/returns (notice): See "systemctl status icinga2.service" and "journalctl -xe" for details.
2020-01-15 15:33:20 +0100 /Stage[main]/Icinga2/Exec[icinga2-reload] (err): Failed to call refresh: 'service icinga2 reload' returned 1 instead of one of [0]
2020-01-15 15:33:20 +0100 /Stage[main]/Icinga2/Exec[icinga2-reload] (err): 'service icinga2 reload' returned 1 instead of one of [0]
2020-01-15 15:33:21 +0100 Puppet (notice): Applied catalog in 14.14 seconds
```

The `safe-reload` script is triggered from the service's unit file (using unmodified RPMs provided by the project):

```
ExecReload=/usr/lib/icinga2/safe-reload /etc/sysconfig/icinga2
```

However, a failure of this script just makes `systemd`  reload the service:

```
Jan 15 15:33:18 fra1pro-infra-2 systemd[1]: Reloading Icinga host/service/network monitoring system.
Jan 15 15:33:19 fra1pro-infra-2 safe-reload[24676]: Validating config files: Failed
[...]
Jan 15 15:33:19 fra1pro-infra-2 safe-reload[24676]: [2020-01-15 15:33:19 +0100] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' [...]

Jan 15 15:33:19 fra1pro-infra-2 systemd[1]: icinga2.service: Control process exited, code=exited status=1
Jan 15 15:33:20 fra1pro-infra-2 systemd[1]: icinga2.service: Killing process 11364 (icinga2) with signal SIGKILL.
Jan 15 15:33:20 fra1pro-infra-2 systemd[1]: icinga2.service: Failed with result 'exit-code'.
Jan 15 15:33:20 fra1pro-infra-2 systemd[1]: Reload failed for Icinga host/service/network monitoring system.
```

Involved versions:

```
[root@fra1pro-infra-2 ~]# systemctl --version
systemd 239
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy
[root@fra1pro-infra-2 ~]# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.2-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 8 (Core)
  Kernel: Linux
  Kernel version: 4.18.0-80.11.2.el8_0.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.2.1
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
