### ISSUE TITLE
Remove releted downtimes when deleting a scheduled downtime object

### ISSUE THREAD

**Issue by wp-perc** [Icinga/icinga2#7555]
## Describe the bug

I created a Scheduled Downtime, deployed, removed it and deployed again.
The Downtime created by this rule is still there.

## Expected behavior

When deleting or editing a Scheduled downtime rule the corresponding Downtime object should be removed or updated.

## Your Environment
* Version used (`icinga2 --version`): **r2.10.5-1**
* Operating System and version: CentOS 7

**Comment by Clasko** [comment]
Version 2.11 does that.

**Comment by dnsmichi** [comment]
Thanks for the heads up 👍
