### ISSUE TITLE
check_dns: -q flag does not exist

### ISSUE THREAD

**Issue by vlcty** [Icinga/icinga2#7556]
## Describe the bug

According to the [Icinga Template Library for check_dns](https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#dns) the option `dns_query_type` exists. You link to the [man pages for check_dns](https://www.monitoring-plugins.org/doc/man/check_dns.html) but the -q option is not present there.

I've found out that the version from monitoring-plugins does not support that flag. The version in [nagios-plugins](https://nagios-plugins.org/doc/man/check_dns.html) supports it.   
A similar bug report can be found here #5383.

I've no idea which vendor Icinga2 wants to prefer. My personal opinion is to stick with monitoring-plugins and to remove the option "dns_query_type" from the config and documentation.

## Your Environment

* Version used (`icinga2 --version`): r2.11.0-1
* Operating System and version: Debian 10.1

**Comment by dnsmichi** [comment]
It is an optional flag which unfortunately hasn't been ported to the monitoring plugins project. You might want to create a PR for them in order to include this feature. The only thing we can do is to update the documentation for this specific command parameter. Would that be sufficient?

**Comment by vlcty** [comment]
Updating the documentation sounds okay to me.
