### ISSUE TITLE
Make directory path constants read-write

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7557]
... so I can set [them](https://icinga.com/docs/icinga2/latest/doc/17-language-reference/#directory-path-constants) and don't have to re-build Icinga 2.

**Comment by dnsmichi** [comment]
You can set them via `-D` on the CLI. It is intended that users don't modify these constants inside the configuration, leading to unwanted behaviour.

**Comment by Al2Klimov** [comment]
1. "unwanted" by the user or us?
2. That kind of protection is pretty useless (and should not exist) as the user can edit the systemd unit file and add `-D...`.

**Comment by Al2Klimov** [comment]
And by the way: If *we* don't want the user to set those in the config, we should ask ourselves what is more important for us – users not setting those in the config or users not building Icinga 2 by themselves.

**Comment by Al2Klimov** [comment]
The `-D...` trick seems to work, but not for `StatePath`. Any idea why?

**Comment by dnsmichi** [comment]
We generally don't support setups where users have modified the installation paths. Only package builds with standard paths are supported. That is why the way to reach such "modifications" is neither fully documented nor made easy. Recompiling Icinga isn't necessary though with the `-D...` overrides.
If users want to go the route with modifying their setup e.g. in a systemd service file, it is up to them. We won't look into such customized setups during support in our channels finding out whether there's a bug or not, this really is time consuming with analysing permissions and paths prior to the real problem.

That being said, the initial request is something I'd close as wont-fix. 

In terms of StatePath, can be a bug in the implementation. Each extra path constant needs several override handlings in various places, being really cumbersome to carry around. I'm really not a friend of these additional path constants compared to the old SysconfDir constants.
