### ISSUE TITLE
Allow to pass --dist-upgrade w/o value to check_apt

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7558]
## Is your feature request related to a problem? Please describe.

I'd like to pass `--dist-upgrade`, but w/o any argument (just as flag) to check\_apt. [Our CheckCommand](https://github.com/Icinga/icinga2/blob/43f7d35a456f0693d71e950b748a243aa5dabeb4/itl/command-plugins.conf#L1917) seems not to allow that.

## Describe the solution you'd like

If `CheckCommand#arguments.x.value` resolves to null, skip the value.

**Comment by julianbrost** [comment]
Works with #9447 now.
