### ISSUE TITLE
Feature request : tags in config file of opentsdbwriter

### ISSUE THREAD

**Issue by handfreezer** [Icinga/icinga2#7559]
Hi,

   I would like to know if it is possible to set specific tag in opentsdb writer.
   Example : say that I have a host with a specific var named city and the value TheCity . in the configuration file of opentsdb writer, I added a line like " tag_city = host.vars.city".
   The goal is to get a tag in opentsdb with key name city and key value TheCity which will be usable as filter in grafana.

Best regards,

**Comment by dnsmichi** [comment]
Hi,

the OpenTSDB feature was contributed by community members, so our knowledge about the storage backend and structure is very limited. If you find a specific structure where these tags could fit, feel free to create a PR. The InfluxDB feature has similar parts with the configuration settings and then resolving the macros and adding this to the dumped metrics.

The last time I looked into the OpenTSDB feature code, I had seen that the implementation still uses the old telnet method and OpenTSDB suggests to use their REST API instead. So maybe this feature needs a general rewrite as well. That's unfortunately nothing we will do ourselves, so we rely on community patches and contributions here.

With 2.11, the development chapter in the documentation provides quite a few more details for your own development environment, making such a contribution happen more easily. Another thing would be asking for a quote via the website for sponsoring this feature.

Cheers,
Michael

**Comment by dnsmichi** [comment]
As far I have seen, this is implemented with #7357
