### ISSUE TITLE
Config sync checksum change detection may not work within high load clusters

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#7565]
## Describe the bug

Given that two masters sync their configuration with a slight delay both to the satellites below, the new checksum algorithm might cause ongoing reloads with always `configChange=true`.

## To Reproduce

1. 2 masters, 1 satellite
2. Huge configuration & a overloaded JSON-RPC message queue between the masters (force a delayed config sync to the satellite)
3. Config master pushes the new configuration to the satellite, reloads
4. Secondary master with the old configuration syncs that to the satellite, this instance reloads
5. Config master again syncs, different config checksum, reloads.

## Expected behavior

Use an ongoing number next to the checksum comparison to identify the version.

## Tasks

- [x] Evaluate whether 2.11.0 still sends the timestamp. If not, re-introduce this for 2.12 instead of 2.11.2
- [ ] Whenever checksums are in place, also read the timestamp flag for the config and compare it to the current version. If the timestamp is equal or older, do not reload. This avoids the sync step from the secondary master in 4.

## Your Environment

* Version used (`icinga2 --version`): 2.11.0

## Additional context

#6716 added the checksums next to the stages.

**Comment by htriem** [comment]
I've evaluated the described scenario using version 2.11.0, and I can confirm the timestamp is still being sent.

**Comment by dnsmichi** [comment]
I've implemented and tested a PR based on these findings.
