### ISSUE TITLE
probably vulnerable: icinga searches PDBs in user writeable paths

### ISSUE THREAD

**Issue by ggzengel** [Icinga/icinga2#7573]
Icinga2 searches for PDBs on drive D while starting.
If drive D is a FAT filesystem like an USB stick user can create special PDBs.
I don't know if it's possible to put code inside a PDB but you shouldn't read PDBs from fixed paths.

```
15:37:45,1669605	icinga2.exe	12548	CreateFile	D:\CFILES\Projects\WinSSL\openssl-1.1.1c\libssl-1_1-x64.pdb	PATH NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Random Access, Attributes: N, ShareMode: Read, Delete, AllocationSize: n/a
15:37:45,1677861	icinga2.exe	12548	CreateFile	D:\CFILES\Projects\WinSSL\openssl-1.1.1c\libcrypto-1_1-x64.pdb	PATH NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Random Access, Attributes: N, ShareMode: Read, Delete, AllocationSize: n/a
15:37:45,2014426	icinga2.exe	12548	CreateFile	D:\agent\_work\2\s\binaries\amd64ret\bin\amd64\vcruntime140.amd64.pdb	PATH NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Random Access, Attributes: N, ShareMode: Read, Delete, AllocationSize: n/a
```

If I put a file there it will be read:
```
15:58:06,6592591	icinga2.exe	11564	CreateFile	D:\agent\_work\2\s\binaries\amd64ret\bin\amd64\vcruntime140.amd64.pdb	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Random Access, Attributes: N, ShareMode: Read, Delete, AllocationSize: n/a, OpenResult: Opened
15:58:06,6593034	icinga2.exe	11564	CreateFileMapping	D:\agent\_work\2\s\binaries\amd64ret\bin\amd64\vcruntime140.amd64.pdb	FILE LOCKED WITH ONLY READERS	SyncType: SyncTypeCreateSection, PageProtection: 
15:58:06,6593174	icinga2.exe	11564	QueryStandardInformationFile	D:\agent\_work\2\s\binaries\amd64ret\bin\amd64\vcruntime140.amd64.pdb	SUCCESS	AllocationSize: 8, EndOfFile: 4, NumberOfLinks: 1, DeletePending: False, Directory: False
15:58:06,6593374	icinga2.exe	11564	CreateFileMapping	D:\agent\_work\2\s\binaries\amd64ret\bin\amd64\vcruntime140.amd64.pdb	SUCCESS	SyncType: SyncTypeOther
15:58:06,6593634	icinga2.exe	11564	ReadFile	D:\agent\_work\2\s\binaries\amd64ret\bin\amd64\vcruntime140.amd64.pdb	SUCCESS	Offset: 0, Length: 4, Priority: Normal
15:58:06,6593926	icinga2.exe	11564	CloseFile	D:\agent\_work\2\s\binaries\amd64ret\bin\amd64\vcruntime140.amd64.pdb	SUCCESS	
```

**Comment by dnsmichi** [comment]
I'm not sure where this is coming from, but Icinga 2 is definitely not loading debug symbols on its own. It seems that Windows tries to load PDB files whenever the application crashes, in order to allow to attach against Visual Studio or WinDbg. 

Since Microsoft doesn't share details about the PDB format itself, I don't think that one could reasonably abuse this for injecting malware. The crash on its own is a problem which should be fixed, but that's part of a different issue in #7568. 

Likely you have [enabled WER reports](https://icinga.com/docs/icinga2/latest/doc/21-development/#debug-on-windows) on your agent which now does that sort of lookup on a crash. This action must be performed by an administrator, and is disabled by default, so no immediate attack vector.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/4c8bb2d8-2629-4ab0-8383-0bf1cafcea9d/debug-using-windows-crash-report?forum=vsdebug
https://www.wintellect.com/pdb-files-what-every-developer-must-know/

TL;DR - I don't see a problem with this during normal operations where these lookups don't happen.

Cheers,
Michael

**Comment by ggzengel** [comment]
I checked this with an production system with version 2.11.0.
I just stopped and started the service and monitored with procmon.
icinga2.exe is runnig as "NT AUTHORITY\SYSTEM".
I have the problem that PDBs are not well documented and that's the reason to declare them as harmful.

**Comment by dnsmichi** [comment]
PDBs contain debug symbols extracted from the binaries, and allow developers to actually see the function name during a stacktrace when run in a debugger. They don't expose a security risk imho with just providing additional binary details for developers.

If you want to access the memory and values from a running service, and it crashes, you really need a full core dump.

https://stackoverflow.com/questions/933883/are-there-any-security-issues-leaving-the-pdb-debug-files-on-the-live-servers
https://stackoverflow.com/questions/608002/do-you-have-to-deploy-the-pdb-file-with-compiling-under-release

I would expect any other Windows binary running to also load certain PDB files and trying to read them in case of failure with writing a stacktrace. That's similar with Linux/Unix where you also have the possibility to add debug symbols.

If you need the icinga2 generated symbols, you can download them from http://packages.icinga.com/windows/ for example, the -symbols.zip file. This helps with debugging crashes directly on the Windows host, e.g. with WinDbg. 

> I have the problem that PDBs are not well documented and that's the reason to declare them as harmful.

That's a very vague argument, and apart from helping you to understand what PDB files are for, I cannot change anything in regard of Icinga here. 

Cheers,
Michael

**Comment by ggzengel** [comment]
I know what PDBs are for but I don't know how save the code is which reads them.
Normally PDBs are only loaded while you control the process with a debugger and shouldn't load while normal usage. In this case you already have full control on this process.

History tells us that the simplest code can be vulnerable and PDB reading is the at least proven code because it is closed source and normally not used in production.

I don't know why openssl reads symbol information on start up. Perhaps it's compiled with some debug options.

**Comment by ggzengel** [comment]
If I read this from https://github.com/Microsoft/microsoft-pdb I get a deja vu about all the zip and media file libraries full of vulnerability:

##What is a PDB

PDBs are files with multiple ‘streams’ of information in them. You can almost assume each stream as an individual file, except that storing them as individual files is wasteful and inconvenient, hence this multiple streams approach. PDB streams are not NTFS streams though. They can be implemented as NTFS streams, but since they are to be made available on Win9X as well, they use a home brewed implementation. The implementation allows a primitive form of two-phase commit protocol. The writers of PDB files write what ever they want to in PDBs, but it won’t be committed until an explicit commit is issued. This allows the clients quite a bit of flexibility - say for example, a compiler can keep on writing information, and just not commit it, if it encounters an error in users’ source code.

**Comment by dnsmichi** [comment]
I'm not sure what you are trying to tell us here. If you consider PDBs insecure, I am pretty sure that group policies on Windows can prohibit their access. It is your Windows system anyways, and it depends on you which security measurements are in place. Without allowing access to PDBs, debugging crashes will be harder though, and crash logs may contain unusable details.
