### ISSUE TITLE
32bit 2.6.3 agent critical/cli: Peer did not present a valid certificate

### ISSUE THREAD

**Issue by Neptunium1129** [Icinga/icinga2#7574]
![이미지 43](https://user-images.githubusercontent.com/32185134/66738962-a31dc900-eeaa-11e9-9d8e-597367d9452b.png)

FIRST ERROR SCREEN SHOT

![이미지 42](https://user-images.githubusercontent.com/32185134/66738772-36a2ca00-eeaa-11e9-82e1-ee2979b657c9.png)

**master** 
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.0-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-862.9.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

=====================
**agent**
icinga2 - The Icinga 2 network monitoring daemon (version: v2.6.3)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /var/run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /var/run/icinga2/icinga2.pid

System information:
  Platform: CentOS
  Platform version: 5.11 (Final)
  Kernel: Linux
  Kernel version: 2.6.18-419.el5
  Architecture: i686

Build information:
  Compiler: GNU 4.8.2
  Build host: 9c5802041d44

* Enabled features (`icinga2 feature list`):
**agent**
[root@localhost icinga2]# icinga2 feature list
Disabled features: command compatlog debuglog gelf graphite influxdb livestatus logstash opentsdb perfdata redis statusdata syslog
Enabled features: api checker mainlog notification

* Config validation (`icinga2 daemon -C`): error occurred  because  icinga2 node wizard 

[MASTER LOG]

[2019-10-14 14:55:06 +0900] information/ApiListener: Reconnecting to endpoint 'agent' via host 'agentIP' and port '5665'
[2019-10-14 14:55:26 +0900] critical/ApiListener: Client TLS handshake failed (from [agentIP]:46456): wrong version number.

[AGENT LOG]
[2019-10-14 10:04:21 +0900] information/JsonRpcConnection: Reconnecting to API endpoint 'masterName' via host 'master Ip' and port '5665'
[2019-10-14 10:04:21 +0900] warning/TlsStream: TLS stream was disconnected.
[2019-10-14 10:04:21 +0900] critical/ApiListener: Client TLS handshake failed (to [115.68.221.161]:5665)
Context:
        (0) Handling new API client connection

another 2.7.0 agent is working

only 32bit v2.6.3 icinga2 not working..

add + openssl version 
[root@localhost icinga2]# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013

> openssl s_client -connect masterIP:5665 -cipher 'ECDHE-RSA-AES256-GCM-SHA384' 

CONNECTED(00000003)
depth=1 CN = Icinga CA
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/CN=namoni
   i:/CN=Icinga CA
 1 s:/CN=Icinga CA
   i:/CN=Icinga CA
---
subject=/CN=namoni
issuer=/CN=Icinga CA
---
Acceptable client certificate CA names
/CN=Icinga CA
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 3457 bytes and written 257 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: D3C3BE0B2F3347C8471F3F0781026144C7A9716B497EC06E046DB650E0A5CFC6
    Session-ID-ctx:
    Master-Key: E9C4C43664C7B9637F30D0F1FB02644FDA310D2C83447FF04FEFB30E078666959EF3DD33A49C7EF6EED3A8077F125C70
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 7200 (seconds)

    Start Time: 1571042549
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)

!import 
master 2.9.1 is work agent 2,6.3!!
but 2.11 update agent 2.6.3 not work..

   
![이미지 43](https://user-images.githubusercontent.com/32185134/66738968-a913aa00-eeaa-11e9-9e61-74ee3c172397.png)

**Comment by Neptunium1129** [comment]
oh my god...
 openssl version complie update  1.0.1 this is not work??

![이미지 44](https://user-images.githubusercontent.com/32185134/66742655-1c211e80-eeb3-11e9-87f9-223ef202e8b8.png)

**Comment by dnsmichi** [comment]
So you're saying you've installed a newer version of OpenSSL on that host, and also have recompiled Icinga 2 in order to use its updated capabilities with OpenSSL?

**Comment by Neptunium1129** [comment]
in agent openssl 0.9.8 -> 1.0.1 compile update 2.6.3 icinga version and  excute icinga2 node wizard 

that work not work anymore??   
ㅠ.ㅠ

**Comment by dnsmichi** [comment]
Icinga is compiled against the header API from OpenSSL. With just updating OpenSSL, it will not enable you to use TLSv1.2. The CLI command works for sure, as seen in your tests above, but Icinga 2 itself doesn't know anything about it.

**Comment by Neptunium1129** [comment]
thanks  reply...

**Comment by Neptunium1129** [comment]
[solve]
master icinga2 downgrade 
2.11 > 2.9.0
![191015](https://user-images.githubusercontent.com/32185134/66804767-51cf1180-ef5e-11e9-98bf-616ded6286e5.png)
