### ISSUE TITLE
InfluxdbWriter with no perf data

### ISSUE THREAD

**Issue by papage** [Icinga/icinga2#7582]
I would like to use influxdb to store status information  ("on"/"off").
There is a large number of scripts that produce this status info, but they don't return performance data, because there is not point in doing so. So, I tried to use InfluxdbWriter to store the statuses to influx, but I discovered that it needs perf data.

I think InfluxdbWriter should store all the service-checks results, even if they don't have perf data.

Thanx,
Sp

**Comment by dnsmichi** [comment]
What's your proposed data structure in storing this? Right now, this is done via the metric label which needs a key and value. 

Also, I don't think that this would a good idea to enable by default since people expect only performance data being written to InfluxDB. Doing otherwise will generate lots of unwanted data, and as such, empty graphs and dashboards in Grafana which relies on metric queries.

**Comment by papage** [comment]
Well, I fully agree that the default behavior should not change. That means that an option should be available for that. Lets say the option is "write_state"=1, like in:
  service_template = {
    measurement = "$service.check_command$"
    write_state =1
    tags = {
      hostname = "$host.name$"
      service = "$service.name$"
      instance = "$service.vars.instance$"
    }
  } 
As far as the data structure is concerned, since InfluxdbWriter  uses the "metric" tag to store the keyname of the perf data, I would say to use the same tag ("metric") and use as a tagvalue the name "state".  In case of conflict with a keyname of perf data, one of these should prevail. I think the service state should prevail, because it is an option that the user selected. So, the user has the choice to disable the option.

**Comment by odeshog** [comment]
@papage isn't the exsting enable_send_metadata option what you want? Assuming the on/off status in the scripts you talk about is the check result (ok/warning etc)

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback (requested here: https://github.com/Icinga/icinga2/issues/7582#issuecomment-567560368) for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
