### ISSUE TITLE
Icinga2 notes_url on host not dynmaic

### ISSUE THREAD

**Issue by Tux12Fun** [Icinga/icinga2#7585]
## Describe the bug

Hi, I like to build the notes_url in my host template dynamicly. On the service this is working without Problems. But on the Host Element the variable is empty.

## To Reproduce
```
template Host "ce.generic.host" {
   max_check_attempts = 5
   check_interval     = 2m
   retry_interval     = 30s
   check_command      = "hostalive"
   enable_flapping    = false
   enable_perfdata    = true
   vars.notification = {
      icingaadmin = {
            h_states = [ Up, Down ]
            h_types  = [ Problem, Acknowledgement, Recovery, Custom,
                         FlappingStart, FlappingEnd, DowntimeStart,
                               DowntimeEnd, DowntimeRemoved ]
            s_states = [ OK, Warning, Critical, Unknown ]
            s_types  = [ Problem, Acknowledgement, Recovery, Custom,
                         FlappingStart, FlappingEnd, DowntimeStart,
                         DowntimeEnd, DowntimeRemoved ]
      }
   }
   notes_url           = "https://confluence.xxxxxxxx/display/" + vars.info.other.confluence_space + "/" + name + "#" + name + "-HOSTDOWN"
}
```

```
template Service "ce.generic.service" {
   display_name        = "dummy_service"
   max_check_attempts  = 7
   check_interval      = 150s
   retry_interval      = 30s
   enable_flapping     = false
   enable_perfdata     = true
   vars.notification   = host.vars.notification.clone()
   notes_url           =  "https://confluence.xxxxxxxx/display/" + host.vars.info.other.confluence_space +  "/" + host.name + "#" + host.name + "-" + (name).upper()
}
```

```
object Host "daa322t.local" {
   import "ce.generic.host"
   address = "10.*****"

   #### INFO ###
   vars.info = {
      sys = {
           system_type = "esx-guest"
           os_type = "LINUX"
      }
      other = {
           confluence_space = "SAP"
      }
   }
}
```

If I take a look into IcingaWeb on a service I can see the following URL:
https://confluence.xxxxxxxx/display/SAP/daa322t.local#daa322t.local-CPU_PERFORMANCE

That works perfekt.

On the Host I can see this URL:
https://confluence.xxxxxxxx/display//daa322t.local#daa322t.local-HOSTDOWN

The "SAP" Part in the url is missing.

Oh the host template I'm not allowed to write host.vars.info.other.confluence_space

## Expected behavior

I'm expecting the URL with the "SAP" Part.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.1-1)

System information:
  Platform: Ubuntu
  Platform version: 18.04.3 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 4.15.0-60-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-LTrJQZ9N-project-298-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

**Comment by dnsmichi** [comment]
The service template likely is imported into an apply rule where you have direct access to the `host` object with `host.vars....`. That indeed works and is supported.

With the host template, you'll have an ordering problem. The host object is constructed within the attribute steps.

- First you'll import the template and map all attributes into the host object context. At this time, `vars.info` is not populated.
- Later on the host object attributes `vars.info` is populated (too late)

One way to solve this could to import the template after defining the `vars.info` attribute on the host object level.

**Comment by Tux12Fun** [comment]
Is it possible to define the Structure on the template and redefine it on the host object?
And using a referenced Variable to the Field of the Dictionary or a Function?

Something like

````
template Host "ce.generic.host" {
   max_check_attempts = 5
   check_interval     = 2m
   retry_interval     = 30s
   check_command      = "hostalive"
   enable_flapping    = false
   enable_perfdata    = true
   vars.notification = {
      icingaadmin = {
            h_states = [ Up, Down ]
            h_types  = [ Problem, Acknowledgement, Recovery, Custom,
                         FlappingStart, FlappingEnd, DowntimeStart,
                               DowntimeEnd, DowntimeRemoved ]
            s_states = [ OK, Warning, Critical, Unknown ]
            s_types  = [ Problem, Acknowledgement, Recovery, Custom,
                         FlappingStart, FlappingEnd, DowntimeStart,
                         DowntimeEnd, DowntimeRemoved ]
      }
   }
   #### INFO ###
   vars.info = {
      sys = {
      }
      other = {
           confluence_space = "DUMMY"
      }
   }

   notes_url           = "https://confluence.xxxxxx/display/" + &vars.info.other.confluence_space + "/" + name + "#" + name + "-HOSTDOWN"
}
````

Or use a function that is executed later?

I would love it, to define the link in my generic template but the confluence_space is generated by ansible on the host later on the time when the department rolles out the check.

**Comment by dnsmichi** [comment]
I'm not sure where you are heading here. As said, with the template import at the last possible state inside the host object, you can solve this.

Also, this isn't really a bug but a configuration question. I suggest asking this over at https://community.icinga.com and reach more users.
