### ISSUE TITLE
2.11 Server/Client builds missing from https://packages.icinga.com RHEL7 release branch

### ISSUE THREAD

**Issue by ricsil** [Icinga/icinga2#7586]
Title more or less says it all.
I see 2.11 built in RHEL8 repo, and RHEL7 only has 2.11 in snapshot folder.
Is RHEL7 not supported? Or should we just build from source?

**Comment by dnsmichi** [comment]
http://packages.icinga.com/epel/7/release/x86_64/icinga2/ has it, and yum also knows about the package index from sub folders. Just try it in a Docker container.

**Comment by ricsil** [comment]
Ah, that was unexpected! Didn't see the folder there, sorry!
