### ISSUE TITLE
Change the Installation Paths

### ISSUE THREAD

**Issue by 10bias** [Icinga/icinga2#7596]
Hello, i am trying to install Icinga2 to a different path than the default (https://icinga.com/docs/icinga2/latest/doc/02-installation/#installation-paths). In the documenation i could not find a way to change the install path. So is there a way to change the install path when i am installing from RPM?
Thanks!

**Comment by dnsmichi** [comment]
Hi,

we only support the default paths provided within the official packages. There's additional CI integration tests running to ensure these work. You may rebuild the srpms and create your own packages. 

Keep in mind though that this requires additional maintenance for you on every new version compared to using the official packages. Also, troubleshooting things get harder and community members & developers won't be able to help aside from standard paths. 

Cheers,
Michael

**Comment by 10bias** [comment]
Thanks for the quick response. I think i will use the official packages and use the default paths. This sounds easier for my problem than rebuilding the srpms.
