### ISSUE TITLE
Child satellite try to deletObjects from parent zone

### ISSUE THREAD

**Issue by PedroMSantosD** [Icinga/icinga2#7599]
## Describe the bug

I'm seeing plenty of errors on logs of my icinga master node, with contents:

> warning/ApiListener: Ignoring config update. 'api' does not accept config.

when evaluating the debug.log, I see this message starts the thread that ends in said error:

> root@icinga.master.internal icinga2# grep 'config::DeleteObject' debug.log  | head
> [2019-10-30 07:31:23 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone1.internal'
> [2019-10-30 07:31:23 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone1.internal'
> [2019-10-30 07:31:34 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone1.internal'
> [2019-10-30 07:31:34 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone1.internal'
> [2019-10-30 07:31:34 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone1.internal'
> [2019-10-30 07:31:37 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone2.internal'
> [2019-10-30 07:31:37 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone2.internal'
> [2019-10-30 07:31:37 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone2.internal'
> [2019-10-30 07:31:37 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone2.internal'
> [2019-10-30 07:31:37 -0400] notice/JsonRpcConnection: Received 'config::DeleteObject' message from 'satellite-1.zone2.internal'

## To Reproduce

Not sure how to fill this, for me is an ongoing issue, a node from a child zone sends a config""DeletteObject and then the master rejects with error ..  'api' does not accept config. 

Why is this happening?

## Expected behavior

Child zones should not try to delete configuration objects from parent zones

## Screenshots

NA
## Your Environment

Include as many relevant details about the environment you experienced the problem in

My icinga version information follows

> # icinga2 --version
> icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)
> 
> Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
> License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Application information:
>   Installation root: /usr
>   Sysconf directory: /etc
>   Run directory: /run
>   Local state directory: /var
>   Package data directory: /usr/share/icinga2
>   State path: /var/lib/icinga2/icinga2.state
>   Modified attributes path: /var/lib/icinga2/modified-attributes.conf
>   Objects path: /var/cache/icinga2/icinga2.debug
>   Vars path: /var/cache/icinga2/icinga2.vars
>   PID path: /run/icinga2/icinga2.pid
> 
> System information:
>   Platform: CentOS Linux
>   Platform version: 7 (Core)
>   Kernel: Linux
>   Kernel version: 3.10.0-957.21.2.el7.x86_64
>   Architecture: x86_64
> 
> Build information:
>   Compiler: GNU 4.8.5
>   Build host: unknown

config validation

> # icinga2 daemon --validate
> information/cli: Icinga application loader (version: r2.8.4-1)
> information/cli: Loading configuration file(s).
> information/ConfigItem: Committing config item(s).
> information/ApiListener: My API identity: icinga.master.internal
> information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 2636, rate: 344.783/s (20687/min 20687/5min 20687/15min); empty in 18199 days, 12 hours, 14 minutes and 22 seconds
> information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
> information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
> information/WorkQueue: #7 (InfluxdbWriter, influxdb) items: 0, rate:  0/s (0/min 0/5min 0/15min);
> information/WorkQueue: #8 (IdoMysqlConnection, ido-mysql) items: 0, rate:  0/s (0/min 0/5min 0/15min);
> information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 25000, rate: 1213/s (72780/min 72780/5min 72780/15min);
> information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 25000, rate: 2189.2/s (131352/min 131352/5min 131352/15min); empty in -2147483648 days
> information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 24986, rate: 2656.55/s (159393/min 159393/5min 159393/15min); empty in infinite time, your task handler isn't able to keep up
> information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 7849, rate: 3097.7/s (185862/min 185862/5min 185862/15min);
> information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 3329, rate: 7369.45/s (442167/min 446796/5min 446796/15min);
> warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 27:1-27:41) for type 'Dependency' does not match anywhere!
> warning/ApplyRule: Apply rule 'alertaio-event-host' (in /etc/icinga2/zones.d/global/notifications.d/notifications.conf: 15:1-15:48) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'alertaio-event-service' (in /etc/icinga2/zones.d/global/notifications.d/notifications.conf: 24:1-24:54) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'mattermost-channel-prod-host' (in /etc/icinga2/zones.d/global/notifications.d/mattermost/notifications.conf: 4:1-4:57) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'mattermost-channel-prod-service' (in /etc/icinga2/zones.d/global/notifications.d/mattermost/notifications.conf: 13:1-13:63) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'mattermost-user-prod-host' (in /etc/icinga2/zones.d/global/notifications.d/mattermost/notifications.conf: 24:1-24:54) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'mattermost-user-prod-service' (in /etc/icinga2/zones.d/global/notifications.d/mattermost/notifications.conf: 33:1-33:60) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'mattermost-channel-nonprod-host' (in /etc/icinga2/zones.d/global/notifications.d/mattermost/notifications.conf: 44:1-44:60) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'mattermost-channel-nonprod-service' (in /etc/icinga2/zones.d/global/notifications.d/mattermost/notifications.conf: 54:1-54:66) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'mattermost-user-nonprod-host' (in /etc/icinga2/zones.d/global/notifications.d/mattermost/notifications.conf: 65:1-65:57) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule 'mattermost-user-nonprod-service' (in /etc/icinga2/zones.d/global/notifications.d/mattermost/notifications.conf: 75:1-75:63) for type 'Notification' does not match anywhere!
> warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/global-internal/services.d/services-mssql.conf: 142:1-142:76) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/global-internal/services.d/services-windows.conf: 222:1-222:58) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule 'pacheck' (in /etc/icinga2/zones.d/global-internal/services.d/services.conf: 20:1-20:23) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/global-internal/services.d/services.conf: 135:1-135:76) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/global-internal/services.d/jurisdiction.conf: 2:1-2:106) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/global-internal/services.d/test_blocking.conf: 1:0-1:110) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/global-internal/services.d/services-bigip.conf: 57:1-57:62) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/global-internal/services.d/services-bigip.conf: 81:1-81:80) for type 'Service' does not match anywhere!
> warning/ApplyRule: Apply rule 'cassandra-core-service' (in /etc/icinga2/zones.d/global-internal/services.d/cassandra-core.conf: 1:0-1:43) for type 'Service' does not match anywhere!
> information/ConfigItem: Instantiated 1 ApiListener.
> information/ConfigItem: Instantiated 45 Zones.
> information/ConfigItem: Instantiated 63 Endpoints.
> information/ConfigItem: Instantiated 1 FileLogger.
> information/ConfigItem: Instantiated 16 ApiUsers.
> information/ConfigItem: Instantiated 1 LivestatusListener.
> information/ConfigItem: Instantiated 1 UserGroup.
> information/ConfigItem: Instantiated 11 NotificationCommands.
> information/ConfigItem: Instantiated 96075 Notifications.
> information/ConfigItem: Instantiated 377 CheckCommands.
> information/ConfigItem: Instantiated 1 EventCommand.
> information/ConfigItem: Instantiated 1 IcingaApplication.
> information/ConfigItem: Instantiated 6217 Hosts.
> information/ConfigItem: Instantiated 287 HostGroups.
> information/ConfigItem: Instantiated 111566 Dependencies.
> information/ConfigItem: Instantiated 591 Downtimes.
> information/ConfigItem: Instantiated 3 TimePeriods.
> information/ConfigItem: Instantiated 100 Users.
> information/ConfigItem: Instantiated 1905 Comments.
> information/ConfigItem: Instantiated 50 ServiceGroups.
> information/ConfigItem: Instantiated 85194 Services.
> information/ConfigItem: Instantiated 67 ScheduledDowntimes.
> information/ConfigItem: Instantiated 1 CheckerComponent.
> information/ConfigItem: Instantiated 1 InfluxdbWriter.
> information/ConfigItem: Instantiated 1 NotificationComponent.
> information/ConfigItem: Instantiated 1 IdoMysqlConnection.
> information/ConfigItem: Instantiated 1 ExternalCommandListener.
> information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
> information/cli: Finished validating the configuration file(s).

enabled features

> # icinga2 feature list
> Disabled features: compatlog debuglog elasticsearch gelf graphite opentsdb perfdata statusdata syslog
> Enabled features: api checker command ido-mysql influxdb livestatus mainlog notification
> 

## Additional context

not sure how to proceed to gather more relevant information on what is causing the problem

**Comment by K0nne** [comment]
Hello!

You should try the most recent release. Your version ist already out of support.

**Comment by PedroMSantosD** [comment]
Thanks for the prompt reply, will update asap.

**Comment by dnsmichi** [comment]
A similar issue is covered with #4969 where these cluster messages are sent back, but then denied by the internal security handling. You can safely ignore them, especially for those from the debug log. Changes in 2.11 also ensure that maybe-occurring loops will never happen again.
