### ISSUE TITLE
execvpe(/usr/lib64/nagios/plugins/check_load) failed: Input/output error results in UNKNOWN

### ISSUE THREAD

**Issue by SiJux** [Icinga/icinga2#7617]
## Describe the bug

If the Storage of a virtual machine crashes and the icinga2-agent could not fork a process for check-script, this results in UNKNOWN error.

## To Reproduce

1. setup distributed monitor with master -> satellite -> client
2. kill the storage of the client
3. The master will shown an unknown error

## Expected behavior

In my opinion this should cause an CRITICAL error

## Your Environment

* Version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.2-1)
* Operating System and version: RHEL 7
* Enabled features (`icinga2 feature list`): Disabled features: compatlog debuglog elasticsearch gelf graphite livestatus opentsdb perfdata statusdata
Enabled features: api checker command ido-mysql influxdb mainlog notification syslog

* Icinga Web 2 version and modules (System - About): Icinga Web 2 Version 2.7.3

**Comment by Al2Klimov** [comment]
Hello @SiJux  and thank you for reporting!

Critical stands not for *something is broken*, but for *the thing to be checked has been checked successfully, but its state doesn't meet the expectation*. In your case the machine's load couldn't even be checked due to the I/O error – unknown.

Best,
AK

**Comment by Al2Klimov** [comment]
@dnsmichi Shall we mention that in our docs?

**Comment by dnsmichi** [comment]
Not sure where this could fit, but it doesn't hurt. On the other hand, users may google for it and find your explanation here. Full ack btw.
