### ISSUE TITLE
MSI silent installation without .net dependency

### ISSUE THREAD

**Issue by elderorange** [Icinga/icinga2#7634]
We have a lot of dependencies to specific .net versions on our windows servers.
That‘s why we can’t role out the needed .net version for icinga2 client per msi installer automatically.

If .net is only needed for the installation per GUI is it possible to set different dependencies for silent/quiet installation where a newer .net version is not required?

**Comment by dnsmichi** [comment]
See my comment here: https://github.com/Icinga/icinga2/issues/7413#issuecomment-520473621
