### ISSUE TITLE
Livestatus does not show modified attributes

### ISSUE THREAD

**Issue by chrnie** [Icinga/icinga2#7637]
## Describe the bug

I recently found a Livestatus issue related to modified Attributes. 
There is a data field in live status. However, this will not be updated when executing actions on hosts or services in the frontend (Thruk, Classic UI, or icingaweb2).

## To Reproduce

Choose a service in your preferred Frontend. Disable or Enable Notifications for this service. 
In thruk there's a field with a modified attributes count. But that stays at 0

You can check it directly via livestatus. There is no update while the modified_attributes.conf knows about the attribute.

> echo -e 'GET services \nColumnHeaders: on \nColumns: host_name display_name modified_attributes \nFilter: host_name = SRV0815 \n' | nc -U /path/to/cmd/livestatus
SRV0815;win-load;0
SRV0815;win-disk c;0 
SRV0815;win-disk d;0 

Snippet from modified_attributes.conf:
> var obj = get_object("Service", "SRV0815!win-load")
if (obj) {
        obj.modify_attribute("enable_notifications", true)
        obj.version = 1570627636.268823
}
var obj = get_object("Service", "SRV0815!win-disk c") 
if (obj) {
        obj.modify_attribute("enable_notifications", false)
        obj.version = 1574245734.218357
}
var obj = get_object("Service", "SRV0815!win-disk d") 
if (obj) {
        obj.modify_attribute("enable_notifications", false)
        obj.version = 1574245853.968103
}

## Expected behavior

I expect livestatus to print the correct number of modified_attributes

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* icinga 2.11.2
* Rhel7
* Enabled features:
  * api
  * command
  * compatlog
  * livestatus
  * mainlog
  * notification
  * perfdata
  * statusdata
* thruk 2.32-3

## Additional context

https://www.thruk.org/documentation/modified_attributes.html

**Comment by dnsmichi** [comment]
The modified_attributes bitmask is not implemented in Icinga 2, this only is available with Icinga 1.x. The background handling of modifying attributes uses a different method. The IDO backend doesn't have that available either.
