### ISSUE TITLE
can_submit_commands in livestatus

### ISSUE THREAD

**Issue by chrnie** [Icinga/icinga2#7639]
## Is your feature request related to a problem? Please describe.

the can_submit_commands field is missing in livestatus. 

https://icinga.com/docs/icinga2/latest/doc/24-appendix/#livestatus-contacts-table-attributes

## Describe the solution you'd like

It would be nice to to have this attribute back, so we can manage this right in thruk and other UIs

## Describe alternatives you've considered

It could be enough to map vars.can_submit_commands to this table. We don't need it as direct contact field

**Comment by dnsmichi** [comment]
That's a flag Icinga 1.x provides, Icinga 2 doesn't implement this.
