### ISSUE TITLE
[ITL] Defaults for check_pgsql prevent basic use case

### ISSUE THREAD

**Issue by Kaelnor** [Icinga/icinga2#7649]
Hi,

I noticed a weird behavior while trying to monitor an instance of postgresql locally on a host.

By default, the check_pgsql plugin uses the socket to connect to postgres if no -H is specified.
This is nice as we can easily allow the user nagios/icinga to connect to the instance with peer authentication.

From the check_pgsql man page:
> All parameters are optional.
> ...
> The plugin will connect to a local postmaster if no host is specified.

But, the defaults in the ITL force -H to $check_address$ if nothing is specified elsewhere.
The line responsible is in /usr/share/icinga2/include/command-plugins.conf (Ubuntu 18.04):
`(line 2687)         vars.pgsql_hostname = "$check_address$" `

**This makes it impossible to have a local check with the default behavior of check_pgsql.**

The same config may impact other check plugins as well but postgres is where I noticed it.
For instance, the configuration is also present for check_mysql but the plugin has a slightly different behavior with localhost:

From the check_mysql man page:
> There are no required arguments. By default, the local database is checked
>  using the default unix socket. You can force TCP on localhost by using an
>  IP address or FQDN ('localhost' will use the socket as well).
----
Version report for reference.

icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.2-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 18.04.3 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 4.15.0-69-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-LTrJQZ9N-project-298-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

**Comment by dgoetz** [comment]
According to the docs the check takes also a unix socket for the hostname so you can override the default via custom var on service or host level.

**Comment by Kaelnor** [comment]
Indeed you can put the path to the directory containing the socket in vars.pgsql_hostname.
This is what I did as a workaround and it is working.

I just find it counter-productive having to specify what is a default setting of the plugin, that could potentially change in the future or be different between OS. In fact, the plugin just uses the default of libpq if you don't specify any hostname.

From the docs of libpq:
> Without either a host name or host address, libpq will connect using a local Unix-domain socket; or on machines without Unix-domain sockets, it will attempt to connect to localhost.

So I can use the check, but the real question is what is better for the configuration of Icinga2 and the user in general ?

1. Let vars.pgsql_hostname default to check_address in the CheckCommand definition. The cost is having to override it at the host or service level and losing the ability to call check_pgsql without arguments.
Without any configuration, the service is checked from icinga2 master to the client via TCP/IP.

2. Remove the default in the CheckCommand definition. Now, without configuration, the service is checked on the master and you have to set command_endpoint in your service. But this allows you to call check_pgsql on clients without overriding vars.pgsql_hostname.

Anyway, I don't know if there is a policy regarding how things should behave in the ITL. If anyone has the same issue on this plugin or another it would be nice to hear your thoughts on this.

**Comment by dnsmichi** [comment]
You can still create your own CheckCommand if you don't like the proposed way inside the ITL. In terms of specific plugin behaviour, we decided to create one path with having an additional fallback from the host to the socket with custom variable influence. If there is yet again another method, that's unfortunate but I doubt we can add this in a safe way to the existing CheckCommand object. It would break in some way, and users must not be affected by such a change.

**Comment by Kaelnor** [comment]
Thank you for your insight.

I understand that users would be affected by this change and the safest way is to create another CheckCommand definition.

I think this issue can be closed.

**Comment by dnsmichi** [comment]
Ok, thanks.
