### ISSUE TITLE
Graphite writer not writing zero values

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icinga2#7666]
## Describe the bug
The graphite writer feature is not sending a metric for warn, crit, min and max if explicitly set to 0. By not doing so graphs look inconsistent for the same check with some having a warning threshold of zero and others with one above.  

## To Reproduce
1. Include a service with a performance data label like `'errors'=10;0;20`
2. In Icinga Web 2 it will correct values below "Performance data"
3. In the Graphite modul it will only show lines for the `value` and `crit`

## Expected behavior
If there is a value set for the threshold it sends also a value to graphite. Only if none is set, nothing is send.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.11.2
* Operating System and version: RHEL 7
* Enabled features (`icinga2 feature list`): graphitewriter
* Icinga Web 2 version and modules (System - About): 2.7.3

## Additional context
Responsible lines are https://github.com/Icinga/icinga2/blob/master/lib/perfdata/graphitewriter.cpp#L363-L370 where the value is returned from `pdv->GetWarn()` and the zero is interpreted as false, so nothing is send.

**Comment by dnsmichi** [comment]
Since we're always sending the data when this is <0 or >0, the if conditions don't make much sense. We could of course change the parser to store value variants, or install additional "hasValueX" guards. Imho that overly complicates the code and also slows things down.

**Comment by dnsmichi** [comment]
I see, these are of the Value type already where IsEmpty() is applicable.
