### ISSUE TITLE
getting CRITICAL when using ./check_snmp_int.pl for snmp GET

### ISSUE THREAD

**Issue by partuner** [Icinga/icinga2#7671]
hello ,

iam trying to make snmp requests to devices from the Icinga2 and allways get the CRITICAL response 
example :
./check_snmp_int.pl '-C' 'public' '-H' '192.168.100.15' '-n' '-v2'

and this is the respond with the CIRTICAL at the end:
Alarm in 5 seconds
SNMP v2c login
Filter : 
OID : 1.3.6.1.2.1.2.2.1.2.5, Desc : GigabitEthernet0/0/0/0
Name : GigabitEthernet0/0/0/0, Index : 5
OID : 1.3.6.1.2.1.2.2.1.2.6, Desc : GigabitEthernet0/0/0/1
Name : GigabitEthernet0/0/0/1, Index : 6
OID : 1.3.6.1.2.1.2.2.1.2.7, Desc : GigabitEthernet0/0/0/2
Name : GigabitEthernet0/0/0/2, Index : 7
OID : 1.3.6.1.2.1.2.2.1.2.8, Desc : GigabitEthernet0/0/0/3
Name : GigabitEthernet0/0/0/3, Index : 8
OID : 1.3.6.1.2.1.2.2.1.2.9, Desc : GigabitEthernet0/0/0/4
Name : GigabitEthernet0/0/0/4, Index : 9
OID : 1.3.6.1.2.1.2.2.1.2.10, Desc : GigabitEthernet0/0/0/5
Name : GigabitEthernet0/0/0/5, Index : 10
OID : 1.3.6.1.2.1.2.2.1.2.11, Desc : GigabitEthernet0/0/0/6
Name : GigabitEthernet0/0/0/6, Index : 11
OID : 1.3.6.1.2.1.2.2.1.2.12, Desc : Loopback1
Name : Loopback1, Index : 12
OID : 1.3.6.1.2.1.2.2.1.2.3, Desc : MgmtEth0/RP0/CPU0/0
Name : MgmtEth0/RP0/CPU0/0, Index : 3
OID : 1.3.6.1.2.1.2.2.1.2.2, Desc : Null0
Name : Null0, Index : 2
GigabitEthernet0/0/0/0:UP, GigabitEthernet0/0/0/1:DOWN, GigabitEthernet0/0/0/2:DOWN, GigabitEthernet0/0/0/3:DOWN, GigabitEthernet0/0/0/4:DOWN, GigabitEthernet0/0/0/5:DOWN, GigabitEthernet0/0/0/6:DOWN, Loopback1:UP, MgmtEth0/RP0/CPU0/0:UP, Null0:UP: 6 int NOK : CRITICAL

if the device is answerd me using port 161 in snmp and i see the response in Icinga , why do i getting the " CRITICAL " state type ?

thank you in advance.

**Comment by TheFlyingCorpse** [comment]
Firstly,
You get a CRITICAL because the plugin returns an exitcode of 2.
The likely reason for this is because it returns some interfaces as DOWN, rather than UP. Check your parameters and modify accordingly.

**Comment by partuner** [comment]
i understand , ok fixed that by adding the --down parameter ,

thank you.

**Comment by dnsmichi** [comment]
Please move these kind of questions to https://community.icinga.com first. If it really is a bug in Icinga, you can always add an issue later.
