### ISSUE TITLE
Optimize error output for missing X-HTTP-Method-Override

### ISSUE THREAD

**Issue by baurmatt** [Icinga/icinga2#7675]
## Is your feature request related to a problem? Please describe.

Let's say I try to run the following script (query could be way more complex, this is just for showing the problem):

```bash
#!/usr/bin/env bash

QUERY=$(cat <<-HEREDOC
{
  "attrs": [
    "address"
  ],
  "pretty": true
}
HEREDOC
)

RESPONSE=$(curl --silent --insecure \
                --user "root:icinga" \
                --header 'Accept: application/json' \
                --request POST \
                --data "${QUERY}" \
                "https://localhost:5665/v1/objects/hosts")

echo "${RESPONSE}"
```

The output looks like this:

```bash
root@testhost01:~# bash icinga.sh
{
    "error": 400.0,
    "status": "Invalid type for 'attrs' attribute specified. Dictionary type is required."
}
```

This is highly misleading as the "actual" problem is, that the HTTP call is missing a `X-HTTP-Method-Override: GET` header.

## Describe the solution you'd like

It would be really helpful as a user if I would get a clearer error message which helps me to faster understand what I did wrong.

**Comment by dnsmichi** [comment]
A POST request to this URL endpoint is totally valid, it just evaluates into a different requirement then. Icinga cannot really guess that the user might have wanted to provide a different header at this scope with overriding the request method.

**Comment by baurmatt** [comment]
ok

**Comment by dnsmichi** [comment]
From my experience, you'll run into this error only once during programming and then you'll always verify it. I also had that issue when creating the api client sample code for the docs with forgetting to set the header accordingly. Unfortunately adding such additional guards to the code would overly complicate it and introduce possible new bugs with false positive error messages.

**Comment by baurmatt** [comment]
Hey @dnsmichi, sorry that was rude yesterday and I apologized for that.

I totally get that you don't want too much guards in your code because it makes it harder to maintain. But this error message still feels misleading from a user perspective (at least for the thing I was trying to develop).

How about extending the error message a little bit?

> "Invalid type for 'attrs' attribute specified. Dictionary type is required. Or is this a POST query and you missed adding a 'X-HTTP-Method-Override: GET' header?"

**Comment by dnsmichi** [comment]
No worries, and thanks for the kind words. Let's just call it a rough Monday :)

That sounds like a good idea, making the error messages more suggestive and helpful. This avoids additional if conditions and checks in this regard. Let's see how fast I can add that :-D

**Comment by baurmatt** [comment]
@dnsmichi I'm happy to provide a PR if you want :)

**Comment by dnsmichi** [comment]
@baurmatt That'll be awesome. I'm already back in my GitLab advanced training material ;-)
