### ISSUE TITLE
Error: boost::filesystem::copy_file: Permission denied: "/etc/icinga2/zones.conf", "/etc/icinga2/zones.conf.orig"

### ISSUE THREAD

**Issue by thalunil** [Icinga/icinga2#7679]
## Describe the bug

When running "icinga2 node wizard" via sudo on OpenSUSE 15.1 and answering all the questions of the wizard, the wizard throws at the end "permission denied".

I am attaching the stack trace which gets generated.

## Expected behavior

Icinga2 configuration should get written without a permission problem

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.11.2-1)
* Operating System and version:openSUSE 15.1
* Enabled features (`icinga2 feature list`): api checker mainlog
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context

[report.1575312423.908547.txt](https://github.com/Icinga/icinga2/files/3913184/report.1575312423.908547.txt)

**Comment by dnsmichi** [comment]
AFAIK SuSE has something similar to SELinux and apparmor. This might hinder the command copying files. Try disabling that and re-run the command.

**Comment by thalunil** [comment]
Hi - this was true. The problem was misconfigured AppArmor - it is by now fixed via OBS (http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_15.1/) and it is version 2.11.2-lp151.59.1. thanks for this hint!
