### ISSUE TITLE
Mysql Schema for NDBCluster

### ISSUE THREAD

**Issue by htsatsu** [Icinga/icinga2#7688]
No sure if this is a bug, but having issues extending the databases with the provided mysql schemas for Mysql NDBCluster.

SQL Server version: 5.7.28-ndb-7.6.12-cluster-gpl MySQL Cluster Community Server (GPL)
The icinga provided Mysql Schema defaults to InnoDB Engine, but NDB Engine is required for the table replication between SQL Nodes.

Can someone provide the mysql schema from MYSQL NDBCluster

**Comment by dnsmichi** [comment]
We had that discussion some years ago, and decided that we only support MySQL/MariaDB and the default engine provided in the schema. NDBCluster is not supported.

**Comment by htsatsu** [comment]
Thank you for your response. Can you share if there is any resource on how to implement MYSQL Clustering or Integration with Icinga2? Trying to implement resilience in my implementation of Icinga2 with Director with MYSQL Database as the data store.

**Comment by dnsmichi** [comment]
The docs in the scenario chapter provide some details about it: https://icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#high-availability-master-with-agents
