### ISSUE TITLE
IcingaDB: history IDs that are not UUIDs should have the Endpoint ID in them

### ISSUE THREAD

**Issue by N-o-X** [Icinga/icinga2#7703]
This is needed for split brain scenarios

**Comment by Al2Klimov** [comment]
## Blocked by

* [ ] #7690
* [ ] #7700

**Comment by Al2Klimov** [comment]
Is this still relevant?

**Comment by N-o-X** [comment]
Yes this is still needed for `acknowlegement_`, `downtime_` and `flapping_history` because we otherwise would overwrite rows in split brain.

**Comment by N-o-X** [comment]
This is something we need to discuss after Icinga 2.12 and Icinga DB 1.0

**Comment by Al2Klimov** [comment]
What were the pros and cons of this one again?

**Comment by N-o-X** [comment]
Without this, endpoints would overwrite each others history entries in case of split brain.

**Comment by Al2Klimov** [comment]
In case of a HA failover the other node calculates different IDs. Could we get trouble due to a HA failover?

**Comment by julianbrost** [comment]
I think so. If there's anything left of this idea, it should be part of #9029. But the very idea of having the endpoint as part of the ID is dead as we want both endpoints to generate identical ideas so that these events are deduplicated.
