### ISSUE TITLE
IcingaDB: Manually rescheduling a check doesn't update next_update & next_check

### ISSUE THREAD

**Issue by N-o-X** [Icinga/icinga2#7707]
Example:
- check_interval = 1m
- Reschedule check to now + 1h

=> Checkable is overdue 1 minute later => 59 minutes before next check should happen

**Comment by nilmerg** [comment]
I'm afraid but it seems that this still doesn't work. Redis is not updated correctly.

**Comment by nilmerg** [comment]
This also applies to `is_overdue`
