### ISSUE TITLE
systemd service's PIDFile references a path below legacy directory /var/run/

### ISSUE THREAD

**Issue by sbraz** [Icinga/icinga2#7710]
Hi,
Currently, `ICINGA2_RUNDIR` is set to `/var/run` by default because it depends on `${CMAKE_INSTALL_LOCALSTATEDIR}`:
https://github.com/Icinga/icinga2/blob/1b23d6b6c072f7238164d3a946ac45fe2dbd3708/CMakeLists.txt#L54

This results in the following systemd warning:
```
[3847500.659305] systemd[1]: /usr/lib/systemd/system/icinga2.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/icinga2/icinga2.pid → /run/icinga2/icinga2.pid; please update the unit file accordingly.
```

I think that the default value of `ICINGA2_RUNDIR` should simply be `run`. I can make a PR but I wasn't sure that this was the preferred solution.

**Comment by dnsmichi** [comment]
There are older systems which still use `/var/run` and up until this is supported by systemd, I would not change this.

**Comment by Al2Klimov** [comment]
## Task

* [ ] have a look at the OSes we support: do all of them have /run?

**Comment by Al2Klimov** [comment]
Great, SLES 12.5 has systemd v228 :)

**Comment by Al2Klimov** [comment]
And our RPMs seem to also already purr like 🐈s: https://git.icinga.com/packaging/rpm-icinga2/-/jobs/127402#L777

@sbraz What OS are we talking about?

**Comment by sbraz** [comment]
I don't want to risk breaking something. Let's keep it this way :)
