### ISSUE TITLE
unknown zone "director-global"

### ISSUE THREAD

**Issue by viper539** [Icinga/icinga2#7714]
It seems i accidentally upgraded the 2nd Node of my HA-Cluster from 2.10 to 2.11.

Now the upgraded Node is unable to restart icinga because it brings this warning:
    Ignoring directory '/var/lib/icinga2/api/zones/director-global' for unknown zone 'director-global'
Sadly in this zone are all my Templates and icinga wouldn't restart without them.

First Node is working fine.

Could you please help me?

icinga2 --version
Node1 r2.10.3-1
Node2 r2.11.2-1

icinga2 feature list
Node1
Disabled features: compatlog debuglog elasticsearch gelf graphite livestatus opentsdb statusdata syslog
Enabled features: api checker command ido-pgsql influxdb mainlog notification perfdata
Node2
Disabled features: command compatlog debuglog elasticsearch gelf graphite livestatus notification opentsdb statusdata syslog
Enabled features: api checker ido-pgsql influxdb mainlog perfdata

Zones.conf
```
object Endpoint "icinga-node1.<domain>" {
        host = "<IP>"
        port = "5665"
}

object Zone "master" {
        endpoints = [ "icinga-node1.<domain>", "icinga-node2.<domain>" ]
}

object Endpoint "icinga-node2.domain" {
}

object Zone "global-templates" {
        global = true
}

#object Zone "director-global" {
#       global = true
#}
```

OS: Debian 
cat /etc/debian_version 10.2

**Comment by viper539** [comment]
Zone-Object of Node1:
Object 'director-global' of type 'Zone':
  % declared in '/var/lib/icinga2/api/packages/director/ca6d0882-86d5-4c74-a47b-7217ae91ac34/zones.d/director-global/zones.conf', lines 1:0-1:28
  * __name = "director-global"
  * endpoints = null
  * global = true
    % = modified in '/var/lib/icinga2/api/packages/director/ca6d0882-86d5-4c74-a47b-7217ae91ac34/zones.d/director-global/zones.conf', lines 2:5-2:17
  * name = "director-global"
  * package = "director"
  * parent = ""
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 28
    * last_line = 1
    * path = "/var/lib/icinga2/api/packages/director/ca6d0882-86d5-4c74-a47b-7217ae91ac34/zones.d/director-global/zones.conf"
  * templates = [ "director-global" ]
    % = modified in '/var/lib/icinga2/api/packages/director/ca6d0882-86d5-4c74-a47b-7217ae91ac34/zones.d/director-global/zones.conf', lines 1:0-1:28
  * type = "Zone"
  * zone = "director-global"

Zone-Object of Node2:
Object 'director-global' of type 'Zone':
  % declared in '/var/lib/icinga2/api/zones/director-global/director/zones.conf', lines 1:0-1:28
  * __name = "director-global"
  * endpoints = null
  * global = true
    % = modified in '/var/lib/icinga2/api/zones/director-global/director/zones.conf', lines 2:5-2:17
  * name = "director-global"
  * package = "_cluster"
  * parent = ""
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 28
    * last_line = 1
    * path = "/var/lib/icinga2/api/zones/director-global/director/zones.conf"
  * templates = [ "director-global" ]
    % = modified in '/var/lib/icinga2/api/zones/director-global/director/zones.conf', lines 1:0-1:28
  * type = "Zone"
  * zone = "director-global"

**Comment by dnsmichi** [comment]
Global zones **must not** be deployed in another global zone. 

- purge away /var/lib/icinga2/api/*
- Add the global zone to zones.conf, similar to what the setup wizards do by default
- Restart Icinga 2
- Fix the Zone management in the Director prior to the next deployment, see here: https://icinga.com/docs/icinga2/latest/doc/15-troubleshooting/#zones-in-zones-doesnt-work

Furthermore, that's a question suited better at https://community.icinga.com 

Cheers,
Michael
