### ISSUE TITLE
check_disk.exe exclude does not accept wildcards

### ISSUE THREAD

**Issue by gitlizko** [Icinga/icinga2#7722]
## Describe the bug

The Windows check_disk does not accept wildcards to exclude disks. The Linux version does. This causes problems when i.e. backup solution restores multiple drives with random string in the name to path.

Please ensure to read https://github.com/Icinga/icinga2/blob/master/doc/15-troubleshooting.md first. Formatting tips: GitHub supports Markdown: https://guides.github.com/features/mastering-markdown/

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

c:\Program Files\ICINGA2\sbin>check_disk.exe -x C:\VeeamFLR*
DISK OK - free space:C:\ 26544635904 B (29%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume0\ 10613141504 B (20%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume10\ 6837264384 B (64%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume11\ 50800066560 B (95%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume1\ 170795008 B (33%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume2\ 27215413248 B (30%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume3\ 17134424064 B (32%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume4\ 95592562688 B (89%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume5\ 12612427776 B (29%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume6\ 121503084544 B (21%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume7\ 101679083520 B (47%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume8\ 31819505664 B (15%); C:\VeeamFLR\HOSTNAME_1d76ee9d\Volume9\ 38755590144 B (18%); D:\ 10613141504 B (20%); I:\ 53450866688 B (100%); J:\ 36917547008 B (6%); K:\ 31819505664 B (15%); L:\ 17112403968 B (32%); M:\ 112091705344 B (52%); N:\ 105841074176 B (99%); R:\ 6837264384 B (64%); S:\ 12612427776 B (29%); T:\ 32111812608 B (15%);

## Expected behavior

check_disk.exe -x C:\Directory* should exclude all the (regexp) matching moutpoints

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: v2.10.2)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Windows
  Platform version: 8 (Server)
  Kernel: Windows
  Kernel version: 6.2
  Architecture: x86_64

Build information:
  Compiler: MSVC 19.0.24215.1
  Build host: ICINGA-BUILD-WI

Application information:

General paths:
  Config directory: C:\ProgramData\icinga2\etc\icinga2
  Data directory: C:\ProgramData\icinga2\var\lib\icinga2
  Log directory: C:\ProgramData\icinga2\var\log\icinga2
  Cache directory: C:\ProgramData\icinga2\var\cache\icinga2
  Spool directory: C:\ProgramData\icinga2\var\spool\icinga2
  Run directory: C:\ProgramData\icinga2\var\run\icinga2

Old paths (deprecated):
  Installation root: C:\Program Files\ICINGA2\
  Sysconf directory: C:\ProgramData\icinga2\etc
  Run directory (base): C:\ProgramData\icinga2\var\run
  Local state directory: C:\ProgramData\icinga2\var

Internal paths:
  Package data directory: C:\Program Files\ICINGA2\\share\icinga2
  State path: C:\ProgramData\icinga2\var\lib\icinga2/icinga2.state
  Modified attributes path: C:\ProgramData\icinga2\var\lib\icinga2/modified-attributes.conf
  Objects path: C:\ProgramData\icinga2\var\cache\icinga2/icinga2.debug
  Vars path: C:\ProgramData\icinga2\var\cache\icinga2/icinga2.vars
  PID path: C:\ProgramData\icinga2\var\run\icinga2/icinga2.pid

* Operating System and version:
Microsoft Windows Server 2016 (OS Build 14393.3326)

* Enabled features (`icinga2 feature list`):
Enabled features: api checker mainlog

* Config validation (`icinga2 daemon -C`):
No errors

**Comment by dnsmichi** [comment]
That's not supported by this plugin. Also, we won't be adding new features to the existing plugins provided with the msi installer. Instead, we recommend to use the Icinga for windows framework in the future - you can test the RC2 already: https://icinga.com/2019/12/16/icinga-for-windows-rc2-available/

**Comment by Al2Klimov** [comment]
@dnsmichi So this is a won't-fix?

**Comment by Al2Klimov** [comment]
@N-o-X So this is a won't-fix?
