### ISSUE TITLE
Icinga client has critical/Application: Error: boost::thread_resource_error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by Mocem1** [Icinga/icinga2#7723]
## Describe the bug

The Icinga2 client has a critical error once it is started. The rest of all our client work fine. 

Here below can you find additional information. If more is needed please let me know. 

Thanks in advance,

Marco

## Your Environment + crash report

[root@psa02 ~]# icinga2 daemon -C
[2019-12-20 10:37:34 +0000] information/cli: Icinga application loader (version: 2.11.2-1)
[2019-12-20 10:37:34 +0000] information/cli: Loading configuration file(s).
[2019-12-20 10:37:34 +0000] information/ConfigItem: Committing config item(s).
[2019-12-20 10:37:34 +0000] critical/Application: Error: boost::thread_resource_error: Resource temporarily unavailable

Additional information is available in '/var/log/icinga2/crash/report.1576838254.703295'

Aborted
[root@server ~]# cat /var/log/icinga2/crash/report.1576838254.703295
Caught unhandled exception.
Current time: 2019-12-20 10:37:34 +0000

  Application version: 2.11.2-1

System information:
  Platform: CloudLinux
  Platform version: 7.7 (Valery Bykovsky)
  Kernel: Linux
  Kernel version: 3.10.0-962.3.2.lve1.5.27.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Error: boost::thread_resource_error: Resource temporarily unavailable

	(0) icinga2: icinga::WorkQueue::EnqueueUnlocked(boost::unique_lock<boost::mutex>&, std::function<void ()>&&, icinga::WorkQueuePriority) (+0xbb4) [0xbcf264]
	(1) icinga2: icinga::ConfigItem::CommitNewItems(boost::intrusive_ptr<icinga::ActivationContext> const&, icinga::WorkQueue&, std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> > >&) (+0x8b1) [0x956861]
	(2) icinga2: icinga::ConfigItem::CommitItems(boost::intrusive_ptr<icinga::ActivationContext> const&, icinga::WorkQueue&, std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> > >&, bool) (+0xb0) [0x947730]
	(3) icinga2: icinga::DaemonUtility::LoadConfigFiles(std::vector<std::string, std::allocator<std::string> > const&, std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> > >&, icinga::String const&, icinga::String const&) (+0x126) [0xb24386]
	(4) icinga2: icinga::DaemonCommand::Run(boost::program_options::variables_map const&, std::vector<std::string, std::allocator<std::string> > const&) const (+0x288) [0xb25a68]
	(5) /usr/lib64/icinga2/sbin/icinga2() [0xb308c3]
	(6) icinga2: main (+0xb8) [0x5fff58]
	(7) libc.so.6: __libc_start_main (+0xf5) [0x7f715db89505]
	(8) /usr/lib64/icinga2/sbin/icinga2() [0x602a13]

***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***
[root@server ~]# rpm -qa boost*
boost169-regex-1.69.0-2.el7.x86_64
boost169-thread-1.69.0-2.el7.x86_64
boost169-program-options-1.69.0-2.el7.x86_64
boost169-coroutine-1.69.0-2.el7.x86_64
boost169-filesystem-1.69.0-2.el7.x86_64
boost169-chrono-1.69.0-2.el7.x86_64
boost169-context-1.69.0-2.el7.x86_64
boost169-system-1.69.0-2.el7.x86_64
boost169-date-time-1.69.0-2.el7.x86_64

**Comment by dnsmichi** [comment]
Whenever threads cannot be created, this means that the system does not have any resources available for doing so. We do have an open issue to catch the error, but the underlaying problem can only be fixed by verifying that the system itself is healthy and has enough resources available. In order to resolve the problem, please check the available CPUs assigned and that no other applications decrease performance here. Might also be the case that you're deploying 100k objects on a single vCPU.

**Comment by Mocem1** [comment]
Thanks for your reply. 

We found the issue. LVE limitations were applied. After removing those it started to work.

Have a good weekend.

Marco
