### ISSUE TITLE
OpenTSDB / connection lost is permanent

### ISSUE THREAD

**Issue by handfreezer** [Icinga/icinga2#7729]
on the master of icinga2, using the perfmodule for OpenTSDB configured correctly, If I do:

1. stop opentsdb server (tsdb)
2. start icinga2
3. leave some check happened => in icinga2 log, there are error message with failure on writing perfdata to opentsdb object
4. start opentsdb (tsdb)
5. error message steal present => opentsdb perfdata do not try to reconnect

Note that hbase is on localfilesystem/tsdb is on localhost : if starting hbase, then opentsdb, then icinga2 : everything is fine.

=> What I guess is that Opentsdb perfdata module do not try to reconnect?

**Comment by dnsmichi** [comment]
The feature has a reconnect timer in the 10s interval. Are you sure that the feature is not paused, e.g. actively running on the Icinga instance? When you are using a HA cluster, it may actually run on the secondary node.

I'm curious about the log file itself, please share it. Also, enable the debug log where lines like `Reconnect to OpenTSDB TSD on host` will occur.

Cheers,
Michael

**Comment by handfreezer** [comment]
Hello,

   First thanks for your interest, and:

1. may I send you log throw private messages as, event if I tried to clean log with private business keyword, I can leave the log public,
2. note : in the last try, vent after 2 minutes, no new try,
3. I'm not in a HA mode deployment for the moment
4. by log file, I guess that starting with command line "icinga2 daemon" and output will be fine?
5. you lost me on "enable debug log where line like.... will occur" : I don't know how to do this. 

Best regards

**Comment by dnsmichi** [comment]
Here's the troubleshooting entry for the debug logs: https://icinga.com/docs/icinga2/latest/doc/15-troubleshooting/#enable-debug-output-on-linuxunix

I don't have access to nextcloud atm, can try so next week. Til then, please check the occurrence for the string above first.

**Comment by handfreezer** [comment]
What I did:

1. stop opentsdb and hbase on local filesystem
2. stop icniga2
3. start icinga2 with "icinga2 daemon -x notice|grep -i opentsdb"

in attached file, the result : no try of reconnection in more than 15minutes.

Here the conf of my perfdata about opentsdb:

> /**
>  * The OpenTsdbWriter type writes check result metrics and
>  * performance data to a OpenTSDB tcp socket.
>  */
> 
> object OpenTsdbWriter "opentsdbLocal" {
>   host = "127.0.0.1"
>   port = 4242
> }
> 

```


[debuglog_icinga2_opentsdb.zip](https://github.com/Icinga/icinga2/files/4079026/debuglog_icinga2_opentsdb.zip)

**Comment by dnsmichi** [comment]
efd4e8ad40 for Graphite and 0466316019 for TSDB don't return early in case of broken connections.

You only need to apply these lines, I'll add a full PR later.

```
@@ -129,9 +131,16 @@ void OpenTsdbWriter::ReconnectTimerHandler()
        } catch (const std::exception& ex) {
                Log(LogWarning, "OpenTsdbWriter")
                        << "Can't connect to OpenTSDB on host '" << GetHost() << "' port '" << GetPort() << ".'";
+
+               SetConnected(false);
+
+               return;
        }
```
