### ISSUE TITLE
ApiEvents::CheckResultHandler & ApiEvents::StateChangeHandler: Add in downtime and is acknowledged info

### ISSUE THREAD

**Issue by froehl** [Icinga/icinga2#7735]
## Is your feature request related to a problem? Please describe.

The api events streams eg.

- ...:5665/v1/events?queue=debugchecks&types=CheckResult

- ...5665/v1/events?queue=debugchecks&types=StateChange 

should contain additional information about downtime and acknowledgement of the checkable object.

## Describe the solution you'd like

Add IsInDowntime() and IsAcknowledged() to the vars_after dict in func Checkable::ProcessCheckResult.

## Describe alternatives you've considered

Add new Attributes (in_downtime and is_acknowledged) to class CheckResult. And set them in Checkable::ProcessCheckResult.

**Comment by dnsmichi** [comment]
`vars_after` and `vars_before` are internal core [attributes](https://icinga.com/docs/icinga2/latest/doc/08-advanced-topics/#checkresult). 

If `in_downtime` and `is_acknowledged` should be exposed via API event streams, we should add them as dedicated attributes into the event types and document them accordingly for the user API.

Also, downtime/ack calculation happens on each node on its own, the attributes from a CR shouldn't have an influence or provide false positives e.g. when synced from a satellite to master instance. Satellite has no downtime, master has one - which CR and attribute is now relevant? I wouldn't want to go that route.

**Comment by froehl** [comment]
@dnsmichi 
Would it be ok to add the two attributes in the class CheckResult as new independent ones? Then I change the PR.

**Comment by dnsmichi** [comment]
The memory footprint of the CheckResult class should be as minimal as possible, since it is used everywhere. Neither should it duplicate information already there, e.g. with the Checkable object owning the reference.

As said, I'd add these attributes into the API event stream scope within

- ApiEvents::CheckResultHandler
- ApiEvents::StateChangeHandler

**Comment by froehl** [comment]
@Al2Klimov Is there any chance of that going into 2.12?

**Comment by Al2Klimov** [comment]
No, unfortunately we have freezed it.

**Comment by Al2Klimov** [comment]
PS: Please keep yourself assigned.
