### ISSUE TITLE
icinga2 segfault

### ISSUE THREAD

**Issue by mzac** [Icinga/icinga2#7754]
## Describe the bug

At 5:15am this morning my Icinga2 instance crashed with a segfault.  All other monitoring of my server seem normal.

Kernel message
```
[451598.966449] show_signal_msg: 7 callbacks suppressed
[451598.966460] icinga2[9052]: segfault at 0 ip 0000000000000000 sp 00007f672ddf0eb8 error 14 in icinga2[55b55f9d2000+a71000]
```

icinga2.log
```
[2020-01-14 05:13:21 -0500] information/WorkQueue: #6 (ApiListener, RelayQueue) items: 0, rate: 12.8333/s (770/min 3825/5min 11477/15min);
[2020-01-14 05:13:31 -0500] information/WorkQueue: #8 (IdoMysqlConnection, ido-mysql) items: 0, rate: 14.1/s (846/min 4163/5min 54454/15min);
[2020-01-14 05:13:41 -0500] information/WorkQueue: #5 (InfluxdbWriter, influxdb) items: 0, rate: 4.38333/s (263/min 1303/5min 3911/15min);
[2020-01-14 05:13:51 -0500] information/WorkQueue: #8 (IdoMysqlConnection, ido-mysql) items: 16, rate: 13.4833/s (809/min 4144/5min 54406/15min);
[2020-01-14 05:13:57 -0500] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
[2020-01-14 05:14:11 -0500] information/WorkQueue: #7 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2020-01-14 05:14:31 -0500] information/WorkQueue: #8 (IdoMysqlConnection, ido-mysql) items: 84, rate: 12.15/s (729/min 4057/5min 54367/15min);
```

/var/log/syslog
```
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Main process exited, code=exited, status=139/n/a
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Killing process 17701 (check_ping) with signal SIGKILL.
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Killing process 17702 (ping) with signal SIGKILL.
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Killing process 17729 (check_ping) with signal SIGKILL.
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Killing process 17730 (ping) with signal SIGKILL.
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Killing process 17768 (check_ping) with signal SIGKILL.
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Killing process 17769 (ping) with signal SIGKILL.
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Killing process 17773 (check_ping) with signal SIGKILL.
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Killing process 17774 (ping) with signal SIGKILL.
Jan 14 05:15:21 mon1 kernel: [451598.966460] icinga2[9052]: segfault at 0 ip 0000000000000000 sp 00007f672ddf0eb8 error 14 in icinga2[55b55f9d2000+a71000]
Jan 14 05:15:21 mon1 systemd[1]: icinga2.service: Failed with result 'exit-code'.
```

## To Reproduce
Not able to reproduce as it crashed on its own

## Expected behavior
Icinga2 should not crash under normal operation

## Screenshots
N/A

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.11.2-1
* Operating System and version: Ubuntu 18.04.3 LTS
* Enabled features (`icinga2 feature list`): api checker command ido-mysql influxdb mainlog notification statusdata
* Icinga Web 2 version and modules (System - About): 2.7.3
* Config validation (`icinga2 daemon -C`): No errors
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context

I was unable to find any other logs or core files that would indicate the cause of the segfault

**Comment by dnsmichi** [comment]
Hi @mzac - this could be related to #7532 with only the JSON parts. The snapshot packages contain fixes to mitigate the behaviour. Can you please [test](https://icinga.com/docs/icinga2/latest/doc/21-development/#snapshot-packages-nightly-builds) them at the instance?

**Comment by mzac** [comment]
Thanks @dnsmichi I updated to **v2.11.2-463-gcb21086d6** so I'll keep an eye on my system to see if it crashes again.  Thanks for the quick response!

**Comment by PedroMSantosD** [comment]
Hi, I have the segfault present on 2.11.3, raised to [IcingaPortal](https://community.icinga.com/t/icinga2-2-11-3-segfault-libstdc-so-6-0-19-7f2b96f62000-e9000/4284) .

Any updates?

**Comment by harisspa** [comment]
Icinga2 version - 2.11.3-1

May 24 09:31:21 agmaster-icinga-1a kernel: icinga2[531]: segfault at 48 ip 000000000062a617 sp 00007fbd824b2990 error 4 in icinga2[400000+a0c000]

We are stuck with this error for almost a week now. Don't see any errors when restarting Icinga2. Only when we check the status of Icinga2 and other logs we see this.

**Comment by harisspa** [comment]
Icinga2 version - 2.11.3-1

May 24 09:31:21 master-icinga-1a kernel: icinga2[531]: segfault at 48 ip 000000000062a617 sp 00007fbd824b2990 error 4 in icinga2[400000+a0c000]

We are stuck with this error for almost a week now. Don't see any errors when restarting Icinga2. Only when we check the status of Icinga2 and other logs we see this.

**Comment by lippserd** [comment]
Hi @PedroMSantosD,

Could you please test the following packages: https://git.icinga.com/packaging/rpm-icinga2/-/jobs/52339. Those are snapshots from our upcoming  2.11.4 release.

Also, please make sure to enable core dumps: https://icinga.com/docs/icinga2/latest/doc/21-development/#core-dump.

All the best,
Eric

**Comment by harisspa** [comment]
@PedroMSantosD , 

[2020-05-28 16:55:43 +0000] information/ConfigObject: Restoring program state from file '/var/lib/icinga2/icinga2.state'

this file was not updated for a week and Icinga2 was still referring this when starting. Emptied this file and restarted, my issue got fixed.

You may run `icinga2 daemon -x debug` and look at all files being referenced and see if any particular file is corrupted

**Comment by Al2Klimov** [comment]
All quiet on the western front = all good on the western front.
