### ISSUE TITLE
Error: Function call 'rename' for file '/var/spool/icinga2/tmp/service-perfdata' failed with error code 2, 'No such file or directory'

### ISSUE THREAD

**Issue by dazed51** [Icinga/icinga2#7763]
Ran into this issue on icinga2 2.10.5-1.stretch, debian 9

critical/Application: Error: Function call 'rename' for file '/var/spool/icinga2/tmp/service-perfdata' failed with error code 2, 'No such file or directory'

Ran the suggested fix and worked. Have not had an issue with restarting services since I last had to restart them prior to the last patch of the application.

**Comment by dnsmichi** [comment]
https://github.com/Icinga/icinga2/issues/4221#issuecomment-575314476
