### ISSUE TITLE
scheduled downtime are not applied and are not showed in icingaweb2 master zone

### ISSUE THREAD

**Issue by Matteo291291** [Icinga/icinga2#7772]
We have 2 master nodes in master zone and 1 satellite node in satellite zones, the masters monitors the principal site and the satellite (with some agents) monitors a secondary site situated in another location. Master1-2 point to galera mysql cluster, satellite have a locally mysql installed. In the satellite dashboard are showed only satellite's host monitored, in masters dashboard are showed master's hosts and satellite's hosts monitored.The checks works fine but we have problems with ScheduledDowntimes: downtimes are applied and showed only on satellite zone.
Below the config files
Master1 and Master2 (SRVMSTR01-02) --> /etc/icinga2/zones.conf:
object Endpoint "SRVMSTR01" {
	host = "ip of master1"
}
object Endpoint "SRVMSTR02" {
	host = "ip of master2"
}
object Endpoint "SRVSTLT" {
}
object Zone "master" {
	endpoints = [ "SRVMSTR01","SRVMSTR02" ]
}
object Zone "global-templates" {
	global = true
}
object Zone "director-global" {
	global = true
}
object Zone "global-commands" {
	global = true
}
object Zone "satellitezone" {
        endpoints = [ "SRVSTLT*****" ]
	parent = "master"
}

Satellite (SRVSTLT) --> /etc/icinga2/zones.conf:
object Endpoint "SRVMSTR01" {
	host = "ip of master1"
	port = "5665"
}
object Endpoint "SRVMSTR02" {
        host = "ip of master2"
        port = "5665"
}
object Zone "master" {
	endpoints = [ "SRVMSTR01","SRVMSTR02" ]
}
object Endpoint "SRVSTLT" {
}
object Zone "satellitezone" {
	endpoints = [ "SRVSTLT" ]
	parent = "master"
}
object Zone "global-templates" {
	global = true
}
object Zone "director-global" {
	global = true
}
object Zone "global-commands" {
        global = true
}

SRVMSTR01 api.conf--> /etc/icinga2/features-enabled/api.conf
object ApiListener "api" {
  accept_config = true
  accept_commands = true
  ticket_salt = TicketSalt
}
SRVMSTR02 api.conf--> /etc/icinga2/features-enabled/api.conf
object ApiListener "api" {
  accept_config = true
  accept_commands = true
}

SRVSTLT api.conf--> /etc/icinga2/features-enabled/api.conf
object ApiListener "api" {
  cert_path = "/var/lib/icinga2/certs/" + NodeName + ".crt"
  key_path = "/var/lib/icinga2/certs/" + NodeName + ".key"
  ca_path = "/var/lib/icinga2/certs/ca.crt"
  accept_config = true
  accept_commands = true
}

We use ScheduledDowntime apply rules to downtime host: /etc/icinga2/zones.d/master/downtimes.conf

apply ScheduledDowntime "backup-downtime2" to Host {
  author = "icingaadmin"
  comment = "Scheduled downtime for backup"
  ranges = {
    monday = "22:15-24:00"
    tuesday = "22:15-24:00"
    wednesday = "22:15-24:00"
    thursday = "22:15-24:00"
    friday = "22:15-24:00"
    saturday = "22:15-24:00"
    sunday = "22:15-24:00"
  }
 assign where host.zone == "master" && assign where host.vars.hosttype == "Veeam"  
}
in satellite zone:
/etc/icinga2/zones.d/satellitezone/downtimes.conf

apply ScheduledDowntime "satellitebackup-downtime2" to Host {
  author = "icingaadmin"
  comment = "Scheduled downtime for backup"
  ranges = {
    monday = "22:15-03:00"
    tuesday = "22:15-03:00"
    wednesday = "22:15-03:00"
    thursday = "22:15-03:00"
    friday = "22:15-03:00"
    saturday = "22:15-03:00"
    sunday = "22:15-03:00"
  }
  assign where host.zone == "satellitezone" && assign where host.name == "agent01***"
}

If run object list ScheduledDowntime, i can see the Downtimes but are not applyed:

from SRVMSTR01--> icinga2 object list --type ScheduledDowntime
Object 'agent01***!backup-downtime2'** of type 'ScheduledDowntime':
  % declared in '/etc/icinga2/zones.d/master/downtimes.conf', lines 1:0-1:49
  * __name = "agent01***!backup-downtime2"
  * author = "icingaadmin"
    % = modified in '/etc/icinga2/zones.d/master/downtimes.conf', lines 2:3-2:24
  * child_options = "DowntimeNoChildren"
  * comment = "Scheduled downtime for backup"
    % = modified in '/etc/icinga2/zones.d/master/downtimes.conf', lines 3:3-3:43
  * duration = 0
  * fixed = true
  * host_name = "agent01***"
    % = modified in '/etc/icinga2/zones.d/master/downtimes.conf', lines 1:0-1:49
  * name = "backup-downtime2"
  * package = "_etc"
    % = modified in '/etc/icinga2/zones.d/master/downtimes.conf', lines 1:0-1:49
  * ranges
    % = modified in '/etc/icinga2/zones.d/master/downtimes.conf', lines 5:3-13:3
    * friday = "22:15-24:00"
    * monday = "22:15-24:00"
    * saturday = "22:15-24:00"
    * sunday = "22:15-24:00"
    * thursday = "22:15-24:00"
    * tuesday = "22:15-24:00"
    * wednesday = "22:15-24:00"
  * service_name = ""
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 49
    * last_line = 1
    * path = "/etc/icinga2/zones.d/master/downtimes.conf"
  * templates = [ "backup-downtime2" ]
    % = modified in '/etc/icinga2/zones.d/master/downtimes.conf', lines 1:0-1:49
  * type = "ScheduledDowntime"
  * vars = null
  * zone = "master"
    % = modified in '/etc/icinga2/zones.d/master/downtimes.conf', lines 1:0-1:49

from SRVMSTR02:
Object 'agent01***!backup-downtime2' of type 'ScheduledDowntime':
  % declared in '/var/lib/icinga2/api/zones/master/_etc/downtimes.conf', lines 1:0-1:49
  * __name = "agent01***!backup-downtime2"
  * author = "icingaadmin"
    % = modified in '/var/lib/icinga2/api/zones/master/_etc/downtimes.conf', lines 2:3-2:24
  * child_options = "DowntimeNoChildren"
  * comment = "Scheduled downtime for backup"
    % = modified in '/var/lib/icinga2/api/zones/master/_etc/downtimes.conf', lines 3:3-3:43
  * duration = 0
  * fixed = true
  * host_name = "agent01***"
    % = modified in '/var/lib/icinga2/api/zones/master/_etc/downtimes.conf', lines 1:0-1:49
  * name = "backup-downtime2"
  * package = "_cluster"
    % = modified in '/var/lib/icinga2/api/zones/master/_etc/downtimes.conf', lines 1:0-1:49
  * ranges
    % = modified in '/var/lib/icinga2/api/zones/master/_etc/downtimes.conf', lines 5:3-13:3
    * friday = "22:15-24:00"
    * monday = "22:15-24:00"
    * saturday = "22:15-24:00"
    * sunday = "22:15-24:00"
    * thursday = "22:15-24:00"
    * tuesday = "22:15-24:00"
    * wednesday = "22:15-24:00"
  * service_name = ""
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 49
    * last_line = 1
    * path = "/var/lib/icinga2/api/zones/master/_etc/downtimes.conf"
  * templates = [ "backup-downtime2" ]
    % = modified in '/var/lib/icinga2/api/zones/master/_etc/downtimes.conf', lines 1:0-1:49
  * type = "ScheduledDowntime"
  * vars = null
  * zone = "master"
    % = modified in '/var/lib/icinga2/api/zones/master/_etc/downtimes.conf', lines 1:0-1:49
## Expected Behavior
Downtimes are applied to Hosts in master zone and showed on icingaweb2 dashboard 

## Current Behavior
Downtimes are not showed and not applied in master zone but in satellitezone yes

## Your Environment

* Version used (`icinga2 --version`): version: 2.11.2-1

* Operating System and version: CentOS 7 (Core) 3.10.0-1062.4.3.el7.x86_64

* Enabled features (`icinga2 feature list`):Disabled features: command compatlog debuglog elasticsearch gelf graphite livestatus opentsdb statusdata syslog
Enabled features: api checker ido-mysql influxdb mainlog notification perfdata

* Icinga Web 2 version and modules (System - About):Icinga Web 2 Version 2.7.3
* Config validation (`icinga2 daemon -C`):
[2020-01-22 01:43:12 +0100] information/cli: Icinga application loader (version: 2.11.2-1)
[2020-01-22 01:43:12 +0100] information/cli: Loading configuration file(s).
[2020-01-22 01:43:12 +0100] information/ConfigItem: Committing config item(s).
[2020-01-22 01:43:12 +0100] information/ApiListener: My API identity: SRVMSTR01
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 1 InfluxdbWriter.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 6 ScheduledDowntimes.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 4 NotificationCommands.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 4068 Notifications.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 18 HostGroups.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 203 Hosts.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 5 Downtimes.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 1 PerfdataWriter.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 12 Zones.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 10 Endpoints.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 2 ApiUsers.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 2 UserGroups.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 258 CheckCommands.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 8 Users.
[2020-01-22 01:43:13 +0100] information/ConfigItem: Instantiated 1914 Services.
[2020-01-22 01:43:13 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-01-22 01:43:13 +0100] information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

I'm new in forum and Icinga2, sorry if I made trivial configuration errors.
Thanks for your help!

**Comment by Matteo291291** [comment]
Also creating Downtime with API doesn't work:
curl -k -s -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/actions/schedule-downtime' -d '{ "type": "Service", "filter": "host.name==\"HOSTNAME\" && service.name==\"SERVICENAME\"", "start_time": 1579687802, "end_time": 1579687922, "duration": 1000, "author": "icingaadmin", "comment": "IPv4 network maintenance", "pretty": true }'

**Comment by dnsmichi** [comment]
Please continue over at https://community.icinga.com/t/downtime-problem/3258 where you've already created a new topic. This issue tracker is solely for bugs and feature requests.
