### ISSUE TITLE
Introduce new column `last_check` for the IcingaDB redis writer

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga2#7784]
`last_update` is used to display when a host/service has been last checked. Since IcingaDB this column is updated on every row update which will then be out of sync with  the real time when the last check was made. Please introduce a new column `last_check` which represents exactly this case.

**Comment by dnsmichi** [comment]
@N-o-X I've created a PR, the getter was already in place.

**Comment by N-o-X** [comment]
We've decided that we don't want to introduce a new column called `last_check`, but to change the value of `last_update` to the value of `last_check`.
