### ISSUE TITLE
Service not overdue nor late with active checks disabled

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga2#7790]
## Describe the bug

Disabled active checks for a single service. Wondered why it didn't get overdue and why the next check wasn't in the past. (i.e. late)

## Expected behavior

The service check should have gone overdue and the next check shouldn't (probably?) be calculated again without a new check result coming in.

**Comment by dnsmichi** [comment]
Solves two purposes:

- If the check is enabled at a later time, e.g. via Web feature action, the correct interval as configured applies
- Freshness checks for passive checks must be intact

That being said, removing this will break the check logic. Once an event happens in the future (checks, notifications, etc.) there are filters to determine whether it is valid at this point of time. There is no forecast possibility as web would require it to display. The whole active/passive check logic needs a redesign but that never happen in the past 7 years.

**Comment by Al2Klimov** [comment]
1. What exactly for?
2. But not for the ones w/o active checks enabled, right?
