### ISSUE TITLE
Rescheduling a check while active checks are disabled also works for non-forced actions

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga2#7797]
## Describe the bug

Disabling a host/service and then rescheduling the next check without passing `force:true` still causes the check getting rescheduled.

This differs from what the tooltip in Icinga Web 2 says and from what is written in the documentation.

## To Reproduce

1. Disable active checks for a host/service
2. Reschdule the next check for this host/service with `force:false`
3. Note that the next check is rescheduled anyway

## Expected behavior

The next check is not rescheduled.

## Your Environment

* Version used (`icinga2 --version`): bugfix/icingadb-fix-last-update
* Icinga Web 2 version and modules (System - About): master

**Comment by dnsmichi** [comment]
Partially explained [here](https://github.com/Icinga/icinga2/issues/7790#issuecomment-580628596) and subject to [Re-design passive checks and freshness](https://github.com/Icinga/icinga2/issues/1951), a long running design task. @lippserd needs to decide upon this as this will include a major rewrite in this component.

**Comment by Al2Klimov** [comment]
_PING_ @lippserd

**Comment by lippserd** [comment]
The docs and tooltips are correct:

> If enabled, the checks are **executed** regardless of time period restrictions and checks being disabled per object or on a global basis.

If active checks are disabled and force is false, Icinga simply sets the next check timestamp, which it also does when the check interval has elapsed.
