### ISSUE TITLE
Release notes for 2.11.3 missing

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icinga2#7877]
hi,
Just installed 2.11.3 on centos6, but was unable to find the release notes.

https://icinga.com/category/releases/
https://github.com/Icinga/icinga2/releases

Commits: 
67fc68b..911c14f

**Comment by N-o-X** [comment]
Hi @mphilipps, 2.11.3 wasn't officially released at that point. Everything should be there now :)

**Comment by dnsmichi** [comment]
The changelog update is missing, same goes for the VERSION file.
https://github.com/Icinga/icinga2/blob/master/RELEASE.md

- https://github.com/Icinga/icinga2/blob/support/2.11/CHANGELOG.md
- https://github.com/Icinga/icinga2/blob/support/2.11/VERSION

**Comment by Al2Klimov** [comment]
💩 happens.
