### ISSUE TITLE
Acknowledgement date, notes and user are not visible on dashboard

### ISSUE THREAD

**Issue by geotekberlin** [Icinga/icinga2#7882]
## Expected Behavior
When a host or service alert is acknowledged, it should be seen by everyone including the ack date, the user who made it and the comment that was given

## Current Behavior
Notification date/notes/user can only be seen by the user who acknowledged it. For all other acknowledgements, only the blue X is visible that allows to remove the acknowledgement.

In event history all ack infos are correctly shown for all users, they are only missing on the main device / service dashboard

## Context
Notification info is essential for collaboration between users using Icinga, it must not be hidden

## Your Environment

* Icinga Web 2.4.2
* Icinga2 2.7.1
* OS: OpenSuse 42.3
* Enabled features: api checker command ido-mysql livestatus mainlog notification perfdata
* Config validation: OK

## This is how an Ack from someone else looks like:
![bestatigung](https://user-images.githubusercontent.com/15341250/31018147-516b5c64-a52b-11e7-9805-9e46a0946411.jpg)

**Comment by nilmerg** [comment]
Moved this here because this is obviously an Icinga 2 problem. Though, didn't reproduced it under real circumstances. So further inspection is required.
