### ISSUE TITLE
Don't wait for checks on reload

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#7888]
## Describe the bug

Our reload is being slowed down by the running checks.

## To Reproduce

https://github.com/Icinga/icinga2/blob/cef4c46ba8399cf2cf944271c7da21c5a66f3868/lib/checker/checkercomponent.cpp#L79

## Expected behavior

Let's don't wait for them.

## Additional context

We (1) update next_check and (2) start the process. If we (3) just reload, we lose the check result. To avoid this, we could add a new internal attribute last_check_started and set it to now just before updating next_check. In the new main process on `Checkable#Start()` if we discover that last_check_started > last check result, we set next_check to last_check_started.

@N-o-X What's your opinion?

**Comment by Al2Klimov** [comment]
ref/IP/19695

**Comment by N-o-X** [comment]
I like your concept. Let's discuss this after 2.12.
