### ISSUE TITLE
more meaningful program_version in livestatus

### ISSUE THREAD

**Issue by chrnie** [Icinga/icinga2#7895]
## Livestatus statustable
Since the different live status implementations are drifting apart more and more, it is necessary to be able to distinguish between them on the client side.

## Solution 
Change the **program_version** field in the status table from **2.11.2-2** to **2.11.2-2-icinga2**. 

https://github.com/Icinga/icinga2/blob/master/lib/livestatus/statustable.cpp#L73

## Impact
Since existing live status backends like neamon or shinken already use the field in the same way, no bad effects on existing apps are expected.

## Refers to:
https://github.com/sni/lmd/issues/92
https://github.com/sni/lmd/issues/95

**Comment by Al2Klimov** [comment]
@lippserd Do we even still maintain Livestatus?

**Comment by lippserd** [comment]
> @lippserd Do we even still maintain Livestatus?

This a quick win for all and should be implemented asap.
