### ISSUE TITLE
Installation instructions for Ubutnu incorrect

### ISSUE THREAD

**Issue by riban-bw** [Icinga/icinga2#7934]
## Describe the bug

Following the installation instructions for Ubuntu do not work. Some changes are required to progress through the installation.

## To Reproduce

1. Follow the instructions for installing icinga2, icingaweb2 and icingadb at https://icinga.com/docs/icinga2/latest/doc/02-installation

## Expected behaviour

icinga2 and icingaweb2 are installed.

## Actual behaviour

Installation fails.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.12.0-rc1-1
* Operating System and version: Ubuntu 18.04.4 64-bit

## Additional context

List of command run, issues experienced and solutions where known:

```
sudo su
apt-get update
apt-get -y install apt-transport-https wget gnupg
wget -O - https://packages.icinga.com/icinga.key | apt-key add -
. /etc/os-release; if [ ! -z ${UBUNTU_CODENAME+x} ]; then DIST="${UBUNTU_CODENAME}"; else DIST="$(lsb_release -c| awk '{print $2}')"; fi; \
 echo "deb https://packages.icinga.com/ubuntu icinga-${DIST} main" > \
 /etc/apt/sources.list.d/${DIST}-icinga.list
 echo "deb-src https://packages.icinga.com/ubuntu icinga-${DIST} main" >> \
 /etc/apt/sources.list.d/${DIST}-icinga.list
apt-get update
apt-get install icinga2
apt-get install monitoring-plugins
systemctl status icinga2
apt-get install vim-icinga2 vim-addon-manager
vim-addon-manager -w install icinga2
. /etc/os-release; if [ ! -z ${UBUNTU_CODENAME+x} ]; then DIST="${UBUNTU_CODENAME}"; else DIST="$(lsb_release -c| awk '{print $2}')"; fi; \
 echo "deb https://packages.icinga.com/ubuntu icinga-${DIST}-testing main" > \
 /etc/apt/sources.list.d/${DIST}-icinga-testing.list
 echo "deb-src https://packages.icinga.com/ubuntu icinga-${DIST}-testing main" >> \
 /etc/apt/sources.list.d/${DIST}-icinga-testing.list
apt-get update
apt-get install icingadb
apt-get install icingadb-redis
apt-get install mysql-server mysql-client
mysql_secure_installation
mysql -u root -p
	CREATE DATABASE icingadb;
	GRANT ALL ON icingadb.* TO 'icingadb'@'localhost' IDENTIFIED BY 'icingadb';
		Query OK, 0 rows affected, 1 warning (0.01 sec)
	quit
```
Ubuntu does not allow access for user when configured with 127.0.0.1. It needs localhost.

**Installation instruction must be updated.**
```
cat /usr/share/icingadb/schema/mysql/mysql.schema.sql | mysql -uroot icingadb
systemctl start icingadb
icinga2 feature enable icingadb
```
Error occurs here:
```
	critical/cli: Cannot enable feature 'icingadb'. Source file '/etc/icinga2/features-available/icingadb.conf' does not exist.
	critical/cli: Cannot enable feature(s): icingadb
```
*** Solution to above issue is to reinstall icinga2 (https://github.com/Icinga/icinga2/issues/7932)

**Installation instruction must be updated.**
```
apt-get install icinga2
icinga2 feature enable icingadb
systemctl restart icinga2
apt-get install apache2
icinga2 api setup
vim /etc/icinga2/conf.d/api-users.conf
	object ApiUser "icingaweb2" {
		password = "Wijsn8Z9eRs5E25d"
		permissions = [ "status/query", "actions/*", "objects/modify/*", "objects/query/*" ]
	}
systemctl restart icinga2
apt-get install icingaweb2 libapache2-mod-php icingacli
icingacli setup token create
```
Within web browser, navigate to: http://localhost/icingaweb2/setup and follow instructions.

At stage: *Monitoring Backend* we are offered "Backend Type" of IDO only. There is no option to select icingadb. 
Subsequent stage: "Monitoring IDO Resource" fails with error: "Cannot find the IDO schema. Please verify that the given database contains the schema and that the configured user has access to it."

**Skip Validation to progress past this stage.**

Upon completion and log in to web interface, presented with errors:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'icingadb.icinga_dbversion' doesn't exist, query was: SELECT icinga_dbversion.version FROM icinga_dbversion" with error content:
```
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(String, Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(1455): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#5 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/ProgramstatusQuery.php(58): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->getIdoVersion()
#6 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(937): Icinga\Module\Monitoring\Backend\Ido\Query\ProgramstatusQuery->joinBaseTables()
#7 /usr/share/php/Icinga/Data/SimpleQuery.php(129): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->init()
#8 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(300): Icinga\Data\SimpleQuery->__construct(Object(Icinga\Data\Db\DbConnection), Array)
#9 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(53): Icinga\Module\Monitoring\Backend\MonitoringBackend->query(String, Array)
#10 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(255): Icinga\Module\Monitoring\DataView\DataView->__construct(Object(Icinga\Module\Monitoring\Backend\Ido\IdoBackend), Array)
#11 /usr/share/icingaweb2/modules/monitoring/application/controllers/HealthController.php(64): Icinga\Module\Monitoring\Backend\MonitoringBackend->from(String, Array)
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HealthController->infoAction()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#18 {main}
```

**Comment by riban-bw** [comment]
Further issues experienced when configuring for

**Comment by JimKlapwijk** [comment]
Would you mind letting me know how you fixed the error `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'icingadb.icinga_dbversion' doesn't exist, query was: SELECT icinga_dbversion.version FROM icinga_dbversion`.
I ran the installation as described here: https://icinga.com/docs/icinga-db/latest/doc/02-Installation/.
However I still ran into the same issue.

**Comment by N-o-X** [comment]
This issues should be fixed with the many changes we did while rewriting Icinga DB after RC1. If you still encounter those issues while testing Icinga DB, please head over to https://github.com/Icinga/icingadb and open a new issue there.

**Comment by tshpr** [comment]
Hi. I am facing the same issue on brand new installation from today.

**Comment by julianbrost** [comment]
Which error do you get (there are multiple error messages mentioned in this issue)? Please also share the versions of all components (`dpkg -l '*icinga*'`).

**Comment by tshpr** [comment]
I opened a thread on the forums and will follow up there.

https://icinga.com/docs/icinga-db/latest/doc/02-Installation/06-Ubuntu/#installing-icinga-db-package
