### ISSUE TITLE
Icinga2 API fails to remove custom vars in HA mode

### ISSUE THREAD

**Issue by junglistikal** [Icinga/icinga2#7940]
## Describe the bug

Lets say I create a service with custom "vars.a" and "vars.b". Later I decide that I do not need "vars.b" anymore and I would like to remove it. Since there are no means to remove single variables, I have to override whole "vars" object. What happens now is that Icinga2 sets correct information about custom vars in "node1.domain.com", however it does leave "vars.b" on "node2.domain.com" with a null value. It does mess up "modified-attributes.conf" file too.

## To Reproduce

1. Create a service with custom vars:
```
curl -u USERNAME:PASSWORD -k -H 'Accept: application/json' -X PUT https://node1.domain.com:5665/v1/objects/services/newhost!newservice -d '{ "attrs": { "check_command": "passive", "vars.a": "true", "vars.b": "false"} }'
```
2. Delete "vars.b" from the service:
```
curl -u USERNAME:PASSWORD -k -H 'Accept: application/json' -X POST https://node1.domain.com:5665/v1/objects/services/newhost!newservice -d '{ "attrs": { "vars": { "a": "true" } } }'
```
3. Check the service object on "node1.domain.com"
```
curl -u USERNAME:PASSWORD -k -H 'Accept: application/json' -X GET https://node1.domain.com:5665/v1/objects/services/newhost!newservice
...
"vars": {
    "a": true,
},
...

cat /var/lib/icinga2/modified-attributes.conf
...
var obj = get_object("Service", "newhost!newservice")
if (obj) {
        obj.modify_attribute("vars", {
a = "true"
})
        obj.modify_attribute("vars.a", "true")
        obj.modify_attribute("vars.b", null)
        obj.version = 1585046896.512601
}
...
```
4. Check the service object on "node2.domain.com"
```
curl -u USERNAME:PASSWORD -k -H 'Accept: application/json' -X GET https://node2.domain.com:5665/v1/objects/services/newhost!newservice
...
"vars": {
    "a": true,
    "b": null
},
...

cat /var/lib/icinga2/modified-attributes.conf
...
var obj = get_object("Service", "newhost!newservice")
if (obj) {
        obj.modify_attribute("vars", {
a = "true"
b = null
})
        obj.modify_attribute("vars.a", "true")
        obj.modify_attribute("vars.b", null)
        obj.version = 1585046896.512601
}
...
```

## Expected behavior

"vars.b" should be removed.

## Your Environment

* Version used (`icinga2 --version`): 2.11.2 (also reproducable in 2.11.3)
* Operating System and version: RHEL7.7
* Enabled features (`icinga2 feature list`): Enabled features: api checker command ido-mysql influxdb mainlog notification
* Icinga Web 2 version and modules (System - About): v2.7.3
* Config validation (`icinga2 daemon -C`): all good
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
```
object Endpoint "node1.domain.com" {
}

object Endpoint "node2.domain.com" {
  host = "node2.domain.com";
  port = "5665";
}

object Zone "master" {
  endpoints = ["node1.domain.com","node2.domain.com"];
}
```
node1 is config master, node2 mainly serves as an active node for Icingaweb2.

**Comment by Al2Klimov** [comment]
Hello @junglistikal and thank you for reporting!

Does it work as expected if you specify `vars` as whole during creation, i.e. `{"attrs":{"vars":{"a":1,"b":2}}}`?

Best,
AK

**Comment by junglistikal** [comment]
Hi @Al2Klimov ,

yes, creation with whole `{"attrs":{"vars":{"a":1,"b":2}}} ` works as expected.

**Comment by Al2Klimov** [comment]
@N-o-X Is this a reasonable workaround?

**Comment by junglistikal** [comment]
@Al2Klimov , not sure are we one the same page, so I will clarify a bit.

We always create hosts/services with `{"attrs":{"vars":{"a":1,"b":2}}}` and it works fine. The problem surfaces when we do an update afterwards, with `{"attrs":{"vars":{"a":1}}}`.

**Comment by Al2Klimov** [comment]
You create them with `{"attrs":{"vars":{"a":1,"b":2}}}`? Not `{"attrs":{"vars.a":1,"vars.b":2}}`?

**Comment by junglistikal** [comment]
Now I understood what you have actually meant. Initially I thought there's no actual difference whichever way you choose to create the hosts/services. Apparently there is... :)

So yes, you are right:

If the service was created with `{"attrs":{"vars.a":1,"vars.b":2}}` and then updated to `{"attrs":{"vars":{"a":1}}}` - `vars.b` gets set to `null`;

If the service was created with `{"attrs":{"vars":{"a":1,"b":2}}}` and then updated to `{"attrs":{"vars":{"a":1}}}` - everything works as expected.

Works both with 2.11.2 and 2.11.3.

Thanks @Al2Klimov !

**Comment by junglistikal** [comment]
However if we create a service with `{"attrs":{"vars.a":1,"vars.b":2}}`, then add another `vars.c` and later remove it with `{"vars":{"a":1}}}` - `vars.c` of course gets set to `null`;

The reason we are doing this - we are trying to get away from issues caused  by #6945

So really these is no escape for us - the only reason we wanted to delete the `vars` is to minimize the query count to MySQL database, as any update to any single `var` does a "refresh" to every other `var` assigned to that service, meaning - a whole bunch of SQL queries. The more `vars` we have on a host/service - the more we bash our MySQL server, even with a single `var` update...

**Comment by Al2Klimov** [comment]
So you can't completely switch to the create/update scheme I suggested?

**Comment by junglistikal** [comment]
Well we use Icinga API with passive checks a lot and store a bunch of information in `vars`, specifying what's going on for that particular job.

So I guess the only way we can proceed right now, is to have only a few `custom vars`, set them on creation and post all data inside them, instead of creating a new `var` every time a new piece of information comes in.

Hopefully this will keep our MySQL database server from exploding :)

**Comment by Al2Klimov** [comment]
_PING_ @N-o-X

**Comment by Al2Klimov** [comment]
Problem solved.
