### ISSUE TITLE
Scheduled Downtime & Summer/Wintertime 

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icinga2#7947]
## Describe the bug

On sunday 29.03.2020 Germany switched to summertime (+1h) which resultet in wrong calculated downtimes. Downtimes were set to time + 1h, see the history picture. All involved servers uses the same timezone and ntp server (even php is set to the correct timezone)

## To Reproduce

Create a daily scheduled downtime and and wait for summer/wintertime change.
Director created scheduled_downtime:
![grafik](https://user-images.githubusercontent.com/6574967/77882155-b528d380-7260-11ea-90b3-6303fe1d11aa.png)

## Expected behavior
Calculated downtime should be set to the time it is configured on days with timechange

## Screenshots

![grafik](https://user-images.githubusercontent.com/6574967/77881906-35026e00-7260-11ea-8e68-6469001d517b.png)

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.11.3
* Operating System and version: CentOS 7.7
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About): 2.7.3
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by MarcusCaepio** [comment]
Hey @Mikesch-mp ,
thanks for already creating the issue! I can confirm this totally and wanted to create an issue too.
Our case: Scheduled Downtime via DSL daily from 23:55 - 00:20. Scheduled was set to 00:55 - 01:20, Icinga woke me up at 00:00 because of unavailable services ^^

**Comment by Al2Klimov** [comment]
Dup of #7066
