### ISSUE TITLE
Daylight saving time and TimePeriod problem

### ISSUE THREAD

**Issue by pboguslawski** [Icinga/icinga2#7951]
Hello,

At 2020-03-29 02:00 daylight saving time 2020 in Poland began (time change from 02:00 to 03:00).

In Icinga 2 from debian stretch-backports (2.10.3-2~bpo9+1) there was a few alerts generated in period 2020-03-30 00:00 - 00:59 for checks with timeperiod that excludes this hour from checking:

```
object TimePeriod "everyday_06_24" {
    display_name = "Everyday 06:00-24:00"
    ranges = {
        "monday" = "06:00-24:00"
        "tuesday" = "06:00-24:00"
        "wednesday" = "06:00-24:00"
        "thursday" = "06:00-24:00"
        "friday" = "06:00-24:00"
        "saturday" = "06:00-24:00"
        "sunday" = "06:00-24:00"
    }
}
```

No such problem after 24h (2020-03-31 00:00-00:59).

Seems Icinga does not take time change into account when scheduling checks is scenario above.

Regards,
Paweł

**Comment by Al2Klimov** [comment]
Dup of #7066
