### ISSUE TITLE
Add info about ongoing support for IDO

### ISSUE THREAD

**Issue by theFeu** [Icinga/icinga2#7957]
Add something to the official documentation with roughly this content:
https://community.icinga.com/t/have-you-tested-v2-12rc1-v2-8rc1/3894/8

Just to reassure people that we are not going to suddenly drop the IDO completely (even though we want to deprecate it)

**Comment by Al2Klimov** [comment]
Where do you think it fits best?

**Comment by theFeu** [comment]
To be honest, I don't know the Icinga docs that amazingly well, but I would say roughly where the Icinga DB and switch to the IDO is mentioned?
https://icinga.com/docs/icinga2/latest/doc/14-features/#core-backends-icingadb

And maybe briefly around the end of this section?
https://icinga.com/docs/icinga2/latest/doc/14-features/#ido-database-db-ido
