### ISSUE TITLE
Icinga2 fails to start with kernel-3.10.0-514.21.2 RHEL7

### ISSUE THREAD

**Issue by dmitriy-terzeman** [Icinga/icinga2#7973]
## Describe the bug

Icinga2 fails to start with kernel-3.10.0-514.21.2 RHEL7, i know that you already have a related closed issue, unfortunately not for all business and users kernel update is an option ;[

Related issue: https://github.com/icinga/icinga2/issues/5367

## To Reproduce

```
# icinga2 daemon -C
execvp: Argument list too long
```

## Expected behavior

```
# icinga2 daemon -C
[2020-04-13 06:26:41 -0700] information/cli: Icinga application loader (version: 2.11.2-1)
[2020-04-13 06:26:41 -0700] information/cli: Loading configuration file(s).
[2020-04-13 06:26:41 -0700] information/ConfigItem: Committing config item(s).
[2020-04-13 06:26:42 -0700] information/ConfigItem: Instantiated 1 FileLogger.
[2020-04-13 06:26:42 -0700] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-04-13 06:26:42 -0700] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-04-13 06:26:42 -0700] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-04-13 06:26:42 -0700] information/ConfigItem: Instantiated 3 Zones.
[2020-04-13 06:26:42 -0700] information/ConfigItem: Instantiated 3 Endpoints.
[2020-04-13 06:26:42 -0700] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-04-13 06:26:42 -0700] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-04-13 06:26:42 -0700] information/cli: Finished validating the configuration file(s).
```

## Your Environment

Include as many relevant details about the environment you experienced the problem in

icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.2-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.21.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

## Hot to fix

Here is the list of options:

#

1) Add --no-stack-rlimit directly in /usr/sbin/icinga2
https://github.com/Icinga/icinga2/blob/master/icinga-app/icinga2.cmake#L29

from:
`exec $ICINGA2_BIN "$@"`
to:
`exec $ICINGA2_BIN --no-stack-rlimit "$@"`

#

2) Call `/usr/sbin/icinga2` with extra arguments variable in systemd:
https://github.com/Icinga/icinga2/blob/master/etc/initsystem/icinga2.service.cmake#L10

from:
`ExecStart=/usr/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG}`
to:
`ExecStart=/usr/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG} ${ICINGA2_EXTRA_ARGS}`

https://github.com/Icinga/icinga2/blob/master/etc/initsystem/safe-reload.cmake#L27

```
: ${ICINGA2_EXTRA_ARGS:=""}

if ! $DAEMON daemon --validate --color $ICINGA2_EXTRA_ARGS > $OUTPUTFILE; then
```

https://github.com/Icinga/icinga2/blob/master/etc/initsystem/icinga2.sysconfig.cmake
Add:
```
ICINGA2_EXTRA_ARGS="" 
```

In this way it will allow users with affected kernels overwrite variable in /etc/sysconfig/icinga2 without core files modification. Also could be useful in future releases if you will need to add additional arguments for icinga2 start

#

P.S. Would be nice to include it in 2.12 release if possible

With best regards,
Dmitriy.

**Comment by Al2Klimov** [comment]
Hello @dmitriy-terzeman and thank you for reporting!

Do I understand you correctly?

* There's a bug in your kernel preventing Icinga 2 from starting
* There's an update for your kernel fixing the bug
* You want not to update the kernel, but Icinga 2 to work around the bug

Best,
AK

**Comment by dmitriy-terzeman** [comment]
Hello @Al2Klimov , kernel upgrade is not always possible.
The best way i would like to see it implemented through 2nd option, its not only a workaround for systems that are unable to be updated currently, it may provide more flexible arguments to the systemd daemon start, that way users will be able to operate https://github.com/Icinga/icinga2/blob/master/etc/initsystem/icinga2.sysconfig.cmake variables with better experience.
Icinga2 in any case starts with `--no-stack-rlimit` option on each system, but its implemented somewhere on higher levels.

With best regards,
Dmitriy

**Comment by Al2Klimov** [comment]
"kernel upgrade is not always possible" => why?

**Comment by dmitriy-terzeman** [comment]
Business critical servers in my case only apply kernel patches for security reasons to protect from CVE for example.
Integrating new monitoring solutions like Icinga2(to replace old one) is not a justification for the business for kernel upgrade(read as server reboot, and potential money loss during the maintenance).

I know its not reasonable to spend Icinga team time to cover only this local case, thats why i instead looking for a benefits for the future development, improving icinga2.sysconfig may provide users better 
experience in advanced configuration.

With best regards,
Dmitriy

**Comment by Al2Klimov** [comment]
Then you should _always_ upgrade the kernel as @torvalds tries not to declare security fixes as such as "you could turn every bug into a security hole".

**Comment by dgoetz** [comment]
@dmitriy-terzeman: While I agree that it is a small use case and kernel updates especially on RHEL/CentOS should be applied as they guarantee API and ABI compatibilty, I would like to provide a idea for working around this with local systemd config as long as it is not possible with Icinga 2.

You can override the ExecStart via a systemd drop-in, but this does not fix the safe-reload script so this needs also to be copied, adjusted and overwritten. (Not tested, but should work)

```
mkdir /usr/local/lib/icinga2
cp /usr/lib/icinga2/safe-reload /usr/local/lib/icinga2
sed -ie 's/daemon/daemon --no-stack-rlimit/' /usr/local/lib/icinga2/safe-reload
cat > /etc/systemd/system/icinga2.service.d/kernelbug.conf << EOF
[Service]
ExecStart=
ExecStart=/usr/sbin/icinga2 daemon --no-stack-rlimit --close-stdio -e ${ICINGA2_ERROR_LOG}
ExecReload=
ExecReload=/usr/local/lib/icinga2/safe-reload /etc/sysconfig/icinga2
EOF
systemctl daemon-reload
systemctl start icinga2.service
systemctl reload icinga2.service
```

After the kernel update is applied sometime in the future, just drop the dropin, reload systemd and icinga2.

**Comment by Al2Klimov** [comment]
I vote for closing this one as dup or won't-fix.

@N-o-X @htriem Please vote as well.

**Comment by lippserd** [comment]
I opt against introducing user-driven configuration here. This would be another option to check for when dealing with support cases and I'd like to save us from this headache. If one really needs this, the solution from @dgoetz should be considered. I'm sorry @dmitriy-terzeman but we'll close this one.
