### ISSUE TITLE
New API events: ObjectCreate/ObjectDelete/ObjectModify

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icinga2#7974]
## Rationale

I'm currently working on a customer project (hopefully to be open-sourced sooner or later, depending on a strategic decision to be made by the customer's management) that makes extensive use of the Event functionality of the Icinga 2 API.

The functionality of the tool depends a lot on the configuration objects present in Icinga 2, which works perfectly. There is, however, one restriction that might hit us in the future if the project will actually be open-sourced or if the customer at some point decides to use a tool like the Direcor: When objects are created, modified or deleted via the Icinga API there currently does not seem to be a way to detect that and update the external tool's object hierarchy via the API. 

## Suggested solution

I would be great to add three new event types to the stream API: ObjectCreate, ObjectDelete and ObjectModify, which would be created when ... well, when Objects are created, deleted or modified after initial startup, i.e. via the API. 

It would also be very helpful if the event would contain some indication whether the event was the immediate cause of the API action or by apply rules (i.e. host creation via the API as opposed to service creation caused by apply rules matching the newly created host).

There are related messages in the Icinga 2 log, so adding events to the event stream should not be a very big change to the code base. 

```
[2020-04-13 16:56:29 +0000] information/ConfigObjectUtility: Created and activated object 'test-host-x' of type 'Host'.
[...]
[2020-04-13 16:56:48 +0000] information/ConfigObjectUtility: Deleted object 'test-host-x!test-service-13' of type 'Service'.
[2020-04-13 16:56:48 +0000] information/ConfigObjectUtility: Deleted object 'test-host-x!test-service-7' of type 'Service'.
[2020-04-13 16:56:48 +0000] information/ConfigObjectUtility: Deleted object 'test-host-x!test-service-8' of type 'Service'.
[2020-04-13 16:56:48 +0000] information/ConfigObjectUtility: Deleted object 'test-host-x' of type 'Host'.
```

## Possible (though not appealing) alternatives

All alternative solutions don't seem very appealing to me, though viable - following the Icinga log file or setting inotify to the `/var/lib/icinga2/api' directory used by the API and then figuring out what changes to look out for, for example.

**Comment by Yonas-net** [comment]
First the event types are defined in the class ``EventType`` and stored in the file ``eventshandler`` in a map as pairs with the corresponding methods, i.e. ``method CheckResult => EventType::CheckResult``. While handling the API queries, it is checked that the user only uses ``http version 1.1`` and does not enter an undefined ``event type`` etc.  And if the checks are all successful, an event subscriber is created before server streaming starts. After successful server startup, an endless for loop is used to provide events encoded in ``Json`` for the ``build response``.
