### ISSUE TITLE
Unwanted/unintended recovery notifcation after downtime ends

### ISSUE THREAD

**Issue by halfgaar** [Icinga/icinga2#7977]
## Description

Since Icinga 2.11, [notification suppressed during downtime are sent when the downtime ends](https://github.com/Icinga/icinga2/commit/60661eaecb21f6640e0821381d908837d62847c1). I think it’s that feature that resulted in:

- It’s 2:00 am.
- plan downtime for host and services till 04:00 am.
- Do work
- See that related services are also going into error. I Planned downtime. This notification was probably already sent out before I planned downtime.
- Work is done.
- Dashboard is green
- It’s 03:00 am.
- Sleep.
- Woken up with a phone text message at 04:00 saying ‘recovered’.

Looking at [FireSuppressedNotifications()](https://github.com/Icinga/icinga2/blob/4464e4990e894afa37fdcf011e304505e050c552/lib/icinga/checkable-notification.cpp#L131), I can’t quite match this with the documentation “_Once the downtime ends and the problem state is still intact, Icinga checks whether a re-notification should be sent immediately_”. The code seems to collect recovery messages for later sending, but that’s not a ‘problem state’, right?

(also, I don’t quite see how the compiler won’t complain about uninitialized booleans there)

The feature already has a somewhat ‘rich’ history (it was reverted once), and maybe I misunderstood something about the code, but what I'm sure of is that we did get those recovery messages after downtime ended, waking me up for no reason.

## Expected behavior

The expected/desired behavior probably depends on people's wishes. I expect recovery messages during downtime just getting lost; "what happens in downtime (Vegas), stays in downtime (Vegas)". We actively re-notify until something is acked, instead of parsing a chain of error/recovery/error/recovery/error/recovery text messages to see what the status is.

But I can imagine that for others, they do want it.

If it's configurable, I don't know what the best place would be. A setting on a notification object, perhaps. That way, you can turn it off for SMS/phone ringing, but still keep the e-mails / Slack messages.

## Your Environment

* Version: r2.11.3-1
* Ubuntu 16.04
* Disabled features: command compatlog debuglog elasticsearch gelf graphite livestatus opentsdb perfdata statusdata syslog                                                                                                                                                       
* Enabled features: api checker ido-pgsql influxdb mainlog notification

**Comment by Al2Klimov** [comment]
Works as intended. A user who received a problem notification shall also receive a recovery one.

**Comment by halfgaar** [comment]
Wouldn't it be worth-while to add a property to a notification that it indeed was a suppressed message? That way, users can filter on it.
