### ISSUE TITLE
Icinga process crash with high memory usage, but not ends on complex API query

### ISSUE THREAD

**Issue by GillesMocellin** [Icinga/icinga2#7988]
## Describe the bug

`[2020-04-21 18:50:32 +0200]  critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in '/var/log/icinga2/crash/report.1587487832.503983'
`
## To Reproduce

With a lot of hosts and services, call API with complex filter : 

POST on https://opur.host.tld/v1/objects/hosts
Authentication : Basic Auth
Headers :
- Accept: application/json
- X-HTTP-Method-Override: GET

Query params:
- filter='regex("%s", [host.name, host.display_name], MatchAny) || regex("%s", [host.name, host.display_name], MatchAny) || ...'

The complexity is here : 114 times the regex on host.name and display_name with different values.

## Expected behavior
Either a repsonse, or if memory is insufficient, a clear error.
Icinga process (or dependant libs) should handle gracefully out of memory on malloc calls and not crash.

## Your Environment

* Version used (`icinga2 --version`):

root -> icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.2-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 16.04.6 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-177-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.4.0
  Build host: runner-LTrJQZ9N-project-298-concurrent-0

## Additional context

Systemd configuration changed to restart on-failure, with a WatchDog of 30s.
But systemd does not catch it, the service is still "Active", processes exist, but do nothing after the log about unexpected termination.

Crash report : 
```
(0) libc.so.6: gsignal (+0x38) [0x7f21d567d428]
(1) libc.so.6: abort (+0x16a) [0x7f21d567f02a]
(2) libc.so.6: <unknown function> (+0x777ea) [0x7f21d56bf7ea]
(3) libc.so.6: <unknown function> (+0x7d814) [0x7f21d56c5814]
(4) libc.so.6: <unknown function> (+0x82a03) [0x7f21d56caa03]
(5) libc.so.6: __libc_malloc (+0x54) [0x7f21d56cc184]
(6) libcrypto.so.1.0.0: CRYPTO_malloc (+0x58) [0x7f21d3df1e78]
(7) libssl.so.1.0.0: <unknown function> (+0x28a05) [0x7f21d41fca05]
(8) libssl.so.1.0.0: <unknown function> (+0x27a19) [0x7f21d41fba19]
(9) libssl.so.1.0.0: <unknown function> (+0x23c64) [0x7f21d41f7c64]
(10) /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2() [0x5c8792]
(11) /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2() [0xa2b9bd]
(12) /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2() [0x65ce32]
(13) icinga2: icinga::NetString::ReadStringFromStream(std::shared_ptr<icinga::AsioTlsStream> const&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, long) (+0x39f) [0x5dd11f]
(14) icinga2: icinga::JsonRpc::ReadMessage(std::shared_ptr<icinga::AsioTlsStream> const&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, long) (+0x3f) [0x6f9cef]
(15) icinga2: icinga::JsonRpcConnection::HandleIncomingMessages(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >) (+0xde) [0x70d8de]
(16) /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2() [0x75cb8f]
(17) libboost_context.so.1.67.0: make_fcontext (+0x2f) [0x7f21d30b35cf]
```

**Comment by N-o-X** [comment]
Hi @GillesMocellin,

sorry for this very late answer. Is this still a problem you're facing? If so, please reopen this issue.

Greetings
Noah
