### ISSUE TITLE
pki save-cert: Error while parsing command-line options: unrecognised option '--key'

### ISSUE THREAD

**Issue by Felix941** [Icinga/icinga2#7992]
##Describe the Bug
When running:
Icinga2AgentModule `
    -DirectorUrl       'http://10.10.10.44/icingaweb2/director/' `
    -DirectorAuthToken 'ff65ded20a32cc887641b0261975b48a35e4ba86' `
    -RunInstaller
It works until

## Expected Behavior
It should acept the command and run without an error.

## Current Behavior

Notice: Started script run...
Notice: Reading host api token "32f377803562d9bf09e432aa0489a6df5f027cd6" from "C:\ProgramData\icinga2\etc\icinga2\icingadirector.token"
Notice: Connected successfully to Icinga Director Self-Service API over stored host token.
Notice: Setting internal Agent Name to "VPC-DC04.ad.xxx.de"
Notice: Trying to fetch Host IP-Address for hostname: VPC-DC04.ad.xxx.de
Notice: Setting IP 10.10.10.10 as primary IP for this host for all requests. Access it with &ipaddress& for all JSON requests.
Notice: Using Icinga version "2.12.0", setting certificate directory to "C:\ProgramData\icinga2\var\lib\icinga2\certs"
Notice: Found Icinga 2 Agent version 2.12.0 installed at "C:\Program Files\ICINGA2\"
Notice: Icinga 2 Agent is up-to-date. Nothing to do.
Notice: Host is already registered within Icinga Director.
Notice: Fetched ticket "aa34e6f3c395157c7b4282bf97506eb218043126" from Icinga Director
Notice: Generating Host certificates required by Icinga 2
Notice: information/base: Writing private key to 'C:\ProgramData\icinga2\var\lib\icinga2\certs\VPC-DC04.ad.xxx.de.key'.
information/base: Writing X509 certificate to 'C:\ProgramData\icinga2\var\lib\icinga2\certs\VPC-DC04.ad.xxx.de.crt'.
Notice: Storing Icinga 2 certificates
Fatal: Ausnahme beim Aufrufen von "generateCertificates" mit 0 Argument(en):  "[2020-04-25 20:39:18 +0200] critical/icinga-app: Error while par"ing command-line options: unrecognised option '--key'
######## The script encountered several errors during run ########
Fatal: Ausnahme beim Aufrufen von "generateCertificates" mit 0 Argument(en):  "[2020-04-25 20:39:18 +0200] critical/icinga-app: Error while par"ing command-line options: unrecognised option '--key'

## Steps to Reproduce (for bugs)
1. Get the Api key from Icinga Director
2.Install Icinga on an Win2019 Server, the powershell module and restart the server
3.Try to execute the data from Icinga Director in Powershell

## Context
I'm trying to register a Windows Machine to Icinga2 with powershell

## Your Environment
Version used:
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.3-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: openSUSE Leap
  Platform version: 15.1
  Kernel: Linux
  Kernel version: 4.12.14-lp151.28.44-default
  Architecture: x86_64

Build information:
  Compiler: GNU 7.4.1
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Enabled features (`icinga2 feature list`):
command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification

* Icinga Web 2 version and modules (System - About):

Icinga Web 2 Version
    2.7.3
PHP Version
    7.2.5
Git commit date
    2019-10-18
Copyright
    © 2013-2020 The Icinga Project 
* Config validation (`icinga2 daemon -C`):
[2020-04-25 20:50:14 +0200] information/cli: Icinga application loader (version: 2.11.3-1)
[2020-04-25 20:50:14 +0200] information/cli: Loading configuration file(s).
[2020-04-25 20:50:14 +0200] information/ConfigItem: Committing config item(s).
[2020-04-25 20:50:14 +0200] information/ApiListener: My API identity: VPC-Icinga
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 85 Notifications.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 34 Hosts.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 Downtime.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 3 Zones.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 ApiUser.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 236 CheckCommands.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 1 User.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 51 Services.
[2020-04-25 20:50:14 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-04-25 20:50:14 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-04-25 20:50:14 +0200] information/cli: Finished validating the configuration file(s).
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
Object 'VPC-Icinga' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 7:1-7:28
  * __name = "VPC-Icinga"
  * host = "10.10.10.44"
    % = modified in '/etc/icinga2/zones.conf', lines 8:3-8:22
  * log_duration = 86400
  * name = "VPC-Icinga"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 7
    * last_column = 28
    * last_line = 7
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "VPC-Icinga" ]
    % = modified in '/etc/icinga2/zones.conf', lines 7:1-7:28
  * type = "Endpoint"
  * zone = ""

**Comment by lippserd** [comment]
Hi @Felix941,

Thanks for the report. I think your master/satellite nodes are version 2.11.3.
The agent you're trying to install/provision reports version 2.12.0 (RC/Snapshot) though.
That is no problem, I just wanted to note that because from the issue description it looks like you're assuming version 2.11.3 for the agent as well.

Apparently we removed the `--key` option from `pki save-cert` with version 2.12.0 in #7835.

That is not good. There was no deprecation notice and all our tools rely on that option being present, obviously.

We'll fix that asap.

@N-o-X @Al2Klimov Could you please have a look here. It makes sense to deprecate those parameters since they're not needed anymore. But we can't just remove them without prior notice.
I opt for reintroducing those parameters with a deprecation warning upon usage. Also our docs must state that these options are deprecated.

Also @Thomas-Gelf and @LordHepipud have to be involved since they consume the `pki save-cert` command.

All the best,
Eric

**Comment by LordHepipud** [comment]
Thank you very much for the feedback! From my understanding, the `--key` argument is no longer required starting with 2.12.0 but we will keep it for now?

I would then provide patches for the [Icinga for Windows](https://github.com/Icinga/icinga-powershell-framework) and [Icinga 2 PowerShell Module](https://github.com/Icinga/icinga2-powershell-module) solutions to drop the argument starting with 2.12.0 installations and keep it for older versions.

That way we will keep compatibility across the board. Are we all fine with this?
Someone will have to take a look on the Linux installation shell-script inside the Director as well.

**Comment by Al2Klimov** [comment]
> I think your master/satellite nodes are version 2.11.3.
> The agent you're trying to install/provision reports version 2.12.0 (RC/Snapshot) though.
> That is no problem,

It **is** a problem. Likely not the cause of this issue, but we don't support more recent versions on hierarchical lower nodes.

**Comment by LordHepipud** [comment]
I just made an update to the old PowerShell module and the new Framework. Both will now handle the `--key` argument starting with 2.12.0.

In case you got some spare time, I would be happy if you could update your PowerShell module file based on the current master of the [Icinga 2 PowerShell module](https://github.com/Icinga/icinga2-powershell-module) and check if the issue in general is resolved there.

At least you can get started until new packages from Icinga 2 are available.

I would appreciate the feedback a lot!
