### ISSUE TITLE
Icinga2 Node Wizard crashes on Ubuntu 20.04

### ISSUE THREAD

**Issue by JensBavenmark** [Icinga/icinga2#7999]
## Describe the bug

When running the Icinga2 node wizard on a new installation of Ubuntu 20.04 the setup crashes after 
the wizard enters the "Reconfigure Icinga" stage:

Reconfiguring Icinga...
critical/Application: Error: boost::filesystem::copy_file: Permission denied: "/etc/icinga2/features-available/api.conf", "/etc/icinga2/features-available/api.conf.orig"

I have checked /etc/passwd and no Icinga user was created during the installation.

**Crash report:**

Caught unhandled exception.
Current time: 2020-05-11 07:09:46 +0000

  Application version: r2.11.2-1

System information:
  Platform: Ubuntu
  Platform version: 20.04 LTS (Focal Fossa)
  Kernel: Linux
  Kernel version: 5.4.0-29-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 9.2.1
  Build host: lcy01-amd64-022

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Error: boost::filesystem::copy_file: Permission denied: "/etc/icinga2/features-available/api.conf", "/etc/icinga2/features-available/api.conf.orig"

        (0) libboost_filesystem.so.1.71.0: boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*) (+0x1f5) [0x7fdd98e5a065]
        (1) icinga2: icinga::Utility::CopyFile(icinga::String const&, icinga::String const&) (+0x60) [0x55aa33a511f0]
        (2) icinga2: icinga::NodeUtility::CreateBackupFile(icinga::String const&, bool) (+0x98) [0x55aa33ca0758]
        (3) icinga2: icinga::NodeWizardCommand::AgentSatelliteSetup() const (+0x1e24) [0x55aa33cb5614]
        (4) icinga2: icinga::NodeWizardCommand::Run(boost::program_options::variables_map const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const (+0x2c5) [0x55aa33cbab15]
        (5) icinga2: <unknown function> (+0x562e75) [0x55aa33a15e75]
        (6) icinga2: main (+0xc2) [0x55aa33a06f32]
        (7) libc.so.6: __libc_start_main (+0xf3) [0x7fdd983050b3]
        (8) icinga2: _start (+0x2e) [0x55aa33a1357e]
 

## To Reproduce

1. Install Ubuntu 20.04
2. Update and upgrade.
3. Setup Icinga repos.
4. Install Icinga2
5. Run Icinga2 node wizard.

## Expected behavior

The node wizard should finish without crashing.
A Icinga user should be created during installation of Icinga2.

## Your Environment

* Version used (`icinga2 --version`): r2.11.2-1
* Operating System and version: Ubuntu 20.04
* Enabled features (`icinga2 feature list`): Enabled features: api checker mainlog

Icinga repos: 
deb https://packages.icinga.com/ubuntu icinga-focal main
deb-src https://packages.icinga.com/ubuntu icinga-focal main

**Comment by Al2Klimov** [comment]
Hello @JensBavenmark and thank you for reporting!

Are you sure that you're actually installing the Icinga 2 packages from our repository?

Best,
AK

**Comment by JensBavenmark** [comment]
I believe so. From where else could it be installed from?

**Comment by Al2Klimov** [comment]
From Ubuntu itself?

**Comment by JensBavenmark** [comment]
Yes you are correct. When checking the logs I can see that they come from archive.ubuntu.com.

**Comment by Al2Klimov** [comment]
> I have checked /etc/passwd and no Icinga user was created during the installation.

Please report this to Ubuntu itself.

**Comment by Al2Klimov** [comment]
I just noticed that we don't have packages for Ubuntu 20.04 yet unfortunately. But we're already in the process of building and providing them. We'll try to get them ready as soon as possible.
