### ISSUE TITLE
icinga crashes during startup without error if wrong permisson to write a log

### ISSUE THREAD

**Issue by marcelfischer** [Icinga/icinga2#8004]
## Describe the bug

I discovered this, because we had to change uid/gid of the icinga user. We forgot to adjust /var/log/icinga2.
Systemd fails to start icinga and when using icinga2 daemon the process just ends with exitcode 1.

Config validates with exitcode 0.

## To Reproduce

1. Stop icinga
2. change owner/group of /var/log/icinga2 to something else than icinga process user
3. Start icinga with _icinga2 daemon_
4.

## Expected behavior

I would expect some kind of error message, that no logfile could be created.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): icinga2 --version
* Operating System and version: RHEL 7.7
* Enabled features (`icinga2 feature list`): api checker mainlog

**Comment by Al2Klimov** [comment]
> * change owner/group of /var/log/icinga2 to something else than icinga process user

@N-o-X IMAO we shall not support this, shall we?

**Comment by N-o-X** [comment]
@marcelfischer doesn't want that we support using a different user. He just would like to see an error message telling him that something is wrong with the permissions, instead of just crashing silently.

**Comment by marcelfischer** [comment]
> @marcelfischer doesn't want that we support using a different user. He just would like to see an error message telling him that something is wrong with the permissions, instead of just crashing silently.

Yes, thats correct.

**Comment by Al2Klimov** [comment]
Should be fixed by #8614.
