### ISSUE TITLE
icinga2 mysql CheckCommand definition does not allow socket checking

### ISSUE THREAD

**Issue by mgwerder** [Icinga/icinga2#8017]
I discovered a small problem with the CheckCommand definition of the check_mysql plugin shipped with Ubuntu Fossa (version: r2.12.0-rc1-1).

The mysql plugin does allow checking of mysql using the socket. However setting the host.vars.mysql_socket with the socket path fails:

```
apply Service "MySQL Socket" {
  import "generic-service"
  check_command = "mysql"

  assign where host.vars.mysql_socket
}
```

With a host:
```
object Host "florian.cyber-geiger.eu" {
  import "generic-host"

  address  = "1.2.3.4"

  vars.os = "Linux"
  .
  .
  .
  vars.mysql_socket  = "/run/mysqld/mysqld.sock"
  vars.mysql_username = "mysqlusername"
  vars.mysql_password = "supersecretcommandlinevisiblepassword"
  .
  .
  .
}
```

This due to the fact that within ```/usr/share/icinga2/include/command-plugins.conf``` the CheckCommand always sets ```vars.mysql_hostname```. According to the plugin help, setting this variable will cause the plugin to ignore ```mysql_socket```.

To fix the issue I propose not setting ```mysql_hostname``` if ```mysql_socket``` is set. This should exactly give the expected behavior of the plugin (runn a socket test if a socket is specified or a tcp test otherwise).

A possible patch is:
```
2770c2770,2772
<       vars.mysql_hostname = "$check_address$"
---
>         if ( "$mysql_socket$" == "" ) {
>               vars.mysql_hostname = "$check_address$"
>       }
```
Regards
Martin

**Comment by Al2Klimov** [comment]
Confirmed. At least after locking out :3306 -s has no effect with -H.
