### ISSUE TITLE
Can't add a comment or schedule a downtime for a host/service with a long name

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga2#8022]
## Describe the bug

Adding a comment or a downtime for a host or service with a long name shows this API error:

```
icinga2: Can't send external Icinga command: 500 Action execution failed: 'Error: Function call 'std::ifstream::open' for file '/opt/icinga2/var/lib/icinga2/api/packages/_api/07d2d10f-dd07-4159-a60a-a0323aa6fe4d/conf.d/comments/looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong-hoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooost!looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong-seeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrviiiiiiiiiiiiiiiiice!d456a095-d6fb-467b-b196-88694f059537.conf' failed with error code 36, 'File name too long'

(0) Compiling configuration file '/opt/icinga2/var/lib/icinga2/api/packages/_api/07d2d10f-dd07-4159-a60a-a0323aa6fe4d/conf.d/comments/looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong-hoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooost!looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong-seeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrviiiiiiiiiiiiiiiiice!d456a095-d6fb-467b-b196-88694f059537.conf'
'.
```

## Expected

If Icinga can handle long host/services names in general, I'd expect it to handle them as well when interacting with the API.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.12.0-rc1-1
* Operating System and version: CentOS 7

**Comment by Al2Klimov** [comment]
Is this an actual real-world problem or just a border test?

**Comment by K0nne** [comment]
This sounds like it has a connection with my 'support hosts >128 characters' issue:

https://github.com/Icinga/icinga2/issues/7472

Long hostnames can be a problem in cloud environments where you have to define distinct unique names.

**Comment by nilmerg** [comment]
This is not a *border test*. The host is added to the IDO, Icinga DB, the config validator does not complain etc. The API **has to** to be able to handle such a case as well.
