### ISSUE TITLE
For API calls Invalid Filters are Ignored

### ISSUE THREAD

**Issue by Zottel92** [Icinga/icinga2#8026]
## Describe the bug

If the filter string is not a boolean, the filter returns True for every Host.

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1. Enable the API
2. Send a request with a random non valid filter-string:
```
curl --location -k --request POST 'https://10.0.0.10:5665/v1/actions/schedule-downtime?filter=%22komisches%20Zeugs%22&type=Service&start_time=1589991859&end_time=1592670259&author=test&comment=testing' \
--header 'Accept: application/json' \
--header 'Authorization: Basic asdfasdfasdf'
```
3. Now Downtimes for all services are set and the filter is ignored

## Expected behavior

An error-message is returned explaining that the filter is incorrect.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.11.2
* Operating System and version: Centos 7
* Enabled features (`icinga2 feature list`): API

## Additional context
I know that the README.md states that the filter-string should be a valid boolean expression, but there should be some checks in place to validate this. 
If the end result would be that a "wrong" filter-string is seen a allways "False" I would issue a feature request about returning information to the user, but since a random-filter-string is read as always True I would see this as a bug.

A user who makes a typo in his filter-string might downtime all of his hosts by accident.

**Comment by Al2Klimov** [comment]
Hello @Zottel92 and thank you for reporting!

Actually every expression (that doesn't throw any errors) is a valid boolean expression:

```
Icinga 2 (version: v2.12.0-rc1-23-g9f45c2923)
Type $help to view available commands.
<1> => !!"lolcat"
true
<2> => !!"0"
true
<3> => !!""
false
<4> =>
```

Best,
AK
