### ISSUE TITLE
CheckCommand: ssl - Add parameter to check certificate expiry of the whole chain

### ISSUE THREAD

**Issue by martinseener** [Icinga/icinga2#8042]
Currently it is not possible to use the internal `ssl` CheckCommand to verify the full certificate chain of an enpoint but rather only the site certificate. It would be nice to have a parameter for the CheckCommand to enable full-chain checks if a certificate in there is about to expire. See recent issue: https://www.ssl.com/blogs/addtrust-external-ca-root-expired-may-30-2020/

## Describe the solution you'd like

I'd like to have a parameter for the `ssl` CheckCommand to enable full chain checks for expiring certificates

## Describe alternatives you've considered

Building my own SSL check and use this instead

**Comment by Al2Klimov** [comment]
Hello @martinseener and thank you for reporting!

> I'd like to have a parameter for the `ssl` CheckCommand to enable full chain checks for expiring certificates

Do you mean an already existing parameter of the used check plugin our CheckCommand isn't aware of? If yes, which one?

Best,
AK

**Comment by martinseener** [comment]
Hello @Al2Klimov, thanks for the quick reply.
So i've checked this: https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#ssl and i only see the normal certificate check there, but not for the whole chain, containing also intermediate certificates that can expire.
Then I checked the chck_tcp plugin here: https://www.monitoring-plugins.org/doc/man/check_tcp.html
and can't also find anything to check the whole chain here. Maybe I miss something?

Thank you!

**Comment by Al2Klimov** [comment]
> Then I checked the chck_tcp plugin here: https://www.monitoring-plugins.org/doc/man/check_tcp.html
> and can't also find anything to check the whole chain here.

Unfortunately this means there isn't any parameter we could add to the ITL.

**Comment by martinseener** [comment]
Hey, ok so this means I rather have to open an Issue for check_tcp? Where can I do this? Thanks for the help!
