### ISSUE TITLE
Use the -S parameter for API queries in the documentation

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icinga2#8065]
## Describe the bug

Throughout the Icinga documentation API queries are executed using the ``-s`` parameter. This way you won't know what's actually happening and that would completely confuse someone new to Icinga2 to debug Icinga2 or reproduce errors from others.
https://icinga.com/docs/icinga2/latest/doc/12-icinga2-api/
## Expected behavior
It would be very helpful if the queries were queried with parameter ``-v``, because with this parameter you can see everything that went wrong and what didn't.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by Mikesch-mp** [comment]
Maybe you should not change this and explain why `-s` is used.
Hint: a lot of users just copy and paster those examples into their scripts

**Comment by Al2Klimov** [comment]
@Yonas-net Figure out how you would replace all `-s` at once (shell command(s)) with `-s -S` and comment it here.

**Comment by Yonas-net** [comment]
I tried it like this and it works perfectly.
```
sed -i 's/-s/-s -S -i/g' 12-icinga2-api.md
```

**Comment by Al2Klimov** [comment]
Make a PR and let me review it.
