### ISSUE TITLE
Windows Agent: Provide Powershell Plugins during Installation

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga2#8069]
## Is your feature request related to a problem? Please describe.

It is a feature request. Since we are shifting more and more towards the [Windows Powershell Plugins](https://github.com/Icinga/icinga-powershell-plugins) I think it is a good idea to provide them during the Windows Agent installation process. 

## Describe the solution you'd like

Icinga Powershell Plugins are installed during the installation process of a Windows Agent. 

## Describe alternatives you've considered

None. 

## Additional context

This would make it easiere for users to setup a Windows Agent with up to date Powershell plugins. Also we should find a solution how to deal with the "old" Windwows check plugins, are we replacing them?

**Comment by Al2Klimov** [comment]
@LordHepipud Anything special we shall be aware of while implementing this?

**Comment by mcktr** [comment]
If not yet done it would also be a good enhancement for users to provide the needed `CheckCommand` definitions out of the box i.e. add the Powershell plugins to the ITL.

**Comment by LordHepipud** [comment]
Hello and thank you very much for your input. Our current goal would be to seperate the packages regarding the Agent and the plugins to keep the best flexibility by allowing users to upgrade each component individually.
We discussed the topic internally and we believe the best approach would be to change the entry point on how to install the Agent on Windows. For that we would update the documentation to use the [Icinga for Windows](https://icinga.com/docs/windows) solution as starting point to install the Agent and all additional components of plugins and other related modules. The Agent installation is already part of the Icinga for Windows solution and taking care of the entire configuration and additional content like plugins.

By doing so, we also have the ability to easily provide a solution for automation, not only with PowerShell but also Puppet, Ansible and other tools in addition.

For the ITL we have it on our roadmap and would add them in one the next releases. Right now we can how ever not give a time estimation on that.

Would you agree here?

**Comment by mcktr** [comment]
Sorry for my late response. 

I strongly disagree. From my point of view Icinga for Windows is **not** a replacement for the C/C++ Windows plugins . The whole project Icinga for Windows brings a complete configuration framework, installation helper, plugin framework, service to register functions to and many more. While all this is a good idea it should not be included in the PowerShell plugins, but unfortunately the framework is a direct dependency of the PowerShell plugins. As an administrator I want to keep the installation as minimal as possible and I don't want to maintain unused components (that may also opens an attack vector).

I think the ideal "drop-in" replacement would be the PowerShell plugins without any of the extra framework stuff bundled into the MSI installer. 

When Icinga (for Windows) shifts more and more towards PowerShell as main programming language for plugins it should be possible to run PowerShell scripts natively, without the following workaround:

```
object CheckCommand "powershell_check" {
  import "plugin-check-command"
  command = [ "C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe" ]
  arguments = {
    "-command" = {
    value = "$ps_command$"
    order = -1
    }
    "-warn" = {
    value = "$ps_warn$"
    }
    "-crit" = {
    value = "$ps_crit$"
    }
    ";exit" = {
    value = "$$LastExitCode"
    }
  }
}
```

There is also a feature request open: https://github.com/Icinga/icinga2/issues/7430

**Comment by mcktr** [comment]
The next thing that come to my mind: What about the Chocolatey packages? Currently the Chocolatey packages install the MSI  with the bundled the C/C++ Windows plugins. If this is no longer possible one have to take manual actions after installing the Chocolatey packages. As a user of Chocolatey this is not what I would expect.

**Comment by Al2Klimov** [comment]
@lippserd @N-o-X Please indicate whether you agree with https://github.com/Icinga/icinga2/issues/8069#issuecomment-652272487.

**Comment by lippserd** [comment]
> From my point of view Icinga for Windows is **not** a replacement for the C/C++ Windows plugins . The whole project Icinga for Windows brings a complete configuration framework, installation helper, plugin framework, service to register functions to and many more.

Icinga for Windows is the replacement for the C / C ++ plugins and all the other things we tried and implemented to monitor Windows. In addition, Icinga for Windows is the leading installation source, so the Icinga MSI does not ship any of its components, but vice versa. However, I agree that the installation must be as lean and simple as possible. But that's a separate concern.
