### ISSUE TITLE
Log if two corresponding nodes run on different versions of Icinga 2

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#8075]
## Is your feature request related to a problem? Please describe.

During debugging of customer setups we sometimes stumbled upon environments where one of the nodes was merely forgotten when updates were rolled out. It's not very common, to be honest, but it would help if we could get that option off the table without going through a full diagnostics output of all corresponding nodes.

## Describe the solution you'd like

I'd like to see in the Icinga log when the communiction partner in an api connection runs on a different version of Icinga 2. And I'd like to see this message repeated once in a while because sometimes you can't get debug logs and sometimes customers just send a short timeframe of logs. Especially when it comes to huge setups.

## Describe alternatives you've considered

* Asking for versions. If a node is forgotten, it's forgotten when you ask explicitely, too
* Asking for Icinga Diagnostics outputs. It helps but it's a lot of data to look at

**Comment by Al2Klimov** [comment]
Yes, we should warn... if a child node runs neither the same version, nor minus one minor version.

**Comment by Al2Klimov** [comment]
Note for whoever I'll assign in the future:

1. Check out 290e8afc3
2. Build this feature (PR) on top of that commit (not master)
