### ISSUE TITLE
Icinga2-v2.10.5-x86_64 Windows Sat - High CPU Usage on Windows Server 2016 after KB4556813

### ISSUE THREAD

**Issue by mariopatov** [Icinga/icinga2#8082]
Hello Everyone,

We have a windows 2016 standard edition server which is running Icinga2-v2.10.5-x86_64 satellite setup. 
This satellite is mainly running PowerShell scripts, which execute PS-Remote checks to multiple monitored servers.
There were no performance problems at all before we applied OS updates which installed the patch KB4556813.

After this update the server runs with CPU 100% all the time and it looks like the PowerShell scripts are started kind of all at once and remain running. This makes the server unresponsive.  

Tested two times, after removing the patch KB4556813 the problem is gone. 

Can you please share if someone experienced the same kind of problem or if there a know fix/solution to resolve this issue?

Thank you in advance!
Mario

**Comment by Al2Klimov** [comment]
@LordHepipud Can we as app devs even do something here?

**Comment by mariopatov** [comment]
I was able to workaround this issue, so wanted to share with us all how if someone meets the same problem:

- On the Windows satellite, limit the number of concurrent checks to 100, by adding the following block in C:\ProgramData\icinga2\etc\icinga2\features-available\checker.conf

`library "checker"  
  object CheckerComponent "checker" {
          concurrent_checks = 100
  }
`
- Also in the PS ICINGA2 command configuration, to reduce the CPU load from the executed PowerShell scripts, added the 
-Mta -NoProfile options: 

`object CheckCommand "check_sepm_av" {
        command = [ PowerShell ]
        arguments = {
                "-Mta" = { }
                "-NoProfile" = { }
                "-command" = {
                value = "& " + PluginPS1Dir "check_sepm_av.ps1"
                }
                "-target" = "$server_name$"
                "-credential" = "$wmi_credential$"
        }
}
`

Thanks!

**Comment by Al2Klimov** [comment]
How may checks does the agent run per minute (average)?

**Comment by LordHepipud** [comment]
To me it does look like the Icinga 2 Client is executing all checks at once instead of distributing it over time.

I assume you are trully running Icinga 2 as satellite and not as Agent? Did you encounter any issues requiring you to delete the Icinga state file or other configuration related topics? This might then result in a problem of all checks running at once and if you are using remote execution, you have plenty of parallel connection attempts which will slow down each other.

This would explain the behaviour of the PowerShell instances being kept open.

**Comment by mariopatov** [comment]
Yes, I am running icinga2 as a satellite, not as an agent. 
I did not have to delete any icinga2 files on the satellite nor on the master servers.
Basically, after server restart, icinga2 satellite starts all checks it has configured to monitor at once. In my case it`s couple of hundred PS-Remote powershell scripts. Before patching the OS this problem did not exist.

**Comment by Al2Klimov** [comment]
@mariopatov Please could you upgrade to v2.11.4 and test the OS patch? (Parent nodes must not run older Icinga versions than child nodes!)

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
