### ISSUE TITLE
Icinga2 HA Setup

### ISSUE THREAD

**Issue by Xavihernandez93** [Icinga/icinga2#8084]
hi all , i want to know that
how much load /checks can a master and satellite can handle 
how much agents can be handled by a single satellite
How do I know that my satellites / master are overloaded and not able to take any more same goes with the master ?

**Comment by N-o-X** [comment]
Hi @Xavihernandez93,

that's a topic for our forums [community.icinga.com](https://community.icinga.com). GitHub is just for bugs and feature requests. Just ask your question to the community and you should get help over there!

Greetings
Noah
