### ISSUE TITLE
Don't close connection on missing heartbeat

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#8095]
## Describe the bug

While processing many messages a node may not see the peer's heartbeat soon enough and close the connection.

## Expected behavior

Don't enforce heartbeats to be received. `m_Seen` is enough.

## Your Environment

v2.11

## Additional context

@lippserd @N-o-X With this we'd not need prio heartbeats anymore.

**Comment by Al2Klimov** [comment]
Note to whoever I'll assign this to:

1. Check out a new branch from v2.11.0 (not master)
2. Create a PR into `support/2.11` (not master)

**Comment by N-o-X** [comment]
Closed by #8097
