### ISSUE TITLE
installation on windows

### ISSUE THREAD

**Issue by Xavihernandez93** [Icinga/icinga2#8106]
this is my setup
![WhatsApp Image 2020-07-09 at 4 06 41 PM](https://user-images.githubusercontent.com/54971983/87117906-7c54bd80-c297-11ea-9e88-f5687ecb5dcd.jpeg)

In addition to this i have one db not added as host here
also one more windows machine 
for that particular windows machine i want to install icinga which has no internet

that windows machine is in same availability zone with other 2 windows machines , can anyone tell me how to do this

**Comment by K0nne** [comment]
Hi!

You shoud post configuration questions in the community forums (https://community.icinga.com/). Github is intended as a bug tracker.

**Comment by Xavihernandez93** [comment]
sorry iam a newbie to icinga , can you please clear my doubt

**Comment by mcktr** [comment]
As @K0nne said please hop on our community platform https://community.icinga.com/ for configuration questions. The issue tracker is for bugs or feature requests.
