### ISSUE TITLE
Deprecate Windows C Plugins, replaced by Icinga for Windows

### ISSUE THREAD

**Issue by bobapple** [Icinga/icinga2#8141]
Plugins for Windows monitoring, included in Icinga 2, should be deprecated. The replacement, [Icinga for Windows](https://icinga.com/docs/windows/latest/plugins/doc/10-Icinga-Plugins/), is the new standard selection for monitoring Windows servers with Icinga and we should not offer two separate solutions.

The Icinga 2 documentation will be updated to match this accordingly, as described in https://github.com/Icinga/icinga2/issues/8069

**Comment by Al2Klimov** [comment]
Was #8071 not the only task for this?

**Comment by bobapple** [comment]
Yes, that should be all for now.

The documentation changes described in #8069 need some more attention and some additional steps which we may plan for a future release.

**Comment by Crunsher** [comment]
Finally someone takes care of my crimes

**Comment by dnsmichi** [comment]
> Finally someone takes care of my crimes

Powerful and easy to kickstart your monitoring setup on Windows for anyone knowing the behaviour from Linux/Unix, working OOTB after the msi install. I'm still glad we moved there in 2015 and made it as convenient as possible. 

No regrets my friend, your contributions will always be remembered 👍  Too bad we couldn't find a better trainee project loosely coupled to the core's code back then. Just think of large enterprises and cooperations running it in production for 5 years, no matter the bugs or crimes we did. 😎

**Comment by kochd** [comment]
> Just think of large enterprises and cooperations running it in production for 5 years, no matter the bugs or crimes we did. 

This leads me to my question:
Are we supposed to migrate the endpoints and service configurations now as soon as possible? Or does deprecated mean it will be provided as it is as long as possible in case there is no major bug or security issue found. Just like many others I've build tons of things based on that now deprecated system including the easy to integrate custom checks in sbin. The blog post did not make this clear to me either.

As I have a large set of well established service checks I integrate new endpoints based on them instead of using the powershell plugins at all . Using the powershell plugins would mean I have to implement everything again from scratch just to get what I had before.

Can somebody clarify?

**Comment by Al2Klimov** [comment]
IMAO still shipping the plugins for a while doesn't hurt (us) – especially while a lot of people are still using them.

**Comment by mcktr** [comment]
The deprecated C/C++ Windows plugins should be shipped __at least__ for the next major version. It may is also a good idea to make this more visible with a warning message when validating the configuration.

**Comment by gunnarbeutner** [comment]
> Finally someone takes care of my crimes

Eh, they sure served their purpose. Plus whatever else Michael already wrote. 🙏

**Comment by Al2Klimov** [comment]
All (!) of the three very first Icinga 2 core devs join the discussion? Just this fact shows... a lot.

Even w/o this I have no problem with shipping those now unmaintained stuff (#8071, #8051, compat) even forever – as long as we won't have to even think about it while developing everything else.

**Comment by kochd** [comment]
> Even w/o this I have no problem with shipping those now unmaintained stuff (#8071, #8051, compat) even forever

Sounds good to me

**Comment by Al2Klimov** [comment]
@bobapple Does #9767 satisfy your needs?

**Comment by bobapple** [comment]
👍

**Comment by Al2Klimov** [comment]
Does that mean that this issue is resolved?
