### ISSUE TITLE
Can't create API user w/ password

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#8164]
```
root@icinga-master-1:~# curl -sSku root:4bef1a71e105776a https://127.0.0.1:5665/v1/objects/apiusers/global\?pretty=1 -X PUT -H 'Accept: application/json' -d '{"attrs":{"zone":"global","password":"global"}}'
{
    "results": [
        {
            "code": 500.0,
            "errors": [
                "Error: Attribute is marked for internal use only and may not be set: password\n"
            ],
            "status": "Object could not be created."
        }
    ]
}root@icinga-master-1:~#
```

**Comment by Al2Klimov** [comment]
@N-o-X Shall we allow this?

**Comment by N-o-X** [comment]
Sure, if an ApiUser has the correct permissions, I'd expect to be able to create other ApiUsers (and also change their passwords).

**Comment by Yonas-net** [comment]
I think the error is thrown in [this If query](https://github.com/Icinga/icinga2/blob/8910784844a5a197c8c91551f5f406684eb49827/lib/remote/configobjectutility.cpp#L131).

**Comment by Al2Klimov** [comment]
Does adding users w/o any passwords work?

**Comment by Yonas-net** [comment]
Command: ``curl -sSku root:icinga https://127.0.0.1:5665/v1/objects/apiusers/global\?pretty\=1 -X PUT -H 'Accept: application/json' -d '{"attrs":{"zone":"global"}}'`` 

Output:
```
{
    "results": [
        {
            "code": 500.0,
            "errors": [
                "Error: Validation failed for object 'global' of type 'ApiUser'; Attribute 'zone': Object 'global' of type 'Zone' does not exist.\nLocation: in /icinga2/prefix/var/lib/icinga2/api/packages/_api/5985f3ee-5a10-4fdd-bc84-b0f1c52ff149/conf.d/apiusers/global.conf: 3:2-3:16"
            ],
            "status": "Object could not be created."
        }
    ]
}%  
```

**Comment by Al2Klimov** [comment]
And w/o the zone?

**Comment by Yonas-net** [comment]
> And w/o the zone?

Command: ``curl -sSku root:af2c18268fe250b7 https://127.0.0.1:5665/v1/objects/apiusers/global\?pretty\=1 -X PUT -H 'Accept: application/json' -d '{"attrs":{}}'``

Result:
```
{
    "results": [
        {
            "code": 200.0,
            "status": "Object was created"
        }
    ]
}%  
```

**Comment by Yonas-net** [comment]
And the newly created apiUser looks like in the ``/../apiusers/global.conf`` file.

```
object ApiUser "global" {
	version = 1602235143.872374
	zone = "master"
}
```

**Comment by Al2Klimov** [comment]
So one gets the error I've described above only while creating ApiUsers w/ a password attribute. Is there anything special about the password attribute?

**Comment by Yonas-net** [comment]
As far as I can estimate the ``password`` attribute is classified as Field Attribute ``NoUserModify``.

**Comment by Al2Klimov** [comment]
What happens if you change that?

**Comment by Yonas-net** [comment]
After I invalidated the bitwise check of the If condition, I was able to create a user with the password attr.

Command: ``curl -sSku root:af2c18268fe250b7 https://127.0.0.1:5665/v1/objects/apiusers/icinga\?pretty\=1 -X PUT -H 'Accept: application/json' -d '{"attrs":{ "password": "password" }}'``

Result:
```
{
    "results": [
        {
            "code": 200.0,
            "status": "Object was created"
        }
    ]
}% 
```

And in the .conf file looks like as follows:
```
object ApiUser "icinga" {
	password = "password"
	version = 1602240221.904256
	zone = "master"
}
```

**Comment by Al2Klimov** [comment]
> After I invalidated the bitwise check of the If condition,

Congrats, you've unprotected **all** such attributes. Change only the password attribute instead.

**Comment by Yonas-net** [comment]
So I changed the password attribute accessibility from ``[no_user_view, no_user_modify]``  to  ``[no_user_view, config]`` and it works.

Command: `` curl -sSku root:af2c18268fe250b7 https://127.0.0.1:5665/v1/objects/apiusers/icinga\?pretty\=1 -X PUT -H 'Accept: application/json' -d '{"attrs":{ "password": "password" }}'``

Result:
```
{
    "results": [
        {
            "code": 200.0,
            "status": "Object was created"
        }
    ]
}% 
```

And to let you know, I have left the if condition as it was before. So with bitwise verification. 😄

**Comment by Yonas-net** [comment]
Icinga2 Log:
```
[2020-10-09 13:26:59 +0200] information/ApiListener: New client connection from [127.0.0.1]:62230 (no client certificate)
[2020-10-09 13:26:59 +0200] information/HttpServerConnection: Request: PUT /v1/objects/apiusers/icinga?pretty=1 (from [127.0.0.1]:62230), user: root, agent: curl/7.64.1).
[2020-10-09 13:26:59 +0200] information/ConfigObjectUtility: Created and activated object 'icinga' of type 'ApiUser'.
[2020-10-09 13:26:59 +0200] information/HttpServerConnection: HTTP client disconnected (from [127.0.0.1]:62230)
```

**Comment by Al2Klimov** [comment]
With this change create an ApiUser w/ a password, fetch that user and share the curl output.

**Comment by Yonas-net** [comment]
Didn't I do that above, or do you want me to add zone attr as well, like below?

Command: ``curl -sSku root:af2c18268fe250b7 https://127.0.0.1:5665/v1/objects/apiusers/icinga\?pretty\=1 -X PUT -H 'Accept: application/json' -d '{"attrs":{ "zone": "master", "password": "secret" }}'``

Result:
```
{
    "results": [
        {
            "code": 200.0,
            "status": "Object was created"
        }
    ]
}% 
```

**Comment by Al2Klimov** [comment]
> fetch that user and share the curl output.

> Didn't I do that above,

No.

**Comment by Yonas-net** [comment]
> No.

But Now 😆:

Command: ``curl -sSku root:af2c18268fe250b7 https://127.0.0.1:5665/v1/objects/apiusers/icinga\?pretty\=1 -X POST -H 'Accept: application/json' -d '{"attrs":{  }}'``

Result:
```
{
    "results": [
        {
            "code": 200.0,
            "name": "icinga",
            "status": "Attributes updated.",
            "type": "ApiUser"
        }
    ]
}% 
```

**Comment by Yonas-net** [comment]
hashed password is not there because the password accessibility  is ``no_user_view``.

**Comment by Al2Klimov** [comment]
Show me this in the curl output.

**Comment by Yonas-net** [comment]
> Show me this in the curl output.

```
{
    "results": [
        {
            "attrs": {
                "__name": "icinga",
                "active": true,
                "client_cn": "",
                "ha_mode": 0.0,
                "name": "icinga",
                "original_attributes": {
                    "password": "secret"
                },
                "package": "_api",
                "paused": false,
                "permissions": null,
                "source_location": {
                    "first_column": 0.0,
                    "first_line": 1.0,
                    "last_column": 22.0,
                    "last_line": 1.0,
                    "path": "/Users/yhabteab/Workspace/icinga2/prefix/var/lib/icinga2/api/packages/_api/c0d54f92-7f8b-4a57-aaa3-e601e18b9154/conf.d/apiusers/icinga.conf"
                },
                "templates": [
                    "icinga"
                ],
                "type": "ApiUser",
                "version": 1602244340.031547,
                "zone": "master"
            },
            "joins": {},
            "meta": {},
            "name": "icinga",
            "type": "ApiUser"
        }
    ]
}%  
```

**Comment by Al2Klimov** [comment]
>                 "original_attributes": {
>                     "password": "secret"
>                 },

Does this also appear w/o your change?

**Comment by Yonas-net** [comment]
Of course not, if the user can't even modify the password attr, how should something appear here.

By the way, when I tried to query the user created with the changes the following came up.

```
{
    "results": [
        {
            "attrs": {
                "__name": "icinga",
                "active": true,
                "client_cn": "",
                "ha_mode": 0.0,
                "name": "icinga",
                "original_attributes": null,
                "package": "_api",
                "paused": false,
                "permissions": null,
                "source_location": {
                    "first_column": 0.0,
                    "first_line": 1.0,
                    "last_column": 22.0,
                    "last_line": 1.0,
                    "path": "/Users/yhabteab/Workspace/icinga2/prefix/var/lib/icinga2/api/packages/_api/c0d54f92-7f8b-4a57-aaa3-e601e18b9154/conf.d/apiusers/icinga.conf"
                },
                "templates": [
                    "icinga"
                ],
                "type": "ApiUser",
                "version": 1602244340.031547,
                "zone": "master"
            },
            "joins": {},
            "meta": {},
            "name": "icinga",
            "type": "ApiUser"
        }
    ]
}% 
```

and the modified-attributes.conf file is empty.

**Comment by Al2Klimov** [comment]
1. Open a PR w/ your changes.
2. Figure out how to avoid this:

>                 "original_attributes": {
>                     "password": "secret"
>                 },

**Comment by Yonas-net** [comment]
After changing the accessibility order of  ``[no_user_view, config]``  -> ``[config, no_user_view]`` it seems to work fine.
