### ISSUE TITLE
Ship the Powershell plugins' command definitions in the ITL

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#8172]
## Is your feature request related to a problem? Please describe.

At the moment our Powershell plugins are easily available only to Director users.

## Describe the solution you'd like

An extra commands config file.

**Comment by Al2Klimov** [comment]
_bump_

**Comment by haxtibal** [comment]
Guess I can contribute the command definitions if you're interested (auto-generated by parsing Arguments tables from [icinga-powershell-plugins/doc/plugins/*.md](https://github.com/Icinga/icinga-powershell-plugins/tree/master/doc/plugins)) .

Please leave a short note here in case you're already working on it at your side, to stop me from bringing a PR into shape.

**Comment by Al2Klimov** [comment]
Thanks, but I've intentionally assigned @LordHepipud as he spoke about a PS -> doc auto-generator or something.

**Comment by LordHepipud** [comment]
Hello,

yes I want the CheckCommand configuration be automated entirely. There was just no time yet to complete this task. Icinga for Windows right now already supports to create Icinga Director Baskets for check commands and should be capable to write plain .conf files as well in the future.

At the moment there are other tasks more important, but I'm planning to either implement this with v1.3.0 already or with v1.4.0

**Comment by dgoetz** [comment]
@LordHepipud: This is now available with https://github.com/Icinga/icinga-powershell-framework/releases/tag/v1.3.0, correct? How about adding some lines to Icinga 2 docs on creating and integrating the CheckCommand definitions (with and without Director) and resolving this issue? 
I could jump in if needed as I want to have it in the training material, but would be happy if I can take it simply from official docs. ;-)

**Comment by LordHepipud** [comment]
Yes, the Icinga configuration is now shipping with every release of plugins and can be downloaded directly from the repositories. In addition the plugin configuration writer now also supports to write plain Icinga 2 `.conf` files besides the `.json` baskets

**Comment by Al2Klimov** [comment]
Admittedly this is a bad idea (in contrast to #5912). Commands on some nodes have to match in case of command endpoints. If we do this, users would have to update all Windows agents just to update the ITL, so that it matches the satellite's one. In contrast, now users generate one config/basket, throw it at the Director and magic happens.
