### ISSUE TITLE
templates doesn't have any effect

### ISSUE THREAD

**Issue by formorer** [Icinga/icinga2#8178]
## Describe the bug

The Terraform terraform only allows to use the templates = [ "template" ] notation. Unfortunately it seems that it doesn't have 
any effect.

## To Reproduce

I can reproduce this with config files:

```
template Host "foo" {
  vars.foo = "bar"
}

object Host "bar" {
  templates = [ "foo" ]
  check_command = "dummy"
}
```

Restarting Icinga and asking the API, tells me that the template is defined:

```
http -a root:$ICINGA_PASSWORD --verify no https://localhost:5665/v1/objects/hosts  | jq ".results[].attrs.templates"
[
  "foo"
]
```

But:
```
http -a root:$ICINGA_PASSWORD --verify no https://localhost:5665/v1/objects/hosts  | jq ".results[].attrs.vars"
null
```

When using import we get the interestring effect that there is also a template defined like the host:

```
http -a root:$ICINGA_PASSWORD --verify no https://localhost:5665/v1/objects/hosts  | jq ".results[].attrs.templates"
[
  "bar",
  "foo"
]
```

And now we have: 

```
http -a root:$ICINGA_PASSWORD --verify no https://localhost:5665/v1/objects/hosts  | jq ".results[].attrs.vars"
{
  "foo": "bar"
}
```

Also adding the hostname to the list of templates doesn't have any effect. 

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):  2.11.4 
* Operating System and version: Debian 10
* Enabled features (`icinga2 feature list`): api checker debuglog mainlog notification

**Comment by Al2Klimov** [comment]
You have to import the template explicitly.

**Comment by formorer** [comment]
That doesn't help me. This should work as documented, why doesn't it work?
