### ISSUE TITLE
default for bind_host apilistener sometimes only listens for ipv4

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icinga2#8183]
hi,
I have 2 icinga2 instances here, that with a default of no value for bind_host only listen to ipv4. I also have icinga2 instances on which it binds correct.

```
$ icinga2 object list --type ApiListener | grep bind
  * bind_host = ""
  * bind_port = "5665"
```

https://icinga.com/docs/icinga2/latest/doc/09-object-types/#apilistener

> Optional. The IP address the api listener should be bound to. If not specified, the ApiListener is bound to :: and listens for both IPv4 and IPv6 connections.

The config is identical on all server, there has to be some kind of auto magic that decides whether to bind to 0.0.0.0:5665 or *:5665. 
The icinga log always reports

> information/ApiListener: Started new listener on '[0.0.0.0]:5665'

Even when it is actually *:5665

explicitly setting bind_host to :: allows servers that would only listen to ipv4 otherwise to listen to both. What is the difference between the default of no value and ::?

It is persistent across service restarts.

* Version used (`icinga2 --version`): r2.12.0-1 and v2.12.0-rc1-72-g2648a82de
* Operating System and version: debian stretch & buster with kernels 4.9,4.19 and 5.4

**Comment by Al2Klimov** [comment]
Hello @mphilipps and thank you for reporting!

Please tell on which protocol Icinga listens, the Icinga and Linux distro versions per instance.

Best,
AK

**Comment by mphilipps** [comment]
| Distro | icinga version | Kernel | bound |
| --- | --- | --- | --- |
| Debian stretch | r2.12.0-1 | 4.9.0 | *:5665 |
| Debian buster  | v2.12.0-rc1-72-g2648a82de | 4.19.0 | 0.0.0.0:5665 |
| Debian buster | r2.12.0-1 | 5.4.0 | 0.0.0.0:5665 |
| Debian buster | r2.12.0-1 | 4.19.0 | 0.0.0.0:5665 |

I am a bit surprised. I though the last time I checked,  the last server in the table was using *:5665. So maybe it is an issue with debian buster?

**Comment by Al2Klimov** [comment]
For me both distro versions, updated or not listen on `0.0.0.0:5665`.

**Comment by mphilipps** [comment]
So no IPv6? Despite what it says in the docu?

**Comment by Al2Klimov** [comment]
> what it says in the docu

Where exactly?

**Comment by mphilipps** [comment]
https://icinga.com/docs/icinga2/latest/doc/09-object-types/#apilistener

| Name | Type | Description |
| --- | --- | --- |
| bind_host | String | Optional. The IP address the api listener should be bound to. If not specified, the ApiListener is bound to :: and listens for both IPv4 and IPv6 connections. |

**Comment by mphilipps** [comment]
In case it matters, on redhat 7 it binds to *:5665.

```
$ ss -ltnp '( sport = 5665 )'
State      Recv-Q Send-Q                                                                                                                 Local Address:Port                                                                                                                                Peer Address:Port              
LISTEN     0      128                                                                                                                                *:5665                                                                                                                                           *:*                   users:(("icinga2",pid=28579,fd=19))

```

**Comment by mphilipps** [comment]
I don't think just changing the documentation is going to fix this, it would at least need to be consistent.

**Comment by julianbrost** [comment]
@mphilipps Can you please share the output of the following  from one of the systems that bind to `*:5665`?
```
python -c 'from socket import *; print(getaddrinfo(None, '5665', AF_UNSPEC, SOCK_STREAM, 0, AI_PASSIVE))'
```

If this returns `::` before `0.0.0.0`, I guess Icinga 2 will listen on IPv6 instead of IPv4 by default. But that happened on none of the systems I tried so far.

**Comment by mphilipps** [comment]
```
linux-debian-buster-64bit:~$ python -c 'from socket import *; print(getaddrinfo(None, '5665', AF_UNSPEC, SOCK_STREAM, 0, AI_PASSIVE))'
[(2, 1, 6, '', ('0.0.0.0', 5665)), (10, 1, 6, '', ('::', 5665, 0, 0))]
linux-debian-buster-64bit:~$ ss -ltnp | grep icinga
LISTEN    0         128                0.0.0.0:5665             0.0.0.0:*        users:(("icinga2",pid=23938,fd=18))
```

```
linux-debian-stretch-64bit:~$ python -c 'from socket import *; print(getaddrinfo(None, '5665', AF_UNSPEC, SOCK_STREAM, 0, AI_PASSIVE))'
[(2, 1, 6, '', ('0.0.0.0', 5665)), (10, 1, 6, '', ('::', 5665, 0, 0))]
linux-debian-stretch-64bit:~$ ss -ltnp | grep icinga
LISTEN     0      128          *:5665                     *:*                   users:(("icinga2",pid=21919,fd=18))

```

**Comment by julianbrost** [comment]
Ok, so much for that theory.

So what Icinga 2 is internally doing is the following: It inputs whatever you entered into `bind_port` into the TCP resolver from Boost.Asio which internally uses `getaddrinfo()` to resolve it to an address. It then tries all the results and uses the first one that succeeds:
https://github.com/Icinga/icinga2/blob/bee4ac7f7c091ce217604bae77e1c2aeeef56288/lib/remote/apilistener.cpp#L373-L408

So for it to end up listening on `[::]:5665`, this has to be returned first by the resolver (doesn't seem to be the case here), or binding to all previous addresses (i.e. `0.0.0.0:5665`) failed somehow. Unfortunately, if the latter happens, nothing is logged as long as some bind succeeds. But I think this should then also fail if you explicitly specify `bind_host = "0.0.0.0"`. Can you please try what happens with this?

Can you please share the output of the following on the system binding to IPv6? The relevant part of the output is between `information/ApiListener: 'api' started.` and `information/ApiListener: Started new listener on ...`.
```
strace -f -yy -e network icinga2 daemon
```

**Comment by mphilipps** [comment]
Interesting. Setting `bind_host = "0.0.0.0"`  has no affected at all. The ipv4 only system still does ipv4 only and the one that used to bind to *:5665 still does so.
However setting `bind_host = "::"` results in the ipv4 only system to listen to `*:5665`.

With `bind_host` removed from the api config again on the stretch (ipv6) system:

```
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE) = 18<NETLINK:[64694504]>
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] bind(18<NETLINK:[64694504]>, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] getsockname(18<NETLINK:[ROUTE:30531]>, {sa_family=AF_NETLINK, nl_pid=30531, nl_groups=00000000}, [12]) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] sendto(18<NETLINK:[ROUTE:30531]>, {{len=20, type=0x16 /* NLMSG_??? */, flags=NLM_F_REQUEST|0x300, seq=1607004625, pid=0}, "\0\0\0\0"}, 20, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 20
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] recvmsg(18<NETLINK:[ROUTE:30531]>, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base=[{{len=76, type=0x14 /* NLMSG_??? */, flags=NLM_F_MULTI, seq=1607004625, pid=30531}, "\2\10\200\376\1\0\0\0\10\0\1\0\177\0\0\1\10\0\2\0\177\0\0\1\7\0\3\0lo\0\0"...}, {{len=88, type=0x14 /* NLMSG_??? */, flags=NLM_F_MULTI, seq=1607004625, pid=30531}, "\2\30\200\0\2\0\0\0\10\0\1\0\n\10\6\2\10\0\2\0\n\10\6\2\10\0\4\0\n\10\6\377"...}, {{len=32765, type=0 /* NLMSG_??? */, flags=0, seq=0, pid=900645888}, ";V\0\0\1\0\0\0\0\0\0\0\240E\234\236\375\177\0\0\0\0\0\0\0\0\0\0\0./a"...}], iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 164
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] recvmsg(18<NETLINK:[ROUTE:30531]>, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base=[{{len=72, type=0x14 /* NLMSG_??? */, flags=NLM_F_MULTI, seq=1607004625, pid=30531}, "\n\200\200\376\1\0\0\0\24\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\24\0\6\0"...}, {{len=72, type=0x14 /* NLMSG_??? */, flags=NLM_F_MULTI, seq=1607004625, pid=30531}, "\n@\200\375\2\0\0\0\24\0\1\0\376\200\0\0\0\0\0\0PT\0\377\376\10\6\2\24\0\6\0"...}, {{len=393236, type=0xffff /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_MULTI|NLM_F_ACK|NLM_F_ECHO|NLM_F_DUMP_INTR|NLM_F_DUMP_FILTERED|0xffc0, seq=4294967295, pid=438}, "\266\1\0\0\375\177\0\0\0\0\0\0\0\0\0\0\0\304\2565;V\0\0\1\0\0\0\0\0\0\0"...}], iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 144
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] recvmsg(18<NETLINK:[ROUTE:30531]>, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base=[{{len=20, type=NLMSG_DONE, flags=NLM_F_MULTI, seq=1607004625, pid=30531}, "\0\0\0\0"}, {{len=1, type=0x14 /* NLMSG_??? */, flags=NLM_F_REQUEST, seq=0, pid=0}}], iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 20
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 18<UDPv6:[64694509]>
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] connect(18<UDPv6:[64694509]>, {sa_family=AF_INET6, sin6_port=htons(5665), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] getsockname(18<UDPv6:[::1:59582->::1:5665]>, {sa_family=AF_INET6, sin6_port=htons(59582), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [28]) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] connect(18<UDPv6:[::1:59582->::1:5665]>, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] connect(18<UDPv6:[::1:59582->::1:5665]>, {sa_family=AF_INET, sin_port=htons(5665), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] getsockname(18<UDPv6:[::1:59582->::1:5665]>, {sa_family=AF_INET6, sin6_port=htons(59046), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [28]) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 18<TCP:[64694513]>
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30539] +++ exited with 0 +++
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] setsockopt(18<TCP:[64694513]>, SOL_IPV6, IPV6_V6ONLY, [0], 4) = -1 ENOPROTOOPT (Protocol not available)
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] setsockopt(18<TCP:[64694513]>, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] setsockopt(18<TCP:[64694513]>, SOL_SOCKET, SO_REUSEPORT, [1], 4) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] bind(18<TCP:[64694513]>, {sa_family=AF_INET, sin_port=htons(5665), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] listen(18<TCP:[64694513]>, 2147483647) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [pid 30531] getsockname(18<TCP:[0.0.0.0:5665]>, {sa_family=AF_INET, sin_port=htons(5665), sin_addr=inet_addr("0.0.0.0")}, [28->16]) = 0
Dec 03 15:10:25 linux-debian-stretch-64bit strace[30515]: [2020-12-03 15:10:25 +0100] information/ApiListener: Started new listener on '[0.0.0.0]:5665'
```

and yes even thought it says `'[0.0.0.0]:5665'` `ss` confirms it as `*:5665`.

**Comment by julianbrost** [comment]
> bind(18<TCP:[64694513]>, {sa_family=AF_INET, sin_port=htons(5665), sin_addr=inet_addr("0.0.0.0")}, 16) = 0

Well, it looks like Icinga indeed only binds to IPv4. Might this actually be an issue with how `ss` displays the listen address? Can you please confirm if Icinga actually responds on IPv6 (`curl -vk 'https://[::1]:5666/'`)? How is the listening address shown if you let another program listen on IPv6/IPv6 only (`nc -4 -l -p 1234` and `nc -6 -l -p 1234`)?

**Comment by mphilipps** [comment]
I assume you meant `curl -vk 'https://[::1]:5665/'` and it appears as icinga2 is right ss is wrong or the output format has changed. I will do more testing tomorrow, right now the nc installed here only supports IPv4 for some reason.

**Comment by julianbrost** [comment]
Sure, should be port 5665. I think I have too many instances running locally. :smile:

**Comment by mphilipps** [comment]
I feel like `ss` is being stupid.

In order: icinga default, nc -4, nc -6
```
linux-debian-buster-64bit:~$ ss -ltnp | grep icinga
LISTEN    0         128                0.0.0.0:5665             0.0.0.0:*        users:(("icinga2",pid=25747,fd=18))                                        

linux-debian-buster-64bit:~$ ss -ltnp | grep nc
LISTEN    0         1                  0.0.0.0:1234             0.0.0.0:*        users:(("nc",pid=18722,fd=3))                                              
linux-debian-buster-64bit:~$ ss -ltnp | grep nc
LISTEN    0         1                        *:1234                   *:*        users:(("nc",pid=18813,fd=3))
linux-debian-buster-64bit:~$ ss -version
ss utility, iproute2-ss190107
```

```
linux-debian-stretch-64bit:~$ ss -ltnp | grep icinga
LISTEN     0      128          *:5665                     *:*                   users:(("icinga2",pid=14653,fd=18))
linux-debian-stretch-64bit:~$ ss -ltnp | grep nc
LISTEN     0      1            *:1234                     *:*                   users:(("nc",pid=8942,fd=3))
linux-debian-stretch-64bit:~$ ss -ltnp | grep nc
LISTEN     0      1           :::1234                    :::*                   users:(("nc",pid=9124,fd=3))
linux-debian-stretch-64bit:~$ ss --version
ss utility, iproute2-ss161212
```

After some more testing it appears that even thought the manpage for nc says:`
     -6      Use IPv6 addresses only.`. It actually binds ipv4 and ipv6.
`
$ nc -6 -l -p 1234`

```
$ exec 3<>/dev/tcp/127.0.0.1/1234
$ echo "foo" >&3
$ exec 3<&-
```
succeeds.


So my conclusion to all of this: the old version of ss used in debian stretch is bugged and it is fixed in the newer one used in buster. However I couldn't find a changelog documenting this.

With the MR #8192 the documentation would match the actual icinga behavior. At this point I still feel like binding to `::` (ipv4+ipv6) would be more desirable as a default, but I can just put a `bind_host` line my template used for generating the icinga config.

Feel free the merge the MR and close this. Thank you for your time.
