### ISSUE TITLE
SELinux error on RHEL 8 with latest agent

### ISSUE THREAD

**Issue by NielsA** [Icinga/icinga2#8187]
Hello,

I have the following SELinux denied warning in my audit.log on my RHEL8 systems. All my checks are
working fine so it doesn't really seem that harmful. 

``
type=USER_AVC msg=audit(1598082663.020:276679): pid=1385 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.121819 spid=1 tpid=1998787 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:nagios_unconfined_plugin_t:s0 tclass=dbus permissive=0  exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=? terminal=?'UID="dbus" AUID="unset" SAUID="dbus"
``

I created a temporary module in order to FIX it. 

```
allow init_t nagios_unconfined_plugin_t:dbus send_msg;
```

# System info 

Icinga : icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.0-1)
RHEL : Red Hat Enterprise Linux release 8.2 (Ootpa)
SELinux: Enforcing

```
[root@foobar selinux]# semodule -l | grep -e icinga2 -e nagios -e apache
apache
icinga2
my_icinga2
nagios
```

```
[root@foobar selinux]# ps -eZ | grep icinga2
system_u:system_r:icinga2_t:s0  1543565 ?        00:01:14 icinga2
system_u:system_r:icinga2_t:s0  1543828 ?        00:00:24 icinga2
system_u:system_r:icinga2_t:s0  1878284 ?        00:01:37 icinga2
```

```
[root@foobar selinux]# semanage port -l | grep icinga2
icinga2_port_t                 tcp      5665
```

**Comment by Al2Klimov** [comment]
@dgoetz Any idea what's the problem and whether the suggested solution is OK?

> I created a temporary module in order to FIX it.
> 
> ```
> allow init_t nagios_unconfined_plugin_t:dbus send_msg;
> ```

**Comment by dgoetz** [comment]
I found now some time to look into it and can not reproduce it.

init_t is the domain of the init daemon so in our case systemd, this should not be communicating to a monitoring plugin directly.

Can you add `-w /etc/shadow -p w` to `/etc/audit/rules.d/audit.rules`, restart the audit daemon and then look for another occurrence in the logs? I hope to see the path of the plugin so it helps to find out why something misbehaves.

**Comment by NielsA** [comment]
I have added the rule to audit.rules, restarted the audit daemon and I still have the same result.

```
## This file is automatically generated from /etc/audit/rules.d
-D
-b 8192
-f 1
-w /etc/shadow -p w
--backlog_wait_time 60000
```
```
 type=USER_AVC msg=audit(1599057644.717:739961): pid=1385 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.314707 spid=1 tpid=374878 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:nagios_unconfined_plugin_t:s0 tclass=dbus permissive=0  exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=? terminal=?'UID="dbus" AUID="unset" SAUID="dbus"
```

**Comment by NielsA** [comment]
Using the dbus-monitor command I got more information

``
error time=1599074625.220588 sender=org.freedesktop.DBus -> destination=:1.4 error_name=org.freedesktop.DBus.Error.AccessDenied reply_serial=5132793
   string "An SELinux policy prevents this sender from sending this message to this recipient, 0 matched rules; type="method_return", sender=":1.4" (uid=0 pid=1 comm="/usr/lib/systemd/systemd --switched-root --system " label="system_u:system_r:init_t:s0") interface="(unset)" member="(unset)" error name="(unset)" requested_reply="0" destination=":1.317807" (uid=0 pid=418221 comm="/usr/bin/sudo setfacl -m u:icinga:r-- /var/log/mes" label="system_u:system_r:nagios_unconfined_plugin_t:s0")"
``

**Comment by dgoetz** [comment]
Ok, still no idea why it needs systemd/dbus to execute sudo, but I have already added this with the boolean `icinga2_run_sudo` (see https://icinga.com/docs/icinga2/latest/doc/22-selinux/#running-plugins-requiring-sudo). Can you test if switching the boolean to true, fixes this for you?

**Comment by NielsA** [comment]
I just tried and I have the same problem with the boolean icinga2_run_sudo switched on 
```
[root@foobar ~]# getsebool icinga2_run_sudo
icinga2_run_sudo --> on
```

aureport
```
295. 09/04/2020 11:15:07 ? system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 0 dbus send_msg system_u:system_r:nagios_unconfined_plugin_t:s0 denied 813111
296. 09/04/2020 11:16:31 ? system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 0 dbus send_msg system_u:system_r:nagios_unconfined_plugin_t:s0 denied 813138
```

**Comment by dgoetz** [comment]
Ok, now I fully got it!

The boolean is only working for sudo around and not in the plugin. This is also why init_t is directly talking to the plugin. But in the current upstream policy is already a line `systemd_dbus_chat_logind(nagios_unconfined_plugin_t)` which indicates that someone already thought about this, but then it was systemd_logind_t instead of init_t. So I am not sure if something misbehaves or only changed and was not adjusted, but it is out of the scope I can fix in the icinga2 policy as it is defined in the nagios policy which is upstream.

So I only have two options for you, open a bug against selinux-policy upstream and reference my findings to get it fixed there or change how you run the command so it runs with sudo around the plugin instead of in it. An advanced example for this way to run the plugin would be running_kernel from the itl (https://github.com/Icinga/icinga2/blob/8c739fe33bd31dc8bc85dc0ba73c6e3185d9cb26/itl/plugins-contrib.d/operating-system.conf#L54-L74), but if this is possible without adjusting the plugin depends on how it was implemented.
