### ISSUE TITLE
Error: boost::thread_resource_error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by ctoepfl** [Icinga/icinga2#8202]
## Describe the bug

Icinga Diredtor - role out a new configuration

boost 1.66

## Your Environment
Caught unhandled exception.
Current time: 2020-08-31 11:43:15 +0200

  Application version: 2.12.0-1

System information:
  Platform: CentOS Linux
  Platform version: 8 (Core)
  Kernel: Linux
  Kernel version: 4.18.0
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.1
  Build host: runner-hh8q3bz2-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.1.1c FIPS  28 May 2019

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Error: boost::thread_resource_error: Resource temporarily unavailable

        (0) icinga2: icinga::WorkQueue::EnqueueUnlocked(boost::unique_lock<boost::mutex>&, std::function<void ()>&&, icinga::WorkQueuePriority) (+0x1203) [0xae04d3]
        (1) icinga2: icinga::ConfigItem::CommitNewItems(boost::intrusive_ptr<icinga::ActivationContext> const&, icinga::WorkQueue&, std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> > >&) (+0x6eb) [0xa5645b]
        (2) icinga2: icinga::ConfigItem::CommitItems(boost::intrusive_ptr<icinga::ActivationContext> const&, icinga::WorkQueue&, std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> > >&, bool) (+0xc3) [0xa56f83]
        (3) icinga2: icinga::DaemonUtility::LoadConfigFiles(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> > >&, icinga::String const&, icinga::String const&) (+0xe7) [0x95d827]
        (4) icinga2: icinga::DaemonCommand::Run(boost::program_options::variables_map const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const (+0x281) [0x95e701]
        (5) /usr/lib64/icinga2/sbin/icinga2() [0xb5de22]
        (6) icinga2: main (+0xb8) [0x6a70f8]
        (7) libc.so.6: __libc_start_main (+0xf3) [0x2abef83be6a3]
        (8) icinga2: _start (+0x2e) [0x6a717e]

***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***

**Comment by mcktr** [comment]
Hi,

this error message indicates that your system does not have any resources available. 

I am closing this in favor of #6600.

Best regards
Michael
