### ISSUE TITLE
check_tcp ITL incompatibility between monitoring-plugins and nagios-plugins

### ISSUE THREAD

**Issue by pprkut** [Icinga/icinga2#8208]
#7741 changed parameter names for check_tcp to update for a change in monitoring plugins. Unfortunately, this change in monitoring plugins is incompatible with the version of check_tcp shipped with nagios-plugins.

There's no monitoring-plugins rpm for RHEL/CentOS users and nagios-plugins is still recommended to be installed there per icinga documentation (https://icinga.com/docs/icinga2/latest/doc/02-installation/#rhelcentosfedora).

IMHO either the shipped ITL should work with both versions, or there should be a monitoring-plugins rpm for RHEL/CentOS users to switch to.

**Comment by pprkut** [comment]
Perhaps the path of least resistance is to rename the parameter in monitoring plugins from `--sni` to `-N`, and then revert the ITL change?

I see there was previous discussion going on but can't really follow the reasoning :-/

**Comment by mcktr** [comment]
Hi,

an incompatibility issue like this pops up over and over again, the two plugin packages `monitoring-plugins` and `nagios-plugins` are simply not compatible and honestly never will be. 

@N-o-X Would it be possible to provide the `monitoring-plugins` package for RHEL/CentOS trough the Icinga repositories? 

Best regards
Michael

**Comment by Al2Klimov** [comment]
_PING_ @N-o-X

**Comment by Seegras** [comment]
What's the status here? There are no nagios-plugins on Ubuntu, and monitoring-plugins check_tcp doesn't understand --sni.

**Comment by Al2Klimov** [comment]
@htriem I'd like to know especially:

> Would it be possible to provide the `monitoring-plugins` package for RHEL/CentOS trough the Icinga repositories?

**Comment by lippserd** [comment]
> @htriem I'd like to know especially:
> 
> > Would it be possible to provide the `monitoring-plugins` package for RHEL/CentOS trough the Icinga repositories?

I can answer that: no.

**Comment by lippserd** [comment]
> [...] monitoring-plugins check_tcp doesn't understand --sni.

It [should](https://github.com/monitoring-plugins/monitoring-plugins/pull/1614) actually. Maybe only a release is missing.

**Comment by Al2Klimov** [comment]
> Perhaps the path of least resistance is to rename the parameter in monitoring plugins from `--sni` to `-N`, and then revert the ITL change?

I don’t think so...

> I see there was previous discussion going on but can't really follow the reasoning :-/

... as [the reasoning](https://github.com/monitoring-plugins/monitoring-plugins/pull/1614#issuecomment-571506042) was doing it like check_http.

**Comment by Al2Klimov** [comment]
> Would it be possible to provide the `monitoring-plugins` package for RHEL/CentOS trough the Icinga repositories?

Maybe our NETWAYS colleagues are so kind and package those in _their_ repos.

CC @RincewindsHat

**Comment by RincewindsHat** [comment]
I am not totally opposed to that idea, but that requires time and effort. Not sure, if I can provide a time frame for that

**Comment by RincewindsHat** [comment]
In the mean time: (Open)Suse builds RPMs, not sure how they are doing on RHEL

**Comment by Al2Klimov** [comment]
If they don't work OOTB, they _may_ be rebuilt from source.
