### ISSUE TITLE
retry_interval is not consistent

### ISSUE THREAD

**Issue by SushanSuresh** [Icinga/icinga2#8216]
Hi,

I am facing a issue with icinga service retry_interval, I have configured a icinga service checks and set check_interval to 60sec and retry_interval to 40sec. but some time these retry_interval is not respected by icinga and changes randomly like 10sec 30sec etc.

## Expected Behavior
on service criticality icinga should check the service at the interval mentioned at retry_interval before sending the notification.

## Current Behavior
icinga retries checks on random interval and triggers notification which is creating problem since total retry interval time is less.

## Your Environment
* Version used (`icinga2 --version`):
_icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.2-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 16.04.5 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-1109-aws
  Architecture: x86_64

Build information:
  Compiler: GNU 5.4.0
  Build host: runner-LTrJQZ9N-project-298-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
<img width="440" alt="Screenshot 2020-09-04 at 2 00 23 PM" src="https://user-images.githubusercontent.com/26277576/92384595-fd142680-f12d-11ea-8012-d44922ce5a38.png">
_

* Enabled features (`icinga2 feature list`):
_Enabled features: api checker command idopgsqlconnection mainlog notification_

* Icinga Web 2 version and modules (System - About):
_Icinga Web 2 Version
_2.7.3
Git commit
06cabfe8ba28cf545a42c92f25484383191a4e51
PHP Version
7.0.33-14+ubuntu16.04.1+deb.sury.org+1
Git commit date
2019-10-18_

**Comment by sowhatim** [comment]
Facing the same issue where retry_interval is random almost always. No response on the ticket o.O

**Comment by sowhatim** [comment]
Hi @julianbrost , thank you for getting back to this problem.

- yes the cluster is top down as recommended. And the affected services are on the node which receives config updates from the parent node.
- nope, this is not related to config reload, this happens everytime in my case. Like if I make service critical anytime, we can see the retry_interval being random. 
- nope, this doesn't take long to execute. Its' simple linux `service status` check.
- currently we have 40+ nodes in the cluster. we have 2 masters and 2 satellites. 
  the issues happens on every node. 

I have attached the the zone file on an agent node.
![image](https://user-images.githubusercontent.com/9086206/96143904-39068c80-0f21-11eb-9bb9-c997685e288a.png)
 
this is behaviour that we see on service being critical. retry_interval is not respected 
![image](https://user-images.githubusercontent.com/9086206/96143582-d9a87c80-0f20-11eb-95da-c5627c1786ba.png)

**Comment by julianbrost** [comment]
Sounds like this is fairly easy to reproduce in your setup. Can you please enable the [debug log](https://icinga.com/docs/icinga2/latest/doc/15-troubleshooting/#enable-debug-output) on one of the affected nodes and share it?

**Comment by sowhatim** [comment]
![image](https://user-images.githubusercontent.com/9086206/97453869-29913580-195c-11eb-8eed-ba70b08a9f9f.png)

Hi @julianbrost , apologies for the delay in the response. Please find the details here for one of the affected node.
The service in question is `ops-zl-services-meta` on node ops_base_2. 
You can check the service being getting into critical state first at [2020-10-28 14:56:05 +0000] in the debug logs attached and then the second occurennce at [2020-10-28 14:56:32 +0000] but then then the next retry just at [2020-10-28 14:56:45 +0000]. Same way, 4th retry is again earlier than expected.
[ops_base_2-icinga-debug.log](https://github.com/Icinga/icinga2/files/5452825/ops_base_2-icinga-debug.log)

This is the config being applied here:
template Service "product-service" {
  max_check_attempts = 4
  check_interval = 1m
  retry_interval = 40s
}

Let me know if I can provide anything else for further debugging.

**Comment by julianbrost** [comment]
Looking at the log before the service went critical, it was checked twice each minute, once due to an ExecuteCommand from ops-icinga-s2.ops.prod.node and once due to one from ops-icinga-s1.ops.prod.node:

```
[2020-10-28 14:53:05 +0000] notice/JsonRpcConnection: Received 'event::ExecuteCommand' message from 'ops-icinga-s2.ops.prod.node'
[2020-10-28 14:53:05 +0000] notice/Process: Running command '/etc/icinga2/scripts/check_service.sh' '-o' 'linux' '-s' 'ops-zl-services-meta': PID 18616
[2020-10-28 14:53:05 +0000] notice/Process: PID 18616 ('/etc/icinga2/scripts/check_service.sh' '-o' 'linux' '-s' 'ops-zl-services-meta') terminated with exit code 0
[2020-10-28 14:53:05 +0000] notice/ApiListener: Sending message 'event::CheckResult' to 'ops-icinga-s2.ops.prod.node'
[2020-10-28 14:53:32 +0000] notice/JsonRpcConnection: Received 'event::ExecuteCommand' message from 'ops-icinga-s1.ops.prod.node'
[2020-10-28 14:53:32 +0000] notice/Process: Running command '/etc/icinga2/scripts/check_service.sh' '-o' 'linux' '-s' 'ops-zl-services-meta': PID 19037
[2020-10-28 14:53:32 +0000] notice/Process: PID 19037 ('/etc/icinga2/scripts/check_service.sh' '-o' 'linux' '-s' 'ops-zl-services-meta') terminated with exit code 0
[2020-10-28 14:53:32 +0000] notice/ApiListener: Sending message 'event::CheckResult' to 'ops-icinga-s1.ops.prod.node'
```

These checks happened precisely at seconds 05 and 32 each minute. The times when the critical checks happend are 14:56:05, 14:56:32, 14:56:45, 14:57:11, 14:57:25. This looks just like both 60 second schedules switch over to 40 seconds.

So it clearly looks like two nodes are independently scheduling checks for this service, now we just have to figure out why. @N-o-X @Al2Klimov Do you have an idea?

**Comment by N-o-X** [comment]
@julianbrost yes, it seems like those satellites don't know about each other.

@sowhatim have you configured your satellites to connect to each other? They need to know each other, just like your masters. Could you provide us with the `zones.conf` of both satellites?

**Comment by sowhatim** [comment]
@julianbrost @N-o-X 

Here is the satellite zone.conf 

`object Zone "director-global" {
  global = true
}

object Zone "global-commands" {
  global = true
}

object Zone "global-templates" {
  global = true
}

object Zone "master" {
  endpoints = ["ops-icinga-m1.ops.prod.node", "ops-icinga-m2.ops.prod.node"]
}

object Zone "satellite" {
  endpoints = ["ops-icinga-s1.ops.prod.node", "ops-icinga-s2.ops.prod.node"]
  parent = "master"
}
`

It's the same as master's zone.conf.

**Comment by N-o-X** [comment]
@sowhatim okay, where do you configure your endpoints?

**Comment by sowhatim** [comment]
satellite endpoint.conf(same for master too) :

`object Endpoint "ops-icinga-m1.ops.prod.node" {
  port = 5665
  log_duration = 1h
}

object Endpoint "ops-icinga-m2.ops.prod.node" {
  port = 5665
  log_duration = 1h
}

object Endpoint "ops-icinga-s1.ops.prod.node" {
  port = 5665
  log_duration = 1h
}

object Endpoint "ops-icinga-s2.ops.prod.node" {
  port = 5665
  log_duration = 1h
}
`
zone.conf and endpoint.conf resides in /etc/icinga2 and icinga2.conf  in the same dir has 

`include "zone.conf"`
`include "endpoint.conf"`

**Comment by sowhatim** [comment]
Update - master endpoint.conf is a bit different and it includes host param as well:

`object Endpoint "ops-icinga-m1.ops.prod.node" {
  host = "10.1.4.80"
  port = 5665
  log_duration = 1h
}

object Endpoint "ops-icinga-m2.ops.prod.node" {
  host = "10.1.4.21"
  port = 5665
  log_duration = 1h
}

object Endpoint "ops-icinga-s1.ops.prod.node" {
  host = "10.1.4.35"
  port = 5665
  log_duration = 1h
}

object Endpoint "ops-icinga-s2.ops.prod.node" {
  host = "10.1.4.32"
  port = 5665
  log_duration = 1h
}
`

**Comment by N-o-X** [comment]
That's your issue. Your satellites need to connect to each other. At least one of them should have the `host` parameter configured so they connect.

**Comment by sowhatim** [comment]
@N-o-X - Ah, right. I see. Let me fix this up and update here.

**Comment by sowhatim** [comment]
yeah, this worked for me. Getting consistent checks now. 
This will be really important as it was breaking the whole monitoring system. 

Thanks so much @N-o-X , @julianbrost  for your help.

**Comment by SushanSuresh** [comment]
Thanks every one for help.
