### ISSUE TITLE
ICINGA agent  windows consuming maximum of virtual memory

### ISSUE THREAD

**Issue by GunalanD95** [Icinga/icinga2#8223]
Description:
 we are using windows server 2012 2016 versions

We are using icinga agent version 2.10.5, since the windows servers has got **.Net version 4.5.x due to dependancy cannot upgrade to 4.6**

The eventlog of the server says

Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: icinga2.exe (3368) consumed 32058224640 bytes,  mcshield.exe (3244) consumed 357441536 bytes, and sqlservr.exe (3320) consumed 293003264 bytes.

event id 2004

Resource Exhaustion Diagnosis Events
What happens ist, that the agent consumes all of the RAM available, leading to an unresponsive server. No RDP login possible,  As soon as I restart the Icinga2 service, the server comes back to live.

**Comment by lippserd** [comment]
ref/IP/27589

**Comment by lippserd** [comment]
We didn't discuss this issue on Github. We have noticed some anomalies with recurring inbound connections to the agent that may have increased memory consumption. Apart from that, we suggested upgrading to a current version of Icinga. If the problem persists, please open a new issue.
