### ISSUE TITLE
Icinga 2 doesn't change status of services with active_checks_enabled=false once removed and added again

### ISSUE THREAD

**Issue by Crited** [Icinga/icinga2#8237]
## Describe the bug
Icinga 2 doesn't change status of passive checks once removed and added again. Icinga Web 2 relies completely on `has_been_checked: 1` becoming false again to get back to pending (as internal state = 99) or state being changed based on an active check. If that is disabled, the former/current outcome will continue to stay in the database while Icinga 2 internally and exposed by the API has state 3 (UNKNOWN).

Could be based on this: https://github.com/Icinga/icingaweb2/blob/25e1942a9b8388f082a0bc41d0ac198cae960311/modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php#L280

So as soon as a service is removed and set inactive (is_active=0 in icinga_objects). Service status is been kept, so `has_been_checked` is still 1 and the `current_state`, which is the last state is continuously used.

Furthermore, when querying the API there is no pending state, but the services are shown if you filter for 'Unknown'. This has been a very confusing behaviour for a customer. 

I consider this a Icinga 2 bug, because it regards to the API and IDO database.
## To Reproduce
1. Create passive check service like this:
```
object Service "passive" {
  check_command = "dummy"
  vars.dummy_state = 3

  passive_checks_enabled = true
  active_checks_enabled = false
  ...
}
```
2. Set the service in Icinga Web 2 to OK (0)
3. Remove the service and reload.
4. Add it again and reload.
-> Service is still OK (0) in Icinga Web 2

## Expected behaviour
Service gets back to pending in Icinga Web 2 and pending state is available via API so there is a consistent behaviour.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): latest(2.12.0) & 2.11.5
* Icinga 2 version used (`icinga2 --version`): latest(2.12.0) & 2.11.5
* PHP version used (`php --version`): 7.3
* Server operating system and version: Centos 7

## Additional Details
ref/NC/689603

**Comment by Al2Klimov** [comment]
@lippserd How'd you expect Icinga to behave?

**Comment by Al2Klimov** [comment]
_PING_ @lippserd

**Comment by lippserd** [comment]
The problem here is the database, in which the status information of deleted objects remains: #5621

But, this will not be fixed for the IDO because the Icinga DB GA is on the way, which does not have this problem.
