### ISSUE TITLE
status object accessor function for monitoring ido work queue.

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icinga2#8304]
hi,
## Is your feature request related to a problem? Please describe.
I would like to monitor the size of the ido work queue, in the past we had an issues like:

`information/WorkQueue: #7 (IdoPgsqlConnection, ido-pgsql) items: 256896, rate: 271.4/s (16284/min 75599/5min 222109/15min); empty in 2 hours, 3 minutes and 2 seconds`

## Describe the solution you'd like

I would like to have an [object accessor function](https://icinga.com/docs/icinga2/latest/doc/18-library-reference/#object-accessor-functions) to access the status 'object' usually reached through /v1/status

## Describe alternatives you've considered

I could read the log file or call the api from the check command. However using the rest api to talk to your self feels a bit silly/inefficient, would be much nicer to have a get_status() function and then be able to read it's attributes.

**Comment by Al2Klimov** [comment]
Hello @mphilipps and thanks for the suggestion!

Would respective perfdata from a built-in Icinga check be fine as well?

Best,
AK

**Comment by mphilipps** [comment]
Of course not having to write the check myself would also be fine.

**Comment by Al2Klimov** [comment]
Does [this one](https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#ido) fit your needs?

**Comment by mphilipps** [comment]
Yes, sorry didn't new this exists. My bad.
