### ISSUE TITLE
On ScheduledDowntime change: remove downtimes created before change

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#8309]
## Is your feature request related to a problem? Please describe.

@julianbrost changed a ScheduledDowntime (monday, ..., friday => monday - friday), but the change didn't apply to the already created downtimes.

## Describe the solution you'd like

* On downtime creation: Hash and store relevant ScheduledDowntime attrs
* Regularily: Hash relevant ScheduledDowntime attrs and compare with stored hash; differ => delete downtime

Due to the already created downtime disappears, it will be re-created automatically with the new, correct attrs.

## Describe alternatives you've considered

To have to remove the already created downtime's config manually and to reload Icinga.

**Comment by widhalmt** [comment]
ref/NC/702456

**Comment by Wintermute2k6** [comment]
ref/NC/704080
