### ISSUE TITLE
crash while reloading

### ISSUE THREAD

**Issue by Sec42** [Icinga/icinga2#8384]
## Describe the bug

icinga2 was reloaded via ansible, shortly thereafter icinga2 crashed.

## To Reproduce

1. service icinga2 reload

## Expected behavior

no crash

## Your Environment

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.3-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1127.18.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Enabled features (`icinga2 feature list`):
Enabled features: api checker graphite ido-pgsql mainlog notification syslog

## Additional context

Last log messages: (munnvmonpmac11 is the local server in question)
```
[2020-10-15 07:50:41 +0000] warning/PluginCheckTask: Check command for object 'munnvmonpmac11' (PID: 24772, arguments: '/usr/lib64/nagios/plugin
s/check_procs' '-a' 'syslog-ng' '-c' '1:1' '-p' '1' '-u' 'root' '-w' '1:9999') terminated with exit code 128, output: PROCS OK: 1 process with a
rgs 'syslog-ng', PPID = 1, UID = 0 (root) | procs=1;1:9999;1:1;0;

[2020-10-15 07:50:41 +0000] critical/Process: Fork failed with error code 0 (Success)
Context:
        (0) Executing remote check for object 'munnvmonpmac11'

[2020-10-15 07:50:41 +0000] warning/Process: PID 24771 ('/usr/lib64/nagios/plugins/check_ping' '-4' '-H' 'mlsnvmonpqmc01' '-c' '5000,100%' '-w' 
'3000,80%') died mysteriously: waitpid failed
[2020-10-15 07:50:41 +0000] warning/Process: PID 24794 ('/usr/lib64/nagios/plugins/check_ping' '-4' '-H' '10.2.130.17' '-c' '5000,100%' '-w' '30
00,80%') died mysteriously: waitpid failed
[2020-10-15 07:50:41 +0000] warning/PluginCheckTask: Check command for object 'mlsnvmonpqmc01' (PID: 24771, arguments: '/usr/lib64/nagios/plugin
s/check_ping' '-4' '-H' 'mlsnvmonpqmc01' '-c' '5000,100%' '-w' '3000,80%') terminated with exit code 128, output: PING OK - Packet loss = 0%, RT
A = 0.46 ms|rta=0.461000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0

[2020-10-15 07:50:41 +0000] warning/PluginCheckTask: Check command for object 'munnvpdehc1pes7' (PID: 24794, arguments: '/usr/lib64/nagios/plugi
ns/check_ping' '-4' '-H' '10.2.130.17' '-c' '5000,100%' '-w' '3000,80%') terminated with exit code 128, output: PING OK - Packet loss = 0%, RTA 
= 0.57 ms|rta=0.571000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0

[2020-10-15 07:50:41 +0000] critical/Application: Error: [json.exception.parse_error.101] parse error at line 1, column 27: syntax error while p
arsing value - unexpected '{'; expected end of input



Additional information is available in '/var/log/icinga2/crash/report.1602748241.329181'
```

The crash file contains the following backtrace:

```
        (0) icinga2: icinga::JsonDecode(icinga::String const&) (+0xe99) [0x908be9]
        (1) icinga2: icinga::Process::DoEvents() (+0x284) [0x991fa4]
        (2) icinga2: icinga::Process::IOThreadProc(int) (+0x399) [0x993559]
        (3) libstdc++.so.6: <unknown function> (+0xb5070) [0x7fccd5f8d070]
        (4) libpthread.so.0: <unknown function> (+0x7ea5) [0x7fccd57abea5]
        (5) libc.so.6: clone (+0x6d) [0x7fccd54d48dd]
```

**Comment by Al2Klimov** [comment]
Hello @Sec42 and thank you for reporting!

Please try these artifacts: https://git.icinga.com/packaging/rpm-icinga2/-/jobs/69841

Best,
AK

**Comment by Sec42** [comment]
Sorry. I've not been able to reproduce this error, so I don't think I can properly test this change. But the code change looks sensible. Thanks.
