### ISSUE TITLE
Can't setup Windows Dev Environment

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#8395]
## Describe the bug

... as I can't install wixtoolset.

## To Reproduce

1. Setup a fresh Win10 machine in https://cloud.netways.de/
2. [Install Chocolatey](https://github.com/Icinga/icinga2/blob/327377a7c/doc/21-development.md#chocolatey)
3. [Install wixtoolset](https://github.com/Icinga/icinga2/blob/327377a7c/doc/21-development.md#packages)

## Expected behavior

It just works.

## Screenshots

![Bildschirmfoto 2020-10-23 um 13 41 37](https://user-images.githubusercontent.com/6053266/97006057-8eedbc80-153f-11eb-9a81-76395de4890f.png)
![Bildschirmfoto 2020-10-23 um 14 48 14](https://user-images.githubusercontent.com/6053266/97006043-8bf2cc00-153f-11eb-9a2f-a7c14ce842f1.png)

**Comment by julianbrost** [comment]
Can't remember having something like this when I followed the instructions about two weeks ago. Looks more like a problem with Chocolatey than Icinga, I'd say?

**Comment by Al2Klimov** [comment]
_I'd_ say _we shall_ have instructions that actually work.

**Comment by julianbrost** [comment]
Looks like .NET 3.5 just wants a reboot. Rebooting and running the same command again works. Alternatively you can run `Enable-WindowsOptionalFeature -FeatureName "NetFx3" -Online` first, which will ask you to reboot. I'll prepare a PR next week.
