### ISSUE TITLE
Connection leak with outgoing anonymous connections to agents with a mismatching CA

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#8478]
If a master or satellite connects to its agents and these have configured certificates from a different CA (important: each node has to have a set of consistent ca.crt/agent.crt/agent.key), a new connection for each agent is attempted every 10 seconds and never closed.

There are already a few pull requests that try to improve/fix this situation but no ticket so far, this is just a very short description of the problem to have one issue to link the PRs to.

**Comment by julianbrost** [comment]
As far as I can tell (correct me if I'm wrong), anonymous connections are only used for certificate requests (`pki::RequestCertificate`) and their responses (`pki::UpdateCertificate`) and the responses messages are only sent from within the request handler, i.e. the endpoint has to poll in order to receive a certificate and this is done once when the connection is established.

So in a working setup, the following happens: every 10 seconds, a connection is established from/to an endpoint that has no valid certificate so far, it sends a certificate request and may or may not receive a certificate almost instantly. The parent endpoint will then close the connection after the certificate request was processed: https://github.com/Icinga/icinga2/blob/8ca765d730efb45eb99bb25bef916955df380dd5/lib/remote/jsonrpcconnection-pki.cpp#L252-L258

In order for the child to send a certificate request, it has to have an authenticated connection (note: both endpoints may have a different view whether a connection is anonymous or authenticated). However, in the situation leading to this bug, the child will also see this as an anonymous connection and never send a certificate request and the connection will live forever.

Therefore I think the best fix will be introducing a timeout for anonymous connections so that a certificate request has to be sent within say 10 seconds or the connection will be closed.

**Comment by N-o-X** [comment]
Resolved by #8482
