### ISSUE TITLE
Random crashes from Icinga Agents on Windows after Deployments

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga2#8480]
## Describe the bug

Since a few weeks, we are facing some issues with our Icinga Agent setups on Windows. We hoped that this problem is gone with 2.11.6 and the fixes #8337 #8308. But it doesn’t. 

So after a while – we think since 2.11.4 – we often have the problem, that our agents are crashing without realizing a particular problem. On the other hand the agent installation on Linux is working fine. On our more than 500 Windows servers (W2012R2, W2016, W2019) not always the same servers are affected. This means that the crashes seems to have happened randomly across our server farm.

We started to write a matrix to find some similarities. What we find out, is following:
- Most of the crashes happens on W2012 R2 servers. Until now there were not very much crashes on servers with W2016 and W2019, but there are some. 
- It mostly happens after we changed something in the director. E.g. in the service sets, service apply rules etc.. So those things that were deployed via the zone „director-global“ on every node. A few minutes after a deployment one of our agents is crashing. Importing/Deleting new hosts doesnt affect.
- We also noticed, that after (manual) deployment the check „load“ is for short time 100% on some servers!

What we still find out about the crashes is following:
- Most of the time the icinga daemon ist stopped completely. And that regardless of the fact, that our server admins configured the daemon in that way, that the service should restart by default. But it didn’t. 
- Sometimes the daemon is running, but  stops checking. In this case no stack trace file is created or EventLog event is created. After restarting the daemon manually it works again. These are the cases where we saw the load is at 100%.

- Sometimes a stacktrace is written. But sadly, it is a bit meaningless. We can’t find much useful information whats going on. We only know that there is a unhandled  SEH  exception. You’ll find some examples in the attachment. 
[report.1604399476.816000.txt](https://github.com/Icinga/icinga2/files/5536143/report.1604399476.816000.txt)
[report.1604657998.669000.txt](https://github.com/Icinga/icinga2/files/5536144/report.1604657998.669000.txt)
[report.1604314931.001000.txt](https://github.com/Icinga/icinga2/files/5536146/report.1604314931.001000.txt)

- Sometimes we find events in the Windows Eventlog after a crash. Depending on the expection code are following files from Windows involved: 

> exception code: 0xe06d7363
> diffrent fault offsets at : 0x0000000000007afc (W2012R2)), 0x0000000000039689 (W2019)
> Faulting module path: C:\Windows\system32\KERNELBASE.dll

> Exception code: 0xc0000409
> Fault offset: 0x000000000006d3be, 
> Faulting module path: C:\Program Files\ICINGA2\sbin\ucrtbase.DLL

In our case it makes not much sense to turn on the debug log on every server without a FileLogger function (like comming with the issue/improvement #8016). That would only fill up the disks of the server, in the hope that one might receive log files from a possible crash and in the hope of not getting any further side effects. If we saw that the daemon is crashed the second time on a server, we turned on the logs. But as so often after the daemon didn’t crashed again on this server.

What we also see is that this issue/improvement #8373 is important. Maybe it’s a good idea to put also the last log lines in such stack trace in cases the logs are disabled. 
Anyway the logs on the the satellite and master looks fine. That means the new config from the director is pushed successfully to the agent. So it looks like something is going to happen while loading the new config.

In any case, we have a deja vu on #7431. But this time it will have a different cause we think

If you need some further information please tell us 

## To Reproduce

As written above it's difficult to say how to reproduce it. What we still know for know it happens after a change in the director and trigger this manually.

## Expected behavior

No crash :-)

## Your Environment

Include as many relevant details about the environment you experienced the problem in

- Our Icinga cluster consists of 2 master server and 4 satellite server in 2 zones. 
- Icinga Version from the Cluster 2.11.6
-Icinga Version installed on the Windows server 2.11.6
- OS at the master/satellite: CentOS 7
- OS at the Windows Agents: W2012R2, W2016, W2019
- We manage our config with the director (v1.7.2). 
We sync the config with a json file, created with the data from the diffrent databases and cmdb we were using. This is working fine for years now. 
- The daemon on the Windows servers are running with the network-user, like mentioned in the docs. But since using some checks from the new PS-Framework, we see that higher permissions are needed. 
- We installed the Icinga agent with the old Powershell Module. Afterwards we installed the new PowerShell framework for the new checks on every server.

**Comment by loulougunner** [comment]
Same problem over here!

**Comment by Yonas-net** [comment]
Hello @stevie-sy , thanks for your report. Unfortunately, with my configuration (1 master and two Windows agents) I could not reproduce the crash. I even automated my Director, so I was able to deploy many randomly generated configs but without success.

@loulougunner Is your crash maybe a bit different and would you share stack traces or logs here (if there exist), which would be a great help for us!

**Comment by stevie-sy** [comment]
Hi @Yonas-net ,

thanks for the answer. That's bad and sadly and was to be expected. As I wrote without a good and meaningful stacktrace it's difficult. But with the exception offset you should find it in the source I think, shouldn't you? It must be something unhandled. 

We setup three new windows test server. Maybe we can recreate the situation a little.

**Comment by Al2Klimov** [comment]
@Yonas-net It seems we have to re-deploy more frequently...

## Tasks

Create a new public GitHub repository and invite me.

**Comment by stevie-sy** [comment]
Small update from our site: 
We installed 3 Windows Test Server (1x W2012R2, 1x W2016, 1x W2019) for our test environment. And we created a test script to rename 1 ServiceSet, 1 timeperiod and 1 host template. We run this script every 5 min via cron now. 
Hopefully we can reproduce this incl. some debug logs

**Comment by stevie-sy** [comment]
First crash after about 5 hours periodly deployment:
Happens on the W2012R2 server (tested with 2.11.7):
- icinga2 service stopped
- no crash files created
- no event log entry 
- debug log entries see attached file [2.11.7.txt](https://github.com/Icinga/icinga2/files/5672918/2.11.7.txt)


Now I downgrade to 2.11.6 and I'll do the same again.

**Comment by Al2Klimov** [comment]
@Yonas-net Try to reproduce this with https://github.com/Yonas-net/windows-crash .

**Comment by Al2Klimov** [comment]
@Yonas-net I assume it didn't crash, yet?

**Comment by Yonas-net** [comment]
No, it is still running.

**Comment by Al2Klimov** [comment]
And if you try (w/o stopping the agent) more files on the server side and/or adding content (e.g. `object Host current_filename { enable_active_checks = false }`)?

**Comment by stevie-sy** [comment]
So 2.11.6 stopped yesterday on our W2019 test server. 
- no crash log
- no eventlog entry
- log file of this agent: [2.11.7.txt](https://github.com/Icinga/icinga2/files/5694649/2.11.7.txt) incl. messages between last successfully deployment and the time when the service stopped.

**Comment by stevie-sy** [comment]
Testet 2.11.8. Also here happend a crash. It's again our W2019 test server. 
This time we can offer 
* a crash log [report.1608317433.960000.txt](https://github.com/Icinga/icinga2/files/5723530/report.1608317433.960000.txt)
* an eventlog entry:

> Faulting application name: icinga2.exe, version: 1.0.0.0, time stamp: 0x5fd8c35b
> Faulting module name: KERNELBASE.dll, version: 10.0.17763.1518, time stamp: 0xff301d3c
> Exception code: 0xe06d7363
> Fault offset: 0x00000000000396c9
> Faulting process id: 0x24a0
> Faulting application start time: 0x01d6d56eaa3ac4d0
> Faulting application path: C:\Program Files\ICINGA2\sbin\icinga2.exe
> Faulting module path: C:\Windows\System32\KERNELBASE.dll
> Report Id: 6aa91508-bdb1-4a17-9c91-c9934a639a17
> Faulting package full name: 
> Faulting package-relative application ID: 

* log file: [2.11.8.txt](https://github.com/Icinga/icinga2/files/5723533/2.11.8.txt)

**Comment by Al2Klimov** [comment]
@Yonas-net Any updates on this?

**Comment by Yonas-net** [comment]
Nope, still no crashes.

**Comment by Al2Klimov** [comment]
Try to add a second test server master.

**Comment by Al2Klimov** [comment]
@Yonas-net Any updates on this?

**Comment by stevie-sy** [comment]
@Al2Klimov , @Yonas-net 
Can we also help? Some more information? Some more tests from our side?

**Comment by Al2Klimov** [comment]
At best you'd attach a debugger to Icinga and run a director deploy. But unfortunately I don’t know how to debug on Windows. CC @julianbrost

**Comment by julianbrost** [comment]
Obtaining a memory dump would be very helpful: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

These can then be analyzed with Visual Studio or WinDbg. Visual Studio has the less annoying interface, but I also had dumps where I could only get stack traces with WinDbg, so it might be worth trying both.

**Comment by stevie-sy** [comment]
@julianbrost  thanks for the link
After some other tests I have to do, I activate it and inform you

**Comment by Yonas-net** [comment]
> @Yonas-net Any updates on this?

The problem with me is that the servers can not run continuously but only during the day as long as I have my VPN on and at night the connection is always interrupted.

**Comment by Al2Klimov** [comment]
Can't you run everything for this test in the cloud?

**Comment by Yonas-net** [comment]
I'm doing that right now too except that the test server can't continue sending config updates because I'm accessing it via ssh and then this connection is interrupted when my laptop evening is locked even if I haven't shut it down.

**Comment by Al2Klimov** [comment]
Have you tried tmux/screen?

**Comment by Al2Klimov** [comment]
Any updates on this?

**Comment by stevie-sy** [comment]
Today we got an dump file of an crash. To be sure it has nothing to do with some other testings we did on our icinga test server, I wait to an other one. But the first look into it, it looks like what we are looking for

**Comment by Al2Klimov** [comment]
Awesome! Please upload it here: https://nextcloud.icinga.com/index.php/s/APeDyLHAMzoRdza

**Comment by stevie-sy** [comment]
done. You can "close" upload option. 
Two dump files incl. the events from the eventlog

**Comment by Al2Klimov** [comment]
@julianbrost Please could you have a look?

**Comment by stevie-sy** [comment]
Are the crash dumps helpful? 
Now I can also offer one from a crash on a W2012R2 server

**Comment by Al2Klimov** [comment]
The more, the better.

**Comment by stevie-sy** [comment]
The link above still works or do you have a new one?

**Comment by Al2Klimov** [comment]
It should work.

**Comment by stevie-sy** [comment]
done

**Comment by julianbrost** [comment]
All are `boost::filesystem::filesystem_error`s within `Utility::RenameFile` called by `DaemonUtility::LoadConfigFiles`:

```
Unhandled exception at 0x00007FFA50D796C9 in icinga2.exe.352.dmp: Microsoft C++ exception: boost::filesystem::filesystem_error at memory location 0x0000006B3898EC70.
```

Saw two slightly different call stacks (one seems to be missing a few frames):

![1](https://user-images.githubusercontent.com/18552/105845304-dc644480-5fda-11eb-827c-1d387d6c9faf.png)
![2](https://user-images.githubusercontent.com/18552/105845298-dbcbae00-5fda-11eb-8918-a789751f1db1.png)

**Comment by julianbrost** [comment]
Looks like another place where we should do something similar to #8318.

**Comment by julianbrost** [comment]
It's this call https://github.com/Icinga/icinga2/blob/d17b4ecc4bfeb94611e4e8f5c52865540a9bb46b/lib/cli/daemonutility.cpp#L204 that indirectly calls `RenameFile`
https://github.com/Icinga/icinga2/blob/d17b4ecc4bfeb94611e4e8f5c52865540a9bb46b/lib/config/configcompilercontext.cpp#L61-L68 that crashes.

**Comment by julianbrost** [comment]
I tried to convince Visual Studio to show the actual exception message which should reveal the involved paths and some error reason/code, but I didn't succeed :(

In the meantime I created #8614 to prevent uncaught exceptions in more places, but this won't prevent this, just log a hopefully more helpful message in this case.

**Comment by julianbrost** [comment]
From debugging a similar case: even with #8614, you might run into #5399 and not see the actual log message introduced in that PR.

**Comment by stevie-sy** [comment]
Hi guys, 
a small update on this: since we have 2.11.4 in production, we no longer observe crashes. It looks like the change #8691 seems to work very well.

**Comment by julianbrost** [comment]
Thanks for reporting back. I think you wanted to say 2.12.4 (or maybe 2.11.9) as that contains the fix you mentioned.

**Comment by stevie-sy** [comment]
yes, 2.12.4
