### ISSUE TITLE
ScheduledDowntime quirks

### ISSUE THREAD

**Issue by william-sy** [Icinga/icinga2#8481]
## ScheduledDowntime Quirks

Right this is more of a question than a bug. But its produces some weird behaviour so we have a downtime planned and working on various occasions. But we have one host that our devs kinda abuse in CPU power on set times because copying an pasting a job is super easy so why change the time he ?

So we came up with this for all seven days of the week: 
`"monday" = "00:00-01:00,06:00-07:00,12:00-13:00,18:00-19:00"`
Now this works sometimes. But some times it skips one, and shcedules the one for the next day. Som days they work all 4. 
this works flawlessly: 
`"monday" = "00:00-07:00,12:00-19:00"`

So I got to wonder is there a limit on this ? 

I read the documentation [https://icinga.com/docs/icinga2/latest/doc/08-advanced-topics/](url)

And it states:

> Icinga 2 attempts to find the next possible segment from a ScheduledDowntime object’s ranges attribute, and wont create multiple downtimes in the future. In case you need all these downtimes planned and visible for the next days, weeks or months, schedule them manually via the REST API using a script or cron job.

So the questions that come up are: 

- So how badly does icinga `attempt` this? 
- Is 2 ranges the limit or 3? 

I know If I want to see them all planned i need to use the API or plan them by hand. 
But if its between: `06:00-07:00,` I kinda expect the `12:00-13:00` to be visible, and not `18:00-19:00` or the next day one.

## To Reproduce

1. Plan a DT of 7 days a week with 4 or more time ranges, check and reload
Example of our setup:
```
template ScheduledDowntime "qrun" {
  ranges = {
    "monday"    = "00:00-01:00,06:00-07:00,12:00-13:00,18:00-19:00"
    "tuesday"   = "00:00-01:00,06:00-07:00,12:00-13:00,18:00-19:00"
    "wednesday" = "00:00-01:00,06:00-07:00,12:00-13:00,18:00-19:00"
    "thursday"  = "00:00-01:00,06:00-07:00,12:00-13:00,18:00-19:00"
    "friday"    = "00:00-01:00,06:00-07:00,12:00-13:00,18:00-19:00"
    "saturday"  = "00:00-01:00,06:00-07:00,12:00-13:00,18:00-19:00"
    "sunday"    = "00:00-01:00,06:00-07:00,12:00-13:00,18:00-19:00"
  }
}
apply ScheduledDowntime "run-downtime" to Service {
  import "qrun"
  author = "username"
  comment = "Scheduled downtime for qrun"
  assign where "wcpu" in service.groups && host.vars.client == "clientname" && host.vars.qrun_dt == "enabled"
}
```

## Expected behavior

See above: 

> I know If I want to see them all planned i need to use the API or plan them by hand. 
But if its between: `06:00-07:00,` I kinda expect the `12:00-13:00` to be visible, and not `18:00-19:00` or the next day one.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

Version info: 
```
icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.1-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1127.19.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-wytxxqbb-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
```

**Comment by Yonas-net** [comment]
Hiii @william-sy , thanks for the report. Well, I played around with it a bit last week and also ran Icinga2 with all the scheduled downtimes over the weekend, and I'd say it worked fine. But I don't know why it didn't work for you sometimes.

> So how badly does icinga attempt this?

The comma separated values in the individual ``ScheduledDowntime ranges`` days are so called segments, i.e. if you enter ``monday = "00:00-01:00,06:00-07:00,12:00-13:00,18:00-19:00"`` as above, ScheduledDowntime ranges monday has 3 possible segments and these individual segments have 2 attributes, ``begin`` and ``end``. Icinga2 will then iterate through these segments and compare if the segment begin is not less than the ``LocalTime()`` and if it is, skips that segment because it has already expired. If none of the available segments are valid, Icinga2 will attempt to Schedule for the next day. The algo for this can be found [here](https://github.com/Icinga/icinga2/blob/master/lib/icinga/scheduleddowntime.cpp#L166) and [here](https://github.com/Icinga/icinga2/blob/master/lib/icinga/legacytimeperiod.cpp#L453).

> Is 2 ranges the limit or 3?

No, there is no limit. You can configure it as much as you need!



@N-o-X | @Al2Klimov Can you confirm this?

**Comment by william-sy** [comment]
Hi @Yonas-net, 

Thanks for that explanation, and effort put into this! So if there is no limit, how often does icinga plan this algo? 
If my current DT of `00:00-01:00` has passed and it starts to look at new DT at `06:30` it makes sense it is skipping the `06-07` but it is not what we would like to see. 

Does the total amount of DT's? in a setup have impact on how often this happens?
`information/ConfigItem: Instantiated 989 Downtimes.`

**Comment by Al2Klimov** [comment]
1. @Yonas-net Yes, you're right.
2. @william-sy Please try to schedule the first monday downtime not from 00:00, but e.g. from 00:10. (I guess #8386 could also fix your problem.)

**Comment by william-sy** [comment]
Hi @Al2Klimov, 

Thank you for your response, I have adjusted the times for tomorrow and Wednesday to: 
`"wednesday" = "00:05-01:00,06:00-07:00,12:00-13:00,18:00-19:00"`

I will keep an eye out to see if this will fix it for us. 

The link you have shared is interesting, As it is already up for merging it iss better to wait for this to become part of the official release.

**Comment by william-sy** [comment]
I have monitored the change made to the schedule. This now seems to plan all the downtimes. 

Thanks for the help! @Al2Klimov @Yonas-net
