### ISSUE TITLE
CRL expires if the daemon is not reloaded/restarted

### ISSUE THREAD

**Issue by xschlef** [Icinga/icinga2#8501]
## Describe the bug
A very simple configuration of icinga2 was unable to connect to our master, because the CRL has expired. The daemon was not reloaded for 30 days, which is our maximum CRL age.
We update our CRL every 6 hours and a restart fixed the issue. So I think, that a running daemon is not reloading a changed CRL.

```
Sep 24 10:06:54 XX icinga2[4217]: API client disconnected for identity 'XXX'
Sep 24 10:06:59 XX icinga2[4217]: Certificate validation failed for endpoint 'XXX': code 12: CRL has expired
```
## To Reproduce
Start icinga2, wait until CRL expiration and connections start to fail.

## Expected behavior
The daemon periodically reloads the CRL or monitors the CRL for changes.

## Your Environment
Application version: 2.12.1-1.buster

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 4.19.0-12-amd64
  Architecture: x86_64

Enabled features: api checker command mainlog notification syslog

Config validation:
```
[2020-11-24 11:08:59 +0100] information/cli: Icinga application loader (version: r2.12.1-1)
[2020-11-24 11:08:59 +0100] information/cli: Loading configuration file(s).
[2020-11-24 11:08:59 +0100] information/ConfigItem: Committing config item(s).
[2020-11-24 11:08:59 +0100] information/ApiListener: My API identity: XXX
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 SyslogLogger.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 Host.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 7 NotificationCommands.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 2 Notifications.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 EventCommand.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 2 Zones.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 2 Endpoints.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 156 CheckCommands.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 7 TimePeriods.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 10 UserGroups.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 31 Users.
[2020-11-24 11:09:00 +0100] information/ConfigItem: Instantiated 1 Service.
[2020-11-24 11:09:00 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-11-24 11:09:00 +0100] information/cli: Finished validating the configuration file(s).
```

## Additional context
We are rolling out our own certificate infrastructure and are not relying on icinga2 pki.

**Comment by dgoetz** [comment]
I had this problem also once when doing such a test setup which got never into production. It would also be great if the CRL is not required to be a local file, but instead could be an URL where Icinga 2 pulls the updates.

**Comment by Al2Klimov** [comment]
## Tasks

Reproduce this issue.

**Comment by Yonas-net** [comment]
### Steps to reproduce this error

First I created a custom openssl configuration under the path ``/var/lib/icinga2/ca`` and looks like this!
```poershell
[ ca ]
default_ca              = CA_default

[ CA_default ]

dir                     = /var/lib/icinga2/ca
database                = $dir/index.txt
new_certs_dir           = $dir/newcerts

certificate             = $dir/ca.crt
serial                  = $dir/serial
private_key             = $dir/ca.key
RANDFILE                = $dir/private/.rand

default_days            = 3650
default_crl_hours       = 1
default_md              = md5

policy                  = policy_any
email_in_dn             = no

name_opt                = ca_default
cert_opt                = ca_default
copy_extensions         = none

x509_extensions         = extensions_section

[ extensions_section ]


[ policy_any ]
countryName             = supplied
stateOrProvinceName     = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional
```

And next i created two files ``index.txt`` and ``index.txt.attr``, which will serve as database for the revoked certificates. Create a third file named ``crlnumber`` with the content ``00``.

Next, create a ``CRL`` file with the following command. ``openssl ca -config openssl.cnf -gencrl -out ha-master.crl``. If you want to know if there is a revoked certificate, you can check the contents of the CRL with the ``crl`` tool. ``openssl crl -in ha-master.crl -noout -text``.

And now we revoke the agent certificate with the following command. ``openssl ca -config openssl.cnf -revoke agent.crt`` and update the CRL file with the following command ``openssl ca -config openssl.cnf -gencrl -out ha-master.crl``. If you restart Icinga2 now, you should see the following message.
```powershell
[2020-11-27 12:25:50 +0000] information/ApiListener: New client connection for identity 'XXXX' from [192.168.242.98]:51891 (certificate validation failed: code 23: certificate revoked)
```

And now undo the certificate revocation by deleting the contents of ``index.txt`` and ``index.txt.attr`` and update the CRL file as above ``openssl ca -config openssl.cnf -gencrl -out ha-master.crl``. 

If you now deploy something or restart the agent without restarting the master, the same message as above should appear. But if you restart the master, everything should be as before.

**Comment by Al2Klimov** [comment]
## Tasks

1. Figure out how we work with the CRL at the moment and write it down here
2. Write down here how you think we could make it better

**Comment by dgoetz** [comment]
Also keep in mind for reproducing that not only changed content could be a problem, but also the lifetime of the crl. In your case `default_crl_hours = 1` the crl would be invalid after 1 hour and needs to be updated. As far as I remember Icinga 2 / the underlying OpenSSL makes use of this and does not except any certificate if a crl has expired. Unfortunately hours is the smallest unit, so testing is perhaps time consuming here.

**Comment by Yonas-net** [comment]
> Figure out how we work with the CRL at the moment and write it down here

So, as I see it, first of all it's like the @dgoetz  mentioned above that icinga expects the ``CRL`` as a file name and not from a URL and secondly Icinga2 calls the ``ApiListener::UpdateSSLContext()`` method only when loading the config, i.e. in ``ApiListener::OnConfigLoaded()`` and when updating the certificate in ``pki::UpdateCertificateHandler()``. But if we don't do the same, the SSL context won't be updated e.g. when reconnecting master <-> agent, i.e. if we restart the agent no certificate or config updates will be done and as long as these two methods are not fired, icinga won't know if the CRL has already been updated.

**Comment by Yonas-net** [comment]
> Write down here how you think we could make it better

I don't know how you see it but my suggestion would be that just before we verify the certificate in ``ApiListener::NewClientHandlerInternal()`` we perform ssl context update so that when Icinga re-establishes a connection with Agent it will also know that the CRL has been updated or not. And of course it would also be great if the ``CRL`` didn't have to be a local file but could instead be a URL from which Icinga2 gets its updates.

**Comment by Al2Klimov** [comment]
1. If we'd update it at the time and code location you suggested, would it have an effect?
2. CRL didn't have to be a local file = other construction area

**Comment by Yonas-net** [comment]
> If we'd update it at the time and code location you suggested, would it have an effect?

Yes, it would have an effect. You wouldn't have to restart the master or something like that, but as soon as the connection is established, the updates would be executed.

**Comment by Al2Klimov** [comment]
But the context has already been set [here](https://github.com/Icinga/icinga2/blob/3f4b09f01c0464ed8201a5105683af68e02488cf/lib/remote/apilistener.cpp#L435). Isn't NewClientHandlerInternal() too late?

**Comment by Yonas-net** [comment]
No it is not too late, it is only set [here](https://github.com/Icinga/icinga2/blob/3f4b09f01c0464ed8201a5105683af68e02488cf/lib/remote/apilistener.cpp#L435) when the endpoint is restarted, i.e. it does not matter whether it is a master or an agent, because no connection is established and no certificate check is performed yet. But we want to update the context only when a connection between two nodes is established and when this is the case, the method ``ApiListener::AddConnection()`` is called and this in turn calls the method ``ApiListener::NewClientHandler()`` and from this method we finally get to ``ApiListener::NewClientHandlerInternal()`` method where the certificate verification is performed.

**Comment by Al2Klimov** [comment]
What do you mean with "we want to _update the context_"? Assigning a new context to an ApiListener member which is used _for new connections only_ while the currently being established connection [already has its **old** context](https://github.com/Icinga/icinga2/blob/3f4b09f01c0464ed8201a5105683af68e02488cf/lib/remote/apilistener.cpp#L435)?

**Comment by Yonas-net** [comment]
Well, it seems that when the master contacts the agent and not the other way around, Icinga2 does not check the CRL at all, although it is configured explicitly. The master does not even notice that there are revoked certificates even if it is restarted.

**Comment by Al2Klimov** [comment]
@julianbrost Shall we just address incoming connections and hope for the best?

**Comment by Al2Klimov** [comment]
I consider that another construction area and (therefore) my question unanswered.

**Comment by julianbrost** [comment]
Then I'm not sure what you mean by "hope for the best". If *this* issue is about expired CRLs, and outgoing connections do indeed ignore CRLs alltogether, sure, there is nothing to change in regard to outgoing connections to fix *this* issue.

**Comment by Al2Klimov** [comment]
@Yonas-net Research whether the behavior you've discovered works as expected (by TLS in general).

**Comment by dgoetz** [comment]
CRL handling is typically always on the server side which verifies the client certificate. If done correctly the CRL should be included in all ApiListener configs (or at least all that await connections). But this would still leave the problem that a revoked client would verify the valid server and allow the connect which could be solved if it verifies its own certificate against the CRL first.

**Comment by julianbrost** [comment]
> which could be solved if it verifies its own certificate against the CRL first

IMHO this is much more likely to hide bugs than to solve anything. If someone has a revoked certificate, you can't trust them to verify it against a CRL.

**Comment by Al2Klimov** [comment]
@dgoetz On the server side only? So [this behavior](https://github.com/Icinga/icinga2/issues/8501#issuecomment-737885410) is correct?

**Comment by julianbrost** [comment]
We shouldn't care about what other software does but about what makes sense for Icinga. And the decision whether a certificate is valid should not depend on whether we are establishing the connection as a TCP client or server when the connection is otherwise symmetric. But if you want an example of a TLS client that verifies the server certificate against a CRL: `curl --crlfile`.

**Comment by julianbrost** [comment]
> Well, it seems that when the master contacts the agent and not the other way around, Icinga2 does not check the CRL at all, although it is configured explicitly. The master does not notice that there are revoked certificates even if it is restarted.

I was unable to reproduce this claim (note that it says `to <addr>` instead of `from <addr>`):
```
information/ApiListener: New client connection for identity 'agent-1' to [172.18.0.8]:5665 (certificate validation failed: code 23: certificate revoked)
```
