### ISSUE TITLE
Unable to toggle notifications from icingaweb2

### ISSUE THREAD

**Issue by eskaaren** [Icinga/icinga2#8533]
## Describe the bug

After upgrade we are unable to toggle Notifications from System->Monitoring Health->Feature Commands.

This is a setup with 2 master nodes and it works when stopping the icinga2 service on one of the nodes and accessing icingaweb2 running on the same node as the running icinga2 process. The issue is when accessing icingaweb2 on master1 and trying to toggle when the active icinga2 endpoint is master2.

This is seen in the debug log on master2:

`notice/ApiListener: Received config update for object: {"modified_attributes":{"enable_notifications":false},"name":"app","original_attributes":["enable_notifications"],"type":"IcingaApplication","version":1607071508.65422,"zone":""}`

`notice/ApiListener: Discarding 'config update object' message from 'master1' (endpoint: 'master1', zone: 'master') for object 'app' of type 'IcingaApplication'. Objects zone '' isn't known locally.`

## To Reproduce

Run a setup with 2 masters upgraded to the r2.12.2-1 with active icingaweb2 endpoint on master1 and active icinga2 endpoint on master2. Try to toggle notifications and the toggle stays in the same position and the setting is not changed.

## Expected behavior

Toggle notifications should work in this multi master configuration.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.12.2-1
* Operating System and version: Ubuntu 18.04
* Enabled features (`icinga2 feature list`): api checker command debuglog ido-mysql influxdb mainlog notification
* Icinga Web 2 version and modules (System - About): 2.8.2
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context

Can this be relevant?
https://github.com/Icinga/icinga2/commit/8ba5f725338118179c0eb7cf2ef97c1292d57bdf#diff-df49d4fcdc0bbcf39a36ee34ad559d603adec46b843bacb6afe9fd480a9c7603

**Comment by julianbrost** [comment]
I was able to reproduce this. The linked commit is very likely relevant.

**Comment by N-o-X** [comment]
Fixed by #8549 (v2.12.3) and #8550 (v2.11.8)
