### ISSUE TITLE
Documentation: Typos in "acknowledge-problem" example for API

### ISSUE THREAD

**Issue by Bobobo-bo-Bo-bobo** [Icinga/icinga2#8546]
## Describe the bug
The example in the "acknowledge-problem" section of the API documentation to acknowledges all services in a hard critical state reads as:

```
curl -k -s -S -i -u root:icinga -H 'Accept: application/json' \
 -X POST 'https://localhost:5665/v1/actions/acknowledge-problem' \
 -d '{ "type": "Service", "filter": "service.state==2&service.state_type=1", "author": "icingaadmin", "comment": "Global outage. Working on it.", "notify": true, "pretty": true }'
```

The filter string seems to be wrong, it should be:

```
curl -k -s -S -i -u root:icinga -H 'Accept: application/json' \
 -X POST 'https://localhost:5665/v1/actions/acknowledge-problem' \
 -d '{ "type": "Service", "filter": "service.state==2 && service.state_type==1", "author": "icingaadmin", "comment": "Global outage. Working on it.", "notify": true, "pretty": true }'
```

(Note the extra `&` and `=`)

**Comment by Al2Klimov** [comment]
Hello @Bobobo-bo-Bo-bobo and thank you for reporting!

Would you like to [adjust the docs](https://github.com/Icinga/icinga2/edit/master/doc/12-icinga2-api.md) – and become an Icinga 2 contributor?

Best,
AK

**Comment by Bobobo-bo-Bo-bobo** [comment]
see pull request #8556
