### ISSUE TITLE
check_http -k option not correctly specified in ITL CheckCommand "http"

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icinga2#8573]
## Describe the bug

The check_http plugin provides the option of specifying the option "-k", which can be used to send specific headers, multiple times, once for each header.

The CheckCommand "http" provided in `/usr/share/icinga2/include/command-plugins.conf` is lacking the `repeat_key=true` option required to address this, so it doesn't work.

**Comment by Al2Klimov** [comment]
Have you actually reproduced it?

**Comment by peteeckel** [comment]
I just verified that even without the repeat_key flag an array as the value for an argument **does** repeat.

Slightly counter-intuitive, but it's documented, so it's not an issue. Closing this.
