### ISSUE TITLE
Inconsistent documentation on zones in zones

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#8585]
https://icinga.com/docs/icinga-2/latest/doc/15-troubleshooting/#zones-in-zones-doesnt-work states that you should not define zones within `zones.d/`, however https://icinga.com/docs/icinga-2/latest/doc/06-distributed-monitoring/ has an example doing exactly this: https://github.com/Icinga/icinga2/blob/cb25be2d12d1b9a68ec4be85ace2f2b267f875fe/doc/06-distributed-monitoring.md#L2217-L2231

Also from my experience this works just fine. Dig a bit deeper into this and fix the docs.

**Comment by Al2Klimov** [comment]
> Also from my experience this works just fine.

Btw.: #7546

**Comment by Al2Klimov** [comment]
> states that you should not define zones within `zones.d/`

## Task

Remove that statement

**Comment by yhabteab** [comment]
> https://icinga.com/docs/icinga-2/latest/doc/15-troubleshooting/#zones-in-zones-doesnt-work states that you should not define zones within `zones.d/`

I don't quite get what's wrong with that, it's just being explained (as a troubleshooting) that the configs placed into `zones.d/ZoneName`, Icinga2 will not include when the appropriate `ZoneName` definition isn't configured.

**Comment by julianbrost** [comment]
My test cluster only has the zone `master` with the `master-1` and `master-2` endpoints defined in `zones.conf`, other zones and endpoints are configured in `zones.d/` including nested satellite zones and it seems to work just fine.

But reading https://icinga.com/docs/icinga-2/latest/doc/15-troubleshooting/#zones-in-zones-doesnt-work sounds to me like this wouldn't work. The section "Doesn’t work" shows pretty much how I defined my satellite zones:

`zones.d/master/satellites.conf`:
```
/*** satellite-a ***/
object Host "satellite-a-1" {
	import "generic-host"
	address = "satellite-a-1"
}

object Endpoint "satellite-a-1" {
	host = "satellite-a-1"
}

object Host "satellite-a-2" {
	import "generic-host"
	address = "satellite-a-2"
}

object Endpoint "satellite-a-2" {
	host = "satellite-a-2"
}

object Zone "satellite-a" {
	parent = "master"
	endpoints = ["satellite-a-1", "satellite-a-2"]
}

/*** satellite-b ***/
object Host "satellite-b-1" {
	import "generic-host"
	address = "satellite-b-1"
}

object Endpoint "satellite-b-1" {}

object Host "satellite-b-2" {
	import "generic-host"
	address = "satellite-b-2"
}

object Endpoint "satellite-b-2" {}

object Zone "satellite-b" {
	parent = "master"
	endpoints = ["satellite-b-1", "satellite-b-2"]
}
```

> > Also from my experience this works just fine.
> 
> Btw.: #7546

Might indeed be the the documentation was correct in stating this doesn't work before that PR and the docs weren't updated since then.
