### ISSUE TITLE
Notification even if acknowledged

### ISSUE THREAD

**Issue by Virsacer** [Icinga/icinga2#8644]
## Describe the bug

A Notification was sent for a service which has been acknowledged before the period of the notification started.

## To Reproduce

    apply Notification "call-rufbereitschaft" to Service {
      command = "call-service-notification"
      states = [Critical]
      types = [Problem]
      users = ["sysadmin-rufbereitschaft"]
      interval = 5m
      period = "rufbereitschaft"
      assign where service.vars.servicetype == "critical"
     }

A service became critical and was acknowledged before 20:00
Timeperiod "rufbereitschaft" starts at 20:00.
And "sysadmin-rufbereitschaft" was unable to acknowledge the problem (via api), because an acknowledgement is already there...

For escalation there is a similar notification-definition (with times.begin) and a period starting 20:30 and it behaves the same way...

## Expected behavior

Do not send notification at start of period if already acknowledged.

## Screenshots

![image](https://user-images.githubusercontent.com/8797510/108361689-1a781100-71f3-11eb-95f5-7339787d0938.png)

## Your Environment

* Version used (`icinga2 --version`): 2.12.3
* Operating System and version: Oracle Linux Server 7.9
* Enabled features (`icinga2 feature list`): api checker ido-mysql mainlog notification perfdata
* Icinga Web 2 version and modules (System - About): 2.8.2
* Config validation (`icinga2 daemon -C`): information/cli: Finished validating the configuration file(s).

**Comment by Al2Klimov** [comment]
Sounds like #8513. Please could you test the snapshot packages?

**Comment by Virsacer** [comment]
I reproduced it with 2.12.3-1.el8.icinga and then "downgraded" to 2.12.0.506.gaa4f53009-0.20210208.1822.el8.icinga
With this version I was unable to reproduce it 👍
