### ISSUE TITLE
how to use REST API to set maintenance mode from http, not the command line

### ISSUE THREAD

**Issue by leoxucn822** [Icinga/icinga2#8672]
## Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is. Ex. I'm always using this feature but am missing [...]

**Comment by julianbrost** [comment]
This sounds like a question that's better suited for [our community forums](https://community.icinga.com/). Also an advice for asking there: to me it's not clear what you mean by maintenance mode? Do you mean downtimes? In any way, it would be good if you include what you're currently doing on the command line that you want to do using the API.
