### ISSUE TITLE
Cannot ignore constant "301" in apply service

### ISSUE THREAD

**Issue by adriangalbincea** [Icinga/icinga2#8690]
## Describe the bug

Cannot ignore value "301" from a defined constant.

I have an apply rule to check domains grabbed from a webhosting server.

## To Reproduce

1.  I have multiple defined constants for various things and if I am trying to add "301" as a constant, will not do anything.
2.  I tried to ignore the value "301" directly in the apply service using match and still no joy. `ignore where match("301", host.vars.nginx_vhosts)`

## Apply Service

It should stop monitoring for the defined constant

```
apply Service "check-domain-expiry-webhosting" for (domain in host.vars.nginx_vhosts){
  import "domain-checker"

  display_name = "Check Domain " + domain
  vars.domain_name = domain
  assign where host.name == "webhosting.hostingassistance.co.uk"
  ignore where domain in IgnoreDomains
}
```

**Comment by Al2Klimov** [comment]
Hello @adriangalbincea and thank you for reporting!

Do you want to ignore if there's 301 in the array? Have you tried `match("301", ["301", "302"], MatchAny)`?

Best,
AK

**Comment by adriangalbincea** [comment]
Hi @Al2Klimov , thank you for the quick reply. It did the trick and I could exclude website and domain check. I am trying to understand what is the issue and why is not working in the normal way?

**Comment by Al2Klimov** [comment]
Because by default match() requires all array items to match.

Is this issue solved now?

**Comment by adriangalbincea** [comment]
It is resolved. Many thanks for the resolution!
My question is that why `ignore where domain in IgnoreDomains` did not work. worked for a name "_" and other weird ones but not for 301, which is a web redirect.

**Comment by adriangalbincea** [comment]
Sortes out my issue. Thanks!
