### ISSUE TITLE
Host from slave zones are missing in postgresql ido

### ISSUE THREAD

**Issue by yoshi314** [Icinga/icinga2#8707]
## Describe the bug

I cannot find any hosts assigned to other zones/satellites in icingaweb2, neither can I find them in postgresql db.

**They are visible in thruk (via livestatus) and via icinga2 object list**

## To Reproduce

1. Install an empty pgsql db
2. Inject the icingaweb2 schema and setup permissions accordingly
3. Setup icinga2 master instance to use it
4. After the db fills up, no hosts from other zones can be found in it. Nor in icingaweb2 interface.

## Expected behavior

I should see all hosts/services.

I had no issues with mysql before, but the db size got out of hand eventually.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 

```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.3-1)

Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 4.19.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

```

* Operating System and version: Debian 10
* 
* Enabled features (`icinga2 feature list`): api checker command compatlog graphite ido-mysql ido-pgsql livestatus mainlog notification statusdata syslog
* Icinga Web 2 version and modules (System - About):

```
Icinga Web 2 Version
    2.8.2
Git commit
    8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version
    7.3.27-1~deb10u1
Git commit date
    2020-08-17
```

```

Name | Version
-- | --
batman | master
businessprocess | 2.2.0
cube | 1.1.0
deployment | 2.0.0-beta1
director | 1.7.2
doc | 2.8.2
graphite | 1.1.0
idoreports | 0.9.0
incubator | 0.5.0
ipl | v0.3.0
jira | 1.0.1
monitoring | 2.8.2
reactbundle | 0.7.0
reporting | 0.10.0
setup | 2.8.2
theme-dark | 0.0.1
toplevelview | 0.1.0
translation | 2.8.2
x509 | 1.0.0
```

* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

```
object Endpoint "icinga2" {
  host = "icinga2"
//  host = "192.168.16.18"
//  port = 5665
}

object Endpoint "icinga" {
  host = "192.168.16.13"
  port = 5665
}

// two nodes in master zone
object Zone "ABS" {
  endpoints = [ "icinga2" , "icinga" ]
}

object Endpoint "offsite.assecobs.pl" {
  host = "offsite.assecobs.pl"
}

object Zone "offsite" {
  endpoints = [ "offsite.assecobs.pl" ]
  parent = "ABS"
}


object Zone "global" {
  global = true
}
```

**Comment by N-o-X** [comment]
Hi @yoshi314,

two questions to clear things up:
- Are you able to see those hosts/services on both of your masters using `icinga2 object list --type Host` or `icinga2 object list --type Service`?
- Where are those hosts/services configured? (Icinga Instance)

Greetings
Noah

**Comment by yoshi314** [comment]
hosts are configured on master in zones.d/offsite

I can see the host only on the instance where i manage the config files.  The other node in my HA setup which receives the configr from second node in zone ABS does not list it.
