### ISSUE TITLE
/v1/actions/acknowledge-problem returns an http status code of 500 when the results json is 409

### ISSUE THREAD

**Issue by mpowrie** [Icinga/icinga2#8726]
## Describe the bug

When acknowledging a problem with the /v1/actions/acknowledge-problem endpoint, if the problem has already been acknowledged or the system is up, the JSON response is 409, but the HTTP response code is 500 (internal server error).

## To Reproduce
On a monitored hostname with a service that either does not have a problem or the problem is already acknowledeged, run the following CURL statement, substituting the server names and authentication string.

```
curl --location -i --request POST 'https://myserver:5665/v1/actions/acknowledge-problem' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
--data-raw '{
    "type": "Host",
    "filter": "host.name==\"mymonitoredserver\"",
    "author": "monitoradmin",
    "comment": "Acknowledgement comment.",
    "expiry": 1618888535133,
    "pretty": true
}'
```

The response will be something like this:
```
HTTP/1.1 500 Internal Server Error
Server: Icinga/2.12.3
Content-Type: application/json
Content-Length: 133

{
    "results": [
        {
            "code": 409.0,
            "status": "Host mymonitoredserver is UP."
        }
    ]
```

## Expected behavior

if the JSON results code is 409, the HTTP response code should also be 409, not 500. A response code of 500 should only be given if there is an error or misconfiguration on the server.

If there are multiple JSON results with different codes, perhaps the result code should be 207 (multi-status?)

## Screenshots
![image](https://user-images.githubusercontent.com/323814/115332644-8ff46380-a1db-11eb-924a-7c6f76a29dca.png)

## Your Environment

* Version used: Icinga version 2.12.3
* Operating System and version: `CentOS 7.9.2009`
* Enabled features (`icinga2 feature list`): `api checker command ido-mysql influxdb mainlog notification perfdata`
* Icinga Web 2 version: 2.8.2, loaded modules: monitoring 2.8.2
* Config validation (`icinga2 daemon -C`):

**Comment by Al2Klimov** [comment]
Sounds like #8532.

**Comment by mpowrie** [comment]
Thanks - I agree - sounds like #8532. Closing bug...
