### ISSUE TITLE
Matching objects in nested filters randomly not working 

### ISSUE THREAD

**Issue by gnammyx** [Icinga/icinga2#8731]
## Describe the bug
When creating host groups or service groups, we use names like "host-netapp" or "services-antivirus". The groups created works well, matching filtered host or services in declaration, but not works like expected when used inside other host groups or service groups filters.
For example when a host group contains filters to include other host groups, sometimes all host are matched correctly, other times hosts from one or more groups does not match.
As a workaround we find that putting an underscore at the start of name like "_host-netapp" or "_services-windows" make groups and filters work as expected.

## To Reproduce
1. Create 2 host groups "host-wds" and "host-file"
2. On host-wds Assign where "host.name = \*wds\*", on host-file Assign where "host.name = \*fil\*"
3. Create an host group "host-generic"
4. On host-generic Assign where "host.group = host-wds or host.group = host-file"
5. Deploy and check the host-generic contents: the hosts on host-fil are present, the hosts on host-wds doesn't.
6. Modify host-wds name to _host-wds, and modify also the host-generic group to match new name.
7. Deploy and now the hosts on _host-wds are correctly matched

## Expected behavior
Host and service groups must match objects without need to modify the name with an underscore in top of it, when nested inside other filters.

## Your Environment
* Icinga Web 2 version and modules (System - About): 
	icingaweb2  2.8.2
	director 	1.7.2
	doc 	2.8.2
	fileshipper 	1.1.0
	grafana 	1.3.6
	idoreports 	0.9.1
	incubator 	0.5.0
	ipl 	v0.3.0
	map 	1.1.0
	monitoring 	2.8.2
	pdfexport 	0.9.1
	reactbundle 	0.7.0
	reporting 	0.9.2 
* Web browser used: Mozilla Firefox 87.0
* Icinga 2 version used (`icinga2 --version`): 2.12.3
* PHP version used (`php --version`): PHP 7.0.33-0+deb9u10
* Server operating system and version: Linux Debian 9

**Comment by Al2Klimov** [comment]
Hello @gnammyx and thank you for reporting!

Please share actual Icinga 2 config or Director screenshots.

Best,
AK

**Comment by gnammyx** [comment]
Hello @Al2Klimov here 2 screenshot of director config:
Let's pick a host group matching \*wds\* word on host.name
![image](https://user-images.githubusercontent.com/57061995/116212438-1d3c3880-a745-11eb-8b53-233cd8d4a203.png)

Now a group containing various host-groups
![image](https://user-images.githubusercontent.com/57061995/116212570-3f35bb00-a745-11eb-93c2-e0deff5c9fd9.png)

As you can see there's some groups starting with underscore and other group with normal names, this is the only way to make the host group work, if I remove the underscore the group stops matching hosts

Let me know if you need more info or config evidence.

Thanks in advance

**Comment by Al2Klimov** [comment]
Hmm.. so you actually create group memberships based on group memberships. This is obviously a dependency cycle. Either:

* keep the underscores or
* start the now underscored groups w/ capital letters or
* instead of _group1 if name matches x_ and _group2 if in group1_ consider _group1 if name matches x_ and _group2 if name matches x_

**Comment by julianbrost** [comment]
Or just use the `groups` attribute of `HostGroup` that allows you to create groups based on the members of groups: https://icinga.com/docs/icinga-2/latest/doc/09-object-types/#hostgroup
