### ISSUE TITLE
Relay Heartbeat messages in a zone

### ISSUE THREAD

**Issue by dasJ** [Icinga/icinga2#8752]
## Is your feature request related to a problem? Please describe.

I'm connecting my agents directly to my two HA master nodes (no satellites involved).
The `cluster-zone` check is executed in the master zone for every agent.

![image](https://user-images.githubusercontent.com/4971975/116878496-bc6a9f80-ac1f-11eb-959d-a476556e6ec0.png)

Now the connection between the agent and Master A breaks.
As long as Master B executes the `cluster-zone` check, everything works well.
But when Master A executes the check, there weren't any heartbets seen recently.

## Describe the solution you'd like

The `event::Heartbeat` message should be relayed between the master nodes so both masters know which zones are connected.

## Describe alternatives you've considered

Maybe modify the `cluster-zone` check to also check the other master or add a new check altogether?

## Additional context

Would be a nice feature for better HA master stuff.

**Comment by Al2Klimov** [comment]
Hello @dasJ!

What about two cluster-zone checks, each pinned on a master? So you'll discover ASAP once a connection breaks.

Best,
AK

**Comment by dasJ** [comment]
Oh sorry for taking so long to respond.

My goal with this setup was to monitor hosts that cannot be reached from Icinga because are behind a firewall (or a NAT that goes the wrong way around).
An example may be monitoring the hosts at a customer's site where we only have NATted internet and no way to directly connect from Icinga to the machines in order to ping them.
The idea was to have the machines connect to the masters (which works because the masters have public IPs) and to schedule checks from the masters to the target machines.
All of this works except a check that checks whether a host is up. The only way I found was the `cluster-zone` check which has the aforementioned downsides.

**Comment by Al2Klimov** [comment]
OK.. in the picture you posted is the red connection really just temporarily broken?

**Comment by dasJ** [comment]
Probably temporarily. I had this issue when I reconfigured a router and forgot to add an ACL

**Comment by Al2Klimov** [comment]
And what's the downside of the solution I suggested?

**Comment by Al2Klimov** [comment]
I mean this one:

> two cluster-zone checks, each pinned on a master

Btw. I don’t agree with you:

> Now the connection between the agent and Master A breaks.
> As long as Master B executes the `cluster-zone` check, everything works well.

Maybe you're lucky and everything [you need] _works_, but I doubt it _works well_. Icinga has not been built for permanently disconnecting, say, the red path on the picture. You should really get **two** checks as explained above to get noticed about the failure ASAP.
