### ISSUE TITLE
systemd unit timeout set to 30 minutes - excessively long 

### ISSUE THREAD

**Issue by willfurnell** [Icinga/icinga2#8757]
Hello,
The Icinga2 systemd unit timeout is set to 30 minutes, which seems rather long. We've had an issue with something going wrong with Icinga on boot on a particular host, and this timeout has delayed the whole host booting by 30 minutes.

Here's where it's defined in the repository:
https://github.com/Icinga/icinga2/blob/master/etc/initsystem/icinga2.service.cmake

Would it be possible to reduce this timeout? Or is there a particular reason why it's this long?

Thank you very much.

**Comment by Al2Klimov** [comment]
As we load the config before notifying systemd: of course we need that time.
