### ISSUE TITLE
Documentation about the new perfdata UOMs unclear

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga2#8758]
## Describe the bug

Icinga 2 will support additional UOMs with the next major version. (#7225) There's also documentation for this: https://github.com/Icinga/icinga2/blob/master/doc/05-service-monitoring.md#unit-of-measurement-uom-

The problem is that the documentation speaks of normalizing a plugin's perfdata of known units to a so called *common base*. This common base is nowhere mentioned.

## Expected behavior

The documentation should mention what the *common base* is for the respective UOMs.

## Additional context

Icinga DB Web (and potentially Icinga Web 2 monitoring) should also be able to interpret these new UOMs. Since Icinga 2 will normalize a plugin's perfdata to the mentioned *common base*, web needs to know that to be able to *de-normalize* the values in order to present them to the user.

**Comment by nilmerg** [comment]
@Al2Klimov Please ensure to note down the respective *common bases* here if there's not enough time to fix the documentation. We need it *now* for https://github.com/Icinga/icingadb-web/issues/71.

**Comment by Al2Klimov** [comment]
De-normalize the values in the web? How would you de-normalize 60s? 1m? 60000ms?

Spoiler: you can’t. You don’t know whether the plugin fed in 60s, 1m or 60000ms **after** normalization.

**Comment by nilmerg** [comment]
Yes, we de-normalize values in web. Or to say it differently, web does some formatting to present the user the shortest presentation: 100000B will show up as 100kB

Looked at the PR you've made now. I don't like the passive-aggressive tone, but anyway. It does make it clear, that Web doesn't need to know the *common base* at all, since Icinga2 doesn't normalize what is put into the database...

I'm really surprised that it works this way. I was under the impression that if Icinga 2 gets proper support for various UOMs and applies this to the metric writers, it does the same for the database writers. Now Web needs to add the exact same algorithm to parse perfdata and be in-line with what Icinga2's metric writers provide to graphing backends. :roll_eyes: 

@lippserd Is there any chance we can change this?

**Comment by Al2Klimov** [comment]
@nilmerg So you'd like to present the perfdata to the DB web user as simple as possible as IW2 does now? But you'd like not to duplicate all the new UoMs? (I2<->DB web)

What about this: Redis+MySQL also provide the perfdata as DB web wants to display it. I.e. the 0.1MB yielded by the plugin becomes not the 100000B for the graphers, but 100kB. Meanwhile you just display the perfdata as-is and once I've implemented the new column you just switch to this column – and get pretty data for free.

**Comment by nilmerg** [comment]
No, I don't want pre-prettified data. I want normalized data just like the graphers get. It's the grapher's (Web's) task to format it in a way the user can grasp it easily. Don't complicate things again, a new column with the normalized values and everyone is satisfied. Thank you.
