### ISSUE TITLE
IDO cleanup performance

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga2#8817]
## Describe the bug

In larger installations of Icinga 2, IDO DB cleanup can become a challenge. Those cleanup queries are scheduled in between any other INSERT or UPDATE query, so they can deferred other queries over time.

Problems:
- Cleanup queries block any other query in execution
- cleanup is scheduled every 60 seconds, this is not configurable and is not run in a separate DB connection (as it was in Icinga 1)
- No limiting exists for those queries, so when enabling cleanup the DELETE would be even larger
- Some indexes are missing (#7753)

## To Reproduce

Not easy to reproduce, you would need a large system with a lot of history in the IDO.

Then you can watch the pending queries, either in log or metrics from the `ido` check.

## Expected behavior

Cleanup should never affect the normal output to IDO.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.12.3
* Operating System and version: CentOS 7

## Additional context

* ref/NC/706743
* I've written a tool to realize cleanup outside of Icinga 2 https://github.com/NETWAYS/ido-cleanup

**Comment by Al2Klimov** [comment]
Would an optional time period be a reasonable option?

**Comment by lazyfrosch** [comment]
Maybe helpful, but usually Icinga is 24x7 relevant, so there is no particular good TP to run cleanup.

I've utilized a LIMIT for the DELETEs and a configurable interval, as well as a fast interval, when there is more to delete.

https://github.com/NETWAYS/ido-cleanup uses this behavior.

**Comment by julianbrost** [comment]
Given that Icinga DB was release, this is unlikely to receive any more attention.
