### ISSUE TITLE
Use source location when modifying existing config files

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#8834]
When Icinga has to modify existing configuration files (for example when deleting objects using the API), it currently just computes the file name where it would now safe the object to using `GetObjectConfigPath()` and then uses this path: https://github.com/Icinga/icinga2/blob/ee705bb110e802f8cafd21bab2d8697b0a538b0a/lib/remote/configobjectutility.cpp#L335-L344

This makes it exceptionally hard to change the schema of these file names, but there are known problems with the existing names (notably due to filename length limits). However, Icinga also knows the file location from where it actually read the config object. Therefore we should consider using this location instead.

This comes with a bit of work to do, notably finding all the places in the code that need to be modified, and, more importantly, ensure that this will check that it operates only on files it's supposed to (i.e. those in `/var/lib/icinga2/api/packages/_api/` and never in `/etc/icinga2/` or `/var/lib/icinga2/api/zones/`

**Comment by Al2Klimov** [comment]
FYI: putting this on the milestone for the sake of #8844.
