### ISSUE TITLE
Inconsistent IDO schema versions

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#8852]
With the 2.11 release, some inconsistencies in the IDO schema version were introduced:

* Importing the MySQL schema into a fresh database writes version 1.14.3 into the database: https://github.com/Icinga/icinga2/blob/31f97d3e6ae71059d714de2cfb4bf840b274bf75/lib/db_ido_mysql/schema/mysql.sql#L1663-L1664
* However, there's a MySQL schema upgrade that sets the version to 1.15.0 https://github.com/Icinga/icinga2/blob/31f97d3e6ae71059d714de2cfb4bf840b274bf75/lib/db_ido_mysql/schema/upgrade/2.11.0.sql#L89
* PostgresSQL schema is still at version 1.14.3 and there was no upgrade to schema version 1.15.0 with Icinga 2.11: https://github.com/Icinga/icinga2/blob/31f97d3e6ae71059d714de2cfb4bf840b274bf75/lib/db_ido_pgsql/schema/pgsql.sql#L1732
* IDO always checks for schema version 1.14.3: https://github.com/Icinga/icinga2/blob/31f97d3e6ae71059d714de2cfb4bf840b274bf75/lib/db_ido/dbconnection.hpp#L15-L16

**Comment by julianbrost** [comment]
@lippserd pointed out that schema version seem to come from Icinga 1 version numbers (1.14.2 was the last release there), so maybe we can just bump everything to current Icinga 2 version numbers?

However, since we only have a pending schema upgrade for MySQL with 2.13, so we'd have to ship an upgrade for PostgreSQL that does nothing except bumping the schema version. This would just be annoying for users for no real improvement.

**Comment by lippserd** [comment]
We discussed leaving the PostgreSQL schema version unchanged and setting the MySQL schema version to `1.15.1` in the next upgrade script and in the schema.
