### ISSUE TITLE
passive service does a recheck after receiving a critical

### ISSUE THREAD

**Issue by e3k** [Icinga/icinga2#8893]
## Describe the bug
We have multiple passive services defined where active checking is disabled and max check attempts is defined to 1. Volatile was set to false. After some of this services go critical after 60 secs they are rechecked actively by a dummy check which leads to wrong results.

Workaround: set volatile to true.

## To Reproduce
1. a passive service receives a critical
2. wait 60sec (default for recheck)
3. the service is actively check with dummy command and gets OK

## Expected behavior
1. a passive service receives a critical
2. wait 60sec (default for recheck)
3. the service remains in critical status until another status is received.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.12.3-1.el7
* Operating System and version: RHEL 7.9
* Enabled features (`icinga2 feature list`): Enabled features: api checker command graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.8.2
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by Yonas-net** [comment]
Hi @e3k , thanks for the report.

Trying to reproduce this wasn't successful. Could you possibly post some of your configs here? And if possible could you also upgrade to the latest release and see if the problem still persists. Thanks!

**Comment by e3k** [comment]
__name	"hostname01!xxxxxx"
acknowledgement	0
acknowledgement_expiry	0
acknowledgement_last_change	1624891200.163726
action_url	""
active	true
**check_attempt	1**
check_command	dummy
check_interval	300
check_period	""
check_timeout	null
command_endpoint	""
display_name	"xxxx"
downtime_depth	0
**enable_active_checks	false**
enable_event_handler	false
enable_flapping	false
enable_notifications	true
**enable_passive_checks	true**
enable_perfdata	false
event_command	""
flapping	false
flapping_current	11.300000
flapping_last_change	0
flapping_threshold	0
flapping_threshold_high	30
flapping_threshold_low	25
force_next_check	false
force_next_notification	false
groups	
ha_mode	0
handled	false
host_name	"hostname01"
icon_image	""
icon_image_alt	""
last_check	1625748197.388332
last_hard_state	0
last_hard_state_change	1624891200.609637
last_reachable	true
last_state	0
last_state_change	1624891200.609637
last_state_critical	1624891100.066516
last_state_ok	1625748197.401648
last_state_type	1
last_state_unknown	0
last_state_unreachable	0
last_state_warning	0
**max_check_attempts	1**
name	"xxxx"
next_check	1628849985.861403
next_update	1625748798.164978
notes	""
notes_url	""
original_attributes	null
package	"_api"
paused	true
previous_state_change	1624891200.609637
problem	false
retry_interval	60
severity	0
state	0
state_type	1
type	"Service"
version	1624891099.983699
**volatile	false**
zone	"A_Master"

sorry cant update it now it is a productive system.

**Comment by e3k** [comment]
i will let you know once that happens.

**Comment by Al2Klimov** [comment]
Hello again @e3k!

Any news from your side?

Best,
AK

**Comment by e3k** [comment]
hi Al2Klimov. The news is that i don't work at the company anymore so i can't tell you...
