### ISSUE TITLE
Provide a way to see all the certificates issued/signed by the Icinga2 CA

### ISSUE THREAD

**Issue by offsides** [Icinga/icinga2#8910]
In light of the security issues fixed in the 2.12.5 release, is there any way to have the CA provide a list of all the certificates that it has signed? Normally an OpenSSL CA maintains copies of all the certs it signs, but I don’t see that anywhere in /var/lib/icinga2, and I don’t think it would be kept anywhere else. And if this isn’t possible, I would suggest that perhaps this would be a good idea, even if it’s just a list of the certs issued? I don’t think the CA and everything need to be replaced, but if I can’t verify that it hasn’t been compromised then due diligence requires that I do so (and so should probably everybody)…

For reference, the command 'icinga2 ca list' only shows any pending CA signing requests, but there's nowhere that I've found that you can find all the certificates themselves.

**Comment by julianbrost** [comment]
Duplicate of #5556
