### ISSUE TITLE
Performance data in multiline output is not correctly parsed

### ISSUE THREAD

**Issue by pdorschner** [Icinga/icinga2#8912]
## Describe the bug

If a plugin returns multiple lines of both text output (long text line) and optional/perfdata, Icinga 2 / Icinga Web 2 will not display it correctly and perfdata is written in a false format to graphite.

## To Reproduce

Like in the guidelines of [Nagios Plugin API(see case 3)](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html), create a plugin which prints the output like so:
<pre><code>TEXT OUTPUT | OPTIONAL PERFDATA
LONG TEXT LINE 1
LONG TEXT LINE 2
...
LONG TEXT LINE N | PERFDATA LINE 2
PERFDATA LINE 3
...
PERFDATA LINE N
</code></pre>

1. Check Icinga Web 2 if all perfdata will be displayed correctly
2. Check Graphite if all perfata is written correctly

## Expected behavior

If a plugin returns multiple lines of both text output and perfdata, Icinga 2/ Icinga Web 2 will  display all perfdata  correctly and forward it to Graphite in the correct format.

## Screenshots

Plugin output on CLI:

> Notice the perfdata: 'kpi_avg_mem_util'

<pre><code>OK - 8 counters checked, 8 ok| 'kpi_avg_cpu_occ'=37
[0] rpn_cap_snd_idp_sms OK - rpn_cap_snd_idp_sms: 741
[1] rpn_cc_map_remote_prv_no_rsp_from_peer OK - rpn_cc_map_remote_prv_no_rsp_from_peer: 10
[2] rpn_diameter_snd_acr OK - rpn_diameter_snd_acr: 9451
[3] rpn_map_atsi_sent OK - rpn_map_atsi_sent: 1702
[4] rpn_map_mo_fsm_rcvd OK - rpn_map_mo_fsm_rcvd: 12856
[5] rpn_map_mo_fsm_sent OK - rpn_map_mo_fsm_sent: 4274
[6] rpn_map_sri_sm_sent OK - rpn_map_sri_sm_sent: 12145
[7] rpn_sip_rcv_msg_200 OK - rpn_sip_rcv_msg_200: 11982| 'kpi_avg_mem_util'=58 'kpi_mavkpi_map_sri_proc_rate_egress'=99.92 'kpi_sip_rate_reg-ok'=100.01 
</code></pre>

As you can see, the "second" perfdata: 'kpi_avg_mem_util' will not be displayed:
![github_issue_icinga_web](https://user-images.githubusercontent.com/37802318/126316156-1d5e2473-755a-4ffa-bb4b-d92a99a682c6.png)

But is written in the false format to graphite:
<code>ls  /opt/graphite/storage/whisper/...</code>

![github_issue_graphite](https://user-images.githubusercontent.com/37802318/126316432-de3d5175-83ee-4bfd-b362-2b655181bea0.png)

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used:  2.12.3
* Icinga Web 2 version: 2 2.8.2

## Additional context

The perfdata could be parsed correctly if there are no LONG TEXT LINE or optional  PERFDATA like so:
<pre><code>TEXT OUTPUT |  PERFDATA LINE</code></pre>

**Comment by Al2Klimov** [comment]
## Tasks

* Reproduce
* Provide detailed reproduction instructions

**Comment by Yonas-net** [comment]
**To Reproduce**
I'm using our internal dev docker. Put the following file to ``env/icinga2/custom.conf.d/`` directory and make sure that icinga2 graphite feature is also enabled and `enable_send_thresholds` set to true.

`custom-hosts.conf`:
```bash
object Host "perfdata-dummy-test" {
    import "generic-host"

    address = "127.0.0.1"
    check_command = "dummy"

    vars.dummy_state = {{
        return 0
    }}

    vars.dummy_text = {{
        var output = "OK - 8 counters checked, 8 ok| 'kpi_avg_cpu_occ'=37 \
            [0] rpn_cap_snd_idp_sms OK - rpn_cap_snd_idp_sms: 741 \
            [1] rpn_cc_map_remote_prv_no_rsp_from_peer OK - rpn_cc_map_remote_prv_no_rsp_from_peer: 10 \
            [2] rpn_diameter_snd_acr OK - rpn_diameter_snd_acr: 9451 \
            [3] rpn_map_atsi_sent OK - rpn_map_atsi_sent: 1702 \
            [4] rpn_map_mo_fsm_rcvd OK - rpn_map_mo_fsm_rcvd: 12856 \
            [5] rpn_map_mo_fsm_sent OK - rpn_map_mo_fsm_sent: 4274 \
            [6] rpn_map_sri_sm_sent OK - rpn_map_sri_sm_sent: 12145 \
            [7] rpn_sip_rcv_msg_200 OK - rpn_sip_rcv_msg_200: 11982| 'kpi_avg_mem_util'=58 'kpi_mavkpi_map_sri_proc_rate_egress'=99.92 'kpi_sip_rate_reg-ok'=100.01"

        return output
    }}
}
```

**Icinga Web 2**:

<img width="1137" alt="Bildschirmfoto 2021-08-10 um 12 57 00" src="https://user-images.githubusercontent.com/57616252/128855147-cc06e7fb-7aa0-4048-b301-1cb82a1c00b9.png">

*short output*:
```sql
MariaDB [icinga2]> SELECT output, perfdata FROM icinga_hoststatus where host_object_id=773;
+-------------------------------+-------------------------------------------------------------------------------------------------------------------+
| output                        | perfdata                                                                                                          |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------+
| OK - 8 counters checked, 8 ok | kpi_avg_cpu_occ=37 '  'kpi_avg_mem_util''=58 kpi_mavkpi_map_sri_proc_rate_egress=99.92 kpi_sip_rate_reg-ok=100.01 |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------+
```
*With long output*:
```sql
MariaDB [icinga2]> SELECT output, long_output, perfdata FROM icinga_hoststatus where host_object_id=773;
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| output                        | long_output                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | perfdata                                                                                                          |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| OK - 8 counters checked, 8 ok |             [0] rpn_cap_snd_idp_sms OK - rpn_cap_snd_idp_sms: 741 \n            [1] rpn_cc_map_remote_prv_no_rsp_from_peer OK - rpn_cc_map_remote_prv_no_rsp_from_peer: 10 \n            [2] rpn_diameter_snd_acr OK - rpn_diameter_snd_acr: 9451 \n            [3] rpn_map_atsi_sent OK - rpn_map_atsi_sent: 1702 \n            [4] rpn_map_mo_fsm_rcvd OK - rpn_map_mo_fsm_rcvd: 12856 \n            [5] rpn_map_mo_fsm_sent OK - rpn_map_mo_fsm_sent: 4274 \n            [6] rpn_map_sri_sm_sent OK - rpn_map_sri_sm_sent: 12145 \n            [7] rpn_sip_rcv_msg_200 OK - rpn_sip_rcv_msg_200: 11982 | kpi_avg_cpu_occ=37 '  'kpi_avg_mem_util''=58 kpi_mavkpi_map_sri_proc_rate_egress=99.92 kpi_sip_rate_reg-ok=100.01 |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
```

For some reason Icinga2 is sending only one PerfData label to graphite. Haven't debugged why this happens, so can't confirm at the moment in which format the labels are stored in graphite.

**Graphite**:

<img width="287" alt="Bildschirmfoto 2021-08-10 um 13 05 15" src="https://user-images.githubusercontent.com/57616252/128856467-445a4e0f-c25d-4ee8-ad2f-bd47c6e016b3.png">

**Comment by Al2Klimov** [comment]
> Haven't debugged why this happens

Please do that.

**Comment by Yonas-net** [comment]
**Update**

<img width="388" alt="Bildschirmfoto 2021-08-10 um 13 18 32" src="https://user-images.githubusercontent.com/57616252/128858235-9b2438a8-b8c3-438c-a324-ec6044ab2e84.png">

**Comment by Al2Klimov** [comment]
So now the instructions https://github.com/Icinga/icinga2/issues/8912#issuecomment-895938876 work?

**Comment by Yonas-net** [comment]
> So now the instructions [#8912 (comment)](https://github.com/Icinga/icinga2/issues/8912#issuecomment-895938876) work?

Sure. I was just too hasty, when you let icinga2 run for a while then all the other PerfData labels are sent as well.

**Comment by Al2Klimov** [comment]
## Task

Debug why https://github.com/Icinga/icinga2/issues/8912#issuecomment-895947226 happens.

**Comment by Yonas-net** [comment]
The output of the API query is also broken. 😞 

```bash
"last_check_result": {
                    "active": true,
                    "check_source": "master",
                    "command": "dummy",
                    "execution_end": 1628601546.908078,
                    "execution_start": 1628601546.908078,
                    "exit_status": 0,
                    "output": "OK - 8 counters checked, 8 ok\n            [0] rpn_cap_snd_idp_sms OK - rpn_cap_snd_idp_sms: 741 \n            [1] rpn_cc_map_remote_prv_no_rsp_from_peer OK - rpn_cc_map_remote_prv_no_rsp_from_peer: 10 \n            [2] rpn_diameter_snd_acr OK - rpn_diameter_snd_acr: 9451 \n            [3] rpn_map_atsi_sent OK - rpn_map_atsi_sent: 1702 \n            [4] rpn_map_mo_fsm_rcvd OK - rpn_map_mo_fsm_rcvd: 12856 \n            [5] rpn_map_mo_fsm_sent OK - rpn_map_mo_fsm_sent: 4274 \n            [6] rpn_map_sri_sm_sent OK - rpn_map_sri_sm_sent: 12145 \n            [7] rpn_sip_rcv_msg_200 OK - rpn_sip_rcv_msg_200: 11982",
                    "performance_data": [
                        "kpi_avg_cpu_occ=37",
                        "'  'kpi_avg_mem_util''=58",
                        "kpi_mavkpi_map_sri_proc_rate_egress=99.92",
                        "kpi_sip_rate_reg-ok=100.01"
                    ],
```
