### ISSUE TITLE
[ITL] The command definition for check_postgresql is lacking some important options

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icinga2#8922]
Some options necessary for some of the functionality of check_postgres are missing from the command definition in the ITL:

```
--datadir (location of the PostgreSQL data directory)
--language (language to use for messages)
--perflimit (limit the number of performance data to report)
```

The data directory must be specified for some of the plugin's functions, such as e.g. prepared transactions, locks, bloat and some more.

Specifying the language is required because the plugin tries to be "intelligent" and determine the language from the system language, among other things. In many cases that's not what is required in the monitoring environment, especially in notifications, so explicitly specifying the language is a much-needed option.

Limiting the number of performance data is necessary in some cases where a monitored database has lots of tables or indices and the amount of performance data returned causes performance issues and/or data bloat in the TSDB, if one is used.

* Version used: `icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.5-2)`
* Operating System and version: `AlmaLinux release 8.4 (Electric Cheetah)`
* Plugin version: `check_postgres.pl version 2.25.0`

**Comment by Al2Klimov** [comment]
Hello @peteeckel!

Please could you reference addressed issues with "fixes #ISSUE_NUMBER" in your PRs' descriptions?

Best,
AK

**Comment by peteeckel** [comment]
I adjusted the PR descriptions to contain the "fixed #..." statement. Would you prefer the commit messages to be edited as well? In that case I'd edit and re-push the commits to make the messages more concise.

**Comment by Al2Klimov** [comment]
No, thanks. No need for unnecessary force-pushing.
