### ISSUE TITLE
Using Rememerme causes an SQL Error

### ISSUE THREAD

**Issue by feuertaenzer** [Icinga/icinga2#8936]
## Describe the bug

We performed the update and try to use the new remember-me-feature. Unfortunately whenever we turn on rememberme during the login process we end up with the following error message.
After refreshing the page, everything else works fine. I'll also add a screenshot below

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'Icinga2_IcingaWeb2.icingaweb_rememberme' doesn't exist
`#0 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(401): PDO->prepare(String)
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(438): ipl\Sql\Connection->prepexec(String)
#2 /usr/share/php/Icinga/Web/RememberMe.php(231): ipl\Sql\Connection->insert(String, Array)
#3 /usr/share/icingaweb2/application/forms/Authentication/LoginForm.php(142): Icinga\Web\RememberMe->persist()
#4 /usr/share/php/Icinga/Web/Form.php(1178): Icinga\Forms\Authentication\LoginForm->onSuccess()
#5 /usr/share/icingaweb2/application/controllers/AuthenticationController.php(83): Icinga\Web\Form->handleRequest()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AuthenticationController->loginAction()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#12 {main}`

## To Reproduce

1. Provide username & password
2. Turn on Remember-me
3. Click Log in

## Expected behavior

A log in an forward to the dashboard

## Screenshots

![Bildschirmfoto 2021-07-26 um 16 48 34](https://user-images.githubusercontent.com/87800757/127109793-1c19b595-6cf7-405b-81cb-7bc1162f82e7.png)

## Your Environment

* Version used (`icinga2 --version`): r2.12.5-1
* Operating System and version: Ubuntu 18.04
* Enabled features (`icinga2 feature list`): api checker command graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): Version 2.9.0, Modules: director 1.8.0, graphite 1.1.0, incubator 0.6.0, ipl v0.5.0, jira 1.1.0, monitoring 2.9.0, reactbundle 0.8.0

**Comment by julianbrost** [comment]
Looks like you haven't applied the database schema upgrade for 2.9.0, see also https://icinga.com/docs/icinga-web-2/latest/doc/80-Upgrading/#upgrading-to-icinga-web-2-29x
