### ISSUE TITLE
Not sending down Host / Service Notifications

### ISSUE THREAD

**Issue by Alex64798** [Icinga/icinga2#8964]
## Describe the bug

We have a problem that when a service is down we do not become notification but when is come back in OK State we become a notification.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.13.0-1
* Operating System and version: CentOS 7
* Enabled features (`icinga2 feature list`): Disabled features: compatlog debuglog elasticsearch gelf icingadb influxdb influxdb2 livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.9.2
* ![image](https://user-images.githubusercontent.com/86724320/128677550-795cf6a0-8519-405a-a2ba-11b04438679a.png)

* Config validation (`icinga2 daemon -C`): OK

**Comment by Yonas-net** [comment]
Hi @Alex64798 , Thank you for the report.

Can you also share your `Notification/Host/Service` configs of the affected objects here please?

**Comment by Alex64798** [comment]
Notification Apply Rule:

```
apply Notification "Apply Regel Service" to Service {
    import "Service Host"

    assign where match("*", service.name)
    states = [ Critical, OK, Unknown, Warning ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    users = [ "Support" ]
}

apply Notification "Apply Regel Host" to Host {
    import "Mail Host"

    assign where match("*", host.name)
    states = [ Down, Up ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    users = [ "Support" ]
}

apply Notification "Apply Regel Teams Host" to Host {
    import "Teams Host"

    assign where match("*", host.name)
    states = [ Down, Up ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    users = [ "Support" ]
}

apply Notification "Apply Regel Teams Service" to Service {
    import "Teams Service"

    assign where match("*", service.name)
    states = [ Critical, OK, Unknown, Warning ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    users = [ "Support" ]
}
```

Notification Templates:

```
template Notification "Mail Host" {
    times.begin = 1m
    times.end = 0s
    command = "mail-host-notification1"
    interval = 5m
    period = "generic-timeperiod"
    states = [ Down, Up ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    users = [ "Support" ]
}

template Notification "Service Host" {
    times.begin = 1m
    times.end = 0s
    command = "mail-service-notification1"
    interval = 5m
    period = "generic-timeperiod"
    states = [ Critical, OK, Unknown, Warning ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    users = [ "Support" ]
}

template Notification "Teams Host" {
    times.begin = 1m
    times.end = 0s
    command = "teams-host-notification"
    interval = 5m
    period = "generic-timeperiod"
    states = [ Down, Up ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    users = [ "Support" ]
}

template Notification "Teams Service" {
    times.begin = 1m
    times.end = 0s
    command = "teams-service-notification"
    interval = 5m
    period = "generic-timeperiod"
    states = [ Critical, OK, Unknown, Warning ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    users = [ "Support" ]
}
```

**Comment by Yonas-net** [comment]
Seems pretty good, actually. Could you also post the configuration from the `Support` user here please? What does `states` and `types` have in there?

**Comment by Alex64798** [comment]
> Seems pretty good, actually. Could you also post the configuration from the `Support` user here please? What does `states` and `types` have in there?

```
object User "Support" {
    import "Admins"

    display_name = "ICINGA ALARM"
    email = "EMAIL"
    pager = "WEBHOOK"
    enable_notifications = true
    period = "generic-timeperiod"
    states = [ Critical, Down, OK, Unknown, Up, Warning ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
}
```

**Comment by Alex64798** [comment]
> Seems pretty good, actually. Could you also post the configuration from the `Support` user here please? What does `states` and `types` have in there?

Hello,
have you updates for me?

**Comment by Yonas-net** [comment]
I can't reproduce it, though. Could you please also share the relevant Notification histories of the affected `Host/Service` object, from Icinga Web 2.

**Comment by Alex64798** [comment]
So the notifications were still working before the update to Icingaweb2 2.9.3. What logs would you need exactly, would you have a path for me?

**Comment by Alex64798** [comment]
Give a Option to downgrade to last functionallty version of 2.9.2 ?

**Comment by Yonas-net** [comment]
> So the notifications were still working before the update to Icingaweb2 2.9.3.

I would be really interested on this, as Icinga Web 2 doesn't have anything to do with sending and not sending notifications.

> What logs would you need exactly, would you have a path for me?

There is a notification history overview, when and for which state of the filtered `host/service` object are being transmitted and this can be found at the following url `icingaweb2/monitoring/hosts` then click on the host in question (**for which you didn't receive a DOWN notification**) and navigate to the history tab.

**Comment by Alex64798** [comment]
> > So the notifications were still working before the update to Icingaweb2 2.9.3.
> 
> I would be really interested on this, as Icinga Web 2 doesn't have anything to do with sending and not sending notifications.
> 
> > What logs would you need exactly, would you have a path for me?
> 
> There is a notification history overview, when and for which state of the filtered `host/service` object are being transmitted and this can be found at the following url `icingaweb2/monitoring/hosts` then click on the host in question (**for which you didn't receive a DOWN notification**) and navigate to the history tab.

We have a script that send mails an a message to a webhook, since the update before 4 weeks all was work good. Since the Update Icinga we have the Problem. Manual sending notifications works but not automatically.

Here we see that Icinga create Notifcation but not send this to any contact.
![image](https://user-images.githubusercontent.com/86724320/132499475-60f1effa-a046-4f7c-bd19-8fb096ab65d8.png)

So summarized since the update no longer sets the notification contact, however, we have not changed anything in the Apply Rules.

**Comment by Alex64798** [comment]
> > So the notifications were still working before the update to Icingaweb2 2.9.3.
> 
> I would be really interested on this, as Icinga Web 2 doesn't have anything to do with sending and not sending notifications.
> 
> > What logs would you need exactly, would you have a path for me?
> 
> There is a notification history overview, when and for which state of the filtered `host/service` object are being transmitted and this can be found at the following url `icingaweb2/monitoring/hosts` then click on the host in question (**for which you didn't receive a DOWN notification**) and navigate to the history tab.

Is there information okay?

**Comment by Alex64798** [comment]
@Yonas-net Have you news for me?

**Comment by Yonas-net** [comment]
Sorry, but I still can' t figure out what the problem could be. Could you possibly start 🤔 icinga2 in debug or notice mode and grep for `Notification` when the problem still occurs and you can easily reproduce it? Then i would send you an upload link and upload the logs there?

**Comment by Alex64798** [comment]
> Sorry, but I still can' t figure out what the problem could be. Could you possibly start 🤔 icinga2 in debug or notice mode and grep for `Notification` when the problem still occurs and you can easily reproduce it? Then i would send you an upload link and upload the logs there?

Okay, how i can set icinga2 in debug mode?

**Comment by Yonas-net** [comment]
> Okay, how i can set icinga2 in debug mode?

https://icinga.com/docs/icinga-2/latest/doc/15-troubleshooting/#enable-debug-output

**Comment by Alex64798** [comment]
> Sorry, but I still can' t figure out what the problem could be. Could you possibly start 🤔 icinga2 in debug or notice mode and grep for `Notification` when the problem still occurs and you can easily reproduce it? Then i would send you an upload link and upload the logs there?

Okay i have now the logs ready, can you sende me a upload link for the logs?

**Comment by Yonas-net** [comment]
> Okay i have now the logs ready, can you sende me a upload link for the logs?

https://nextcloud.icinga.com/index.php/s/kCgtxTBKL54S5GN

**Comment by Alex64798** [comment]
> > Okay i have now the logs ready, can you sende me a upload link for the logs?
> 
> https://nextcloud.icinga.com/index.php/s/kCgtxTBKL54S5GN

Logs has been uploaded.

**Comment by Yonas-net** [comment]
I realized this after seeing the logs. The problem is the `times.end` attribute. You have set it to `0s` everywhere and Icinga2 discards all notifications that occur after this `0s` and will most likely never send a notification. If you remove the `times.end` attribute from all notification templatess, it should work again.

**Comment by Alex64798** [comment]
> I realized this after seeing the logs. The problem is the `times.end` attribute. You have set it to `0s` everywhere and Icinga2 discards all notifications that occur after this `0s` and will most likely never send a notification. If you remove the `times.end` attribute from all notification templates, it should work again.

Okay thanks this resolve my problem, now send all host and services notifications :)
