### ISSUE TITLE
icinga2 ca list always empty

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icinga2#8976]
## Describe the bug

I noticed recently that the command: 
does not show any result.

I tried with --all and - removed.

After that i looked into the sourcecodicinga2 ca liste and found that the command checks the directory
/var/lib/icinga2/certificate-requests/

which is also empty.

So I registered a new host with icinga director and self service api, the host gets its certificate and can perform checks but the directroy is still empty

I know it is not an inventory nad weekly cleared

Thanks for your help and best regards

Nicolas

## To Reproduce

register a new host
run icinga2 ca list --all
check dir /var/lib/icinga2/certificate-requests/

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): (version: r2.12.5-1)
* Operating System and version: Ubuntu 18.04
* Enabled features (`icinga2 feature list`): api checker debuglog ido-mysql influxdb mainlog notification
* Icinga Director 1.8.1

**Comment by Al2Klimov** [comment]
> the host gets its certificate and can perform checks

What's the problem then?

**Comment by moreamazingnick** [comment]
Could it be something like that:
If the signing-process via self service api and ticket works as expected the ca list stays empty.

If the signing-process fails there is a cert to sign manually in the list, and after the manual signing it gets renamed and deleted some time later on

**Comment by Al2Klimov** [comment]
Yes.

**Comment by moreamazingnick** [comment]
perfect, closed
