### ISSUE TITLE
2.13.1 agent fails connecting to master

### ISSUE THREAD

**Issue by Sec42** [Icinga/icinga2#8982]
## Describe the bug

Upgrading the icinga agent from 2.13.0 to 2.13.1 makes the connection to the master server(s) fail.

The issue at https://icinga.com/blog/2021/08/19/icinga-2-13-1-security-release// does not mention the agent connection being affected

## Your Environment

master server is currently at 2.12.4-1

Logfile messages on the agent:

[2021-08-24 06:01:45 +0000] warning/ApiListener: Certificate validation failed for endpoint 'munnvmonpmac11': code 62: Hostname mismatch
[2021-08-24 06:01:45 +0000] information/ApiListener: New client connection for identity 'munnvmonpmac11' to [IP.AD.DR.ES]:5665 (certificate validation failed: code 62: Hostname mismatch)

The cert file in /var/lib/icinga2/certs/ for the master server does have the hostname, IP & FQDN in it:
Subject:              munnvmonpmac11
SubjectAltNames:      IP Address:IP.AD.DR.ES, DNS:munnvmonpmac11.pci.neosventures.com

**Comment by julianbrost** [comment]
Was this certificate issued by Icinga or some external tooling?

Part of this fix was to enable standard OpenSSL name validation on TLS client connections which prefers subject alternative names (if present) over the common name.

**Comment by R-Sommer** [comment]
You are trying to run an [unsupported version mix](https://icinga.com/docs/icinga-2/latest/doc/06-distributed-monitoring/#versions-and-upgrade).

**Comment by Sec42** [comment]
@julianbrost  you were on the right track.

Meanwhile I found the problem. The certificate of the icinga server looked like this:
```
Subject:              munnvmonpmac11
SubjectAltNames:      IP Address:IP.AD.DR.ES, DNS:munnvmonpmac11.pci.neosventures.com
```

which worked fine with 2.13.0 clients. However with 2.13.1 clients it needs include the CN also in the AltNames like this:

```
Subject:              munnvmonpmac11
SubjectAltNames:      IP Address:IP.AD.DR.ES, DNS:munnvmonpmac11.pci.neosventures.com, DNS:munnvmonpmac11
```

Maybe a notice about this should be put into the changelog / upgrading notes.
