### ISSUE TITLE
IcingaDB Redis: Downtime event appears twice in icinga:runtime stream

### ISSUE THREAD

**Issue by mpmX** [Icinga/icinga2#8985]
Icinga Version: 2.13.1

In my test setup, I have one host (influxdb) with one service (random).
When I set a downtime on the host, the icinga:runtime stream contains two downtime events for the host and two for the service (see screenshot).
![image](https://user-images.githubusercontent.com/2395900/131125941-8097756f-ee95-4e59-a149-18dbbf0478b1.png)
The expected behavior would be that the event only shows up once for the host and once for the service.

Other questions:
Are the icinga:runtime and icinga:runtime:state streams consumed by the IcingaDB daemon?
Do these streams have a maxlen or should one prune the stream periodically to avoid OOM?

**Comment by mpmX** [comment]
Seems to be the case when sticky=True

**Comment by Al2Klimov** [comment]
## Task

Figure out what's the problem here.

**Comment by Yonas-net** [comment]
Since when creating a downtime the `OnVersionChangedHandler` signal is also triggered, icingadb is sending the config updates twice, once in `IcingaDB::DowntimeStartedHandler()` and in `IcingaDB::VersionChangedHandler()`.

**Comment by mpmX** [comment]
I'm listening to the stream using redis consumer groups and forward (some) events to a custom redis stream which is then exposed to my custom frontend via websocket. Because the two downtime events may be processed by different consumers, I cannot make a deduplication there.

**Comment by Al2Klimov** [comment]
Can't you use https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#icinga2-api-event-streams ?

**Comment by mpmX** [comment]
I previously used the HTTP streams but I prefer Redis streams because they provide features like Consumer Groups & Event Acknowledgement. Anyways, thanks for looking into this!
