### ISSUE TITLE
Zone and endpoint object are not longer required to be defined in zones.conf only?

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icinga2#8987]
With 2.13.1-1 it looks like I can define zone and endpoint objects elsewhere. Is this a bug or feature that they do not have to be defined in zones.conf only (which was introduced with 2.11)?

**Comment by julianbrost** [comment]
What change in 2.11 are you referring to? The `zones.conf` is not really special, it's simply included in `icinga2.conf`. It's only special in that stuff like `icinga2 node wizard` writes to that file, but the daemon itself doesn't really care. In case you want to sync endpoint/zone objects, you just have to be careful to not introduce any dependency cycles (i.e. a node can't sync config for its parent as it already needs this to perform the sync).

**Comment by R-Sommer** [comment]
I've tried to reproduce but couldn't find a valid example. Let's close this issue.
