### ISSUE TITLE
raspbian bullseye repo doesn't have armhf/arm64 releases

### ISSUE THREAD

**Issue by gianmarco-mameli** [Icinga/icinga2#8997]
## Describe the bug

Hi, i've configured the Icinga2 raspbian repo for bullseye, but the releases are only for amd64/i386, no compatible with any Raspberry Pi
Is it possible to have armhf and arm64 releases?

Thanks

## To Reproduce

Configure this repo deb [signed-by=/usr/share/keyrings/icinga-archive-keyring.gpg] http://packages.icinga.com/raspbian icinga-bullseye main

No armhf/arm64 releases

## Expected behavior

armhf/arm64 releases for installing icinga2 packages

## Your Environment

* Operating System and version: RaspberryOS/Debian Bullseye 11.0

**Comment by julianbrost** [comment]
As far as I can tell, Raspbian based on Debian bullseye was not released yet. So we will probably take care of it once that happens.

**Comment by gianmarco-mameli** [comment]
ok no problem, but I don't understand why make publicly available a repo without the correct architectures, bullseye in fact is installable without problems on arm cpus. Anyway thanks for your info.

**Comment by KKeXX** [comment]
As Raspberry PI OS Bullseye has been released officially by the end of October. Do you have planes about a package for armhf?

**Comment by mkrauser** [comment]
I would love to see packages for arm64 and armhf as well!
