### ISSUE TITLE
code security assessments

### ISSUE THREAD

**Issue by servicesarchitecturemanager** [Icinga/icinga2#9031]
Hi 
Given the Solarwinds agent attack, is the code of the Icinga Agent (Windows and Unix) subjected to scans such as SAST , DAST, pen-test after each significant release, either by a third party or by the dev team?

**Comment by servicesarchitecturemanager** [comment]
would like an answer on current situation or plans

**Comment by lippserd** [comment]
Hi,

I'm not entirely sure which of these methods would have prevented the SolarWinds hack as it was a supply chain attack. We sign all of our packages so package managers and users verify the integrity. We also have customers and partners who, for example, perform scans with Nessus. Additionally, we have staff with a strong security background to help improve current code and develop new features, as well as internal testing prior to release.

All the best,
Eric
