### ISSUE TITLE
Custom notifications on downed hosts also send another down notification

### ISSUE THREAD

**Issue by dasJ** [Icinga/icinga2#9046]
## Describe the bug

I have a host that is down and that has notifications with `interval = 0` so renotifications are disabled.
When the initial notification was sent and I send another custom notification, it sends another down notification.

## To Reproduce

1. Have a host with notifications that have `interval = 0`
2. Have the host in a down state
3. Wait for the notification to arrive
4. Send a custom notification for this host

## Expected behavior

I should only receive a custom notification and not also a down notification shortly afterwards.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): `r2.13.0-1`
* Operating System and version: `NixOS 21.05`
* Enabled features (`icinga2 feature list`): `api checker ido-mysql notification syslog`
* Icinga Web 2 version and modules (System - About): Irrelevant
* Config validation (`icinga2 daemon -C`): It's valid
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes. Irrelevant

**Comment by Al2Klimov** [comment]
Sounds like #7818

**Comment by yhabteab** [comment]
Duplicate of #6333
