### ISSUE TITLE
Change in performance data values writing to influx after upgrading to 2.13.1

### ISSUE THREAD

**Issue by retozeder** [Icinga/icinga2#9060]
We noticed a sudden change from our icinga perfomance data writing to an influxdb after upgrading to 2.13.1. 

Oct 25 10:11:39 Updated: icinga2-bin-2.13.1-1.el7.icinga.x86_64

At this time, there's a change in values within the influxdb, for example static max values from a memory-check. The following query

`SELECT ("max") FROM "memory-windows" WHERE ("hostname" = 'testserver.local' AND "metric" = 'memory') AND time >= '2021-10-25T08:00:00.000000000Z' AND time <= '2021-10-25T09:25:00.000000000Z'`

results in a new value after the upgrade.

1635148819000000000 12884377600
1635148999000000000 12884377600
1635149179000000000 12884377600
**1635149359000000000 12884377600**
**1635150079000000000 12287500000**
1635150259000000000 12287500000
1635150439000000000 12287500000

The values were correct before and matched the performance data displayed in icingaweb

memory | 2.37 GiB | **12.00 GiB** | 1228.75 MiB | 614.38 MiB

Did something change in how that data is written to influxdb?

**Comment by julianbrost** [comment]
What was the version before the upgrade? Version 2.13 introduced support for more units in perfdata ([docs](https://icinga.com/docs/icinga-2/snapshot/doc/05-service-monitoring/#unit-of-measurement-uom), #7871), maybe that could have introduced some (possibly unwanted) change how existing perfdata is handled.

Can you please provide the raw output of the check command that's used to collect that data?

**Comment by retozeder** [comment]
The version before the update was icinga2-2.12.5. The plugin is executed like this:

`C:\\Program Files\\ICINGA2\\/sbin/check_memory.exe", "-c", "5%", "-u", "mb", "-w", "10%"`

which then results in performance data like this:

`performance_data = [ "memory=1261.19MB;409.50500000000005;204.75250000000003;0;4095.05" ] `

This check was and still is exectued always identically like this.

1635149155000000000 4293971148.8
1635149155000000000 4293971148.8
1635150235000000000 4095050000

But it seems that the current values are correct, i'd guess that there were some changes regarding the metrics (SI vs. IEC) and how this data is processed for the influxdbwriter. Was just a little bit confused suddenly seeing the new values.
