### ISSUE TITLE
Delayed problem notification not trigger if last recovery notification was suppressed

### ISSUE THREAD

**Issue by icurga** [Icinga/icinga2#9066]
## Describe the bug

If the recovery notification - after the last notified delayed problem notification  - is suppressed,
then the next delayed problem notification will not be triggered.

The cases where a recovery is suppressed and the bug follows then:
* Manually disabled notification for the object or globally, while the recovery occurs 
* Soft state overlapping a downtime end, after the recovery happened inside the downtime
* Other bugs leading to a lost recovery notification

This bug **not happening** for recovery notifications suppressed via `states`  and `types`.

## To Reproduce

There are two cases shown in the screenshots below.
Here the steps to reproduce the first one:

1. Create a notification object with delay `times.begin = 10s` and apply it to a service
2. Let the service become `Critical` and notify yourself
3. Disable notifications for the service in Icinga Web or over API
4. Recover the service to `OK` state
5. Enable notifications for the service in Icinga Web or over API
6. Let the service become `Critical` again
7. The delayed `Problem` notification is not triggered

## Expected behavior

Delayed notifications should be triggered when entering a notification window, also if the last recovery notification never happened.
Instant notifications have no problem with the same prequel.

## Screenshots

Notification manually disabled | Soft state overlapping downtime end
------------ | -------------
![NoDelayedProblemNoti_when_lastRecoveryIsMissing](https://user-images.githubusercontent.com/93325902/140912199-8fafa885-fe73-4cde-b369-a87edd4529cd.png)|![NoDelayedProblemNoti_when_lastRecoveryIsMissing2](https://user-images.githubusercontent.com/93325902/140935664-18d8a4cc-25dd-4c24-a017-6c13a093f959.png)

## Your Environment

* Version used (`icinga2 --version`): `2.12.5-1`
* Operating System and version: `CentOS 7 x86_64`
* Enabled features (`icinga2 feature list`): `api checker ido-mysql mainlog notification`
* Icinga Web 2 version and modules (System - About): `2.9.3`
* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: 2.12.5-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga2master-1.monitoring.test
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 3 Users.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 4 TimePeriods.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 Service.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 2 Notifications.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 2 Comments.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 236 CheckCommands.
information/ConfigItem: Instantiated 1 ApiListener.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

## Additional context
This bug was reported by our customer and then reproduced in a fresh installed Icinga single setup.

The relevant objects:
Two users to see the difference between delayed and instant notifications more obvious.
```
object User "INSTA-icingapolice" {
  email = "root@localhost"
}

object User "DELAY-icingacat" {
  email = "root@localhost"
}
```

The only used notification objects:

```
apply Notification "INSTA-Noti" to Service {
  import "mail-service-notification"
  users = [ "INSTA-icingapolice" ]

  interval = 0s

  assign where host.vars.notification.mail
}

apply Notification "DELAY-Noti" to Service {
  import "mail-service-notification"
  users = [ "DELAY-icingacat" ]

  times.begin = 10s
  interval = 0s

  assign where host.vars.notification.mail
}
```
`states` and `types` definition:
```
template Notification "mail-service-notification" {
  command = "mail-service-notification"

  states = [ OK, Critical ]
  types = [ Problem, Recovery ]

  period = "24x7"
}
```

**Comment by icurga** [comment]
In the latest version `2.13.1-1` the bug is no longer present.
I guess this PR https://github.com/Icinga/icinga2/pull/8562 fix this bug here too.

## Screenshots
Notification manually disabled | Soft state overlapping downtime end
------------ | -------------
![FIX-NoDelayedProblemNoti_when_lastRecoveryIsMissing](https://user-images.githubusercontent.com/93325902/141454186-5b9b381e-fd38-4b03-adc8-3ea998fe088a.png)|![FIX-NoDelayedProblemNoti_when_lastRecoveryIsMissing2](https://user-images.githubusercontent.com/93325902/141454205-ba6547b4-2b35-4b26-a21e-56834dac9527.png)

**Comment by julianbrost** [comment]
So looks like this has sorted itself out, looks like a well-written bug report though :+1:
