### ISSUE TITLE
[dev.icinga.com #5043] Implement range support for warning/critical values in PerfdataValue

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#909]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/5043

**Created by gbeutner on 2013-11-09 09:05:30 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-08 00:51:15 +00:00 (in Redmine)_

---

### Problem

Performance data ranges are not properly parsed.

The following example from 'check\_procs':

    procs=1;1:;1:;0;

would mean

-   warn = "1:" (1 to infinity)
-   crit = "1:" (1 to infinity)
-   min = 0
-   max = null

#### Specification

Perfdata Value

    'label'=value[UOM];[warn];[crit];[min];[max]

Threshold Ranges

    A range is defined as a start and end point (inclusive) on a numeric scale (possibly negative or positive infinity).

    A threshold is a range with an alert level (either warning or critical). Use the set_thresholds(thresholds *, char *, char *) function to set the thresholds.

    The theory is that the plugin will do some sort of check which returns back a numerical value, or metric, which is then compared to the warning and critical thresholds. Use the get_status(double, thresholds *) function to compare the value against the thresholds.

    This is the generalised format for ranges:

    [@]start:end
    Notes:

    start ≤ end

    start and ":" is not required if start=0

    if range is of format "start:" and end is not specified, assume end is infinity

    to specify negative infinity, use "~"

    alert is raised if metric is outside start and end range (inclusive of endpoints)

    if range starts with "@", then alert if inside this range (inclusive of endpoints)

#### Additional Resources

https://www.monitoring-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
https://www.monitoring-plugins.org/doc/guidelines.html#AEN200

### Proposal

Find a way to store threshold ranges inside the PerfdataValue class.
Evaluate whether these attribute names make sense for inclusive and negative infinity.

-   warn\_upper
-   warn\_lower
-   crit\_upper
-   crit\_lower

### Additional thoughts

Graphios doesn't support threshold ranges. https://github.com/shawn-sterling/graphios/blob/master/graphios.py#L351

inGraph parses the ranges
https://github.com/NETWAYS/ingraph/blob/master/ingraph/parser.py#L58
and stores upper and lower and additional the type ("inside") - the latter would become cumbersome as time series field in graphite.
https://github.com/NETWAYS/ingraph/blob/master/ingraph/parser.py#L132
https://github.com/NETWAYS/ingraph/blob/master/ingraph/parser.py#L224
https://github.com/NETWAYS/ingraph/blob/master/ingraph/model.py#L855

    datapoint = Table('datapoint', metadata,
        Column('plot_id', Integer, ForeignKey('plot.id'), nullable=False, primary_key=True, autoincrement=False),
        Column('timeframe_id', Integer, ForeignKey('timeframe.id'), nullable=False, primary_key=True, autoincrement=False),
        Column('timestamp', Integer, nullable=False, primary_key=True, autoincrement=False),
        Column('min', Numeric(precision=20, scale=5, asdecimal=False), nullable=False),
        Column('max', Numeric(precision=20, scale=5, asdecimal=False), nullable=False),
        Column('avg', Numeric(precision=20, scale=5, asdecimal=False), nullable=False),
        Column('lower_limit', Numeric(precision=20, scale=5, asdecimal=False)),
        Column('upper_limit', Numeric(precision=20, scale=5, asdecimal=False)),
        Column('warn_lower', Numeric(precision=20, scale=5, asdecimal=False), nullable=True),
        Column('warn_upper', Numeric(precision=20, scale=5, asdecimal=False), nullable=True),
        Column('warn_type', Enum('inside', 'outside', name='warn_type_enum'), nullable=True),
        Column('crit_lower', Numeric(precision=20, scale=5, asdecimal=False), nullable=True),
        Column('crit_upper', Numeric(precision=20, scale=5, asdecimal=False), nullable=True),
        Column('crit_type', Enum('inside', 'outside', name='crit_type_enum'), nullable=True),
        Column('count', Integer, nullable=False),

This obviously fits into an RDBMS backend, but not Graphite or any other time series database.

**Changesets**

_2015-03-02 12:26:33 +00:00_ by _jyoung15_ af72a60c4b04fb480715c174bb2508b65c38af63

    Update PerfdataValue::Parse to ignore invalid warn, crit, min, and max values
    
    ... instead of generating exception so that metric values can
    still be passed to the graphing backend.
    Also update icinga-perfdata tests to reflect these changes.
    
    refs #5043
    
    Signed-off-by: Michael Friedrich <michael.friedrich@netways.de>

_2015-03-02 12:52:41 +00:00_ by _jyoung15_ faf6ce1a5f2eb5468e6ebb5db4f7fd08419d2c35

    Update PerfdataValue::Parse to ignore invalid warn, crit, min, and max values
    
    ... instead of generating exception so that metric values can
    still be passed to the graphing backend.
    Also update icinga-perfdata tests to reflect these changes.
    
    refs #5043
    
    Signed-off-by: Michael Friedrich <michael.friedrich@netways.de>

---

**Relations**:

* relates [#5043](https://dev.icinga.com/issues/5043)
* relates [#5043](https://dev.icinga.com/issues/5043)
* relates [#5043](https://dev.icinga.com/issues/5043)
* relates [#9461](https://dev.icinga.com/issues/9461)
* duplicates [#5043](https://dev.icinga.com/issues/5043)
* duplicates [#5043](https://dev.icinga.com/issues/5043)

**Comment by zstyblik** [comment]
> This proposed patch does not implement perfdata range support, however it modifies the PerfdataValue::Parse function to ignore "invalid" warn, crit, min, and max values in the legacy Icinga/Nagios perfdata format ('label'=value[UOM];[warn];[crit];[min];[max]).

Please, can you clarify on what do you mean by "legacy" and what's the current way of sending perf data then?

Thank you.

**Comment by dgoetz** [comment]
Calling it legacy is wrong as there were ideas about replacing/adjusting/adding but nothing was brought further than this initial step. So calling it the "old fashioned way" would be better.

Only other way I know is shipping the perfdata by the plugin instead of Icinga, one example would be check_interfacetable_v3t which can create perfdata files on its own, but I could also imagine plugins exist which can directly send to graphite/influxdb/opentsdb.

**Comment by zstyblik** [comment]
Hello @dgoetz,

thank you for your reply.

> Only other way I know is shipping the perfdata by the plugin instead of Icinga, one example would be check_interfacetable_v3t which can create perfdata files on its own

I'm sorry, but I don't follow. Please, could you point me to some documentation, even Nagios one. My problem is that icinga2 doesn't correctly interpret perf data from plugins. Therefore, I don't understand how shipping perf data "differently" would solve the issue at hand. But if it does, I'm happy to consider it as an option.

> I could also imagine plugins exist which can directly send to graphite/influxdb/opentsdb

So could I, but why? I want perf data and their interpretation in web UI. In icinga's web UI, to be specific. I'm quite happy with how things are interpreted now, more or less. Except for the fact that it's not 100% correctly supported and obviously there are some bugs.

**Comment by dnsmichi** [comment]
Can you please move the discussion away from this ticket? This is solely for parsing performance data ranges which is not yet implemented.

**Comment by zstyblik** [comment]
@dnsmichi, no problem. I'll create issues for other bugs I've encountered. I just wanted clarification whether perf data are or are not supported by icinga2 or what's the way forward.

**Comment by dnsmichi** [comment]
For the time being, there's no solution for this. Will be taken into account if we ever create our own plugin api specification.
