### ISSUE TITLE
Disallow empty objects names

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#9097]
At the moment, Icinga allows `""` or `null` as object names, i.e. the following config files validate:
```
object HostGroup "" {}
```
```
object HostGroup null {}
```

Both create an objects with the empty string as its name, leading to all kinds of weird situation, for example:
* it can't be queried as a single object using the API
* it can't be specified in the `groups` attribute of a host

So I think the correct behavior would be to simply reject this configuration.

**Comment by Al2Klimov** [comment]
## TODO

along with the PR:

Preserve the validity of `template T /* null */ default { }`

**Comment by Al2Klimov** [comment]
Admittedly it worked... somehow.

![Bildschirm­foto 2023-05-11 um 12 25 25](https://github.com/Icinga/icinga2/assets/6053266/c08e77b8-e298-416d-9a95-b78c9a7346c7)

**Comment by julianbrost** [comment]
> worked... somehow

Well, isn't that the whole point of the change here? It was allowed, but it resulted in broken behavior in so many places:

> * it can't be queried as a single object using the API
> * it can't be specified in the `groups` attribute of a host

And looks like you just found another one.
