### ISSUE TITLE
Retain Acknowledgements through Critical/Unknown/Critical state transitions

### ISSUE THREAD

**Issue by kenmarsh8** [Icinga/icinga2#9105]
I described the issue here: https://community.icinga.com/t/unknown-state-removes-acknowlegement-to-critical-service/3817

Simply put, an Service Ack "goes away" any time there is a network flap for the Host object. This does not work well for our use cases, we end up with duplicate issues on the same problem.

**Comment by Al2Klimov** [comment]
Sticky acknowledgments is what you want: https://icinga.com/docs/icinga-2/latest/doc/08-advanced-topics/
