### ISSUE TITLE
Config parser accepts strings for attributes of type "Number"

### ISSUE THREAD

**Issue by N-o-X** [Icinga/icinga2#9117]
Our config parser allows for strings to be used as values in our `Number` attributes. Example:

```
object CheckCommand "test_command" {
   arguments = {
      "-A" = {
         order = "1" // This should not be allowed
         value = "$a$"
         }
      "-B" = {
         order = "2" // This should not be allowed
         value = "$b$"
         }
      }
   command = ["test.sh"]
}
```

This isn't a problem for Icinga itself and works perfectly fine, but becomes a problem when you forward this string to Icinga DB which expects a number.

I'd suggest to not allow anything other than numbers in our `Number` attribute type.

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icinga2/blob/77eb7f4e1ecc9a330df78bc0aa487a0b8eac9e4a/tools/mkclass/classcompiler.cpp#L540-L542

https://github.com/Icinga/icinga2/blob/77eb7f4e1ecc9a330df78bc0aa487a0b8eac9e4a/tools/mkclass/classcompiler.cpp#L1175-L1177

![](https://img.welt.de/img/kmpkt/mobile193712903/9312509257-ci102l-w1024/Grumpy-Cat-Makes-Appearance-At-Kitson-Santa-Monica.jpg)

**Comment by Al2Klimov** [comment]
Maybe it’s a Director thing. Shall we cast the stuff (for Icinga DB) instead?

**Comment by Al2Klimov** [comment]
CC @Thomas-Gelf

**Comment by Al2Klimov** [comment]
Btw. a fix would affect **all** of our `Number`s.

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icinga2/blob/77eb7f4e1ecc9a330df78bc0aa487a0b8eac9e4a/lib/icinga/command.ti#L34-L43

**Comment by Al2Klimov** [comment]
@lippserd Please create a Director CheckCommand and share the config.

**Comment by Al2Klimov** [comment]
I'd not say our situation is **that** bad:

```
$ prefix/sbin/icinga2 daemon -C -c 9117.conf
[2022-01-03 13:09:13 +0100] information/cli: Icinga application loader (version: v2.13.0-122-gd6a1757cb; debug)
[2022-01-03 13:09:13 +0100] information/cli: Loading configuration file(s).
[2022-01-03 13:09:13 +0100] information/ConfigItem: Committing config item(s).
[2022-01-03 13:09:13 +0100] critical/config: Error: Validation failed for object '9117' of type 'CheckCommand'; Attribute 'arguments' -> 'lolcat' -> 'order': Invalid type.
Location: in 9117.conf: 3:2-5:2
9117.conf(1): object CheckCommand "9117" {
9117.conf(2):  command = [ "true" ]
9117.conf(3):  arguments = {
               ^^^^^^^^^^^^^
9117.conf(4):   "lolcat" = { order = "lolcat" }
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9117.conf(5):  }
              ^^
9117.conf(6): }
9117.conf(7):
[2022-01-03 13:09:13 +0100] critical/config: 1 error
[2022-01-03 13:09:13 +0100] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
$
```

**Comment by julianbrost** [comment]
> I'd not say our situation is **that** bad:

Well the code mentioned in https://github.com/Icinga/icinga2/issues/9117#issuecomment-985715161 already ensures that it is possible to convert the value to a double, but it keeps the existing value instead of storing it as a double.
