### ISSUE TITLE
Docs - Installation - Debian Bullseye - apt gpg key -> lack of docu

### ISSUE THREAD

**Issue by Darkentik** [Icinga/icinga2#9128]
Hey,
while doing manually the installation for checking all stuff as preparation for my saltstack automation, i just noticed that the docs for the installation on Debian has a lack for installing the repo key.
The docs here doesn't work for debian bullseye: https://icinga.com/docs/icinga-2/latest/doc/02-installation/#debianubunturaspbian-repositories

You have to save the GPG key in the new folder of apt:
`wget -O - https://packages.icinga.com/icinga.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/icinga-archive-keyring.gpg`

With help of the https://packages.icinga.com/debian/ i found the solution here:
`Archive Key

wget -O - https://packages.icinga.com/icinga.key | gpg --dearmor -o /usr/share/keyrings/icinga-archive-keyring.gpg
# or
curl https://packages.icinga.com/icinga.key | gpg --dearmor -o /usr/share/keyrings/icinga-archive-keyring.gpg
`

So can please someone update the docs with that very important commands for Debian Bullseye?!

Thanks!

**Comment by Darkentik** [comment]
Ok after a second try it works but no i'm confused.
Doesn't Bullseye forces the gpg keys must be in the directory /etc/apt/trusted.gpg.d/ ?
The command you said does not place the gpg key into this folder.

**Comment by julianbrost** [comment]
It adds the key to `/etc/apt/trusted.gpg` which is deprecated but still works. Anyways, the instructions given in the icinga2 docs and on https://packages.icinga.com/debian/ differ and should probably be unified towards how it's described on packages.icinga.com.

**Comment by jaapmarcus** [comment]
See linked PR as apt-key has been deprecated anyway on Ubuntu 22.04 and Debian will follow soon most likely

Also affects Ubuntu 

Extra reason to change it:
https://blog.cloudflare.com/dont-use-apt-key/
