### ISSUE TITLE
NRPE v4 command-plugins definitions (support for v3 packets)

### ISSUE THREAD

**Issue by 107142** [Icinga/icinga2#9129]
NRPE `command-plugins.conf` definitions are missing new switches for NRPEv4 executable. This most noticeable for the `-3` switch forcing the server to use only v3 packets.

While this does not necessarily break anything (older clients will still work with NRPEv4) it does produce quite a log spam on the client side since NRPE opens with v4 packets which client does not understand and logs the information, NRPE server then downgrades to v3 packets and all is fine.

Support for `-3` switch so v3 packets can be enabled would be very welcome.

**Comment by Al2Klimov** [comment]
Fixed in #9296.
