### ISSUE TITLE
Icinga DB notification history might use incorrect previous_hard_state

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#9132]
When sending notifications, a situation like the following may happen in a HA zone:
1. Node A processes a check result.
2. This results in a notification, Node A generates an `event::SendNotifications` cluster message.
3. Node B receives the message, sends out the notifications and generates an `event::NotificationSentToAllUsers` cluster message.
4. Node A receives the message and generates entries for the Icinga DB notification history stream.

If node a now processes a newer check result in between this interaction, this can result in an incorrect `previous_hard_state` value in the history stream.

Note that the involved notification-relates cluster events all include the check result that is acted upon:
https://icinga.com/docs/icinga-2/latest/doc/19-technical-concepts/#eventsendnotifications (both messages have a `cr` parameter).

This one is also passed to and used for generating the Icinga DB notification history entry:
https://github.com/Icinga/icinga2/blob/cbbaf4eac8479c2791914904567bc8a480a47cc5/lib/icingadb/icingadb-objects.cpp#L1701-L1704

However, for `previous_hard_state`, the checkable is accessed directly:
https://github.com/Icinga/icinga2/blob/cbbaf4eac8479c2791914904567bc8a480a47cc5/lib/icingadb/icingadb-objects.cpp#L1735

Therefore, the checkable may have received another check results changing its state to something newer than what the Icinga DB history code would need.

One possible less-invasive fix should be to add the last state information to the `vars_before`/`vars_after` attributes of a check result and use these.

**Comment by Al2Klimov** [comment]
Why incorrect? Imagine the notification is delayed (e.g. by a TP). Meanwhile the state transition is slightly different. I'd expect the state transition happened at the send time.

**Comment by julianbrost** [comment]
I've observed that both icinga2 instances write inconsistent values for the `previous_hard_state` attribute to the history streams for the very same notification. So one if them is incorrect for sure. I haven't looked into delayed notifications, so there might be other edge-cases as well.

**Comment by Al2Klimov** [comment]
The question is not the behavior, but the expected behavior.

**Comment by julianbrost** [comment]
The history generated by all nodes should reflect the view of the node sending the notification at the time of the notification.

What's the situation you're thinking about? Some checkable, two notifications on it: NotifyAlways without a time period and NotifySometimes with some time period restriction:
1. Starting situation: checkable is OK and we are within the time period of NotifySometimes
2. Time period of NotifySometimes ends
3. Checkable goes into HARD WARNING (NotifyAlways should notify here)
4. Checkable goes into HARD CRITICAL (NotifyAlways should notify here)
5. Time period of NotifySometimes starts (NotifySomestime should notify here about the HARD CRITICAL)

And the question now is if the `previous_hard_state` of the history entry should be OK (reasoning: the notification did not observe the WARNING state so to say) or WARNING (reasoning: that's the state transition of the checkable).

So you can reason for both, I don't know which would make more sense or be more consistent with the overall notification logic.

**Comment by Al2Klimov** [comment]
I'd reason for the one of them with 0 effort. :)

**Comment by julianbrost** [comment]
Result of our internal discussion: we want to go with the previous hard state of the checkable at the time the notification is generated, regardless of suppression state, i.e. in the the example in my previous comment, it should be WARNING.
