### ISSUE TITLE
Holidays in Timeperiods

### ISSUE THREAD

**Issue by LasBushus** [Icinga/icinga2#9135]
I am looking for a way to set Holidays in the timeperiods.
Christmas is easy, it's a set date. But what about Easter?
There is a Perl-Library e.g. for [german holidays](https://metacpan.org/pod/Date::Holidays::DE) that is able to calculate the local holidays.
Is there a possibility to create a "holiday-timeperiod" with the specific country (and state) settings, to generate the specific holidays, so that this timeperiod, could then be included or excluded in other timeperiods?

**Comment by julianbrost** [comment]
Things like first/second/last Wednesday are also supported by time periods, but I think this still isn't enough to catch all public holidays.

So I suggest to use that Perl library (or something comparable) to just generate config for a time period that you then include in your config.

Theoretically, there is some undocumented functionality that would allow you to dynamically generate this within the config, but then you'd have to reimplement all that logic in the Icinga config language. But the other option is probably the easier way.
