### ISSUE TITLE
Icinga's initial threads are linked to core count in host with no way to adjust or limit

### ISSUE THREAD

**Issue by froooooooo** [Icinga/icinga2#9147]
Currently the number of threads spawned is tied to the number of cores/cpu-threads the host running icinga has. Ideally, we would like to reduce the number of threads icinga needs to just run off of 1 
 initial thread if possible.
 
 It seems this used to be possible with the init.conf but this was removed a while ago. For example, the value I'm referring  to when doing checks is this. The below command shows the threads per icinga. 
 
 18-core-host # icinga2 console -e Concurrency
18

4-core-host # icinga2 console -e Concurrency
4

128-core-host-with-2-threads-per-core # icinga2 console -e Concurrency
256

## To Reproduce

1. Start icinga and check via `icinga2 console -e Concurrency`
2. This number correlates  directly to the number of cpu-threads which also is 1 icinga process per core/cpu-thread on startup

As shown above, this will change depending on the number of cores the host's cpu has.

## Expected behavior

I would prefer a way to minimize this. We are pinning icinga to one core on our hosts, so in theory we should only require 1 thread (based on this logic), however it is still spawning a bunch of threads.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): **2.13.1-1**
* Operating System and version: **Rhel6/Centos 7** 
* Enabled features (`icinga2 feature list`): **Enabled features: api checker mainlog**

## Additional context

I can get any more info if needed. But this is a huge concern for our environment. Thank you!

**Comment by leeclemens** [comment]
For the sake of cross-referencing: https://community.icinga.com/t/any-way-to-reduce-the-number-of-threads-in-icinga/8840

**Comment by Al2Klimov** [comment]
Have you tried `const Concurrency = 1`?

**Comment by froooooooo** [comment]
> Have you tried `const Concurrency = 1`?

Where should I set this?

**Comment by Al2Klimov** [comment]
E.g. in the constants.conf.

**Comment by froooooooo** [comment]
So it looks like this doesn't help. I tried with both `const Concurrency = 1` and `const concurrency = 1`, but both had the same results ie. 1 thread per core.

**Comment by Al2Klimov** [comment]
Hmm... and -DConcurrency=1 in the systemd file just after _icinga2 daemon_?

**Comment by froooooooo** [comment]
No changes as well with this added to systemd.

**Comment by Al2Klimov** [comment]
Have you done `systemctl daemon-reload` before re**start**ing Icinga 2?

**Comment by julianbrost** [comment]
IIRC one of the insights when looking at #9099 was (of course not written down) that there are some places where the number of thread can't be easily controlled by the user at the moment:
https://github.com/Icinga/icinga2/blob/f2563cc8904e73dada16d390f5a93c3b89a56f5b/lib/base/io-engine.cpp#L87
https://github.com/Icinga/icinga2/blob/f2563cc8904e73dada16d390f5a93c3b89a56f5b/lib/base/threadpool.hpp#L39

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icinga2/pull/7845/commits/6414ce3742eaf412664eda255e24ba4dcd2375ce

**Comment by froooooooo** [comment]
> Have you done `systemctl daemon-reload` before re**start**ing Icinga 2?

yes I did and still no luck.

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icinga2/commit/6414ce3742eaf412664eda255e24ba4dcd2375ce from #7845 may help.
