### ISSUE TITLE
Support ipv6 for icinga2 pki save-cert

### ISSUE THREAD

**Issue by paladox** [Icinga/icinga2#9149]
## Is your feature request related to a problem? Please describe.

We have setup ipv6 only hosts and we cannot connect to port 5665 because it's only available over ipv4. Could support for ipv6 be added please?

## Describe the solution you'd like

Support for it to listen to port 5665 on ipv6.

## Additional context

Example root@mon111:~# /usr/sbin/icinga2 pki save-cert --host mon111.miraheze.org --port 5665 --key /var/lib/icinga2/certs/mon111.miraheze.org.key --cert /var/lib/icinga2/certs/mon111.miraheze.org.crt --trustedcert /var/lib/icinga2/certs/trusted-cert.crt

**Comment by julianbrost** [comment]
Which version of icinga2 are you using?

And is this report about `icinga2 pki save-cert` not being able to connect to an IPv6 server or the `icinga2 daemon` process not listening on IPv6 by default? If it's the latter, the default was changed in version 2.13, so if you're using something older, please upgrade or manually set `bind_host` in your `ApiListener` configuration to `"::"` ([docs](https://icinga.com/docs/icinga-2/latest/doc/09-object-types/#apilistener)).

**Comment by paladox** [comment]
Oh I forgot to close this as resolved. I managed to fix this by setting bind_host to :: for the api. Though that makes it ipv6 only.

**Comment by julianbrost** [comment]
> Though that makes it ipv6 only.

It shouldn't. IPv6 sockets bound to :: can also be accessed via IPv4 (Icinga explicitly sets the `IPV6_V6ONLY` socket option to 0)
