### ISSUE TITLE
Icinga2 out of FreeBSD's ports tree (net-mgmt/icinga2) does not build with LibreSSL

### ISSUE THREAD

**Issue by davehayes** [Icinga/icinga2#9174]
## Describe the bug

For the past two quarterly ports releases, icinga2 does not build with LibreSSL. This is concerning. 

Please reference [this link](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260143) for details. The [port skeleton](https://github.com/freebsd/freebsd-ports/tree/main/net-mgmt/icinga2) can also be viewed if necessary.

## Your Environment

* Icinga 2.13.2
* Operating System and version: FreeBSD 12.2

**Comment by botovq** [comment]
Update your boost port or backport this fix
https://github.com/boostorg/asio/commit/2f207559f0e3882e09b8cb2d610f85855f019eaa

**Comment by julianbrost** [comment]
If the incompatibility is within boost, there isn't much we can do here. Icinga 2 builds fine with Boost 1.78, so likely that's the way to go as that seems to be fixed there.

**Comment by davehayes** [comment]
Just a note, the fix has been backported:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260143
