### ISSUE TITLE
Satellite HA Setup not work as HA Setup

### ISSUE THREAD

**Issue by tuxracer1337** [Icinga/icinga2#9192]
Hello

I reported to Eric that we have a problem in the setup of 2 satellites.
He asked me to open this ticket here.

## Example setup

```
                                 master server (eth0 192.168.0.10)
				  /                             \
                                 /                               \
		  (eth0 192.168.0.11)                       (eth0 192.168.0.12)
      Satellite1  (eth1 192.168.20.11)----------------------(eth1 192.168.20.12) Satellite2
                  (eth2 192.168.30.11)                      (eth2 192.168.30.12)
                                \                                /
				 \                              /
                           System with Icinga Agent (eth0 192.168.30.13)
```
						
Both satellites are connected to the master via network interface eth0. 
The two satellites are connected to each other via network interface eth1
The two satellites are connected to the agent via network interface eth2

## Example Check Configuration
The following checks are configured for the system agent

check_agent_health > checksource Satellite1
check_memory > checksource agent - check via internal agent check command
check_mssql_health > checksource agent - check via external check command

All checks work and are "OK

NOTE: This is a simplified representation, because Icinga negotiates internally which check is executed via which satellite.
So it could be that check_memory is executed via Satellite1 and check_mssql_health via Satellite2.
But this plays only a minor role for the description of the error pattern and the associated error behavior.

## Simulate error case
In the hypervisor of Satellite1 the network card eth2 breaks (or a switch in the network segment fails).
Once this was simulated via IPTABLES, where every connection on Satellite 1 to and from agent was DROP'ED.
Once this was simulated by removing the virtual network cable in the hypervisor for eth2.

## Assuming what should happen in the above error case

Check_agent_health becomes "WARNING" as Satellite1 can no longer communicate with Agent, but Satellite2 can still talk to Satellite1 and take over the checks from Satellite1
Check_memory will be checked more, because Satellite2 can still communicate with Agent and can take over the checks from Satellite1
Check_mssql_health will be checked more, because Satellite2 can still communicate with Agent and can take over the checks from Satellite1

## What really happens in the above error case
Check_agent_health becomes "CRITICAL", because Satellite1 can no longer communicate with Agent
Check_memory is no longer checked because Satellite1 can no longer communicate with agent and check_agent_health is CRITICAL
Check_mssql_health is no longer checked because Satellite1 can no longer communicate with Agent and check_agent_health is CRITICAL

## Notes
- It would be desirable to have a Satellite HA setup that behaves like a HA setup.
- Currently the HA does not act like a HA but like a load balancer without error protection, because checks are not taken over by the still working satellite.

Eric explained to me that currently it works as designed, but it could probably be rebuilt with manageable effort to work better in that the satellites can take over the work of the other in the above error case.
It would be great if you could take care of this and rebuild it, as this is an essential part of a HA setup.

If you have any questions or need more information, please let me know.

Best regards
Andreas

**Comment by julianbrost** [comment]
> Eric explained to me that currently it works as designed

Let's call it known limitation of the current design.

I already created #8635 for this a while ago, so closing this one as a duplicate.
