### ISSUE TITLE
Perfdata: Unknown UOMs are not shown as-is

### ISSUE THREAD

**Issue by kbnba** [Icinga/icinga2#9206]
It seems that Icinga does not grok kWh in perfdata, but if I change to Wh the data are accepted.

Here are the plugin output with kWh:

$ ./check_snmp_apc_pdp -H s3-pdp-a.sbti -C public -m 3
All lines OK | 'A 2.1 R4-Total'=3602.9kWh; 'A 2.1 R4-Power'=1.6kW; 'A 2.2 R5-Total'=1861.8kWh; 'A 2.2 R5-Power'=1.2kW; 'A 2.3 R6-Total'=2548.5kWh; 'A 2.3 R6-Power'=.9kW;

Then Icinga shows this for perf:

![billede](https://user-images.githubusercontent.com/81555951/152484497-7a785a57-ef7b-417d-8eb0-de1e290b2e45.png)

But if I change to Wh in data:

$ ./check_snmp_apc_pdp -H s3-pdp-a.sbti -C public -m 3
All lines OK | 'A 2.1 R4-Total'=3603000Wh; 'A 2.1 R4-Power'=1.5kW; 'A 2.2 R5-Total'=1861900Wh; 'A 2.2 R5-Power'=1.2kW; 'A 2.3 R6-Total'=2548500Wh; 'A 2.3 R6-Power'=.9kW;

![billede](https://user-images.githubusercontent.com/81555951/152484735-43c2c67c-e80f-42a9-ab7b-7636afc45f45.png)

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: 2.13.2-1)

* Operating System and version:
RHEL 8

* Enabled features (`icinga2 feature list`):
Disabled features: command compatlog debuglog elasticsearch gelf icingadb influxdb influxdb2 livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker graphite ido-pgsql mainlog notification

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version    2.9.5
Git commit    053971c99dc1a4510beb64a888ea695cc14032dc
PHP Version    7.4.19
Git commit date    2021-11-18

**Comment by yhabteab** [comment]
Actually it's not a problem with Icinga2, It' s rather a problem with the monitoring module. If I'm not mistaken, the monitoring module doesn't/won’t support the [UoMs](https://github.com/Icinga/icinga2/issues/7225) which have been added recently at all, only the icingadb-web module. So I just tested it and everything works fine except in monitoring.

Maybe @nilmerg  can enlighten us!

**Comment by nilmerg** [comment]
Yeah, that's it. Though monitoring should at least show them as-is.
