### ISSUE TITLE
Icinga2 - Variable references are not resolved

### ISSUE THREAD

**Issue by fl0wx** [Icinga/icinga2#9211]
## Describe the bug
Variable references are not resolved like you can see here:
https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/281

Details:
```
icinga2 object list --type service --name generic_k8s_heapused | grep "query =" |head -n 1
    * query = "(base_memory_usedHeap_bytes{app="$host.vars.kubernetes_appname$", kubernetes_namespace="$host.vars.kubernetes_namespace$", prometheus_cluster=''} / base_memory_maxHeap_bytes{app="$host.vars.kubernetes_appname$", kubernetes_namespace="$host.vars.kubernetes_namespace$", prometheus_cluster=''}) * 100"
```

## Expected behavior

the given "host.vars.xxx" or any other reference inside of a var should be resolved to use it propery

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.9.5
* Version used (`icinga2 --version`): 2.11.3
* Operating System and version: Debian GNU/Linux 10 (buster)
* Enabled features (`icinga2 feature list`): api checker command ido-pgsql influxdb mainlog notification
* Config validation (`icinga2 daemon -C`): (/)

**Comment by fl0wx** [comment]
@julianbrost context: https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/281
its not clear to me who is responsible to resovle the variable. Icingaweb2 Team says it has to be done by module owner, module owner say hes using methods from icingaweb2 and that methods are calling icinga2 api and it hast to be done in icinga2. 

Can you help out here?

**Comment by julianbrost** [comment]
I have looked at that issue and it misses information that I need for understanding what the actual issue is. What's the purpose of that `query` variable and which component (probably Mikesch-mp/icingaweb2-module-grafana) is reading it from where and expects that some macro resolution should have happened?

**Comment by fl0wx** [comment]
It serves two purposes:
1. it is used and passed to the assoziated check command to run that query against prometheus and calculate a return code (works fine)
2. to be passed as custom var via grafana module plugin to grafana and generate the graph dynamically (which doenst work, because the variable isnt resolved)

Refer to (1. works without any issues, 2. was not resolved): 
![image](https://user-images.githubusercontent.com/2448081/154961229-0c68ffc1-0c2d-44b3-a7de-058c9b8696ff.png)

Additional Grafana Graphs Debug Output:
![image](https://user-images.githubusercontent.com/2448081/154961857-291dc075-4521-4dbe-97e1-457d0967cb1a.png)

**Comment by julianbrost** [comment]
Probably the Grafana plugin takes the value from the IDO custom var table (or maybe also from the Icinga 2 API). The thing is, both show the configuration, macro resolution only happens when Icinga 2 actually uses the value, for example when executing a command. The issue here is that `$host.name$` is somewhat special as it's a fixed value, but there are [many more macro variables](https://icinga.com/docs/icinga-2/latest/doc/03-monitoring-basics/#host-runtime-macros) that are dynamic and may change with every evaluation, so they can't be put into a config snapshot.

So you'd have to ensure that the value is already evaluated in the configuration, so something like this could do the trick:
```
vars.foo = "example"
vars.query = "..." + vars.foo + "..."
```

**Comment by fl0wx** [comment]
okay that sounds good but is there any way to do that with icinga director?

**Comment by Al2Klimov** [comment]
OK, normally I first ask for workaround reasonability, but for me https://github.com/Icinga/icinga2/issues/9211#issuecomment-1046903724 is absolutely reasonable.

Unfortunately you can't wrap Julian's solution into a default template as they're going to be imported first, not last #7929. So you'll have to do DSL in this case as Julian showed https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/281#issuecomment-1041147687. Or you import vars.query also via Director.

**Comment by fl0wx** [comment]
Thanks for the feedback. I cannot drop director entirely here, so that is not a a solution for me (as proposed in https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/281#issuecomment-1041147687). So i need a solution which works in director. How can i achieve that? I dont understand what you mean with "Or you import vars.query also via Director." ?

**Comment by fl0wx** [comment]
@Al2Klimov hey ho, sorry i havent had time to work / debug on this issue. But the issue still isnt solved on my site and i still cant follow you comment. I do have "both" variables provided via director, or what i am missing? 
![image](https://user-images.githubusercontent.com/2448081/219307623-c679011c-ff63-4254-8470-bd681fa8d759.png)
none of the 2 variables work as expected if i try to use them in the grafana query. neither the first nor the second gets resolved.

**Comment by Al2Klimov** [comment]
## Status quo

```
vars.query = "whatever"
vars.resolved_query = "$query$"
```

## My suggestion

```
vars.query = "whatever"
vars.resolved_query = "whatever"
```

**Comment by fl0wx** [comment]
Ah now i understand your suggestion. That will not really help me since the first query "vars.query" contains variables itself (for example: "$host.vars.kubernetes_appname$"). There could be a solution in icingadb like advised here: https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/281#issuecomment-1432874352 so if they integrate this macro feature in the grafana module v2, i think it should work as expected

**Comment by Al2Klimov** [comment]
The Director already renders vars.kubernetes_appname=whatever for every host, right? Could it also render my suggestion, on every host?
