### ISSUE TITLE
Changing system time backwards causes CheckerComponent to no longer execute active checks

### ISSUE THREAD

**Issue by haxtibal** [Icinga/icinga2#9278]
To reproduce, simple call `date $(date +%m%d%H%M%Y.%S -d '-2 hour')` while icinga2 is running. All checks will then be delayed by two hours, regardless of their `check_interval`.

In practice we stumbled upon this because a hardware clock was 2 hours in front of NTP time, and chrony changed time while icinga2 was already running.

What happens (considering a 2h change back in time) is:
- If time is changed while checker thread is blocking on [m_CV.wait_for](https://github.com/Icinga/icinga2/blob/v2.13.2/lib/checker/checkercomponent.cpp#L126) (likely), it blocks for full 2h, instead of the few wait seconds it usually would. See this [so question](https://stackoverflow.com/questions/51005267/how-do-i-deal-with-the-system-clock-changing-while-waiting-on-a-stdcondition-v) for why this happens with [std::condition_variable](https://en.cppreference.com/w/cpp/thread/condition_variable)s.
- If we're lucky, [m_CV.notify_all](https://github.com/Icinga/icinga2/blob/v2.13.2/lib/checker/checkercomponent.cpp#L333) is called due to external check events, and we get out of the `wait_for`. But again no checks are executed, because `NextCheck` timestamps in [CheckerComponent::m_IdleCheckables](https://github.com/Icinga/icinga2/blob/v2.13.2/lib/checker/checkercomponent.hpp#L77) all have an old timestamp from before the change, which is now effectively 2h in the future, and the next `wait_for` will block again for 2h.

Would you consider this as bug or "works as designed"?

If bug, I could try to provide a PR. Solution could be to extend the existing [time jump detection](https://github.com/Icinga/icinga2/blob/v2.13.2/lib/base/application.cpp#L340) to update not only periodic timers, but also checkable timestamps, and then notify the `CheckerComponent`s condition variable.

## Expected behavior

Checks are executed within their `check_interval`, even if there was a change in system time.

## Your Environment

Icinga 2.13.2 on CentOS 7, but should be reproducible on any POSIX system.

**Comment by julianbrost** [comment]
Icinga works with absolute timestamps just about everywhere, so if your time jumps backwards, this will probably be problematic in so many more places. For example, if you'd implement what you've suggested, you'll end up with totally erratic history in your database as those two hours passed twice and you end up having interleaved entries from both timelines. So I doubt that there's an easy and safe fix for this unfortunately.

The claim about `std::condition_variable::wait_for` sound interesting though, You have to love C++ I guess.

> The standard recommends that a steady clock be used to measure the duration.

-- https://en.cppreference.com/w/cpp/thread/condition_variable/wait_for:

Recommends, sounds great! So if that's indeed not the case, that might be technically correct but is totally useless :(

But yeah, in general, I'd say works as expected and avoiding time travel is probably a good idea. Especially in a distributed Icinga setup, it's crucial to have properly synchronized time anyways.
