### ISSUE TITLE
Changing system time may cause "short read" error when reading JSON RPC message

### ISSUE THREAD

**Issue by haxtibal** [Icinga/icinga2#9279]
While debugging #9278, I noted this error:

```
Feb 22 09:58:25 myhost icinga2[1390]: We jumped backward in time: 7135.15 seconds
Feb 22 09:58:28 myhost icinga2[1390]: Error while reading JSON-RPC message for identity 'myotherhost': Error: short read
                                      Stacktrace:
                                       0# __cxa_throw in /usr/lib64/icinga2/sbin/icinga2
                                       1# icinga::NetString::ReadStringFromStream(boost::intrusive_ptr<icinga::Shared<icinga::AsioTlsStream> > const&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, long) in /usr/lib64/icinga2/sbin/icinga2
                                       2# icinga::JsonRpc::ReadMessage(boost::intrusive_ptr<icinga::Shared<icinga::AsioTlsStream> > const&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, long) in /usr/lib64/icinga2/sbin/icinga2
                                       3# icinga::JsonRpcConnection::HandleIncomingMessages(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >) in /usr/lib64/icinga2/sbin/icinga2
                                       4# 0x0000000000AFA8B7 in /usr/lib64/icinga2/sbin/icinga2
                                       5# 0x0000000000B06A89 in /usr/lib64/icinga2/sbin/icinga2
                                       6# make_fcontext in /lib64/libboost_context.so.1.69.0
```

Time change was caused by chrony and correctly detected by icinga2. The "short read" error from next log line seems to happen in consequence, but I have no proof.

## To Reproduce

I'd say change system time while agents connect to your master, and repeat that a few times. But not sure yet, sorry.
Will update here if there's more evidence.

## Your Environment

Icinga 2.13.2 on CentOS 7.

**Comment by julianbrost** [comment]
I'm not sure if that's related to system time. I'd rather expect this to be the remote shutting down in the middle of sending a JSON-RPC message. I wouldn't rule out that this might be some secondary effect of something strange happening due to the time jumping backwards.

**Comment by Al2Klimov** [comment]
Hello @haxtibal!

How far do you have to jump in time to get this at all?

Best,
A/K

**Comment by haxtibal** [comment]
Hi @Al2Klimov,

> How far do you have to jump in time to get this at all?

Sorry, I don't know, I have no reproducer so far besides the log above where it was a jump of 2h backwards right while config and replay log sync were in progress. There's no hard evidence of error and time jump being really correlated. It just seemed obvious because log messages were close to each other.

**Comment by Al2Klimov** [comment]
@haxtibal Is there an actual problem? IMAO re-connects are a common thing in Icinga 2.

**Comment by haxtibal** [comment]
@Al2Klimov

> Is there an actual problem?

No, at least not from a functional point of view. In the observed case the client was disconnected after the read error, and it reconnected immediately.

When writing this issue I guessed it could be possible that realtime clock leaps badly affect `Boost::asio`, just as they [disturb an in-progress std::condition_variable::wait_for](https://stackoverflow.com/questions/51005267/how-do-i-deal-with-the-system-clock-changing-while-waiting-on-a-stdcondition-v), which would then be source for bugs in general. But as said, I have no evidence and no reproducer. This would need further investigation. Feel free to close this bug.
