### ISSUE TITLE
Future next_check timestamps from icinga2.state are not corrected and therefore prevent check execution

### ISSUE THREAD

**Issue by haxtibal** [Icinga/icinga2#9280]
Icinga [already sanitizes](https://github.com/Icinga/icinga2/blob/v2.13.2/lib/icinga/checkable.cpp#L93) `next_check` timestamps when loading them from `icinga2.state` on startup. Too old `next_check`s (likely) are discarded, and replaced with ones distributed evenly within one minute from now.

However, there's no handling for timestamps that are too new. If system time was changed backwards between two icinga2 runs (manually or by ntp), checks are not executed after startup because their `next_check` is now effectively in the future.

## To Reproduce

1. Say it's 13 pm. Run icinga2, let active checks execute with `check_interval` of 1 min, then stop the daemon.
1. Change system time 1h backwards: `date $(date +%m%d%H%M%Y.%S -d '-1 hour')`
1. Start icinga2 again. `next_check`s are restored to 13:01 pm, but now it's only 12 pm. I.e. they will be executed 1 hour too late.

## Expected behavior

Active checks are always executed within their configured `check_interval` no matter how much system time jumps around.

## Your Environment

Icinga 2.13.2 on CentOS 7.

**Comment by haxtibal** [comment]
> Have you tried _check now_ in web?

Yes, check now in web and also [reschedule-check](https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#reschedule-check) via API would lead to immediate execution and correct check period.

**Comment by Al2Klimov** [comment]
Do you consider that a reasonable workaround?

**Comment by haxtibal** [comment]
> Do you consider that a reasonable workaround?

For us [reschedule-check](https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#reschedule-check) can serve as a workaround, as we have own software around icinga that can detect such time issues and force a reschedule.

In general it's more problematic, because a user won't even notice there's anything wrong. It's the same as with #9278. Checks just stay green-OK (the restored state from the previous session) and you feel safe, but actually no checks happen. Your system can break unnoticed despite active health monitoring. In some scenarios the "check late" clock icon would appear in web, but that will probably also go unnoticed.

**Comment by julianbrost** [comment]
> If you have a minute left, could you explain what [freshness checks](https://icinga.com/docs/icinga-2/latest/doc/08-advanced-topics/#check-result-freshness) are? By reading the documentation they sound useful to detect late checks, but when searching in icinga2 source code there seems to be no special handling related to freshness at all. So what is a freshness check, and under what condition would it bite?

That's just some naming for active checks when a service usually receives passive check results. If these are missing for the check interval, the active check is executed, allowing to detect that the usual source of the check results broke.

**Comment by haxtibal** [comment]
Just noticed that `actions/reschedule-check` REST API requests with a filter that's valid but won't give a match will result in HTTP status code 500, "Internal server error". I don't think that's a semantically correct response, is it? Should I open a dedicated issue?

Imo it should either give 404 "No objects found.", or even 200, because the request was processed and did exactly what the user requested (I mean, if one requests "please reschedule no host", then rescheduling no host is success).

Noticed it while trying a workaround like
```sh
now=$(date +%s)
curl -k -s -S -i -u 'root:root' -H 'Accept: application/json' -X POST \
 'https://localhost:5665/v1/actions/reschedule-check' \
 -d "{ \"filter\": \"host.next_check>$now+host.check_interval || host.next_check<$now\", \"type\": \"Host\", \"force\": true }"

HTTP/1.1 500 Internal Server Error
Server: Icinga/2.13.2-1
Content-Type: application/json
Content-Length: 14

{"results":[]}
```
but you can reproduce it simpler, just give any filter where no object will match.

**Comment by Al2Klimov** [comment]
Sounds like #8532.

**Comment by Al2Klimov** [comment]
Go for it.

**Comment by Al2Klimov** [comment]
Not sure if all this is an actual bug...

**Comment by haxtibal** [comment]
> Not sure if all this is an actual bug...

I don't know either :-) I'd expect a monitoring system to reliably warn about errors within the configured `check_interval` (+ some margin) - really no matter of what weird things happen on your system. This issue shows an example how that expectation can be missed, and it's one of the reasons why we implemented the [mentioned watchdog](https://github.com/Icinga/icinga2/pull/9295#discussion_r836418649). But don't won't to push on this, feel free to close the issue.

**Comment by Al2Klimov** [comment]
> the configured `check_interval` (+ some margin

Well, that's how web's _schedule check_ works.

**Comment by haxtibal** [comment]
> Well, that's how web's _schedule check_ works.

Yes, but that's implemented in web. That late check won't actually change the status. So it can't trigger event handlers, and we couldn't forward the failure-event to superordinate alarming systems by means of remote APIs. Our systems run mostly unattended, the clock symbol in web is likely to go unnoticed.
