### ISSUE TITLE
--sni option missing in check_tcp ITL

### ISSUE THREAD

**Issue by geotekberlin** [Icinga/icinga2#9307]
## Describe the bug
The --sni switch available in the check_tcp command of monitoring plugins 2.3.x is missing in ITL

## To Reproduce
Install Icinga 2.13.2 and try to use the --sni parameter in check_tcp command.

## Expected behavior
ITL should allow to use all command parameters offered in current monitoring plugins

## Your Environment
Icinga  r2.13.2-1 on Debian 11 with Icinga Web 2.10.0 and Director 1.9.0

**Comment by Al2Klimov** [comment]
Hello @geotekberlin,

the `ssl` check command is your friend. #7741

Best,
A/K
