### ISSUE TITLE
Ignoring invalid perfdata 

### ISSUE THREAD

**Issue by FI5CHER** [Icinga/icinga2#9330]
Since update to icinga2 2.13.2 (Redhat 7)  my messages are filled by millions of this messages:
 
Apr  8 09:51:23 icingaserver1 icinga2: Ignoring invalid perfdata for checkable 'somehost.intern!cpu' and command 'check_cpu_local' with value: CpuIdle=99.75%;0,0;0;#012Context:#012#011(0) Processing check result for 'somehost.intern!cpu'

... and yes ... the CpuIdle is gone vom the graphs since that ;-(

I'm running an 110% boring standard cpu check since ages ...

/usr/lib64/nagios/plugins/check_cpu -w 90,90,90 -c 95,95,95

CPU STATISTICS OK : user=30.92% system=9.73%, iowait=0.75%, idle=12.47%, nice=46.13%, steal=0.00% | CpuUser=30.92%;90;95;0; CpuSystem=9.73%;90;95;0; CpuIowait=0.75%;90;95;0; CpuIdle=12.47%;0,0;0; CpuNice=46.13%;0;0;0; CpuSteal=0.00%;0;0;0;

/usr/lib64/nagios/plugins/check_cpu -v
Revision 2.3.3 (c) 2008 Steve Bosek (steve.bosek@gmail.com)

... config of the cpu check
###################################################

object CheckCommand "check_cpu_local" {
  /*  /usr/lib64/nagios/plugins/check_cpu -n 5 -w 101,101,101 -c 102,102,102
  */
  import "plugin-check-command"
  command = [ PluginDir + "/check_cpu" ]
  arguments = {
  "-w" = "$check_cpu_warn$"
  "-c" = "$check_cpu_crit$"
  #"-n" = "10"
  }
}

apply Service "cpu" {
  import "generic-sap-service"
  display_name = "cpu"
  check_command = "check_cpu_local"
  command_endpoint = host.name
  icon_image = "img/GD/cpu.png"
  vars.notification.mail.begin=30m
  vars.servicemail = "false"
  vars.servicesms = "false"

  if (host.vars.glpi_sap_cpu=="90_95") {
  vars.check_cpu_warn = "90,90,90"
  vars.check_cpu_crit = "95,95,95"
  } else if (host.vars.glpi_sap_cpu=="95_99") {
  vars.check_cpu_warn = "95,95,95"
  vars.check_cpu_crit = "99,99,99"
  } else if (host.vars.glpi_sap_cpu=="99_101") {
  vars.check_cpu_warn = "99,99,99"
  vars.check_cpu_crit = "101,101,101"
  } else if (host.vars.glpi_sap_cpu=="101_102") {
  vars.check_cpu_warn = "101,101,101"
  vars.check_cpu_crit = "102,102,102"
  } else {
  vars.check_cpu_warn = "105,105,105"
  vars.check_cpu_crit = "110,110,110"
  }

  assign where host.vars.glpi_sap_cpu && host.vars.os == "Linux" && host.vars.monitoringtype == "icinga" && host.vars.zone == "DE-MUC1-SAP"
}

#####################################

icinga2 -V
#####################################
icinga2 - The Icinga 2 network monitoring daemon (version: 2.13.2-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1160.53.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

**Comment by julianbrost** [comment]
> Since update to icinga2 2.13.2

Which version did you upgrade from?

> CpuIdle=12.47%;0,0;0;

That one is invalid indeed. There should be no `,` in there.

According to https://exchange.nagios.org/directory/Plugins/System-Metrics/CPU-Usage-and-Load/check_cpu_stats-2Esh/details, there also seems to be a fixed version:

>  2.3.6 | 05.08.11 | Steve Bosek | Bug fix in NAGIOS_DATA : replace comma with semicolon in perfdata - compatibility with pnp

> filled by millions of this messages

In which time? But sounds like too much in any way.

**Comment by julianbrost** [comment]
Also, which of the different writers are you using? Looks like the log output is from syslog and that seems to miss that information unfortunately and all of the ElasticSearch/Gelf/Graphite/Influxdb(2)/OpenTsdbWriters may log that kind of message.

**Comment by FI5CHER** [comment]
Hi Julian.

>> CPUIdle=12.47%;0.0;0;

The problem was really that an old version of check_cpu that was accidentally distributed to all systems during the icinga2 client & server update ( via ansible ) 

THX !!!! 👍
