### ISSUE TITLE
Icingadb notifications have wrong icingaweb2 url

### ISSUE THREAD

**Issue by rafi0101** [Icinga/icinga2#9350]
## Describe the bug

As already described in the [community forum](https://community.icinga.com/t/icingadb-notifications-with-correct-icingaweb2-link/9674): When using icingadb instead of ido-mysql backend (and icingadb-web) the icingaweb2 url is wrong in email notifications.

Maybe you can change the mail notification script to influence the correct url path by configuration. (If using ido-mysql or icingadb)

## To Reproduce

Set up Icinga2 with icingadb backend and icingadb-web as icingaweb2 module, send a notification and click on the url

## Expected behavior

@nilmerg has described it as it should be: [see community](https://community.icinga.com/t/icingadb-notifications-with-correct-icingaweb2-link/9674/2)

## Your Environment

- Icinga DB Web version (`1.0.0-rc2`):
- Icinga Web 2 version (`2.9.6`):
- Web browser: `Chrome`
- Icinga 2 version (`r2.13.3-1`):
- Icinga DB version (`v1.0.0-rc2-dev`):
- PHP version used (`7.4.28`):
- Server operating system and version: `Debian 11` (Icingaweb2 is running in docker)

**Comment by Al2Klimov** [comment]
Colleagues, shall we just change the URLs to Icinga DB ones as Johannes described in the forum?

**Comment by julianbrost** [comment]
Doesn't really make sense to have links to the old stuff there. This in files in `/etc`, so they are supposed to be changed by the user, so the file may or may not be updated by the package manager. So probably only in 2.14. If it bothers you, you can edit the script, it's supposed to be an example after all.

@nilmerg IIRC, Web already has the feature to show some "view this in the icingadb module" link on pages in the monitoring module. Would it be an option to use the same mapping for automatic redirects if the monitoring module is disabled? Might allow for a more graceful migration and would also keep other old links intact.

**Comment by nilmerg** [comment]
Yeah.. maybe.

**Comment by Al2Klimov** [comment]
Once you s/maybe/definitely/, please transfer this issue to IW2/IDBW/whatever.

**Comment by lippserd** [comment]
When changing this, please also add a note in the upgrading docs that the URLs may [1] have changed.

[1] The URL is changed for new installations and upgrades if the scripts never have been changed.
