### ISSUE TITLE
Override variable set in include/command-plugins.conf

### ISSUE THREAD

**Issue by ajtwatching** [Icinga/icinga2#9355]
## Describe the bug

The default variable set in /usr/share/icinga2/include/command-plugins.conf persists despite variable being set inside command definition.
```
# grep 'nrpe_timeout_unknown =' /usr/share/icinga2/include/command-plugins.conf
	vars.nrpe_timeout_unknown = false
	vars.nrpe_timeout_unknown = false 
```

Fairly stock command definition which attempts to over ride nrpe_time_unknown:
```
# cat ./zones.d/global/commands/check_nrpe.conf

object CheckCommand "check_nrpe" {
    import "plugin-check-command"

    command = [ PluginDir + "/check_nrpe" ]

    arguments = {
        "-H" = "$nrpe_address$"
        "-p" = "$nrpe_port$"
        "-c" = "check_errors"
        "-n" = {
            set_if = "$nrpe_no_ssl$"
            description = "Do not use SSL."
        }
        "-u" = {
            set_if = "$nrpe_timeout_unknown$"
            description = "Make socket timeouts return an UNKNOWN state instead of CRITICAL"
        }
        "-t" = "$nrpe_timeout$"
        "-a" = "$nrpe_arguments$"
    }

    vars.nrpe_address = "$address$"
    vars.nrpe_no_ssl = false
    vars.nrpe_timeout_unknown = true
}
```
With nrpe_timeout_unknown now true, nrpe check command should add the '-u' flag.

## To Reproduce

1. Duplicate the supplied configuration
2. Monitor how the nrpe command is actually being called

## Expected behavior

With the override of nrpe_timeout_unknown = true in the command definition, check_nrpe should run with "-u" flag. I have verified that it's not being set both from monitoring the process list, however also simply when a 10 second timeout check is hit, a critical alert is generated instead of an unknown.
```
 -u, --unknown-timeout        Make connection problems return UNKNOWN instead of CRITICAL
```

## Your Environment

```root@monm01:~# rpm -qf /usr/share/icinga2/include/command-plugins.conf
icinga2-common-2.12.0-1.el8.icinga.x86_64
root@monm01:~# rpm -qi nrpe
Name        : nrpe
Version     : 4.0.3
Release     : 1.el8
Architecture: x86_64
```

## Additional context

If I override the variables in the default/include file - /usr/share/icinga2/include/command-plugins.conf - the '-u' flag is applied.

I also tried relocate the variable override in case position in the object definition mattered.. doesn't seem to have made a difference.

```
# cat zones.d/global/commands/check_nrpe.conf

object CheckCommand "check_nrpe" {
    import "plugin-check-command"

    vars.nrpe_timeout_unknown = true

    command = [ PluginDir + "/check_nrpe" ]
...
```

**Comment by julianbrost** [comment]
I don't think your `./zones.d/global/commands/check_nrpe.conf` file is loaded at all (have you defined a zone named `global`?). You can't replace existing objects like this, if the file was loaded you should get an object already exists error.

I think what you'd actually want to do would be to add `vars.nrpe_timeout_unknown = true` to your Host/Service templates.

**Comment by ajtwatching** [comment]
Thanks for taking a look, I do hear what you're saying...

Although config check is happy.
```
# icinga2 daemon -C
```

And object list suggests it is being loaded.
```
  * templates = [ "check_nrpe", "plugin-check-command", "plugin-check-command" ]
    % = modified in '/etc/icinga2/zones.d/global/commands/check_nrpe.conf', lines 2:1-2:32
    % = modified in 'methods-itl.conf', lines 18:2-18:94
    % = modified in 'methods-itl.conf', lines 18:2-18:94
  * timeout = 60
  * type = "CheckCommand"
  * vars
    * nrpe_address = "$address$"
      % = modified in '/etc/icinga2/zones.d/global/commands/check_nrpe.conf', lines 25:5-25:35
    * nrpe_no_ssl = false
      % = modified in '/etc/icinga2/zones.d/global/commands/check_nrpe.conf', lines 26:5-26:28
    * nrpe_timeout_unknown = true
      % = modified in '/etc/icinga2/zones.d/global/commands/check_nrpe.conf', lines 5:5-5:36
  * zone = "global"
```

The check command object in the system default config is `object CheckCommand "nrpe" {` where as we're creating a new one called `object CheckCommand "check_nrpe" {` which is what we subsequently call.

```
# grep nrpe /var/tmp/object.lst | egrep ^Object
Object 'check_nrpe' of type 'CheckCommand':
Object 'nrpev2' of type 'CheckCommand':
Object 'nrpe-audit' of type 'CheckCommand':
Object 'nrpe' of type 'CheckCommand':
```

I guess the intent was to try and override this "globally" with a new nrpe definition... but you're suggesting this is an invalid configuration?

**Comment by julianbrost** [comment]
When first reading the issue, I missed that you called the CheckCommand `check_nrpe` so it's a different object than the one shipped with Icinga (that's called just `nrpe` omitting the `check_` prefix). So ignore what I said about that the config validation.

What are you using as the `check_command` attribute of your services? If it's `nrpe`, you should get the default behavior of no `-u` and if it's `check_nrpe` you should be using your newly defined CheckCommand and `-u` should be included by default.

But basically that's the other option: redefine the CheckCommand with a different name and using that one.
