### ISSUE TITLE
API: Set downtime during reload returns "success" but no downtime is created

### ISSUE THREAD

**Issue by log1-c** [Icinga/icinga2#9366]
## Describe the bug

Hi team :),

we are currently running the following setup to set downtimes for terminal servers in an auto-scaling:

The Shutdown script on the agent host makes an API call to a HAProxy running on the satellite which is a hop to the master.
_This was necessary as the agent hosts can’t reach the master directly and the downtimes are rejected if the satellite is used as endpoint for the API call._

Now we occasionally have the problem that downtimes “don’t turn up” even though the API call returns returns a success like `Successfully scheduled downtime 'ts1002!06ad14a8-5xaf-4fa8-a986-a012c09429bd' for object 'ts1002'` but with no downtime being actually active
Example where at 22:32 the downtime was set via the script:
![image](https://user-images.githubusercontent.com/24474580/166894849-4adaf0a6-a6b4-48ba-93e9-869da7e37731.png)

As there was a config reload triggered (by the Icinga Director) at 22:32 as well, it seems to be the origin of the problem

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1.Trigger a config reload
-- not sure if this is only "Icinga Director config reload" related or happens without the Director as well
2. Trigger a downtime set via API directly/shortly after the reload was triggered
3. ???
4. (no) Profit

## Expected behavior

The API should either return a failure for the action so that this can be caught by the script and a retry can be done or the API "buffers" the request and activates the downtime once the reload is completed

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.13.2

**Comment by julianbrost** [comment]
Might be related to #9365, both issues are about some changes done during a config reload being lost.

**Comment by log1-c** [comment]
Sounds similar indeed.
The config in our setup is deployed via the Director as well. Will add that above!
