### ISSUE TITLE
No CentOS 8 packages for 2.13.3

### ISSUE THREAD

**Issue by Blorpy** [Icinga/icinga2#9369]
## Describe the bug

There are no el8 packages for 2.13.3 at https://packages.icinga.com/centos/8/release/x86_64/icinga2/ that I can find. 

## Expected behavior

el8 flavour packages are available for this release.

**Comment by julianbrost** [comment]
CentOS 8 reached its end of life, so we no longer provide new packages for it. In case you are using RHEL 8, please have a look at https://icinga.com/blog/2022/02/16/announcing-official-icinga-packages-for-rhel-amazon-linux-2-and-sles/
