### ISSUE TITLE
icinga2 rpm packages for EL8 out-dated

### ISSUE THREAD

**Issue by prupert** [Icinga/icinga2#9372]
## Describe the bug

The icinga2 rpm packages for Enterprise Linux 8 and derivatives (i.e. RockyLinux 8, AlmaLinux 8, CentOS 8) are out-dated. 

The current version is 2.13.3 as released on [April 14th 2022](https://icinga.com/blog/2022/04/14/releasing-icinga-2-13-3-and-2-12-7/).

The latest version available in https://packages.icinga.com/centos/8/release/src/icinga2/ is 2.13.2 from November last year.

**Comment by julianbrost** [comment]
The repository you linked is intended for CentOS 8 which has reached its end of life now, so we don't publish new versions to this repository. If you're looking for a replacement for RHEL, please have a look at https://icinga.com/blog/2022/02/16/announcing-official-icinga-packages-for-rhel-amazon-linux-2-and-sles/

**Comment by froooooooo** [comment]
> The repository you linked is intended for CentOS 8 which has reached its end of life now, so we don't publish new versions to this repository. If you're looking for a replacement for RHEL, please have a look at https://icinga.com/blog/2022/02/16/announcing-official-icinga-packages-for-rhel-amazon-linux-2-and-sles/

Is there still no update in regards to rocky 8 and icinga2? This package is fairly outdated now and it will make migrating from centos 7 to rocky 8 a bigger challenge as we will potentially need to drop icinga support if it wont be getting any updates etc
