### ISSUE TITLE
Check_update error Windows 2019

### ISSUE THREAD

**Issue by fwehuerguweioergjioerier** [Icinga/icinga2#9375]
Hello, 2x of my windows-servers shows an error when checking windows update.
Output:
`Failed to format error message, last error was: 2149859335`
The icinga community gave me the advice that it might be a bug.
Is there a way to see a full error message in any log file?

(Windows 2019, GUI Version)

Thanks for help.

* Version used (`icinga2 --version`): r2.13.3-1
* Operating System and version: Ubuntu 20.04.4 LTS
* Enabled features (`icinga2 feature list`): api checker / icingadb / ido-mysql / mainlog / notification
* Icinga Web 2 version and modules (System - About): 2.10.1
* Config validation (`icinga2 daemon -C`): Okay

**Comment by julianbrost** [comment]
Hi,

can you please provide some more information on where you see that error? I'm a bit confused as you say Windows server and later on mention Ubuntu. Is that the result of some check of a Windows server you run from Linux? If so, it's probably an issue with the check plugin in use. What's the check command in use (i.e. what does the service definition look like)?

**Comment by fwehuerguweioergjioerier** [comment]
Hello,
the icinga2 Master server is installed on the Ubuntu 20.04.4 LTS server.

The check_disk.exe is running on the Win Server 2019 I want to monitor.

The defined check command is configured as followed:

`object CheckCommand "update-windows" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_update.exe" ]
    timeout = 5m
    arguments += {
        "--no-reboot-critical" = {
            description = "Do not automatically return critical if an update requiring reboot is present."
            set_if = "$ignore_reboot$"
        }
        "--possible-reboot" = {
            description = "Treat 'may need update' as 'definitely needs update'"
            set_if = "$update_win_reboot$"
        }
        "-c" = {
            description = "Number of updates to trigger a critical"
            value = "$update_win_crit$"
        }
        "-w" = {
            description = "Number of updates to trigger a warning"
            value = "$update_win_warn$"
        }
    }
}
`
The error in icinga looks like this:
![image](https://user-images.githubusercontent.com/105846598/169787437-9bc83a33-8755-4602-933e-9e5d4f2af1ba.png)

**Comment by Al2Klimov** [comment]
Even if they don’t work, they should be fixed. They are our new way of Windows monitoring. The old C++ Windows plugins are legacy.

@bobapple What about dropping them **from the docs** if favor of IfW?

**Comment by Al2Klimov** [comment]
@julianbrost Do you agree as well?

**Comment by julianbrost** [comment]
They are already marked as deprecated in the docs: https://icinga.com/docs/icinga-2/latest/doc/10-icinga-template-library/#windows-plugins-for-icinga-2

And you'd want to just remove that section? I don't think we have removed the documentation for other deprecated features before removing the feature itself.
