### ISSUE TITLE
Agent does not support subjectAltName when connecting to Satellite

### ISSUE THREAD

**Issue by ze42** [Icinga/icinga2#9376]
## Describe the bug

Having an agent trying to connect to a satellite, it checks the CN, but does not accept to validate on subjectAltName.

[related code I found](https://github.com/Icinga/icinga2/blob/master/lib/remote/apilistener.cpp#L703-L716)

## To Reproduce

1. Generate a certificate having:
   - hostname as CN
   - alternateSubjectName including a different DNS entry
2. Configure an agent to connect, using the alternate DNS name

## Expected behavior

Acccepting to connect, and not an "Unexpected certificate common name"

## Screenshots
```
[2022-05-20 13:18:40 +0000] warning/ApiListener: Unexpected certificate common name while connecting to endpoint 'generic-alternate.dns-name.tld': got 'hostname.fullqualified.tld'
```

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.3-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.41-grsec-cerberhost-0.17.0-rap
  Architecture: x86_64

Build information:
  Compiler: GNU 10.2.1
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* Operating System and version: Debian/11
* Enabled features (`icinga2 feature list`): Enabled features: api checker mainlog notification
* Icinga Web 2 version and modules (System - About): N/A
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context

Trying to have (among other usages):
* satellite on AWS, that will have hostname == instance-id (aka, generated dynamicly when we re-create one)
* agents that will connect via a generic DNS entry pointing to "local" (same AWS region) satellite
* not wanting to reconfigure each agent if we change the satellite hostname, just updating DNS entry

**Comment by julianbrost** [comment]
The certificates are also used in the TLS client role and the server has to choose an `Endpoint` object based on the certificate. It uses the common name for this because this allows this mapping to be unambiguous. Similarly, when Icinga initiates an outgoing connection, it's doing so in order to connect to a specific endpoint, so this identity also has to be known beforehand.

The endpoint name doesn't have to match the hostname, so you can also use generic names as endpoint names as well.

**Comment by ze42** [comment]
For my agents, the endpoint should be ambiously "the closest satellite", the agent itself should **NOT** have to know about internals about satellite repartition/naming/...

The master should know on which satellite each end-agent is expected to connect... but why would an end-agent need to have exact specifics about the satellites it connects to?!

Yes, we could use a generic name per area, but would still need the agents to know exactly in which satellite area they are, and be configured with the specifics about the area.

From what I understand of your suggestion, and limitations I found:
* A satellite looks for its NodeName certificate, and must have the NodeName as CN
* Agent connecting to it can use the satellite NodeName as endpoint
* So, need to have a dedicated "Generic" name per area
* the satellite itself will have to use the GenericName, and will not be monitored via its hostname but via the GenericName

Am I right, or is something wrong about it?

(Is there any better place to discuss this, if not in usses?)

**Comment by julianbrost** [comment]
> For my agents, the endpoint should be ambiously "the closest satellite", the agent itself should **NOT** have to know about internals about satellite repartition/naming/...
> 
> The master should know on which satellite each end-agent is expected to connect... but why would an end-agent need to have exact specifics about the satellites it connects to?!

It's just how Icinga works at the moment. On the agent, you put it into a zone. In this zone, you have to specify the name of a parent zone, which basically defines your cluster topology.

> Am I right, or is something wrong about it?

Sounds correct.

> (Is there any better place to discuss this, if not in usses?)

Not really. Thing is, this limitation isn't something you could simply remove and things would be better, but rather requires rather fundamental changes to the cluster communication. There are also some suggestions in #7814, I haven't checked if this particular suggestion is in there, if it's not, adding it there in a central issue would probably be better.
