### ISSUE TITLE
installation instructions broken for fedora >= 34

### ISSUE THREAD

**Issue by tpo** [Icinga/icinga2#9382]
## Describe the bug

The installation instructions on https://icinga.com/docs/icinga-2/snapshot/doc/02-installation/04-Fedora/ do not work for Fedora >= 34.

```
# dnf install https://packages.icinga.com/fedora/icinga-rpm-release-$(. /etc/os-release; echo "$VERSION_ID")-latest.noarch.rpm`
root@officepc ~ # dnf install https://packages.icinga.com/fedora/icinga-rpm-release-$(. /etc/os-release; echo "$VERSION_ID")-latest.noarch.rpmLetzte Prüfung auf abgelaufene Metadaten: vor 0:08:32 am Mo 30 Mai 2022 12:00:36.
[MIRROR] icinga-rpm-release-34-latest.noarch.rpm: Status code: 404 for https://packages.icinga.com/fedora/icinga-rpm-release-34-latest.noarch.rpm (IP: 185.233.189.126)
[MIRROR] icinga-rpm-release-34-latest.noarch.rpm: Status code: 404 for https://packages.icinga.com/fedora/icinga-rpm-release-34-latest.noarch.rpm (IP: 185.233.189.126)
[MIRROR] icinga-rpm-release-34-latest.noarch.rpm: Status code: 404 for https://packages.icinga.com/fedora/icinga-rpm-release-34-latest.noarch.rpm (IP: 185.233.189.126)
[MIRROR] icinga-rpm-release-34-latest.noarch.rpm: Status code: 404 for https://packages.icinga.com/fedora/icinga-rpm-release-34-latest.noarch.rpm (IP: 185.233.189.126)
[FAILED] icinga-rpm-release-34-latest.noarch.rpm: Status code: 404 for https://packages.icinga.com/fedora/icinga-rpm-release-34-latest.noarch.rpm (IP: 185.233.189.126)
Status code: 404 for https://packages.icinga.com/fedora/icinga-rpm-release-34-latest.noarch.rpm (IP: 185.233.189.126)
```

in fact:

```
# wget https://packages.icinga.com/fedora/icinga-rpm-release-34-latest.noarch.rpm
--2022-05-30 12:10:05--  https://packages.icinga.com/fedora/icinga-rpm-release-34-latest.noarch.rpm
Auflösen des Hostnamens packages.icinga.com (packages.icinga.com)… 185.233.189.126
Verbindungsaufbau zu packages.icinga.com (packages.icinga.com)|185.233.189.126|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2022-05-30 12:10:05 FEHLER 404: Not Found.
```

I think this might be due to missing symlinks on your web server from https://packages.icinga.com/fedora/34/release/noarch/icinga-rpm-release/icinga-rpm-release-34-4.fc34.icinga.noarch.rpm back to the Fedora top level directory at https://packages.icinga.com/fedora/ ?

## To Reproduce

See above

## Expected behavior

Installation instructions on Fedora >= 34 should work.

## Your Environment

This is on Fedora 34

**Comment by JackTheExecuter** [comment]
Same issue with raspian:

root@pi:/home/pi# apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Ign:3 https://packages.icinga.com/ubuntu icinga-bullseye InRelease
Err:4 https://packages.icinga.com/ubuntu icinga-bullseye Release
  404  Not Found [IP: 185.233.189.126 443]
Reading package lists... Done
E: The repository 'https://packages.icinga.com/ubuntu icinga-bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@pi:/home/pi# apt install icinga2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package icinga2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'icinga2' has no installation candidate

**Comment by julianbrost** [comment]
@JackTheExecuter That's not the same issue. You are using the Ubuntu repository. Packages for Raspbian are at https://packages.icinga.com/raspbian/

**Comment by Al2Klimov** [comment]
@htriem Any objections against such or similar instructions instead of the repo RPM?

**Comment by htriem** [comment]
@Al2Klimov It's on the right track, but for one we only want the release repo to be implemented, and only for a specific Fedora version. I will implement `dnf config-manager --add-repo https://packages.icinga.com/fedora/$(. /etc/os-release; echo "$VERSION_ID")/release` as an instruction.
