### ISSUE TITLE
add windowseventlog.conf boolean that disables early logging 

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icinga2#9393]
## Is your feature request related to a problem? Please describe.

After icinga2 agent start on windows there are many log entries written regardless of severety level.
It would be nice to disable early logging and only enable it for troubleshooting.

## Describe the solution you'd like

make usage of void Logger::DisableEarlyLogging()

or

Use the severtity level for early logging

## Describe alternatives you've considered
change back to mainlog

Best Regards Nicolas

**Comment by Al2Klimov** [comment]
Hello @moreamazingnick!

> After icinga2 agent start on windows there are many log entries written regardless of severety level.

Which ones exactly for example?

Best,
A/K

**Comment by moreamazingnick** [comment]
`
Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Triggering Start signal for config items
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0578628Z" />
    <EventRecordID>244190</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Triggering Start signal for config items</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigObject: Restored 507 objects. Loaded 0 new objects without state.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0558576Z" />
    <EventRecordID>244189</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigObject: Restored 507 objects. Loaded 0 new objects without state.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigObject: Restoring program state from file 'C:\ProgramData\icinga2\var\lib\icinga2/icinga2.state'
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0528620Z" />
    <EventRecordID>244188</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigObject: Restoring program state from file 'C:\ProgramData\icinga2\var\lib\icinga2/icinga2.state'</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ScriptGlobal: Dumping variables to file 'C:\ProgramData\icinga2\var\cache\icinga2/icinga2.vars'
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0508594Z" />
    <EventRecordID>244187</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ScriptGlobal: Dumping variables to file 'C:\ProgramData\icinga2\var\cache\icinga2/icinga2.vars'</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 1 ApiListener.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0488600Z" />
    <EventRecordID>244186</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 1 ApiListener.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 2 Endpoints.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0488600Z" />
    <EventRecordID>244185</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 2 Endpoints.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 399 CheckCommands.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0488600Z" />
    <EventRecordID>244184</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 399 CheckCommands.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 4 Zones.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0478593Z" />
    <EventRecordID>244183</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 4 Zones.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 36 HostGroups.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0478593Z" />
    <EventRecordID>244182</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 36 HostGroups.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 1 FileLogger.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0478593Z" />
    <EventRecordID>244181</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 1 FileLogger.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 1 EventCommand.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0468607Z" />
    <EventRecordID>244180</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 1 EventCommand.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 9 NotificationCommands.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0468607Z" />
    <EventRecordID>244179</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 9 NotificationCommands.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 20 ServiceGroups.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0468607Z" />
    <EventRecordID>244178</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 20 ServiceGroups.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 33 TimePeriods.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0468607Z" />
    <EventRecordID>244177</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 33 TimePeriods.</Data>
  </EventData>
</Event>

Protokollname: Application
Quelle:        Icinga 2
Datum:         14.06.2022 09:12:18
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP
Beschreibung:
information/ConfigItem: Instantiated 1 IcingaApplication.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:18.0458588Z" />
    <EventRecordID>244176</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>information/ConfigItem: Instantiated 1 IcingaApplication.</Data>
  </EventData>
</Event>
`

and some apply rule warnings which should also not be there for loglevel critical

`
Beschreibung:
warning/ApplyRule: Apply rule 'WMI Free Disk Space' (in C:/ProgramData/icinga2/var/lib/icinga2/api/zones/director-global/director/servicesets.conf: 668:1-668:35) for type 'Service' does not match anywhere!
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Icinga 2" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-14T07:12:17.9508595Z" />
    <EventRecordID>243920</EventRecordID>
    <Correlation />
    <Execution ProcessID="19476" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>warning/ApplyRule: Apply rule 'WMI Free Disk Space' (in C:/ProgramData/icinga2/var/lib/icinga2/api/zones/director-global/director/servicesets.conf: 668:1-668:35) for type 'Service' does not match anywhere!</Data>
  </EventData>
</Event>
`

**Comment by julianbrost** [comment]
The issue here is that early logging is logging that happens before the logging configuration was processed, i.e. we can't use the logging configuration as it was not loaded yet. Therefore some hardcoded default is used.

One possibility would be that Icinga logs to a dedicated Icinga section in the Windows Event Log, keeping the generic application log clean. Additionally, we could consider raising the minimum log level for early messages to warning, information might be a bit excessive and warning should totally suffice for the reason why this was introduced in 2.13 (until then, these messages were just lost, so if you deployed a broken configuration, the agent wouldn't start but also wouldn't log anything).

**Comment by moreamazingnick** [comment]
dedicated icinga log section would be great.

Best Regards
Nicolas
