### ISSUE TITLE
404 in icinga docs for icinga web db setup

### ISSUE THREAD

**Issue by s0ftcorn** [Icinga/icinga2#9426]
On https://icinga.com/docs/icinga-2/snapshot/doc/02-installation/01-Debian/#set-up-icinga-db clicking the [install the Icinga DB daemon on Debian](https://icinga.com/docs/icinga-db/latest/doc/02-Installation/03-Debian/#installing-icinga-db-package) link leads to a 404.

Browser: Chrome 103
OS: Windows 11

**Comment by julianbrost** [comment]
Link seems to work now. We're in the process of releasing things across repos, so there might be a few broken links for a short time.
