### ISSUE TITLE
apt check issues in 2.13.4-1?

### ISSUE THREAD

**Issue by kiwichrish** [Icinga/icinga2#9431]
## Describe the bug

After upgrading some VMs running Ubuntu 22.04 and 20.04 from 2.13.3-1 to 2.13.4-1 the apt update check fails with ''/usr/bin/apt-get true dist-upgrade' exited with non-zero status.' when there are no packages due for update.  Downgrading the machines again fixes it.  

## To Reproduce

1. Started running icinga2 install on 2.13.3-1 across 10 vms in my home test lab.
2. Upgraded 22.04 and 20.04 machines to 2.13.4-1.focal / jammy
3. re-check apt and get the error in the web UI ''/usr/bin/apt-get true dist-upgrade' exited with non-zero status.'
4. Downgrade and apt-mark hold affected VMs and error goes away.

## Expected behavior

apt update check returns '0' when there are no patches due.

## Screenshots

![Screenshot 2022-07-02 100245](https://user-images.githubusercontent.com/7635913/176973111-7d5bed6c-b4c9-4150-bd7a-a60f2168e6c8.png)

## Your Environment

* Version used (`icinga2 --version`): 2.13.3-1 / 2.13.4-1
* Operating System and version:  Ubuntu 20.04 for icinga2 'master'  Ubuntu 20.04 and 22.04 on monitored clients.
* Enabled features (`icinga2 feature list`): Enabled features: api checker mainlog (the client that's reporting the error)
* Icinga Web 2 version and modules (System - About): 2.10.1 graphite / monitoring
* Config validation (`icinga2 daemon -C`):   Passes on both host and client with just warnings about some unused / no match stuff.  Not sure if you need host or client?

**Comment by kiwichrish** [comment]
Interesting..  A couple of machines on the production network at work upgraded to 2.13.4-1.focal  before I put the apt-mark hold on them and are not getting the error.

**Comment by kiwichrish** [comment]
Tracked it down to the use of the apt_dist_upgrade parameter.

On the test system that fails I had:

    apt_dist_upgrade="true"

In the command template.  Per the error msg above it's passing this through as 'true' to the command line parameters for apt-get.

Switching to true without the quotes gives the same result.

Not sure where this should live now.  Something has clearly changed in the handing of check_apt but when it's not overridden with a custom command but I'm not sure where it lives in icinga2 as I've not had problems with the default stuff before.

**Comment by chn42** [comment]
Behaviour changed with 069c3968d9aaf5ab1be853ae298e25378a024c2e, and the same is true for --upgrade.

**Comment by ThomasLeister** [comment]
I'm having the same issue since a few days and I'm not sure what / if I can do anything about it. Is there any workaround for this or do we need to wait for an Icinga2 update? Hmm. :thinking:

**Comment by kiwichrish** [comment]
> I'm having the same issue since a few days and I'm not sure what / if I can do anything about it. Is there any workaround for this or do we need to wait for an Icinga2 update? Hmm. 🤔

Just comment out the apt_dist_upgrade setting in your apt template / checks and it will go away.
