### ISSUE TITLE
influxdbwriter ignores perfdata from passive checks

### ISSUE THREAD

**Issue by kochd** [Icinga/icinga2#9439]
I noticed that influxdbwriter (v1) does not handle the perfdata of passive checks.
v2 might be affected by this as well.

The passive check result is submitted using the API (https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#process-check-result)

The latest perfdata is available to icingaweb2 (when viewing the service) but it never gets send to the influxdb (I queried for it using the influx cli).
There is no meassurement named 'lvm-thin' even tho I have a service named 'lvm-thin' which has perfdata aswell. 

This tells me that the passive-check is correctly sending perfdata and it gets written into the ido but the influxwriter ignores it for some reason. 

I found multiple people noticing the same, but it was never solved. (https://github.com/Icinga/icinga2/issues/6228 and in the community forums)
I cant find any sort of log that gives more information about why it never gets written.

Imho this is an unintended behavior of influxdbwriter and therefore an actual bug.

**Comment by Al2Klimov** [comment]
Hello Daniel and thanks for reporting!

Last year I've successfully set up passive checks with perfdata for InfluxDB myself.

In other words: works for me.

Please share an example of your passive check as a curl invocation.

Best,
A/K

**Comment by kochd** [comment]
Hello Alexander, thank you for investigating this.
While writing this down I figured that I was mislead by false beliefs.

# API
Request body that gets send:

``` json
{
  "type": "Service",
  "filter": "host.name==\"hostname.domain.local\" && service.name==\"lvm-thin\"",
  "exit_status": 0,
  "plugin_output": "[OK] pve: {:lv_name=>\"data\", :lv_size=>7009919303680, :lv_data_pct=>9, :lv_metadata_pct=>2, :provisioned=>2370847113216, :provisioned_pct=>34}\n",
  "performance_data": [
    "pve_lv_size=7009919303680b",
    "pve_lv_data_pct=9%;85%;90%",
    "pve_lv_metadata_pct=2%;85%;90%",
    "pve_provisioned=2370847113216b",
    "pve_provisioned_pct=34%;100%"
  ],
  "check_source": "hostname.domain.local",
  "pretty": true
}
```

using curl that would be:
``` bash
curl -k -s -S -i -u root:icinga -H 'Accept: application/json' \
 -X POST 'https://localhost:5665/v1/actions/process-check-result' \
-d '{"type":"Service","filter":"host.name==\"hostname.domain.local\" && service.name==\"lvm-thin\"","exit_status":0,"plugin_output":"[OK] pve: {:lv_name=>\"data\", :lv_size=>7009919303680, :lv_data_pct=>9, :lv_metadata_pct=>2, :provisioned=>2370847113216, :provisioned_pct=>34}\n","performance_data":["pve_lv_size=7009919303680b","pve_lv_data_pct=9%;85%;90%","pve_lv_metadata_pct=2%;85%;90%","pve_provisioned=2370847113216b","pve_provisioned_pct=34%;100%"],"check_source":"hostname.domain.local","pretty":true}'
```

# Icinga Web
Shows the perfdata as expected:
![image](https://user-images.githubusercontent.com/1825660/210239533-419b0e1c-bf26-4c77-acd6-b7803355f88b.png)

# Influx
Doesn't know about a measurement named _lvm-thin_
```
> show MEASUREMENTS with MEASUREMENT = "lvm-thin"
NULL
```

# Solution
While writing this down I figured that I was mislead by false beliefs.
As I wrote in the initial report:
> There is no measurement named 'lvm-thin' even tho I have a service named 'lvm-thin' which has perfdata aswell.

However my [influxdb.conf](https://github.com/Icinga/icinga2/blob/master/etc/icinga2/features-available/influxdb.conf) defines that the service template is:
```
measurement = "$service.check_command$"
```

and the check_command used is "passive". 
The service name is irrelevant for naming the measurement.  

Therefore if I query Influx:
```
select * from passive where service = 'lvm-thin' limit 10;
```
it works totally fine. 
I just had to query them differently than I query for active checks.
