### ISSUE TITLE
Acknowledgement delete only the comment after expire time but not the acknowledgement state

### ISSUE THREAD

**Issue by bab-mkedziora** [Icinga/icinga2#9452]
## Describe the bug
After the acknowledgment expiry time is expired, Icinga2 is clearing the comment but not clearing the acknowledgments and not enabling the re-notifcations.

The history logs that the acknowledgments has been removed (see screenshot). But, the check is still in acknowledgment state and re-notifications are not getting triggered. 

Also the logs on the Icinga host show that only the comment was removed but not the acknowledgement

[2022-07-22 13:21:11 +0200] information/ExternalCommandListener: Executing external command: [1658488871] ACKNOWLEDGE_SVC_PROBLEM_EXPIRE;n095211;ssh_restrict_entropy;0;1;0;1658488921;m.kedziora;test
[2022-07-22 13:21:11 +0200] information/ConfigObjectUtility: Created and activated object 'n095211!ssh_restrict_entropy!8014a2a9-8f65-4856-b056-32c05dd57a11' of type 'Comment'.
[2022-07-22 13:21:11 +0200] information/Checkable: Notifications are disabled for checkable 'n095211!ssh_restrict_entropy'.
[2022-07-22 13:21:11 +0200] information/Checkable: Acknowledgement set for checkable 'n095211!ssh_restrict_entropy'.
[2022-07-22 13:22:19 +0200] information/ConfigObjectUtility: Deleted object 'n095211!ssh_restrict_entropy!8014a2a9-8f65-4856-b056-32c05dd57a11' of type 'Comment'.

## To Reproduce
Acknowledgment any warning/critical check with expiring time and bide the time.

## Expected behavior
The acknowledgement is removed after expiry time is expired.

## Screenshots
![image](https://user-images.githubusercontent.com/47978652/180437265-255fd5c5-490e-449d-9cd9-f98566471d13.png)
![image](https://user-images.githubusercontent.com/47978652/180437430-3d0b1cf7-16bb-45ce-8bb9-2dfbf0332350.png)
![image](https://user-images.githubusercontent.com/47978652/180437447-fba4757c-75f7-47d5-976d-1663c027ffbd.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):  Icinga Web 2 Version 2.10.1-1
* Web browser used: Firefox 102
* Icinga 2 version used (`icinga2 --version`): r2.13.3-1
* PHP version used (`php --version`): 7.3.29
* Server operating system and version: CentOS 7

**Comment by julianbrost** [comment]
Does this also happen when you use the [API](https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#acknowledge-problem) rather than the deprecated ExternalCommandListener? When I tried this using the API, it worked just fine.

**Comment by bab-mkedziora** [comment]
> Does this also happen when you use the [API](https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#acknowledge-problem) rather than the deprecated ExternalCommandListener? When I tried this using the API, it worked just fine.

It happens when we use the icinga2 Web GUI

**Comment by Al2Klimov** [comment]
And if you switch that GUI from ExternalCommandListener to API?

**Comment by bab-mkedziora** [comment]
> And if you switch that GUI from ExternalCommandListener to API?

How can we switch from ExternalCommandListener to API? Do you have a HowTo?

**Comment by Al2Klimov** [comment]
Yes: https://www.youtube.com/watch?v=_xSPTqQnJxk

**Comment by bab-mkedziora** [comment]
@Al2Klimov, with API works fine! Thanks a lot!
I close this Issue
