### ISSUE TITLE
config reload doesn't work on OpenBSD

### ISSUE THREAD

**Issue by jmatthew** [Icinga/icinga2#9481]
## Describe the bug

After the first reload completes, `l_CurrentlyStartingUnixWorkerState` is set to `Pending`. The parent then asks the previous worker to exit, which results in a SIGCHLD delivered to the parent. On platforms such as OpenBSD where siginfo_t doesn't provide the pid that exited, the parent can't match this up to `l_CurrentlyStartingUnixWorkerPid`, so it sets `l_CurrentlyStartingUnixWorkerState` to Failed even though it wasn't a currently-starting worker that exited.

On the next reload, `l_CurrentlyStartingUnixWorkerState` will still be `Failed`, so the parent will immediately conclude the new worker failed to load the config, so the reload process fails.

I can see a couple of simple fixes for this - either set `l_CurrentlyStartingUnixWorkerState` to Pending just before forking, or check that `l_CurrentlyStartingUnixWorkerPid` is not -1 in the signal handler. I'm running with the first one now and reloads work properly. I'm not sure which of these to go with, and they're both trivial changes, so I haven't open a pull request.

## To Reproduce

1. Install icinga on OpenBSD. I'm using 7.1, where icinga 2.13.3 is available as a package, but it's probably been like this for a while. I just upgraded my icinga server directly from OpenBSD 6.6 and icinga 2.11.2, where (with #7739 backported) reloads worked properly. I haven't been able to identify a specific commit that broke it.
2. Start icinga (`rcctl start icinga2`)
3. Reload config (`rcctl reload icinga2`)
4. Reload config again - icinga stops working at this point and has to be killed

## Expected behavior

Reload process should be successful, and icinga should keep working.

## Screenshots

n/a

## Your Environment

* Version used (`icinga2 --version`):  2.13.3
* Operating System and version:  OpenBSD 7.1
* Enabled features (`icinga2 feature list`): api checker mainlog notification
* Icinga Web 2 version and modules (System - About): n/a
* Config validation (`icinga2 daemon -C`): works

**Comment by Al2Klimov** [comment]
## How it currently works

![](https://user-images.githubusercontent.com/6053266/184867122-c7f56eb2-c263-4272-aa2b-8bdb14c51cc1.jpg)

## How it shall work

![1](https://user-images.githubusercontent.com/6053266/184867196-5ee13b7e-baa8-490b-8d81-f54c1f8b13ce.jpg)

@julianbrost Any objections?

**Comment by julianbrost** [comment]
@Al2Klimov I don't really understand what your pictures are trying to say. The failed state is unreachable in the second one, what should happen if it actually fails to load the config?

**Comment by Al2Klimov** [comment]
That pictures do (and shall) not cover all cases, only a particular one. In the case you mentioned it becomes reachable.

**Comment by julianbrost** [comment]
So what is "8) CHLD" supposed to say then? Given that it's not attached to some error, it looks like it does nothing. But at the moment, that's how the failed condition is detected, so it has to do something or has to be replaced with something else. So just from this pictures, I can't tell what you want to do.
