### ISSUE TITLE
Icinga2 autodiscovery

### ISSUE THREAD

**Issue by lAnviuml** [Icinga/icinga2#9490]
Hello,

I am a technician and I am asked to set up Icinga with automatic discovery.

I was originally asked to configure Icinga with librenms auto-discovery (apparently already configured), how is this possible?

What are the possible solutions to implement Autodiscover in Icinga?

Thanks in advance,

Adrian.

**Comment by Al2Klimov** [comment]
Cross-post of https://community.icinga.com/t/icinga2-autodiscovery/10380

**Comment by duven87** [comment]
is a loop between 2 web sites that do not provide any info or any idea of future projection to implement it.

**Comment by slalomsk8er** [comment]
@duven87 I don't know what you mean by loop between 2 websites?
I use 
- https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/librenms-alerts 
- https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/librenms-health
- https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/librenms-version

to check LibreNMS and/or single devices in LibreNMS from Icinga2.

You can also use the Icingaweb2 director module to read the LibreNMS DB and automatically generate Icinga2 configuration for the devices in there.
If you don't push stuff via REST API into Icinga2, the way of automating is to read your CMDB or other source via Icingaweb2 director and generate the config to monitor the "discovered" devices.
Also the Icingaweb2 x509 module can be used for auto discovery / net crawling and then again you can use the director to write config for the discovered TLS hosts and ports.

So a Icingaweb2 module that does use nmap as backend for "autodiscovery" and use the director automation, REST API or the Icinga2 REST API would be possible but maybe a explicit feature request would be better then asking for a howto.
