### ISSUE TITLE
Support for Enterprise Linux 9 // Rocky 9 / Alma 9 / Rhel9 / CentOS Stream 9

### ISSUE THREAD

**Issue by VonNao** [Icinga/icinga2#9493]
Would it be possible to create support for Enterprise Linux 9 // Rocky 9 / Alma 9 / Rhel9 / CentOS Stream 9
EL9 is stable for a while and we would like to deploy Icinga2 to el9

**Comment by lippserd** [comment]
Hi,

Packages for RHEL9 are available via [subscription](https://icinga.com/subscription/).

All the best,
Eric
