### ISSUE TITLE
Avoid redundant `GetObjectIdentifier()` calls

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icinga2#9507]
## Describe the bug

It is unnecessary to call `GetObjectIdentifier()` repeatedly for the same object, as it is already time-consuming. For example, one could cache the hashed checksum and then pass it around to others as needed. Here the object is passed to `IcingaDB::InsertObjectDependencies()`, which generates a checksum to process all its dependencies, and just one line below we are generating a new hash for the same object.
https://github.com/Icinga/icinga2/blob/3a8abdcc3b85a3be62a0805b465e5fac55ae0538/lib/icingadb/icingadb-objects.cpp#L1528-L1530

 I haven't really checked it out yet, but it would also be smart if we didn't have to keep casting the object back and forth all the time. Or at least use `static_pointer_cast<>()` instead of dynamic casting where applicable.

https://github.com/Icinga/icinga2/blob/3a8abdcc3b85a3be62a0805b465e5fac55ae0538/lib/icingadb/icingadb-objects.cpp#L291-L293

https://github.com/Icinga/icinga2/blob/3a8abdcc3b85a3be62a0805b465e5fac55ae0538/lib/icingadb/icingadb-objects.cpp#L329

https://github.com/Icinga/icinga2/blob/3a8abdcc3b85a3be62a0805b465e5fac55ae0538/lib/icingadb/icingadb-objects.cpp#L335

**Comment by yhabteab** [comment]
Alternatively, we could introduce a new attribute that contains the checksum of an object. Then we would have to hash the object only once and we could use it all over IcingaDB. That would save us a lot of CPU time.

**Comment by Al2Klimov** [comment]
## Suggestion

* a non-config, non-state, non-API string attribute in the (I guess) ConfigObject base class
* GetObjectIdentifier() uses it as cache (if "", calculate, set, endif, return the value)

Any objections?

**Comment by julianbrost** [comment]
Should be fine as long as the object IDs are only influenced by the then `environment_id` (shared by all IcingaDB objects in one icinga2 process) and the object names which should be constant (should because of #9407).
