### ISSUE TITLE
Docs: incorrect start command for icingadb-redis on Debian

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#9511]
https://icinga.com/docs/icinga-2/latest/doc/02-installation/01-Debian/#run-icinga-db-redis gives the following command to enable and start the Redis server on Debian:

```shell
systemctl enable --now icingadb-redis
```

However, when actually using this command, you get the following error:

```
Failed to enable unit: Refusing to operate on alias name or linked unit file: icingadb-redis.service
```

This is with version 7.0.2-1.bullseye of the icingadb-redis package where `icingadb-redis.service` is an alias for `icingadb-redis-server.service`.

Note that this step is somewhat redundant, as the package (by Debian standards) automatically enables and starts the service anyways.

**Comment by Al2Klimov** [comment]
Fixed in v7.0.15: https://icinga.com/blog/2024/06/26/new-redis-open-source-server-packages-for-icinga-db/
