### ISSUE TITLE
Python requests library cannot get the Cookie : sessionID

### ISSUE THREAD

**Issue by jovanickg** [Icinga/icinga2#9525]
Hello everyone,

I made python code that is sending the GET requests to our Icinga monitoring system. But I am not able to save the Cookie session ID, no matter which request I make... 

I am clearly seeing it through my browser and when I try to access it with the code it's impossible.

I will be very glad to hear from you and I hope I am not bothering anyone. Thanks in advance! Cheers!
LJ

**Comment by julianbrost** [comment]
This sound more like a question about Python or the libraries you use to me. Maybe those provide help channels that may be better places to ask this question, or if those don't exist, you may ask for help in our [community forum](https://community.icinga.com/), but please include more details on what you're trying to do (for example, share code snippets showing what you are doing).
