### ISSUE TITLE
InfluxDBwriter: warning/InfluxdbWriter: Flush failed, cannot connect to InfluxDB: Error: TLS certificate validation failed: code 62: Hostname mismatch

### ISSUE THREAD

**Issue by SB211** [Icinga/icinga2#9527]
Host system running icinga2 : FreeBSD 13.1-RELEASE-p2
Icinga2 version running: icinga2-2.13.4_1

Host system running InfluxDB v 1.8: FreeBSD 13.1-RELEASE-p2
InfluxDB version: influxdb-1.8.10_6 

InfluxDB has been setup using HTTPS/TLS utilizing self-signed certificates.

Within our domain (no DNS, every host is accessed by IP) multiple hosts reporting in sensor data via working(!) SSL connection to InfluxDB,  using curl (curl -ssl -unsafeSsl ...).

Icinga2 is supposed to report performance data to influxdb server, therefore influxdb has been setup:
# icinga2    feature list
Disabled features: compatlog debuglog elasticsearch gelf icingadb ido-mysql influxdb2 opentsdb statusdata
Enabled features: api checker command graphite ido-pgsql influxdb livestatus mainlog notification perfdata syslog

more /usr/local/etc/icinga2/features-enabled/influxdb.conf

[...]
object InfluxdbWriter "influxdb" {
        host = "XXX.XXX.XXX.XX"
        port = 8086
        ssl_enable = true
        //ssl_ca_cert = "/var/lib/icinga2/ca/ca.crt"
        ssl_cert = "/usr/local/etc/certs/icinga/server.pem.crt"
        ssl_key = "/usr/local/etc/certs/icinga/server.key"
        database = "XXXXX"
        username = "XXXX"
        password = "XXXXXX"
        flush_threshold = 1024
        flush_interval = 10s
        enable_send_thresholds = true
        enable_send_metadata = true
        host_template = {
                measurement = "$host.check_command$"
                tags = {
                        hostname = "$host.name$"
                }
        }
        service_template = {
                measurement = "$service.check_command$"
                tags = {
                        hostname = "$host.name$"
                        service = "$service.name$"
                }
        }
}
[...]

PROBLEM:

Icinga never gets a valid connection to the influxdb host logging allways:

InfluxDBwriter: warning/InfluxdbWriter: Flush failed, cannot connect to InfluxDB: Error: TLS certificate validation failed: code 62: Hostname mismatch

Accessing the influxdb on the influxdb-host via the CLI influx utility from the icinga2 host works without problems! Disabling TLS/HTTPS on InfluxDB Host renders Icinga2 InfluxDBWriter working (but this is not an option).

For the record: InfluxDB/influxdb running host uses ECC self signed certificate with key algo prime256v1 (we realized that brainpool256r1 has issues with the underlying GO library and is not working).

The TLS setup of the influxdb backend is now plain, the least possible setup no restrictions on ciphers, TLS version whatsoever). Still no connection with icinga2!
Influx CLI works like a charme!

I'm out of ideas here. I couldn't find any hint whether Icinga2 is unwilling/incapable of dealing with unsigned certificates and I did not find any hint of a magix switch like SSL_NO_VERIFY_PEER/SSL_NO_VERIFY_HOSTNAME in the config as shown above as those environemnt variables are usually used to signal the underlying SSL library to avoid certain authenticity test and so on.

Please can someone point me to the reason why Icinga2 isn't dealing with the proper connection?

**Comment by Al2Klimov** [comment]
Hello @SB211!

Is it an option to let the self-signed certificate match the hostname/ IP address via SAN?

Best,
A/K

**Comment by RincewindsHat** [comment]
@SB211 did you try the `ssl_insecure_noverify` or the (better) `ssl_cert` option in the InfluxDB Writer config of Icinga2?
Why use HTTPS anyway, if you are using self-signed certs and do not attempt to verify them?

**Comment by Al2Klimov** [comment]
I see we have more than on reasonable fix...
