### ISSUE TITLE
Icinga 2 and Rocket Linux

### ISSUE THREAD

**Issue by tkoeck** [Icinga/icinga2#9538]
CentOS Linux will be [discontinued](https://en.wikipedia.org/wiki/CentOS#cite_note-22) so a lot of companies like ours seem to migrate to Rocket Linux.

Will Icinga 2 also support Rocket Linux? It doesn't seem to be officially supported right now.

**Comment by ms217** [comment]
That was discussed before. See #9390

Short: No freely available binaries, except for RHEL/CentOS 7.

**Comment by Al2Klimov** [comment]
Actually there's https://icinga.com/subscription/developer-subscription/
