### ISSUE TITLE
Wrong executable name for check_systemd plugin

### ISSUE THREAD

**Issue by lyknode** [Icinga/icinga2#9547]
Hi,

In [itl/plugins-contrib.d/systemd.conf](https://github.com/Icinga/icinga2/blame/master/itl/plugins-contrib.d/systemd.conf#L4), the command definition for check_systemd plugin looks for `check_systemd.py`.

However, in upstream [README.rst](https://github.com/Josef-Friedrich/check_systemd/blob/main/README.rst), upstream [icinga2 command definition](https://github.com/Josef-Friedrich/check_systemd/blob/main/contrib/icinga2/command.conf#L2) and in [Debian](https://packages.debian.org/sid/all/monitoring-plugins-systemd/filelist), the plugin is installed as `check_systemd`.

Would it be possible to update the plugin name in the docs and the command definition to match the command name as defined by upstream and installed in Debian?

Let me know if you want me to provide the corresponding PR.

Best,

**Comment by krishnacx** [comment]
Please empower me to work on this issue.

**Comment by julianbrost** [comment]
> Please empower me to work on this issue.

You don't need any special permissions to create pull requests against this repo.

But let's first sort out if we want to change this. Has that project renamed the command in the meantime or does this discrepancy exist from the beginning? @yayayayaka As you added the command, do you know of any distributions that provide this check with the `.py` extension in the command name?

**Comment by yayayayaka** [comment]
This discrepancy exists since the beginning and we should fix that.
