### ISSUE TITLE
Windowseventlog severity doesn't work

### ISSUE THREAD

**Issue by phil-or** [Icinga/icinga2#9564]
Changing the log level in windowseventlog.conf and restarting the service or disabling/enabling the feature has no effect on the Windows event log.

object WindowsEventLogLogger "windowseventlog" {
    severity = "critical"
}

There are still "warnings" in the eventlog.

**Comment by phil-or** [comment]
Icinga Version: 2.13.4

This message for example:
warning/ApplyRule: Apply rule 'disk' (in C:/ProgramData/icinga2/var/lib/icinga2/api/zones/director-global/director/servicesets.conf: 4663:1-4663:24) for type 'Service' does not match anywhere!

**Comment by julianbrost** [comment]
Please upgrade to [version 2.13.5](https://github.com/Icinga/icinga2/releases/tag/v2.13.5), this was fixed in that version (#9457).

**Comment by phil-or** [comment]
Okay thanks, I will try it out!
