### ISSUE TITLE
Fedora 37 RPM builds are missing

### ISSUE THREAD

**Issue by 4ndyZ** [Icinga/icinga2#9587]
## Problem/Request

Fedora 37 got released last week (see https://fedoramagazine.org/announcing-fedora-37/) but there are no RPM packages available for it at the moment at the official repository at https://packages.icinga.com/fedora/

## Solution

The rpm.spec (at https://git.icinga.com/packaging/rpm-icinga2) and Docker images (at https://git.icinga.com/build-docker/fedora) have to be updated to include Fedora 37 and point to the right dependencies.

Also the Github workflows have to be updated. I have created a pull requests for it.

Unfortunately the other repositories are not available to public pull requests.

**Comment by 4ndyZ** [comment]
@cla-bot check

**Comment by htriem** [comment]
Our packages for Fedora 37 have been released by now, so I'll close this. Follow the discussions in the mentioned issues to check how we'll manage the GitHub Actions. 

And thanks for opening up the PRs!
