### ISSUE TITLE
Customize global runtime macro $date

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/icinga2#9590]
It would be useful, if the user could modify global runtime macros like $date.

For example:
You want to use $date but with a different format. The format from $date is always "YYY-mm-dd". In some cases, users could need another date format. For example "YYYYmmddTHHMMSS". Configuring this where possible would be a nice feature.

**Comment by tbauriedel** [comment]
ref/NC/768837

**Comment by Al2Klimov** [comment]
Do you consider `{{ DateTime().format("%Y-%m-%d") }}` a sufficient replacement for `"$date$"`?
