### ISSUE TITLE
Allow API to specify tls_protocolmin TLSv1.3 

### ISSUE THREAD

**Issue by roguenorman** [Icinga/icinga2#9626]
Our security team insist that we must disable TLSv1.2 and below on our servers for compliance reasons. Currently there is no way to force TLSv1.3 on the API

Can the ApiListener support the tls_protocolmin TLSv1.3
```
object ApiListener "api" {
  accept_commands = true
  accept_config = true
  tls_protocolmin = TLSv1.3
  ticket_salt = TicketSalt
}
```

**Comment by julianbrost** [comment]
What version of Icinga are you using and on which operating system are you? If you're using 2.13 and the OS ships a version of OpenSSL that supports TLS 1.3, this should work, you just have to pass the value as a string (i.e. add double quotes around it).
