### ISSUE TITLE
IcingaDB: PerfData normalization drops min/max when there is no warn/crit

### ISSUE THREAD

**Issue by EmTeedee** [Icinga/icinga2#9634]
## Describe the bug
Normalization incorrectly drops min/max values. e.g. `'test'=10;;;0;20` is normalized to `'test'=10`.

This prevents icingadb-web from displaying pie charts.

## To Reproduce

1. Create dummy test with dummy_text = `'test'=10;;;0;20`
2. Wait for service to be updated.
3. Check icingadb database in the servicestate table

## Expected behavior

As much of the performance data as possible should be forwarded.
In this case I expect `example|'test'=10;;;0;20`

## Actual behavior

Data in table gets shortened to `'test'=10`

![icinga_perfdata_drop](https://user-images.githubusercontent.com/195600/212951571-1bdd642f-3247-455e-a8fa-9dad9f3bd323.png)

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.13.6-1
* Operating System and version: Debian 11
* Enabled features (`icinga2 feature list`): api checker graphite icingadb ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.11.3
* Config validation (`icinga2 daemon -C`): some unrelated warnings

## Additional context

Documentation doesn't mention that warn/crit are required.

- https://icinga.com/docs/icinga-2/latest/doc/05-service-monitoring/#performance-data-metrics
- https://www.monitoring-plugins.org/doc/guidelines.html#AEN201

Perfdata without warn/crit can be helpful for reporting on and assessing a problem.

I believe it would suffice to change the nesting in this if-structure, but I don't have a working dev environment atm:
https://github.com/Icinga/icinga2/blob/ce5e6e7d13a8701031072f56e22b5e34bb6a2492/lib/base/perfdatavalue.cpp#L366-L380

**Comment by scjundev** [comment]
I'm a beginner that would like to work on this issue. Could you assign it to me? @EmTeedee @Al2Klimov
