### ISSUE TITLE
Icinga sends out notifications despite acknowledgements

### ISSUE THREAD

**Issue by BT-Basit** [Icinga/icinga2#9755]
## Describe the bug

Although services were acknowledged they still sent out notifications:
![image](https://user-images.githubusercontent.com/120741671/235852658-a1102f77-dcba-4432-9e4a-d2642b4d4be6.png)

During our troubleshooting session we found incorrect values in the 'Object inspection' view. The value of 'acknowledgement' was 0. All other services that don't have this problem showed values other than 0. So our guess is that the director gets a wrong result when querying the object data:
![image](https://user-images.githubusercontent.com/120741671/235852706-ce63e4d7-6bbc-4314-9be2-b8ca914681cb.png)

Furthermore, when we were analyzing the acknowlegdement comments in the configuration directory (`/var/lib/icinga2/api/packages/_api/{stage}/conf.d/comments`) we noticed that .conf files of the problematic services had not been synced on both masters.

Is it possible that Icinga has some trouble syncing the acknowledgement configs between the two masters and because of that acknowledgements are not handled correctly? Also, where does the value 0 of acknowledgement in 'Object inspection' come from?

## To Reproduce
We were not able to reproduce this issue.

## Expected behavior
Icinga should not send notifications while a host/service is acknowledged.

## Your Environment

* Version used (`icinga2 --version`): r2.13.6-1
* Operating System and version: RHEL 7 (7.9)
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.11.3
* 2 Master and 2 Satellites for each Master

**Comment by BT-Basit** [comment]
Hi there,

are there any updates regarding this issue?
This problem is still not solved on our side.

Best regards,

Basit

**Comment by julianbrost** [comment]
> Also, where does the value 0 of acknowledgement in 'Object inspection' come from?

From the Icinga 2 API ("Inspected via icinga1 [...]").

> Is it possible that Icinga has some trouble syncing the acknowledgement configs between the two masters and because of that acknowledgements are not handled correctly?

Quite possible, please query the service attributes from both nodes using the API URL `https://<icinga-host>:5665/v1/objects/services/<host-name>!<service-name>` for that service and compare the values.

The timestamp shown for `acknowledgement_last_change` shown in the screenshot (1677845151, which is Fri 03 Mar 2023 12:05:51 UTC) is way before the acknowledgement shown in the history on March 23rd. So something is missing on that node for sure and it would be interesting to know what the state on the other node is.

**Comment by BT-Basit** [comment]
Hi Julian,

thanks for your reply.

First of all the service seen in my initial screenshot recovered in the meantime but I have another example with other timestamps obviously: 

In the Object Inspection view  the value for `acknowledgement `is shown as 0 again. `acknowledgement_last_change` corresponds to Sunday, 26. March 2023 07:35:19 UTC

![image](https://github.com/Icinga/icinga2/assets/120741671/26ff8140-35b4-46df-b1f9-aa2f04e8c331)

However in the history another timestamp is shown (as UTC +1): 

![image](https://github.com/Icinga/icinga2/assets/120741671/63d0472d-3266-4925-90cc-b6961be51496)

> From the Icinga 2 API ("Inspected via icinga1 [...]").

Yes, I think all the information shown in the 'Object Inspection' come from the API. But how does the API get this value? Does this come from a database table?
When I look into icinga_acknowledgements the acknowledgement_type has the value 2:

![image](https://github.com/Icinga/icinga2/assets/120741671/c3ceaf9c-f9b8-4760-a411-4a8410471402)

> please query the service attributes from both nodes

**Result from first master (icinga1)**

`
{
    "results": [
        {
            "attrs": {
                "__name": "<Host>!<Service>",
                "acknowledgement": 0,
                "acknowledgement_expiry": 0,
                "acknowledgement_last_change": 1679816119.99804,
... }
`

**Result from second master (icinga2)**

`
{
    "results": [
        {
            "attrs": {
                "__name": "<Host>!<Service>",
                "acknowledgement": 2,
                "acknowledgement_expiry": 0,
                "acknowledgement_last_change": 1679658190.412078,
`

There seems to be a difference in the acknowledgement values and the timestamps. I don't understand how this happened.

**Comment by BT-Basit** [comment]
Hi @julianbrost ,

what do you think about my comment above?
There was a difference between the masters. How can this happen?

Thanks for your help!

**Comment by BT-Basit** [comment]
Hi @julianbrost 

sorry to keep bothering but what are your thoughts on this issue?
Is this maybe a duplicate to #9652?

**Comment by julianbrost** [comment]
What would help in isolating the problem would be if you can have a look at the `acknowledgement` value reported by the API on both masters in general. Like if you go over all hosts/services that are currently acknowledged, for how many is it consistent/inconsistent? Are the values consistent shortly after acknowledging something (i.e. can we pin down if the acknowledgement never makes it to the second master or if gets lost after some time)?

**Comment by BT-Basit** [comment]
**Fix**
Apparently adding the line `accept_config = true` to `/etc/icinga2/features-enabled/api.conf` fixed this issue.
