### ISSUE TITLE
Docs: Add more references to Icinga for Windows (PowerShell Framework/Checks)

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#9765]
There are two places in the documentation that say something about how to monitor without even mentioning Icinga for Windows:

https://icinga.com/docs/icinga-2/latest/doc/05-service-monitoring/#windows-monitoring
https://icinga.com/docs/icinga-2/latest/doc/06-distributed-monitoring/#agent-setup-on-windows

These should be updated or maybe even better rewritten with Icinga for Windows in mind.

**Comment by Al2Klimov** [comment]
Sure, I also like putting all docs fixes to an upcoming version, https://github.com/Icinga/icinga2/pull/9763#issuecomment-1551395059
if(!) they're ready to merge. This one isn’t, so I'd not let it block the release.
