### ISSUE TITLE
Debian 12: icinga2-web PHP Deprecated

### ISSUE THREAD

**Issue by Troubadix** [Icinga/icinga2#9803]
Hi,

tried installing icinga2-web on Debian 12.

Webinstall starts but after entering DB credentials I can't continue.

Maybe it is not compatible with ne PHP 8.2 yet?

`Deprecated
: Creation of dynamic property Zend_Validate_NotEmpty::$zfBreakChainOnFailure is deprecated in
/usr/share/icingaweb2/library/vendor/Zend/Form/Element.php
on line
2176

Deprecated
: Creation of dynamic property Zend_Validate_NotEmpty::$zfBreakChainOnFailure is deprecated in
/usr/share/icingaweb2/library/vendor/Zend/Form/Element.php
on line
2176

Deprecated
: Creation of dynamic property Zend_Validate_NotEmpty::$zfBreakChainOnFailure is deprecated in
/usr/share/icingaweb2/library/vendor/Zend/Form/Element.php
on line
2176

Deprecated
: Creation of dynamic property Icinga\Web\Form\Validator\InArray::$zfBreakChainOnFailure is deprecated in
/usr/share/icingaweb2/library/vendor/Zend/Form/Element.php
on line
2176

Deprecated
: Creation of dynamic property Zend_Validate_NotEmpty::$zfBreakChainOnFailure is deprecated in
/usr/share/icingaweb2/library/vendor/Zend/Form/Element.php
on line
2176

Deprecated
: Creation of dynamic property Zend_Validate_NotEmpty::$zfBreakChainOnFailure is deprecated in`

**Comment by julianbrost** [comment]
> Maybe it is not compatible with ne PHP 8.2 yet?

Yes, there's already an issue for that in the corresponding project: https://github.com/Icinga/icingaweb2/issues/4918
