### ISSUE TITLE
High InfluxDB disk usage after upgrading to 2.14.0

### ISSUE THREAD

**Issue by devopstt** [Icinga/icinga2#9948]
Hi,

we are using Icinga with InfluxDB (1.8) feature in an environment with about 2000 Hosts and 30.000 service checks.
We upgraded Icinga2 from 2.13.4 to 2.14.0 two moths ago.

Environment: Icinga2 2.14.0, InfluxDB 1.8
OS: Ubuntu 20 (Icinga and also InfluxDB)

It looks like we have way more disk usage on our influxDB machines since upgrading to 2.14.0. Its the exact moment when the upgrade was installed

https://community.icinga.com/uploads/default/original/2X/4/4075a4043d29986fc22a37f79e87f84d278d223c.png
 
In the patch nodes I found the following change:
> Influxdb(2)Writer: write more precise timestamps (nanoseconds). #9599

Do you also had way more disk usage? How can I avoid it?
We have a retention policy of 730d in InfluxDB

This is my influxdb feature configuration:
```
/**
 * The InfluxdbWriter type writes check result metrics and
 * performance data to an InfluxDB HTTP API
 */

object InfluxdbWriter "influxdb" {
  enable_ha = true
  host = "xxx.xxx.xxx.xxx"
  port = 9096
  database = "xxxxxxxxxxxxxxx"
  username = "xxxxxxxxxxxxxxx"
  password = "xxxxxxxxxxxxxxx"
  ssl_enable = true
  ssl_insecure_noverify = true
  enable_send_thresholds = true
  enable_send_metadata = true
  flush_threshold = 1024
  flush_interval = 10s
  host_template = {
    measurement = "$host.check_command$"
    tags = {
      hostname = "$host.name$"
      bereitschaft = "$host.vars.bereitschaft$"
      codename = "$host.vars.codename$"
      environment = "$host.vars.environment$"
      os = "$host.vars.os$"
      platform = "$host.vars.plattform$"
    }
  }
  service_template = {
    measurement = "$service.check_command$"
    tags = {
      hostname = "$host.name$"
      service = "$service.name$"
      bereitschaft = "$host.vars.bereitschaft$"
      codename = "$host.vars.codename$"
      environment = "$host.vars.environment$"
      os = "$host.vars.os$"
      platform = "$host.vars.plattform$"
    }
  }
}
```

If it is because of the more precise timestamps in nanoseconds - can we have an option to specify it in the feature configuration?

**Comment by julianbrost** [comment]
ref/IP/49075

**Comment by Al2Klimov** [comment]
This is how Icinga used to write Influx data:

```
POST /write?db=icinga2&precision=s HTTP/1.0
User-Agent: Icinga/2.11.11-1
Host: 10.27.1.27:8086
Content-Length: 967

memory-usage,hostname=aklimov-i2all-master-2,service=memory-usage,metric=usage_percent unit="percent",value=20.200000 1705070234
memory-usage,hostname=aklimov-i2all-master-2,service=memory-usage,metric=total unit="bytes",value=1927786496 1705070234
memory-usage,hostname=aklimov-i2all-master-2,service=memory-usage,metric=used unit="bytes",value=162586624 1705070234
memory-usage,hostname=aklimov-i2all-master-2,service=memory-usage,metric=available unit="bytes",value=1539239936 1705070234
memory-usage,hostname=aklimov-i2all-master-2,service=memory-usage,metric=free unit="bytes",value=515788800 1705070234
memory-usage,hostname=aklimov-i2all-master-2,service=memory-usage,metric=shared unit="bytes",value=33984512 1705070234
memory-usage,hostname=aklimov-i2all-master-2,service=memory-usage,metric=buffers unit="bytes",value=2662400 1705070234
memory-usage,hostname=aklimov-i2all-master-2,service=memory-usage,metric=cached unit="bytes",value=1246748672 1705070234
```

In v2.14 we changed that:

* #9599

## How to reproduce

1. Get InfluxDB 1.8 up and running
2. create database filldisk214
3. create database filldisk213
4. create database filldisk212
5. Run script below
6. Await all of `du -sh /var/lib/influxdb/data/f*` to get a noticeable size
7. Compare them
    * 2.14: 32M
    * 2.13: 8.4M
    * In short, we could just revert the mentioned PR.

```
for i in {0..29}; do
for j in {0..99999}; do
printf 'filldisk,icinga=214 unit="bytes",value=%d 16%03d%05d%09d\n' $RANDOM $i $j $RANDOM
done >data.txt
curl -fsSX POST --data-binary @data.txt 'http://127.0.0.1:8086/write?db=filldisk214&precision=ns'
done

for i in {0..29}; do
for j in {0..99999}; do
printf 'filldisk,icinga=214 unit="bytes",value=%d 16%03d%05d\n' $RANDOM $I $j
done >data.txt
curl -fsSX POST --data-binary @data.txt 'http://127.0.0.1:8086/write?db=filldisk213&precision=s'
done

for i in {0..9}; do
for j in {0..99999}; do
printf 'filldisk,icinga=214 unit="bytes",value=%d 16%03d%05d\n' $RANDOM $I $j
done >data.txt
curl -fsSX POST --data-binary @data.txt 'http://127.0.0.1:8086/write?db=filldisk212&precision=s'
done
```

**Comment by carraroj** [comment]
ref/NC/804880

**Comment by sciolto** [comment]
Hi @julianbrost @Al2Klimov is this behavior confirmed?  I can confirm that most of our bigger environments are experiencing disk saturation issues because of InfluxDB. 
 Do you plan to revert this PR https://github.com/Icinga/icinga2/pull/9599 and do another release in the short run ? 
Thanks

**Comment by devopstt** [comment]
Thanks for taking care and releasing a fix!

**Comment by julianbrost** [comment]
The [InfluxDB documentation describes an optimization they make for storing timestamps](https://docs.influxdata.com/influxdb/v1/concepts/storage_engine/#timestamps), that was possible before Icinga 2.14.0 as all timestamps were multiples of 10⁹ but is no longer possible starting with 2.14.0 as #9599 added information in those last 9 decimal places:

> Many timestamps are also monotonically increasing and fall on even boundaries of time such as every 10s. When timestamps have this structure, they are scaled by the largest common divisor that is also a factor of 10. This has the effect of converting very large integer deltas into smaller ones that compress even better.

Note: I didn't find the corresponding place in the documentation for v2, there they just link a video to explain the TSM format, but I guess they haven't made the timestamp encoding worse in v2.
