### ISSUE TITLE
Cannot install icinga2 at Fedora39

### ISSUE THREAD

**Issue by JanGardian** [Icinga/icinga2#9961]
## Describe the bug

Followed documentation https://icinga.com/docs/icinga-2/latest/doc/02-installation/04-Fedora/ and in 1 step with command `rpm --import https://packages.icinga.com/icinga.key` got output:
```
warning: Certificate C6E319C334410682:
  Policy rejects subkey 146117B313F2C675: Policy rejected asymmetric algorithm
```

After that I added icinga2 repo but cannot install icinga2 or found it at all. I suspect that if added repository is not signed it will not be used.

Looks like it is related to upgraded security policy in Fedora 38 https://discussion.fedoraproject.org/t/popular-third-party-rpms-fail-to-install-update-remove-due-to-security-policies-verification/70498.

Can you check and if possible use different key for Fedora repository?

Thank you

## To Reproduce

1. Install Fedora39
2. Follow https://icinga.com/docs/icinga-2/latest/doc/02-installation/04-Fedora/

## Expected behavior

To be able to install icinga2 at Fedora39

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): cannot install icinga2
* Operating System and version: Fedora 39
* Enabled features (`icinga2 feature list`): cannot install icinga2
* Icinga Web 2 version and modules (System - About): cannot install icinga2
* Config validation (`icinga2 daemon -C`): cannot install icinga2

**Comment by JanGardian** [comment]
I found that issue was not with unsuported algorithm for repository key but as per issue https://github.com/Icinga/icinga-packaging/issues/296 it was missing packages in repository structure for Fedora 39. On 24.1 they added missing packages and yesterday I tested official instruction for icinga2 installation at Fedora39 and successfully installed icinga2 with all needed dependencies.

**Comment by herbozo2003** [comment]
thanks everyone!!!
